### ISSUE TITLE
Videos / iFrame not displaying in results template (default and custom)

### ISSUE THREAD

**Issue by colonelclaypoo** [microsoft-search/pnp-modern-search#1000]
**Version used**
4.1.0

I am displaying data from a SharePoint list in a Search Results webpart. We know that SharePoint lists can contain HTML / iframe data in their cells to show embedded Videos. I am retrieving such a cell and everything shows search results but the video (from Stream). Other items display linked screenshots for example but not videos. Am I doing something wrong or is this a potential bug?

I tried the provided Details List as well as the List layout. The slot for _{{getSummary (slot item @root.slots.Summary)}}_ uses the property BodyOWSMTXT which contains the HTML markup including the iframe.

Here's the markup as it's returned from the SharePoint Online source list:

`<div class="ExternalClass34B2368B3D81440AA76C4922B09EC3DF"><p><strong></strong><strong>[SANITIZED]<br></p><p><br></p><div class="ms-rtestate-read ms-rte-embedcode ms-rtestate-notify ms-rte-embedil"><iframe src="https&#58;//web.microsoftstream.com/embed/video/25c93fa0-704f-40e7-b838-c2f6204277fd?autoplay=false&amp;showinfo=true" allowfullscreen="" width="640" height="360" style="border&#58;medium none;"></iframe>&#160;</div><p><br></p><p><br></p></div>`

That does diplay the text ([SANITIZED]) but not the video. Then I tried to directly embed the iframe `<iframe src="https://web.microsoftstream.com/embed/video/25c91fa0-704f-40e7-7838-c2f6204277fd?autoplay=false&amp;showinfo=true" allowfullscreen="" width="640" height="360" style="border: medium none;"></iframe>`
into the results template but it didn't change anything.

Can anyone repro?

Thanks

**Comment by colonelclaypoo** [comment]
Okay, so it seems iframe is still the issue? That's unfortunate that SharePoint won't let you display videos from Stream without the Embed or Stream webpart.

**Comment by wobba** [comment]
If you go to site settings and HTML Field Security, then enter the stream domain - does it work?

**Comment by colonelclaypoo** [comment]
Thanks for your reply. The video url is _https://web.microsoftstream.com/embed/video/25c93fa0-704f-40e7-b838-c2f6204277fd_. So I put _web.microsoftstream.com_ as well as _stream.microsoft.com_ into the HTML field security whitelist. Unfortunately, it didn't change.

Thus far I've been using `{{getSummary (slot item @root.slots.Summary)}}` in the template to which I mapped the property _BodyOWSMTXT_ which contains the list items body. Since this does not show the iFrame I tried to directly put the iFrame markup `<iframe src="https://web.microsoftstream.com/embed/video/2s5c93fa0-d704f-40e7-bdd838-c2f6204277fd?autoplay=false&amp;showinfo=true" allowfullscreen="" width="640" height="360" style="border:medium none;"></iframe>&nbsp;` into the template where replacing the previous summary slot markup. Also no change.

A Youtube video also does not work.
Do you need more/other details?

Thanks.

**Comment by wobba** [comment]
We won't render html from say BodyOWSMTXT or in the template without sanitizing it as it can cause security issues. Allowing arbitrary iframe src can introduce for example click jacking. I'll see if we could have stream domains as an exception, or read the list of allowed domains from site settings.

**Comment by colonelclaypoo** [comment]
Thank you, I understand and this is much appreciated.

**Comment by PFudala** [comment]
Hi ! Any update on this behavior ?

**Comment by wobba** [comment]
Question is how we should improve to allow iframes for this specific case, as it's a security risk. @PFudala can you explain your scenario?

**Comment by PFudala** [comment]
Hi @wobba ,

We'd like to use a customization of the slider template, which query pages in a SharePoint site and display them as it was designed by the contributor. To do this, we hoped to use the "Path" slot and customize template in order to display results via iframe in "template--slide" div.
Contents source is in the same tenant.

**Comment by wobba** [comment]
There's no way we can easily use the current template which show a preview and inject html from BodyOWSMTXT into it. And investing a lot into contents from classic pages or advanced rich text in a list is likely not something we will do for these web parts. Your best option is to create a custom web component and use that in the template to handle your scenario. I suggest you rather store a stream URL as a url or string, and not as part of rich text.
