### ISSUE TITLE
User from different domains(But still under the same company) can't get the search bar or verticals to show correctly. 

### ISSUE THREAD

**Issue by walterciz** [microsoft-search/pnp-modern-search#1002]
**Version used**
 4.1.0

**Describe the bug**
 I am part of a large company that has multiple domains under its umbrella and some of the users in certain domains can't access/view the search bar/verticals. We have tested with different users with different domains. 

**To Reproduce**
1. Go to main page where the Search box is located
4. See error " 
**Something went wrong**
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS (There are none)

**Expected behavior**
The user should see the search box and results. 

**Screenshots**
 **Error: With user that can't see the search box**

<img width="1336" alt="Screen Shot 2021-05-16 at 11 49 42 AM" src="https://user-images.githubusercontent.com/68163790/118408992-22522080-b63d-11eb-90c9-dccfc695ef0c.png">

**Correct look:** 
<img width="1336" alt="Screen Shot 2021-05-16 at 11 52 40 AM" src="https://user-images.githubusercontent.com/68163790/118409024-4d3c7480-b63d-11eb-81d1-d183d248affc.png">

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
This is a large company with 167 domains.

**Comment by wobba** [comment]
Check this post https://laurakokkarinen.com/sharepoint-online-guest-user-troubles-and-how-to-get-past-them/#custom-share-point-apps-dont-load-for-guest-users-by-default

Likely guest user and SPFx issue, not these web parts in particular.

**Comment by wobba** [comment]
This issue will shortly be closed due to inactivity.
