### ISSUE TITLE
Date refiner: Error making HttpClient request in queryable [500] 

### ISSUE THREAD

**Issue by ileana2019** [microsoft-search/pnp-modern-search#1006]
Hello,
Inside a document library, we are having a Due Date column (see settings attached). We edited the RefinableString115 to map the crawl property "ows_[Internal Column Name]". The type of information in the RefinableString is Text (cannot select other type, it is grayed out). Inside the Search Filters webpart, we added the refiner using the Date range refiner template (see attachment). When filtering on the date range From and To, the following error appears in the Search results:

Error making HttpClient request in queryable [500] ::> {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}

Could you please help?
![DueDateColumn](https://user-images.githubusercontent.com/55545989/118626208-f5337880-b7ca-11eb-8388-073c5387ff70.PNG)
![error](https://user-images.githubusercontent.com/55545989/118626210-f5cc0f00-b7ca-11eb-8df5-e05c5e1e210f.PNG)
![Refiner](https://user-images.githubusercontent.com/55545989/118626211-f664a580-b7ca-11eb-83a0-1d397220ddff.PNG)

Thank you!

**Version used**
3.19.0.0

**Comment by wobba** [comment]
You should map date values to any of the reusable `RefinableDate` or `Date` properties. https://docs.microsoft.com/en-us/sharepoint/manage-search-schema#default-unused-managed-properties
