### ISSUE TITLE
How to download searched results documents from pnp Search Result?

### ISSUE THREAD

**Issue by mayabank** [microsoft-search/pnp-modern-search#1007]
Hello,

I have a requirement to be able to pick and choose (selected or all) documents that are searched resulted in pnp search result.

Any help would be much appreciated.

PnP version - 3.19

Thanks and regards,
Mayank

**Comment by wobba** [comment]
You need to create custom component for this. See https://microsoft-search.github.io/pnp-modern-search/v3/search-extensibility-library/getting-started/
