### ISSUE TITLE
Persona refiner not displaying values when large list of values

### ISSUE THREAD

**Issue by joelfmrodrigues** [microsoft-search/pnp-modern-search#1008]
**Version used**
Ex: 3.19.2

**Describe the bug**
Persona refiner not displaying refiner values when the list of values is very large.

I have debugged this and the issue happens within the `getUserInfos` method of the UserService when the component tries to batch query all users to get their account name and display name. The batch query never gets resolved when the number of batch request is very large, but works when the number is reduced.

As the getUserInfos service method only retrieves the account and display name, I believe this is not required as we have that information in the refinement value string already. There are already different places within the same control where the display name is being extracted from the refinement value string.

I will submit a PR with this approach as I have tested it and seems to be working as expected.

**To Reproduce**
1. Setup a refiner based on a people field
2. Ensure the query returns a very large number of refiner values for that people refiner (500+)
3. Persona refiner stuck on loading 

**Expected behavior**
Display refiner values

**Screenshots**
![image](https://user-images.githubusercontent.com/19577724/118735865-36627180-b839-11eb-95fc-e2a557e6e5ce.png)

**Desktop (please complete the following information):**
 - Browser [Edge (modern)]

**Additional context**

**Comment by joelfmrodrigues** [comment]
Just updating the issue based on comments from the PR: requesting display name may be required for some users where display name is not present in the refiner value.

**Comment by FranckyC** [comment]
Resolved by #1012. Thanks @joelfmrodrigues !
