### ISSUE TITLE
Cannot add new result type row

### ISSUE THREAD

**Issue by FrankMuraschow** [microsoft-search/pnp-modern-search#1010]
**Version used**
4.1.0

**Describe the bug**
I cannot add any custom result types to the search result webpart. The "+" button stays greyed out although I entered all necessary data. I compared my findings with the v3.19.2 - here it works without a problem and as expected.

**To Reproduce**
1. Add a search results webpart to any page
2. Edit the properties
3. Go to settings page 2 of 4 
4. Choose list as layout
5. Click "Edit result types"
6. Enter value: FileType equals pdf
7. Error: You cannot click the "+" icon

**Expected behavior**
I expect to be able to add a new result type row

**Screenshots**
![image](https://user-images.githubusercontent.com/5666768/118783773-adc2f000-b88f-11eb-87f7-fb2ce1c3e229.png)

**Desktop (please complete the following information):**
 - Browser Edge v90.0.818.62

**Comment by FranckyC** [comment]
Hi @FrankMuraschow , this issue is already fixed in the develop branch and will be available in the next release. See https://github.com/microsoft-search/pnp-modern-search/issues/887
