### ISSUE TITLE
Hide this web part if there's nothing to show > still takes up whitespace

### ISSUE THREAD

**Issue by h-h-o** [microsoft-search/pnp-modern-search#1011]
**Version used**
4.1.0.0

**Describe the bug**
When using the 'Hide this web part if there's nothing to show' option in the 'PnP - Search Results' web part, the web part still takes up some (vertical) whitespace when no results are found. The web part below it displays lower than it should. I tried with different layouts (including custom) but the result is always the same.
This is not the case with the OOB SPO web parts. 

**To Reproduce**
1. On a Communication Site, add an OOB SPO web part that shows some data (e.g. the News web part in Tiles mode)
2. Directly above the News web part, add the 'PnP - Search Results' and select the 'Hide this web part if there's nothing to show' option
3. Make sure there are no results in the PnP web part, to trigger the behavior
4. Save and Publish the page
5. Notice that the hidden PnP web part still takes up some whitespace, and the News web part starts lower than it should.

**Expected behavior**
The hidden PnP webpart does not take up any space. The News web part is in the exact same location as if the PnP web part was not there

**Screenshots**
NA

**Desktop (please complete the following information):**
 - Browser: New Edge and Firefox (up-to-date)

**Additional context**
NA

**Comment by wobba** [comment]
Any web part will take up some space on a page as part of how SPFx works. We could DOM hack this, but that's not a good approach and as such I'm closing this as expected behavior.
