### ISSUE TITLE
Download item from search results

### ISSUE THREAD

**Issue by fijaz** [microsoft-search/pnp-modern-search#1017]
**Is your feature request related to a problem? Please describe.**
There is no option to download a file from Search results

**Describe the solution you'd like**
I want to see a document download option from Search results page

**Describe alternatives you've considered**
SharePoint has this feature, in document library. When we search in a document library, we can download from that page

**Additional context**
![ej07yYDnqu](https://user-images.githubusercontent.com/7151140/119214836-c998e280-ba97-11eb-9af4-0ec19428a459.png)

**Comment by hervedorierai3** [comment]
Hello, 
you can easely add this kind of code to your custom template :  onclick="window.location.assign('{{slot item @root.slots.SPSiteUrl}}/_layouts/15/download.aspx?UniqueId={{slot item @root.slots.ItemId}}')".

The slot mapping : 
- SPSiteUrl = SPSiteUrl
- ItemId = NormUniqueID

Best regards.

**Comment by wobba** [comment]
@fijaz are you ok with the help @hervedorierai3 provided?

**Comment by fijaz** [comment]
Yes, Thanks for followup. I am ok with feedback provided by @hervedorierai3.
