### ISSUE TITLE
Persona card not showing on hover: The mailbox is either inactive, soft-deleted, or is hosted on-premise

### ISSUE THREAD

**Issue by rcelesti** [microsoft-search/pnp-modern-search#1022]
**Version used**
4.0.0

**Describe the bug**
The persona card do not show on hover while browsing people results (not guests) on the PnP Search Results Web Part. People layout is selected, "Show persona card on hover" and "Use Micrsoft Graph Toolkit" have been turned on and API permissions have been set. 

In the network tab of developer toolbar I get "The mailbox is either inactive, soft-deleted, or is hosted on-premise" (it's true, mailbox are stil on Exchnage on prem).

**To Reproduce**
1. Add Search Results Web Part
2. Set LocalPeopleResults as Result Source ID;
3. Add * to query template;
4. Select People in available layouts;
5. Mouse over a user picture
6. See error

**Expected behavior**
Person card show up on mouse over

**Screenshots**
-

**Desktop (please complete the following information):**
 - All (tested on Chrome)
 
**Additional context**
-

**Comment by wobba** [comment]
I think that error says it all. The profile you are looking at does most likely not have a representation in the Graph. And we don't control how the toolkit components work.

**Comment by rcelesti** [comment]
Thank you Mikael. Not sure this is the right place to ask, but is there a way I can check it or reproduce the error in graph explorer?

**Comment by wobba** [comment]
Monitor the network calls to graph.microsoft.com and you see the query it is trying, and you can do the same in graph explorer.

**Comment by rcelesti** [comment]
Thank you Mikael, I found it.
