### ISSUE TITLE
Collapsible content not respecting data-is-default-collapsed value

### ISSUE THREAD

**Issue by raymond-tishenko** [microsoft-search/pnp-modern-search#1027]
**Version used**
4.1.0.0

**Describe the bug**
When using the <pnp-collapsible> web component in a custom template the content displays expanded by default, ignoring the 'data-is-default-collapsed' value.

**To Reproduce**
1. Add Search Results web part
2. Set layout to 'Custom'
3. Edit results template, add &lt;pnp-collapsible&gt; web component within resultTypes (even using [example snippet](https://microsoft-search.github.io/pnp-modern-search/extensibility/web_components_list/#ltpnp-collapsiblegt))
4. Set data-is-default-collapsed="true"
5. Collapsed section is expanded by default

**Expected behavior**
Expect the collapsible section to render 'collapsed' by default on page/results load.

**Desktop (please complete the following information):**
 - Chrome
 - Edge
 - Firefox

**Additional context**
Collapsible section does 'expand' or 'collapse' when clicked, just doesn't load using default specified.

**Comment by wobba** [comment]
Try to use `data-default-collapsed` and I will update the docs.

**Comment by raymond-tishenko** [comment]
Thanks @wobba, that's got it!
