### ISSUE TITLE
Ability to specify which verticals specific sort options are shown on

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#1029]
**Is your feature request related to a problem? Please describe.**
Without breaking search into a page per vertical, I would like to be able to specify unique Sort options for each search vertical. Currently Sort is shared across all verticals, but not all configured sort types apply to each vertical. The extra fields are confusing users. For example, we have a Sort for "Number of Issues", this is only applicable to a single vertical, but shows up on all.

**Describe the solution you'd like**
Add a multi-select field in the Sort configuration that allows admin to specify which vertical the sort value should appear on. 

**Describe alternatives you've considered**
Breaking our search page into separate pages to support unique filters and sort. This adds other complications, such as vertical counts no longer working (shows 0 for verticals you are not actively on) and duplication of work to maintain pages. 

**Additional context**

**Comment by wobba** [comment]
Possible with v4 setup as it has a result web parts per vertical.
