### ISSUE TITLE
Add custom fields to Search Result and Search Refiner webparts.

### ISSUE THREAD

**Issue by mcpang** [microsoft-search/pnp-modern-search#103]
Hi there,
I have added three webparts onto my page in purpose of searching and refining a document library in the site. I got them configured almost the way I want except a few issue I run into which I wonder if it can be done.

In the document library I have a few custom column i.e. Owner, Category etc.

**Describe the solution you'd like**
I am wondering if there's a way to add those custom columns to display in the Search Result web part and also add to the Refiner web part so users can filter on them.  I am using the Details list as the Results Layout in the Search Result webpart. 

![Capture](https://user-images.githubusercontent.com/24362727/74857065-62263d00-5300-11ea-8042-b3216c1f4c55.PNG)

**Comment by wobba** [comment]
Hi, you need to look into crawled and managed properties in the search schema. https://docs.microsoft.com/en-us/sharepoint/search/manage-the-search-schema is a good start and is applicable to SPO as well. Basically each column gets a crawled property named ows_columnname, which you can map to eg. RefinableString01 which you can use in the webpart.

**Comment by FranckyC** [comment]
Hi @mcpang Actually you can add your custom columns to the Details List layout and define the corresponding managed properties as values (lie `RefinableStringXX`). To do, enter them as free text value in the **selected properties** of the Web Part and press enter. Then the value will become available in the property list in the Details List layout configuration.

![image](https://user-images.githubusercontent.com/5659122/74860225-488ff000-5316-11ea-8902-18669f36ce6c.png)

![image](https://user-images.githubusercontent.com/5659122/74859949-e636ef80-5315-11ea-8ed1-5167cf9f169e.png)

Then you could alphabetically filter on them individually afterwards. Notice the sort doesn't work when using an Handlebars expression.

**Comment by mcpang** [comment]
> Hi, you need to look into crawled and managed properties in the search schema. https://docs.microsoft.com/en-us/sharepoint/search/manage-the-search-schema is a good start and is applicable to SPO as well. Basically each column gets a crawled property named ows_columnname, which you can map to eg. RefinableString01 which you can use in the webpart.
> 
> I cover these concepts a bit as well in https://www.amazon.com/Troubleshooting-Search-SharePoint-Online-solving/dp/1080506411

**Comment by mcpang** [comment]
@FranckyC Thank you for promptly response. However, I have tried the same but not quite getting the result. Below are steps I took:
1. In my custom document library I have created a simple single text colunm named '**iCategory**' and filled with random values.
2. I went to Site collection settings > Search Schema  > New Managed Property
3. I named the new managed property yycCategory and mapped to the ows_iCategory as in screenshot below.
![image](https://user-images.githubusercontent.com/24362727/74936042-a5d38200-53a6-11ea-8748-7715a900b3b2.png)
4. Then in the Selected Properties of the Search Results webpart, I entered 'yycCategory' and hit enter as you said.
![image](https://user-images.githubusercontent.com/24362727/74936264-124e8100-53a7-11ea-9c7b-f7ad2990929a.png)

5. Then in the Managed column, yes, I did see the column yycCategory available for me to pick. So, I picked and saved the settings.
![image](https://user-images.githubusercontent.com/24362727/74936431-59d50d00-53a7-11ea-9d53-a9b49dcbd4b0.png)

However, I don't see the value of the column displayed in the Search Results. They are blank.
Not sure if there's anything I have missed.
![image](https://user-images.githubusercontent.com/24362727/74936858-234bc200-53a8-11ea-9d89-d835d2aacc79.png)

**Comment by FranckyC** [comment]
@mcpang You can try:
- To use a `RefinableString` managed property instead on a custom one
- Reindex your library and wait a couple of minutes

**Comment by FranckyC** [comment]
Also I see you managed property is not set as 'Retrievable'. This could be explain why you can see the value.

**Comment by mcpang** [comment]
@FranckyC Yes, it was because the Retrievable option was not set. After setting the option, the value shows up in the web part now. 

![image](https://user-images.githubusercontent.com/24362727/74938990-4f694200-53ac-11ea-8d8e-2195cb927a82.png)

**Comment by mcpang** [comment]
@FranckyC and @wobba, thank you so much for help.
