### ISSUE TITLE
How to remember SearchTerm when I use different vertical

### ISSUE THREAD

**Issue by MirasManica** [microsoft-search/pnp-modern-search#1030]
Hi,

It is question but not issue. I did not find the answer within other issues. I am sorry for my low knowledge.

I have case that I am using different verticals as a links. Each verticals has own page with results. When I search some key word and I would like to go to another vertical, I am correctly redirected but without key words. I have to fulfill them again. Could you help me how to set it up correct? And previous vertical is still underlined although I am on the new one.

![image](https://user-images.githubusercontent.com/54021786/120053500-cf0fa300-c02a-11eb-86cb-6b3bb7ac10f6.png)
![image](https://user-images.githubusercontent.com/54021786/120053589-3e859280-c02b-11eb-9596-cd90c280519e.png)

Thank you for your advice. I hope this is the right channel where to ask these topics.

Mirek

**Comment by wobba** [comment]
You need to configure search term to be picked from query parameter using tokens. See the token section for https://microsoft-search.github.io/pnp-modern-search/usage/search-verticals/#configure verticals as I assume you are using v4 since no specific version is mentioned.

**Comment by MirasManica** [comment]
Thank you for your fast response. I confirm that it works. You are right, I am using v4, I guess it is more cool because of verticals on one page. Does exist a way how to create a link directly to concrete "vertical"? Something special in URL? I have vertical as you see below on screen. I have tried to use parameters "v=", "vertical=" or "verticals" and does not work. Maybe it works only in v3? Do you have information about release date of v4?

![image](https://user-images.githubusercontent.com/54021786/120163175-84905100-c1f9-11eb-80b4-450981c253e9.png)

**Comment by wobba** [comment]
v4 does not yet support landing on a specific vertical via the URL.

**Comment by MirasManica** [comment]
Thank you for your help and answers :)
