### ISSUE TITLE
Handlebars #times - potential collision

### ISSUE THREAD

**Issue by salascz** [microsoft-search/pnp-modern-search#1031]
**Version used**
3.19.2

**Describe the bug**
The search results might not be rendered correctly when using `times` handlebar helper.
There is a collision between `times` helper registered in `BaseTemplateService.tsx` and `times` helper registered in the package `handlebars-helpers: 0.10.0`.

Sample of non-working code (actually it can be simulated on default shimmer snipped):
```
            <div class="document-card-container"> 
                {{#times @root.paging.totalItemsCount}}
                    <div class="document-card-item">
                        <pnp-document-card-shimmers data-is-compact="{{@root.isCompact}}"></pnp-document-card-shimmers>
                    </div>
                {{/times}}
            </div>
```

**To Reproduce**
1. Use the #times helper in your Results template
2. Save the webpart configuration and refresh the page
3. See error "TypeError: expected the second argument to be a number"

**Expected behavior**
The #times helper should work as defined in the pnp-modern-search solution.

**Screenshots**
![image](https://user-images.githubusercontent.com/5662939/120185642-c5489400-c212-11eb-8d9f-f4ec8b91ff58.png)

**Additional context**
Our solution was recently updated from 3.14.2 - it worked without an issue (pnp-modern-search used an older version of handlebars-helpers library)

**Comment by wobba** [comment]
Thank you for this and have to find the best way to handle this. Ideally we would rename the web part one, but I see that has issues.

**Comment by wobba** [comment]
"times" is an alias for "multiply". I re-arranged the code so that "times" works as expected in the next release.

**Comment by salascz** [comment]
Great, thanks for such a quick reaction.
