### ISSUE TITLE
package.json with @ in devDependencies

### ISSUE THREAD

**Issue by Reo1980** [microsoft-search/pnp-modern-search#1032]
https://github.com/microsoft-search/pnp-modern-search/blob/bc2600599eb164146d1b72d6b7483f2370f5ccad/search-parts/package.json#L79
https://github.com/microsoft-search/pnp-modern-search/blob/bc2600599eb164146d1b72d6b7483f2370f5ccad/search-parts/package.json#L80

Are those "@" in the version numbers correct?

Getting the following error while setting up a fresh dev environment on "npm i"

> Error: Invalid tag name "@16.9.36": Tags may not have any characters that encodeURIComponent encodes.

Trying npm in version 6.14.6, 7.13.0 and 7.15.0

Removing the "@" fixes this problem.

**Comment by wobba** [comment]
They are wrong :)
