### ISSUE TITLE
"Hide this web part if there's nothing to show" flapping

### ISSUE THREAD

**Issue by tknaller** [microsoft-search/pnp-modern-search#1033]
**Version used**
4.1.0.0

**Describe the bug**
When using the Search Results Web Part's Feature "Hide this web part if there's nothing to show" the result is flapping shortly when the page is newly loaded.

**To Reproduce**
1. Add Search Bar Webpart
2. Add Search Results Wbpart and enable "Hide this web part if there's nothing to show" 
3. Connect those Webparts
4. Add content below Search Results
5. Publish Page
6. Reload Page 
7. Search Results Shimmered List is shortly visible, thus flapping the layout

**Expected behavior**
No Flapping.

**Comment by wobba** [comment]
This is to be expected as we show a loading shimmer. If you don't want the loading shimmer remove the contents within the `<content id="placeholder-content">` part of the template.
