### ISSUE TITLE
Inconsistent results with 'OR' vs. 'or'

### ISSUE THREAD

**Issue by sympmarc** [microsoft-search/pnp-modern-search#1034]
**Version used**
Ex: 4.1.0

**Describe the bug**
When I use a compound search like `125 or johnson` vs. `125 OR johnson`, I get different results from the PnP Modern Search Web Parts. If I try those two variations in the Microsoft Search box at the top of the page, I get the same results.

'or' seems to be considered a word in the query - not a reserved word - whereas 'OR' is recognized correctly.

NOTE: I do NOT see the inconsistency with 'and' vs 'AND'.

**To Reproduce**
Add a Search Box and a Search Results Web Part to a page. Search for something with a compound search including 'or' and then try 'OR'. Issue the same queries in the Microsoft Search box above and compare the results.

Obviously, your queries will need to make sense based on your underlying content.

**Expected behavior**
I expect to get the same results, regardless the capitalization of the word 'or'.

**Desktop (please complete the following information):**
 - Edge

**Comment by wobba** [comment]
This is not inconsistent and relates to KQL, not these web parts :) Operators should always be uppercase.

**125 or johnson** -> 125 **AND** or **AND** johnson
**125 and johnson** -> 125 **AND** and **AND** johnson
**125 OR johnson** -> 125 **OR** johnson

if you can rule out that the example using `and` does not have that term included, then file a bug 😉

**Comment by sympmarc** [comment]
Interesting. I do think I found a bug, though a different one.

If I type `125 or johnson` in the search bar and hit enter, I get  1 result. If I then edit the seach string to be `125 OR johnson` and hit enter, I still have one result.

But if I go back to the page and type `125 OR johnson`, I get 72 results.

So the search box doesn't recognize my switch from poor typing (lower case) to good typing (upper case). Because of that, I thought my results with OOB search weren't the same as with the MSWP.

Is this something I should report somewhere else?

**Comment by wobba** [comment]
Number of results on a page is an estimation based on returned data, as getting the exact number is not efficient for the back-end. But I would expect the actual number to be the same each time you query and page thru. 1 vs 72 results is weird indeed.

Would be great if you can capture a difference in the search request when this happens. If the request is the same, but response is different, then that is a bug to be reported.

**Comment by sympmarc** [comment]
My guess is the search box is deciding my edit from `or` to `OR` isn't actually a change. It doesn't look like it even issues the second query. If I change it from `125 OR johnson` to `125 OR  johnson` (extra space), then the query is issued and I get the 72 results.

So the fault may lie in the search box itself not recognizing the change. Should be easy for you to reproduce.

**Comment by sympmarc** [comment]
@wobba Sorry - I don't think I was clear above. My testing for case was with the Microsoft Search box at the top of the SharePoint page. 

The MSWP Search Box actually handles the case switching correctly.

**Comment by wobba** [comment]
Got it.. I'll log it internally :)
