### ISSUE TITLE
Search Filters - Case sensitive

### ISSUE THREAD

**Issue by nemegeerm** [microsoft-search/pnp-modern-search#1035]
**Version used**
4.1.0.0

**Describe the bug**
The value you type in a search filter field with template combo box seems to be case sensitive. In my list I have J317. If I start typing j it shows no result and an empty list

**Expected behavior**
Case insensitive ?

**Screenshots**
None

**Desktop (please complete the following information):**
Chrome

**Additional context**
None

**Comment by wobba** [comment]
Makes sense to look at this. Also remember that returned filter values are case sensitive, but we should be able to match on both.

**Comment by wobba** [comment]
Will be part of the next release.
