### ISSUE TITLE
pnp-collapsible

### ISSUE THREAD

**Issue by celinefolliet** [microsoft-search/pnp-modern-search#1037]
Hi,

Trying to use pnp-collapsible in search result web part / manage columns
https://microsoft-search.github.io/pnp-modern-search/extensibility/web_components_list/#ltpnp-collapsiblegt

```
the default code bellow doesn't work, it doesn't collapse.
<pnp-collapsible 
    data-group-name="Collapsible content" 
    data-is-default-collapsed="true">

    <template id="collapsible-content">
        <div>
            My Content!
        </div>
    </template>

    <template id="collapsible-footer">
        <div>
            My Footer!
        </div>
    </template>

</pnp-collapsible>
```
**You have to change data-is-default-collapsed="true" by data-default-collapsed="true" to collapse by default.**

**Comment by wobba** [comment]
Already changed
