### ISSUE TITLE
French version is broken

### ISSUE THREAD

**Issue by stevebeauge** [microsoft-search/pnp-modern-search#1039]
**Version used**
Ex: 4.2.0

**Describe the bug**

https://github.com/microsoft-search/pnp-modern-search/blob/8f17d99f495e51d3ef2317e4f2ee20651a1255b8/search-parts/src/loc/fr-fr.js#L1

There's a invasive smiley at the begin of the file...

https://github.com/microsoft-search/pnp-modern-search/blob/8f17d99f495e51d3ef2317e4f2ee20651a1255b8/search-parts/src/loc/fr-fr.js#L109

Also a quote escape issue.

This brokes the french version with an obscure HTTPS certificate issue :

````
[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/mytenant.sharepoint.com/sites/appcatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/CommonStrings_fr-fr_973b91079d5c136780e40991b17f5b7d.js' for resource 'CommonStrings' in component '544c1372-7e5a-49ec-8db6-812f76c375f2' (pnpSearchBoxWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

````

**To Reproduce**
* Deploy the latest V 4.2.0 version
* try to navigate to a page with the search components, using a french user.

**Comment by wobba** [comment]
Thank you 🙂 4.2.1 released
