### ISSUE TITLE
Refiner - Error Message "Something went wrong"

### ISSUE THREAD

**Issue by AlanSharePoint** [microsoft-search/pnp-modern-search#104]
**Version used**
3.7.0.0

**Describe the bug**
"Something went wrong" above Search Refiners web part

**To Reproduce**

Hi Team,
I'm using the search web parts on multiple pages of my site. Specifically the search box, refiners, results, and pagination. 

1. When I first load a search page, everything works well.
2. I search for something in the first page
3. I complete my task on the first page, and navigate to another search page (containing a different query) to perform another task. 
4. Once I navigate to the next search page, I see "Something went wrong" above the Search Refiners web part. (Arrow below is showing me clicking on a link to a different search page, and error occurring)
![Move from one page to another error](https://user-images.githubusercontent.com/61286929/74958820-84d75500-53d7-11ea-9388-d54ba412deb1.png)
5. If I refresh that page, the error goes away. 

**Expected behavior**
"Something went wrong" should not be displayed

**Screenshots**
Screenshot of error message:
![Error message](https://user-images.githubusercontent.com/61286929/74959373-6887e800-53d8-11ea-8d3b-53c6fd20cceb.png)

Error in developer mode:
![Error in developer mode](https://user-images.githubusercontent.com/61286929/74959346-5f971680-53d8-11ea-86b8-509272732e85.png)

Section of code error appears to be occurring:
![Section of code](https://user-images.githubusercontent.com/61286929/74959440-83f2f300-53d8-11ea-97b2-7c1a51be9bb6.png)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Additional context**
If you require any additional information, please let me know.

**Comment by wobba** [comment]
Can you reproduce using the latest version v3.9.0 ?

**Comment by AlanSharePoint** [comment]
Hi Wobba,
Thanks for the response. We updated to v3.9.0, and this no longer occurs. However, we have encountered a different bug. I will open a new issue request. 

Thank you for your help!
