### ISSUE TITLE
Create collapsible text

### ISSUE THREAD

**Issue by surfingknowledge** [microsoft-search/pnp-modern-search#1040]
**Describe the solution you'd like**
 @FranckyC @wobba @s-KaiNet 

Please I need help, I'm not super Dev so...your assistance would be appreciated. thanks, 
We've DocDescription metadata/column in SP doc library. And we want the description text/section to be collabislbale, It's too big and taking too much space.  So, What code should I inject and where?  

Aside note: Thank you all for a great job...My client is super happy with the result and simple UI to navigate. The best search tool has been created in SP history... much appreciated 

3 Pics below, The last 2 pics are desired UI where DocDesciption is collapsed, And the 1st pic is existing and bulky   

<img width="347" alt="ExistingUI" src="https://user-images.githubusercontent.com/43178227/120667520-95400180-c45b-11eb-92cc-414e0aa0e016.PNG">
<img width="325" alt="DesiredA" src="https://user-images.githubusercontent.com/43178227/120667541-9a04b580-c45b-11eb-980c-68d03da34d51.PNG">
<img width="624" alt="DesiredB" src="https://user-images.githubusercontent.com/43178227/120667551-9cffa600-c45b-11eb-84cc-31ef8e29a779.PNG">

**Comment by wobba** [comment]
See https://microsoft-search.github.io/pnp-modern-search/extensibility/web_components_list/#pnp-collapsible
