### ISSUE TITLE
{Today-X} Not working

### ISSUE THREAD

**Issue by mdressel** [microsoft-search/pnp-modern-search#1041]
**Version used**
4.1.0.0

**Describe the bug**
When I add a Query Template that includes `{Today-7}` the resulting `queryModification` has this token replaced with an empty string. `{Today}` and `{Today+7}` work as expected.

**To Reproduce**
1. Go to 'Query template' property of a Query Results web part
2. Put the following text in `{searchTerms} fiveDaysAgo={Today-5} now={Today} fiveDaysInTheFuture={Today+5}`
3. Go to 'Available layouts' and select Debug
4. Look at the `queryModification` property and you will see something like `fiveDaysAgo= now=2021-06-03T19:39:02Z fiveDaysInTheFuture=2021-06-08`

**Expected behavior**
At a minimum I would expect that the fiveDaysAgo field to have todays date minus 7 days.

In addition I feel like Today should not include the current time.

**Screenshots**
![image](https://user-images.githubusercontent.com/30449770/120725371-cc3a0580-c4a3-11eb-818c-63f51aff6044.png)
![image](https://user-images.githubusercontent.com/30449770/120725386-d52ad700-c4a3-11eb-87a4-b89e559124a7.png)

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**

**Comment by wobba** [comment]
I get this output `"queryModification": "fiveDaysAgo=2021-05-30 now=2021-06-04T10:13:37Z fiveDaysInTheFuture=2021-06-09"`

The web part itself replace '{Today}' and the ones with date modifiers are passed on to the system. Look at the QueryTemplate passed on the search request.

`QueryTemplate: "{searchTerms} fiveDaysAgo={Today-5} now=2021-06-04T10:15:06Z fiveDaysInTheFuture={Today+5}"`

That said, the webpart should replace the +- case as well, not passing them down to ensure they work for graph connections as well.

**Comment by mdressel** [comment]
@wobba So it looks like this is an issue in the 4.1 version. I just noticed there was an update to V4.2.2 and upgraded. That made this work.

Do you want me to leave this open as it is more appropriate for the QueryTemplate is also updated with the proper date?

**Comment by wobba** [comment]
I'd like to leave it open as we should improve on the code as {Today} should be handled in the webpart, not as a query variable.
