### ISSUE TITLE
Improve documentation on how to populate properties in the column picker

### ISSUE THREAD

**Issue by NotYourTypicalDeveloper** [microsoft-search/pnp-modern-search#1043]
### Managed Columns in the Results Web Part is frozen

**Version used**
Ex: 4.0.0 and 4.2.2

**Describe the bug**
I have added the web parts to my page, when trying to configure the 'MANAGE COLUMNS', the column value field is "frozen" meaning it is impossible to enter any value in, also the drop down menu is not available.

I had no issues with a sharepoint site located on my "sandbox"tenant, which is my "dev" environment. It was working well.

**To Reproduce**
1. Uploaded the SPPKG file and deploy the web part at the tenant level
2. Go to the site -hosted on the tenant
3. Insert the PNP Modern search web parts on a page
4. Click EDIT on the Results web part
5. Click on "Manage Columns" to set the column value fields
6. I have tried to delete and re-install few times at the tenant level / same with the web parts on my page. 
7. I have re-installed the newest version (4.2.2)

**Expected behavior**
Expected to be able to select my Managed properties in the drop down, or at least being able to type them, then save.

**Screenshots**
The app is deployed:
![image](https://user-images.githubusercontent.com/41584108/120794845-a9096780-c530-11eb-83a6-16b1fefe4dcd.png)

this is where I am supposed to go for the configuration:
![image](https://user-images.githubusercontent.com/41584108/120794380-1072e780-c530-11eb-9d05-b9f328f28a48.png)

The column value field is sort of disabled:
![image](https://user-images.githubusercontent.com/41584108/120794168-c984f200-c52f-11eb-914c-9ebe5dea2435.png)

I can't type nor select anything in the field:

![image](https://user-images.githubusercontent.com/41584108/120794042-96426300-c52f-11eb-8768-f81ddd5c6401.png)

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
The PNP Modern search webpart doesn't even show in the "Add an app" section of the destination site however I am able to add the web parts in any page. This issue occured on both version 4.0.0 and 4.2.2
It worked perfectly on my sandbox tenant with version 4.0.0

Please help Thank You

**Comment by wobba** [comment]
If it works on one tenant and not another, do you see any errors on api calls or in debug console on the tenant where it's not working?

**Comment by CAH1983** [comment]
Thanks for the quick reply, this is what I get when I open the page and try to edit the web part.
104 warnings and some errors here below (some errors are the same as on the tenant which works):
![image](https://user-images.githubusercontent.com/41584108/120989670-b19faf00-c777-11eb-9331-14ee74cb3e96.png)

**Comment by wobba** [comment]
Those errors are coming from:
* A browser extension you have (chrome-extension error)
* TypeError is from some script you have running on the page calling `executeFunc` - ref the jquery reference.

I suggest you remove any other script on the page and re-try. Seems something else could be messing up the pnp web parts. Is there a script editor webpart in place or global/site scoped application customizers?

**Comment by wobba** [comment]
You need to ensure you have results showing in the web part before you can expand the list of properties as it's populated based on returned results - not based on the properties specified in the managed property list.

I'll see if we can make this clear somehow.

**Comment by CAH1983** [comment]
Sorry! On my tenant prod, I had no results showing after performing a search, this is why I thought I should configure the Managed Columns first. 
The page I developed previously on "Tenant Test" is working but I can't remember what are the steps I followed in order. I will try to make it work then and only after it shows results, then I will configure the properties. Please let me know if you update the documentation later.
Thank you Mickael for the help and support

**Comment by wobba** [comment]
I renamed the issue and will keep it open until we improve :)
