### ISSUE TITLE
v4 Verticals not using result source

### ISSUE THREAD

**Issue by roberAlb** [microsoft-search/pnp-modern-search#1044]
**Version used**
Version 4

**Describe the bug**
I have read that Verticals now are assigned from the results webpart itself through a dropdown. In version v3, we had a result source per vertical and was refreshing the results webpart with the right results depending on vertical selected. What happen now in v4 if we have 10 different verticals? Should we have 10 results webpart in a page? Is this not affecting to the performance?

**Expected behavior**
I would expect to have just one single results webpart in the page.

**Desktop (please complete the following information):**
 - Tested in chrome

**Comment by wobba** [comment]
Correct. You add multiple web parts, and pick the vertical it corresponds to per web part. It's decoupled from result sources as those are a specific classic API dependency, not working across different search providers.
