### ISSUE TITLE
Event display error

### ISSUE THREAD

**Issue by Mcdga** [microsoft-search/pnp-modern-search#1045]
**Version used**
4.2.2

**Describe the bug**
The event is not displayed.
![eventsDisplayError](https://user-images.githubusercontent.com/25668196/120813661-18c12780-c51c-11eb-8c9f-cde6a04d6a7e.JPG)

**To Reproduce**
1) Filter to "STS_ListItem_Events". 
![eventsDisplay2](https://user-images.githubusercontent.com/25668196/120818763-ea921680-c520-11eb-8b38-248ac4c6d9f2.JPG)
2) Click on an event
3) The event is not displayed
The result link is : https://xxxxxx.sharepoint.com/sites/yyyyyy/Lists/Events/7_.000?web=1
![eventsDisplayError2](https://user-images.githubusercontent.com/25668196/120818343-8707e900-c520-11eb-96db-336fb1c1480a.JPG)

**Expected behavior**
The event should appear in a SharePoint event or in a web calendar.
The result link should be : https://xxxxxx.sharepoint.com/sites/yyyyyy/_layouts/15/Event.aspx?ListGuid=e415373f-7711-4f60-acc4-ebf812d867a4&ItemId=7  (SharePoint event)
![SPEvent](https://user-images.githubusercontent.com/25668196/120817576-d00b6d80-c51f-11eb-9669-e7f35685f3f8.JPG)

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by wobba** [comment]
See #945

**Comment by wobba** [comment]
In the latest version the URL is do DispForm.aspx which is what the result return. If you want to re-write this to Event.aspx you can do so yourself in a custom template.
