### ISSUE TITLE
PnP Search Web Parts(V4.2.2) not supported by IE11 browser

### ISSUE THREAD

**Issue by shariq1379** [microsoft-search/pnp-modern-search#1047]
**Is your feature request related to a problem? Please describe.**
We are very happy to use PnP Search web part and it fills all business requirements in SPO. However, We noticed PnP search web parts do not support IE11 version and IE11 still a  standard browser in our organization. This is a big concern for us now.  

**Describe the solution you'd like**
It will be great help for us if PnP search web parts (v.2.2) support IE11 browser. Could you please make it possible? 

**Describe alternatives you've considered**
No alternative way. It's kind of a showstopper for us

**Comment by wobba** [comment]
Only PnP v3 and v4 is updates, and making it work for IE11 is just too much of a hassle unfortunately, and is why we call out that it's not supported at https://microsoft-search.github.io/pnp-modern-search/#supported-browsers. Also, Office 365 is stopping support for IE11 in August so the time has come to move on 🙂

https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666
