### ISSUE TITLE
Documentation improvement / question about "Static" filter vs "Refiner" filter.

### ISSUE THREAD

**Issue by hervedorierai3** [microsoft-search/pnp-modern-search#1050]
Hello, 

in the documentation concerning the [filter webpart v4](https://microsoft-search.github.io/pnp-modern-search/usage/search-filters/), a chapter deals with the difference between "static" and "refiner".
It's probably due to my bad english, but I understand the difference, but I don't undestand how to set a filter as static.

My need if to have a static filter (searchable combobox) on a predefinied termset : the user select a taxonomy value in the combobox, and the search result webpart show all content tagged with this valeur (search criteria, not a refinement).

Thank you for your feedback.

**Comment by wobba** [comment]
Today the date picker template is the only pure static one. The date range one is somewhat static, but it looks at returned results to pick which entries to show.

Currently we don't have a static taxonomy option, but I have thought about this as well as an improvement. It's possible for a developer to either extend the filter web part to support this, or create a custom static filter web part which can connect via dynamic data to support this.

**Comment by wobba** [comment]
Updated at https://microsoft-search.github.io/pnp-modern-search/usage/search-filters/#filter-types-static-filter-versus-refiner-filter
