### ISSUE TITLE
Translate terms according to a modern page's translation language - to override UX language

### ISSUE THREAD

**Issue by LetMeSP** [microsoft-search/pnp-modern-search#1053]
**Version used**
4.2.2.0

**Describe the bug**
When a term label is renamed in the term store for the managed metadata PnP web parts (Results & Filter) still show the old value. The label shown in the SP document library is updated as expected. Term label is mapped to a RefinableString used for PnP web parts.

**To Reproduce**
- Rename a term in the term store.
- Start manual re-index of the document library where the term is used.
- Confirm that the term label is updated in the library. 
- Confirm that the label is not updated in the PnP search web parts.

**Expected behavior**
The term label in the PnP web parts should show the new label from the term store.

**Desktop (please complete the following information):**
Win 10 / tested on Chrome & Edge

**Comment by wobba** [comment]
I'll update the docs for v4, but have you set up your managed properties according to https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-results/#miscellaneous-taxonomy-values-dynamic-translation ?

**Comment by mw-test-acc** [comment]
We have a similar issue.
We have a communication site where Sitepages have been created for English (default), French and Spanish Languages.
We have English, French and Spanish Labels enabled for Terms in Term Store.
The Term Set is mapped to a Managed metadata site column which is added to a Document Library
Localization is enabled on the Search Results webpart
But the Search Results webpart and the Refiners that show the Refinable Property display the Term Labels in English and not in French/Spanish on their respective pages.

We are using version 4.2.3 of PnP Modern Search
Could you please let us know if this the correct behavior?

**Comment by wobba** [comment]
@mw-test-acc Would be good if you can explain how you have done the cp/mp mapping. If you use the debug template, what does the value for a refiner value look like in the response?

**Comment by mw-test-acc** [comment]
![image](https://user-images.githubusercontent.com/86765215/124149398-2aabd100-daae-11eb-8533-47ece36488ea.png)
The taxonomy mp (RefinableString125) is mapped to cp created for the site column.
In debug template, of the French sitepage, the value is displayed in English
   "RefinableString125": "GP0|#bf08a7c4-7f83-4534-827b-5b106a31b0b0;L0|#0bf08a7c4-7f83-4534-827b-5b106a31b0b0|IT;GTSet|#e21dee54-2424-4a34-9d73-9659e43c4681",
        "RefinableString126": "IT",
        
But the value specified for French is seen below
![image](https://user-images.githubusercontent.com/86765215/124150263-08668300-daaf-11eb-8079-c30997f48402.png)

**Comment by wobba** [comment]
The term will be translated to the language of the browser / SP UX. It's not clear how you are testing or how you are expecting the translation to happen? Is your question more about that the web part should respect the content language of a translated page, and not the UX language of the user?

**Comment by mw-test-acc** [comment]
My question is if the SharePoint site is a Communication site and the Language selected by user is for instance French, will PnP Modern Search webparts not translate the Terms to the selected Language? Note - Localization is enabled on the Search Results webpart.
![Translation](https://user-images.githubusercontent.com/86765215/124436587-bca82800-dd93-11eb-8463-510b2edd35e0.png)

**Comment by wobba** [comment]
@mw-test-acc No, selecting a translation language is not respected today. Only the SP UX language is respected, which from your screenshot is English. I'll rename this issue and tag as an enhancement.

**Comment by mw-test-acc** [comment]
> @mw-test-acc No, selecting a translation language is not respected today. Only the SP UX language is respected, which from your screenshot is English. I'll rename this issue and tag as an enhancement.

Thank you! That would be much appreciated

**Comment by wobba** [comment]
I believe this should be working now as we pick up the culture from translated pages.
