### ISSUE TITLE
HTML Tags are appearing in Search results

### ISSUE THREAD

**Issue by girimng** [microsoft-search/pnp-modern-search#1054]
PnP Search is implemented in our SharePoint Online application.
Version Used: 3.14.1.0

In one of the custom webpart, "**Plain text muti line text**" column is used and values are saving with HTML tags in the SharePoint list.

In the search results, custom result template is being used and "hit highlighted summary" is mapped with the above mentioned custom column. When we try to pull the values it displays with html tags in the PnP Search results webpart

Note: Already tried with  {{{getSummary HitHighlightedSummary}}}. this is not working. In the search result webpart values should be shown without HTML tags.

Kindly suggest anyother method to overcome this issue.

![HTML Tags issue](https://user-images.githubusercontent.com/53866130/121174832-fc085500-c877-11eb-8237-b75223199e6a.PNG)

**Comment by wobba** [comment]
See #533 on how to deal with html. You need to enclose the property with tripple braces {{{prop}}}. This is not a web part issue, but a handlebars thing you have to deal with when using multi-line SharePoint fields.

**Comment by girimng** [comment]
@wobba As i mentioned earlier we have already tried with tripple braces {{{prop}}} but no luck yet. Kindly suggest any other method to overcome this issue.

**Comment by wobba** [comment]
You can try something like this. Not sure if it's optimal, and might not work if the data is encoded.

```html
{{#each (getSummary HitHighlightedSummary) as |summary| }}
     <span>{{sanitize summary}}</span>
{{/each}}
```

Your other option is to create a custom handlebar helper or web component which formats this for you the way you want.
