### ISSUE TITLE
Unable gulp Serve the new Pnp Search V4

### ISSUE THREAD

**Issue by tony-philipose** [microsoft-search/pnp-modern-search#1055]
I have downloaded it from the repository and install the npm packages with the **node version 8.11.1** and **npm version 5.6.0**. successfully installed the npm packages but unable to **gulp serve** as it shows below warnings. 

![image](https://user-images.githubusercontent.com/30836715/121191475-a177f480-c889-11eb-9c9f-deb89fa5eae5.png)
Kindly give me a solution thanks in advance.

**Comment by wobba** [comment]
Start here for SPFx dev: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

Then you see node v8 is not supported for later versions of SPFx.
