### ISSUE TITLE
Incorrect encoding when connecting search box and search results

### ISSUE THREAD

**Issue by stevebeauge** [microsoft-search/pnp-modern-search#1056]
**Version used**
Ex: 4.2.2

**Describe the bug**
I often use the combo search box + search results WP, connected using dynamic values.

However, when there's a space in the query (maybe other special chars too ?), the query encode the space with a `%20`.

For example, typing `some term` in the search box results in the query `some%20term`:

The page's url is `..../sitepages/search.aspx#some term` (actually reached using a search box WP in another page).

Hardcoding `some term` in the query in the search result WP produces results, while dynamic query won't because of the encoding.

**To Reproduce**
In a modern page, put the two WPs:
* SearchBox WP:
  * connect its source to use the url query fragment (`#myterms`)
* Search results WP:
  * connect to SP Search
  * keep the default query `{searchterms}`
  * in the 3rd page use a dynamic value:
    * source : page environement
    * property : query string
    * query string: url fragment
(not sure of the english labels)

Save the page, and trigger a query with "some term"

**Expected behavior**
Spaces shouldn't be encoded and results should be returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/184604/121307617-741a5d80-c900-11eb-8dca-6e36850af3a6.png)

**Desktop (please complete the following information):**
Firefox

**Comment by stevebeauge** [comment]
I'm not sure, but I feel the issue came from : https://github.com/microsoft-search/pnp-modern-search/blob/9df6c4e1d26cf004d9d04e9b423ec832d88c435a/search-parts/src/webparts/searchResults/SearchResultsWebPart.ts#L257

The output of `this.property.queryText.tryGetValue()` yet contains the `%20`. I'm not sure of the impact, but maybe this should be url decoded here ?

**Comment by wobba** [comment]
Will be part of the next release.
