### ISSUE TITLE
How to get or show PromotedResults in search results in pnp modern search v4

### ISSUE THREAD

**Issue by AnjalyDeepak** [microsoft-search/pnp-modern-search#1058]
In pnp version 3.16.0 we get promoted results in the result JSON like below:

 `"secondaryResults": [],
  "promotedResults": [
    {
      "Title": "test",
      "Url": "https://....",
      "Description": "..."
    },
    {
      "Title": " ...",
      "Url": "https://,,/",
      "Description": "..."
    }
  ],`

How to get promoted results? We have already enabled query rules in the search result web part property.

**Comment by wobba** [comment]
(Please fill out the issue template with steps tried when logging issues.)

The List layout has oob support for promoted results in v4.

![image](https://user-images.githubusercontent.com/51104/121368708-8e256180-c93b-11eb-878e-2f36d347f24b.png)

You can see it coming back using the debug template as well.

![image](https://user-images.githubusercontent.com/51104/121368957-bf059680-c93b-11eb-906e-055e3293db48.png)

This is the template fragment used in the List template

```html
   {{#if @root.data.promotedResults}}
        <ul class="template--defaultList template--promotedResults">
            {{#each @root.data.promotedResults as |promotedResult|}}
            <li>
                <div>
                    <pnp-icon data-name="MiniLink" aria-hidden="true"></pnp-icon>
                </div>
                <div>
                    <a href="{{url}}" style="color:{{@root.theme.semanticColors.link}}">{{title}}</a>
                    <div>{{description}}</div>
                </div>
            </li>
            {{/each}}
        </ul>
        {{/if}
```

**Comment by JonoSuave** [comment]
I'm using PnP Modern Search v4 with Query Rules enabled, but the query rule I set up only shows at the top with OOB search results page and not within the PnP search results web part. In debug mode I see an empty array for "secondaryResults" but primaryResults doesn't even exist as a property.
![PnP Modern Search Enable query rules](https://user-images.githubusercontent.com/22969971/123299388-762b1180-d4e7-11eb-8057-5e9a2e47d19f.png)
![Query Rules Displaying with OOB Search Results](https://user-images.githubusercontent.com/22969971/123299394-77f4d500-d4e7-11eb-9850-f93dc905e4d9.png)

**Comment by wobba** [comment]
As mentioned, you should have a `promotedResults` node if it's configured correct. And the list layout should render it. Please don't comment on closed issues, but log separate ones providing details of your setup like query template etc.
