### ISSUE TITLE
[Question] Filters reset after new search

### ISSUE THREAD

**Issue by joelfmrodrigues** [microsoft-search/pnp-modern-search#1060]
**Version used**
Ex: 3.19.2

Hi, I think this is more a question than an actual bug, but just wanted to confirm:

1. I have a search page and perform a search using the search box web part 
2. Search results and filters web parts update accordingly based on results returned
3. I can apply filters and the search results update based on the filter I selected
4. I then search for a different sentence in the search box
5. The filters web part is reset and no previous selected filters are preserved

Is this the expected behaviour? Is it possible, if I changed the code, to preserve filters between queries? (I know I could be asking a silly question but wanted to be 100% sure about the options here)

**Comment by joelfmrodrigues** [comment]
@wobba thanks, that's what I thought but wanted to double-check with someone that knows the solution better :)
In my case, I have something similar to the first 2 points you mentioned above. I extended the filters available and added a custom filter that I created as a full term set representation in a tree view. I then disable the filters that have zero results after each query.
The client now enquired about the possibility of retaining selected filters between searches and I wanted to be 100% sure that this was no simple task before getting back to them.

Will close this item, thanks again

**Comment by wobba** [comment]
We have an old item #36 for this :) Having a static taxonomy filter makes a lot of sense. Tie it to a termset and use as a filter.

**Comment by joelfmrodrigues** [comment]
@wobba That's what I have as it was an explicit requirement from a client. Personally, I prefer the multi-checkbox template as you only get refiner values that are valid, but the client really wanted an entire term set. The term set Id is configurable in the refiners data collection panel of the web part.
I can't share this for now due to the commercial arrangement in place with the client, but in the future, I will try to get this out if others find value (assuming the client agrees to it).

![image](https://user-images.githubusercontent.com/19577724/121758367-ff6e3b80-cb18-11eb-99ee-2242da6d2db6.png)
