### ISSUE TITLE
PnP Search Filter: Sorting of filter names is first on number, then uppercase, then lowercase.

### ISSUE THREAD

**Issue by PerOve** [microsoft-search/pnp-modern-search#1063]
**Version used**
Ex: 4.1.0.0

**Describe the bug**
A PnP Search Filter webpart filter can be sorted by Name.
When you do, the sorting is not working as expected for letters.
It will place words with numbers first as expected.
Then it will list all words starting with an UpperCase letter.
Then it will list all words starting with lowerCase letters.

**To Reproduce**
Create text metadata with some entries starting with numbers, uppercase letters and lowercase letters.
Use this metadata in the Filters webpart.
Sort on name
Look at the sorting of the names for this filter.

**Expected behavior**
Sorting on letters should be case-insensitive.

**Comment by wobba** [comment]
Filters are sorted as returned by the API request which is case-sensitive. One can argue what the right approach is. The real issue is having data which is not consistent, as `foo` and `Foo` are two different refiner values, even though they both return the same set of data.

I'll tag this as an enhancement.

**Comment by PerOve** [comment]
Thank you @wobba for the very quick answer.
I can agree with you in many and maybe most cases.

The case where I met this issue, was with a large company using Enterprise keywords.
These keywords are written by end users. For them, "Foo" and "foo" are the same.

For this case it would be nice to switch to a case-insensitive sorting. 
Meaning that FOO, FOo, Foo, foo and all other variants will be listed as alternative filters.

Or would it be possible to "merge" them?

**Comment by wobba** [comment]
Added case insensitive sorting on filter names.

**Comment by PerOve** [comment]
Sooo cool! Have a nice weekend @wobba 🥳👍🙂
