### ISSUE TITLE
Unable to search for words separated by punctuations

### ISSUE THREAD

**Issue by Swathi-Shankarnarayana** [microsoft-search/pnp-modern-search#1066]
We have most of our File names separated by punctuations.
We are unable to search for words in between these punctuations.

**Version used**
3.16

**Describe the bug**
Filename: abc-pqr-xyz.docx
When we search for keywords for example abc*, it returns the correct results.
However, when we search for a string in between the punctuations such as *pqr* or *xyz, no results are returned.
Could you please help us understand if this is a correct behaviour? If this is expected behaviour, are there any workarounds to search for words separated by punctuations?

**To Reproduce**
Please refer to screenshots

**Expected behavior**
Want to be able to search for words between punctuations.

**Screenshots**
![image](https://user-images.githubusercontent.com/85704238/121581766-de8be480-ca4b-11eb-810e-d4dce1fca43a.png)
![image](https://user-images.githubusercontent.com/85704238/121581984-1bf07200-ca4c-11eb-9c37-a30c358ae264.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by wobba** [comment]
How tokenization and KQL works is a search and API issue, not web part related. See https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference#property-values-in-the-full-text-index for how wildcard support works. Which is prefix only.. meaning **term*** not ***term**
