### ISSUE TITLE
Slow loading search results webparts

### ISSUE THREAD

**Issue by allafridman** [microsoft-search/pnp-modern-search#1067]
I have Search webpart 3.18.1.0 release in my tenant. Use accordion in the search results template. The results are coming back slow, especially when there are multiple search results webparts on the page.
![image](https://user-images.githubusercontent.com/43753953/121689952-41549e80-ca93-11eb-9cad-689af04b5808.png)

  <div class="template_root">
        {{#if @root.hasPrimaryOrSecondaryResults}} 
		<div class="AcordionHeader">Human Resources</div>
            {{#if showResultsCount}}
                <div class="template_resultCount">
                    <label class="ms-fontWeight-semibold">{{getCountMessage @root.paging.totalItemsCount keywords}}</label>
                </div>
            {{/if}}
    
            <ul class="template_defaultList">
                
                {{#group items by ="MenuParentOWSTEXT"}}
                  <pnp-accordion 
					data-accordion-header-text="{{value}}" 
					data-theme="Default (default) | Neutral" 
					data-size="# | 12 (default)" 
					data-start-open="false" 
					data-rounded-corners="false">
    
                {{#each items as |item|}}
                <li tabindex="0" >
                        {{#> resultTypes item=item}}
                        
                            {{!-- The block below will be used as default item template if no result types matched --}}
                            <div class="template_result">
                                    <div class="template_contentContainer">
                                        
                                        <span class="template_title example-themePrimary" ><a data-interception="off" href="{{getUrlField MMUrlOWSURLH}}" target="_blank">{{Title}}</a></span>
                                    </div>
                            </div>
                        {{/resultTypes}}
                    </li>
                {{/each}}
                </pnp-accordion>
               
               {{/group}}
            </ul>
            
    </div>

**Comment by wobba** [comment]
We have no control of API call latency. With many parts and lot of usage you could perhaps be throttled?

https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online

**Comment by wobba** [comment]
Issue will be closed due to author inactivity.
