### ISSUE TITLE
Number of filter Refiners) values limited to 100?

### ISSUE THREAD

**Issue by sympmarc** [microsoft-search/pnp-modern-search#1068]
**Version used**
4.0.0

**Describe the bug**

We've got `RefinableString01` mapped to the `CrawledProperty` for `SiteTitle`. In the PnP Modern Search page we've built we're using `RefinableString01` as a filter. 

We know there are about 166 different values for the filter. It appears there are exactly 100 values returned in the `Refiners` property for the `postquery`. The values are returned in descending order based on the number of results.

**To Reproduce**
Add a filter to your PnP Filter Web Part which you know will have more than 100 values. Observe that not all the values are returned. (`SiteTitle` is a good proxy for this.)

**Expected behavior**

We'd like to see *all* refiner values in the filter. Is there a way to expand the number of refiner values returned?

**Screenshots**
![image](https://user-images.githubusercontent.com/1295627/121720967-b636d100-cab1-11eb-83fc-687c7b460e28.png)

cc: @eemancini @dcashpeterson

**Comment by wobba** [comment]
v4.1 added support for specifying the number to return per refiner.

**Comment by sympmarc** [comment]
I thought that might be the case. We'll upgrade and report back!

**Comment by sympmarc** [comment]
@wobba - You were, of course, correct, and the upgrade solved the issue. Thanks for the help!
