### ISSUE TITLE
Search extensibility custom libraries not working after upgrading to 4.2.x

### ISSUE THREAD

**Issue by mbice** [microsoft-search/pnp-modern-search#1070]
**Version used**
4.2.2

**Describe the bug**
After upgrading to 4.2 I realized that custom extensibility libraries I was using would no longer load correctly. In particular, custom web components I was using in my templates were not being loaded.

**To Reproduce**
1. Add a search results web part to a page
2. Add a custom extensibility library
3. Add your custom web component to the Handlebars template
4. Note that the custom web component doesn't load up. Results are returned in the query, but nothing renders.

**Desktop (please complete the following information):**
 - Chrome (latest)

**Additional context**
I think this is related to a change to SearchResultsWebPart.ts in this PR https://github.com/microsoft-search/pnp-modern-search/pull/1021/files. Seems the extension loading was moved after the registration of the web components. If I move it back to before the call to registerWebComponents, my extensibility library components start to show up again.

![image](https://user-images.githubusercontent.com/985283/121732005-859d6a00-caa6-11eb-8885-d84d6ab2c502.png)

@wobba thoughts? I didn't want to submit a new PR moving that line back up because it looks like it was moved to resolve a different bug.

**Comment by wobba** [comment]
Good call....please PR and I'll validate the handlebar helper loading and put out a dot release tomorrow.

**Comment by mbice** [comment]
Thanks, @wobba. PR #1071 submitted.

**Comment by wobba** [comment]
This again breaks the handlebar helpers :D I'll take a new stab at resolving both... not easy.

**Comment by wobba** [comment]
Should be fixed now and a new release updated.
