### ISSUE TITLE
Search query not passed from vertical to vertical when using separate pages

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#1073]
### Check existing issues before logging new ones
Similar issues. Tried all suggestions. I'm not sure if I'm just missing something or if it's broken

**Version used**
3.19.2 and 3.18

**Describe the bug**
Using M365 search box, configure Search verticals that point to two different pages. The query string is not passed from vertical to vertical.

**To Reproduce**

1. Configure two search pages.
2. Configure a search vertical that points to each page, using the syntax: https:/path/page.aspx?q={searchTerms)&v=vertical1
3. Configure to open in same page (though, it doesn't work if you use a new tab either)
4. Set up search results web part so they are connecting to Page Environment, Search , Search query on both pages.
5. Enter a query on one tab, then click on the other tab. Note that nothing is passed in the q= parameter. Example of url displayed: https://xxx.sharepoint.com/sites/SearchTEST/sitepages/search1.aspx?q=&v=vertical2
6. Set up search results web part so they are connecting to Page Environment, Query STring, Query parameter, q.
7. Enter a query on one tab, then click on the other tab. Note that nothing is passed in the q= parameter.

**Expected behavior**
the Query string q= parameter is used to pass the search query from one vertical to the other. 

**Screenshots**

**Desktop (please complete the following information):**
Windows 10
Current Edge and Chrome

**Additional context**
Query string showing after query for 'blue' on vertical 1: ../sitepages/search.aspx?q=blue&k=blue
Click on vertical2, which is configured for query string q, and see this in the url:  /search1.aspx?q=&v=Partner

**Comment by bryllyg** [comment]
Any hints on this? Am I setting it up incorrectly, or is it a bug? We're wanting to move to unique pages per vertical, so we can get unique sort and filters, but can't do so if we can't pass the query. Thanks!

**Comment by wobba** [comment]
Seems like a bug, but haven't had any spare time to look at it. Hence the triage tag :)

**Comment by wobba** [comment]
Tested using the latest code base and it works as expected. I assume there is a typo in your issue with ) and not } after `searchTerms`.

**Comment by bryllyg** [comment]
It's not the ) for }, that was just me editing the sample not to include the command. The actual one has {}.  I tested on two sites, but I'll give it another go.

**Comment by wobba** [comment]
I just released version 3.21 https://github.com/microsoft-search/pnp-modern-search/releases/tag/v3.21.0

**Comment by bryllyg** [comment]
I'm using this syntax in the "link URL" field: https://bmgf.sharepoint.com/sites/name/sitepages/SearchP.aspx?q={searchTerms}&v=P.  I've tried this on two sites and tried setting up the results source connection with Page environment > Search and Page environment > Query String > Query parameters > q, with no success.  Should I be using Search or Query String? Does it matter?

I'll grab the newest rev and give it a try.

**Comment by wobba** [comment]
This is what I have and tested using the latest v3 version. Same setup on two pages.
![image](https://user-images.githubusercontent.com/51104/125671466-2b50554c-46b2-4efc-a28f-e582ccfd3910.png)

And linking a vertical to:
`https://tenant.sharepoint.com/sites/some/SitePages/Page2.aspx?q={searchTerms}&v=People

**Comment by bryllyg** [comment]
Cannot get it to work using {searchTerms}, but we were able to get it working using {QueryString.q}, so we're up and running now. Thanks!
