### ISSUE TITLE
Search refiners showing #;

### ISSUE THREAD

**Issue by chaitanya81-web** [microsoft-search/pnp-modern-search#1082]
Hi, 

I am using PNP Modern Search and for some of the files the refiners showing # and ; symbols. When i checked on the column fields on the library there is no special characters. 

![image](https://user-images.githubusercontent.com/52916638/122385669-b724a280-cf8a-11eb-9b2e-3fc5edcfc3f2.png)

I opened a case with Microsoft also, they are unable to identify the issue. 

can someone help me why it is showing and how to fix it?

Regards
Chetan

**Comment by Laul0** [comment]
Hi @chaitanya81-web,

What is the kind of metadata behind the refiner? Managed metadata, choice, single line of text, ...?
It is a custom refiner or are you using a default one?

**Comment by chaitanya81-web** [comment]
am using the default refiner which came with pnp-modern search. Those are choice fields on the library which are made as crawled metadata.

**Comment by Laul0** [comment]
I just tried it on my side and it looks great.
Did you configure a `RefinableStringXX` mapped with your field?
It is a multivalued field? Did you map the field with an internal name that looks like `ows_yourFieldName`?

**Comment by wobba** [comment]
My guess is this is a multi-choice field? And our web parts show whatever is stored in the internal SP field. Sure it's annoying. With v4 you can customize the template for refiners and add cleanup logic. And maybe we  should add a cleanup/normalize option as well.

**Comment by chaitanya81-web** [comment]
Its not a multi choice field. Yes i did configure a refinablestring and mapped field with ows_fieldname. I am using PNP-modern search 

PnP Modern Search - Search Web Parts | pnp-modern-search-parts | Version: 3.19.2.0

**Comment by chaitanya81-web** [comment]
It is a multi choice field with dropdown choices. Yes i did configure a refinablestring and mapped field with ows_fieldname. I am using PNP-modern search 

PnP Modern Search - Search Web Parts | pnp-modern-search-parts | Version: 3.19.2.0

![image](https://user-images.githubusercontent.com/52916638/122452574-04266a00-cfc7-11eb-91a4-73b1c78fb539.png)

**Comment by Laul0** [comment]
Ohh ok, it is not the latest version. @wobba, can you change the label to `v3` plz?
Ok, it is a multi-choice field!

Did you try the `v4` yet?

**Comment by chaitanya81-web** [comment]
dont see an option to download v4.

**Comment by chaitanya81-web** [comment]
sorry just downloaded it.  if i upgrade does it effect the existing search pages?

**Comment by Laul0** [comment]
Based on an existing issue: https://github.com/microsoft-search/pnp-modern-search/issues/907
I suggest you do a test first. It should not impact the existing configuration if you have not customization BUT I am not 100% sure.
If you can copy the site and test the upgrade that can be better for you I think

**Comment by chaitanya81-web** [comment]
@wobba i have installed the v4 and configured the search. However i have the # showing in the refiners / filters. Can you help me with the logic to get rid of #. MS guys wasted almost 15days and no help yet.

**Comment by wobba** [comment]
@chaitanya81-web It's not really a search issue that you have hash/semicolon in a refiner. This is verbatim how the data is stored in SharePoint. If you want to display it different that is up to you or your app showing the value. MS support should have closed your issue right away, not wasting 15 days 😉

Take a look at https://github.com/helpers/handlebars-helpers#replace and read up on handlebars 🙂
