### ISSUE TITLE
Error: Missing helper: "getGraphPreviewUrl"

### ISSUE THREAD

**Issue by PFederwitz** [microsoft-search/pnp-modern-search#1083]
**Version used**
4.2.2

**Describe the bug**
I am using PNP-Search to create a search page for our photo library. I am using the Card layout, but need a better way to link to the photo than the default. When you click on the Title it takes you directly to the photo file. First, I need it to open a new tab or page because when people view the photo and then click the back button they end up with a new search rather than where they were. Second, I like the view of the photo that you get in the asset library (where the photos are stored) where you get options at the top to download, copy, etc and the options on the right get a better view. 

On the templating page (https://github.com/microsoft-search/pnp-modern-search/blob/develop/docs/extensibility/templating.md) there is an option for getGraphPreviewUrl which provides the exact link that I want.

**To Reproduce**
I replaced the Location section on the Card view with a link because I am allowed to use HTML for that and I needed to add 'target="_blank" data-interception="off"' so that it would open in a new tab. Here is the code:
<a style="color:{{@root.theme.palette.themePrimary}};font-weight:600;font-family:'{{@root.theme.fonts.small.fontFamily}}'" href="{{getGraphPreviewUrl DocumentLink}}" target="_blank" data-interception="off">File Properties</a>

But now I get this message in the search results:
Error: Missing helper: "getGraphPreviewUrl"

**Expected behavior**
I should have a link with the name "File Properties" and the link should be to the Preview URL like: https://aequosdev.sharepoint.com/sites/dev/Shared%20Documents/?id=/sites/dev/Shared%20Documents/MyDocument.pdf&parent=/sites/dev/Shared%20Documents

If I remove "getGraphPreviewUrl" from the code it works fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/86069251/122437824-9c056300-cf89-11eb-963d-1783a79071f8.png)

**Desktop (please complete the following information):**
 - Browser Edge Version 91.0.864.33

**Additional context**

**Comment by FranckyC** [comment]
Hi @PFederwitz, good catch. Actually this helper was not present in the code. I've just add it to the develop branch so you should be fine.
