### ISSUE TITLE
When using external template URL in Search Filters webpart, Filter webpart does not load

### ISSUE THREAD

**Issue by ghost** [microsoft-search/pnp-modern-search#1086]
On PnP Modern Search version 4.2.3, Filters webpart are not rendering on the Page when we use HTML templates (using the external template URL) This was previously working on version 4.1.0
The HTML File is uploaded in the Site Assets Library.
The Filters webpart load correctly when the HTML is directly given via "Edit filters template" section instead of using external template URL.

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
Ex: 4.2.3

**Describe the bug**
On PnP Modern Search version 4.2.3, Filters webpart are not rendering on the Page when we use HTML templates (using the external template URL)
The HTML File is uploaded in the Site Assets Library.
The UI loads for a second and is then removed after the Page is saved.
The Filters webpart load correctly when the HTML is directly given via "Edit filters template" section instead of using external template URL. 

**To Reproduce**
1. Configure Search Filters webpart
2. Edit Refiners (Add one or more refiners)
3. Under available Layouts, select Custom
4. Provide URL of the external template HTML file under "Use an external template URL"

**Expected behavior**
Filters should load irrespective of whether we use Custom HTML or HTML via external template URL

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome/Edge
![PnPModernSearchIssue](https://user-images.githubusercontent.com/85704238/122629871-af294780-d0dd-11eb-87cc-bedcec299464.png)

**Additional context**

**Comment by FranckyC** [comment]
Hi @Swathi-Shankarnarayana , did you conenct the filter WP to the search results WP?

**Comment by Swathi-Shankarnarayana** [comment]
> Hi @Swathi-Shankarnarayana , did you conenct the filter WP to the search results WP?

Yes, I did.

**Comment by wobba** [comment]
Can you share setup for repro. Data provider, which refinement etc.

**Comment by mw-test-acc** [comment]
I have a similar issue.

Data Source - SharePoint Search
Refinement:
- Template - Checkbox
- Layout: Custom

External Template is stored in Style Library.
Search page is in SitePages Library
Both Template and Search Pages are in the same site collection

URL used for linking is in the format
https://******.sharepoint.com/sites/******/Style%20Library/ExternalTemplate.html

Please note, external Template works fine for Search Results webpart. However, it is not working for Search Filters webpart.

The Filters webpart load correctly when the HTML is provided via "Edit filters template" section instead of using external template URL.

Please help, we would really like to use External Templates for Filters

**Comment by mw-test-acc** [comment]
Is there an update on this issue?

**Comment by wobba** [comment]
When someone has time to look at this they will leave a comment. No need to ping. Remember that all efforts are based on volunteer work, and we always welcome more devs to help out :)

**Comment by wobba** [comment]
Tried now and cannot repro. You can try to name the file .txt and see if it helps. If you check the network tab, do you see calls trying to load your file?

**Comment by mw-test-acc** [comment]
I cannot add a txt file. The valid templates are either html or html.
I am able to see the html file in the Network tab with a 304 status code.
The DOM does not render on the page once I save the page.

**Comment by wobba** [comment]
@mw-test-acc rename the file to .txt. The PnP web parts don't care about the extension, but the web server serving the file does.

**Comment by mw-test-acc** [comment]
Please check this screenshot. Once I rename the file from html to txt and update the external template URL, it shows that it is not a valid template
![image](https://user-images.githubusercontent.com/86765215/126968749-9c532b2d-105f-472e-ab34-e1796fbfa5c1.png)

Once I save the page, the txt external template gets removed
![image](https://user-images.githubusercontent.com/86765215/126968892-e747557c-79e8-43d1-b6fe-9e4ba3e640c0.png)

**Comment by wobba** [comment]
My bad.. maybe we should open up to any extension, or add txt.

**Comment by wobba** [comment]
Added support for .txt
