### ISSUE TITLE
Configuration panel not loading

### ISSUE THREAD

**Issue by rdormanHW** [microsoft-search/pnp-modern-search#1088]
**Version used**
v3.20.0

**Describe the bug**
I have just downloaded and added this package (v3.20.0 last updated by @wobba ) to the App Catalog for my SharePoint Online tenant.

I have then attempted to add the Search box and Search Results web parts to a page in my communication site, however the Configuration panel fails to load for either web part.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create new page within Communication site
2. Click on '+' to add a new web part
3. Select the 'Search Results' web part
4. Click "Configure" button

**Expected behaviour**
I expected there to be configuration options available in the configuration panel as per the video demonstration

**Screenshots** Problem area highlighted in red box
![image](https://user-images.githubusercontent.com/81604756/122633443-10700b80-d11c-11eb-89f1-5c69b08f68f6.png)

**Desktop (please complete the following information):**
 - Browser: Google Chrome

**Comment by wobba** [comment]
Bases on your description we cannot help out. I suggest you hit F12 and look for issues in the network and console tab to provide more info.

**Comment by rdormanHW** [comment]
Thank you for your time. I have come back today to try to get the extra information you requested only to find that the configuration panel has now decided to load correctly. Must have been some sort of network glitch.

**Comment by wobba** [comment]
@rdormanHW just after upload/install there can be some time (minutes usually) before things work 100% due to js caching and if you have set up CDN etc.
