### ISSUE TITLE
Show individual users as refiners for multi-people field types

### ISSUE THREAD

**Issue by RamaKaryam** [microsoft-search/pnp-modern-search#109]
**Is your feature request related to a problem? Please describe.**
I have a crawled property (ows_InternalFieldName) resulting from multi-people picker field. It is mapped to an OOB managed property (RefinableStringxxx) in admin center. When this managed property is used as a refiner, it displays a comma separated list of users. 
![image](https://user-images.githubusercontent.com/32988250/75070352-e36c0400-54a7-11ea-9bb9-6a57b96ff44f.png)

**Describe the solution you'd like**
It would be great if it split them into individual users and then aggregated the result counts.

**Describe alternatives you've considered**
We used to be able to do it via display templates in classic search refiners. But refiners webpart doesn't expose that kind of extensibility yet. To be sure, I mapped the other two crawled properties that are generated -  ows_q_USER_InternalFieldName and just the InternalFieldName -  to other OOB managed properties and checked. They give the whole claims thing like below and that's not what we want.

_user@tenant.com | User Name | 693A30232E667C6D656D626572736869707C726368617661698K2GD696C6C696D616E6465762E636F6D i:0#.f|membership|user@tenant.com_

**Comment by FranckyC** [comment]
@RamaKaryam You can try to use the 'Persona' refiner template using the `ows_q_USER_InternalFieldName` crawled property (mapped to a RefinableStringXX). this should work.

**Comment by RamaKaryam** [comment]
Thank you @FranckyC . Working as you described.
