### ISSUE TITLE
pnp-modern-search web parts - not working for Hungarian users

### ISSUE THREAD

**Issue by JaneAnderson21** [microsoft-search/pnp-modern-search#1090]
We are using the search web parts on multiple site collections. One site has approximately 12800 items across multiple document libraries where we use * to return all results. 

For everyone, all 12800 documents appear as a total count about the search results web part. However, for 7 users in Hungary, only 2 documents appear in the total count. 

They have read access to all documents on the site, and I have even increased their site permissions to full control to see if that made a difference and it didn't. If the affected person performs a search using the normal site search, the results appear as normal but not within the pnp search web parts.

As mentioned earlier, these web parts are in use across multiple site collections but it's only this site that is affected for them.

Do you have any ideas what may be causing this?

![2 results](https://user-images.githubusercontent.com/86222485/122718731-31904380-d265-11eb-8c26-4dafac8fcb7a.jpg)
![12800 RESULTS](https://user-images.githubusercontent.com/86222485/122718889-5c7a9780-d265-11eb-96fc-4b292806fb07.jpg)

**Comment by wobba** [comment]
You have to examine the request/response going - as there is nothing special happening. It's the same API query for everyone and I don't know how you have configured the web parts in terms of query template, result sources etc, so cannot tell you why this happens. It's most likely setup related as the web parts are just passing the API query to the backend and rendering the results.

I would try to use the `Debug` template and look at what `QueryModification` displays for these users.

v3
![image](https://user-images.githubusercontent.com/51104/122744320-2a2e6180-d288-11eb-8795-78a7323d0721.png)

v4
![image](https://user-images.githubusercontent.com/51104/122744432-4205e580-d288-11eb-96a3-4e79b3c3b32f.png)

**Comment by JaneAnderson21** [comment]
Thanks for your response.

We've realised that this is related to the browser language. If we set our Hungarian's browser language to English, all 12800 results are displayed. Does anyone know which browser languages are officially supported please?

**Comment by wobba** [comment]
It's still unclear to me why it shows 2 only if the browser language is in Hungarian. Are you picking up the language somehow and using it as a query variable in the query?

**Comment by wobba** [comment]
Results shown and count should be the same regardless of the UX language assuming they have access to the same items, and if the query is not lemmatized/stemmed in a special way during search.

**Comment by JaneAnderson21** [comment]
We worked with Microsoft on this and we found that the 2 documents that were appearing had HU as the detected language when using the search query API.

We had a call with our Hungarian user yesterday and we switched their browser language to English then all results appeared with the results web part.

We then checked the settings that we had on the results web part and it was set to Localisation = ON, Use Interface Language. When we switched this to English, we could still see all results regardless of what the browser was set to.  Turning Localisation to OFF did not work for the HU browser language

Hope that helps provide some further details on how we managed to get around this issue.

Thank you all for your time.

**Comment by wobba** [comment]
Localization is to translate term labels/filters, and we should probably call this out in the settings. The UX support for the web parts is limited to a lot fewer languages. It's still not clear to me why you only got two docs vs many depending on the UX language. To me it seems like you are using the UX language as part of the KQL query to limit what you are seeing.

Or, when passing HU as the query language it limits what is returned. As you are querying for "*" you should get the exact same documents back if there are no language filters on the KQL/query template. If there are no KQL adding to restrict on language I would consider this an API bug to log with Microsoft for sure.

I tested using the SharePoint Search Query Tool, setting the language to HU, or using 1038 as the culture and got the exact same results. Can you share what the output of `queryModification` is if you switch to the debug template as I mentioned? 

I'd like to understand how the UX language impacts your results. If it's a setup on your end or an API bug 🙂

**Comment by JaneAnderson21** [comment]
Here is the query we are using as a result source: {searchTerms} Path:{SiteCollection.URL} ContentType:"Marketing Literature" FileType=PDF

and here is the output from the queryModification:

"queryModification": "* Path:\"https://XXXX\" ContentType:\"Marketing Literature\" FileType=PDF",

If I instead do a search on the file name e.g. GCM_72.pdf I would get 6 results rather than the expected 8 - as described earlier, 2 results have a detected language of HU. Microsoft suggested that perhaps the Word document had been created using a Hungarian Office client - this is not likely to be honest but we have no other answer right now!

**Comment by wobba** [comment]
Still weird. Changing the UX language should not have an impact on returned results for a '*' query using what you show above. I would push back on support to figure out what happens here.

Also do use `ContentType`, but use `SPContentType`.

**Comment by wobba** [comment]
Stale issue
