### ISSUE TITLE
Issue sorting by ViewsLifeTime

### ISSUE THREAD

**Issue by Leighton365** [microsoft-search/pnp-modern-search#1093]
**Version used**
Ex: 3.16

**Describe the bug**
I'm seeing an issue when sorting by ViewsLifeTime on a document library.
On page 2 of the Search Results configuration, under 'Edit Sortable Fields', I have added ViewsLifeTime (sort descending).
The sort order does not reflect this when viewing in in the search results.
It appears to be random.

**To Reproduce**
1. Configure the PNP search web parts to show results from a document library
2. On page 2 of the Search results configuration, click on 'Edit sortable fields' and add 'ViewsLifeTime' (then save).
3. On page 3 of the Search results configuration, click on 'Manage columns' and add ViewsLifeTime' (then save).
4. Close the configuration blade, and then go to the search results.
5. Select Lifetime Views from the sort order dropdown.
6. Observe that the sort order appears to be random.

**Expected behavior**
I would expect that the sort order of ViewsLifeTime would show in an incrementing or decrementing order depending on whether it is set to ascending or descending.

**Screenshots**
<img width="35" alt="Lifetimeviews" src="https://user-images.githubusercontent.com/86303200/122934382-64226500-d367-11eb-8547-5bcee7093a9f.PNG">
<img width="666" alt="ManageColumns" src="https://user-images.githubusercontent.com/86303200/122934583-8fa54f80-d367-11eb-8861-17fb7d2969e3.png">
<img width="623" alt="SortableFields" src="https://user-images.githubusercontent.com/86303200/122934730-b499c280-d367-11eb-971b-3f0b9a67846b.png">

**Desktop (please complete the following information):**
 - Microsoft Edge

**Additional context**

**Comment by wobba** [comment]
You need to set default sorting via sort order. And also ensure you add `ViewsLifetime` to the list of managed properties to retrieve.
![image](https://user-images.githubusercontent.com/51104/123248424-33b60480-d4e8-11eb-86ea-df5141696f4e.png)
![image](https://user-images.githubusercontent.com/51104/123248665-7972cd00-d4e8-11eb-9e02-e7ad76e194f5.png)

Then you will see the values and sorted correct on initial load.
![image](https://user-images.githubusercontent.com/51104/123248800-a1fac700-d4e8-11eb-9fe6-e50a43354809.png)

Remember if you click the sort arrow on the column, that is re-ordering in page - not requery, as noted in the documentation.

**Comment by Leighton365** [comment]
Hi wobba,
Many thanks for the reply.
I can confirm I have that configuration:
![SortOrder](https://user-images.githubusercontent.com/86303200/123334696-60dfd280-d53b-11eb-8687-711050d8cf93.png)
![MabagedProperties](https://user-images.githubusercontent.com/86303200/123334720-69380d80-d53b-11eb-97c3-8884f8b4599a.PNG)

I've noticed that I get different results (both incorrect) depending on how I sort.
For example:
If I sort using the Sort box (See pic)
![SortBox](https://user-images.githubusercontent.com/86303200/123335006-c5029680-d53b-11eb-9e99-38260599f3e9.png)
Then the order is completely random (see pic).
However, if I sort by clicking on the Views column (see pic)
![ViewsColumn](https://user-images.githubusercontent.com/86303200/123335210-0b57f580-d53c-11eb-8c1a-6d1f595730e4.PNG)
Then the order is almost correct, in that it is sorting in ascending/descending.
However, it seems to count 10, 11 as the 1's and 20, 21 as the 2's if that makes sense?
So
1
10
2
23
3
And so on.
It's clearer in the screenshots.
Is that a bug or just a misconfiguration somewhere do you think?

**Comment by wobba** [comment]
Issue will soon be closed due to author inactivity.
