### ISSUE TITLE
Search Filter Web Part Not loading Data from Site Column - Single Line Of Text

### ISSUE THREAD

**Issue by lambo77** [microsoft-search/pnp-modern-search#1094]
Version used
4.2.3

Bug
After adding a managed property to RefinableString005 and mapping the property to a site column (single line of text) i then enabled the property on the search result web part and added it as a new filter on the search filter web part.  Nothing is being loaded for that filter. 

To Reproduce

3 web parts on the page
Pnp Search box
Pnp Search Results
Pnp Seatch Filters

Added and configured all web parts and result content being returned . However Filter web parts not working as expected. Data from Single line of text field not being pushed into the filters

### Screenshots
Mapped Managed Property
![image](https://user-images.githubusercontent.com/75328696/122934364-5ff64780-d367-11eb-8ab6-bdba8869bd2b.png)

### Selected Property on Search Results 
![image](https://user-images.githubusercontent.com/75328696/122934666-a481e300-d367-11eb-8ee9-2d79355a5d85.png)

Added Filter 
![image](https://user-images.githubusercontent.com/75328696/122935142-017d9900-d368-11eb-89ed-6b01fe7beb65.png)

But only the first Filter Visible 
![image](https://user-images.githubusercontent.com/75328696/122935320-270aa280-d368-11eb-9a86-d1812a822e12.png)

Mapped data Filter not loading 

Using Chrome Browser Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by Laul0** [comment]
Hi @lambo77,
Here some ways that can help you:
1. did you connect/link your filter web part with the results web part and vice versa
2. did you try to not use a filter and display the results with the debug view to ensure that your field has content?
3. rather than use the internal field, did you try `RefinableString05` or the alias `agraTradeRefRefinable`

Let us know if that solves your issue

**Comment by lambo77** [comment]
Hi 
Thanks for the reply. Using RefinableString05 worked ! 

![image](https://user-images.githubusercontent.com/75328696/123061593-adc08d80-d403-11eb-9a59-027d616b1cbe.png)

Regards
Liam
