### ISSUE TITLE
Ampersand "&" in the search query is causing issue

### ISSUE THREAD

**Issue by SaratchandraPeddinti** [microsoft-search/pnp-modern-search#1096]
My search box webpart is configured to refresh the URL parameters of the page environment when user keys in search query & hits on the search button.

Issue: However, when the user searches for any search query consisting of the "Ampersand" is resulting in inaccurate search results as the Search Results webpart is not omitting any text after the ampersand symbol.

E.g.: I enter "Test_value1 & Test_value2" in the search box & hit on search, it only searches for "Test_value1 " and omits the rest of the value. I tried with URL encoding of the ampersand, it didn't work either.  Please help me with this.

Thanks in advance.

**Comment by FranckyC** [comment]
Hi @SaratchandraPeddinti , this should be resolved by @Laul0 PR. Can you try it using the `develop` branch and confirm?

**Comment by camel028** [comment]
Hi @Laul0 , @SaratchandraPeddinti , could you please make a fix for version 3 as well?

Many thanks!
