### ISSUE TITLE
Refiners not loading all the values of refinable properties

### ISSUE THREAD

**Issue by SaratchandraPeddinti** [microsoft-search/pnp-modern-search#1097]
Hi there,

My search page returns 200k+ results(documents). And, the refiners load values of all the refinable properties associated with the documents. However, the refiners are not showing all the values that are supposed to be available.

E.g.: The returned results set has a refinable property, called "Document Category". The refinable property usually binds a large array of values to the refiner webpart. Issues is it's not showing all the values. Is there a hard limit on how many values a refiner webpart displays? If yes, what should I do to extend the list of values

Thanks in advance.

**Comment by FranckyC** [comment]
Hi @SaratchandraPeddinti, the maximum is 5000 values for a refiner if I remember correctly. However, using the latest v4 version you can now control the number of values for a specific filter:

![image](https://user-images.githubusercontent.com/5659122/123156354-2f7dde80-d437-11eb-9c9e-7d4edb86b401.png)

This setting is not present for v3.

**Comment by wobba** [comment]
For very large result sets there is also server side logic to stop processing after X time - so you are not ensured all values will be returned depending on the scenario.

Refiners with more than maybe 15 values is not very user friendly or useful - unless you use filtering to find the value you look for.

**Comment by SaratchandraPeddinti** [comment]
Sure. Thanks Mikael.

**Comment by wobba** [comment]
@SaratchandraPeddinti are you good with closing the issue?

**Comment by samrutur** [comment]
@wobba - I am running into this issue on a page with large result set. The filter for the JobTitle property in People search is not showing all the values in the search results. We don't have any limit set on the number of filters. What is the limit of the filters that can be loaded? Also, when I use the search in the filter the expected value doesn't show up. It appears that it does a partial load of the filters.

**Comment by SamanthaSt** [comment]
Hey, I´m jumping on here because I have same Issue. 
I want to filter a RefinableString but even if I set the number of values to 5000 I only get back 1000. 
![image](https://user-images.githubusercontent.com/35326712/232084251-d7c1cf56-2ef2-4c0b-bc16-891a77f4e39f.png)

PnP Search Version: 4.8.0

**Comment by wobba** [comment]
If the API is capped at 1000, there is no way to get more than 1000.

**Comment by SamanthaSt** [comment]
@wobba but you guys said further up that 5000 is possible. So is that no longer the case?

**Comment by SamanthaSt** [comment]
@wobba  is there a way to access the API myself? I use the Extention Library to create my own Tree View for the organization filter. So i would be able to load them myself if there is an open APO to get the refinables with their values.

**Comment by wobba** [comment]
It used to be 5000, now it seems to be 1000.
