### ISSUE TITLE
@root.data.promotedResults doesn't exist with query rules Enabled

### ISSUE THREAD

**Issue by JonoSuave** [microsoft-search/pnp-modern-search#1101]
**Version used**
4

**Describe the bug**
I'm using PnP Modern Search v4 with Query Rules enabled, but the query rule I set up only shows at the top with OOB search results page and not within the PnP search results web part. In debug mode I see an empty array for "secondaryResults" but primaryResults doesn't exist as a property.

**To Reproduce**
1. Set up a query rule as documented by Microsoft: https://docs.microsoft.com/en-us/sharepoint/manage-query-rules. In my case I used the word mission with Advanced Query Text at the tenant admin level.
2. Enable query rules within search results web part
3. See attached for search box and search results web parts configurations
4. Search for query rule text in OOB Search and the OOB search results will have a banner of the link posted in the query rule.
5. Do the same search using the PnP - Search Box web part

**Expected behavior**
PnP Modern Search Results web part renders the promoted page set in query rules.

**Screenshots**
![PnP Modern Search Enable query rules](https://user-images.githubusercontent.com/22969971/123302757-074fb780-d4eb-11eb-8524-cf0877f7244c.png)
![Query Rules Displaying with OOB Search Results](https://user-images.githubusercontent.com/22969971/123302767-0a4aa800-d4eb-11eb-892a-3462077bad0c.png)
![Screen Shot 2021-06-24 at 12 48 04 PM](https://user-images.githubusercontent.com/22969971/123302895-3108de80-d4eb-11eb-95e5-1ef35ddfe25e.png)
![Screen Shot 2021-06-24 at 12 48 45 PM](https://user-images.githubusercontent.com/22969971/123302899-31a17500-d4eb-11eb-9bb0-c6e9972207c1.png)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by wobba** [comment]
Using the list template it should work if you have configured it correctly using the latest version of v4 as per #1058. Use the debug display template to see what data you get back.

And you have not shared your query template nor tiggering (if any) of the promoted result you are not seeing.

**Comment by szyvett** [comment]
Hi @wobba, I have a similar issue. I have created a tenant-wide query rule last week, and have a list template for my Search Result, however, I wanted to add more query rules but on a site collection level to search for promoted results in a specific Hub site only. I did the same steps as before, and it is only the first rule I created that works. I have tried with a site-wide query rule, but that doesn't work either, so I decided to make another tenant-wide query rule, and that one is not showing up either. 
Only the first query rule that I have created. (I hope this makes sense)

If I use the OOB search, all the query rules behave as expected. 
How can I add multiple query rules to v4 search? Do site collection and site-wide query rules work on v4? Have I missed anything? I created the query rules as per [https://docs.microsoft.com/en-us/sharepoint/manage-query-rules#promote-a-search-result](url) - I forgot if I need to connect the query rule's GUID to the v4 search (I am very new to modern search and query rules.) 

Not-working Site Collection Query rule
![rule](https://user-images.githubusercontent.com/32570227/124447447-4a2a4e80-dd79-11eb-9ec0-ac4df302f710.JPG)

Working Promoted result
![home](https://user-images.githubusercontent.com/32570227/124445879-d8053a00-dd77-11eb-85f1-12edc0bc1cf2.jpg)

Not working Promoted result
![covid](https://user-images.githubusercontent.com/32570227/124445872-d6d40d00-dd77-11eb-857b-6f453d6adfa6.JPG)

OOB Promoted result (expected result for previous search)
![covid2](https://user-images.githubusercontent.com/32570227/124445877-d76ca380-dd77-11eb-814b-9d50e12b0a9d.jpg)

**Comment by wobba** [comment]
Query rules are tied to a result source. By default the web part uses the default results source (whatever that is on your site). Without knowing how you have set up the query rules in terms of connecting to a result source, and also how(if you have configured to use a result source in v4 it's hard to tell.

My test:

1. Result source ID: `LocalSharePointResults`
2. Query template: `{searchTerms}` <- Do not add anything else here. If you do, that is included in the triggering og rules
3. Enable query rules: on
4. Template: List

This will show promoted results from tenant+site. Top is tenant, two others are on the site in the screenshot below.

![image](https://user-images.githubusercontent.com/51104/124486928-61376380-ddae-11eb-87cb-d9e1e4ae71dd.png)

**Comment by wobba** [comment]
@JonoSuave any progress? If not we will close the issue due to inactivity.

**Comment by JonoSuave** [comment]
@wobba thank you! I had to change my result source id and that did the trick! Glad to better understand how it works.
