### ISSUE TITLE
Profile image for employee directory

### ISSUE THREAD

**Issue by PathToSharePoint** [microsoft-search/pnp-modern-search#1102]
**Version used**
4.2.3

**Question**
I am trying to leverage PnP Modern Search to build an employee directory (cf. [related twitter thread](https://twitter.com/Path2SharePoint/status/1407454513519161345) involving in particular @wobba and @sympmarc).

Configuration:
SharePoint Search (no Graph API access granted)
Results source: LocalPeopleResults
Layout: People

This is working pretty well, except that the profile pictures are not showing up for some users (screenshot below). What am I missing here?

Thanks!

**Screenshots**
![image](https://user-images.githubusercontent.com/40323257/123337219-beecc580-d4fb-11eb-980c-bb45579ad8c7.png)

**Comment by wobba** [comment]
If you hit F12 and look at:
* Network calls which fails for image
* Inspect the DOM for the URL which is being used

We are using this URL:
`/_layouts/15/userphoto.aspx?size=L&username=<username/upn>`

**Comment by PathToSharePoint** [comment]
Right, and I actually found the URL in the handlebars expression under the results Web Part Property Pane.

I assume the pictures for my test users Miriam and Megan don't show up because they never visited SharePoint. They used Teams and the SharePoint API but apparently that's not enough.

Would you have another option to recommend - using the Property Pane settings - to get the profile pictures?

**Comment by wobba** [comment]
That's the only URL I know which is within the SP domain not needing extra auth to be called.

**Comment by PathToSharePoint** [comment]
@wobba ok, thanks for the help. I'll continue working on my employee directory customization, let's keep in touch!
