### ISSUE TITLE
Dynamic Filter Options for selected Search Verticals

### ISSUE THREAD

**Issue by PranavR7** [microsoft-search/pnp-modern-search#1103]
As an avid user of the Search v3, we had the functionality of having different filters/refiners for a selected search vertical. However, After moving to Search V4, We found that we can't have dynamic filter options for different search verticals. 

Like for e.g. if a user selects a vertical called "Documents" they get X filter options & in the event where they switch to "Pictures" Vertical , they get Y filter options using the same filter web part. We were able to achieve this filtering using just 1 filter web part in search v3 but in search v4 we need to create two filter web parts one for Documents search vertical & result & the other for Picture Vertical & Results to achieve this.

I'm attaching a few images below for more understanding:

![1111](https://user-images.githubusercontent.com/86447968/123352103-f746df00-d5a1-11eb-8fe0-9ba221dcaffa.PNG)
![1111_0](https://user-images.githubusercontent.com/86447968/123352109-fa41cf80-d5a1-11eb-8b40-f549b0673fd1.PNG)
![000](https://user-images.githubusercontent.com/86447968/123352118-fd3cc000-d5a1-11eb-9acd-14ceee58466f.PNG)
![000_2](https://user-images.githubusercontent.com/86447968/123352124-ff068380-d5a1-11eb-9cda-43eb8e196ab7.PNG)

**Comment by sympmarc** [comment]
In the settings for the Search Filter Web Part, be sure to select all the Search Results Web Parts from which you'd like to use filter values. If you only have selected one, you get the same filters for all the Search Results.

![image](https://user-images.githubusercontent.com/1295627/123354237-3b4dcb80-d531-11eb-8ae4-f4789ebd4113.png)

This actually gives you more flexibility, but I've been caught by it, too!

**Comment by PranavR7** [comment]
Thanks a lot @sympmarc ! That fixed it.
