### ISSUE TITLE
Graph api permissions: app or delegated permissions?

### ISSUE THREAD

**Issue by TGiersberg** [microsoft-search/pnp-modern-search#1104]
**Version used**
4.2.3

**Question**
PNP Search webpart is asking for graph api **app** permissions. Can you explain why app permissions where chosen over delegated permissions?

**Comment by wobba** [comment]
They are delegated permissions. It's how SPFx work calling the Graph. https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-microsoft-graph-apis#approve-the-requested-microsoft-graph-permissions
