### ISSUE TITLE
Refiners do not refresh when navigating between two search pages

### ISSUE THREAD

**Issue by AlanSharePoint** [microsoft-search/pnp-modern-search#111]
**Version used**
3.9.0

**Describe the bug**
Refiners do not refresh when navigating between two search pages

**To Reproduce**
I'm using the search web parts on multiple pages of my site. Specifically the search box, refiners, results, and pagination.

1. When I first load a search page, everything works well.
2. I search for something in the first page
3. I complete my task on the first page, and navigate to another search page (containing a different query) to perform another task.
![1](https://user-images.githubusercontent.com/61286929/75077936-2fcc3980-54d2-11ea-8eb3-e9b600d49f9f.png)
4. Once I navigate to the next search page, the same filters remain, and no items show under them
![2](https://user-images.githubusercontent.com/61286929/75077942-322e9380-54d2-11ea-8867-5dbd5d51ce53.png)
5. I refresh the page, and the appropriate filters show up with items under them
![3](https://user-images.githubusercontent.com/61286929/75077945-335fc080-54d2-11ea-9d57-0cd135e2df15.png)

**Expected behavior**
Correct filters should show when navigating between search pages

**Screenshots**
See above

**Desktop (please complete the following information):**
 - Browser Chrome

Thanks for your help!

**Comment by wobba** [comment]
@FranckyC quickest solution would be as in #112 to add `data-interception="off"` to the navigation link. Or can we easily detect the router nav and load all webparts propertly?

**Comment by AlfreMoreno** [comment]
Hi @wobba, in this case, we are not creating link tags, just using the Sharepoint modern navigation. so we can't add the data-interception="off" attribute because SharePoint doesn't provide a simple way to customize the links.

![image](https://user-images.githubusercontent.com/22582515/75184000-a30fbe80-5711-11ea-8102-359b6a4b28e9.png)

**Comment by wobba** [comment]
@AlfreMoreno still an issue?

**Comment by bcameron1231** [comment]
@wobba I see the PR #394 to fix this issue was merged into develop. Any clue when it may get pushed into main and into a release?

**Comment by wobba** [comment]
@bcameron1231 When I get to it :) I'll try to get a preview release out this week for testing.
