### ISSUE TITLE
Manifest not found for component id "0d910c1 #Extensibility #Custom web component

### ISSUE THREAD

**Issue by saurabhsachan19** [microsoft-search/pnp-modern-search#1114]
Hi team, 

I am using PnP modern search V4 and need customization for web component. Then I go for extensibility for that I have folow below steps
1) Created on spfx library project 
2) Implement "IExtensibilityLibrary" in main entry point
3) Add web component .tsx file extents "BaseWebComponent"

finally generate sppkg and deployed on tanent level. And configure it in PnP search Web.
But its not wokring when I have checked sharepoint console there is multiple error is comming few of them mentioned below:

2021/06/28 09:50:35.159  verbose   SPComponentLoader.loadComponen  **Failed to load component "c89a236a-f986-496d-b4b8-XXXXXXXXX" (CustomComponentLibrary). Original error: Manifest not found for component id "0d910c1** 
2021/06/28 09:50:35.159  verbose   SPComponentLoader.loadComponen  Loading component "c89a236a-f986-496d-b4b8-XXXXXXXXX" (CustomComponentLibrary). Attempt 3 of 3. 
2021/06/28 09:50:35.159  verbose   SPComponentLoader.loadComponen  Loading component "c89a236a-f986-496d-b4b8-XXXXXXXXX" (CustomComponentLibrary). Attempt 3 of 3.

**2021/06/28 09:50:36.849  warning  RootServiceScope  PnPModernSearchExtensibilitySe  No extensibility library component found with id 'c89a236a-f986-496d-b4b8-XXXXXXXXX'**

I have not much experiece in spfx. Please let me know in case you need any other information.

**Comment by FranckyC** [comment]
Hi @saurabhsachan19, when you uploaded the library package to the app catalog, did you check the "Make this solutionavailable to all sites" flag? Also, did you configure the library ID in the Search Results Web Part property pane (last page)?

**Comment by saurabhsachan19** [comment]
Hi @FranckyC, Thanks for your quick reply. Yes I it is available to all sites and also configure this library id in search result web part.
![image](https://user-images.githubusercontent.com/28757352/123746991-f4185f80-d8cf-11eb-8083-71af4f9ebbe6.png)
 Webpart Registered here
![image](https://user-images.githubusercontent.com/28757352/123747574-be27ab00-d8d0-11eb-81f7-4a80eaf81db9.png)

below is the version details of my development enviornment.

Node version: 12@1.0.2
@microsoft/generator-sharepoint@1.12.1
@pnp/modern-search-extensibility@1.0.2

your help will always appreciated... thanks

**Comment by wobba** [comment]
@saurabhsachan19 you should verify the manifest id of the package you uploaded as per the docs https://microsoft-search.github.io/pnp-modern-search/extensibility/#register-your-extensibility-library-with-a-web-part 

The message says it's not available. You can try to delete it from the app catalog, and re-add. See if that resolves it.

**Comment by saurabhsachan19** [comment]
Yes @wobba , I have deleted this and re-add but still no luck... :(

**Comment by FranckyC** [comment]
HI @saurabhsachan19, can you try using the default extensibility sample library https://github.com/microsoft-search/pnp-modern-search-extensibility-samples/tree/main/search-extensibility-samples? Does it work with this one?
