### ISSUE TITLE
Display spelling suggestions in the OOTB result templates

### ISSUE THREAD

**Issue by felixbohnacker** [microsoft-search/pnp-modern-search#1116]
**Is your feature request related to a problem? Please describe.**
Currently, spelling suggestions are not displayed in any of the OOTB result templates.

**Describe the solution you'd like**
Ideally, there should be a toggle similar to the "Show "Did you mean?"" option for the classic search result web part. If this option is checked, a query suggestion should be shown on top of the search results if applicable.

**Describe alternatives you've considered**
Having to modify one of the existing result templates myself to achieve this is quite a hassle. I imagine that other people would benefit from this feature as well.

**Additional context**

**Comment by wobba** [comment]
v3 support this. v4 currently does not as there is no suggestion API available for the Search Graph API. The classic suggestion provider is not ideal either as it only relates to classic search experience/logging, not Microsoft Search.

**Comment by wobba** [comment]
The Microsoft Search provider support spelling suggestions as an option.
