### ISSUE TITLE
Guidance / Builtin web components -PnP Modern Search (v4)

### ISSUE THREAD

**Issue by surfingknowledge** [microsoft-search/pnp-modern-search#1118]
**I'm not dev Please I need help**

Is there any walk through or guidance **on how/where the Builtin Web-Components code should be injected?**  I'm looking to leverage the pnp-collapsible and pnp-panel . But I found zero help on internet. NO documentation at all on how to inject the code/Customize templates . 

https://microsoft-search.github.io/pnp-modern-search/extensibility/web_components_list/#pnp-panel

Thanks,

**Comment by MakingThingsWorkToronto** [comment]
To leverage these in a custom manner you will have to build a custom template and select the custom layout option in the web part property pane.

The documentation is here:  https://microsoft-search.github.io/pnp-modern-search/extensibility/templating/

Look at the html files here for out of the box layout templates: https://github.com/microsoft-search/pnp-modern-search/tree/main/search-parts/src/layouts/results

**Comment by wobba** [comment]
You can also pick an oob template, then click the `{}` button and that template is copied into the edit panel. Same as browsing the repo.
