### ISSUE TITLE
Search results do not refresh when using page attributes in query

### ISSUE THREAD

**Issue by coupalm** [microsoft-search/pnp-modern-search#112]
**Version used**
3.9.0

**Describe the bug**

Multiple pages having the search results web part using page attributes to filter results.
When navigating between these pages, the search results do not get refresh (always the results of the first page being accessed)
 
**To Reproduce**

1- Create 2 pages with the search results web part. Both pages use the same query: 
Ex: {searchTerms} RefinableString00:{Page.udfCategory.Label}

2- Both pages are set with a different value in udfCategory page attribute.

3- In both pages, put a quick links web part that refers both pages

4- Access page one. Search will return items base on the page property. 

5- In the page, quick on the link to second page. The page header will be page 2 but the search results will not change (results of page 1). Clicking a second time on the link of the current page will reload the search result correctly.

Note: If writing the filter value in each page instead of using the page attribute, the results refresh correctly.

**Expected behavior**

Search results should refresh and return results based on the page attribute

**Desktop (please complete the following information):**
 - Chrome, Edge Chromium

**Additional context**

**Comment by wobba** [comment]
Can you add `data-interception="off"` to the <a> tag you use to navigate between pages? That will disable the smart router navigation and should be a workaround.

**Comment by coupalm** [comment]
Hi Mikael,

My navigation for switching pages is also based the search results. I'm using the "Tile" layout. 

Is there a way to pass this information to the pnp-document-card ? 

I tried another template where I could add this attribute to the link and it seems to be fixing the issue.

I don't understand the logic of this smart router as some links were refreshing correctly and others not... 

Thanks for your quick response!

**Comment by coupalm** [comment]
I've created a new template for my navigation and used the data-interception="off" and my search result web part is refreshing everytime.

Thanks you very much for your help!

Martin.

**Comment by coupalm** [comment]
Just a last obervation: I still don't understand why hard coding the search criteria value instead of using  the {Page.udfCategory.Label} in my query was working correctly (re-executing the search result query when navigating)... Is it because the query sentence was always the same using the page parameter (before dynamically changing the value on execution) and this is why it was not reloading data?

**Comment by wobba** [comment]
We need to do work to properly pick up that a router navigation has happened which is the default navigation in SharePoint to provide quicker page loads. If you do a "real" browser navigation, everything on the page is re-loaded which ensures any page load logic runs, but at the cost of possible browser flicker and more loading.

**Comment by wobba** [comment]
I believe this will be solved with #394
