### ISSUE TITLE
Shortcut URL for .url filetypes errors when .url file is in OneDrive

### ISSUE THREAD

**Issue by rdicicco** [microsoft-search/pnp-modern-search#1121]
**Version used**
3.20

**Describe the bug**
If search results include a .url file that is in OneDrive, the following Error is shown and search results will not load:
_Error: Error making HttpClient request in queryable [403] Forbidden ::> {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Attempted to perform an unauthorized operation."}}}_
In the network tab, the error occurs on the following api call:
https://{tenant}-my.sharepoint.com/personal/{user id}/_api/web/getFileByServerRelativeUrl('/personal/{user id}/Documents/{url file name}.url')/$value

**To Reproduce**
1. Go to your OneDrive
2. Click on "New" > "Link" and create a link in your OneDrive to a file that exists in a SharePoint site.
3. Wait for search crawl, then search for your .url file
4. See error described above.

**Expected behavior**
If the .url file is NOT in OneDrive, but in a SharePoint site, the search result shows some text from the .url file in the Search Result and there is no error.

**Screenshots**
![image](https://user-images.githubusercontent.com/49653021/124049583-08df1b00-d9d6-11eb-820a-b21a75b52e3c.png)

**Desktop (please complete the following information):**
 - Browser: Reproducible in Chrome and Edge

**Comment by wobba** [comment]
There is no easy way to solve this as ODB is on a different domain and we don't have an access token available for the ODB host. The same issue appears for multi-geo tenants if you get results from a geo outside of where the search parts are hosted.

I'll tag this as an enhancement to at least provide a better description when the error happens.

**Comment by rdicicco** [comment]
It looks like the error is thrown in this function.  
![image](https://user-images.githubusercontent.com/49653021/124139479-e20bfd80-da44-11eb-9bc4-558e4e9c3fff.png)

Maybe it would be better to determine if the file is in ODB and just bypass this instead? I can submit a PR for what I've put in as a fix for my users if it would help.

**Comment by wobba** [comment]
If you do a fix, add a check to line 816. Something like this:

`&& result.SPSiteUrl.indexOf(window.location.host) !== -1`

That ensures you have a valid token for the domain.

**Comment by wobba** [comment]
Fixed with #1138
