### ISSUE TITLE
Select All and Download Search Results

### ISSUE THREAD

**Issue by mellolr1** [microsoft-search/pnp-modern-search#1122]
**Is your feature request related to a problem? Please describe.**
Have to be able to select multiple results and download.

**Describe the solution you'd like**
Search results with an option to allow multiple files being selected and downloaded.  As in a document library where after a search we can select all files and download them as zip. 
![image](https://user-images.githubusercontent.com/30582791/124169820-ae48cc00-da74-11eb-9611-2c31828c0ea7.png)

**Describe alternatives you've considered**
Tried using search within the document library to download files. Because this document library exceeds the 5,000 item view threshold it's search results are capped at 60 items. So we can't use select/download from the library view. Also tried using different views to filter the results but the filters break the view due to the 5,000 limit.

**Additional context**
This document library has near 40,000 items. Result sets may have a couple hundred files that would need to be downloaded and sent to a third party. This used to be in a file share with it's metadata in Access and was recently moved to SPO with modern search. I tried following the extensibility documentation, but haven't found a complete sample that I could take apart yet.

**Comment by FranckyC** [comment]
Hi @mellolr1, I understand your use case but this is not really in the scope on these Web Parts and  be unlikely implemented in the future to be honest. It seems what you're looking for is more the [Microsoft 365 Content Search feature](https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search?view=o365-worldwide) allowing KQL search with results export, just want you need.

**Comment by mellolr1** [comment]
Hey @FranckyC, would regular users be able to access it or would they have to have either administrator, compliance officer, or eDiscovery manager access? That level of access is restricted to a few individuals and their group would not be ok doing these searches and downloads as often as we need.
Do you know of any complete examples of extensibility components available?

**Comment by FranckyC** [comment]
This feature is reserved to administrators for compliance purposes. Also there is no extensibility components you can use tho achieve that with these Web Parts. This a change that has to made on the core logic and like I said, this is not really the priority list for now.

**Comment by wobba** [comment]
@mellolr1 Selecting a lot of files to zip and download without a server side component is not easily done. If you are to download more than 60 files, then what is the usecase? Maybe a better solution is to set up sync on the library with OneDrive. Then you can download all the files you need at demand with selective sync.
