### ISSUE TITLE
Data source field is empty while editing result types for Pnp Search Results webpart

### ISSUE THREAD

**Issue by shridha21** [microsoft-search/pnp-modern-search#1124]
**Version used**
Version: 4.2.3

**Describe the bug**
Data source field is empty while editing result types for Search Results webpart, when there are more than one Search Results webpart and are marked to show under different Verticle tabs. So the Search Results webpart which shows under the first vertical tab, works fine. But for other Search Results webparts under other tabs Edit Result Type Data Source field is empty.

**To Reproduce**
1. Create a page and add Search Results webpart and configure it fetch Search results. (lets call this webpart SR1)
2. Make sure all properties on which you want to filter in Edit result types are selected in Search Results Selected Properties.
3. Click on edit Result types and Data source Field has values to select.
4. Similarly add a new Search Results webpart and configure it to show search results (lets call this webpart SR2). Datasource in Edit Result types has values under Data source field
5. Now add a Search Vertical webpart on the page. Add 2 tabs. Add Webpart SR1 under 1st tab and webpart SR2 under second tab.
6. Edit Result Type on webpart SR1, data source filed still has values.
7. Edit Result types for Webpart SR2 and Datasource field is empty, no values in the picker, nor it allows to type in the property name.
8. Now swap the webpart under the vertical tabs. Bring webpart SR1 under tab 2 and webpart SR2 under tab 1.
9. Edit Result Type on SR 2 webpart which is now under tab 1. The data source field now has a drop down to pick up values, but empty for webpart SR1
 

**Expected behavior**
No matter which vertical a webpart is in , it should allow Edit Result type Data source to have values in the picker.

**Screenshots**
Screenshots refer files in this order 1.png, 2.png, 3.png

**Desktop (please complete the following information):**
 - Browser [Chrome, Edge]

**Additional context**
![2](https://user-images.githubusercontent.com/46351822/124327345-e4aa4800-db55-11eb-94b6-b0ac405998d7.png)
![3](https://user-images.githubusercontent.com/46351822/124327350-e4aa4800-db55-11eb-938e-e7673de3a570.png)
![1](https://user-images.githubusercontent.com/46351822/124327353-e542de80-db55-11eb-8861-9e1dfd4d47ef.png)

**Comment by shridha21** [comment]
Please close #1123, while trying upload the files, everything got overwritten.

**Comment by shridha21** [comment]
![2](https://user-images.githubusercontent.com/46351822/124327734-5a161880-db56-11eb-9989-2a9eaba8f42a.png)
![3](https://user-images.githubusercontent.com/46351822/124327736-5aaeaf00-db56-11eb-8d91-eef8087a7aa8.png)
![1](https://user-images.githubusercontent.com/46351822/124327737-5aaeaf00-db56-11eb-8f9b-10dd8e505e00.png)

**Comment by wobba** [comment]
@shridha21 you can close issues yourself as well :) Or even edit them. Can you try the dev branch? as there's been a fix which could relate to this one.

**Comment by FranckyC** [comment]
Hi @shridha21, this should be fixed in the `develop` branch and available in the next release. Thanks!

**Comment by shridha21** [comment]
When is the next release expected to come out.
