### ISSUE TITLE
"Enable query rules" throwing HTTP 500 - Internal Server error.

### ISSUE THREAD

**Issue by ManuhinSPalath** [microsoft-search/pnp-modern-search#1125]
Hi Team,

When setting "Enable query rules" to true, it throws HTTP 500 - Internal Server error. Also unable to implement promoted results without setting "Enable query rules" to true.

Any fix for this issue?

Thanks.

**Comment by wobba** [comment]
Please use the bug template, or we will have to close the issue.

**Comment by ManuhinSPalath** [comment]
List layout is showing promoted results when setting "Enable query rules" to TRUE. 

But setting "Enable query rules" to TRUE throwing below error (HTTP 500 - Internal Server error) in search results web part:

![image](https://user-images.githubusercontent.com/43960039/124545468-b1620480-de46-11eb-954d-e31a9867543f.png)

Is there any way to get promoted results without setting "Enable query rules" to TRUE or any fix for this error?

**Comment by wobba** [comment]
Promoted results are query rules, so yes, you have to enable that. Don't really see how you can get promoted results and an error at the same time when you enable query rules. Closing the issue as you failed to use the bug template to provide full information even after I asked for it.
