### ISSUE TITLE
Search Result Webpart:  Use @microsoft/mgt-spfx instead of @microsoft/mgt/

### ISSUE THREAD

**Issue by MarcoSPDeveloper** [microsoft-search/pnp-modern-search#1127]
**Version used**
4.2.3

**Question**
Why you are using @microsoft/mgt/ instead of @microsoft/mgt-spfx package when it comes to loading the Graph components in Search Results webpart?

I think the mgt-spfx package makes more sense for SharePoint development.
https://docs.microsoft.com/en-us/graph/toolkit/get-started/mgt-spfx

**Screenshots**
For testing purposes i have change the reference in SearchResultsWebpart.ts without any issues:
![image](https://user-images.githubusercontent.com/61829528/124560916-9b9c1180-de3d-11eb-8a37-95bcd03e318c.png)

**Additional context**
The background of this question is: There are some problems with the current implementation when it comes to multiple components from registering their own set of Microsoft Graph Toolkit components on the page. Also in connection with SharePoints partial page load. See this Bug [here ](https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/229) for more details. This Bug happens also for pnp-modern-search result webparts

**Comment by wobba** [comment]
Because that the spfx version was not released when we added support for mgt. Feel free to PR a change :)

**Comment by wobba** [comment]
Updated and fixed the persona template which was not using the right parameter to query for the person.

**Comment by wobba** [comment]
Reverting as using mgt-spfx with webpackchunk fails.
