### ISSUE TITLE
Missing "Show All" in Filters

### ISSUE THREAD

**Issue by mkau97** [microsoft-search/pnp-modern-search#1128]
Version used 4.2.3

Hello

We have filters in use. These can have more than 20 entries (for example Filetype). It is possible to limit the number to five. However, is it also possible to display the first five and then get an "expand all" button? Or, if not available, could this feature be added in another version?

Thanks for the help :)

**Comment by wobba** [comment]
![image](https://user-images.githubusercontent.com/51104/124653612-cc139800-de9d-11eb-9943-ffdd22a03c31.png)
You can fill in how many values you want returned in the filter configuration. We don't have a current UX option to limit how many are shown, but you might can create a custom filter template and add the logic yourself using handlebars.

![image](https://user-images.githubusercontent.com/51104/124653809-0b41e900-de9e-11eb-9b0c-bf2a3597e5d3.png)
