### ISSUE TITLE
Document Library Enterprise Keywords Tags Show GUID in Name

### ISSUE THREAD

**Issue by chasquad** [microsoft-search/pnp-modern-search#1129]
**Version used**
Ex: 4.2

**Describe the bug**
When using the PnP Search Filters Web Part with a Document Library that is using Enterprise Keywords, the GUID in the "name" field for the keywords shows up just before each tag name (ass seen in the attached image.  

Wondering if this is a bug or if there is a better way to do this to not have the GUID display in the Filter panel.

**To Reproduce**
1. Add Tags filter option to the PnP Search Filters Web Part as checkboxes
2. View the filters and see that there is a GUID in front of the actual tag name (see image)

**Expected behavior**
Just the tag names should be displayed.

**Screenshots**
![ziggy](https://user-images.githubusercontent.com/48724701/124628780-6f38c300-de46-11eb-8fad-aa8767a65c34.JPG)

**Desktop (please complete the following information):**
 - Browser Chrome
 - 
**Additional context**
Thanks!

**Comment by wobba** [comment]
Did you enable localization in SharePoint provider? https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/#source-configuration

**Comment by chasquad** [comment]
Perfect! Thank you!  It was a simply on/off for the enable localization!

**Comment by chasquad** [comment]
Also, is there a place where I can just ask questions?  These are not bugs!

**Comment by wobba** [comment]
We have three issue templates - pick the one for question :)
![image](https://user-images.githubusercontent.com/51104/124768921-5957fa80-df39-11eb-93ac-c9a9ab25f4ec.png)

**Comment by chasquad** [comment]
Thanks

**Comment by FelloSimon** [comment]
Hello, 

I want to display the tags on the card views as well but by doing so (through "manage card fields", the entire internal name stays visible. 

![image](https://github.com/microsoft-search/pnp-modern-search/assets/172600347/e3d5ab86-5111-41ef-ae1b-6fc73a199f2c)

Does someone has any idea what handle bar or setting I have to configure to only the part after "|" appear? Tags on the first card should be "Marketing" and "Policy". Tags of the second card should be "Projects" and "Policy". Tags of the third card should be "Projects" and "Policy".

Thanks

**Comment by kasperbolarsen** [comment]
You are commenting on a closed case. Please create a new issue or question
