### ISSUE TITLE
Bug with search Filters webpart

### ISSUE THREAD

**Issue by BobRouleur** [microsoft-search/pnp-modern-search#1133]
**Version used**
4.2.3

**Describe the bug**
None of the layouts seem to work. The template filter is always empty. Even if I modify the template manually, nothing is kept when saving.  As a result, the webpart does not work at all.

![image](https://user-images.githubusercontent.com/7772076/124667837-f7868a80-de7d-11eb-81c1-1cda967cda0a.png)

**Steps to reproduce**
Add a Search Results Web Part and Search Filters WebPart in a page.  Go to the configuration of Search Filters Webart, the filter template is empty.

**Comment by wobba** [comment]
Cannot reproduce so you need to provide a bit more on your setup. Which parts, what refiners, how have you connected the web parts, which datasource are you using?

Steps:
* New page
* Add result wp (no config)
* Add filter wp (no config)
* Navigate on filter wp to config screen 2
* Pick "Custom"
* Save page
* Refresh
* Config is still there

**Comment by BobRouleur** [comment]
Hi,  I follow your steps and config is not still there after saving the page. and refresh.

![image](https://user-images.githubusercontent.com/7772076/124795026-a4641480-df1d-11eb-830c-cf7412dc0f6a.png)
![image](https://user-images.githubusercontent.com/7772076/124795079-b0e86d00-df1d-11eb-8843-49480f583ad1.png)

It's a fresh new installation of PnP Modern Search v 4.2.3, not updated from a older version like 4.1

If I remove completely the version 4.2.3 and install the version 4.1, I don't have this bug.

I use Chrome like browser.

**Comment by wobba** [comment]
Are you able to build the dev branch and test?

**Comment by JonoSuave** [comment]
Same issue. My first panel is using data from my search results web part on the same page. For simplicity, my only Customize filters slot is on the search filters is Created. My search results web part currently only returns two site collections as results.

**Comment by wobba** [comment]
@BobRouleur does @JonoSuave 's comment solve your issue?
