### ISSUE TITLE
Managed Properties not displaying in Search Result webpart

### ISSUE THREAD

**Issue by Viipiin** [microsoft-search/pnp-modern-search#1134]
**Version used**
Ex: 4.2

**Question**
Hi team,
I am using PnP Search solution for one of my requirement where I am displaying result based on Search term.
I have added 1 Vertical webpart,1 Search box and 3 Search results webparts where I need to display my result based on search term.
I have added 2 managed properties in Layout slots in all three search result webparts and using that in Edit Results Template.
I am able to see those managed properties in first search result webpart but not able to see those managed properties in other two webparts.
I don't know what I am doing wrong.Can anyone help in that? I am using Modern experience.

**Screenshots**
![image](https://user-images.githubusercontent.com/9314627/124760447-6206fb80-df4e-11eb-83ab-abfc38fcccdc.png)

![image](https://user-images.githubusercontent.com/9314627/124760610-895dc880-df4e-11eb-9c3b-7486bb9be0c6.png)

**Comment by wobba** [comment]
Have you added the mp's to the list of mp's to be fetched as well as in the slots?
![image](https://user-images.githubusercontent.com/51104/124768429-f1091900-df38-11eb-8f8d-e11137e8c69a.png)

**Comment by Viipiin** [comment]
> Have you added the mp's to the list of mp's to be fetched as well as in the slots?
> ![image](https://user-images.githubusercontent.com/51104/124768429-f1091900-df38-11eb-8f8d-e11137e8c69a.png)

Thanks.that helped.
Now I need to format date only ? Any workaround

**Comment by wobba** [comment]
Check `getDate` - all in the docs :) https://microsoft-search.github.io/pnp-modern-search/extensibility/templating/#handlebars-helpers
