### ISSUE TITLE
Empty Search Results Before Keyword Searching

### ISSUE THREAD

**Issue by chasquad** [microsoft-search/pnp-modern-search#1135]
**Version used**
Ex: 4.2

**Question**
I have the setting turned on to hide the Web Part if it is empty.  However when someone visits the search page they see all documents before they have even put in a search keyword.  Is there a way to have the search results be empty  until they have entered a keyword and searched?

**Screenshots**
![searchquestion](https://user-images.githubusercontent.com/48724701/124770181-bc2ca000-deff-11eb-9332-d830be086197.JPG)

**Additional context**
Thanks so very much!

**Comment by wobba** [comment]
Ensure you have no wildcards in the query template.
![image](https://user-images.githubusercontent.com/51104/124785252-ff5e3180-df46-11eb-8368-a7a21c0f431a.png)

Ensure this is unchecked
![image](https://user-images.githubusercontent.com/51104/124785321-0d13b700-df47-11eb-8fae-daf996472a04.png)
