### ISSUE TITLE
"NOT" or "AND NOT" do not working

### ISSUE THREAD

**Issue by tomobak** [microsoft-search/pnp-modern-search#1136]
**Version used**
3.19.2
**Describe the bug**
Standard search Boolean Operators do not seem working.  When I did "Automotive NOT BMW" in search box, the results were documents contains "Automotive", "not" and "BMW".  Similarly "AND NOT" does not seem working neither. 

**To Reproduce**
1. Type "Automotive NOT BMW" in Search Box
2. The results were documents contains "Automotive", "not" and "BMW".

**Expected behavior**
The results documents contains word "Automotive" but not "BMW".

**Screenshots**
![image](https://user-images.githubusercontent.com/43676417/124799445-8c42c400-df22-11eb-9379-d186f9b271e4.png)

**Desktop (please complete the following information):**
 - Browser - Chrome

**Additional context**

**Comment by wobba** [comment]
Cannot repro. You should test the same query in OOB search. If you see the same issue, then report an issue with your tenant as it's not web part related, but API related.

**Comment by tomobak** [comment]
I tested OOB search results page and it worked as standard Boolean operator.  Just this PnP Modern Webpart does not work....

**Comment by wobba** [comment]
Ack as a bug.

**Comment by tomobak** [comment]
Forgot to mention... 
"Automotive -BMW" (minus '-' as 'NOT') worked. It resulted only documents with "Automotive" not contains "BMW"
Hope this helps!

**Comment by wobba** [comment]
I'll get a fix in for the next release.

**Comment by wobba** [comment]
Will be part of v3.21.0

**Comment by VerlindenEAM** [comment]
Thanks, this fixed the issues we had when using AND OR NOT operator in the query.
