### ISSUE TITLE
Search result web part not handling web links properly

### ISSUE THREAD

**Issue by bkwaz4** [microsoft-search/pnp-modern-search#114]
**Version used**
3.9 (latest)

Expected or Desired Behavior
The url contained in a web link should have the link action mapped to the url field contained in the web link, not the name of the web link with a .url appended onto the end by default.
This prevents the users from creating multiple links to the same source doc but with different names that work in the modern search web part. These links are always downloaded by the browser and you cannot open them.

Observed Behavior
Web link to a document named My web link.pdf that has URL="https://contoso.sharepoint.com/Shared Documents/sourcedoc.pdf"
will have a link named My web link.pdf in a search result with an action of https://contoso.sharepoint.com/My web link.pdf.url"
Clicking on this link downloads the link and the link cannot be opened because it is invalid.

Steps to Reproduce
(Optional) turn on the Document ID service and create links using the document IDs rather than the absolute urls so you can move the source documents around without affecting the links.
Configure the search result web part to display a document library.
Create a different document library for the source documents
Create a document called My web link.pdf in the source document library
Create a web link that uses the url https://contoso.sharepoint.com/sourcelib/My web link.pdf named My web link.pdf
Copy the web link to the target document library
Rename the target library web link to 01 My web link to remove the extension and facilitate sorting
Search for the link using the modern search web part
Click on the search result for the link which will be named 01 My web link
Link is downloaded
Link cannot be opened.

**Comment by FranckyC** [comment]
@wobba you self assigned this. Any update?

**Comment by wobba** [comment]
Haven't had time, and trying to think what my idea was. Feel free to take it.

**Comment by FranckyC** [comment]
Actually I have no solution for now :)

**Comment by wobba** [comment]
There is no good info afaik in the search properties returned from a link, which means we would have to open the file to find the actual url. You can get lucky and get the URL in the` HitHighlightedSummary`, but very shaky logic.

One solution is to have a click hander for .url files which will read the contents of the file, then redirect to it. But I'll leave that as a task for someone to implement as usage of .url files is not that widely used afaik.

@bkwaz4 feel free to PR a solution.
