### ISSUE TITLE
People Directory in Modern Search v4

### ISSUE THREAD

**Issue by szyvett** [microsoft-search/pnp-modern-search#1142]
PnP Modern Search v4 4.2.3.0

Good Afternoon, 

I am wondering if someone could help me with the Modern Search People layout. I am trying to create a People directory with filters and search verticals. I want to filter the results based on Job Title (which was quite straight forward) and Department. I also want to show the "About me" section upon search. I am not sure which properties I could use to get these information.  

At the moment I have the following layout:
![Search](https://user-images.githubusercontent.com/32570227/125087485-6d7c3300-e0c4-11eb-824a-650d7bbc2b3f.PNG)

I want to get the information from the following page:
![Capture](https://user-images.githubusercontent.com/32570227/125087542-7967f500-e0c4-11eb-9a29-fcd2367f87d4.PNG)

I have been trying to use the "AboutMe" managed property in the Search Results, and the "DepartmentId" and "Description", but they all return null.

I tried creating new slots but that hasn't worked either, still only returning "null" (since the slot fields would be the above mentioned ones).

I am hoping that once I have the correct property value, I will be able to display it via the "Manage People Fields" option. 

Thank you for your help in advance.

**Comment by wobba** [comment]
You can use both `AboutMe` and `Description` to get back the "ask about me" data. And ensure you add the property you use to the list of managed properties you want to have returned. If not specified, then it won't be there :) 

You can pick `Description` in the dropdown, or manually input `AboutMe` as it's not listed (not something we control).
![image](https://user-images.githubusercontent.com/51104/125095287-52192400-e0d4-11eb-9888-bb97345abd79.png)


It can take hours after you update before it's available in search.

**Comment by szyvett** [comment]
Thank you @wobba ! It probably hasn't come through yet then! I updated the the information a few hours ago.

**Comment by wobba** [comment]
Department you have to add manually.
Type over what is in the box and hit ENTER - that will add it to the list (not ideal UX, but it's a shared PnP control, and something we want to improve on).

![image](https://user-images.githubusercontent.com/51104/125096576-922cd680-e0d5-11eb-9721-11f3e16265ee.png)

**Comment by szyvett** [comment]
Thank you very much!

**Comment by anoroita** [comment]
Hi @szyvett I'm trying to configure the same people search functionality, can you please help outlining the steps and PNP options you've used
