### ISSUE TITLE
Search result is displaying Even there is no keyword in search box

### ISSUE THREAD

**Issue by Viipiin** [microsoft-search/pnp-modern-search#1143]
Hi Team I have a search result and search box webpart.
when I am using like below ,my result webpart is empty and that is what I am expecting.
![image](https://user-images.githubusercontent.com/9314627/125189699-0ba00280-e257-11eb-9000-00b608a99695.png)

but when I am using query template like this,Results are displayed in webpart
![image](https://user-images.githubusercontent.com/9314627/125189772-6cc7d600-e257-11eb-89a4-7fb4a5697774.png)

I want to search from Site collection only when I type search keyword in search box but that is not happening here.
Also my managed property is not dispalying in correct format it is displaying twice.

Can anyone help me out.

**Comment by wobba** [comment]
You removed important parts of the issue template like what version are you using, how have you set up the web parts etc. That said, the answer is simple. Check the modifiedQuery in the debug template and you'll likely see your query without a keyword is: `Title: path:https://xyz`. 

Take a look at the {?...} syntax which might help you out. Didn't find it in the official docs right now but I mention it in https://www.techmikael.com/2014/05/s15e03-query-variables-constant-trouble.html

**Comment by wobba** [comment]
@Viipiin if this solved your issue, please close it.
