### ISSUE TITLE
Exact keyword return

### ISSUE THREAD

**Issue by sb-sheriff** [microsoft-search/pnp-modern-search#1146]
**Version used**
 4.2.3

**Question**
Hi, how do I configure to return the results by having the exact searched "keywords" only? 
I've tested and researched the current installation produces the same results as the default search from SharePoint, which includes some results that are unexplainable/unreasonable, i.e. including the results that having no keywords within.

Thank you.

**Comment by wobba** [comment]
When you use `{searchTerms}` as the query template it's substituted with whatever comes from the search box, and search for exact as type. If you mean exact phrase, then you can add quotes around it `"{searchTerms}"` but this only works for simple term searches, not if a user starts to add operators like OR/AND/NOT/- etc. By default terms are AND'ed. If I searrch for `foo bar` the query is `foo AND bar`, but the order or where in a file they match is not a factor. `bar foo` would be the the same query.

Does this help?

**Comment by sb-sheriff** [comment]
Hi Wobba,

Can you please clarify on "use {searchTerms} as the query template"? What kind of configuration and documentation you could refer to?

Yes, I meant the exact phrase. And keep asking my users to use the additional quotes around "{searchTerms}" is not so user-friendly per my work environment, and that's why I look for a solution to deliver the search result based on the exact phrase. Indeed, the default search function within SharePoint online does provide so; therefore, I was advised by Microsoft support to utilize this pnp search web part to substitute the default search function.

Thank you for your help!

**Comment by wobba** [comment]
I'm not talking about what the user inputs. If you use the SharePoint provider you have a query template setting where you can add restrictions etc. to the query. This is where you add the quotes. What comes from the search box is substituted into the variable `{searchTerms}`. 

This all comes from the way classic search web parts worked in SharePoint and you should be able to find documentation. I cover query variables in my old post https://www.techmikael.com/2014/05/s15e03-query-variables-constant-trouble.html.

![image](https://user-images.githubusercontent.com/51104/125680980-3f58c73a-887a-40fc-9f46-93292d8d3a2c.png)

**Comment by sb-sheriff** [comment]
Hi,

I've tried to configure the Query template as "{searchTerms}" and it still didn't return the exact phrase. 

And I have been trying to add the filter by following from the reference below:
https://microsoft-search.github.io/pnp-modern-search/scenarios/page-with-filters/
But it seems the page was having an error? :::image type="content" source="assets/page-with-filters/page-layout-with-filters.png" alt-text="Page layout with PnP Filters Web Part":::

What is the "In the image above"?

Thanks!

**Comment by wobba** [comment]
@sympmarc seems image references are wrongly added 🙂

**Comment by wobba** [comment]
@sb-sheriff hard to help without seeing your setup. But quotes around a query is exact phrase. See https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference for docs. If you use the debug template for output and look at the queryModification value you see what the executed query is.

**Comment by sympmarc** [comment]
@wobba Yikes! Sorry about the image issues, @sb-sheriff. I'll get those fixed today. Added issue #1156.

**Comment by sb-sheriff** [comment]
@wobba I'm sorry that I don't see the syntax with regard to the exact phrase on the query template reference you pointed. I only found this one: "SensitiveType:{searchTerms}" and it didn't work. By the way, is {searchTerms} serving as the variable for the general keywords/phrases?   
https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide

Thanks!

**Comment by sb-sheriff** [comment]
@wobba  Any further advice?
Thank you.

**Comment by sb-sheriff** [comment]
@wobba  No answer on the variable for the general include all search terms?

**Comment by wobba** [comment]
`{searchTerms}` will include whatever is put in the searchbox. If you want a multi term query to be targeted against a property as exact phrase then use `"{searchTerms}"` not `{searchTerms}`.

If I query for `foo bar` the query will then be `"foo bar"` as a phrase and not `foo AND bar`. However, if the user adds quotes in the query, then you have an issue as you get double/multiple quotes and the query may fail.

So might be better to teach users that phrase query has to have quotes around it - same as any google query.

**Comment by sb-sheriff** [comment]
Got your point, thank you! If we want to customize to have a checkbox to let users select for the search of the exact results, what kind of customization we should look into? On all three web parts or just could be just customized on the filter portion?

Thanks again.

**Comment by wobba** [comment]
@sb-sheriff I would probably do it in the search box web part, and then pass inn quotes around the query if checked which is then picked up by the result web part. If using the filter web part, items should be exact as to the picked filter.

**Comment by sb-sheriff** [comment]
I've tried the "{searchTerms}" at few spots under the configurations and none of them is working. Please see the screenshot below: 

![image](https://user-images.githubusercontent.com/87348254/127950428-3f5446ae-60dc-4333-b8a4-bd84b0fd54a1.png)

Can you help to verify if the "{searchTerms}" is at the right spot for the query template? The problem now is the results displaying all searchable documents by default without entering keywords. And if I input Refinement filters with "{searchTerms}" then I got nothing to return. What was wrong with the configurations? Wish there was a good example of the configuration under the help document.

**Comment by wobba** [comment]
You should not input anything into the Refinement filters box. You should take a look at the scenario documentation on how to get started with the web parts.

**Comment by sb-sheriff** [comment]
I had tried without the input to the Refinement filters box and I got thousands of documents as the return results even no keyword put in for search yet. Something wrong with taking the "{searchTerms}" at the query template?

**Comment by wobba** [comment]
If all you want is phrase results, then keeping the query template as per your image is the correct thing to do in the result web part. If you don't want results when the search box is blank, then ensure you have no default value in the search box connection.
![image](https://user-images.githubusercontent.com/51104/128730055-2f9b21f5-55c0-45d0-af7a-edae93270aab.png)

**Comment by sb-sheriff** [comment]
I do have the exact same configuration and there is no default value.

![image](https://user-images.githubusercontent.com/87348254/128906395-c88d838f-2170-45d3-be7c-159e9611bb27.png)

**Comment by sympmarc** [comment]
I see the **Use a default value** checkbox in your screenshot. It's in the same place where @wobba highlighted it. Or do you mean something different?

**Comment by sb-sheriff** [comment]
@sympmarc  I meant it is no difference -- I don't have a default value there. 
And even I don't have the default value; I got thousands of results returned across the organization once I set up and connected the filter even keeping blank in the search box.

**Comment by sympmarc** [comment]
Does your **Query template** only have `{searchTerms}` in it?


![image](https://user-images.githubusercontent.com/1295627/128914362-7ff0a7b8-2630-4da1-a26c-4fe79d6f79b6.png)

**Comment by sb-sheriff** [comment]
Yes, it was that way like you have.

**Comment by sympmarc** [comment]
If you only have `{searchTerms}` in the Query template and no default value, then the page should load with no results, unless I'm missing something.

**Comment by sb-sheriff** [comment]
That was when I had the filter set up in between the result and the search box, and followed wobba's idea of changing between {searchTerms} and "{searchTerms}".

**Comment by wobba** [comment]
@sb-sheriff can you export your result wp config and share either here or off-line?

**Comment by sb-sheriff** [comment]
Hi @wobba  I've emailed you the exported settings. 
Updates:
1) After I corrected the field name, I could get the filter showing up now.
2) But I only got "Created" field to show; and all other fields are not show up for the filter.
3) It's searching the results across the organization for all SharePoint websites. I look for the search result within the contents of the local sharepoint website only. 

Thank you!

**Comment by wobba** [comment]
@sb-sheriff You can only get filters for managed properties which are set to be "refinable" as seen in the search schema. https://contoso-admin.sharepoint.com/_layouts/15/searchadmin/ta_listmanagedproperties.aspx?level=tenant

**Comment by sb-sheriff** [comment]
I did look into that "refinable" as well but I found out that the field is dimmed and cannot be changed under the settings. Even I was granted as SP admin and still couldn't access?

**Comment by sympmarc** [comment]
If you read the article @wobba linked to, you can learn how to map Crawled Properties to pre-existing Managed Properties like RefinableString00-30, etc.

**Comment by sb-sheriff** [comment]
Why the location field is "refinable" already and still doesn't show up for the filter?

Btw, the first link was broken: https://contoso-admin.sharepoint.com/_layouts/15/searchadmin/ta_listmanagedproperties.aspx?level=tenant

**Comment by sb-sheriff** [comment]
![image](https://user-images.githubusercontent.com/87348254/129785959-fdf584ee-2103-401e-8e91-18b90cdca40f.png)

**Comment by sb-sheriff** [comment]
![image](https://user-images.githubusercontent.com/87348254/129786176-aac48686-bac7-4d58-a532-7a5873bdd333.png)

**Comment by sb-sheriff** [comment]
![image](https://user-images.githubusercontent.com/87348254/129823320-626a3304-f6c8-4904-91ea-141ee6404bf3.png)

**Comment by sb-sheriff** [comment]
![image](https://user-images.githubusercontent.com/87348254/129823600-b839f2f4-3abd-44b3-872a-8ecbde2f3337.png)

**Comment by sb-sheriff** [comment]
I finally got the refinablestring portion with the help from Microsoft :)

![image](https://user-images.githubusercontent.com/87348254/129823669-8a9e3dca-8022-4a30-b66f-81923a37ea6c.png)

**Comment by sb-sheriff** [comment]
![image](https://user-images.githubusercontent.com/87348254/129823731-f1a10fed-edfc-4e9d-a410-a1ccb44325de.png)

**Comment by sb-sheriff** [comment]
![image](https://user-images.githubusercontent.com/87348254/129823818-5ce49451-b561-44d4-9aba-245e33d95dc9.png)

**Comment by sb-sheriff** [comment]
**But the search filter still only showing for the one filter! please review.**

![image](https://user-images.githubusercontent.com/87348254/129824181-1222c6da-fc85-4457-8fbc-be6ca78e16d4.png)

**Comment by wobba** [comment]
If web parts are connected and the items you are returning have value in them you should see filters. Remember, once map a crawled property to a managed property, the content has to be re-indexed for the value to be populated in search.

Covered in my troubleshooting book 😉

**Comment by sb-sheriff** [comment]
Yes, I had to wait more than 24 hours for the re-indexed to see the new filter populated. But then they are not in the way designed. I'm troubleshooting and where is your troubleshooting book? Thanks.

**Comment by wobba** [comment]
@sb-sheriff https://www.techmikael.com/2019/12/troubleshooting-search-in-sharepoint.html
