### ISSUE TITLE
v3 Functionless ResultSourceId in Verticlas with Synonyms using

### ISSUE THREAD

**Issue by DominikLeitgeb** [microsoft-search/pnp-modern-search#1149]
The use case is to get the right results with a search term and their synonyms.
In my case I'm using the search box, verticals, refiners and result web parts who are connected.

I use a ResultSourceIdentifier with this content:
{searchTerms} AND Path:"https://.../sites/*" AND IsDocument:1 AND RefinableString<>"Nein"

(I tried different ways for the identifier, but always the same results)

The RefinableString contains the strings "Ja", "Nein" or "" (empty)  [no  boolean values]

If I insert a term into the search box I get a result inside the result source, but even not in every way.
I found some inserts that makes the result source id inside the verticals functionless for this search query.

For example:

Serach box insertion:    **moped**
Available synonyms:     **Term: "MO"          Synonyms: "Makler"**  (This synonym has nothing to do with the search term!)

With the result source identifier I should get results with RefinableString:"Ja" or RefinableString:"" (empty)
but I get also results with RefinableString:"Nein".

I checked with the SharePoint Insider the query of the earch:

**(moped) OR ((mo OR makler)ped)**
That's the query of the search I got from the SharePoint Insider Networks.
If I try (mo OR mo) for example, it's the same result, the identifier doesn't work. That means I get also the elements with RefinableString:"Nein".

The search splited the search term into two parts because of the synonyms and thats the reason for the wrong result, I think. The synonym has nothing to do with the search term and makes no sense in this way. I tried different inserts inside the SpahrePoint Insider and this way works, I think:

**((moped) OR ((mo OR makler)ped))**

I get all elements with RefinableString:"Ja" and "" (empty) like it should be.

So my questions:

- Is it correct that the search splits the terms into two pieces because of the synonyms in this way?
- Is it my mistake in any way or is there something wrong with the tranformation of the search query with using the synonyms?

**Comment by wobba** [comment]
Not sure what version you are using but there was a recent fix (#1136) to synonym expansion to match on word bondary, and you can use the debug template and look at the output of `queryModification` to see how the query was expanded with synonyms. I would also put () around `{searchTerms}` to ensure the AND part following is treated correct from a boolean perspective.

**Comment by DominikLeitgeb** [comment]
Thank you so much, the () around the {searchTerms} in the ResultSource works and it looks like the new version solves the problem with the synonyms.
Really nice, thanks for help.
