### ISSUE TITLE
Facing multiple issues with PnP Search webparts

### ISSUE THREAD

**Issue by Viipiin** [microsoft-search/pnp-modern-search#1151]
Hi @wobba ,
I am having problem with my search experience while using PnP Search webparts.
**Version used**
4.2.3.0

**Question**
I am implementing PnP Search experience for one of my project requirement but ended up by multiple issues/feature.

- When clicking on cross icon (remove) in search box, it is not clearing my words from search box .
![image](https://user-images.githubusercontent.com/9314627/125580094-aec9d856-0652-4bea-aadc-788598da9608.png)

- While clicking on cross icon in search box it is clearing results but filter webpart is still visible.
![image](https://user-images.githubusercontent.com/9314627/125580397-deb3a4d2-0bf8-40c0-9546-f6535ab8514f.png)

- I have no filter webpart attached to second search result webpart that is displaying results when I select Archive tab but still filter option from active result webpart is displaying
![image](https://user-images.githubusercontent.com/9314627/125580803-bfa12636-b350-4001-a7bc-48abcacd13fb.png)

- When switching between verticals ,filters are expanding even I have not make that option select in filter webpart.

Please provide insights for this.

**Comment by wobba** [comment]
What you have logged is not a question, but a bug. Please use the correct template. And please don't log multiple issues in the same one. Filters and x of search box are two separate issues.

**Comment by Viipiin** [comment]
Apology. But filter is not disappearing when I switch between verticals (tabs).That's the major problem I have right now.

**Comment by wobba** [comment]
If you connect the filter web part to both result web parts, does that help? 

And which is why the bug an repro steps are so important for triage. So we can easily test it.

Is this correct?

* Two result wp's each configured to a vertical
* One filter wp connected to one result wp
* When displaying results from the non-filter connected wp, the filter is not cleared

**Comment by Viipiin** [comment]
Hi @wobba ,
_Connecting filter web part to both result web parts help me to **solve the issue** but is that how it should be🙄🙄 ?_

Now,

- Two result wp's each configured to a vertical

> Yes two result wp's are connected to single vertical wp that has 2 tabs only.

- One filter wp connected to one result wp

> Yes earlier I have connected only active result wp to filter only but now connecting to both result wp solve the issue but it also confuse me.

- When displaying results from the non-filter connected wp, the filter is not cleared

> Yes

**Comment by wobba** [comment]
Connecting one filter wp to multiple results is for the vertical scenario. If one was connected it could in theory send a message of blank to the filter if it was hidden. At least you have a workaround for now 🙂

**Comment by wobba** [comment]
Clearing of search box on X seems to work fine. When clearing it will not re-query which is expected.
