### ISSUE TITLE
Logical operator in a custom template {{#if}} conditional

### ISSUE THREAD

**Issue by shridha21** [microsoft-search/pnp-modern-search#1154]
Version:  4.2.3

**Question**
How can i use the And OR operators in {{#if}} in custom templates. Is there any block helper available for it.

**Comment by wobba** [comment]
Check the docs for handlebars or handlebars-helpers. Should be docs and tutorials on the web about handlebars. See for example https://github.com/helpers/handlebars-helpers#and

**Comment by shridha21** [comment]
Thank you
