### ISSUE TITLE
Export/Download web part raw properties to have distinct JSON filename

### ISSUE THREAD

**Issue by MarinBuric** [microsoft-search/pnp-modern-search#1155]
When exporting and downloading web part raw properties - all JSON files have the same name which is confusing. 

![image](https://user-images.githubusercontent.com/52964255/125745438-d51b1ac9-69fd-4f01-94c5-70d47462f433.png)

It would be nice if JSON filename would contain web part name -- for example: 
- Search Results_webpartproperties.json
- Search Box_webpartproperties.json

Or, even better: SiteTile_WebPartTitle_webpartproperties.json

Thank you!
Marin

**Comment by wobba** [comment]
This is a PnP reusable control outside our control. It is what it is 🙂
