### ISSUE TITLE
Images incorrectly added to scenario articles

### ISSUE THREAD

**Issue by sympmarc** [microsoft-search/pnp-modern-search#1156]
Documentation issue with images in the scenario docs. Example:

https://microsoft-search.github.io/pnp-modern-search/scenarios/page-with-filters/
But it seems the page was having an error? :::image type="content" source="assets/page-with-filters/page-layout-with-filters.png" alt-text="Page layout with PnP Filters Web Part":::

Mentioned in #1146 

Please assign to me.

**Comment by sb-sheriff** [comment]
@sympmarc  It says fixed but still the same? https://microsoft-search.github.io/pnp-modern-search/scenarios/page-with-filters/

**Comment by sympmarc** [comment]
I submitted the fix, but it looks like they haven't published yet.

**Comment by FranckyC** [comment]
Published and online. I close this one
