### ISSUE TITLE
Use an external template URL

### ISSUE THREAD

**Issue by CMREDD** [microsoft-search/pnp-modern-search#1160]
1. How can I  "Use an external template URL" in pnp modern search result WebPart for custom layout?
2. where can I find it? what is this?
3. I am working for pnp modern search WebPart V4

![Use external template](https://user-images.githubusercontent.com/50401427/125962988-5509954d-c2d6-49cb-945e-3d739796e8a8.PNG)

**Comment by FranckyC** [comment]
Hi @CMREDD, please follow the template when creating a new issue or question. This is not the first time. Next time, the issue will be closed directly.

Also, you could find all the necessary information in the documentation. A quick search would have helped before asking this question...

![image](https://user-images.githubusercontent.com/5659122/126354067-e37c237b-5c94-4b27-9c25-ecb845cae66f.png)

Anyway, a complete scenario is available also here https://microsoft-search.github.io/pnp-modern-search/scenarios/howto-store-custom-templates-in-sharepoint/
