### ISSUE TITLE
Managed and  mapped crawled properties

### ISSUE THREAD

**Issue by CMREDD** [microsoft-search/pnp-modern-search#1161]
Hi Folks,

1. What is Managed Properties, How can I create it?
2. What is crawled properties, How it will mapped to managed property.

I have a Doc Library in that choice column(Phase), How can I create managed property for choice field, What is the mapped crawled properties.
 Kindly let me know anybody the creation process

**Comment by Viipiin** [comment]
simple short answer is read MS Docs about search.
But for you 
Go to SharePoint admin center(Online).Check for Search there and than go to manage search schema and you will get everything that you need to know.

https://<sitecollection>-admin.sharepoint.com/_layouts/15/searchadmin/ta_listmanagedproperties.aspx?level=tenant

[Search Docs](https://docs.microsoft.com/en-us/sharepoint/get-started-with-modern-search-experience)

**Comment by FranckyC** [comment]
Hi @CMREDD, as @Viipiin is suggesting, you should see the Microsoft documentation for this part as it is not directly related to this solution. I close it for now.
