### ISSUE TITLE
PnP Webpart result sorting is different from OOB modern search results due to PersonalScore field

### ISSUE THREAD

**Issue by nowshad-m** [microsoft-search/pnp-modern-search#1164]
**Version used**
3 and 4

**Question**
The PnP webpart always uses Rank by default for sorting. When we compare the results with OOB modern search results, its bit different. For example, some of the PDF documents are listed high in the order in PnP webpart, but all the word documents are listed high in the order in OOB results.

**Additional context**
Analyzed the query a bit more and figured that OOB search query is using a sort field called 'PersonalScore' (not Rank), so just checking if there is a possibility of using PersonalScore column in PnP webpart. This field is not available in crawled properties, so assuming its internally managed by Microsoft.

Any help with understanding the usage of PersonalScore would be a great help

Thanks,
Nowshad

**Comment by FranckyC** [comment]
Hi @nowshad-m , more a question for @wobba as I don't know this property.

**Comment by wobba** [comment]
Using the SharePoint provider you cannot get the same rank as OOB Microsoft Search. You can get that by using the Graph provider in v4. Which is why OOB and newer API's are the way to go ;)
