### ISSUE TITLE
Search Filters - Combo-box multi-values, filter by text prevents selection of options

### ISSUE THREAD

**Issue by willhaywood** [microsoft-search/pnp-modern-search#1165]
**Version:**
v: 4.2.3

**Bug:**
When typing text into a combo box filters with multi-values, you are unable to select the value

**Steps to reproduce the behaviour:**
1. Search for item with filterable values
2. Activate a search filter of type multi-select combo-box
3. Type to refine values
4. Select value value following refinement
5. Combo-box reloads, without having selected or applied the filter value

**Expected behaviour**
Selecting a refiner within a combo-box select list should activate the refiner.

**Screenshots**
Filter Setup:
![image](https://user-images.githubusercontent.com/5337029/126101742-9bc941a7-d4a9-4f38-9dfa-394b2cff3e06.png)
Filter Activation:
![image](https://user-images.githubusercontent.com/5337029/126101802-a831e5c4-4220-484d-b745-e327861fa26c.png)
Filter Refinement:
![image](https://user-images.githubusercontent.com/5337029/126101837-adb4123d-6a98-434e-9968-87aeef69ca70.png)
Selected Refiner: Select list reloads and does not select value:
![image](https://user-images.githubusercontent.com/5337029/126101858-07952f7d-6d3b-4dcf-9e6a-9f4c7484bbaa.png)

**Desktop (please complete the following information):**
 - Browser: Chrome 91

**Comment by FranckyC** [comment]
Hi @willhaywood. It is now resolved in the `develop` branch. Thank you for flagging this issue.
