### ISSUE TITLE
Hi Team, I am trying to reuse this solution on SharePoint 2019 on-premises. But we are not able to use on the same. The package deployment failed. Also after deployment it is giving same manifest error as per opened in earlier threads. Can you please confirm if this solution can be used in SharePoint 2019? 

### ISSUE THREAD

**Issue by DeveshRV** [microsoft-search/pnp-modern-search#1166]
### Issues related to data mapping, e.g. SharePoint columns to crawled properties to managed properties, will be closed by default and should be asked elsewhere as it's outside the scope of this project. However if you cannot repro the issue with classic web parts, then it's ok as it relates to these web parts 🙂

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
Ex: 4.2

**Describe the bug**
A clear and concise description of what the bug is. Keep questions and bugs related to the web parts. If the issue relates to KQL or question around crawled and managed properties please use [Microsoft TechCommunity](https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev). Which means, if you experience the same behavior in classic web parts, then it's not an issue with PnP Modern Search 😉

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by FranckyC** [comment]
Hi @DeveshRV , this solution is not compatible with SharePoint 2019.

**Comment by DeveshRV** [comment]
Hi Franky.. Thanks for your update. Can you please help if there is any alternative available for this environment. We will appreciate if you could share any inventory data available.

**Comment by wobba** [comment]
@DeveshRV search the issue list and you can find some reference to someones fork for 2019.
