### ISSUE TITLE
 Customize custom cards properties 

### ISSUE THREAD

**Issue by CMREDD** [microsoft-search/pnp-modern-search#1169]
Hi Folks,

I am working for pnp modern search WebPart V4,
In the search result WebPart there is a layouts like (Detail list , list, slider, Debug, Cards, People, Custom)
I have to implement "custom" cards layout (with code).
Kindly let me know where can i implement the code for this template.

Cards values:
Title
URL
Date
Preview Image URL
Location
Date
Tags
Author
Is Folder
File Extension

My work is have to implement same as for custom card.
Can any body assist me code at least one value of the card.
Please find the attachment
![Cards](https://user-images.githubusercontent.com/50401427/126340450-e183c5d1-6bd7-4e90-ad75-a2ce9a614943.PNG)

**Comment by FranckyC** [comment]
Hi @CMREDD, instead of creating a custom template, you could just customize the card fields the way you want. Does that option work for you?

![image](https://user-images.githubusercontent.com/5659122/126350775-1b4df948-3ef9-4afd-a617-2bfe7b2fc78f.png)

**Comment by CMREDD** [comment]
Hi Francky,

I am not familiar with this whether custom template will work or not, My supervisor asking custom template to implement for search result WebPart,
Kindly let me know it will possible or not?
if possible, what code can i implement to show custom cards on search results WebPart for this? 

Can you let me know steps first how to read doc library path code and how to implement cards code for search results WebPart 
kindly provide at least  or 2 examples.

Regards
Maheswar

**Comment by FranckyC** [comment]
You can definitely create custom templates with this solution. Customization options all detailled in the documentation https://microsoft-search.github.io/pnp-modern-search/extensibility/. Did you even read this part before asking? I seriously doubt....

To customize cards, you have 3 options:
1. Use default "Cards" layout and configure card fields like described here https://microsoft-search.github.io/pnp-modern-search/usage/search-results/layouts/#cards
2. Use a the "Custom" layout and the `<pnp-documentcard>` web component with custom values:  https://microsoft-search.github.io/pnp-modern-search/extensibility/web_components_list/#pnp-documentcard
3. If the two options above are not suitable, create you own web component leveraging the Office UI Fluent document card React component https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_web_component/

**Comment by Ofer-Gal** [comment]
@FranckyC I am using for author the same handlebar as you show here `{{slot item @root.slots.Author}}` but I need to show it as an added column in "Details List" 
In Manage columns I added column 4 "Author" and Use Handlebars expression "{{slot item @root.slots.Author}}" but it shows "OGal@ecgmc.com | Gal, Ofer | 693A302...." 
So I found somewhere  `{{#with (split (slot item @root.slots.author) '|')}}                    {{[1]}}    {{/with}}`
But then Nothing Shows

A better solution would be the  <mgt-person> but Your example is just for people search.
So It tried  `<mgt-person person-query="{{slot item @root.slots.Author}}" view="twoLines"></mgt-person>` but I get just the Head Icon
Any advice?
Thanks
