### ISSUE TITLE
"Something went wrong" Errors

### ISSUE THREAD

**Issue by chasquad** [microsoft-search/pnp-modern-search#1170]
**Version used**
Ex: 4.2

**Question**
I finally got my search filters, results ,etc. all working!  But now when I sent the link to the page with the search results on it to another Site Owner, they get a "Something went wrong" error for each of the PNP Search web parts (box, filter and results).

**Screenshots**
<img width="923" alt="searchpartserrors" src="https://user-images.githubusercontent.com/48724701/126343914-18794428-0d11-4a57-8b29-80c08307d7f6.png">

**Additional context**
I can still see and use the PNP Search Web parts but no one else can (even site owners).  Any help would be appreciated.

**Comment by FranckyC** [comment]
Hi @chasquad, did you use the package from this repository or did you built a custom one? Also, can you tell us what is the error message you get when clicking on "Technical details". Also:

- Did you deploy in a site collection or global app catalog?
- Are users externals?
- Did you build a custom package with a custom CDN?

Thanks!

**Comment by Lee-StreetCrane** [comment]
Hi @FranckyC  ,

Just to add to this point raised by @chasquad. I have just had the same issue reported by some of our users. 

A couple of things I've noticed:

1. Clicking technical details: ![image](https://user-images.githubusercontent.com/82372715/126476112-ef0b8a74-8f7f-4d55-8625-69fa20b9c72a.png)
2. These errors only seem to appear if a user is using explorer 11 or Edge.    Chrome, Edge Chromium and Firefox seem to work ok and as expected, at least in my tests.

I hope this info might help.

Thanks,

Lee

**Comment by FranckyC** [comment]
Thanks @Lee-StreetCrane , for IE11, this browser is not supported so it explains. Does this error appear for all web parts or just a particular one?

Did you try to open the page in a private window? Are you using the latest version as well?

**Comment by Lee-StreetCrane** [comment]
Hi @FranckyC 

I thought that might be the case with IE11.   I had it appearing on the webparts I was using on our search page, just tried adding the other and the error is appearing on all of them. 

I've just tested it with a couple of our users and we still get the error message using an InPrivate window in the standard version of Edge.

I'm using 4.2, but just realised 4.3 has been released.  Should I give that a try?

**Comment by FranckyC** [comment]
@Lee-StreetCrane if an upgrade to 4.3 is ok for you, you can give it a try. You can also test using global tenant app catalog and site collection app catalog to see if there is any differences.

**Comment by chasquad** [comment]
Same user, works fine in Chrome but not in Edge (Chromium).  Is there some compatibility setting in Edge (Chromium) that could be set?  I'm having our Help Desk take this issue over since it doesn't appear to be an issue on the SP end.  Thanks Everyone!
