### ISSUE TITLE
SPLoaderError.loadComponentError

### ISSUE THREAD

**Issue by xLucipher** [microsoft-search/pnp-modern-search#1171]
Hello guys,

i've tried to deploy the pnp-modern-search-parts-v4.sppkg but i've got this error when using it as webpart:

> [SPLoaderError.loadComponentError]:
> Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Failed to load URL 'https://...sharepoint.com/sites/...appcatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/CommonStrings_en-us_1450f51a76900c0a848f1608cd3a8462.js' for resource 'CommonStrings' in component '544c1372-7e5a-49ec-8db6-812f76c375f2' (pnpSearchBoxWebPart). The file was not found in the server.
> 
> INNERERROR:
> Failed to load URL 'https://...sharepoint.com/sites/...appcatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/CommonStrings_en-us_1450f51a76900c0a848f1608cd3a8462.js' for resource 'CommonStrings' in component '544c1372-7e5a-49ec-8db6-812f76c375f2' (pnpSearchBoxWebPart). The file was not found in the server.
> CALLSTACK:
> Error
>     at t [as constructor] (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_c95f6684fe547a50b6b522f096c976ff.js:65:19844)
>     at new t (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_c95f6684fe547a50b6b522f096c976ff.js:65:169760)
>     at Function.e.buildErrorWithVerboseLog (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_c95f6684fe547a50b6b522f096c976ff.js:65:207199)
>     at Function.e.buildLoadComponentError (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_c95f6684fe547a50b6b522f096c976ff.js:65:203244)
>     at https://modernb.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_de-de_dbaf73e391f98dcbc776.js:1:11895
> 

I am the owner of the page on which the web part is to be used and admin on the app catalog.
"The file was not found in the server." how is this possible? 
I can also see and add the web part on the Sharepoint page, then the file cannot be "missing" or "not found"?
I use modern Sharepoint in case that should matter.

**Version used**

- newest v4
- tested it with v3 also

**To Reproduce**
1. Go to your App-Catalog
2. Click on the +
3. Choose the package and upload it - deployed to all websites (tested without also)
4. Go to the sharepoint page of your choice and add the web part
5. See Error

**Expected behavior**

- There should be the Search Box? Don't know what you expect what i would write here

**Desktop (please complete the following information):**
 - Browser [chrome | opera | firefox | edge]

**Comment by wobba** [comment]
Try to delete and re-add the sppkg in your app catalog and see if that helps. I see you are running without CDN enabled, and suggest you enable that for perf reasons in a prod environment (not related to your issue, but a good practice).

You say you tested with v3 as well....did that work or same error?

**Comment by xLucipher** [comment]
Thank you for your quick response.
Yes, I also tested with v3. I got the same error there. Re-adding didn't help.

Other suggestions?

**Comment by wobba** [comment]
Can you try the June versions?

**Comment by xLucipher** [comment]
Same Error.
Tested v.4.2.3.0 (June)

> [SPLoaderError.loadComponentError]:
> Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Failed to load URL 'https://...sharepoint.com/sites/keytechappcatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/CommonStrings_en-us_1450f51a76900c0a848f1608cd3a8462.js' for resource 'CommonStrings' in component '544c1372-7e5a-49ec-8db6-812f76c375f2' (pnpSearchBoxWebPart). The file was not found in the server.
> 
> INNERERROR:
> Failed to load URL 'https://...sharepoint.com/sites/keytechappcatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/CommonStrings_en-us_1450f51a76900c0a848f1608cd3a8462.js' for resource 'CommonStrings' in component '544c1372-7e5a-49ec-8db6-812f76c375f2' (pnpSearchBoxWebPart). The file was not found in the server.

**Comment by wobba** [comment]
Then I'm unsure what happens. And it's a tenant app catalog, which has been there for a while? Can you visit sites/keytechappcatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/ and see if the file it asks for is there or not? And this is first time you install the webparts at this tenant? Can you try another tenant?

**Comment by xLucipher** [comment]
Looks like there is something wrong with the server.
The Sharepoint server as well as the app catalog are quite fresh and so far largely unconfigured. All settings are currently set to default.
When I uploaded the file, an error is now displayed (see attachment).
If I understand correctly, I cannot look at the logs due to Sharepoint Online. If the problem comes from Microsoft, I will probably have to open a ticket there. Could the problem come from the package and not from Microsoft? I don't know any further details.
![Bild_2021-07-23_085024](https://user-images.githubusercontent.com/87712345/126746782-b82ff6e0-4721-42d1-bd2d-3edc7a694937.png)

**Comment by wobba** [comment]
As the packages work elsewhere I would open a support ticket.

**Comment by coupalm** [comment]
I have a similar issue with v 4.3.0.0

One user have similar error when accessing the page from Teams Viva connect. However, when accessing directly from SharePoint there is no issue... Another user have the errors when accessing directly from SharePoint. Most users have no issue... I don't get it... Public CDN is enable.

I've uninstall et re-install and same issue. The web parts are deployed globally.

Here are the errors

[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-fb1d-4e96-bc1e-31fd66979667" (pnpSearchFiltersWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/tenant.sharepoint.com/sites/apps-catalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/ControlStrings_fr-fr_2890edc1e9781767448052400b504f62.js' for resource 'ControlStrings' in component '544c1372-fb1d-4e96-bc1e-31fd66979667' (pnpSearchFiltersWebPart). There was an error requesting the file.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/tenant.sharepoint.com/sites/apps-catalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/ControlStrings_fr-fr_2890edc1e9781767448052400b504f62.js' for resource 'ControlStrings' in component '544c1372-fb1d-4e96-bc1e-31fd66979667' (pnpSearchFiltersWebPart). There was an error requesting the file.
CALLSTACK:
Error
    at t [as constructor] (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_fr-fr_d8c3895f6551ed0f9aea266ca1f1889f.js:65:19844)
    at new t (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_fr-fr_d8c3895f6551ed0f9aea266ca1f1889f.js:65:170366)
    at Function.e.buildErrorWithVerboseLog (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_fr-fr_d8c3895f6551ed0f9aea266ca1f1889f.js:65:207838)
    at Function.e.buildLoadComponentError (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_fr-fr_d8c3895f6551ed0f9aea266ca1f1889f.js:65:203883)
    at https://modernb.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_fr-fr_0eba02f0141d373ece15.js:1:11895


Loading chunk 159 failed. (error: https://tenant.sharepoint.com/SitePages/undefinedchunk.pnp-modern-search-sharepoint-search-datasource_c9d311c08e8d1817df62.js)Pour de plus amples renseignements, veuillez consulter les documents officiels.

**Comment by coupalm** [comment]
Here are some info from console errors
![Search-error](https://user-images.githubusercontent.com/11309224/127336770-da269600-3718-4317-95c1-2cb27f8f8290.png)

**Comment by coupalm** [comment]
Have uninstalled and reinstall June version 4.2.3, same issues.
Version 3 is working ok.

**Comment by coupalm** [comment]
Ok, problem solved. Needed to clear cache and cookies for some users.
