### ISSUE TITLE
v3 - Search box not working on results filtered by content type

### ISSUE THREAD

**Issue by corily18** [microsoft-search/pnp-modern-search#1172]
I am working with the v3 of the Search Results.
I am using the results, the search, and the filter web part in many of my projects. 
Normally it works like a charm, I am just having one issue regarding the search functionality.

The implementation

- Search Results: list view of pages in several site collections, filtered by a specific content type
- Search Box: connected with the search results.
 
The problem:
![Search 1](https://user-images.githubusercontent.com/8677989/126613654-8e642799-d210-44c7-8356-ec42314f49ef.png)

When I search for pages (also searching for *) the result is always empty. In the attachment, you can find the screenshot.

Info: When I configure the web part with another query (E.g. {searchTerms} WebTemplate:GROUP) it works like a charm.

Any idea?
Thanks in advance!

**Comment by wobba** [comment]
A bit hard to answer why you don't get results. Maybe the id you are adding is not present on your items? I suggest you check the content type id value of your results to verify that you have it right.

**Comment by corily18** [comment]
Thanks @wobba. It was a stupid typing. I had the right query in the default search query but the wrong one in the query template. That broke it!
