### ISSUE TITLE
PnP Search (v4.2.3) - Translate web parts according to a modern translated page's language, not the UX language

### ISSUE THREAD

**Issue by shariq1379** [microsoft-search/pnp-modern-search#1175]
I have created English Page and then translated page in French using SharePoint Translation (multilingual) feature, but the PnP Refiner Web Part showing date Calendar in English only. 

**PnP Search Refiner:**
English page – It’s showing Calendar in English as expected.
French page – It’s showing Calendar in English. It should show Calendar in French on French translated page because I switched Language toggle to French

**Version used**
Ex: 4.2.3

**Describe the bug**
Date Calendar is showing in English only on both English and French pages.

**To Reproduce**
1. Create New page, add PnP Search and Refiner Web Parts and add Date filter in Refiner web part. 
2. Save and publish page this page.
3. Translate this page in French, save and publish.
4. French Page - Date Calendar is appearing in English instead of French. 

**Expected behavior**
Date Calendar should show in French on French translated page (multilingual) based on selection language from Language dropdown.   

**Screenshots**
![image](https://user-images.githubusercontent.com/77804584/126847106-ef777878-91a8-4c2a-85c0-48b2b1a4e678.png)

**Desktop (please complete the following information):**
 - Desktop - Chrome Browser

**Comment by wobba** [comment]
PnP web parts do not read the language of a translated page, but from the UX language. Related to #1053.

**Comment by wobba** [comment]
Tracked in #1189
