### ISSUE TITLE
Document preview is not showing up for cross geo locations

### ISSUE THREAD

**Issue by Bhoomi95** [microsoft-search/pnp-modern-search#1176]
Hi,

Document preview for the cross geo locations are not showing up . I am getting the error like "Refused to connect". 
Ex: If have to logged into Australia member firm and tries to preview the document of UK/Japan/Or any other geo location, I am getting "refused to connect" issue. 
Could you please help me with this as we are going live with this package in few weeks.

**Comment by wobba** [comment]
If you mean the thumbnail, this is a known limitation due to the auth token from geo not working for other geo's. Solving this requires calling via the Graph API instead, needing another token.
