### ISSUE TITLE
Using three search boxes for searching for different columns

### ISSUE THREAD

**Issue by rpes2** [microsoft-search/pnp-modern-search#1177]
I am working with the v4 version.
We have a document library with many items. We need a possibility to seach for three columns (like category, sub-category, company, ...).
Is it possible to insert more than one search box and combine the values of these boxes in a query for one seach result?

**Comment by wobba** [comment]
You may only connect one search box web part to a result web part. You can however create your own search box web part to solve this. Or you can use the vertical web part, one vertical per column, and three result web parts, one tied to each vertical.
