### ISSUE TITLE
Search verticals not wrapping to next line

### ISSUE THREAD

**Issue by joelfmrodrigues** [microsoft-search/pnp-modern-search#118]
**Version used**
Ex: 3.9

**Describe the bug**
When configuring multiple search verticals, list of options don't wrap to next line when the content is bigger than the space available

**To Reproduce**
Add multiple search verticals to exceed the existing space

**Expected behavior**
Not exactly sure, but perhaps allow the items to wrap to next line? This should work well on smaller screens as well

**Screenshots**

(content is being "cut" at the end)
![image](https://user-images.githubusercontent.com/19577724/75565448-dd48cb00-5a45-11ea-8c38-f17a604b0530.png)

(smaller window - no way to select the other options)
![image](https://user-images.githubusercontent.com/19577724/75565571-1a14c200-5a46-11ea-878d-7717c309b963.png)

One of the elements seems to be enforcing this behaviour
![image](https://user-images.githubusercontent.com/19577724/75565759-72e45a80-5a46-11ea-9b20-229b76b10d7a.png)

**Desktop (please complete the following information):**
 - Browser tested on Chrome and new Edge

**Comment by FranckyC** [comment]
@joelfmrodrigues We use the pivot control directly from Office UI Fabric with no styling change. I will see I can use the `style` to make it behave correctly in mobile view.

**Comment by FranckyC** [comment]
@joelfmrodrigues didn't see your PR. I'll process it for the next release. Thanks!

**Comment by FranckyC** [comment]
Resolved by #119.
