### ISSUE TITLE
PNP filters web part showing GPOI#<guid> in the metadata columns (Country)

### ISSUE THREAD

**Issue by VinuPTomySP** [microsoft-search/pnp-modern-search#1181]
I have checked similar issue reported  link below and followed the solution steps 
https://github.com/microsoft-search/pnp-modern-search/issues/610

Version used is 4.1.0
 Bug explained below : 
PNP filters web part showing GPOI#<guid> in the metadata columns (Country)

I have followed the PNP search results documentation , 

1. Created Refinable string and mapped to Crawled property.

![image](https://user-images.githubusercontent.com/88133324/127454657-24daefa1-0df0-4637-85e1-4dc0ab1eb78e.png)

![image](https://user-images.githubusercontent.com/88133324/127453667-465421b8-b7d7-4fad-8c5d-605a86aecee5.png)

2. In PNP search results webpart make sure that - in slots, we are  using the Autoowstaxidmetadataalltagsinfo property for the "Tags" slot.

![image](https://user-images.githubusercontent.com/88133324/127452188-b8aa55ca-b178-493e-a011-9b79e5bf4912.png)

3. Enabled Localization in PNP search results web part
![image](https://user-images.githubusercontent.com/88133324/127452255-e2e577c7-b4e0-4935-b4d9-a6d2f2fba2fc.png)

1. Launch PNP search results web part page
2. Expand MMS refiner 
3. You will see the values with GUID
Screenshot of error below: 

![image](https://user-images.githubusercontent.com/88133324/127452060-e5881e05-730f-493c-8f1d-02a084ba2e17.png)

Expected Behaviour 
Label of MMS with out GUID

Desktop - Windows 10
 Browser Edge

**Comment by FranckyC** [comment]
HI @VinuPTomySP , I see in your screenshot you mapped the `ows_DocumentCategory` crawled proeprty instead of `ows_taxid_DocumentCategory`. The `ows_taxid_xxx` properties contain GUID of taxonomy items unlike `ows_xxx` who contain only the text value representation. Can you try this and let us know?

**Comment by VinuPTomySP** [comment]
Hi @FranckyC  I have made the change
![image](https://user-images.githubusercontent.com/88133324/127496399-be20290b-6c35-488e-a27f-1fb20ad7edfc.png).
Issue is still there. I may wait for few more minutes and retest it

**Comment by corily18** [comment]
just one remark.... I have the same issue... and in the v3 of the webpart it was also working with the owsallmetadatatags

**Comment by corily18** [comment]
check also this one: https://github.com/microsoft-search/pnp-modern-search/issues/1129

**Comment by VinuPTomySP** [comment]
@corily18 you meant to say  in V3 filter webpart work fines with out issues?

**Comment by wobba** [comment]
@VinuPTomySP You need to reindex your content for the new value to appear, or create new items.

**Comment by VinuPTomySP** [comment]
@wobba , @FranckyC Issue still present  there with V4 after Multiple reindexing and trying out suggested options in the web part.

**Comment by wobba** [comment]
@VinuPTomySP did you enable localization as per https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/#source-configuration?

**Comment by VinuPTomySP** [comment]
@wobba , Yes it is tried and it is not fixed the issue.

**Comment by ileana2019** [comment]
@VinuPTomySP did you fix this issue? I have the same issue with v3.23, v4.7, v4.8
