### ISSUE TITLE
Search Results Web part - Selected Properties field not adding properties correctly

### ISSUE THREAD

**Issue by rdormanHW** [microsoft-search/pnp-modern-search#1184]
**Version used**
4.3

**Describe the bug**
If you type a comma separated list of properties directly into the Selected Properties field of the Search Results Web Part config they are added to the config JSON as a single string instead of a comma separated list of individual property strings.

**To Reproduce**
1. Add a Search Results web part to your page
2. Click in the Selected Properties field (not the drop down arrow) and add a new property by typing (not selecting through the checkboxes), e.g. ,WorkEmail added to the end of the list
3. Look at the config JSON for the webpart.

**Expected behavior**
```
expected JSON: 
		"selectedProperties": [
			"contentclass",
			"ContentTypeId",
			"Created",
			"CreatedBy",
			"DefaultEncodingURL",
			"FileType",
			"HitHighlightedSummary",
			"JobTitle",
			"MobilePhone",
			"NormListID",
			"NormSiteID",
			"NormUniqueID",
			"NormWebID",
			"owstaxidmetadataalltagsinfo",
			"Path",
			"SiteTitle",
			"SPSiteUrl",
			"Title",
			"UniqueID",
			"UserName"
			"WorkEmail",
			"WorkPhone"
		],
```

actual generated JSON:
```
		"selectedProperties": [
				"contentclass,ContentTypeId,Created,CreatedBy,DefaultEncodingURL,FileType,HitHighlightedSummary,JobTitle,MobilePhone,NormListID,NormSiteID,NormUniqueID,NormWebID,owstaxidmetadataalltagsinfo,Path,SiteTitle,SPSiteUrl,Title,UniqueID,UserName,WorkEmail,WorkPhone"
		],
```

**Desktop (please complete the following information):**
 - Google Chrome

**Additional context**
Search then tries to return the big string as a property, which never returns anything

![image](https://user-images.githubusercontent.com/81604756/127643067-ac330681-785a-421c-b174-fc6e274a7681.png)

**Comment by wobba** [comment]
You have to add them one by one and ENTER between each time. The behavior of the PnP SPFx control we use is not ideal. I'll tag it as enhancement to parse and re-work if pasting something with a comma. So in a way it's by (bad) design.

**Comment by clayjam** [comment]
I am experiencing the same issue - I manually type in the custom Managed Property and hit enter. It adds the Managed Property but it doesn't show in the web part (I have some added slots and some other custom managed properties are showing correctly in the web part) but nothing happens. Occasionally the dropdown works and shows one long string of all Managed Properties.

I have two custom managed properties showing but no matter what I do I can't get other managed properties to show.

**Comment by wobba** [comment]
Wait for the next version which has improved handling on typing one or pasting a comma list.  #1252
