### ISSUE TITLE
Accented characters in filter web part's search box

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#1185]
**Version used**
PnP 3.21 and PnP 4.3

**Describe the bug**
When the filter is configured as a multi-value refinement item (3.x) or combo box (4.x) you get the filter specific search box. When searching in this box for country names that contain special characters, the search only works if you use the special character. For example, searching for "Côte d’Ivoire" works, but searching for "Cote d'Ivoire" without the accent over the o does not. 

**To Reproduce**
1. Create a list of countries and include countries that include accented characters.
2. Configure search results web part to show results from this list.
3. Add a filter web part for the country name
4. Configure a filter for the country name as a multi-value refinement item or combo box.
5. save page
6. Expand filter and enter 'Côte d’Ivoire' in filter search box. This works. The list of options for this filter is filtered to show only Côte d’Ivoire as an option to select.
7. Clear the filter and filter search box.
8. Enter "Cote d'ivoire' (no accent) in the filter search box. Notice that once you enter the 'o", Côte d’Ivoire is no longer an available option.

**Expected behavior**
The query works with and without the accented character. By default, English keyboards to not support accented characters, so many English speaking users will enter the word without the accent. Expected behavior is that the query works with or without the accent.

**Screenshots**
![3 x with accent](https://user-images.githubusercontent.com/2616432/128070766-c3e42099-d6fa-47e1-b6df-ebf3f452d731.jpg)
![3 x without accent](https://user-images.githubusercontent.com/2616432/128070769-c480cb9d-103e-43b8-bb6c-9318258ea2c6.jpg)
![4 x with accent](https://user-images.githubusercontent.com/2616432/128070771-9fd71d83-6b07-4934-b74c-750570f8f363.jpg)
![4 x without accent](https://user-images.githubusercontent.com/2616432/128070774-27cec8ab-465d-49cf-925b-217ada80d417.jpg)

**Desktop (please complete the following information):**
 - Current versions of Chrome and Edge

**Additional context**

**Comment by wobba** [comment]
A good suggestion to handle in-line filtering to the base characters. Code wise we can use something like this when matching:

`"strïng".normalize("NFD").replace(/\p{Diacritic}/gu, "")`

**Comment by wobba** [comment]
Fixed for v3

**Comment by wobba** [comment]
Fixed for v4
