### ISSUE TITLE
Need help to display People results with default template

### ISSUE THREAD

**Issue by DeveshRV** [microsoft-search/pnp-modern-search#1186]
Hello Team,

We need your help in modifying the code for Search webpart

Currently, we are able to search with a keyword and get the search result as per the Template selected in WebPart Properties(Ex. Slider, Details-List, Peoples, Tiles etc).

Now, We have a requirement to bring all the results and show on the Page like from Peoples & Documents in single search 'OR' We can provide a checkbox in the UI and show the search results based on the Checkbox value(Only People and Only Documents)

Appreciate your help for any suggestion or code sample.

**Comment by wobba** [comment]
Technically the API makes it hard to get people and documents in the same results. This type of modification to the web part is outside of the support we can give. If you want to modify the web parts pull down and investigate the code :) Or create something custom. I think you might be better off using two result web parts. One for people and one for documents.
