### ISSUE TITLE
How to get content of site collections with sensitivity labels

### ISSUE THREAD

**Issue by JonoSuave** [microsoft-search/pnp-modern-search#1187]
![Screen Shot 2021-08-04 at 9 40 41 AM](https://user-images.githubusercontent.com/22969971/128211054-a784577e-ad8c-4aca-90f2-5d6dbe2deaf7.png)
**Version used**
4.2.3

**Question**
Is it possible to get Document content in the search results web part for site collections that have a specific sensitivity label? 

**Additional context**
I'm able to query for site collections that have a specific sensitivity label (had to mapped crawled property ows_IpLabelId to a RefinableString managed property first), but I'd like to return the content from those site collections.  The content (i.e. documents) of the site collection doesn't have a sensitivity label -- only the site collection.

**Comment by wobba** [comment]
See https://joannecklein.com/2018/01/20/use-aip-label-in-sharepoint-search/

And unsure if a sites label is propagated down to all the items in terms of search. This is more of a SharePoint issue than a search issue.
