### ISSUE TITLE
People Search Alphabetical Display

### ISSUE THREAD

**Issue by yszilagyi** [microsoft-search/pnp-modern-search#1190]
**Version used**
4.3.0

How can I sort LocalPeopleResults alphabetically? I have tried to edit the Sort order on the Search Results to be by UserName, but then I have an error saying that "Field name: This property is not sortable".

![sort](https://user-images.githubusercontent.com/70965501/128480023-993057c6-2c85-494d-93d8-9b4cdd4f3ac8.PNG)

Thank you for your help in advance!

**Comment by wobba** [comment]
You need to map first name or last name or display name crawled properties from people search to a RefinableStringXX property so that you can sort on it. I know... why isn't this a default setup? It just isn't so you need to do it yourself unfortunately.

**Comment by yszilagyi** [comment]
Thank you @wobba ! :)
