### ISSUE TITLE
People Search formatting gone wrong when hover card turned on

### ISSUE THREAD

**Issue by yszilagyi** [microsoft-search/pnp-modern-search#1191]
**Version used**
Ex: 4.3.0

Hi I have had a problem with displaying large amount of text when the hover card was turned on. The issue is, whilst in the original vie, the excess text would be cut and an ellipses (...) would be displayed to indicate that there is more information, when I turn on the hover card, the text goes on in the same line till the scree is just not wide enough anymore. 

**To Reproduce**
1. Go to Search Results, add the following to the query template: {searchTerms} UserName:[yourTenant]
2. on Page 2, select the People Layout,
3. click on Manage People Fields, and set the Optional Text to "Description" and click Save
4. Turn on "Show persona card on hover"

_***This goes to all People fields, not only the Optional Text!***_

**Expected behavior**
I expect to have the same layout with the ellipsis (...) when having the hover card turned on. 

**Screenshots**
Default and Expected View
![original](https://user-images.githubusercontent.com/70965501/128482532-97b9a275-8b3c-4056-95c2-ea0912463c57.PNG)

Actual display of large text when hover card is ON 
![hover](https://user-images.githubusercontent.com/70965501/128482528-8dc77375-ff39-4f2c-a710-32d57e124cfb.PNG)

**Possible Solution** 
If the ms-Persona-optionalText has the attributes of white-space:normal, then the whole text is displayed in a nice format (see below). 
![solved](https://user-images.githubusercontent.com/70965501/128483692-f58fd05d-fec2-4553-aa4c-2a46b3d0bc03.PNG)

**Comment by wobba** [comment]
Fixed for the next version. I added wrapping to all the lines to be sure :)
