### ISSUE TITLE
How to perform a search only by selecting filters?

### ISSUE THREAD

**Issue by CAH1983** [microsoft-search/pnp-modern-search#1193]
**Version used**
Ex: 4.2.2

**Question**

My user wants to be able to:
A/ Search by typing any keyword in the search box --> works well
B/search only by selecting options in the filter(s). --> failed

I could not find a way to display the search filters by default, so it would if I remember allow me to search by filter. also, on my UI, I only get this sole filter showing up (date filter) :
![image](https://user-images.githubusercontent.com/41584108/128502566-5c679d46-e5d6-4bcc-878e-2041f465a5ce.png)

### Steps followed: 
In the search results web part config panel: I tried to set the Default value to '*' so it would display all the items from my list
![image](https://user-images.githubusercontent.com/41584108/128502779-812ab1b3-7864-4fbb-97c0-17749b64c4cd.png)
but I was unsucessfull.

Also, when I type '*' in the search box - expecting to display all the items in the results web part - I get 0 results.
![image](https://user-images.githubusercontent.com/41584108/128503690-f21abef2-8114-4775-9fa2-73ecef006107.png)

This used to work in the version 4.0.0.0

I'm not sure what I am doing wrong, if you could help me that would be great, many thanks

**Comment by CAH1983** [comment]
moved this one to bug because I think it is a bug and not a question

**Comment by wobba** [comment]
You need to ensure you configure the web part correct to show all results when using * as the default query. Then filters will work just fine.
