### ISSUE TITLE
handlebars-helpers don't help me 🤷‍♀️🤦‍♂️

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft-search/pnp-modern-search#1194]
**Version used**
Ex: 4.3.0.0

**Question**
I am trying unsuccessfully to add an "Author" column to a "Detailed List" layout of the search results.
The "Author" slot contains "AuthorOWSUSER" 
I added Column 4 with column value with:
1. expression "{{#with (split (slot item @root.slots.author) '|')}} {{[1]}} {{/with}}" as suggested in one of the issues here. The column shows no data
2. {{ item @root.slots.author }} shows "[object Object]"
3. {{ slot item @root.slots.author }} shows nothing
4. {{ (slot item @root.slots.author) }} shows Parse error on line..

So what is the right what is the right syntax to show the Slot value?
How will I use it with <mgt-person> ? 

I also deployed the "PnP Modern Search - Extensibility Library Demo" and added it to the "Extensibility libraries to load" but I don't see what the demo helper do.
How can I sample that?

**Comment by wobba** [comment]
I'm inclined to let you stew for some more days, but I'll be nice. You didn't pay attention to casing ;) You need to match the casing of the slot names.

`{{#with (split (slot item @root.slots.Author) '|')}} {{[1]}} {{/with}}`

**Comment by Ofer-Gal** [comment]
Yes `{{#with (split (slot item @root.slots.Author) '|')}}{{[0]}}{{/with}}`
gives the eMail
Thanks
