### ISSUE TITLE
Setting '*' as a default value in the Search result web part doesn't return any results, hence can't search by refiners only

### ISSUE THREAD

**Issue by CAH1983** [microsoft-search/pnp-modern-search#1195]
**Version used**
Ex: 4.2.2

**Question**

My user wants to be able to:
A/ Search by typing any keyword in the search box --> works well
B/search only by selecting options in the filter(s). --> failed

I could not find a way to display the search filters by default, so it would if I remember allow me to search by filter. also, on my UI, I only get this sole filter showing up (date filter) :
![image](https://user-images.githubusercontent.com/41584108/128502566-5c679d46-e5d6-4bcc-878e-2041f465a5ce.png)

### Steps followed: 
In the search results web part config panel: I tried to set the Default value to '*' so it would display all the items from my list
![image](https://user-images.githubusercontent.com/41584108/128502779-812ab1b3-7864-4fbb-97c0-17749b64c4cd.png)
but I was unsucessfull.

Also, when I type '*' in the search box - expecting to display all the items in the results web part - I get 0 results.
![image](https://user-images.githubusercontent.com/41584108/128503690-f21abef2-8114-4775-9fa2-73ecef006107.png)

This used to work in the version 4.0.0.0

I'm not sure what I am doing wrong, if you could help me that would be great, many thanks

**Comment by wobba** [comment]
Can you switch to the debug template and show the value of the `queryModification` part? Could it be your query template which is wrong?
![image](https://user-images.githubusercontent.com/51104/128734512-12654d56-8de7-4ca5-a585-c3cea3e91658.png)

**Comment by CAH1983** [comment]
Hello, and thanks for the reply. How do I access this debug template please, is it in SharePoint? Also, I apologized I've opened this request twice by mistake (the other one is in the question section).
I searched on how to configure the search webpart to display all the items from my list but I couldn't find it, would you please indicate me which option do I have to toggle? Thank you

**Comment by wobba** [comment]
Pick the display option named "Debug" for visualization. See https://microsoft-search.github.io/pnp-modern-search/usage/search-results/layouts/

**Comment by CAH1983** [comment]
Hello, I already used scenario 3 to configure the webparts. It's all working but I just need to display the filters by default and be able to pick any value from them.
Also, the search is already limited to only 1 list.

here is what is in the debug file:
`{
  "data": {
    "totalItemsCount": 0,
    "items": [],
    "filters": [],
    "queryModification": "\"*\"  -contentclass:STS_List_* Path:https://xxx.sharepoint.com/sites/Sandbox/CH/Lists/Policies/ -ContentClass=urn:content-class:SPSPeople",
    "secondaryResults": []
  },`

but all I want is to be able to search by keyword (this works perfectly on my page) OR to search without typing any keyword in the search box but only by selecting values from the filters, like so:
![image](https://user-images.githubusercontent.com/41584108/128836661-17ff42de-9ec0-4a78-b759-561870f71682.png)

I was able to do that in the past with version 4.0.0.0. The page was set to display all the filters by default. now, the filters have gone and they will appear only if I type a keyword and launch a search. if that make sense.

**Comment by wobba** [comment]
I did some testing and seems that enclosing `*` with quotes when you have additional property restrictions fails. If you remove the quotes it works. Not sure if this is a recent change or not and will post a question internally.

**Comment by wobba** [comment]
I verified on SP2016. "*" does not work, so this is expected :) So that's the real issue. If it happens to work at times that's the real bug ;)

**Comment by CAH1983** [comment]
> I did some testing and seems that enclosing `*` with quotes when you have additional property restrictions fails. If you remove the quotes it works. Not sure if this is a recent change or not and will post a question internally.

Are you saying I have to remove the quotes from this `queryModification": "\"*\" -contentclass:STS_List_* Path:https://xxx.sharepoint.com/sites/Sandbox/CH/Lists/Policies/ -ContentClass=urn:content-class:SPSPeople", "secondaryResults": [] }
`
also, sorry but to which section/ config "queryModification" corresponds to? is that the query template?

**Comment by CAH1983** [comment]
Hello, so I understood that "queryModification" corresponds to the query template.
I removed the quotes from {searchTerms}* and now the filters appear. that's awesome, thanks a lot Mickael !

**Comment by wobba** [comment]
queryModification shows the fully expanded query being executed combining all query templates down the stack (web part, result source, query rules). And quotes with * is not supported. Then * is treated as a character not wildcard.
