### ISSUE TITLE
Prioritize Search results based on a managed property

### ISSUE THREAD

**Issue by shridha21** [microsoft-search/pnp-modern-search#1196]
**Version used**
Ex: 4.3.0.0

**Question**
Is there a way we can prioritize search results based on a certain managed property. For example:
PnP Search Results webpart is getting data from Local SharePoint data source. Search keyword is "Tony". The search results will bring items where Tony is a keyword, including documents, list items, Site pages, News, Announcements etc, is there away we can show all News article first in the results set and then rest of the results. Looking to use Content Type property to show News Articles first. 
Also is there a possibility to show search results from a particular list first and then rest on the results.

**Comment by wobba** [comment]
Take a look at https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference#dynamic-ranking-operator and at https://www.techmikael.com/2016/12/tip-for-writing-multiple-xranks-or.html
