### ISSUE TITLE
Changing search results to show FileName rather than Title

### ISSUE THREAD

**Issue by kviklund** [microsoft-search/pnp-modern-search#1198]
I am trying to figure out how to change the results to show the FileName Rather than the Title. 

For example The below screen shot shows the document is called "Contracts 101"
![image](https://user-images.githubusercontent.com/88687986/128776820-d9eee944-2e16-48b6-a708-a9757189b389.png)

The actual File name is "Contract Training.pptx" 

Thanks

Kris

**Comment by Laul0** [comment]
Hi @kviklund,

By default, the `Title` is mapped via the Layout slots with the **Title** returned by the search.
If you want to change that, you must:
1. Add the `Filename` property into the **Selected properties**
2. Edit the **Layouts slots** by replacing the value _Title_ from the **Slot field** with _Filename_
3. Save the Layouts slots
4. It is done

**Comment by FranckyC** [comment]
HI @kviklund, does it answer your question?

**Comment by kviklund** [comment]
Sorry for the delay yes this does. Thanks so much for the help.

**Comment by kasperbolarsen** [comment]
It sounds like have forgotten to map a slot for FileName in the Layout slots?
![data_source_slots.png](https://user-images.githubusercontent.com/20593570/227595007-9d0d06d6-1790-4774-a5ae-6462668b7439.png)

**Comment by SPT-Seb** [comment]
> It sounds like have forgotten to map a slot for FileName in the Layout slots? ![data_source_slots.png](https://user-images.githubusercontent.com/20593570/227595007-9d0d06d6-1790-4774-a5ae-6462668b7439.png)

Thanks a million!
This is exactly that, I was updating Layout options>Managed card fields instead of Layout slots > Customize.
