### ISSUE TITLE
Whether to send data outside the M365 tenant

### ISSUE THREAD

**Issue by ykano001** [microsoft-search/pnp-modern-search#1200]
Whether to send data outside the M365 tenant.

We recognize that PnP Modern Search customizes the search function.
So we don't think we need to send data outside our M365 tenant.

Question：
Is there a case where PnP Modern Search sends data outside of its M365 tenant?
（If the above is yes, we are concerned about data leaks.）

Thank you and best regards,

**Comment by wobba** [comment]
PnP does not send or log any data anywhere. We have even disabled telemetry for use of the PnP reusable SPFx components we use. To vet this you can go over the code :)

**Comment by ykano001** [comment]
Thank you for your quick response.
I understand the process.

Thank you and best regards,
