### ISSUE TITLE
SearchTerm are not returning correct results

### ISSUE THREAD

**Issue by PShapiro10** [microsoft-search/pnp-modern-search#1203]
Hi,

Two questions, 

1. I just uploaded the latest version of the search (
I am using Search verion 4.  Do I need to re-deploy it to the tenant if the earlier version 4 has already been deployed?  I am not seeing the deployment option.

2. I am using the below string in the query template:

{searchTerms} 
(Path:https://airleasecorp.sharepoint.com/sites/virtualbinders2/Asset%20Binders OR Path:https://airleasecorp.sharepoint.com/sites/virtualbinders2/Lease%20Binders OR Path:https://airleasecorp.sharepoint.com/sites/virtualbinders2/Subsidiaries OR Path:https://airleasecorp.sharepoint.com/sites/virtualbinders2/Financings) AND
(SPContentType = "Migrated Document" OR
SPContentType = Document) 

If I run the above with just the (SPContentType = "Migrated Document") + the path, I get over 100,000 documents. if I run above with the (SPContentType = "Document") + the path, I get over 180,000 documents.  The issue is that if I run the above with the OR in the SPContentType, I only get a bit over 160,000 documents....  Why is the OR not working?  Should I contruct my query differently?

Thanks
Pinella

**Comment by wobba** [comment]
1. You can upload over the old v4 and it updates automatically
2. There should be no spaces between the property, operator and value in KQL.

`Foo = "a b"` <- FAILS
`Foo="a b"` <- WORKS

**Comment by PShapiro10** [comment]
Hmm, I tried, but I am getting the same results:  {searchTerms} (Path:https://airleasecorp.sharepoint.com/sites/virtualbinders2/Asset%20Binders OR Path:https://airleasecorp.sharepoint.com/sites/virtualbinders2/Lease%20Binders OR Path:https://airleasecorp.sharepoint.com/sites/virtualbinders2/Subsidiaries OR Path:https://airleasecorp.sharepoint.com/sites/virtualbinders2/Financings) AND
(SPContentType="Migrated Document" OR
SPContentType="Document") 

I also tried this:  (SPContentType:"Migrated Document" OR
SPContentType:"Document") 

and this:  (SPContentType:Migrated Document OR
SPContentType:Document)

I am just trying to only include documents (of which I have two content types - Document and Migrated Document) and exclude all other content types like libraries, folders, document sets.  And my focus is specific libraries on this one site.

**Comment by wobba** [comment]
Assuming your content types are correct this should work:

`{searchTerms} (SPContentType:"Migrated Document"
SPContentType:"Document") I would examine the SPContentType value on your results to verify. Then add e.g. path filter to limit to one site collection if CT is used in other sites. You can also use ContentTypeId if you have localization on CT names.
