### ISSUE TITLE
EntityType: Acronym Support?

### ISSUE THREAD

**Issue by benice25** [microsoft-search/pnp-modern-search#1205]
**Version used**
Ex: 4.3

**Question**
Is PnP going to take on searching for EntityTypes like Acronyms? 

**Screenshots**
N/A

**Additional context**
I'm currently trying to build a webpart that will use the graph api to pull back acronyms & answers, but it appears that the route it takes to pull that information is not handled with the standard routing. It would be awesome if the, "Entity types to search" drop down included Acronyms so it's simple to build an acronyms webpart that just displays acronyms.

Also thanks for all of your hard work!

**Comment by wobba** [comment]
When the Graph Search API expose this we can, when someone takes the time to add the support 🙂
