### ISSUE TITLE
Localized Terms within a Layout

### ISSUE THREAD

**Issue by dfrancoeur** [microsoft-search/pnp-modern-search#1207]
Hello,
I have a solution using localized terms (from the Term Store). My filters are working correctly and adjusting the labels to the localized variant. I am struggling, however, with getting the same behaviour when I add the same property into the Search Results layout. In this case, rather than seeing the clean localized term, I get the whole GUID (without any parsing).

Is there a way to correct this to mirror the same behaviour in the filters?

![image](https://user-images.githubusercontent.com/79175670/129235787-cda0f83c-6370-467d-87df-4df108e8c152.png)

![image](https://user-images.githubusercontent.com/79175670/129235861-5e50fd25-09b8-49fc-9de0-3b55b85c33c5.png)

**Comment by CreativeAcer** [comment]
Would something like this work?  
  
```
{{#each (split (slot item @root.slots.Tags) ',') as |tag| }}
            <a  href="#{{slot item @root.slots.Tags}}:'{{trim tag}}'">{{tag}}</a>
{{/each}}
```

**Comment by dfrancoeur** [comment]
> Would something like this work?
> 
> ```
> {{#each (split (slot item @root.slots.Tags) ',') as |tag| }}
>             <a  href="#{{slot item @root.slots.Tags}}:'{{trim tag}}'">{{tag}}</a>
> {{/each}}
> ```

Thanks for sharing! Unfortunately I still get the unparsed string:

![image](https://user-images.githubusercontent.com/79175670/129570519-7ac71c4c-60a8-4b06-b2e6-5e863721901d.png)

**Comment by FranckyC** [comment]
Hi @dfrancoeur , did you configure the 'Tags' slot to use the 'Auto' prefix and enable the localization at Web Part level? According to the documentation: 

> To use translated values in your template, you must use the 'Auto + <property_name>' property format instead of the original property name. For instance, to use translated values of the 'owstaxidmetadataalltagsinfo' property, you must use the 'Autoowstaxidmetadataalltagsinfo' auto created property.

**Comment by CreativeAcer** [comment]
The above mentioned by @FranckyC  is indeed also needed:  
![image](https://user-images.githubusercontent.com/15908395/129573835-18fe0f9f-9e26-4e67-a090-bbc8829e0dcd.png)
and Layout Slots  
![image](https://user-images.githubusercontent.com/15908395/129573924-107aad79-b243-4356-bcaf-46f5a2c10265.png)

**Comment by dfrancoeur** [comment]
Hi Franck and Marco (@FranckyC @CreativeAcer)
TY for the help! Yes I did have localization enabled already. I had not seen that part of the documentation, thank you so much for sharing it. I have never heard/used this "auto" version of the property before. 

Here's what I've done:

![image](https://user-images.githubusercontent.com/79175670/129599375-0339a181-054d-4684-9ce4-dc67e3239ec6.png)

![image](https://user-images.githubusercontent.com/79175670/129599405-c15f6bb2-532e-4b43-becb-c06dba8d2ff9.png)

![image](https://user-images.githubusercontent.com/79175670/129599445-679885a8-f41c-45bc-9dbd-99af779dd2ca.png)

![image](https://user-images.githubusercontent.com/79175670/129599641-22e0f596-7ba1-468e-84f7-02a3c81fe802.png)

Result ( category column is empty )
![image](https://user-images.githubusercontent.com/79175670/129599654-17c5859b-6204-4823-a4ec-fb8fd2179cae.png)

**Comment by dfrancoeur** [comment]
FYI I also tried the CP without the underscores as AutoowstaxIdDocCategory

**Comment by FranckyC** [comment]
Can you try with `AutoRefinableString116` for the slot value?

**Comment by dfrancoeur** [comment]
@FranckyC Duh! That makes more sense than the crawled property. I should have tried that. 
It works! Thank you very much!

![image](https://user-images.githubusercontent.com/79175670/129602644-99aab4c9-b033-4a54-8f1c-a9f7f92df7f6.png)

**Comment by FranckyC** [comment]
De rien ;)

**Comment by dfrancoeur** [comment]
> De rien ;)

Merci!
