### ISSUE TITLE
How to set IconSrc property in Tiles card

### ISSUE THREAD

**Issue by vui211** [microsoft-search/pnp-modern-search#121]
**Version used**
3.9

**Describe the bug**
Hi guys,
Could you please clarify how we can use IconSrc property in Tiles card? I couldn't find information about it here https://microsoft-search.github.io/pnp-modern-search/search-parts/templating/#template-options_1. 
I'd like to change file icon for search results but it seems I can do it through FileExtension property only and it supports predefined set of icons like aspx, html, etc. Can I use custom image urls  for icons?
Thanks in advance

**Screenshots**
<img width="530" alt="IconSrc" src="https://user-images.githubusercontent.com/23225932/75726607-ad503f00-5d47-11ea-8369-8cca6b8bd68c.png">

**Comment by wobba** [comment]
I took a look at the code and we don't use the `IconSrc` property at all. Added logic to read it so you can specify a string using handlebars, or a managed property with an image source url.
