### ISSUE TITLE
Add Crawled Property to filter view

### ISSUE THREAD

**Issue by HamEv** [microsoft-search/pnp-modern-search#1215]
**Version used**
4.3

**Describe the bug**
I configured the filter webpart to filter my people search for Department, JobTitle and OfficeNumber (all necessary properties are mapped correctly and works fine ;-) )  Departemtn and JobTitle are shown in my filter webpart, but OfficeNumber will not be shown up.
How can I filter for this property? Furthermore it's not necessary any more to override the "Selected property" text box in search results. That was the way I did in Version 3, where everything worked great!

**To Reproduce**
1. Insert search results and filter webpart
2. Configure both webparts

**Expected behavior**
All three filter refeners are shown up correctly.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/61208008/129783813-e3bc4e74-ea01-487d-b067-6758a35c8bbf.png)

![grafik](https://user-images.githubusercontent.com/61208008/129783877-b084a6b2-bf6b-44e6-88cb-90d9b0bcf625.png)

![grafik](https://user-images.githubusercontent.com/61208008/129783949-ff113d7f-fafc-4892-b558-99c85e4090f4.png)

![grafik](https://user-images.githubusercontent.com/61208008/129784102-ffe6b9ac-6dd7-4c7f-85bd-c3dc3516a243.png)

**Desktop (please complete the following information):**
 - All Browsers

**Comment by FranckyC** [comment]
Hi @HamEv, I understand the 'OfficeNumber' is a custom user profile property in your case. First of all, did you configure it as 'indexed'? Then, for this property to be refinable you must map the underlying crawled property to a predefined RefinableStringXXX property. 
Use this RefinableStringXXX property in the filter configuration instead of OfficeNumber.

**Comment by HamEv** [comment]
Hi, thanks a lot for your answer and solution. OfficeNumber is a default property and I have not seen, that's it is not refinable. So I mapped it to a predefined RefinabelString.
