### ISSUE TITLE
Custom/New Result source ID not working - No Result found!!

### ISSUE THREAD

**Issue by ketanrana2001** [microsoft-search/pnp-modern-search#1218]
**Version used**
4.3.0
**Describe the bug**
Created new custom Search Result Sources to site collection level with a custom query to search. In the PnP - Search Results web part, in the edit mode, there is a Result source ID, type custom Result Sources Source ID, and hit enter.

"no result was found".

**To Reproduce**
1.	Configure new custom Search Result Sources to site collection level with a custom query to search. (site setting-->search result source (under Site Collection Administration)->new result source-->enter name and let all default settings with new Query Transform ("{searchTerms}Contentclass:STS_ListItem_WebPageLibrary")-->save)
2.	Edit the new result source (we just created) and copy the Source ID from the URL
3.	Create a new SharePoint page
4.	Add pnp result source web part
5.	Edit mode, there is a Result source ID, type (or copy/paste from the URL) custom Result Sources Source ID, and hit enter

**Expected behavior**
OOB if we search, getting the result as expected based on the new custom result source. 

With PnP - Search Results web part no result was found.

**Screenshots**
In the Screenshot, 
1. OOB box result for same result source and expected result.
2. Custom result source- Source ID from the URL
3. configure (2 of them) Source ID to PnP - Search Results in web part-  Result source ID and result.

![OOB search with custom result source](https://user-images.githubusercontent.com/53315866/129807157-a5a4c8d5-ff8d-4313-aced-0a04d1b5dbad.jpg)
![New Result Source with ID](https://user-images.githubusercontent.com/53315866/129807165-56c6e192-1121-46c8-8fdb-36442f86c093.jpg)
![PNP search config 1](https://user-images.githubusercontent.com/53315866/129807172-51ecd68a-6c76-4d5e-8cc1-e6fe57c4df0a.jpg)
![PNP search config 2](https://user-images.githubusercontent.com/53315866/129807181-07b9c66a-9b4b-4de1-8a42-cdf276e4255d.jpg)

**Comment by CreativeAcer** [comment]
Did you add the property you search on to your selected properties in the settings ?

**Comment by ketanrana2001** [comment]
Hello Marco,

I have not added any property, but I have test remove (unchecked) some of the properties which we do not want but have the same result.

Also I have test changing Query Template to {inputQueryText} instead of {searchTerms} but no result.

![Image 3](https://user-images.githubusercontent.com/53315866/129930244-018d8d44-17cc-4588-b40f-09ca72230875.jpg)

**Comment by CreativeAcer** [comment]
What are the settings for your result source?

**Comment by ketanrana2001** [comment]
We want to search only for the pages in the site collection. I have already attached result source screenshots.

{searchTerms}Contentclass:STS_ListItem_WebPageLibrary

![New Result Source with ID](https://user-images.githubusercontent.com/53315866/129938509-7d752d19-5a95-4d71-a076-696d3e5ae2be.jpg)

**Comment by CreativeAcer** [comment]
I just tested this with version 4.3.0 in my tenant and everything works as expected.
Are you sure you have selected the following in your selected properties:
![Screenshot from 2021-08-18 19-17-53](https://user-images.githubusercontent.com/15908395/129943508-5ac6503c-16e1-4656-bff3-c30c03c680c3.png)

**Comment by ketanrana2001** [comment]
Yes, I am using the same.

![Image 7](https://user-images.githubusercontent.com/53315866/129944955-bde81fd5-fc3d-43ee-8d5b-3b0b676faf4e.jpg)

**Comment by CreativeAcer** [comment]
Do you get results when u use the default localSharePointResults result source ?

**Comment by ketanrana2001** [comment]
Yes. I can see results while using the OOB result source from SharePoint (localSharePointResults, pages etc)

![image](https://user-images.githubusercontent.com/53315866/129960575-c3451b23-2f9d-45db-9456-f8d1f7cf30bb.png)

**Comment by FranckyC** [comment]
Hi @ketanrana2001 , quickly it seems your result source query is wrong. Try to put a space after `{searchTerms}` and retry. Otherwise `Contentclass:STS_ListItem_WebPageLibrary` will be treated as free text.

**Comment by ketanrana2001** [comment]
Thank you, Franck. I was about to reply here as I was testing with another query and figure it out the same!!

I have to change the result source to just search within site collection instead of all site collection in tenant and had modified by result source as {searchTerms} (Contentclass:STS_ListItem_WebPageLibrary) Path:{SiteCollection.URL} **and it does work** with PNP search results.

Wondering how the OOB result page took the result source without space and provide the expected result!!!

Thank you again, Franck and Marco. Appreciated your help!!

**Comment by FranckyC** [comment]
Good to know ;) I close this one then.
