### ISSUE TITLE
Refinment Filters in Results web part; using dynamic data

### ISSUE THREAD

**Issue by JohnAdamsSP** [microsoft-search/pnp-modern-search#1219]
**Version used**
Ex: 4.0

**Question**
Within the Search results web part, i am trying to use the Refinement Filters so that the results are only from the current site. I  do this using _SPSiteURL:"https://contoso.sharepoint.com/sites/site1"_ this works, however if i replace the URL as a string with a token such as _SPSiteURL:{Site}_ i get no results. (i need to use a dynamic token as this site will be copied multiple times)
My question is, do Refinement filters even allow for dynamic data? as i have not been able to find any documentation which definitely says it does and if it does then why does the above not work  (SPSiteURL:{Site})?

**Screenshots**
![image](https://user-images.githubusercontent.com/39958376/129925570-8d2c5a8b-20c8-4649-ab1f-b972e79c9a12.png)

**Additional context**

**Comment by CreativeAcer** [comment]
Would using the following query template help you?  
`{searchTerms}path:{Site}`

This offcourse does not anwser your question but it might help you momentarely

**Comment by JohnAdamsSP** [comment]
> Would using the following query template help you?
> `{searchTerms}path:{Site}` or `{searchTerms}SPSiteUrl:{Site}`
> instead of using Refinement Filter
> 
> This offcourse does not anwser your question but it might help you momentarely

Thank you for your reply, i assume you mean to use this in the Query template box? i have tried this and while it does work, it then does a search on page load so the results web part has results data. I wanted to use the refinement filters so that the results web part is empty on page load until a user types in a search.

**Comment by wobba** [comment]
You're using the wrong setting. You want to put the filter in the Query Template to limit per site.

@CreativeAcer and @JohnAdamsSP, please add proper spaces in samples. If not people might copy and have issues. Always a space after `{searchTerms} ` :)

**Comment by JohnAdamsSP** [comment]
> You're using the wrong setting. You want to put the filter in the Query Template to limit per site.
> 
> @CreativeAcer and @JohnAdamsSP, please add proper spaces in samples. If not people might copy and have issues. Always a space after `{searchTerms} ` :)

Thank you for your reply.
My understanding (and what happens when i try this) is that putting a filter like path:{Site} into the Query template box triggers a search on page load. So there are always results in the search results web part, regardless of a value in the linked search box or not or am i using it wrong:
![image](https://user-images.githubusercontent.com/39958376/130060692-704eb645-f6a7-4b78-b86c-4221d6d643a7.png)

**Comment by wobba** [comment]
This notation should solve it for you.

`{?{searchTerms} Path:{Site}}`

See https://www.techmikael.com/2014/05/s15e03-query-variables-constant-trouble.html for a primer on query variables and syntax.

**Comment by JohnAdamsSP** [comment]
> {?{searchTerms} Path:{Site}}

Thank you @wobba that has worked perfectly! i will now use that.
For my understanding and to answer this question for anyone else who is looking for more information on the Refinement filters, is it that it does not allow dynamic tokens? as i could not find the answer to this in any of the documentation.

**Comment by wobba** [comment]
Correct, tokens are not supported in setting a default refinement filter. Which we probably could support. I'll tag this as an enhancement.

**Comment by JohnAdamsSP** [comment]
> Correct, tokens are not supported in setting a default refinement filter. Which we probably could support. I'll tag this as an enhancement.

Thank you again @wobba its helped me out a lot

**Comment by wobba** [comment]
Keeping open as enhancement issue.

**Comment by wobba** [comment]
This is now supported.
