### ISSUE TITLE
Search results - Get categories event

### ISSUE THREAD

**Issue by ayblanchet** [microsoft-search/pnp-modern-search#1220]
Version used: 4.3.0

Hi,

Can you say me if it's possible to get categories of Events using Search results webpart with Microsoft Search?
Currently, I can get only:

"resource": {
          "@odata.type": "#microsoft.graph.event",
          "hasAttachments": false,
          "isAllDay": false,
          "sensitivity": "normal",
          "subject": "",
          "type": "Single",
          "end": {
            "dateTime": "2021-08-18T16:00:00Z",
            "timeZone": "UTC"
          },
          "start": {
            "dateTime": "2021-08-18T15:00:00Z",
            "timeZone": "UTC"
          }
        }

Thank you,

Best regards,

**Comment by wobba** [comment]
Not sure as the docs at https://docs.microsoft.com/en-us/graph/search-concept-events don't say if you can ask for particular properties, or what to filter on. Ask you question at https://stackoverflow.com/ and tag it with `microsoft-graph-api`.
