### ISSUE TITLE
Is it possible to have a single SharePoint document library as data source?

### ISSUE THREAD

**Issue by Kev-Houston** [microsoft-search/pnp-modern-search#1221]
Is it possible to configure the V4 solution to delivery search results from a single SharePoint document library? I have attempted to enter a library GUID into the Result Source ID, however the results continue to be environment wide.

**Comment by wobba** [comment]
You can for example use:
`path:https://contoso.sharepoint.com/sites/test/Documents` 
or 
`ListId:9d494609-6702-4d11-a920-167d989418fe` <- guid of your library

Tack on `IsDocument:1` if you don't want potential folders returned.

**Comment by Kev-Houston** [comment]
Thank you for the response @wobba 

The ListId: is to be entered into the Result Source ID field of the Search Results webpart?

**Comment by Kev-Houston** [comment]
ah - in the query template!
