### ISSUE TITLE
Refinement Filters scroll not accessible throughout the page.

### ISSUE THREAD

**Issue by KshamaShrey** [microsoft-search/pnp-modern-search#1222]
**Version used**
     4.3

**Bug Description**
 Whenever the content in the Pnp modern search refinements filters exceeds the screen size(only in touch devices eg.iPhone,iPad)the user is not able to scroll throughout the page.The page is scrollable only in the left hand side of the panel but not scrollable throughtout the page.Please find the screenshot attached. When the user touches the orange highlight (as perthe screenshot below) to scroll ,the page is scrollable.But on trying to scroll in other areas of the page the user is not able to scroll.

**To Reproduce**
Create a modern sharepoint page.
Add Pnp modern search refinements filters webpart to the page with more filters that exceed the mobile screen.
add Pnp modern search results webaprt to the page to filter the search results

**Expected behavior**
Expected behavior is that the user is able to scroll anywhere in the page not only in the orange highlight area mentioned in the screenshot and the scrollbar should appear when the refinement filters exceeds the mobile screen.

**Screenshots**
<img width="367" alt="Screenshot 2021-08-19 at 3 07 43 PM" src="https://user-images.githubusercontent.com/39548087/130046325-ac3c60b9-b139-4e29-b7e9-78771b70c28c.png">

Issue is found only in touch devices in all the browsers.

**Comment by wobba** [comment]
Will be fixed in the next release.

**Comment by KshamaShrey** [comment]
Thnak you.That was a quick response. Could you please let us know what is the expected date for the next release?

**Comment by wobba** [comment]
I cannot :) We try to do monthly but depends on available time. You can however build the dev branch yourself while waiting.

**Comment by KshamaShrey** [comment]
@wobba Any updates on this?

**Comment by wobba** [comment]
If you follow the releases v4.5 was released this week.
