### ISSUE TITLE
People Vertical - Info needed on missing props like Office Location, Projects and Skills

### ISSUE THREAD

**Issue by Naveen-Rangarajan** [microsoft-search/pnp-modern-search#1224]
**Version used**
Ex: 3.16

**Question**
The People Vertical does not contain the details related to Office Location, Projects and Skills. I am not sure which selected property holds this data. Tried with some of the below props, but they are returning null values.

AboutMe - null
Skills - not able to find in the drop down of Selected Properties in search settings configuration
AdditionalInfoOWSMTXT - null
Project/EventTitleOWSTEXT -  null
ProjectOWSTEXT - null
ProjectNameOWSTEXT - null

Can you please help in identifying the correct selected property names to retrieve these details.

**Screenshots**
<img width="490" alt="Project and Skills" src="https://user-images.githubusercontent.com/61411651/130058382-1cb69fac-7c84-4be7-8d0a-95c55620a1aa.png">

<img width="269" alt="Screen shot1" src="https://user-images.githubusercontent.com/61411651/130059500-57a376e9-23ca-43ec-8153-1fe52cbacf46.png">

**Additional context**
Add any other context which is helpful to understand the question.

**Comment by wobba** [comment]
If you go to https://contoso-admin.sharepoint.com/_layouts/15/searchadmin/ta_ListCrawledProperties.aspx?category=People&level=tenant you can see the list of managed properties available for people profiles, and also which crawled property it maps to, which again correspond to the UPA properties.

**Comment by Naveen-Rangarajan** [comment]
Thank you for the prompt reply :)

I dont have access to the Admin Tenant and need to check with my clients. In the meantime, do we have any other resources to look into to get this info?

**Comment by wobba** [comment]
Then run it from any site you have access to via:

`/sites/somesite/_layouts/15/ListCrawledProperties.aspx?category=People&level=sitecol`

😉

**Comment by Naveen-Rangarajan** [comment]
Thank you for the update. I was able to identify Skills and Projects, but not location. Tried Location, BaseOfficeLocation, Office, but none seems to be working.

**Comment by VerlindenEAM** [comment]
Hello Naveen, I had similar issues when using profile properties on site collection level.
If you wish to use profile properties and use them as refiners, make sure they are set as refiners on tenant level instead of site collection level.

**Comment by Naveen-Rangarajan** [comment]
Thank you for the update again.

It's to display the data in the search results for People results and not used as refiners.

**Comment by wobba** [comment]
See https://www.techmikael.com/2016/02/search-schema-mapping-level-explained.html for an explanation on mapping at different levels.
