### ISSUE TITLE
Failed to load component from https://publiccdn.sharepointonline.com 

### ISSUE THREAD

**Issue by abc2milton** [microsoft-search/pnp-modern-search#1226]
When I insert any of the PnP Search webparts in a page I see the following:
![error](https://user-images.githubusercontent.com/24484409/130152058-d7a69b82-0962-491d-8c27-9436cb0d3d66.jpg)

If I use Edge I see them ok which is very strange.

The App Catalog is on its own Site Collection

App installs fine with no errors
I can see the content in the list:
![image](https://user-images.githubusercontent.com/24484409/130152179-46a1a3ce-010b-4bcc-8d99-f1e1b6015397.png)

I cannot navigate to the URL listed in the error: 'https://publiccdn.sharepointonline.com/[my site].sharepoint.com/sites/[subsite]/ClientSideAssets and get an access denied error

Is there anyway to force the App to not use the https://publiccdn.sharepointonline.com site for server up content?

I appreciate all support in advance

**Comment by wobba** [comment]
@abc2milton still an issue?
