### ISSUE TITLE
Title field returned is File Name field

### ISSUE THREAD

**Issue by diguerd** [microsoft-search/pnp-modern-search#1227]
**Version used**
Ex: 4.3.0.0

**Describe the bug**
When i add the "Title" field to the Search Results, the Title field displays the Filename and not the Title field of the document.

**To Reproduce**
Add Title field to results

**Expected behavior**
Display contents of Title field

**Comment by wobba** [comment]
This issue will be closed if proper repro steps and explanation is not added.
