### ISSUE TITLE
Card layout tweaking (hyperlinks and dimensions)

### ISSUE THREAD

**Issue by mthanos7** [microsoft-search/pnp-modern-search#1232]
**Version used**
Ex: 4.3

**Question**
Hello! I'm building an app catalog/gallery using the card layout in v4.3 and have a few questions regarding how to customize its appearance. The main components within each card are the app name, a logo image, and a text description of what it does. I'm querying a SharePoint list as the data source.

1. I can obtain the description text either by the handlebar statement, "{{slot item @root.slots.Summary}}", or by calling the property, "Description"; I've assigned this value to the "Tags" section under "Managed card fields". Some of the description text as it appears in the SharePoint list have additional hyperlinked text that redirects to certain pages. However, I haven't been able to get those hyperlinks to show up in the card with the method I'm using above (the text is there, but are not linked/clickable). Is there a way I could achieve this result and how?

2. The card fields are dynamically sized to the content shown and number of cards displayed per row. Could I adjust the height of the cards so that they are uniform and can be sized to fit more content? And how?

Thank you!

**Screenshots**
![Capture](https://user-images.githubusercontent.com/22053481/130676289-63999912-f1f0-411d-ba12-f7de4a1bac1e.PNG)

**Comment by mthanos7** [comment]
On the same topic, how could I display values in the PnP Search Results card layout that come from a hyperlink column in the source list? Would I map it to a RefinableString or is there a way for me to call it using a specific handlebar statement?

**Comment by mthanos7** [comment]
Update: Figured out how to display a hyperlink 

> 
> 
> On the same topic, how could I display values in the PnP Search Results card layout that come from a hyperlink column in the source list? Would I map it to a RefinableString or is there a way for me to call it using a specific handlebar statement?

Managed to display a hyperlink with html via handlebar. Would still like opinions on whether links are able to be fetched if they are in the description text and how to standardize size for all cards!

**Comment by wobba** [comment]
@mthanos7 we don't have any special handling for html/richtext coming back - and we would also have to sanitize the markup if we did to avoid script injection.

**Comment by FranckyC** [comment]
Hi @mthanos7 , if you want to display links correctly coming from an HTML input text, you can only use fields marked as **'Allow HTML'**. All other fields in the card are always treated as text only, even if they contain HTML markup.

![image](https://user-images.githubusercontent.com/5659122/131387582-d4c172f0-7850-4e3f-8165-a628d82e2000.png)

These fields are like placeholders so you can put anything here an leave the description field empty for instance.

**Comment by mthanos7** [comment]
@wobba @FranckyC Thank you! I managed to get to a solution. Regarding my other inquiry, is it possible to standardize a card height to make all the cards uniform?

**Comment by mthanos7** [comment]
@wobba @FranckyC I have additional questions regarding the tweaking of the card layout; please let me know if I should be creating separate questions for this. From a user standpoint, I find that when the cursor is anywhere on the white space of a card, the cursor is a "link pointer" (as if the area is clickable to redirect to a link). However, this does not link to anything. Is is possible to set a url for this action to link to, or remove this behavior so that the cursor is a basic pointer when not hovering over hyperlink text?

![1](https://user-images.githubusercontent.com/22053481/131554473-e2dc7379-0ade-4300-ac9e-82870a3e68d9.PNG)

Additionally, is it possible to display the Title value of a card in plaintext and not as a hyperlink?

**Comment by wobba** [comment]
The cards do have a fixed height. I'm guessing your custom html somehow break this? As for the cursor being a pointer, log that as an issue, not a question. And maybe someone have a suggestion for a fix.
