### ISSUE TITLE
Search Results - Not possible to display mgt-get response fields

### ISSUE THREAD

**Issue by FrankMuraschow** [microsoft-search/pnp-modern-search#1233]
**Version used**
4.3

**Describe the bug**
When searching for people, I want to display profile information. I can get this information via the _/beta/users/[email]/profile_ MS graph endpoint. To make use of that endpoint, I implemented the mgt-get component inside a custom template. Using the example found on [mgt.dev](https://mgt.dev/?path=/story/components-mgt-get--extending-person-card) I can see the conditional expressions (i.e. _data-if="languages && languages.length"_ ) working. Unfortunately I'm not able to access the same properties, that have just been used to assess the condition.

**To Reproduce**
1. Implement a search results webpart
2. For demo purposes enter a fixed query text (email address of a user)
3. Edit the template and [use this](https://pastebin.com/MVYk9xWE) (again for demo purposes)
4. There is no language rendered

**Expected behavior**
See the languages of the user

**Screenshots**
I can see inside the network tab, that the request triggered by mgt-get reponds correctly. 

![image](https://user-images.githubusercontent.com/5666768/130757376-d6963860-e4ca-4fdd-8a9b-af3e5c3914ad.png)

**Conclusion**
As you can see the response by _mgt-get_ is read / interpreted correctly, when being used inside a _data-if_ attribute but not when trying to plainly display the information.

**Comment by FranckyC** [comment]
Hi @FrankMuraschow, inside the mgt template you can try to escape the expression using `\`, otherwise it will be processed as an Handlebars expression. Ex:

```
<span data-for="interest in interests">
    \{{interest.displayName}}
</span>
```
