### ISSUE TITLE
PnP Modern Search (v4) filter webpart - user field support?

### ISSUE THREAD

**Issue by DavidRehak87** [microsoft-search/pnp-modern-search#1234]
Hello,
does PnP Modern Search (v4) filter webpart supports user field?
I am getting AuthorOWSUSER or EditorOWSUSER from search results webpart as follows:
_**email@domain.com | Name Surname | 693A30232E778C6D656D781446836869707C726566987B64406261736661642E547173662E6E6574 i:0#.f|membership|email@domain.net**_

But filter webpart seems to completely ignore it.
Thanks

**Comment by DavidRehak87** [comment]
Thank you for the answer. Then I think I might have problem somewehere else because I don't see this filter even though I recieve values under AuthorOWSUSER in the search webpart. 
My Filter webpart settings:
![filter1](https://user-images.githubusercontent.com/66776045/131648306-4e76b36e-30ca-4de6-9880-5f2ac90cdc1e.PNG)

But when I get the resluts I don't see this value in the filter webpart:
![filter2](https://user-images.githubusercontent.com/66776045/131648428-b5e73b69-9262-4e1a-94de-cd18877efd21.PNG)

**Comment by wobba** [comment]
If you want something in the filter, you need to map a crawled property to a refinable managed property, and then use this refinable managed property in the filter web part. You can use `DisplayAuthor` as your filter, but data wise it's not great imo - too much noise.

**Comment by DavidRehak87** [comment]
Thank you very much for your help. 
I did mapped **ows_q_USER_Author** to RefinableString:
![filter1](https://user-images.githubusercontent.com/66776045/131974493-8afb4571-6422-4dab-8ac8-ba1e35bc8e5d.PNG)
But it in search results was this Refinable still empty:
![filter2](https://user-images.githubusercontent.com/66776045/131974523-26dc07d6-dd90-40c0-b14a-cbe441c1a792.PNG)

Nevertheless the DisplayAuthor Managed property worked great and I am able to filter the Author now. Why that would be "Too much noise?".
Thanks again!

**Comment by wobba** [comment]
For the created by display name you need to use the cp `Office:4`. It's weird I know.

**Comment by DavidRehak87** [comment]
Yes, it is :) thank you for the explanation.
