### ISSUE TITLE
Prototype Pollution Vulnerability in the set-getter library

### ISSUE THREAD

**Issue by levalencia** [microsoft-search/pnp-modern-search#1235]
**Is your feature request related to a problem? Please describe.**
High vulnerability found on codescan tool.

**Describe the solution you'd like**
Change the dependencies if possible

**Describe alternatives you've considered**
Develop the entire search myself

**Additional context**
In my organization code scans are required before deploying something to production , the modern search package is amazing however when we used the veracode scan it found one high finding:
https://sca.analysiscenter.veracode.com/vulnerability-database/security/prototype-pollution/javascript/sid-30901

After some research through the dependency chain I found out that  its used by handlebars indirectly.

I hate that I have to develop this webpart myself, it would take ages, I checked npm for new version of set-getter but there are no new versions since long time ago.

My security team in a global organizacion rejected the package and therefore either we have to develop it ourselves, or mitigate it somehow.

Not sure if someething can be around this issue

**Comment by wobba** [comment]
@levalencia If you can share details of which dep etc. we can have a look.  And even though the tool flags it, doesn't mean it's a real issue depending on how we use purify the handlebar template to avoid injections.
