### ISSUE TITLE
Search Box Query String double encoding

### ISSUE THREAD

**Issue by jhholm** [microsoft-search/pnp-modern-search#1236]
**Version used**
4.3

**Describe the bug**

I'm using the Search Box Web Part to search for people in Microsoft Search. If I search by using a single word, e.g. Megan. Everything works. If I add any uriencodable characters such as a space, the search query parameter seems to be double uriencoded. See screenshots below.

**To Reproduce**

1. Install PnP Modern Search App to a site of your choice
2. Add a PnP Search Box Web Part to a page in the site.
3. Open Property pane for the Web Part
4. Set **Send the query to a new page** to On
5. Set **Page URL** to your tenants people search page _e.g. https://{mytenant}.sharepoint.com/_layouts/15/search.aspx/people_
6. Set **Method** to Query string parameter
7. Set **Parameter name** to q
8. Save your changes and publish the page
9. Try searching for e.g. **Megan Bowen**
10. You should navigate to the people search page, and see that the space in the query parameter is encoded twice as q=**Megan%2520Bowen**

**Expected behavior**
Query parameter should not be double encoded. Query parameter should be  **q=Megan%2520Bowen**

**Screenshots**

![image](https://user-images.githubusercontent.com/13876124/130813511-b6d6833c-94a6-4d82-99ec-ef0b37399236.png)
Example configuration

![image](https://user-images.githubusercontent.com/13876124/130813652-3b6cc194-cf9e-441d-9555-09c15366358b.png)
Search result page after searching for Megan Bowen

![image](https://user-images.githubusercontent.com/13876124/130814298-cf09f3b5-ef2f-4ab1-a96e-ffe82278ff05.png)
Query parameter double encoded

**Additional context**

I guess this is a similar case as in issue #20.

I think I found the culprit of the issue here

https://github.com/microsoft-search/pnp-modern-search/blob/b78aba6323a9d12ae2cca39f709f933d0f3f1746/search-parts/src/webparts/searchBox/components/SearchBoxContainer.tsx#L94

The querystring is encoded before the function call in line 94 and encoded again within the function.

If you take a look at the other use of the same function here, the string is not encoded before the function call.

https://github.com/microsoft-search/pnp-modern-search/blob/b78aba6323a9d12ae2cca39f709f933d0f3f1746/search-parts/src/webparts/searchBox/SearchBoxWebPart.ts#L651

**Comment by wobba** [comment]
@jhholm  please do :)

**Comment by jhholm** [comment]
See PR #1249

**Comment by jhholm** [comment]
... accidental click on github mobile.
