### ISSUE TITLE
PnP Search Filter - how to change the font/ css class for Checkbox Header 

### ISSUE THREAD

**Issue by shridha21** [microsoft-search/pnp-modern-search#1240]
**Version used**
Ex: 4.3

**Question**
With PnP Search Filter webpart, i am looking to change the font size or update the css class for the Checkbox Header. I am able to change it for Combobox style, by updating the custom template, but not for Checkbox. It looks Checkbox  is using pnp-collapsible component, which has no option to change the header style.

![image](https://user-images.githubusercontent.com/46351822/131035083-5b61c748-00b1-4fe1-a9ff-272b7fd0656e.png)

**Comment by wobba** [comment]
You can use a custom template. Something like below where you bold the filter title.

```
<content id="data-content">

	{{#each @root.filters as |filter|}}    
	
		<div><strong>{{filter.filterName}}</strong></div>
	
		{{#each filter.values}}
			<pnp-filtercheckbox 
				data-filter-name="{{filter.filterName}}" 
				data-name="{{name}}" 
				data-value="{{value}}" 
				data-selected="{{selected}}" 
				data-disabled="{{disabled}}"
				data-theme-variant="{{JSONstringify @root.theme}}"
			>
			</pnp-filtercheckbox>
		{{/each}}
		
		
		{{#eq filter.values.length 0}}
			<div>{{@root.strings.FilterNoValuesMessage}}</div>
		{{else}}
		
			{{#if filter.isMulti}}
				<pnp-filter-multi data-filter-name="{{filter.filterName}}" data-theme-variant="{{JSONstringify @root.theme}}"></pnp-filter-multi>
			{{/if}}
		{{/eq}}

	{{/each}}

</content>
```

**Comment by shridha21** [comment]
Thank you Wobba for sharing, this. I tried this and there seem to be challenges that i am facing .
1. Instead of the filter name it is showing the name of the underlying Refinable property
2. The collapsible functionality is no longer available.

Is there a way to maintain the collapsible functionality and still be able to change the css of the Filter Name title. I have around 10 filters on my page and with 100s of values under them. Cannot have filter with collapsible functionality. Any guidence will be appreciated.

**Comment by wobba** [comment]
If you use the debug template it shows all the data, and you should be able to figure out the data model notation and what properties to use for the separate pieces. The default vertical template can be found at https://github.com/microsoft-search/pnp-modern-search/blob/main/search-parts/src/layouts/filters/vertical/vertical.html and you can copy this and modify as needed.

**Comment by shridha21** [comment]
Thanks wobba. That's my initial question about, when i try to customize the Vertical Template layout, it uses pnp-collapsible module for checkbox type filters and there is no way to alter the font of the filter header. Font for filter check boxes can be changes but not the header Filter displayname.

**Comment by wobba** [comment]
Adding this CSS in the template seems to work ok. Assuming the internal component markup/structure don't change, and we don't plan on doing that. https://github.com/microsoft-search/pnp-modern-search/blob/develop/search-parts/src/components/CollapsibleContentComponent.tsx#L162

```css
pnp-collapsible div[class^="collapsible__filterPanel__body__group__header"] span {
   font-size: 140px;
}
```

**Comment by shridha21** [comment]
this did the job. thank you :)
