### ISSUE TITLE
PnP Search v3: Wrong query modification with self created Source Id's in Verticals Web Part

### ISSUE THREAD

**Issue by DominikLeitgeb** [microsoft-search/pnp-modern-search#1241]
Hello,
I'm using the Search version 3 (latest update) and in my demo tenant this problem doesn't exist but in another tenant I've the problem that the conected vertical doesn't change the result .
All self created ResultsourceId's has the same result.
I checked in debug mode the query modification and with all self created result sources I got this in line 2:

"queryModification": "test -ContentClass=urn:content-class:SPSPeople",

Any idea why my created result sources doesn't works?
I tested with other result web part, other verticals web part, new own source Id's and SharePoint source Id's...
The web parts works and with SharePoint Id's everythings is fine, but with self made source Id's I get this problem. Everything is configurated like in the test tenant and the properties was imported from the test tenant.

**Comment by wobba** [comment]
You should check that the result source id is set on the http request. And you can also try to configure a classic web part the same way and see if you experience the same behavior or not.

Can you also check the response header `x-searchplatform` and see if the value is the same for your environments where it works and not?

**Comment by DominikLeitgeb** [comment]
I tried to create a new sitepage with the result web part only and insert the SearchResultId + * Query an I got the same results. I added a few pictures to show this.
I don't know which web part do you mean with classic, where I can use des ResultSourceId to check that. Maybe you have short  instruction for me, how to do this?

![ResultSorceId Configuration](https://user-images.githubusercontent.com/87366596/131485151-4477d751-1297-4b1d-b661-eba1a31f2152.jpg)
![X-SearchPlatform](https://user-images.githubusercontent.com/87366596/131485158-48a5b1d3-62cf-4f15-af1c-2ad67c420aac.jpg)
![ResultSorceId Configuration KQL](https://user-images.githubusercontent.com/87366596/131485173-ac15a207-f910-49f2-ab3d-b9f02bd879c5.jpg)
![Result Debug Mode](https://user-images.githubusercontent.com/87366596/131485182-5b4dc4d6-ad1c-4f3c-8dd4-f0684d5a7636.jpg)
![Result Config on new Sitepage](https://user-images.githubusercontent.com/87366596/131485194-74983617-483c-47ae-b03e-57eced257324.jpg)
![Query Request Payload](https://user-images.githubusercontent.com/87366596/131485204-30802358-2cec-4db9-a6a3-765410e68c8f.jpg)

**Comment by wobba** [comment]
Can you remove the / from the result source name (to ensure the special characters not cause an issue), and try the notation `SPSite|name` instead of the id? And weird that it works in one environment and not the other. Seems to be an API issue, and not really a PnP web part issue.

Classic web parts require you to enable classic features and create e.g. a wiki page. SharePoint 2010/2013 style :) You should find info on the web for this if you want to test it out.

**Comment by DominikLeitgeb** [comment]
I tried all the steps, but nothing changes.
From one day to the next: Looks like it works now.
Now the Query Modification works like it should and I get the expected results.
I really don't know why. I didn't changed anything in the configuration or something else...
Maybe was a internal problem from SharePoint.

I thank you so much for your Help.
