### ISSUE TITLE
Pagintion breaking after 50 pages in Mircosoft tenant.

### ISSUE THREAD

**Issue by chintanupadhayay** [microsoft-search/pnp-modern-search#1242]
### Check existing issues before logging new ones
[#947](https://github.com/microsoft-search/pnp-modern-search/issues/947)

Unable to find this scenario here. Hence opening it again. Any suggestions are much appreciated. Thanks in advance.

**Version used**
PnP Modern Search 4.3.0

**Describe the bug**
Hello @wobba,
 
I have tested v4.3.0 with two environments Microsoft and another tenant, pagination is working fine with other tenants but in Mircosoft tenants [Dev and Live] is not able to get records after the 50 pages.

When clicking on 50 pages, query returning null data.

**To Reproduce**
1. Download the latest version of the PnP package
2. Upload on app catalog 
3. Add on page

**Expected behavior**
Search Results for the last page should be displayed.

**Screenshots**

** #request JSON**

:authority: microsoftapc.sharepoint.com
:method: POST
:path: /teams/{SiteName}/_api/search/postquery
:scheme: https
accept: application/json;odata=nometadata
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 1434
content-type: application/json;odata=verbose;charset=utf-8
cookie: MicrosoftApplicationsTelemetryFirstLaunchTime=1615185392341; MicrosoftApplicationsTelemetryDeviceId=70df25de-ade2-ffdc-2caa-44e047e9643a; ai_user=DriblMPtPGgszD5khble4k|2021-05-25T14:09:15.803Z; rtFa=lNyCJVFZzVBlWkLxF7NpzTDwkcfMi0TZhcWVfb8AQ/EmRUM2M0IwOUItOTc0OC00N0JBLTkwMTgtQkVFQURENDA1MjA0IzEzMjczODQzMTA4NTg5NTM1NiNBNzAyRTc5Ri1GMEE4LTAwMDAtRDlFRS1EOUY5MTk5MkE5RjUjVi1ISVJLQVQlNDBNSUNST1NPRlQuQ09NHe+Cakvg05WI6AV5uiiAOhinb/dd1N5f9iWGd0mUR0wetTeObYQn2PK8L+DXckCBRDFAUnLuARlfRrzBIfykVzjkYoFew8wliGJFSiy7XZkgqqBNr2yJsO3lVGQs0fLVSkhgQ9Da4in36l4zlDJNu9RbFX0zAjvnGli1Xhk8ZvKI9/TdOLOZ4mRuvl/sYg/zkKWOe6OyLzEwgBibg0bcY2Oh/PnmcmrkixabFWNh0205a377XU0opjYJWf/PMALUAT7p6heKMf9iRFtqtbn3WlaoMmf29mXo4dxlducdPcemEKezUlNjSuZeI90Wa3iWlG/MaikkO/C/fKitiaySHJYAAAA=; ScaleCompatibilityDeviceId=d44f729a-7379-4f8b-bf36-3da9b6dee1d7; WSS_FullScreenMode=false; splnu=1; ClientSideDisableThirdPartyCache=; ScaleVolatility=ec63b09b-9748-47ba-9018-beeadd405204; FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjExLDBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMGI2MjhkYWYxQGxpdmUuY29tLDAjLmZ8bWVtYmVyc2hpcHx2LWhpcmthdEBtaWNyb3NvZnQuY29tLDEzMjQ4NTI3MTUwMDAwMDAwMCwxMzIzMjA1MDU4MzAwMDAwMDAsMTMyNzQ5ODE0Nzg2NTI5NDM4LDE1Ny4zMy40NC4xNTEsNzA3LGVjNjNiMDliLTk3NDgtNDdiYS05MDE4LWJlZWFkZDQwNTIwNCwsYWE4ZTYxZTktYjJkMS00MTVkLTk0NjktNGMyYTQ4ZTdmOWI3LDJiMDJlNzlmLTkwZDctMDAwMC1hYzUyLTgyNWYxNmFiN2IzOSw0ZGE0ZTk5Zi0xMDQ1LTAwMDAtYzQxNy0xZGJlOGVkNjJmY2UsLDAsMTMyNzQ1NTMwNzg2NTI5NDM4LDEzMjc0ODA4Njc4NjUyOTQzOCwsLGV5SjRiWE5mWTJNaU9pSmJYQ0pEVURGY0lsMGlMQ0o0YlhOZmMzTnRJam9pTVNJc0luQnlaV1psY25KbFpGOTFjMlZ5Ym1GdFpTSTZJbll0YUdseWEyRjBRRzFwWTNKdmMyOW1kQzVqYjIwaWZRPT0sMjY1MDQ2Nzc0Mzk5OTk5OTk5OSwxMzI3Mzg0MjYwMDAwMDAwMDAsMTg1NzQ0ZTEtNzZmNS00ZTY0LTg5YmQtYjBkZDQ3ZGZmZDljLCwsLCwsMCxoWHArV0I4a1A2OUZJUTRtNkNTVnBuRGtHMmJ1NFdUNXZtcGk2MTZCL05VN3lya2tDR0xybGp3MDFaOGFudUV1RnAwZ0lER3llaHZrZVVqakJ2KzdONEIrNktFemxMbStXQUx2NERvcHAydDlDY0w2RE1LMTQ0RWJ3MUVJWFVyRkFZcE5pYy8xdmVob0J5TjBxb25kNlRGWEYraDltU0xVdHZ1R0RMZjRJOUNLWjRSVk45emlNd2V5K3h5SnhUTFN3UlhhS1dEVFNOMWluR1EwYkt2MmZQMXNWc3hmbW04dmV3QlVQWWxFNHVEcEt2aWQ1VW92emdjMnZKZDdENXRIaUJoZXVsU3Q5WXdhT2hZOTFRRzlpZCt2WkNFVGpQU0ZCTTBFZjRmc2ZiejgzMGR4T1R4QWVtTUZUWjZoR2pFRHBxelJHK3Q4c1FSZVJxRk1oRWVFcHc9PTwvU1A+; ai_sessionSearchResultsWebPart=oW5zVGrulsuG1eKQPV1Wca|1630075164793|1630075981170
odata-version: 3.0
origin: https://microsoftapc.sharepoint.com
referer: https://microsoftapc.sharepoint.com/teams/{SiteName}/SitePages/{Page.aspx}
sdkversion: SPFx/pnpSearchResultsWebPart/544c1372-42df-47c3-94d6-017428cd2baf
sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
useragent: NonISV|PnP|ModernSearch
x-clientservice-clienttag: NonISV|PnP|ModernSearch
x-requestdigest: 0xD5C0C02F72F815D4DAC3F795D4A9698AB846214FF642EAA094F52F2827BE22E9D1952D030E9C52FC9AE23A62C3A42A55A8D662713BA56A2AC2CC38BB09E0104A,27 Aug 2021 14:52:59 -0000

**request Payload**

request: {__metadata: {type: "Microsoft.Office.Server.Search.REST.SearchRequest"},…}
ClientType: "PnPModernSearch"
Culture: 1033
EnableNicknames: false
EnablePhonetic: false
EnableQueryRules: false
HitHighlightedProperties: {results: []}
Properties: {results: [{Name: "EnableDynamicGroups", Value: {BoolVal: true, QueryPropertyValueTypeIndex: 3}},…]}
QueryTemplate: "{searchTerms} Path:https://microsoftapc.sharepoint.com/teams/{SiteName}/Lists/{LisName}"
Querytext: "*"
RefinementFilters: {results: []}
Refiners: "CreatedBy"
ReorderingRules: {results: []}
RowLimit: 10
SelectProperties: {,…}
SortList: {results: []}
SourceId: "8413cd39-2156-4e00-b54d-11efd9abdb89"
StartRow: 540
TimeZoneId: 13
TrimDuplicates: false
__metadata: {type: "Microsoft.Office.Server.Search.REST.SearchRequest"}

**Pages 1-49** 
![UpTo50](https://user-images.githubusercontent.com/29138303/131147897-a1a967fd-3c37-4691-89e0-ad2716a26cb5.PNG)

**Pages 50-100** 
![Oresults](https://user-images.githubusercontent.com/29138303/131147807-5c5bd2b2-5b62-411b-be6f-bb7d581571de.PNG)

**Response**
![totalros](https://user-images.githubusercontent.com/29138303/131147920-2b71d346-4286-4cef-abf1-ddf5301e76f8.PNG)

**Desktop (please complete the following information):**
 - Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Additional context**
Are there any limitations for Microsoft tenants to get 50+ pages?

**Comment by wobba** [comment]
Cannot repro. I can page just fine to say page 100. Either way, it's not a PnP issue, but an API issue. Which means you can test using classic web parts and should face the same issue. And then file a support ticket.

**Comment by YogeshT15** [comment]
@wobba We are also facing this issue. No matter result count is 50 or 50K. Result page work till 50 pagination, after that result webpart doesn't work. 

I tested classic search and its working fine.

is it PNP search limitation??

**Comment by wobba** [comment]
I don't have repro.. here's using v4 with the SP provider. StartRow=670 and RowLimit=10.

![image](https://user-images.githubusercontent.com/51104/152210300-98f38ccb-65fb-4ab4-a421-f62db2b64ec7.png)

**Comment by vineetsawarkar** [comment]
@wobba : I am also facing the issue. After the 500 items. As per my observation it is not related with pagination.
E.g : 1 ) if per page item limit is 100,in this case we can face error on page 6 that is after 500 item.
        2) if per page item limit is 50,in this case we can face error on page 11 that is after 500 item.

Please suggest trouble shooting steps to check the response JSON.

**Comment by wobba** [comment]
Hit F12 in your browser and open dev tools. Then look at the requests going when you search. If using the SharePoint provider they include the term postquery.

This screenshot is from Edge.
![image](https://user-images.githubusercontent.com/51104/152513167-0558bb82-5ff0-476a-ad4c-b66de5da8271.png)
