### ISSUE TITLE
Contains handlebars helper 

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft-search/pnp-modern-search#1244]
**Version used**
Ex: 4.3
**Question**
I have 2 content types the results web part shows results for. it is a custom layout and I have a line to show the content type in:
`{{#if ContentType}} <span>Source:</span><span><em>{{ContentType}}</em></span>{{/if}}`
but it shows more than the content type name for example ('DPCDocuments' is the content type that I want to show as 'DPC Documents')
`application/vnd.openxmlformats-officedocument.spreadsheetml.sheet DPCDocuments` 

My logic is:
if it contains 'DPCDocuments' show 'DPC Documents' if 'WorkingPapers' show 'Working Papers'

I found a mention of #contain helper `{{#contains "WorkingPapers" ContentType }}` but nothing came out
I followed a link from the documentation and found `{#match (ContentType "DPCDocuments")  }}` but it caused errors and nothing showed.

1. Is there another managed property I should reference?
2. Is there another available handlebars helper I can use?
3. Do I have to use extensibility to register a new helper? examples?

**Screenshots**
![image](https://user-images.githubusercontent.com/5054931/131340194-bce90cd8-1593-4732-96da-a63d11bb1133.png)

Took me a while to get this but now I feel this package is great helper. Thank you much

**Comment by wobba** [comment]
Old trick. Never use the `ContentType` managed property. Always use the `SPContentType` one, which has the correct name. Or use `ContentTypeId` :)

**Comment by wobba** [comment]
The `contains` helper is for item inside an array. What you want to use is `test`. See https://github.com/helpers/handlebars-helpers#test

**Comment by Ofer-Gal** [comment]
I added SPContentType to Selected properties but it does not show.
 But the ContentType stated showing without the extra wording.
End result `{{#eq ContentType "DPCDocuments" }} <span>if eq:</span><span><em>DPC Documents</em></span>{{/eq}}`
does what I need. thanks

**Comment by wobba** [comment]
Up to you, but SPContentType should work and is preferred :) https://www.techmikael.com/2016/02/when-query-by-content-type-name-use.html
