### ISSUE TITLE
Re-Packaging the PnPSearch Source Code

### ISSUE THREAD

**Issue by PwnGinger** [microsoft-search/pnp-modern-search#1245]
**Version used**
Ex: 4.2

**Question**
How do you re-package the PnPSearch source code?

**Screenshots**
None

**Additional context**
We needed to modify the source code due to certain hardcoded commercial endpoints. Our tenant is GCC-High so certain .com endpoints won't work as they need to be .us instead. I plan to open a separate issue for this topic.

**Comment by wobba** [comment]
You can clone the repo and modify. If you let us know what changes are needed we can try to get them in as part of the solution instead. Makes it easier for you to upgrade later 🙂

**Comment by PwnGinger** [comment]
> You can clone the repo and modify. If you let us know what changes are needed we can try to get them in as part of the solution instead. Makes it easier for you to upgrade later 🙂

Thanks! I created a separate [issue](https://github.com/microsoft-search/pnp-modern-search/issues/1246) providing more detail around the issue!
