### ISSUE TITLE
Did you mean Query Spelling Inclusions

### ISSUE THREAD

**Issue by JonoSuave** [microsoft-search/pnp-modern-search#1247]
Am I to understand that if I include a new word under Query Spelling Inclusions term store that this word would be included within the spelling corrections suggestions of the search result web part? For example, if I added the term basquetball (instead of basketball) then I'd receive a message, "Did you mean basketball?" when I search for basquetball?

**Comment by wobba** [comment]
No, as per December 2020 this functionality was removed in Microsoft 365 https://docs.microsoft.com/en-us/sharepoint/manage-search-dictionaries#manage-query-spelling-correction. Longer term we hope to get the new functionality via the Graph Search API.

**Comment by JonoSuave** [comment]
Hmmm, darn. Is there any other method to let PnP Modern Search know of terms that should be included for spelling corrections (e.g. company names)?

**Comment by wobba** [comment]
There is no automatic spelling correction today on the SPI search API. There might be something coming on the Graph Search API's.

**Comment by edarroudi** [comment]
@wobba i have a pull request for this: https://github.com/microsoft-search/pnp-modern-search/pull/1480
It failed the check because of *** SonarCloud thinking that labels for multiple languages are duplicates...

**Comment by edarroudi** [comment]
@wobba i think you can close this now ?:)

**Comment by emilyLin** [comment]
> There is no automatic spelling correction today on the SPI search API. The Graph Search API do have this, but we haven't implemented it yet. https://docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta#request-spelling-correction

@wobba Can we update the spelling correction e.g. adding company name or any organisational acronyms?

**Comment by AtlasPark77** [comment]
@wobba 

We're currently using PnP version 4.6.1 and have activated the "Did you mean" functionality that is working a treat. The question I have is can the "Did you mean" dictionary be added to? We have a requirement to add in specific spelling mistakes for acronyms and other company related terms

![image](https://user-images.githubusercontent.com/109932963/180711150-9519eea5-8285-4085-ab7a-0c34917b6d97.png)


Kind Regards,

Atlas

**Comment by wobba** [comment]
There is no option to modify the suggestions coming from the API today,

**Comment by AtlasPark77** [comment]
> 

Thanks @wobba
