### ISSUE TITLE
Sorting within the Query String

### ISSUE THREAD

**Issue by PwnGinger** [microsoft-search/pnp-modern-search#1248]
**Version used**
Ex: 4.2

**Question**
Is there a way to request search results be provided in a specific order either by adding something to the query template or to the query string passed via the URL - something like "ModernSearch&sortlist=author:descending"? Ideally would like to be able to modify the order results are presented by appending the sort order to the request to allow for dynamically changing the results ordering without needed to build a different page for each differing order.

**Screenshots**
None

**Additional context**
None

**Comment by FranckyC** [comment]
Hi @PwnGinger, this could be achieved using a custom search result source, query rules and the `{QueryString.xxx}` token:

1. Create a result source with your KQL query and default sorting.
2. On this result source, create a query rule that only changes the sort order when a specific keyword is entered (like 'desc'). Don't keep the `{searchTerms}` token as you don't want to include it in the query.

![image](https://user-images.githubusercontent.com/5659122/131543311-28933654-339f-4a90-adee-2931311074fb.png)

3. In the Web Part query template, use the `{QueryString.<your_param>}` expression.

That should do the trick.
