### ISSUE TITLE
Replace default image for the folder view

### ISSUE THREAD

**Issue by sb-sheriff** [microsoft-search/pnp-modern-search#1251]
Hi,

Did anyone get experience to replace the broken default image as shown below?

![image](https://user-images.githubusercontent.com/87348254/131589298-1c1bd02b-7bda-4157-9c26-cd5fbdb590ef.png)

**Comment by FranckyC** [comment]
Hi @sb-sheriff, this is not a broken image, just a placeholder image when no preview image is available for the result. In your example, you are displaying folders so it is the expected behavior.

**Comment by FranckyC** [comment]
If you want to get rid of if, simply update the Handlebars template logic.

**Comment by sb-sheriff** [comment]
I see. Yes, I'm looking to replace this placeholder image with an image of the regular folder.  May I get to know where to find the Handlebars template logic?

**Comment by wobba** [comment]
@sb-sheriff You can use the result type option for example - and provide a custom template for folders. I'll tag this as an enhancement to skip preview for folders, as it doesn't make sense to have it.

**Comment by sb-sheriff** [comment]
@wobba OK, now I need to find out where to use the result type option/custom template -- this one? 
https://github.com/microsoft-search/pnp-modern-search/blob/main/docs/scenarios/edit-templates-using-vscode-and-onedrive.md

I thought I could simply replace that default image with a regular folder image and not confuse the user as something broken.

**Comment by wobba** [comment]
I assume you're using v4. Take a look at https://microsoft-search.github.io/pnp-modern-search/usage/search-results/layouts/#result-types

**Comment by wobba** [comment]
Added a fix for this and also made sure OneNote notebooks work as expected as they had folder icons.

**Comment by sb-sheriff** [comment]
Copy that, thanks!

**Comment by wobba** [comment]
Re-open until we get the change into v4 as well.

**Comment by wobba** [comment]
Fixed for the SP provider in v4. Awaiting the Graph provider which seems to have API issues.

**Comment by sb-sheriff** [comment]
> Fixed for the SP provider in v4. Awaiting the Graph provider which seems to have API issues.

Supposed I could download and reinstall the v4 to fix the issue? ... if the Graphy provider resolved the API issue...
