### ISSUE TITLE
Language with moment not working

### ISSUE THREAD

**Issue by ellinge** [microsoft-search/pnp-modern-search#1253]
**Version used**
Ex: 4.3

**Describe the bug**
I use moment to format my search result dates for an event (from/to). Today when upgrading to 4.3 I noticed it no longer worked with localization. After downgrading again, the dates are in Swedish format again.

I've tried using the documented getDate as well, but it only chooses English even if the browser and page is set to Swedish.

**To Reproduce**
1. Have a date mapped to RefinableDate00
2. . Go to the result template of a search result webpart and add the following
```
{{#*inline "datumFormatering"}}
  {{#if (eq (regex '2999' datum) '2999')}}
    Tills vidare
  {{else if (eq (regex '\d{4}' (moment datum lang="sv" calendar=null)) '-')}}
    {{replace (moment datum lang="sv" calendar=null) ' 00:00' ''}}
  {{else}}
    {{replace (moment datum lang="sv" format="Do MMMM HH:mm") ' 00:00' ''}}
  {{/if}}
{{/inline}}
<li>
{{> datumFormatering datum=item.RefinableDate00}}
</li>
```
3. Save page and notice that the result is in English either way

**Expected behavior**
I expect the handlebars methods for getDate or moment to return a localized result.

If not being able to use moment, extend getDate to be able to set calender=null to more control over the output.

**Screenshots**
With lang="sv" working (4.1.0)
![bild](https://user-images.githubusercontent.com/17863113/131683238-2434332c-d36a-42cb-9f67-9c8d7cffed54.png)

With lang="sv" not working (4.3.0)
![bild](https://user-images.githubusercontent.com/17863113/131683477-87e70662-e52c-49bc-9990-cf69c6de7cbe.png)

**Desktop:**
 - Browser Chrome, Safari

**Additional context**
I know getDate is the documented handlebar function for the pnp search results but needing more control over the formatting (a.k.a yesterday etc with calender) I tried using the moment method directly. Something has obviously changed under the hood but have not found what change between 4.1 and 4.3 which caused it. The browser seems to load the Swedish locale chunk in both cases/versions.

**Comment by FranckyC** [comment]
Hi @ellinge , can you confirm the UI language is Swedish? We use the UI language to load the correct local for the moment library.

**Comment by ellinge** [comment]
I tried with version 4.2.3 also:
![bild](https://user-images.githubusercontent.com/17863113/131725362-8ecb5d51-20f5-49b4-83f9-807544377085.png)

With following template:
```
<style>
    .datefield{
        padding: 5px;
    }
</style>
<li>
  <div class="datefield">{{moment item.RefinableDate00 lang="sv" calendar=null}}</div>
  <div class="datefield">{{moment datum lang="sv" format="Do MMMM HH:mm"}}</div>
  <div class="datefield"><strong>{{getDate item.RefinableDate00 "Do MMMM HH:mm"}}</strong></div>
</li>
```
The browser has Swedish as preferred language, the sharepoint site is created with Swedish.

**Comment by ellinge** [comment]
![bild](https://user-images.githubusercontent.com/17863113/131727512-8e8db37a-c9a5-43e3-a98e-6ec558ca4cf3.png)
Has it something to do with the chunk renaming?

**Comment by wobba** [comment]
@ellinge that is my guess, and we're changing this a bit again :) You could test with the dev branch if you can build yourself.

**Comment by FranckyC** [comment]
That's shouldn't be. I'm trying to reproduce the issue and it seems the locale is not loaded.

**Comment by ellinge** [comment]
This is a possible candidate as well, not marked as externals anymore:
https://github.com/microsoft-search/pnp-modern-search/commit/4ff5b4ecad4f68f6bf23f6dcfd4262ae958f2eb5

**Comment by ellinge** [comment]
Adding this line to a develop build causes it:
https://github.com/microsoft-search/pnp-modern-search/blob/b78aba6323a9d12ae2cca39f709f933d0f3f1746/search-parts/config/config.json#L31

![bild](https://user-images.githubusercontent.com/17863113/131740138-8247c375-588c-4d8e-9752-7d39f2009bbe.png)

**Comment by wobba** [comment]
The externals have been removed in the dev branch. It optimized the bundle, but apparently side effects.

**Comment by ellinge** [comment]
Develop untouched without externals works. It’s main/4.3 with externals which is not working. Perhaps having moment as a external with the combination of renamed chunks causes it? The localized chunk having one name and momentlib another because it’s set as an external (ignoring the webpackChunkName?). Just a guess.

**Comment by wobba** [comment]
@FranckyC It made for a smaller bundle all up, but I'm ok with anything :) Closing this as it should be fixed in the dev branch and then upcoming release.
