### ISSUE TITLE
Promoted Results Disappear?

### ISSUE THREAD

**Issue by JonoSuave** [microsoft-search/pnp-modern-search#1254]
**Version used**
V4

**Describe the bug**
I had the promoted results displaying, but today they aren't displaying on the search results web part. Just to be sure my edits from two days ago wasn't the cause I reverted back to a version from a week ago -- still no promoted results. I verifed the result source ID is correct as well for the managed query rules I created.

**To Reproduce**
1. Create a managed query rule
2. Search for that query rule term (be sure your handlebars template includes code to display promted results). Here's what my promoted results code looks like:

```
{{#if @root.data.promotedResults}}
		
		<ul style="border:.75px solid #043561" class="template--defaultList template--promotedResults">
		    <h3 style="
    margin-block-start: .5em;
    margin-block-end: 1em;
">Promoted Results</h3>
			{{#each @root.data.promotedResults as |promotedResult|}}
			<li>
				<div style="margin-left: -12px; color: #043561">
					<a href="{{url}}" style="text-decoration: none;
    color: #043561;"><pnp-icon style="font-size: 28px" data-name="FavoriteStar" aria-hidden="true"> </pnp-icon></a>
				</div>
				<div style="margin-left: 4px">
					<a
						href="{{url}}"
						style="color:{{@root.theme.semanticColors.link}}; font-size:18px; font-weight:bold"
						>{{title}}
					</a>
					
					<div>{{description}}</div>
				</div>
			</li>
			{{/each}}
		</ul>
		{{/if}}
```

3. Search for the managed query rule term

**Expected behavior**
I expect to see a banner for promoted results

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
Promoted results appears to be working in OOB Search

**Comment by wobba** [comment]
If it used to work and is no longer working, then this is an API issue, not a PnP web part issue. You need to contact Microsoft support for this. In order for the support case to be accepted you should set up a repro using the classic web part's, as those are part of the product. Support tend not to respond to API questions, or 3rd party solution issues.

**Comment by JonoSuave** [comment]
The promoted result is returning in the OOB search results, so would that still be a SharePoint API issue?
![Screen Shot 2021-09-01 at 11 58 27 AM](https://user-images.githubusercontent.com/22969971/131720750-0efa024f-9811-4b1c-b5fb-46b6d7bddd91.png)
![Screen Shot 2021-09-01 at 11 58 05 AM](https://user-images.githubusercontent.com/22969971/131720753-80009e30-eaad-42d4-8839-0af62bc7861b.png)
 Attached are pics showing how I input the Result source ID from the managed query rules. Did I do that correctly?

**Comment by wobba** [comment]
Next step, check the request that you are passing the correct result id, and check the response if it's coming back or not. You can also use the SharePoint Search query tool.

Using Modern Search on a site as a test does not surface SharePoint Search API issues, so you need to use something which hits the SP API's. If you haven't changed anything, it's an API issue. So we cannot really help. It works on my dev tenant just fine.

**Comment by MariaTusak** [comment]
Hello, 
Having the same issue here. IDs are fine, I am getting results from the right source, but none of my promoted results are showing, even though it worked fine before. 
Just for confirmation...

**Comment by wobba** [comment]
@MariaTusak I recommend logging a support ticket. For better support I recommend configuring a  classic webpart/wiki page with classic web parts to surface the issue, as those are OOB web parts - not 3rd party.

**Comment by JonoSuave** [comment]
@wobba do you have an example of a classic webpart that uses the SharePoint API? I checked, you are correct OOB Search seems to use Microsoft Search and when I query using SharePoint API secondary results aren't returning promoted results.

**Comment by JonoSuave** [comment]
@wobba I also spun up a test on dev tenant but had no luck there either. Could you post on the configurations you have set up on your dev tenant? Attached are screenshots of my configurations within search results, search query rules, and lack of promoted results
![Screen Shot 2021-09-03 at 10 33 40 AM](https://user-images.githubusercontent.com/22969971/132039128-071144b6-4c51-4a9b-a24a-58cb4ce9ed3a.png)
![Screen Shot 2021-09-03 at 10 30 12 AM](https://user-images.githubusercontent.com/22969971/132039135-e5fe59c7-55ba-431c-a82c-e4f82ac99f52.png)
![Screen Shot 2021-09-03 at 10 29 40 AM](https://user-images.githubusercontent.com/22969971/132039137-9c8eae18-8646-468c-997c-890f83791b86.png)
![Screen Shot 2021-09-03 at 10 29 01 AM](https://user-images.githubusercontent.com/22969971/132039138-0c4c20be-2c5f-485e-8172-a02535099dcb.png)

**Comment by wobba** [comment]
You should also be able to trigger and test this:

* If it's a site created promoted result, append this to your site URL and see if it triggers `/_layouts/15/osssearchresults.aspx`.
* If it's a tenant wide promoted results go to `https://tenant.sharepoint.com/search` and test.

**Comment by JonoSuave** [comment]
One thing I noticed that's happening when this issue occurs is that the Querytext isn't passed into the postquery request. This only occurs when the query is made via the OOB Microsoft search that then redirects the search to the search page
![EmptySecondaryQueryResults](https://user-images.githubusercontent.com/22969971/181656327-27b7150c-f2ca-484c-b79c-f78c1b19a3f0.png)
![NoQuerytextPassedIn](https://user-images.githubusercontent.com/22969971/181656329-34bbc666-f815-4ed1-aee6-a929af56faff.png)
![QuerytextPassedIn](https://user-images.githubusercontent.com/22969971/181656331-4557515c-6244-4e44-bc40-e9bb5b2c2348.png)
![SecondaryQueryResultsReturned](https://user-images.githubusercontent.com/22969971/181656335-9ba8d753-a35a-43d4-9edd-8ccbbd605479.png)
 (everything comes back correctly when using the PnP Search Box on the same page as the search results page).

**Comment by JonoSuave** [comment]
@wobba following up when you have a moment

**Comment by wobba** [comment]
I've been on sick leave and vacation for the past 5 weeks. It would help if you could detail the repro steps with page and web part setup. And also how the promoted result is set up to trigger.

**Comment by JonoSuave** [comment]
Welcome back (hopefully fully renewed :)! 
Search Results config setup:
- Available data sources: SharePoint Search
- Layout slots: See attached
- Query template: {searchTerms} followed by Path and content type filters
- Result Source Id: Id from tenant result source
- Selected Properties: "AuthorOWSUSER",
        "contentclass",
        "ContentTypeId",
        "Created",
        "DefaultEncodingURL",
        "Department",
        "Description",
        "FileType",
        "JobTitle",
        "LastModifiedTime",
        "ModifiedBy",
        "NormListID",
        "NormSiteID",
        "NormUniqueID",
        "NormWebID",
        "owstaxidmetadataalltagsinfo",
        "Path",
        "RankingOWSNMBR",
        "RefinableString09",
        "SiteTitle",
        "Title",
        "UniqueID",
        "UserName",
        "WorkPhone"
- Sort settings: See screenshot
- Enable query rules is On
- Trim duplicates: Off
- Enable audience targeting: Off
- Enable localizations: Off
- Hit-highlighted properties: None
- Show paging: On
- Number of pages to display in range: 5
- Hide navigation buttons: Off
- Hide firts/last navigation buttons: Off
- Hide navigation buttons if they are disabled: On
- Custom handlebars template (let me know if you need it)
- Use MGT, Show results count, show selected filters are On
- Use input query text turned on with Dynamic value
- Connect to PnP - Search Box
- PnP - Search Box's properties: Search query
- Connect to a filters Web Part: On
- Version: 4.7.0
- PnP telemetry is On


![Screen Shot 2022-08-15 at 8 27 04 AM](https://user-images.githubusercontent.com/22969971/184654293-a6df9e29-9e77-4df7-828c-c1e9b65b619c.png)


![Screen Shot 2022-08-15 at 8 20 12 AM](https://user-images.githubusercontent.com/22969971/184653194-ae83b97d-c475-4d13-9ee1-71ac1067cb82.png)
![Screen Shot 2022-08-15 at 8 20 22 AM](https://user-images.githubusercontent.com/22969971/184653200-33294a20-a1cb-41c2-b82a-f0f5f98f61d3.png)

**Comment by wobba** [comment]
(You know you can export out the settings via the last web part pange/page right?) 😉

**Comment by wobba** [comment]
Is this still an issue for you? And can you examine the primary and secondary results in the response and see if you find the promoted result there? I'm adding a minor fix for another query rule scenario which may or may not impact your case.
