### ISSUE TITLE
Error message only on one page

### ISSUE THREAD

**Issue by MirasMNC** [microsoft-search/pnp-modern-search#1256]
Hello,

two days ago we have received the error message (bellow on the screen). It is only on one page. On other pages it still works well without any issues. When I created new page with the same settings it works. Do you have any idea what happened and how to fix it without creating new settings again? I am not able to reproduce the issue. I have just one page where it happens.

<img width="712" alt="search issue" src="https://user-images.githubusercontent.com/62887437/131742913-3bb5bc45-2e50-440f-b295-666d7ed6c59a.png">

I would to avoid this situation.

Thank you for your tips

Mirek

**Comment by wobba** [comment]
Closing issue as it's not using the bug template filling in needed information to provide any useful answer.
