### ISSUE TITLE
Is it possible to specify a specific folder as the search range?

### ISSUE THREAD

**Issue by rikyo233** [microsoft-search/pnp-modern-search#1257]
I set the pnp search box and Search Results in my page 
Is it possible to specify a specific folder as the search range?

**Comment by wobba** [comment]
Yes it is, and closing as you didn't use the question template.
![image](https://user-images.githubusercontent.com/51104/131880622-9f30c2ae-285a-41c9-89d4-3d358fe0d8fb.png)
