### ISSUE TITLE
search results in specific order

### ISSUE THREAD

**Issue by kvpnvp** [microsoft-search/pnp-modern-search#1259]
**Version used**
Ex: 3.14

**Question**
Is there a way to request search results be provided in a specific order either by adding something to the query template or to the query string passed via the URL. Ideally would like to be able to modify the order results based on type of result. I have string as a type, I do not want to sort asc or dsc but in specific order for eg. type 'Info' appears first, type 'Comment' appear after all 'Info' types etc. How to do this without need to build a different page or filter.

**Screenshots**
None

**Additional context**
None

**Comment by wobba** [comment]
Check the "sort order" setting https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-results/#search-settings or change the order via a custom result source.

**Comment by wobba** [comment]
@kvpnvp did you get your issue resolved?
