### ISSUE TITLE
Add support for telemetry callback on item click

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#126]
When a user clicks a result, it would be nice to be able to call an ajax call back js function, or a call an ajax https URL for scenarios where people want to log telemetry and usage. The callback/URL should be able to get the search session, keywords, and full result or params when clicked.

If we allow a `callback="myfunc('{{Title}}',b,c,d,e)"` or `callback="https://lalala?a={{Title}}"`, or similar, then a tenant can register the function globally on the page to be available by the webparts to be called.

**Comment by FranckyC** [comment]
Hi @wobba, could it be a dedicated wrapper web component instead so you could put it anywhere in your template? Like:

```
<pnp-telemetry url="https://your_rul" data="{{<whatever>}}">
       <!-- The DOM element(s) you want to monitor on onClick -->
</pnp-telemetry>
```

This wrapper would be triggered on the onClick() event in the inner DOM elements.

**Comment by wobba** [comment]
Makes sense to me. Either a GET/POST url, or a javascript function callback. Can we support both? url or callback param for example.

**Comment by wobba** [comment]
Closing until there is an API available.
