### ISSUE TITLE
PnP Search result webpart changing the template results using custom slot 

### ISSUE THREAD

**Issue by sanjivpradhan** [microsoft-search/pnp-modern-search#1260]
Version used
Ex: 4.2

**Problem Statement**

I have a SharePoint custom list which has two fields, **Title** and **SiteRedirectURL** both are text field , List information will look like below .

**Title         |       SiteRedirectURL**
Google              https://google.com
Microsoft          https://Microsoft.com

I am trying to show the search result in PnP search result webpart and making sure , If the users click the Title item this will redirect the user to respective  SiteRedirectURL mentioned in the list . Currently this is not working.

Steps taken :
1) Change the Search result query template with my list URL 
**{searchTerms} Path:"https://shareTest.sharepoint.com/sites/IT/Lists/DCAppList"**
2) Crated new managed property name **MPRedirectURL** in SharePoint search and mapped this with crawled properties ows_SiteRedirectURL of the list .
3) Created new Layout slots name **SlotRedirectURL** map with managed property name **MPRedirectURL**  in the PnP search result webpart
4) Change the result template with below highlighted information understanding clicking the Title will redirect to RedirectURL mentioned in the list .  

Details tag is as below

<ul class="template--custom">
            {{#each data.items as |item|}}

                {{#> resultTypes item=item}}
                    {{!-- The block below will be used as default item template if no result types matched --}}
                    <li>
                        <pnp-iconfile class="icon" data-extension="{{slot item @root.slots.FileType}}" data-theme-variant="{{JSONstringify @root.theme}}"></pnp-iconfile>
                        
						<span class="example-themePrimary"><a href="{{slot item @root.slots.SlotRedirectURL}}">{{slot item @root.slots.Title}}</a></span>
                    </li>
                {{/resultTypes}}

            {{/each}}
        </ul>
[](url)

Wanted to check, Am i missing something here , Also wanted to know how to check the new slot value is coming on the PnP search result webpart.

**Comment by sanjivpradhan** [comment]
Hi @wobba Need your help !

**Comment by wobba** [comment]
Help is whenever someone has time. Use the debug template to verify what data is returned on your items. You likely haven't added `SlotRedirectURL` to the "Selected properties" list. https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/#source-configuration

**Comment by wobba** [comment]
@sanjivpradhan did you get your issue resolved?

**Comment by sanjivpradhan** [comment]
Yes this get resolved .. Thank you so much @wobba !!
