### ISSUE TITLE
Filter Webpart Issue for External Users

### ISSUE THREAD

**Issue by Mathr001** [microsoft-search/pnp-modern-search#1261]
**Version used**
Ex: 4.2.2

**Question**
Guest or External Users do not see the Filters configured.  Tenant AD Users work as expected.
All other Search functionality works as expected for External users.

**Comment by wobba** [comment]
Closing as this is logged as a question, and I see no question.

And I have no problem seeing filters as a guest user using the SharePoint provider in v4.
