### ISSUE TITLE
Error message instead of search results

### ISSUE THREAD

**Issue by MirasMNC** [microsoft-search/pnp-modern-search#1262]
**Version used**
v4.3

**Question**
We use new modern search web parts v4 and suddenly only one page it appears error message instead of search results. Have you ever met with this what is the reason of this behaviour? I have tried to reproduce and without success. I have tried to change the settings and nothing helps. I created new page with the same settings and it works. I would like to avoid in the future.

**Screenshots**
<img width="712" alt="search issue" src="https://user-images.githubusercontent.com/62887437/132132220-98b9b837-8973-4ea8-8189-2f106578abfd.png">

**Additional context**
-

**Comment by wobba** [comment]
I did fix an issue last week which could be the culprit behind this as by default there was an extra comma which caused a null value to be sent over in the request. https://github.com/microsoft-search/pnp-modern-search/pull/1252/files#diff-df240ce73edefa66b3c3df10f10e8f7409ff2b138661fbff21ade4846be22f08L368 The fix will be included in the next release.

**Comment by MirasMNC** [comment]
Thank you for your response. I will wait for new release. :)

**Comment by paylord** [comment]
@wobba meh sorry - missed that one!
