### ISSUE TITLE
PNP - Search Filters only show one option

### ISSUE THREAD

**Issue by AnderOllive** [microsoft-search/pnp-modern-search#1263]
I configured PNP - Search Filter with 2 options, but this web part show only one option, can help me, please?

![image](https://user-images.githubusercontent.com/88772391/132201925-95c70b12-623f-4463-9ba8-022c69442c3b.png)
And only see:
![image](https://user-images.githubusercontent.com/88772391/132202054-6065fe97-5ef1-4e2f-a57c-4c15a3c822e2.png)
Because not show me 2 options.

**Comment by wobba** [comment]
Closing as the issue do not adhere to any of the issue templates, and does not show information on which properties are used in filters. Thus we cannot give an answer as there is too little information. Sorry.
