### ISSUE TITLE
Sortable Fields missing in V4?

### ISSUE THREAD

**Issue by bengschf** [microsoft-search/pnp-modern-search#1264]
Hello everyone,

I cannot find a way to add a sortable field in V4.3. In V3.x, I was able to add a sortable field:

![image](https://user-images.githubusercontent.com/49641330/132223043-dde44b50-4791-4f21-9ae7-1f6a5603b56c.png)

The result was that the user could sort the search results:
![image](https://user-images.githubusercontent.com/49641330/132223156-32dc2da2-1283-4234-a824-18ef9893aa4d.png)

Is there no way in V4.3?

BR

**Comment by bengschf** [comment]
Update: Is there no way to show the count of results in the verticals? In V3, this was possible

**Comment by wobba** [comment]
Closing as the issue is not following issue guidelines. And you are correct that this UX option is not developed for v4 yet.
