### ISSUE TITLE
On page column sorting not working if column is set to use handlebars expressions

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#1265]
**Version used**
4.3

**Describe the bug**
Using the list layout and when you check a column to have on-page sorting, the sorting up/down arrow is missing if the column is also set to use handlebars expressions.

**To Reproduce**
* Title is default sortable in the webpart, but no arrow showing. Uncheck "use handlebars expression" and the sorting option appears.

**Expected behavior**
I expect sorting and expressions to work independently.

**Screenshots**
![image](https://user-images.githubusercontent.com/51104/132250748-b877de72-d3fb-499f-9a7f-b195aa0d55a4.png)

**Comment by FranckyC** [comment]
Hi @wobba , according ot the documentation:

> Sortable: allows you to sort column values alphabetically when the column header is clicked (ascending or descending). The sort is done statically on the current page results set and works only when the column value **is not an Handlebars expression**.

What you describe is more like a UI bug because this is the expected behavior otherwise. Do I understand correctly? In this case, the sortable option should be disabled by default for the default 'Title' column you're right.

**Comment by wobba** [comment]
My bad. RTFM 🤩
