### ISSUE TITLE
Search Filters & Search Results break when lazy loading from header link.

### ISSUE THREAD

**Issue by Ludwixix** [microsoft-search/pnp-modern-search#1267]
**Version used**
4.3.0

**Describe the bug**
When a site is loaded via a header link which performs a lazy load. The Search Filters and Search Results web part break on the initial load and require the page to be refreshed before displaying correctly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Search Filters, Search Results and Search Box to a page. Ensure they are connected to each other.
2. Create a new a link in the OOTB quick links header to the site containing the PnP Search Web parts.
3. Click the link and observe the site containing the search web parts is lazy loaded.

**Expected behaviour**
Web Parts should load as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/40622681/132265099-1d9c8011-2fd3-496a-8d87-626ec8c25d20.png)

![image](https://user-images.githubusercontent.com/40622681/132265126-a219acdd-78a3-4738-9ba0-a64fb2498d45.png)

![image](https://user-images.githubusercontent.com/40622681/132265090-eb6f84d1-c578-4a2b-9e77-32c87863ffe1.png)

[PnPSearchErrorLog.log](https://github.com/microsoft-search/pnp-modern-search/files/7118002/PnPSearchErrorLog.log)

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
I have tried removing any custom mappings or configurations and the issue still occurred.

**Comment by FranckyC** [comment]
Hi @Ludwixix, unfortunately, I.m not able to reproduce your issue. I tested with both hub + site header links and both work. Is there anything special on your page/web parts configuration? Is the solution deployed globally or site collection scoped? Also, did you try in private mode?

Thanks!

**Comment by Ludwixix** [comment]
Hey Franky,

Thanks for the quick response.

I have tried incognito mode as well.

The tenant is using MCAS, so it's this may be causing some sort of issue, I'm still exploring this avenue.

**Comment by wobba** [comment]
@Ludwixix You have deployed web parts globally? You have search page on one site, and link from another site to it? Is that the repro steps?

**Comment by Ludwixix** [comment]
@wobba That's correct. We have search web parts on other sites which are linked to via the menu. When loading these sites via the menu on a freshly cleared cache we experience the error.

![image](https://user-images.githubusercontent.com/40622681/132774090-666daf17-4c0a-40bb-af47-fddb9da9d753.png)

**Comment by danielmargison** [comment]
Hi @wobba is there any update on this?

**Comment by wobba** [comment]
I can repro the scenario and will see if there's a good solution.

**Comment by wobba** [comment]
Fixed
