### ISSUE TITLE
Enterprise Keywords Search from a Document Library

### ISSUE THREAD

**Issue by lodohs** [microsoft-search/pnp-modern-search#1269]
Hello,

Sorry I've looked through existing issues and am not sure I could find one the same (but please direct me if this has already been answered).

I want to create a search which looks at just one particular document library on my site and which searches from the Enterprise Keywords column. Do you know if this is possible?

Many thanks

**Comment by wobba** [comment]
Put this as your query template using the SharePoint provider:

`Keywords:({searchTerms}) path:https://tenant.sharepoint.com/site/asite/Lists/MyList`

**Comment by lodohs** [comment]
Hello Wobba,

Thanks for your help.

So I inputted Keywords:({searchTerms}) path:**_my document library URL_** into the Query Template field.

However it did not work when searching.

I am selecting:
SharePoint Search
Result source ID: LocalSharePointResults
No refinement filters 
Use Input Query text - Dynamic Value - PnP Search Box - Search Query

I have not setup the filter yet as wanted to get the search working first.

If I put the GUID id for the document library in refinement filters it will only show me documents from that library however it always shows me the same documents no matter what keyword I search.

Many thanks

**Comment by wobba** [comment]
You should not put any guids anywhere, and don't put values into the refinement filters box. You need to know how that works before using it.

1. Pick the "debug" template to display results
2. Enter a query in the search box and search
3. Show us the output of the queryModification field, as that will quickly show if you have done the correct thing or not.
![image](https://user-images.githubusercontent.com/51104/132521639-b5b3b65c-4365-4e19-bea7-bd2cff54e889.png)

Here's a good tutorial https://searchexplained.com/set-up-pnp-search-page-sharepoint-online/

**Comment by lodohs** [comment]
Hello wobba,

Thanks again for all your help!!

So I setup as per the 'Search Explained' site just to make double sure and this is my query modification line:

"queryModification": "Keywords:(climate) path:https://orbispartnerships.sharepoint.com/sites/research_engagement_consultation/Shared%20Documents/Forms/AllItems.aspx -ContentClass=urn:content-class:SPSPeople",

So I inputted my URL as it appears at the top of the documentation library.

Thanks again!

**Comment by wobba** [comment]
You need to remove `/Forms/AllItems.aspx` from the path, similar to what I had as my list sample `https://orbispartnerships.sharepoint.com/sites/research_engagement_consultation/Shared%20Documents`

**Comment by lodohs** [comment]
Hello wobba,

Thanks for this however I'm still returning no results :(

"queryModification": "Keywords:(climate) path:https://orbispartnerships.sharepoint.com/sites/research_engagement_consultation/Shared%20Documents -ContentClass=urn:content-class:SPSPeople",

![image](https://user-images.githubusercontent.com/90253486/132647862-23569517-eb63-47ae-b2ae-b541307b317c.png)

**Comment by lodohs** [comment]
Hello,
I checked on another site and someone just recommended the below which has worked for me

path:https://orbispartnerships.sharepoint.com/sites/research_engagement_consultation/Shared%20Documents
{searchTerms}

Thanks,
Louise

**Comment by wobba** [comment]
That one is ok.. but if you only want to target enterprise keywords you need to query on the `Keywords` property. And you should of course check that it has values.
