### ISSUE TITLE
Container Tree

### ISSUE THREAD

**Issue by Jis-collab** [microsoft-search/pnp-modern-search#1270]
**Version used**
3.14.1.0

**Question**
I am using the Container Tree as a Refiner template to show folder structures.
My document library has around 237 items excluding the folder count.
But the refiner shows the count as ( 66 ) at level 1 and the  below levels [see screen shot].
and also it doesn't show the second folder i have at the level1.

where as another document library with no folder structure shows the correct count (293) (in my example)
Can i know how is the item count works here?

**Screenshots**
![image](https://user-images.githubusercontent.com/77057389/132332462-93161da2-62db-4516-b2bb-b00a3fb00d62.png)

**Additional context**
Add any other context which is helpful to understand the question.

**Comment by FranckyC** [comment]
Hi @Jis-collab , the 'Tree container' doesn't support empty folders. I think that explains why the count is not correct.

**Comment by Jis-collab** [comment]
Ok , but there is a huge difference in terms of the count even if empty folders are not shown. 
In my scenario ,
Of the 281 items in the library there are only 44 folders are present.
And none of the folders are empty it has either subfolders or files.

**Comment by FranckyC** [comment]
Ok I update what I said, the 'Tree container' doesn't support folders where there is no files (only folders for instance). This template actually doesn't read anything in the library. It just deduce a tree hierarchy based on a list of paths. Unfortunately, we can't do much to get accurate counts as it is not linked to the underlying library.

**Comment by Jis-collab** [comment]
Ok. I had the question as the count in brackets (66) creates a confusion especially because its part of the Search. Its good to have the result count.
Is there a way to remove them ?

**Comment by wobba** [comment]
For v3 the counts are hard coded to show today. You can log an issue for an change.
