### ISSUE TITLE
Property not available in manage column section

### ISSUE THREAD

**Issue by davemehr** [microsoft-search/pnp-modern-search#1273]
**Version used**
Ex: 4.3

**Describe the bug**
I use a mapped RefinableString100 managed property. I would like to use this property in the details list layout (PnP - Search Results; Page 2) in the layout options section under "Manage columns", to show this values in the search results. But i can choose this values in the drop down. I have added this values under "selectes properties". 
As test, i have deleted the results webpart and added this webpart new, but same.

**To Reproduce**
1. add results webpart
2. add managed property to selected properties
3. choose Details List layout
4. Edit Manage columns
5. add the property in "Column value" > not available

**Expected behavior**

**Screenshots**
![pnp modern search v4 selected properties](https://user-images.githubusercontent.com/65955023/132460597-1aea07e0-2e1e-4534-b2d3-69396da60a57.png)

![pnp modern search v4 manage columns](https://user-images.githubusercontent.com/65955023/132460603-7efc2529-c1e8-4c0c-8d6b-422f99946b77.png)

**Desktop**
 - Browser: MS Edge

**Comment by wobba** [comment]
When adding a new property you need to overwrite the comma list and type the new name, and click ENTER. Then select it in the dropdown afterwards. It's very quirky and the next version will allow pasting a comma list into the box.

Also, the mp picker require you to have a result with values coming back for the property to show (if I remember correctly).

**Comment by davemehr** [comment]
With your described procedure it works fine. I can add the additional properties to the list layout. Thank you @wobba 

![modern search v4](https://user-images.githubusercontent.com/65955023/132525770-c7d02b43-6da2-4f9d-b5b5-013b14053120.png)

**Comment by wobba** [comment]
Glad you solved it and we should improve on the docs or how this works. We could in theory copy props from slots to the list of requested properties.
