### ISSUE TITLE
Search Results webpart enabling audience targeting

### ISSUE THREAD

**Issue by agilbull** [microsoft-search/pnp-modern-search#1275]
Hi, 

I can't figure out the difference between audience targeting on and off on my search results. Only the order is changing. 
How could I get result based only on audience?

Thank you

**Comment by wobba** [comment]
Closed as issue template was not followed to be able to provide information. Did you read about audience targeting in the docs at https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/sharepoint-search/ and the official Microsoft docs?

**Comment by agilbull** [comment]
Yes I red the docs. May be I didn't understand everything. Using this webpart seems to be a good equivalent to the content query webpart form sharepoint 2010 because, you can search only on one  content type in one site  and sort...

**Comment by wobba** [comment]
That works.. and audience targeting works similar to audience targeting in the out of the box modern web parts. It's a replacement for the content by search web part, not the content query web part.

**Comment by agilbull** [comment]
You're wright. I just tought that audience targeted content would only be shown. Customize the search result webpart is easy so I wanted to use it this way.
