### ISSUE TITLE
Ability to set the web part properties from an external file in json format

### ISSUE THREAD

**Issue by coupalm** [microsoft-search/pnp-modern-search#128]
New feature request:
Ability to set the webpart properties (other than the result layout for the search result webpart) from an external file in json format.

Business Case:
I've created a site pages template that is using the modern search webparts. The search result webpart is using the page properties to construct a dynamic query.

Users are creating new pages from this template and set the page properties according to what they want to display in the search results.

If I need to update this dynamic query, I need to go into each pages to update the query. It would be easier to just change one external file that would contains the webpart configuration (like the result layout).

Thanks.

**Comment by FranckyC** [comment]
Hi @coupalm I understand the case but why not doing it progammatically using PnP ClientSidePage cmdlets for instance? I close it for now since there are workaround on this.
