### ISSUE TITLE
PNP - Modern Search Result - Add more option in 'manage field people'

### ISSUE THREAD

**Issue by AnderOllive** [microsoft-search/pnp-modern-search#1280]
**Version used**
Ex: 4.3

**Question**
How do add more options in manage People fields(template People), in pnp modern search results.

**Additional context**
I need add more one field in manage people field.
I have all options filled
But in  JASON I add more one option, this option appears in manage people field. I can choose what I want, but not appear in results.
Screenshot bellow, show better my question

**Screenshots**
5 field in manage people field (default)

![image](https://user-images.githubusercontent.com/88772391/132660984-ef28ca3d-5c7e-4f08-9843-3bfb6dc39e99.png)

In JASON, I add more one option and appear in manage people field, now I have 6 option.

![image](https://user-images.githubusercontent.com/88772391/132661251-03805d41-ba29-486d-8db3-7a3ba9681783.png)
_illustrative picture_
![image](https://user-images.githubusercontent.com/88772391/132661475-f254e02f-0b2b-4b4c-9c83-eddfdbc90ad6.png)

But in Results, no show this option. (added field to appear email - {{getUserEmail (slot item @root.slots.UserEmail)}}
![image](https://user-images.githubusercontent.com/88772391/132661747-ab753e54-5b93-45d9-9c7f-7b934b20e98f.png)

**Comment by FranckyC** [comment]
Hi @AnderOllive. this component uses the 'Persona' Office UI Fluent control. According to its documentation regarding the optional text https://developer.microsoft.com/en-us/fluentui#/controls/web/persona:

> Optional text to display, usually a custom message set. The optional text will only be shown when using size100. 

Where size 100 = 'Extra large' in the Web Part settings. Did you try this size? 

Also, did you make sure there is actually a value in the slot you use?

**Comment by AnderOllive** [comment]
> Hi @AnderOllive. this component uses the 'Persona' Office UI Fluent control. According to its documentation regarding the optional text https://developer.microsoft.com/en-us/fluentui#/controls/web/persona:
> 
> > Optional text to display, usually a custom message set. The optional text will only be shown when using size100.
> 
> Where size 100 = 'Extra large' in the Web Part settings. Did you try this size?
> 
> Also, did you make sure there is actually a value in the slot you use?

Hi @FranckyC I'm using extra large option in persona template
![image](https://user-images.githubusercontent.com/88772391/133052299-381e1007-6422-41d1-948a-8d09ea0ed1de.png)

And this option chosen has value.
![image](https://user-images.githubusercontent.com/88772391/133052565-13f60443-1c79-411f-83a5-34af417d7dc6.png)

If i choice only 5 options, include 'department', this value appear normal, but if i add extra option, how to mentioned above, not appears 'department' in card.

**Comment by wobba** [comment]
The persona card component from fluent UI only support the options we have defined. See the supported fields at https://docs.microsoft.com/en-us/javascript/api/react/ipersonaprops?view=office-ui-fabric-react-latest

If you want more you need to create a fully custom template - not using the people layout.

**Comment by AnderOllive** [comment]
_Many thanks @wobba and @FranckyC I will make tests. More one time, I'm grateful for your help._
