### ISSUE TITLE
Managed Card Fields - linking to RefinableString

### ISSUE THREAD

**Issue by lodohs** [microsoft-search/pnp-modern-search#1281]
Hello,

Hope you are well.

So not a question on how to setup crawled/managed properties but just once they are already setup I have a question.

Within 'Manage Card Fields' can I point my field to a RefinableString property instead of a slot?

So for my document library the automatic date is the date I added them to the library however I was adding historical files so have made my own 'Date Produced' column with the month and year as text.

I would like to add this to display under the Authors name on the card (so presumably adding to the existing date field value).

Any help would be greatly appreciated.

Thanks!

**Comment by FranckyC** [comment]
Hi @lodohs,

> Within 'Manage Card Fields' can I point my field to a RefinableString property instead of a slot?

Yes.

> I would like to add this to display under the Authors name on the card (so presumably adding to the existing date field value).


The only places in the card where you can add your own HTML with your own values are 'Tags' and 'Location' placeholders. Except that, what you can do is simply replace the default value for other fields:

![image](https://user-images.githubusercontent.com/5659122/132884830-dc03a6c9-c349-4d17-8d75-d5c18f8e8d52.png)

If you really want to create your own card layout, you can still create a custom web component: https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_web_component/

**Comment by lodohs** [comment]
Hello FranckyC,

Thanks for this. 

Updating the 'Tags' section sounds like my best best. Do you have a link to the best instructions on which handlebars expression/HTML I should use to get the field to point to my RefinableString?

Thanks,
Louise

**Comment by FranckyC** [comment]
You can simply edit the Handlebars expression in the fields configuration and use either a [slot](https://microsoft-search.github.io/pnp-modern-search/usage/search-results/slots/) or your `RefinableString` field directly. See https://microsoft-search.github.io/pnp-modern-search/usage/search-results/layouts/#cards
