### ISSUE TITLE
DisplayAuthor confusion

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft-search/pnp-modern-search#1283]
### Check existing issues before logging new ones
In issue [1234](https://github.com/microsoft-search/pnp-modern-search/issues/1234) You solved my problem of never seeing filter by author (I tried the refinable and anything. only "DisplayAuthor" shows the selection.

**Version used**
Ex: 4.3

**Question**
The issue that I see is that "DisplayAuthor" actualy holds more than  one name for some reason. (see screen)
So if I chose "Reed, Jessica" I get all the documents that include her name.

I thought there was only one "Created By" (Author) for each document.

**Screenshots**
![image](https://user-images.githubusercontent.com/5054931/132899274-d4189359-8eba-4210-b16f-0c7356954f51.png)
![image](https://user-images.githubusercontent.com/5054931/132899426-62a6d339-ef0d-453c-8283-5d08da8fa55b.png)

Thank you much

**Comment by wobba** [comment]
`DisplayAuthor` is not a good property to use. I might blog why `DisplayAuthor` is a bad one. You need to think about which person value you want to show, and then figure out how to make that happen. EditorOWSUser and AuthorOWSUser are two you can use, but you need to do some formatting.

**Comment by Ofer-Gal** [comment]
How can I do formatting in the "Edit filters"?
When I choose AuthorOWSUser in the first row
![image](https://user-images.githubusercontent.com/5054931/132995092-72981504-0a26-42b2-8625-4b57ade4eb43.png)
The panel does not even show an Author DropDown
![image](https://user-images.githubusercontent.com/5054931/132995124-d4cd1f75-4689-4cf1-9959-a7f44330c696.png)

In the custom layout, I do 
`<mgt-person person-query="{{#with (split (slot item @root.slots.Author) '|')}}{{[0]}}{{/with}}"
 person-presence="true" view="OneLine" person-card="hover" fallback-details='{}'>
 </mgt-person>`
And I can show just name with
`{{#with (split (slot item @root.slots.Author) '|')}}{{[1]}}{{/with}}`
But How can this be used to show author filter?

**Comment by wobba** [comment]
You need to use a custom refinement render template. https://microsoft-search.github.io/pnp-modern-search/usage/search-filters/layouts/#custom In this you can massage data.

And you keep mixing screenshots of results and filters. Not all properies can be used as filters.

AuthorOWSUser is for example not refinable. If you consider Created By user as the Author, map `Office:4` to a refinablestring managed property and use that.

**Comment by Ofer-Gal** [comment]
First of all, thanks for answering on a Sunday much appreciated.
Did you mean like this:
![image](https://user-images.githubusercontent.com/5054931/132997915-c0ffab82-e994-4042-afaa-dce135dce054.png)
Then in the filters
![image](https://user-images.githubusercontent.com/5054931/132997985-9d0a7957-6ecc-40a4-9e6e-05afd1244dd6.png)
?
I know it will take time for the mapping to take effect, so I will check later
The only explanation to Office:n I found is in:
https://{tenant}-admin.sharepoint.com/_layouts/15/searchadmin/ta_listcrawledproperties.aspx?level=tenant
Is there a better explanation anywhere?

I will read about the "custom refinement render"

Thank you again.

**Comment by Ofer-Gal** [comment]
Office:4 Works like a charm 
Thanks

**Comment by josy1024** [comment]
dear @wobba,
I've got a Custom Lookup Field Colum mapped to Searchable (ows_Country => RefinableString00). => **WORKS GREAT!**
how can i display the Lookup Field in Search Results?
define with slots or access direct? - are there any best Practices?
{{slot item @root.slots.RefinableString00}}

**Comment by Ofer-Gal** [comment]
@josy1024 , try once with the debug view, you may find your answer there

**Comment by wobba** [comment]
Either via slots or directly from the item. I think I would go with the direct approach `item.RefinableString00` unless you want to name the slot with something more recognizable.

**Comment by josy1024** [comment]
> @Ofer-Gal 
> @wobba HOW to substring in Results Template? - or is this Possible at the SLOT def?
-- toLowerCase(substring(@currentField.lookupValue,7,9)) --

Summary: This was Working for me:
* ADD A SLOT: Country => RefinableString00
* **ADD Property in "Select Properties"**: RefinableString00 => Then it shows up in debug!
* Edit results template: {{slot item @root.slots.Country}}

**Comment by wobba** [comment]
Take a look at e.g. https://github.com/helpers/handlebars-helpers#string for available handlebar functions.

**Comment by josy1024** [comment]
GOT THE REPLACE WORKING in "LOCATION" thanks @wobba!
MY CODE:
from: {{slot item @root.slots.CustomPL}} to =>
`{{replace (slot item @root.slots.CustomPL) "https://tenant.sharepoint.com" ""}}"`

Put all Together:
### ADD SLOTS:
CustomDL DocumentLink
CustomPL ParentLink

### MANAGE CARD FIELD:
Location
```
<a style="color:{{@root.theme.palette.themePrimary}};font-weight:600;font-family:'{{@root.theme.fonts.small.fontFamily}}'" href="{{SPSiteUrl}}">{{SiteTitle}}</a>

<br><a href="{{slot item @root.slots.CustomPL}}/?id={{replace (slot item @root.slots.CustomDL) "https://tenant.sharepoint.com" ""}}&parent={{replace (slot item @root.slots.CustomPL) "https://tenant.sharepoint.com" ""}}">Preview</a>

```
