### ISSUE TITLE
Error: Idle tracking cookie is missing when select manage people fields -> drop down menu on JobTitle

### ISSUE THREAD

**Issue by jsonp80** [microsoft-search/pnp-modern-search#1284]
Check existing issues before logging new ones

Version used
4.3

Describe the bug
The drop-down is not populating column to select under manage people fields -> drop down menu on JobTitle

To Reproduce
1. Add search result wp
2. edit webpart
3. click next to 2 of 4
4. click on "Manage people fields"
5. try to select dropdown of JobTitle or WorkPhone or any fields that doesn't have use Handlebars expression

**Screenshots**
![image](https://user-images.githubusercontent.com/52767314/132901593-34eea725-5bfa-4e7c-a402-cd7b43aeab2d.png)

 - Browser: chrome, ie, edge all does the same

**Comment by FranckyC** [comment]
Hi @jsonp80, the values in the drop down depends on the current displayed results and is here to help you to choose a valid property. If you don't have any results, you don't see the available properties. This is the expected behavior.

**Comment by wobba** [comment]
Closing as it's the expected behavior, and we we agree the docs/instructions can be improved here.

1. Ensure you add the property you want as retrieved properties
2. Ensure you have results showing in Edit mode
3. Then the list should show available properties
