### ISSUE TITLE
Few user's requests

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft-search/pnp-modern-search#1285]
**Is your feature request related to a problem? Please describe.**

1. Can't have a user choice of filters.
2. Can't have the Search Results feed {searchTerms} from both the query string and a search filter

**Describe the solution you'd like**

1. My users want to be able to choose to enter either Date interval or date range and only then filtering.
2. My users would like to filter the results further with additional "Containing text"

**Describe alternatives you've considered**

1. Tried adding both but only one showing
2. I will try to add a web part that will have an Input box that will add its content to the query string

**Comment by wobba** [comment]
If you for 1 mean the user should be able to edit and pick which filters to show - then this out of scope, and not sure what this would look like. Feel free to expand? And for 2 you can pick up a query string parameter and use that in your query template together with {searchTerms} just fine. E.g. `{searchTerms} {QueryString.foo} `. https://microsoft-search.github.io/pnp-modern-search/usage/search-results/tokens/#context-tokens

**Comment by Ofer-Gal** [comment]
For 1 I just wanted the user to choose if he want to filter by the OOB Date intervals or by entering any date range. Not a real deal breaker.  using Date intervals should be enough.  
For 2, your `{searchTerms} {QueryString.foo}` advice is great. I will use it but there are few small caveats.
the "Connect to source" must be "PnP search box" and then the "Show results count" only shows the count when there is something entered in the "PnP search box" not the initial results from the query string.
Again, very minor, I will adopt as is and I think my uses will be happy.

Thank you much.

**Comment by wobba** [comment]
You can try to create custom filter template which combine `<pnp-filterdaterange>` and `<pnp-filterdateinterval>` as one.

Something like this fragment (note tested)
```
<div class="filter--value">
	<pnp-filterdateinterval 
		data-instance-id="{{@root.instanceId}}" 
		data-filter="{{JSONstringify filter 2}}"
		data-theme-variant="{{JSONstringify @root.theme}}"
	>
	</pnp-filterdateinterval>
	<pnp-filterdaterange 
		data-instance-id="{{@root.instanceId}}" 
		data-filter="{{JSONstringify filter 2}}"
		data-theme-variant="{{JSONstringify @root.theme}}"
	>
	</pnp-filterdaterange>
</div>
```

Take a look at for example https://github.com/microsoft-search/pnp-modern-search/blob/main/search-parts/src/layouts/filters/horizontal/horizontal.html which is the horizontal layout being used and you can find similar ones for the other templates. And you can build your own.

**Comment by Ofer-Gal** [comment]
I will give it a try
Thanks
