### ISSUE TITLE
PNP search results - Show only events

### ISSUE THREAD

**Issue by AnderOllive** [microsoft-search/pnp-modern-search#1286]
**Version used**
4.3

**Question**
Guys, I need configure PNP modern search results, to only show events. But I cannot configure this option. I have events in several sites and all events are connected in hub site. I need show all events in modern search result, I tried many configuration, but whitout success

**Screenshots**

![image](https://user-images.githubusercontent.com/88772391/133086379-92dcc692-3d92-44b7-886b-a78f73148eae.png)

I don't know what option using in Result source ID and if I need configure more something.

**Comment by wobba** [comment]
Use LocalSharePointResults and in the query template try something like:

`{searchTerms} SPContentType=Event` or `{searchTerms} ContentTypeID:0x0102*`

It's a matter of knowing how SharePoint settings make their way to the search index as different metadata.

**Comment by wobba** [comment]
We should probably add some docs on typical examples. Not hard to know without SP search experience.
