### ISSUE TITLE
Selected Properties Not Loading 

### ISSUE THREAD

**Issue by cajetan77** [microsoft-search/pnp-modern-search#1289]
**Version used**
Ex: 3.18.0

**Question**
When trying to select managed properties in the Pnp Search the managed properties just load  and does not provide the properties
**Screenshots**
![image](https://user-images.githubusercontent.com/26503913/133187531-c2749191-5787-4d33-90af-ac902d95e4ce.png)

**Comment by wobba** [comment]
We cannot control the API to retrieve managed properties as it's not a real or documented API. You can also manually type in a sortable/refinable managed property name you have content in.
