### ISSUE TITLE
Search Refiner not showing column name 

### ISSUE THREAD

**Issue by spo365** [microsoft-search/pnp-modern-search#129]
As i have selected 2 refiner Created Date and Size of the file but in filter section it shows one column name which is Created Date other refiner Size of the file is missing.

![image](https://user-images.githubusercontent.com/5062256/76618658-356ee980-657d-11ea-9941-ae90d9e56412.png)

**Comment by FranckyC** [comment]
Hi @spo365 Good catch, I can see the error. Will be fixed in the next release.

**Comment by FranckyC** [comment]
Should be resolved by #147. Let me know if it works for you. Thanks!

**Comment by spo365** [comment]
Thanks :) will let you know.
