### ISSUE TITLE
Sorting of entries in filter

### ISSUE THREAD

**Issue by HeKr09** [microsoft-search/pnp-modern-search#1293]
**Version used**
4.1

**Question**
I have several entries within a filter. For example: EN, US, DE, ES, MX and so on. And I have another filter value called "_Group". This one is placed at top within the term store sorted alphabetically.
But in the search it is at the bottom.
So in the term store it is sorted:
1. _Group
2. DE
3. EN
4. ES
5. MX
6. US

But in the search filter it is sorted:
1. DE
2. EN
3. ES
4. MX
5. US
6. _Group

Can anybody tell me why?

**Comment by wobba** [comment]
We're using lodash _sortBy so I attribute this to how this function handles sorting. https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L9929

**Comment by FranckyC** [comment]
Hi @HeKr09, filter values sort order is independant from the term set order (custom or default). The values order is determined according to the filter configuration ('By name' or 'By count'):

![image](https://user-images.githubusercontent.com/5659122/133442030-a60136bd-961c-48ef-a18b-44e57aa11401.png)
