### ISSUE TITLE
Accessible name is not provided for the interactive element (search button) on PnP search box - V4.2.2.0

### ISSUE THREAD

**Issue by MariaAug** [microsoft-search/pnp-modern-search#1295]
Screen reader using NVDA speech viewer is reading the search button (Forward icon next to clear icon) as button. Instead it should read out as Search button so that the user would be able to understand. 

![SearchBox-AccessibilityIssue](https://user-images.githubusercontent.com/90712499/133294237-69f2f829-9d1f-4cf8-add9-08b80ab0df58.jpg)

**Comment by wobba** [comment]
Closed as it does not follow issue templates to provide version information etc.
