### ISSUE TITLE
Filter showing multi people field as one value

### ISSUE THREAD

**Issue by HeKr09** [microsoft-search/pnp-modern-search#1297]
**Version used**
4.1

**Describe the bug**
I am mapping an multi user field of a list to a RefinableString (also multi values) in the search service application.
In the filter webpart I am using this RefinableString also as MultiValue.
But there are entries shown as:
- User1
- User1;User2
- User2
- User3

**Expected behavior**
I expect that the users are divided so that you have the following result.
- User1
- User2
- User3

**Desktop (please complete the following information):**
 - Chrome

**Comment by wobba** [comment]
The web parts respect the data coming back on the response. If it's not coming back as you expect it's an API issue.
