### ISSUE TITLE
Search textbox look and feel

### ISSUE THREAD

**Issue by srinivastd** [microsoft-search/pnp-modern-search#1299]
What is the best way to change the look/feel of the search textbox? Basic things like increase the height of the textbox, make the edges curved.

Version used:4.2.3

**Comment by FranckyC** [comment]
Hi @srinivastd, short answer, you can't for now. However, you can create your own SPFx Web Part and plug it to the Search Results Web Part.

**Comment by srinivastd** [comment]
Thanks @FranckyC  for the quick response.

**Comment by srinivastd** [comment]
Hi Franck -  Does the current SPFx support just adjustment to height of the
search box?

**Comment by FranckyC** [comment]
Hi @srinivastd, no unfortunately
