### ISSUE TITLE
SharePoint Online people search doesn't work on mobile

### ISSUE THREAD

**Issue by erkanch** [microsoft-search/pnp-modern-search#1300]
I realize this may not be the best platform to report this issue but I'm hoping someone from Microsoft like @wobba will see this. The people tab in modern search doesn't work on mobile devices. We tried in 2 tenants using iOS and Android and they all fail. I've checked using browserstack as well and it can be reproduced. Below you can see the call that fails.
![peoplesearch](https://user-images.githubusercontent.com/55555837/133457251-dce685b2-12a5-40b6-932a-366dd3e2a5a9.png)

**Comment by wobba** [comment]
Closing as off-topic for this project. Use official support channels for product issues.
