### ISSUE TITLE
Is there more information on the "auto" prefix?

### ISSUE THREAD

**Issue by corriespondent** [microsoft-search/pnp-modern-search#1301]
**Version used**
4.2.1

**Question**
The layout slots refer to AutoPreviewImageUrl and AutoPreviewUrl, and I recently came across Autoowstaxidmetadataalltagsinfo. Is there any information on what the Auto prefix does and when you would use it?

**Screenshots**
![image](https://user-images.githubusercontent.com/23064475/133509370-afaa5eef-c1dd-4283-8292-064257017500.png)

**Comment by popeadam** [comment]
To get the 'Auto' prefix to appear on other properties, you'll need to enable localisation. Once done, you can add this to the 'Slot field'. If you then use the 'Card' or 'List' or 'Details' layouts, the tag metadata for the items in the results should come through without the TermID. Form the [docs](https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/):

> To use translated values in your template, you must use the 'Auto + <property_name>' property format instead of the original property name. For instance, to use translated values of the 'owstaxidmetadataalltagsinfo' property, you must use the 'Autoowstaxidmetadataalltagsinfo' auto created property.

I have struggled with implementing this using v4.2.3 however; if I use owstaxidmetadataalltagsinfo in the 'Tags' slot, the values come through correctly but untranslated (ie; TermID|Label); but if I use Autoowstaxidmetadataalltagsinfo then the tags for one result appear to duplicate themselves across all the results on the page:
![image](https://user-images.githubusercontent.com/54813914/133792879-e393bad4-32e8-4331-93bb-a23a4da3ab55.png)

**Comment by corriespondent** [comment]
@popeadam Do you understand if there is a related reason for having Auto before the preview url properties? I have not found documentation about what properties might allow for an Auto prefix and what it is even for.

**Comment by corriespondent** [comment]
@popeadam I had success using Autoowstaxidmetadataalltagsinfo to display the translated tags properly. They showed the tags that they were meant to show:

![image](https://user-images.githubusercontent.com/23064475/133801520-103c5d73-efa0-41cd-b22b-1379082cf4b0.png)

All I did was 1) enable localization and 2) use the Autoowstaxidmetadataalltagsinfo for the Tags layout slot.

**Comment by wobba** [comment]
The Auto is for the thumbnail and preview features as we have logic in place piecing together data from several properties to get a valid one. See https://microsoft-search.github.io/pnp-modern-search/usage/search-results/slots/#builtin-slots
