### ISSUE TITLE
Is it possible to specify a specific folder as the search range?

### ISSUE THREAD

**Issue by rikyo233** [microsoft-search/pnp-modern-search#1302]
**Version used**
Ex: 4.2

**Question**
I set the pnp search box and Search Results in my page
Is it possible to specify a specific folder as the search range?

**Screenshots**

**Additional context**
I set this but does not work.
`{searchTerms}path:"https://test.sharepoint.com/sites/portal/Shared%Documents/<foldername>"`

**Comment by FranckyC** [comment]
Hi @rikyo233, it should work using the wildcard character (*) at the end of the `Path` expression:

{searchTerms} Path:"https://test.sharepoint.com/sites/portal/Shared%Documents/<foldername>*"

Please make sure there is a whitespace between `{searchTerms}` and `Path`

**Comment by rikyo233** [comment]
Hi @FranckyC 
It is worked. thankyou!
But I want to search in the folder under the document library not in entire document library.Is there a way to do this?

And Is it possible to  not show results in the searchresult unless you search keyword in searchbox?
Currently, no keywords are entered, but all results be displayed.

**Comment by Laul0** [comment]
Hi @rikyo233,

1. You can specify several path in your query like this: `{searchTerms} path:"{site.absoluteUrl}/Shared Documents" OR path:"{site.absoluteUrl}/SitePages" (contentclass:STS_ListItem)`
2. By default, if no search keyword is specified, it is such as if your choose to display everything. You can specify a default value in the Search Result (a value that does not match with anything) and toggle the option `Hide this web part if there's nothing to show`.
  Example:
    <img width="327" alt="Screen Shot 2021-09-17 at 11 45 39" src="https://user-images.githubusercontent.com/15279205/133817160-257fb3e1-b6f6-4640-85c8-104d0cb37518.png">

**Comment by rikyo233** [comment]
@Laul0 Hi
About 1:Perfect!!! Thank you!!!
About 2:It is worked but when I delete the keyword the searchresult keep the result. Can I fix about it?

keyword :
![image](https://user-images.githubusercontent.com/87470199/134101645-104498be-0f8c-4abf-a383-33ca09c8455b.png)

Delete keyword :
![image](https://user-images.githubusercontent.com/87470199/134101739-bc537e64-d76e-4d6a-84af-4fdf574f501f.png)

**Comment by wobba** [comment]
We don't have an option where we trigger search when you remove everything in the search box - as it's not "search as you type". This aligns with OOB search box behavior as well.

**Comment by rikyo233** [comment]
OK Thank you!!! 
It's enough for me.
