### ISSUE TITLE
pnp search v4 Filters deep links

### ISSUE THREAD

**Issue by RezaMatin** [microsoft-search/pnp-modern-search#1307]
I'm trying to use Filters deep links in v4, nothing happening,
https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-results/#filters-deep-links

any suggestion? thanks

**Comment by FranckyC** [comment]
Hi @RezaMatin , deep links are not supported for v4 yet.

**Comment by RezaMatin** [comment]
thanks :-)
