### ISSUE TITLE
People pop up when clicking person

### ISSUE THREAD

**Issue by HamEv** [microsoft-search/pnp-modern-search#1308]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see the person card implemented in people view. If you combare that to the people information which is shown in sharepoint by default, it's quite ugly.

**Describe the solution you'd like**
When I click on a user in search web part (people layout) I would like to get the following popup:
![image](https://user-images.githubusercontent.com/61208008/133669178-b89338ac-f99f-4cf0-8859-fd97c82907c4.png)

Is there any possiblility to achive that now?

**Comment by Laul0** [comment]
Hi @HamEv,

The OOTB person card cannot be reused for the components of the Search, this is why is not the same.
In addition, the framework that currently allows displaying a persona card is Graph Toolkit: https://docs.microsoft.com/en-us/graph/toolkit/components/person-card

If the default design does not match your needs, you can edit the solution to change the card in accordance with your needs.

If you cannot make the change, it is necessary to wait for a charitable soul 😇

**Comment by wobba** [comment]
@HamEv There is no supported way to call into the People card of the host app, so using the Graph Toolkit is the best we can do. If such an option will became available (and I've tried to get it for the past two years), then we'll snap to it.
