### ISSUE TITLE
Search Filters v4 - not showing correct count

### ISSUE THREAD

**Issue by clayjam** [microsoft-search/pnp-modern-search#1309]
**Version used**
Ex: 4.3.0

**Describe the bug**
The Search Filter isn't showing the correct counts as shown in the image. You can see that Civil and Construction both have have two documents but the web part shows a count of 1 for both.

![image](https://user-images.githubusercontent.com/29591956/133714308-5439048d-05a4-4f76-a248-b968d999b64e.png)

**To Reproduce**
1. Add a Search Results and Filter web part
2. Configure both web parts to show custom managed properties
3. Perform a search and the filter web part count is incorrect
4. See image above

**Expected behavior**
The count should be correct to what is displaying in the Search Results Web Part

**Screenshots**
![image](https://user-images.githubusercontent.com/29591956/133714639-ea9718e0-697e-4e5c-9c9a-d2fcaa8ccc14.png)

**Desktop (please complete the following information):**
 - Browser Microsoft Edge
 

**UPDATE**
I reindexed the library and it has sorted itself out and is now showing correctly.

**Comment by FranckyC** [comment]
I'll clise this issue then.
