### ISSUE TITLE
Support for UTC time in tokens

### ISSUE THREAD

**Issue by ellinge** [microsoft-search/pnp-modern-search#1311]
I found a special case today in which I filtered a start and end date for events.

The tokens for {Today} etc. only seems to work with the browsers current time zone. Since SharePoint stores the dates in UTC format there's a mismatch when filtering on dates with {Today}.

E.g.
The search index result (08:00 - 12:00 locally/in SharePoint GUI)
```
  "RefinableDate00": "2021-09-17T06:00:00Z",
  "RefinableDate01": "2021-09-17T10:00:00Z",
```
And using RefinableDate00<={Today+14} RefinableDate01>{Today} gives (matches current local time):
RefinableDate00<=2021-10-01\nRefinableDate01>2021-09-17T10:59:26Z

If I change to >={Today-0} everything is fine, a.k.a there's a search result match, since the time is dropped so everything worked for this scenario. But for future troubles with more detail on time this should be a possibility to change.

A proposal is to introduce more tokens with UTC as a suffix which uses getUTCDate etc instead in case of the presence of this suffix. This could be included in the current regexps as an optional which changes which methods get called in the token replacements.

https://github.com/microsoft-search/pnp-modern-search/blob/b78aba6323a9d12ae2cca39f709f933d0f3f1746/search-parts/src/services/tokenService/TokenService.ts#L377

Not sure if it's supposed to but any +/- drops the time in the replacement. But it looks as if the time is expected in formatDate.

**Comment by wobba** [comment]
Question. What do you expect to be the behavior when using {Today}? Items from 00:00->23:59 in Z time, or in the users locale?

**Comment by ellinge** [comment]
Actually I thought {Today} would match what Sharepoint index uses for date (UTC/Z). But since that is not the case and that would be a breaking change the separate UTC-tokens would suffice I guess?

But it seems to be replaced with a Z-format which should be UTC so yeah I guess it’s a bug more.

**Comment by ellinge** [comment]
It’s also teoretically interesting what the other date-tokens should match. When between time zones. When filtering items on CurrentXXX some are actually could be wrongly filtered in/out.

**Comment by wobba** [comment]
I changed the code to take the current UTC time when evaluating the date, to match with what the index uses.
