### ISSUE TITLE
PNP Search Results - Doubts about how to show events page

### ISSUE THREAD

**Issue by AnderOllive** [microsoft-search/pnp-modern-search#1312]
**Version used**
Ex: 4.3

**Question**
I created events and I want to people click in link title and I want open the page of events where was created, but when click in this link, show me the page of the event how to list. Images below

**Screenshots**

I have this event configured in my pnp search modern results, option template (card)
![image](https://user-images.githubusercontent.com/88772391/133768464-f059d53d-517c-45c9-a693-ea3f4b690bf2.png)

By clicking on the title of this link, I would like to see it like this.
![image](https://user-images.githubusercontent.com/88772391/133769062-306c0756-fed0-4f71-8fc5-abb8b27eebe1.png)

But in card manage fields, i choose some options :
{{slot item @root.slots.SitePath}}
AutoPreviewUrl
Path
and other options, but all options appear only this format when click in the title link.

![image](https://user-images.githubusercontent.com/88772391/133770369-a4d45b6e-b046-405c-b792-512804392da3.png)

**Comment by Laul0** [comment]
Hi @AnderOllive,

This behavior is totally normal.
The search returns an event - an event is a list item and not a page - the display that you want is an OOTB event form provided by Microsoft.

The item path returns the URL to the list item (`Lists/Events/DispForm.aspx`) and not to the `_layouts/15/Event.aspx` page.

You need to edit the Template to have an URL like this: `/_layouts/15/Event.aspx?ListGuid=[ListId]&ItemId=[ListItemID]`.

Here, the steps:
1. Add `ListItemID` to the Selected Properties
2. Edit Layouts Slots and replace `NormUniqueId` by `ListItemID`
3. From the `Edit Result Type`, add:
    | Data source field |  Operator | Condition Value | Inline Template |
    |------------------|-----------|-----------------|----------------|
    | contentclass | Equals | STS_ListItem_Events | Replace `data-href` value with `{{item.SPSiteUrl}}/_layouts/15/Event.aspx?ListGuid={{slot item @root.slots.ListId}}&ItemId={{slot item @root.slots.ItemId}}`  |
4. Save and enjoy 😉

**Comment by AnderOllive** [comment]
@Laul0 Thank you my friend, great solution. Working perfectly, thank you very much and have a nice day.
