### ISSUE TITLE
PnP Search Bar Incorrect Date in Search Bar returns all items in tenant.

### ISSUE THREAD

**Issue by chriswilper** [microsoft-search/pnp-modern-search#1316]
We configured a RefinableDate00 to a custom column ctmDateIn.  The RefinableDate was created with a alias of "DateIn".  Then we configured the search web part to only return documents from a single site collection and only a certain content type.  When we use the search bar and enter "DateIn>2020-11-11", "DateIn<=2020-01-01", etc every thing works as expected.

If I enter an invalid date "DateIn<="2020-30-11" in the search bar all records across multiple site collections are being returned.  This is a huge security risk for the client.

**Version used**
Ex: 4  (got latest 9/1)

**Describe the bug**
PnP Search Results web is returning all records in a tenant when invalid data is used in the search bar.  It is not following the Query Template settings
{searchTerms}  Path:"[site collection]" ContentTypeId:[Document Content Type]

**To Reproduce**
1. Create a document library
2. Create a custom content type that includes a date field
3. Configure a RefinableDate to point to the date field
4. Create a page that uses the PnP Search web part configure to use the search bar.
5. Enter an invalid date into the search bar  RefinableDate00<2020-30-11

**Expected behavior**
No results should have been returned in the results

**Comment by wobba** [comment]
Parsing of KQL in what is returned is an API issue, not something we can control in the web parts themselves.
