### ISSUE TITLE
Hide search result webpart title on empty result 

### ISSUE THREAD

**Issue by lnatus** [microsoft-search/pnp-modern-search#132]
The toggle "Show blank if no result" doesn't hide the webpart title. There should be an option to hide the title for empty results as well.

**Comment by wobba** [comment]
I'd rather hide the title as default with the existing toggle, instead of adding another toggle. As it quickly becomes too technical to set up. @FranckyC  what do you think?

**Comment by FranckyC** [comment]
Hi @lnatus It makes sense. However, I would not add an other toggle but simply hide the title as well when "Show blank" is set.

**Comment by FranckyC** [comment]
Should be resolved by #148. Let me know if it works for you.
