### ISSUE TITLE
OWSMTXT columns always null in v4

### ISSUE THREAD

**Issue by MakingThingsWorkToronto** [microsoft-search/pnp-modern-search#1326]
**Version used**
Ex: 4.3.0

**Describe the bug**
v4 results web part returning "null" in place of actual values for any *OWSMTXT managed properties.  The postquery request is returning null when inspected in developer tools > network.  Are we doing something with the request that would result in these returning null?  The OWSMTXT values are returned in both v3 and in the Search Query Tool (v2.8.6).  

**To Reproduce**
1. Navigate to a modern SharePoint Site Page > click Edit > click Page Details > enter the description for the page.
2. Wait for search to index changes to the page.
3. Using search query tool, add column DescriptionOWSMTXT, and enter query Path:"https://_<tenant>_.sharepoint.com/sites/_<site>_/SitePages/*"
4. Note the DescriptionOWSMTXT column returns data.
5. Create SharePoint page and add the PnP Search Results web part onto the page.
6. Enter the same search query and add DescriptionOWSMTXT to the select properties.
7. Switch the layout to "Debug".
8. Note the OWSMTXT column is null.
9. Inspect the postquery request in developer tools / network.
10. Note the value returned in DescriptionOWSMTXT is also null.

**Expected behavior**
The postquery request should return the value of the OWSMTXT columns and hence the MSWP should display data.

**Desktop (please complete the following information):**
 - Windows 10.
 - Chrome and Edge

**Additional Context
- I've tested this against several different OWSMTXT managed properties.
- Behavior is consistent for all OWSMTXT managed properties and is not isolated to DescriptionOWSMTXT.

**Comment by FranckyC** [comment]
Hi Matthew, thank you for raising this issue. Indeed this is a weird behavior :(. By any chance, did you try with a `RefinableStringXXX` mapped with the same crawled property just to see if there is a value? As I remember, there is no additionnal process for this type of properties in the code.

@Laul0 do you have time to explore this behavior?

**Comment by wobba** [comment]
@MakingThingsWorkToronto can you compare requests in v3 and v4 and see if you spot any difference?

**Comment by MakingThingsWorkToronto** [comment]
@FranckyC - I am waiting on indexing and will get back to you.  I did test creating a new managed property and that has the same problem as the ootb OWSMTXT property.

@wobba - yeah, both hitting the /_api/search/postquery endpoint. 

v4 adds the following to the request:
  EnableNicknames: false
  EnablePhonetic: false
  Properties >
  --> ClientFunction: PnPSearchWebPart
  --> ListId: <guid>
  --> ListItemId: <guid>

Additionally SelectProperties in v3 & v4 are encoded differently, v3 is a proper JSON array whereas v4 is a single item array:
-- v3: [ "mangagedproperty", "mangagedproperty", "mangagedproperty", "mangagedproperty", "etc."] 
-- v4: [ "mangagedproperty,mangagedproperty,mangagedproperty,mangagedproperty,etc." ]

At first glance everything else looks the same.

I haven't had time to test the code, but will.  Figured you already knew about the limitation...

**Comment by wobba** [comment]
Initial thought is the mp passing as a string. Can you check GET vs POST in the query tool as well?

**Comment by wobba** [comment]
And..can you check the X-searchplatform response header value?

**Comment by MakingThingsWorkToronto** [comment]
@wobba - 
Search Query Tool using HTTP POST option does return the value (as does HTTP GET).

Interesting enough x-searchplatform is different between v3 and v4:
- v3 "Default"
- v4 "Substrate"

**Comment by wobba** [comment]
@MakingThingsWorkToronto  except the query tool has a proper array `['Path', 'Title', 'Site', 'FileName']`. So that's definitely the issue here.

**Comment by MakingThingsWorkToronto** [comment]
@wobba @FranckyC - Here is the sequence of events leading to this is:

1) Error retrieving managed properties in SharePointSearchService.ts > getAvailableManagedProperties()

![image](https://user-images.githubusercontent.com/13340007/135121506-1e327e96-134d-4076-8fe7-673eb440b720.png)

![image](https://user-images.githubusercontent.com/13340007/135118925-7fb2e3a5-2111-47f5-b5d7-d9c84dd7eb3e.png)

2) User adds new property by typing directly into the Select Properties dropdown.... Selected Properties are concatenated into a string with a single checkbox in the dropdown:

![image](https://user-images.githubusercontent.com/13340007/135122740-1c762c9a-9703-4d38-851a-766209cbf28b.png)

3) Search is called without splitting the properties into appropriate array elements.

It appears the behavior has changed in the develop branch.  Is that possible?

I added a check in the SharePointSearchDataSource.ts file to force the selected properties into an array.  This resolves any backwards compatibility issues.  Please let me know if you want me to submit a PR.

@FranckyC - the RefinableString mapping didn't work.

**Comment by jhholm** [comment]
I think I've run into this problem with similar symptoms. I'm guessing you typed the selected properties manually or used copy paste to input the selected properteis? I think there's an issue within that drop down element. Could you check from the last configuration page, from the import/export json that the generated selected properties look ok. 

I had a similar issue when I typed in a selected property manually. It would garble the selected properties as multiarrays and so on. Thus any manual configuration I do nowadays, I handle it via the import/export -functionality. I can attach screenshots later. Otherwise I would recommend that you select the properties manually from the dropdown.

**Comment by jhholm** [comment]
![image](https://user-images.githubusercontent.com/13876124/135452359-e03941d9-f7b2-45ef-b130-4883e31b87ee.png)
This is how the configuration looks when using a freshly added search results webpart

![image](https://user-images.githubusercontent.com/13876124/135452521-19059f07-f160-402e-ad32-55fd028bf918.png)
This is how the configuration looks when you type a field manually as a selectable property. See line 31.

**Comment by jhholm** [comment]
So check from Import / Export settings if you have similar errorneous configuration.

![image](https://user-images.githubusercontent.com/13876124/135457986-f1206c42-d198-4a76-9e52-eec0864d1bb3.png)

**Comment by wobba** [comment]
@MakingThingsWorkToronto can you also test the dev branch?

**Comment by FranckyC** [comment]
@MakingThingsWorkToronto I can't reproduce your issue: 

![image](https://user-images.githubusercontent.com/5659122/136039496-4b2290ec-9c6a-4287-9e01-3ea7a9fcf861.png)

The problem is with the input value for the dropdown resulting to an incorrect payload. To properly add a new selected property, you must:

- Clear the value in the dropdown
- Type the managed property name
- Press 'Enter'

Can you confirm this works using this procedure?

Forcing the property as an array in the `SharePointSearchDataSource.ts` file is more like a hack since the property should always be array. If I remember correctly, an update has been recently to parse new added values.

To avoid mistakes, maybe I should just clear the value automatically on drop down focus so you can type new property here.

**Comment by wobba** [comment]
@FranckyC should we keep or delete the branch https://github.com/microsoft-search/pnp-modern-search/tree/feature/1326 ?

**Comment by FranckyC** [comment]
Branch deleted
