### ISSUE TITLE
Query template - path - search local site

### ISSUE THREAD

**Issue by sb-sheriff** [microsoft-search/pnp-modern-search#1327]
I've checked the existing issues and couldn't find one exactly like I am having.

**Question**
I've understood by using "{searchTerms}PATH:https://parentabc.sharepoint.com/sites/local101" to limit the search result within local101 SP site. However, the issue is that the page has returned the search result when it is loaded without the user entered any search term yet. Anyway we could change not to load before the search?

**Version used**
4.3.0

**Screenshots**
![image](https://user-images.githubusercontent.com/87348254/134272847-ca8ccef2-5c2a-4912-aeb4-e0ffbd5e6bdc.png)

**Comment by Laul0** [comment]
Similar question and answer here 😉 https://github.com/microsoft-search/pnp-modern-search/issues/1302#issuecomment-921901366

**Comment by sb-sheriff** [comment]
@Laul0 Thanks! It's working except it is also acting as previously reported -- the search result still stayed when user cleaned the search term. Any further suggestions on that?

**Comment by wobba** [comment]
@Laul0 clearing the search box will not execute a new search which is expected behavior. It's not a search as you type experience, similar to OOB search.
