### ISSUE TITLE
Cards template with odd numbers

### ISSUE THREAD

**Issue by paalolav** [microsoft-search/pnp-modern-search#1329]
### Check existing issues before logging new ones

**Version used**
4.3 (July release)

**Describe the bug**
This issue occurs when using the cards template with compact mode and 2 preferred cards per row.
With a result that has odd numbers (3, 5, 7, etc)  the last result is separated from the other results with a visible gap.

**To Reproduce**
1. Use the Cards template
2. Select Compact mode
2. Choose 2 preferred cards per row.
4. Make sure your search results are in odd numbers, since even numbers work fine.

**Expected behavior**
I'd expect the results to use the same space on the last row as the other rows.

**Screenshots**

![screenshot_2021-09-21_at_15 30 37](https://user-images.githubusercontent.com/55249575/134333812-2deccf80-e273-4e8a-b86b-e65279038abc.png)
![Screenshot 2021-09-21 at 15 28 12](https://user-images.githubusercontent.com/55249575/134333337-edb8ab7b-1e71-4dc2-9a63-c44af2ddb47c.png)

**Desktop (please complete the following information):**
Latest Edge & Chrome. MacBook Pro 16" MacOS 11.6.

**Additional context**
As a workaround, add the following styling:

        .template--cardContainer {
        align-items: stretch;
        }

**Comment by FranckyC** [comment]
Thanks @paalolav . Fixed in the `develop` branch.
