### ISSUE TITLE
 Edit Synonym Feature : Problem when  configuring terme with compound synonym

### ISSUE THREAD

**Issue by kortov950** [microsoft-search/pnp-modern-search#133]
Version used : 3.8.0 and 3.0.10
the search engine does not return a result when configuring terme with compound synonym 

for exemple 
![image](https://user-images.githubusercontent.com/13348836/76908806-e80ab900-68a9-11ea-80fb-cc27ebb05f27.png)
 when i search with " plan compte" the search engine don't return anything

**Comment by FranckyC** [comment]
Hi @kortov950, can you use the `Debug` layout and see what is the value of the `queryTransformation` variable?

![image](https://user-images.githubusercontent.com/5659122/77680563-85c94c80-6f6a-11ea-80b2-a8f8470b117d.png)

**Comment by kortov950** [comment]
Hi @FranckyC , thanks for you reply 
my data does not contains the keywords (plan compte)
I added this keywords as synonyms for this term
i need when i search with this keyword , the  search engine redirect to this term 
that's the goal of functionality Edit synonym ?

**Comment by FranckyC** [comment]
What if you switch the terms in the configuration?

**Comment by kortov950** [comment]
also no result  
i think the compound synonym dont work

**Comment by FranckyC** [comment]
Could you please debug the query and tell me what is the query text sent to the search API? You can use your browser network taband look for `psotquery` and use the 'Debug' layout. Thanks.

**Comment by kortov950** [comment]
When i search with compound synonym

![image](https://user-images.githubusercontent.com/13348836/77787227-7a0b8200-705f-11ea-8597-0c35504c2d3a.png)

When i search with simple synonym

![image](https://user-images.githubusercontent.com/13348836/77787841-88a66900-7060-11ea-92d2-59222ee61705.png)

the case with compound synonym it doesn't find the related synonymes

**Comment by wobba** [comment]
What's the * in front and behind {searchboxquery}? * in front will never work. * at the end is appended then to the last term. Take the query text and replace into the variable, and evaluate if you think the KQL makes sense. (It doesn't when you have () in there)

**Comment by kortov950** [comment]
the problem is in the searching synonymes and mapping with keywords
i debugged the inject _injectSynonyms  function,
this function split the keywords by space 
after that  this line const value = this._synonymTable[key]
![image](https://user-images.githubusercontent.com/13348836/77826736-7fc1a000-7111-11ea-99b8-38c2714a8742.png)

dont find any  compound synonyme 

in my case i have the synonym "plan compte" configured for the term "SAP S/4 Finance"
when the function  split the query  we have a array with item "plan" and "compte"
but the array _synonymTable contains  the item with the key "plan compte"

**Comment by wobba** [comment]
Fixed.
