### ISSUE TITLE
Entity type list missing in Microsoft Search data source

### ISSUE THREAD

**Issue by VerlindenEAM** [microsoft-search/pnp-modern-search#1332]
**Version used**
4.3

**Describe the bug**
When using Microsoft Search as datasource the Person and List entity is now shoing.

**To Reproduce**
1. Go to 'PnP - Search Results' webpart
2. Click on 'Entity types to search'

**Expected behavior**
Entity types to search should match the same entities as described in the Microsoft Search API documentation.
In the Source configuration section of the PnP Modern Search documentation, the entity types to search are pointed to the MS API docs.
https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/#source-configuration_1

**Screenshots**
![image](https://user-images.githubusercontent.com/35732908/134475710-96aba6e3-b77f-49ce-a799-12ebdf2e3d58.png)

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**
n/a

**Comment by wobba** [comment]
People is not part of the Graph Search API, but we can add "list" for sure.
![image](https://user-images.githubusercontent.com/51104/134495006-1b650839-1414-4318-81dc-8c24ea6ec1bb.png)
