### ISSUE TITLE
SearchRequest Invalid DO NOT use null or empty string in fields

### ISSUE THREAD

**Issue by VerlindenEAM** [microsoft-search/pnp-modern-search#1333]
**Version used**
4.3

**Describe the bug**
When adding the Results webpart to a page, it gives the following error by default.
Error message: SearchRequest Invalid DO NOT use null or empty string in fields.

**To Reproduce**
1. Go to 'Modern Page'
2. Add 'Results webpart'
3. See error
4. Unselect one of the 'Selected fields'
5. Select the same 'Selected field'

**Expected behavior**
No error message on adding the webpart by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/35732908/134486899-227745f7-4296-444d-b921-9234d051de2c.png)

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**
Workaround is to unselect and select one of the Selected Fields.

**Comment by wobba** [comment]
This is already fixed in the dev branch and will be in the next release.
