### ISSUE TITLE
Wrong number of results on search vertical using query template

### ISSUE THREAD

**Issue by joelfmrodrigues** [microsoft-search/pnp-modern-search#134]
**Version used**
Ex: 3.10

**Describe the bug**
Number of results for Search verticals not correct when using Query Template and another vertical is selected.
When selecting the vertical, query template is applied and total number of results is updated to the correct value

**To Reproduce**
Create 2 verticals with the same result source
Add Query Template logic to reduce the number of results in one of the verticals
Navigate between verticals to see the count being updated

**Expected behavior**
Total number of results to display the correct number

**Desktop (please complete the following information):**
 - Browser: tested on Chrome/Edge

**Comment by FranckyC** [comment]
Hi @joelfmrodrigues, by any chance, does your result source have the `{searchTerms}` expression in it?

**Comment by FranckyC** [comment]
After testing it seems the query template is ignored when the result source ID does not contain the `searchTerms` token. Here is my working setup for verticals with the default `LocalSharePointResults` source. This works, count are correct:

![image](https://user-images.githubusercontent.com/5659122/77679135-8a8d0100-6f68-11ea-945f-02ff740c167c.png)

![image](https://user-images.githubusercontent.com/5659122/77680190-fe7bd900-6f69-11ea-8eb1-300bffcda37c.png)

**Comment by joelfmrodrigues** [comment]
This is what I am using
![image](https://user-images.githubusercontent.com/19577724/77685197-fab07c80-6f92-11ea-8b15-5400c64dbdf9.png)

But number of results is only correct when that vertical is selected. When not selected, it seems that the query template condition is not applied

**Comment by FranckyC** [comment]
The result source you are using is `LocalSharePointResults` ?

**Comment by FranckyC** [comment]
Ok think I got it. This is because you used a token in your template and they are not resolved in the method to get verticals count. I will fix that.

**Comment by FranckyC** [comment]
Should be resolved by #150. Let me know if the update works for you. Thanks!

**Comment by joelfmrodrigues** [comment]
Thanks a lot Frank, this seems to resolve the count issue.
I have pulled the latest commits to my branch where I have the refiner options filter (I have to keep this for now as always displaying the selected items was a requirement from my client) and the filter no longer works. It seems that the property being tested has the refiner name and not the option value, but I believe this was not the case before as the filter was working. Can you confirm if this is correct before I update my code?
![image](https://user-images.githubusercontent.com/19577724/77752070-c2568000-701e-11ea-8669-eed220cad246.png)

**Comment by joelfmrodrigues** [comment]
This seems to be affecting other things. 
For example:
-set a refiner to multi select
-select 2 options
-unselect one of the options
-both options are unselected

**Comment by FranckyC** [comment]
Yes now the `RefinementName` always contains the refinement name (i.e. the refinable managed property name). It was a mistake in the code to duplicate the refinement value twice. For instance, with the search API, the `Size` managed property always returns the value for both `RefinementName` and `RefinementValue` causing issues like #129 .

**Comment by FranckyC** [comment]
For the other issues, I'll look into this.
