### ISSUE TITLE
Webpart not loading for unmaneged devices

### ISSUE THREAD

**Issue by MarcoSPDeveloper** [microsoft-search/pnp-modern-search#1344]
**Version used**
4.2

**Question*
Our organisation has turned on policies for unmanged devices. The Unmanaged device policy is set to "Allow Limited, Web-only access" in SharePoint Admin Center.  

The pnp modern search webpart is now not loading any longer on unmanaged devices. While the standard news web part is loaded. Means the error only appears with the pnp web part. 

I would be grateful for a hint how the policy can be circumvented. Is it possible to define an exception for /sites/appCatalog or .js files? I am aware that this is not the direct scope of the project, but I still hope for a hint

**Screenshots**
![webpartError](https://user-images.githubusercontent.com/61829528/134879542-e7220b2f-d986-46ce-97ed-20d90c765c41.JPG)
*

**Additional context**
[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-42df-47c3-94d6-017428cd2baf" (pnpSearchResultsWebPart). Original error: Failed to load path dependency "SearchResultsWebPartStrings" from component "544c1372-42df-47c3-94d6-017428cd2baf" (pnpSearchResultsWebPart). Original error: Error loading https://component-id.invalid/544c1372-42df-47c3-94d6-017428cd2baf_4.2.3/SearchResultsWebPartStrings
	Unable to load script https://xxxpreprod.sharepoint.com/sites/appcatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/SearchResultsWebPartStrings_en-us_d1e1149a24446f6458cf1bd0b4008814.js

**Comment by wobba** [comment]
My recommendation it to enable CDN https://docs.microsoft.com/en-us/sharepoint/dev/spfx/enable-microsoft-365-content-delivery-network such that resources are available.

I'll close this issue as it's not web part dependent but relates to how access policies and apps are deployed.
