### ISSUE TITLE
OSSM WhiteSource detected high risk library vulnerabilities in development branch

### ISSUE THREAD

**Issue by ulbrigiu** [microsoft-search/pnp-modern-search#1346]
**Version used**
development branch of Sep 23, 2021 (latest commit: de33aab)

**Describe the bug**
I want to introduce this application in a corporate context in my company. As standard procedure open source apps are scanned for any vulnerable libraries via WhiteSource. I performed this action to the main branch where the scan resulted in a high vulnerability score (see [issue #1322 ](https://github.com/microsoft-search/pnp-modern-search/issues/1322)) - @wobba recommended using the dev branch as there some updates already had been performed. 

The scan of the development branch resulted for the PnP search in a high vulnerability score due to outdated libraries. I attach the vulnerability report for reference. As standard for my company the high risk vulnerabilities needs to be fixed before we can use the application:
* node-sass-4.14.1.tgz as part of LibSass 3.5.4.: LibSass needs to be updated at least to version 3.6.0.
* tar-2.2.2.tgz: note-tar needs to be updated to versions tar - 3.2.2, 4.4.14, 5.0.6, 6.1.1
* trim-newsline-1.0.0.tgz: needs to be updated to versions 3.0.1, 4.0.1
* glob-parent-3.1.0.tgz needs to be updated to glob-parent-5.1.2

**To Reproduce**
I have cloned the dev branch on Friday (latest commit: de33aab), performed `npm i` in search-extensibility and search-parts to create the package-lock.json file which was used by WhiteSource to perform the assessment. 
I attach the package-lock files as well for reference

**Expected behavior**
No high risk vulnerabilities should be detected to use the application in a corporate context

**Screenshots**
![image](https://user-images.githubusercontent.com/91061667/135031663-e15f0674-c49b-49a6-b24b-a4e7dd3e6ef6.png)

**Desktop (please complete the following information):**
n/a

**Additional context**
* [DT-PNP-MODERN-SEARCH-DEV-ALL-risk.pdf](https://github.com/microsoft-search/pnp-modern-search/files/7241409/DT-PNP-MODERN-SEARCH-DEV-ALL-risk.pdf)
* [package-lock files.zip](https://github.com/microsoft-search/pnp-modern-search/files/7241424/package-lock.files.zip)

**Comment by wobba** [comment]
All those libs are used during building the web parts, not in the web part it self. This is for any SPFx project. You cannot run a check on the build tool chain. You need to run on the transpiled output. If you have issues with the SPFx tool chain I suggest you new up a new SPFx project, then create a report for it and log at https://github.com/SharePoint/sp-dev-docs

**Comment by ulbrigiu** [comment]
Thank you @wobba, this information helped a lot - I really appreciate your (very fast!) support. I have analyzed the dependency and was able to show, that the effectively used direct and indirect dependencies contain no security vulnerabilities for the current version in development branch. As soon as the next release will be available in main branch, I am allowed to introduce to our corporate landscape! 
One last question from my side: Do you already have a release plan - when you plan to release this next version?

**Comment by wobba** [comment]
We'll release when time allows, and time is sparse for this spare time project these days. As soon as possible.
