### ISSUE TITLE
Search Filters Web Part - Custom strings

### ISSUE THREAD

**Issue by KmDroid** [microsoft-search/pnp-modern-search#1349]
**Version used**
Ex: 4.3.0

**Question**
With the PnP Search Filter Web Part, I am trying to translate some filter words such as Apply, Clear, and ComboBoxPlaceHolder. 
Is there any custom option to change the filter text?

![image](https://user-images.githubusercontent.com/65020331/135259758-42717ed8-a31d-4e31-8393-672c63a816bd.png)

**Comment by wobba** [comment]
Localization files are located at https://github.com/microsoft-search/pnp-modern-search/tree/main/search-parts/src/loc and we welcome new languages :)

**Comment by KmDroid** [comment]
Hi,
I will translate the web part to Portuguese from Portugal (pt-PT). the best option will be to create a branch under development and open a pull request with the changes made?

**Comment by FranckyC** [comment]
Hi @KmDroid , yes, fork the repo, create a new branch, and then submit a PR against the `develop` branch . Also you have to do translations for **all** Web Parts, not just the filters one.

**Comment by wobba** [comment]
Closing this and looking forward to your PR @KmDroid  :)
