### ISSUE TITLE
groupBy helper not working in v4

### ISSUE THREAD

**Issue by MakingThingsWorkToronto** [microsoft-search/pnp-modern-search#1352]
**Version used**
4.3.0 develop branch

**Describe the bug**
The groupBy handlebars helper is not working in v4.  Believe the issue is related to v3 to v4 change where we are now using a local instance of handlebars over global. The helper is not being added to the local instance but rather to the global instance.

**To Reproduce**
Use the helper #group in any custom template.  Note the console reports a missing helper error message.

![image](https://user-images.githubusercontent.com/13340007/135356052-1d967946-1cdf-4f2b-b913-516e2580cce3.png)

**Expected behavior**
Grouping should work as is in v3.

**Desktop (please complete the following information):**
Windows any browser.

**Resolution**
Please update line 538 in TemplateService.ts to: 

`groupBy(this.Handlebars);`

Please let me know if you would prefer a PR for this change.  Thanks for everything you're doing for us guys!

**Comment by wobba** [comment]
@MakingThingsWorkToronto please PR the fix.

**Comment by FranckyC** [comment]
Good catch @MakingThingsWorkToronto. Fixed in the `develop` branch.
