### ISSUE TITLE
how to apply filter for slots value based on that apply the condition

### ISSUE THREAD

**Issue by SrinivasVeepuri** [microsoft-search/pnp-modern-search#1356]
I would like to filter the value in search results based on one of the value of Search filter data, hence let me know the way to resolve an issue

I would like to filter the Design Component for that only I would like to keep hyper link, hence please let me know the correct code, the below code I couldn't able to resolve an issue Under.
The below I wrote under Managed card fields section of Tags Name
Ex:
#if (slot item @root.slots.Tags="Design Component")
View SnapShot
Else
{
}

**Comment by FranckyC** [comment]
Hi @SrinivasVeepuri, this is more an Handlebars question, You must use the [`{{eq}}`](https://github.com/helpers/handlebars-helpers#eq) operator instead.
