### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by tmolbach** [microsoft-search/pnp-modern-search#136]
Many modern search experiences support "infinite scrolling", i.e. as I scroll down the page, more results are loaded. This would replace the need to "page" through the results. It would be great to get support for this in our web parts.

**Comment by wobba** [comment]
If you look to web it's used primarily for images/video or card based layouts. So could be interesting to add, but not on the internal short list as of now. If someone wants to add we'll of course accept it 🙂

**Comment by FranckyC** [comment]
It would be cool yes, but not necessary for now so not the priority here :).
