### ISSUE TITLE
include OneDrive for Business results 

### ISSUE THREAD

**Issue by LynnFranceusXylos** [microsoft-search/pnp-modern-search#1369]
I created a result source to get documents from the OneDrive of user. For testing purposes I limited it to my own OneDrive that has 2 files that have been uploaded at least two months ago. 

In the query example of the result source I see these two files appear. 
![image](https://user-images.githubusercontent.com/89204353/136030840-5db3adb8-a076-448e-aad7-6cf38889c7d6.png)
![image](https://user-images.githubusercontent.com/89204353/136030882-0cb3595b-e3f1-4f2d-8b79-9b5332ef9852.png)

When I include the result source ID in the PnP Search Results web part, I get 0 results (!!).
![image](https://user-images.githubusercontent.com/89204353/136031089-04bb2be1-8dfd-490f-b15a-92dc4d23d686.png)
![image](https://user-images.githubusercontent.com/89204353/136031109-1f97674f-e2fb-4120-9333-430dfbdd5b20.png)

Putting the property "Include OneDrive for Business results" ON and OFF gives both the same results.
![image](https://user-images.githubusercontent.com/89204353/136031235-c944a705-29f3-4155-a663-68fd7da96072.png)

Does anybody have an explanation why it doesn't simply visualize the query of my result source? 

Interesting to know is that otherwise I can see all the files in OneDrive that have been shared with me minus 2. I never see my own files. 

PnP Modern Search Version: 4.1.0.0
Release Date: may 2021

**Comment by mattiasmainil** [comment]
It returns the following:
![snipPNP](https://user-images.githubusercontent.com/18209557/141992507-7b848cb0-08c9-481b-95cf-5a6aa18b435c.png)

**Comment by wobba** [comment]
@LynnFranceusXylos do you still experience this issue?

**Comment by mattiasmainil** [comment]
@wobba My apologies. I have taken over the issue from Lynn. Yes we still experience this issue

**Comment by wobba** [comment]
@mattiasmainil Seems there is no space between your `path` part and the `(contentclass)` part? But the template is being picked up from your result source - so hard to know why you don't get results.

**Comment by mattiasmainil** [comment]
I still get no results from the result source. Only in the query example of the result source

**Comment by wobba** [comment]
Without seeing the request and response JSON it's impossible to troubleshoot this. Result sources do work for others and for myself when testing. You can always try the guid of some of the OOB sources and see if there's a difference.

**Comment by mattiasmainil** [comment]
What information do you require from the XML file that is generated from the query with the result source ID?

**Comment by wobba** [comment]
I suggest you get hold of someone who can diagnose this with you who understands the search API requests and responses. If it's an API issue it's outside the scope of this project. If it's something in the web parts parsing the response wrongly somehow, then we should look into it.

You can also go to page 4 of the web part settings and click `Edit Properties` then export the web part config and share it securely. This way we can take a look if the config is wrong somehow.

**Comment by mattiasmainil** [comment]
@wobba I have send the web part config file to your e-mail adress

**Comment by wobba** [comment]
Not much I can troubleshoot. You have a custom result source, and I cannot repro how this is set up or works in your environment. You can try to add the path filter to the query template in the web part instead and remove the result source and see if that work any different.

**Comment by wobba** [comment]
All results should be returned.
