### ISSUE TITLE
"Share dialog" for display templates

### ISSUE THREAD

**Issue by tmolbach** [microsoft-search/pnp-modern-search#137]
As we can't use javascript with Handlebars in the display templates, it would be great to have support for a "share dialog". When building search experiences based on the PnP web parts, I would like to allow my users to "share" an item with others. 

Here is an example card showing a piece of IP. I would like to add a "share" button to it:
![image](https://user-images.githubusercontent.com/12969319/77183014-1358f800-6aa4-11ea-98fb-e6abb7182e9e.png)

I don't think that a standard share dialog exists in Office 365, and we probably have to build a custom one. 

Here is an example dialog from a document folder in SharePoint. We could mimic something like this: 
![image](https://user-images.githubusercontent.com/12969319/77183193-54510c80-6aa4-11ea-8203-d1fee6fc1e0e.png)

**Comment by wobba** [comment]
Something like https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/react-command-share-pnpjs

**Comment by FranckyC** [comment]
@tmolbach You can create a [custom web component](https://microsoft-search.github.io/pnp-modern-search/search-extensibility-library/getting-started/#create-a-custom-web-component) for this.

**Comment by FranckyC** [comment]
Added to the backlog but with low priority. I close this for now.
