### ISSUE TITLE
Query variables with mutliple values

### ISSUE THREAD

**Issue by FloWae** [microsoft-search/pnp-modern-search#1371]
**Version used**
4.2

**Describe the bug**
If you are using query variables with multiple values the query is not submitted correctly. So it is not possible to query against a variable with multiple values.

**To Reproduce**
1. Create taxonomy column with multiple values
2. Use this column within pages
3. Map it to a "Refinable String"
4. Create page, add PnP Search Result Webpart and go to 'Query Template'
5.Insert query with a variable with multiple values : {|RefinableString:{page.{fieldName}}}
6.. Click "Apply"

**Expected behavior**
Query looks like:RefinableString:"Value1"OR oRefinableString:"Value2" OR "RefinableString:Value3" like described in the last paragraph: https://docs.microsoft.com/en-us/sharepoint/technical-reference/query-variables 

**Screenshots**
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/92033799/136208129-2e1bea38-ae4e-4120-90f0-22913a5600a7.png)

**Desktop**
 - Browser doens't matter

**Comment by FranckyC** [comment]
Hi @FloWae , what if you use the `{|RefinableString:{page.{fieldName.TermID}}}` or `{|RefinableString:{page.{fieldName.Label}}}` expression instead?
