### ISSUE TITLE
Search Box "clear text" button clears results, but not the text in the search input

### ISSUE THREAD

**Issue by kflogdev** [microsoft-search/pnp-modern-search#1374]
**Version used**
4.3

**Describe the bug**
When clicking the "clear text" button on the Search Box web part, the results are cleared, but the text entered into the input is not cleared.

**To Reproduce**
1. Type something into the Search Box, press "enter"
2. Click the "clear text" [X] button.
3. Search results are cleared, but text in input remains.
4. See .gif below

**Expected behavior**
Clicking the "clear text" [X] button should clear results AND any text entered into the search input.

**Screenshots**
![clear search](https://user-images.githubusercontent.com/72807146/136257321-94f7ace5-b400-4c40-8e5e-458686644922.gif)

**Desktop (please complete the following information):**
 - Chrome Browser

**Comment by wobba** [comment]
Cannot repro.
![2021-10-13_09-51-23](https://user-images.githubusercontent.com/51104/137090569-88d64877-3356-4122-8be7-022dec8d9f3e.gif)
