### ISSUE TITLE
Horizontally expanded refiners

### ISSUE THREAD

**Issue by tmolbach** [microsoft-search/pnp-modern-search#138]
It would be good to have an option for horizontal expansion of filters. A lot of web sites provide this, e.g. kayak.com (In this example: round-trip, 1 adult, etc):

![image](https://user-images.githubusercontent.com/12969319/77184113-b52d1480-6aa5-11ea-8e4c-ef6e385f4550.png)

Each filter would provide a drop down with values to select. The selected value(s) will be the "caption" after selection. If time allows, we can have a toggle that shows a headline instead and build up the selected values in a breadcrumb like the filter is doing today.

**Comment by FranckyC** [comment]
Added to the backlog as low priority. I close this for now.
