### ISSUE TITLE
Selected properties not loading

### ISSUE THREAD

**Issue by gcapisaniQIC** [microsoft-search/pnp-modern-search#1387]
**Version used**
Ex: 4.3.0

**Describe the bug**
Whe expanding the Selected properties the list does not show. The spinning loading icon shows but nothing happen.

**To Reproduce**
1. Edit Pnp - Search Results webpart
2. Click on 'Selected properties'

**Expected behavior**
See the list of selected properties and be able to select new one

**Screenshots**
![image](https://user-images.githubusercontent.com/45838152/137089485-f8081926-31a4-42fd-8088-d4c87ea9d3c6.png)

**Desktop (please complete the following information):**
 - Tested on Edge and Chrome

**Comment by mi-di** [comment]
@jhholm There isn't a postquery at all

**Comment by jhholm** [comment]
Opening the Selected Properties drop down should generate the aforementioned "undocumented" API call within the site to postquery endpoint with the following request payload.

![image](https://user-images.githubusercontent.com/13876124/138047134-9d4d2cd7-0c9a-47e6-84aa-d1133cf8ed96.png)

Are you still getting HTTP errors in network or console? I would remove the webpart and add it manually and try again.

**Comment by mi-di** [comment]
I even installed it again and I have this problem with several tenants, even a colleague noticed these same problem.

This is what I get in the console when I select the drop down for the first time:

Error: Error: Idle tracking cookie is missing.
    at IdleSessionActivityMonitor.GetCookieValue (activitymonitor.js:365)
    at IdleSessionActivityMonitor.InitializeSettingsFromCookie (activitymonitor.js:349)
    at Function.LogIssoActivity (activitymonitor.js:130)
    at HTMLDocument.IdleSessionActivityMonitor.HandleClick (activitymonitor.js:76)
activitymonitor.js:137 Error: Error: Idle tracking cookie is missing.
    at IdleSessionActivityMonitor.GetCookieValue (activitymonitor.js:365)
    at IdleSessionActivityMonitor.InitializeSettingsFromCookie (activitymonitor.js:349)
    at LogIssoActivity (activitymonitor.js:130)
sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:68 
        
       POST https://--------.sharepoint.com/sites/Intranet/_api/search/postquery 500
e.fetch @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:68
e.fetchCore @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:68
(anonymous) @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:68
Promise.then (async)
e._fetchWithInstrumentation @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:68
(anonymous) @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:68
Promise.then (async)
(anonymous) @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:68
Promise.then (async)
e.fetchCore @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:68
e._fetch @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:68
e.post @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:68
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
f @ modern-search-results-web-part_c978012c218ead8510b0.js:1
e.getAvailableManagedProperties @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ chunk.pnp-modern-search-sharepoint-search-datasource_c9d311c08e8d1817df62.js:1
(anonymous) @ chunk.pnp-modern-search-sharepoint-search-datasource_c9d311c08e8d1817df62.js:1
(anonymous) @ chunk.pnp-modern-search-sharepoint-search-datasource_c9d311c08e8d1817df62.js:1
(anonymous) @ chunk.pnp-modern-search-sharepoint-search-datasource_c9d311c08e8d1817df62.js:1
F @ chunk.pnp-modern-search-sharepoint-search-datasource_c9d311c08e8d1817df62.js:1
t.getAvailableProperties @ chunk.pnp-modern-search-sharepoint-search-datasource_c9d311c08e8d1817df62.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
m @ modern-search-results-web-part_c978012c218ead8510b0.js:1
t.getOptions @ modern-search-results-web-part_c978012c218ead8510b0.js:1
t.componentDidUpdate @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
as @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
uc @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
t.unstable_runWithPriority @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
Bi @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
lc @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
Xs @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
(anonymous) @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
t.unstable_runWithPriority @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
Bi @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
Gi @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
zi @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
U @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
qt @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
Show 13 more frames
chunk.vendors~sp-pages-sharetoyammer_none_3dae73fd90c6780963a8.js:2 
        
       The 'reason' properties of event 'PromiseRejectionEvent' have been removed from the event because euii / customer content has been detected. The 'reason' property contains an ip address.
o @ chunk.vendors~sp-pages-sharetoyammer_none_3dae73fd90c6780963a8.js:2
c @ chunk.vendors~sp-pages-sharetoyammer_none_3dae73fd90c6780963a8.js:2
o @ chunk.vendors~sp-pages-sharetoyammer_none_3dae73fd90c6780963a8.js:2
(anonymous) @ chunk.vendors~sp-pages-sharetoyammer_none_3dae73fd90c6780963a8.js:2
g @ chunk.vendors~sp-pages-sharetoyammer_none_3dae73fd90c6780963a8.js:2
(anonymous) @ chunk.vendors~sp-pages-sharetoyammer_none_3dae73fd90c6780963a8.js:2
modern-search-results-web-part_c978012c218ead8510b0.js:1 
        
       Uncaught (in promise) Error: [HTTP]:500 -  [CorrelationId]:1fedfa9f-6029-c000-6ee5-6443a7e334a7 [Version]:16.0.0.21806
    at e.<anonymous> (modern-search-results-web-part_c978012c218ead8510b0.js:1)
    at modern-search-results-web-part_c978012c218ead8510b0.js:1
    at Object.next (modern-search-results-web-part_c978012c218ead8510b0.js:1)
    at a (modern-search-results-web-part_c978012c218ead8510b0.js:1)
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
a @ modern-search-results-web-part_c978012c218ead8510b0.js:1
Promise.then (async)
l @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
m @ modern-search-results-web-part_c978012c218ead8510b0.js:1
t.getOptions @ modern-search-results-web-part_c978012c218ead8510b0.js:1
t.componentDidUpdate @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
(anonymous) @ modern-search-results-web-part_c978012c218ead8510b0.js:1
as @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
uc @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
t.unstable_runWithPriority @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
Bi @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
lc @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
Xs @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
(anonymous) @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
t.unstable_runWithPriority @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
Bi @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
Gi @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
zi @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
U @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
qt @ sp-pages-assembly_nl-nl_7889fe1e44451556acd28796beb9ed8c.js:70
