### ISSUE TITLE
Minor: Allow alignment for "filter" web part

### ISSUE THREAD

**Issue by tmolbach** [microsoft-search/pnp-modern-search#139]
I have a search driven page based on cards, and the filter dialog looks out of place with it's "left" alignment. It would be great to allow left, right or center alignment of the "Filter" caption.

My example:

![image](https://user-images.githubusercontent.com/12969319/77184772-aabf4a80-6aa6-11ea-9068-b59d7ef296c4.png)

**Comment by FranckyC** [comment]
Hi @tmolbach, what version are you using?

**Comment by tmolbach** [comment]
@FranckyC, I'm using version 3.10.0.

**Comment by FranckyC** [comment]
Ok any custom HTML or WP on the page?

**Comment by FranckyC** [comment]
@tmolbach Can I see the page in edit mode to see your setup? I can't reproduce this.

**Comment by tmolbach** [comment]
The challenge is that the "Filter" label is left-aligned in the web part. To make it look nice on the page, it would be good if I could have it right aligned.
The "Reset View" label is from a normal content web part and I can right align that when I get the "Filter" label right aligned...

**Comment by FranckyC** [comment]
Ok the screenshot is misleading. Now I get it. This is the behavior expected. I will add this to the backlog as low priority for now. Feel free to make a PR on this if you want this early.
