### ISSUE TITLE
Filter panel flickers when selecting a filter

### ISSUE THREAD

**Issue by PieterVandendriessche** [microsoft-search/pnp-modern-search#1391]
__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
4.3

**Describe the bug**
When opening the filters panel and selecting a filter the panel flickers. This is visually very annoying. This is very noticeable on a mobile device.
See video below:
https://user-images.githubusercontent.com/25928373/137131828-fbd441ab-22f8-43db-8cac-3b285630fa78.mp4

**To Reproduce**
1. Add both filters webpart and search results webpart on the page
2. Configure them both and link them
3. Select the panel layout in the filters webpart

**Expected behavior**
The panel shouldn't open and close between rerendering data. It should remain open.

**Desktop (please complete the following information):**
 - iOS
 -  Chrome (with debugger modus on iPhone)

**Comment by bva999** [comment]
I have the same problem. It is impossible to use filters because of this
