### ISSUE TITLE
Search Filters web part does not receive values from search results web part version 4.3

### ISSUE THREAD

**Issue by mtburkett** [microsoft-search/pnp-modern-search#1395]
**Version used**
4.3.0

**Describe the bug**
I have a search filter web part connected to a search results web part on a web part page. On a brand new page with only these two web parts I am having issues getting the filter web part to receive filter values from the results web part.

I have several managed properties set up that I am receiving back data for in the results web part - meaning the results web part shows the expected results for each managed property - all are simple text values. When I select any of these as filter values the filter web part displays "No available filter to display". The only time I am able to get a result into the filter field is if I choose the "Created" field. For every other field I get the "No available filter to display" message.

This occurs with the latest Chrome as well as Edge.

**To Reproduce**
1. Create a new Site Page in a SPO communications site.
2. Add a PNP Search Results web part.
3. Add a PNP Search Filters web part.
4. Under Query Template enter the path to a particular list to limit results - i.e. "(Path:https://yoursite.sharepoint.com/sites/ContinuousOperationalImprovement/Lists/ProcessCatalog) (contentclass:STS_ListItem)"
4. In the PNP Search Results Web Part select one or more managed properties in the Selected Properties dropdown.
5. Use the debug layout to ensure that the selected managed property contains data.
5. Cick Connect to a filters Web Part to select "On" and choose the filter web part previously added.
6. Configure the filter web part
7. Under Available connections choose the previously added Search Results web part.
8. Click Edit under "Customize Filters"
9. Enter a display name, choose one or more managed properties for which the search results web part does show values (known good), select a template and save the filters settings.

**Expected behavior**
The search filter web part should show the values from the selected managed property.

**Screenshots**
Results shown in the search results web part:
![image](https://user-images.githubusercontent.com/25694364/137161725-14074ab1-79e1-4e81-bc62-a75696a04279.png)

Managed properties being selected in the search filter webpart:
![image](https://user-images.githubusercontent.com/25694364/137162024-639942b7-5520-4c86-91d5-4ebc6cb620b5.png)

No results in search filter web part:
![image](https://user-images.githubusercontent.com/25694364/137162229-5a53b8c1-74fe-49e9-ba42-db158757eed7.png)

**Desktop (please complete the following information):**
 - Browser: Chrome 94.0.4606.81, Edge 94.0.992.38
**Additional context**
The only property that will display results and works as expected is the "Created" property.

**Comment by wobba** [comment]
You can only use managed properties which are marked to be refinable. The drop down list will not filter on these only so you need to check the schema in SharePoint. Any Refinable* property is refinable by nature.

**Comment by clayjam** [comment]
Wobba - I have the same problem. I created a number of custom managed properties and the filters web part was working fine, and none of these custom managed properties were marked as refinable (because they can't). 

Are you saying I need to use one of the existing refinable managed properties so it can be used in the Filters web part ?

**Comment by wobba** [comment]
"I created a number of custom managed properties " <- you cannot create refinable managed properties, only use the existing Refinable* ones. If it was working, that is an API bug. I have reported this internally and you may see that custom properties will stop working - as they really shouldn't.

**Comment by clayjam** [comment]
Thanks for replying so quickly - much appreciated. Ok - that make sense as why it suddenly stopped working. 

Just wondering why the refinable limitation for custom managed properties exists?

Also, I am thinking then that I should never create a custom managed property and I should only use the existing refinable properties - do you have a use case of when I shouldn't use an existing refinable property and create a custom property?

**Comment by mtburkett** [comment]
Thanks for the help @wobba. I got headed in the right direction thanks to your feedback. For anyone else with the same issue, the fix for me was to go to one of the existing refinable properties and map it to the crawled property I needed. Worked like a charm.
