### ISSUE TITLE
Get search results from a specific list

### ISSUE THREAD

**Issue by claudivieira** [microsoft-search/pnp-modern-search#1396]
**Version used**
Ex: 4.2

**Describe the bug**
Hello everyone. I'm trying to have a search results page based on a list. 
I have a list of names and I need to be able to search in the box for whatever name in the list. I've tried several things that I saw over the internet, but I can't make it work only with results from that specific list so I thought maybe you could give me some help over here or tell me what I'm missing. TIA

**Screenshots**
![image](https://user-images.githubusercontent.com/39301758/137173147-53710e01-4091-46bf-9ad9-a91b9835c70c.png)

**Desktop (please complete the following information):**
 - Browser: Chrome and Firefox

**Comment by wobba** [comment]
Change the query template to: `path:https://contoso.sharepoint.com/Lists/Clients contentclass:sts_listitem_* ` this will return only list items from your list
