### ISSUE TITLE
Search results web part edit panel is blank

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#140]
**Version used**
Ex: 3.10.0

**Describe the bug**
Search results web part edit panel is blank

**To Reproduce**
1. Edit a page with search results web part on it
2. Click on edit web part

**Expected behavior**
Edit panel opens and allows reconfiguration

**Desktop (please complete the following information):**
Chrome Version 80.0.3987.149 (Official Build) (64-bit) on W10 Enterprise

**Additional context**
Any one else notice the results edit panel is blank? All other web parts including search box, refiners and pagination work fine.

**Comment by wobba** [comment]
Can you click F12 and check debug console for error message?

**Comment by webbrewer** [comment]
Console:
Failed to load resource: the server responded with a status of 404 ()
search-results-web-part_b7d6eeba17c1b7a4ab4e8e4a026bb27b.js:26 Message: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://xxx.sharepoint.com/sites/site/_api/web/regionalsettings/installedlanguages' exceeded the quota. Data: {"stack":"Error: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://xxx.sharepoint.com/sites/xxx/_api/web/regionalsettings/installedlanguages' exceeded the quota.\n    at e.put (https://xxx.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_b7d6eeba17c1b7a4ab4e8e4a026bb27b.js:16:12930)\n    at e.cacheData (https://xxx.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_b7d6eeba17c1b7a4ab4e8e4a026bb27b.js:26:28110)\n    at https://xxx.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_b7d6eeba17c1b7a4ab4e8e4a026bb27b.js:26:27997"}
e.log @ search-results-web-part_b7d6eeba17c1b7a4ab4e8e4a026bb27b.js:26
search-results-web-part_b7d6eeba17c1b7a4ab4e8e4a026bb27b.js:26 Message: [SearchService._getQueryLanguages()]: Error: QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://xxx.sharepoint.com/sites/xxx/_api/web/regionalsettings/installedlanguages' exceeded the quota.
e.log @ search-results-web-part_b7d6eeba17c1b7a4ab4e8e4a026bb27b.js:26
2search-results-web-part_b7d6eeba17c1b7a4ab4e8e4a026bb27b.js:28 Uncaught (in promise) Error: QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://xxx.sharepoint.com/sites/xxx/_api/web/regionalsettings/installedlanguages' exceeded the quota.
    at e.<anonymous> (search-results-web-part_b7d6eeba17c1b7a4ab4e8e4a026bb27b.js:28)
    at search-results-web-part_b7d6eeba17c1b7a4ab4e8e4a026bb27b.js:28
    at Object.throw (search-results-web-part_b7d6eeba17c1b7a4ab4e8e4a026bb27b.js:28)
    at a (search-results-web-part_b7d6eeba17c1b7a4ab4e8e4a026bb27b.js:28)
dialog.css:1 Failed to load resource: the server responded with a status of 404 ()
sp-pages-assembly_en-us_fdf3776f111bbeeb7dd400ba4dd8a086.js:48 Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.
    at a._onNavMenuDismiss (sp-pages-assembly_en-us_fdf3776f111bbeeb7dd400ba4dd8a086.js:48)
    at Object.u (sp-pages-assembly_en-us_fdf3776f111bbeeb7dd400ba4dd8a086.js:21)
    at m (sp-pages-assembly_en-us_fdf3776f111bbeeb7dd400ba4dd8a086.js:21)
    at sp-pages-assembly_en-us_fdf3776f111bbeeb7dd400ba4dd8a086.js:21
    at S (sp-pages-assembly_en-us_fdf3776f111bbeeb7dd400ba4dd8a086.js:21)
    at O (sp-pages-assembly_en-us_fdf3776f111bbeeb7dd400ba4dd8a086.js:21)
    at Array.forEach (<anonymous>)
    at P (sp-pages-assembly_en-us_fdf3776f111bbeeb7dd400ba4dd8a086.js:21)
    at D (sp-pages-assembly_en-us_fdf3776f111bbeeb7dd400ba4dd8a086.js:21)
    at En (sp-pages-assembly_en-us_fdf3776f111bbeeb7dd400ba4dd8a086.js:21)

**Comment by FranckyC** [comment]
Hi @webbrewer , can you try to clear the local storage of your browser and retry? `localStorage.clear();`

**Comment by webbrewer** [comment]
Thank you - that worked and the panel options are now visible. I don't want to burden you but can you explain why this happened?

**Comment by FranckyC** [comment]
First time I see this. By any chance, do you have any other custom WP on the page? It may happen if they write in the local storage also. Basically the error says the is not enough space in the local storage anymore. Suprising because to reach this limit you have to put a huge amount of data...

**Comment by FranckyC** [comment]
That could be also any other web page displayed in the same browser ;)

**Comment by webbrewer** [comment]
Indeed, and I'm still seeing an empty properties panel on some pages - sometimes just hitting f12 populates the panel, sometimes I have to clear local storage. I don't think this is an issue with the app, so feel free to close this.
