### ISSUE TITLE
Search vertical: Content source with query variable

### ISSUE THREAD

**Issue by Heavm00** [microsoft-search/pnp-modern-search#1401]
**Version used**
v3.21.0

**Describe the bug**
I've created a content source with the following query:
{searchTerms} (ContentTypeId:0x0101E0* OR ContentTypeId:0x01E0*) AND RefinableString55:{User.organization}
That query returns all results sucessfully within Query-generator
![image](https://user-images.githubusercontent.com/61208008/137296814-68c569de-9ba4-4c93-a3f6-a10a070860a3.png)

I'm using the ID of that content source in my search vertical. When I click on the search vertical the result box remains empty (searching *)

**To Reproduce**
1. Create global search content source with a query variable
2. Incluce content source ID in search vertical 
3. Search for everything

**Expected behavior**
Getting the results for the content source

**Comment by HamEv** [comment]
How does this have an impact on API depending on my tenant?
Luckily on my tenant it works now after 24 hours.
