### ISSUE TITLE
Results count inconsistent every time I refresh

### ISSUE THREAD

**Issue by mikezimm** [microsoft-search/pnp-modern-search#1413]
**Version used**
4.3

**Describe the bug**
When I have the results unfiltered on the page and refresh, the "results" count is different.
This is a controlled test meaning no items are being added to the library and I also found that the count varies up and down seemingly randomly.

See screenshots to see what I'm referring to...  The Site Contents page shows 5394 items total for my library..
After refreshing over and over... these are the results I get in random testing (in order they happened)
5208, 5172, 5207, 5392, 5207, 5392, 5265, 5217, 5217, 5265, 5168

What I do find interesting after doing that test, is that I see some numbers coming up twice which seems rather unlikely given the odds.  I could not really find a pattern though since it does go up and down.

**To Reproduce**
1. Installed the latest sppkg yesterday.
2. Setup library, site columns, managed meta yah dah yah dah yah dah :)
3. Created a really big library with lots of items
4. Added results and filter on the page (filter with just the * filter)
5. Refreshed the page a bunch of times ( about 5 second delay between each one)

**Expected behavior**
The unfiltered results count should show a consistent number.  I get that a search crawl could always be happening which may impact the numbers.  But if nothing was added during a period of time then the number should be stable and consistent.

**Screenshots**
![image](https://user-images.githubusercontent.com/49648086/137539176-2abcc9e1-5c71-4335-bc28-9a37f0ba2dd6.png)

![image](https://user-images.githubusercontent.com/49648086/137539184-ebe77abd-04a8-4a51-bb20-e08bcdf518b0.png)

**Comment by FranckyC** [comment]
Hi @mikezimm, the result count is an estimation given by the SharePoint search engine especially for large results set so this is the default behavior and not a bug. If you test with a smaller results set, the count should be consistent.

**Comment by mikezimm** [comment]
@FranckyC , thanks for the answer, I just saw it after my follow-up since I probably started that before your message.

Do you know off hand how it handles the results in large lists?
For instance, will it work with an 50k file count library without hard-coding any preset filters in the settings?

I'm looking at using the refiners so that the end result should always be well under 5k.

Thanks

**Comment by wobba** [comment]
@mikezimm this is internal logic in Microsoft Search and nothing we can control nor guess how it will work for different scenarios.

**Comment by mikezimm** [comment]
@wobba , well that was easy... Thanks!
