### ISSUE TITLE
Search Filter Web Part and Search Results Web Part and RefinableStrings

### ISSUE THREAD

**Issue by PaulMac66** [microsoft-search/pnp-modern-search#1419]
**Version used**
PnP Modern Search - Search Web Parts - v4: 4.3.0.0

**Describe the bug**
Once my Search Results page has been setup with Search Box, Search Results and Search Refiners I am get strange and inconsistent results returned when using the refiners web part.

I have Managed Metadata fields mapped to RefinableStrings 
RefinableString00
RefinableString01
RefinableString03
RefinableString06

The query template on the Search Results web part is:
{searchTerms} IsDocument:1
path:"https://*******************.sharepoint.com/sites/####/Published%20iBMS%20Documents*"

And my selected Properties are setup to include:
RefinableString00
RefinableString01
RefinableString03
RefinableString06

**Expected behavior**
The expected behaviour, which works sometimes, is that if a refiner is selected with, lets say a total of (12) then the Search Results web part should show the 12 items or what ever the number of results are. However, this is where the issue lays. Sometime it does display the correct number and sometimes its less that what was indicated.

**Screenshots**
**You can see there are 12 refinable Items under Plans, but when selected only 10 display**

![image](https://user-images.githubusercontent.com/7661818/137894168-56a6d172-a054-47d3-993b-4a85566fc687.png)

![image](https://user-images.githubusercontent.com/7661818/137894202-fbfe76a5-7b99-49e4-b070-fe009575f7cb.png)

**If I type in the search box to select the RefinableString03:Plans (PLA) the results is displayed is 12, the correct amount**

Selecting the refiner will display only 10. Sometimes is might be 4 other times ii is random. Occasionally is 12 the correct number. This will apply to all filers, sometime they are right other times they are now, more often not. 

![image](https://user-images.githubusercontent.com/7661818/137894428-bad622c5-a9e7-4c26-ba52-b69ea01be60e.png)

![image](https://user-images.githubusercontent.com/7661818/137894468-1a65bf71-0318-48be-88b8-bff14186ceda.png)

**Desktop (please complete the following information):**
 - Browser Chrome 

Has anyone else has this issue?

**Comment by wobba** [comment]
That's the response data, not what the request is. You need to look at the bottom of the "headers" tab.

**Comment by PaulMac66** [comment]
Once again thank you both for your efforts on this issue. 

The fix you have put in place on version 4.4 for the refiners is working like a charm now.
I have fully tested this and labels with ( ) included are be display correctly and the connected search web part is displaying the correct number of items according to the count in the refiners web part. 

This is completely fixed

**Comment by PaulMac66** [comment]
I will close this issue.
