### ISSUE TITLE
On click of pagination, Filter panel is opening

### ISSUE THREAD

**Issue by SuriyakalaT** [microsoft-search/pnp-modern-search#1422]
**Version used**
Ex: 4.1.0.0

**Describe the bug**
After applying filters, clicking on pagination opens the filter panel instead of going to next page of result.

**To Reproduce**
1. Go to 'search results page (where pnp v4 search is configured)'
2. Click on 'Filter' and apply any one of the filter
3. Scroll down to pagination section and click on any number. 
4. it opens filter panel
5.It is the same behavior even after clearing filter. 

**Expected behavior**
search results should be navigated to next page(pagination) and should not open filter panel. 

**Screenshots**
![image](https://user-images.githubusercontent.com/92366603/138053518-6048419f-62f9-44e7-9fc3-fd0432b8a4eb.png)

**Desktop (please complete the following information):**
 - Browser [ chrome, edge]

**Additional context**
Checked in V3, there it is working fine.

**Comment by wobba** [comment]
Can you log the new issues as separate ones? Easier to track. Will close this as resolved.
