### ISSUE TITLE
Search Results webpart results count varies

### ISSUE THREAD

**Issue by JonoSuave** [microsoft-search/pnp-modern-search#1446]
**Version used**
4.3

**Describe the bug**
When I search for a term about thirty percent of the time the results count doesn't appear to apply the query template. In the  screenshots you'll see that sometimes the result count for a searched term is 37 results and sometimes it's 5842 results.

**To Reproduce**
1. Configure search results web part to query only a certain content types (I did this by ContentTypeId). Here's a snippet part of my query template: (ContentTypeId:0x0101007C71331914CDF34DA9FA1A3C6CAE54DA*) OR (ContentTypeId:0x0101009D1CB255DA76424F860D91F20E6C411800B344BE6A657FCF48BC5751475BB85ECC*) OR (ContentTypeId:0x0101001E7F795C9B221A49995F9ED1FD848423*) 
2. Search for a term from the OOB search box and have the site collection redirect to the page the PnP Search Web part is on
3. Run that search multiple time (you can just refresh the search results page multiple times)

**Expected behavior**
I expected Search Results web part results count to be the same every time for the same search term.

**Screenshots**
![Screen Shot 2021-10-26 at 12 59 13 PM](https://user-images.githubusercontent.com/22969971/138946144-aa1473de-ade0-4193-94ff-f2af62176b63.png)
![Screen Shot 2021-10-26 at 12 59 38 PM](https://user-images.githubusercontent.com/22969971/138946146-434936b0-053a-44fb-b6b5-53ea3937f497.png)

**Desktop (please complete the following information):**
 -Chrome

**Comment by JonoSuave** [comment]
I noticed a similar issue with Promoted results when this occurs: the correct promoted result and count flashes and then an unfiltered list of results shows with no promoted results. Once I take an action on the refiners web part the correct results are shown. This occurs on about 15-20 percent of our searches. What out-of-the-box web part can be used to show Microsoft it's a SharePoint search API issue?

**Comment by wobba** [comment]
@JonoSuave seems your issue is different as you mention flashing. I suggest you log this with repro steps if you think it's a web part issue.
