### ISSUE TITLE
Missing Properties "HitHighlightedSummary" and "AutoPreviewImageUrl"

### ISSUE THREAD

**Issue by KennethGagan** [microsoft-search/pnp-modern-search#1449]
This issue appears to be closely related to issues [#1387](https://github.com/microsoft-search/pnp-modern-search/issues/1387) [#1442](https://github.com/microsoft-search/pnp-modern-search/issues/1442
) [#1431](https://github.com/microsoft-search/pnp-modern-search/issues/1431)

**Version used**
Ex: 4.3.0.0
![image](https://user-images.githubusercontent.com/26394406/139158560-64ae340e-89b0-4f6c-80cd-5f1759a53528.png)

**Describe the bug**
I have a number of RefinableStrings defined as Search Managed Properties that I wish to use as Search Refiners:
![image](https://user-images.githubusercontent.com/26394406/139159011-886d69dd-7dde-461f-a4fc-4a3e975c1907.png)

When clicking on the Selected Properties to enable selection I get the spinning circle and the list never appears.
The work around for this issue is to manually enter the property names. So I manually add the properties into the combobox.
![image](https://user-images.githubusercontent.com/26394406/139159529-848fa2dc-c2d3-4fe5-9943-30dfa70dd578.png)

Full list of Selected properties: 
RefinableString03,RefinableString05,RefinableString06,RefinableString07,RefinableString08,Title,Path,DefaultEncodingURL,FileType,HitHighlightedSummary,AuthorOWSUSER,owstaxidmetadataalltagsinfo,Created,UniqueID,NormSiteID,NormWebID,NormListID,NormUniqueID,ContentTypeId,contentclass,UserName,JobTitle,WorkPhone,SPSiteUrl,SiteTitle,CreatedBy

The moment the new properties are entered The debug layout of the Search Results Web Part updates:
Now "HitHighlightedSummary" is null, "AutoPreviewImageUrl" is missing.

**To Reproduce**
1. Add Search Results webpart on page.
2. Set layout to debug
3. You can see the "HitHighlightedSummary" and "AutoPreviewImageUrl" properties....
![image](https://user-images.githubusercontent.com/26394406/139160710-5cc3cba0-b121-4b49-ad10-259ac5ca6f6e.png)
![image](https://user-images.githubusercontent.com/26394406/139160819-21876090-8448-4346-a426-7a117eb9dbf1.png)

4. Click into "Selected Properties"
5. Add new properties manually. 
 
![image](https://user-images.githubusercontent.com/26394406/139161030-7189832a-6d98-4b84-a199-c6fe43e9c62e.png)

6. You can now see the debug layout change to show the new properties that have been added, however "HitHighlightedSummary" is null, "AutoPreviewImageUrl" is missing.

![image](https://user-images.githubusercontent.com/26394406/139161289-e7571c9a-d7fa-4f8f-84a3-88cc5a05b63e.png)
![image](https://user-images.githubusercontent.com/26394406/139161403-3315872f-d8bb-422b-8855-fb48981bc0fd.png)

**Expected behavior**
I would expect to see the new properties and all the previous properties to remain unchanged.

**Desktop (please complete the following information):**
 - Browser Chrome & Edge

**Additional context**
Filters are working beautifully. No issue with that webart, the only issue is being able to format the layout of results list with a summary and a preview image.

Errors thrown in browser console:
![image](https://user-images.githubusercontent.com/26394406/139162227-9f5e5a4e-0dea-465d-8e5a-cb77eec6445f.png)

**Comment by apanada** [comment]
We have been using Microsoft Search as Data Source in PnP Search 4.5.3 latest version and for us, "AutoPreviewImageUrl" is null always. is there any way to get this value? 

But if SharePoint Search as Data Source in PnP Search 4.5.3, we get the value for the "AutoPreviewImageUrl" property.

![modern search issue](https://user-images.githubusercontent.com/25530129/152146059-8e8b01fe-024c-4be4-8a6b-ab12c48b6af2.png)

Also is there any provision to get the "AutoPreviewUrl" property with readable document preview but the not editable version of same?

        "AutoPreviewUrl": "https://m365x083241.sharepoint.com/sites/GermanContoso/Freigegebene Dokumente/Profile card templates.pptx?web=1"

**Comment by wobba** [comment]
@apanada Please log a new issue as this one is closed and resolved.
