### ISSUE TITLE
Modern Search: Refinement value filter

### ISSUE THREAD

**Issue by stijnbrouwers** [microsoft-search/pnp-modern-search#145]
When having a lot of values available for a refinement, it can be cumbersome to navigate through all of them to find the desired value to apply. 

It would be nice if for each refinement we can have an option 'show value filter' that, when checked, it shows a textfield. The textfield can be used to enter a string that will be used to match against the refinement filter values. Only the values will be shown that contain the value filter string.

![image](https://user-images.githubusercontent.com/9864443/77504731-75797a80-6e61-11ea-9f6f-3cb756e1ece5.png)
The above image shows a filtering on 'cust' which will only show refinement values that contain the string

**Comment by FranckyC** [comment]
Resolved by #146
