### ISSUE TITLE
Error making HttpClient request in queryable [500] when using URL parameter

### ISSUE THREAD

**Issue by HamEv** [microsoft-search/pnp-modern-search#1456]
**Version used**
3.22.0.0

**Describe the bug**
I'm dealing with KQL queries within URL parameter in a page, where I added a search result webpart. The KQL query is not very interessting, it's just /SitePages/Suche.aspx?k=Title:EG (Example 1). I tried some other queries with Title like /SitePages/Suche.aspx?k=Title:Buero (Example 2). Both (respectively all of my queries) are working correct with SharePoint Search Query Tool or /_api/search/query?querytext=
When doing my request with search result in some cases I get the error message: Error making HttpClient request in queryable [500] ::> {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"de-DE","value":"Unbekannter Fehler."}}}

I think that the response is somehow destroyed. Is there a possibility to get more information about the error or getting some detailed information? Is there any possibility to test my query?

It's really frustrating, because everywhere the search works like expeced and I do not have that much documents to return.

Thanks!

**Comment by wobba** [comment]
Also, can you try on the web parts without using a custom result source.

**Comment by HamEv** [comment]
Hi everyone, I removed my webpart and added a new one and tried everything step by step.
It's now working - thanks a lot for your help!
