### ISSUE TITLE
Permissions Slow to Apply

### ISSUE THREAD

**Issue by taylorSteeleIntergen** [microsoft-search/pnp-modern-search#1464]
**Version used**
3.16.0.0

**Describe the bug**
SharePoint permissions are slow to apply and users are able to see content that they do not have access to. 

**To Reproduce**
- User is a Site Owner on a site. As an owner they have access to a file called "Top Secret". When they use Modern Search, the item appears. When they use the out-of-the-box search, the item appears. 
- User has their permissions to the site removed. 
- When they use Modern Search, the "Top Secret" file still appears. If they select the file they receive an access denied message. When they use the out-of-the-box search, the item does not appear. 
- Around an hour or two later, the item no longer appears in Modern Search. 

**Expected behavior**
- When the user's access to the site is removed, the item immediately disappears from Modern Search. 

**Desktop (please complete the following information):**
 - Microsoft Edge

**Comment by FranckyC** [comment]
Hi @taylorSteeleIntergen, maybe https://github.com/microsoft-search/pnp-modern-search/discussions/1460 can help you. I close this one as it is not directly related to the Web Parts.

**Comment by taylorSteeleIntergen** [comment]
@FranckyC, I disagree that this is not related to the web parts. The issue only appears when using the web parts, the permissions work as expected in both classic and modern search.

**Comment by FranckyC** [comment]
@taylorSteeleIntergen then you must inspect the query to see if this is the same as other interfaces. I guess not because there is no security trimming or anything like this in the Web Parts, the secruity part is done at API level.

**Comment by taylorSteeleIntergen** [comment]
@FranckyC does the web part cache results at all?

**Comment by FranckyC** [comment]
There is no cache mechanism there

**Comment by wobba** [comment]
You have to wait for a security crawl to occur so that ACL's are updated in the search index. This runs at an irregular interval we cannot control.

The quickest way to have item access revoked is to grant access via AAD groups and not on items themselves.
