### ISSUE TITLE
with reference to #1422 flickering of filter panel occurs on clicking pagination and page is not moving to top of the result

### ISSUE THREAD

**Issue by SuriyakalaT** [microsoft-search/pnp-modern-search#1465]
**Version used**
Ex: 4.4

**Describe the bug**
This is in continuation with #1422.As suggested in #1422 updated search to v4.4 now filter panel is not opening fully(on clicking pagination) but appears for a fraction of second causing the page to flicker and also view is not moved to top of the page.

**To Reproduce**
1.create a search result page with pnp v4.4 search results, search verticals and search filter webparts 
2. use basic configurations to fetch results based on query string.
3.allow pagination in search results and select panel in filter layout.
4.Add more than one filter in the filter webpart.
5.search any keyword to fetch results with pagination.
6.Apply filter, check pagination
7. Filter panel appears and disappears within fraction of second
8. Page is not moved to top of the result

**Expected behavior**
Pagination should not open filter panel,
Pagination should navigate to the selected page and display top of the result page,
Page should not flicker on clicking pagination (after applying filter) 

**Screenshots**
Not able to capture

**Desktop (please complete the following information):**
 - Chrome, edge

**Comment by FranckyC** [comment]
Hi @SuriyakalaT, are you using v4.4 or 4.3? Not so obvious in your description as you mention the two versions.

**Comment by SuriyakalaT** [comment]
Hi @FranckyC , version tested are v4.3 and v4.4 , included 4.3 in procedure by mistake, rectified now.

**Comment by wobba** [comment]
Re-log if still an issue.
