### ISSUE TITLE
Log handlebar-helper does not write to console output

### ISSUE THREAD

**Issue by sw00sh0r** [microsoft-search/pnp-modern-search#1472]
**Version used**
4.4.1

**Describe the bug**
The handlebar helper for writing logs to the developer console doesn´t work anymore in the current released version when used in a custom template for Search Results web part.

**To Reproduce**
1. Go to any custom template in Search Results web part
2. Insert line `{{log "Hello world"}}`
3. See no log in console window in dev tools

**Expected behavior**
Line "Hello world" logged to console output in dev tools

**Screenshots**
In v3.15.3 logging works:

![image](https://user-images.githubusercontent.com/68747426/140042304-fde92e4b-b896-48ba-9003-d07fefaf7ec1.png)

**Desktop (please complete the following information):**
Microsoft Edge (Chromium Version 95.0.1020.40 (Official build) (64-bit)

**Additional context**
In Version 3.15.3. the handlebar helper logs the line "Hello world" to the browser´s console output as expected, see screenshot

Edit:
I did a little testing, the last working version logging to dev tools console using the log handlebar is v3.16.0
As of v3.17.0, logging no longer works.

I compared v3.16.0 with v.3.17.0, maybe the bug is related to this change in die gulpfile.js:

![image](https://user-images.githubusercontent.com/68747426/140075871-4351585a-8c53-491d-a534-b3b3bb243ddc.png)

**Comment by wobba** [comment]
Hi, when updating to the latest handlebar-helpers we had to omit logging to have webpack work. If you find a way for it to work feel free to PR. As logging is not needed for end-user functionality I decided to omit it. I can update docs on this.
