### ISSUE TITLE
Multi select combo filter with Multi value managed property shows No results

### ISSUE THREAD

**Issue by SjoerdV** [microsoft-search/pnp-modern-search#1475]
**Version used**
4.4.1.0

**Describe the bug**
Multi value/select 'Tags' filter does not get passed through to Results parts on page. The connected Results parts will always show zero results when any Tags filter value is selected.

**To Reproduce**
1. CREATE following layout and connect all the parts (Filters is connected to all 3 Results (and vice versa), SearchBox is connected to all three Results, all Results only show when the right Vertical is selected)
```
|Verticals              |Filters        |
|SearchBox              |               |
|Results 1 SharePoint   |               |
|Results 2 Graph        |               |
|Results 3 People       |               |
```
2. SEARCH for 'zip' without quotes
3. I get several results with these Filters (Created, Size, DisplayAuthor, RefinableString00) (see screen 1)
4. Filters are set to 'AND' operator (also doe not work with 'OR)', 
5. With 'RefinableString00' mapped to 'ows_taxId_MetadataAllTagsInfo' (same results with default 'owstaxidmetadataalltagsinfo' managed property, btw)
6. RefinableString00 = Multi-value with 'OR' operator with Combobox setting (also does not work with 'AND')
5. Now when I select a 'DisplayAuthor' filter value (Displayname 'Author') all is well, so there is no issue with connections!
6. Now deselect all Filters and select 1 of the values under 'Tags'. 
7. This leads to NO RESULTS, for any combination or selection. 
8. the Filter will also show 0 results for the selected filter values (see screen 2)

**Expected behavior**
I expect the filter to show results where the filter is applicable and show some result.

**Screenshots**
screen1:
![image](https://user-images.githubusercontent.com/13275320/140048865-c14084ce-57e8-45ac-ab56-e794416c92b5.png)
screen 2:
![image](https://user-images.githubusercontent.com/13275320/140048411-5659fbd9-2a46-43c8-893c-a85c351f2961.png)
screen 3:
![image](https://user-images.githubusercontent.com/13275320/140050393-ffcb1b6c-5942-4064-acdf-1eba5758d5a5.png)

**Desktop (please complete the following information):**
 - Browser: Tested with Edge (Chromium) and Brave

**Additional context**
- v3 webparts (on another site, same tenant) just work correctly btw.
- Unfiltered the Results parts (SharePoint and Graph) do show the Tags on the Cards (see screen 3)

**Comment by wobba** [comment]
Currently filters do not clear when switching a vertical, is that the behavior you want?

**Comment by SjoerdV** [comment]
I am totally fine with filters remaining when switching verticals. 

I am now on version 4.8 of the solution and the issue reported (showing zero results when a multiselect filter is applied) is solved in the meantime so I will close it gladly!
 
Still: Great webparts btw!
