### ISSUE TITLE
Tag description instead of whole content of AllTagsInfo...

### ISSUE THREAD

**Issue by CarlVerret** [microsoft-search/pnp-modern-search#1481]
PNP Search reults,  Version: 4.4.1, Display in list mode

This is more a question than a bug
Is there a  way to display Tag Description instead of all the tags info : 
For example:  I'm getting this 

L0|#0dcfff126-bb85-44e9-8ef2-45ba018bd3ab|Formulaires
 
Instead of only "Formulaires"

Thanks!

**Comment by FranckyC** [comment]
Hi @CarlVerret, please use the "Discussion" tab for questions instead of creating a new issue. To answer your question please see https://github.com/microsoft-search/pnp-modern-search/pull/1468. Using `{{last (split name "|")}}` should do the trick.
