### ISSUE TITLE
No results when i define "RecommendedItems" inside the "Result source ID" inside "PnP - Search Results"

### ISSUE THREAD

**Issue by mvcsharepointdev** [microsoft-search/pnp-modern-search#1489]
I added a  "**PnP - Search Results**" and inside the "Result source ID" i defined "define "RecommendedItems" .. but i did not get any results.. is this a bug?

**Comment by wobba** [comment]
No, v4 requires you to enter the guid/id of the result source. Closing as this is not following the issue template. I recommend reading the docs at https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/#sharepoint-search.
