### ISSUE TITLE
KQL gives CorrelationID error when using AND

### ISSUE THREAD

**Issue by myatix** [microsoft-search/pnp-modern-search#1499]
**Version used**
Ex: 4.4.1

**Describe the bug**
Should the following refinement filter not work? This is a managed property I have mapped to a Manage Metadata column

RefinableString00 is mapped to ows_taxId_ColumnName

![image](https://user-images.githubusercontent.com/48433526/140938917-cdbe8dd5-7c18-4b56-a21b-de9e267c7332.png)

`RefinableString02:"GPP|#e2c6be1c-47df-421a-85a5-e4e132d6d2d0" AND RefinableString02:"GP0|#e2c6be1c-47df-421a-85a5-e4e132d6d2d0"`

**To Reproduce**

As soon as I add the "AND" switch to the refinement filter I get a correlationID error?

**Comment by wobba** [comment]
Try to repro outside of PnP parts. If you can, then log a support issue. If only in these parts, copy out the request JSON on the postquery API call (assuming you use the SP provider)

**Comment by myatix** [comment]
@wobba If you would like me to provide the JSON on post query then you will need to provide me with info to do that as I am not a Dev. 

I have tried posting the exact same query as provided in the screenshot in the Out of Box "Highlighted Query" WebPart and I don't get a correlation ID Error???

In terms of the incomplete submission:

To recreate this issue:

1. Create a document library list.
2. Create a column with managed Matadata EG ColumnName and use a nested term set.
3. Setup a RefinableString managed property for the above column
4. Choose the RefinableString in the "Selected Properties" for the pnp modern results webpart
5. Configure Search results webpart with a Search Query pointing to the list created in step 1.
EG:
`Path:https://<tenant>.sharepoint.com/sites/O365_Test/Delte%20dokumenter`

6. Then add a refinement filter for the RefinableString managed property created in step 3
EG:
 `RefinableString02:"GPP|#47e50123-9406-41e8-a46f-b4f265ca7c1d" AND RefinableString02:"GP0|#47e50123-9406-41e8-a46f-b4f265ca7c1d"`

**Comment by wobba** [comment]
Hit F12 in your browser. Go to the network tab and try to grab the request payload. Below screenshot is using Chrome. Should be similar in Edge.

![image](https://user-images.githubusercontent.com/51104/141943003-583d0323-418b-4df1-9aa1-fb655f220d4e.png)

**Comment by wobba** [comment]
For point 6, you are adding it using KQL. refinement filters are using FQL. Add it to your query template instead. Result is the same.

**Comment by myatix** [comment]
@wobba I hope you can use this?

{
  "lang": "en-US",
  "value": "Invalid parameter: RefinementFilters."
}

![image](https://user-images.githubusercontent.com/48433526/141960862-6fef40af-3a6b-4c83-96aa-78d91981f0ac.png)


Failed to load resource: the server responded with a status of 400 (Bad Request)
modern-search-results-web-part_f0739c37e7778c38f861.js:1 Uncaught (in promise) Error: [HTTP]:400 - Bad Request [CorrelationId]:5aa403a0-e007-3000-647a-afcd236497b3 [Version]:16.0.0.21903
    at f.<anonymous> (modern-search-results-web-part_f0739c37e7778c38f861.js:1)
    at Generator.next (<anonymous>)
    at a (modern-search-results-web-part_f0739c37e7778c38f861.js:1)

**Comment by myatix** [comment]
Also looks like the documentation is outdated if this is the case?

> For point 6, you are adding it using KQL. refinement filters are using FQL. Add it to your query template instead. Result is the same.

https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/

<html>
<body>


Refinement filters | The initial refinement filters to apply to the query. Both KQL (Keyword Query Language) and FQL (Fast Query Language) expressions work here (Ex: KQL FileType:docx, FQL: FileType:equals("docx")). They will be applied every time to the current search query regardless selected filters from connected Web Parts. Note: for string expressions, use " instead of '. | None.
-- | -- | --



</body>
</html>

**Comment by wobba** [comment]
Indeed the docs are wrong.. as `FileType:docx` is valid both for kql and fql, while `foo AND bar` is not.
