### ISSUE TITLE
Site title not showing on tiles layout

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#15]
It's instead showing the title of the current site with {{}} around it.

![image](https://user-images.githubusercontent.com/51104/68248946-d6580180-ffeb-11e9-8213-a4d0780fb36c.png)

Related to tiles.html which uses JSON.stringify instead of passing in explicit properties

**Comment by FranckyC** [comment]
I'm no able to reproduce it. The site title is correctly displayed. What is the value of the 'SiteTitle' mp in the debug view?

**Comment by wobba** [comment]
The correct one, and if I copied from the carousel template it worked. I can look into it later as well.

**Comment by FranckyC** [comment]
Can I close this one or you can reproduce?
