### ISSUE TITLE
RefinementName on refinement options seems to have been updated

### ISSUE THREAD

**Issue by joelfmrodrigues** [microsoft-search/pnp-modern-search#151]
**Version used**
Ex: 3.10.0.0

**Describe the bug**
RefinementName seems to have been updated and is now introducing some bugs on the selected refiners. This seems to have been introduced recently.
Also mentioned in #134 

**To Reproduce**
Of of the examples is when selecting multiple refiners
1. set a refiner to multi select
2. select 2 options
3. unselect one of the options
4. both options are unselected

**Expected behavior**
Selected refiner values to be correctly recognized and handled

**Screenshots**
![image](https://user-images.githubusercontent.com/19577724/77754735-d51f8380-7023-11ea-8b3f-9344c9bdff38.png)

**Additional context**

**Comment by joelfmrodrigues** [comment]
I can submit a PR to update the properties on CheckboxTemplate to use the RefinementValue property instead

**Comment by FranckyC** [comment]
Hi will submit a PR for this because it affects other templates as well but thank you for sunbmitting this issue, I didn't check all the templates.

**Comment by FranckyC** [comment]
Should be OK now
