### ISSUE TITLE
Getting an Error while trying to search people using LocalSharePointResults Recourse ID

### ISSUE THREAD

**Issue by sumitdeyonline** [microsoft-search/pnp-modern-search#1512]
### Check existing issues before logging new ones
There is no issue like this before

**Version used**
Ex: 4.4.1.0

**Describe the bug and Reproduce**
When we were trying to search any people name like "sumit dey"  using LocalSharePointResults Recourse ID, we are getting the following error 

[HTTP]:500 - Internal Server Error [CorrelationId]:c03902a0-8083-c000-840c-7fabb92e7978 [Version]:16.0.0.21827

![image](https://user-images.githubusercontent.com/23446009/141386123-494b6bb1-4130-4d42-9642-7c0125178db8.png)
In the Browser console 
![image](https://user-images.githubusercontent.com/23446009/141386294-f3d283fb-ad3f-488e-bc4d-a15e277a269f.png)

We have used "Sharepoint Search" and query template like below 

Path:https://xxx.sharepoint.com/sites/X1 OR Path:https://xxx.sharepoint.com/sites/X2 OR Path:https://xxx.sharepoint.com/sites/X3 OR Path:https://xxx.sharepoint.com/sites/X4 {searchboxquery}

Result source ID : LocalSharePointResults

When we are searching for anything other than a name, it works absolutely fine. 

**Expected behavior**
If there is no record, it should show "0 results for Sumit Dey" only, instead of through an error on the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/23446009/141386123-494b6bb1-4130-4d42-9642-7c0125178db8.png)

**Desktop (please complete the following information):**
 - Browser [Chrome, Edge]

**Comment by wobba** [comment]
You cannot use path filter and people together. People are a separate index outside of sites.

**Comment by wobba** [comment]
@sumitdeyonline did you resolve this, or have more information to share?

**Comment by sumitdeyonline** [comment]
This issue has been resolved using "LocalPeopleResult" as a result source Id.
