### ISSUE TITLE
Search : Have to click the apply button 'twice' for the clear button to display as active

### ISSUE THREAD

**Issue by SaltySweats** [microsoft-search/pnp-modern-search#1522]
**Version used**
4.4.1.0

**Describe the bug**
When using PnP Search Filters, a user has to click the 'Apply' button twice before the 'Clear' button appears.

**To Reproduce**
Note: This issue is reproduceable if you click on a filter that equals the amount of results in the search results section. If you use a refiner that has only a few items, it works as expected.

1. Click on an available filter on a pnp search results page: 
![image](https://user-images.githubusercontent.com/36278490/141817349-167d7307-e514-4e63-8ba3-08c0dfd2df41.png)

2. Click on 'apply':
![image](https://user-images.githubusercontent.com/36278490/141817404-34b2f2d2-9533-4de7-970b-62d78ad3d948.png)

3. Notice the 'clear' button is not active:
![image](https://user-images.githubusercontent.com/36278490/141817473-d322fb78-2d05-46dd-a2c6-ab7a6c366f27.png)

4. Click on the apply button again and notice the clear button is now active:
![image](https://user-images.githubusercontent.com/36278490/141817561-95f6598b-0506-413d-8e22-8444d540217c.png)

**Expected behavior**
When a user clicks on the 'apply' button the first time, the 'clear' button should be active.

**Screenshots**
Using a refiner with less than the amount of total results works as expected. On the first click of the 'apply' button, the clear button shows as active:
![image](https://user-images.githubusercontent.com/36278490/141817967-7c41bd51-c6a7-4992-9bda-9e8e1638d042.png)

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
None

**Comment by wobba** [comment]
I cannot repro. Clear becomes active as soon as I click apply.

**Comment by SaltySweats** [comment]
@wobba  Thank you for checking. Did you attempt to use a refiner that had the same # of results as the total # of results? In the scenario above, I chose a refiner that had 66 results and there was 66 results total (with no refiners selected), that's the current use case of the issue.

**Comment by wobba** [comment]
If you pick a refiner which has less than the total, does it work then?

**Comment by SaltySweats** [comment]
@wobba  yes it does work in that case, this is only when you select a refiner with the same # of results as the total. Are you able to reproduce?

**Comment by wobba** [comment]
Will be fixed in 4.9
