### ISSUE TITLE
Search vertical is resolving {searchTerms} to "undefined" when search was not yet executed.

### ISSUE THREAD

**Issue by till-llit** [microsoft-search/pnp-modern-search#1532]
**Version used**
4.5.0

**Describe the bug**
Vertical is resolving {searchTerms} to "undefined" when search was not yet executed.

**To Reproduce**
1. Have a Verticals Webpart with a hyperlink vertical. use the {searchTerms} parameter in the link url.
1. Enter a term in the search box, **but do not execute the search.** 
1. Click on the Search Vertical to navigate to the external url
1. {searchTerms} is resolved to the string "undefined" in the url

**Expected behavior**
{searchTerms} should be resolved to the search box term. if this is not possible because the search was not yet executed {searchTerms}  should at least resolve to Empty String. 

**Screenshots**

**Desktop (please complete the following information):**
MS Edge 94

**Additional context**

**Comment by till-llit** [comment]
issue is still reproducable with 4.5.0

in both cases (empty search box and search box with text, but never executed) the parameter {searchTerms} is "undefined"

**Comment by wobba** [comment]
Closing as it resolves to empty string with v4.8 from my testing.
