### ISSUE TITLE
`{?{searchTerms} .... }` syntax not properly handled (V4)

### ISSUE THREAD

**Issue by stevebeauge** [microsoft-search/pnp-modern-search#1535]
**Version used**
4.4.1.0 (nov 2021)

**Describe the bug**
 The following query template stopped to works as expected: `{?{searchTerms} IsDocument:true}`.

This query results in returning what I guess to be the whole search index (behaves like `*`) instead of conditioning the query inside the brackets to the presence of a search terms, when no value is provided

**To Reproduce**
Put a search result webpart on a page.

Set its query template to `{?{searchTerms} IsDocument:true}`.

=> This returns the whole SP index (not expected)

Bind the search box to the result web part.

Type something ==> correct results are returned.

Empty the search box ==> whole SP index is returned (ignoring the other properties).

**Expected behavior**
The expected behavior is to get no result when nothing is typed in the search box. When something is typed, both search terms and other conditioned property restriction are applied (this works)

In user terms, search terms is mandatory to get results.

**Desktop (please complete the following information):**
 - Edge Chromium and Firefox

**Additional context**
When using the Debug layout, I can see :

* when search box is empty, there's no `$.data.queryModification` at all
* when search box is not empty, there's a `$.data.queryModification` equals to `something IsDocument:true -ContentClass=urn:content-class:SPSPeople`

I would bet on a incorrect parsing of tokens.

**Comment by wobba** [comment]
Can you check what the request looks like... is it sending * or a blank query? If a blank query this is a known API bug which is being worked on. As a blank query should return nothing, not wildcard.

**Comment by stevebeauge** [comment]
Not sure how to check that, but comparing the REST requests in the browser tools show this diff:
![image](https://user-images.githubusercontent.com/184604/142272839-17879a20-8272-4060-8b32-d99eb8f99b29.png)

The only diff is the missing query text, which seems to be what you are talking about. By API do you mean it's a Sharepoint OOB issue, not pnp modern search fault? Do you have link to an issue I can follow ?

Thanks

**Comment by wobba** [comment]
Ahh.. it's missing, then it's an API issue - and it has been reported internally and is being worked on afaik.

**Comment by Laetterman** [comment]
> Ahh.. it's missing, then it's an API issue - and it has been reported internally and is being worked on afaik.

Hi @wobba 
It was me that has reported the issue over a separate channel because it is not pnp webpart related. Do you have any news from the search backend team?

Regards
Marc

**Comment by wobba** [comment]
@Laetterman I don't have an update and not actively tracking the fix. You should ask thru your support ticket.

**Comment by wobba** [comment]
@stevebeauge is this working for you in the latest release as we changed token handling?

**Comment by Laetterman** [comment]
Hi @wobba: the main issue still exists as it has nothing to do with the PnP Modern Search Webpart. From our side we did a workaround using a 'dummy/hidden' default search term with the &lrm; character. The best way is to copy it from here and put it in your config.

The only 'downside' is that you get a "0 results found for ''" but or us it is acceptable... :-)

https://unicode-explorer.com/c/200E

**Comment by stevebeauge** [comment]
I check again, to be sure.

The issue is still present using `{?{SearchTerms} Path:{Site}}` in a page.

Empty query : query modification not present at all

![image](https://user-images.githubusercontent.com/184604/153175891-a62b3d91-f5d3-4aca-9d73-b2f57487b44f.png)

Non empty query : query modification actually present

![image](https://user-images.githubusercontent.com/184604/153176061-6a209695-0dfa-4546-9717-599453a536ab.png)

**Comment by wobba** [comment]
Hi, this is an API issue which I'm trying to track internally to get a fix for. It only applies to some tenants (more and more).

**Comment by IvanTheBearable** [comment]
> Hi @wobba: the main issue still exists as it has nothing to do with the PnP Modern Search Webpart. From our side we did a workaround using a 'dummy/hidden' default search term with the &lrm; character. The best way is to copy it from the link below and put it in your config.
> 
> The only 'downside' is that you get a "0 results found for ''" but or us it is acceptable... :-)
> 
> https://unicode-explorer.com/c/200E

@Laetterman - a small update to your template will fix that 'downside':
```handlebars
{{#if @root.properties.showResultsCount}}
<div class="template--resultCount">
  {{#isnt @root.inputQueryText '&lrm;'}}
    <label class="ms-fontWeight-semibold">{{getCountMessage @root.data.totalItemsCount @root.inputQueryText}}</label>
  {{/isnt}}
</div>
{{/if}}
```

**Comment by till-llit** [comment]
we have this bevahiour now on our productive tenant. i suspect the new cloud search plattform is the reason for this behaviour.

we only have this since the X-SearchPlatform changed to "Substrate". it also changed the behaviour of the default search page /_layouts/15/search.aspx that is now also loading for ages to display all results without search term.

**Comment by wobba** [comment]
@till-llit you should log a support case with Microsoft about this.

**Comment by wobba** [comment]
I made a fix that if `{searchTerms}` is empty, we pass it downstream for the API to resolve the `{?}` part.
