### ISSUE TITLE
Promoted Results Flash and then are not displayed on occasion

### ISSUE THREAD

**Issue by JonoSuave** [microsoft-search/pnp-modern-search#1536]
**Version used**
Ex: 4.3

**Describe the bug**
The correct promoted result and count flashes and then an unfiltered list of results shows with no promoted results. Once an action is taken on the refiners web part the correct results are shown. This occurs on about 15-20 percent of our searches.

**To Reproduce**
1. Create a new tenant result source for managed query rules and add for each query rule promoted results
2. As part of the newly created result source configurations I set the Query Transform like so: {searchTerms} -FileType:msg  -FileType:sql  -FileType:html -FileType:htm -FileType:ms-one-stub -FileType:mmap -FileType:ppkg -FileType:js -FileType:css -FileType:sql  -FileType:md -FileType:eml -FileType:jpeg -FileType:jpg -FileType:bmp -FileType:svg -FileType:png Path:"https://{tenant}.sharepoint.com/sites/(any site that begins with a chosen prefix)_*" -FileName:DispForm.aspx -FileName:AllItems.aspx
3. On the PnP Search Results web part configure it to have the GUID that refers to the result source created
4. Test out a promoted result and try refreshing the page up to 6-7 times. On one of the refreshes (could be the first) you'll see the promoted result flash and then go away.

**Expected behavior**
Expected promoted results to consistently display on query rule search

**Screenshots**
<img width="756" alt="Screen Shot 2021-11-17 at 11 25 33 AM" src="https://user-images.githubusercontent.com/22969971/142250969-7d4fdc20-0137-43a6-b8af-f66a80b4f5ad.png">
<img width="746" alt="Screen Shot 2021-11-17 at 11 26 15 AM" src="https://user-images.githubusercontent.com/22969971/142250974-b8c1b71d-502e-4391-99a7-199d81eae38f.png">

**Desktop (please complete the following information):**
 -Chrome

**Additional context**
I don't believe it made a difference in my testing, but I also included eight ContentTypeId properties in the apply template along with Path (i.e. I only wanted results beginning with a specific path).

**Comment by JonoSuave** [comment]
Checking to see if there's an update on the triage?

**Comment by wobba** [comment]
Updates will happen when we look at it. I just tag issues which has to be looked into when time allows.

**Comment by wobba** [comment]
@JonoSuave can you recheck if this is still the case with the latest version?
