### ISSUE TITLE
Show persona card on hover shows different card for other users

### ISSUE THREAD

**Issue by meklulose** [microsoft-search/pnp-modern-search#1537]
**Version used**
 PnP Modern Search v 4.3

**Describe the bug**
I am using PnP Modern Search v 4.3. When I enable the "show persona card on hover", it is showing different result when I am viewing my own card vs when I am viewing another user's card. The following is when I am logged in as user test
![image](https://user-images.githubusercontent.com/81180944/142256092-cd5fb452-2ca2-4b75-8d40-9cd93f05897b.png)

when I look at user test88 I am seeing less information
![image](https://user-images.githubusercontent.com/81180944/142256147-3520e339-1b11-493a-a533-8eaf2c0c6131.png)

Is this an expected behavior? Ideally I want to be able to see the same information I am seeing in picture 1. I have asked the same question in Q&A as I wasn't sure if this is expected behavior or a bug. 

**To Reproduce**
1. Enable "Show persona card"
2. Search for a user 
3. Hover over user
4. Only contact is shown

**Expected behavior**
I would be able to see skills and experience as well as other tabs similar to image 1 

**Desktop (please complete the following information):**
 - Browser used Chrome and Microsoft edge

**Comment by wobba** [comment]
We have no control over this component and could be depending on what access scopes have been granted. Issues with the persona card should be logged at https://github.com/microsoftgraph/microsoft-graph-toolkit

**Comment by wobba** [comment]
Closing as also logged as a discussion.
