### ISSUE TITLE
SearchBox : Cannot read properties of undefined (reading 'q')

### ISSUE THREAD

**Issue by kachihro** [microsoft-search/pnp-modern-search#1550]
**Version used**
3.20

**Describe the bug**
When editing the page, and properties of SEARCH BOX, the left hand side is shown as BLANK.
When saving the page, there is a SharePoint 'something went wrong' error.

_ERROR:
Cannot read properties of undefined (reading 'q')_

This occurs when using the 'page environment' and querystring such as Q or K.    And - editing the page doesn't have this value.

**To Reproduce**
Define a search page with SearchBox and SearchResults.    Include a querystring 'dynamic source'.
When page is working OK, clear the querystring - eg. SearchResults.aspx (only)

Then edit the page - and edit the webpart (SearchBox)

Have to then change to an old 'version history' for the page.

_NOTE :   similar problem within 4.4.1 (new) version - but shows as [object Object]_

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/16025947/142938582-25617086-d055-4504-9c20-c7302d7c82b7.png)

![image](https://user-images.githubusercontent.com/16025947/142938631-194432ce-1b87-446f-af18-01bce0e97335.png)

**Comment by wobba** [comment]
We'll see if we can catch this in a good way. Workaround is to always have the required query params when editing the page.

**Comment by kachihro** [comment]
Yes - that's what I do now.   It's not so bad in the new 4.1 version - I'll take a look into it, and see if I can intercept (eg. null check)
