### ISSUE TITLE
Incorrect issue number listed 1232 should be 1282

### ISSUE THREAD

**Issue by mbalcarek** [microsoft-search/pnp-modern-search#1552]
**Version used**
Ex: 4.4.1.0

**Describe the bug**
On page https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.4.1 you reference issue 1232, but it should be 1282.😉

**To Reproduce**
1. see above

**Comment by FranckyC** [comment]
Haha nice catch @mbalcarek! Fixed, sorry for the typo.
