### ISSUE TITLE
Unable to filter the localSharePointresult using the CreatedBy or author fields inside my PnP Modern Search web part

### ISSUE THREAD

**Issue by mvcsharepointdev** [microsoft-search/pnp-modern-search#1553]
I am using the pnp-modern-search v4 and i have the following Search Result web part:-

![S1](https://user-images.githubusercontent.com/79726511/143293357-ceae8d99-3188-4535-85bf-b4e1c112d5ba.png)

which mainly searches everything inside a specific site collection.

Then i defined the following filter web part, to filter the results based on; Created + File type + Created By (Author), here is my filter web part's settings:-

![S2](https://user-images.githubusercontent.com/79726511/143293454-e2772499-4219-4af8-aa9f-067cf7fc67cc.png)

but when i save the page >> i will only get the Created + the File Type, while the Created By & Author filters will be missing, as follow:-
![s3](https://user-images.githubusercontent.com/79726511/143293494-a2339fac-6ac7-48ed-b753-7509af28ae4e.png)

also if i add a new filter web part and i only chose to filter based on the Created By i will get this error:-
![s4](https://user-images.githubusercontent.com/79726511/143293303-7c74a1a1-73f9-4c2d-969b-e1342065aef7.png)

any advice why i am unable to filter the search result using the CreatedBy/Author?

**Comment by FranckyC** [comment]
Hi @mvcsharepointdev, `CreatedBy` and `AuthorOWSUSER` are not refinable managed properties by default so can't be used as refiners. You must use `RefinableStringXX` properties in your search schema mapped to the corresponding crawled properties to make it work.
