### ISSUE TITLE
"LocalPeopleResults" inside "PnP-Search Results" web part will not show any results unless we check the "Enable audience targeting" checkbox

### ISSUE THREAD

**Issue by mvcsharepointdev** [microsoft-search/pnp-modern-search#1554]
I added a "PnP-Search Results" we part v4. and i defined the "Result source ID" to be "LocalPeopleResults", as follow:-

![w1](https://user-images.githubusercontent.com/79726511/143325227-7059a246-179e-4007-8d22-2b5a71623eda.png)

but the web part will not show any results unless we check the "Enable audience targeting" checkbox, as follow:-

![w2](https://user-images.githubusercontent.com/79726511/143325213-b373acbd-4190-4b60-9b17-b24ee6606a4f.png)

so why this is the case?
Thanks

**Comment by FranckyC** [comment]
Hi @mvcsharepointdev, what value did you put as query template? Does it work with `{searchTerms} *` for instance without the flag enabled?

**Comment by wobba** [comment]
Can you try with the guid instead? `b09a7990-05ea-4af9-81ef-edfab16c4e31`

**Comment by mvcsharepointdev** [comment]
Hi @FranckyC  thanks for the comment, the Query template is as follow "{searchTerms} path: [https://******.sharepoint.com/](https://*****.sharepoint.com/)"

**Comment by mvcsharepointdev** [comment]
@wobba  thanks for the reply.. but this is the guid of what exactly ?

**Comment by wobba** [comment]
You shouldn't need to use a `path` filter with people results. That guid is the underlying id of LocalPeopleResults.

**Comment by wobba** [comment]
Put the cursor in the field and start typing. It's a combo box.
![image](https://user-images.githubusercontent.com/51104/143414674-b3e68cb1-a328-4bb9-a467-b5d632b12c6a.png)

**Comment by mvcsharepointdev** [comment]
@wobba ok i tired to define the Guid but it did not fix the issue... still i need to enable Audience Target to get the results...any advice? thanks

**Comment by wobba** [comment]
Audience targeting should not have anything to do with this, as it doesn't apply to people search. You need to figure out if the search request is sent correct, then look at the response. Likely it's an API issue. You should try the setup on a different tenant as well.

**Comment by mvcsharepointdev** [comment]
@wobba i tired on the customer tenant + on our tenant and both had the same behavior.. the People will not show unless we enable Audience Targeting ...  that looks really weird .. any advice? thanks

**Comment by wobba** [comment]
I cannot repro. Picked LocalPeopleResults as the source, added * as the querytemplate, picked the people template, and I get all people in my demo tenant.

**Comment by mvcsharepointdev** [comment]
> repro

this is not working neither inside our tenant nor inside our customer tenant...

**Comment by kasperbolarsen** [comment]
@mvcsharepointdev , did you found the reason for this error or a work around?

**Comment by wobba** [comment]
@mvcsharepointdev is it working via the Search Query Tool or via classic search web parts?
