### ISSUE TITLE
Handlebar {{#if xxx}} doesn't work within HTML Table in Search Results Layout Template

### ISSUE THREAD

**Issue by droper-lcb** [microsoft-search/pnp-modern-search#1571]
**Version used**
4.4.1

**Describe the bug**
Hi Team, When customising the search results template, I'm trying to do a simple #if around a row within a html table, and it seems to be ignored and the row is always shown.
If I wrap the same #if around the whole table it works fine, just not within / around an individual `<TR>` tag.

**To Reproduce**
Wrap an #if around a table row:

`<table>`
`{{#if RefinableString07}}`
`<tr>`
`<td>Some String</td>`
`<td>{{RefinableString07}}</td>`
`</tr>`
`{{/if}}`
`{{#if RefinableString09}}`
`<tr>`
`<td>Another String</td>`
`<td>{{RefinableString09}}</td>`
`</tr>`
`{{/if}}`
`</table>`

**Expected behavior**
#if works within html table

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by FranckyC** [comment]
Hi @droper-lcb , quite hard to debug without the template content. Can you share it so we can see the structure?

**Comment by droper-lcb** [comment]
Hi @FranckyC and thanks for replying.

Its a customised version of the inbuilt list template, where I just stripped out the Summary and Tags and replaced with this table.

![image](https://user-images.githubusercontent.com/95255041/143959202-b4551fe3-ab7f-4313-b922-dd07ab258ac3.png)

But interestingly, if I save the template as HTML file and just view it in the browser, it renders the #if above the tablerows. Not sure if that's related but certainly would explain it.

![image](https://user-images.githubusercontent.com/95255041/143959537-9a3a2222-c15e-40c1-9836-f6a9a1457af9.png)

**Comment by FranckyC** [comment]
Did you try without the `<table>`?

**Comment by droper-lcb** [comment]
It works as expected outside the table, so either affecting the whole table itself, or not using a table at all then its fine. 
Just within the table the {{#if}} is ignored and the data is rendered regardless.

**Comment by FranckyC** [comment]
Can't really tell why it doesn't work :/. Anyway HTML `<table>` is not so modern and can be easily replaced by flex boxes.

**Comment by FranckyC** [comment]
I'll close this one for now as you found a workaround.
