### ISSUE TITLE
Filter Webpart: check box selection in the panel layout the panel got refreshed.

### ISSUE THREAD

**Issue by rdksp2013** [microsoft-search/pnp-modern-search#1574]
Issue: i have used panel layout in filter web part and the issue is we have more than 100 options in filter to choose and those are check box options.

i  have selected one option from the check box and the panel got refreshed so  i need to scroll down for finding the option is there any way we can avoid panel refresh.

**Version used**
Ex: 4.3

**To Reproduce**
1. add filter web part.
2. select panel layout ,( one of the refinable property having more than 100 options)
3. select one of the option (Check box type).
4. the panel got refreshed on check box selection.

**Expected behavior**
 the panel should not refresh on check box selection.

any suggestions would be great.

**Comment by wobba** [comment]
Not sure what we can do.. seems to work as expected. A click will fire off a new query, so we should rebind and refresh.
