### ISSUE TITLE
Search Box web part text color white in dark background page section

### ISSUE THREAD

**Issue by MakingThingsWorkToronto** [microsoft-search/pnp-modern-search#158]
**Version used**
Ex: 3.11.0

**Describe the bug**
When search box is placed in a section with dark background the text color is rgb(255,255,255)

**To Reproduce**
1. Create a page and add a section with background color dark (tested with gray theme).
2. Add search box to page.
3. Enter text into search box.
4. Note you cannot see text.

**Expected behavior**
The text should be a dark color that contrasts with the white input element.

**Screenshots**
![image](https://user-images.githubusercontent.com/13340007/77975267-97db2000-72c7-11ea-9a1c-4e78e2aee777.png)

First search box is in dark section.  Note the placeholder and any text entered is not readable. Second search box is in light section.  Note the placeholder and text are readable.

**Desktop (please complete the following information):**
 - Browser: Chrome version 80, Windows 10

**Comment by MakingThingsWorkToronto** [comment]
Not an ideal fix but here it is ... SearchBoxWebPart.module.css ... replace .searchTextField class with the following:

    .searchTextField {
        width: 100%;
        flex: 1 1 auto;
        border: none;

        :global(.ms-SearchBox-field) {
            color: #272727;
        }

        :global(.ms-SearchBox-iconContainer) {
            color: #272727;
        }
    }

**Comment by wobba** [comment]
Would rather use theme tokens to ensure this works.

**Comment by MakingThingsWorkToronto** [comment]
Yeah ... Something like this could work:

Light theme:
![image](https://user-images.githubusercontent.com/13340007/79773553-99fd3100-82ff-11ea-9a46-1f19419de5c4.png)

Dark theme:
![image](https://user-images.githubusercontent.com/13340007/79773644-b4370f00-82ff-11ea-8b1a-7dd03a065efa.png)

    .searchBoxWrapper {
        display: flex;
        border: 1px solid '[theme:primaryButtonBackground, default:#0078d7]';

        &:hover {
          border-color: '[theme:primaryButtonBackgroundHovered, default:#0078d7]';
        }
    }

    .searchTextField {
        width: 100%;
        flex: 1 1 auto;
        border: none;

        :global(.ms-SearchBox-field) {
            color: '[theme:primaryButtonBackground, default:#0078d7]';
        }

        :global(.ms-SearchBox-iconContainer) {
            color: '[theme:primaryButtonBackground, default:#0078d7]';
        }
    }

**Comment by wobba** [comment]
Fixed with #205
