### ISSUE TITLE
unable to open .tiff file in browser

### ISSUE THREAD

**Issue by Arwayne** [microsoft-search/pnp-modern-search#1581]
**Version used**
4.4.1.0

**Describe the bug**
when I search for .tiff file and from search results click on the hyperlink under title column it downloads the file. Need your help to know if there is any way to open the tiff files in browser from search results

**To Reproduce**

Simply crawl a library which has modern experience enabled.
Search for tiff files and get the result.
Click on hyperlink under Title column.
it downloads the file 

**Expected behavior**
the .tiff file should open in browser , as it does in out of the box library search result 

**Screenshots**

1![image](https://user-images.githubusercontent.com/95385198/144321951-e69b836e-4ac2-4731-8501-e976e4c7c552.png)

**Desktop (please complete the following information):**
Browser Chrome

**Comment by wobba** [comment]
Ideally the web=1 parameter which is appended by default should resolve this, but it's not. So no easy way unfortunately. I'm working internally with Microsoft to have an easier way to open images into the previewer experience, but no timelines.
