### ISSUE TITLE
Search Verticals Web Part Hover Issue on Dark Section Background

### ISSUE THREAD

**Issue by MakingThingsWorkToronto** [microsoft-search/pnp-modern-search#1584]
**Version used**
Ex: 4.4.1

**Describe the bug**
When the verticals web part is added to a page with a dark section background the hyperlink hover style results in the link being unreadable.  

**To Reproduce**
1. Create a Site Page.
2. Add a section and apply the dark color background.
3. Add the verticals web part with a couple links.
4. Note when you hover over each vertical the text becomes unreadable.

**Expected behavior**
The text color should be readable.

**Screenshots**
![image](https://user-images.githubusercontent.com/13340007/144461439-75ca266e-3f04-4254-a233-0ae937884d7d.png)

**Desktop (please complete the following information):**
 - Windows 10, Chrome, Edge

**Comment by FranckyC** [comment]
Closed. Fixed by https://github.com/microsoft-search/pnp-modern-search/pull/1585
