### ISSUE TITLE
Search Results web part connection not properly set in Chrome, Firefox, Edge Chromium

### ISSUE THREAD

**Issue by MakingThingsWorkToronto** [microsoft-search/pnp-modern-search#159]
**Version used**
3.11.0

**Describe the bug**
The search results web part connection is not properly set when connecting to the Search Box search query in Google Chrome.

**To Reproduce**
1. Add a search box web part to the page and configure to use query string parameter q.
2. Add search results web part to the page and connect to source search box > search query.
3. On the web part side panel click next to navigate to page 2 of 3.
4 (quick). On the web part side panel click back to navigate to page 1 of 3.
5 (quick). The Search query configuration has disappeared (blank).

4 (alternate). click Save as draft & re/publish the page.
5 (alternate). Hard refresh page.
6 (alternate). Edit page and note Search Results Web Part query configuration has disappeared (blank).

**Expected behavior**
The search query configuration should persist when using Google Chrome.

**Desktop (please complete the following information):**
Browser Chrome 80, Windows 10

**Additional context**
The search query configuration does work by design in Microsoft Edge 44.18362

**Comment by wobba** [comment]
Does it work in other browsers?

**Comment by MakingThingsWorkToronto** [comment]
Thanks for the quick reply.  The only browser this works in is Edge as per above.

Does not work in Chromium Edge Beta 81.0.416.41
Does not work in Firefox 74.0.

**Comment by ejudson** [comment]
I have the same issue, SP online, Tuesday evening around 11pm, they just stopped working in chrome, edge and firefox.  Updated the the latest 3.11, still same issue.  We have now fallen back to i.e. 11 as it still works there. Seems to be Site Collection related, as I have other site collections in the same tenant working.  Could be due to throttling?  Trying to debug it now

**Comment by nilsvbconxion** [comment]
Been having the same issue this week.
A colleague of mine had the same behavior, but managed to fix it by reinstalling it.
I however, hasn't been able to fix it, nor by removing the app on the sitecollection, nor by completely removing and reinstalling the app-package in the AppCatalog.

I had previously installed another version of this app on the tenant. Could it have something to do with this?

Google Chrome: version 80.0.3987.163 (Official build) (64-bits)

**Comment by ejudson** [comment]
It went away for me randomly after two days and started working again, this morning none of the connections are working again, looks like this.properties.queryKeywords.tryGetValue() is returning undefined.  Different site collection is working though, so it seams its site collection related

**Comment by MakingThingsWorkToronto** [comment]
Got more time to play around with this today - seems to be happening only for custom templates. Can anyone else validate? 

Add the results web part as above & configure the connection to the search box. Then switch to a custom template and add any html, ex// <p>test</p> to the custom "inline" template.

Save the page then edit, remove the connection and then try to configure the connection again. I'm seeing a dynamic data error:

![image](https://user-images.githubusercontent.com/13340007/79821404-b67b8680-835c-11ea-8830-ea8b659200df.png)

**Comment by wobba** [comment]
I cannot reproduce this, and would help with a screenshot to point out what is missing. The tryGetValue() call can in theory return undefined if the connection is not detected, but unsure of when/how this will happen.

**Comment by MakingThingsWorkToronto** [comment]
@wobba - from what I can see the onPropertyPaneFieldChanged event is not firing. I thought it was a dynamic data issue yesterday but haven't been able to reproduce that today. I can reproduce it by restoring an old version of the page - available to help in any way I can!

**Comment by wobba** [comment]
I either need to be able to repro it, or someone else can repro in debug and propose what the fix should be.

**Comment by MakingThingsWorkToronto** [comment]
I will test it again on a second tenant this afternoon. If I can validate it's an issue with the spfx distribution then we can close this.

**Comment by MakingThingsWorkToronto** [comment]
This seems to have gone away on multiple tenants. Was related to the event not firing & likely part of a bad spfx distribution!

**Comment by wobba** [comment]
I'll close for now, and we can reopen if it surfaces back to investigate further.
