### ISSUE TITLE
Search Result pages doesn`t display proper image. 

### ISSUE THREAD

**Issue by Kostadin-cmd** [microsoft-search/pnp-modern-search#1595]
Hello, 

We have issue with Modern pnp Search Result web part v3.16
We are trying to display new pages from different site. The pages are displayed but the images are not displaying. (Please find the attached screenshot). This problem comes only to one specific site. Week ago it was working properly. It usually takes the header image of the page, but for some reason it stop working. 
Any ideas why is this happening?

**Comment by wobba** [comment]
Closing as incomplete not following issue guidelines and template.
