### ISSUE TITLE
v4: lowest refiner/filter in panel view is hidden by sticky "Apply | Clear" layer

### ISSUE THREAD

**Issue by MarcoSimon** [microsoft-search/pnp-modern-search#1596]
**Version used**
4.4.1.0

**Describe the bug**
When using the filter webpart to display in the panel, the last refiner/filter on the bottom of the panel is hidden by the sticky "Apply | Clear" layer.

**To Reproduce**
To reproduce this display error, just use enough refiners to fill the complete panel from top to bottom or even more. You can scroll down in the panel, but you will not reach the very last refiner/filter.

**Expected behavior**
The filter list in the panel is displayed completely and you can use each filter. E.g. by adding some margin or padding to the .filterPanelContent div or something.

**Screenshots**
![image](https://user-images.githubusercontent.com/6904649/144854372-c8d46d53-0156-4ae3-98b4-c3492fb21772.png)

**Desktop (please complete the following information):**
 This behaviour can be observed in latest versions of Chrome/Edge and Firefox. I didn't test other browsers or versions.

**Comment by wobba** [comment]
@MarcoSimon, how many filter would you need to set up for it to break? From a IA point of view you should not have much more than 7 filters. To assess the importance of addressing this.

**Comment by MarcoSimon** [comment]
@wobba, you need at least as many filters as fit into the panel, no matter how big the panel is (resize the browser). The last one (filter or refiner) will always be hidden as soon as you have to scroll down:

![image](https://user-images.githubusercontent.com/6904649/144989414-73575d13-6c2c-4aa1-b964-378f826e4713.png)
1. Filters needs less space than the panel height
2. Expanding one more refiner results in hiding the last refiner
3. Expanding the last refiner results in hiding the last filter

![image](https://user-images.githubusercontent.com/6904649/144989470-e257d688-13bb-4f5e-b8e1-ee3cd250e00b.png)

**Comment by wobba** [comment]
Fixed in v4 dev branch with #1542 as it now looks like this.

![image](https://user-images.githubusercontent.com/51104/145623171-4e2e3237-1ddb-41a9-925c-7fe446176ef7.png)
