### ISSUE TITLE
v4: Conjunction "AND" is displayed when deleting the last filter via "Clear" link in the filter webpart

### ISSUE THREAD

**Issue by MarcoSimon** [microsoft-search/pnp-modern-search#1597]
**Version used**
4.4.1.0

**Describe the bug**
When filtering by two (or more) filters and then clearing the last filter by clicking the "Clear" link in the filter (no matter if vertical, horizontal or panel), the conjunction "AND" will still kept in the result webpart. If you
* delete the filter by clicking the filter icon beneath in the result webpart,
* delete not the last filter, but the first or one in between,
* delete the filter by deselecting the checkbox and clicking "Apply",
the conjunction disappears as expected.

**To Reproduce**
1. Use a filter webpart, connected with a result webpart.
2. Apply two filters or more (from at least two different refiners).
3. Delete the last filter(s) by clicking "Clear" in the filter webpart.

**Expected behavior**
The last occurence of the conjunction "AND" should disappear.

**Screenshots**
After applying two filters: 
![image](https://user-images.githubusercontent.com/6904649/144859862-acc33fc8-f066-411d-9635-25d1654aa379.png)
After deleting the last one via "Clear":
![image](https://user-images.githubusercontent.com/6904649/144859931-1ba996d7-e785-46e0-b031-d0a77babba3d.png)
After deleting the last one via clear filter icon:
![image](https://user-images.githubusercontent.com/6904649/144870258-0f191968-1666-4ca2-87ca-d85a38c1491c.png)

**Desktop (please complete the following information):**
This behaviour can be observed in latest versions of Chrome/Edge and Firefox. I didn't test other browsers or versions.

**Comment by wobba** [comment]
This has been fixed in later versions.
