### ISSUE TITLE
Tokens with no values return the value of the token instead of nothing

### ISSUE THREAD

**Issue by umaknow-lp** [microsoft-search/pnp-modern-search#1599]
**Version used**
Ex: 4.4.1

**Describe the bug**
Whenever we use a token, for example: {QueryString.[queryStringValue]}, and the value for that QueryString is empty, instead of returning nothing, it returns the token ({QueryString.[queryStringValue]} in the case of this hypothetical example).

**To Reproduce**
1. Create 2 SitePages: one with at least a PnP - Search Vertical webpart and another one that will stay empty.
2. In the setting of the Search vertical, press the configure vertical button and add a vertical pointing to the same page. Activate the hyperlink checkbox and add a link URL to the empty page. At the end of the link URL, add "?search={QueryString.search}". All the other values of that vertical are not important for this issue, but cannot be left empty.
3. Add "?search=" at the end of the current page URL.

**Expected behavior**
When pressing on the vertical, the "?search=" part of the URL of the newly opened page should still be "?search=", but instead is "?search={QueryString.search}"

**Desktop:**
 - Tested on Chrome, Firefox and edge

**Additional context**
This bug is not present on version 4.3.0

**Comment by wobba** [comment]
Try: `{?QueryString.[queryStringValue]}`

And we should document this - it's the same behavior as in SharePoint API.

**Comment by umaknow-lp** [comment]
Thanks, using the token in the format you provided fixed my problem.
