### ISSUE TITLE
Person Field Refiner

### ISSUE THREAD

**Issue by gristy58** [microsoft-search/pnp-modern-search#16]
Currently person fields in refiners are returned as claims username, is there a way to get it to display the display name, or would this require an enhancement?

**Comment by FranckyC** [comment]
Hi @gristy58 What managed properties are you using for refiners?

**Comment by gristy58** [comment]
I mapped People:Manager to RefinableString

**Comment by FranckyC** [comment]
Can you add this RefinableString to the list of selected properties in the search results and use the debug view? You should see the raw value coming from the search index.

In the refiner WP, value are displayed as is (except for dates). If the raw value doesn't fit your needs, maybe you can try to map an other crawled property.

**Comment by gristy58** [comment]
yeah can you please process claims usernames and display display name? as there is no other way i can figure out to display the name properly.

**Comment by FranckyC** [comment]
I will see what I can do but I'm very busy until the end of the year so this won't be soon :( Maybe @wobba  @YannickRe can help if you have some time?

**Comment by FranckyC** [comment]
Hi @gristy58 . This should be resolved by PR #37. Let me know if it works for you.

**Comment by FranckyC** [comment]
Resolved by #59.
