### ISSUE TITLE
react & react-dom not found when testing debug build (404)

### ISSUE THREAD

**Issue by MakingThingsWorkToronto** [microsoft-search/pnp-modern-search#160]
**Version used**
3.11.0

**Describe the bug**
react and react-dom distributions not found on local host when running debug build on SharePoint Online.

**To Reproduce**
1. Clone repo on local machine and install dependencies using npm install
2. gulp bundle
3. gulp package-solution
4. gulp serve
4. upload sppkg to app catalog
5. add app to site collection.
6. add search results web part to page and configure query as *
7. save and publish page.
8. hard refresh.
9. console reports 404 error loading react and react-dom

**Expected behavior**
react and react-dom should return with status 200

**Screenshots**
![image](https://user-images.githubusercontent.com/13340007/77981991-3de35600-72d9-11ea-8790-22a3bce93118.png)

**Desktop (please complete the following information):**
Chrome 80, Windows 10

**Additional context**
Believe this is a packaging issue with react and react-dom.  Please try running gulp clean and rebundle to test.

**Comment by wobba** [comment]
If you want to debug and serve locally I suggest you either use the hosted workbench `_layouts/15/workbench.aspx` or append `?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js` to the page you want to test in. Much quicker and easier than packaging up and deploying a debug build.

**Comment by FranckyC** [comment]
Hi @MakingThingsWorkToronto , does this work using the hosted workbench page?

**Comment by MakingThingsWorkToronto** [comment]
@wobba - thanks for the tip!  Unfortunately same error when debugging directly on the page with query string AND web part is no longer functional in edit mode:
![image](https://user-images.githubusercontent.com/13340007/78060924-63fd0a80-735a-11ea-849b-068c86cc6698.png)

@FranckyC - The web part is functional in the hosted workbench however still see the error:
![image](https://user-images.githubusercontent.com/13340007/78060471-90fced80-7359-11ea-9514-5f8b257777b1.png)

Thanks for the help all!

**Comment by pravinn080317** [comment]
@wobba @FranckyC 

Even i faced the same issue. 

**Steps to reproduce the behavior:**

- Clone repo on local machine and install dependencies using npm install
- gulp bundle
- gulp package-solution
- gulp serve
- upload sppkg to app catalog
- add app to site collection.
- add search results web part to page and configure query as *
- save and publish page.
- hard refresh.

console reports 404 error loading react and react-dom and 
https://localhost:8080/dist/my-company-library-library.js

**Comment by pravinn080317** [comment]
Search Webpart is Functional. But its taking about about 2 minutes to load search box & search results webpart in the page because of this errors.
Most of the errors are "**net::ERR_CONNECTION_CLOSED**"  inside this dist

**Comment by FranckyC** [comment]
Unfortunately, I'm not able to reproduce this error. Did you run `gulp clean` before packaging? Also what is your node.js version?

**Comment by MakingThingsWorkToronto** [comment]
Ran node clean.  Above instructions use fresh clone so clean should not be necessary.

On node v10.18.0

What happens if you delete your node_modules folder and run a fresh npm install?

The issue I'm seeing is the **dist** folder isn't included in react/react-dom 16.8.5 within node_modules.

**Comment by MakingThingsWorkToronto** [comment]
This can be closed provided the documentation is updated on how to debug locally according to @wobba first suggestion.

**Comment by wobba** [comment]
That said, I had it working fine in local workbench today, so unsure what causes the issue. And I won't update docs for this. Any sane SPFX dev know to use the SPO hosted workbench 😉

**Comment by MakingThingsWorkToronto** [comment]
To be fair, it is unusual that a debug build doesn't run on a modern page. The hosted workbench doesn't help much in debugging on the page hence the suggestion.

**Comment by wobba** [comment]
Why doesn't the hosted workbench work? And might add a link to an article explaining manifest load on a page. The only thing not working on hosted workbench is page context variables, and connection to nav bar search box. Curious to learn more about the scenario.

**Comment by MakingThingsWorkToronto** [comment]
Yeah - a link to the manifest load is what I was referring to adding to the docs.

When there are errors with the web parts on the page we should be able to debug/understand root cause. As you said the workbench isn't apples to apples - nice starting point but not the target runtime environment.

**Comment by wobba** [comment]
@MakingThingsWorkToronto added to the getting started docs now with https://github.com/microsoft-search/pnp-modern-search/commit/9b3a458490312cd9eae964b6e80cba3b0873baba
