### ISSUE TITLE
Add an option to have an inclusive date range filter

### ISSUE THREAD

**Issue by umaknow-lp** [microsoft-search/pnp-modern-search#1601]
**Is your feature request related to a problem? Please describe.**
When having a Date Range filter, the refiner will return "<=" for the "from" portion of the Date Range, but will only return ">" for the "To" portion of the date range, which cause problems if you want the results to have the dates set in the Date Range to appear in the Search Results.

**Describe the solution you'd like**
Give an option for the Date Range filter in the filer panel option so the refiner can return "<=" instead of forcing "<" (maybe give the same option for the "From" portion too).

**Additional context**
Picture to better show the problem
![image](https://user-images.githubusercontent.com/60614648/144935988-74b880d7-adf3-407c-90c5-1cf2d1a08265.png)

**Comment by wobba** [comment]
This is more of a bug report than a feature request. I think we should just change to have => and <= for both dates.

**Comment by wobba** [comment]
Fixed in the next release. Made the filter include both start and end dates.
