### ISSUE TITLE
Filter pane pastes query string into search box

### ISSUE THREAD

**Issue by Bunghoolio** [microsoft-search/pnp-modern-search#1602]
**Version used**
Ex: 4.4.1.0

**Describe the bug**
I have set up a search environment, using a search box, a result pane and a filter pane (and a verticals application, but this does not matter right now). When I start searching something, I get my results in the results pane back as expected. When I try to use the filter pane for any criteria, a query string will be added to the search box and no result will be shown/retrieved. I can now remove the recently added query string from the search box which was added by the filter. Now I see the results filtered as expected. Please see the mp4 screen recording for more details. 

**To Reproduce**
1. PnP search environment using search box, results pane and filter pane.
2. search anything
3. using a filter to refine the filter results
4. At this step the unexpected behavior occurs. A query string will be added to the search box. No search result will be shown anymore. 

**Expected behavior**
I want the results to be filtered based on the selected filter. 

**Screenshots**
![image](https://user-images.githubusercontent.com/56604124/144979663-654c536e-2ef1-49db-bab5-f5c05b0396a9.png)

**Desktop (please complete the following information):**
 - System: Windows 10 Enterprise 2020H2
 - Browser: Microsoft Edge (96.0.1054.43), Google Chrome (96.0.4664.93)

**Additional context**
A screen recording of this issue can be found here. 
https://user-images.githubusercontent.com/56604124/144980377-4c801fac-64fd-4d64-9c73-07dad510e5b9.mp4

**Comment by wobba** [comment]
Can you expand on the web part setup? Web part connection setup etc. Properties of the parts, which filter you used etc.

**Comment by Bunghoolio** [comment]
> Can you expand on the web part setup? Web part connection setup etc. Properties of the parts, which filter you used etc.

Sure - please find below.
Please let me know, if I can support with further details. 

# Search Box:
![image](https://user-images.githubusercontent.com/56604124/145014932-2250f54d-76ba-443c-889d-77d5afae18a7.png)
![image](https://user-images.githubusercontent.com/56604124/145014948-0b5e16a9-ee93-49b7-b39b-6b6228bd7e84.png)
![image](https://user-images.githubusercontent.com/56604124/145014968-da27974c-86ee-43fc-9ac8-d4f3fcd0f9a6.png)

# Search Results:
![image](https://user-images.githubusercontent.com/56604124/145015051-179b9849-7db3-4b85-bc2e-feaf4514780f.png)
![image](https://user-images.githubusercontent.com/56604124/145015072-9137da18-17d1-4c8b-9d7c-36bd7ce20dc3.png)
![image](https://user-images.githubusercontent.com/56604124/145015148-a1215532-02b6-4920-9af2-60514fb78ad1.png)

# Search Filters:
![image](https://user-images.githubusercontent.com/56604124/145015218-555bb878-eb77-4f4e-a52b-f94c2bb91cf2.png)
![image](https://user-images.githubusercontent.com/56604124/145015230-9af2cd9e-b562-4ba7-b219-987df9f1a0f7.png)
![image](https://user-images.githubusercontent.com/56604124/145015246-a595c255-918c-4321-802d-ba80e4766151.png)

**Comment by Bunghoolio** [comment]
Hi @wobba, I've seen that there had been a new release for V4. Shall I update the version and test if the issue still occurs or do you need me to stick to this version for repro-purposes?

**Comment by wobba** [comment]
If you can re-test on v4.5 that would be helpful.

**Comment by Bunghoolio** [comment]
Hi @wobba 
The new version fixes my issue. The filter is now working properly. Therefore, I consider this issue as resolved!
Thank you for your support on this great application!
