### ISSUE TITLE
v4: Custom filters (refiners) won't work in panel view, just combined with default refiners (e.g. "file type")

### ISSUE THREAD

**Issue by MarcoSimon** [microsoft-search/pnp-modern-search#1606]
**Version used**
Ex: 4.4.1.0

**Describe the bug**
I have many custom refiners (RefinableString20 - RefinableString45, 5-50 options each) to filter by. But when click on one option, the result page will flicker and nothing else happens. Neither the "Apply" nor the "Clear" link will be clickable. You can select as many options as you want to, but you can't apply them. There is no script error thrown. And sometimes when selecting or de-selecting a (custom refiner) filter, the filter panel suddenly closes whithout any error, too.

When adding another default filter like "File type" (and e.g. filter by ".png"), the other filters have been also considered. But when clicking "Clear", only the "file type" filter will be disabled. The others are still enabled and take effect on the results. And again, de-selecting the filter won't enable the "Apply" or "Clear" links in the panel.

The behaviour is still the same when I use only one RefinableString in the filter webpart. Using the horizontal or vertical view works as expected.

**To Reproduce**
1. Define at least one refiner, mapped to a managed property
2. Use a filter webpart, connected with a result webpart, use "panel" view
3. Filter by one option of the custom refiner
4. You can't apply the custom filter
5. Add a default refiner, such as "file type"
6. You can filter by file type and custom filter, but not only by custom filter
7. Clearing the filters will only clear the default filters
8. Using another view (horizontal/vertical), the all filters are working as expected

**Expected behavior**
Expected behaviour would be that you can filter by custom filters also in the panel, not only in horizontal or vertical view.

**Desktop:**
The behaviour can be observed in latest versions of Chrome/Edge and Firefox; I didn't tested it in other or older browsers.

**Additional context**
Please let me know if you need more or more precise information, such as debug outputs, request logs, configuration details, specific screenshots, etc.

**Comment by MarcoSimon** [comment]
In addition: I found a similar (but already closed) bug, it should be solved with v4.4.0: https://github.com/microsoft-search/pnp-modern-search/issues/1419. But I still run into the error with v4.4.1, as I described before.

**Comment by wobba** [comment]
Re-log if still an issue with latest version.
