### ISSUE TITLE
OneDrive results not appearing in Search Results

### ISSUE THREAD

**Issue by Naveen-Rangarajan** [microsoft-search/pnp-modern-search#1607]
__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
Ex: 3.22.0

**Describe the bug**
OneDrive results are not appearing in the search results after all the configurations are made and explained below.
1) Enabled "Include personal OneDrive results" from web part properties 
2) Added path in the KQL - path:"https://tenant.sharepoint.com" OR path:"https://tenant-my.sharepoint.com"

Still results are not visible. Please check below screen shots for references. No errors in console as well.

**Screenshots**
1) OneDrive Enabled
![image](https://user-images.githubusercontent.com/61411651/145037302-6a8091df-972a-45ee-8cfc-2f82efa0afdf.png)

2) OneDrive Files
![image](https://user-images.githubusercontent.com/61411651/145038126-4dba28c5-7883-40a8-8129-4c8e3b4afe4b.png)

3) KQL is retrieving the data
![image](https://user-images.githubusercontent.com/61411651/145038636-449e4121-c4cf-4a9f-8502-19e390d5061a.png)

4) Code in place for Toggle
![image](https://user-images.githubusercontent.com/61411651/145039403-89c2b1cc-1876-45f5-b977-c3a0cab44abf.png)

5) searchResultResponse from Console (OneDrive items empty)
![image](https://user-images.githubusercontent.com/61411651/145040056-4bcbe464-8397-437d-818a-667b0f6c2b84.png)

6) One Drive items not displaying
![image](https://user-images.githubusercontent.com/61411651/145039257-2f5a104c-bef3-437f-b845-5290b313035d.png)

7) Excluding OneDrive items, Search on other documents not stored in OneDrive is yielding results
![image](https://user-images.githubusercontent.com/61411651/145041219-4ec1c418-e567-4a00-a2e3-e4254f906178.png)
  

**Desktop (please complete the following information):**
 - Browser [Chrome]

Please do let me know if additional configurations are needed that I might have missed.

**Comment by wobba** [comment]
The toggle should have no effect as it was a stop gap in the API. I'll see if I remove it in a later version. Or are you not getting ODB results regardless of how the setting is?

**Comment by Naveen-Rangarajan** [comment]
@wobba , Irrespective of the toggle settings, the ODB results are not retrieved.

**Comment by wobba** [comment]
For me it fails if I have the toggle on, but works fine if it's off. I'll remove it for the next version.

**Comment by Naveen-Rangarajan** [comment]
Hi @wobba 

Are there any other changes to look out for apart from removing the toggle for ODB?

**Comment by wobba** [comment]
And ODB results should come in the PrimaryQueryResult. Not sure what to look out for as it's working in my two test tenants I use.

**Comment by Naveen-Rangarajan** [comment]
@wobba 

I have updated the code by removing all references related to ODB. Its working in my Dev Tenant. But, its not working in Client's Test and PROD tenants.

 As mentioned earlier, from KQL, ODB results are retrieved in all Tenants - Dev, Test and PROD. 
 
 Also, the default search link provided by MS as below - 
  https://MyDomain.sharepoint.com/sites/MySiteName/_layouts/15/search.aspx?q=SearchQueryText
 
is also able to retrieve OneDrive items in Test and Prod tenants.

![image](https://user-images.githubusercontent.com/61411651/145534003-b84dd43c-d3b5-465a-b3eb-8cffe434406a.png)

Any reasons why this behavior? Kindly update if you find anything.

**Comment by Laetterman** [comment]
> For me it fails if I have the toggle on, but works fine if it's off. I'll remove it for the next version.

Hi @wobba 
why completely remove? In my case we do not want to have the personal OneDrive items... :-)
As you mentioned: the toggle seem to work the oposite way: off --> you have reults from OD, turned on you do not have Results. Maybe below it is a failure on the api/code, but from the 'UI switch side' it functions that 'oposite' way... :-)

**Comment by wobba** [comment]
@Laetterman because the current option was an intermediate API option introduced at one time which is no longer needed. If you want one or the other you can use a path filter - as was the solution before this API option was added. I'll do a PR and change the official docs to remove the parameter https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview#contentsetting

**Comment by wobba** [comment]
I cannot repro this and seems to be an API issue if you cannot use a path filter to show odb or sp docs. Will close for now.

**Comment by Naveen-Rangarajan** [comment]
@wobba 

Since ODB results are showing up in KQL which makes use of path filter, is it possible to find where exactly it is breaking w.r.t API.

And is it possible if some settings exists in Admin center or Azure portal or elsewhere where the results are blocked for OneDrive.

**Comment by wobba** [comment]
If the two queries below return as expected, then all is ok. If they don't return as expected you have an API issue at hand - assuming there are not result source modifiers etc which interfere with the queries.

* `path:https://tenant-my.sharepoint.com/` return ODB
* `path:https://tenant.sharepoint.com/` return SP

**Comment by Naveen-Rangarajan** [comment]
@wobba ,

I (and end users) can access both the links. Still the results are not retrieved.

OneDrive URL
![image](https://user-images.githubusercontent.com/61411651/145969811-6bf4eae2-15ae-4e4e-9daa-55c34919035a.png)

Tenant URL (Cannot share more coz of confidentiality !!)
![image](https://user-images.githubusercontent.com/61411651/145970178-f0927fbb-71ad-424c-b22f-07550794559d.png)

Result source modifier is a simple Search Terms
![image](https://user-images.githubusercontent.com/61411651/145970793-ad9eeac1-712b-4f34-b7c8-bed512934161.png)

**Comment by wobba** [comment]
Look at the queryModification response if you use the debug display template. That tells you what KQL was executed.

**Comment by Naveen-Rangarajan** [comment]
@wobba 

I just directly use the simple-list.html for the display template. Are you referring to the same? Else, can you please update on where to look for queryModification response. 

Should I debug the page using this query --> loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js

**Comment by Naveen-Rangarajan** [comment]
@wobba ,

Any updates on the above query ?

**Comment by wobba** [comment]
![image](https://user-images.githubusercontent.com/51104/146735660-950ff3ff-bb69-4c78-bc01-e05338210a08.png)

No need to debug the web part itself. That said, this seems to be more of an API/config issue than a web part issue. If you need troubleshooting help start a discussion in the Discussion area.
