### ISSUE TITLE
Feature request : split render templates into multiples templates

### ISSUE THREAD

**Issue by stevebeauge** [microsoft-search/pnp-modern-search#161]
**Is your feature request related to a problem? Please describe.**

Classic search components use multiple templates for rendering (Display templates). The separation allowed us to concentrate on single result item templating, which covers majority of use case (showing additionnal metadata, ...).

The modern search components are using a single handlebars template for the whole rendering. That means every update of the OOB templates should be reported to all customisation.

For exemple, the 3.11 version introduced the pagination component that should be applied to all custom templates to preserve the pagination behavior.

**Describe the solution you'd like**
I think it would be cool to split the rendering into multiple templates.
Maybe :
* a `control `template, which my be considered as the main template. Its purpose is to generated the global structure of the webpart.
* a `header` template which renders the top of the component (result count, ...)
* an `items` template, which manage the items outer structure, and an interator for the items, the query rules logic, ...
* collection of `item` templates
* a `footer` template to render additionnal informations
* a `pagination` template to render the pagination

if this feature is implemented, the immediate benefits is that the future releases are less likely to cause maintenance requirements. As most of the customizations are `item` customization, any changes to the webpart fonctionnality, applied to the other templates, won't require any maintenance to current uses of the webpart.

**Describe alternatives you've considered**

**Additional context**

**Comment by FranckyC** [comment]
Good suggestion. For the item, you can already use the result types feature with/without external templates. For pagination, this would goes to a `footer` section, not a dedicated one.

**Comment by MakingThingsWorkToronto** [comment]
The search navigation web part reduced the complexity required within each search page. Additionally as search verticals were not working perfectly in previous releases many clients used search navigation. They were also useful to add direct links into specific vertical searches. Any chance we can have the search navigation web part restored in this release and deprecated over time? Although I love the idea of more work, am concerned some clients may see this breaking change as happening to fast & refactoring required is too significant to move forward with these modern search webparts.

**Comment by wobba** [comment]
This can be achieved using web components in v4. Will close this.
