### ISSUE TITLE
(Mapped) Crawled property/column of a list not displaying results in Results Web part

### ISSUE THREAD

**Issue by jftrim** [microsoft-search/pnp-modern-search#1613]
I have a column in a list called "Contact", which I've mapped to managed property called "ContactDetails".  Searching within Sharepoint Query Tool, shows the value being returned, but when it's added to the results, it is blank??

Have I done something wrong?

![image](https://user-images.githubusercontent.com/95770749/145370852-71e1f38b-e833-429d-ab33-0c38696d0944.png)

**Comment by FranckyC** [comment]
Hi @jftrim, what if you switch to the 'Debug' layout. Can you see a value here? Also, make sure you are using the same settings as Search Query Tool (result source, query template ,etc.).

**Comment by jftrim** [comment]
When I run in Debug, it does not return ANY of the columns from the List, including the one I've mapped to a Managed Property.

Not sure if I'm using the same settings - I've just used the defaults.  I pointed the SQT at the specific web site.  
This is the  query URL  https://xxx.sharepoint.com/sites/KnowHowandTraining/_api/search/query?querytext='martin+pointer+Path%3ahttps%3a%2f%2fxxx.sharepoint.com%2fsites%2fKnowhowandTraining%2fLists%2fBlack%2520Book'

On the Results web-part, I've specified it to use the path of the list I want to search in the Query Template:

{searchTerms}
Path:https://xxx.sharepoint.com/sites/KnowhowandTraining/Lists/Black%20Book

I think they're both the same??

**Comment by jftrim** [comment]
Just to be clear.  When I search on SSQT, and select "Primary Results" it shows the same as Debug.  It's when I click on "Managed Properties" at the bottom of the the result that I see the meta-data I am looking for

**Comment by jftrim** [comment]
Okay - I've worked out what was wrong - I didn't select the Managed Property in the "Selected Properties" section.  It works now
