### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by PeterVos111** [microsoft-search/pnp-modern-search#162]
When i open a search result file, it opens in the same tab. When i press previous, my search query and refiners revert to default

**Describe the solution you'd like**
Open Files in a new tab so i don't lose my search results when opening a file

**Describe alternatives you've considered**
Tell users to press the 'CTRL' button when selecting the file, or using the right mousebutton and selecting 'open in  new tab'. 

This is not ideal, since a lot of users have minimal knowledge of PC's and SharePoint

**Comment by FranckyC** [comment]
Hi @PeterVos111 , which layout are you using (simple list, cards, etc) and what version of the solution?

**Comment by PeterVos111** [comment]
Hi @FranckyC ,

I'm in Version 3.11, and am mostly using 'detail cards'.

**Comment by wobba** [comment]
OOB search always open in a new tab. If we changed to this for the OOB templates I think that would be ok. Could also have a setting, but more settings is not necessarily good either.

**Comment by PeterVos111** [comment]
It would be a great change to let it open in a new tab OOB, Though i have no clue if there are users beside my company who would like it to open in the same tab.

**Comment by FranckyC** [comment]
Hi @PeterVos111. The 'Cards' layout uses a `target='_blank'` so it would open in a new tab every time. Can you confirm you ues the default layout and not a custom one?

**Comment by wobba** [comment]
I have a fix for latest dev branch which fails on open in new tab (due to sanitization). I'll verify layouts with target attribute before my PR.

**Comment by wobba** [comment]
My PR #208 should align open in new tab per item as well as have a good open link for pretty much any item.
