### ISSUE TITLE
PnP Search Refiner - Date Calendar overlapping numbers with Text on Mobile View

### ISSUE THREAD

**Issue by shariq1379** [microsoft-search/pnp-modern-search#1620]
**Version used**
Ex: 4.2.3

**Describe the bug**
date picker calendar overlapping numbers with text for some months on Mobile view. It's working fine on browsers. Please see the screenshots which I attached.

**To Reproduce**
1. Open the search page
2. Click on debugger and switch to Mobile view.
3. Click on the PnP Date Calendar and up/down arrows to change the month
4. Month numbers are overlapping with text for some months(Ex - January 2021)

**Expected behavior**
Numbers should not overlapping with text...

**Screenshots**
I have added 3 screenshots

**Desktop (please complete the following information):**
 MS Edge & Chrome

![image](https://user-images.githubusercontent.com/77804584/145646011-f18c1064-97ff-479d-88ac-71c18e9edb7a.png)

![image](https://user-images.githubusercontent.com/77804584/145646026-e6219552-17bc-4fb9-94f3-cd5bb4000e2d.png)

![image](https://user-images.githubusercontent.com/77804584/145646037-6a1697af-2229-419a-9d30-a53a07afdafc.png)

**Comment by wobba** [comment]
As this is a reusable control from office-ui-fabric-react we cannot easily fix this styling. Hopefully it will be resolved in some newer version of uifabric.
