### ISSUE TITLE
Custom Template Paging Style issue ( Style cleared after paging event)

### ISSUE THREAD

**Issue by edarroudi** [microsoft-search/pnp-modern-search#1623]
**Version used**
4.5.3

**Describe the bug**
Custom styles inserted in an custom template are not rendered after a paging event.

**To Reproduce**
1. Add SearchBoxResult Webpart
2. Select SharePoint Provider
3. Select ResultSource LocalPeopleResults
3. Select People Template
4. edit result template 
5. add custom style .ms-Persona-tertiaryText
        {
            font-weight:600;
        }

![image](https://user-images.githubusercontent.com/935493/145799574-583375fd-e393-4583-ac08-4944701fb0c9.png)
6. Save template
7. Save page
8. Page the site

**Expected behavior**
Style tag shouldn't be empty

**Screenshots**
![image](https://user-images.githubusercontent.com/935493/145800296-2b6e147e-b74b-4085-bf92-b1467bab7de1.png)
![image](https://user-images.githubusercontent.com/935493/145800809-518752d9-32f8-4d2e-aac9-7bc720796eaa.png)

**Desktop (please complete the following information):**
 - Browser edge, chrome

**Additional context**
Also: it seems to not be a problem of paging, but also if you do a second query. Like search something and it the style is filled / rendered correctly. Then without a page refresh, search for something else => style is not rendered

**Update**: 
Yes, only happens in People template.
Additionally: if you have a results webpart with people template on a page and customized other results webparts, the people template will break the other templates as well.

**Comment by edarroudi** [comment]
I added a PR with a "Fix" for it https://github.com/microsoft-search/pnp-modern-search/pull/1730
Funny stuff.

**Comment by FranckyC** [comment]
Fixed with #1730
