### ISSUE TITLE
Incorrect taxonomy term label values in filter web part

### ISSUE THREAD

**Issue by jcoolsen** [microsoft-search/pnp-modern-search#163]
**Version used**
March 2020

**Describe the bug**
After updating to the March 2020 release (from February 2020) and reconnecting web parts as necessary, my taxonomy term id filter values are not all translated to their label any longer. It worked fine before.

**To Reproduce**
1. Set up a refinable string managed search property to point to the "ows_taxid_***" crawled property in existing content.
2. Reindex the list/library.
3. Configure a filter pointing to this refinable string mangaged search property.
4. Notice how some values are ok (Agency, ISO) while others are not (GTSet|#d434c..., GP0|#dd3b...)

**Expected behavior**
The values of the terms should be presented by their labels only.

**Screenshots**
![image](https://user-images.githubusercontent.com/28727502/78030719-d245cb00-7362-11ea-9e18-f0992fec72ac.png)
![image](https://user-images.githubusercontent.com/28727502/78030687-c528dc00-7362-11ea-81d8-29b101571dc5.png)
![image](https://user-images.githubusercontent.com/28727502/78030893-16d16680-7363-11ea-8501-2b9dc882330a.png)
![image](https://user-images.githubusercontent.com/28727502/78030502-7da25000-7362-11ea-8fa5-d12053d6d9ef.png)

**Desktop (please complete the following information):**
 - Chrome

**Additional context**

**Comment by FranckyC** [comment]
Hi @jcoolsen , can you debug the REST call in the browser and inspect the search JSON response especially the `RefinementResults` property? It is weird because the code looks for the `L0|#...` pattern to translate a term.

![image](https://user-images.githubusercontent.com/5659122/78034452-c263c200-7335-11ea-8a8f-f310e089d16f.png)

**Comment by FranckyC** [comment]
Ok nevermind I think I got it. I have a fix in this branch https://github.com/microsoft-search/pnp-modern-search/tree/hotfix/163, could you just clone this, package and tell me if the issue is resolved?

**Comment by jcoolsen** [comment]
Thank you, @FranckyC . I'll try and test, but it'll take me a few days.

**Comment by jcoolsen** [comment]
@FranckyC , that went faster than expected. I have verified that the fix works. Thank you.

Looking at the code, I do worry that two separate terms with same label would be presented as one item, however. But I guess that would be a separate issue...

**Comment by FranckyC** [comment]
Hi @jcoolsen . Glad to hear that I will be a new package. About your concern, this shouldn't be the case because the ID are different.
