### ISSUE TITLE
Search Verticals - Import / Export settings missing

### ISSUE THREAD

**Issue by till-llit** [microsoft-search/pnp-modern-search#1634]
**Version used**
4.5

**Describe the bug**
Search Verticals Webpart is missing the Import / Export settings 

**To Reproduce**
Add Verticals Webpart to page. Open Webpart Properties. Goto page 2.

**Expected behavior**
Export / Import settings like in 4.4.1 and before.

**Screenshots**
![image](https://user-images.githubusercontent.com/91128746/145958984-595853ee-b0aa-435a-8a91-3d7c96818664.png)

**Desktop (please complete the following information):**
Edge 95

**Additional context**

**Comment by FranckyC** [comment]
Resolved by 4.5.1 version.
