### ISSUE TITLE
Custom templating based on selected vertical.

### ISSUE THREAD

**Issue by Georg-Trixl** [microsoft-search/pnp-modern-search#164]
I am trying to write a custom all in one template. 
A single template uses the different formats like 'pnp-persona-card', 'pnp-document-card', 'pnp-details-list' or custom style.
Those formats are switched by a selected vertical.

Create a handlebars helper getSelectedVertical

The alternative would be refactoring the "Results layout" of the web part configuration.
Provide per vertical a "Results layout" configuration. (similar to Result Types)

**Comment by wobba** [comment]
You can use the result type features:
![image](https://user-images.githubusercontent.com/51104/78106753-598f4f00-73f4-11ea-82dd-c880a863e067.png)

Ensure each vertical is scoped to items matching the expressions you use here.
