### ISSUE TITLE
PnP Search Result WP - Modern SharePoint OOB Search box stop working

### ISSUE THREAD

**Issue by shariq1379** [microsoft-search/pnp-modern-search#1642]
**Version used**
Ex: 4.2.3

**Describe the bug**
We created custom SharePoint Search page using PnP search result page and mapped page URL with SharePoint OOB search box(from Search Setting option). 
**Scenario**
When we search text from OOB search box (from home page). It redirected to custom search page which is expected, but when click on back button and hit again on search box then search box stop working. Search box do not redirect to the custom search page.
In addition to this, search box redirection works without any issue if remove PnP search web part from the custom search page.

**To Reproduce**
1. Create new custom page and add PnP search web parts(PnP search box, PnP search results, PnP search refiner)
2. Go to site settings -> Search Settings -> change/add the custom page URL 
3. Go to home page
4. Type "test" on SharePoint OOB search box and hit search link or enter.
5. Result (first time) - Redirected to custom search page
6. Click on back button (search box back button) from custom page
7. Change search test "xyz" and hit search again
8. Issue - search box do not redirect to anywhere...   

**Expected behavior**
SharePoint OOB search box should be redirected to custom search page always when hit the search .

**Screenshots**
![image](https://user-images.githubusercontent.com/77804584/146096929-7efa1a98-0efc-4c38-96cf-dff4fb9657ec.png)

**Desktop (please complete the following information):**
 - Edge & chrome

**Comment by till-llit** [comment]
might be related to #1483 - can you confirm you see the dynamic data provider exception in the console?

**Comment by wobba** [comment]
We don't support v4.2.3 any more. Try the latest v4.5.

**Comment by shariq1379** [comment]
We tried with version v4.4 and it's not working.  Yes, It's look like same issue #1483.

**Comment by wobba** [comment]
Should be fixed in the latest release, v4.5.1. Re-open if you have repro.
