### ISSUE TITLE
PnP Search webparts are not in responsive design on large screens resolution

### ISSUE THREAD

**Issue by in8sanjc** [microsoft-search/pnp-modern-search#1655]
**PnP Search WebParts** 

PnP Search webparts are not in responsive design on large screens resolution

**Expected behavior**

These PnP Search webparts should be responsive design on large screens, and there should not be blank space on large screen resolution

**Actual behavior**
There are lot of blank space in right side of page in the large screen with PnP Search Webparts

**Steps to reproduce behavior**
 
![Issue](https://user-images.githubusercontent.com/61194822/146534587-50b58cab-84e5-4088-a182-d83c178c0a37.JPG)

**What is the version of the PnP Web parts**
SPFx package version: 3.13

**Comment by wobba** [comment]
This is a limitation of the one column layout in modern pages, not web part related. The web part will use whatever space is available in the section it's added.
