### ISSUE TITLE
Filters and Results Do Not Render When Doing a WildCard Search 4.5.2

### ISSUE THREAD

**Issue by adamsdatconed** [microsoft-search/pnp-modern-search#1656]
**Version used**
4.5.2

**Describe the bug**
After connecting the search results webpart to the search filters webpart 0 results are returned.  If I do a specific query such as SPContentType="Conntent Type Name" then results are returned and the filters render correctly.  A wildcard search e.g. * returns 0 results and does not populate the filter values.  I am using the page environment-> search-> search query. Could this be an issue with the volume of data?  Currently there are 486k items in the search index for this tenant.  This did work correctly in my test tenant that only had 4k items in it.

**To Reproduce**
1. Connect the filters webpart to the results webpart
    1.1 Use the following properties as a refiners / values (FileType, Author, LastModifiedTime)
2. Run a wildcard search from the global search bar

**Expected behavior**
The expected behavior is to show the total number of items matching the search term(s) above the returned search results and for the filters / refiners to populate with the options that correspond to those results.

**Screenshots**
//Wild Card Search
![FilterIssueWildCard](https://user-images.githubusercontent.com/88151146/146579811-38d84926-26c0-4eed-a29e-b7a019cd199a.jpg)

//Specific Search
![FilterIssuesSpecificSearch](https://user-images.githubusercontent.com/88151146/146580429-2c1ce7b6-123b-4a35-8552-e67edc7068a0.jpg)

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**
Thank you for any help or guidance!
The test tenant does not have mcas activated and is working correctly
The production tenant where this issues is happening does have mcas / Microsoft Defender enabled and is not working correctly
Receiving a 500 error for GetClientSideComponents "The HTTP method 'GET' cannot be used to access the resource 'GetClientSideComponents'. The operation type of the resource is specified as 'Default'. Please use correct HTTP method to invoke the resource"
//api call failing
tenant/sites/siteName/_api/web/GetClientSideComponents?McasCtx=2&McasUserAuth=casBF3NoYXJlZC1uaXB0dWNrLTIwMjAwODA5rml7CS8gsnjlfZcI4ja9T_fLCLeBWS-Ay__4TSZ5-cYyxu7bLM_UYwF3C80maY8QjUmd_9Q_wh51EY6P45U53ahmzwzGAFVOGM1TwKW56QYf6yK31yxZGQsOzWYyT6xFcMQMnA2i33iji619XiGBELKBDy3fO16VmqNZpwV59nJqW1VO59zQq9ehfhasRuc6Mp3-C_O4nJqj40eS0Pwi_D8qyNhoTuRym5XLyD-FdXxQpkDuSp9XzmfBYMHYJny-X4iMkhftlWJyNWhryiWVYhsd68Ht0VLKZycxgwa03Atu5UwpAH7SuBrCUWF2HVbL

//Search Results Settings
```
{
	"documentationLink": "https://microsoft-search.github.io/pnp-modern-search/",
	"selectedLayoutKey": "SimpleList",
	"resultTypes": [],
	"dataSourceProperties": {
		"queryTemplate": "{searchTerms}",
		"enableQueryRules": true,
		"enableLocalization": false,
		"refinementFilters": "",
		"selectedProperties": [
			"Title",
			"Path",
			"DefaultEncodingURL",
			"FileType",
			"HitHighlightedSummary",
			"AuthorOWSUSER",
			"owstaxidmetadataalltagsinfo",
			"Created",
			"UniqueID",
			"NormSiteID",
			"NormWebID",
			"NormListID",
			"NormUniqueID",
			"ContentTypeId",
			"contentclass",
			"UserName",
			"JobTitle",
			"WorkPhone",
			"SPSiteUrl",
			"SiteTitle",
			"CreatedBy",
			"HtmlFileType",
			"SiteLogo"
		],
		"resultSourceId": "8413cd39-2156-4e00-b54d-11efd9abdb89",
		"sortList": []
	},
	"queryTextSource": 1,
	"layoutProperties": {
		"showFileIcon": true,
		"showItemThumbnail": true
	},
	"showSelectedFilters": false,
	"showResultsCount": true,
	"showBlankIfNoResult": false,
	"useMicrosoftGraphToolkit": false,
	"enableTelemetry": false,
	"itemSelectionProps": {
		"allowItemSelection": false,
		"selectionMode": "AsDataFilter",
		"allowMulti": false,
		"valuesOperator": "or"
	},
	"extensibilityLibraryConfiguration": [
		{
			"name": "Default extensibility library",
			"enabled": true,
			"id": "dc4f961b-dbe0-44b4-982d-5776bf99d015"
		}
	],
	"selectedVerticalKeys": [],
	"useVerticals": false,
	"paging": {
		"itemsCountPerPage": 10,
		"pagingRange": 5,
		"showPaging": true,
		"hideDisabled": true,
		"hideFirstLastPages": false,
		"hideNavigation": false,
		"useNextLinks": false
	},
	"dataSourceKey": "SharePointSearch",
	"templateSlots": [
		{
			"slotName": "Title",
			"slotField": "Title"
		},
		{
			"slotName": "Path",
			"slotField": "DefaultEncodingURL"
		},
		{
			"slotName": "Summary",
			"slotField": "HitHighlightedSummary"
		},
		{
			"slotName": "FileType",
			"slotField": "FileType"
		},
		{
			"slotName": "PreviewImageUrl",
			"slotField": "AutoPreviewImageUrl"
		},
		{
			"slotName": "PreviewUrl",
			"slotField": "AutoPreviewUrl"
		},
		{
			"slotName": "Author",
			"slotField": "AuthorOWSUSER"
		},
		{
			"slotName": "Tags",
			"slotField": "owstaxidmetadataalltagsinfo"
		},
		{
			"slotName": "Date",
			"slotField": "Created"
		},
		{
			"slotName": "SiteId",
			"slotField": "NormSiteID"
		},
		{
			"slotName": "WebId",
			"slotField": "NormWebID"
		},
		{
			"slotName": "ListId",
			"slotField": "NormListID"
		},
		{
			"slotName": "ItemId",
			"slotField": "NormUniqueID"
		},
		{
			"slotName": "IsFolder",
			"slotField": "ContentTypeId"
		},
		{
			"slotName": "contentclass",
			"slotField": "contentclass"
		},
		{
			"slotName": "PersonQuery",
			"slotField": "UserName"
		},
		{
			"slotName": "UserDisplayName",
			"slotField": "Title"
		},
		{
			"slotName": "UserEmail",
			"slotField": "UserName"
		}
	],
	"useFilters": true,
	"useInputQueryText": true,
	"filtersDataSourceReference": "WebPart.544c1372-fb1d-4e96-bc1e-31fd66979667.a9ad131c-c2aa-47cf-afef-52e8dcecb0e4:pnpSearchFiltersWebPart",
	"defaultQueryText": "*",
	"useDefaultQueryText": true,
	"queryText": {
		"__type": "DynamicProperty",
		"reference": {
			"_reference": "PageContext:SearchData:searchQuery",
			"_sourceId": "PageContext",
			"_property": "SearchData",
			"_propertyPath": "searchQuery"
		}
	},
	"filtersData": {
		"__type": "DynamicProperty",
		"value": {}
	},
	"selectedItemFieldValue": {
		"__type": "DynamicProperty",
		"value": ""
	}
}
```

**Comment by wobba** [comment]
You need to share details on search provider, template setup, default query/dynamic data setup etc.

**Comment by adamsdatconed** [comment]
@wobba  Thank you for the guidance and comment.  I have updated my post to include my search results webpart settings.  Please let me know if there is anything else that I can provide that may be of help.  Appreciate your time and the response!

**Comment by wobba** [comment]
I cannot repro. * search works fine showing all three refiners.

![image](https://user-images.githubusercontent.com/51104/147948208-28e4d1fe-68ac-4f02-afc7-e1804d52ded5.png)

**Comment by adamsdatconed** [comment]
@wobba  I'll close the issue since it is probably environment specific.  The prod environment has a little over 500k items returning with the Local SharePoint Results result source and the filters only break when doing a wild card search against that volume of data.  I created new result sources and search verticals to force the user to have smaller / more targeted data sets returned.  This is working as expected, I just couldn't get the filters to work when querying against large data sets.  Thank you for your time and for looking into this.

**Comment by wobba** [comment]
Happy you found a work around, but still weird.
