### ISSUE TITLE
Call template service from library component

### ISSUE THREAD

**Issue by malcom1120** [microsoft-search/pnp-modern-search#166]
**Is your feature request related to a problem? Please describe.**
I'm trying to build a popup component where part of the search data is shown and the user can click it and show the rest of the data in the popup modal window.  The concept of popup I had working in custom renders and I'm trying to convert to library components.  Since I'm having to recode it anyway, I wanted to create a way for the user to build out templates for the main and modal and then I could just render using the template service so that I just build the popup component once instead of the 5 cloned custom renders (each slightly different data) I have today.

**Describe the solution you'd like**
Ability to reuse the configured template service and call it from a library extension component.

**Describe alternatives you've considered**
I'm sure I can rebuild the service in my component, but I didn't want to have to keep it up as changes are made.

**Comment by MakingThingsWorkToronto** [comment]
I'm not sure if this fits your purpose, but I'm trying to get this working using the extensibility library [here](https://microsoft-search.github.io/pnp-modern-search/search-extensibility-library/getting-started/). My goal is a bit different to merely display the item form in the side panel, but similar methodology.
I do have a custom renderer that displays a Bing Map so if the service was ported to a stand alone repo I'd definitely incorporate that in there too!

**Comment by malcom1120** [comment]
I have the custom web component working from the extension library, but I really would like to be able to use the template service so that I don't have to create 5 unique popup components when the only change is the data and format in the popup.  If I could create a template in the custom template and give it a unique class so that I can get it out of the HTML with a query selector and then use the template service to compile and generate the HTML, it would cut down on the number of "unique" components that I need to build and make it infinitely usable in the future.

**Comment by FranckyC** [comment]
Hi @malcom1120 Unfortunately this wouldn't possible right now. For now, you can still use your Handlebars compiler in your web component. You could define your custom templates using the `<template>` tag in the main HTML template. Waht do you mean by unique component? Do you pass the search results/format as parameter?

**Comment by malcom1120** [comment]
Like you said, my plan to create the "template" in the HTML using the template HTML tag and give it a unique class name so that I can get it out.  For my popup, right now I'm passing the current Item just like is done in the example web component.  I would think pass two additional params, template class name for display format and template class name for popup format. If you think it is possible at some point to implement the template service so it can be called, then I would just use that service in my one popup component with the formats passed in.  Currently in my custom renders, I have 5 popup renders where the only difference is the data displayed to click and the popup data.  What I'm going to do for now is use my own handlebars compiler (mostly cloned from this one) and keep moving.  I will then retro fit if it comes available. I understand it might take some time to implement, but I just wanted to get it on the radar to see if it is valuable to others.  Making the components reusable and expandable is my main goal here. I might even push my generic handlebar rendered popup component over to the project once I get it working (pending approval from my company ☹)

**Comment by malcom1120** [comment]
I think I figured out to use the search HB.  I was looking through the code and noticed that the HB is that is registered is put on the windows object for global usage (Thank You!!!!).  Well, I'm just getting it off of the windows object if it is defined else I'm setting it to a default HB object.

`const hb = ((window as any).searchHBHelper !== undefined) ? (window as any).searchHBHelper : Handlebars;`

Then I use the hb const where I would have used Handlebars.  Works perfectly.

Still trying to figure out how to get to the templates defined in the property pane instead of passing it in on the WebComponent as a string param, but I have it working like I wanted. Little more debugging and I'm good to go.

**Comment by malcom1120** [comment]
@wobba or @FranckyC  - Is there a way to get to the template defined in the webpart either by the HTML or URL? I can't seem to get to it so I thought I'd ask.

**Comment by wobba** [comment]
Not today, but it could probably be passed on, but in general if you do a custom component you handle all yourself, typically not using handlebars(?)

**Comment by malcom1120** [comment]
Well I'm building reusable custom components like Modal Popup and Accordion.  In my company we have quite a few search pages were we cloned the display template to make it unique for that user but the functionality was the same just the content was different. So here we are and I'm building reusable ones where I pass in the data format and let the component build it.

**Example**
`<search-accordion-component item="{{JSONstringify item 2}}" accordionHeaderText="More Information" templateBody="<span>\{{Title}}</span>"></search-accordion-component>`

![image](https://user-images.githubusercontent.com/8712085/80523629-59836000-895c-11ea-986b-c3f34358fc08.png)

I'll keep hacking at ideas on how to best handle the template. But having the handlebar in the windows object was a great first step for me.

**Comment by malcom1120** [comment]
Closing issue since the initial issue of using Handlebars in a custom component.

**Comment by MakingThingsWorkToronto** [comment]
@malcom1120 - tested another way to do this where template is compiled / executed outside the scope of the Web Component -> so you're not getting a template but rather the post processed output.

1) Add the handlebars template as a child of the web component. 

2) In the WebComponent > connectedCallback grab the this.innerHTML and assign it to the props to be passed into your react component (props.children = this.innerHTML).

3) Apply the raw HTML within the react component however you want. 

Nesting web components within the child template also seems to work fine at first glance. 

There is an example [here](https://github.com/MakingThingsWorkToronto/mtw-search-extensibility/blob/master/src/components/SidePanelTemplateComponent/SidePanelTemplateComponent.tsx) of one of your first scenarios - opening a side panel where the contents are the output of a template.

The difference with this pattern is you wouldn't assign web component properties for item**s** nor template, but rather just rely on the (non-global) handlebars processing the items for you, and then grabbing the output & spitting it out in the format you'd want in the web component.

**Comment by malcom1120** [comment]
Great idea. I'll try that tomorrow. I think that will be more intuitive for the users. I'll let you know how it goes.

**Comment by malcom1120** [comment]
Thanks @MakingThingsWorkToronto.  That worked prefectly.  Now the "template" is inside of the component inner body and no need for any template handling in my component, just normal HTML handling.

`<search-accordion-component accordionHeaderText="More Information">
                                {{#if RefinableString23}}
                                    <div class='moreContentRow'><span>Content Owner:</span><span><a href='#' target='blank'>{{{RefinableString23}}}</a></span></div>
                                {{/if}}
                                {{#if RefinableString24}}
                                    <div class='moreContentRow'><span>Document Type:</span><span>{{{RefinableString24}}}</span></div>
                                {{/if}}
                                {{#if RefinableString33}}
                                    <div class='moreContentRow'><span>Hazard(s):</span><span>{{{RefinableString33}}}</span></div>
                                {{/if}}
                                {{#if RefinableString36}}
                                    <div class='moreContentRow'><span>Business Unit(s):</span><span>{{{RefinableString36}}}</span></div>
                                {{/if}}
                                {{#if RefinableString37}}
                                    <div class='moreContentRow'><span>Business Areas(s):</span><span>{{{RefinableString37}}}</span></div>
                                {{/if}}
                                {{#if RefinableString48}}
                                    <div class='moreContentRow'><span>Asset Family:</span><span>{{{RefinableString48}}}</span></div>
                                {{/if}}
                                {{#if RefinableString51}}
                                    <div class='moreContentRow'><span>Chemical(s):</span><span>{{{RefinableString51}}}</span></div>
                                {{/if}}
                            </search-accordion-component>`
