### ISSUE TITLE
Filter: Apply / Clear button out of sight in long dropdowns

### ISSUE THREAD

**Issue by till-llit** [microsoft-search/pnp-modern-search#1660]
**Version used**
4.5.x

**Describe the bug**
With 4.4 the apply button was changed to be visible always in Filter Combo Boxes.

With the change #1542 this helpful change was revoked - apply and cancel button is again out of scope and invisble for the users for combo boxes with high amount of items (scrollbar)

**To Reproduce**
connect filter to results webpart and add a filter with a high amount of choices.
open the filter, you will not see the apply button until you scroll down to the end of the list

**Expected behavior**
option a)  remove the apply button. implement instant filter on checkbox click in the filter.
option b) ensure that apply and cancel buttons are always visible (maybe on top of the combo box?)

**Screenshots**

**Desktop (please complete the following information):**
edge 95

**Additional context**

**Comment by FranckyC** [comment]
Will be fixed in the next release 4.5.3 coming soon.

**Comment by till-llit** [comment]
@FranckyC : the fix is not working in my tenant, apply and cancel are still on the bottom and out of scope:

![image](https://user-images.githubusercontent.com/91128746/147051396-bddf5ef9-4515-4971-aa6b-a0eb30f9dafe.png)
