### ISSUE TITLE
Configurer filter webpart on a people vertical

### ISSUE THREAD

**Issue by jeffangama** [microsoft-search/pnp-modern-search#1662]
**Version used**
4.5.2

**Describe the bug**
I added a filter webpart, when i click to connect it to the People vertical I Have (one search results inside)
i get a white page in the property pane and this error in the console
Error: The value for "Custom field key" must not be undefine

**To Reproduce**
1. I added a filter webpart, when i click to connect it to the People vertical I Have (one search results inside)
2. i get a white page in the property pane and this error in the console
3. Error: The value for "Custom field key" must not be undefine

**Expected behavior**
No white page in the property pan, so that i can configure the filter webpart

**Screenshots**
![image](https://user-images.githubusercontent.com/6776269/146910393-8d4e9195-e3f0-4a0f-9766-12f9fe15e499.png)

**Desktop (please complete the following information):**
 -Chrome, Edge

**Additional context**
NA

**Comment by FranckyC** [comment]
Hi @jeffangama, It is due to missing FR translations. Will be fixed in the next release. Thanks!

**Comment by jeffangama** [comment]
Alright :) Thank you so much for the work done ;)
FYI when i hover the people card , it shows the people profile and the labels are in english

**Comment by wobba** [comment]
@jeffangama Graph Toolkit don't have language translations when I last looked at the code so nothing we can do for that card.

**Comment by jeffangama** [comment]
Unless you hard code translation :p but not recommended I guess :) 
Anyway thank you so much

**Comment by FranckyC** [comment]
@jeffangama this sample uses the Live Persona component, not the Microsoft Graph Toolkit:

**Comment by jeffangama** [comment]
Thank you guys for your inputs ! You rock :)
