### ISSUE TITLE
Web Part Connections appear not working in Edge Browser

### ISSUE THREAD

**Issue by bcameron1231** [microsoft-search/pnp-modern-search#167]
**Version used**
3.5.0.0

SharePoint Build Version
16.0.0.19918 ( also Standard Release)

**Describe the bug**
Search Result web part is no longer feeding information from connected web parts when using Edge. When I first configure the web part, the refiners and search box work correctly. 

After the page refreshes, the refiners and search box no longer update the queryText and refinementFilters for the search results. Web Part connections are still listed within the web part properties.

Also, if I use SearchBox send query to new page, and configure the new page to pull from the browser. It executes the first request correctly, but immediately sends a subsequent request, and renders with the wrong results as if there was no search query.

Appears to work in Chrome browser.

**To Reproduce**
1.  Add search box, refiner and search results web part to page
2. Connect the web parts
3. Refresh the page in Edge, the search box and refiners no longer work.

**Expected behavior**
Refiners and Search Box should update the search results.

**Screenshots/Requests**
1. Initial  page load using * queryText and a default query template (hidden results for privacy)
![image](https://user-images.githubusercontent.com/7944457/78169551-cd3e5580-740e-11ea-8459-64aebd5e5eb4.png)

`{
   "request":{
      "__metadata":{
         "type":"Microsoft.Office.Server.Search.REST.SearchRequest"
      },
      "ClientType":"ContentSearchRegular",
      "Properties":{
         "results":[
            {
               "Name":"EnableDynamicGroups",
               "Value":{
                  "BoolVal":true,
                  "QueryPropertyValueTypeIndex":3
               }
            },
            {
               "Name":"EnableMultiGeoSearch",
               "Value":{
                  "BoolVal":true,
                  "QueryPropertyValueTypeIndex":3
               }
            }
         ]
      },
      "Querytext":"*",
      "EnableQueryRules":false,
      "QueryTemplate":"{searchTerms} Path:{Site} ContentTypeId:0x0101009A1CA45428369C47A509AB4D7A9E9B5B*",
      "RowLimit":20,
      "SelectProperties":{
         "results":[
            "",
            "UniqueIDTitle",
            "Path",
            "Created",
            "Filename",
            "SiteLogo",
            "PreviewUrl",
            "PictureThumbnailURL",
            "ServerRedirectedPreviewURL",
            "ServerRedirectedURL",
            "HitHighlightedSummary",
            "FileType",
            "contentclass",
            "ServerRedirectedEmbedURL",
            "DefaultEncodingURL",
            "owstaxidmetadataalltagsinfo",
            "UniqueID",
            "RefinableString100",
            "RefinableString101",
            "RefinableString102",
            "RefinableString103",
            "RefinableString104",
            "RefinableString120",
            "ParentLink"
         ]
      },
      "TrimDuplicates":false,
      "SortList":{
         "results":[
            {
               "Property":"Created",
               "Direction":0
            },
            {
               "Property":"Size",
               "Direction":1
            }
         ]
      },
      "Culture":1033,
      "Refiners":"RefinableString120,RefinableString122,RefinableString123,RefinableString121,RefinableString124,FileType",
      "HitHighlightedProperties":{
         "results":[

         ]
      },
      "RefinementFilters":{
         "results":[

         ]
      },
      "ReorderingRules":{
         "results":[

         ]
      }
   }
}`

2. Selecting a refiner
Notice how the refinementFilters isn't populating. Same behavior with QueryText for the searchbox. Results remain the same.

![image](https://user-images.githubusercontent.com/7944457/78169326-70429f80-740e-11ea-993d-53823700e8e3.png)

`{
   "request":{
      "__metadata":{
         "type":"Microsoft.Office.Server.Search.REST.SearchRequest"
      },
      "ClientType":"ContentSearchRegular",
      "Properties":{
         "results":[
            {
               "Name":"EnableDynamicGroups",
               "Value":{
                  "BoolVal":true,
                  "QueryPropertyValueTypeIndex":3
               }
            },
            {
               "Name":"EnableMultiGeoSearch",
               "Value":{
                  "BoolVal":true,
                  "QueryPropertyValueTypeIndex":3
               }
            }
         ]
      },
      "Querytext":"*",
      "EnableQueryRules":false,
      "QueryTemplate":"{searchTerms} Path:{Site} ContentTypeId:0x0101009A1CA45428369C47A509AB4D7A9E9B5B*",
      "RowLimit":20,
      "SelectProperties":{
         "results":[
            "",
            "UniqueIDTitle",
            "Path",
            "Created",
            "Filename",
            "SiteLogo",
            "PreviewUrl",
            "PictureThumbnailURL",
            "ServerRedirectedPreviewURL",
            "ServerRedirectedURL",
            "HitHighlightedSummary",
            "FileType",
            "contentclass",
            "ServerRedirectedEmbedURL",
            "DefaultEncodingURL",
            "owstaxidmetadataalltagsinfo",
            "UniqueID",
            "RefinableString100",
            "RefinableString101",
            "RefinableString102",
            "RefinableString103",
            "RefinableString104",
            "RefinableString120",
            "ParentLink"
         ]
      },
      "TrimDuplicates":false,
      "SortList":{
         "results":[
            {
               "Property":"Created",
               "Direction":0
            },
            {
               "Property":"Size",
               "Direction":1
            }
         ]
      },
      "Culture":1033,
      "Refiners":"RefinableString120,RefinableString122,RefinableString123,RefinableString121,RefinableString124,FileType",
      "HitHighlightedProperties":{
         "results":[

         ]
      },
      "RefinementFilters":{
         "results":[

         ]
      },
      "ReorderingRules":{
         "results":[

         ]
      }
   }
}`

**Desktop (please complete the following information):**
Edge 44.18362.449.0

**Comment by bcameron1231** [comment]
So looks like it may be a SP Services issue on my build version. Dynamic Data isn't working on any web parts for this tenant in Edge. I've opened a ticket with MSFT on this.

**Comment by FranckyC** [comment]
Thanks for the update @bcameron1231. Good to know :)
