### ISSUE TITLE
{{getPreviewSrc item}} does not return expected result

### ISSUE THREAD

**Issue by McBamm** [microsoft-search/pnp-modern-search#1672]
I have encountered the same issue within two seperate tenancies when using Handlebars Template to customise search results.

The following notation does not return a preview of the items image as expected and instead image displays the site logo.

`<div class="n-card-image" style="background: url('{{getPreviewSrc item}}'); background-position: center center; background-size: cover; "></div>`

Whereas using this notation works and the page's image displays as expected:

`<div class="n-card-image" style="background: url('{{PictureThumbnailURL}}'); background-position: center center; background-size: cover; "></div>`

Obviously not a difficult issue to correct and work around, however, I am curious as to why the getPreviewSrc item function has stopped working.

**Comment by FranckyC** [comment]
Hi @McBamm, can you tell the version you are using? Please follow the issue template next time...

**Comment by coupalm** [comment]
I've found the same issue. In my case the returned items are jpeg files and the {{getPreviewSrc item}} return for all items is:
https://tenant.sharepoint.com/sites/apps-digitalAssets/SiteAssets/__sitelogo__presentation.png

When using PictureThumbnailURL it returns the right url and the Thumbnail display correctly.

My customer is using Version 4.1.0.0. I'll upgrade if new realease fix the issue.

**Comment by wobba** [comment]
v3 is no longer maintained
