### ISSUE TITLE
See all link option is missing in PnP Search Result

### ISSUE THREAD

**Issue by ggelosi** [microsoft-search/pnp-modern-search#1674]
**Version used**
4.5.3

**Describe the bug**
Option to show a "See all" link is not available, even if it's in the documentation https://microsoft-search.github.io/pnp-modern-search/usage/search-results/layouts/#common-settings

**To Reproduce**
Add a PnP Search Result webpart, insert any query, select any layout and the setting to show a "see all" link is never shown

**Expected behavior**
Under common settings there should be an option to have or not a see all link

**Screenshots**
![seeAllPnp](https://user-images.githubusercontent.com/77103764/147206287-8aa9d8f3-b0fe-481e-b161-5b3824beeeca.png)

**Desktop (please complete the following information):**
 - Chrome, Edge, Firefox

**Comment by wobba** [comment]
@FranckyC we need to update the documentation to reflect the current common options. @ggelosi for your scenario you should add the link to a custom layout instead as we don't plan to add this feature back.

**Comment by FranckyC** [comment]
Hi @ggelosi, this is unfortunately a mistake in the documentation. This feature is not available. You should add the link manually in the template.
