### ISSUE TITLE
PnP Search result (People Template) - Showing some users with blank detail

### ISSUE THREAD

**Issue by shariq1379** [microsoft-search/pnp-modern-search#1675]
**Version used**
4.2.3

**Describe the bug**
PnP search result shows some blank details for some users when we search "test23456782" term in PnP search result (People template) page. We have checked, these users are having correct details mapped as other users. Also, when we change it to custom handlebar template to default people template then it shows correct details with these users. Please refer attached screenshot.
**To Reproduce**

1. Search "test23456782" term 
2. PnP search result (people template) shows blank users 

**Expected behavior**
PnP search result (People) should show correct users details

**Screenshots**
![image](https://user-images.githubusercontent.com/77804584/147290590-86205588-ceb6-4445-a1b0-a60594bb28a7.png)

**Desktop (please complete the following information):**
 - chrome, edge

**Comment by FranckyC** [comment]
Hi @shariq1379, this behavior is due to Microsoft Graph Toolkit `person` not finding the user. To bypass the issue you can try to update the tempate and use the `AADObjectID` managed property instead of the default value for the `user-id` attribute of the **mgt-person** component:

```
<mgt-person user-id="{{AADObjectID}}" person-card="hover">
...

**Comment by FranckyC** [comment]
Hi @shariq1379 . Will be fixed in the nex release.
