### ISSUE TITLE
Can we connect few Search text boxes to one Result webpart?

### ISSUE THREAD

**Issue by Gennady-G** [microsoft-search/pnp-modern-search#1676]
Hi! 

As I understand - currently we only can send result from one text box:

![s2-2021-12-24_143305](https://user-images.githubusercontent.com/5569346/147345359-8e230d5f-4daa-489a-a426-8935edad4718.jpg)

We can use KQL queries to get more results: for example here we search by two columns:
![s0-2021-12-24_143539](https://user-images.githubusercontent.com/5569346/147345491-4be3eb32-aa42-4473-bd28-275c1ea66f69.jpg)

I also can add aliases and use something like this: `(T:CA*) OR (Num:080*)`

But all these is a little complicated for simple users. Can I add several inputs - one for Title and second for Number?..

Best regards, Gennady

**Comment by FranckyC** [comment]
Hi @Gennady-G, unfortunately, you can't really do that with the default option. You can only connect one search box per search results.

**Comment by Gennady-G** [comment]
Thank You for response @FranckyC! :) Happy New Year!
