### ISSUE TITLE
Pagination issues switching tabs targeting a single document library

### ISSUE THREAD

**Issue by vynarim** [microsoft-search/pnp-modern-search#1677]
**Version used**
4.5.2

**Describe the bug**
When you click on pagination items in a tab with several items and you come back to another tab with only one item, the item is not shown if on previous tab you were on page 2 or more. 

**To Reproduce**
1. Configure PnP search results scope to target a single site and only items from the default document library
2. Create content in order to have 1 item returned by first tab and several items (at least 3 pages) for the second tab
3. Click on tab 1 to display search results (1 item is shown as you can see on picture 1)
4. Click on tab 2 to display search results (several items are shown) with at least 3 pages
5. Click on page 2 from tab 2 to display items (as you can see on picture 2)
6. Click on tab 1 : no items are shown (picture 3)
7. click on tab 2 and then on page 1 and then on tab 1 : the item from tab 1 is displayed again

**Expected behavior**
When you click on a tab, you always see search restults (if exists), it should not depend on the page number you were selecting on a previous tab

**Screenshots**
![image](https://user-images.githubusercontent.com/20367460/147586452-fc91beb7-8b0c-4ec1-ab6d-ed61e10b26d4.png)
![image](https://user-images.githubusercontent.com/20367460/147586295-af16daa2-8922-45f6-8df9-72453afac0ad.png)
![image](https://user-images.githubusercontent.com/20367460/147586330-62e3affe-7a08-486e-83b2-571a488e5b05.png)

**Desktop (please complete the following information):**
- Edge 96.0.1054.62 
- Chrome 96.0.4664.110

**Additional context**
Please note this issue does not occur when you configure the search results webpart to crawls several sites with each tabs refining on a specific content type (default mainstream configuration for an intranet)

![image](https://user-images.githubusercontent.com/20367460/147586989-cad430ee-e907-41ad-b38a-9830e337a42b.png)

**Comment by vynarim** [comment]
Here is the webparts configurations
[webpartproperties-search-results.json.txt](https://github.com/microsoft-search/pnp-modern-search/files/7787923/webpartproperties-search-results.json.txt)
[webpartproperties-vertical.json.txt](https://github.com/microsoft-search/pnp-modern-search/files/7787924/webpartproperties-vertical.json.txt)

**Comment by wobba** [comment]
Cannot reproduce with latest version. Relog issue if still present on latest for you.
