### ISSUE TITLE
Search result should update after selecting filters values (Multiple value selection option) 

### ISSUE THREAD

**Issue by spo365** [microsoft-search/pnp-modern-search#168]
**Is your feature request related to a problem? Please describe.**
Search result should update after selecting filters values (Multiple value selection option).
For example:- when user selected values from product filter it should update results rather user click on apply button on each filter section. 

**Describe the solution you'd like**
Search result should update results on check event rather then on click event for apply link

**Additional context**
![image](https://user-images.githubusercontent.com/5062256/78218937-5a1a0980-750a-11ea-98c6-46fe30cc5724.png)

**Comment by FranckyC** [comment]
Because new refinement results are returned every time dynamically by the API when one is selected, the behavior you describe is simply not possible. That's why there is an apply button for multi values. We send selected filters with a OR condition between values.
