### ISSUE TITLE
Filter: Apply / Clear button out of sight in long dropdowns #1660

### ISSUE THREAD

**Issue by till-llit** [microsoft-search/pnp-modern-search#1683]
Happy new year ;)

#1660 is still reproducable with 4.5.3 and not resolved for me

**Comment by FranckyC** [comment]
Hi @till-llit, can you try in a private window to make sure this is the correct version you are using and not a cached version. I redeployed the 4.5.3 package and the Apply/Clear buttons are on top as expected.

**Comment by till-llit** [comment]
thats strange. im on 4.5.3 since 22.12.2021 - so caching should not be an issue.

just tested it again - both buttons are still on bottom.
![image](https://user-images.githubusercontent.com/91128746/147946055-08846eba-6472-43b0-a5e3-9b50878f8ef5.png)

for both, check box and combo box

**Comment by till-llit** [comment]
thanks! that did the trick - buttons are now on top.
