### ISSUE TITLE
"People" source on Graph provider gives error

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#1685]
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/1682

<div type='discussions-op-text'>

<sup>Originally posted by **mariaarcena** December 31, 2021</sup>
Hello! So I updated the pnp modern search on our tenant and I wanted to try the Microsoft Search (as the data source) and search only "People" and I get this:
Object reference not set to an instance of an object
![image](https://user-images.githubusercontent.com/17426994/147796102-bd50eeb4-8f84-4385-9c84-b39fd69b167e.png)

Am I missing something? 🤔💭
</div>

Issue is due to passing down the `Fields` array on the request. Removing this and the query works. Have to investigate if this is supported or if we need to not pass fields on the people source if the returned fields are hard coded.

**Comment by edarroudi** [comment]
@wobba I had this problem too and checked with graph-explorer (tester) - it was not supported.

**Comment by wobba** [comment]
I'll check if it's an API issue or by design - and then see if we should fix it in the web part or not.

**Comment by wobba** [comment]
There's an API fix likely rolling out in about two weeks time to fix this. An intermediate workaround is to ensure `phones` is added to the fields list to avoid breaking the call.
