### ISSUE TITLE
'People' search is throwing '[500] Internal Server Error' [PnP modern search V3.15]

### ISSUE THREAD

**Issue by TanZul** [microsoft-search/pnp-modern-search#1691]
**Version used**
3.15

**Describe the bug**
People search not returning results. Instead when type user name in the search box on a PnP modern search page it throws below error:
**"Error making HttpClient request in queryable [500] Internal Server Error ::] {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}"**

![image](https://user-images.githubusercontent.com/97188825/148270706-af203bf0-9396-493a-9433-64118d5b3cb5.png)

**To Reproduce**
1. Go to PnP search page
2. Type a name of employee on the search box and
3. Click on 'All' vertical - it throws the error mentioned above
4. Click on the 'People' vertical - it shows '0Results found'

**Comment by TanZul** [comment]
We have validated that default search (People search) and REST API work as expected:
•	The default search portal: https://tenant.sharepoint.com/sites/Search
•	Direct REST query: https://tenant.sharepoint.com/sites/search/_api/search/query?querytext=%27kenneth%27&trimduplicates=false&rowlimit=10&sourceid=%27b09a7990-05ea-4af9-81ef-edfab16c4e31%27&clienttype=%27ContentSearchRegular%27
•	Result Source Query Builder Test: (SPO admin > Search > Manage Result Sources > new result source > Launch Query Builder
Test Query: {searchTerms} ContentClass=urn:content-class:SPSPeople

**Comment by wobba** [comment]
Can you re-test with the latest version? https://github.com/microsoft-search/pnp-modern-search/releases/tag/v3.23.0 And you don't share how the verticals are set up, so a bit hard to repro based on what you give of information.

**Comment by TanZul** [comment]
We deployed the **V3.23** in our staging env. It is not functioning well. Upon typing names of employees it gives files/sites/links in results, but that seems something missing in configuration. It doesn't search people yet but doesn't give error either. Will double check the configuration and let you know how that goes.

Below are the screenshots of configuration of our production PnP search which we have issue with: 

**Search Vertical:**

![image](https://user-images.githubusercontent.com/97188825/148453940-513f1a62-7ae6-4826-92e8-470fe700a787.png)


**Link URL for People Tab:** https://TENANT.sharepoint.com/sites/Search/SitePages/Results.aspx?q={QueryString.q}&k={QueryString.q}&tabName=People





**Search Box:**

![image](https://user-images.githubusercontent.com/97188825/148452227-2dce3114-c4aa-45d2-9e98-6cdb3f191590.png)

![image](https://user-images.githubusercontent.com/97188825/148452633-ace991cc-9476-4d6a-9379-e6c1a2705d39.png)






**Search Result:**

![image](https://user-images.githubusercontent.com/97188825/148451990-73e7b42a-f51a-43a9-abea-e10e5173e2cc.png)

![image](https://user-images.githubusercontent.com/97188825/148452048-24af57a0-00da-4d45-b3cf-d5f9e04fdc1b.png)

![image](https://user-images.githubusercontent.com/97188825/148452061-6362af7d-fb9f-416a-8ff2-8a4760f90d49.png)

![image](https://user-images.githubusercontent.com/97188825/148452073-0e53eac7-05a4-49e6-8bae-658b915af973.png)

**Comment by wobba** [comment]
` {searchTerms} STS_Site departmentId:{xxxxx-xxxxx-xxxxx-xxxxx}` <- this is a weird query template if you want to have people search. And you need to use `b09a7990-05ea-4af9-81ef-edfab16c4e31` as the result source id to hit the people index.

**Comment by TanZul** [comment]
We deployed the PnP search 3.23 version in our test tenant. Used only the source ID for people search and removed the other piece from the search term but it still doesn't search people. However we did not get an error in the lower environment as we get in production (V3.15). It throws files, sites and other links instead of 'People'.

![image](https://user-images.githubusercontent.com/97188825/149385055-0d9bc2f5-f727-496f-b4eb-e24bb81774f0.png)

![image](https://user-images.githubusercontent.com/97188825/149385085-458e0505-0ce5-4f14-b4ea-90460ba415f5.png)



The issue cannot be in the configuration as we are using this PnP search V3.15 since last January 2021 and the people search was working fine until it broke in January 2022. Other verticals are still working fine like All, Files and Sites.

**Comment by wobba** [comment]
To figure out 500 issues you need to examine the request made, to see if it's correct or not. Could be a change has been made to the API to allow less "errors" to be handled gracefully as an example. 

It's either a malformed request which now manifests itself, or an API bug being introduced.

**Comment by TanZul** [comment]
We have validated there is not an API bug with validating that default people search works in the default search portal. (If there was an API bug, people search would fail in the default portal)
Also, direct REST query works: https://tenant.sharepoint.com/sites/search/_api/search/query?querytext=%27kenneth%27&trimduplicates=false&rowlimit=10&sourceid=%27b0**9a7990-05ea-4af9-81ef-edfab16c4e31**%27&clienttype=%27ContentSearchRegular%27

Result Source Query Builder Test works: (SPO admin > Search > Manage Result Sources > new result source > Launch Query Builder
Test Query: {searchTerms} ContentClass=urn:content-class:SPSPeople

We also confirmed the the source ID -  9a7990-05ea-4af9-81ef-edfab16c4e31.

**Comment by wobba** [comment]
If you get a 500 error, something is "wrong" with the request sent from the web parts. And to figure that out I would need to look at the JSON request made from the web part.

Similar to this screen shot.

![image](https://user-images.githubusercontent.com/51104/149985177-3ed3792d-3a84-4a8d-819e-ec9a56d0a5fb.png)

**Comment by TanZul** [comment]
Here is the PostQuery payload: 

![image](https://user-images.githubusercontent.com/97188825/150010005-3d660f40-37cc-4fbf-a073-6a7baa05989b.png)

**Comment by TanZul** [comment]
Below is the expanded request output. Expanded all except properties..



![image](https://user-images.githubusercontent.com/97188825/150386896-c004138e-d4e9-410d-b4cf-1175b4fb4924.png)

![image](https://user-images.githubusercontent.com/97188825/150386925-141ae05c-d3a1-4374-808b-5f856b2a72bb.png)


Note: We have switched the cb parameter to nb.

**Comment by wobba** [comment]
@TanZul Can you please share the JSON as text and not screenshots? For the request click "view source" and copy the text.

**Comment by TanZul** [comment]
Please see the output in attached text file.

[PnPSearch-json_1-21-22_946.txt](https://github.com/microsoft-search/pnp-modern-search/files/7914517/PnPSearch-json_1-21-22_946.txt)

**Comment by wobba** [comment]
Looked at the request and cannot see anything which stands out. I cannot make the query fail.

Some input on your setup. You have both XRANK and sorting on the query. Those will not work together. You either use XRANK or you use sorting. You can also try to turn of query rules, in case there's a query rule triggering which interfere somehow.

**Comment by wobba** [comment]
I believe your query template should be like below using `contentclass` - and also curious how the error applies to people search as the title of the issue is. Is the idea that you want to boost libraries to the top, then sites? And boost those with a title match within those?
```
(({searchTerms} XRANK(nb=1) Title:{searchTerms}) XRANK(nb=100) contentclass:STS_Site) XRANK(nb=1000) contentclass:STS_ListItem_DocumentLibrary
```

**Comment by TanZul** [comment]
We were using _**(({searchTerms} XRANK(cb=1) Title:{searchTerms}) XRANK(cb=2) STS_Site) XRANK(cb=3) STS_ListItem_DocumentLibrary departmentId:{389aaa2f-7b3e-4e2d-bd1a-8740ba4a5bdf}**_  in query. After removing the department piece and changing the cb to nb ( so it is now -  _**(({searchTerms} XRANK(nb=1) Title:{searchTerms}) XRANK(nb=2) STS_Site) XRANK(nb=3) STS_ListItem_DocumentLibrary)**_, the people search started working for some users. The strange thing is why it is working for some users and not for others. For some users it is throwing errors on 'All' vertical. 'People' vertical is returning correct results for all the users now.

![image](https://user-images.githubusercontent.com/97188825/150563560-1885627d-9c9e-4088-8b07-65b8d81938b3.png)


We get error only when we search a person in the search box. Search works fine when we search for other key words like promoted search, files, docs etc.. 

We tested with the this query  - _**(({searchTerms} XRANK(nb=1) Title:{searchTerms}) XRANK(nb=100) contentclass:STS_Site) XRANK(nb=1000) contentclass:STS_ListItem_DocumentLibrary**_   but no change in search behavior. It still gives errors for some users.

**Comment by wobba** [comment]
It's not in 3.15, it was added in v3.18.2. So you need at least that version or newer.

That said, a call should not break because you specific multi-geo, even though you don't have it in my opinion. Unless documented that it should

**Comment by TanZul** [comment]
Current state:  The PnP search is working partially for people search. For some users it throws errors but not for others. It doesn't seems to have anything with query. If query is wrong, will be wrong for all the users names.

Other issue is that search is not pulling the users' images. When type some letters of the names, as per setting it give names suggestions list, but images are not there with name.

![image](https://user-images.githubusercontent.com/97188825/150812306-5ee45f5d-958e-43b4-a557-982c705d6a09.png)


Right clicked on the image logo and checked the image address, this seems linked to wrong url (https://outlook.office.com/owa/service.svc/s/GetPersonaPhoto?email=firsname.lastname@tenant.com&UA=0&size=HR96x96&sc=1611327817880).

It should be going to - 
https://tenant.sharepoint.com/_layouts/15/UserPhoto.aspx?size=m&accountName=firstname.lastname@tenant.com&default=none


Do you know where is this setting to change it to correct address?


Thanks for all your help!

**Comment by wobba** [comment]
Hard to know what results you are looking at and what template you are using. Don't think the outlook URL is coming back from search for a profile image. Do you have a custom suggestion provider installed?

**Comment by TanZul** [comment]
No we do not have custom suggestions provider installed ( as per our knowledge). The developer who built the search is no longer with the company. Not sure how we can verify it.  The setting for "custom suggestions provider" was enabled in the webpart. When I disable it, it stops suggesting any result. Even though the "Enable query suggestions" is enabled.

![image](https://user-images.githubusercontent.com/97188825/151048594-786006d2-ab96-407f-a8a6-43b31543e80e.png)

![image](https://user-images.githubusercontent.com/97188825/151048639-b1427624-f990-453d-9d99-d3d8cf9cdb88.png)


The point to note is that we get 500 error only when we search person name and the error come only on the 'All' vertical. Any other query words ( meaningful or non meaningful) don't throw error.
Also we get error only when we add **departmentId:{389aaa2f-7b3e-4e2d-bd1a-8740ba4a5bdf}** in the search term (It was always there and we had no issue until now)  of 'All' vertical.

I can send you our PnP search configuration kb in your email, so you can take a look how the search package was built.

**Comment by TanZul** [comment]
@wobba - did you receive the setup word file in the email?

**Comment by wobba** [comment]
@TanZul Don't know as I don't which address to look at and what to look for. E-mail processing is rather slow these days. That said, this does not seem like a web part issue, but some API issue depending on what your query is sent as. I unfortunately don't have to dig into this for repro and as you're the only one reported this then it should be possible for you to figure out how to either config your way around it, or send a valid REST JSON request to Microsoft for investigation.

**Comment by TanZul** [comment]
@wobba - Can we schedule a call so you can see our entire configuration? I believe that way you will find the dot which causing the issue. It is being really long since our search is broke and we need to do something to give end users search back. We are fine to go to upper version. But need some help to limit the scope of search and set the verticals correctly.

**Comment by TanZul** [comment]
I have discovered that the issue is caused by turning on query rules in webparts.

![image](https://user-images.githubusercontent.com/97188825/154592448-ced88a2f-028e-4412-9768-0d57edab4b9d.png)

![image](https://user-images.githubusercontent.com/97188825/154592430-adaf40f2-eda3-4b7c-80be-5e12d3d1149f.png)


However, we need to keep the query rules enabled to utilize Promoted Search feature. 

The issue persists regardless of the version, even the with latest version **V4.5**.

**Comment by wobba** [comment]
@TanZul can you share what the query rule does? Rewrite the query, result block, promoted result?

**Comment by TanZul** [comment]
We are using the query rule just for promoted results.

**Comment by sumitdeyonline** [comment]
@wobba - I am having a similar issue, is there any resolution regarding this?

**Comment by wobba** [comment]
You have to talk to Microsoft support.

**Comment by sumitdeyonline** [comment]
@wobba - Thank you for your suggestion, however, we have tried with the out-of-box Microsoft search with the query rules, it's working as expected.

**Comment by sumitdeyonline** [comment]
@TanZul - Are you able to figure out this issue?
