### ISSUE TITLE
When opening web page in Edit on Sharepoint, SearchBox crashes when trying to search for character '%' 

### ISSUE THREAD

**Issue by BartCoder88** [microsoft-search/pnp-modern-search#170]
**Version used**
3.10

**Describe the bug**
I've installed 2 webparts: SearchBox and SearchResults on a "sharepoint online based" web site.
I've configured the SearchBox web part as DataSource of SearchResults in the same web page.
While I've the web page in Edit mode, I try to search a phrase with the special character '%' and there is a crash of the SearchBox webpart

**To Reproduce**
1. Add SearchBox and SearchResults webparts in the same web page
2. Configure SearchBox as Data Source of SearchResults
3. Type a phrase containing the '%' character (i.e.: test%), having the web page in Edit Mode
4. SearchBox crashes and disappears from the web page

**Expected behavior**
Searching phrase with special characters with no crashes

**Screenshots**
Example of test case:
![image](https://user-images.githubusercontent.com/63094667/78341233-a3646a80-7597-11ea-86fc-8418bff48a09.png)

**Desktop (please complete the following information):**
 - chrome

**Additional context**
Exception details:
**------console log chrome browser---------**
sp-pages-assembly_it-it_5af4874aac4793cb77eecbda00ede52e.js:21 URIError: URI malformed
at decodeURIComponent (<anonymous>)
at t.UNSAFE_componentWillReceiveProps (search-box-web-part_e42aabcb467a214797d49f2c6cba49b9.js:1)

**-------source code at row 21 (minified)------**
t.prototype.UNSAFE_componentWillReceiveProps=function(e){this.setState({searchInputValue:decodeURIComponent(e.inputValue)})}

**maybe this is the related piece of source code (in SearchBoxContainer.tsx) that caused the exception:**
  
  public UNSAFE_componentWillReceiveProps(nextProps: ISearchBoxContainerProps) {
    this.setState({
      searchInputValue: decodeURIComponent(inputEncoded),
    });
  }

**Comment by FranckyC** [comment]
Hi @BartCoder88 Did you set a default data source connection to the search box?

**Comment by BartCoder88** [comment]
Hi @FranckyC. This is the screenshot of console log:

![image](https://user-images.githubusercontent.com/63094667/81800391-10620d00-9513-11ea-8445-b633788d2e4b.png)

**SearchBox** is configured as follows:

![image](https://user-images.githubusercontent.com/63094667/81800902-dba28580-9513-11ea-9cf8-1d8c05c74ce2.png)

And **SearchResults** as follows:

![image](https://user-images.githubusercontent.com/63094667/81800984-ff65cb80-9513-11ea-904d-eddac34b9fcc.png)

**Comment by MakingThingsWorkToronto** [comment]
The issue here is with dynamic data. We should open a bug with the spfx group:

let inputValue = this.properties.defaultQueryKeywords.tryGetValue();
^ doesn't appear to be parsing the URL correctly...

**Comment by wobba** [comment]
@BartCoder88  Why haven't you picked something in the third drop-down when picking dynamic data in the search box?
