### ISSUE TITLE
Applying a metadata tag as search filter result in an empty search result webpart

### ISSUE THREAD

**Issue by AndreSchiemann** [microsoft-search/pnp-modern-search#1702]
**Version used**
4.5.3

**Describe the bug**
After a wildcard search I am getting a selection of metadata tags as possible search filters from the search results. After selecting one of the provided metadata filter values the search result webpart shows no items. 

However, using the configured filter for the Managed Property "Author" the filtering of search results works perfect and I am getting the search results.

**Expected behavior**
the applicable filtered search results are shown in the search result webpart

**Screenshots**
configuration of search filter for the metadata tags:
![2022-01-11 search refiner config](https://user-images.githubusercontent.com/76996358/149022559-10a9ca3b-d6aa-4cc1-af00-c75be4d7e5b9.PNG)

provided value for metadata tag:
![2022-01-11 search filter](https://user-images.githubusercontent.com/76996358/149022622-77f07326-8db5-42a0-b0dc-f99f9a4a9407.PNG)

after selecting this particular tag as filter I am getting no search results and the filter webpart shows in this way:
![2022-01-11 search filter after select](https://user-images.githubusercontent.com/76996358/149022685-0e47358d-f2cb-4c9e-8437-abaac7765635.PNG)

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**
* items are news pages in one particular website. 
* Query template is {searchTerms} AND PromotedState=2  WebId:{Site.ID}

May I have a misconfiguration here or its really a bug!?

Thanks in advance,
André

**Comment by FranckyC** [comment]
Hi @AndreSchiemann, I think I know what could cause this. Can you just switch to the debug template and tell me what is the value of the property `owstaxidmetadataalltagsinfo`? Thanks!

**Comment by FranckyC** [comment]
PR  #1703 should fix this if you have the opportunity to test

**Comment by AndreSchiemann** [comment]
@FranckyC 
Here is the value for owstaxidmetadataalltagsinfo from the debug template of the search result webpart. The values are from the first item of the provided search result (based on wildcard search).

`"owstaxidmetadataalltagsinfo": "L0|#0c181d723-0899-426d-bcec-96c9e8162c02|Portfolio Development;L0|#0e779202f-c1bc-49f3-97fb-091578d3d7a7|Acquisition;L0|#078edc8f6-277d-4a90-ab04-1ad6d926719d|Enterprise;L0|#015730b15-8cdf-49a4-887d-03d8d5158c59|Portfolio",`

To complete my config for displaying the metadata tags: 
* I enabled Localization
* I configured the layout slot for "Tags" to "Autoowstaxidmetadataalltagsinfo"

Does this help regarding your assumption?

Meanwhile I will rebuild the scenario with v3.23 to check if the bug is there too and hopefully to provide a working solution for my customer :-)

Cheers,
André

**Comment by AndreSchiemann** [comment]
Update:
* I rebuild the scenario with v.3.23 - there is no bug on filtering search results for "owstaxidmetadataalltagsinfo". 
* In this version is no need to configure the layout slot for "Tags" to "Autoowstaxidmetadataalltagsinfo" and enable localization

**Comment by FranckyC** [comment]
I was able to reproduce the issue and the PR #1703 should fix it. As a workaround, you could use a **RefinableStringXX** managed property instead targeting your columns crawled properties.
