### ISSUE TITLE
Search Results Sorted By Relevancy

### ISSUE THREAD

**Issue by tomobak** [microsoft-search/pnp-modern-search#1704]
**Is your feature request related to a problem? Please describe.**
We have many users who are struggling with the sort order.  They wanted to see files in order of "Relevance" (files contains most number of keywords on top of the results).  However, with current pnp-modern search we can only sort by metadata ascending/descending.

**Describe the solution you'd like**
Sort the search results by Relevance.

**Describe alternatives you've considered**
Date descending.

**Additional context**
We think people are used to the classic search experience that the default sort order was by relevancy.  Is there any way to havethe same experience with the classic search results sort order?

**Comment by FranckyC** [comment]
HI @tomobak, you can configure the property **Rank** in the sort order configuration for the search results Web Part (type the value and press 'Enter' and then save the configuration)

![image](https://user-images.githubusercontent.com/5659122/149144567-cd919f71-e746-4610-8607-1406b925a484.png)

However, this is only the initial sort order. Sorting results through the UI is not possible currently.

**Comment by tomobak** [comment]
Hi FranckyC, I don't have "Rank" in the field list.  The closest one was "RankingOWSNMBR", but it gives me "this property is not sortable".
By they way, I am using v3.23

![image](https://user-images.githubusercontent.com/43676417/149148083-74e0ebd2-9fee-4ccf-8ca0-e5f1501e93e8.png)

**Comment by FranckyC** [comment]
This field is not present by default is the list, you can simply type the name and press enter in the dropdown field to add it.

**Comment by tomobak** [comment]
Yes, it seems taking more relevant files on top.  Can I ask what is the logic behind??

**Comment by FranckyC** [comment]
Can we close this issue?

**Comment by tomobak** [comment]
Thank you!!  This is perfect!
