### ISSUE TITLE
Page Link is Wrong in Search Results

### ISSUE THREAD

**Issue by tomobak** [microsoft-search/pnp-modern-search#1709]
**Version used**
3.23

**Describe the bug**
Some page link in the search results generated by {{getUrl item}} are wrong links.

The actual link should be:
_https://tenant.sharepoint.com/sites/sitecollection/SitePages/page.aspx_

The link generated for the pages in search results shows:
_https://tenant.sharepoint.com/sites/sitecollection/SitePages/?id=/sites/sitecollection/SitePages/Page.aspx&parent=/sites/sitecollection/SitePages_

When you click the link, it opens image viewer window displaying preview image of the page.

Some page links are generated like "https://tenant.sharepoint.com/sites/sitecollection/SitePages.aspx?web=1" and opens correct page.

**To Reproduce**
1. Search some pages (.aspx)
2. Hover over the title of the page in the search results.
3. Wrong URL (ODSP viewer link??) is displayed in the left lower corner and if you click on the link, it does not take you to the page but opens image viewer window displaying preview image of the page.

**Expected behavior**
Link should be a correct page link.

**Screenshots**
![image](https://user-images.githubusercontent.com/43676417/149206162-0f674ffd-4048-424d-91b8-219e22567ff0.png)

**Desktop (please complete the following information):**
Chrome

**Additional context**
Not all page results has this problem but cannot find what is the difference between those pages.

**Comment by tomobak** [comment]
The content type is "Site Page".  But both bad link and good link page has the same "Site Page" content type.

**Comment by wobba** [comment]
@tomobak makes it a bit hard to have a repro :) If you can share the response JSON or diff the JSON for a working item vs.one which is not working, that would help to track down the difference and which logic might fail.

**Comment by tomobak** [comment]
Hi. I pulled xml results instead using /_api/search/query?querytext='keyword', and compared Good page and Bad page results.  I found Good one contains "FileType" as "aspx" but Bad one does not have value at "FileType".  Would it be the reason?

**Comment by wobba** [comment]
@tomobak if "FileType" is missing in the properties of the bad one, that could very likely be the culprit. I've never seen `FileType` missing for a result when requested before as it should be populated for all SP items. Can you try to edit and resave the file which fails? Then wait for re-indexing and see if it's resolved.

**Comment by tomobak** [comment]
Hi. I tried republish and re-index it but FileType is still not populating... 

**Bad Page**
<d:Key>FileType</d:Key>
<d:Value/>
**Good Page**
<d:Key>FileType</d:Key>
<d:Value>aspx</d:Value>

I realized those pages with no FileType are at the sites created in 2019 and many pages were copied from existing page (so if there were no "FileType", it copied over too).  It seems newer sites' pages have FileType as 'aspx'.

Would it be possible for you to update the code to recognize aspx File Type from "Path"?

<d:Key>Path</d:Key>
<d:Value>https://sitename.sharepoint.com/sites/People/SitePages/PageName**.aspx**</d:Value>

Or if it is out of scope i understand too.  Thank you.

**Comment by wobba** [comment]
@tomobak the SharePoint item should have a property `File_x0020_Type` where the value is set, and seems this is missing for those pages. I have seen this myself as well when using the copy API internally in SharePoint, and ended up setting the value explicitly to be sure it was set as part of that custom work.

We could probably add more robustness and check e.g. the FileExtension property as well if FileType is missing.

I'll think it over a bit - but it's really a data problem 😉 one you can fix using e.g. PowerShell, but hard to know all pages where the bug is present.

**Comment by tomobak** [comment]
@wobba Thank you for your response.  I understood and agree that this is a data problem.  I will keep looking for a fix (like PowerShell and/or open a ticket with Microsoft), but if you can cover this in your webpart code, that would be really appreciated!

**Comment by wobba** [comment]
If you have the id of the page you can do something like:

```posh
Connect-PnPOnline -Url https://tenant.sharepoint.com/sites/yoursite
Get-PnPListItem -List SitePages # will list all pages so you can find the page id
Set-PnPListItem -List SitePages -Identity <your id> -Values @{"File_x0020_Type"="aspx"} -SystemUpdate
```

Then re-index the library.

**Comment by tomobak** [comment]
Super!  Thank you very much!  I will try this and if this works I think I am ok as we know which site's site pages are affected.

**Comment by tomobak** [comment]
FYI.. Set-PnPListItem does not seem working for File_x0020_Type.  I didn't get any error but FileType have still no data.
![image](https://user-images.githubusercontent.com/43676417/150162201-eb11cc23-51ac-4eef-865d-f875168b4287.png)

I tried "FileType" instead of "File_x0020_Type" but got an error the field does not exist...

**Comment by wobba** [comment]
I'm site admin at the site I'm testing and I can run `Set-PnPListItem -List SitePages -Identity 11 -Values @{"File_x0020_Type"="aspx"} -UpdateType SystemUpdate` just fine. I switched the value from aspx to pdf and back.

You have to re-index the library and wait for the change to be picked up.

If you run:
`(Get-PnPListItem -List SitePages -Id 527).FieldValues["File_x0020_Type"]` you should see the value you set.

**Comment by tomobak** [comment]
You are right... Get-PnPListItem gives me "aspx".  I just reindex the library and wait for the results changes.
Thank you again!

**Comment by tomobak** [comment]
Mmmm.. sorry again.  I indexed library and waited over night but FileType is still blank.  Also, search result of that page still have a bad link..

Get-PnPListItem still gives me "aspx" on the page. However, I run Get-PnPListItem on another bad page with no FileType but I have not run Set-PnPListItem on File Type, and that gives me also "aspx"....?  So file type "aspx" was there but not showing up in "FileType" when we run search query.

**Comment by wobba** [comment]
Hmmm.. not sure what happens. You don't have a custom column named FileType on the library by any chance?

**Comment by tomobak** [comment]
No... it is out of box "Site Pages" library and no custom column.

**Comment by tomobak** [comment]
FYI - I tested SharePoint out of box results page and did same keyword search.  Then the pages does not have "FileTyp" had correct link with https://sitecollection/sites/sitename/sitepages/page.aspx...

**Comment by wobba** [comment]
@tomobak because our internal search page has different logic to pick the icon 🙂 I'm working internally (in Microsoft) on re-working the logic to identify items correct with the correct icon, and will ensure the logic is shared here. SharePoint is a long list of edge cases.

**Comment by tomobak** [comment]
Thank you very much for the update!  I really appreciate your help... Please let me know if you need any other information.

**Comment by tomobak** [comment]
One more FYI..  

I tested with v4.5.3 and the link of no "FileType" page seems generated better like this and opens the page -> https://tenant/sites/sitename/sitepages/pagename.aspx?web=1

The link icon is blank document icon instead of and no preview.

**Comment by wobba** [comment]
The icon fix is not in yet.

**Comment by tomobak** [comment]
Hello, I know you have a lot in your plate but would v3 be updated sometime soon for this missing "FileType" link issue?

**Comment by wobba** [comment]
Sorry, I don't have an ETA for this.

**Comment by wobba** [comment]
Still no ETA from me if I'm to do the work as I have limited free time to spend on coding.

**Comment by vikaskottari** [comment]
Is there a resolution yet? I am facing the exact same problem, version 3.15.3.0.
However, on the pnp search filter web part, i have added FileType as a refiner and i am able to see and filter "ASPX" files. But the url is incorrect as described above. In addition, the resulted summary column wither shows empty, or as a random long guid like:  **02ec6658-736a-46ff-ade4-e6277a8f7f26 6138c306-d907-4ac0-960d-15083adf7fba…**

**Comment by wobba** [comment]
No. I'm very limited on time, and when I code it's mostly on v4.

**Comment by kasperbolarsen** [comment]
Since v3 is not being updated anymore this case is closed
