### ISSUE TITLE
PnP Search Web Parts -  New property(toggle) for enable/disable Deephits 

### ISSUE THREAD

**Issue by shariq1379** [microsoft-search/pnp-modern-search#1716]
**Is your feature request related to a problem? Please describe.**
Yes it is, I raised an issue #1437 
Actually we are getting zero(0) count in PnP search refiner when search a specific keywords. We tried directly trigger same request using MS Search API and get the same issue, but when we added "DeepHits" then API return correct refiner counts, so I think, it will be good to have this property with web parts so that  we can enable/disable according to the load in search API.

**Describe the solution you'd like**
PnP Search Web Parts should have a new property which can enable/disable deephits. Also , when enable deephits property then it should ask to set number of deephits limit.
Ex: (deephits=1000000)

**Describe alternatives you've considered**
I don't think so if any other alternative. It could be if set default deephits value with search api request in PnP web parts

**Additional context**

**Comment by wobba** [comment]
As the deephit parameter is available for the SPO provider only I'm thinking how best to do this. We could hardcode a value large enough which seems around 10.000.

**Comment by wobba** [comment]
Added deephits to the SharePoint provider. And set Microsoft Search to 1 instead of 0 for minimumCount for good measure.
