### ISSUE TITLE
Error on iOS device

### ISSUE THREAD

**Issue by bdani1** [microsoft-search/pnp-modern-search#1717]
Hi Team,

**Version used**
Ex: 4.1.0

**Describe the bug**
I made a search page with PnP components (search box + verticals + results WP). It works fine on desktop and android, but not on iOS devices.

**To Reproduce**
Open the page. It does not even load.

**Expected behavior**
The page with pnp webparts get rendered.

**Screenshots**
Error message  says:
[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/XXX.sharepoint.com/sites/apps/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-box-web-part_e02c9a336c04e8a79728c494219c84df.js' for resource 'modern-search-box-web-part' in component '544c1372-7e5a-49ec-8db6-812f76c375f2' (pnpSearchBoxWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/XXX.sharepoint.com/sites/apps/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/modern-search-box-web-part_e02c9a336c04e8a79728c494219c84df.js' for resource 'modern-search-box-web-part' in component '544c1372-7e5a-49ec-8db6-812f76c375f2' (pnpSearchBoxWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
t@https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de_3dadbd0472a2721b5fefedf0fa51305e.js:70:213690
t@https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de_3dadbd0472a2721b5fefedf0fa51305e.js:71:9402
t@[native code]
@https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de_3dadbd0472a2721b5fefedf0fa51305e.js:71:46653
@https://modernb.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_de-de_ac154927ebbabd7d3c4b.js:1:6072

**Desktop (please complete the following information):**
 -On desktop it works fine in Edge/Chrome/Firefox

**Additional context**

**Comment by wobba** [comment]
Please add details of your deployment according to all the fields in the bug template. If not the issue will be closed.

**Comment by bdani1** [comment]
Hi Wobba, I'm sorry. I updated it according to the bug template.

**Comment by wobba** [comment]
@bdani1 as v4.5.1 is the latest you should retry with that one as we don't do patch releases on older versions.

**Comment by till-llit** [comment]
tested with 4.4.1 and 4.5.1 on iOS 15.1

MS SharePoint App for iOS: all PNP Modern Search Webparts are working
Edge for iOS: all PNP Modern Search Webparts are working

cannot test with Safari (not supported in our enviroment)

**Comment by bdani1** [comment]
I upgraded to 4.5.1 and the issue is gone. Thank you, I could have done this step by myself ;)
