### ISSUE TITLE
URL filtering with german umlaut

### ISSUE THREAD

**Issue by HamEv** [microsoft-search/pnp-modern-search#1725]
**Version used**
3.23.0.0

**Describe the bug**
I'm using a search page, which is be references by different url parameters, to show different file types in search result box. I'm looking for different file type in buildings, eg. alarm system documents, fire protection documents ,...
The page is called by the following url:
https://tenant.sharepoint.com/SitePages/Suche.aspx?filters=[{"n":"SPContentType","t":["Alarmanlage"]},{"n":"RefinableString19","t":["string('lalala')"]}]
This works pretty cool and the filters in search result page are set automatically:
![image](https://user-images.githubusercontent.com/61208008/149737981-11b22d48-de0b-4c41-8100-ff4ea17aa644.png)

The problem is, when I want to show a document type, which contains a german umlaut (https://en.wikipedia.org/wiki/Germanic_umlaut#German_orthography):
https://tenant.sharepoint.com/SitePages/Suche.aspx?filters=[{"n":"SPContentType","t":["**Gebäudeplan**"]},{"n":"RefinableString19","t":["string('lalala')"]}]
The filter does not recognize the string and does not show anything. As a workaround I tried to filter with following term: https://tenant.sharepoint.com/SitePages/Suche.aspx?filters=[{"n":"SPContentType","t":["Geb*"]},{"n":"RefinableString19","t":["string('lalala')"]}] - the result is shown correct, but filter is not checked:
![image](https://user-images.githubusercontent.com/61208008/149738502-e7bb1890-f3cd-4cae-8b7c-b86db0b990ac.png)

**To Reproduce**
Filter for a term with umlaut inside.

**Expected behavior**
Filtering with german words with umlaut should be work, too.

**Desktop (please complete the following information):**
 - Browser: chrome, edge, ...

Can you please check, why filter is not working with termn with umlaut.

**Comment by wobba** [comment]
Hmm.. this was supposed to be fixed with #1185. I'll retest it.

**Comment by HamEv** [comment]
@wobba using the filter on the page itself is working:
![grafik](https://user-images.githubusercontent.com/61208008/149885288-ad0542dd-8784-461f-aad4-2c923a11ca26.png)

The problem is just, when calling the page with filter parameter in the URL.

**Comment by wobba** [comment]
@HamEv do you have a sample URL of how the `ü` is encoded in the URL? How are you linking into the page with pnp search parts?

**Comment by HamEv** [comment]
@wobba  I do not encode the ü in my url - I'm calling the URL like this: _https://tenant.sharepoint.com/SitePages/Suche.aspx?filters=[{"n":"SPContentType","t":["Gebäudeplan"]},{"n":"RefinableString19","t":["string('lalala')"]}]_

I'm using this link in my quicklink webpart. SharePoint is changing the URL to: _https://tenant.sharepoint.com/SitePages/Suche.aspx?filters=%5b%7b%22n%22:%22SPContentType%22%2c%22t%22:%5b%22Geb%c3%a4udeplan%22%5d%7d%2c%7b%22n%22:%22RefinableString19%22%2c%22t%22:%5b%22string%28%27lalala%27%29%22%5d%7d%5d_

**Comment by wobba** [comment]
Figure it out and will be fixed in the next release.

**Comment by HamEv** [comment]
Jehhhh - thanks a Lot!
