### ISSUE TITLE
Issue implementing custom web component

### ISSUE THREAD

**Issue by firmends** [microsoft-search/pnp-modern-search#1727]
Hello, I have created an SPFx extensibility library for the modern search web parts with several custom Handlebars helpers and all of those work fine.

When I attempt to implement a custom web component I am facing an issue where the library seems to fail to load at all. I implemented the custom web component using only the component sample code found at https://github.com/microsoft-search/pnp-modern-search-extensibility-samples/tree/main/search-extensibility-samples/src/libraries/

The issue occurs when I return the custom component object in getCustomWebComponents().

public getCustomWebComponents(): IComponentDefinition<any>[] {
    //prettier-ignore
    return [
      {
       componentName: 'my-custom-component',
        componentClass: MyCustomComponentWebComponent
      }
    ];
  }

If I simply comment out the above code and return an empty [] the problem goes away.

I am using the latest version of SPFx 1.13 and the @pnp/modern-search-extensibility 1.0.9.

When the problem occurs I am seeing errors in the console from modern-search-results-webpart.js about missing helpers (referencing some of the custom helpers I am using in my template).

I am stuck! Any help would be greatly appreciated!

**Comment by FranckyC** [comment]
Hi @firmends, can you:
- Tell us the exact error message you have in the console.
- Try with the [sample extensiblity](https://github.com/microsoft-search/pnp-modern-search-extensibility-samples/tree/main/search-extensibility-samples) library see if you get the same issue with the demo web component.
- Try to downgrade SPFx to the same version as the core Web Part (`1.12.1`)

**Comment by firmends** [comment]
Hi @FranckyC,

Thanks for your guidance. I downgraded the yeoman generator to 1.12.1 and rebuilt the solution from scratch and that seems to have solved my issue. I am able to use the generic custom component from the sample library in my template and it renders as expected now.

Thank you!
