### ISSUE TITLE
Pnp Search filter stopped rendering suddenly

### ISSUE THREAD

**Issue by shridha21** [microsoft-search/pnp-modern-search#1731]
**Version used**
Ex: 4.2.3

**Describe the bug**
We have created a custom search results page using Pnp v4 Webparts. The page displays search results using Pnp Search results webpart and it is tied to show Pnp filters. All of sudden without making any changes to this page the filters have disappeared. The search and filters had been working fine until Friday and all of sudden stopped working. if the user clicks on paging the filters reappear. 

**To Reproduce**
1. Create a site page and add the Search results webpart and setup Datasource - SharePoint Search
2. Set up result source to be Local SharePoint or any custom result source (GUID)
3. Use custom layout to display the results
4. Add Pnp Search filter on the same page and use the Search results webpart under available connections
5. Use Vertical layout for Filter
6. Enable Selected Filter option on the Search results webaprt and associate the Search filter.
7. Save and publish the page. The filters will show as expected
8. Now edit the page and change the Filter layout to custom and provide template file name and save and publish - the filters will not render. The custom layout for filter was working until Friday ( and it had been working for past several months) and all of a sudden stopped rendering. If there is paging with the search results click on another page and filter renders. Even refreshing or hard refresh doesn't help with rendering the filters.
9. Also now edit the page again and the filter webpart shows the message - "Display filters from connected Search results Webpart" followed by configure button. No matter how many times i make sure the filter properties are correct and the filter webpart show right in edit mode and the moment you save it and publish, same issue no filter show in the webpart.

**Expected behavior**
The filters if applicable should render whether it is custom layout or Vertical layout and also the filters should render at all times and user shouldn't be clicking on the paging section to reload the filter.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser- Edge, chrome

**Additional context**![pnpFilterconfigure](https://user-images.githubusercontent.com/46351822/150036649-6418f4a3-5741-4f13-a92a-1e53936581e5.png)

**Comment by wobba** [comment]
Seems like an API issue if it suddenly stopped working. Which properties are you using as filters?

**Comment by shridha21** [comment]
We have just one tenancy and different site collections for dev test and prod, how can i use the most recent version without updating in other site collections

**Comment by shridha21** [comment]
We have create managed properties (Refinable) properties that we are using the properties haven't changed. The filters appear when you click on the paging in the Search results webpart. So the filters are not loading on the for the first load.

**Comment by wobba** [comment]
@shridha21 get yourself a free dev tenant https://developer.microsoft.com/en-us/microsoft-365/dev-program

**Comment by shridha21** [comment]
Thank you wobba, I have a dev tencany, just wanted to see if there was any other way of doing it per site collection in one tenancy.

With regards to the error message - i don't see anything significant. Please let  me know if you would need the log.

**Comment by shridha21** [comment]
Update: a workaround has been found for this issue 
I am currently using the Custom layout for filters, the issue still exists if i use the template through external file. However, if i copy paste content of the file in the editor, the issue does not occur.

**Comment by wobba** [comment]
@shridha21 You can enable an app catalog for a site only, then upload a separate version in that one site.

**Comment by shridha21** [comment]
It was identified that sppkg file in app catalog was in checked state and as soo as it was checked in , the webparts started working. No further action needed.
