### ISSUE TITLE
Unnecessary margin in canvaszone when using verticals

### ISSUE THREAD

**Issue by VerlindenEAM** [microsoft-search/pnp-modern-search#1732]
**Version used**
4.5.2

**Describe the bug**
When you select the next vertical you will get extra white space per vertical. 
So when you for example have 6 verticals, you will get 5 times extra white space added.

I can see the following extra canvaszone added:
a_c_50a7110f a_c_50a7110f root-87 CanvasZone row CanvasZone--alignment CanvasZone--noMargin CanvasZone--read

**To Reproduce**
1. Page with multiple verticals and results webparts
2. Show result webpart only with specific vertical
3. Select next vertical
4. See screenshot

**Expected behavior**
Hidden results webpart doesn't create extra margin

**Screenshots**
![image](https://user-images.githubusercontent.com/35732908/150090030-72182f5b-b3a2-4121-a57e-650d9c26b9a5.png)

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**

**Comment by wobba** [comment]
@VerlindenEAM we can see if this is possible but an empty web part in SPFx will unfortunately add space. To remove it we need to do a DOM hack similar to what I have done in this sample web part. https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-script-editor/src/webparts/scriptEditor/ScriptEditorWebPart.ts#L29

It's a bit "hacky" so not sure if we want to add it. I'd rather have a proper solution built into SPFx.

**Comment by FranckyC** [comment]
Actually we already remove the blank part. Maybe Microsoft changed their DOM. Need to investigate.

**Comment by FranckyC** [comment]
Hi @VerlindenEAM , did you correctly hide Web Parts when verticals are not selected in the configuration?

**Comment by VerlindenEAM** [comment]
Hello @FranckyC , we used the setting "Display data only when the following vertical is selected" on all results webparts

**Comment by FranckyC** [comment]
@VerlindenEAM I cannot repro on my side :/. Can you try to enable the setting "Hide this web part if there's nothing to show"?

**Comment by VerlindenEAM** [comment]
@FranckyC , we selected the "Hide this web part if there's nothing to show", but the problem still persists.

**Comment by wobba** [comment]
Fixed with #3038
