### ISSUE TITLE
Unable to create context for SPHttpClient and PageContext using this._servicescope from BaseWebComponent while working with custom web component

### ISSUE THREAD

**Issue by soumyadeep2207** [microsoft-search/pnp-modern-search#1738]
Hi Team,

**Version used**
Ex: 4.2.3

**Describe the bug**
I am trying to create one custom web component and from there will call REST API using SPHttpClient. While doing so I am trying to use _serviceScope property coming with BaseWebComponent class like below. 

**export class MyCustomComponentWebComponent extends BaseWebComponent {
  
  private sphttpClient: SPHttpClient
  private pageContext:PageContext
  constructor()
  {  
    super()
    this._serviceScope.whenFinished(()=>{
      this.pageContext = this._serviceScope.consume<PageContext>(PageContext.serviceKey)--- this assignment
      this.sphttpClient= this._serviceScope.consume<SPHttpClient>(SPHttpClient.serviceKey)--- and this assignment are failing
      //const msGraphClientFactory: MSGraphClientFactory= this._serviceScope.consume<MSGraphClientFactory>(MSGraphClientFactory.serviceKey)
    })
 }**

But every time I am trying to assign service key to a property of type SPHttpClient its throwing me below error

**Argument of type 'import("../../../node_modules/@microsoft/sp-core-library/dist/index-internal").ServiceKey<import("../../../node_modules/@microsoft/sp-http/dist/index-internal").SPHttpClient>' is not assignable to parameter of type 'import("../../../node_modules/@microsoft/sp-component-base/node_modules/@microsoft/sp-core-library/dist/index-internal").ServiceKey<import("../../..//node_modules/@microsoft/sp-http/dist/index-internal").SPHttpClient>'.
  Types of property 'defaultCreator' are incompatible.**

I checked the following for the same https://github.com/microsoft-search/pnp-modern-search/issues/918. For SPFx webpart earlier I used service scope and have not found this issue. I am using SPFx 1.13 and Node 12.22.1, npm 6.14.12. I even tried deleting node module and re ran npm install but no luck.

Can you please have a look and guide me @wobba @FranckyC 

Thanks in Advance

**Comment by soumyadeep2207** [comment]
Hi Team,

Also I would like to have your view on below scenarios
1. How to consume SharePoint REST API/pnp Js from custom react component which is being rendered from BaseWebComponent
public async connectedCallback() {

        let props = this.resolveAttributes();
        **const debugView = <CustomComponent {...props}/>;**
        ReactDOM.render(debugView, this);
    }   
2. If yes then how to  pass the context in order to use any PnP Resuable controls like PeoplePicker. which reside in custom react component

Looking forward to hear from you. Thanks in advance

**Comment by FranckyC** [comment]
Hi @soumyadeep2207, the error is because you don't use the same SPFx version as the core Web Part. You must use the `1.12.1` version instead for the extensibility library.

**Comment by FranckyC** [comment]
For your other use case, please open a new discussion and not an issue. Thanks!

**Comment by soumyadeep2207** [comment]
Hi @FranckyC ,

Thanks for the quick suggestion, with 1.12.1 now able to create Service Key. For other queries I will raise a new discussion.
