### ISSUE TITLE
Filters web part panel configuration no longer shows selected filters inline on the page

### ISSUE THREAD

**Issue by mbice** [microsoft-search/pnp-modern-search#1744]
**Version used**
4.5.3

**Describe the bug**
Not sure if this is a bug or an intentional change, but in V3 when using the "Panel" configuration for the filters web part, the selected filters would show up on the page. After upgrading to V4, selected filters no longer show up and the user has to click "Filters" to see selected ones in the panel flyout.

V3:

![image](https://user-images.githubusercontent.com/985283/150650160-04230f2f-e4fd-4bc4-8e6c-da71cc33f87c.png)

V4:

![image](https://user-images.githubusercontent.com/985283/150650190-991e11af-a646-43c9-82e6-173a0cfbab30.png)

**To Reproduce**
1. Add filters web part and set configuration to "Panel"
2. Apply a filter
3. Notice the selected filters only show up in the panel flyout and no longer inline on the page itself

Is this expected? We are encountering some confusion from users, especially for scenarios where we apply filters automatically via querystring.

Thanks!

**Desktop (please complete the following information):**
 - Browser - any

**Comment by FranckyC** [comment]
This option is now in the search results Web Part when filters are connected:

![image](https://user-images.githubusercontent.com/5659122/150653598-a7163f09-e2cd-4a8f-8fe5-7d3b0c39825e.png)
