### ISSUE TITLE
Cannot find module ./zh.js

### ISSUE THREAD

**Issue by lesca** [microsoft-search/pnp-modern-search#1749]
**Describe the bug**
Some users unable to search with Search Box. Check the web console, the see error message:
`Cannot find module './zh.js'`
All the users unable to search in common -- the default language of the browser is "Chinese", i.e. not English. 

**To Reproduce**
1. Go to the page with PnP Search Box
2. Type any text and hit "Enter" to search
3. Nothing happens
4. Check the web console, see the error message `Cannot find module './zh.js'`

**Expected behavior**
The page on my computer works fine. Type text and hit "Enter" the Search Results shows up.
And from the console, there is no error above.

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/5976219/150922150-8e52c609-3584-4092-9224-e4b1af3d53f9.png)

**Desktop (please complete the following information):**
 - Version 97.0.1072.69 (Official build) (64-bit)

**Additional context**
Walkaround is clear all other languages in the SharePoint site.

**Comment by wobba** [comment]
Please use the template when logging issue, as the version information is important to repro any issue.

**Comment by lesca** [comment]
@wobba My apologize I accidently removed that part. The version is 4.5.3.0

**Comment by wobba** [comment]
Thank you, and to confirm, are you using Chinese as the browser language?

**Comment by lesca** [comment]
>

**Comment by wobba** [comment]
I have repro and assume this is v4. Next time please use the template and fill in all needed information on web part version, browser setup with language, sharepoint setup etc.

**Comment by wobba** [comment]
Fixed in the dev branch and the next release.
