### ISSUE TITLE
Error loading PnP search results on mobile devices

### ISSUE THREAD

**Issue by Gorica-M** [microsoft-search/pnp-modern-search#1750]
**Version used**
4.4.1

**Describe the bug**
Search and Filter web parts are not loading on mobile devices. Same behavior on both, Android and iOS devices.

**Expected behavior**
Web parts load the same way they load on a desktop device.

**Screenshots**

![image](https://user-images.githubusercontent.com/59504406/150940187-4f2ea855-c3e7-4ac1-a08d-da2b1eb7e1aa.png)

**Comment by Gorica-M** [comment]
@wobba thanks for that. I've upgraded to the latest version of the solution however users that are using the guest accounts are getting the below error message:


Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Failed to load path dependency "SearchBoxWebPartStrings" from component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Error loading https://component-id.invalid/544c1372-7e5a-49ec-8db6-812f76c375f2_4.5.3/SearchBoxWebPartStrings
Unable to load script https://xxx.sharepoint.com/sites/AppCatalogue/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/SearchBoxWebPartStrings_en-us_ba503fbfba8306ea4166a509a2679649.js

INNERERROR:
Failed to load path dependency "SearchBoxWebPartStrings" from component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Error loading https://component-id.invalid/544c1372-7e5a-49ec-8db6-812f76c375f2_4.5.3/SearchBoxWebPartStrings
Unable to load script https://xxx.sharepoint.com/sites/AppCatalogue/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/SearchBoxWebPartStrings_en-us_ba503fbfba8306ea4166a509a2679649.js
CALLSTACK:
t@https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-au_024601772bb8775b7506d447a271c4ea.js:70:215646
t@https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-au_024601772bb8775b7506d447a271c4ea.js:71:9108
t@[native code]
https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-au_024601772bb8775b7506d447a271c4ea.js:71:46239
https://modernb.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_88160e71d1f04ec1a8e4.js:1:6072
promiseReactionJob@[native code]

**Comment by wobba** [comment]
@Gorica-M If you have repro setup on the newest version, then log a new issue. Remember that when updating the package it can take minutes/hours before it reads correctly in SPFx due to caching.

**Comment by Gorica-M** [comment]
Thanks @wobba. I've logged a new issue: https://github.com/microsoft-search/pnp-modern-search/issues/1774.
