### ISSUE TITLE
custom suggestions provider with key 'CustomSuggestionsProvider' was not found

### ISSUE THREAD

**Issue by JamesHForsytheIV** [microsoft-search/pnp-modern-search#1753]
**Version used**
Search Parts 4.5.3, Extensibility Sample Suggestion provider 4.00 June 2021 update
(behaves this way on all of the v4 releases)

**Describe the bug**
I deployed changes to suggestions as usual then it was noticed that this error message displays on the search box.

The custom suggestions provider with key 'CustomSuggestionsProvider' was not found. Make sure the solution is correctly deployed to the app caltog and the manifest ID registered for this Web Part.Please refer to the official documentation.

Seems like the page in runtime can intermittently access the the suggestion provider.

Trying to determine if there is an issue with my App Catalog, MS had an issue with the App catalog that is "Resolved" but the suggestions provider has been intermittent since, I have updated all the deployments with latest code and this issue persists only in our Production tenant, the issue was also experienced in the development tenant where it is much harder to reproduce...

**To Reproduce**
1. Go to site 
2. Click on search box if no error suggestions appear, when the page state changes from navigation or searching the search box will intermittently error, once it errors you have to clear cache to fix until it errors again

**Expected behavior**
Search suggestions appear from the CustomSuggestionsProvider that should be available but is not intermittently 

**Screenshots**
attached

**Desktop (please complete the following information):**
modern desktop browsers
![suggerr](https://user-images.githubusercontent.com/67155153/151014621-7c2f1593-5bed-42a0-b96c-19d05eb184c5.PNG)

**Additional context**

MS Advisory 
Users with solution packages are unable to access some SharePoint Online sites, site features, and files
SP31668
![appcat](https://user-images.githubusercontent.com/67155153/151014804-1d19213b-d818-470e-9770-4f8eb88643cf.PNG)

![suggerr](https://user-images.githubusercontent.com/67155153/151014681-655fe199-51ba-48de-b94a-80960cae2f2b.PNG)
4, SharePoint Online, Last updated: January 24, 2022 9:52 PM
Estimated start time: January 15, 2022 2:00 AM

**Comment by JamesHForsytheIV** [comment]
Nothing yet going to try and look into the deployment options for using
multiple extensions,  I have heard this can cause issues with solution
files and versions.

I also will need to deploy this using CDN going to see how that goes.

**Comment by maartendevos** [comment]
Same issue here, also experience an issue when using the custom web components.
Not only with Search Parts V4.5.3 older versions too.

**Comment by JamesHForsytheIV** [comment]
After testing out for a day the search extensibility suggestion project seems to have suddenly started working correctly again.

**Comment by wobba** [comment]
Which means the SPFx fix is rolled out :) Closing this one.
