### ISSUE TITLE
Upgraded to 4.5.3.0 Modern Search no longer works. 

### ISSUE THREAD

**Issue by mouseman85** [microsoft-search/pnp-modern-search#1760]
**Version used**
4.5.3.0

**Describe the bug**
I have upgraded to the 4.5.3.0 and it now won't load on any site. 

**To Reproduce**
1. Upload New Package to App Catalouge
2. Insert webpart on site 
3. Error shown

**Expected behavior**
1. Upload new version
2. Insert webpart, and old webparts updated. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11850876/151185557-6a91d6f9-6b87-4f0e-b1f1-676b7b3b5f41.png)

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**

**Comment by wobba** [comment]
Re-upload the app package, publish it. And can take some time for CDN to pick up the updated package. Common SPFx scenario.

**Comment by mouseman85** [comment]
I reuploaded as a fresh install, waiting 30-45 minutes and still getting the same error
![image](https://user-images.githubusercontent.com/11850876/151249606-970208c7-e566-41e7-8729-949304c23054.png)
If I use an older version it loads instantly with no issues.

**Comment by wobba** [comment]
From the error message it's a CDN issue. And did you try to delete the app package, then upload a new one? You can also navigate to tenant.sharepoint.com/sites/CustomApps/ClientSideAssets and see if the folder 59903278-dd5d-4e9e-bef6-562aae716b8b is there with the files inside of it. Sometimes these things do get stuck. So not a web part issue, but SPFx install issue.

**Comment by mouseman85** [comment]
After 12 hours it seems it is now working that folder is showing, is there a reason why the new version would take so much longer to pull through, when testing with older version it was instant. 

![image](https://user-images.githubusercontent.com/11850876/151336092-7686e346-a98d-4bbb-81cc-1b1bdf8e236e.png)

**Comment by wobba** [comment]
Not anything to do with the version. All on SPFx and CDN propagation. Best is to update packages over a weekend. And it doesn't happen that often in my experience. But annoying indeed.
