### ISSUE TITLE
New documents not appearing in modern search results - despite appearing in native search results.

### ISSUE THREAD

**Issue by jimbul** [microsoft-search/pnp-modern-search#1763]
**Version used**
Ex: 4.5.3

**Describe the bug**
Hi There - Firstly - thank you, love this set of webparts, such a massive help. 

On the 25th January our Sharepoint modern search instance has stopped returning new results. Documents added to monitored libraries no longer appear in results. I have re indexed all four libraries that the search page looks at and rebuilt the site index and the issue remains. If i use SharePoint native search from the top bar, the results are returned as expected with files from the 26th and 27th as well. I had the same issue with v3 back in November but had to transfer all documents to new document libraries and when i rehomed the search to these new libraries all documents appeared as expected.

**To Reproduce**
I am able to reproduce the issue by adding a new file, categorising it with metadata and then searching using modern search, the new files do not show in results. If i search in SharePoint native search from the top bar all files are displayed as expected.

**Expected behavior**
For modern search to return recent as well as historical files in the library.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - Microsoft Edge, FireFox and Chrome

**Additional context**
N/A

**Comment by wobba** [comment]
Do you see the documents in classic search? https://tenant.sharepoint.com/sites/yoursite/_layouts/15/osssearchresults.aspx?

And should be no difference in what is returned in the web parts vs OOB search in SharePoint.

**Comment by jimbul** [comment]
Yes they appear perfectly in classic! so odd...

**Comment by jimbul** [comment]
These documents have been missing from modern search for more than 48 hours - please let me know if is there anything else i can check? I have checked that approval isn't enabled etc.

**Comment by FranckyC** [comment]
Hi @jimbul , are you using tokens or SharePoint query variables in your query by any chance?

**Comment by wobba** [comment]
@jimbul can you switch to the Debug template and look at the output of `queryModification` as it seems something is not set up correctly for you and interfering with the results.

**Comment by jimbul** [comment]
Hi @FranckyC  @wobba Yes of course - will do this morning and post here. @FranckyC - my query is below for the results part (apologies if this is not what you are looking for!:

{searchTerms} -fileextension:aspx Path: https://XXXXX.sharepoint.com/sites/NewBusiness/CCAP OR Path:https://XXXXX.sharepoint.com/sites/NewBusiness/NewBusResources OR Path:https://XXXXX.sharepoint.com/sites/NewBusiness/Best%20Practices OR Path:https://XXXXX.sharepoint.com/sites/NewBusiness/CCAPXXXX OR Path:https://XXXXX.sharepoint.com/sites/NewBusiness/CCAPXXXXXX
{SearchBoxQuery} (-ContentTypeId:0x0120*)

On Saturday morning a new item from Friday appeared in the results but those in the intervening period did not resurface. 
I then went to a few of the missing items, deleted and re-uploaded and they all appeared within 2-3 minutes.?

Thanks for your responses its super helpful

**Comment by wobba** [comment]
Probably doesn't matter but you might want to simplify and add some logical grouping.  Also wrote all props in the correct casing for good measure. Properties with the same name has an implicit OR so removed them - but fine to keep as well. Removed space after `:` for the first path as well.

```
{searchTerms} -ContentTypeId:0x0120* -FileExtension:aspx (path:https://XXXXX.sharepoint.com/sites/NewBusiness/CCAP
path:https://XXXXX.sharepoint.com/sites/NewBusiness/NewBusResources 
path:https://XXXXX.sharepoint.com/sites/NewBusiness/Best%20Practices 
path:https://XXXXX.sharepoint.com/sites/NewBusiness/CCAPXXXX 
path:https://XXXXX.sharepoint.com/sites/NewBusiness/CCAPXXXXXX)
```

**Comment by jimbul** [comment]
Beyond the call of duty - thank you very much @wobba

**Comment by jimbul** [comment]
@FranckyC @wobba - here is output from debug - is it possible my bad syntax in the query template has caused this to occur intermittently? (i have not yet applied the corrected template @wobba wrote above.

 "queryModification": "hong kong -fileextension:aspx Path: https://XXXXX.sharepoint.com/sites/NewBusiness/CCAP OR Path:https://XXXXX.sharepoint.com/sites/NewBusiness/NewBusResources OR Path:https://XXXXX.sharepoint.com/sites/NewBusiness/Best%20Practices OR Path:https://XXXXX.sharepoint.com/sites/NewBusiness/CCAPXXXX OR Path:https://XXXXX.sharepoint.com/sites/NewBusiness/CCAPXXXXX \nhong kong (-ContentTypeId:0x0120*) -ContentClass=urn:content-class:SPSPeople",
    "secondaryResults": []

**Comment by FranckyC** [comment]
@jimbul I suspect your query template to be incorrect. For instance the `{SearchBoxQuery}` token does not work with Modern Search but works in the classic search.

**Comment by wobba** [comment]
@jimbul Yes, your query template is wrong and will cause issues for you.. specifically the space after the `:` on the first `Path` part. Not sure how the `\n` will impact things but would remove it.

**Comment by jimbul** [comment]
Thank you @wobba  and @FranckyC  - I have applied your modified template and understand what i have done wrong, very grateful for your great support.
