### ISSUE TITLE
Extensibility library (Advanced customizations) failed to load

### ISSUE THREAD

**Issue by salascz** [microsoft-search/pnp-modern-search#1775]
**Version used**
Modern Search v4 (4.5.3) + original pnp-modern-search-extensibility-samples
Modern Search v3 (3.23.0) + custom extensibility library

**Describe the bug**
Hello,
we are using custom extensibility library in our solution. The solution stopped working without any reason (deployment/configuration) few days ago (probably last Friday). Our solution is deployed to Site App Catalog (both packages - modern-search + library). I have tried to simulate the behaviour with latest version with the same result. 

I tried to debug the issue - the ExtensibilityService throw an error inside `SPComponentLoader.loadComponentById` call. In fact, the engine is not able to load the extension manifest for the extension (sample from v3):
![image](https://user-images.githubusercontent.com/5662939/151767553-f87b100a-54c3-4178-92b0-7e97094a5a2f.png)

and the library load failed in loadComponent method:
![image](https://user-images.githubusercontent.com/5662939/151767738-dc312dee-ba01-4d1f-8a94-f416ac86e690.png)

Extensibility libraries do not seem to be loaded correctly. I hope it should not be a caused by using site app catalog...

**Interesting fact**
The solution work for the first reload sometime (e.g. InPrivate window), does not work after reload.

**To Reproduce**
1. Deploy the latest version of modern-search + extensibility-samples packages to site app catalog
2. Add Search Box OR Search Results WebPart on the page
3. Check the webpart configuration (Search Box WebPart OR Search Results WebPart should contains default extensibility provider
3a. For Search Box - I would expect the "Custom Suggestions Provider" to be loaded in configuration (Result: Not visible) 
3b. For Search Result - Configurate the layout to custom and insert "My custom component" (`<my-custom-component data-my-string-param="{{item.Title}}"></my-custom-component>`) to the template -> the Title should be rendered inside the <div> element. (Result: Not visible)

**Desktop (please complete the following information):**
 - Browsers: Chrome + Microsoft Edge

It looks like something was changed in SharePoint :-(.

Thanks

**Comment by FredrikEkstroem** [comment]
I'm having the exact same issue. It worked perfectly fine friday, but today none of the customizations are loading. No change or deploys happened from our side. I'm using v4

**Comment by FredrikEkstroem** [comment]
Ctrl f5 reload brings it back for me, after that a normal reload makes it fail again

**Comment by jacob-tornqvist** [comment]
I'm also facing the same issue

**Comment by jhholm** [comment]
See #1768. This is a known issue that is caused by SPFx behind the scenes

**Comment by salascz** [comment]
Thank you, 
I did not expect this issue to be closed already (sorry) 👍.

On the other hand, it is hard to explain to business they have to wait a week for a fix  🙄...

**Comment by salascz** [comment]
I'll close this one, please track a resolution via SharePoint/sp-dev-docs#7664.
