### ISSUE TITLE
Error: Missing helper: "x"

### ISSUE THREAD

**Issue by bcameron1231** [microsoft-search/pnp-modern-search#1779]
**Version used**
4.5.30

**Describe the bug**
When create an extensibility library for Handlebar Helpers, the Web Part is unable to successfully load the library. If I clear my cache by doing a hard refresh, the helper library will load successfully.

**To Reproduce**
1. Create a simple handlebar helper through an SPFx library.
2. Deploy to the App Catalog
3. Register the library manifest guid in the Web Part properties
4. Add Helper to Manage Column definition in layout options
5. See error 

**Expected behavior**
Web Part should be able to load the extensibility library which is configured for the web part.

**Screenshots**
Layout Column Definition
![image](https://user-images.githubusercontent.com/7944457/151811271-cffc56d6-f126-4045-a80c-0c73d075d267.png)

Web Part to Library Configuration
![image](https://user-images.githubusercontent.com/7944457/151811297-214a6fd0-228c-49f9-8d0c-828ab6c3cbf6.png)

Rendered Display (Using Details List)
![image](https://user-images.githubusercontent.com/7944457/151810811-a488a34b-12c0-4a84-9eb0-422eb50b363e.png)

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**
I'm not sure if this is an issue with the Web Part itself, or an issue on the MSFT side with caching, but the SPFx Library will not load. When I clear my cache, it loads fine and will work for a little while... if I leave and come back to the page, I need to clear my cache in order for the helper to work.

I also use the Filters Web Part and the Search Box Web Part on the page.

I've read through previous issues such as #594 but seems it's still an issue.

**Comment by wobba** [comment]
Seems related to #1775
