### ISSUE TITLE
Use modern search webparts page as custom results page URL

### ISSUE THREAD

**Issue by toblum** [microsoft-search/pnp-modern-search#178]
**Version used**
3.11.0

**Describe the bug**
Dear pnp-modern-search team,

I'm not 100 % sure if this is this right place to ask this as it's not directly related to the modern search webparts. It's more on the usage of them, but I hope you can help me or direct me to the right place.

We created a search page using the really great modern search web parts which works fine and wanted to configure our sitecollection search boxes to point to our custom results page. We did this as shown by Vesa here: https://youtu.be/SG3ngNXGUX8. We set the search settings ("search center URL" and "custom results page URL") to our page, on web and sitecollection level, to be 100 % sure. But even after days, the search field still points to the built-in results page. We tried it on several communication sites manually via site settings or using the "Set-PnPSearchSettings -SearchPageUrl xxxx" commandlet via PS. No changes to the behaviour.

The only visual difference is, that on our tenant the search box isn't yet moved to the suite bar, it's still located in the right header section. Does this make a difference? Has anybody seen the same behaviour on another tenant?

Any help would be appreciated.

Best regards
Tobias

**To Reproduce**
1. Go to 'site settings'
2. Set "search center URL" and "custom results page URL" to your target results page.
3. Wait some time
4. Search field still opens built-in results page.

**Expected behavior**
Should redirect to custom results page

**Screenshots**
![image](https://user-images.githubusercontent.com/18660238/78713075-f2a0f700-7919-11ea-8c5e-c843a5f8e5ab.png)
Settings used

![image](https://user-images.githubusercontent.com/18660238/78713128-0ba9a800-791a-11ea-8d24-060096965f74.png)
This is how the search field is shown on this tenant.

**Comment by wobba** [comment]
You need to wait for the search bar to ship in the header for this to work, which also allows you to consume the query from the header search box.

**Comment by toblum** [comment]
Hello, Mikael,

thanks for the really quick response. I was afraid of this answer, when I saw the behaviour. Then I suppose we'll have to wait for the feature to be released to launch our search solution.

If I see it right, this should be the roadmap item https://www.microsoft.com/de-de/microsoft-365/roadmap?filters=&searchterms=57133. Right? I have already seen it on new tenants, so it seems to be in rollout. Do you have any insight into when the feature might be received on existing standard release tenants? 

Many greetings

**Comment by toblum** [comment]
Oh, I just saw that you edited your answer after I sent mine. Thanks for the feedback on the rollout.

**Comment by wobba** [comment]
It's in TR and 10% GA, and was halted a while ago due to a regression issue which unfortunately has taken some time to get properly fixed.
