### ISSUE TITLE
CSS injection case

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#179]
**Version used**
Ex: dev-branch

**Describe the bug**
The following template does not remove the original CSS, allowing CSS injection. Add an empty div and style tag.

```
<content id="template">
    <div>
    </div>
    <style>
        .ms-Button-label {color:red !important;}
    </style>
    <div class="template_root">
```

![image](https://user-images.githubusercontent.com/51104/78784432-9d122c00-79a5-11ea-95a1-484a0db35d20.png)

**Comment by FranckyC** [comment]
@wobba Resolved by #212. My bad, I just forgot to remove styles once prefixed. Should be ok now.
