### ISSUE TITLE
Different Character in LastName is not displayed

### ISSUE THREAD

**Issue by gristy58** [microsoft-search/pnp-modern-search#18]
Please see screenshot for example:

![Annotation 2019-11-12 084217](https://user-images.githubusercontent.com/37768717/68625161-63d5ad00-0528-11ea-9e4b-3a1d5242c248.png)

**Comment by FranckyC** [comment]
Hi @gristy58, could you give me more context about this? Are you talking about refiners or results?

**Comment by gristy58** [comment]
Only tested in results. Expected output is O'Neill

Tested on last name and job title with this issue but department is fine

**Comment by FranckyC** [comment]
@gristy58 Fixed by #64.
