### ISSUE TITLE
search result webpart: persona card component rendering issue

### ISSUE THREAD

**Issue by pravin080317** [microsoft-search/pnp-modern-search#180]
while rendering the personacardcomponent from the result types in search result webpart, the properties of optionaltext,secondarytext and tertiarytext is showing as undefined because of the casesensitive of second part of the letters "Text" "text". because of this persona rendering component is displaying only the image and text.
kinldy check on the below screenshots and let me know if i am wrong.

![image](https://user-images.githubusercontent.com/35328578/78769238-aeaa0280-79aa-11ea-8cf5-d7547ce0f9e3.png)

![image](https://user-images.githubusercontent.com/35328578/78769359-e3b65500-79aa-11ea-8607-655329c4ba9c.png)

ref of calling persona component via result types
`<div className={ styles.personaCard }> <a href='{{Path}}' target="_blank"> <pnp-persona-card text='{{Title}}' image-url="/_layouts/15/userphoto.aspx?size=M&accountname={{last (split AccountName '|')}}" **secondaryText**='{{last (split AccountName '|')}}' size={PersonaSize.size32} /> </a> </div>`

**Comment by pravin080317** [comment]
please refer the url for the more background..

https://github.com/microsoft-search/pnp-modern-search/issues/169

**Comment by wobba** [comment]
@FranckyC should attributes in latest version be `data-text`, `data-secondary-text` etc? And update template.md to reflect this?

**Comment by wobba** [comment]
Updated documentation to reflect to use `<pnp-persona-card ` with `pnp` prefix. Also prefixed attributes with `data` but not really needed.
