### ISSUE TITLE
Native SP Search (Modern) Site Level broken since PnP v4.5.3 installed and used

### ISSUE THREAD

**Issue by SPGitGhost** [microsoft-search/pnp-modern-search#1800]
**Version used**
4.5.3

**Describe the bug**

Not sure if anyone has experienced but unable to find any root cause at present. 

Native OOTB SharePoint Online modern search, when searching on ANY site/subsite (Search this site) level in the tenant, shows "Something went wrong" message. The behavior has started since the installation of PnP v4.5.3. 

Native search is working as expected when searching at a Tenant level or at a library/list level, BUT not at a site level.

Using the PnP v4 search web parts only on a particular subsite, nowhere else. Do have the V3 installed and in use elsewhere prior to this but this issue has never been experienced before re: native search broken, only when on a site level.

The PnP web parts are working as expected - results and filters in use and all looks fine there.

Is there any possible way that the V4 search web parts could be interfering with the native SP search? 

**Expected behavior**

Didn't expect the native Search at Site/Subsite level to be impacted by the search web parts v4.

**Screenshots**

![image](https://user-images.githubusercontent.com/99023589/152530867-14ac0971-81cd-499c-b6b9-2fc8be454000.png)

- Desktop: Windows 10
 - Browser - Chrome and Edge

**Additional context**

Really looking for any pointers if it is the PnP V4 search web parts causing this!

**Comment by FranckyC** [comment]
Hi @SPGitGhost, if it is a native search error then it is not related to PnP Modern Search Web Parts. By any chance you can inspect the network tab or console of your browser to see if you can get a more explicit error message.

**Comment by SPGitGhost** [comment]
@FranckyC  Thank you. That's been checked and cannot find anything explicit pointing towards the Search issue being experienced. The Query value looks absolutely fine captured via the Dev Tools > Network, and with successful Status Code of 200. The query value's structure also matches to the other tenant's query value for the similar search, where search is working as it should and with the search web parts v4 installed, but no V3 installed in that tenant alongside the v4.

Will appreciate if any further thoughts/pointers? Thanks

**Comment by SPGitGhost** [comment]
@wobba Apologies but thought I'd try asking the question if in case you could signpost to something by any chance? We are engaged with MS Support but not much luck on that front yet. Thanks

**Comment by wobba** [comment]
@SPGitGhost kind of hard to see the connecting with the PnP webparts. Try appending `disable3PCode=1` to the search.aspx URL and see if the issue is still there. That parameter will disable SPFx from loading deployed solutions.

You don't share anything about your setup for the page you search from. Are you on a modern page with a modern search wp, and then search? If so, if you create a blank page and search does that work?

You need to establish the SPFx/web part relationship with your issue.

**Comment by SPGitGhost** [comment]
Thank you @wobba 

It doesn’t feel it should be related but kind of running out of options to check/try in a way. The timing of installing the PnP V4 web parts and the issue to appear, was something that was a factor.

Some more info on exact issue:

-  the native search across all sites in the tenant is affected, not just on the site/page where the V4 search web parts are in use.

- the native search at tenant level and library/list level is working fine. 

- The issue is only when searching at the site level and native search box shows “search this site”

- All, Sites, Files, and People verticals show the above seen error, except just the images vertical.

- All verticals and result sources etc. are default OOTB. Nothing custom.

- The PnP V4 web parts are actually working fine where in use.

Like I say, it doesn’t seem it should be related but thought I’d ask if in case there was even a remote possibility of the V4 web parts inflicting this kind of behaviour, affecting the native SP search in this manner!

Don’t even see anything out there in the community that refers to native search with this kind of issue, with or without the V4 web parts being installed in the tenant. 

Thanks for looking at this anyway, but any pointers are welcome at this stage. MS Support are engaged but not sure if that’s going to be useful, at least not that quickly if at all.

**Comment by wobba** [comment]
Did you test `disable3PCode=1` and can we close this?

**Comment by SPGitGhost** [comment]
@wobba Thanks. Yes, that doesn't make a difference. And as earlier, it might not be related to the search web parts but it was an attempt to see if someone else had encountered similar behavior at all. 

Yes, I think if there's nothing else as a pointer at this stage then this can be closed. Thanks for your time though.
