### ISSUE TITLE
Don't works with sharepoint online

### ISSUE THREAD

**Issue by lmagoni** [microsoft-search/pnp-modern-search#1805]
Version: Latest

Description:
Searchbox cannot be linked with search results in Sharepoint Online
Searchbox cannot be configured in SharePoint Online (blank Screen after click on "edit webpart")
Search Results cannot be linked with searchbox

Screenshots:
attached

 - Browser [chrome, edge]
![2022-02-07 16_17_52-Intranet – Homepage](https://user-images.githubusercontent.com/99196669/152816557-cce89524-78c2-459c-848d-ff97f91c73ae.png)
![2022-02-07 16_16_23-Intranet – Homepage](https://user-images.githubusercontent.com/99196669/152816563-27080b9f-af1f-49db-8cbe-d938070ac87a.png)
![2022-02-07 16_19_08-Intranet – Homepage](https://user-images.githubusercontent.com/99196669/152816564-8e1c26f8-d724-444a-9c94-f5ee0236c472.png)

**Comment by wobba** [comment]
Check documentation at https://microsoft-search.github.io/pnp-modern-search/scenarios/ and closing issue as it doesn't follow the issue template guideline.
