### ISSUE TITLE
Intranet in Teams App : template 

### ISSUE THREAD

**Issue by SPNomad** [microsoft-search/pnp-modern-search#1822]
**Version used**
4.5.3.0

**Describe the bug**
When you package a sharepoint intranet site, in a Teams app, the template doesn't work if you activate "Display the image of the map by pointing the cursor"

**To Reproduce**
1. Create a SharePoint communication site
2. Create a page with PnP - Search, PnP Results
3. Choose data source "SharePoint" > LocalPeopleResults
4. Select property Department, JobTitle, People, Title, UserName, WorkPhone
5. Choose template "People3
6. Activate "Display the image of the map by pointing the cursor"
7. Build the Teams App with the Microsoft documentation : https://docs.microsoft.com/fr-fr/sharepoint/viva-connections-desktop#step-by-step-guide-to-setting-up-viva-connections-desktop-only
8. Deploy the app on Teams admin

**Expected behavior**
People template working on sharepoint site from teams app with card hover people

**Screenshots**
![bug01](https://user-images.githubusercontent.com/47565550/153603088-5d46769f-8746-43c1-aa1c-5e688ca59df2.png)
![bug02](https://user-images.githubusercontent.com/47565550/153603112-e973a51e-99bf-4a3d-b4d5-002649a659a2.png)
![bug03](https://user-images.githubusercontent.com/47565550/153603131-cc56e448-8220-4154-85fc-5b7325b7f221.png)

**Desktop (please complete the following information):**
 - Microsoft Teams Desktop

**Comment by FranckyC** [comment]
Hi @SPNomad, did you:

- Approve API permissions in the SharePoint administration center? https://microsoft-search.github.io/pnp-modern-search/installation/
- Try with the latest 4.5.4 version? We've made some updates regarding people layout.
Thanks!

**Comment by SPNomad** [comment]
Hi @FranckyC,

- Yes, the 9 API are approved (the page with PnPResult works fine via a browser, crash only via a Teams app)
- I updated with the last version. Now I can see results!!! Thanks, but the card is loading loading, and sometimes it displays the user's information after 10 or 30 seconds, any idea ?
![API](https://user-images.githubusercontent.com/47565550/153849244-6f858706-4e3f-481b-a3f6-6dc7e9a68b1c.png)
![Teams](https://user-images.githubusercontent.com/47565550/153858241-e664846b-6121-4034-970b-44e97cf8c0c7.png)

**Comment by wobba** [comment]
I suggest you test in Teams via a browser and look at the network calls to figure out what might be happening (or not happening).

**Comment by SPNomad** [comment]
Maybe a cache issue... recreating the page resolves the problem.

Conclusion : updating to 4.5.4 resolving my display issue.

Thanks everybody!
Damien
