### ISSUE TITLE
Search randomly returns "No Results" searching list content

### ISSUE THREAD

**Issue by melkinsco** [microsoft-search/pnp-modern-search#1833]
**Version used**
3.23

**Describe the bug**
I've created a search page for a Glossary for a GCC client. The search page searches a number of lists on the same site with four properties:  Preferred Term (text), Alternate Terms (Text), Term Definition (multi-line text), and URL.  Each of the attributes is tied to a managed property and the search returns results, most of the time.  Sometimes, no results are returned.  A page refresh with the same term will produce results again.  The display template for the search results is Details List.

**Expected behavior**
Expecting the same search result when search is run using the same, known term rather than a random "no results" return.

**Screenshots**
![Search Result Pass](https://user-images.githubusercontent.com/49201599/153946341-9df9bc62-6f37-4d16-bc4a-e862c14d7cdb.png)
![Screenshot search fail](https://user-images.githubusercontent.com/49201599/153946363-3f8b69d5-232a-4168-acaa-c1c82d249914.png)

**Desktop (please complete the following information):**
Browser:  Edge current.
Windows 11 pc

**Additional context**
Microsoft Lists using a content type for common capture of content.  Currently, all lists are on the same site.  Looking to deploy more broadly if this works.  GCC client so Acronyms are not available and wanted to be more accessible to broader user community to submit terms.

**Comment by wobba** [comment]
You need to provide network traces to figure out why you are getting no results. When you search, what does the query request look like, and what does the response look like? I cannot repro with a simple setup in GCC myself.

**Comment by melkinsco** [comment]
Thanks!  I'll pull the config and get it added.  I'll also see about getting the network trace as well.
