### ISSUE TITLE
RefinementToken with Range Operation won't work  in Search Filter Webpart (SharePoint Search Service)

### ISSUE THREAD

**Issue by wuxiaojun514** [microsoft-search/pnp-modern-search#1835]
**Version used**
4.5.4 (4.5.3 doesn't have this kind of issue)

**Describe the bug**
We have a date filter using checkbox template which will generate range operation in refinement token to fitler the date. e.g.  **range(2013-09-21T00:00:00Z, 2013-09-22T00:00:00Z)** (You can find the same refinement token example in  [Query Refinement in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/query-refinement-in-sharepoint#table-3-format-and-contents-of-refinement-data))

This kind of refinement token works in 4.5.3. But I find it doesn't work when we upgrade to 4.5.4
When I debugged the code, I found it will add quotes to this range refinement token in "DataFilterHelper.ts" with [Item selection and tokens improvements #1692](https://github.com/microsoft-search/pnp-modern-search/pull/1692) pull request
![image](https://user-images.githubusercontent.com/29603048/154025777-d5e6c9e2-0275-4a46-a303-a8d3d110df5d.png)

It will generate the refinement filters like **Created:"range(2020-01-01T00:00:00.00Z, 2022-01-01T00:00:00.00Z)"**, while **Created:range(2020-01-01T00:00:00.00Z, 2022-01-01T00:00:00.00Z)**(without quotes) is the correct value. You can use SharePoint Search Query tool to test it.

If I remove the quotes in "DataFilterHelper.ts", range refinement token will work.
I think we can add a check, if it uses **range** operation, then skip adding the quotes.

**To Reproduce**
1. Create PnP Filter Webpart, Filter field uses "Created", Template choose "Checkbox"
![image](https://user-images.githubusercontent.com/29603048/154038296-8f6c4b19-95a4-43c0-ba5f-206e71a35dc3.png)
2. It will show the filter like this screenshot
![image](https://user-images.githubusercontent.com/29603048/154038810-c0bb2fb2-a427-4611-8920-dd408e55863f.png)
3. Choose the filter, then it will return empty due to invalid range refinement token
![image](https://user-images.githubusercontent.com/29603048/154038964-e281cdab-1852-45bb-9bcf-5d79d2806f95.png)

``

**Comment by wobba** [comment]
Feel free to PR a fix :)

**Comment by FranckyC** [comment]
Hi @wuxiaojun514, thanks for flagging this issue. This will be updated in the next release

**Comment by FranckyC** [comment]
Fixed by #1836.

**Comment by wuxiaojun514** [comment]
Thank You @FranckyC
