### ISSUE TITLE
Managed property not visibli in 

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#184]
**Version used**
3.11.1

**Describe the bug**
Default managed property (RefinableDate00) mapped to a crawled property doesn't show in template "manage columns" picker. Another one does show but content isn't rendered

**To Reproduce**
1. Map a crawled property to a predefined managed property (eg RefinableDate00)
2. Reindex list and wait a while
3. Edit search results web part and add new column to template
4. Try to find new managed property in list

**Expected behavior**
Should be able to select the managed property to be added to the results template and values in column should get rendered

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**

**Comment by wobba** [comment]
We don't control 100% the properties being returned in the list. Just type it in manually instead. Enter the field, go to the end of it and type `,RefinableDate00`.

**Comment by webbrewer** [comment]
I tried your suggestion and still not seeing the managed property values getting rendered.  I tried a few other managed properties and none get rendered. Not sure what I'm doing wrong?

**Comment by wobba** [comment]
Can you use the search query tool or similar to ensure you have values in the property?

**Comment by webbrewer** [comment]
My bad - I "assumed" the managed properties for the fields had been included in the "selected properties" which they weren't. Once added, it works as expected and I can add any managed property. Thanks for the quick responses and the great work you guys have done!
