### ISSUE TITLE
How to connect the webpart search filter to search result

### ISSUE THREAD

**Issue by tocri** [microsoft-search/pnp-modern-search#1842]
Hi,

I have been creatin g a SP and i added the webparts **serch filters** and **search results**
On the spfx search filters , i setup the connection to the webpart search results. 

On the other webpart, i check **connect to a filers webpart** and i select the search filter web part on the dropdown list.
But even with these parameters, no filters are showed up on the spfx and i don't know why.

I'm using the last version of  php-modernn-search-parts-v4 (4.5.5.0) an dearch extensibilt demo 4.0.0.0 bu i don't know if this last one is very important ?

Thanks for your reply

**Comment by FranckyC** [comment]
Hi @tocri, maybe this should help https://microsoft-search.github.io/pnp-modern-search/usage/search-filters/#configuration?

**Comment by tocri** [comment]
It's what i did.
I have added some screenshot 

[Screenshot](https://1drv.ms/u/s!AoEBGFd4Hq6Iw-9UaNVeYfTksMHHxw?e=0YyCl5)

Could you have a look, if you want ?

**Comment by FranckyC** [comment]
Ok but what filters did you configure in the Search Filters Web Part? You need to use `Refinable` properties from the search schema to get it work.

**Comment by tocri** [comment]
Oh my god. I'm so stupid sometimes. I forgot refinable. I'm in love with these pnp webparts. I rediscover SP Search.
Maybe i'm wrong ? But are you from brittany :-) ? I saw the triskell on your website.
I also saw your class. Little expensive currently for me. I would like to buy it next month.

**Comment by FranckyC** [comment]
Haha it happens sometimes ;). BTW, I'm French from Brittany (but live in Canada). Thank you for your support.
