### ISSUE TITLE
PnP Modern Search Webpart v3 not registering built-on handlebars helpers

### ISSUE THREAD

**Issue by lonestarcz** [microsoft-search/pnp-modern-search#1844]
**Version used**
Ex: 3.23

**Describe the bug**
If I navigate to a page with search results webpart - with custom template (connected to a search box and search filter webparts)  from the SPO navigation the filter contains correct items, but the search result webpart shows nothing. In browser console I found an error with message message: Missing helper: "eq", Missing helper: "times" or Missing helper: "split". After the page refresh everything works as expected. This happens only if the page is opened from navigation (even opening the page in new tab works fine). So it looks like the built-in handlebars are not registered, any help please?

**To Reproduce**
Unfortunately this issue occurs in our PROD environment and I cannot reproduce in other environments.

**Expected behavior**
It should display the results even on the first load.

**Screenshots**
![image](https://user-images.githubusercontent.com/54359174/154471461-66441ebe-8dc6-4e46-8681-b6ff5057c589.png)
on of the error

**Desktop (please complete the following information):**
 - Edge

**Comment by kasperbolarsen** [comment]
Since v3 is not being updated anymore this case is closed
