### ISSUE TITLE
File preview issue mostly with the Excel file types

### ISSUE THREAD

**Issue by sumitdeyonline** [microsoft-search/pnp-modern-search#1849]
### Check existing issues before logging new ones
We are using the latest version(current dev version)

**Version used**
Current dev version

**Describe the bug**
When a search contains results that return results with either a file with XLSM or XLSB, it will either display the grey default image(
![image](https://user-images.githubusercontent.com/23446009/154595954-af1cdf34-8381-421f-b690-ebbbd49797c7.png))
 or will contain no preview at all. When the default image appears, clicking it will bring up the file in excel preview. A search on our site using ‘XLSB’ returns mixed results of expected previews and a default icon. A search on our site using ‘XLSM’ returns no previews.

**To Reproduce**
1. Go to Sharepoint site
2. Type "xlsb' or 'xlsm' in the text box.
3. Get the result of the query
4. Some files have a preview image, others the default images are showing for file extension(.xlxb). There are no preview images is showing for the file extension(.xlxm)

**Expected behavior**
All preview images would be shown on the search result.

**Screenshots**
 Some files have a preview image, others the default images are showing for file extension(.xlxb)
![image](https://user-images.githubusercontent.com/23446009/154596926-d6aacb11-1ed2-451b-a621-b52e878be2ff.png)

No Preview for file extension(.xlxm)

![image](https://user-images.githubusercontent.com/23446009/154597080-87c3f865-cebd-4392-8cfa-44cbdaea9f5c.png)

**Desktop (please complete the following information):**
Chrome, Edge

**Comment by FranckyC** [comment]
Hi @sumitdeyonline, this is unfortunately a known issue wht Excel files and we can't do much about it :/

https://github.com/microsoft-search/pnp-modern-search/issues/283#issuecomment-632908043
