### ISSUE TITLE
Managed property not visible in "manage columns" template list

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#185]
**Version used**
3.11.1

**Describe the bug**
Default managed property (RefinableDate00) mapped to a crawled property doesn't show in template "manage columns" picker. Another one does show but content isn't rendered

**To Reproduce**
1. Map a crawled property to a predefined managed property (eg RefinableDate00)
2. Reindex list and wait a while
3. Edit search results web part and add new column to template
4. Try to find new managed property in list

**Expected behavior**
Should be able to select the managed property to be added to the results template and values in column should get rendered

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**

**Comment by wobba** [comment]
Dupliate of #184
