### ISSUE TITLE
Develop branch from Feb 16, 2022 throws errors when deployed. Failed to load component "544c1372-77ae-40a0-9095-805ae2a0d5e9" (pnpSearchVerticalsWebPart). Original error: Failed to load URL...

### ISSUE THREAD

**Issue by Forest-runklebc** [microsoft-search/pnp-modern-search#1852]
Found some issues with SearchBox not loading, but none for SearchVerticalWebPart

**Version used**
4.5 develop branch from Feb 16, 2022.

**Describe the bug**
Deploying the current dev branch to a sharepoint site results in the following errors:

Failed to load component "544c1372-77ae-40a0-9095-805ae2a0d5e9" (pnpSearchVerticalsWebPart). Original error: Failed to load URL...

**To Reproduce**
1. Clone the develop repo from Feb 16, 2022. 
2. Successfully build search-parts with the commands:
gulp clean --ship
gulp build --ship
gulp bundle --ship
gulp package-solution --ship
(See build logs at bottom of issue)

3. Navigate to sharepoint\solution\pnp-modern-search-parts-v4.sppkg
4. Upload the file from step 3 to app catalog.
5. See that the app catalog displays that the .sppkg is deployed with no errors.
6. Go to sharepoint site and see that all search parts are throwing the error in the screenshot.

**Expected behavior**
.sppkg should successfully build and not throw any errors when uploaded/being used on sharepoint site.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/5815376/154707196-4caa0ee2-a257-44ff-83c4-cef088abced3.PNG)

**Desktop (please complete the following information):**
 - Browser: Chrome/Windows 10

**Additional context**

Build logs from step 2 of "steps to reproduce". Too many characters to post together.

https://pastebin.com/3fLEv0Cu All logs.

PS C:\Users\runkl\Desktop\pnp dev branch\pnp-modern-search-develop\search-parts> gulp clean --ship
Build target: SHIP
[17:53:25] Using gulpfile ~\Desktop\pnp dev branch\pnp-modern-search-develop\search-parts\gulpfile.js
....
PS C:\Users\runkl\Desktop\pnp dev branch\pnp-modern-search-develop\search-parts> gulp bundle --ship
Build target: SHIP
[17:53:51] Using gulpfile ~\Desktop\pnp dev branch\pnp-modern-search-develop\search-parts\gulpfile.js
....
PS C:\Users\runkl\Desktop\pnp dev branch\pnp-modern-search-develop\search-parts> gulp package-solution --ship
Build target: SHIP
[17:55:04] Using gulpfile ~\Desktop\pnp dev branch\pnp-modern-search-develop\search-parts\gulpfile.js
....
PS C:\Users\runkl\Desktop\pnp dev branch\pnp-modern-search-develop\search-parts> gulp package-solution --ship
Build target: SHIP
[17:55:04] Using gulpfile ~\Desktop\pnp dev branch\pnp-modern-search-develop\search-parts\gulpfile.js

**Comment by FranckyC** [comment]
Hi @Forest-runklebc, do you still have this issue?
