### ISSUE TITLE
Search Result Pagination - last numeric value blank on first visit, populates on subsequent

### ISSUE THREAD

**Issue by jessicastoner** [microsoft-search/pnp-modern-search#1853]
**Version used**
4.5.3

**Describe the bug**
Using PnP Search Results web part, retrieves results that appear across multiple pages - show paging is on, and navigation buttons enabled.  When the user clicks on the last numeric value the first time, the page shows no results.  If navigating away (e.g. to another page or through the arrows), and then back to the final page, on the second and subsequent clicks the page populates.

**To Reproduce**
1. Navigate to page with PnP Search web part 
2. Scroll to bottom of list, and see that there are several pages of results
3. Click on the last numeric value -- this is where the issue occurs 
4. Click away to another numeric value -- results return
5. Click back to the final numeric value -- results that did not appear in step 3 now are visible

Desktop (please complete the following information):
**Browser**
Edge, Chrome

**Comment by wobba** [comment]
I cannot repro. Can you compare the JSON request for step 3 vs. step 5 when looking at the request in the network tab in the debug panel of your browser?

**Comment by FranckyC** [comment]
Hi @jessicastoner, do you still have the issue?
