### ISSUE TITLE
Handlebars Date Add or Subtract

### ISSUE THREAD

**Issue by kachihro** [microsoft-search/pnp-modern-search#1856]
**Describe the bug**
Within the Handlebars template for PEOPLE RESULTS, I'm wanting to show "how many days" since a user was created.
Eg..  Current Date - "Created" (from search results).

But - none of the Handlebars expressions are working ;
{{moment (getDate Created) subtract="days" amount="7" format="DD/MM/YYYY"}}
{{moment (getDate Created) subtract="365" subtractparam="d" utc=true}}

**To Reproduce**
Within the Search Results webpart, include an expession as above.
Eg.  TITLE field - to include {{ expression }}

**Expected behavior**
Can calculate the number of days - using ADD or SUBTRACT - with {{moment}} handlebars expressions

**Comment by FranckyC** [comment]
As far as I can see, you can't really do that with available helpers. If you are referring to this helper https://www.npmjs.com/package/handlebars-helper-moment, it is not included in the solution.

You can still write your own Handlebars helper with the extensibility as a workaround https://microsoft-search.github.io/pnp-modern-search/extensibility/handlebars_customizations/.

**Comment by kachihro** [comment]
OK - thanks - I'll check that out...
