### ISSUE TITLE
When user has an apostrophe (') in their email address. The people search not able to bring back user information 

### ISSUE THREAD

**Issue by meklulose** [microsoft-search/pnp-modern-search#1858]
### Check existing issues before logging new ones
If you are not using the latest version, triage your issue with the latest version before logging as we won't provide patches to older versions.

### Issues related to data mapping, e.g. SharePoint columns to crawled properties to managed properties should be asked in the discussion section.

**For any question regarding Web Parts usage, please use the ["Discussions"](https://github.com/microsoft-search/pnp-modern-search/discussions) tab instead of creating a new issue.**.

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
Ex: 4.4.1

**Describe the bug**
I have noticed that the persona card doesn't work on a user because they have an apostrophe (') in their username. For example when username is JohnO'real@test.onmicrosoft.com, the persona card is not displaying as it is trying to find mgt-person user-id= "real@test.onmicrosoft.com". 

**To Reproduce**
1. Create a user with an apostrophe in their email
2. Set up people search with show the persona card
3. Search *
4. The user will be display as following 
![image](https://user-images.githubusercontent.com/81180944/155003134-28d4ab44-4d0a-45c0-b52e-7f62ac804d1d.png)

**Expected behavior**
As an apostrophe is a valid symbol allowed by M365 I should be able to see the persona card when I hover over the user 

**Desktop (please complete the following information):**
 - Browser:  chrome, edge

**Comment by FranckyC** [comment]
Hi @meklulose, because you are not using the latest version, change the slot value for `PersonQuery` to `AADObjectID`:

![image](https://user-images.githubusercontent.com/5659122/155338532-99eb6968-9746-4885-bbbc-f83e099b980d.png)

**Comment by meklulose** [comment]
Hi @FranckyC  thanks for the response. I made the change but the change has made the show persona card stop working. 
![image](https://user-images.githubusercontent.com/81180944/155348002-0a6f1933-93f8-4fdb-aae8-9f6d8e40103d.png)
 
![image](https://user-images.githubusercontent.com/81180944/155348054-f553eee4-1f7a-4b4e-a301-324ea96490ac.png)

**Comment by FranckyC** [comment]
Ok can you check your People layout template and replace existing MGT code snippet with this one:

```html
 <mgt-person user-id="{{getUserEmail (slot item @root.slots.PersonQuery)}}" person-card="hover">
    <template>
        <pnp-persona 
            data-image-url="\{{personImage}}" 
            data-fields-configuration="{{JSONstringify @root.properties.layoutProperties.peopleFields}}" 
            data-item="{{JSONstringify item}}" 
            data-persona-size="{{@root.properties.layoutProperties.personaSize}}"
            data-theme-variant="{{JSONstringify @root.theme}}"
            data-instance-id="{{@root.instanceId}}"
            data-context="{{JSONstringify @root}}">
        </pnp-persona>
    </template>
    <template data-type="person-card">
        <mgt-person-card inherit-details>
        </mgt-person-card>
    </template>
</mgt-person>
```

**Comment by FranckyC** [comment]
The important part is the `user-id="{{getUserEmail (slot item @root.slots.PersonQuery)}}"`
