### ISSUE TITLE
Custom Verticals in Modern Search

### ISSUE THREAD

**Issue by srinivasamyneni** [microsoft-search/pnp-modern-search#186]
I'm looking to have custom verticals and which need to pull the results from 3rd party Search Index using API calls?

is this possible with this PnP Solution?

**Comment by wobba** [comment]
Not with the current code. SharePoint only.

**Comment by srinivasamyneni** [comment]
@wobba, is it possible to add this feature by customizing the existing PnP solution? are it only allow existing verticals in office 365 (i,e, All, Files, Sites, People, News)?

**Comment by wobba** [comment]
The webparts are open source and you could modify as needed. Not saying it's easy. Also, PnP webparts have no tie-in to oob search and verticals there, and web parts can not be added to the oob search page.
