### ISSUE TITLE
Sortable Properties are missing in v4

### ISSUE THREAD

**Issue by PavelBrokhman** [microsoft-search/pnp-modern-search#1862]
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/1854

<div type='discussions-op-text'>

<sup>Originally posted by **PavelBrokhman** February 18, 2022</sup>
Please help me with the next case scenario:
When Search results is loading it would be sorted let's say by ColumnX.
After it is loaded I would like to sort by the ColumnY. It should sort all the results not only current page. 

In v3 I could do it by configuring Sortable Properties. 

How can I do the same in v4?</div>

**Comment by FranckyC** [comment]
Already answered in discussion.
