### ISSUE TITLE
Global Service Principal ID Error: Error: {}

### ISSUE THREAD

**Issue by stanlygoodspeed** [microsoft-search/pnp-modern-search#1863]
Hi, we are getting an error when adding an application to sharepoint. 

We get error "Could not retrieve Global Service Principal ID Error: Error: {}"

Moreover, the application works on the portal site itself without graph toolkit functions. We tried to issue all permissions on the Azure side, but the error does not go away. What could be the problem?

[https://wmpics.pics/di-CLUU.png](url)

**Comment by FranckyC** [comment]
Hi @stanlygoodspeed, can't see your screemshot. It is hard to tell what it could be. Seems to be an SPFx issue. Please post your issue here instead: https://github.com/SharePoint/sp-dev-docs/issues
