### ISSUE TITLE
Use multilingual terms (managed metadata) as refiners

### ISSUE THREAD

**Issue by jbmueller0584** [microsoft-search/pnp-modern-search#1865]
Hi guys,

first of all, i checked the previous issues but i have not found a proper one for my scenario.

Is it possible to use multilingual terms (definied within the term store)

![2022-02-23 10_24_52-Terminologiespeicher-Verwaltungstool und 5 weitere Seiten - JBM Admin – Microsof](https://user-images.githubusercontent.com/94067337/155297122-7d37f945-3124-49af-8e99-fb280edde7db.png)

as refiners

![2022-02-23 10_18_23-Translate into German_ Studiensuche und 5 weitere Seiten - JBM Admin – Microsoft](https://user-images.githubusercontent.com/94067337/155297044-90bc74b2-2f26-4de9-ad7f-979eb5a6377c.png)

which means that when we have a multilingual comm.-site and appropriate browser language that the values will be displayed in the specific language for the users?

Best regards,
Joerg

**Comment by FranckyC** [comment]
Hi @jbmueller0584, you must enable the flag "Enable localization" in the search results Web Part and configure the managed properties accordingly. See https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/

> If enabled, the Web Part will try to translate the taxonomy term IDs found in result item properties and refinement values to their corresponding label according to the curent UI language. To get it work, you must map a new refinable managed property associated with ows_taxId_ crawled property and turn this toggle 'on': If enabled and depending on how many items are currently being displayed, this could slightly decrease the loading performance. To use translated values in your template, you must use the 'Auto + <property_name>' property format instead of the original property name. For instance, to use translated values of the 'owstaxidmetadataalltagsinfo' property, you must use the 'Autoowstaxidmetadataalltagsinfo' auto created property.

**Comment by jbmueller0584** [comment]
Thank you so much @FranckyC ! ! !
