### ISSUE TITLE
pnp modern search web parts issue

### ISSUE THREAD

**Issue by westronman** [microsoft-search/pnp-modern-search#1868]
Hi I have deployed v4 of the pnp modern search web parts package. All was working fine when using the option to show the persona card on hover when displaying People Results. However it has just stopped working. Tried deleting the web parts and re-adding on a different page, even deleted the app ad re-added it but still the persona card will not display on hover. Any ideas as to what has caused this? Like I said it was working yesterday but not today!!

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
Ex: 4.5

**Describe the bug**
A clear and concise description of what the bug is. Keep questions and bugs related to the web parts. If the issue relates to KQL or question around crawled and managed properties please use [Microsoft TechCommunity](https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev). Which means, if you experience the same behavior in classic web parts, then it's not an issue with PnP Modern Search 😉

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Attached

**Desktop (please complete the following information):**
 - Browser [Edge]

**Additional context**
![image](https://user-images.githubusercontent.com/74354988/155545595-ce937762-5eda-434f-ac96-ef0755682eb2.png)

**Comment by FranckyC** [comment]
You can check if the Graph API permissions are still approved in the SharePoint admin center. Alsom a good way to check if that would be the issue is to open the network tab in the browser console and see if there is any HTTP 403 errors.

**Comment by wobba** [comment]
If it suddenly stopped working you should look in the debug console of the browser for errors and like @FranckyC says, errors on network requests.

**Comment by FranckyC** [comment]
Hi @westronman, do you still have the issue?
