### ISSUE TITLE
Search box & Result not working after refresh the page

### ISSUE THREAD

**Issue by lam01007** [microsoft-search/pnp-modern-search#188]
**Version used**
3.7

**Describe the bug**
No Search Result with Search Box

**To Reproduce**
1. Add Search Box & Search Result web part;
2. Edit the properties of Search Result web part, and connect to the Search Box:
![image](https://user-images.githubusercontent.com/10590442/79414120-65763600-7fdc-11ea-99bb-747f4628e1ab.png)
3. Save it as draft or Publish the page.
4. Press F5 to refresh the page.
5. Enter search term in search box and click search icon or press "Enter"
6. No response, and without any error on console

**Expected behavior**
Search Result properly show, depend on the search term.

**Desktop (please complete the following information):**
 - Chrome, Edge

**Additional context**

The function is work fine on yesterday. and I had tracing on the network tab in F12 of Chrome, and compare with the 2 cases:

After Save as Draft:
![image](https://user-images.githubusercontent.com/10590442/79414334-ee8d6d00-7fdc-11ea-8fe0-8778f2ef9d69.png)

Before Save as Draft:
![image](https://user-images.githubusercontent.com/10590442/79414521-71aec300-7fdd-11ea-929d-cfb689981a2a.png)

There are missing the "postquery" call after save the page.

And I got the similar issue on site search, not sure the issue is related to SharePoint Online or not.
https://techcommunity.microsoft.com/t5/sharepoint/error-in-site-search/m-p/1311493#M40167 

any idea?

**Comment by wobba** [comment]
You should try v3.10 https://github.com/microsoft-search/pnp-modern-search/releases/tag/3.10.0 and see if it has the error. v3.11 might have braking changes for you, so testing 3.10 is probably the best approach.

**Comment by lam01007** [comment]
> You should try v3.10 https://github.com/microsoft-search/pnp-modern-search/releases/tag/3.10.0 and see if it has the error. v3.11 might have braking changes for you, so testing 3.10 is probably the best approach.

Thanks @wobba , the issue solved.
