### ISSUE TITLE
Search Verticals Not applying result source value

### ISSUE THREAD

**Issue by jimmywim** [microsoft-search/pnp-modern-search#1883]
**Version used**
4.5.3

**Describe the bug**
Configuring Search Verticals with result source IDs as the "Tab Value" doesn't result in the search results using that result source.

**To Reproduce**
- Add Search Verticals web part
- Add a Search Vertical to the table, any display name in the Tab name, and a valid, custom Result Source ID in the Tab Value column
- Add Search Results - do NOT configure a Result Source
- Connect the Search Results web part to the Verticals web part

Observe that clicking the vertical tab does not modify the search results. 

**Expected behavior**
Search results would be restricted to those in the result source

**Desktop:**
 - Chrome

**Additional context**
If you use Network inspector to look at the requests to postquery, you'll see the "SourceId" property is never set in the outgoing queries.

The token `{verticals.value}` is not allowed to be set in the Search Result's `Result Source Id / Scope|Name` property.

This is either a bug or a complete deviation from expected functionality carried over from V3, where in V3's docs it states:

```
When you set a query template or a result source id for a vertical, these override the ones in the connected search results
```

If this is expected behaviour, then documentation may require a note of the difference in behaviour from V3, as well as clarifying this at the top of the `Configure search verticals` collection editor, where it currently states `Add a new vertical to allow users to search in a predefined scope or data source.`. The words "scope" and "source" here suggests use of Result Sources in the generated search queries.

**Comment by FranckyC** [comment]
Hi @jimmywim, this is the expected behavior. Verticals behavior are quite different from v3 to v4. I'll update the documentation to be more clear

**Comment by jimmywim** [comment]
@FranckyC Cheers - just had one of my content editors ask about this so I'll feed back.

Any plans to replicate this behaviour over to V4?

**Comment by FranckyC** [comment]
Short answer: no. The v4 behavior is way more flexible than v3.

**Comment by wobba** [comment]
@jimmywim we have scenario docs coming for this https://github.com/microsoft-search/pnp-modern-search/blob/main/docs/scenarios/Create-a-search-page-with-verticals-within-the-same-page.md
