### ISSUE TITLE
In handlebars templates - expose current logged in user

### ISSUE THREAD

**Issue by Georg-Trixl** [microsoft-search/pnp-modern-search#189]
**Description**
My goal is to highlight the items which are edited of created by "me"

**Solution** 
have a handlebars helper - that exposes the current logged in user. So that conditional formating can be done based on the current logged in user.

**Alternative**
1.  if the current logged in user is already in handlebars templating, the describe in the documentation how to achieve that
-- or --
2. include user created/edited documents highlighting as switch in the results webpart.

**Additional context**
This can users help to identify their own data and can handle custom data, that delve doesn't handle right.
![Git-sample](https://user-images.githubusercontent.com/62948158/79443175-c94b2f80-7fd9-11ea-95da-01e8ea7a9e7b.png)

**Comment by wobba** [comment]
We could expose the SPFx context variables probably as a helper.

**Comment by Georg-Trixl** [comment]
@wobba That would be pretty cool, can you image, when such a solution would be available a released version?

**Comment by wobba** [comment]
@Georg-Trixl when someone has the time and creates a PR for it, so I have no idea. @FranckyC does most of the dev, and the focus now has been on securing the templating and refactoring.

**Comment by Georg-Trixl** [comment]
@wobba and @FranckyC  would a money donation help to speed up the feature requests of my company? :-D 
Because we also wan't some other cool features in near future  ;-)

**Comment by wobba** [comment]
Now in the dev branch. Was almost too easy to add. Enjoy 🙂

Setting | Description
-------|----
`{{getPageContext "property"}}` | Retrieve SPFx page context data to show in the template. See [https://docs.microsoft.com/en-us/javascript/api/sp-page-context/pagecontext](https://docs.microsoft.com/en-us/javascript/api/sp-page-context/pagecontext) for possible values. Example `{{getPageContext "user.displayName"}}` `{{getPageContext "cultureInfo.currentUICultureName"}}`.<br>**Note: Casing matches the object model.**

**Comment by MakingThingsWorkToronto** [comment]
Awesome suggestion @Georg-Trixl & Great work @wobba! This will come in handy big time!

**Comment by Georg-Trixl** [comment]
Awesome work! Thank you very much :-D
