### ISSUE TITLE
Update extensibility documentation to include SPFx version

### ISSUE THREAD

**Issue by jhholm** [microsoft-search/pnp-modern-search#1893]
**Problem**
I stumbled upon a versioning conflict on a customer project last month. My other solutions were using SPFx 1.13.1 and I created a library component with the same version to create custom modern search layouts. I followed the documentation and used stuff that worked before. I couldn't successfully build the solution anymore. I think there are breaking changes from 1.12 to 1.13 packages that causes this issue. Thus for now I need to create modern search extensions in SPFx 1.12.1. Currently SPFx 1.14 is already the default one provided to developers.

**Solution**
I guess just adding a simple note to the extensibility documentation to inform you probably should use the same version of SPFx in your extensibility library as your installed version of PnP Modern Search. I guess an overkill solution would be to create a compatibility matrix with SPFx / modern-search / modern-search-extensibility compatible versions.

I can create a pull request for the documentation. Simple note or a compatibility matrix?

**Comment by wobba** [comment]
Don't see why the version should matter.... if you create a lib component from scratch using 1.13.1 or 1.14, why wouldn't that build if you have the interfaces etc?

We will update to a later SPFx at some point, but I hit a bundle increase issue I haven't had time to properly investigate yet #1455

**Comment by jhholm** [comment]
```
[tsc] Types of property 'defaultCreator' are incompatible.
```

That's the first error I'm getting while building the example template with 1.13.1. I think the sp-core-library has some breaking changes with the service pattern.

**Comment by jhholm** [comment]
So technically it breaks either on registering a suggestion provider, or if you are using **this._serviceScope.consume** in your custom web component.

**Comment by wobba** [comment]
Would be useful is you could share your steps in creating a, I assume, web component(?). I'd like to repro it so I better understand it and to see what the best solution to fix it is.

**Comment by jhholm** [comment]
I'll create a simple repro from the search extensibility sample, with a component that uses the pagecontext service. I'll also test in 1.14.0 as well.

**Comment by FranckyC** [comment]
Fixed with #1952. See https://microsoft-search.github.io/pnp-modern-search/extensibility/#prerequistes
