### ISSUE TITLE
Getting error [HTTP]:500 - [CorrelationId]:572926a0-d0ba-3000-a093-33556b83e8aa [Version]:16.0.0.22216 when searching with two digits seperated by "." e.g. 1.7

### ISSUE THREAD

**Issue by Namrata99sah** [microsoft-search/pnp-modern-search#1894]
Version :  4.5.3.0

Search with any 2 digit number separated with decimal, e.g. 1.7, 3.5 the Result webpart is throwing below error.

![image](https://user-images.githubusercontent.com/62616681/156597346-e932210f-faad-46e9-baf0-91df2cf13871.png)

Observations - 
1. Changing the Result Template to "ItemsMatchingTag" is resolving the error from "LocalSharePointResults".
2. Search with quoted text "1.7", "3.5" is returning correct results.
3. The same template is working in other site collection with same settings. For the errored Site "&scope=site" is getting appended in the URL.
4. Searching with 100.1 or three digit is working fine.

Below is the Network Trace:
{"request":{"__metadata":{"type":"Microsoft.Office.Server.Search.REST.SearchRequest"},"ClientType":"PnPModernSearch","Properties":{"results":[{"Name":"EnableDynamicGroups","Value":{"BoolVal":true,"QueryPropertyValueTypeIndex":3}},{"Name":"EnableMultiGeoSearch","Value":{"BoolVal":true,"QueryPropertyValueTypeIndex":3}},{"Name":"ClientFunction","Value":{"StrVal":"PnPSearchWebPart","QueryPropertyValueTypeIndex":1}},{"Name":"ListId","Value":{"StrVal":"e956a8c2-c00c-4fec-a3a4-72c2d1f739b3","QueryPropertyValueTypeIndex":1}},{"Name":"ListItemId","Value":{"StrVal":"2573","QueryPropertyValueTypeIndex":1}}]},"Querytext":"1.2","EnableQueryRules":true,"QueryTemplate":"1.2 Path:{Site} AND IsContainer:\"false\" AND Archived<>\"True\"  1.2","SourceId":"8413cd39-2156-4e00-b54d-11efd9abdb89","EnableNicknames":false,"EnablePhonetic":false,"Culture":1033,"TimeZoneId":93,"Refiners":"RefinableString01,RefinableString102,RefinableString105,RefinableString04,RefinableDate00(discretize=manual/2021-03-03T15:37:08.352Z/2021-12-03T15:37:08.352Z/2022-02-03T15:37:08.352Z/2022-02-24T15:37:08.352Z/2022-03-02T15:37:08.352Z/2022-03-03T15:38:08.352Z), LastModifiedTime(discretize=manual/2021-03-03T15:37:08.352Z/2021-12-03T15:37:08.352Z/2022-02-03T15:37:08.352Z/2022-02-24T15:37:08.352Z/2022-03-02T15:37:08.352Z/2022-03-03T15:38:08.352Z),FileType","RefinementFilters":{"results":[]},"RowLimit":10,"StartRow":0,"TrimDuplicates":false,"SortList":{"results":[{"Property":"Created","Direction":0},{"Property":"Size","Direction":1}]},"SelectProperties":{"results":["AuthorOWSUSER","contentclass","ContentType","ContentTypeId","Created","CreatedBy","DefaultEncodingURL","FileType","HitHighlightedSummary","IsContainer","JobTitle","LastModifiedTime","NormListID","NormSiteID","NormUniqueID","owstaxidmetadataalltagsinfo","PageURL","Path","PolicyPageURL","RefinableDate00","RefinableString00","RefinableString01","RefinableString02","RefinableString03","RefinableString04","RefinableString05","RefinableString06","RefinableString07","RefinableString08","RefinableString09","RefinableString10","RefinableString100","RefinableString101","RefinableString102","RefinableString103","RefinableString104","RefinableString105","RelatedGroupId","ServerRedirectedEmbedURL","ServerRedirectedPreviewURL","ServerRedirectedURL","SiteLogo","SiteTitle","SPSiteUrl","Title","UniqueID","UserName","WorkPhone"]},"HitHighlightedProperties":{"results":[]},"ReorderingRules":{"results":[]}}}

**Comment by wobba** [comment]
Looking at the request it seems to have quotes around true/false and spaces as well in the query template which could breaks the JSON - assuming you pasted correctly above. Can you share some more of your setup?

```
 "QueryTemplate": "1.2 Path:{Site} AND IsContainer:" false " AND Archived<>" True " 1.2",
```

That said, there are numerous other 500 issues reported which all stem from the backend. Can you try to turn off query rules?

**Comment by Namrata99sah** [comment]
I disabled Query rules and the error is gone..How to find which rule is creating this error? @wobba

**Comment by wobba** [comment]
It's not one rule in particular, but an issue with some queries when query rules are triggering. I propose you open a support case with Microsoft. If you can repro it using classic web parts, it's easier to get traction on the issue (and it's reported by others as well).

**Comment by Namrata99sah** [comment]
@wobba I searched the specific terms in "https://contoso.sharepoint.com/sites/foo/_layouts/15/osssearchresults.aspx" classic search but it is working fine.
Also, in the same site I created another page and added the search webparts, if I add the Search box + Search results with query rules enabled - it is working fine. But once I add the Filter webpart the same issue is happening.

**Comment by wobba** [comment]
@Namrata99sah don't reply to closes issues. Log separate ones for your exact case.

**Comment by AkiraSPO** [comment]
> @wobba I searched the specific terms in "https://contoso.sharepoint.com/sites/foo/_layouts/15/osssearchresults.aspx" classic search but it is working fine. Also, in the same site I created another page and added the search webparts, if I add the Search box + Search results with query rules enabled - it is working fine. But once I add the Filter webpart the same issue is happening.



> @wobba I searched the specific terms in "https://contoso.sharepoint.com/sites/foo/_layouts/15/osssearchresults.aspx" classic search but it is working fine. Also, in the same site I created another page and added the search webparts, if I add the Search box + Search results with query rules enabled - it is working fine. But once I add the Filter webpart the same issue is happening.

@Namrata99sah, I am facing a similar issue, any luck finding a solution?

**Comment by AkiraSPO** [comment]
> 

@Namrata99sah  any luck finding a solution or the reason at least? I have a similar issue and I have tried the same things as mentioned in this issue. Your inputs will be greatly appreciated.

**Comment by Namrata99sah** [comment]
@AkiraSPO - Created new result source and new replicated query rules were added to the new source then its working
