### ISSUE TITLE
Search results webpart disappeared in full page refresh

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#19]
https://github.com/SharePoint/sp-dev-solutions/issues/357

Seems to be related to the card rendering view - And I've been able to repro it, but no error message.

**Comment by mahmoudhamed** [comment]
Yep, I was using the Tiles/Card view

**Comment by wobba** [comment]
Have you experienced this @FranckyC ?

**Comment by FranckyC** [comment]
Resolved by #29 and 3.8.0 version.
