### ISSUE TITLE
Big Document library (1000) Pagination not working.

### ISSUE THREAD

**Issue by jscedunn1** [microsoft-search/pnp-modern-search#190]
I have set up the search according to the guidelines and pagination is not working. Is there another way I can use this web part. I have a document library of 1000, I have metadata tags that I use to filter, some of those bring back 100 to 600 results but I can only see up to 50. I also need a return of the all of the documents. Can I please have some help?

**Comment by wobba** [comment]
To list all documents in a large volume I suggest using PnP PowerShell.

`Invoke-PnPSearchQuery -Query "something" -All -RelevantResults`

As for not being able to paginate we need a bit more information on your setup in order to help troubleshooting.

**Comment by wobba** [comment]
We're adding an option to allow up to 500 per page which is the API limit. Beyond this you have to page or do custom code as we won't support more than the API limit per page, with internal paging.
