### ISSUE TITLE
ClientAuthError

### ISSUE THREAD

**Issue by jojocode77** [microsoft-search/pnp-modern-search#1905]
**Version used**
Ex: 4.5.3

**Describe the bug**
Using Edge browser, using the PnP Search Results web part which uses mgt components within the display template, occasionally the search results are not loaded with the following errors shown in the console

tygraph-pages-engine-application-customizer_afc55602589e0aea1fe3.js:2

tyGraph Pages Engine - error retrieving user profile from Microsoft Graph (no response or error returned) - Token renewal operation failed due to timeout.
trackException @ tygraph-pages-engine-application-customizer_afc55602589e0aea1fe3.js:2
tygraph-pages-engine-application-customizer_afc55602589e0aea1fe3.js:2 tyGraph Pages Engine - user info - true
chunk.vendors~msalImplicit_none_011fc447b4cfce590bd4.js:1

Uncaught (in promise) ClientAuthError: Token renewal operation failed due to timeout.
at t [as constructor] (res-1.cdn.office.net/files/sp-client/chunk.vendors~msalImplicit_none_011fc447b4cfce590bd4.js:1:108706)
at new t (res-1.cdn.office.net/files/sp-client/chunk.vendors~msalImplicit_none_011fc447b4cfce590bd4.js:1:109265)
at Function.t.createTokenRenewalTimeoutError (res-1.cdn.office.net/files/sp-client/chunk.vendors~msalImplicit_none_011fc447b4cfce590bd4.js:1:109746)
at res-1.cdn.office.net/files/sp-client/chunk.vendors~msalImplicit_none_011fc447b4cfce590bd4.js:1:141265

Opening the same page in Chrome works fine. Opening the same page in an InPrivate Edge window also works. But loading it correctly in other browsers or windows does not fix the issue with the original erroring window.

**To Reproduce**
I'm unable to reproduce the error consistently.

**Expected behavior**
Authentication should not fail.

**Desktop (please complete the following information):**
 - Browser Edge 99.0.1150.30

**Comment by FranckyC** [comment]
Hi @jojocode77, seems to be related to a 3rd party component, not PnP Modern Search sorry.
