### ISSUE TITLE
Passing through of query string parameters between Microsoft Searchbox and PnP Searchbox

### ISSUE THREAD

**Issue by VerlindenEAM** [microsoft-search/pnp-modern-search#1915]
**Version used**
4.5.2

**Describe the bug**
We have a large Hub site with over 400 connected sites, where we are using a custom results page with PnP Modern Search.
The custom results page has 7 verticals, seperate filters and results webpart per vertical and a PnP Searchbox.

When using the Microsoft Searchbox with keyword "test" the following URL parameters are created &q=test&k=test&scope=hub and the query keyword will be filled in the PnP Searchbox.
If you then change the keyword in the PnP Searchbox from "test" to "test2", the parameter is not changed but added in URL parameters &q=test2&q=test&k=test&scope=hub

This will result in refining the results in both "test" and "test2".

Using the clear searchbox cross only cleares the PnP Searchbox and URL parameter that was connected to it, but it doesn't clear the Microsoft Searchbox and other URL parameters with q= and k=

**To Reproduce**
1. Configure a custom results page with multiple verticals, results webparts and a PnP Searchbox.
2. Configure the PnP Searchbox to use a query string parameter with parameter 'q'.
3. Configure Microsoft Searchbox to the custom results page.
4. Type keyword 'test' in the Microsoft Searchbox
5. Type keyword 'test2' in the PnP Searchbox
6. See behavior

**Expected behavior**
Correct passing through of query string parameters between Microsoft Searchbox and PnP Searchbox

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**

**Comment by FranckyC** [comment]
Hi @VerlindenEAM, can you test with the latest version (4.6.1)? I can't repro. I get the 'q' parameter value replaced and not duplicated,

**Comment by tandrasi** [comment]
Hey, I'm using 4.6.1.0 and can confirm that this doesn't work for me. When using the Microsoft Searchbox, I get both **?q=test&k=test** appended to the URL, but the PnP Searchbox does not pick up the query string and doesn't trigger a search based on said query string. Was there a setting I haven't enabled or configured? Thanks!

**Comment by VerlindenEAM** [comment]
Hello @tandrasi q is used Modern SharePoint and k is used for OnPremise SharePoint if you have configured hybrid search.

@FranckyC, we will install 4.7 on our environment when it is available. I will test the passing through again and get back to you.

**Comment by tandrasi** [comment]
Thanks @VerlindenEAM and @wobba, I completely missed those settings! Works like a charm!
