### ISSUE TITLE
Hardcode refinable and sortable property lists

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#1916]
Hardcode the SharePoint provider property lists for sorting/filtering to avoid any github issues where people pick a property which shouldn't work for that scenario.

**Comment by FranckyC** [comment]
Done with https://github.com/microsoft-search/pnp-modern-search/pull/1931 with the sorting control. However, we do not list the `RefinableXX` ones. In this case, users have to enter the value manually (same for aliases).

**Comment by wobba** [comment]
@FranckyC I think we could list all Refinable ones as well, and leave input for alias.
