### ISSUE TITLE
Add Search Token {User.Audiences} 

### ISSUE THREAD

**Issue by JoelBVezina** [microsoft-search/pnp-modern-search#1919]
Been trying to apply audiencing on List items via PnP Search webpart. Even though modern audiencing doesn<t support lists, I was confident to be able to do this by leveraging the audiencing in PnP webpart.

Unfortunately, the audiencing doesn't seem to register at all for list items.

Another option would be to use the Audiences property  and add something like Audiences:{User.Audiences} in the KQL search query.

Unfortunately, the {User.Audiences} property isn't returning anything via the PnP webpart. It is a property that I would have expected to be able to get though.

See User properties in Query variables : https://docs.microsoft.com/en-us/sharepoint/technical-reference/query-variables

See User tokens in Pnp search doc :  https://microsoft-search.github.io/pnp-modern-search/usage/search-results/tokens/#user-tokens

Would it be possible to add User.Audiences in the list of user token parsable by the webpart? I'm open to discussion if required.

Thanks!

****EDIT*** Adding the issue template since this was originally logged as improvement request

**Version used**
Version: 4.5.3.0

**Describe the bug**
User.Audiences search token doesn't seem to return any value when used in PnP Search WP. This seems prevent the audiencing to not work with list items. Also not possible to extract value from token {User.Audiences} in KQL search query

**To Reproduce**
1. Create custom list 
2. Activate Modern audiencing
3. Create items and assign audiences 
4. Create Page with Pnp search result and query those items specifically
5. Activate Audiencing on Pnp search result webpart. No item with audience seems to be returned (issue 1)
6. Deactivate audiencing on PnP search result webpart
7. Add to KQL something like "AND Audiences:{User.Audiences}
8. Check in debug mode for the query. you should see "Audiences:" (issue 2)

**Expected behavior**
I'd like to know how to make the webpart work with audiencing and list items (issue 1). If not possible, I'd like to have access to {User.Audiences} token. 

**Screenshots**

**Desktop (please complete the following information):**
 Tested on Chrome

**Additional context**
See initial description above

**Comment by FranckyC** [comment]
@JoelBVezina  Can you please fill the issue template? We don't even know what version you are using...This token should be supported in the latest release.

**Comment by JoelBVezina** [comment]
Thank you @FranckyC. Initially posted as feature request so template was only description. 

I will look into the latest release. I must admit I was looking at the documentation and since there was no mention of this previously, didn't believe it would be corrected in betweem 4.3 and 4.5.4

**Comment by JoelBVezina** [comment]
Confirmed that updating to 4.5.4 does change behavior and has the {User.Audiences} token to Audiences:user-audience-place-holder-string in the query. This seems to be the expected value as this is the default value set to ModernAudienceAadObjectIds once we activate audiencing. 

Still doesn't work though. Unsure if we are expecting the audiencing to work with list item Content type at all. I didn't think it would impact though.

**Comment by wobba** [comment]
If you compare how the query looks with PnP web parts vs highlighted content web part when audiences are added, that should weed out any KQL issues at least.

**Comment by JoelBVezina** [comment]
> If you compare how the query looks with PnP web parts vs highlighted content web part when audiences are added, that should weed out any KQL issues at least.

You are right. As soon as I add "(ModernAudienceAadObjectIds:{User.Audiences} OR NOT IsAudienceTargeted:true)" which is the highlighted content query part related to audiencing enabled webpart, it doesn't work with list items, even on the highlighted content webpart. The behavior is the same for PnP Search result webpart. I must then just assume that audiencing and list items just isn't compatible. 

If you guys have an idea as to why, I'd be more then willing to investigate by myself afterward.

For now I'll close this issue as I believe it's not entirely related to the token but more to SPO not behaving how I was expecting audiencing wise.
