### ISSUE TITLE
Search in document names (question)

### ISSUE THREAD

**Issue by Tim2711** [microsoft-search/pnp-modern-search#193]
When i make a search for a document name the search is made in the summary of the document.
What i want is a priority for the document name. Is this possible?

**Comment by wobba** [comment]
Search searches multiple parts of a document, filename, title, content in the document, metadata columns in SharePoint etc. If you want to search only the filename use:

`Filename:(search terms)`

if you only want to search the title:

`Title:(search terms)`

if you want to search both:

`Filename:(search terms) OR Title:(search terms)`

**Comment by Tim2711** [comment]
Thank you Mikael,

In the search results settings i put this query:

{SearchTerms}
(Path:https://tennant.sharepoint.com/sites/
filename:(search terms)

i get to many results...i'm doing something wrong i think.

gtrz Tim
________________________________
Van: Mikael Svenson <notifications@github.com>
Verzonden: donderdag 16 april 2020 16:45
Aan: microsoft-search/pnp-modern-search <pnp-modern-search@noreply.github.com>
CC: Arnoud Dekker <a.dekker@innovam.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [microsoft-search/pnp-modern-search] Search in document names (question) (#193)


Search searches multiple parts of a document, filename, title, content in the document, metadata columns in SharePoint etc. If you want to search only the filename use:

Filename:(search terms)

if you only want to search the title:

Title:(search terms)

if you want to search both:

Filename:(search terms) OR Title:(search terms)

**Comment by wobba** [comment]
If this is your query template it should be:

`Path:https://tennant.sharepoint.com/sites/ Filename:({searchTerms})`

This query will limit results to any path starting with `Path:https://tennant.sharepoint.com/sites/` where search terms are in the filename.

If you want to limit to the current site use:

`Path:{Site} Filename:({searchTerms})`

**Comment by Tim2711** [comment]
Hi,

This is my query template:

Path:https://tennant.sharepoint.com/sites/
Filename: ({search terms})

This does not work properly; on every search the same results...

________________________________
Van: Mikael Svenson <notifications@github.com>
Verzonden: vrijdag 17 april 2020 10:37
Aan: microsoft-search/pnp-modern-search <pnp-modern-search@noreply.github.com>
CC: Arnoud Dekker <a.dekker@innovam.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [microsoft-search/pnp-modern-search] Search in document names (question) (#193)


If this is your query template it should be:

Path:https://tennant.sharepoint.com/sites/ Filename:({searchTerms})

This query will limit results to any path starting with Path:https://tennant.sharepoint.com/sites/ where search terms are in the filename.

If you want to limit to the current site use:

Path:{Site} Filename:({searchTerms})

**Comment by wobba** [comment]
Which is correct, cause that's what your template says. Use my suggestion and you would be fine.
