### ISSUE TITLE
Pagination is not working as intended, it should display total search results spanning the items 4 per scroll.

### ISSUE THREAD

**Issue by sputnala** [microsoft-search/pnp-modern-search#1932]
**Version used** 
4.5

**Describe the bug**
 The issue with pagination of the search results not showing all the search results returned, it shows nothing or only partial search results.

**To Reproduce**

1. Create a search result page with PnP v4.5 search results. 
2. Use basic configurations to fetch results based on query string. 
3. Allow pagination in search results and select “Number of items per page” to 50 and “Number of pages to display in range” to 50. 
4. Add Sort Order of a RefineableDate00 managed metadata as Descending.  
5. Search Results are not displayed, when we change the above number sometimes it will show partial results sets. 
6. Pagination doesn’t not display all the items (Search Results should fetch all 57 items and span across 4 each to form a pagination). 
7. When we change the items per page the content panel appears and disappears within fraction of second. 
8. Page is not moved to top of the result.

**Expected behavior** 
Pagination should work with the total search results spanning the items 4 per scroll.

Screenshots Not able to capture

Desktop (please complete the following information):
	•	Chrome, edge

**Comment by wobba** [comment]
Hi,
Your issue is a bit hard to figure out in terms of repro. If I understand correctly. If you set the page size to 50 you some times get results and some time you don't? Is it ties to the "number of pages to display"? As that seems weird.

Point 7, what does this mean? In edit mode, in runtime mode?

Point 8, that is an enhancement already logged #1917

Which sub-version of the web parts are you using? Which search provider are you using? Have you tried to repro the same query using e.g. the Search Query Tool?

**Comment by sputnala** [comment]
Thanks Wobba for the follow up, below are the clarifications, hope this helps...

Your issue is a bit hard to figure out in terms of repro. If I understand correctly. If you set the page size to 50 you some times get results and some time you don't? Is it ties to the "number of pages to display"? As that seems weird.

Point 7, what does this mean? In edit mode, in runtime mode? **Edit mode**

Point 8, that is an enhancement already logged https://github.com/microsoft-search/pnp-modern-search/discussions/1917

Which sub-version of the web parts are you using? Which search provider are you using? Have you tried to repro the same query using e.g. the Search Query Tool?

It seems when the sort order is changed to ASC, the pagination shows up but if the sort order is changed to DESC it does not shows any data.

**Comment by wobba** [comment]
If we have bugs in edit mode only, I'm not overly concerned :) Does it work as expected in display mode?

**Comment by sputnala** [comment]
It does not work in display mode too.

**Comment by wobba** [comment]
Does it work if you set the page to 10, if you remove sorting?

Can you also monitor the network calls to see if it's a data/API issue (data not returning) or a UX issue not showing the data being returned.

**Comment by wobba** [comment]
You should re-test with v4.6 or v4.7 to see if it's still an issue.

**Comment by wobba** [comment]
Pagination seems to work as expected based on what is returned from the API call.
