### ISSUE TITLE
We are getting "Internal Server Error" while search a user name

### ISSUE THREAD

**Issue by sumitdeyonline** [microsoft-search/pnp-modern-search#1938]
### Check existing issues before logging new ones
We are using the current DEV release

**Version used**
Ex: 4.5.4 (DEV release)

**Describe the bug**
We are getting an "Internal Server Error" while searching for any username in the search box using Result ID to LocalSharepolintResults. we know that LocalSharepolintResults doesn't provide the people result, however, it should not through an error 

**To Reproduce**
1. Go to site home page
2. search for the name(i.c sumit dey)
3. Search result is getting "Internal Server Error" 
In the console, we are getting the following error 
![image](https://user-images.githubusercontent.com/23446009/158243868-05b2c331-54f7-4a72-a26e-adf2ef14d793.png)

In the Network tab(postquery) is getting following error 

![image](https://user-images.githubusercontent.com/23446009/158244169-509c1658-93a6-4a7a-92af-4520dbbf7343.png)

![image](https://user-images.githubusercontent.com/23446009/158244286-c4756477-99a7-4ea2-ab54-f530e9141ed8.png)

Here is the response of this request 
**{"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}**

**Expected behavior**
It should return files belonging to that user(author or modifier) or no result(without any error)

**Screenshots**
![image](https://user-images.githubusercontent.com/23446009/158245088-544afbbb-a09c-4b69-b6bb-325b27c5c66a.png)

**Desktop (please complete the following information):**
 - Browser [chrome, edge]

**Comment by sumitdeyonline** [comment]
It is happening when we linked the result webpart to the filter webpart, which I forgot to identify in the bug post.

**Comment by sumitdeyonline** [comment]
It is happening when we enabled the query rule in the search result web part

**Comment by wobba** [comment]
Closing as this is another 500 API issue. Not the web parts.
