### ISSUE TITLE
pnp-modern-search Adding a hyperlink to the delve profile record in Manage Persona Fields

### ISSUE THREAD

**Issue by marting1010** [microsoft-search/pnp-modern-search#194]
Latest version

In manage persona fields, in the optional field I've tried to put in <a href="{{OriginalPath}}"</href> </a> but it just ends up as text in the web part

@FranckyC have I done something wrong here or is adding a hyperlink here not possible please?

**Comment by wobba** [comment]
You cannon inject html into the fields. You can however add a tags around in the custom template. We use the [Office UI Fabric control](https://developer.microsoft.com/en-us/fluentui#/controls/web/persona) which don't have a click target built-in.

```
<a href="some url">
  <pnp-persona-card fields-configuration="{{JSONstringify ../../../peopleFields}}" item="{{JSONstringify item}}" persona-size="{{../../../personaSize}}" />
</a>
```
