### ISSUE TITLE
mgt persona not returning newly added users

### ISSUE THREAD

**Issue by harikanagidi** [microsoft-search/pnp-modern-search#1940]
Hi ,

I have added few users in sharepoint admin center. I want to see them in pnp search results web part . this is only returning old / existing users and newly added users are not displayed. I can see them in Azure portal and office.com.

Any help is highly appreciated.

<mgt-person user-id="{{slot item @root.slots.Email}}" person-card="hover">
                                            <template>
                                               <pnp-persona
                                                    data-image-url="{{slot item @root.slots.Email}}"
                                                    data-primary-text="{{slot item @root.slots.Title}}"
                                                    data-secondary-text="{{slot item @root.slots.SecondaryText}}"
                                                    data-tertiary-text="{{slot item @root.slots.Phone}}"
                                                    data-optional-text="{{slot item @root.slots.EmailId}}"
                                                    data-persona-size="5" >
                                                </pnp-persona>
                                            </template>
                                            <template data-type="person-card">
                                                <mgt-person-card inherit-details>
                                                </mgt-person-card>
                                            </template>
</mgt-person>       

My data source  is Microsoft search
![image](https://user-images.githubusercontent.com/101328602/158363525-58e03eca-9eed-4e10-8588-57db0451a4de.png)
![image](https://user-images.githubusercontent.com/101328602/158363786-e22c174f-7da1-4f85-8f31-5fbad88dd719.png)

Displays results for existing users
![image](https://user-images.githubusercontent.com/101328602/158364558-dc8ac11c-440d-4933-88d2-16eb877d29a1.png)

**Comment by FranckyC** [comment]
Hi @harikanagidi, I see you are using a custom version of the PnP Modern Search Web Part. First, we do not support custom implementations. Then you didn't follow the issue template and did not provide any information about the layout you are using nor the slots/data source configuration. I close this one for now.
