### ISSUE TITLE
Filter Combo Box search is not case insensitive

### ISSUE THREAD

**Issue by Marlen-Jacob** [microsoft-search/pnp-modern-search#1943]
**Version used**
4.5.4

**Describe the bug**
The Filter Combo Box search is not case insensitive, even though this [Search Filters - Case sensitive](https://github.com/microsoft-search/pnp-modern-search/issues/1035) reads that there is a commit [support case insensitive filtering](https://github.com/microsoft-search/pnp-modern-search/commit/658779c563a934435d066df58e4944c04ce41c30) that supports it and that it is part of the next release. (It's not part of the release notes though).

**To Reproduce**
1. Add Filter Combo Box
2. search word with upper case -> you get a result
3. search word with lower case -> you get no result

**Expected behavior**
you get a result with upper and lower case

**Screenshots**
![uppercase](https://user-images.githubusercontent.com/82037661/158542812-b742754b-4c23-4d4c-9f09-3e3a4b4ec222.jpg)

![lowercase](https://user-images.githubusercontent.com/82037661/158542825-6aec0681-47d7-46bf-8531-52836c7535e1.jpg)

**Desktop (please complete the following information):**
 - any Browser

**Comment by FranckyC** [comment]
Hi @Marlen-Jacob, thanks for flagging this. Fixed with #1951 and will be available in the next release.
