### ISSUE TITLE
Google like search in PnP search V4

### ISSUE THREAD

**Issue by kcs-chandreshmungara** [microsoft-search/pnp-modern-search#1945]
For Ex: we have five files -  1) file1 file8 file9.doc, 2) file2.doc, 3) file3.doc, 4) file4.doc and 5) file5.doc

If I'm search below term in SharePoint OOTB search or PnP Search web part search box
- **file1 AND file8**
	then return 1 result :file1 file8 file9.doc
- **file1 AND file2**
	then return 0 result
- **file1 OR file2**
	then return 2 result : file1.doc and file2.doc
- **file1 OR file**
	then return 5 result : all 5 files display 

But

I'm not getting result without using AND OR NOT & LIKE operator.

For Ex: If I'm search : **file1 file2**
**then It returns 0 result**

If I'm search different word with file name or with tag or etc... then relavant result will be display in results

Is PnP search support this kind of functionality in search?

Thanks

**Comment by FranckyC** [comment]
PnP Modern Search uses KQL syntax with no modification. Please refer to the official documentation for more information https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference
