### ISSUE TITLE
Issue with z-index and mgt-person hover card in the details list template

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#1967]
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/1963

<div type='discussions-op-text'>

<sup>Originally posted by **BrinaD1** March 25, 2022</sup>
I'm not sure where to post this issue. I'm creating a list view employee directory and using the Details list template so the end users can sort as well as filter their results. The results template uses pnp-detailslist and the first column uses  mgt-person  (view="threeLines"  person-card="hover").

The hover card for the users is hidden behind the details rows except for the very bottom of the screen where it renders properly on top of the rows. 
<img width="393" alt="image" src="https://user-images.githubusercontent.com/5232243/160184301-81173376-b64c-42f7-ba56-1e30547ca8ca.png">

![image](https://user-images.githubusercontent.com/5232243/160184321-f719ece1-1135-4eb0-b695-f8615dacd077.png)

Any help is appreciated, thanks!</div>

**Comment by FranckyC** [comment]
Unfortunately, I don't have a fix right now. I can't get the callout to be stacked correctly :/. If a CSS guy wants to check out :D

**Comment by till-llit** [comment]
im stuck on the same issue, any updates on this?

**Comment by wobba** [comment]
@till-llit status as @FranckyC wrote is that we need help from someone on the needed CSS to solve this.

**Comment by FranckyC** [comment]
You could also post your issue directly in the MGT repo https://github.com/microsoftgraph/microsoft-graph-toolkit/issues

**Comment by FranckyC** [comment]
See https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/971

**Comment by till-llit** [comment]
thanks a lot @FranckyC ! the "fix" from the related issue really solved the problem:

```
<style>
     .ms-DetailsRow {
         animation-name: none;
    }
    </style>
```
too bad the custom css is changing the layout type from Details List to Custom and i cannot use "Manage Columns" anymore.

is there a better way to inject the css above and keep the Details List layout?

![image](https://user-images.githubusercontent.com/91128746/177340138-176f9136-df10-4082-a8dc-edf4b10726b7.png)

**Comment by FranckyC** [comment]
A fix has been deployed to `develop`
