### ISSUE TITLE
Search V4 Not Returning Results from Site Property Bag

### ISSUE THREAD

**Issue by cajetan77** [microsoft-search/pnp-modern-search#1983]
**Version used**
4.4.1

**Describe the bug**
When trying to filter on Site Properties in the result query template  it does not render any results and shows it as undefined

**To Reproduce**
1. Go to '.Search  Results Web Part'
2. Choose 'Sharepoint Search'
3. In Query Template Put Path:{SiteURL}
4. Go to Debug and see the query modification you will see the query as Path:undefined -ContentClass=urn:content-class:SPSPeople

**Comment by wobba** [comment]
Please read the documentation for proper token usage. https://microsoft-search.github.io/pnp-modern-search/usage/search-results/tokens/
