### ISSUE TITLE
Selected Properties in PnP - Search Results stops working

### ISSUE THREAD

**Issue by MatthiasAbt** [microsoft-search/pnp-modern-search#1984]
I am using version 4.5.4.
I have a Library on Site Collection a and i would like to show Document from this Location at other Pages. I created one Content Typ with 4 Columns (Managed Metadata). Two have Multiselect option, the other can have only a single option.

After some Tests with different layout Options and try to use the Tax. Columns as Filters, the Option to select Properties stopped Working and in the Devtools  I found the following error Message.

Cannot perform DeepCopy() because a circular reference was encounteres, object: [object Object], property: helper
![2022-03-31 10_53_43-Window](https://user-images.githubusercontent.com/38460859/161017932-da415d17-07c6-48f6-9fc6-ebc714417651.png)

What i have done before:
- Created a Content Type with the same Name & Fields on the Target Site
- Removed some unused Fields from the Layout Slots 
- Checked the mapping from my Tax Fields to RefinableString00, RefinableString01, RefinableString02, RefinableString03
-
What i tried to fix:
- Remove, Publish andre-add all PnP Webparts to the site
- Check the Result WebPart on other site of the same tenant
- Reindex Site
- Waiting for some hours.

**Comment by FranckyC** [comment]
Hi @MatthiasAbt, actually the dropdown list is just to help you to choose a property. If it doesn,t work you can still enter the property name manually and press "Enter" to add it as selected property (ex: "RefinableStringXXX". Repeat the operation for all properties and you should be fine.

**Comment by MatthiasAbt** [comment]
Yes, that is still possible. But also the Dropdown of the Field name doesn't show existing Values, same error in DEV Console, typing Value directly is here also working.

**Comment by FranckyC** [comment]
Can you inspect the network tab in your browser console at the time you expand the dropdown list and see if you get some errors?

**Comment by MatthiasAbt** [comment]
Yes i did, but there is no error in the network Tab, but a difference to another tenant i use to test.
![notWorking](https://user-images.githubusercontent.com/38460859/161062399-a488c5ae-6136-4d96-bde9-b442a61db7b7.png)
![working](https://user-images.githubusercontent.com/38460859/161062428-606b6e38-c828-42ab-9170-32c9e61c6c3c.png)

postquery is not send.

**Comment by FranckyC** [comment]
If the `postquery` call is not sent that could explain because the values comes from here. If you inspect the call do you anything wrong?

**Comment by MatthiasAbt** [comment]
When editing the Sort Order, postquery is there, but a 500 Status comes back.

**Comment by FranckyC** [comment]
Any special message? Or just 'internal error'?

**Comment by FranckyC** [comment]
Can you share the request + payload ?

**Comment by MatthiasAbt** [comment]
@FranckyC : Which request do you mean? Request Header from postquery

**Comment by FranckyC** [comment]
This one, I'll make some tests. Thanks!

**Comment by ullaspadup** [comment]
I am facing same issue with custom spfx webpart with pnp aswell, Something is off at microsoft end.
Recursive call fails after returning 3000 items (6 sets of 500

)
public async getItemsBySearch(queryText: string, startRow: number, empID: string, organization: string, country: string, itemsArr: any[]): Promise<any> {
        console.log(queryText, startRow);
        return new Promise<any>(async (resolve, reject) => {
            sp.search({
                Querytext: queryText,
                RowLimit: 500,
                SelectProperties: ["ListItemID", "RefinableString00", "POCFNameOWSTEXT", "POCLNameOWSTEXT", "POCEmailOWSTEXT", "RefinableString02", "RefinableString01", "ContentTypeId", "LinkOfficeChild"],
                StartRow: startRow,
                TrimDuplicates: false
            })
                .then((results) => {
                    itemsArr = itemsArr.concat(results.PrimarySearchResults);
                    if (results.TotalRows > startRow + results.PrimarySearchResults.length) {//check for next paging
                        startRow = startRow + results.PrimarySearchResults.length;
                        this.getItemsBySearch(queryText, startRow, empID, organization, country, itemsArr).then(resolve);
                    } else {
                        console.log(itemsArr);
                        resolve(itemsArr);
                    }
                    //resolve(itemsArr);

                })
                .catch(err => {
                    resolve(itemsArr);
                    //reject(err);
                });
        });
    }

**Comment by FranckyC** [comment]
Hi @MatthiasAbt, I'm not able to reproduce this issue unfortunately. I'll close this issue for now. Feel free to reopen it if you encounter it again.
