### ISSUE TITLE
Search box web part gets stuck on dynamic data source and can't be reconfigured

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#199]
**Version used**
3.11.1

**Describe the bug**
After selecting the "dynamic data source" option in the search box web part and connecting the wp to a list view on the page (which didn't work by the way), I no longer  get the option to connect the wp to a results web part. (See image)

**To Reproduce**
1. Add a search box, results and list view wp to a page
2. Connect the search box wp to the list view (title column)
3. Save the page, then go back to search box wp to change properties
4. Look for "connect" option

**Expected behavior**
You should be able to reconfigure the properties of the search box wp and connect it to the results wp using the  "connect to" button.

**Screenshots**
attached

**Desktop (please complete the following information):**
 Chrome

![Untitled](https://user-images.githubusercontent.com/51796756/79772059-a1bbd600-82fd-11ea-9a67-5ad1a7c86529.png)

**Additional context**
Tried publishing the page and clearing browser cache to no effect

**Comment by wobba** [comment]
If you want to connect it to retrieve page props etc, you check "Use a dynamic data source". It doesn't have a "connect" link. Does that answer you question?
