### ISSUE TITLE
Problem using PnP Search Results and PnP Search filters with managed metadata columns

### ISSUE THREAD

**Issue by miguelisidoro** [microsoft-search/pnp-modern-search#1990]
Hello,

I am using PnP Modern Search web parts and trying to know how some values in search works when applied to managed metadata columns.

I have a column name "Tags" that is linked to a Term Store in SharePoint Online that allows users to tag site pages in SharePoint Online.

One of the possibilities in those pages is to click on the Tags associated to the page that allows the user to be redirected to a search center page that filters search results by the selected Tag.

![image](https://user-images.githubusercontent.com/5429152/161156084-a385ec08-d1f3-4501-86a9-697c49317283.png)

For the search center page at https://mytenant.sharepoint.com/sites/searchcenter/SitePages/SearchCenter.aspx, I am using PnP Search Results and PnP Filters web parts.
When refining search results in the filters web part, I select one of the tags (managed metadata) I get the following url:

![image](https://user-images.githubusercontent.com/5429152/161156316-95f44f3d-d487-4d1f-b663-f23c45e208b2.png)

https://mytenant.sharepoint.com/sites/searchcenter/SitePages/SearchCenter.aspx?Tags=Travel&f=****[{"filterName":"RefinableString111","values":[{"name":"Travel","value":"\"ǂǂ54726176656c\"","operator":0,"disabled":false}],"operator":"and"}]#****

My question is regarding the "ǂǂ54726176656c" value that is associated with a term in my Term Store. This value is returned in the Search Results but I don't know what this is. How can I get this value from the term store (is there an API where I pass the Term Label and this value is returned?) so that for each tag listed in the page I can generate the correct URL to filter pages by tag in the search center?

Thanks

**Comment by FranckyC** [comment]
Hi @miguelisidoro, this value corresponds to the HEX encoded value of the term label prefix by `ǂǂ`:

![image](https://user-images.githubusercontent.com/5659122/161317880-fc3e0e6d-cd52-4468-80b9-d5dd6aac522e.png)

You can use tool like `https://www.convertstring.com/EncodeDecode/HexEncode` to generate the value based on the text. However, putting the text value in the URL would work as well.

**Comment by miguelisidoro** [comment]
Hello @FranckyC , that was it. Thanks, I managed to get a working JS function to get the hexadecimal value of the refiner and make it working.
