### ISSUE TITLE
In the Search Refiners, configured 10 properties but when searched showing only 2 properties for refining, while the data is present for all of the 10 properties.

### ISSUE THREAD

**Issue by rameshbaburanga** [microsoft-search/pnp-modern-search#1992]
In the Search Refiners, configured 10 properties but when searched showing only 2 properties for refining, while the data is present for all of the 10 properties.

**Comment by FranckyC** [comment]
@rameshbaburanga, that's a shame you've totally dismissed the issue template when submitting your issue. As stated:

![image](https://user-images.githubusercontent.com/5659122/161319154-c8b22268-d92e-49f8-a5ab-7069169d9d7e.png)

Please resubmit with more details. We can't guess your specific context.
