### ISSUE TITLE
 Certain search terms give 500 Internal Server Error when Query rules and 'refiners' are enabled 

### ISSUE THREAD

**Issue by AkiraSPO** [microsoft-search/pnp-modern-search#1996]
**Version used**
Ex: 4.5.4

**Describe the bug**
I am receiving a 500 error on certain keywords e.g. 'compass' and a certain user names in both version 4.5.4 and 4.5.3. Here is what I have observed:
I get the error only when these 2 conditions are true:
 1. 'enable query rules' is enabled in the search results webpart 
 2. Results webpart is connected to a search filter webpart on the page. (even a simple filter like filetype will make it through a 500 )
If I either remove the filter webpart connection or disable query rules, the results start showing up.

**To Reproduce**
1. Create a page with title or content containing word 'compass'
2. Create a search results webparts using latest pnp modern search
3. Add search results webpart and filter webpart 
4. Configure filter webpart to have 'FileType' filter
5. Configure search results webpart to be connected to the filter webpart and also enable the 'Enable query rules' option

**Expected behavior**
Search results should display results related to the search term (i.e. compass)

**Screenshots**
![image](https://user-images.githubusercontent.com/102831180/161337352-78a53d1d-ceaf-4b43-b1ee-bd14dacee7d3.png)

**Desktop (please complete the following information):**
 - Browser  -chrome
 -
**Additional context**
Tried the same query in Sharepoint search query tool v 2.9.0 and got the same 500 error with same conditions (i.e. enabled query rules' and fileType filter)
No custom query rules have been defined on the site.

**Comment by wobba** [comment]
Closing as it's an API issue. There are other similar issues reported and could be related to query rules triggering on your term. Either way it's not a web part issue.

**Comment by AkiraSPO** [comment]
Just came back here to say V4.8.0 fixed this issue for me. In case someone else come across this issue. I believe this change fixed it for me:
searchQuery.EnableInterleaving = false;

**Comment by wobba** [comment]
Or you could turn off query rule processing.
