### ISSUE TITLE
Feature Request: Bump Version to 4.0

### ISSUE THREAD

**Issue by MakingThingsWorkToronto** [microsoft-search/pnp-modern-search#200]
**Is your feature request related to a problem? Please describe.**
The 3.11 release has removed web parts & significant breaking updates over the 3.10 version.  Think it's time to bump the major version.

**Describe the solution you'd like**
I'd like to see the version bumped to 4.0 and version three end at 3.10 

**Describe alternatives you've considered**
Not absolutely necessary however would better convey the changes required from 3.10 -> 3.11 may require rebuilds. Concerned clients without test environments may install 3.11 expecting merely minor changes.

**Additional context**
N/A

**Comment by wobba** [comment]
I tend to agree and I've brought it up. We also would like to avoid maintaining two versions going which should not be needed, but rather document upgrade paths.

It's breaking in terms of setup, but not functionality, and only if you used the removed parts, which we don't have an overview of how many are using each one.
