### ISSUE TITLE
Refiner link color on dark background issue

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#2001]
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/1997

<div type='discussions-op-text'>

<sup>Originally posted by **LetMeSP** April  4, 2022</sup>
After updating to the newest version refiner filter links are still dark when changing to the dark background. Before it was white. Is this a bug or am I missing something? Screenshot for reference.

![2022-04-04_11-02-45](https://user-images.githubusercontent.com/41652178/161605196-59e5eaf5-1c21-4f5a-8c2d-2269195c87a9.png)
 </div>

**Comment by FranckyC** [comment]
Fixed with #2133
