### ISSUE TITLE
Broken link on how-to-contribute.md documentation

### ISSUE THREAD

**Issue by LeHailender** [microsoft-search/pnp-modern-search#2003]
Found a broken link on https://github.com/microsoft-search/pnp-modern-search/blob/main/docs/how-to-contribute.md

Code part:
`As a result, we accept pull requests from the community. You can refer to [this post](**https://tahoeninjas.blog/2019/08/18/my-github-cheat-sheet-for-pnp-contributions-an-interactive-cheat-sheet**/) by Hugo Bernier to know how make a PR on a GitHub repository.`

The link -> https://tahoeninjas.blog/2019/08/18/my-github-cheat-sheet-for-pnp-contributions-an-interactive-cheat-sheet redirects to a 'empty' WordPress site.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/85994794/161915321-93ce9f93-3c51-4149-880f-f0adb9528344.png">

**Comment by wobba** [comment]
Thank you. Docs will be fixed next time we publish them.
