### ISSUE TITLE
Feature Request: Load All Search Results

### ISSUE THREAD

**Issue by MakingThingsWorkToronto** [microsoft-search/pnp-modern-search#201]
**Is your feature request related to a problem? Please describe.**
A limitation of the classic Content by Search web parts was the inability to load over 50 search results. Customizers hacking the web part to display over 50 results became common. I propose support for users to load all search results for a query.

**Describe the solution you'd like**
Add option to allow all search results to be loaded. Need several changes for performance sanity: 
1) Add Boolean property to load all search results;
2) Add Boolean property to trim duplicates ensuring no results are dropped; 
3) Add Boolean property allowing users to disable/enable mapping of search results to icons (icons not required in many custom scenarios & significantly slower on larger data sets).

This above has been implemented in the below fork.

Moreover, would like a web part property for provisioning purposes that determines the maximum # of results in the slider. Ideally developers could add a web part with code to page that increased the maximum number of search results in property pane from 50 to a larger number (max 500). This would allow us to increase batch sizes.

**Describe alternatives you've considered**
Adding more search result web parts to the page. Redesigning use case scenarios.

**Additional context**
See example here: https://github.com/MakingThingsWorkToronto/pnp-modern-search

**Comment by wobba** [comment]
500 search results are max per request, and should be possible to add. No icons can be accommodated with a custom handlebar template. Duplicate trimming is off my default in the web part, and will not add a capa to turn it on as it's crap functionality 😉

Which leads to your issue being to up the max result count per page.

**Comment by MakingThingsWorkToronto** [comment]
@wobba - I may be misunderstanding how the icons are mapped (with respect to old sp icons), so please feel free to clarify. In SearchService.ts it appears a batch request is sent for each item in the relevant results. That's where in the past I've seen the performance penalty - even with only 500 results, it was too significant. Is the thought IconSrc will be deprecated in the future? If not, even at 500 rows we'd need a mechanism to disable that batch call.

Consider a grouped UI, with no paging, where the user wants to show 1000+ items, and search only returning two managed properties: Title and a URL; using a custom template. Data volume over the pipe is fairly low, but would require two search api requests & to feed the Grouped UI. Is there a better way to accomplish this through the extensibility library or a custom renderer? A recursive call to search within SearchService.ts accomplishes this with few code changes as per example.

To elaborate a bit further, the tools stapled into your webparts: filters, extensibility, renderers, verticals etc. are very useful for cross cutting larger data sets. Building custom spfx web parts to solve the problem makes it difficult to leverage the above. For me, merely upping the page size to 500 would not guarantee all results were loaded.

If a user wants more than 500 rows on a page they can always add several instances of the web part. Thus in not supporting this, we could run into more significant performance penalties with duplicate calls etc. while lacking the ability to leverage the tools consistently.

Hardcoding trimduplicates to false works fine for me!

**Comment by wobba** [comment]
Short answer is the web parts are primarily used for regular user scenarios. What you talk about sounds closer to eDiscovery etc, as browsing many hundreds++ results is a very uncommon use case for most users.

As for icons I'll take a look and check what you talk about. As we have replaced/updated icon usage to ouifr icon packages.

**Comment by MakingThingsWorkToronto** [comment]
May be easiest to review the changes in the fork to get an idea for what I turned off/changed to make this work.

UI is useful for enterprises whom have a large number of "partners / projects", "buildings / tenants", "clients / disputes" , _parent/child relationships_ - to drive traffic from a destination site into appropriate site collection, folder etc.. Wouldn't be able to easily put this in a menu.

Agreed: It's not a typical search scenario, but it's not uncommon & there are no great solutions for this OOTB. The ability to have filters, search, etc. make this the perfect web part - albeit not as common a usage scenario not difficult to support.

The work around being adding a search web part for each partner, building, client, _parent_ etc. each having one group results in many more calls to the search API and a more significant performance hit. Uncommon sure, but It'd be very nice to support OOTB.

**Comment by wobba** [comment]
Hi,
For icons, if the template is using `IconSrc` then it will do the old batching, which old templates my have. New templates will not have this, and should use client side logic only for outputting an ouifr icon.

Verified that code has duplicate trimming off, and has had it like that for a good long while.

I'm replacing the slider with a text box to allow 1-500.

**Comment by MakingThingsWorkToronto** [comment]
@wobba - thanks. I will maintain my fork to ensure people have access to something that loads all search results. Unfortunately 500 isn't enough for my use case. Cheers!

**Comment by wobba** [comment]
Loading 1 million items ;) I'd rather implement infinite scroll and load as you scroll.

**Comment by MakingThingsWorkToronto** [comment]
Could use a web part property that's not connected to the UI/property pane to enable. At least that mitigates the risk of 1M records being loaded by someone not understanding the implication. Users would have to provision the WP via code to enable. Could also add a ceiling (constant) that'd prevent over ## records from loading ... making it easy enough to merge. 
The modern lists & libraries use infinite scroll and anything over 200 rows is a usability nightmare. That's one of the primary drivers of these requests with my clients.

**Comment by MakingThingsWorkToronto** [comment]
@wobba - thanks for following up on the feature request. I completely understand why you wouldn't want to implement. Appreciate everything you've done for the community by starting this project! It's been a long time favorite!

**Comment by vijaypsi** [comment]
Hi In pnp modern search web part - 
  In search result web part,  is any maximum limit of for result load ?

**Comment by wobba** [comment]
Max 500 per page which is the API limit.

**Comment by vijaypsi** [comment]
@wobba Thank for update

But on my load it show **4562 result for *** 
<img width="565" alt="result" src="https://user-images.githubusercontent.com/7701131/121499454-0868eb00-c9fb-11eb-93d3-9a327cf290e4.PNG">

**Comment by vijaypsi** [comment]
This implemented in modern site using modern Pnp Webpart I have more then 200000 records but it load 4562 every time so is any limit ?

**Comment by wobba** [comment]
The count is an estimate based on heuristics for the returned set - not exact.

**Comment by vijaypsi** [comment]
Really big thanks for update and valuable information

**Comment by vijaypsi** [comment]
Hi,
I have deployed 3.12.1 version of PnP Search We part , Client reported issues about  it not load all result in refiner (only 100 option in Refiner available). it seem resolved in 3.15.1.

We are planning upgrade from 3.12.1 to 3.19.2 (As 4.x just released and need to reconfigure client would like to go with 3.x)
I need your help on below.

1.If I upload 3.19.2 on Appcatalog is this overwrite 3.12.1 ?
 (Due to some reason my tenant not working proper so can not able to try and error)
2.Is 3.19.2 auto upgrade on all site collection where currently 3.12.1 configured or I need to reconfigure all we part again ?
3.Is at any version of pnp search webpart out of box export to excel support ?

Thanks in Advance

**Comment by wobba** [comment]
@vijaypsi Updating/overwrite should work fine., and if you use the tenant app catalog all places will start using the new version. You can always upload v3.12.1 back if something wrong happens :) Remember that when you update, especially if you use CDN, it can take a minute or so before everything works. And remember to check in the uploaded version when you update.

There is not Excel export today. See #503 for a feature request.

And... please open new issues for your questions, don't comment on closed unrelated thread.

**Comment by vijaypsi** [comment]
ok thanks for update
