### ISSUE TITLE
Value for 'HitHighlightedSummary' is not populated when the Query Template starts with '{searchTerms} AND '

### ISSUE THREAD

**Issue by SjoerdV** [microsoft-search/pnp-modern-search#2010]
**Version used**
Ex: 4.4.1

**Describe the bug**
Value for 'HitHighlightedSummary' (and thus the computed 'Summary' slot) is not populated when the Query Template starts with '{searchTerms} AND '

**To Reproduce**

**Prepare assets**
1. Add some documents and links in a library somewhere

**Configure Page (Part 1)**
1. Create a modern page, or use the homepage of a site
1. Add a PnP searchbox webpart
1. Add a default PnP results webpart (use the 'Details List' layout, which will have the Summary column added by default)
1. Add this as a Query Template ```{searchTerms} AND Path:<URL to the DocumentLibrary>*```
1. Connect this Results webpart to the SearchBox webpart

Notice the Summary column is NOT filled, DEBUG view shows 'null'  as a value

**Configure Page (Part 2)**
1. Add a second PnP default results webpart (use the 'Details List' layout, which will have the Summary column added by default)
1. Add this as a Query Template ```Path:<URL to the DocumentLibrary>*```
1. Connect this Results webpart to the previous SearchBox webpart (not really functional without the token in the Query Template, but just to complete the setup)

Notice the Summary column is filled, DEBUG view shows some computed value

**Expected behavior**
I would expect it not to matter whether or not any token or this specific token is used in the Query Template. It should always deliver a filled in Summary slot and thus a filled in 'HitHighlightedSummary' search result property

**Screenshots**

**Desktop (please complete the following information):**
 - Firefox, Edge Chromium

**Additional context**

**Comment by wobba** [comment]
Closing as the web parts cannot control what the API return or not. You should replicate the bug and file a support ticket with Microsoft.

**Comment by SjoerdV** [comment]
Just found a workaround.
I forgot to mention that the result webparts were also having a default value set for the searchbox connection which was set to "*" (no quotes) and the solution lies here in.

1. let's say the Query Template is equal to ```{searchTerms} AND Path:<URL to the DocumentLibrary>*```
1. then set the Default value for the Results webpart connection with the Searchbox to "Path:<URL to the DocumentLibrary>*" (no quotes), so just repeat the entire query without the ```{searchTerms} AND ``` part. This will miraculously make the HitHighlightedSummary value be populated.

So it's probably an API issue indeed, but perhaps someone can use this. Don't use just a plain asterisk as a default value is my lesson here. If someone disagrees I'd like to hear it though

**Comment by stevebeauge** [comment]
As anyone update regarding this issue ?
I can cheat using the workaround from @SjoerdV but it's not cumfortable.

And opening a ticket for every single bug in SharePoint would require hiring a full dedicated team

**Comment by spinyriptide** [comment]
> Just found a workaround. I forgot to mention that the result webparts were also having a default value set for the searchbox connection which was set to "*" (no quotes) and the solution lies here in.
> 
> 1. let's say the Query Template is equal to `{searchTerms} AND Path:<URL to the DocumentLibrary>*`
> 2. then set the Default value for the Results webpart connection with the Searchbox to `Path:<URL to the DocumentLibrary>*`, so just repeat the entire query without the `{searchTerms} AND ` part. This will miraculously make the HitHighlightedSummary value be populated.
> 
> So it's probably an API issue indeed, but perhaps someone can use this. Don't use just a plain asterisk as a default value is my lesson here. If someone disagrees I'd like to hear it though

So this would work without the token {searchTerms}? I didn't try it yet, but this is my first thought.

**Comment by spinyriptide** [comment]
> As anyone update regarding this issue ? I can cheat using the workaround from @SjoerdV but it's not cumfortable.
> 
> And opening a ticket for every single bug in SharePoint would require hiring a full dedicated team

lol, there are SO MANY... including the documentation. What a gnarly web they weave.
