### ISSUE TITLE
Result Source ID is being disregarded

### ISSUE THREAD

**Issue by shridha21** [microsoft-search/pnp-modern-search#2012]
**Version used**
Ex: 4.5.3

**Describe the bug**
We have setup various Search pages to display results from different Result sources. All of a sudden today, all the Search Results webparts are showing results from all SharePoint Online sites, as if ignoring the Result Source Id's associated with the Search Results webparts.

**To Reproduce**
1. Create a new page and add a Pnp Search Results webpart
2. Set Source as SharePoint
3. Use input Query text and set any static value
4. Select Results Soucre as predefined Result source -Data shows accordingly in Search result webpart.
5. Change the Result Source to a Result Source GUID - Data comes in from all SharePoint, as if result source ID is not taken into consideration. The GUIDs are correct. They had been working correctly untill yesterday.

**Expected behavior**
When a Result Source ID ios specified the results should show from that result source and not all across.

**Desktop (please complete the following information):**
 - Browser - Edge, Chrome

**Additional context**
Issue started occurring today

**Comment by patrikhellgren** [comment]
@shridha21 This has been an ongoing issue on and off for a couple of months now and has been discussed in #1918.
This is not related to the Modern Search web parts and has to be taken to Microsoft support. I have had three different support cases (including one ongoing) in the last two months related to Result Sources not working correctly and very similar to yours.

**Comment by shridha21** [comment]
Thank you @patrikhellgren for your just in time input. I was on call with Microsoft support when i received your message and it was helpful in pushing them to do some troubleshooting. Looks like there was some outage of service or something that Microsoft reverted discreetly as this issue doesnot occur any longer.
Thank you for your assistance.

**Comment by wobba** [comment]
Not a web part issue, API related. Feel free to log this with Microsoft support.
