### ISSUE TITLE
Default search not working v3.14.2

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#2018]
I'm using a results web part with the default search set to show all items from 3 lists using a wild card "*", and a connected search box to allow filtering results on the title field.  
Query template:
`(Path:https://xxx.sharepoint.com/sites/Employee-Recognition/Lists/xxx  OR Path:https://xxx.sharepoint.com/sites/Employee-Recognition/Lists/xxx OR Path:https://xxx.sharepoint.com/Lists/xxx) Title:{searchterms}`
This has been working great for years, but now the default results display nothing when the page loads. Still works correctly if you enter a search term. There are roughly 11000 items in the 3 lists but even if I just search one list, the default results are still empty.

**Comment by wobba** [comment]
Contact Microsoft support as this is an API issue, not web part issue.

**Comment by webbrewer** [comment]
@wobba  I don't think so because if I don't connect the search box to the results web part, all results are shown.

**Comment by webbrewer** [comment]
Narrowed it down to the refinement of Title:{searchTerms}.
Title:{searchTerms} doesn't show any items
{searchTerms} shows all items, but obviously I want restrict search to the Title field. 
As I said this worked before and in query builder - and nothing was changed.

**Comment by webbrewer** [comment]
Curious - I was using Title:{searchTerms} which was what stopped working recently. **Title:({searchTerms})** now seems to resolve the problem.
