### ISSUE TITLE
Search box web part with Title 

### ISSUE THREAD

**Issue by spo365** [microsoft-search/pnp-modern-search#202]
**Is your feature request related to a problem? Please describe.**
User should have flexibility search the document by - document title. 

**Describe the solution you'd like**
When user enter search keyword on search box web part they should have flexibility to search document by title. 

**Describe alternatives you've considered**
N\A
![image](https://user-images.githubusercontent.com/5062256/80042291-ef288500-8541-11ea-9bdb-ea5c69400eb0.png)
idered.

**Additional context**
If we add checkbox in search box webpart with the help of react state we can post the selected value to result page to display the record based on title.

**Comment by wobba** [comment]
We won't add custom settings to the search box like this. You are however free to create your own version. A workaround is to have two pages, or two verticals where you set the query template to scope to particular fields, and use the vertical nav to solve this, or the page itself.

**Comment by spo365** [comment]
Hi @wobba ,

Thanks for workaround i have a question if i add two search result pages and one page with title search and other page without title search, how we can navigate from search box page to these pages as we have only one option in query parameter.
![image](https://user-images.githubusercontent.com/5062256/83828356-c50ed900-a723-11ea-8f03-7a02ebdb8cd6.png)

**Comment by MakingThingsWorkToronto** [comment]
You should use the Search Verticals webpart for this. See docs here: https://microsoft-search.github.io/pnp-modern-search/search-parts/search-verticals/

The user has to click the vertical to switch between pages but it’ll accomplish what you need :)

**Comment by spo365** [comment]
Thanks :)  everyone for your help.
