### ISSUE TITLE
Item Count Not Matching Actual Results

### ISSUE THREAD

**Issue by dilkry** [microsoft-search/pnp-modern-search#2026]
**Version used**
4.6.1

**Describe the bug**
When I do a search, the number of items returned does not match the number of items in search results. From image below, you see the search results shows 85 results but when I get to page 7 of a 10 item per page setting, I see only one item. these means there was only 71 actual results. It appears that there might be some duplication in the count of the items. This has happened with multiple search terms and not just with the one in the example.

![2022-04-19_10-13-18](https://user-images.githubusercontent.com/34752091/164037640-e9fb6951-89f8-44d7-86cb-ed1fb9183ae1.jpg)

**To Reproduce**
1. Go to the search page
2. Enter a search term
3. Scroll through the pages until you come to a page with fewer than ten results on the page
4. Count the number of results and compare to the result number at the top of the search

**Expected behavior**
I expect the number of items listed above the results to match the number of results on the page so if it lists 85 results, I expect it to show 85 items and not 71.

**Screenshots**
![2022-04-19_10-13-18](https://user-images.githubusercontent.com/34752091/164037640-e9fb6951-89f8-44d7-86cb-ed1fb9183ae1.jpg)

**Desktop (please complete the following information):**
 - Edge version 100.0.1185.44 

**Additional context**
No additional information

**Comment by wobba** [comment]
The count coming back on the API response is an estimate and we cannot control what the API returns.
