### ISSUE TITLE
Filter - Date interval with wrong date ranges

### ISSUE THREAD

**Issue by ric2804** [microsoft-search/pnp-modern-search#2027]
**Version used**
Ex: 4.5.3

**Describe the bug**
When using the search filter webpart for a date field, and choosing the option "Date Interval" as template, the applied date intervals don't match the selected wording. It looks like the option "past 24 hours" is missing, and the applied filter values are all moved to the next filter choice, please see the screenshots for a detailed description.

**To Reproduce**
1. Use the Filter Webpart
2. Use a managed property (date)
3. Use "Date interval" template
4. Select any of the provided choices --> look at the selected filters

**Screenshots**
This is an example for a wrong applied filter date:
![image](https://user-images.githubusercontent.com/104016143/164038473-8e0d5263-68af-4be4-919e-2e5588515f8d.png)

Theses are the applied filters selected for a date filtering on April 19th 2022:
![image](https://user-images.githubusercontent.com/104016143/164032276-94abb733-87a9-485a-b838-87029a265d94.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/104016143/164039145-11e0bcf9-19fd-44bd-bfd3-449ff12138a2.png)

**Comment by wobba** [comment]
It's not an option missing, but changing the wording to match the actual intervals.

**Comment by FranckyC** [comment]
Fixed by #2134. Will be available in the next release.

**Comment by ufkdev** [comment]
How the selected property for Created Date is called?

**Comment by wobba** [comment]
@ufkdev the managed property for created date is named `Created`.
