### ISSUE TITLE
New MS Change? "This app is supported only in the classic SharePoint Store experience"

### ISSUE THREAD

**Issue by edarroudi** [microsoft-search/pnp-modern-search#2030]
**Version used**
Ex: 4.6.1.0

**Describe the bug**
I had problems loading my extension / activating it in my dev tenant1. So i created a sandbox tenant and tried it there. Since it still didn't show up I added the latest Version of the pnp-modern-search-parts-v4.sppkg . What stood out immediatley is that MS did some changes to the master App catalog.

**To Reproduce**

![image](https://user-images.githubusercontent.com/935493/164434048-fc5af6fe-2fc5-4734-be7e-aba78523717d.png)

Problem is that the modern search app is not visible in the "Add App" in my test site.
Neither in classical or modern experience.

![image](https://user-images.githubusercontent.com/935493/164434520-717cfa50-b135-46bf-98ca-32e065b4170b.png)
![image](https://user-images.githubusercontent.com/935493/164434552-37b16c5d-58ca-42aa-bf24-c2ad072baf38.png)

if I click on view app details on the modern search package I get to the following site:
![image](https://user-images.githubusercontent.com/935493/164434840-264592b0-644b-42e5-8059-5bda39e75a30.png)

![image](https://user-images.githubusercontent.com/935493/164435005-9b3ffcaf-dbcc-4552-ad43-0a3768d92469.png)

Following the "Switch to the classic SharePoint Store" link:
![image](https://user-images.githubusercontent.com/935493/164435520-075bee0a-e93c-456d-b6c9-d22969322d7a.png)

I can add it to the app catalog site. So I copied part of the url "/15/storefront.aspx#vw=AppDetailsView,app=6f6acc19-8c6c-495c-a1f6-5c9915a62e41,clg=1" and pasted it on the test site.. That way it was possible to add the modern app to the site

![image](https://user-images.githubusercontent.com/935493/164437638-3d506b2d-4553-4e36-a89b-f27c59c9bbfa.png)

Still it feels like the whole thing is messed up somehow. Like if I want to add another app it says that i didn't add any apps yet:
![image](https://user-images.githubusercontent.com/935493/164439445-250fbb51-e834-44ad-b874-f03456677127.png)

Is there some word from MS that announced those changes?

**Expected behavior**
ModerSearch App should be available in the modern experience.

**Desktop (please complete the following information):**
 - chrome

**Comment by wobba** [comment]
Do you see the issue with 4.6.1 only?

**Comment by edarroudi** [comment]
No, I just tried the february version as well... Doesn't work there as well.

**Comment by wobba** [comment]
The app store message is likely due to the web parts being on SPFx v1.12.1. We will update them at some point, but no real need in terms of functionality yet.
