### ISSUE TITLE
Bug in 4.6.1 Filter web part when typing in combobox

### ISSUE THREAD

**Issue by erikthomte** [microsoft-search/pnp-modern-search#2031]
**Version used**
Version 4.6.1

**Describe the bug**
PnP Filter webpart with combobox. Typing in box to narrow down choices, select a element in the filtered choices (screenshot 1, step 1).
Can only make one selection before "full drop down" with all choices is displayed.
Try to select another element with the same first letters as the element selected in step 1, but another element is autoselected instead
(screenshot 2, step 2 and 3).

Tried to check with both Propercase(Eri) and Lowercase (eri), same bug.
If an element without the same letters (eg. Dolly) is selected, then everything works fine.

Also tried in another tenant, and when typed in "knu" , selected user with first name "Knut", then I got the same issue when trying to select another user with first name "Knud". 

Possibly an index problem occurs when shifting from type-ahead "dialog" to the "full filter list choice dialog" ?

FYI: Tested in 2 different tenants, one standard and the other one first release, same issue.
Did a rollback to 4.5.4 both tenants, no bug, but then had to remember to use capital first letter in type-ahead (and no new sorting functionality which btw worked well).

**To Reproduce**
1. Use filter web part, type in combobox, narrow down selection
2. Select one choice
3. "Full list dialog" is shown, tries to make another selection with the same first letters as the first selection
4. Wrong element in list is autoselected

**Expected behavior**
Same behavior as 4.5.4, but still have case insensitivity.

**Screenshots**
![PnP Filter web part first select](https://user-images.githubusercontent.com/11938837/164458293-4a994d41-2348-4cdb-b2d5-fb6de9f271b4.jpg)
![PnP Filter web part second select wrong index](https://user-images.githubusercontent.com/11938837/164458294-cfc6fda3-6931-4d22-a7f8-244eb3e88597.jpg)

**Desktop (please complete the following information):**
Windows 10, Chrome Version 100.0.4896.127 

**Additional context**
This part not really a bug, but it would be more user friendly if the first type ahead filtering in the combo box would allow multiple choices, and an "Apply" button could be used directly instead of switching to the full list and have to find/scroll a possibly long list to find other ones similar to the one originally selected.
Currently it is quicker to just use the drop down list directly instead of doing the type-ahead filtering, and still have to go to the full list.

**Comment by jhholm** [comment]
I can actually reproduce this with 4.5.4. Pretty weird and not easy to reproduce.

 This could be an internal issue with Fluent UI, but I could skip the bug via adding **persistMenu={true}** to the <ComboBox /> -element.
https://github.com/microsoft-search/pnp-modern-search/blob/7710b8a5e9651dadb55f36400ed8c9f77c2f0f97/search-parts/src/components/filters/FilterComboBoxComponent.tsx#L151

I think it has something to do that the ComboBox is using freeform and focusing is done via a reference on onPendingValueChanged.
https://github.com/microsoft-search/pnp-modern-search/blob/7710b8a5e9651dadb55f36400ed8c9f77c2f0f97/search-parts/src/components/filters/FilterComboBoxComponent.tsx#L163

If I remove the focusing part of the code, the combobox doesn't open automatically, but also doesn't show this same issue.

**Comment by erikthomte** [comment]
Thanks for your repo and insights Janne. I thought this bug was introduced with the 4.6.1 fix for case insensitive type-ahead, but I can also repo on 4.54.

@wobba and @FranckyC  - can Jannes bugfix be added to the codebase, and then release a 4.6.2 version ? If not could it be included in the next scheduled release ?

**Comment by jhholm** [comment]
I can continue to check if I can produce a fix, if using **persistMenu** would produce performance issues.

**Comment by wobba** [comment]
Not too worried about performance, and feel free to PR a fix.

**Comment by FranckyC** [comment]
Hi @erikthomte, I've made a fix with PR #2104. Now you can select multiple filtered values at once. The whole list is not rendered anymore after selecting an option. However, I didn't add the `persistMenu` option as I can't really tell if it is really needed. If you have the chance to test on the `develop` branch, let me know!

**Comment by erikthomte** [comment]
Thanks for your suppoert and the fix @FranckyC I'm on vacation this week and the next , but I will try to make a test when I'm back at work.

**Comment by erikthomte** [comment]
Hi @FranckyC , I have had a lot of work to catch up after my vacation, but I finally had some time to run a quick test today. Tested with a tenant with Targeted release, using PnPModern Search 4.7.0 beta and Chrome web browser.

The no-rerender fix for the combobox works well. Thanks for your support, and great work!
BTW, when can we expect an official 4.7.0 release?
