### ISSUE TITLE
Our Guest Uses can't read the result of the PnP Modern Search - Search Web Parts - v4

### ISSUE THREAD

**Issue by AnnickMainville** [microsoft-search/pnp-modern-search#2040]
**Version used**
Ex: 4.5.3.0

**Describe the bug**
Hello, we have installed the PnP Modern Search - Search Web Parts - v4 application in the application catalog for Sharepoint Online. It works for people in our organization, but not for guest accounts that were created in our tenant, these have an error message: sorry we encountered a problem.

Complet error message : 

[SPLoaderError.loadComponentError]: Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Failed to load path dependency "SearchBoxWebPartStrings" from component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Error loading https://component-id.invalid/544c1372-7e5a-49ec-8db6-812f76c375f2_4.5.3/SearchBoxWebPartStrings Unable to load script https://msss365.sharepoint.com/sites/apps_catalogue/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/SearchBoxWebPartStrings_fr-fr_f6c583c430c9f7a4e384cb07f3683a46.js INNERERROR: Failed to load path dependency "SearchBoxWebPartStrings" from component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Error loading https://component-id.invalid/544c1372-7e5a-49ec-8db6-812f76c375f2_4.5.3/SearchBoxWebPartStrings Unable to load script https://msss365.sharepoint.com/sites/apps_catalogue/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/SearchBoxWebPartStrings_fr-fr_f6c583c430c9f7a4e384cb07f3683a46.js CALLSTACK: Error at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_fr_97cb8d3f8847df3921d02ca522e9968d.js:70:214345) at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_fr_97cb8d3f8847df3921d02ca522e9968d.js:71:8138) at Function.e.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_fr_97cb8d3f8847df3921d02ca522e9968d.js:71:45460) at Function.e.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_fr_97cb8d3f8847df3921d02ca522e9968d.js:71:41551) at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_fr-fr_b8bbfc716fef8650007c.js:1 

We then, in the admin console, shared our application catalog with the guests, but the problem is still there.

**To Reproduce**
N/A

**Expected behavior**
We want guest users to be able to view the results of pnp search

**Screenshots**
![image](https://user-images.githubusercontent.com/104205403/165527974-da61d808-9b4b-4e39-b3c8-2ecbff679410.png)
![image](https://user-images.githubusercontent.com/104205403/165528110-0668c8bb-4e55-4d86-933e-e1dc1bf61b0d.png)

**Desktop (please complete the following information):**
 - Browser Chrome and Edge

**Additional context**
N/A

**Comment by wobba** [comment]
See this awesome post by @LauraKokkarinen on how you can resolve this issue https://laurakokkarinen.com/sharepoint-online-guest-user-troubles-and-how-to-get-past-them/#custom-share-point-apps-dont-load-for-guest-users-by-default
