### ISSUE TITLE
Caroussel template layout not working with small amount of results.

### ISSUE THREAD

**Issue by guillaume-kizilian** [microsoft-search/pnp-modern-search#2044]
__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
4.5.3.0

**Describe the bug**
When handling a few elements, the slider is not calculating display correctly (arrows are grayed, not enough dots)

**To Reproduce**
0. Have enough elements to reproduce (like 10 pages)
1. Create a Modern Page
2. Turn section into a 3 column section
3. Add PnP - Search Result to a Column
4. Choose your source and SlideShow display
5. Play with number of result per page to limit test 

**Expected behavior**
Slideshow should work with 1 to 4 slides.

**Screenshots**
![Expect 4 dots](https://user-images.githubusercontent.com/6792560/165929153-b7d5328c-d0b8-4e35-ba20-4e4bc192bf77.png)
![Expect 3 dots](https://user-images.githubusercontent.com/6792560/165929266-dce7ff8a-a325-4a54-838c-a69b70e1bec2.png)

Thanks you,
Regards
Guillaume

**Comment by wobba** [comment]
Can you update a bit to clarify your setup. How many items are needed to power the carousel, and for what values does it fail. Also does the size of the web part region matter?

**Comment by guillaume-kizilian** [comment]
If the Modern Search Webpart is big enough to display only 1 tile and you have 3 matching elements in the request, it should have the arrows ungrayed and more positional dots.
![image](https://user-images.githubusercontent.com/6792560/166418282-19eee53d-d52e-40ca-98f2-16d8809abb91.png)


I guess size of web part region matter only to the test, because if it's bigger, you'll need more matched news to see that it is not working correctly.

**Comment by guillaume-kizilian** [comment]
Never mind, found the issue.
I missed a parameter in page 2 (translated  : Number of elements to group together "3").
Setted it to 1 and it worked.

Sorry for your time. Thank you.

Regards,
