### ISSUE TITLE
Locale file for italian language not found

### ISSUE THREAD

**Issue by keccomoria** [microsoft-search/pnp-modern-search#2046]
**Version used**
4.6.1.0

**Describe the bug**
Locale file for italian language not found

**To Reproduce**
1. Select the "Italian" as preferred language in your browser profile (ex. Edge)
2. Edit a SharePoint page and add a "PnP Search Results" and "PnP Search Filters" webpart
3. Edit the webpart properties
4. Only "Available data sources" option is available (if setup done in other available languages, ex. english, the results are not visible)

**Expected behavior**
options for setup webpart and results available for italian language

**Screenshots**
<img width="297" alt="image" src="https://user-images.githubusercontent.com/16364003/165966963-10902712-eb4c-4799-832b-da1bee671a27.png">
<img width="919" alt="image" src="https://user-images.githubusercontent.com/16364003/165970995-ae8b1590-22b6-4871-9f98-2ca71e6ebff0.png">

**Desktop (please complete the following information):**
 - Edge (italian language profile)

**Comment by wobba** [comment]
Fixed in the dev branch

**Comment by SudhiDevAXA** [comment]
> Fixed in the dev branch

Hi, 
We need some help on this issue - we do not see the search results for Italy language. 
Do you have an update for this whether we can incorporate the latest change in our solution?
