### ISSUE TITLE
PnP Search Web Part -Sortable Column Setting Defaults to String Sort Regardless 'Edit Sort Order'

### ISSUE THREAD

**Issue by RamBalani** [microsoft-search/pnp-modern-search#2053]
**Issue is tied to sorting when 'Edit Sort order' is set to numerical sorting while at the same time a sortable column setting in Managed Column is set using the same column.**

Refinableint00 defined in 'edit sort order' has remedied. on entry to a PnP web part that the PnP list items can be sorted in ID  (List source) numeric ascending sequence as in the list source.

However -  tweaking 'on' a checkbox  on  the same column as 'Sortable. in the Managed Column page as reverts to string based sorting when sort is clicked as descending then back to ascending via click-enabled arrows.

To illustrate:
There are 15 list items on 1st PnP Results page, 1 thru 15 by ID# in numeric ascending ID sequence number on the PnP web part screen per page-show list items as 1,2,3,4,5,6,7,8,9....15.

When sortable column is clicked however to descending order - sort  reverts to string based sorting neglecting my 'Edit sort order' setting anchored to a RefinableInt00 (* crawled ows_ListItemID was mapped to RefinableInt00 in the schema, RefinableInt00 was used to 'Edit Sort Order;*)!

List page on PnP screen contains 15 list items (1 - 15 numerically ID'ed) - clicking  column sort order arrow to descending sort I expect to go 15,14,13,12,11,10,9,8...1 if sorted numerically--it does not, instead it shows cock-eyed again reverting to sorting as strings.
See attachment screen shots below.
-------------------
Sorts Correctly on initial screen presentation, i.e Edit sort order on Refinableint00 works as intended.
![Screenshot -on Entry REV3-ISO-13485-PnP-Use Web Part-Sorts correct](https://user-images.githubusercontent.com/37209670/166144750-f20c8113-d083-4d96-a57b-f8508f897eba.jpg)
===============
When Sortable column arrow clicked to descending order -- fails to maintain numeric list IT items sequences -ie. Sortable columns defaults to string based sequence sorting.
![Screenshot -on Entry REV3-ISO-13485-PnP-Use Web Part-SortClick-MuckedupShow5 ](https://user-images.githubusercontent.com/37209670/166144829-c8de69d6-55bf-4c08-9b34-8a895f91c177.jpg)
----------
![Screenshot -on Entry REV3-ISO-13485-PnP-Use Web Part-SortClick-MuckedupShow15](https://user-images.githubusercontent.com/37209670/166144837-84847822-6f0a-481b-a21d-3598b369da92.jpg)

**Comment by FranckyC** [comment]
Hi @RamBalani , just tested with the latest version and works as expected. Are you using the latest one? Because we've made some changes recently to the sort settings. I suspect you are using an old version with still a static sort on the details list olumns. See this blog post https://franckcornu.com/post/modern-search-overview-sort-control/

**Comment by wobba** [comment]
Closing, stale issue.

**Comment by RamBalani** [comment]
This wa sresolved eons ago-thanks.
