### ISSUE TITLE
[SearchBoxWebpart] Allow tokens in "Send the query to a new page/ Property Page URL"

### ISSUE THREAD

**Issue by edarroudi** [microsoft-search/pnp-modern-search#2055]
**Is your feature request related to a problem? Please describe.**
Since we can have different settings maybe dependent on user attributes (or other), it would be nice to be able to send search queries to a different url.

**Describe the solution you'd like**
I want this:
![image](https://user-images.githubusercontent.com/935493/166225562-2be4e442-d115-45b3-bfeb-6da3308383d2.png)

**Describe alternatives you've considered**
I can think of no other good solutions...

**Additional context**
![image](https://user-images.githubusercontent.com/935493/166225820-07ae2c46-118f-47e8-8601-4058a79486f6.png)

**Comment by FranckyC** [comment]
Thanks for the suggestion @edarroudi. It will be available in the next release. See #2125.
