### ISSUE TITLE
Search results not visible when changing language 

### ISSUE THREAD

**Issue by AlexanderDMA** [microsoft-search/pnp-modern-search#206]
**Version used**

3.6.3.0

**Describe the bug**
When the language for a user is not in the default language of the site, there are no search results available. 
In the debugger, I found following error message: 
Unable to get property 'ManageDetailsListColumnLabel' 
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/64209375/80108519-ad690000-857c-11ea-92a5-968d3542d695.png">

The default language on the site is English, and the language for the users profile was Dutch. 
I can test this with my account, and in English everything works fine, but when changing my language to Dutch i don't retrieve any results. 

**To Reproduce**
1. Add the pnp modern search app on a modern teamsite with default language = English
2. Add the "search results" app on a page and show some results
3. Change your language (in my case, it was changed to dutch) and wait until the SharePoint site is displayed in Dutch
4. Go to the page with the results, now it's not working anymore. 

**Desktop (please complete the following information):**
 - Tested with multiple browsers (Chrome, IE, Firefox) and in private sessions

**Comment by wobba** [comment]
Please test and repro with a newer version. 3.10 might be best as 3.11 has breaking changes for a few scenarios

**Comment by AlexanderDMA** [comment]
Thank you @wobba , now it works.
