### ISSUE TITLE
Refiner dont show filter for selected property

### ISSUE THREAD

**Issue by mayabank** [microsoft-search/pnp-modern-search#2061]
1. Property DOCUMENTTypeOWSTEXT added as refiner in Search Filter configuration

![image](https://user-images.githubusercontent.com/84386411/166630320-8dcaf8e3-6c38-4cfb-8cdf-b731a7ca2cd0.png)

2. When the search result render, the property is not shown on the Filter, while the value of the given property is available
![image](https://user-images.githubusercontent.com/84386411/166630468-f52797af-8ff5-496f-b2b0-9b8b694f9aa4.png)

3. In the postquery request filters are added 

![image](https://user-images.githubusercontent.com/84386411/166630967-4b28c75b-ba30-44aa-b4b5-8fa401d03e10.png)

4. In the postquery response only 2 refiner entries
![image](https://user-images.githubusercontent.com/84386411/166630532-db770191-e3d2-4812-93b4-f3764303b313.png)

Greatly appreciate if can advise if am missing anything to make it work.

Thanks and regards,
Mayank

**Comment by FranckyC** [comment]
Hi @mayabank, `DOCUMENTTypeOWSTEXT` is not a refinable search managed property. You must use the predefined ones like `RefinableStringXX` in the search schema and map the correct crawled property corresponding to your column. See https://docs.microsoft.com/en-us/sharepoint/search/how-to-add-refiners-to-your-search-results-page
