### ISSUE TITLE
Result types not working when using ressource."@odata.type" as data source field

### ISSUE THREAD

**Issue by IngoHenning** [microsoft-search/pnp-modern-search#2080]
**Version used**
4.6.1

**Describe the bug**
Using @odata.type in result types is not working. I tried to set up something like the All vertical but with PnP web parts. I set up sear result web part to use Microsoft Search and return drive, drive item, lists, list items and sites. I want to use different layout templates for these results. I tried to configure result types and choose resource."@odata.type" in the data source field drop down. Using this setting ends with an exception in console.

**To Reproduce*
1. Go to PnP Search Results web part settings and choose Microsoft Search as data source
![image](https://user-images.githubusercontent.com/71497033/167900007-6a5df194-c2ac-4402-8ad3-98233c59f681.png)

2. Click on Entity types to search and choose Drive, Drive items, List items, List and Sites
![image](https://user-images.githubusercontent.com/71497033/167900402-f1e69c9a-6785-442e-b93e-c79a85ec3622.png)

3. Go to page 2 of the settings and choose List as layout
4. Click on "Edit result types", open "Data source field" drop down and choose resource."@odata.type"
![image](https://user-images.githubusercontent.com/71497033/167901171-92af4e97-5efa-457c-ae70-66c1c2b8b998.png)

5. Add a condition
![image](https://user-images.githubusercontent.com/71497033/167901300-f91584a0-57e0-477a-93f8-d39e7f43dce5.png)

6. Save everything and publish the page
7. Open dev tools console and reload the page. The following error is shown
![image](https://user-images.githubusercontent.com/71497033/167901717-834fe8ac-e1c6-4e7d-9542-6d2d6004caa3.png)

**Expected behavior**
It should be possible to use @odata.type in result types otherwise it will not be possible to differentiate the returned results from graph api.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - Microsoft Edge Version 101.0.1210.39 (Official build) (64-bit)

**Additional context**
-

**Comment by FranckyC** [comment]
Hi @IngoHenning, good catch! Should be fixed in the next release by #2087. Thanks!
