### ISSUE TITLE
PnP Search web part version 3.15.3.0 pagination is not working properly and inconsistant when apply filter

### ISSUE THREAD

**Issue by Mani51** [microsoft-search/pnp-modern-search#2083]
**Version used**
Ex: 3.15.3.0

**Describe the bug**
I have applied settings to display 10 records per page and when the filter results are huge, they display in multiple pages. When i click on the second page in pagination, the relevant results are loaded but the pagination has disappeared and doesn't come back.

**To Reproduce**
1. Add Search Result webpart.'
2. Add Search Filter webpart
3. Configure all settings
4. Search and apply filter and click pagination

**Expected behavior**
It should go to next page and the filter should stay in place.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/17005401/168045420-60ddfc37-c3a2-4326-ad07-ffd5f8a19215.png)

![screenshot1](https://user-images.githubusercontent.com/17005401/168052392-0d6a27ae-0f81-45ab-a3ff-9ce24c975b97.png)

**Desktop (please complete the following information):**
 - Browser chrome, edgex

**Comment by Mani51** [comment]
Hi Wobba,

Is there any update on the above issue?

Thanks,
Mani

**Comment by kasperbolarsen** [comment]
Since v3 is not being updated anymore this case is closed
