### ISSUE TITLE
Cannot read properties of undefined (reading 'dynamicDataSourceManager')

### ISSUE THREAD

**Issue by jacksonv1lle** [microsoft-search/pnp-modern-search#2085]
**Version used**
3.23.0

**Describe the bug**
I have a page with the search results web part and search refiners web part. Both web parts are connected. 

I receive this JS error when I edit the page, save the page, and edit the page again:

    TypeError: Cannot read properties of undefined (reading 'dynamicDataSourceManager')

This causes the Search Refiners web part to display the 'No filter to display' message.

**To Reproduce**
1. Add Search Results & Search Refiners webparts to a page
2. Connect the two web parts together
3. Use the '*' wildcard for the search query keyword in the Search Results web part
5. Save the page
6. Refresh the page
7. Edit the page
8. Save the page
9. Edit the page

**Expected behavior**
The Search refiners continue to display correctly each time I edit the page

**Screenshots**
See attached video

**Desktop (please complete the following information):**
 - Browser: Chrome

https://user-images.githubusercontent.com/2648490/168264939-54116d12-e386-4acc-bb0a-db6231f97c6d.mp4

**Comment by kasperbolarsen** [comment]
Since v3 is not being updated anymore this case is closed
