### ISSUE TITLE
Link to another vertical from search results does not work - v4

### ISSUE THREAD

**Issue by MirasMNC** [microsoft-search/pnp-modern-search#2086]
**Version used**
4.5.4

**Describe the bug**
I have two Verticals (Contacts and Departments) and Search results (Contacts and Departments). Within Contacts search results I have a link to "Departments" vertical. Each contact works in some department. This value I use to create as a link to redirect to search Deparment results. Unfortunately it does not work. When I click on the link, the URL is changed but I stay still on the current "Contacts" vertical. Only when I refresh the page then the vertical is changed. I tried to use "target="_blank" and it also does not work. The link still loads in the same tab.

**To Reproduce**
1. Go to PnP Verticals set the parametr for default "v" and configure two verticals "Contacts" and "Departments"
2. Configure two search results (Contacts and Departments) with query to two different source.
3. Connect defined search results to verticals (Contacts > Contacts and Departments > Departments)
4. Within Contacts search results create custom template and add there <a href="https://TENANT.sharepoint.com/sites/intranet/SitePages/NAMEPAGE?v=Departments&q=*">department link</a>
5. Publish page and click on the link if you will be redirected to second vertical "Department"

**Expected behavior**
When click on the link that the vertical is changed and I see results from diffent source.

**Screenshots**
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/62887437/168482820-67587c0a-2753-46c8-afc3-4c22c08a3260.png">
<img width="914" alt="image" src="https://user-images.githubusercontent.com/62887437/168482845-a0f49ef2-4cde-481c-a959-c1bcd1ead5fd.png">

**Desktop (please complete the following information):**
Google Chrome 101.0.4951.54

**Comment by FranckyC** [comment]
Hi @MirasMNC, this behavior is due to the SharePoint page router. You must add the attribute `data-interception="off"` and `target="_blank"` to your `<a/>` link. It will refresh the whole page and the default selection should work.

**Comment by MirasMNC** [comment]
@FranckyC  thank you for fast reaction. I added the attribute and it works! Thank you
