### ISSUE TITLE
Uncaught (in promise) Error: Cannot find module './pt-pt.js'

### ISSUE THREAD

**Issue by HappytoGit** [microsoft-search/pnp-modern-search#2089]
**Version used**
4.6.1

**Describe the bug**
A clear and concise description of what the bug is. Keep questions and bugs related to the web parts. If the issue relates to KQL or question around crawled and managed properties please use [Microsoft TechCommunity](https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev). Which means, if you experience the same behavior in classic web parts, then it's not an issue with PnP Modern Search 😉

**To Reproduce**
1. Using Chrome profile with Portuguese Language (PT-PT) active
2. Go to a page with the 'PnP - Search Results' webpart active
3. Check console and search for the error: "Uncaught (in promise) Error: Cannot find module './pt-pt.js'" (first attached)
4. Edit Page and see only 2 pages of config of the webpart (second attached)

**Expected behavior**
Webpart should appear (no errors)

**Screenshots**
![CannotFindModule pt-pt](https://user-images.githubusercontent.com/43241911/168569634-7285ae60-d20c-459f-8889-81ee907c36cb.png)

![CannotFindModule pt-pt (Webpart Edit)](https://user-images.githubusercontent.com/43241911/168569865-58b92627-cce4-46b3-95a5-15c60b95fffd.png)
______________________________________________________________________________________________________________________________________________

**Desktop (please complete the following information):**
 - Browser Chrome (Latest)

**Additional context**
There is no problem if the browser is set to English (EN-US or EN-GB)

**Comment by HappytoGit** [comment]
Ok guys. I found the issue.

The was a missing language name in the DateHelper.ts file for the "pt-pt" culture.

I added a "pt" to the "momentTwoLetterLanguageName" array variable so that the culture check would split the "pt-pt" culture into "pt".

This way the momentJS can find the correct module.

I'll leve a picute of what I did.
![image](https://user-images.githubusercontent.com/43241911/169297306-2df51b00-f0f2-4364-85d8-7b5d2db9a972.png)

**Comment by HappytoGit** [comment]
I was wrong to close this.

This needs to be fixed for portuguese users.

**Comment by wobba** [comment]
I added pt-pt to the list which should result in pt. There's also "pt-br" which would be ignored with your change :)

**Comment by marcelo09714** [comment]
> Ok guys. I found the issue.
> 
> The was a missing language name in the DateHelper.ts file for the "pt-pt" culture.
> 
> I added a "pt" to the "momentTwoLetterLanguageName" array variable so that the culture check would split the "pt-pt" culture into "pt".
> 
> This way the momentJS can find the correct module.
> 
> I'll leve a picute of what I did. ![image](https://user-images.githubusercontent.com/43241911/169297306-2df51b00-f0f2-4364-85d8-7b5d2db9a972.png)

Onde encontras-te esse ficheiro? Não o consigo encontrar

**Comment by wobba** [comment]
@marcelo09714 what version are you using and what issue are you encountering? And best to log a new issue instead of commenting on old ones.
