### ISSUE TITLE
search results

### ISSUE THREAD

**Issue by tswah** [microsoft-search/pnp-modern-search#2092]
### Check existing issues before logging new ones
If you are not using the latest version, triage your issue with the latest version before logging as we won't provide patches to older versions.

### Issues related to data mapping, e.g. SharePoint columns to crawled properties to managed properties should be asked in the discussion section.

**For any question regarding Web Parts usage, please use the ["Discussions"](https://github.com/microsoft-search/pnp-modern-search/discussions) tab instead of creating a new issue.**.

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
Ex: 4.5

**Describe the bug**
A clear and concise description of what the bug is. Keep questions and bugs related to the web parts. If the issue relates to KQL or question around crawled and managed properties please use [Microsoft TechCommunity](https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev). Which means, if you experience the same behavior in classic web parts, then it's not an issue with PnP Modern Search 😉

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tswah** [comment]
We are using the Search Box, Search filter and Search Results in the SharePoint. Microsoft mentioned i should log the issue over here as it is not out of the box feature under SharePoint.

When doing a search, the results showing is not returning the correct icon and the preview image. See attached for the comparison between the Search within SharePoint site vs Search using the Web Parts. For example, when the search results return folder, the left screen shows folder icon whereas the right click shows non-folder icon. The expectation is to show word doc icon for word doc, ppt for ppt doc, folder icon for folder. Please enlighten.

Thank you

![image](https://user-images.githubusercontent.com/105707856/168764340-c3250b65-917d-4f8d-914d-3d31e7b1c7d0.png)

**Comment by wobba** [comment]
Please edit the original template and fill out all details requested. If not we cannot triage or replicate what you see. This is why the template is there, read it, don't ignore it :)
