### ISSUE TITLE
Filters web part causes 500 error in Search Results when searching by a name

### ISSUE THREAD

**Issue by JonoSuave** [microsoft-search/pnp-modern-search#2093]
This doesn't happen for every name, but some names (in this case Jack and Erik) will result in the following error: [HTTP]:500 - [CorrelationId]:da513ea0-6055-1000-c9a3-dc1b683432e9 [Version]:16.0.0.22504.

When I remove the customize filters from within the Search Filters filters web part the error goes away.
![Screen Shot 2022-05-17 at 10 56 50 AM](https://user-images.githubusercontent.com/22969971/168869277-174d6cda-0d0c-421c-9ec9-e67aebd1127f.png)
![Screen Shot 2022-05-17 at 10 57 07 AM](https://user-images.githubusercontent.com/22969971/168869281-c7e178fa-2987-4e5a-a6a7-d58319220a8e.png)

**Comment by wobba** [comment]
Incomplete submission. 500 errors are API issues so you would have to find something weird with the request. Or set up a replicate scenario with classic web parts and report it.
