### ISSUE TITLE
PnP Search Results v4 - Selected properties: not possible to select a managed property from the drop down list

### ISSUE THREAD

**Issue by ileana2019** [microsoft-search/pnp-modern-search#2095]
**Version used**
4.5.2.0

**Describe the bug**
In the Search results webpart properties, you cannot select any property in the Selected properties drop down list. 

**To Reproduce**
1. Go to the properties of the Search results webpart
2. Click on the drop down Selected properties

**Expected behavior**
The drop down should open and all the managed properties should be visible to select.

**Screenshots**
![Selected Properties](https://user-images.githubusercontent.com/55545989/169262224-22612485-1b4a-41c3-89be-baf86385102a.PNG)

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**
It used to be possible to type in the drop down list, the name of the managed property, then hit enter; But even that is not possible anymore.

**Comment by wobba** [comment]
This is a know issue at times as the "API" used to fetch properties is a non-api. We plan to change the dropdown to a fixed list instead. As a workaround enter the managed property name manually in the combo box and hit ENTER. That will add it to the list of retrieved properties.
