### ISSUE TITLE
pnp-modern-search edit result types query for people results

### ISSUE THREAD

**Issue by marting1010** [microsoft-search/pnp-modern-search#210]
I want to use the edit result types option to display people results in a different layout to other search results (when used in conjunction with a people search vertical). l want people to have the same layout as when you click on the people result type. So I thought I could select edit result types, have contentclass = urn:content-class:SPSPeople as the condition and copy in the layout you see from the people result type (I copied the content from the edit template option when clicking on the People result type (see the 1st image below)). It seems to recognize the condition but it doesn't render properly. See the second image. Can I do this please or do I need to do something different for this to work?

how I got the layout for people result type
![Screenshot_10](https://user-images.githubusercontent.com/55257720/80237850-4cf9c180-8655-11ea-93c9-efefcab7f409.png)

rendering image 
![Screenshot_11](https://user-images.githubusercontent.com/55257720/80237860-53883900-8655-11ea-825d-a61d6055a1af.png)

**Comment by wobba** [comment]
`contentclass contains SPSPeople` should work and I've set this up before.

**Comment by marting1010** [comment]
I don’t think it’s the identification of contentclass = spspeople that’s the problem as it’s trying to change the layout to the standard layout, but there must be a problem with what I have in the inline template definition in here:

[cid:image001.png@01D61A94.43B166F0]

I have this in here which I copied from the people template.

<content id="template">

    <style>
        #pnp-modern-search_{{@root.instanceId}} .personaCard {
            margin: 10px;
        }
    </style>

    <div id="pnp-modern-search_{{@root.instanceId}}" class="template_root">
        {{#if @root.hasPrimaryOrSecondaryResults}}
            <div class="template_defaultCard">
                {{#if showResultsCount}}
                <div class="template_resultCount">
                    <label class="ms-fontWeight-semibold">{{getCountMessage @root.paging.totalItemsCount keywords}}</label>
                </div>
                {{/if}}
                <div class="ms-Grid">
                    <div class="ms-Grid-row">
                        {{#each items as |item|}}
                        <div class="ms-Grid-col ms-sm12 ms-md12 ms-lg12">
                            {{#> resultTypes item=item}}
                                <div class="personaCard">
                                    {{#with (split AccountName '|')}}
                                        <pnp-persona-card fields-configuration="{{JSONstringify ../../../peopleFields}}" item="{{JSONstringify item}}" persona-size="{{../../../personaSize}}" />
                                    {{/with}}
                                </div>
                            {{/resultTypes}}
                        </div>
                        {{/each}}
                    </div>
                </div>
            </div>
            {{#if @root.paging.showPaging}}
                <pnp-pagination
                    total-items="{{@root.paging.totalItemsCount}}"
                    hide-first-last-pages="{{@root.paging.hideFirstLastPages}}"
                    hide-disabled="{{@root.paging.hideDisabled}}"
                    hide-navigation="{{@root.paging.hideNavigation}}"
                    range="{{@root.paging.pagingRange}}"
                    items-count-per-page="{{@root.paging.itemsCountPerPage}}"
                    current-page-number="{{@root.paging.currentPageNumber}}"
                >
                </pnp-pagination>
            {{/if}}
        {{else}}
            {{#unless showBlank}}
                <div class="template_noResults">{{@root.strings.NoResultMessage}}</div>
            {{/unless }}
        {{/if}}
    </div>
</content>

<content id="placeholder">
    <div id="pnp-modern-search_{{@root.instanceId}}" class="placeholder_root">
        <div class="template_defaultCard">
            <div class="ms-Grid">
                <div class="ms-Grid-row">
                    {{#times @root.paging.totalItemsCount}}
                        <div class="ms-Grid-col ms-sm12 ms-md12 ms-lg12">
                            <pnp-persona-card-shimmers persona-size="{{@root.personaSize}}"></pnp-persona-card-shimmers>
                        </div>
                    {{/times}}
                </div>
            </div>
        </div>
    </div>
</content>

It then looks like this on the page:

[cid:image002.png@01D61A94.43B166F0]

Regards,
D. Martin Griffiths
IT Development Manager - IT
For and on behalf of Geldards LLP
________________________________

Direct Dial: +44 (0)29 2039 1796 - Direct Mobile: +44 (0)7425 629539
Email: martin.griffiths@geldards.com<mailto:martin.griffiths@geldards.com>

**Comment by FranckyC** [comment]
Hi @marting1010, you can use the following condition in the result types:

> contentclass 'Contains' SPSPeople

![image](https://user-images.githubusercontent.com/5659122/80281903-67c34900-86dc-11ea-8f10-596e685d769a.png)

Then use this template to render a persona item:

```
<style>
    
    .template_listItem {
        min-height: 10px;
    }
    
</style>
<div class="personaCard">
    {{#with (split AccountName '|')}}
        <pnp-persona-card 
            data-persona-size="4" 
            data-image-url="/_layouts/15/userphoto.aspx?size=L&username={{[2]}}"
            data-text="{{../FirstName}} {{../LastName}}"
            data-secondary-text=""
            data-tertiary-text="{{[2]}}"
            data-optional-text="{{../WorkPhone}}"
        />
    {{/with}}
</div>
```
![image](https://user-images.githubusercontent.com/5659122/80281994-eb7d3580-86dc-11ea-9151-2c77104cd2cd.png)

Don't forget to add required selected properties in the Web Part settings (here `AccountName` `FirstName`, `LastName`, `WorkPhone`).

**Comment by marting1010** [comment]
Hi there @FranckyC , thank you for looking at this for me. I've tried that now and it behaves differently but still showing the details I need. 

![Screenshot_16](https://user-images.githubusercontent.com/55257720/80369954-07243f80-8887-11ea-9c56-a575b5d113e5.png)

It doesn't seem to resolve against any returned people. What does the [2] do in your script? I'm wondering if that is different on your environment to mine. Those four fields are listed in the selected properties by the way.

![Screenshot_17](https://user-images.githubusercontent.com/55257720/80370121-566a7000-8887-11ea-9c8b-5baa2937a395.png)

**Comment by FranckyC** [comment]
The `[2]` is for the previous `(split AccountName '|')`. What if you use the debug layout, is there a value for those fields especially `AccountName`?

**Comment by marting1010** [comment]
Oh of course. Yes there is values in the AccountName field in the format " "AccountName": "i:0#.f|membership|joe.bloggs@abc.com"". Does that numbering start at 0 or 1 in which case it should be [3]?

**Comment by FranckyC** [comment]
Do you use the latest version? If not, remove the `data-` prefix for attributes.

**Comment by marting1010** [comment]
The version I downloaded on April 13th was 3.11.1 so that's the latest version isn't it? Well the good news is taking data- off the attributes seems to work up to secondary text. the tertiary-text and optional-text attributes don't seem to contain content whether I have data- in front or not. There are data in the fields I'm asking it to show though (checked in debug).

**Comment by FranckyC** [comment]
Hi @marting1010 yes 3.11 is the latest. With this version, you must prefix attribute with `-data` to get it work. To ensure you have data for those managed properties, you can use the Debug layout. Also you can inspect the DOM after the initial render to see if attributes get populated.

**Comment by marting1010** [comment]
Ok thanks, @FranckyC . I tried this so basically re-instated data- in front of tertiary-text and optional-text. I can't see those values in debug mode BUT when going into DOM Explorer they do contain content. They're just not shown when the web part renders i.e. they're not not rendering because they're blank.

**Comment by FranckyC** [comment]
Hi @marting1010 , maybe related to #232 . Can you try with the latest branch on develop? I've made a PR related to it.

**Comment by tom-daly** [comment]
I am facing the same issue - I am trying to use a custom set of values for the search tabs and different template for people values [same as above] 

I am not seeing "AccountName" in debug mode? do you have any suggestions? 

![image](https://user-images.githubusercontent.com/9259305/83710760-752ef580-a5ef-11ea-8d3f-fb587dfdf093.png)

**Comment by FranckyC** [comment]
Hi @tom-daly , can you send the template markup for the result type you use for people? Maybe it is just a wrong property path.

**Comment by tom-daly** [comment]
strange it's showing today. I was working with it for a few hours yesterday and it was not showing on the one page but it was there on a separate page different configs. If i notice any odd i will report back. thanks for the quick reply.

**Comment by ballapalli** [comment]
hi for this below code, how to add link to delve or live activity card?
<style>
    
    .template_listItem {
        min-height: 10px;
    }
    
</style>
<div class="personaCard">
    {{#with (split AccountName '|')}}
        <pnp-persona-card 
            data-persona-size="4" 
            data-image-url="/_layouts/15/userphoto.aspx?size=L&username={{[2]}}"
            data-text="{{../FirstName}} {{../LastName}}"
            data-secondary-text=""
            data-tertiary-text="{{[2]}}"
            data-optional-text="{{../WorkPhone}}"
        />
    {{/with}}
</div>
