### ISSUE TITLE
PnP Modern Search Not Show Webpart "PnP Search Result"

### ISSUE THREAD

**Issue by mirkodesimone7** [microsoft-search/pnp-modern-search#2107]
**Describe the bug**
Hi,
i've deployed the PnP Modern Search on my SharePoint Online Site Collection.
When i try to configure the webpart "PnP Search Result" i don't see the tab for configuration in the edit section of webpart (like image).
![image](https://user-images.githubusercontent.com/106141129/169969226-1209bac2-57e6-49f2-b28f-539014545ed7.png)
I know that i should see 4 section instead 2.
When i publish the page i don't see the webpart but i see a blank section.

**Version used**
4.6.1.0

**Screenshots**

**Desktop:**
 - Browser [Chrome, Edge, Firefox]

**Comment by FranckyC** [comment]
Hi @mirkodesimone7, do you have any error message in the browser console (F12)? I suspect this because your current display language is not supported and the Web Part does not find resource files. Waht if you try to switch your language to english?

**Comment by mirkodesimone7** [comment]
Hi @FranckyC, thanks for the rapid answer.
Changing Display Language (from my profile) to "English" the webpart works!
I attach some info from browser console.

![cat1](https://user-images.githubusercontent.com/106141129/170215226-becd2fa4-d968-49d3-9a02-df9c2c32678a.JPG)
![s2](https://user-images.githubusercontent.com/106141129/170215229-021a6de1-463e-40ba-a166-9c333066c91c.JPG)

Do you think that in the future the italian language will be supported?
Thanks a lot

**Comment by wobba** [comment]
This was fixed with #2046 (it-it) so will be part of the next release.

**Comment by SolidFighter69** [comment]
The problem also affects the german language. I have the same problem.

**Comment by wobba** [comment]
@SolidFighter69 you need to log a separate issue. `de-de` was fixed with #2006 in v4.6.1
