### ISSUE TITLE
PnP Search webpart is showing only 500 records.

### ISSUE THREAD

**Issue by nareshgmail** [microsoft-search/pnp-modern-search#2111]
**Version used**
4.6.1.0

**Describe the bug**
PnP Search webpart is showing only 500 records.
we have 2 lists(located in different site collection) which have more than 2000 records and configure the search webpart to show the data, after build the query it is showing items count as 1503, but after 500th record the search result webpart is showing as blank. we used paging feature also each page shows 50 records, from 11th page the results are empty. Please let me know if there is any setting should be enabled to show more than 500 records.

**To Reproduce**
1. Add the Search Results webpart to a page
2. enable the paging on search results webpart
3. number of items to per page set as 50
4. if the result count more than 500 then select the page number 11.

**Screenshots**
![image](https://user-images.githubusercontent.com/18656166/170710255-f624c1b4-f1c8-4c4b-a31a-98f68cf58397.png)

When i click on 11th page, it is showing blank

**Desktop (please complete the following information):**
chrome, Edge

**Comment by FranckyC** [comment]
Hi @nareshgmail, if I remember correctly this is a hard limit from the API and we can't do anything about that. Just to make sure can you inspect the network tab when clicking on the 11th page and look for the `postquery` call, especially the request payload data?

Also browsing the 11th page to get your correct result seems to be a poor search experience design. As a best practice, you could benefit from refiners, search box and verticals to narrow the search and avoid this use case.

**Comment by wobba** [comment]
If you used to depend on paging for more than 500 results and cannot page beyond 500 results today you should log a ticket with Microsoft support about this as well as log this at https://github.com/SharePoint/sp-dev-docs.
