### ISSUE TITLE
Search Results don't reset when search box text is removed and a Default value is used

### ISSUE THREAD

**Issue by clayjam** [microsoft-search/pnp-modern-search#2113]
**Version used**
4.5.4

**Describe the bug**
I have a Search Box, Search Results and Search Refiner web parts. The Search Results web part has its Default Value property set to * so it loads documents without any text inputted. I want this behaviour as it allows users to immediately use the Filters web part to find documents. With this setup if a user enters text in the Search box the results filter correctly, however if you remove all the text in the search box and hit the Enter key nothing happens, the previous search term is still in use and because there is no text in the search box you can't clear the results as the (X) which clears the text only shows when there is some text in the search box.

**To Reproduce**
1. Configure Search Results to have a Default Value of *
2. Enter text into the Search Box to filter some results and hit the Enter key
3. Remove all the text in the Search Box and click Enter key and nothing happens. You also can't clear the filter as the (X) doesn't show

**Expected behavior**
If I remove all the text in the Search Box and hit the Enter key, I would like the same behaviour as clicking the (X) to clear the Search Box. This will show all documents as the Default Value is set to *

**Screenshots**
![github search](https://user-images.githubusercontent.com/29591956/170444576-17672207-efdd-45bc-b6ef-391fedfa854a.jpg)

**Desktop (please complete the following information):**
 - Browser Edge

**Comment by wobba** [comment]
This is by design, as we don't have "search as you type" or allow search for a "blank" value. I suggest adding a hyperlink to the result template or above the search box with "Reset" search, re-navigating to the same page you are at.

**Comment by clayjam** [comment]
Thanks for your idea.
This user experience doesn't work when the Search Results uses a default value.

**Comment by wobba** [comment]
@clayjam It's the same as OOB search. By default you get a wildcard query if you navigate to search.aspx. You query something. Then if you remove your query, nothing happens. Same if you have a deeplink with query to e.web search. Clearing the search box will not revert to the original query.

To support this you would need some flag to say "re-issue original query if query is blank". I'm not saying the scenario is not understood, just that the current search box is not designed to query if it's blank. Default query is part of the search result web part, not the search box. Thus the search box has to change to support the scenario of triggering for empty searches.
