### ISSUE TITLE
GP0 in column at search Term Store

### ISSUE THREAD

**Issue by chris883773** [microsoft-search/pnp-modern-search#2120]
**Version used**
v4

**Describe the bug**
Hello,
i am using some terms of term store. So i used it for the status of a project in a content type.
![image](https://user-images.githubusercontent.com/50053446/170992475-86788ee0-5368-4daf-9d81-f0b4f553af3c.png)
I want to show this status in the search results. But i had only a "GP0-#xxxxxxxxxxxxxxxxx" number in the column. 
![image](https://user-images.githubusercontent.com/50053446/170992830-62d12eba-6bbe-4696-92f9-64c3d1340b83.png)

I saw the words from my term store.  The column calls owstaxIdStatus. I think that is only the view in my manage columns, but maybe some other have the same problem and it is a bug. 

Thank you for help.

**Comment by FranckyC** [comment]
Hi @chris883773, to work with translatations, you need to enable the localization in the search results Web Part options and update the the property `owstaxidmetadataalltagsinfo` in the slots configuration to `Autoowstaxidmetadataalltagsinfo`

![image](https://user-images.githubusercontent.com/5659122/171185244-6fc1f447-b14f-4eda-9858-4c0a90e67c66.png)

![image](https://user-images.githubusercontent.com/5659122/171185413-9de9c046-ea65-4ac0-b41e-ce13ac4155dd.png)

Then in your Details List column, use this slot using the following Handlebars expression:

![image](https://user-images.githubusercontent.com/5659122/171185916-ee209db9-554b-4a27-a2ee-cdd3df16ab3b.png)

**Comment by chris883773** [comment]
Great. Thank you.
