### ISSUE TITLE
Search vertical won't pass keyword across other vertical pages

### ISSUE THREAD

**Issue by tvakisai** [microsoft-search/pnp-modern-search#2130]
I am experiencing this same issue on Version: 4.6.1.

I am using the {SearchBoxQuery} token to pass the search text to a separate page. It works if there is a search keyword typed but passes **undefined** if there is the query is empty.

![VerticalsTest](https://user-images.githubusercontent.com/11034351/171629673-cd09e6f4-3e8a-4b2b-a118-a712aafeb042.PNG)

_Originally posted by @tvakisai in https://github.com/microsoft-search/pnp-modern-search/issues/461#issuecomment-1144809719_

**Comment by FranckyC** [comment]
Can you try with `{inputQueryText}` or `{searchTerms}` instead?

**Comment by tvakisai** [comment]
> Can you try with `{inputQueryText}` or `{searchTerms}` instead?

Thanks Frank

I had tried to use {searchTerms} and that also passes undefined.

{inputQueryText} works when a search term is available but when there is no search term, it is not replaced in the URL resulting in the search box having that value on load.
![VerticalsTest2](https://user-images.githubusercontent.com/11034351/171647620-8a0367f5-960d-467a-94db-898ed7be6fe4.PNG)

**Comment by FranckyC** [comment]
I'm able to reproduce the issue and a fix has been pushed to develop #2132. Will be available in the next release early or mid June.
