### ISSUE TITLE
PnP Modern Search - Sorting options not working in French UI

### ISSUE THREAD

**Issue by roroinlondon** [microsoft-search/pnp-modern-search#2136]
**Version used**
4.6.1

**Describe the bug**
I set the Search Results sorting option to sort the managed properties 'SPTranslationLanguage' and 'Title'.
It works fine with the default UI language: en-US.
But iI get a 500 error with the French UI.

**To Reproduce**
1. Go to 'Edit sort settings' in the Search Results web part.
2. Add the field 'SPTranslationLanguage'.
3. Check the box "Sort by default'.
4. Add the field 'Title'.
5. Check the box "Sort by default'.
6. Publish the page.
7. In a browser set in English, the sort works fine.
8. Change the UI language of your browser in French, you should get an error 500...

**Expected behavior**
The behavior of the sorting should be the same with any language.

**Screenshots**
<img width="916" alt="image" src="https://user-images.githubusercontent.com/6698103/172353267-002da942-30e2-4672-9cdd-5948c308fa3f.png">
<img width="634" alt="image" src="https://user-images.githubusercontent.com/6698103/172353328-ee21a1f3-6f76-4c17-8f2f-e11d78912b0d.png">

**Desktop (please complete the following information):**
 - Browser Chrome / Edge

**Comment by FranckyC** [comment]
Hi @roroinlondon, it seems to be an API issue and not necessarily related to the language in my opinion. The `Title` property is not sortable in the search schema by default so the `HTTP 500` is expected. To sort on title, you must use a `RefinableStringXX` property mapping the same crawled properties as `Title`.

**Comment by renewtx** [comment]
Hi -- I am seeing a similar issue with sorting not working but in the default language (English).  Not sure if I am missing something in the configuration of if this is a bug -- best i can tells i have it correctly configured .  I posted this under discussions in case I am just missing something [(https://github.com/microsoft-search/pnp-modern-search/discussions/2265) ], but so far no responses.

I am using one of the Refiner properties provided out of the box to which I mapped one of my crawled properties

Thanks

**Comment by wobba** [comment]
`SPTranslationLanguage` and `Title` are not a sortable managed property. Will close.
