### ISSUE TITLE
Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart)

### ISSUE THREAD

**Issue by nikkelje** [microsoft-search/pnp-modern-search#2149]
Hello All,

I am working with my IT department to install the pnp Modern Web parts.  After it was installed, I am getting this message when I add the webpart to a Sharepoint page.

[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Manifest not found for component id "96dcffa8-2c69-47ec-ba5c-770213aeb4fe" and version "1.0.0".

INNERERROR:
Manifest not found for component id "96dcffa8-2c69-47ec-ba5c-770213aeb4fe" and version "1.0.0".
CALLSTACK:
t@https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_a75f6966d7bb57c053063897431fa506.js:70:214440
t@https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_a75f6966d7bb57c053063897431fa506.js:71:7680
self.spModuleLoader</ff4n/e.buildErrorWithVerboseLog@https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_a75f6966d7bb57c053063897431fa506.js:71:44944
self.spModuleLoader</ff4n/e.buildLoadComponentError@https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_a75f6966d7bb57c053063897431fa506.js:71:41035
PypK/O/<@https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_8ba778ca573ea69fc754.js:1:6012

Can someone help me understand what is gone awry?  As mentioned, I didn't do the install, so can't speak to what was done exactly, so am hoping you can give me some hints on what I should ask them to look for.

Thanks!

**Comment by FranckyC** [comment]
Hi @nikkelje, di you check the **Make this solution available to all sites in the organization** option when deploying? By default we use the `"skipFeatureDeployment": true` flag in the package:

![image](https://user-images.githubusercontent.com/5659122/174450020-6bd38ce9-ccc7-43b1-9a9c-eef461397be9.png)

**Comment by nikkelje** [comment]
I checked with my IT partner, and he said that had checked that on.

**Comment by wobba** [comment]
It's quite common to get the error right away or if upgrading, but it should go away. You can try to delete the solution and re-add it as well.

**Comment by colonelclaypoo** [comment]
Hi, I'm experiencing the same issue (4.7.0. but even before with 4.6.1.). What I'm noticing at the moment is that if I clear my browser cache upon the first reload the search results webpart will show just fine. However, entering the page edit mode oder simly reloading the page will provoke the error again.
Was able to confirm this behaviour multiple times on one page and on multiple. Can I provide something that could be of use? Thanks.

**Comment by wobba** [comment]
This has nothing to do with the web parts but with SPFx and caching. Delete and re-add, or just re-upload typically resolves it.
