### ISSUE TITLE
Preview Pane does not work when selection is enable

### ISSUE THREAD

**Issue by MrBadou** [microsoft-search/pnp-modern-search#2151]
Hello,

I use the cards template layout, and when activate the preview and at the same time i enable the selection of the results, the preview pane does not open.

It does not work either with the list template.

I don't have an error either, it just does the selection wherever i click on the card.

Thank you.

**Comment by FranckyC** [comment]
Hi @MrBadou, should be resolved in the next release. If you need a workaround right now for the List layout you can use this attribute in the template. Thanks!

![image](https://user-images.githubusercontent.com/5659122/174452154-6580fc0d-52b4-4eb0-ae0d-475337ca142d.png)
