### ISSUE TITLE
Paging is not displayed after entering a search term via suite bar search box 

### ISSUE THREAD

**Issue by mavuongfellowmind** [microsoft-search/pnp-modern-search#2160]
**Version used**
4.6.1.0

**Describe the bug**
I created a custom search center and linked it to the search box in the Suite Bar.

When I type in a search term, I land on the Custom Search Center, the search results webpart also shows the correct results based on the search term.

However, the paging is not displayed even though there are more results (number of results is greater than number of max items per paging).
This behavior only occurs when searching from the search box in the suite bar.

As soon as I reload the page, the paging is displayed. Once the paging is visible and you enter a new search term in the search box, the paging is still visible.

**To Reproduce**
1. Create a page and configure the PnP Modern Search Webpart on this page with the following settings:
![image](https://user-images.githubusercontent.com/87697791/174612213-7aecd29c-c165-405b-88d0-5b7f1141310c.png)
2. Make sure to configure a KQL, which shows random items and set the maximum number of items per paging lower than the number of the results.
2. Go to "Search settings" on site level and enter the page URL where the PnP web part is located:
![image](https://user-images.githubusercontent.com/87697791/174612657-22ba2e6e-5463-43a4-92e2-45c382901069.png)
3. Go to the site homepage and enter a search term in the search box in the suite bar. Press enter. You should land on the page.
4. The paging should now not be displayed.

**Expected behavior**
Paging should be immediately visible as soon as I enter a search term via the search box in the Suite bar and then land on the Custom Search Center. This worked fine before. The problem was suddenly there at some point.

**Comment by wobba** [comment]
I cannot repro this. Pagination shows just fine. I'm using the details template.

**Comment by mavuongfellowmind** [comment]
> I cannot repro this. Pagination shows just fine. I'm using the details template.

I have switched to the details template. Unfortunately, the behavior is also the same with this template. Paging is not showing, only after reloading the page.

**Comment by wobba** [comment]
Do you have other SPFx extensions/webparts running?

**Comment by mavuongfellowmind** [comment]
> Do you have other SPFx extensions/webparts running?

We have LiveTiles as a framework in use. LiveTiles itself comes with many SPFx extensions. The display of the paging via the suite bar search box has suddenly stopped, a few days ago it still worked.

**Comment by wobba** [comment]
I suggest setting up a clean page/site where only PnP Search runs to see if you still have repro. Could very well be other SPFx code interfering somehow.

**Comment by kasperbolarsen** [comment]
@mavuongfellowmind any updates on this issue?
