### ISSUE TITLE
Multiple grouping on Search Results

### ISSUE THREAD

**Issue by MaxMattiello** [microsoft-search/pnp-modern-search#2161]
I'm developing a search result page for my customer where i've the need to display document library records like a Windows explorer view where a item could be nested inside a folder and i want to use the grouping option in order to display one level for each folder structure.
Is there a way to achieve this requirement with the actual functions? If not there is the possibility to improve Grouping functions for search result element?

Thanks

**Comment by MaxMattiello** [comment]
Thanks, i will try to do what you suggest. Is it possible to think the implementatio of at least 2 grouping levels like is present on the standard SharePoint list?

**Comment by wobba** [comment]
Maybe.. using handlebars functions and css/html. Except you cannot do click events in the html templates, as that is blocked. If you need click event you need to develop a custom web component and do your grouping/logic there.
