### ISSUE TITLE
http 500 error in PnP Search result web parts

### ISSUE THREAD

**Issue by wardvanweyenbergh** [microsoft-search/pnp-modern-search#2166]
We receive the following HTTP error when the search result web part is loading results:
[HTTP]:500 - [CorrelationId]:0d7d49a0-9081-4000-5f97-848097635e51 [Version]:16.0.0.22608

This happens for all the web parts we have already added in the environment and also if we add a new one and use the default configuration. 

We already installed the latest version but it did not solve the issue. 

Any idea where we can find more information?

**Comment by rikehuman** [comment]
Same for me today. Yesterday all web parts worked fine but today [HTTP]:500 - Internal Server Error [CorrelationId]:fe7e49a0-50a2-4000-84f8-bdc3baa1aae8 [Version]:16.0.0.22608

**Comment by Mark-1783** [comment]
Just as above... started today [HTTP]:500 - [CorrelationId]:9c7e49a0-f09b-4000-3fa3-83fff42dedb1 [Version]:16.0.0.22608...
