### ISSUE TITLE
Guide Text in the Template URL field

### ISSUE THREAD

**Issue by kasperbolarsen** [microsoft-search/pnp-modern-search#2169]
**Version used**
 4.7.0 beta

**Describe the bug**
The text in the "Use an external template URL" field ( Result web part) reads "https://myfile.json" when using the Adaptive Cards option and a custom template.

![image](https://user-images.githubusercontent.com/20593570/175032918-3b373ed4-3000-428f-b0ba-c0060280e527.png)

However the error mesage seems to indicate that it should have been a HTML file 
![image](https://user-images.githubusercontent.com/20593570/175033486-a10b48a8-58d8-454b-82c7-6f6aa6857427.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**

**Comment by FranckyC** [comment]
Hi @kasperbolarsen, good catch! Will be fixed in the upcoming release. Thanks!
