### ISSUE TITLE
PnP Search Result Web Part - Regex is failing in Handlebar template 

### ISSUE THREAD

**Issue by shariq1379** [microsoft-search/pnp-modern-search#2173]
**Version used**
Ex: 4.2.3

**Describe the bug**
MS Search API shows GUID in description which we have raised ticket to Microsoft.
Meanwhile, I have applied changes in handle bar template to replace GUID with space("") using regex and it works fine, but fail in one case. It replace "-"  also from summary.

{{getSummary (replace (slot item @root.slots.Summary) (regex '[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?' (slot item @root.slots.Summary)) '')}}

Example:
When I search "world-class" in search box and then the search result web part shows "worldclass" in summary. Regex remove "-" and show "worldclass" in summary.  

**To Reproduce**
1. Search "world-class" in search box
2. PnP Search result shows "wordclass" in summary

**Expected behavior**
Regex should follow correct pattern in handle bar template and should not replace "-" 

**Screenshots**
Attached
![image](https://user-images.githubusercontent.com/77804584/175109326-d1e09e76-eeb4-441d-ac80-cedbf2396c43.png)

**Desktop (please complete the following information):**
 - MS Edge & chrome

**Comment by wobba** [comment]
In OOB search for Microsoft we clean out leaking guids in the summary, and there has also been a change in how SharePoint pages are indexed to avoid web part guids to be indexed.

That said, I don't think the regex is what is removing the hyphen for you. I would check the network trace on what is actually coming back on the response to see if the hyphen is removed server side. We also don't control the logic of the handlebar helpers `regex` function. So will close this.
