### ISSUE TITLE
Forum for discussion

### ISSUE THREAD

**Issue by GTEM19889** [microsoft-search/pnp-modern-search#218]
I have watched the video on Youtube several times as I need to produce something which this webpart seems perfect for. I have several questions and struggle to follow this extremely long video (or probably fall asleep before I get to the end :) )

Would appreciate s forum to allow people that follow this to ask questions about it. (This would also give you an idea of what people struggle with and how to make this more user friendly in tutorials)

I thought github might offer a forum for discussion but if it does I cannot seem to find it anywhere.

Some of the questions I have.
1. How to define KQL query to only search one column in List
2. Why can I not find a Column in Selected Properties
3. Nor can I see the column in Manage Columns
4. How can I change what happens when the results are clicked on in "Edit template" (e.g. when I click on item it opens the item in "Edit item" but my result is a Video and I want it to play the video instead.

Looks like a fantastic system you have created, I think the use will increase if it is easier to get help on how to use it. (I do appreciate that you have put a lot of effort into the training video already)

**Comment by wobba** [comment]
TechNet used to be the place to ask questions about KQL and search workings. SharePoint Stack Exchange would probably work.

That said, I'll give some short answers.
1. In the case of list columns you need to find the crawled property matching your SP column and map it to a queryable managed property. I cover some of this in my SPO troubleshooting book, and you find bits and pieces in the official docs around crawled/managed properties. For site columns there are autogen managed properties you can query against.
2. Not all props are listed, as there is no real API to list the mp's. You can enter manual names as well if you know the name.
3. See 1
4. This is autofixed in the dev branch or wait for the next release.

**Comment by GTEM19889** [comment]
Thank you for your kind response, I did look at TechNet before posting here but could not find anything specifically related to PNP Modern Search there so thought I would try and post here. If you have existing Forums at either TechNet or StackExchange then please post the link here.

I did also post on TechNet to see if I get a response. Just thought it would be handy if you had your own forum, however now that I have posted here in what is called "Issues" it does seem to act a bit like a forum, however I thought it might just be for issues??? (Forums tend to get users to help one another out with answers instead of programmers having to answer to all issues)

As for the rest of your answers. 
1. Where do I find your book then? 
2. How do you find out what the name is? I have tried the name of the column but nothing returns when I use it, 
4. It's not just the autofix I need, would like to know how to alter the code in the template as for other results I might wish for something else to happen.

Thanks again for the response.

**Comment by wobba** [comment]
Your questions are generic SharePoint search ones, going back to SP2013 🙂 I have two book: https://www.amazon.com/s?i=stripbooks&rh=p_27%3AMikael+Svenson&s=relevancerank&text=Mikael+Svenson&ref=dp_byline_sr_book_1 Search queries you can find as posts on my blog as well.

3. There's a convention how this works. On my phone and don't have the exact docs at hand to explain it. Typically Column Name -> ows_ColumnName (cp)

4. not really doable in handlebars, hence the fix to make preview work for most file types.

**Comment by FranckyC** [comment]
Close it for now since it is more a question than an a real issue.
