### ISSUE TITLE
Selected Properties drop-down limitation

### ISSUE THREAD

**Issue by adecaes** [microsoft-search/pnp-modern-search#2184]
**Version used**
Ex: 4.6.1

**Describe the bug**
The Search Results web part Selected Properties drop-down is limited to 1,000 items followed by any custom properties defined in the web part. The last item shown changes daily as managed properties change, but it consistently stops at 1,000 (see screenshots).

**To Reproduce**
1. Go to Search result WebPart settings
2. Click on Selected properties

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15139134/176200378-756246a3-19d1-4b93-8b27-e10fb919e5f4.png)

**Desktop (please complete the following information):**
 - Browser (Edge)

**Comment by wobba** [comment]
We request 50.000, so 1000 seems to be an API issue we cannot do anything about. This is a limitation on the number of values returned for a refiner/filter.
