### ISSUE TITLE
PnP Search Results: Cannot read properties of undefined (reading 'Name')

### ISSUE THREAD

**Issue by ThexTobi** [microsoft-search/pnp-modern-search#2185]
**Version used**
v4 June 2022 (Pre-Release)

**Describe the bug**
PnP Search results throws error when integrated into page.
(First use ever)

**To Reproduce**
1. Generate German Site
2. Add PnP Search Results Web Part
3. Encounter Error

[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-42df-47c3-94d6-017428cd2baf" (pnpSearchResultsWebPart). Original error: Failed to load entry point from component "544c1372-42df-47c3-94d6-017428cd2baf" (pnpSearchResultsWebPart). Original error: Error loading https://component-id.invalid/544c1372-42df-47c3-94d6-017428cd2baf_4.6.1
	Cannot read properties of undefined (reading 'Name')

INNERERROR:
Failed to load entry point from component "544c1372-42df-47c3-94d6-017428cd2baf" (pnpSearchResultsWebPart). Original error: Error loading https://component-id.invalid/544c1372-42df-47c3-94d6-017428cd2baf_4.6.1
	Cannot read properties of undefined (reading 'Name')
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_17c61e51d8e2dc1831efaf516caf4f52.js:70:214284)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_17c61e51d8e2dc1831efaf516caf4f52.js:71:7974)
    at e.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_17c61e51d8e2dc1831efaf516caf4f52.js:71:45358)
    at e.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_17c61e51d8e2dc1831efaf516caf4f52.js:71:41449)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_de-de_dc58eaaa7aaff14eda18.js:1:6012

**Expected behavior**
Should be able to configure the web part.

**Screenshots**
![image](https://user-images.githubusercontent.com/60385459/176202736-3b5999ef-d728-4304-b71b-50b131f69610.png)

**Desktop (please complete the following information):**
 - Browser: Edge

**Additional context**
App was installed today.
Instructions of the website were followed. 
API Access requests are approved too.
(Found the same error in another issue. (Missing Spanish language)

**Comment by FranckyC** [comment]
Hi @ThexTobi, this is probably due to a missing translation. Will be fixed in the final release.

**Comment by FranckyC** [comment]
The package has been updated in the release page https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.7.0-beta. It should solve your issue.

**Comment by ThexTobi** [comment]
Hi @FranckyC, thank you very much. It's working. ^^
