### ISSUE TITLE
Selected properties not showing all properties in the dropdown

### ISSUE THREAD

**Issue by VerlindenEAM** [microsoft-search/pnp-modern-search#2188]
**Version used**
4.7 (beta)

**Describe the bug**
Since several weeks not all properties are listed in the dropdown of the Selected Properties anymore.
Only properties that start with a, b, c..  are shown and all the selected properties.
Tested with both 4.5.2 tenant deployment and 4.7 (beta) in a test site with separate app catalog.

**To Reproduce**
1. Go to 'Results webpart'
2. Click on 'Selected properties'
3. Scroll down to 'c'
4. See screenshot

Workaround: manually type the properties needed

**Expected behavior**
Please allow to show all properties in the dropdown list.

**Screenshots**
![image](https://user-images.githubusercontent.com/35732908/176635134-cd14bd15-ef23-453d-bd25-e5c0dd9c1eae.png)

**Desktop (please complete the following information):**
 - Browser Edge (Chromium)

**Additional context**

**Comment by wobba** [comment]
This is an API limitation which we cannot control, as it's basically not a real API we use. Seems the API is now capped at returning 1000 items. The workaround is to manually type the property you want.
