### ISSUE TITLE
Question: Support for more than one Extensibility Library

### ISSUE THREAD

**Issue by MakingThingsWorkToronto** [microsoft-search/pnp-modern-search#219]
Question: Are there plans to support more than one Extensibility Library?

The limitation of the current approach is we can't deploy more than one Library with the predefined GUID in the manifest. Additionally the ExtensibilityService will only load the single library deployed with the predefined GUID.

Presume we would need to add properties to the results web part for users to specify dynamic component GUIDs to be loaded and adapt the ExtensibilityService.  Any concerns around this concept - security, performance, usability?

Great improvements in the develop branch. Looking forward to the 4.0 release.

**Comment by wobba** [comment]
Short answer, yes :) When depends a little bit but plan is to make it modular in multiple ways, hopefully before summer.

**Comment by MakingThingsWorkToronto** [comment]
Would it be helpful for me to take a stab at it? May have time in the next couple days ... If so any preferences?

**Comment by wobba** [comment]
Sure..dm'd you on twitter 👍
