### ISSUE TITLE
LivePersona Handlebar Partial doesn't render template with Handlebars

### ISSUE THREAD

**Issue by malcom1120** [microsoft-search/pnp-modern-search#220]
**Version used**
3.11

**Describe the bug**
Trying to use the LivePersona handlebar partial with a template.  The template is not use as a template and is pushed into the HTML as raw HTML. Raw HTML renders fine.

**To Reproduce**
Try to use LivePersona partial in a custom render. Here is my example.

`<div class="template_result">
                    <div class="gsh-infocard">
                        {{#>livepersona upn="upn" disableHover=false }}
                        <div class="gsh-inforcard-content">
                            \{{#with (split RefinableString30 '|')}}                              
                            <div class="gsh-persona-picture ms-srch-hover-postPersona"><img src="/_layouts/15/userphoto.aspx?size=L&username=\{{[0]}}" title="\{{[1]}}" /></div>
                            <div class="gsh-persona-data">
                                <div class="gsh-infocard-highlight">\{{[1]}}</div>
                                \{{#if RefinableString36}}
                                <div class="gsh-infocard-text">
                                    \{{#each (split ../RefinableString36 ';') as |company|}}
                                    \{{{this}}}<br/>
                                    \{{/each}}
                                </div>
                                \{{/if}}
                            </div>
                            \{{/with}}
                        </div>
                        {{/livepersona}}
                    </div>
                </div>
`

**Expected behavior**
Expectation is the template that is passed in would be used in via handlebars to render. Much like the slider partial does.

**Screenshots**
![image](https://user-images.githubusercontent.com/8712085/80413825-0f3ba980-889e-11ea-99ca-020431d68de9.png)

**Comment by wobba** [comment]
LivePersona is not supported. I'm still working in getting proper support for it, but it's a bit complicated and no timelines still - unfortunately :(

**Comment by malcom1120** [comment]
So is the LivePersona handlebar partial going to stay in code or be removed?  If not supported, I would have thought it was removed.

The LivePersona part of the partial works great. Just not the template part.  😉😎

**Comment by wobba** [comment]
Good q...left it there for a while for discovery ;) and it can/will possibly break in the future.

**Comment by malcom1120** [comment]
I'll close issue as the underlying persona is not supported. Hopefully it will one day.
