### ISSUE TITLE
Search Pagination in search-custom-renderer

### ISSUE THREAD

**Issue by rognym** [microsoft-search/pnp-modern-search#221]
Is it possible to add Search Pagination in the custom renderer? 
When looking to the samples they are without pagination and in the documentation there is only code for handlebars.

**Comment by wobba** [comment]
You can output the markup for the web component. There was a discussion at https://github.com/microsoft-search/pnp-modern-search/pull/155#issuecomment-616489917 on the same issue and we have to address the issue properly.

**Comment by FranckyC** [comment]
Can be closed. You can continue in the #155 thread.

**Comment by frankok** [comment]
Hi Mikael, thank you for your help. Could you please elaborate what you mean by "output the markup for the web component"? I read through the discussion at #155, but couldn't find any working examples. 

I assume you are referring to the markup found in this article:
https://web.archive.org/web/20201014031828/https://microsoft-search.github.io/pnp-modern-search/search-parts/search-pagination/
But how and where to place this code?

Thank you for any assistance!

**Comment by FranckyC** [comment]
Hi @frankok, actually it means, if you use React, you have to output the `<pnp-pagination/>` web component HTML markup in your .tsx file. The page you are referring to is the markup to output in the `render()` method. Of course, with React, you couldn't use Handlebars tokens so you will have to use your own values. Ex:

```
<pnp-pagination 
        data-total-items="1" 
        data-hide-first-last-pages="false"
        data-hide-disabled="false"
        data-hide-navigation="false"
        data-range="5" 
        data-items-count-per-page="5}" 
        data-current-page-number="1"
    >
    </pnp-pagination>
```

Just FYI, the custom renderers will be deprecated in the v4 but we plan to replace them with something similar.

**Comment by frankok** [comment]
Hi Franky,

Thank you for your feedback.
However, I'm still confused. Is this markup going into my tsx file? That won't work...

The only place I can find markup of this kind is inside the Search Results WebPart, under Custom template, and then selecting Edit Template:

![image](https://user-images.githubusercontent.com/20436301/102065776-493fc880-3df9-11eb-9dcd-9a367b01e176.png)

Am I supposed to add an additional WebPart on the page, and then render this with the Custom template?

**Comment by wobba** [comment]
@frankok Yes, in your tsx file. Same as you output any other (html) tag in markup, the web component can be outputted. It's a global "tag" on the page.
