### ISSUE TITLE
Multiple webpart properties are not saved

### ISSUE THREAD

**Issue by till-llit** [microsoft-search/pnp-modern-search#2211]
**Version used**
4.7
**not** reproducable with 4.6.1 and before

**Describe the bug**
Webpart properties of all search webparts (verticals, results, refiner) that open a dialog are not saving changed values correctly anymore.
You must change the "primary" field of the option additionally to the required change to trigger the saving.

Reproducabel in 
Search Verticals - Configure verticals
Search Results - Layout Details List - Manage Columns

but i guess all property dialogs with multiple entries are affected (framework change?)

**To Reproduce**
easiest way to reproduce:

add search vertical webpart to new page
open "configure verticals" and add at least one entry and save 
open "configure verticals" again, change any value (e.g. "Tab value") and save -> **your change is not persistent**
open "configure verticals" change the "Tab Name" and any other Field (e.g. "Tab value") -> **your change is persisent.**

it looks like the "Save" action only detect changes of the "primary" field (here : "Tab name") and only change the row if changes are detected. Other changes are ignored.

**Expected behavior**
changes to the properties are saved

**Screenshots**

**Desktop (please complete the following information):**
edge 102

**Additional context**

**Comment by FranckyC** [comment]
This is likely a bug with the latest version of `@pnp/spfx-property-controls`. I reverted to the previous package version. Should be resolved in `develop`. See #2220.

**Comment by sparkitect** [comment]
rolled back a customer install to previous v and porblem went away...
