### ISSUE TITLE
Specific Term shows no results after weeks of working fine

### ISSUE THREAD

**Issue by 1nY0urF4c3** [microsoft-search/pnp-modern-search#2214]
Hello all,

I have the following problem. In a customer environment we have configured a search part and assigned refinable strings as filter options. The terms mentioned here are for example: MS Teams, SharePoint, Onedrive etc.

We have also configured and pre-filtered Result Webparts. 

For a few days now, the filter function for a specific term no longer works. If I change the expression to another term, the correct results are displayed. The terms are all content of the same expression set.

Does anyone have any ideas?
![grafik](https://user-images.githubusercontent.com/92848152/178000148-7eab2915-db63-41f0-9333-d02c1cb231f8.png)
![grafik](https://user-images.githubusercontent.com/92848152/178000243-d1dad940-f5ef-44de-8ed8-107d585c16ad.png)

**Comment by FranckyC** [comment]
Hi @1nY0urF4c3, you shouldn't user refinement filters as it is a legacy feature. You can achieve the same with a KQL query in the query template like:

`RefinableString111:SharePoint`

And by "no longer works", you mean you don't get any results? I suggest you to test with [Search Query Tool](https://github.com/pnp/PnP-Tools/tree/master/Solutions/SharePoint.Search.QueryTool) if you encounter the same behavior.

**Comment by 1nY0urF4c3** [comment]
@FranckyC  thank you very much and i am sorry for my delayd reply. Your advice to use KQL and avoid refinement filters worked well with all configured webparts in all tenants. Thank you very much for the link to the search query tool, too!
