### ISSUE TITLE
Search Results Webpart - Result Types - alter one Condition Value to multiple Condition Values

### ISSUE THREAD

**Issue by Georg-Trixl** [microsoft-search/pnp-modern-search#222]
**Description**
Reuse one inline template for multiple _Condition Value_'s
As for example i like to reuse one picture _Result Type_ for multiple _FileType_'s and write the _Condition Value_ like: **JPG, PNG, JPEG, BMP** (and such a list could be much longer than 4 example values.
The supplied _Inline template_ should be applied to all results that match those  _Condition Value_'s.
This keeps _Result types_ out of the custom display template and on the other side easier to manage in the settings panel.

**Possible solution**
Use a splitting character like  **;**  or  **#;**  or  **,** 
During looping through the results and _Result Type_'s detect **if** a _Result Type / Condition Value_ has a splitting character inside.
**Then** apply the _Operator_ for each _Condition Value_ against the _Managed Property_ to check if the condition evaluates to true and render the _Inline template_

**Alternative**
More complex for the settings panel would be: to allow for one Managed Property line to add via plus icon multiple _Condition Value_ text boxes. And evaluate each _Condition Value_ against the _Managed Property_ by with the _Operator_.

**Additional context**
I hope that it is not that much effort brings a small usability boost to this awesome project.

![Git-sample-1](https://user-images.githubusercontent.com/62948158/80501813-2a76e980-8970-11ea-9839-dffde24227d0.png)

**Comment by wobba** [comment]
Good suggestion and should be easy to do if we can agree on a separator. @FranckyC any thoughts?

**Comment by FranckyC** [comment]
Hi @Georg-Trixl Yep very good idea indeed but what would be the operator between values then? OR/AND? The best I guess would be to be able to choose in the UI. Should be doable for the May release.

**Comment by wobba** [comment]
It would be OR.... as you look for string matches. AND is not needed for this case imo.

**Comment by Georg-Trixl** [comment]
Hi @FranckyC I agree with @wobba the OR is the operator.

**Comment by Georg-Trixl** [comment]
Any news about this _enhancement_ ? Is it implementable with a semicolon separator?

BR & have nice day

**Comment by wobba** [comment]
@Georg-Trixl  Today `contains` translates to https://github.com/helpers/handlebars-helpers#contains which will not work like this. We could  support test+regex as an option, but the question is if that will cause more confusion for most people.

**Comment by wobba** [comment]
Closing and recommend copying the template as a workaround for now.
