### ISSUE TITLE
PnP search web parts don't work with SharePoint Limited Web-Only access on unmanaged devices

### ISSUE THREAD

**Issue by SinghGurd** [microsoft-search/pnp-modern-search#2221]
**Version used**
4.7

**Describe the bug**
Our company provides SharePoint Limited Web-Only access from unmanaged devices. This is mainly used by users when accessing SharePoint from their own devices from home. Web-Only access is the SharePoint feature whereby user is not allowed to download any documents. None of the PnP modern search web parts load when accessed from an unmanaged device browser session that is restricted with web-only access.

**To Reproduce**
1. Enable SharePoint Limited web-only access in SPO admin center
2. Browse to SharePoint page with PnP search web parts
3. None of the webparts load and throws an error such as Unable to load script https://<tenant url>/sites/appcatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/SearchBoxWebPartStrings_en-us_ba503fbfba8306ea4166a509a2679649.js

**Expected behavior**
I expected PnP search web parts to work in browser sessions controlled with SharePoint Limited Web-Only access restrictions.

**Desktop (please complete the following information):**
 - Browser

**Comment by FranckyC** [comment]
Hi @SinghGurd, the error is probably because these users can't access the Web Part assets in the appcatalog. Basically they can't download the scripts to be exectued by the browser and we can't bypass that.
