### ISSUE TITLE
Search box setting to enable custom suggestion provider will not save v4.7

### ISSUE THREAD

**Issue by SinghGurd** [microsoft-search/pnp-modern-search#2222]
**Version used**
4.7

**Describe the bug**
When I enable the custom suggestion provider in pnp search box web part, the setting will not stick. It remains disabled and my custom suggestions does not load.

**To Reproduce**
1. Deploy the most recent 4.7 version of pnp modern search web part
2. Deploy the custom suggestion provider pkg that is built from the search-extensibility
3. Add search box to page and try to enable the custom suggestion provider
4. The setting to enable the suggestion provider never saves and remains in disabled state. No custom suggestions load.

**Expected behavior**
Setting to enable the Custom suggestion provider in search box web part property pane to stick and custom suggestions to work.

**Desktop (please complete the following information):**
 - Browser [Edge]

**Comment by FranckyC** [comment]
Hi @SinghGurd, seems related https://github.com/microsoft-search/pnp-modern-search/issues/2211. We've made a fix in the `develop` branch.
