### ISSUE TITLE
Search verticals etc. should be hidden when search results have option "Hide this web part if there's nothing to show"

### ISSUE THREAD

**Issue by svermaak** [microsoft-search/pnp-modern-search#2225]
**Is your feature request related to a problem? Please describe.**
When I have a page with no results possible, I cannot hide the search verticals etc.

**Describe the solution you'd like**
Search verticals etc. should have similar option to search results' "Hide this web part if there's nothing to show". It should functions on all connected search result web parts

**Describe alternatives you've considered**
No viable alternatives

**Additional context**
NA

**Comment by FranckyC** [comment]
Hi @svermaak, regarding verticals, it can't be done as we can't determine in advance if there will be results for a particular vertical and connected Search Results.
