### ISSUE TITLE
Search Result Duplicates

### ISSUE THREAD

**Issue by Lennart28213** [microsoft-search/pnp-modern-search#2227]
Hello together,

since a few days, unfortunately, all search results are shown to me twice. I use PNP search in the version: 4.5.4. The duplicate results are displayed both without configuration of the query and when limiting to a specific search path.  Before everything worked fine, is the error on the side of MS or is this due to a wrong setting on our side, although we have actually not changed anything?

![image](https://user-images.githubusercontent.com/105660404/178688424-30db7973-5a5b-4038-a834-073e0284289c.png)

**Desktop (please complete the following information):**
 - Chrome

Thank you very much for your support

**Comment by HawkOn1** [comment]
I experience the same in one tenant, In others I don't. I had version 4.6.1, updated to 4.7 without that helping. 
![image](https://user-images.githubusercontent.com/109071995/178714739-cbd94131-31d8-4a42-a6d8-d048a92cc833.png)

**Comment by FranckyC** [comment]
Hi @Lennart28213, I guess you ar using the SharePoint search data source. By default the "trim duplicates" option is set to off. With `4.7.0` we've added a parameter in the Search Results Web Part proeprty pane to control the behavior explicitly. Can you try to turn this 'on' and see if there is any difference?

![image](https://user-images.githubusercontent.com/5659122/178757990-ed92ceb8-061a-4813-a621-2ed2a9e60183.png)

Otherwise it could be an issue with Microsoft APIs.

**Comment by HawkOn1** [comment]
@FranckyC  it worked for me. Thanks!

**Comment by FranckyC** [comment]
@Lennart28213 what about the solution I proposed?

**Comment by Lennart28213** [comment]
Hi @FranckyC , 
Thank you for your support!
The "trim duplicates" option works by removing the duplicate entries from the search results. However, the results count is still wrong. It currently shows 436 documents instead of 303 in our test library. Up until a few days ago, it was still showing ~600 search results.

The same problem exists with the refiners, here too many documents are displayed in the count.

Overall it displays: 436 results
![image](https://user-images.githubusercontent.com/105660404/180382529-ed750af0-e7f7-4c7f-a690-6363efe9d267.png)

A random refiner shows 15 possible results:
![image](https://user-images.githubusercontent.com/105660404/180382598-21c78eac-97ef-4034-bfd5-34ab8f39a67e.png)

After applying the refiner it will display 10 actual and unique results:
![image](https://user-images.githubusercontent.com/105660404/180382722-be5f2796-9156-487c-8724-6c6bc53a9953.png)

Any idea what could cause this problem?

Thanks again and best regards

**Comment by FranckyC** [comment]
The result is always a estimation and not the actual count. However, to see if this is an API issue, you can do the same request using PnP Search Query tool and see if you get the same count using the same options.
