### ISSUE TITLE
Webparts not available to add to a site page

### ISSUE THREAD

**Issue by stvpwrs** [microsoft-search/pnp-modern-search#2229]
Hello,

I installed the June update, version 4.7.0.0, but after deploying this and adding it to a site, the PnP webparts are not available to add. Everything appears to be approved and added correctly, but the webparts do not show up when editing a page.

Has anyone see this before?

**Comment by FranckyC** [comment]
How did you deploy the solution? If you didn't check the "Make this solution available to all sites in the organization" flag, you need to manually add the app to your site. Maybe it explains.

If doesn't work, you can go to https://<tenant>.sharepoint.com/sites/yoursite/Lists/ComponentManifests/AllItems.aspx and remove entries related to PnP Modern Search, then redeploy
