### ISSUE TITLE
Search result webpart display columns

### ISSUE THREAD

**Issue by Takeda-scrm-O365-VJE0880** [microsoft-search/pnp-modern-search#223]
trying to display the name of the content type in my search result. not sure how do i fetch the content type name that result belong too. please provide your input

in same search result webpart, i need to show Updated item item, i could by default Create with Handler expression, But i would like use similar for Modified Date. how to retrive the Modified date values in my search result.

thanks,
Narasi.

**Comment by wobba** [comment]
Retrieve the managed property `SPContentType`. It has the name. See https://docs.microsoft.com/en-us/sharepoint/technical-reference/crawled-and-managed-properties-overview for a list of many oob managed properties. And take a look at the [SharePoint Query Tool](https://github.com/pnp/PnP-Tools/releases/tag/v2.8.6-Search-QueryTool) to see what managed properties are available. Your question is a bit outside the scope of the web parts, as they relate more to a basic understanding of SharePoint search.
