### ISSUE TITLE
Search Results Web Part - Columns sizes cannot be changed when horizontal scroll is required

### ISSUE THREAD

**Issue by Dididam** [microsoft-search/pnp-modern-search#2236]
**Version used**
Ex: 4.61

**Describe the bug**
When the search results web part has a number of columns which will require the horizontal scrollbar, then the sizes of the columns cannot be changed by the user. The arrow to adjust the column width is displayed, but the column size remains.

**To Reproduce**
1. Configure the results web part to show multiple columns, which will activate the horizontal scrollbar
2. In the search results, click on the space between the column titles (not the first one, but any other) 
3. Try to resize the column
4. nothing changes

**Expected behavior**
the column width can be adjusted even if the horizontal scroll bar is required

**Screenshots**
![grafik](https://user-images.githubusercontent.com/92945934/179458570-c7acc276-1577-47ed-8c57-71a49d1dba86.png)

**Comment by FranckyC** [comment]
Hi @Dididam, I guess you've set columns as "Resizable" in the settings?

![image](https://user-images.githubusercontent.com/5659122/181364188-720af120-0ace-4d68-b8e8-644c3d0e8f74.png)

Also what browser are you using? Tested with Chrome, Firefox and Edge and all work fine.

**Comment by Dididam** [comment]
Hi @FranckyC all browser behave same. The columns are set to resizable. And do resize BUT if you add columns until the web part will require a horizontal scrollbar, the columns (except for the first) are not resizable anymore. So the point to reproduce this issue is the horizontal scrollbar.

**Comment by FranckyC** [comment]
I got the point with the horizontal scroll bar, and like I said I don't have this issue. Did you try with latest version?

**Comment by wobba** [comment]
Closing as no response
