### ISSUE TITLE
Autoowstaxidmetadataalltagsinfo doesn't create AutoRefinableString since upgrading from v4.5.2 to 4.7

### ISSUE THREAD

**Issue by ileana2019** [microsoft-search/pnp-modern-search#2239]
**Version used**
Ex: 4.7

We upgraded the app from v4.5.2 to 4.7 and we are using Managed Metadata SharePoint columns linked to RefinableStrings managed properties. When using the v4.5.2, we could setup the Search Results webpart to enable localization and use the Autoowstaxidmetadataalltagsinfo for the Tags layout slot. Then in the Manged Columns, we could add AutoRefinableString to the details lists. With the same settings, in v4.7, the AutoRefinableString are not created anymore (in order to nicely display the managed metadata fields). 

**To Reproduce**
1. On the search results webpart properties: Enable localization to On and, in Layouts slots, link the Tags to the Autoowstaxidmetadataalltagsinfo
3. Select Details list as layout
4. Click on Manage columns
5. In the Select property drop down list, the AutoRefinableString is not created

**Expected behavior**
The AutoRefinableStrings should be created automatically, when setting up the webpart as described above.

**Comment by ileana2019** [comment]
Maybe this issue and the issue: https://github.com/microsoft-search/pnp-modern-search/issues/2212 are somehow linked?

**Comment by ileana2019** [comment]
I will add 2 screenshots for this issue: The first one is a search page where we added the v4.5.2 of the pnp and then we migrated to v4.7:
![Search page created with v4 5 2](https://user-images.githubusercontent.com/55545989/180239861-fffb2a7b-67b1-4355-95d9-162f90525036.PNG)
The second one is a search page where we added the v4.7 of the pnp: 
![Search page created with v4 7](https://user-images.githubusercontent.com/55545989/180240039-cc7208df-a320-41e1-a612-b8a61aaf12bd.PNG)
Both have the same pnp settings.

**Comment by FranckyC** [comment]
Hi @ileana2019,  FYI the "Autoowstaxidmetadataalltagsinfo" property (and all 'AutoXXX' properties in general) has nothing to do with filters actually. It is only useful to be used in results display. In filters configuration you use "owstaxidmetadataalltagsinfo" property only.

Also, for the 'AutoXXX' proeprties to be created and selectable in the dropdown list (from layouts for instance), you must have results containing values for the original property. If don't don't see anything, this is probably there are no such results. In this case, instead of selecting the property, you can simply type the proeprty name manually and press 'enter' to validate the setting.

Anyway, can you confirm this works with 4.5.2 but not with 4.7.0 **with the same data**? Also, dumb question I know, but did you check the term actually exist in the term store with these IDs?

**Comment by ileana2019** [comment]
Hi @FranckyC ,
I Started again from scratch, to recreate the search page, where I added just the Search results webpart and the Filters webpart. 
In the search results I see the following result :
![Search Results](https://user-images.githubusercontent.com/55545989/183447394-be9ab3c9-f316-42c1-9282-405990c60625.PNG)

In the filters webpart I do not see any results; The filters webpart is configured as following:
![Search Filters](https://user-images.githubusercontent.com/55545989/183447537-38decdd5-5298-4a67-9995-c20ec41203a7.PNG)

The RefinableString is configured as following:
![RefinableString](https://user-images.githubusercontent.com/55545989/183447652-563adca1-1783-4497-860d-33346b607e40.PNG)

So how do I nicely display the RefinableString (linked to a Managed Metadata column) in the search results (just the text, without the IDs)? And why I do not see any results in the filters? This used to nicely work in v4.5.2 (by setting the Enable Localization to On in the search results webpart, and by linking the slot name "Tags" to the slot field "Autoowstaxidmetadataalltagsinfo".

**Comment by FranckyC** [comment]
@ileana2019 did you connect filters WP and search results WP both ways? With the localization flag 'on' you should use **AutoRefinableString110** field in your "Cluster" column to display the friendly label (or map that field to the 'Tags' slot)

**Comment by ileana2019** [comment]
Hi @FranckyC,
Indeed, I forgot to connect the search results webpart to the filters webpart. Thank you for pointing that out! I now see results in the Cluster filter, but it says "Term with ID cannot be found":
![Term cannot be found](https://user-images.githubusercontent.com/55545989/184121194-929fd980-7ebe-4c9c-9157-239da437eb2b.PNG)
I tried to map the slot Tags with RefinableString110 and Autoowstaxidmetadataalltagsinfo, still no change. I cannot see the AutoRefinableString110 in Manage columns:
![Manage columns](https://user-images.githubusercontent.com/55545989/184121773-5cfe10ab-1897-4c9e-bdc6-c5b547d6e95d.PNG)

**Comment by ileana2019** [comment]
Hello, Are there any updates to fix this bug?
@FranckyC could you please remove the label Needs Author feedback? Because I did give the feedback.
Thank you!

**Comment by VerlindenEAM** [comment]
Hello @FranckyC and @wobba ,
Could this be related to [discussion 2403](https://github.com/microsoft-search/pnp-modern-search/discussions/2403).

**Comment by wobba** [comment]
@VerlindenEAM don't think so as #2403 is about merged terms. But I see the output looks the same,

**Comment by kasperbolarsen** [comment]
@ileana2019 Can you verify if this issue exists in the current version?

**Comment by kasperbolarsen** [comment]
Closed due to inactivity
