### ISSUE TITLE
Double taxonomy terms in filter web part

### ISSUE THREAD

**Issue by Georg-Trixl** [microsoft-search/pnp-modern-search#224]
**Version used**
3.11.1 March 2020

**Describe the bug**
All filter items are shown duplicated. If one of the duplicated filter items is selected, the other same item is selected as well. But in our term store are those display filter items only uniquely 
![Git-Bug-0 1](https://user-images.githubusercontent.com/62948158/80694141-5e6b1f80-8ad4-11ea-8111-4cb947a2a285.png)
stored. See attached Pictures
![Git-Bug-0 0](https://user-images.githubusercontent.com/62948158/80693949-1815c080-8ad4-11ea-97fd-40fb6f8d5e51.png)
![Git-Bug-0 2](https://user-images.githubusercontent.com/62948158/80693989-28c63680-8ad4-11ea-943b-bec2b795bc64.png)

**To Reproduce**
In _Search Results Webpart_ set following _Enable taxonomy values localization for refiners and results_ to enabled

Use more than one _Managed Properties_, that are _Term Store_ based, in the filter webpart setting _Edit refiner_ . For example SharePoint Online should have to already configured _Managed Properties_ configrated:

- _Tags
- ows_taxId_MetadataAllTagsInfo_

If both are added to the configuration the duplicates come up
(the stupid thing on that example is, that both _Managed Properties_ are using in the background the same _Crawled Properties_)
If the same _Managed Property_ based on _Term Store_ information is added twice - one filter element is display correct, the other is displayed raw (not _Term Store_ translated/localized ).

**Expected behavior**
The items of a Filter configuration should be display unique.

**Desktop (please complete the following information):**
Chrome version 80 and Firefox version 75 on Windows 10 Pro 1909.

**Comment by wobba** [comment]
1. If you turn off localization, does it work?
2. If you only use one term based managed property does it then work?

Trying to understand the exact case when it works/doesn't work.

**Comment by kmprasad4u** [comment]
Here are my observations
* It appears to happen only when adding Enterprise Keywords (owstaxidmetadataalltagsinfo) as one of the filters
* Didn't notice the issue when there is No Tags, but two Multi Select Managed Metadata Field
* I think with localization turned off, it works properly as implementing a tree would not have remove the issues

Have chosen "024" for my tests
![01_FilterDuplicateIssue_Metadata](https://user-images.githubusercontent.com/48886361/81480409-3f445e80-9247-11ea-9906-ceaabc3c9322.PNG)

Without Tags
![02_FilterDuplicateIssue_NoTags](https://user-images.githubusercontent.com/48886361/81480412-410e2200-9247-11ea-851b-c100bf3c69d1.PNG)

Without Tags - Without Localization
![02_FilterDuplicateIssue_NoTags_NoLocalization](https://user-images.githubusercontent.com/48886361/81480413-41a6b880-9247-11ea-98ea-7e926089314f.PNG)

With Tags 
![03_FilterDuplicateIssue_WithTags](https://user-images.githubusercontent.com/48886361/81480414-423f4f00-9247-11ea-9e27-42dbbe159cdf.PNG)

With Tags - No Localization
![03_FilterDuplicateIssue_WithTags_NoLocalization](https://user-images.githubusercontent.com/48886361/81480415-423f4f00-9247-11ea-8f15-7b4d235a2427.PNG)

With Tags & Single Select Managed Metadata Field
![04_FilterDuplicateIssue_WithTags2](https://user-images.githubusercontent.com/48886361/81480411-40758b80-9247-11ea-939c-f4d7345be8dc.PNG)

With Tags & Single Select Managed Metadata Field - No Localization
![04_FilterDuplicateIssue_WithTags2_NoLocalization](https://user-images.githubusercontent.com/48886361/81480410-40758b80-9247-11ea-9089-830439567bf7.PNG)

**Comment by Georg-Trixl** [comment]
Okay sorry, did miss the update on that issue item.
In the scenario I'd described:
It renders GUID values when localisation is turned on - in one filter (refiner), the other is translated by the localisation feature.
It renders GUID values when localisation is turend off.

**Comment by glpallavi** [comment]
I am also facing the same issue , is there a fix for this ?
Only without tags i still see duplicates in the Search filter webpart

**Comment by wobba** [comment]
Still an issue?

**Comment by Georg-Trixl** [comment]
not really an issue, found other ways to get things implemented thanks
