### ISSUE TITLE
Search box web part not connecting to search results web part

### ISSUE THREAD

**Issue by jvonbank** [microsoft-search/pnp-modern-search#2240]
For some reason after updating from v3 to v4 and working through the manual setup, the new PnP - Search Box web part will not connect to the PnP - Search Results web part. Attempting to search does not trigger any changes in the Search results. If I add the old Search results web part, the search works as expected. This would be a workaround, but I need to work with the PnP - Search Filters web part and this is not recognized by v4. 

Please let me know if any additional information is needed!

**Comment by FranckyC** [comment]
Hi @jvonbank, can we see the setup you have in the Search Results WP regarding connections (3rd configuration page)?

**Comment by jvonbank** [comment]
![PnP-search-pg3](https://user-images.githubusercontent.com/80417392/181616275-0e191fb2-5c2b-4829-8ee1-870e38de133d.png)

Please see attached and let me know if any further information is needed.

**Comment by FranckyC** [comment]
You've used the wrong option, you must connect the search box using the "Use input query text" toggle and then use dynamic query option.

**Comment by jvonbank** [comment]
Thanks for the feedback FranckyC, I was able to get this working after working with the "Use input query text". Closing this one out!
