### ISSUE TITLE
Filters are not working in version 4.7

### ISSUE THREAD

**Issue by FHaslwanter** [microsoft-search/pnp-modern-search#2241]
**Version used**
4.7

**Describe the bug**
The Filter webpart is not working. There only is a message with "No available filters to show", though we connected the filter webpart with the search result webpart and vice versa and selected appropriate and filled in fields to filter.

**To Reproduce**
1. Insert a filter and search result webpart.
2. Search with the asterisk to get results.
3. Go to the filter and search result webpart and connect both with each other.
4. Go to the filter webpart and select the filter fields needed and fill out as seen in the screenshots.
5. Save the filters and publish the page.

**Expected behavior**
Filters are shown and can be applied.

**Screenshots**
![image](https://user-images.githubusercontent.com/109658783/179943872-e1ea7f51-e0d7-41ad-8f0e-84e24dac5c8d.png)
![image](https://user-images.githubusercontent.com/109658783/179943959-d3dcdf83-3947-4e43-9c97-f67ac7a255fd.png)
![image](https://user-images.githubusercontent.com/109658783/179944123-f1b9d06a-bef8-42cc-8c5c-cb10bd0518ce.png)

**Desktop (please complete the following information):**
 - Microsoft Edge

**Additional context**
We already had the version 4.3 installed and there, the filters also didn't work.

**Comment by newfy78** [comment]
I am having the same issue.  From what I can tell, the Filter webpart doesn't have an option to connect to the Search Box.  Only the Search Results:

![filter configure](https://user-images.githubusercontent.com/109675440/179998706-85760b07-5ce1-432b-adeb-b23fcd1bff19.png)
![filter screenshot](https://user-images.githubusercontent.com/109675440/179998709-8a315be3-24eb-48be-a17f-22a688d245d1.png)

**Comment by FranckyC** [comment]
Hi @FHaslwanter, it seems this is due to this error https://github.com/microsoft-search/pnp-modern-search/issues/2211 and should be fixed in the next version.

**Comment by tlambourne** [comment]
I am able to set up a date range filter but not a checkbox or combo filter type. The bug is specific to those templates.

**Comment by wobba** [comment]
This should be resolved already.
