### ISSUE TITLE
Values of columns are not shown in the search result webpart, but are filterable

### ISSUE THREAD

**Issue by FHaslwanter** [microsoft-search/pnp-modern-search#2242]
**Version used**
Ex: 4.7

**Describe the bug**
We currently upgraded from version 4.3 to 4.7 and had already some columns with metadata filled in to test PnP Modern Search. The values filled in before the upgrade are still shown in the columns webpart. Values from new columns are not shown, but filterable like seen in the screenshots.

**To Reproduce**
1. Create a new column in asharepoint library
2. Fill in values for this new column and assign them to documents
3. Select the new properties under "Selected Properties"
4. Give the new properties a Layout Slot
5. Manage Columns and create a new column with the respective slot item and layout slot name
6. Refine the search query and filter a specific value of the newly created column
7. The right search results are shown, but the values are not shown in the column

**Expected behavior**
The values of the column "Note" is shown and not only filterable.

**Screenshots**
![image](https://user-images.githubusercontent.com/109658783/179946678-3176d4f8-2ba1-4645-874a-f9710f5a2846.png)
"Auswahl" is a old column, which already existed before the upgrade. "Note" is the new column, which is filterable but the values are not shown as can be seen in the screenshot

**Desktop (please complete the following information):**
 - Microsoft Edge

**Additional context**
We currently upgraded from V4.3 to V4.7. In V4.3 it worked perfectly fine.

**Comment by FranckyC** [comment]
Hi @FHaslwanter, can you ensure the value is correctly saved in the details list column? It may be related to an other issue we have in the 4.7 release. you can also switch to debug layout to see if the value is present in the results.

**Comment by FHaslwanter** [comment]
Hey @FranckyC, I just looked the value up in the debug mode. The value is present in the results like you can see in the screenshot attached.
![image](https://user-images.githubusercontent.com/109658783/183367773-913cfb6b-b797-44f6-bd9e-05910d10ff81.png)

**Comment by wobba** [comment]
Does this happen to all columns, or only ones starting with a number? And if you reference the property directly and not via slots, does that work?

**Comment by FHaslwanter** [comment]
If i reference the property directly and not via slots, it's the same behaviour. So the value is shown in the debug mode but not in another view.
![image](https://user-images.githubusercontent.com/109658783/185140189-82628766-6ea6-4f5b-bc20-e93466b3889f.png)

I also made a new column which does not start with a number and there it is working like intended. There I see the value in the search results webpart and also in the debug mode.
![image](https://user-images.githubusercontent.com/109658783/185140474-81345e5a-0f77-428e-a0a4-379c22a35c69.png)

**Comment by wobba** [comment]
Ok.. so seems an issue on our end where the mp starts with a number then.

**Comment by wobba** [comment]
Fixed with 3034, and you can also use the mp directly with `{{item.1234asbs}}` instead of slots.
