### ISSUE TITLE
Filter web part not displaying any filter values other than "Created" or "File Type"

### ISSUE THREAD

**Issue by alexvg12** [microsoft-search/pnp-modern-search#2245]
**Version used**
4.7.0

**Describe the bug**
Installed a fresh version of sppkg.
Configured search box and search results. Verified all data present in search results.
Added filter web part. Connected it to search results. Also connect search results to the filter. No matter which fields in the filter are being selected, the web part shows "No available filter to display." The only field that works with the filter is "Created" or "File Type".

**To Reproduce**
1. Go to filter web part properties, configure it to use Author or Path under "Customize fitlers", for example. 
2. Publish page
3. Filter web part shows "No available filter to display"
4. The only time that filters are working is when using "Created" or "File Type" as the filter field.

**Expected behavior**
Expect to see a selection of filter values.

**Screenshots**
![image](https://user-images.githubusercontent.com/109701066/180090185-c6c4dccd-bbd3-4e26-80c5-c2536d2c767b.png)
![image](https://user-images.githubusercontent.com/109701066/180091384-53647eeb-38f5-43d9-80bf-ce035fd7d340.png)

**Desktop (please complete the following information):**
 - Windows 10, Chrome browser 103.0.5060.114 (Official Build) (64-bit)

**Comment by FranckyC** [comment]
Hi @alexvg12, to make it work you have to make sure the properties you select in the filters are actually marked as "[refinable](https://docs.microsoft.com/en-us/sharepoint/manage-search-schema#refine-on-managed-properties)" in the search schema. For instance, the properties you are trying to use are not so it may explain.

**Comment by alexvg12** [comment]
Right on - that did the trick!
