### ISSUE TITLE
Special character in refinablestring alias

### ISSUE THREAD

**Issue by ayblanchet** [microsoft-search/pnp-modern-search#2255]
Version used
Ex: 4.7 & 4.6.1

Describe the bug
We currently upgraded from version 4.5.3 to 4.7. We have refinable string with alias contains accented characters. In this case the get value from these alias are filled in debug view, but not filled in details list view.
Same behaviour with 4.6.1.

To Reproduce

- Create a sharepoint column
- Map this column to a refinableString with alias contains accented characters
- Use this alias in pnp search result with details list

Desktop (please complete the following information):
Microsoft Edge

**Comment by FranckyC** [comment]
Hi @ayblanchet why not using the `RefinableString` property name in the details list configuration instead? Was it working with 4.5.4?

**Comment by ayblanchet** [comment]
Hi @FranckyC, I have checked my previous version it was not 4.5.4 but it was the 4.5.3, sorry.
It's doesn't work with 4.5.4, so this issue appeared into 4.5.3 and 4.5.4.

**Comment by FranckyC** [comment]
@ayblanchet in your Details List template, can you try to use the epxression `{{slot item 'MyAliasWithAccent'}}` instead and sse if it makes a difference

**Comment by ayblanchet** [comment]
@FranckyC  It's doesn't work too, this error occurs before the slot mapping.

**Comment by wobba** [comment]
I don't recommend using anything but a-z/0-9 in a managed property name or alias. I suspect this is more an api issue than web part issue,

**Comment by ayblanchet** [comment]
I understand that special character it's not recommended. But I think is not an API issue, except if API changes between 4.5.3 and 4.5.4.

**Comment by wobba** [comment]
Can you revert to 4.5.4 and retest? I'm thinking your update might have coincided with a service change.

**Comment by ayblanchet** [comment]
Hi, 
Sorry for the wait, It's always works in 4.5.3.
Best regards,

**Comment by wobba** [comment]
I'll mark it as bug but not high up on the list to look into as you can easily fix it by changing the alias or **adding one more alias** of the underlying managed property instead.
