### ISSUE TITLE
Paging is not been reset after filter update

### ISSUE THREAD

**Issue by salascz** [microsoft-search/pnp-modern-search#2259]
**Version used**
4.7.0

**Describe the bug**
Hello, 
we have a problem with communication between paging and filter controls in latest version of Modern Search solution.
Search Result WebPart render empty content in some cases (described bellow).
I have tried multiple filters (single/multi etc.) configuration and multiple result templates with the same result. I was not able to reproduce this behaviour on another solution using previous version of Modern Search (v4.6.1)

**To Reproduce**
1. Open a page with Modern Search WebPart (should contain multiple pages of results and some filters)
2. Go to the latest page (using >> or page number)
3. Change the filter to something that will reduce the number of results significantly (should return less pages than the current page number, one page ideally).
4. Apply the filter

**Expected behavior**
Paging would be set to first page, results are visible

**Desktop (please complete the following information):**
 - Browser Chrome, Edge

**Additional context**
There seem to be two "postquery" request visible in the Network tab. The first one with correctly "StartRow" property set to 0. The second request use the previously entered "StartRow" value. 

<img width="364" alt="image" src="https://user-images.githubusercontent.com/5662939/182227890-725220ec-3057-4dff-92ad-a5f218e38aad.png">

**Comment by FranckyC** [comment]
Hi @salascz I've been able to reproduce your issue and fix it. This will be available in the next release. Thanks!
