### ISSUE TITLE
Token not resolved in custom html search template: verticals.name + verticals.value

### ISSUE THREAD

**Issue by till-llit** [microsoft-search/pnp-modern-search#2269]
**Version used**
4.6

**Describe the bug**
according to https://microsoft-search.github.io/pnp-modern-search/usage/search-results/tokens/#connections-tokens i tried to use the token {{verticals.name}} in a custom html template. even though a vertical webpart was connected to the result webpart the value of the token is NULL.

i found this old issue where it is said that the token is not beeing populated and should be removed from documentation:
https://github.com/microsoft-search/pnp-modern-search/issues/1201

i tried to reproduce the test case and could not reproduce the issue - when i add both tokens in the Query template i see the correct values resolved:

![image](https://user-images.githubusercontent.com/91128746/183038777-4473c287-dda3-4be2-95ee-911c1ae76191.png)

so i have hope the token is working - just i fail to read it in my query template:

![image](https://user-images.githubusercontent.com/91128746/183038962-44ba019d-5446-481c-8867-b0b7c74a4492.png)

is resolved to:

![image](https://user-images.githubusercontent.com/91128746/183039080-446b212e-21e6-4061-b826-89e6e4d21ee7.png)

-> you can see that the token inputQueryText was resolved (it was "test" in this repro) - but verticals.name is empty

**To Reproduce**
create a search result page with vertical + search results connected.
create a custom html template with {{verticals.name}} reference
configure the search results to use a custom display template with the html template.

**Expected behavior**
vertical name should be displayed in the results

**Screenshots**
see above

**Desktop (please complete the following information):**
edge 103

**Additional context**

**Comment by FranckyC** [comment]
Hi @till-llit, tokens are resolved differently in query template and Handlebars template. In your layout template, you must use this expression to access the current vertical data: 

```
{{@root.verticals.selectedVertical.name}}
```

Basically, you can access all properties listed in the 'Debug' layout:

![image](https://user-images.githubusercontent.com/5659122/184438374-8029ee79-0e33-40c8-bfc4-6fc55bd03c46.png)
