### ISSUE TITLE
I want to use Modified date in Refiner as well as in search result webpart

### ISSUE THREAD

**Issue by Narasireddy447** [microsoft-search/pnp-modern-search#227]
Hi team,
I am struggling to configure "Modified" in refiner. i have used managed property "LastModifiedTime" in the refiner configuration. in Search schema i gave "ows_Modified" crawled property.

please help to configure "Modified" in refiner as well as in search result webpart.

**Comment by wobba** [comment]
You should not re-map cp's to `LastModifiedTime`. Would help if you can add more details to what you are struggling with. What have you tried, what does not work etc.

**Comment by FranckyC** [comment]
Duplicate of #228.
