### ISSUE TITLE
PnP-Search Result issue : Title is not displayed.

### ISSUE THREAD

**Issue by Rachel-0107** [microsoft-search/pnp-modern-search#2274]
**Version used**
The latest version

**Describe the bug**
Using PnP - Search Results Web parts, I tried to display some documentfiles.
In some documents files, the title is not displayed and instead it is displayed the text "Title".
Many documents files shows correct title on the Web parts
As you know, when I point out the title, screen shows the url of the file on the screen lower left. 
I check the url, it shows correctly and the correct title is showed.
Why it this happened? Is this problem of crawl?

**Expected behavior**
PnP - Search Results Web part shows correct files' title.

**Screenshots**
I cannot take the screenshot because this issue happens on cutomer's environment.

**Desktop (please complete the following information):**
Microsoft Edge

**Comment by FranckyC** [comment]
Hi @Rachel-0107, can you share the Web Part configuration, especially:
- What layout you are using?
- What source (SharePoint or MSSearch) and query template if any?
- Did you make any update to the template?
- Does the 'Title' field contains value when you switch to the 'Debug' layout?
