### ISSUE TITLE
"hashchange" event doesn't trigger on searchbox when I use "Url Fragment" as data source

### ISSUE THREAD

**Issue by wuxiaojun514** [microsoft-search/pnp-modern-search#2280]
**Version used**
4.7.0

**Describe the bug**
I am using SharePoint Search Service and use "Url Fragment" as the dynamic data source in search box
![image](https://user-images.githubusercontent.com/29603048/184291179-c51f8220-64c9-4314-b8a5-beedebf9c7a6.png)
The search result webpart connects on this search box webpart.
I added some hash link in the search result webpart template,e.g. `<a href="#{{@root.slots.Tags}}=%22{{trim tag}}%22">{{tag}}</a>`
However, when I click the tag link, it won't update the search box and search result webpart.
![image](https://user-images.githubusercontent.com/29603048/184293792-f13b3c8b-2642-4b49-9913-840ada02a0ff.png)
Then I did some debug and found the problem is on the **_bindHashChange** method in **SearchBoxWebpart.ts**.
The "queryText?.reference" is undefined while "this.properties.queryText" contains right reference
![image](https://user-images.githubusercontent.com/29603048/184294319-dca0e094-395d-45f4-9157-c9fb18222fcb.png)
![image](https://user-images.githubusercontent.com/29603048/184294412-eccc5959-3aae-419b-bde0-f885f5c198a9.png)
So it won't add the hashChange listener and my tag link won't work. I don't know how DynamicProperty work very well.

**Expected behavior**
The **_bindHashChange** method in Search Box should trigger correctly when use "Url Fragment"

**Desktop (please complete the following information):**
 - Browser Chrome/Edge

**Additional context**
SharePoint Search Service

**Comment by FranckyC** [comment]
Hi @wuxiaojun514, good catch. This will resolve in the next PR. See #2285 Thanks!
