### ISSUE TITLE
PnP - Search Results - Sort settings result in error code 500

### ISSUE THREAD

**Issue by MuesliP** [microsoft-search/pnp-modern-search#2281]
**Version used**
4.7.0

**Describe the bug**
The PnP - Search Results Web Part returns an Internal Server Error (500) if sort settings are included.

**To Reproduce**
1. Edit PnP - Search Results web part
2. Use SharePoint Search as data source
3. Click on "Edit sort settings"
4. Add sort setting and save

**Expected behavior**
The sort settings used should work as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/74404234/184315648-93ecda34-8cfa-48ab-92db-565cbe8f4e29.png)

![image](https://user-images.githubusercontent.com/74404234/184315471-602d2ebd-3cf7-43de-b142-8a1149574655.png)

![image](https://user-images.githubusercontent.com/74404234/184313786-0c0f7d83-c7aa-44b6-ba26-af9ff7053098.png)

**Desktop (please complete the following information):**
 - Browser:
    - Microsoft Edge Version 104.0.1293.54 (Official build) (64-bit)
    - Google Chrome Version 104.0.5112.81 (Official Build) (64-bit)

**Comment by FranckyC** [comment]
Hi @MuesliP , this error is because the default 'Title' managed property is not marked as 'Sortable' in the search schema. You need to use a `RefinableStringXX` property instead. See https://github.com/microsoft-search/pnp-modern-search/issues/1518

**Comment by MuesliP** [comment]
Hi @FranckyC thanks for the quick feedback and the reference to #1518.
