### ISSUE TITLE
Sort by placeholder and default sort option are not translated

### ISSUE THREAD

**Issue by Titef** [microsoft-search/pnp-modern-search#2288]
**Version used**
4.6.1

**Describe the bug**
In the Search Result Web Part :
- The sort dropdown placeholder is not translated and is always displaying "Sort by...".
- The default sort option is not translated and is always displaying "<Default>".

**To Reproduce**
1. Configure Sort options in the Search Results Web Part
2. Set you browser language to anything else than English
3. Drop down is still displaying "Sort by..." as a placeholder and "<Default>" for the default sort option

**Expected behavior**
"Sort by..." and "<Default>" should be translated into browser's current language

**Screenshots**
![image](https://user-images.githubusercontent.com/34166028/184812842-54004d34-55db-4c09-bcb3-03d585a5e16c.png)

**Desktop:**
 - Browsers: All

**Comment by wobba** [comment]
Please re-test with the latest version, and the web parts support:

* English
* Danish
* Spanish
* Finnish
* French
* Norwegian
* Dutch
* Polish
* Swedish

**Comment by Titef** [comment]
Hello,
Same issue in v4.7.0. We are using French language.
Thanks

**Comment by FranckyC** [comment]
Hi @Titef, the translations was missing. It will be fixed in the next release. See #2301. Thanks!
