### ISSUE TITLE
Search Results Web Part : Items selection triggers web part refresh

### ISSUE THREAD

**Issue by Titef** [microsoft-search/pnp-modern-search#2291]
**Version used**
v4.6.1

**Describe the bug**
When using the "Details List" layout, the Search Results Web Part is refreshing when a result is selected, making the web part flickering. This doesn't happen with the "List" layout.

**To Reproduce**
1. Add a Search Result Web Part to a blank page
2. Configure the Web Part with the "Details List" layout and allow Selection
3. Select an item in the results : the Web Part is refreshing. According to the Page's Header Web Part, this can lead to the page to scroll back at the top.

**Expected behavior**
Selecting an item should not refresh the Web Part

**Desktop (please complete the following information):**
 - Browsers: all

**Comment by wobba** [comment]
Can you re-test with the latest version?

**Comment by Titef** [comment]
Hello,
Same issue in v4.7.0.
Thanks

**Comment by wobba** [comment]
@Titef I don't see any flickering when testing

https://user-images.githubusercontent.com/51104/186239113-e8c9ec7b-183a-4561-bef3-046b51821f84.mp4

.

**Comment by Titef** [comment]
Hello @wobba,

Thanks for the feedback but I'm still facing the issue. I even did a test on another tenant with a fresh App installation.

For information, items selection is not working either for Card and Sliders layouts (nothing happens when you click on an item) whereas it is working if I rollback to 4.6.1.

**Comment by wobba** [comment]
I'd need more details on your actual setup as I cannot repro. Anything in the debug console?

**Comment by Titef** [comment]
No specific error in the console. On my side I can reproduce the issue with the simple steps indicated in my initial post. Would you need the WebPart Raw Properties export?

**Comment by wobba** [comment]
That could help.

**Comment by aarrass** [comment]
Same issue here with version 4.8. When a row from the results is selected, not only the page is flickering, but the page scrolls up to top. Very annoying.

**Comment by wobba** [comment]
Made an improvement. Ideally nothing would move when clicking, but couldn't get that working right now. Fixed in dev branch.
