### ISSUE TITLE
Filters deep links - Many filters get selected issue

### ISSUE THREAD

**Issue by mahmoudhamed** [microsoft-search/pnp-modern-search#230]
**Version used**
3.10

**Describe the bug**
I am using the Filters deep links feature to create a topic page experience. 
Currently I have many news pages tagged with terms from a term set called Topic. I created a managed metadata field in the site pages library to tag the pages and the field support multi-values. I am creating now a deep link to filter only for a single topic "Digitalization" for example but because also the pages are tagged with other topics these are also selected by default.

**Expected behavior**
Only the Digitalization filter should be selected.

**Screenshots**

![image](https://user-images.githubusercontent.com/7877441/80975646-a8306e80-8e22-11ea-8d92-d6af377ee31b.png)
![image](https://user-images.githubusercontent.com/7877441/80975702-b9797b00-8e22-11ea-94ff-2f98f0950b5e.png)
![image](https://user-images.githubusercontent.com/7877441/80976152-5cca9000-8e23-11ea-971c-8778b96e8c8d.png)

**Page field value example**
![image](https://user-images.githubusercontent.com/7877441/80976542-e0847c80-8e23-11ea-974d-f102fcd1d784.png)

**Desktop (please complete the following information):**
 - Browser: chrome

**Comment by MakingThingsWorkToronto** [comment]
Appears the issue relates to line 1774 in SearchResultsWebPart > _mapDefaultSelectedFiltersToRefinementResults:

`
} else if (StringHelper.longestCommonSubstring(updatedSelectedFilterValue.RefinementToken, refinementValue.RefinementValue) && updatedSelectedFilterValue.RefinementToken.indexOf("range") === -1) {
// Means the provided condition in URL is an FQL expression so we try to guess the corresponding refinement results using the text value contained in the expression itself
`


For the above use case modifying the above if to the following resolves the problem.

`} else if (updatedSelectedFilterValue.RefinementValue.indexOf(refinementValue.RefinementValue) > -1 ) {
`

Having said that, I'm not sure I fully understand the intention behind the longestCommonSubstring comparison so unsure if this causes a regression.

**Comment by FranckyC** [comment]
Hi @mahmoudhamed , maybe this would help to understand the behavior https://microsoft-search.github.io/pnp-modern-search/search-parts/search-results/#how-default-selected-values-are-set-in-the-search-filters-wp. You can try to use a KQL expression instead of the FQL value, in your case, this would be:

```
filters=[{"n":"RefinableString05","t":["Digitalization"]}]
```

Also, in your managed property, did you map the text crawled property `ows_xxx` or the `owsTaxIdxxx` one?

**Comment by mahmoudhamed** [comment]
Hi @FranckyC, I am using the owsTaxIdxxx beacuse I want to support localization in the future and due to that using KQL expression will not work as the owsTaxIdxxx structure looks like this behind the scenes "L0|#0eadbdf88-5fee-423b-94e1-76bf1d26cd97|Digitalization" for example!

**Comment by MakingThingsWorkToronto** [comment]
@FranckyC - looks like this could be related to #385 ...

Not totally clear on what the longestCommonSubstring comparison is doing based on current comment/documentation. I'd also like to get this resolved to fix an issue with a custom web component not selecting the filter in the refinement panel / having duplicate filters be selected.
