### ISSUE TITLE
Search results don't refresh if search box got cleared / User can't submit empty search box to refresh search results

### ISSUE THREAD

**Issue by Stressf1sh** [microsoft-search/pnp-modern-search#2306]
**To Reproduce**
1. Enter a search term into the search box
2. Delete search term with backspace

**Expected behavior**
1. Search results get refreshed on keydown-event (that would be awesome)
2. User can submit empty search box once the search term has been deleted with backspace (that would be "ok")

**Comment by wobba** [comment]
This is by design, and has been logged before. We don't do "search as you type", so clearing the search box does nothing - same as OOB search experience in M365.
