### ISSUE TITLE
Edit Webpart panel blank and missing property pages

### ISSUE THREAD

**Issue by nicolesherman00** [microsoft-search/pnp-modern-search#2308]
**Version used**
Ex: 4.7.0

**Describe the bug**
When trying to edit any of the pnp webparts, the panel on the right is blank.
When trying to add new search results, the panel only has 2 pages. 
This is happening on all sites.
I have tried overriding the app with a new copy and clearing cache and cookies and still does this.

**To Reproduce**
Edit page > Edit webpart > Issue occurs
Edit page > Add webpart > Issue Occurs.

**Expected behavior**
Webpart properties show up in right panel after click the edit webpart button.
Search results webpart has 4 pages usually instead of 2?

**Screenshots**
![image](https://user-images.githubusercontent.com/22782498/186214838-ff2fd987-7795-4b5f-8f47-bc208f503d93.png)
![image](https://user-images.githubusercontent.com/22782498/186214881-a49e7070-cd81-4b7b-b658-4633be9faa97.png)

**Desktop (please complete the following information):**
 - Browser - CHROME

**Comment by nicolesherman00** [comment]
Sometime am getting this error as well.
![image](https://user-images.githubusercontent.com/22782498/186215123-7ccbc8c2-046f-4fbd-bd23-63c2cf800cfa.png)

**Comment by wobba** [comment]
Does the comments on #2303 help?

**Comment by wobba** [comment]
I did notice this myself today.. if you click another web part, then back to the other it showed. I have no idea why the code to trigger the property pane is not triggered as this is oob SPFx behavior.

**Comment by wobba** [comment]
![image](https://user-images.githubusercontent.com/51104/186408935-5f31bf8e-e8a5-400f-9447-40d574ff7bc0.png)
It fails when clicking the Configure button, but works when clicking the wp edit button.

**Comment by wobba** [comment]
Fixed in the dev branch and will be part of next release.
