### ISSUE TITLE
Solution package for 3.12 (April 2020 release) in downloads is not versioned correctly

### ISSUE THREAD

**Issue by alexabramkin** [microsoft-search/pnp-modern-search#231]
**Version used**
3.12.0

**Describe the bug**
Solution package in downloads is of version 3.11.0.0 when installed into App Catalog

**To Reproduce**
- Download the package (pnp-modern-search-parts.sppkg) from [https://github.com/microsoft-search/pnp-modern-search/releases/tag/3.12.0](url)
- Upload the package to application catalog and observe the App version column to read 3.11.0.0

**Expected behavior**
App version column is to read 3.12.0.0

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
In addition: if you are updating previous version (3.11.1.0) already installed in app catalog and have it instantiated there is no upgrade option on the application instance in your web

**Comment by wobba** [comment]
That's an oopsie we will get fixed!

**Comment by FranckyC** [comment]
Fixed. My bad ;)

**Comment by alexabramkin** [comment]
Thank you for reacting so quickly and thank you for all your hard work!
