### ISSUE TITLE
PnP Search WP v4.7.0 : Click on vertical tab shows {QueryString.k} when blank 

### ISSUE THREAD

**Issue by shariq1379** [microsoft-search/pnp-modern-search#2310]
### Check existing issues before logging new ones

If querystring/search box blank and then click on vertical search box, it shows {QueryString.k} in qquerystring and searchbox  

**Version used**
Ex: 4.7.0

**Describe the bug**
If querystring/search box blank and then click on vertical search box, it shows {QueryString.k} in qquerystring and searchbox. It is new issue.. we do not have this issue in old versions such as 4.3.0  

**To Reproduce**
1. Access search page without search keyword
2. PnP Search WP return the result
3. Click on another vertical tab
4. It shows {QueryString.k} in querystring & search box 

**Expected behavior**
It show show blank searchbox and search result should show all results

**Screenshots**

<img width="523" alt="PnPSearchWPIssue" src="https://user-images.githubusercontent.com/77804584/186262695-067ef8e4-8b2d-4f98-bdf1-673137abb664.PNG">

**Desktop (please complete the following information):**
 chrome, MS Edge

**Comment by FranckyC** [comment]
Hi @shariq1379, I'm not sure I get the setup you have. Can you share the exact configuration you've made with your WebParts? The steps you provided are not very clear to me :/

**Comment by wobba** [comment]
@shariq1379 do you experience this with 4.8 as well, and share your page setup for repro.

**Comment by kasperbolarsen** [comment]
closed due to lack of feedback
