### ISSUE TITLE
4.7 Cannot see web parts when editing page

### ISSUE THREAD

**Issue by LeeM103** [microsoft-search/pnp-modern-search#2313]
**Version used**
4.7

**Describe the bug**
When creating or editing a page I cannot see the v4.7 web parts available.

**To Reproduce**
1. Add the App to the App Catalog and Deploy (not globally)
2. On the site you want to add the web parts on, add the App.
3. Once installed and visible in site contents, go to the site homepage and click 'New > Page > Create PAge'.
4. Click the + sign to add a web part, these are not shown.

**Expected behavior**
Web parts would be available to be chosen.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Chrome.

**Additional context**
I do not have issues with previous versions and have the issue if the previous versions have never been added onto the site.

**Comment by LeeM103** [comment]
We have done this and waited days. How long do you suggest we wait before the web part shows and you accept it as an issue?

I am assuming the process for deploying hasn't changed from previous versions?

**Comment by wobba** [comment]
Re-upload the sppkg and see if that resolves it. Or delete and re-upload. This solution is nothing special, so a SPFx deploy issue.
