### ISSUE TITLE
Search requests fail with HTTP 500 or take too long to respond 

### ISSUE THREAD

**Issue by chetan-d-mahajan** [microsoft-search/pnp-modern-search#2317]
**Version used**
Ex: 4.6.1.0

**Describe the bug**
The PnP Modern Search makes use of SharePoint REST API (POST).

The search query requests are failing with HTTP 500 intermittently or they take too long (> 20 sec) when successful.

When we remove the parameter "ClientType": "PnPModernSearch", the requests work without error at all and takes less than 5 seconds to respond.

Does anyone else experience the same? Has something changed recently?

**To Reproduce**

Request URL : _<Site URL>/_api/search/postquery_
Request Type : _POST_
Request body:

_{
    "request": {
      "__metadata": {
        "type": "Microsoft.Office.Server.Search.REST.SearchRequest"
      },
      "ClientType": "PnPModernSearch",
      "Properties": {
        "results": [
          {
            "Name": "EnableDynamicGroups",
            "Value": {
              "BoolVal": true,
              "QueryPropertyValueTypeIndex": 3
            }
          },
          {
            "Name": "EnableMultiGeoSearch",
            "Value": {
              "BoolVal": true,
              "QueryPropertyValueTypeIndex": 3
            }
          },
          {
            "Name": "ClientFunction",
            "Value": {
              "StrVal": "PnPSearchWebPart",
              "QueryPropertyValueTypeIndex": 1
            }
          },
          {
            "Name": "ListId",
            "Value": {
              "StrVal": "09eafba6-2be5-406f-95ba-0eb1f2e1e315",
              "QueryPropertyValueTypeIndex": 1
            }
          },
          {
            "Name": "ListItemId",
            "Value": {
              "StrVal": "30",
              "QueryPropertyValueTypeIndex": 1
            }
          },
          {
            "Name": "SourceLevel",
            "Value": {
              "StrVal": "SPSite",
              "QueryPropertyValueTypeIndex": 1
            }
          },
          {
            "Name": "SourceName",
            "Value": {
              "StrVal": "<Result source>",
              "QueryPropertyValueTypeIndex": 1
            }
          }
        ]
      },
      "Querytext": "hydrogen",
      "EnableQueryRules": false,
      "QueryTemplate": "{?hydrogen {?hydrogen} }",
      "Culture": 1033,
      "TimeZoneId": 3,
      "RefinementFilters": {
        "results": []
      },
      "RowLimit": 9,
      "StartRow": 0,
      "TrimDuplicates": false,
      "SortList": {
        "results": []
      },
      "SelectProperties": {
        "results": [
          "AuthorOWSUSER",
          "contentclass",
          "ContentTypeId",
          "ContentType",
          "Created",
          "CreatedBy",
          "DefaultEncodingURL",
          "Department",
          "Description",
          "FileType",
          "HitHighlightedSummary",
          "IsDocument",
          "IsContainer",
          "JobTitle",
          "NormListID",
          "NormSiteID",
          "NormUniqueID",
          "NormWebID",
          "LastModifiedTime",
          "Path",
          "PromotedState",
          "PublishingImage",
          "SiteLogo",
          "SiteTemplate",
          "SitePath",
          "SiteTitle",
          "SPSiteUrl",
          "Title",
          "UniqueID",
          "UserName",
          "WorkPhone"
        ]
      },
      "HitHighlightedProperties": {
        "results": []
      },
      "ReorderingRules": {
        "results": []
      }
    }
  }_

**Expected behavior**
If we remove "ClientType" parameter from the request above, things start working as expected.

**Screenshots**
**Request failing (with ClientType)**
![image](https://user-images.githubusercontent.com/26963448/186606169-69ae4b0f-8b63-4c3a-a486-789ad71833af.png)
![image](https://user-images.githubusercontent.com/26963448/186606337-4177648c-8f98-411a-8d43-92bbf0a76e85.png)

**Request success (without ClientType)**
![image](https://user-images.githubusercontent.com/26963448/186606562-a774467a-9ae3-4c5b-9d27-70991f02f71d.png)
![image](https://user-images.githubusercontent.com/26963448/186606695-0b1022a0-b5e4-4f3f-b857-bfbe793d0931.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, Edge]

**Additional context**

**Comment by wobba** [comment]
Closing as API issues are unrelated to the web parts themselves and has to be reported via support channels.
