### ISSUE TITLE
attributes on web components is breaking change for 3.12

### ISSUE THREAD

**Issue by malcom1120** [microsoft-search/pnp-modern-search#232]
**Version used**
3.12

**Describe the bug**
Upgraded my test site collection to latest release and found that my custom templates do not work because the attributes of all of the pnp web components require data- now. While this is just my test site where I test out the new features, I do have production search pages with custom templates.  This breaking change is going to be a big change for those pages.

**To Reproduce**
Don't use data- on the attribute

**Expected behavior**
Not a breaking change.  Allow the attributes to work with or without data-.  

**Screenshots**
![image](https://user-images.githubusercontent.com/8712085/81000482-5680e780-8e14-11ea-9b91-3023e16c5b96.png)

**Comment by FranckyC** [comment]
Hi @malcom1120 , that was already the case in 3.11 so you moved from 3.10 to 3.12?

**Comment by malcom1120** [comment]
No - I was on 3.11 this morning.  I just upgraded to 3.12 about 15 minutes ago.

**Comment by FranckyC** [comment]
This change was introducted in 3.11. Anyway, if you're fine, you could submit a PR to include other attributes as well. This update was made to limit possible malicious HTML code.

**Comment by malcom1120** [comment]
Well I just looked at the 3.12 commit and this is new for 3.12. I'm fine with leaving it as is, but I would put the Breaking Change in the release notes so no one else it caught off guard like I was. I'll just tell my team that it is a breaking change and they will need to update their custom templates if they have any.

![image](https://user-images.githubusercontent.com/8712085/81003516-0193a000-8e19-11ea-8f68-dd80a59e5f00.png)

**Comment by pravin080317** [comment]
@FranckyC : 

Iam too facing this issue for the v12.1. i have used "data-" for the web-components in custom template, but still the results are breaking. especially for the "pnp-pagination" and "pnp-persona-card".

Please note that everything works fine in the earlier version v11.0  without using "data-".
please verify it from your end.

@malcom1120

**Comment by MakingThingsWorkToronto** [comment]
@pravin080317 - can you post the custom template code?

**Comment by pravin080317** [comment]
@MakingThingsWorkToronto -- for persona card
`<li class="template_listItem template_people"> 
        <div className="personaCard">
             <a href='{{Path}}' 
             target="_blank"> <pnp-persona-card data-text='{{Title}}'
             data-image-url="/_layouts/15/userphoto.aspx?size=M&accountname={{last (split AccountName '|')}}" 
             data-secondary-text='{{WorkPhone}}'
             data-tertiary-text=''
             data-persona-size={PersonaSize.size32} /> </a>
         </div>
        </li>`
for pagination
`  <pnp-pagination 
                    data-total-items="{{@root.paging.totalItemsCount}}" 
                    data-hide-first-last-pages="{{@root.paging.hideFirstLastPages}}"
                    data-hide-disabled="{{@root.paging.hideDisabled}}"
                    data-hide-navigation="{{@root.paging.hideNavigation}}"
                    data-range="{{@root.paging.pagingRange}}" 
                    data-items-count-per-page="{{@root.paging.itemsCountPerPage}}" 
                    data-current-page-number="{{@root.paging.currentPageNumber}}"
                >
                </pnp-pagination>`

**Comment by MakingThingsWorkToronto** [comment]
@pravin080317 - That is correct. Can you verify the version in the App Catalog and try deploying to all site collections again?

Out of curiosity, when you inspect the HTML output (using developer tools), are all the attributes assigned correctly?

I can confirm this change was inconsistent in 3.11.1 .

**Comment by pravin080317** [comment]
@MakingThingsWorkToronto 

Earlier the web-parts were broken due to the upgrade of 3.12.1 version from 3.11.0.  
using this post i came to know that the attribute for the web-components has been prefixed to 'data-'. so for the 3.12.1 version which was installed in my tenant i have used 'data-' attribute for the pagination and pnp persona card web component which doesn't solve the issue. still i can see the web-parts are broken. 
But suddenly today, the webcomponents were started to work without using 'data-' prefix for the 3.12.1 version. please find the app catalog version detail below.

![image](https://user-images.githubusercontent.com/35328578/81541947-876f9800-9391-11ea-815b-3c9564bba4a9.png)

**Comment by FranckyC** [comment]
Hi @malcom1120 , this PR #261 should do the trick. Now we allow all attribute formats (with or without the `data-` prefix). Attributes name will still be converted to camel case for React props. Can you try with the latest develop branch and tell me if it is OK for you?

**Comment by malcom1120** [comment]
Sorry @FranckyC for not responding yet.  I didn't need the PR to happen, I was just looking to get the Release Notes updated with the data- attribute requirement as a Breaking Changed like on the 3.11 release notes with Pagination so it didn't come as a surprise. I personally think for validate HTML the attributes should have data- in them. I have converted all of mine to data- attributes and notified my company of the Breaking Change so that others with custom templates can fix theirs. I'm good either way, but as for the PR, it is up to you if you want to put it in.

**Comment by FranckyC** [comment]
Hi @malcom1120, I've added a note on the April release. Anyway, in the upcoming release, `data-` and non `data-` attributes will both work.

**Comment by malcom1120** [comment]
Breaking Change note added to April release notes resolves this issue for me.

**Comment by wobba** [comment]
Want to note that #261 effectively don't sanitize the html for script injection. This will be fixed for the next release.

Question, do we still need to support attributes without the 'data-' prefix?

**Comment by malcom1120** [comment]
I personally don't think the HTML attributes without the 'data-' prefix should be supported. I was fine with the change to only support 'data-' attributes and the reason for this issue was to make sure that was noted in the release notes since it was a breaking change at the time.  I think since all of the examples use 'data-' it is safe to say that after 3 months it can change to only supporting 'data-'.

**Comment by wobba** [comment]
I'll go with the approach to only support `data-` as custom attributes then on any tag 👍 Thank you.
