### ISSUE TITLE
Old version of @microsoft/gulp-core-build-serve@3.5.5 as devDependency required?

### ISSUE THREAD

**Issue by jhholm** [microsoft-search/pnp-modern-search#2320]
**Version used**
4.7 from main branch
WSL2 Ubuntu 20.04
Node 14.18.0
npm 8.5.2

**Describe the bug**
I had some issues with getting the **search-parts** solution to build with **spfx-fast-serve** (npm run serve) last week and was about to create a bug report. Currently unable to reproduce the issue anymore. I noticed that the devDependency for **@microsoft/gulp-core-build-serve@3.5.5** could have been the cause as I cannot see any use for it. Internally a newer version **3.9.x** is a dependency on the standard build. So currently it just seems to be an unnecessary dependency that could cause issues.

**To Reproduce**
No bug to 100% reproduce right now, but I was unable to get **npm run serve** working last week. Could have been a network error, but this causes multiple versions of  **@microsoft/gulp-core-build-serve** downloaded as node_modules in the solution.

**Expected behavior**
Building a development version with **gulp serve --nobrowser** and **npm run serve** should work. For now they seem to work again.

**Possible change**
Updating the devDependency of **@microsoft/gulp-core-build-serve** to ~3.9.x or removing the dependency completely.

**Comment by jhholm** [comment]
The issue that I was facing was that **@microsoft/gulp-core-build-serve@3.5.5** does not have **@rushstack/debug-certificate-manager** as a dependency and for some reason that was not installed and thus **npm run serve** threw an error. **@microsoft/gulp-core-build-serve@3.9.15** seems to have it as a dependency and that version is used as a dependency by **@microsoft/sp-build-web.**

**Comment by wobba** [comment]
I tried to remove the dependency all together and that seems to work. Can you try and verify on your end?

**Comment by jhholm** [comment]
The dependency removal should be ok.

This is how I tested
1. Removed package-lock.json
2. Removed node_modules
3. npm install
4. Tested with both **gulp serve --nobrowser** and **npm run serve**

----

I unfortunately checked some other stuff here.

I guess you're using pnpm as I noticed a different configuration on **search-parts** vs **search-extensibility**.

Another similar find (unnecessary dependency?)
* Old version of **rush-stack-compiler** is included in **search-extensibility** https://github.com/microsoft-search/pnp-modern-search/blob/e0663a98a98e4953f69b640974105a4e74dab318/search-extensibility/package.json#L16

Extra notes (sorry if I'm getting out of track)
* **.npmrc** only for **search-parts**
* **package-lock.json** in **.gitignore** for **search-parts**, not in **search-extensibility**
* **@webcomponents/webcomponentjs** included in both 
  * different versions 2.4.3 vs 2.6.0
  * **search-extensibility** seems to be only using **@webcomponents/custom-elements** polyfills instead
  * I did not find either **custom-elements** or **webcomponentjs** as peerDependencies
  * I guess **@webcomponents/webcomponentjs** could be removed from both?

**Comment by wobba** [comment]
Feel free to help to PR some alignment :) And yes, I tend to use pnpm, and try to exclude any lock files or package manager file deps as people should be able to use what they want.

**Comment by wobba** [comment]
I removed the dev dependency.
