### ISSUE TITLE
PnP Search WP: Select people name from MS Search box is not passing selected name to search page

### ISSUE THREAD

**Issue by shariq1379** [microsoft-search/pnp-modern-search#2321]
### Check existing issues before logging new ones

Select people name from search box is not passing selected name keyword(as a querystring) to PnP Search page.
Note: It works fine when type and click on search link button icon from MS search box

**Version used**
Ex: 4.7.0

**To Reproduce**
1. Go to SharePoint site
2. Select people name from MS search box 
3. It redirect to PnP search page, but fail to pass select search keyword to search page  

**Expected behavior**
It should pass select people name as a querystring to search page when select people name from MS search box. 

**Screenshots**
![image](https://user-images.githubusercontent.com/77804584/187264635-2c93aed8-3b71-41f0-85d1-55e510de176c.png)

![image](https://user-images.githubusercontent.com/77804584/187264752-9918a317-f337-46d2-8a6a-0a4777876beb.png)

**Desktop (please complete the following information):**
 chrome and MS Edge

**Comment by jhholm** [comment]
I think this might be an issue with M365 search bar. When you are using a custom URL for the search results, the people result link is not providing any parameters for the custom search result page.

Not sure if there is some extra configuration required or this is just not working right now.

**Comment by shariq1379** [comment]
Yes, we had a discussion with Microsoft. They are assuming this issue could be if PnP Search WP is not handling "people centric search".
