### ISSUE TITLE
Values are not saved in manage persona fields

### ISSUE THREAD

**Issue by HamEv** [microsoft-search/pnp-modern-search#2327]
**Version used**
4.7.0.0

**Describe the bug**
I want to change the persona fields within the (people) search result webpart. The changes are not saved and when re-opening the dialog the old value are still there.

**To Reproduce**
1. Open 'manage persona field'
2. do any change (eg. change primary text to: {{slot item @root.slots.UserLastName}} {{slot item @root.slots.UserFirstName}} -> SAVE -> SAVE
3. Re-open 'manage persona field' -> you'll see the old value in primary text ({{slot item @root.slots.UserDisplayName}})

**Expected behavior**
Savining the values and showing the search results in a correct way.

**Screenshots**
![image](https://user-images.githubusercontent.com/61208008/187873331-c48d05e3-c273-4ced-b9e3-48e88d1b79b7.png)

After re-opening:
![image](https://user-images.githubusercontent.com/61208008/187873442-98e94377-8908-4fbb-b9b9-46eb355fd44e.png)

**Comment by jhholm** [comment]
I am unable to reproduce this. It is even possible to input and save errorneous handlebars text.

It is possible that the webpart might have some other errorneous config that breaks the saving of the people fields. Could you try if the following works. Do only the configurations listed below.

1. Create a new page
2. Add a new PnP Search Results WebPart
3. Configure to use Microsoft Search
4. Set querytemplate to {searchTerms} *
5. Set Result Source Id to LocalPeopleResults
6. Set layout to People (Handlebars/html)
7. Click "Manage people fields"
8. Try doing any change

You could also check if you get any kind of an error on your browser developer console and paste it here.

**Comment by Christian-Stahl** [comment]
Yeah, I have observed this one too in verison 4.7.0.0. It worked just fine in the previous version (4.6.1.0), same thing happens for the other fields, for example "Location", no Handlebars, HTML etc can be saved. Let me know if you need more info

**Comment by HamEv** [comment]
Hi,
I'm trying you described steps, but it's the same behavoiur. 
Step 7 - Click "Manage people fields" - default dialog:
![grafik](https://user-images.githubusercontent.com/61208008/188634590-315cc728-69f3-4d68-9a8e-465e692a13f0.png)

please go on with the following:
8. Change JobTitle to Handlebar Expression {{JobTitle}}
![grafik](https://user-images.githubusercontent.com/61208008/188634719-52c402e5-6683-451f-87ed-cac51677987a.png)
--> SAVE
9. Re-open manage people fields: Value has original value; checkbox has been saved
![grafik](https://user-images.githubusercontent.com/61208008/188634882-b695fb63-0fd1-4570-b326-fa7a6ef3af28.png)

You can do any change in handlebar expression - nothing will be saved.

**Comment by jhholm** [comment]
I managed to reproduce this as of now. Cannot see anything in console. I'll try to debug what could be wrong.

**Comment by jhholm** [comment]
Can reproduce in all browsers. I think I initially was testing against the develop branch, thus didn't notice a prior revert relating similar issues in 4.7.0.

This also seems to be a bug with **@pnp/spfx-property-controls@3.7**. There have been some fixes for **PropertyFieldCollectionData** after 3.7. Using either the latest version 3.9 or 3.2 used in modern search 4.6.x seems to fix this. Couldn't locate the exact cause, but the issue seems to lie in **PropertyFieldCollectionData**.

For some odd reason this is broken in both People and Card layout, but works in DetailsList.

In the develop branch **@pnp/spfx-property-controls** has already been reverted to 3.2.

**Comment by HamEv** [comment]
Hmm...is there a chance to get that fixed until the next relase?

**Comment by FranckyC** [comment]
Hi @HamEv, a release will come this month. We are working on it ;)

**Comment by FranckyC** [comment]
@HamEv can you test with the latest beta version https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.8.0? Thanks!

**Comment by HamEv** [comment]
Hi @FranckyC , thanks for the Beta Release, I just installed it for testing :-) 
It seems to work a little bit better, I can change row 2 and 4 inside the dialog. But unfortunatly row 3 (e-mail) ist not saving any changes. I would not have to change anything, but the e-mail adress with the existing code is not working/showing.

![grafik](https://user-images.githubusercontent.com/61208008/195091781-00b5c736-bc2d-4d64-936c-ce6b890a6eb9.png)
