### ISSUE TITLE
Wolu like to apply styling to "Search Box", " Search refiner", "Search result" web parts

### ISSUE THREAD

**Issue by Takeda-scrm-O365-VJE0880** [microsoft-search/pnp-modern-search#233]
i was able to configure and its working fine. But per my client would like to apply client branding like would like to apply Styles.
Custom-List template looks similar to our requirement but need to apply styles to custome-list template. is it possbilble to apply style to custom-list template?
If not how can i create my own search result template? any samples can i get?

thanks in advance

**Comment by wobba** [comment]
We don't support styling for the search box, but it picks up theme colors.

For the item templates you can add CSS to a custom template as you see fit, and it has a CSS section which shows a sample using it.
