### ISSUE TITLE
Search result WP - Manage card field - read only

### ISSUE THREAD

**Issue by TomasSmid-AtomTS** [microsoft-search/pnp-modern-search#2345]
### Search result WP - Manage card field - read only
I have latest version (June 2022) and i can't modify card fields once I choose Cards layout. I had no problems in older versions but here, cannot be changed. Once click save, nothing happen. Still same values are there.

Browser: Chrome

![image](https://user-images.githubusercontent.com/70215912/188887970-4f8d6afa-50ca-486c-9047-738e864bdc6c.png)

![image](https://user-images.githubusercontent.com/70215912/188887932-917ce465-8870-4137-937d-59a49b928961.png)

**Comment by HamEv** [comment]
I opened the same issue some days ago -> https://github.com/microsoft-search/pnp-modern-search/issues/2327

**Comment by FranckyC** [comment]
Known issue. Will be resovled in the next release. Thanks!
