### ISSUE TITLE
Trouble retrieving document library columns

### ISSUE THREAD

**Issue by mthanos7** [microsoft-search/pnp-modern-search#235]
**Version used**
3.12.0

**Describe the bug**
I have a document library in Sharepoint that I want build a dedicated search page for using the pnp-modern-search webpart(s). As of now, I've set the query template to query only the document library and it's returning its contents correctly. However I'm unable to query some of the columns in the document library and I'm unable to find them via the selected properties or managed columns in the search results web part. 

**To Reproduce**
1. Set up document library
2. Add search results webpart (connect to search box and any other relevant parts)
3. Set default query to * and query template to the document library URL
4. Unable to find certain columns via selected properties or managed columns

**Expected behavior**
Although I was able to set up the default properties to return as columns in the search results (e.g. file name, created), I expected to be able to locate some of the custom columns added to the document library. After some reading, I found that this might be an unresolved modern Sharepoint issue where even after re-indexing and crawling the site, it isn't picking up on new columns and generating the appropriate crawled/managed properties that we would be able to query. Admittedly, if this is the case, it is not a bug in the pnp-modern-search build, but I wanted to ask if you guys on the pnp team encountered such an issue before and if you had a recommendation for an alternative way to query and retrieve the missing columns or be able to display the data populating those missing columns through some of the available functionality in the webpart(s). I'm trying to work with Microsoft to see if we can resolve this by getting the properties correctly established but wonder if you could recommend a workaround.

**Screenshots**
This is the document library. A lot of the native functionality allows me to search this library how I want (i.e. searching for the files in the library and adding dedicated refiners/filters for the columns) but I wanted to use the webpart to create a better user experience
<img width="1792" alt="Screen Shot 2020-05-05 at 3 16 41 AM" src="https://user-images.githubusercontent.com/22053481/81042993-5e29a600-8e7f-11ea-9a2c-984c6c7ace1e.png">

This is my current set up using the php-modern-search webparts. As you may see, I'm missing some of the custom, non-default columns/properties (like group, sub-group and process name) that I would have liked to add but can't because I'm unable to find them through the webpart or through Sharepoint's search schema.
<img width="1792" alt="Screen Shot 2020-05-05 at 3 22 52 AM" src="https://user-images.githubusercontent.com/22053481/81043395-2c650f00-8e80-11ea-9c48-e09b63295d42.png">

**Desktop (please complete the following information):**
 - Browser [Safari]

**Additional context**
I'll be happy to explain more about my previous efforts if required. Help is much appreciated.

**Comment by wobba** [comment]
Column->crawled property->managed property mapping is outside of the scope of this project. Once you set up such that there are managed properties with values for your content, you can use it in search. Should be material out on the web on how to do this as it hasn't changed since SP2013 :)
