### ISSUE TITLE
owstaxidmetadataalltagsinfo -> Autoowstaxidmetadataalltagsinfo

### ISSUE THREAD

**Issue by sympmarc** [microsoft-search/pnp-modern-search#2350]
Hello, smart folks! I'm having a problem in multiple pages trying to change `owstaxidmetadataalltagsinfo` -> `Autoowstaxidmetadataalltagsinfo` in the Layout slots. In each case, when I save the settings, the `Auto` disappears.

In some pages where I'm using the PnP Search Results Web Part, it works fine; in others I have this problem. So far, I haven't discerned a pattern.

I'm using 4.7.0

The goal is to show the tags NOT like this:

![image](https://user-images.githubusercontent.com/1295627/189408090-16e88fad-0285-46f0-910d-b576ad4428f2.png)

To do this, I always change `owstaxidmetadataalltagsinfo` -> `Autoowstaxidmetadataalltagsinfo` and enable localization.

**Comment by sympmarc** [comment]
I've also tried editing the `selectedProperties` in the exported JSON and importing it back, but that doesn't "take", either. Might there be some other setting which conflicts with this?

**Comment by FranckyC** [comment]
Hi @sympmarc, this is a known issue related to the underlying data collection PnP control used to save values. This should be resolved in the next release coming this month. Until then, you should stay with previous version if possible. Sorry for the inconvenience.

**Comment by sympmarc** [comment]
Bummer. It's weird, because it works sometimes, but not other times.

**Comment by FranckyC** [comment]
I guessed this was the issue. I suggest you to wait for the new version to see if it resolves.

**Comment by sympmarc** [comment]
Reverting to the prior version does seme to solve it.
