### ISSUE TITLE
Sort by Filename

### ISSUE THREAD

**Issue by sympmarc** [microsoft-search/pnp-modern-search#2351]
**Version used**
Ex: 4.6.1

**Describe the bug**
I'd like to have the result set sort by **Filename**. I can add this setting in the **Sort settings**, but it doesn't seem to work as expected. My guess is maybe there's an interplay between the **Title** and the **Filename**?

**To Reproduce**
Set up a Search Results Web Part to show some results. Go into **Sort settings** and set a single sort for **Filename**, and make it the **Default sort**.
![image](https://user-images.githubusercontent.com/1295627/189412360-dba680e8-2516-4f0c-a9d2-f808e2664755.png)

The result changes, but it's not the right sort:
![image](https://user-images.githubusercontent.com/1295627/189412515-d3153f3f-3ad6-4235-b149-ed31f65e4ade.png)

**Expected behavior**
Reliable alphabetic sort by **Filename**.

**Desktop (please complete the following information):**
 - Edge

**Comment by sympmarc** [comment]
Looking at the specific documents, I do thing it's the interplay of **Title** and **Filename**. Unfortunately, **Title** isn't available as a sort field.

Any suggestion on how to accomplish this?

**Comment by FranckyC** [comment]
Hi @sympmarc, I'm not able to reproduce, using latest version the sort is performed as expected. However, it depends how you configured slots. By default we use the Title property but it can be different from the **Filename**. If you want to sort by Title, you should use a `RefinableStringXX` property.

**Comment by sympmarc** [comment]
I think things sort as expected if the Title and the Filename are the same. If you have different Title, it can feel off.

Here's an example. These five docs sort in this order if I use **Filename**. What would be great is to be able to sort by what is actually displayed in the search result (Title if it exists, otherwise Filename).
![image](https://user-images.githubusercontent.com/1295627/189429292-b8b22a48-3197-4505-a827-cfdb24a40660.png)

**Comment by sympmarc** [comment]
Here's are the search results when I sort by Filename:

![image](https://user-images.githubusercontent.com/1295627/189429715-933db36f-79b8-489a-a311-54d6419b7263.png)

**Comment by FranckyC** [comment]
> What would be great is to be able to sort by what is actually displayed in the search result (Title if it exists, otherwise Filename).

"Title" is not sortable by default in the search schema so you need to use a "RefinableStringXX" property instead and use it for the 'Title' slot in the configuration.

**Comment by sympmarc** [comment]
Right, but consider the case where some docs have Title populated and some don't. In the result set, you see Title if it exists, and if it doesn't, the filename. It would be great to be able to sort on that - I'm not sure it has a name.

**Comment by FranckyC** [comment]
We can't really do that unfortunately. In the end you should sort on the property that make the most of sense to you. It is a data issue not a Web Part issue.

**Comment by sympmarc** [comment]
Tell that to a client. 😀 But I get what you're saying.

**Comment by FranckyC** [comment]
> Tell that to a client. 😀 But I get what you're saying.

As a consultant, I do when needed yes :D

**Comment by wobba** [comment]
@sympmarc Title vs Filename is interesting and hard. Good Title's are good, but too many customers have bad values in Title due to copying docs, templates, and how Office clients might populate it automagically. Which is why we use Filename in OOB search which seems to work for a larger percentage, but having both is better if you know how to use them.

My suggestions is to map cp's for filename and title to RefinableStringXX and use that, and set the order such that Title is prioritized, and if missing you pick the filename. Then strip away the extension if present of the Filename in the UX.

**Comment by sympmarc** [comment]
That's a good suggestion, @wobba.  For posterity, what I'm going to do is:
* Map `ows_Title` and `ows_FileLeafRef` to RefinableStringxx - in that order
* Sort by RefinableStringxx
If `Title` is blank, the `FileLeafRef` will be used, so we should get what we want.

**Comment by sympmarc** [comment]
Actually, and a further question... In the **Sort settings**, I don't see the RefinableStringxx's I've set up, even though I've added them in the **Selected properties**. Is that going to prevent me from doing this? What's the trick to get a MP to show up in the **Sort settings**?

**Comment by sympmarc** [comment]
Never mind. I read the instructions on the page!

**Comment by wobba** [comment]
@sympmarc Use `RefinableStringFirst00` .. and that's a first for me as well.. never seen/used them and have to update my map property script to support them.

**Comment by sympmarc** [comment]
Ah, those Refinable things that no one understands!
