### ISSUE TITLE
Filter webpart: unselected items are still visible

### ISSUE THREAD

**Issue by HamEv** [microsoft-search/pnp-modern-search#2354]
**Version used**
3.23

**Describe the bug**
I have a filter webpart with 6 refiners/filter. Since some days 2 of these filters have a suspect behaviour. When selecting an item, the search results appear correct, but the unselected filter items are still visible. Thats not working in 2 of 6 filters. 4 filters are working correct (settings are the same). 

**Expected behavior**
Unselected items should be hidden.

**Screenshots**
![image](https://user-images.githubusercontent.com/61208008/189826596-5cb118b9-e252-4652-bc7e-f4784f61f1bc.png)

**Desktop (please complete the following information):**
 - Browser: chrome, edge

**Comment by wobba** [comment]
So this used to work, and now it has changed? If so it seems to be API related.

**Comment by kasperbolarsen** [comment]
Since v3 is not being updated anymore this case is closed
