### ISSUE TITLE
Refiner filters are returning different results when using the hex code vs. the actual label

### ISSUE THREAD

**Issue by erkanch** [microsoft-search/pnp-modern-search#2358]
**Version used**
4.7

**Describe the bug**
Configured the Refiners for RefinableString01. Filtering on "Diversity, Equity, and Inclusion (DEI)" label returns only 2 results when we have 5 pages using that label. An inspection on "postquery" shows the RefinementFilters having: RefinableTopic:"ǂǂ4469766572736974792c204571756974792c20616e6420496e636c7573696f6e202844454929". If we update the request to RefinableTopic:"Diversity, Equity, and Inclusion (DEI)", it does return the 5 items that have "Diversity, Equity, and Inclusion (DEI)" as a topic. Used a hex to ascii converter (https://www.rapidtables.com/convert/number/hex-to-ascii.html) to verify that the hex value is correct. Is it possible that the Refiner web part is using a buggy hex converter? Or, could the problem be with the SharePoint Online search engine when it tries to decode the hex?

**To Reproduce**
Create a custom managed metadata field called Topic in SP Online and map it to RefinableStringX. Use the "Diversity, Equity, and Inclusion (DEI)" label to tag multiple items or pages and use the PnP refiner and search results web parts to test the "Diversity, Equity, and Inclusion (DEI)" filter.

**Expected behavior**
All items with "Diversity, Equity, and Inclusion (DEI)" topic should be returned.

**Desktop (please complete the following information):**
 - Chrome

**Comment by FranckyC** [comment]
Hi @erkanch, what crawled property did you map to the RefinableString01 proeprty? The `ows_taxId_xxx` one?

**Comment by erkanch** [comment]
Hi, I mapped the ows_Topic crawled prop, which is based on our site column called Topic (managed metadata).

**Comment by FranckyC** [comment]
Can you try to map an other RefinableString property but this time using the ows_taxId crawled property see if makes a difference?

**Comment by erkanch** [comment]
I mapped ows_taxId_Topic to another refinable str. This doesn't help mush as you end up seeing the IDs under the filters. Also, I tried selecting the ID corresponding to "Diversity, Equity, and Inclusion (DEI)" and received  no results.

![image](https://user-images.githubusercontent.com/55555837/190457029-57dfb332-de75-4c47-a9c7-0ea5470dbf39.png)

**Comment by FranckyC** [comment]
You can turn the 'Enable localization' in the search results Web Part + add the 'Auto' prefix in the Search Filters WP for the managed property `RefinableStringXX`

> To use translated values in your template, you must use the 'Auto + <property_name>' property format instead of the original property name

**Comment by erkanch** [comment]
If I use AutoRefinableString104 instead of RefinableString104, it doesn't render the Topic104 filter at all.

**Comment by FranckyC** [comment]
My mistake, you don't need to prefix the filters properties, using RefinableStringXX should work

**Comment by FranckyC** [comment]
@erkanch I've tested the configuration you have and can't reproduce the issue unfortunately. Can you enable the 'count' option for the filter and see if the value matches the actual number of results? Thanks

**Comment by erkanch** [comment]
It does show 5:
![image](https://user-images.githubusercontent.com/55555837/190512446-99a0caa3-74e8-47f7-8d9b-a57e79eb11b6.png)

But applying it returns 2:
![image](https://user-images.githubusercontent.com/55555837/190512532-36cad81d-520c-448c-8c98-0692e6559a07.png)

**Comment by erkanch** [comment]
Hi @wobba, I'll try that out. In the meantime, I can reproduce the issue in your query tool.
RefinableTopic:"ǂǂ4469766572736974792c204571756974792c20616e6420496e636c7573696f6e202844454929" returns 2, whereas RefinableTopic:"Diversity, Equity, and Inclusion (DEI)" returns 5 for the same query. I captured the hex code from the postquery request of the PnP search web part.
![image](https://user-images.githubusercontent.com/55555837/190672321-f727e184-170f-4feb-b2d8-cfb7d1a202a8.png)

![image](https://user-images.githubusercontent.com/55555837/190672214-b98dd496-eecf-4e07-869d-db111dd4aae7.png)

**Comment by erkanch** [comment]
@wobba I get the same issue in classic with:
https://1ybsbl.sharepoint.com/sites/ClassicPub/Pages/Search.aspx#Default={"k":"*","r":[{"n":"RefinableString01","t":["\"ǂǂ4469766572736974792c204571756974792c20616e6420496e636c7573696f6e202844454929\""],"o":"and","k":false,"m":null}],"l":1033}
Using the label for "t" (https://1ybsbl.sharepoint.com/sites/ClassicPub/Pages/Search.aspx#Default={"k":"*","r":[{"n":"RefinableString01","t":["\"Diversity, Equity, and Inclusion (DEI)\""],"o":"and","k":false,"m":null}],"l":1033}) returns 5.
![image](https://user-images.githubusercontent.com/55555837/190703155-5a784f4b-95fd-43ca-a334-6cbce0426a30.png)

**Comment by FranckyC** [comment]
Thanks for testing this @erkanch. It means this is not an issue with the PnP Modern Search Web Part but more with the data/API. By any chance is the term "Diversity, Equity, and Inclusion (DEI)" reused or pinned elsewhere in the term store? What if you change the operator to "equals" instead of ':' for the refinement filter like `RefinableTopic:equals("Diversity, Equity, and Inclusion (DEI)")`?

**Comment by erkanch** [comment]
Returns 5:
![image](https://user-images.githubusercontent.com/55555837/190705824-e334622b-0532-4fc8-83eb-d569ecb2a490.png)

**Comment by FranckyC** [comment]
:/ really weird, seems really related to HEX encoding. @wobba are you aware of recent changes regarding the search API?

**Comment by wobba** [comment]
@erkanch can you either log a support case with Microsoft and/or log this at https://github.com/SharePoint/sp-dev-docs/issues and tag with these labels
![image](https://user-images.githubusercontent.com/51104/190856353-4c5798b2-25e7-4156-a441-325c78234f38.png)

**Comment by erkanch** [comment]
Hi @wobba, submitted https://github.com/SharePoint/sp-dev-docs/issues/8443
I wasn't able to tag it with the requested labels. Would you mind adding the labels? Thanks for your help!
