### ISSUE TITLE
Search verticals go previously selected resultpage instead of the first

### ISSUE THREAD

**Issue by MattSpar** [microsoft-search/pnp-modern-search#2359]
**Describe the bug**
Sometimes when switching search verticals no results are shown. I think this is because of a previously selected resultpage which is larger than the resultset of the newly selected vertical.

**To Reproduce**
1. Click on the first Search vertical which is showing all the people in the company
 ![1  all results](https://user-images.githubusercontent.com/76517828/190116844-b2017758-3e3d-4c70-ad52-59285c0a2334.png)
3. Click on page 5 to show the results of page 5
5. Click on the second search vertical which is supposed to show all the people in the Business Support department
6. See no results
![3  results of 2nd search vertical](https://user-images.githubusercontent.com/76517828/190116851-62376134-17cf-4911-9dd8-08205cf6e00b.png)
8. Clicking back on the first search vertical also gives no results however the resultscounter still gives 23 results (instead of 361)
![5  results of first search vertical when clicking again on the first vertical](https://user-images.githubusercontent.com/76517828/190116853-8a539a4c-cca1-46b8-94c5-822312771611.png)

**Expected behavior**
When clicking on a search vertical the selected result page should default back to the first one.

**Screenshots**
See the screenshots for more clarification

**Desktop (please complete the following information):**
 - Browser: Edge, Chrome

**Additional context**

**Comment by FranckyC** [comment]
Hi @MattSpar, can you detail the configuration you have in Search Results Web Parts for the first two tabs, especially the connections settings with verticals?
Also, are you sing custom layout/templates or do you see any error message in the console?

**Comment by wobba** [comment]
Stale issue
