### ISSUE TITLE
People Search: Synonyms are added to queryModification - and i cant disable this.

### ISSUE THREAD

**Issue by till-llit** [microsoft-search/pnp-modern-search#2368]
**Version used**
4.8.0-beta.1

**Describe the bug**
The search result webpart connected to SharePoint search and configured to use a people based result source (e.g. "local people results") will always add similar word to the query - this is not wanted and should be at least configurable.

**To Reproduce**
1. Configure search result webpart to use a people result source and set view to debug.
2. search for a word, e.g. "eberlein" ( a common german surname)
3. check the QueryModification:  "queryModification": "WORDS(eberlein,eberlein,,berlin,)"
4. i receive 283 results instead of 4, because "berlin" is causing a lot of hits.

**Expected behavior**
i would like to disable the additional queryModifications for people search.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by FranckyC** [comment]
Hi @till-llit, the Web Part does not transform the query by adding synonyms. Maybe you have query rules configured or other customizations that cause this behavior.

**Comment by till-llit** [comment]
Thanks for the hint - it was indeed a query rules (added by default to people result sources).

After i set "Fill In Results" inactive the query was "clean" again. What confused me that this behaviour was not visible in the SP Search Query Tool.
