### ISSUE TITLE
PnP Modern search results gives 'Http 400 - We didnt understand your search terms. Make sure they're using proper syntax' when searching for all documents and navigating to end results

### ISSUE THREAD

**Issue by NishkalankBezawada** [microsoft-search/pnp-modern-search#2371]
**Version used**
Ex: PnP Modern Search webparts - v4.7.0

**Describe the bug**
I am configuring the modern search webpart to fetch all the documents throughout the tenant. I have set the navigation buttons to be displayed too. If inavigate to the last navigation button to show the end of the search results, i however get the end search results, but i also see an error as below. 

![image](https://user-images.githubusercontent.com/47456098/191060802-6e166dc6-2653-48d0-b65d-fedd8cbd7c6c.png)

Checked the console, and the postquery gives me 400 error as below. 

![image](https://user-images.githubusercontent.com/47456098/191061061-3b7770d2-9cc3-46ef-a9e6-e49106ddd684.png)

**To Reproduce**
1. search with Test* or any test keyword from the search box 
2. results will be displayed in the search results, and click on '>>' at the end
3. search will fetch the last page of the search results, however we can see http 400 error as in the above screen shot

**Expected behavior**

**Screenshots**
Added screenshots above

**Desktop (please complete the following information):**
 - Browser - Chrome & Edge

**Additional context**

**Comment by FranckyC** [comment]
Hi @NishkalankBezawada, can you inspect the 'Payload' tab as well and share the details? Thanks!

**Comment by NishkalankBezawada** [comment]
> 

Hello @FranckyC Please find the screen for 'Payload' tab as below. 

![image](https://user-images.githubusercontent.com/47456098/191269663-c9a5f14c-e583-44c2-86bd-0eb1cafff703.png)


Thanks,
Nishkalank

**Comment by NishkalankBezawada** [comment]
> s it adds a lot of white spaces

Hello @FranckyC , I have removed the QueryTemplate field value from the screen shot. You may check with the below? 

![image](https://user-images.githubusercontent.com/47456098/191297810-68911ba1-4bde-466c-868e-cf7e0c93e4e9.png)

Thanks, 
Nishkalank Bezawada

**Comment by NishkalankBezawada** [comment]
> ds a lot of white spac

Gives same error when removed the whitespaces too. 

Please suggest.

**Comment by jooaij** [comment]
I'm facing the same issue on a client, the search API returns 400 with the error message "We didn't understand your search terms. Make sure they're using proper syntax."

The search has worked before, but it suddenly stopped. The payload for search queries is below:
![image](https://user-images.githubusercontent.com/22955738/191939808-1970af26-3d91-4789-8594-81ff500369bc.png)

**Comment by wobba** [comment]
Closing as this is an API issue, not web part related. API issues should be logged with Microsoft Support or at https://github.com/SharePoint/sp-dev-docs. And before logging you should try to repro using classic sharepoint web parts or the Search Query Tool. If the issue repro's all places, that's a high probability of API/service issue.

**Comment by saxonsai** [comment]
> > ds a lot of white spac
> 
> Gives same error when removed the whitespaces too.
> 
> Please suggest.

Hi, I am facing same issue please suggest the resolution for this issue
