### ISSUE TITLE
Search Filters Issue : When we moving between the vertices or search results, the current search filters will not clearing and applying for new search result page 

### ISSUE THREAD

**Issue by GangadharMFord** [microsoft-search/pnp-modern-search#2385]
Hi Team,

I'm facing the below problem with search filters when I move between the search results page.
In First results page, Applied some filters and able see the data according the filter condition and then moved or clicked in another vertices and the current filters in the previous search results will carry forwarding to new search results section and sometimes (if there data according to the filter selection happened in previous results) there is data as well. With my checking filter conditions are carry forwarding to new search results and able to see no data.

Kindly help me out is this the expected behavior for search filters Or should automatically clear when will move between the vertices / search results pages?

**Comment by wobba** [comment]
Will close this one as it does not use the bug template to help triage/repro. Please re-log with proper use of the template.
