### ISSUE TITLE
V3.14 filters not working when paging through results

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#2394]
### Check existing issues before logging new ones
I tried upgrading to v3.23 but am seeing errors so stuck with 3.14

**For any question regarding Web Parts usage, please use the ["Discussions"](https://github.com/microsoft-search/pnp-modern-search/discussions) tab instead of creating a new issue.**.

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
3.14

**Describe the bug**
The filters don't work when you go to page 2+ of results

**To Reproduce**
1. Add results web part and filter web part to page
2. Configure paging so there are 2 or more pages and you can reproduce the bug
3. Appy a filter
4. Go to page 2 of results
5. Clear the filter or select a different filter

**Expected behavior**
Applying or clearing a filter should reset the results

**Screenshots**

**Desktop (please complete the following information):**
 Chrome

**Additional context**

**Comment by wobba** [comment]
We won't patch fix older versions, so either upgrade, or preferably manually replace what you have with v4 web parts.
