### ISSUE TITLE
Results shown when search box is empty in PnP Modern Search version 4. 

### ISSUE THREAD

**Issue by poobalu** [microsoft-search/pnp-modern-search#2402]
Results shown when search box is empty in PnP Modern Search version 4. 

**See below url for discussion:**
https://github.com/microsoft-search/pnp-modern-search/issues/1721

**Version used**
4.7.0.0 - https://microsoft-search.github.io/pnp-modern-search/

**Describe the bug**
The search results should be empty with no results when no search term has been entered in the search box.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to search results web parts settings
2. On connections tab connect to search box, and leave the "Use a default value" checkbox unchecked
3. Publish the page
4. Browse to the search page to see search results without entering anything in search box.

**NOTE:** We alos changed Query template to **{?{searchTerms}}** from Query template to **{searchTerms}** still results shown when search box is empty.

![Uploading Search-box-page1-4.jpg…]()
![Search-results-page1](https://user-images.githubusercontent.com/4516403/193166650-a76ff9eb-1488-4752-b81a-7b71cd0028f2.jpg)
![Search-results-page2](https://user-images.githubusercontent.com/4516403/193166673-b99be329-1b8d-4ac3-838e-c9792f54ddea.jpg)
![Search-results-page3](https://user-images.githubusercontent.com/4516403/193166699-18b5bd1d-e2b3-4d58-8800-0d1ccf298ec0.jpg)
![Search-results-page4](https://user-images.githubusercontent.com/4516403/193166720-6a6cfd4d-cba3-4287-bd68-a51ed4701fa8.jpg)

**Comment by wobba** [comment]
It's an API change, not web part issue. Try this query template instead `{?{searchTerms}}` and see if this resolves it for you.

**Comment by poobalu** [comment]
Hi @wobba , We have alos changed query template to {?{searchTerms}} and tested, still results shown when search box is empty.

**Comment by wobba** [comment]
I cannot repro. I don't get results using either of the formats using v4.7.

**Comment by wobba** [comment]
Stale issue
