### ISSUE TITLE
Referring custom css in custom handlebar template not working after upgrade

### ISSUE THREAD

**Issue by arunakshi** [microsoft-search/pnp-modern-search#2408]
**Version used**
 4.7.0

**Describe the bug**
We had v3 handle bar templates where we referenced our custom css as external stylesheet in the handlebar template, like this:    `<link rel="stylesheet" href="https://xxxdev.sharepoint.com/sites/mysite/SiteAssets/TeaserTemplates/Custom-Renderer-Template.css">`

We are upgrading now to v4.7.0 and found that the above CSS loading is not working anymore. It is loading the CSS sometimes, however the CSS is not applied. 

The CSS is applied to my components if I add styles directly in the handlebar template in between <style> tags. I want to avoid this since we have the same styles applied for placeholder elements and data/content elements. 

**To Reproduce**
1. Take any external css file and reference it in V4 of custom handlebar template with <Link> tag
2. Configure MSW with custom handlebar template. 
3. See if the CSS is applied or not.

**Expected behavior**
There should be no need to change the CSS references in custom handle bar templates.

**Comment by FranckyC** [comment]
In v4, all scripts and links are trimmed for security reasons so it is expected. If you really need to include this specific CSS you can:

- Add inline classes in `<style></style>` attribute.
- Reference your CSS using the Script Editor Web Part (https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor).
