### ISSUE TITLE
PnP Search Refiner Web Part is showing wrong count when using multiple refiners

### ISSUE THREAD

**Issue by satyaagar** [microsoft-search/pnp-modern-search#2415]
**Version used**
Ex: 4.7

**Describe the bug**
PnP Search Refiner Filter (v4) web part shows wrong count when used multiple refiners. Usually its happens after applying second refiner when there in no result for any of the previously applied filter values.  Please see attached screenshots.

**To Reproduce**

Configured results page with search results and 2 refiners in my case configured with FileType and SPSiteUrl 
Perform some search and select filetype (aspx,csv,txt) refiner to narrow down the results. results filtered based on 3 selected filetypes and showing results and refiners with count correctly.
Now filter on siteUrl refiner with some site urls values and apply filters.
Now results web part is filtered correctly and showing correct count as well, but filetype filter still shows old selected refiners with old counts mainly for those who are having 0 results after applying second refiner.
If deselect any filetype refiner item then it will remove that item immediately (without performing Apply/clear action).

**Expected behavior**
The previously selected refiners values should be cleared if they are not having any results after applying second filter.

**Screenshots**
![image](https://user-images.githubusercontent.com/50171938/194265319-8d10c6f3-f74a-4832-a3cb-ae7a31376cbd.png)

![image](https://user-images.githubusercontent.com/50171938/194258923-f5ad2dc7-a32a-48e0-99a3-430d3c0d6afe.png)

**Desktop (please complete the following information):**
 - Browser  Edge, chrome

**Additional context**

**Comment by wobba** [comment]
Please fill out all fields in the issue template, if not we will close this one.

**Comment by satyaagar** [comment]
> Please fill out all fields in the issue template, if not we will close this one.

Hi, I have updated the issue now.. please let me know if any more information required.

**Comment by wobba** [comment]
To be sure, you are using v4.7?

**Comment by satyaagar** [comment]
> To be sure, you are using v4.7?

Yes. 4.7

**Comment by wobba** [comment]
Next step, look at the response coming back on the search API call. If the counts there show what the UX shows then this is an API issue. The web parts cannot control the counts coming back on the API.
