### ISSUE TITLE
Cannot Sort by Title or any other field

### ISSUE THREAD

**Issue by GGuizani** [microsoft-search/pnp-modern-search#2417]
**Version used**
4.6.1.0

**Describe the bug**
When trying to sort by a column for exemple : Title , we have a problem in the client tenant , however it works in the workbench and in the development tenant .
We tried debugging but we cannot discover the problem .

**To Reproduce**
Search by a keyword
Sort by title

**Expected behavior**
The results search table should be sorted by title .

**Screenshots**
**Test in the workbench :**
![Tri par titre _environnement dev](https://user-images.githubusercontent.com/75728985/194332830-ad8a4be3-9dd5-4c83-b7b3-83f98b343ad1.gif)

**Test in the the client tenant :**
![Tri environnement stago](https://user-images.githubusercontent.com/75728985/194335973-f448327b-e546-49f0-af76-b70842f313b4.gif)

**Desktop :**
 - chrome , firefox

Thank you for your help

**Comment by GGuizani** [comment]
So i found the solution to this problem here : https://github.com/microsoft-search/pnp-modern-search/issues/551
As i see here : https://microsoft-search.github.io/pnp-modern-search/usage/search-results/layouts/#details-list
That it won't work for sorting when using an Handlebars expression , it needs to specify the field from the separate dropdown.
When i applied it , it doesn't work , so i remove the handlebars expressions , i applied the sort , it works .
Then i added the handlebars expressions , i specified the field from the dropdown that appears when i check the sortable option , an it works now even with handlebars expressions. 💯 
![image](https://user-images.githubusercontent.com/75728985/194573855-28413a6f-f21e-412a-b768-81556d14b5f7.png)

**Comment by GGuizani** [comment]
It didn't work for me , please i'm waiting for your help .

**Comment by wobba** [comment]
You have to follow the issue template when logging. If not we will close it.

**Comment by GGuizani** [comment]
Issue was updated

**Comment by wobba** [comment]
As you are using v4.6, can you still repro with 4.7 or 4.8-beta?

**Comment by GGuizani** [comment]
Thank you for your eply , when we update the version to 4.7 in the AppCatalog , we cannot find the new pnp search results + search filters + search box in the add wepbart page .
Even the page that we created is empty and we have a message that says that the add in is maybe deleted .
We use 4.6.1.0 because we found an extensibility feature to add export button to export result search . 
The client needs the export button .
https://github.com/ellinge/pnp-modern-search/tree/feature/export-to-csv

**Comment by wobba** [comment]
When you overwrite a previous version sppkg with a new no change has to be made.. it should updated automatically for all pages where it's used. You can also try 4.7 for your scenario in a dev/test tenant if you want to stay on 4.6.

**Comment by GGuizani** [comment]
We have tested with the v4.7 and we got the same issues  , i cannot select a field because the dropdown values is empty .
Here is a screenshot about the sort by column problem :
![Tri par titre v4 7 0](https://user-images.githubusercontent.com/75728985/196153123-2bdd03c3-442c-47d1-af6c-1a3c1f26cd49.gif)

**Comment by GGuizani** [comment]
Hello, 
Any updates about this issue ?

**Comment by wobba** [comment]
@GGuizani updates will be written when they happen. And someone has to decide they want to look into this, and verify with the v4.8-beta codebase. If there are no comment, it means there are no updates.

**Comment by kasperbolarsen** [comment]
@wobba do you just ned someone to verify the scenario using the latest beta, or should it be someone with the ability to debug the code?

**Comment by wobba** [comment]
Need someone to verify the issue still exists in the develop code branch for starters.

**Comment by kasperbolarsen** [comment]
I'll look into it , either tonight or early next week

søn. 20. nov. 2022 13.02 skrev Mikael Svenson ***@***.***>:

**Comment by kasperbolarsen** [comment]
Any chance a kind soul can provide a dev build for me to test? Building it myself is beyond my abilities :-(

**Comment by kasperbolarsen** [comment]
@GGuizani can you verify the settings for the Managed Property Title in your environments? Using a trial tenant it sure looks like the Title property is NOT sortable out of the box: ( just for fun I added a RefinableString property to the columns and sorting seems to work fine with that property)
![image](https://user-images.githubusercontent.com/20593570/203032366-14f00cd5-ef44-41bd-9c2b-8d72637ae0b0.png)

**Comment by kasperbolarsen** [comment]
@Reyansh0802  Hi, just to be sure we are on the same page: This is by no means a PnP Modern Search Web parts issue as it is related to updating the out of the box search schema in order to make the Title field sortable. 
It is a task for the Search admin on each tenant, and it will not be handled by this project.
That said you should be able to map to a RefinableString and use that RefinableString in the web part for user defined sort :-)

**Comment by Reyansh0802** [comment]
@kasperbolarsen :We didn't have this issue in previous versions. We are using the 4.7.0 version now and  not able to select any field for **sort select field** under managed columns. It is showing no field( nothing is populating in the dropdown) but we are able to add the sort field under sort settings. We have already mapped the respective RefinableString XX crawled properties as well, and still it's not working. Please suggest

**Comment by kasperbolarsen** [comment]
It us see if I got this right: 
You have mapped the crawled properties to a RefinableString, this RefinableString does show up in the debug view with a value?
You have defined the RefinableString as a sortable column , like this:
![SettingSortableColumn](https://user-images.githubusercontent.com/20593570/208846847-5b02a722-02ea-4cb4-ba9e-080fcbbba51f.png)

Finally you have updated the column settings like  this? :
![Columnsettings](https://user-images.githubusercontent.com/20593570/208847135-08f1ba21-5a1e-4f80-aa77-0863ba906aa0.png)

**Comment by kasperbolarsen** [comment]
@Reyansh0802 is this your configuration?

**Comment by melkinsco** [comment]
Having the same issue with 4.8.  This only appears with the Details List View.  The filter part shows with both Card and List view. I'm migrating from V3 to V4 and have the same attributes in use.  Works fine in V3 but not in V4 so I know my attribute is sortable (RefinableString).

**Comment by kasperbolarsen** [comment]
@melkinsco   Are you sure this is the same issue? This original issue was related to column sorting on the Title property. You are writing about the filter web part?

**Comment by kasperbolarsen** [comment]
@Reyansh0802  @GGuizani I have just checked in version 4.9 if I can sort on Title ( mapped to a RefinableString) and it works just fine.
Any comments or questions? Otherwise I will close this issue by the end of June 23

**Comment by melkinsco** [comment]
@kasperbolarsen yes, but not the title.  Rather than created and summary, we have two custom properties (RefinableString) based on topic classifications.  The arrow didn't appear for those fields.

**Comment by melkinsco** [comment]
@kasperbolarsen problem resolved. I'd missed a sortable field setting (assumed it carried over from the managed property setting).

**Comment by kasperbolarsen** [comment]
issue resolved
