### ISSUE TITLE
Previous Filters will be applying for new search or when change the search vertices.

### ISSUE THREAD

**Issue by GangadharMFord** [microsoft-search/pnp-modern-search#2422]
Thank you for posting this filters issue and We also facing the same issue with PnP filters.
I have also similar scenarios like below,

User first searched with keyword and applied some filters to the data then immediately changed the vertices (Example from SharePoint vertices to File) then the current applied filters are forwarding to new search results (With in new search vertices from SharePoint to File). Customer expectation will be the current Filters should not apply on new search or change vertices selection and it should delete automatically (Applied filters from previous search - vertices).
User first searched with keyword and applied some filters to the results data then changed search keyword without clearing the current filters then also the previous filter conditions will be applying to the new search.
User expecting will be delete the previous filters automatically if the search string will changed or moved between new or other vertices.
please help on the above two scenarios .... thank you in advance.

**Comment by wobba** [comment]
Will close as the issue does not follow the issue template.
