### ISSUE TITLE
Tags in Search Filter Stopped working after upgrade to 4.7

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#2426]
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/2409

<div type='discussions-op-text'>

<sup>Originally posted by **nthoman** October  4, 2022</sup>
I went from 4.3 to 4.7 and now my "PnP - Search Filters" stopped working for "Tags" only. My other search filters work fine. The search filter will show the correct number of records but when I try to filter it down the Search Results will change to 0 records.

![image](https://user-images.githubusercontent.com/48287847/193829915-2848883d-9b4b-4e69-90b4-4cfb22406e06.png)
 
![image](https://user-images.githubusercontent.com/48287847/193830099-8df16899-72f8-4f8c-b79c-18f154a883cd.png)

![image](https://user-images.githubusercontent.com/48287847/193830391-fa8c2289-440b-4515-8b5c-e12405d01afe.png)
</div>

**Comment by wobba** [comment]
@FranckyC do you know if this is resolved in v4.8

**Comment by FranckyC** [comment]
@wobba This has to do with the `owstaxidmetadataalltagsinfo` property and we've made a fix in 4.8-beta. @nthoman can you test with this version?

**Comment by kasperbolarsen** [comment]
closed due to inactivity on OPs side
