### ISSUE TITLE
Change german translation of sorting text in filter web part

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#2435]
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/2413

<div type='discussions-op-text'>

<sup>Originally posted by **SoerenOhlsen** October  5, 2022</sup>
Hi,

our customer mentioned to rename the default sorting-button. Maybe it can also be made configurable through the JSON configuration in the SortList section.

Or is there already a solution to do so? 

![image](https://user-images.githubusercontent.com/67585513/194125819-04bb52c5-3da1-4a00-b998-9de452aef0ed.png)
</div>

**Comment by Georg-Trixl** [comment]
In this context I would say <Default> translates best as <Standard> .... (just as an opinion as Austrian - German nativ speaker). 
On the other side, to get something like that translated to german is nice, but not really important, rather low priority. Almost every german nativ speaker had in school english lessons.
@wobba if further translation is required contact me.

**Comment by wobba** [comment]
Changed as per suggestion in discussion.
