### ISSUE TITLE
Search Verticals not saving with link URL

### ISSUE THREAD

**Issue by StarsandPlanets99** [microsoft-search/pnp-modern-search#2436]
**Version used**
4.7

**Describe the bug**
When Configuring the search verticals when selecting Is hyperlink and adding the link URL the link URLs are not saving. They are resetting to blank

**To Reproduce**
1. Configure search vertical
2. Insert the tab name
3. Add  a fluent icon
4. Activate the option - is hyperlink
add the URL (have tried https://www.bing.com and another sharepoint site.  Have also tried adding parameter q={SearchBoxQuery} at the end )
5. In Open behaviour -Select Use the Current Tab/Open in new page
6. Select Show link Icon
7. Save
8. Go back and the URL is blank

**Expected behavior**
The URL should be saved

**Screenshots**
![image](https://user-images.githubusercontent.com/115179834/195019333-1b72fe75-6659-44d4-ac16-289e3229455e.png)
![image](https://user-images.githubusercontent.com/115179834/195019582-a33e26c0-d6e9-4d48-aab0-67d912409ad7.png)

**Comment by till-llit** [comment]
this is resolved in 4.8.0-beta
