### ISSUE TITLE
open file in new tab?

### ISSUE THREAD

**Issue by PeterVos111** [microsoft-search/pnp-modern-search#244]
Hi, 

According to earlier communications, the new update should let files open in a new tab. Is there anything i have to configure for this except updating the app? the files are currently still opening in same tab. 

Regards,

**Comment by wobba** [comment]
@PeterVos111 depends on your template.. you might have to pick template back and forth. I suggest configuring a new page and test to verify.

**Comment by PeterVos111** [comment]
I double checked if the update was successfull, 
Checked with both Chrome and FireFox browsers,
Installed on a different SP-Site.
and checked with a different Template.

No luck as of yet. There isn't anything i have to do after getting the new version of the app right? 
I go to sitecontent -->search webparts --> Details --> Get new version (3.12)

**Comment by wobba** [comment]
Two of the templates failed, so fixed them now. Thank you :)

**Comment by wobba** [comment]
Added in the update v3.12.1 release

**Comment by PeterVos111** [comment]
Thanks for quick solve!
