### ISSUE TITLE
Search Results Web Part -- Manage Columns changes are not saving

### ISSUE THREAD

**Issue by sivakavuri** [microsoft-search/pnp-modern-search#2444]
**Version used**
Ex: 4.7.0

**Describe the bug**
I try to change the Column Value under Manage Columns. The changes are not saving.

**To Reproduce**
1. Add Search Results Web Part
2. Click on EditWeb Part
3. Go to second page
4. Click on Manage Columns
5. Change the value under Manage Columns "Column Value"
6. Hit Save
7. Click on Manage columns and if you observe it still retains the old value

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by PicGadm** [comment]
We are also having this issue. Not only with the "Details List", also the "Cards" layout.
We cannot save changes to the "Manage card fields".

**Comment by wobba** [comment]
Did you try with v4.8.beta?

**Comment by PicGadm** [comment]
> Did you try with v4.8.beta?

No we did not yet tried to install the V4.8, because it is a Beta and we do not have a test environment available at the moment.

**Comment by PicGadm** [comment]
> Did you try with v4.8.beta?

Tried it with the V4.8 Beta, and the issue is resolved.
