### ISSUE TITLE
Result webpart : SPContentType 

### ISSUE THREAD

**Issue by pereirautv** [microsoft-search/pnp-modern-search#2463]
Hello ,
I have problem displaying the SPContent Type to my list view. 
![1](https://user-images.githubusercontent.com/59980484/196694941-22aca118-0694-44a1-ae65-ca72503b209c.png)

It works in the filter webpart but not inte result webpart. 
![2](https://user-images.githubusercontent.com/59980484/196694051-482f40dd-ea5e-4f1b-8e76-3cc087fb123d.png)

The Content type are made from SharePoint Syntext. Don't know if this can affect the result. 
When i looked in the debug mode the SPContent Type is set to null. 
![Skärmbild 2022-10-19 141541](https://user-images.githubusercontent.com/59980484/196694265-450f3d11-1be5-4455-aba1-814fd5238305.png)

Anyone know how i can display the ContentType?

**Comment by wobba** [comment]
SPContentType is set to not be retrievable in the search schema, so this is expected.

![image](https://user-images.githubusercontent.com/51104/197389388-0316d34e-1d2b-46c5-be88-7bf2b71f0a63.png)
