### ISSUE TITLE
'Search Results' web part > 'Manage columns' does not allow me to select properties to add new columns

### ISSUE THREAD

**Issue by aaronrwilson** [microsoft-search/pnp-modern-search#2465]
**Version used**
4.7.0.0

**Describe the bug**
'Search Results' web part > 'Manage columns' does not allow me to select properties to add new columns.

**To Reproduce**
1. Add 'Search Results' web part to page.
2. On page 1 of setting pane, verify 'FileType' is selected in the 'Selected properties' setting.
3. On page 2 of settings pane, click 'Manage columns'.
4. Fill in 'Column display name' of 'File Type' and attempt to select that 'Column value' -- but nothing happens -- the dropdown is inoperable and although I can place the cursor in the text box, typing does nothing, so I'm unable to add the column.

**Expected behavior**
Should be able to select the existing property and add the column.

**Screenshots**
![image](https://user-images.githubusercontent.com/40477360/196740917-8b839258-335b-449b-8748-d125390b4526.png)

**Desktop (please complete the following information):**
 Browser: Chrome, Edge (same behavior on both, including incognito mode)

**Additional context**
I've successfully used v3 with no related issues previously.

**Comment by aaronrwilson** [comment]
I just had the same issue with v4.6.1.  I then tried v3.2.1.0 and it works fine:

![image](https://user-images.githubusercontent.com/40477360/196746756-613eca3c-6e14-40a9-8121-a960c1d080fc.png)

**Comment by wobba** [comment]
Can you re-test with 4.8-beta?

**Comment by kasperbolarsen** [comment]
Have you tried to add a new Search results web part on the page and set it up like the one with the issue?
It sounds like an issue with the properties stored within the web part

**Comment by MarkUden** [comment]
I've just created a new page and added the Search Box and Search Results web parts. The search works, but again I can't select any fields to display or sort by.

**Comment by MarkUden** [comment]
Update: the reason the data wasn't displayed on the Search Results was that all the top results were from a library that wasn't set up correctly with the site columns used in the search. Now I've corrected that, it is working correctly.

However, I am still unable to select fields within the Search Results web part configuration. I just get the rotating "in progress" icon until eventually the page edit times out.

**Comment by wobba** [comment]
Can you enter it manually as a workaround? The API to list props is a somewhat non-API which cannot be relied upon (unfortunately).

**Comment by wobba** [comment]
* Ensure you have results in the result web part
* This will show a list of properties returned on results

But that list has many non-refinable properties. So will change the UI to be input only, not a combobox.

**Comment by wobba** [comment]
Added some helper text below the grouping field picker.
