### ISSUE TITLE
Loading chunk error with Search Results web part

### ISSUE THREAD

**Issue by sunshine202de** [microsoft-search/pnp-modern-search#2466]
**Version used**
4.7.0.0

**Describe the bug**
When utilizing the Search Results web part, a loading chunk error is received:
"Loading chunk 20 failed. (error: https://hcgroupnet.sharepoint.com/sites/AppCatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/chunk.pnp-modern-search-results-detailslist-layout_a3a1b354b0e9a77dadd2.js)". 

The number of screens for the web part reduces from four to two.

**To Reproduce**
1. Place **PnP - Search Results** in edit mode
2. Advance to Screen 2
3. Click on 'Details List' or 'List' under **Available Layouts**

**Expected behavior**
Expect to see the search results in list or detailed list format.

**Screenshots**
![loading-chunk-error2](https://user-images.githubusercontent.com/116263526/196912194-269707ad-1cc5-41b8-a57c-683e8dcff0a2.png)
![loading-chunk-error](https://user-images.githubusercontent.com/116263526/196912203-1aa084e9-f1dd-4427-baf0-e9e9e857d0ba.png)

**Desktop (please complete the following information):**
 - Edge Version 105.0.1343.33 (Official build) (64-bit)
 - Using PC with Windows 10

**Additional context**
Issue is not occurring on the two sites where web part were loaded.

**Comment by wobba** [comment]
This is related to #2405
