### ISSUE TITLE
Not able to execute "gulp serve --nobrowser" command on my machine

### ISSUE THREAD

**Issue by AmitTyagi1** [microsoft-search/pnp-modern-search#247]
**Version used**
3.12.0

**Describe the bug**
I have downloaded the latest version of this project and trying to build using Visual Studio code. But, i am getting the error while running the following command.
Command => gulp serve --nobrowser
Error => 
[09:16:11] Local gulp not found in C:\Amit1\PnPDemo\SPFxWebpartsDownloaded\pnp-modern-search-master\pnp-modern-search-master\search-parts
[09:16:11] Try running: npm install gulp

I have the following versions of relevant software my machine.
1.	Node – 10.20.1
2.	Gulp – 2.2.0
3.	npm – 6.14.4
4.      Visual Studio Code - 1.44.2

**To Reproduce**
1. Open Visual Studio Code
2. Open the "Search-Parts" folder
3. Open the terminal
4. Execute the command "gulp serve --nobrowser"
5. The following error appears and the command is terminated.
[09:16:11] Local gulp not found in C:\Amit1\PnPDemo\SPFxWebpartsDownloaded\pnp-modern-search-master\pnp-modern-search-master\search-parts
[09:16:11] Try running: npm install gulp

**Expected behavior**
After executing the command successfully the "Workbench.aspx" page should open in the browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/33560478/81220371-0af64700-8f96-11ea-8ce1-e8445192896c.png)

**Comment by wobba** [comment]
Can you build a blank SPFx project you create?

**Comment by AmitTyagi1** [comment]
Yes @wobba i tried just now and i was able to create and execute a test Hello-World project

**Comment by wobba** [comment]
I would try to delete node_modules and run `npm i` again and ensure you have SPFx v1.10. Shouldn't be any special tricks. As per docs we also recommend using `npm run serve``for the project for a faster debug build.
