### ISSUE TITLE
Search Results web-part returning error when used with Search Box web-part

### ISSUE THREAD

**Issue by AmitTyagi1** [microsoft-search/pnp-modern-search#248]
**Version used**
3.12.0

**Describe the bug**
I downloaded the ".sppkg" file and added it to App catalog in my environment. Then i added the Search Box and Search Results web-parts to a site page.  I configured them by following the details on [this site](https://microsoft-search.github.io/pnp-modern-search/search-parts/getting-started/). But i am receiving the following error.
> Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"A null value was found for the property named 'Direction', which has the expected type 'Edm.Int32[Nullable=False]'. The expected type 'Edm.Int32[Nullable=False]' does not allow null values."}}}

**To Reproduce**
1. Edit a modern site-page
2. Add "Search Box" webpart to the page
3. Enter your text in "Placeholder text in search box" property
4. Add "Search Results" web-part below Search Box webpart
5. Set the configurations as shown in the following screenshots
6. It shows the error mentioned in the error description even after entering anything in the Search Box

**Expected behavior**
Expected to see the results based on the text entered in the Search Box..

**Screenshots**
The non visible settings are left at default level.
![image](https://user-images.githubusercontent.com/33560478/81237902-992df580-8fb5-11ea-902d-84b8062cd169.png)

**Desktop (please complete the following information):**
 - Browser used -> Chrome 79.0.3945.117

**Comment by malcom1120** [comment]
This issue was just corrected today with 3.12.1 release.

**Comment by AmitTyagi1** [comment]
Thanks for the information @malcom1120 . Actually i already had an issue (#247 ) open for not being able to build this project on my machine. So, I downloaded the .sppkg file which was available under the assets earlier. But i checked it is not available now. Can you please upload that to under the assets? I will really appreciate your help.
