### ISSUE TITLE
Enable Localization is not working with V4.7.0

### ISSUE THREAD

**Issue by arunakshi** [microsoft-search/pnp-modern-search#2489]
**Version used**
4.7.0

**Describe the bug**
Managed Metadata values are not showing with Labels when we enable localization in the webpart settings. There is no change we see in the managed metadata values, if we enable / disable localization.

**To Reproduce** 
1. Add V4.7.0 version webpart to a page.
2. Select Managed metadata to be displayed in the debug mode.
3. Enable Localization, it always display the resulted values with Guid's.

**Expected behavior**
We expect Labels are displayed when we enable Localization setting for modern search webpart.

**Screenshots**
V4 webpart results when Localization enabled:

![image](https://user-images.githubusercontent.com/12812202/198130055-d9917098-d818-4274-a0da-e0777e207802.png)

V3 webpart results when Localization enabled:
![image](https://user-images.githubusercontent.com/12812202/198130294-3071391f-bf02-41da-8d5c-5043d71df14e.png)

**Desktop (please complete the following information):**
 - Browser : Chrome, Edge

**Comment by arunakshi** [comment]
Found that it has to be handled differently when localization enabled.

**Comment by ileana2019** [comment]
Hi @arunakshi , I have the same issue; How did you solve it? Thank you!
