### ISSUE TITLE
Update 3.12.1 had a bugfix for opening new tabs. is not working yet

### ISSUE THREAD

**Issue by PeterVos111** [microsoft-search/pnp-modern-search#249]
**Version used**
3.12.1

**Describe the bug**
My documents open in the same tab

**Expected behavior**
selecting the file opens the file in a new tab

**Desktop (please complete the following information):**
 - used chrome and firefox for testing

**Comment by wobba** [comment]
@PeterVos111 I tried all templates. Can you use use browser tools and inspect the anchor tag. Should look something like this:

![image](https://user-images.githubusercontent.com/51104/81269193-46058280-9049-11ea-8e3b-fd0dfaefafe5.png)

**Comment by PeterVos111** [comment]
I was not able to find that tag anywhere with a target arribute for the searchresults webpart. i could only find them for other links on that page (nav bar) Maybe i am looking in the wrong place? I'm not a webdeveloper.

**Comment by wobba** [comment]
@PeterVos111 can you re-install the updates sppkg, and ensure it's published. Create a new page, add search webpart and re-test.

**Comment by FranckyC** [comment]
@PeterVos111 What layout are you using?

**Comment by PeterVos111** [comment]
Such an easy way to fix it, i am a bit embarrassed.

I deleted the older versions of this app in the appcatalogue, reuploaded it (new file). That was all i needed to make it work. 
This also fixed some other issues i had earlier that would have been fixed in previous versions. 

Thanks guys!
