### ISSUE TITLE
Mapped Title to RefinableString and now it wont show up in the search Results

### ISSUE THREAD

**Issue by nicolesherman00** [microsoft-search/pnp-modern-search#2492]
Not sure what I did wrong here. I went and mapped my title to a refinable string managed property hoping It would allow me to sort by Title in the search results but it wouldnt work with the refinable string assigned to the title layout slot.. Then I removed the mapping in the refinable string managed property and reassigned Title to the Title layout Slot, but it wont bring anything in now. I am able to see the title in other webparts so I do not believe this is a Sharepoint index issue.

![image](https://user-images.githubusercontent.com/22782498/198418250-d11e39ca-e099-4d2b-b6ec-0f7cddee1606.png)

![image](https://user-images.githubusercontent.com/22782498/198421123-cebf6ec6-8bd5-4774-be7c-4958f542a1d3.png)

**Comment by nicolesherman00** [comment]
This is an existing issue. Will comment on their post. (also didnt use the issue template so not worth keeping on here :))

**Comment by wobba** [comment]
Ask in discussions and you are likely mapping the wrong crawled property. Map the Office:2 cp and you should be ok 🙂

**Comment by nicolesherman00** [comment]
Do you see that being the reason why my title is no longer showing up? I unmapped it from the managed property and it’s just gone no matter what I do.
