### ISSUE TITLE
Compact mode have a wrong image size in document card

### ISSUE THREAD

**Issue by stevebeauge** [microsoft-search/pnp-modern-search#25]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

When activating the compact mode of tile layout, thumbnails should render correctly:

![image](https://user-images.githubusercontent.com/184604/69744586-be822200-1140-11ea-8fbd-511bebe4a8bb.png)

#### Observed Behavior

When activating the compact mode of tile layout, thumbnails do not render properly :

![image](https://user-images.githubusercontent.com/184604/69744387-5d5a4e80-1140-11ea-98f4-713b5bb05f04.png)

#### Steps to Reproduce

1. Add a search result web part in a page. 
2. Set its query to `*` 
3. Choose tile layout and check compact mode

**Comment by FranckyC** [comment]
Resolved by #29
