### ISSUE TITLE
Small bug in search vertical rendering - hyperlink with results count

### ISSUE THREAD

**Issue by Georg-Trixl** [microsoft-search/pnp-modern-search#250]
**Version used**
V 3.12.1

**Describe the bug**
I have normal verticals and a hyperlink to an external page.
The hyperlink shows a result count - but since this a external page, this should not displayed.

**To Reproduce**
I think this is easy reproducible, if that is not possible, do not hesitate to contact me.

**Expected behavior**
When the hyperlink checkbox is clicked

**Screenshots**
![Bug-V3 12 1-0](https://user-images.githubusercontent.com/62948158/81270206-a9dc7b00-904a-11ea-9480-d057b6090c5b.PNG)

**Desktop (please complete the following information):**
Firefox 75

**Comment by FranckyC** [comment]
Hi @Georg-Trixl , good catch, this will be fixed for the next release.

**Comment by FranckyC** [comment]
Hi @Georg-Trixl , should be resolved by #260. Thanks for your contribution.
