### ISSUE TITLE
Org Chart in Persona Card showing disabled users

### ISSUE THREAD

**Issue by sympmarc** [microsoft-search/pnp-modern-search#2507]
**Version used**
Ex: 4.6.1

**Describe the bug**
When displaying people using the People layout, we can choose to show the persona card on hover. I think there's a bug in that implementation, in that people who are disabled in AAD are showing up. This doesn't match the behavior of the Org Charts in Microsoft Search results.

**To Reproduce**

To reproduce, you need to have user profiles with Manager values. Those user profiles must be disabled in AAD. If you search for the Manager in Microsoft Search and look at the Org Chart, you won't see the disabled user(s). If you search in the PnP Modern Search Web Parts and look at the Org Chart in the persona card, you will.

**Expected behavior**
Consistency between the two Org Chart implementations

**Screenshots**
NA

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**
We've tested this pretty thoroughly and believe it to be a bug.

**Comment by wobba** [comment]
I assume this is the mgt card? And if so their repo is https://github.com/microsoftgraph/microsoft-graph-toolkit/issues and you can close this issue 🙂

**Comment by sympmarc** [comment]
Not sure, as I'm just using this setting on the 2 of 4 property panel for the PnP Search Results Web Part. Wouldn't it be how the persona card is used in that implementation?

![image](https://user-images.githubusercontent.com/1295627/199587163-9b34c442-d08e-438f-ae20-f0dfa38fe786.png)

**Comment by wobba** [comment]
Correct, and we reuse the graph toolkit components and have no control over their API calls or logic. We just load the card with a UPN and things happen.

**Comment by sympmarc** [comment]
Ok, got it. I'll lodge a complaint over there.

**Comment by sympmarc** [comment]
[Issue in MGT](https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/1929)

**Comment by sympmarc** [comment]
The MGT team is putting a fix into the December release.

**Comment by wobba** [comment]
Packages are now updated in the dev branch

**Comment by sympmarc** [comment]
Just out of curiousity, do you have a timeframe for the next release? I won't hold you to it. :)

**Comment by wobba** [comment]
Sometime in 2023 😁

**Comment by Ami99049** [comment]
Have you released the new version with the changes in Hover Card org Chart or is it still in development phase

**Comment by kasperbolarsen** [comment]
Please review this issue, as it will inform you that the Org Chart is a MGT component,  and just used by this project.

**Comment by Ami99049** [comment]
@kasperbolarsen I installed pnp version 4.8 and still Disabled users is visible in Hover Card Org Chart via Microsoft Search as Data source. Is there any way to exclude those users.

**Comment by kasperbolarsen** [comment]
Not in this project as we are just using the MGT component. 
You should log the issue with MGT.
