### ISSUE TITLE
Can we limit the scope of search results to Hub site and its connected sites ?

### ISSUE THREAD

**Issue by AmitTyagi1** [microsoft-search/pnp-modern-search#251]
Can we limit the scope of search results to Hub site and its connected sites only ?

Please suggest if it is possible by any configuration already.

**Comment by Georg-Trixl** [comment]
Hi @AmitTyagi1 
By using provided buttons in the search configuration panels or further development this is not possible.
But you can specify search parameters on your own, this will deliver exactly the search result that you are looking for and of course this has also a problem attached.

**Basically**
Search does not know anything about hierarchy and hubs sites and what ever is connected to it. 

**How to achieve a "Hub-Site search" and connected results?**
If you configure search parameters as for example in search verticals, you narrow down search results to specific paths. Specify there the path to your hub site and to each connected site.
{searchTerms}  
    ( 
        (
            Path:"https://tenant.sharepoint.com/sites/WS_*" OR 
            Path:"https://tenant.sharepoint.com/sites/HS_*" OR 
            Path:"https://tenant.sharepoint.com/sites/CS_*" 
        )  
        -Path:"https://tenant-my.sharepoint.com"  
        -Path:"https://tenant.sharepoint.com/sites/mtest/*"  
        -Path:"https://tenant.sharepoint.com/sites/migtest/*"  
        -Path:"https://tenant.sharepoint.com/sites/migtestv2/*"  
        -Path:"https://tenant.sharepoint.com/sites/migtestv3/*" 
        -Path:"https://tenant.sharepoint.com/sites/archive/*" 
    )   

**Whats the attached problem on that solution?** 
When somebody associates a site to the hub site, you need to be informed by that guy, in order that you can update the search parameter configuration.

**Comment by wobba** [comment]
Don't listen to @AmitTyagi1.

Use this in the query template field:
`DepartmentId:{PageContext.hubSiteId}`

See https://microsoft-search.github.io/pnp-modern-search/search-parts/search-results/#custom-query-variables and https://www.techmikael.com/2018/04/working-with-hub-sites-and-search-api.html for reference.

**Comment by AmitTyagi1** [comment]
> Don't listen to @AmitTyagi1.
> 
> Use this in the query template field:
> `{searchTerms} DepartmentId:{PageContext.hubSiteId}`
> 
> See https://microsoft-search.github.io/pnp-modern-search/search-parts/search-results/#custom-query-variables and https://www.techmikael.com/2018/04/working-with-hub-sites-and-search-api.html for reference.

Sure @wobba will try your suggestion.

**Comment by wobba** [comment]
More effective for the search system and works when more sites are added to the hub.

**Comment by AmitTyagi1** [comment]
Hi @wobba, I tried your suggestion. But it doesn't give me any results. I am not sure if i missed something, but below is how my Search Results configuration looks. 

Do i need to make any related changes on the "Search Box" also ?

I tried pasting the actual Site Id also in the query template field but it didn't worked too. Like,
`{searchTerms} DepartmentId:{11111111-1111-1111-1111-1111111111}`

![image](https://user-images.githubusercontent.com/33560478/81436766-e11c5c00-911e-11ea-9c2d-72caf02c4251.png)

**Comment by wobba** [comment]
All items should have the SiteID of the hub in the DepartmentId managed property. If you remove the {} does it work in your manual test?

**Comment by AmitTyagi1** [comment]
I tried following as per your suggestion with no luck. 
`{searchTerms} DepartmentId:11111111-1111-1111-1111-1111111111`

I am ready to test if you have any other suggestions.

**Comment by AmitTyagi1** [comment]
Is there a quick way to verify(may be using Powershell or any other means) that DepartmentId property is being populated with the SiteID of the hub in my tenant.

**Comment by FranckyC** [comment]
Hi @AmitTyagi1 , can you try to double curly braces like this: `DepartmentId:{{PageContext.hubSiteId}}`. If I remember correctly, the `DepartmentId` managed property includes `{}` already in its value.

**Comment by AmitTyagi1** [comment]
Great !!! @FranckyC  double curly braces worked. Thanks a lot for your help.

**Comment by wobba** [comment]
I might add trimming of {} as well on those props. Very inconsistent usage with and without in SP 😕

**Comment by AmitTyagi1** [comment]
Do we have a way to exclude the Site Assets and Form Templates libraries from the search results ?
