### ISSUE TITLE
Microsoft Search Datasource error: Token request previously failed

### ISSUE THREAD

**Issue by 2161669** [microsoft-search/pnp-modern-search#2514]
**Version Used**
4.8.0-beta.1

**Describe the bug**
When using the PnP Search Results Webpart and selecting Microsoft Search as the data source after granting the necessary graph api permissions, the webpart by default shows "Token request previously failed" error with 0 results.

**To Reproduce**

**Go to a SharePoint Online page**
Add a PnP Search Results Webpart
Edit the webpart and select "Microsoft Search" as a data source.
Select other items from the dropdown "Entity types to search" such as External Items, List Items, List, Sites.
0 results with error: Token request previously failed appears
Expected behavior
Search results from the site appears that come from OneDrive, SharePoint.

**Screenshots**
![image](https://user-images.githubusercontent.com/117626792/200245529-fe3c7362-7644-49a8-b100-b881ba4a53df.png)

As per bug **Microsoft Search Datasource error: Token request previously failed #2374**
I have already tried the 4.8.0-beta.1 version of the pnp search solution. still unable to get any output.

**Additional Comments**
We tried this using personal microsoft account and site, it showed results. however, when we try it in our organization's domain, it gives this error. Is there any kind of privileged access, which we are missing in our case? Please provide your input.

**Comment by 2161669** [comment]
@wobba Sure, please guide us, how we can connect and check this error. It is on high priority for us.

**Comment by kasperbolarsen** [comment]
Just tested above using 4.8 from Mikael on a trial tenant and not able to reproduce this error. Any chance it can be a timing issue?

**Comment by 2161669** [comment]
The API access was an issue. The necessary access for Microsoft Graph API were granted and it worked. 

Thanks for acknowledging. :)
