### ISSUE TITLE
 [HTTP]:500 - [CorrelationId]:aa3076a0-d0af-2000-cb87-77d2da1f7054 [Version]:16.0.0.23019 Error

### ISSUE THREAD

**Issue by GangadharMFord** [microsoft-search/pnp-modern-search#2515]
Hi Team,

I have facing HTTP: 500 correlation error for few searches keywords. 
Cross checked the network traces and found the below postquery is failing with error code 500 and please find the below details as below.
Request Method: POST
Status Code: 500 
Response header: 
Content security-policy: frame-ancestors 'self' teams.microsoft.com *.teams.microsoft.com *.skype.com *.teams.microsoft.us local.teams.office.com *.powerapps.com *.yammer.com *.officeapps.live.com *.office.com *.stream.azure-test.net *.microsoftstream.com *.dynamics.com *.microsoft.com securebroker.sharepointonline.com;
nel: {"report_to":"network-errors","max_age":7200,"success_fraction":0.001,"failure_fraction":1.0}

{"group":"network-errors","max_age":7200,"endpoints":[{"url":"https://spo.nel.measure.office.net/api/report?tenantId=XXXXXXXXXXXXXXXX&destinationEndpoint=Edge-Prod-CH1r5e&frontEnd=AFD"}]}

{
  "code": "-1, Microsoft.Office.Server.Search.REST.SearchServiceException",
  "message": {
    "lang": "en-US",
    "value": "An unknown error occurred."
  }
}

Network response : 
{"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}

**Comment by wobba** [comment]
Closed as the issue does not follow the issue/bug template to provide information needed to be able to assess what the issue can be.

**Comment by GangadharMFord** [comment]
Could you help me on choosing the template? because I have faced the same issue many times.

**Comment by wobba** [comment]
Quite easy.. when you pick "bug" just remove the text which it tells you to remove, and fill in the information for each header. Like version number, steps needed to configure the web part and how to repro etc.

**Comment by IvanTheBearable** [comment]
FYI - I am encountering this issue as well, with the Search Results web part. It seems to be intermittent, but quite frequent. Exactly the same query will sometimes work, sometimes fail. So, it seems like it is an issue with the API rather than with the Modern Search web parts.

I have [logged an issue](https://github.com/SharePoint/sp-dev-docs/issues/8639) in sp-dev-docs. @GangadharMFord may want to follow that ticket and add any other relevant information.
