### ISSUE TITLE
Open in client app doesn't work

### ISSUE THREAD

**Issue by girvol** [microsoft-search/pnp-modern-search#252]
Hi i found '[Open Search Results in Client App #75](https://github.com/microsoft-search/pnp-modern-search/issues/75)' about this topic but after changing template documents are still opened in Office Online App.

Maby i'm making a change in wrong place, could you tell me where I should change it? 

Regards,
Marek

**Comment by wobba** [comment]
I assume you have a custom template? What's a sample value rendered, and I think the browser has a say as well. Opening the SP preview is often quicker imo.

**Comment by girvol** [comment]
I don't use custom template. I'm not sure if i put this in right place, I'm putting this in column expression. When I render it as a column it gives path to file. 
Unfortunately it's not my decision and demand is to open documents in client app.

**Comment by wobba** [comment]
See this SO question whic propose a solution: https://sharepoint.stackexchange.com/questions/115089/open-docx-file-in-word-client-from-hosted-app-sp-2013
