### ISSUE TITLE
Result count is mismatch with Search refiner count.

### ISSUE THREAD

**Issue by md786** [microsoft-search/pnp-modern-search#2527]
Under search result count is displaying "42" and Left side of Search refiner its getting displayed "68". Result Count is not matching properly.
<img width="1709" alt="ResultCountIssue" src="https://user-images.githubusercontent.com/28361246/200835634-7f91f3d3-d66c-4d73-a6e5-cb73e514f5af.png">

**Comment by wobba** [comment]
This is an API limitation we have no control over in the web parts.

**Comment by md786** [comment]
I have found why its mismatch count. In property pane there is option i.e "Trim Duplicate", so I have selected this for that time onwards my count mismatch happen in Result count and Refiner. Please whenever anyone face this type of issue please check whether you selected this option i.e "Trim Duplicate". if select means because of this count mismatch.

**Comment by md786** [comment]
I have found why its mismatch count. In property pane there is option i.e "Trim Duplicate", so I have selected this for that time onwards my count mismatch happen in Result count and Refiner. Please whenever anyone face this type of issue please check whether you selected this option i.e "Trim Duplicate". if select means because of this count mismatch.

**Comment by wobba** [comment]
I would never enable trim duplicates myself :) https://www.techmikael.com/2013/12/duplicate-trimming-in-sharepoint-2013.html
