### ISSUE TITLE
Paging Numbers White on White background

### ISSUE THREAD

**Issue by mouseman85** [microsoft-search/pnp-modern-search#2542]
Version used
4.7.0

Describe the bug
Custom theme in SharePoint has white as the background when enabling paging on the PNP Search Results the text font colour is showing as white so cannot be seen. If changing to a Dark background for the page section the text follows and matches the background color. 

To Reproduce
1. Set theme to custom theme which is just White background as standard for page sections or the navy blue page sections 
2. enable paging
3. See error

**Expected behavior**
Paging to match same colour font as the result items which is black. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11850876/201900841-f93fba49-77d2-44a4-9c6f-781cbd656631.png)
![image](https://user-images.githubusercontent.com/11850876/201900915-1d89b575-9788-4fba-9159-6df25b14e0c0.png)

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**
Changing to dark does the same thing:
![image](https://user-images.githubusercontent.com/11850876/201901070-81b002c0-281e-44f4-8eb4-5d61ab9b5a0f.png)

**Comment by wobba** [comment]
Can you share a copy of the theme you are using? So we can pinpoint where we are not using theme colors.

**Comment by mouseman85** [comment]
Hi Wobba,

Below is the code: 
$themepallette = @{

"themePrimary" = "#1b619d";

"themeLighterAlt" = "#ecf4fc";

"themeLighter" = "#cde3f6";

"themeLight" = "#86bbea";

"themeTertiary" = "#2e8bdc";

"themeSecondary" = "#1d68aa";

"themeDarkAlt" = "#18578e";

"themeDark" = "#113e65";

"themeDarker" = "#0f3557";

"neutralLighterAlt" = "#f8f8f8";

"neutralLighter" = "#f4f4f4";

"neutralLight" = "#eaeaea";

"neutralQuaternaryAlt" = "#dadada";

"neutralQuaternary" = "#d0d0d0";

"neutralTertiaryAlt" = "#c8c8c8";

"neutralTertiary" = "#a6a6a6";

"neutralSecondary" = "#666666";

"neutralPrimaryAlt" = "#3c3c3c";

"neutralPrimary" = "#333333";

"neutralDark" = "#212121";

"black" = "#1c1c1c";

"white" = "#ffffff";

"primaryBackground" = "#ffffff";

"primaryText" = "#333333";

"bodyBackground" = "#ffffff";

"bodyText" = "#333333";

"disabledBackground" = "#f4f4f4";

"disabledText" = "#c8c8c8";

}

Add-SPOTheme -Name "<your theme name>" -Palette $pallette -IsInverted $true

I believe it maybe related the the -IsInverted $true - we had to enable to this due to an update to the page settings where our dark themes with a dark background kept being reset to white but enabled -IsInverted $true seemed to work. Also exploring the CSS styling of the field in Edge Dev Tools shows this: 

.paginationContainer__paginationContainer__pagination_097bc45b .inverted_097bc45b a {
    color: #fff;
}

When the page/section is set to a white background

and this when the page is set to the navy background: 

.paginationContainer__paginationContainer__pagination_097bc45b .standard_097bc45b a {
    color: #0f2b42;
}

It looks like its picking up the wrong inversion in the CSS Styling.

**Comment by wobba** [comment]
Fixed with #3397
