### ISSUE TITLE
Search Refiners

### ISSUE THREAD

**Issue by harishbalajigilead** [microsoft-search/pnp-modern-search#255]
1. Can we group the File Types (for e.g., .xls, .xlsx etc into single refiner value 'Excel' like classic refiners for FileType managed property so that it'll be helpful in categorizing the refiners based on the File types and also reduce the number of refiner values displayed? 

This can be a new or existing template that can be selected from the Refiners configuration. The search on the refiner values should be both on the Grouped refiner value or the actual file type.

2. Can we also provide a checkbox in refiners configuration whether to display the results count next to the refiner value or not? Currently, count gets displayed next to the refiner values.

**Comment by wobba** [comment]
Only with custom code, and we're thinking to support custom templates/code renderers for refiners as well.

Today we do not support this.

**Comment by wobba** [comment]
Included as part of #225
