### ISSUE TITLE
Using {Today} token in Refinement panel not working

### ISSUE THREAD

**Issue by GilesGregg** [microsoft-search/pnp-modern-search#2551]
The Today token doesn't appear to be working for the refinement panel in the search results web part

my query is
and(ContentTypeId:equals("0x01002071A0E029BE4C89B12D7191A981257B00DF126DFC16C14686BDB4606C8E857B60020200DCFCA5E8FE2AE84D95ED4BAC52056679"),RefinableString102:equals("Resolved"),RefinableDate03:range(datetime({Today-5}),datetime({Today})))

Am I doing something wrong? If I hard-code date values the results are returned as expected

**Comment by wobba** [comment]
Please the the full issue template when reporting issues, with steps on how you have configured your setup. This makes it possible to more quickly do a repro. Closing this one, and feel free to log a new complete one :)
