### ISSUE TITLE
Unable to use {Today} token in refinement panel

### ISSUE THREAD

**Issue by GilesGregg** [microsoft-search/pnp-modern-search#2555]
**Version used**
Version: 4.7.0

**Describe the bug**
In the refinement panel, if I use literal dates, I get the expected results

**working**
RefinableDate03:range(datetime("2022-11-15T00:00:00Z"),datetime("2024-01-01T00:00:00Z"))

if I use the {Today} token, I get no results

**not working**
RefinableDate03:range(datetime("{Today-7}"),datetime("2024-01-01T00:00:00Z"))

**To Reproduce**
Use the {Today} token in a refinement

**Expected behavior**
sharepoint content filtered by dates

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**
Do I have the syntax correct with using the datetime function? I can't find any examples on how to use this token in a refinement.

![Screenshot 2022-11-21 113735](https://user-images.githubusercontent.com/53594934/202936016-a06ccd14-a416-4036-884b-9f9d4d609aee.png)

**Comment by FranckyC** [comment]
Hi @GilesGregg , tokens were no supported for that field. I've just fixed that in #2560 and will be available in the next release very soon. Thanks!
