### ISSUE TITLE
People Search: Escape special characters 

### ISSUE THREAD

**Issue by till-llit** [microsoft-search/pnp-modern-search#2556]
**Version used**
4.8-beta

**Describe the bug**
Search for people with special characters in their name is not working - it looks like the people search of sharepoint is somehow different compared to the regular search content source.

Example: Person Name is "D'Angelo"

If i search for this name in a people search scenario i will receive zero results.
If i change the query to "d\'angelo" or "d/'angelo" i will find him.

**To Reproduce**

- Have at least one account with a special character like 

> '

 in the name

- Add Search result webpart and refer to LocalPeopleResults as a Result Source
- Search for the user last name -> you will find nothing

**Expected behavior**
i guess special characters must be escaped to return correct search results from people focused result sources.

**Screenshots**

**Desktop (please complete the following information):**
edge 106

**Additional context**

**Comment by wobba** [comment]
This is API related and not related to the web parts. That said, special characters are usually tokenized away on search.

**Comment by till-llit** [comment]
well, we could accept that the API might not change - and to enable people search with the webparts we could escape the search query.

**Comment by wobba** [comment]
There is no escape character afaik on a query. And / would not be escape, \ is escape in programming 🙂

And you state that `d'angelo` works, or did you mean with quotes around it?

**Comment by till-llit** [comment]
using the SP Search Query Tool i get the following results:

Query Text: `d'angelo`
Local People Results: 0
Local SharePoint Results: 41
Status: nOK

Query Text: `"d'angelo"`
Local People Results: 0
Local SharePoint Results: 34
Status: nOK

Query Text:  `d''angelo`
Local People Results: 1
Local SharePoint Results: 8145
Status: OK

Query Text: `d/'angelo`
Local People Results: 1
Local SharePoint Results: 8145
Status: OK

Query Text: `d\'angelo`
Local People Results: 1
Local SharePoint Results: 8144
Status: OK

i would propose to "escape" `'` with another `'` to deliver better results.

**Comment by wobba** [comment]
@till-llit Do you have the same experience in OOB search? If you query for `d angelo` does that give one result as well?

**Comment by till-llit** [comment]
Query Text: `d angelo`
Local People Results: 1
Local SharePoint Results: 8151
Status: OK

OOB Search (Modern Search Experience) - this is already using graph endpoint, i get identical results with the graph people search.

https://<tenant>.sharepoint.com/_layouts/15/search.aspx/people?q=d%27angelo
Results: 15

**Comment by till-llit** [comment]
you are right, i was confused by the similarity of additional results.

https://graph.microsoft.com/beta/search/query
`"queryString": "d'angelo"`  is returning 12 results
a lot of those hits have just similar names like "Angelika"

OOTB People Search use https://substrate.office.com/search/api/v2/query 
it looks like the frontend is already splitting the query, this request is send 2 search terms even though i searched for `d'angelo`
`"SearchTerms ["d'", "angelo"]`

Still not the same results like the Sharepoint API, here i receive only 1 result for `d angelo` compared to 15 results from substrate.office.com.

Both, OOTB and Graph results are not helpful in my opinion, when a user is search specificially for `d'angelo` it is not good to return 'angelika' or other similar names to 'angelo'

**Comment by wobba** [comment]
Fuzzy name match is a good idea for most cases, but agree that the name you search for should be on top and part of recall.

**Comment by till-llit** [comment]
hi @wobba - is there a chance that you might reopen the issue and somebody talented work on this issue? we are a little bit stuck here on this topic and i would love to resolve this

**Comment by wobba** [comment]
This is not a web part issue, so has to be logged with Microsoft support (I don't work on the query logic).

**Comment by till-llit** [comment]
hey @wobba, i did that with our unified support contract at microsoft last year in parallel and they rejected to resolve the issue.

in the backend it is related to the missing "Language Neutral Tokenization" setting for the People Fields like LastName or FirstName. We cannot change this in the search schema on our own and the product group rejected to resolve this.

Without this setting the apostroph is recognized as a word seperator in the search query.

I totally understand that the issue root cause is not in the pnp search query webpart, but it looks like that with the current situation users should be aware that it is currently impossible to search properly for people with apostrophs in their name.

**Comment by wobba** [comment]
@till-llit You should try this:

Map the cp for name to `RefinableStringLn00`. Then use this in the query template and see what happend: `RefinableStringLn00:({searchTerms})`

**Comment by till-llit** [comment]
we are currently evaluating a workaround pretty similar to your idea.

i created a property with "Language Neutral Tokenization" set to true and mapped the LastName property. 
i changed the search query to `{searchTerms} OR NeutralLastName:{searchTerms}` and this seems to work.

currently we are waiting for the people crawl to finish populating the new property, but for the already crawled people it is working.
