### ISSUE TITLE
Entity Types to search gets stuck after save

### ISSUE THREAD

**Issue by kasperbolarsen** [microsoft-search/pnp-modern-search#2557]
### Check existing issues before logging new ones
If you are not using the latest version, triage your issue with the latest version before logging as we won't provide patches to older versions.

### Issues related to data mapping, e.g. SharePoint columns to crawled properties to managed properties should be asked in the discussion section.

**For any question regarding Web Parts usage, please use the ["Discussions"](https://github.com/microsoft-search/pnp-modern-search/discussions) tab instead of creating a new issue.**.

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
4.8.*

**Describe the bug**
After saving the results web part I am no longer able to update the "Entiry types to search" setting ( MS search page 1)

**To Reproduce**
1. Added new Results web part
2. Changed Entity types to search til ListItems
3. Saved the page as draft
4. Edit the page and web part again, updates to the Entity types to search list not longer works

**Expected behavior**

**Screenshots**
Video of issue attached

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**

**Comment by kasperbolarsen** [comment]
https://fellowminddk-my.sharepoint.com/:v:/g/personal/kasper_larsen_fellowmind_dk/EbYxo8jG0mBOixjYLga2-lUB98d8tZB_DGdOhznuRtWxUA?e=7Xe6F3

**Comment by wobba** [comment]
Didn't quite understand the issue even with the video. If you hard refresh the page, same issue?

**Comment by kasperbolarsen** [comment]
Verified on the new 4.8.0 stable : the issue is no longer :-)
