### ISSUE TITLE
Search Refiners - Date range (Fixed Intervals)

### ISSUE THREAD

**Issue by harishbalajigilead** [microsoft-search/pnp-modern-search#257]
**Version used**
3.12.1

**Describe the bug**
When I select 'Past 24 hours' refiner value, remaining values vanishes except 'Any time' and 'Older than a year'. It behaves weirdly when I select different values. Could you please confirm if a fix can be made for this?

**Comment by wobba** [comment]
Cannot repro. I pick "Past 24h" and the others still show.

![image](https://user-images.githubusercontent.com/51104/81699732-046d4100-9468-11ea-894b-c61e7190c814.png)

**Comment by harishbalajigilead** [comment]
That's interesting. Please see the screenshot. What could be the problem?

![SearchRefiners](https://user-images.githubusercontent.com/64979811/81778968-63d35b80-9511-11ea-8c9d-1bfcc552d32e.png)

**Comment by harishbalajigilead** [comment]
One more thing that I found out is when I select 'Past 24 hours' and when there are no matching results, Search Results part shown no results found message but Search Refiners part also displays 'No filter avaialble' message instead of showing the available refiners. There is no way other than refresh the page to proceed further.

**Comment by harishbalajigilead** [comment]
> Cannot repro. I pick "Past 24h" and the others still show.
> 
> ![image](https://user-images.githubusercontent.com/51104/81699732-046d4100-9468-11ea-894b-c61e7190c814.png)

When I changed the Refiner Sort Type to '--', it was fine. But, you can see 'Older than a year' option is missing in your screenshot. Also, when you select 'Older than a year', other options vanishes. Could you please confirm?

**Comment by wobba** [comment]
If you pick "past 24" then those items are not older than a year :) If you pick items older than a year, then the other options are not applicable to those items. This is intended behavior. Having it static becomes complicated when you start refining on other properties.
