### ISSUE TITLE
V4.7 - PNP Search Results Web Part - Sorting - List of available Fields appears truncated

### ISSUE THREAD

**Issue by cosburback** [microsoft-search/pnp-modern-search#2570]
**Version used**
4.7

**Describe the bug**
After updated to version 4.7 when editing the sort settings I do not have access to all my fields. I used to have access to the RefinableStrings, and other fields selected for use, but not since updating.

**To Reproduce**
1. Add a PnP - Search Results web part and set up your query template query.
2. Click on the Selected properties dropdown to bring up the properties to choose from. Choose the Refinablestring you have mapped your Title to (or any other column you would like to sort on)
3. Just to be thorough, add that Refinablestring to your Layout slots list.
4. Wait a bit to ensure everything catches up and then "Edit sort settings"
5. Click on the dropdown to Select field...
6. See that the Refinablestring you would like to use is not listed, not only that, only 52 items are listing, which in our tenant, means that RefinableStrings won't display.

**Expected behavior**
I expected to see all the selected properties listed. As in the previous version I had been able to select refinablestrings.

**Screenshots**
See that it just stops at RecsClickedRecent and doesn't show anything below that.
![image](https://user-images.githubusercontent.com/118854590/203420313-59a69dbc-b553-4973-8c7a-a091af6e8978.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - 

**Additional context**

**Comment by FranckyC** [comment]
Hi @cosburback, since 4.7 we switched to a static list of properties instead of a dynamic one (see https://github.com/microsoft-search/pnp-modern-search/blob/cda9ca9fc0ccd3068f1b64ab8b68e2a5c9d4a516/search-parts/src/common/Constants.ts#LL46C8-L46C8). This was because we had too many issues related to a wrong usage of 'non sortable' fields. To use 'RefinableXXX' fields, you can simply type the name and press enter.

**Comment by cosburback** [comment]
Thank you for the answer. I hadn't even tried it as only dynamic worked before. I appreciate the clarification. Have a great day.

**Comment by wobba** [comment]
@FranckyC All the refinable ones should be added to the list of sortable, as they are also sortable.
