### ISSUE TITLE
Analytics - Track search usage

### ISSUE THREAD

**Issue by MarcelKaxon** [microsoft-search/pnp-modern-search#258]
Hi all,

It would be useful to track the **behaviour of the search users**.
At the moment i don't know a way to get useful data to **improve the search experience**.

_(a kinda workaround i used is to use the nlp-function in the searchbox-webpart to catch the searchqueries with a flow)_

But there is no information about the context. User/Page(Source)/Success.

**Are there any plans / ways to get information out of the modern search usage?**

**Comment by wobba** [comment]
We plan to add cability to include your own handlebar helper functions. Using this you can log anything anyway you want. But it's all up to you. Microsoft Search today has no public API to log this and return in back. That said, there are plans to provide insight from the OOB Microsoft Search experiences via the admin portal.
