### ISSUE TITLE
AutoPreviewImageURL shows null for all components when configuring Microsoft Search in Pnp Modern Search

### ISSUE THREAD

**Issue by 2161669** [microsoft-search/pnp-modern-search#2580]
Steps to Reproduce:
Implement Microsoft search using PnP modern search and check for the results shown on the page.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/117626792/203733860-ba3692d0-04ac-4c38-8823-a862585e1a6b.png">

Go to 2nd page of property pane, and select Debug, the AutoPreviewImageURL shows null value
<img width="155" alt="image" src="https://user-images.githubusercontent.com/117626792/203734395-ee7203a7-63d6-4585-9785-c51612de33da.png">

Let us know, if we are missing something here.

**Comment by wobba** [comment]
Closing as it's not using the issue template providing repro steps and version used.
