### ISSUE TITLE
Can't sort by relevance

### ISSUE THREAD

**Issue by stevebeauge** [microsoft-search/pnp-modern-search#259]
**Is your feature request related to a problem? Please describe.**

As far as I know, in order to sort search results by relevance, you have to provide an empty sort list.

However, search result webpart have it's sort property mandatory. I didn't found a way to provide sort drop down to provide such sorting.

**Describe the solution you'd like**
It would be cool to have the ability to select no property or a special one named relevance, to allow sorting by relevance. Both for the default sort and for the sorts drop down list.

**Describe alternatives you've considered**
no alternative found

**Additional context**

**Comment by MakingThingsWorkToronto** [comment]
Please try using the managed property "Rank" for this type of sorting.

**Comment by stevebeauge** [comment]
This property is not sortable (strangely)

**Comment by wobba** [comment]
Rank:Descending or nothing works just fine, as you can clear the oob two sort fields.

**Comment by stevebeauge** [comment]
Only for default sort. Not for sort list.

**Comment by stevebeauge** [comment]
The english name for what I said "sort list" parameter is actually "Sortable fields" pannel

**Comment by stevebeauge** [comment]
Also, Rank managed property is not sortable. The sort pannel prevents typing this property because of that.

**Comment by stevebeauge** [comment]
Actually, the property can be manually set

**Comment by wobba** [comment]
I know 🙂 and tested before my answer 😉

**Comment by stevebeauge** [comment]
Thanks to have pointed the trick. Should be simplify though, but it's working

**Comment by wobba** [comment]
I disagree....and there is no proper schema lookup API....also see my amended comment above. We could document it though, also removing the default props makes it fall back to sorting of the result source you use.
