### ISSUE TITLE
PNP search bar and shows the results in the default page, the parameter is not working

### ISSUE THREAD

**Issue by Juanka76** [microsoft-search/pnp-modern-search#2590]
Using PHP search bar and shows the resullt in the default search page of SharePoint

We have a page in SharePoint site, on this page we have a PNP search bar, the results is showing in a  Search Page default.
The action will open the default page and move the phase to be search as parameter in the URL
Method: Query String Parameter
Parameter Name: q

But the page open the default page as expected but in the sentence to be search the engine incorporate %25 in the middle of the sentence

Steps
Sentence to search: this is a test
On the url on the search page is showing this parameter
/_layouts/15/search.aspx/siteall?q=this%2520is%2520a%2520test

We tested in all browner
Chrome, Firefox and Microsoft Edge

![2022-11-24_19-37-35](https://user-images.githubusercontent.com/118991709/203883572-674c0d9e-633e-46bd-98c7-0c2f145d75c4.png)
![2022-11-24_19-38-46](https://user-images.githubusercontent.com/118991709/203883580-e2279961-ff83-4a93-ac30-4b59813886e6.png)

**Comment by wobba** [comment]
Issue is not following the template, and as stated will therefor be deleted.
