### ISSUE TITLE
Documentation - Extensibility possibilities - Link to Custom data sources is broken

### ISSUE THREAD

**Issue by MarkusLanger** [microsoft-search/pnp-modern-search#2615]
The link to the "Custom data sources" is broken.

![image](https://user-images.githubusercontent.com/12131918/205019277-51f1d8fd-c181-4e58-abc9-66b76cb0e3ff.png)

![image](https://user-images.githubusercontent.com/12131918/205019391-3201cab5-ed47-42ef-a87f-5f25e224a3fe.png)

**Comment by edarroudi** [comment]
Thank you. This is fixed in the develop branch.

**Comment by wobba** [comment]
@FranckyC can you republish the docs?

**Comment by FranckyC** [comment]
Done, thanks @edarroudi
