### ISSUE TITLE
Custom Query Modification not loading

### ISSUE THREAD

**Issue by Fringie** [microsoft-search/pnp-modern-search#2618]
**Version used**
V4.8

**Describe the bug**
This issue is regarding the extensibility feature - custom query modifier:

I have setup the functionality following the documentation in https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_query_modifications/

When I look in the WebPart settings to configure the WebPart, I don't see anything. So I added a breakpoint into the `getCustomQueryModifiers` method and nothing happened:
![image](https://user-images.githubusercontent.com/7203124/205050852-60751f89-826c-4475-9c7b-6e867a6b1618.png)

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Setup an Modern Search library with the extensibility packages "@pnp/modern-search-extensibility": "1.5.0"
2. Setup the custom query functionality using this guide https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_query_modifications/
3. Review the webpart settings and put a breakpoint in the getCustomQueryModifiers method

**Expected behavior**
I expect the query modifier logic to run.
**Screenshots**

**Desktop (please complete the following information):**
Windows 10, Chrome

**Additional context**
The other OOTB events such as invokeCardAction, registerHandlebarsCustomizations, getCustomWebComponents, getCustomLayouts are working for me. When I F12 on my `getCustomQueryModifiers `method it takes me to the interface so I know it's not a typo.
![image](https://user-images.githubusercontent.com/7203124/205054456-1619837c-7531-4068-89e8-ce8aae6d82d7.png)

If anyone has any workarounds for the short term please let me know.

**Comment by edarroudi** [comment]
The query modifier will be available when you activate the  input connection switch on page 3. did you see it there? Of course your breakpoint should normally be called.

**Comment by Fringie** [comment]
> The query modifier will be available when you activate the input connection switch on page 3. did you see it there? Of course your breakpoint should normally be called.

Thank you for taking the time to post.

I don't see the option.
![image](https://user-images.githubusercontent.com/7203124/205118823-6a367bd7-703a-43a4-9f25-83a0bfef111c.png)

**Comment by kasperbolarsen** [comment]
Just a question: shouldn't this issue have be raised in the extensibility repository?

**Comment by edarroudi** [comment]
Can you install https://github.com/microsoft-search/pnp-modern-search-extensibility-samples/releases/download/1.2.0/pnp-modern-search-extensibility-demo.sppkg and check again? This is tested so if it doesn’t work I think you don’t have the 4.8 version or something else is wrong and I can check that.

**Comment by Fringie** [comment]
> Can you install https://github.com/microsoft-search/pnp-modern-search-extensibility-samples/releases/download/1.2.0/pnp-modern-search-extensibility-demo.sppkg and check again? This is tested so if it doesn’t work I think you don’t have the 4.8 version or something else is wrong and I can check that.

PNP Modern Search Solutions:
![image](https://user-images.githubusercontent.com/7203124/205260065-8d03e934-993e-48fc-9032-e8fd9f8f5ca4.png)


Loaded extensions: 
![image](https://user-images.githubusercontent.com/7203124/205259946-37593b71-2491-4cf7-af74-5e33c31cd5ab.png)
I've confirmed the GUID is correct via https://github.com/microsoft-search/pnp-modern-search-extensibility-samples/blob/main/search-extensibility-samples/src/libraries/myCompanyLibrary/MyCompanyLibraryLibrary.manifest.json


Search results WebPart settings:
![image](https://user-images.githubusercontent.com/7203124/205260291-1d450c19-7c34-44b0-abfb-ffb7956cba43.png)

**Comment by edarroudi** [comment]
It seems your are using a different pnp-modern-search-parts version? It says it's a beta version. But it should look like this:
![image](https://user-images.githubusercontent.com/935493/205261603-061df620-1ae0-43f0-87d0-402be59607e4.png)

**Comment by Fringie** [comment]
> Just a question: shouldn't this issue have be raised in the extensibility repository?

Thank you, switching to V4.8 instead of V4.8 beta version resolved my problem.
