### ISSUE TITLE
Filters rendering

### ISSUE THREAD

**Issue by LRPowys** [microsoft-search/pnp-modern-search#2624]
**Version used**
Version 4.8

**Describe the bug**
Upon selection of values, associated with the first two filters, it hides the rest of the filters. The filters reappear if the browser page is refreshed. The filters are 5 in total and correspond to columns with the same names as created in the document libraries.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to the 'Filters' webpart of the PNP Module
2. Click on the first checkbox to select a value from the first filter. Then click on the next checkbox down to select a value from the second filter. The rest of the filters, visible up to that moment then disappear and it is not possible to further specify the filtering. There are definitively tags on files that are in Level3 filter and above.
3. Go to browser 'Refresh' at the top or press CTRL+R.
4. The missing filter(s) reappear and a value within it can now be selected.

**Expected behavior**
The filters should not hide if there are values associated with files within that particular filter. Constant refreshing of the browser page to prompt the filters to re-appear is not acceptable from user perspective. It used to be the filters were working properly and the fault seems to have started occuring after the upload of some files on the site. The upload may just be a coincidence and may not have anything to do with the issue.

**Screenshots**

Screenshot 1
![image](https://user-images.githubusercontent.com/119879292/205687869-dc3537e3-0d89-4780-abc2-aa30d4745132.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/119879292/205703854-f8e3ea29-73e6-485d-87ef-9bba075b31e5.png)

Screenshot 3
![image](https://user-images.githubusercontent.com/119879292/205688561-9ff9690b-d3f4-409a-a4cb-878a2e3a9d32.png)

Screenshot 4
![image](https://user-images.githubusercontent.com/119879292/205689097-4bbb1ae3-79ae-4151-867d-ff41c9796ccf.png)

Screenshot 5
![image](https://user-images.githubusercontent.com/119879292/205689332-e41d7621-2c79-4630-b86d-42fbc29e2843.png)

**Desktop (please complete the following information):**
 - Browser: Chrome, Edge

**Additional context**
The problem started manifesting itself after latest uploads of some few hundred files into some of the document libraries. Up until that moment the filters were working correctly. The SP site contains about 17 000 items in total. Even if the "Query template" box in the 'Search Results' webpart is configured to perform the search in only one of the libraries, one that only has about 3000 items, that does not change the behaviour of the filters. The site has been re-indexed and the separate document libraries too. New page with the same webparts with setting up the options in the filters section from new has been created, however the problem still persists. 
The filters correspond to columns, created at a site level, and the files within the document libraries are tagged with different labels. The crawled properties (site columns called Level1 through to Level5) have been mapped to RefinableString properties on SP Admin Center. The filters stopped working correctly regarding both - the initially uploaded files and tags applied and also the recently uploaded files. On a separate note, the whole PNP module appears to be sluggish and barely responsive. Hard reset with clearing the cache of the browser has been done and switch to a different browser attempted as well.

**Comment by wobba** [comment]
Can you verify that data is coming back for your repro steps for the Level 3 one?

**Comment by LRPowys** [comment]
> 
![image](https://user-images.githubusercontent.com/119879292/205704320-9629ed34-c126-4e66-be35-e29f9ee6f09a.png)

Not entirely clear on the question, but there is definitively tags associated with Level3 in the example above. It is only after the selection of the value in Level2, Level3 dissapears entirely.

**Comment by wobba** [comment]
F12 dev tools and network tab. Examine the network response when the search query comes back with JSON data. And compare the request with what is done with the refresh query.

**Comment by LRPowys** [comment]
Compared as advised. In both cases - pre- and after refreshin I am getting lines of errors as follows:

"- Uncaught (in promise) TypeError: Cannot set properties to null 
at...
at...
at...
at...
- Failed to process execution entry:Error: Cannot perform DeepCopy() because a...js:70 circular reference was encountered, object..."

The different, additional line I get after doing a refresh reads:

"Some icons were reregistered. Applications should only call registerIcons modern-search-result.... for any given icon once"

**Comment by wobba** [comment]
Not console...look at the json response from the search call in the network tab.

**Comment by LRPowys** [comment]
> Can you verify that data is coming back for your repro steps for the Level 3 one?

It seem data is coming back and it is loading. The first screenshot is from pre-refresh - just after making selection of the first two filters, after which the rest of the filters stop showing on the actual webpage. The second screenshot is from when the page is refreshed when the filters eventually show up.
![image](https://user-images.githubusercontent.com/119879292/205902807-fdbfc4e2-c943-49e4-8828-c5817d4c9d4d.png)
![image](https://user-images.githubusercontent.com/119879292/205903612-363ec61c-8746-4116-8c1e-d6e8331058d8.png)

**Comment by LRPowys** [comment]
> Not console...look at the json response from the search call in the network tab.

@wobba Does the above make sense? Anything else you would like me to provide? What are the steps in investigating this?

**Comment by wobba** [comment]
Having someone who understand looking at network traces per click verify request and response following your steps :) You screenshots don't really help much in terms of understanding so repro is likely needed when someone has the time.

**Comment by wobba** [comment]
Fixed in the dev branch. Thank you @salimbharuchi
