### ISSUE TITLE
Failed to load component error on specific tenant

### ISSUE THREAD

**Issue by in-pv** [microsoft-search/pnp-modern-search#2628]
Hi All,

I am trying to upgrade from 4.6.1 to 4.8.0 but on a specific tenant I get the following error. I get a similar error for all the web parts except for the search box.

![image](https://user-images.githubusercontent.com/89818679/205820532-0d0bdd0d-eda4-4660-bacb-2b643ab29273.png)

If I revert back to 4.6.1 all starts working again so is definitely related to our config for 4.8.0. Any ideas as to what might be causing the issue? All the api permissions were granted successfully

![image](https://user-images.githubusercontent.com/89818679/205821861-5d263284-d2ef-42b9-b144-26510e156972.png)

Any help would be much appreciated

**Comment by FranckyC** [comment]
Hi @in-pv, is it the same using a private browser window? Are you using tenant or site collection app catalog?

**Comment by in-pv** [comment]
Hi @FranckyC,

It works in edge private browser window and works in firefox for a normal window and a private window.

This is related to my ms edge settings then?

The app is deployed to the tenant app catalog

/sites/appcatalog/_layouts/15/tenantAppCatalog.aspx/manageApps

![image](https://user-images.githubusercontent.com/89818679/206035149-31c9e9fd-74f0-4a16-81be-1379cca9f6a9.png)
