### ISSUE TITLE
Microsoft Search Datasource error: Token request previously failed

### ISSUE THREAD

**Issue by absoluteg** [microsoft-search/pnp-modern-search#2629]
**Version used**
4.8.0

**Describe the bug**
We appear to be having the same issue that was reported previously by some other users as of late, "Error: Token request previously failed".  We work for a business that has a domain, azure ad connect, etc.  We are not using personal accounts for any of this.  What is interesting for us is that the only place we see this problem with our Teams Deployed App (using a SharePoint page with the Web Parts and Only the "Microsoft Search" connector) is Teams Desktop.  The Web Version of Teams and the app works perfectly fine!  Going direct to the SharePoint page and doing searches works fine as well.

I was able to launch the Teams Dev Tools and find that we keep hitting 
![image](https://user-images.githubusercontent.com/3689100/205994033-4da0ccbf-06c8-4189-ac52-c50cbd744d89.png)

We have reviewed the Manifest file for the app and making sure that we have the right context for Single Sign-On {teamsSiteDomain} as well as the personal app tab setting leveraging the same Context Variable.  Still doesn't work.

The most recent closure to this issue mentioned being fixed by an API Permission being assigned but doesn't say which one. Bug #2514.  We have accepted/published all of the default permissions requested as part of this integration in the SharePoint Admin center.  Which includes a new one as part of 4.8.0 - Presence.Read.All - this still didn't fix our issue (even with all the default API permissions through the app integration).

Hoping someone can help us to understand if we require a different API permission for this to work or if there might be some other issue going on.

Thank you!
Greg Jones

**Comment by absoluteg** [comment]
Just adding an additional screenshot from deskop and web versions of teams.

Teams desktop and the error i show is related to this experience of using the "Microsoft Search" context within the search web parts.

![image](https://user-images.githubusercontent.com/3689100/206021759-d726f391-8d3c-41d9-a050-1a6e72a7043d.png)

The Teams Web App - same app functions just fine.
![image](https://user-images.githubusercontent.com/3689100/206022056-0bb54506-0a23-4ee2-b9b7-0586e53e6e8d.png)

**Comment by wobba** [comment]
..and I assume it works fine on a page by itself in SharePoint? Thus the issue is using the Graph provider with people in Teams desktop? Is that correct summarization? Please share your web part setup if you want someone to try to repro the issue.

**Comment by absoluteg** [comment]
@wobba, It does work correctly when hitting the SharePoint Page Directly.  It also appears work just fine in Teams Web App version of Teams.  It's only in the Desktop Version of Teams where it appears to get the "Token failed previously" error.  Deeper in the errors (in review with Microsoft Support) there was mention of "failed to retrieve client secret" - so the thought was that deleting and re-creating the client secret on the "SharePoint Online Client Extensibility Web Application Principal" in Azure might fix the problem.  There had been some other cases from support where this fixed those issues.  This did not fix the problem for us, in this scenario of using PnP Search Web Parts.   I will work on getting the manifest file and details shared today.  Interesting, that we have also tried to reproduce this in another test tenant, and unable to repo.  However, in our production environment we have 2 apps, basically same configuration of PnP Search Web Parts and both give the same "Token Failed Previously" error message.

**Comment by absoluteg** [comment]
@wobba - Please let me know what additional details you need.

We have a Modern SharePoint Communication Site Collection, we enabled the App Catalog (via Powershell) on the site collection.  This lit up the App Catalog in the Site Collection, we then uploaded 4.8.0 of PnP Modern Search Webpart. We got promted to accept/trust the API Permissions.  We then went the SharePoint Admin and "Approved" the API Permissions.  I also confirmed on the SharePoint Online Principal (in Azure Portal App Registrations) that the API Permissions are listed and "Granted on behalf of the Organization".  Once these pre-req items are completed we then add Web Parts to page.

We took this down to as basic configuration as we could to test.  Below is the "export" of each of the settings for "raw properties".  Please do keep in mind, that this does work when loading the SharePoint page directly.  It's when we go to build and app and deploy in Teams Desktop where we get "Token previously failed" error (I have at the very bottom of this thread, the Manifest for the Teams App we created).

On Sharepoint page we added:

**SearchBox (no special config).** 
`{
	"documentationLink": "https://microsoft-search.github.io/pnp-modern-search/",
	"inputTemplate": "{inputQueryText}",
	"openBehavior": "Self",
	"queryPathBehavior": "URLFragment",
	"suggestionProviderConfiguration": [
		{
			"key": "SharePointStaticSuggestions",
			"description": "Retrieve SharePoint static user defined search suggestions",
			"enabled": false,
			"name": "SharePoint Static search suggestions"
		}
	],
	"numberOfSuggestionsPerGroup": 10,
	"providerProperties": {},
	"extensibilityLibraryConfiguration": [
		{
			"name": "Default extensibility library",
			"enabled": true,
			"id": "dc4f961b-dbe0-44b4-982d-5776bf99d015"
		}
	],
	"useDynamicDataSource": false,
	"enableQuerySuggestions": false,
	"queryText": {
		"__type": "DynamicProperty",
		"value": ""
	}
}`

**Added PnP Search Verticals:**
`{
	"documentationLink": "https://microsoft-search.github.io/pnp-modern-search/",
	"verticals": [
		{
			"uniqueId": "ffbbc04b-c0ed-4724-9171-3c97e4797c9a",
			"tabName": "Sites",
			"iconName": "PageData",
			"tabValue": null,
			"isLink": null,
			"linkUrl": null,
			"openBehavior": null,
			"showLinkIcon": null,
			"sortIdx": 1,
			"key": "4811b655-c3e7-4c38-8df7-adba0aba2b55"
		},
		{
			"uniqueId": "9690fe33-b24c-4b91-8a20-540f943cca1f",
			"tabName": "People",
			"iconName": null,
			"tabValue": null,
			"isLink": null,
			"linkUrl": null,
			"openBehavior": null,
			"showLinkIcon": null,
			"sortIdx": 2,
			"key": "6aa28146-47e9-48dd-8d39-b3b1efa561bb"
		},
		{
			"uniqueId": "021140ad-f133-4415-a788-11c553bfad4c",
			"tabName": "Files",
			"iconName": null,
			"tabValue": null,
			"isLink": null,
			"linkUrl": null,
			"openBehavior": null,
			"showLinkIcon": null,
			"sortIdx": 3,
			"key": "6bf08dbe-3776-47d7-a445-678d5051b9be"
		}
	],
	"defaultVerticalQueryStringParam": "v"
}`

**Add PnP Search Results (Total 3 Search Results: Sites, Files, People all using Microsoft Search datasource):
Search Results for Files:**
`{
	"documentationLink": "https://microsoft-search.github.io/pnp-modern-search/",
	"selectedLayoutKey": "SimpleList",
	"resultTypes": [],
	"dataSourceProperties": {
		"entityTypes": [
			"driveItem"
		],
		"fields": [
			"name",
			"webUrl",
			"filetype",
			"createdBy",
			"createdDateTime",
			"lastModifiedDateTime",
			"parentReference",
			"size",
			"description",
			"file",
			"folder",
			"subject",
			"bodyPreview",
			"replyTo",
			"from",
			"sender",
			"start",
			"end",
			"displayName",
			"givenName",
			"surname",
			"userPrincipalName",
			"phones",
			"department"
		],
		"sortProperties": [],
		"sortList": [],
		"contentSourceConnectionIds": [],
		"queryAlterationOptions": {
			"enableModification": false,
			"enableSuggestion": false
		},
		"queryTemplate": "{searchTerms} ",
		"useBetaEndpoint": false,
		"enableResultTypes": false,
		"trimDuplicates": false
	},
	"queryTextSource": 1,
	"layoutProperties": {
		"showFileIcon": true,
		"showItemThumbnail": true
	},
	"showSelectedFilters": false,
	"showResultsCount": true,
	"showBlankIfNoResult": false,
	"useMicrosoftGraphToolkit": true,
	"enableTelemetry": true,
	"itemSelectionProps": {
		"allowItemSelection": false,
		"selectionMode": "AsDataFilter",
		"allowMulti": false,
		"valuesOperator": "or"
	},
	"extensibilityLibraryConfiguration": [
		{
			"name": "Default extensibility library",
			"enabled": true,
			"id": "dc4f961b-dbe0-44b4-982d-5776bf99d015"
		}
	],
	"queryModifierConfiguration": [],
	"queryModifierProperties": {
		"endWhenSuccessfull": false
	},
	"selectedVerticalKeys": [
		"6bf08dbe-3776-47d7-a445-678d5051b9be"
	],
	"useVerticals": true,
	"paging": {
		"itemsCountPerPage": 10,
		"pagingRange": 5,
		"showPaging": true,
		"hideDisabled": true,
		"hideFirstLastPages": false,
		"hideNavigation": false,
		"useNextLinks": false
	},
	"adaptiveCardsHostConfig": "{\n\t\"fontFamily\": \"Segoe UI, Helvetica Neue, sans-serif\"\n}",
	"layoutRenderType": "Handlebars",
	"dataSourceKey": "MicrosoftSearch",
	"templateSlots": [
		{
			"slotName": "Title",
			"slotField": "resource.name"
		},
		{
			"slotName": "Path",
			"slotField": "resource.webUrl"
		},
		{
			"slotName": "Summary",
			"slotField": "summary"
		},
		{
			"slotName": "FileType",
			"slotField": "resource.webUrl"
		},
		{
			"slotName": "PreviewImageUrl",
			"slotField": "AutoPreviewImageUrl"
		},
		{
			"slotName": "PreviewUrl",
			"slotField": "AutoPreviewUrl"
		},
		{
			"slotName": "Tags",
			"slotField": "owstaxidmetadataalltagsinfo"
		},
		{
			"slotName": "Date",
			"slotField": "created"
		},
		{
			"slotName": "SiteId",
			"slotField": "resource.fields.normSiteID"
		},
		{
			"slotName": "WebId",
			"slotField": "resource.fields.normWebID"
		},
		{
			"slotName": "ListId",
			"slotField": "resource.fields.normListID"
		},
		{
			"slotName": "ItemId",
			"slotField": "resource.fields.normUniqueID"
		},
		{
			"slotName": "IsFolder",
			"slotField": "resource.fields.contentTypeId"
		},
		{
			"slotName": "Id",
			"slotField": "hitId"
		}
	],
	"inlineTemplateContent": null,
	"externalTemplateUrl": "",
	"useInputQueryText": true,
	"useDefaultQueryText": false,
	"verticalsDataSourceReference": "WebPart.544c1372-77ae-40a0-9095-805ae2a0d5e9.d44b1d6a-b720-46ea-9ee9-826c3bd07a4d:pnpSearchVerticalsWebPart",
	"useDynamicFiltering": false,
	"queryText": {
		"__type": "DynamicProperty",
		"reference": {
			"_reference": "WebPart.544c1372-7e5a-49ec-8db6-812f76c375f2.c5541122-2e88-4b8a-9a34-b1bbb7b46926:pnpSearchBoxWebPart",
			"_sourceId": "WebPart.544c1372-7e5a-49ec-8db6-812f76c375f2.c5541122-2e88-4b8a-9a34-b1bbb7b46926",
			"_property": "pnpSearchBoxWebPart"
		}
	},
	"filtersData": {
		"__type": "DynamicProperty",
		"value": {}
	},
	"selectedItemFieldValue": {
		"__type": "DynamicProperty",
		"value": ""
	}
}`

**Search Results for People:**
`{
	"documentationLink": "https://microsoft-search.github.io/pnp-modern-search/",
	"selectedLayoutKey": "People",
	"resultTypes": [],
	"dataSourceProperties": {
		"entityTypes": [
			"person"
		],
		"fields": [
			"name",
			"webUrl",
			"filetype",
			"createdBy",
			"createdDateTime",
			"lastModifiedDateTime",
			"parentReference",
			"size",
			"description",
			"file",
			"folder",
			"subject",
			"bodyPreview",
			"replyTo",
			"from",
			"sender",
			"start",
			"end",
			"displayName",
			"givenName",
			"surname",
			"userPrincipalName",
			"phones",
			"department"
		],
		"sortProperties": [],
		"sortList": [],
		"contentSourceConnectionIds": [],
		"queryAlterationOptions": {
			"enableModification": false,
			"enableSuggestion": false
		},
		"queryTemplate": "{searchTerms} ",
		"useBetaEndpoint": false,
		"enableResultTypes": false,
		"trimDuplicates": false
	},
	"queryTextSource": 1,
	"layoutProperties": {
		"peopleFields": [
			{
				"name": "Image URL",
				"field": "imageUrl",
				"value": "/_layouts/15/userphoto.aspx?size=L&username={{getUserEmail (slot item @root.slots.UserEmail)}}",
				"useHandlebarsExpr": true,
				"supportHtml": false
			},
			{
				"name": "Primary text",
				"field": "primaryText",
				"value": "{{slot item @root.slots.UserDisplayName}}",
				"useHandlebarsExpr": true,
				"supportHtml": true
			},
			{
				"name": "Secondary text",
				"field": "secondaryText",
				"value": "JobTitle",
				"useHandlebarsExpr": false,
				"supportHtml": true
			},
			{
				"name": "Tertiary text",
				"field": "tertiaryText",
				"value": "{{getUserEmail (slot item @root.slots.UserEmail)}}",
				"useHandlebarsExpr": true,
				"supportHtml": true
			},
			{
				"name": "Optional text",
				"field": "optionalText",
				"value": "WorkPhone",
				"useHandlebarsExpr": false,
				"supportHtml": true
			}
		],
		"personaSize": 14,
		"showPersonaCard": true
	},
	"showSelectedFilters": false,
	"showResultsCount": true,
	"showBlankIfNoResult": false,
	"useMicrosoftGraphToolkit": true,
	"enableTelemetry": true,
	"itemSelectionProps": {
		"allowItemSelection": false,
		"selectionMode": "AsDataFilter",
		"allowMulti": false,
		"valuesOperator": "or"
	},
	"extensibilityLibraryConfiguration": [
		{
			"name": "Default extensibility library",
			"enabled": true,
			"id": "dc4f961b-dbe0-44b4-982d-5776bf99d015"
		}
	],
	"queryModifierConfiguration": [],
	"queryModifierProperties": {
		"endWhenSuccessfull": false
	},
	"selectedVerticalKeys": [
		"6aa28146-47e9-48dd-8d39-b3b1efa561bb"
	],
	"useVerticals": true,
	"paging": {
		"itemsCountPerPage": 10,
		"pagingRange": 5,
		"showPaging": true,
		"hideDisabled": true,
		"hideFirstLastPages": false,
		"hideNavigation": false,
		"useNextLinks": false
	},
	"adaptiveCardsHostConfig": "{\n\t\"fontFamily\": \"Segoe UI, Helvetica Neue, sans-serif\"\n}",
	"layoutRenderType": "Handlebars",
	"dataSourceKey": "MicrosoftSearch",
	"templateSlots": [
		{
			"slotName": "Title",
			"slotField": "resource.name"
		},
		{
			"slotName": "Path",
			"slotField": "resource.webUrl"
		},
		{
			"slotName": "Summary",
			"slotField": "summary"
		},
		{
			"slotName": "FileType",
			"slotField": "resource.webUrl"
		},
		{
			"slotName": "PreviewImageUrl",
			"slotField": "AutoPreviewImageUrl"
		},
		{
			"slotName": "PreviewUrl",
			"slotField": "AutoPreviewUrl"
		},
		{
			"slotName": "Tags",
			"slotField": "owstaxidmetadataalltagsinfo"
		},
		{
			"slotName": "Date",
			"slotField": "created"
		},
		{
			"slotName": "SiteId",
			"slotField": "resource.fields.normSiteID"
		},
		{
			"slotName": "WebId",
			"slotField": "resource.fields.normWebID"
		},
		{
			"slotName": "ListId",
			"slotField": "resource.fields.normListID"
		},
		{
			"slotName": "ItemId",
			"slotField": "resource.fields.normUniqueID"
		},
		{
			"slotName": "IsFolder",
			"slotField": "resource.fields.contentTypeId"
		},
		{
			"slotName": "Id",
			"slotField": "hitId"
		}
	],
	"inlineTemplateContent": null,
	"externalTemplateUrl": "",
	"useInputQueryText": true,
	"useDefaultQueryText": true,
	"verticalsDataSourceReference": "WebPart.544c1372-77ae-40a0-9095-805ae2a0d5e9.d44b1d6a-b720-46ea-9ee9-826c3bd07a4d:pnpSearchVerticalsWebPart",
	"queryText": {
		"__type": "DynamicProperty",
		"reference": {
			"_reference": "WebPart.544c1372-7e5a-49ec-8db6-812f76c375f2.c5541122-2e88-4b8a-9a34-b1bbb7b46926:pnpSearchBoxWebPart",
			"_sourceId": "WebPart.544c1372-7e5a-49ec-8db6-812f76c375f2.c5541122-2e88-4b8a-9a34-b1bbb7b46926",
			"_property": "pnpSearchBoxWebPart"
		}
	},
	"filtersData": {
		"__type": "DynamicProperty",
		"value": {}
	},
	"selectedItemFieldValue": {
		"__type": "DynamicProperty",
		"value": ""
	}
}`

**Search Results for Files:**
`{
	"documentationLink": "https://microsoft-search.github.io/pnp-modern-search/",
	"selectedLayoutKey": "SimpleList",
	"resultTypes": [],
	"dataSourceProperties": {
		"entityTypes": [
			"site"
		],
		"fields": [
			"name",
			"webUrl",
			"filetype",
			"createdBy",
			"createdDateTime",
			"lastModifiedDateTime",
			"parentReference",
			"size",
			"description",
			"file",
			"folder",
			"subject",
			"bodyPreview",
			"replyTo",
			"from",
			"sender",
			"start",
			"end",
			"displayName",
			"givenName",
			"surname",
			"userPrincipalName",
			"phones",
			"department"
		],
		"sortProperties": [],
		"sortList": [],
		"contentSourceConnectionIds": [],
		"queryAlterationOptions": {
			"enableModification": false,
			"enableSuggestion": false
		},
		"queryTemplate": "{searchTerms} ",
		"useBetaEndpoint": false,
		"enableResultTypes": false,
		"trimDuplicates": false
	},
	"queryTextSource": 1,
	"layoutProperties": {
		"showFileIcon": true,
		"showItemThumbnail": true
	},
	"showSelectedFilters": false,
	"showResultsCount": true,
	"showBlankIfNoResult": false,
	"useMicrosoftGraphToolkit": true,
	"enableTelemetry": true,
	"itemSelectionProps": {
		"allowItemSelection": true,
		"selectionMode": "AsDataFilter",
		"allowMulti": false,
		"valuesOperator": "or"
	},
	"extensibilityLibraryConfiguration": [
		{
			"name": "Default extensibility library",
			"enabled": true,
			"id": "dc4f961b-dbe0-44b4-982d-5776bf99d015"
		}
	],
	"queryModifierConfiguration": [],
	"queryModifierProperties": {
		"endWhenSuccessfull": false
	},
	"selectedVerticalKeys": [
		"4811b655-c3e7-4c38-8df7-adba0aba2b55"
	],
	"useVerticals": true,
	"paging": {
		"itemsCountPerPage": 10,
		"pagingRange": 5,
		"showPaging": false,
		"hideDisabled": true,
		"hideFirstLastPages": false,
		"hideNavigation": false,
		"useNextLinks": false
	},
	"adaptiveCardsHostConfig": "{\n\t\"fontFamily\": \"Segoe UI, Helvetica Neue, sans-serif\"\n}",
	"layoutRenderType": "Handlebars",
	"dataSourceKey": "MicrosoftSearch",
	"templateSlots": [
		{
			"slotName": "Title",
			"slotField": "resource.name"
		},
		{
			"slotName": "Path",
			"slotField": "resource.webUrl"
		},
		{
			"slotName": "Summary",
			"slotField": "summary"
		},
		{
			"slotName": "FileType",
			"slotField": "resource.webUrl"
		},
		{
			"slotName": "PreviewImageUrl",
			"slotField": "AutoPreviewImageUrl"
		},
		{
			"slotName": "PreviewUrl",
			"slotField": "AutoPreviewUrl"
		},
		{
			"slotName": "Tags",
			"slotField": "owstaxidmetadataalltagsinfo"
		},
		{
			"slotName": "Date",
			"slotField": "created"
		},
		{
			"slotName": "SiteId",
			"slotField": "resource.fields.normSiteID"
		},
		{
			"slotName": "WebId",
			"slotField": "resource.fields.normWebID"
		},
		{
			"slotName": "ListId",
			"slotField": "resource.fields.normListID"
		},
		{
			"slotName": "ItemId",
			"slotField": "resource.fields.normUniqueID"
		},
		{
			"slotName": "IsFolder",
			"slotField": "resource.fields.contentTypeId"
		},
		{
			"slotName": "Id",
			"slotField": "hitId"
		}
	],
	"useInputQueryText": true,
	"inlineTemplateContent": null,
	"externalTemplateUrl": "",
	"verticalsDataSourceReference": "WebPart.544c1372-77ae-40a0-9095-805ae2a0d5e9.d44b1d6a-b720-46ea-9ee9-826c3bd07a4d:pnpSearchVerticalsWebPart",
	"useDefaultQueryText": true,
	"queryText": {
		"__type": "DynamicProperty",
		"reference": {
			"_reference": "WebPart.544c1372-7e5a-49ec-8db6-812f76c375f2.c5541122-2e88-4b8a-9a34-b1bbb7b46926:pnpSearchBoxWebPart",
			"_sourceId": "WebPart.544c1372-7e5a-49ec-8db6-812f76c375f2.c5541122-2e88-4b8a-9a34-b1bbb7b46926",
			"_property": "pnpSearchBoxWebPart"
		}
	},
	"filtersData": {
		"__type": "DynamicProperty",
		"value": {}
	},
	"selectedItemFieldValue": {
		"__type": "DynamicProperty",
		"value": ""
	}
}`

**Teams App Manifest (we used https://dev.teams.microsoft.com to create) we have side loaded for testing as well as deployment and publish in the environment for testing (no change in behavior).  Also in manifest file below, replace ABC with name to test with to make this valid, hidden company name.**

Teams App Manifest:
`{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.15/MicrosoftTeams.schema.json",
  "version": "1.0.34",
  "manifestVersion": "1.15",
  "id": "b73bac95-1667-4648-b14b-4d9ea98a0c57",
  "packageName": "com.package.name",
  "name": {
    "short": "Test Search App",
    "full": "Test Search App for ABC Company"
  },
  "developer": {
    "name": "ABC Company",
    "mpnId": "",
    "websiteUrl": "https://www.ABC.com",
    "privacyUrl": "https://www.ABC.com/privacy",
    "termsOfUseUrl": "https://www.ABC.com/termsofuse"
  },
  "description": {
    "short": "Test PnP Search WebPart",
    "full": "ABC Testing integration of PnP Search"
  },
  "icons": {
    "outline": "outline.png",
    "color": "color.png"
  },
  "accentColor": "#470a0a",
  "staticTabs": [
    {
      "entityId": "231083f2-7d5a-4475-af75-8614e5b6a577",
      "name": "PNPSearch",
      "contentUrl": "https://{teamSiteDomain}/_layouts/15/teamslogon.aspx?SPFX=true&dest=/sites/EnterpriseSearch/SitePages/ABC-Search-v2.aspx?app=portals",
      "websiteUrl": "https://ABC.sharepoint.com/",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "about",
      "scopes": [
        "personal"
      ]
    }
  ],
  "validDomains": [
    "{teamsitedomain}",
    "ABC.sharepoint.com",
    "*.login.microsoftonline.com",
    "*.sharepoint.com",
    "*.sharepoint-df.com",
    "spoppe-a.akamaihd.net",
    "spoprod-a.akamaihd.net",
    "resourceseng.blob.core.windows.net",
    "msft.spoppe.com"
  ],
  "webApplicationInfo": {
    "id": "00000003-0000-0ff1-ce00-000000000000",
    "resource": "https://{teamSiteDomain} "
  },
  "isFullScreen": true,
  "defaultGroupCapability": {
    "team": "tab",
    "groupchat": "tab",
    "meetings": "tab"
  }
}`

In my second post earlier, I shared the User Experience as well as the Dev Tools output. 

I hope this is what you are looking for?  I'm more than happy to setup a call and time to step through it with someone if that would be helpful!!  Really appreciate the assistance! :-)

Thank you,
Greg

**Comment by wobba** [comment]
You could try a small SPFx project where you issue a graph call yourself with the same permissions.

**Comment by absoluteg** [comment]
@wobba , actually Microsoft Support did another follow up.  This problems seems to have stemmed from a corrupted Client Secret on the "SharePoint Online Client Extensibility Web Application Principal" - found in Azure Portal under App Registrations.  I had orginally, per the MS Support recommendation and backing from PG - deleted the old secret and then manually recreated a Secret - this still didn't work/fix the problem.  Today they asked me to do the following;

1. Go to the "SharePoint Online Client Extensibility Web Application Principal" - delete the secret (DO NOT RECREATE MANUALLY)
2. Go to SharePoint Admin Center and "touch" the API page.  Let it load.
3. Wait 5-10minutes and confirm that an Auto Secret was recreated under "SharePoint Online Client Extensibility Web Application Principal"
4. Once that new Secret appears go out to Teams Desktop and load my custom org app and confirm the solution works.  No more "Token previously failed" or "Unable to retrieve client secret" error messages.

I'm glad to say that this process worked and our solution using the PnP Modern Search WebParts is now working through Teams Desktop App. 

I hope that this thread can help someone else out down the road!!
