### ISSUE TITLE
Hit-Highlights not working when the Query Template is modified

### ISSUE THREAD

**Issue by silersbald** [microsoft-search/pnp-modern-search#2648]
**Version used**
4.8.0

**Describe the bug**
Adding a path or ContentTypeID to the Query Template of the Search Results web part causes Hit-Highlighting to no longer work.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Setup a simple search page with a search box and search results.
2. Do not modify the Query Template.  Query Template will be: {searchTerms}
3. Conduct a search.  Hit-Highlighting should work as expected.
4. Edit the page and modify the Query Template by adding: Path:{Site}.  Query Template will now be: {searchTerms} Path:{Site}
5. Conduct the same search as before.  Hit-Highlighting no longer works.  Nothing gets highlighted.

**Expected behavior**
I expect that Hit-Highlighting will work when the query template is modified.  Furthermore, I expect that hit-highlighting will highlight occurrences of the original query text as entered by the end user.

**Desktop (please complete the following information):**
 - Browser = Chrome

**Additional context**
Hit-Highlighting is currently highlighting occurrences of the result of the query template not the original query as entered by the end user.  This can be shown by doing the following:  Modify the query template to be:  {searchTerms}roll.  Then perform a search for "pay", what gets highlighted is occurrences of the word "payroll", not  occurrences of the word "pay".

**Comment by wobba** [comment]
This is an API issue, not a web part issue, so will close it.
