### ISSUE TITLE
v4 upgrades do not use the same names

### ISSUE THREAD

**Issue by buildbod** [microsoft-search/pnp-modern-search#2657]
Attempted to upgrade from v4.5.4.0 to v4.8.0.0 but it failed with the message that:

_A solution with the same product ID already exists.  Please upload the file with the same name and replace the existing solution._

On inspection the internal name used in v4.8.0.0 is different:

![image](https://user-images.githubusercontent.com/13903544/208646606-1f58eb7a-1fff-4c1e-80b8-922902eabf7b.png)

Expected the existing package to update but it failed. As the app is published via the organisations catalog it would be preferrable to perform an in-place upgrade rather than a delete and add.

**Comment by wobba** [comment]
Good point. Rename the sppkg before uploading and it should be ok. I have renamed the sppkg file now in the release.
