### ISSUE TITLE
Using the Search Box webpart in a search page clear previously selected refiners in the Search Filters webpart

### ISSUE THREAD

**Issue by mahmoudhamed** [microsoft-search/pnp-modern-search#266]
**Version used**
3.10

**Describe the bug**
I have a page with the below 3 webparts connected:
- Search Box
- Search Results
- Search Filters

Now I open the page and select one refiner
![image](https://user-images.githubusercontent.com/7877441/81814972-b882d080-9529-11ea-8628-c5119cf89422.png)
then I get 5 results. After that I want to search within these 5 results using the Search Box webpart and I type test for example this works but this also clear the previously selected refiners "Press and Media" in my case.
![image](https://user-images.githubusercontent.com/7877441/81815550-68583e00-952a-11ea-8144-a004de5ac779.png)

**Expected behavior**
I think that you should be able to search with the results by Search Box filtered with Search Filters without the Search Box clearing the previously selected refiners.

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by wobba** [comment]
This is intended behavior and consistent with default search. Searching from the searchbox will reset searching. You need to add more to the search box to support "clear" for this. Feel free to propose a change, but we probably won't put this high on our current backlog right now.

**Comment by mahmoudhamed** [comment]
@wobba I understand now that this is by design, but is there is anyway to prevent this behavior. let’s imagine this dynamic topic page experience that filter all the news in the environment based on a dynamic topic that sent to it, then you need to search more in this page using free text search is there is anyway we can achieve this by?

**Comment by wobba** [comment]
Sure, if you/someone develop the functionaly :) As a workaround, if you have a fixed set of filters you can use the"vertical" web part instead. One vertical per value.
