### ISSUE TITLE
Filter date in Search query keywords

### ISSUE THREAD

**Issue by Brain0verflow** [microsoft-search/pnp-modern-search#267]
Hello,

i'm trying to setup a small birthday list that is showing the people's birthday without the year (The year is always 2013). The dates are mapped to the field refinabledate00.
I've managed to show all people with birthdays with the correct format in the list.

**Describe the solution you'd like**
The search results should show only the birthdays from the current day and the next 30 days and ignoring the year.
 
Is this possible?

Best Regards
Christian

**Comment by wobba** [comment]
This is not a web part specify question, but a general search question. Try tech community or StackExchange.

But yes, should be doable with some trickery and cleverness.
