### ISSUE TITLE
Cannot retrieve the WorkPhone in search results

### ISSUE THREAD

**Issue by shirleysham** [microsoft-search/pnp-modern-search#2675]
I've added a PnP Search results and a search box web parts and did the following in Search Results:
-Under SharePoint Search, added the WorkPhone and WorkPhoneOWSTEXT in the Selected Properties
-Added WorkPhone in layout slot for the data source (using LocalPeopleResults)
-Under Layout options --> Manage people fields, added {{slot item @root.slots.WorkPhone}} as optional text.

However, no workphone information showed up.  I've verified that the Workphone information is included in the User profiles.  Appreciate if you can help.  Many thanks.

**Comment by kasperbolarsen** [comment]
Hi :-) I guess step one in almost every case should be to verify is the expected data is showing up in the debug Layout. Can you confirm that the data is there ?

![image](https://user-images.githubusercontent.com/20593570/210515719-456cff01-a162-48d8-86b7-a4ed9016e49a.png)

**Comment by shirleysham** [comment]
Hi Kasper,

Yes I can find the Workphone information in Debug.  Thanks.

[image: image.png]

**Comment by kasperbolarsen** [comment]
Great :-) The most basic setup is to 
1) add the results web part
2) define the web part to user SharePoint as source, set the query template to {searchTerms} * , set the result source id to LocalPeopleResults
3) change to page 2 of the web part config and select the People Layout and select the Conponent size to Extra large

You should be able to see the WorkPhone in the results now.

**Comment by shirleysham** [comment]
Hey that did it, thanks!!

**Comment by kasperbolarsen** [comment]
Nice 😁

Happy to hear that the issue has been resolved 👌
