### ISSUE TITLE
Sort direction icon (header) and corresponding sort order field(s) not in-sync on initial render

### ISSUE THREAD

**Issue by Kem-El** [microsoft-search/pnp-modern-search#268]
**Version used**
3.11.1 and 3.12.1

**Describe the bug**
After configuring field sort order (via the 'Edit sort order' button) in the Search Results web part and setting any field sort direction to "Descending", if that field(s) is displayed in the details header, the sort icon next to the field incorrectly displays as ascending (up arrow, default) instead of descending (down arrow, configured sort direction).

**To Reproduce**
1. Edit the page and go to any Search Results web part configuration pane
2. Click on 'Edit sort order' button
3. Change direction of any field to 'Descending'
4. Save/Republish the page

**Expected behavior**
The arrow icon in the details header should be pointing down to indicate "Descending" sort order.

Screenshots of the issue:
![MS-PnP-ModernSearch-SortFields](https://user-images.githubusercontent.com/1111137/82172378-996ca180-988f-11ea-8250-757211cbc127.JPG)
![MS-PnP-ModernSearch-InitialLoad](https://user-images.githubusercontent.com/1111137/82172387-9f628280-988f-11ea-8019-5ff6433a2bc0.JPG)

**Desktop (please complete the following information):**
 - Chrome, Chredge/Edgium

**Comment by wobba** [comment]
As the sorting on the details list is an in memory sort I suggest you perhaps use the "Edit sortable fields" option instead. The inline sorting only works if the number of elements shown is less than or equal to the number of items returned. As an example the `Title` managed property is not sortable on the full result set.
