### ISSUE TITLE
Filters with Site Title is not working as expected

### ISSUE THREAD

**Issue by GowthamiKothapalli** [microsoft-search/pnp-modern-search#2684]
Hi Team,

In search results webpart query template I'm using {searchTerms} PromotedState:2 to show news that are published, which is working fine, however I'm trying to add Site Title filter using Filters webpart, as Site Title is not refinable used RefinableString00 to map Site Tile Crawled property, however it's not showing any Filters, but   if I remove PromotedState:2 from Query Template Site Title filters populate (showing).

Please let me know if I'm doing anything wrong here .

**Site Title filter not showing up:** 

![image](https://user-images.githubusercontent.com/19287164/211382148-dd526167-a6b6-4e31-804e-2e0ec4d59e29.png)

**Site Title filter showing up:** 

![image](https://user-images.githubusercontent.com/19287164/211382414-d0e77e29-53ce-4cef-bcf9-2ef14a498385.png)

Regards,

**Comment by kasperbolarsen** [comment]
most likely the issue is related to the mapping of Title. Perhaps this issue can guide you https://github.com/microsoft-search/pnp-modern-search/issues/2417

**Comment by GowthamiKothapalli** [comment]
thanks for swift response, don't think its Title mapping related, when I remove PromotedState:2 from Query Template box, Site Title filter works fine though

**Comment by kasperbolarsen** [comment]
Your mapping looks like this and the RefinableString has been added to "Selected properties", right ?
![image](https://user-images.githubusercontent.com/20593570/211418213-83586d07-c156-4c10-aa1d-3019589c70f6.png)

**Comment by GowthamiKothapalli** [comment]
Yes that’s correct

**Comment by kasperbolarsen** [comment]
And you have configured the Results Web Part to connect to the Filter web part ?
![image](https://user-images.githubusercontent.com/20593570/211423434-22c22d8d-865a-46c9-ba45-a5a3608abfd4.png)

**Comment by GowthamiKothapalli** [comment]
Yes I did

**Comment by kasperbolarsen** [comment]
And the RefinableString shows up with a value when switching to the debug layout?
![image](https://user-images.githubusercontent.com/20593570/211424230-67fbd067-5965-4fea-a0f2-8e6f886b2e56.png)

**Comment by GowthamiKothapalli** [comment]
Yes it does

**Comment by kasperbolarsen** [comment]
Please try the change PromotedState:2 to Path:[URL of one of the sites that contains a published news item], like this

![image](https://user-images.githubusercontent.com/20593570/211425496-fe985d07-7fbe-4330-afce-3786db4223c7.png)


Any change?

**Comment by GowthamiKothapalli** [comment]
thanks @kasperbolarsen for your help this seems to be working, need to so some more testing's
