### ISSUE TITLE
Use RefinableString for the Default Value in the Search Results WebPart

### ISSUE THREAD

**Issue by Dominique96** [microsoft-search/pnp-modern-search#2687]
**Version used**
Ex: 4.8

**Describe the bug**
I want to use a refinableString with the user Property in the Default Value of the PnP Search Results.
With only the {user} property it works and also with an {User.<property>}, but with an refinableString it doesn't work. 

Example: {User.refinableString63}

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to step 3 of 4 in the PnP Search Results WebPart
2. Click on "Use a default Value"
3. Enter in Default Value {User.refinableStringXY}
4. Save
5.  and See error

**Expected behavior**
It should load the search results of the query

**Screenshots**
![image](https://user-images.githubusercontent.com/12407169/211552407-94558d5c-1f1a-4438-bdff-c44bc99c5ee8.png)
![image](https://user-images.githubusercontent.com/12407169/211552456-bf63fd7a-6448-461c-b195-a0ba3b3cfc50.png)
![image](https://user-images.githubusercontent.com/12407169/211552471-2c2ce9e6-30e3-4d56-baca-5f1d41ad7dc4.png)

**Desktop**
 - Browser [e.g. Egde, Google Chrome]

**Comment by FranckyC** [comment]
Hi @Dominique96, this is expected as you can't use query variables here, only free text keywords. For your use case, you should use this value in the query template field in the search results Web Part instead.
