### ISSUE TITLE
PnP 4.2.3 Search Webparts are not working all of a suddenly

### ISSUE THREAD

**Issue by soumyadeep2207** [microsoft-search/pnp-modern-search#2688]
**Version used**
4.2.3

**Describe the bug**
We are seeing below error for all PnP Search Webparts (Search Box, Search Filter, Search Results) from yesterday which was working earlier 

SPLoaderError.loadComponentError]:
Failed to load component "544c1372-fb1d-4e96-bc1e-31fd66979667" (pnpSearchFiltersWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/xxx.sharepoint.com/sites/AppCatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/PropertyControlStrings_en-us_3770839de1f3a0bef2a56730368aab40.js' for resource 'PropertyControlStrings' in component '544c1372-fb1d-4e96-bc1e-31fd66979667' (pnpSearchFiltersWebPart). The file was not found in the server.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/xx.sharepoint.com/sites/AppCatalog/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/PropertyControlStrings_en-us_3770839de1f3a0bef2a56730368aab40.js' for resource 'PropertyControlStrings' in component '544c1372-fb1d-4e96-bc1e-31fd66979667' (pnpSearchFiltersWebPart). The file was not found in the server.
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_49d37ded9db4e12f19a385ada4e9abe3.js:70:540775)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_49d37ded9db4e12f19a385ada4e9abe3.js:70:798693)
    at e.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_49d37ded9db4e12f19a385ada4e9abe3.js:70:835977)
    at e.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_49d37ded9db4e12f19a385ada4e9abe3.js:70:832068)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_c9d296eaa8490acee6b3.js:1:6036

**Expected behavior**
PnP Modern Search Webparts should appear properly
**Screenshots**

![PnP Search Issue](https://user-images.githubusercontent.com/55022369/211671111-cc8f2bcd-38f7-44bf-ba86-20b3e727a1d1.PNG)

Anything major happening with v4.2.3. Please assist us 

Regards,
Soumyadeep

**Comment by ChezMarsupilami** [comment]
Hi, we are running version 4.3.0 and it is also not working today, but yesterday worked fine. Can't provide the logs as I'm not the admin of our Office365 instance, sorry. But apparently the issue is the same.

Any help please? Thanks a lot.

**Comment by soumyadeep2207** [comment]
@FranckyC  @wobba , please share your inputs on the issue, we are still facing the issue but intermittently now compare to yesterday. Looking forward to your response

**Comment by ChezMarsupilami** [comment]
Hi,

AFAIK this was due to a change in Sharepoint’s API that broke the query we issued. Our platform provider has made some changes on it and everything is working fine again. Sorry for not being able to provide any more information.

  Best regards,

Rafael Flores Yoldi ***@***.******@***.***>
Departamento de Informática – Saltoki S.A.

**Comment by Ukiman1014** [comment]
> AFAIK this was due to a change in Sharepoint’s API that broke the query we issued.

What was the change?  We're using v.4.8 and noticed that it broke yesterday as well.  Unsure of how to fix it.

**Comment by Ukiman1014** [comment]
FYI, I fixed our particular issue by removing the quotes around the static search term.  Previously it was "*" and now it's just *.  I couldn't get Microsoft to look up a correlation ID for me, so I do not know if it was the exact same issue, but this had been working for months and suddenly broke.

![image](https://user-images.githubusercontent.com/22643106/212966524-13d123ea-4a55-44a3-8fb6-3b3d38e94deb.png)

**Comment by soumyadeep2207** [comment]
Hi,

But for my case its sporadic, **search result webpart is displaying some results to some of the users but for some users its not at all working**, giving below error till now.

Also in my query template there is no static search term present. 
![image](https://user-images.githubusercontent.com/55022369/213364883-02dd8d64-482c-430b-8b4c-851abeb8f05e.png)



![image](https://user-images.githubusercontent.com/55022369/213364579-d16a07b0-1598-4fb9-91e8-9fbcb1b59d17.png)

Not sure where lies the issue. Can anybody shed any pointer at what to look for. We in fact tried to upgrade version to 4.8, downgrade to 4.2.3 but affected users are still facing the same issue.

Regards,
Soumyadeep

**Comment by wobba** [comment]
If you recently uploaded a new version then caching is involved, particularly with CDN. If you wait some hours, and/or clear your browser cache it should resolve itself. For users with an error, try open a private browser window to re-test.

**Comment by soumyadeep2207** [comment]
Hi @wobba ,

We tried clearing cache/logging from Incognito but neither version 4.2.3 nor the higher version working for the affected users. But for some users same version working properly which is even more strange. 

Regards,
Soumyadeep

**Comment by wobba** [comment]
All internal users should have access to your CDN by default setup. So not sure why you have issues. If you are using site added web parts you can try to re-add them to the site (no need to change the pages).
