### ISSUE TITLE
Sort List from Querystring or Dynamic Data

### ISSUE THREAD

**Issue by whitegenie** [microsoft-search/pnp-modern-search#269]
**Is your feature request related to a problem? Please describe.**
Under certain conditions I need to display the search results in a specific order, different from the default order set in the page. For example when reaching the search results page through a specific link with a certain value in querystring.

**Describe the solution you'd like**
It would be nice to have the option to use the querystring values ​​in the sort list.

**Describe alternatives you've considered**
Another option, maybe a better one, would be to have the possibility to link the sort list (totally or partially) with dynamic data. In this way, I could create another web part that exposes the sort list via dynamic data calculated by querystring or in any other way.

**Comment by Georg-Trixl** [comment]
Nice idea of sorting. In some systems are ordering options shown above of the search results.
I could imagine, that a sorting UI could be positioned below of the verticals webpart and that sorting would be configured in the verticals as there are configurations for search query is done. On the other hand, sorting should also be possible without of use of a vertical webpart.
Overall I think that's not so easy to implement.
In general I am happy with the default ranking model used in the search. But when it comes to solutions based on SharePoint other sorting methods are often mandatory.

**Comment by michikammerer** [comment]
Extending the querystring by an other ranking model e.g. "&rankingmodelid='9399df62-f089-4033-bdc5-a7ea22936e8e'" would solve my problem. The default ranking model of sharepoint doesn't support the actuality of the items. Changing the ranking model would solve the problem.

e.g. search query:
https://<sites>/_api/search/query?querytext='Test'&rankingmodelid='9399df62-f089-4033-bdc5-a7ea22936e8e'

**Comment by wobba** [comment]
Due to the direction search is moving in Office 365 there are no plans to support rankmodel's directly in the PnP modern search web parts. You can however do it via result sources as a workaround or add it yourself in a custom branch. If you want to add emphasis on dates you may also do this via nested XRANK's which is available via the SP Search Query Tool.

![image](https://user-images.githubusercontent.com/51104/98268231-9031d700-1f8c-11eb-9e03-2b4475da3eba.png)
