### ISSUE TITLE
500 CorrelationId on particular Path values

### ISSUE THREAD

**Issue by svanmoerkerke** [microsoft-search/pnp-modern-search#2690]
**Version used**
4.8

**Describe the bug**
When i setup the PnP Search Results webpart, i get 500 error on particular Path values: 
[HTTP]:500 - [CorrelationId]:04358ba0-d0e8-5000-e544-0de2685677d7 [Version]:16.0.0.23207

But only on specific Path value. My client has 2 site(collection)s, xxx (+ 5 million files) and xxx-dev (33k files), the dev version is for testing purposes. 

Whenever i configure the PnP webparts to show all files, files only, without aspx and for xxx path, i get 500 error. When i use a subsite of xxx i have no problem. 

So 
- Path:https://contoso.sharepoint.com/sites/xxx does **not** work
- Path:https://contoso.sharepoint.com/sites/xxx/* does **not** work
- Path:https://contoso.sharepoint.com/sites/xxx/finance does work
- Path:https://contoso.sharepoint.com/sites/xxx/quality does work
- Path:https://contoso.sharepoint.com/sites/xxx-dev does work
- Path:https://contoso.sharepoint.com/sites/xxx-dev/* does work
- Path:https://contoso.sharepoint.com/sites/xxx-dev/finance does work

The complete Query template i use is this:
{?{searchTerms} IsDocument:1 -fileextension:aspx Path:"https://contoso.sharepoint.com/sites/xxx/*"}

Another strange thing is that when i edit the webpart properties, and first i get a 500 error, when i change the Query template a couple of times, and end with {?{searchTerms} IsDocument:1 -fileextension:aspx Path:"https://contoso.sharepoint.com/sites/xxx/*"}, I sometimes do get results without error? But when i publish, i get the 500 error again?

I did log a ticket with Microsoft to get help on this, but their answer is they don't support PnP Modern Search problems??:
_After a thorough research and after checking with my team, it was confirmed that PnP Modern Search is an open source, and we are unable to provide support for it at the moment.
 
Have you tried any SharePoint built in webparts as shown in the documentation below?
[Using web parts on SharePoint pages - Microsoft Support](https://support.microsoft.com/en-us/office/using-web-parts-on-sharepoint-pages-336e8e92-3e2d-4298-ae01-d404bbe751e0)_

**To Reproduce**
1. Add PnP Search box
2. Add Pnp Search Results to page
3. put in different Path values as mentioned above
4. get error for certain path values and not for others

**Expected behavior**
always get results, depending on provided Path value

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**
this is the payload which gives errors
{"request":{"__metadata":{"type":"Microsoft.Office.Server.Search.REST.SearchRequest"},"ClientType":"PnPModernSearch","Properties":{"results":[{"Name":"EnableDynamicGroups","Value":{"BoolVal":true,"QueryPropertyValueTypeIndex":3}},{"Name":"EnableMultiGeoSearch","Value":{"BoolVal":true,"QueryPropertyValueTypeIndex":3}},{"Name":"ClientFunction","Value":{"StrVal":"PnPSearchWebPart","QueryPropertyValueTypeIndex":1}},{"Name":"ListId","Value":{"StrVal":"40acf101-f5ed-4158-a0d5-b154519a3280","QueryPropertyValueTypeIndex":1}},{"Name":"ListItemId","Value":{"StrVal":"3","QueryPropertyValueTypeIndex":1}}]},"Querytext":"","EnableQueryRules":false,"QueryTemplate":"{? IsDocument:1 -fileextension:aspx Path:https://contoso.sharepoint.com/sites/xxx}","SourceId":"8413cd39-2156-4e00-b54d-11efd9abdb89","EnableNicknames":false,"EnablePhonetic":false,"Culture":1033,"TimeZoneId":3,"Refiners":"","RefinementFilters":{"results":[]},"RowLimit":10,"StartRow":0,"TrimDuplicates":false,"SortList":{"results":[]},"SelectProperties":{"results":["AuthorOWSUSER","contentclass","ContentTypeId","Created","CreatedBy","DefaultEncodingURL","FileType","HitHighlightedProperties","HitHighlightedSummary","HtmlFileType","JobTitle","NormListID","NormSiteID","NormUniqueID","NormWebID","owstaxidmetadataalltagsinfo","Path","RefinableString01","SiteLogo","SiteTitle","SPSiteUrl","Title","UniqueID","UserName","WorkPhone"]},"HitHighlightedProperties":{"results":[]},"ReorderingRules":{"results":[]}}}

response is 
{"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}

this is payload that does not give error:
{"request":{"__metadata":{"type":"Microsoft.Office.Server.Search.REST.SearchRequest"},"ClientType":"PnPModernSearch","Properties":{"results":[{"Name":"EnableDynamicGroups","Value":{"BoolVal":true,"QueryPropertyValueTypeIndex":3}},{"Name":"EnableMultiGeoSearch","Value":{"BoolVal":true,"QueryPropertyValueTypeIndex":3}},{"Name":"ClientFunction","Value":{"StrVal":"PnPSearchWebPart","QueryPropertyValueTypeIndex":1}},{"Name":"ListId","Value":{"StrVal":"40acf101-f5ed-4158-a0d5-b154519a3280","QueryPropertyValueTypeIndex":1}},{"Name":"ListItemId","Value":{"StrVal":"3","QueryPropertyValueTypeIndex":1}}]},"Querytext":"","EnableQueryRules":false,"QueryTemplate":"{? IsDocument:1 -fileextension:aspx Path:https://contoso.sharepoint.com/sites/xxx-dev}","SourceId":"8413cd39-2156-4e00-b54d-11efd9abdb89","EnableNicknames":false,"EnablePhonetic":false,"Culture":1033,"TimeZoneId":3,"Refiners":"","RefinementFilters":{"results":[]},"RowLimit":10,"StartRow":0,"TrimDuplicates":false,"SortList":{"results":[]},"SelectProperties":{"results":["AuthorOWSUSER","contentclass","ContentTypeId","Created","CreatedBy","DefaultEncodingURL","FileType","HitHighlightedProperties","HitHighlightedSummary","HtmlFileType","JobTitle","NormListID","NormSiteID","NormUniqueID","NormWebID","owstaxidmetadataalltagsinfo","Path","RefinableString01","SiteLogo","SiteTitle","SPSiteUrl","Title","UniqueID","UserName","WorkPhone"]},"HitHighlightedProperties":{"results":[]},"ReorderingRules":{"results":[]}}}

response is
{"ElapsedTime":0,"PrimaryQueryResult":{"CustomResults":[],"QueryId":"7756df13-5324-410d-a2b2-42ebe4a2f934","QueryRuleId":"00000000-0000-0000-0000-000000000000","RefinementResults":null,"RelevantResults":{"GroupTemplateId":null,"ItemTemplateId":null,"Properties":[{"Key":"RenderTemplateId","Value":"~sitecollection/_catalogs/masterpage/Display Templates/Search/Group_Default.js","ValueType":"Edm.String"},{"Key":"QueryModification","Value":"IsDocument:1 -fileextension:aspx Path:https://contoso.sharepoint.com/sites/xxx-dev -ContentClass=urn:content-class:SPSPeople","ValueType":"Edm.String"},{"Key":"ExecutionTimeMs","Value":"0","ValueType":"Edm.Int32"},{"Key":"StartRecord","Value":"0","ValueType":"Edm.Int32"},{"Key":"piPageImpressionBlockType","Value":"2","ValueType":"Edm.Int32"},{"Key":"IsLastBlockInSubstrate","Value":"true","ValueType":"Edm.Boolean"},{"Key":"IsFirstBlockInSubstrate","Value":"false","ValueType":"Edm.Boolean"},{"Key":"IsFirstPinnedResultBlock","Value":"false","ValueType":"Edm.Boolean"},{"Key":"IsLastPinnedResultBlock","Value":"false","ValueType":"Edm.Boolean"},{"Key":"IsFirstRankedResultBlock","Value":"true","ValueType":"Edm.Boolean"},{"Key":"IsLastRankedResultBlock","Value":"true","ValueType":"Edm.Boolean"},{"Key":"MixedTableOrder","Value":"0","ValueType":"Edm.Int32"}],"ResultTitle":null,"ResultTitleUrl":null,"RowCount":10,"Table":{"Rows":[{"Cells":[{"Key":"AuthorOWSUSER","Value":...

**Comment by wobba** [comment]
500 errors are API issues and not something we can solve with the web parts. You have to log a support case or try via https://github.com/SharePoint/sp-dev-docs/issues
