### ISSUE TITLE
Broken show persona card on hover pull-down option in People layout when "Allow items selection" is on. 

### ISSUE THREAD

**Issue by gretchunkim** [microsoft-search/pnp-modern-search#2695]
**Version used**
 4.8.0.0

**Describe the bug**

**To Reproduce**
Detailed steps to reproduce the behavior: 
1. Add PnP-Search Results in the page. 
2. Select SharePoint Search as data source and pick LocalPeopleResults under Result Source ID (1 of 4). 
3. Select "People" under Available layouts (2 of 4). 
4. Allow items selection and On Show persona card on hover (2 of 4). 
5. Save/draft/publish the page.
6. Hover over to show persona card.
7. Click "expanded-details-button' on the persona card. 
8. No detail persona card shows. 
9. To get back the detail persona card, turn off "Allow items selection". 

**Expected behavior**
"Allow items selection" won't conflict with Show persona card detail to show. 

**Screenshots**

![image](https://user-images.githubusercontent.com/8564035/212580899-1fc0e006-7abb-41a0-9448-9ac42cbca9e9.png)

**Desktop (please complete the following information):**
 - Chrome- tested 

**Additional context**
Not tested using MS Graph as data source at this time.

**Comment by kasperbolarsen** [comment]
Could it be that this can be resolved by updating the layout alone? If so, I can give it a go. @gretchunkim will you be able to variety the new layout template?

**Comment by kasperbolarsen** [comment]
Unfortunately it was more complicated than I hoped, so I have not been able to fix it 😕

**Comment by gretchunkim** [comment]
@kasperbolarsen I see.  That's good news as I'm behind my task for this week. Thank you.

**Comment by wobba** [comment]
Took a look an there's no easy way to figure out that the hover is showing to then dismiss the selection. So won't fix.
