### ISSUE TITLE
Live Persona Card missing on person

### ISSUE THREAD

**Issue by bartvermeersch** [microsoft-search/pnp-modern-search#27]
When using the person render template, should there be a Live Persona Card visible on hover? Or am I misinterpreting the template option "Disable info on hover".

The wording is a bit misleading ("Show info on hover" would be easier to understand). I tried true as well as false but could get any Live Persona Card pop up. I tried Chrome, Firefox and Chromium.

**Comment by FranckyC** [comment]
Hi @bartvermeersch yeah actually this part was here initially but we had to remove it due to a limitation of the LivePersona component. According to Microsoft, we are not supposed to use this component directly in our custom Web Parts. Maybe this will come back in next releases.

**Comment by stevebeauge** [comment]
Hello @FranckyC . Are you talking about [this](https://github.com/Anil-Lakhagoudar/SPFxLivePersonaCard/blob/master/src/webparts/spContactCard/components/SPFXPeopleCard/SPFxPeopleCard.tsx) component ?

**Comment by FranckyC** [comment]
@stevebeauge Exactly
