### ISSUE TITLE
Unable to find newly added webpart after deployment

### ISSUE THREAD

**Issue by Narasireddy447** [microsoft-search/pnp-modern-search#270]
Hi Team,
I have added a new webpart to the PnP search solution, after sucessfull deployment not able to find the newly added webpart.

may i know how to see my newly added webpart.

**Comment by wobba** [comment]
You need to share more details of your exact deployment in order to help.

**Comment by FranckyC** [comment]
Hi @Narasireddy447, can you try to redeploy your solution from the app catalog using the 'Deploy' button in the ribbon? 

![image](https://user-images.githubusercontent.com/5659122/82336417-8b667000-99b8-11ea-97c2-4f9f2f6884df.png)

**Comment by jmuehlenbein** [comment]
I'm having the same issue and re-deploying has not changed anything. I completely removed the app, then re-added to app catalog and deployed the latest--3.14.2.0 but still no luck. When I select 'add an app' it doesn't show up as an option.
