### ISSUE TITLE
Results web part disappears when clicking the File Type icon

### ISSUE THREAD

**Issue by kasperbolarsen** [microsoft-search/pnp-modern-search#2702]
**Version used**
 4.8.0
Browser: Edge Version 109.0.1518.55

**Describe the bug**

When clicking on the FileType icon in the Column Headers using the Details List layout the entire results grid disappears.
Web part: Search Results

**To Reproduce**
Detailed steps to reproduce the behavior:
1) Add some documents in the Document Library
2) Add a Results Web part
3) Select SharePoint as the Data Source
4) Change the Query to : {searchTerms} path:{Site} isDocument:1
5) Select the Details list as a Layout
6) Publish the page
7) Click on the File Type icon in the Column Header

![image](https://user-images.githubusercontent.com/20593570/213681823-fda3f9bc-b2f5-4610-963b-da60355a843c.png)

**Comment by wobba** [comment]
Fixed with #3044
