### ISSUE TITLE
PnP search webpart work for some users, but showing zero results for other. Even they have access to sites.

### ISSUE THREAD

**Issue by AshutoshGDS** [microsoft-search/pnp-modern-search#2708]
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/2705

<div type='discussions-op-text'>

<sup>Originally posted by **AshutoshGDS** January 23, 2023</sup>
I am adding Query Template in PnP - search web part.
Earlier it works fine for everyone, but from Friday it seems like working with some users but for some users its not showing any result.

I check with the search query api, users are able to get the result in API but in this webpart its not available.</div>

**Comment by wobba** [comment]
If it used to work and stopped, then it's an API issue and you have to log a support ticket with Microsoft and/or log an issue at https://github.com/SharePoint/sp-dev-docs
