### ISSUE TITLE
Search Results for New Document Library not Returning in PnP - Search Results

### ISSUE THREAD

**Issue by noodleNT** [microsoft-search/pnp-modern-search#2712]
**Summary:**
I have a Report Repository Site with a Document Library for each of our test environments and production.

**Environment = Document Library**
- Production = Reports
- Q (UAT) = ReportsQ
- D (Development) = ReportsD
- F (Debugging\Testing) = ReportsF (I created this one from a saved template created from Q without contents)

I use PnP - Search Verticals to select each environment which in turn will select a different PnP - Search Results web part. I have each web part configured with a custom Query Template so it only returns results in that matching document library.

Production
```
and({searchTerms}, 
path:"https://bmic149.sharepoint.com/sites/Reports/Reports/")
IsDocument:1
```

Q
```
and({searchTerms}, 
path:"https://bmic149.sharepoint.com/sites/Reports/ReportsQ/")
IsDocument:1
```

D
```
and({searchTerms}, 
path:"https://bmic149.sharepoint.com/sites/Reports/ReportsD/")
IsDocument:1
```

F
```
and({searchTerms}, 
path:"https://bmic149.sharepoint.com/sites/Reports/ReportsF/")
IsDocument:1
```

For some reason F will not return any results. I have double checked everything here:
https://learn.microsoft.com/en-us/sharepoint/make-site-content-searchable#show-content-from-lists-or-libraries-in-search-results?WT.mc_id=365AdminCSH_SupportCentral

The only thing different was that I created a Document Library Template first from ReportsQ so I didn't have to re-create my views.

**Debugging:**
Now I created a test search page with just one PnP - Search Results webpart and set the Query template to show one file that I know exists in each document library.

`BREPPAYEFT*
IsDocument:1`

I added URL to my column result list and confirmed the paths:

https://******.sharepoint.com/sites/Reports/ReportsF/BREPPAYEFT-2023-01-24.pdf

https://******.sharepoint.com/sites/Reports/Reports/BREPPAYEFT-2023-01-13.pdf

https://******.sharepoint.com/sites/Reports/ReportsH/BREPPAYEFT-2023-01-24.pdf

https://******.sharepoint.com/sites/Reports/ReportsF/BREPPAYEFT-2023-01-24.pdf

Any ideas?

**Comment by noodleNT** [comment]
Found my issue... my KQL syntax was incorrect.

```
({searchTerms} path:"https://bmic149.sharepoint.com/sites/Reports/ReportsD/")
IsDocument:1
```

**Comment by kasperbolarsen** [comment]
Good to hear :-)
