### ISSUE TITLE
Modern Search Results: Not all items shown, sometimes they are

### ISSUE THREAD

**Issue by OnlySam89** [microsoft-search/pnp-modern-search#2727]
**Version used**
4.8

**Describe the bug**
We are using PNP Modern Search Results to display to end users a list of document libraries within SharePoint that they have access. This is filtered using the description field against each document library to break this down against per company within the group.

The majority of document libraries show as expected, however we have a couple that will only display randomly - you can check back later that day and they've disappeared until a random point in time again in the future. This behaviour occurs for all users viewing these results.

Yesterday I updated to the latest version to see whether this was a bug or know issue, initially everything showed as expected within the results - however today some are missing again.

I've raised a support case with Microsoft support as I assumed that this was an issue with SharePoint, but after checking they said that I should raise it here.

**To Reproduce**
Webpart: PnP: Search Results
Available data sources: SharePoint Search
Query text: {searchTerms}
Result source ID: LocalSharePointResults
User input query test: On
Query text (static): ("SPSiteUrl": "https://xxxxxx.sharepoint.com/sites/Company-Shares") AND contentclass:STS_List_DocumentLibrary AND (Description:<company name> OR Description:Group)
Connect to a verticals web part: On (used to filter between the different group companies, each has it's own search web part to display results) 

**Expected behavior**
A list of all document libraries that match the correct SP Site URL which contain the stated description value. The user will only see document libraries that they have access.

**Desktop (please complete the following information):**
 - Browser: Chrome, Edge, FireFox

**Additional context**
Users can access the document libraries as normal through the direct URL, just won't show up in the PnP search results.

**Comment by kasperbolarsen** [comment]
Can you share the message from MS support pointing you here?

**Comment by gretchunkim** [comment]
@kasperbolarsen I can second what @OnlySam89 says about MS Support team. Whenever I tell them my use case, although the issue or question is about the MS Graph, SharePoint API, even MS Graph Connector, they told me that there's only one Graph Support Engineer and out of luck.  I've opened a simple technical documentation question back in Dec 2022 about Graph Connector supporting On Prem SQL procedure and they couldn't answer the question. In fact, they couldn't answer any questions.

**Comment by kasperbolarsen** [comment]
I might or might not agree that MS Support sometimes doesn't deliver :-) However in this case I was wondering if MS Support had any findings related to this case that would point us in the right direction.

PS How does the search behaves if the  "AND (Description: OR Description:Group)"  section is temporarily removed?

**Comment by kasperbolarsen** [comment]
Or perhaps try to check when the item was indexed last time using https://pnp.github.io/powershell/cmdlets/Get-PnPSearchCrawlLog.html

**Comment by wobba** [comment]
The best for API related issues is to replicate the issue using the classic search experience and then log it based on that. Or log the issue at https://github.com/SharePoint/sp-dev-docs which is triaged monthly for search API related issues.
