### ISSUE TITLE
PDF preview shows explorer view instead

### ISSUE THREAD

**Issue by varunmshetty** [microsoft-search/pnp-modern-search#273]
**Version used**
3.12

**Describe the bug**
When hovering over a pdf, the preview doesn't render the document view, but instead shows the explorer view of the folder where the document resides.

**To Reproduce**
This issue is not restricted to a single PDF. Tried this on over 20 different files.
Not restricted to a single tenant. Tried on a Developer and a Live tenant.
Search for a file and hover (click) on it to experience the behavior.

**Expected behavior**
The PDF preview must be shown and not the explorer view of its parent folder.

**Screenshots**
Screenshot attached.

**Desktop (please complete the following information):**
On Win 10, witnessed on Chrome (81.0.4044.138), Firefox (68.8.0 ESR), New Edge (81.0.416.72)

**Additional context**
The PDF preview of the out of the box search works just fine. Issue only with the PNP modern search.

![Search_PDF_Issue_DevTenant](https://user-images.githubusercontent.com/21065632/82385707-b8d70c00-9a00-11ea-9166-3741af908533.PNG)

**Comment by malcom1120** [comment]
I had this same issue.  I'm looking at the code on this now.  It had an old custom template that still works with PDFs so I'm comparing that template and the new default templates.

**Comment by wobba** [comment]
We'll look into it, and shouldn't be hard to fix :)
