### ISSUE TITLE
Profile Image on card layout is missing

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#2743]
The username from the creator attribute is not passed down rendering an incorrect profile URL.

### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/2733

<div type='discussions-op-text'>

<sup>Originally posted by **janetslei** February  2, 2023</sup>
Is there anything I need to change in the default settings of the search results web part to get the profile picture of the Author to show up in the card layout? The People layout shows it with no issues for the same user, what am I missing?
![image](https://user-images.githubusercontent.com/8562215/216224914-d57d704a-effa-4e50-8749-62e3c239c795.png)
</div>

**Comment by kasperbolarsen** [comment]
OK , found the problem, use this workaround until we can roll out the update:
in the "Managed Card fields" find the "Profile Image Url" property. It contains this value:
/_layouts/15/userphoto.aspx?size=L&username={{getUserEmail (slot item @root.slots.UserEmail)}}

There are not a UserEmail slot in this layout. Replace @root.slots.UserEmail  with @root.slots.Author , and now it works
