### ISSUE TITLE
"Starts with" operator in Result Types does not work

### ISSUE THREAD

**Issue by RobertSStorm** [microsoft-search/pnp-modern-search#2789]
**Version used**
4.8

**Describe the bug**
In the Search Results web part, when using result types using the "Starts with" operator, results that meet the result type condition do not get the result type template applied.

**To Reproduce**
1. Go to page 2 of the Search Results web part settings
2. Click on 'Edit result types'
3. Configure a result type with the "Starts with" operator
4. Load results that meet the condition of this result type
5. The result type template is not applied.

**Expected behavior**
The result type template should be applied to items that meet the result type condition.

**Screenshots**
![image](https://user-images.githubusercontent.com/125990098/220379155-62c17012-49e0-4504-96c6-6d58a4b60601.png)
![image](https://user-images.githubusercontent.com/125990098/220379230-9c09840a-ad31-490f-8d8f-fa756ddf7932.png)

**Desktop:**
 - Browser: Edge

**Comment by wobba** [comment]
Fixed with #3402
