### ISSUE TITLE
Alphabetical order of filters

### ISSUE THREAD

**Issue by schatti** [microsoft-search/pnp-modern-search#2809]
**Version used**
Ex: 4.8.0

**Describe the bug**
Filter Webpart doesn't order values correct alphabetical. Capital Letters are always on top of list

**To Reproduce**
- Use a Filter WP
- Configure to sort values alphabetical

**Expected behavior**
Use sorting case insensitive

**Screenshots**
![image](https://user-images.githubusercontent.com/20019646/221861347-4f24c7b1-f7a2-42d3-80d6-ea17b651a4b0.png)

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**

**Comment by wobba** [comment]
I assume you have "sort my name ascending". So you would like case-insensitive sort?

**Comment by schatti** [comment]
Yes I would expect to have "Bycell Cross" on top of "ByVention" when setup "sort my name ascending".

**Comment by wobba** [comment]
Fixed with https://github.com/microsoft-search/pnp-modern-search/commit/6f502a695b43ebecebf385e6b89803d7da2007bb
