### ISSUE TITLE
Can't use people layout with anything else than user profles

### ISSUE THREAD

**Issue by stevebeauge** [microsoft-search/pnp-modern-search#281]
**Version used**
3.12.1

**Describe the bug**
I want to display searchs result using people layout but not from the local people results (imagine a contact list or custom people repository).

1st issue is that the Result Source Identifier can't be emptied. each time I choose the people layout, the parameter is reset to the local people result source ID. I didn't found a way to clear this field.

As a workaround, I can set the "Local SharePoint results" source ID (once the field is set, it seems to be preserved).

2nd issue, is that it renders blanks. Even if there is data, the component appears blanks. Not hidden as if there were no results, but blank like there are mulitple blank lines.

I didn't found a way (yet) to solved that.

I may be using it wrong, but I feel there's something in the profile that's missing in my case.

**To Reproduce**
1. Create a simple generic list, named "Debug" (or anything else)
2. populate data (only title)
3. wait for the list to be indexed
4. drop a search result webpart somewhere
    1. Set `*` in the Search query keywords (page 1)
    2. Set `{?{searchTerms} Path:"{\Site}/Lists/Debug*"}` in the Query template field (page 2)
    3. ==> Results should appears in a grid
    4. Select People layout (page 3)
    5. Actual profiles should render. This is **not** what we are looking for. 
    6. Go back to page 2
    7. Clear the Result Source Identifier field
    8. Go to page 3, then page 2
    9. Query template and Result Source Identifier is reset to local people results ==> **1st issue**
    10. force the Result Source Identifier to `8413cd39-2156-4e00-b54d-11efd9abdb89` (which is the local sharepoint result source ID), and apply again the query template `{?{searchTerms} Path:"{\Site}/Lists/Debug*"}`
    11. ==> The component goes blank, event if results are found
    12. Configure the template fields of the layout. Especially, set up the `Title` managed property in the `Primary text` field
    13. ==> the component is still blank

**Expected behavior**
The people layout should allow rendering data from any kind of object, not only profiles

**Screenshots**

![image](https://user-images.githubusercontent.com/184604/82678828-92a4ac80-9c4a-11ea-9677-0d3c97a38ef6.png)

![image](https://user-images.githubusercontent.com/184604/82678851-9f290500-9c4a-11ea-8bc0-4c9eb5d8c75d.png)

![image](https://user-images.githubusercontent.com/184604/82679014-e7e0be00-9c4a-11ea-8ad6-5287dc05927b.png)

**Desktop (please complete the following information):**
 - Any browser

**Additional context**

Here's the HTML output of the component (extracted using the Firefox dev tools):

````html
<div><style>#pnp-modern-search-template_27bf8001-5013-4382-92d9-14dbc293c0a8 .personaCard { margin: 10px; }</style><div id="pnp-modern-search-template_27bf8001-5013-4382-92d9-14dbc293c0a8">

    <div class="template_root">
            <div class="template_defaultCard">
                <div class="template_resultCount">
                    <label class="ms-fontWeight-semibold"><b>4</b> résultats pour '<em>*</em>'</label>
                </div>
                <div class="ms-Grid">
                    <div class="ms-Grid-row">
                        <div class="ms-Grid-col ms-sm12 ms-md12 ms-lg12">
                                <div class="personaCard">
                                </div>
                        </div>
                        <div class="ms-Grid-col ms-sm12 ms-md12 ms-lg12">
                                <div class="personaCard">
                                </div>
                        </div>
                        <div class="ms-Grid-col ms-sm12 ms-md12 ms-lg12">
                                <div class="personaCard">
                                </div>
                        </div>
                        <div class="ms-Grid-col ms-sm12 ms-md12 ms-lg12">
                                <div class="personaCard">
                                </div>
                        </div>
                    </div>
                </div>
            </div>
                <pnp-pagination data-total-items="4" data-hide-first-last-pages="false" data-hide-disabled="true" data-hide-navigation="false" data-range="5" data-items-count-per-page="10" data-current-page-number="1"></pnp-pagination>
    </div>
</div></div>
````

As you can see, there are the correct number of iterations (4 results in my sample), but with empty divs

````
<div class="ms-Grid-col ms-sm12 ms-md12 ms-lg12">
                                <div class="personaCard">
                                </div>
                        </div>
````

A final note: no error are visible in the dev tools console

**Comment by Georg-Trixl** [comment]
I think there is no real way, as the People card requires, these managed properties
_**'AccountName', 'FirstName', 'LastName', 'Department', 'JobTitle', 'WorkPhone'**_
The only thing that could work, that you create in your custom list all those columns and map them additionally to the manged properties.

Code reference for that is here
[https://github.com/microsoft-search/pnp-modern-search/blob/master/search-parts/src/services/TemplateService/TemplateService.ts](https://github.com/microsoft-search/pnp-modern-search/blob/master/search-parts/src/services/TemplateService/TemplateService.ts)
starting at the line 481 with private _getPeopleLayoutFields

**Comment by stevebeauge** [comment]
It would be nice to have these managed props configurable in the card field options.

**Comment by Georg-Trixl** [comment]
:-) nice try but, that won't happen, this is stuff for search experts only 💯 
configure the managed properties under
https://**yourtenant**-admin.sharepoint.com/_layouts/15/searchadmin/TA_SearchAdministration.aspx

**Comment by FranckyC** [comment]
@stevebeauge you can create a custom template using the `<pnp-persona-card/>` web component with individual properties mapped to your managed properties:

```html
<pnp-persona-card
	data-item="{{JSONstringify item}}"
	data-image-url="/_layouts/15/userphoto.aspx?size=L&usernamejohn.doe@contoso.com"
	data-text="Primary text"
	data-secondary-text="Secondary Text"
	data-tertiary-text="Tertiary Text"
	data-persona-size="4"
	data-optional-text="Optional Text"
/>
```

**Comment by stevebeauge** [comment]
Thanks @FranckyC. This will probably help.
