### ISSUE TITLE
Is there a way to exclude the default pages from search results ?

### ISSUE THREAD

**Issue by AmitTyagi1** [microsoft-search/pnp-modern-search#282]
**Version used**
3.12.1

**Describe the bug**
Is there a way to exclude the default pages from the search results ?
Like, Default.aspx and calendar.aspx

**To Reproduce**
1. Add Search Box and Search Results web-parts on a page.
2. Type 'default' or 'calendar'
3. Scroll down in the results to find 'default.aspx' or 'calendar.aspx'

**Expected behavior**
The results should not contain these OOTB pages.

**Screenshots**
![image](https://user-images.githubusercontent.com/33560478/82704611-c7a10700-9c2a-11ea-8e59-5e14d2738e66.png)

![image](https://user-images.githubusercontent.com/33560478/82704619-cd96e800-9c2a-11ea-9767-9973f1b3dd50.png)

**Comment by wobba** [comment]
This is a KQL question, not a web part question. The web parts merely wrap a UI on top of the API (and some more). You are free to use KQL syntax to include or exclude any items you want based on file names, content types etc. Some times easy, often hard.

**Comment by AmitTyagi1** [comment]
Thanks. I will try to construct the KQL for this.
