### ISSUE TITLE
Thumbnail (for only xlsx files) issue and Preview pane issue (for all file types) in Edge browser

### ISSUE THREAD

**Issue by AmitTyagi1** [microsoft-search/pnp-modern-search#283]
**Version used**
3.12.1

**Describe the bug**
In edge browser there are two issues which i have observed for the results.
1) For xlsx files, there is no thumbnail shown.
2) No preview is shown for any file-types in preview pane. 

**Screenshots**
![image](https://user-images.githubusercontent.com/33560478/82705844-46973f00-9c2d-11ea-9b1a-027540cf45d8.png)

**Desktop (please complete the following information):**
Microsoft Edge 41.16299.1480.0 (EdgeHTML 16.16299)

**Comment by wobba** [comment]
Excel don't have thumbs as there is no good API for this. Preview fixed in dev branch.

**Comment by AmitTyagi1** [comment]
Thanks @wobba .
As i don't have the DEV environment setup yet. Can you please provide me the changes which i can incorporate in my "Simple List" results layout ?

**Comment by wobba** [comment]
I did't change it in the layout. So you have to wait for the next release if you cannot build.
