### ISSUE TITLE
Accessibility: Need to trap focus in filter dropdowns

### ISSUE THREAD

**Issue by raytri** [microsoft-search/pnp-modern-search#2833]
**Version used**
4.5.4

**Describe the bug**
Keyboard navigation of filter dropdowns is not complete. For instance, with radio/checkbox dropdown:
1. I can tab to the webpart
2. "Enter" focuses the webpart
3. Arrow keys let me move between the checkboxes
4. Space key lets me select an option

So far so good! However:
5. Once in the radio/checkbox group, I cannot reach other parts of the dropdown (combobox, apply/clear buttons, etc.) because using the "tab" key takes me out of the webpart altogether and to the next element on the page.

The individual elements within the dropdown all seem to have the proper focusability/tabindex/etc. So I believe the issue is that focus is not trapped within the dropdown when it opens.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Configure a filter webpart to use either radio buttons or checkboxes to select filter values
2. Starting at the top of the page, hit "Tab" until the filter webpart is focused
3. Hit "Enter" to open the dropdown
4. Use arrow keys to focus an option
5. First indication of bug: Once you are in the radio/checkbox group, you cannot reach any other part of the dropdown via keyboard
6. Hit Space key to select an option
7. Second indication of bug: because you cannot reach any other part of the dropdown via keyboard, there is no way to clear the selected filters
8. Hit "tab" key. You will be taken out of the webpart entirely and to the next focusable element on the page. This indicates that focus is not trapped within the dropdown.

**Expected behavior**
1. Once in a dropdown, hitting "tab" key should take you to the next focusable element WITHIN the dropdown.
2. Once in a dropdown, hitting "Enter" should close the dropdown and return focus to the top of the webpart, just as in step 3 above.

**Screenshots**
![image](https://user-images.githubusercontent.com/1403283/224124210-5af82627-1321-4891-b21c-c7f974689ee9.png)

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**
While this bug calls out the radio/checkbox components, the problem likely manifests in multiple places within the filter webpart -- any place it shows a conditional interface such as a dropdown. Implementing a focus trap should fix those occurrences as well.

**Comment by wobba** [comment]
We don't triage issues on old versions. Please re-test with the latest version and see if the issue is still there. If so, we can re-open this issue.
