### ISSUE TITLE
Markup in Hithighlightedsummary breaks layout template rendering

### ISSUE THREAD

**Issue by corriespondent** [microsoft-search/pnp-modern-search#2847]
**Version used**
4.8.0.5

**Describe the bug**
Not sure if this is a "bug," but I came across some search results where the Hithighlightedsummary contained some markup, and the markup included an opening comment tag but not a closing comment tag, which broke the rendering of the rest of the page. The first screenshot shows the search API response with the Hithighlightedsummary that shows the opening comment tag (<!-- ). The second screenshot shows the search result rendering, and while out of context to protect client data, trust me when I say that the rest of the page didn't render. 

As a fix for now, I edited the layout template directly by adding an empty comment tag directly after the Summary layout slot reference (see third screenshot). This allowed the rest of the results to be rendered (see fourth screenshot).

This feels like a bug because I would expect that the whole page doesn't break, but I also understand that the Hithighlightedsummary needs to preserve markup to allow for highlighting keywords. So this seems more like an issue with Hithighlightedsummary allowing for document metadata that has unencoded markup.

**To Reproduce**
Unfortunately I'm not sure where that markup in the metadata came from, so I'm not sure how to have someone else reproduce this! 

**Expected behavior**
I would expect that the layout doesn't break.

**Screenshots**
![image](https://user-images.githubusercontent.com/23064475/225032173-f8dfae71-46e5-4eb1-9406-d1c3b49080bd.png)
![image](https://user-images.githubusercontent.com/23064475/225033318-3ffccc7f-00a1-40f0-9f4a-1bf40d08a33b.png)
![image](https://user-images.githubusercontent.com/23064475/225033631-a5b8cc9d-f8e9-4fa1-b91a-0e2f2d9eb8c4.png)
![image](https://user-images.githubusercontent.com/23064475/225034900-13f885e0-97e1-4c04-9ebc-c840dac91837.png)

**Desktop (please complete the following information):**
 - Browser: Chrome, Edge

**Comment by wobba** [comment]
Seems like a special case we could handle. Or you can replace `<!--` and `-->` yourself in the template before calling `getSummary`. It's our html sanitizer/DOMPurify which removes content inside the comment most likely. I'll see if this https://stackoverflow.com/questions/53284363/allow-html-comments-in-dompurify solves the issue.

**Comment by wobba** [comment]
Fixed with #2957 in the dev branch
