### ISSUE TITLE
No result when path in query contains space

### ISSUE THREAD

**Issue by Oegl** [microsoft-search/pnp-modern-search#285]
Version used
3.12.1

I configured a search vertical to filter for path, get by url parameter.
![Search issue when url parameter contains space](https://user-images.githubusercontent.com/65904352/82869197-2669c780-9f2e-11ea-81a7-73de151b5148.png)

It seems that no results will be shown when the URL contains a space.
![Search issue when url parameter contains space_002](https://user-images.githubusercontent.com/65904352/82869956-6d0bf180-9f2f-11ea-85fa-6788dde2b9b3.png)

When I try to use the same query in the query builder, results will come up.
![Search issue when url parameter contains space_004](https://user-images.githubusercontent.com/65904352/82869995-7f862b00-9f2f-11ea-96be-ab46b8e4e436.png)

It also works well for URLs without a space.
![Search issue when url parameter contains space_003](https://user-images.githubusercontent.com/65904352/82869966-71380f00-9f2f-11ea-9dcc-8d4bf5063aee.png)

**Comment by wobba** [comment]
Add quotes around it `path:"{something}"`. KQL syntax.

**Comment by Oegl** [comment]
with your hint, it works.
Thanks for that!!!
