### ISSUE TITLE
Search query (people results) no results when adding two many characters of double name 

### ISSUE THREAD

**Issue by ZzyzxIsAlreadyTaken** [microsoft-search/pnp-modern-search#2865]
**Version used**
4.8

**Describe the bug**
Web part is set up for peoplesearch with very little customization.

When searching for for example 
"Stein Tore Surname" I get search results when searching for:
Stei
Stein
"Stein "
Stein T
Stein To
Stein Tor

But when Im searching for "Stein Tore"
![image](https://user-images.githubusercontent.com/18461079/226320589-75b686ba-6047-42e2-b8e8-fe7377dd6e90.png)

If I add 2 characters to surname I get results again. 
This is the same for any other search aswell.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to Search Box web part which is connected to a Search Results web part
2. Enter search query as from the example above

**Expected behavior**
Search results for the person when I write any part of the name, not missing results when adding more letters to the name.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - Edge on PC or Mac (applicable in any browser I guess)

**Additional context**
Tested with multiple people results.

**Comment by kasperbolarsen** [comment]
tip: you might try out the same queries at https://[Tenant].sharepoint.com/search/results.aspx  , I believe that the classic search center will be a better test area for your queries.

**Comment by ZzyzxIsAlreadyTaken** [comment]
If I do the same testing against the classic search center I get no results. :/ 

Any configuration tips for making the search web part work as expected?
