### ISSUE TITLE
PNP Modern Search Web Parts not displaying

### ISSUE THREAD

**Issue by alexvg12** [microsoft-search/pnp-modern-search#2884]
Wonder if anyone has run into this issue. I am on the latest revision of the solution (4.8.0.0).

I added web parts and configured them, tested, published the page, then closed the browser. Next time I returned to the page the Web Parts were not showing, as if they were gone. The only way I was able to bring them back to display was to navigate to another site collection where the older version of the web parts was configured. Those loaded. Now I navigated back to the problematic page and the web parts loaded, too.  This is consistent across browsers (Google Chrome, Edge Chromium) and multiple users.

**Comment by alexvg12** [comment]
I've got v4.8.0.0 installed (most recent production release as of present date)

**Comment by wobba** [comment]
Seems like a caching issue maybe.. same problem today?

**Comment by wobba** [comment]
I would maybe try to remove and re-add the web part app to that site.

**Comment by alexvg12** [comment]
Definitely thought of that, too. Went as far as building a new page from scratch (after having removed the solution from the site and and then having re-added it back). Web parts don't even show up in the web part picker dialog at first. Once I visit another site collection, the web parts there load, then I return to my problematic one and the web parts show up in the picker this time.

**Comment by kasperbolarsen** [comment]
> I've got v4.8.0.0 installed (most recent production release as of present date)

Sorry, I read "was to navigate to another site collection where the older version of the web parts was configured." as you had both v3 and 4.8 on the tenant.

**Comment by wobba** [comment]
@alexvg12 any other spfx parts/extensions installed on that site? If you create a new site, does it work there? Any errors in the console on the problematic site?

**Comment by jhholm** [comment]
I might be getting this reproduced, but I'm not yet sure why. 

One tenant, two different sites, the other one seems to work, the other rarely (every 10th reload). When editing the page, the following API call 
**/_api/web/GetClientSideComponentsByComponentType(componentTypesString='1',supportedHostTypeValue=2)** gives or doesn't give the PnP Modern Search webparts, but other SPFx webparts are returned always. I also noticed the following

1. I can see from the server returned DOM of the page if the webparts are going to show or not, **<link rel="preload" />** for the webpart is missing when the webpart is not showing
2. viewing the page with ?maintenancemode=true, will not show the webparts at all
3. Editing the page will just show blank webparts at their positions
4. Navigating to the "broken site" from another site makes the webparts load correctly

**Comment by jhholm** [comment]
My testing page has 4.8.0 search box and search results webparts in use. I also get page loads where only the search result webpart is working, and in that case the prefetch link for search box webpart is missing.

**Comment by jhholm** [comment]
For me, removing the pnp modern search app with powershell and readding it to the site seems to have fixed the issue.

**Comment by alexvg12** [comment]
What worked for me was spinning up a new site collection, migrating all content there, and turning on the search web parts. Not really sure what was causing the issue on the original site collection.
