### ISSUE TITLE
Display the parent folder name as a column

### ISSUE THREAD

**Issue by aaronrwilson** [microsoft-search/pnp-modern-search#289]
I have multiple use cases where users need to be able to see the parent folder name for each result, displayed as a column in the Search Results (details list) web part.  This would help them easily see where the file is housed within a document library.

Since the Parent Link property already has the full URL of the parent folder, is there a way to split that URL string to only show the segment to the right of the last '/' in the string?  That would effectively show the parent folder name.

This custom helper for Handlebars Expressions seems to do just that:
https://medium.com/@akarshseggemu/how-to-split-and-slice-a-string-in-handlebars-14f7aec5e22c

Can this custom helper please be registered?  Or can someone please clarify how else this can be done?  Thanks!

**Comment by wobba** [comment]
You should be able to combine `split` with `last` probably.

**Comment by bldeveloper** [comment]
sorry for reopning the thread, but i have the same issue as @aaronrwilson but i am unable to register custom handlebar expressions.. Any help will be greatly appreciated!

**Comment by wobba** [comment]
As I said, combine split/last on `ParentLink` using the handlebar expressions available and it should be possible. https://github.com/helpers/handlebars-helpers#split
