### ISSUE TITLE
Updates to Site Pages thumbnails do not get reflected in search results

### ISSUE THREAD

**Issue by erosu-hab** [microsoft-search/pnp-modern-search#2893]
**Version used**
4.8

**Describe the bug**
After the initial setup of a page, any subsequent updates to the thumbnail do not get reflected in search results.

**To Reproduce**
Detailed steps to reproduce the behavior:
1.	Create a new Site Page, say “News-with-thumbnail.aspx”
2.	Set the header to Plain and set the thumbnail to an image of your choice.
3.	Publish the page.
4.	Create another Site Page, say "Search.aspx"
5.	Add the PnP Search results web part.
6.	Select the SharePoint as data source.
8.	Set query template such that the page created in step 1 gets displayed in the results. For example: Path:https://tenant.sharepoint.com/sites/test/SitePages/News-with-thumbnail.aspx
9.	Select the default Cards display template
10.	Save and publish Search.aspx
11.	News-with-thumbnail.aspx should display the thumbnail set in step 1.
12.	Go to News-with-thumbnail.aspx and set the thumbnail to a different image.
13.	Publish the page.
14.	View Search.aspx page
15.	Search results should display the updated thumbnail. Instead, the old thumbnail gets displayed.
16.	View the OOTB Microsoft search results page.
17.	News-with-thumbnail.aspx shows the correct thumbnail on this page.

**Expected behavior**
When the thumbnail gets updated for a page, PnP search results displays the newly set thumbnail.

**Desktop (please complete the following information):**
 - Chrome, Edge

**Additional context**
The PreviewImageUrl slot is mapped to AutoPreviewImageUrl.
To see the updated thumbnails, I needed to either clear the bowser cache, browse incognito or browse in a different browser.

We’d like our users to see the updated thumbnails, rather than stale content. 
Regardless if this is something that can or will be fixed in PnP Modern Search in the future, we'd still like to have an interim solution. 
Do you have any suggestions on how to overcome this behaviour? We thought of appending last modified time to PreviewImageUrl, in the display template, to force a cache refresh, but we’re not sure if this would be the correct fix.

Thank you!

**Comment by erosu-hab** [comment]
We switched to using PictureThumbnailURL managed property instead of AutoPreviewImageUrl. PictureThumbnailURL seems to be working as expected.

**Comment by wobba** [comment]
Added support to prefer PictureThumbnailURL if present in the data
