### ISSUE TITLE
Search Box doesn't work - when enter a search-criteria nothing happens

### ISSUE THREAD

**Issue by sam888k12** [microsoft-search/pnp-modern-search#2895]
I am using SharePoint online with a PnP-Searchbox, PnP-Search- Filters and PnP-Search Results. When I type a search string in the Search box nothing happens.  Right now I have 6 docs in my test library with display automatically in the search results before actually searching (that's another issue) but when I type in a unique word that should return one doc nothing changes.  I have followed several tutorials online and connected everything but I'm not sure why the search itself is not working.

**Comment by kasperbolarsen** [comment]
Please share your query, as it must contain {searchTerms} in order to work. Also please check that the results part is connected to the search box on "page" 3

**Comment by sam888k12** [comment]
This is my query Path:"https://xxx.sharepoint.com/sites/xxx/xxx/Test%20xxx/" AND IsDocument:"True" and my results part is connected on page 3.  I do get docs in the search results.  They just don't ever change no matter what I type into the search box.

**Comment by kasperbolarsen** [comment]
As expected you are missing the {searchTerms} in the query.

When you add a new result web part it is in the query all ready,  you must have deleted it by accident.

**Comment by sam888k12** [comment]
Thank you - I added back the search terms and it works however only when I remove the library name from the query.  This is the working query: {searchTerms} Path:"https://xxx.sharepoint.com/sites/xxx/xxx/" AND IsDocument:"True".  If I add this to the end: /Test%20DOBS/ it no longer returns results.  I know this is a different issue but if you have a quick fix I would much appreciate it.  If not I will go searching.  :-)  Thanks again!

**Comment by kasperbolarsen** [comment]
Does Path:"https://xxx.sharepoint.com/sites/xxx/xxx/*" solve your issue?
AfAIK Path: should always end with an *

**Comment by sam888k12** [comment]
YES!!!!  Thank you very much.  Have a great rest of your evening!

**Comment by kasperbolarsen** [comment]
issue resolved
