### ISSUE TITLE
Configure search verticals to other page

### ISSUE THREAD

**Issue by davemehr** [microsoft-search/pnp-modern-search#290]
**Version used**
3.12.1 - newest version

**Describe the bug**
I use the search verticals webpart. Well, i would like to link to an other page in the search verticals configuration. I would like to use the same search query. But i can't find the right configuration.

**To Reproduce**
1. On search page i use search box, search verticals, search results, search refiners (all works)
2. enter your search term
3. use search verticals to link to an other page
4. nothing do on the linked page

**Expected behavior**
The linked page use the same search term from the source page.

What is the correct query template configuration on the source page's search verticals and the configuration on the target page that i can use the same search query)?

**Additional context**
I think, it's not a "bug", but i can't found the right configuration for this scenario. - thx for help

**Comment by FranckyC** [comment]
Hi @davemehr , in your vertical URL you can specify the tokens `{SearchBoxQuery}` or `{searchTerms}` like this:

`https://mypage?q={SearchBoxQuery}`

Then, in your target page, in the search box use a dynamic value grabbing the `q` query string parameter.

**Comment by davemehr** [comment]
Thank you @FranckyC  , the full link with the page and the token was the key ;)
