### ISSUE TITLE
People Search: Issue with pagination in search results webpart

### ISSUE THREAD

**Issue by harshasyamala** [microsoft-search/pnp-modern-search#2905]
When creating a people search results pages using Microsoft Search as data source, facing issue with pagination. After a bit of digging, seems the issue is with Search API. Is this a known issue ?

When paging is enabled on webpart settings, irrespective of (actual) total number of people returned, only 1 page is visible in navigation.

### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/2904

<div type='discussions-op-text'>

<sup>Originally posted by **harshasyamala** April 12, 2023</sup>
MS Graph API : People Search endpoint is returning incorrect values in "Total" field of the response. This is causing a problem when Paging is enabled on PnP Modern Search webpart - people results use cases. 

For example, when searching for people (using graph explorer) for 

**Case 1:** keyword "test", (without specifying any specific size) the total number of people returned are 7
-------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/28626579/231419286-36865360-e602-41a7-a715-d3576ad8c3a5.png)

**Case 2:** keyword "test", (with specifying "3" size) to get 3 results per page. Issue is the "total" changed to 3 instead of actual 7. 
---------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/28626579/231419475-5596c96b-fd5e-469c-99ec-191d2ba0e122.png)

Question here is, is this an expected behaviour or am I missing something here ? </div>

**Comment by kasperbolarsen** [comment]
Would you be able to verify that you get the same results when using the Graph explorer?

**Comment by wobba** [comment]
Closing as API related and you should rather log this with the Graph API.
