### ISSUE TITLE
Refine

### ISSUE THREAD

**Issue by PikeSal** [microsoft-search/pnp-modern-search#2908]
The refinement  operator to use between filters seems to over ride the filters on the search results page. Is this by design? Where the operator between filters trumps the filters on the search result page.

Operator to use between filters - Selected AND
![image](https://user-images.githubusercontent.com/73570781/231852481-8bb01056-7472-4b24-b467-33cccdc9eb63.png)

Refinement values -  Selected OR
![image](https://user-images.githubusercontent.com/73570781/231852697-204de3ce-220e-46f9-b36c-078b47dbd106.png)

**Describe the solution you'd like**

I had to change the operator between filters to AND since OR was increasing the result count substantially since there are other fields like File Type which have a very broad search scope and they impact the result count negatively (increases the result count). 

Example 
Author 1 = Jane OR  Author 2 = Jane = 525 items
Author 1 = Jane  OR Author 2 = Jane OR FileType = doc = 19677 items

**Describe alternatives you've considered**
I want to search for the Author name in Author 1 and Author 2 fields, without increasing the search result count substantially.

**Comment by wobba** [comment]
Can you explain a bit better what you try to accomplish, and what do you mean by "override the filters on the search result page"?

**Comment by PikeSal** [comment]
I am trying to filter content by Author's name in two columns (Author1 and Author2).
![image](https://user-images.githubusercontent.com/73570781/232856490-e72673bb-d460-444c-94ab-ae1da5bebe4c.png)


If the operator to use between filters is set to AND I get 0 results, however, if set to OR I get 523 results. The reason I am using AND is because we have third column called File Type which increases the results to 19580 if the operator to use between filters is set to OR.

Operator to use between filters
![image](https://user-images.githubusercontent.com/73570781/232856752-d71dd542-7b0c-4557-8b17-4c8a3afa04be.png)

![image](https://user-images.githubusercontent.com/73570781/232856828-cb0db396-d1f8-43db-bbc3-d4d8952cadb4.png)

**Comment by wobba** [comment]
So you want:

(Author 1 = Jane OR Author 2 = Jane) **AND** FileType = doc

Today that is not possible.

**Comment by PikeSal** [comment]
Thanks for confirming.
