### ISSUE TITLE
Question: "[Feature] Provide defaut selected filters using an URL parameter" is Done?

### ISSUE THREAD

**Issue by luismanez** [microsoft-search/pnp-modern-search#291]
In the backlog, I can see this feature marked as Done [[Feature] Provide defaut selected filters using an URL parameter](https://github.com/microsoft-search/pnp-modern-search/projects/1#card-33171873)

However, I don´t see any documentation or sample about how to pass Filters in the URL. 
What´s the format, could you provide any sample?
Thanks!

**Comment by FranckyC** [comment]
Maybe this could help https://microsoft-search.github.io/pnp-modern-search/search-parts/search-results/#filters-deep-links

**Comment by luismanez** [comment]
Oh! so ashamed I didn´t see it before!!!... thanks.
