### ISSUE TITLE
Pnp Search thtowing error: [HTTP]:500 - [CorrelationId]:ba4caca0-10b4-6000-6637-908b5d6eb7d0 [Version]:16.0.0.23605

### ISSUE THREAD

**Issue by AndyOppelaar** [microsoft-search/pnp-modern-search#2925]
Since today I am getting this error on PnP Search version 4.8.0.0 on every site when adding a Search results box
[HTTP]:500 - [CorrelationId]:ba4caca0-10b4-6000-6637-908b5d6eb7d0 [Version]:16.0.0.23605

![image](https://user-images.githubusercontent.com/131661619/233959782-6347ee55-da89-4b28-aa78-a3bd86ac99c4.png)

**Comment by kasperbolarsen** [comment]
general outage
![image](https://user-images.githubusercontent.com/20593570/233974807-9b2705fd-0d30-45ef-bba2-9e9f77e30d98.png)

**Comment by AndyOppelaar** [comment]
Ah, thanks. I'll wait :-)

**Comment by kasperbolarsen** [comment]
The last update seems to be from 01pm UTC. If you have access to a tenant then see https://admin.microsoft.com/Adminportal/Home?source=applauncher#/servicehealth/:/alerts/MO545600
