### ISSUE TITLE
componentDidMount and componentDidUpdate events getting fired on page refresh/on page reload  

### ISSUE THREAD

**Issue by spo365** [microsoft-search/pnp-modern-search#293]
**Version used**
Ex: 3.7

**Describe the bug**
componentDidMount and componentDidUpdate events getting fired on page refresh/on page reload  
Complete scenario:
using query string as below
:https://xyz.sharepoint.com/sites/test/SitePages/Search-Results-Page.aspx?q=test&chkBoxStatus=false
- search box on the same page is using query string as data source
- search results on the same page is using search box as data source
- code segment in search results 
 
component did mount -----
 
<div>    public async componentDidMount() {
 
                       let initialCheckBoxValue:boolean;
                        var urlParams:any = new UrlQueryParameterCollection(window.location.href);
                        /* query string parameter chkBoxStatus used to handle title or content based search
                        chkBoxStatus = true means search is based on title only
                        chkBoxStatus = false means search is based on content */
                        if(urlParams.getValue("chkBoxStatus".toUpperCase()))
                        {
                          initialCheckBoxValue = JSON.parse(decodeURIComponent(urlParams.getValue('chkBoxStatus'.toUpperCase())));
                          if(initialCheckBoxValue)
                          {
                            this.props.searchService.queryTemplate = "title:{searchTerms}";
                          }
                          else{
                                this.props.searchService.queryTemplate = "{searchTerms}";
                          }
                        }
                        this.setState({
                            results: searchResults,
                            areResultsLoading: false
                        });
 
    }</div>
 
 
<div> public async componentDidUpdate(prevProps: ISearchResultsContainerProps) {
     
            if(this.state.searchCheckBoxStatus ){
                console.log("if");
                this.props.searchService.queryTemplate = "title:{searchTerms}";
            }
            else {
                console.log("else");
                this.props.searchService.queryTemplate = "{searchTerms}";
            }
}
  --- Issue ---</div>
 
Both events getting fired on page refresh/on page reload  
 
 

**To Reproduce**
1. Go to search result page using query string'
2. if we refresh page 10 time out 8 it load correct but 2 times it calls componentDidMount() and componentDidUpdate due to that i display different results 
 
**Expected behavior**
on page load or refresh search result should always be same.
**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by FranckyC** [comment]
Hi @spo365, it seems to be custom code here that we don't support. Anyway to answer your question, it appears to be the normal React behavior as I can see in your code...

The `componentDidMount` method is called after the initial render. Inside of it you call `this.setState()` triggering the `componentDidUpdate`. 

This issue is definitely not related to the solution.

**Comment by spo365** [comment]
thanks sorry
