### ISSUE TITLE
PnP -Search Filter - some values not visible in filter choice pane

### ISSUE THREAD

**Issue by PikeSal** [microsoft-search/pnp-modern-search#2931]
**Version used**
Ex: 4.8

**Describe the bug**
Since 2 weeks, we are getting "No results found" when we try to lookup for a couple of Author names in the Search filter search bar, the names are also not visible in the list of choices. However, if i search by Author 1:AuthorName in the search box, i can see the Author's name in the filter pane. I tried re-indexing the document libraries which made no difference.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. No results found when i search by the Author name in the Author 1 filter
![image](https://user-images.githubusercontent.com/73570781/234292416-f8bac560-38cf-4d23-8290-c3d2f5dfb6ac.png)

2. Author name also not visible in the list of Authors
3. I can see the Author's name in the filter pane when searching by Author 1:AuthorName in the search box.
![image](https://user-images.githubusercontent.com/73570781/234294227-ec9c7837-f374-48f0-a912-8b090ab2fc02.png)

4. The refinement values are mapped to RefineableString fields.
5. Tested as SharePoint admin, to rule out issue with permissions
6. Confirming items Tagged with Authors names in the document libraries.

**Expected behavior**
Ability to search and see all authors in the Authors filter selection, currently not all Authors are visible or searchable in the Search Filters selection. This issue surfaced 2 weeks ago.

**Screenshots**
Above

**Desktop (please complete the following information):**
 - Browsers tested [chrome, Edge, Firefox]

**Additional context**

**Comment by wobba** [comment]
Can you repro in OOB search? Modern or classic? Or in search query tool? And using SharePoint admin is not smart in terms of results as an admin don't have implicit ACL's on search results.

Want to rule out if it's an API issue or filter webpart sending the wrong query.

**Comment by wobba** [comment]
Because the number you enter is the number to retrieve technically.
