### ISSUE TITLE
SharePoint PnP search Search Results Selected Properties Loading issue.

### ISSUE THREAD

**Issue by Soubhagya100** [microsoft-search/pnp-modern-search#2944]
Hi Team,

We are facing the selected Properties Loading issue. and below are the details 

Version used
Ex: 4.3

Describe the bug
The PnP search results web part help us to choose/specify the properties for search results. In our case when we are trying to check the available properties to select, the available properties list is not loading but the loading icon is showing from long time. Hence we are unable to see the available properties and select those properties later.

To Reproduce
Detailed steps to reproduce the behavior:
1.Go to edit the Page (Page must be using the PnP search web part)
2.Go to PnP search Results web part and edit that web part, will get the right side pop up for this one.
3.Choose the available data source as SharePoint search
4.In the SharePoint search query search given the input as the {searchTerms} ContentType:"Bible Document" Path: {site}
5.Choose the result source id with the available options in the dropdown.
6. Choose the selected properties with the available properties. but here we not getting any values in the dropdown of=d the Selected properties.

Expected behavior 
The selected properties should display the available properties. so that we can choose form the available properties.

Screenshots
![search error 1](https://user-images.githubusercontent.com/132087202/235607269-44afcda4-10db-4fcd-8439-2ab197088fc7.PNG)
![search error2](https://user-images.githubusercontent.com/132087202/235607305-976606e7-ed63-4706-ad93-b979a34c8cc9.PNG)

Desktop (please complete the following information):

Browser [e.g. chrome, safari] : edge, chrome

Team , kindly help for this one, Please let uk know if we need to use the latest version only or this version can have the resolution.

**Comment by kasperbolarsen** [comment]
We can't help with previous versions,  so I'll suggest that you update to the current release version, 4.8

**Comment by Soubhagya100** [comment]
ok thank you. will update to the current release version 4.8.

**Comment by Soubhagya100** [comment]
Please let us know would we be able to role the update out to all SharePoint sites using the pnp webparts?
 It would be grateful if we get the link for the upgrade to the latest version.

Thanks & Regards,
Soubhagya M

**Comment by wobba** [comment]
This is an issue as the API we use is not a supported nor reliable one. Workaround is to put your cursor in the box and type the property you want added manually, then hit ENTER. Then it will appear in the list of properties.

**Comment by karthi2488** [comment]
Hello Team,
Is there a fix available for this issue in the latest version of the webpart or not? since the version 4.11.1.0 also having this issue.
SharePoint PnP search Results Selected Properties Loading issue.

**Comment by wobba** [comment]
The web part cannot solve API issues, and fetching all properties is not a real API, and never has been. Workaround is to type in properties manually instead of picking.
