### ISSUE TITLE
Thumbnails do not work for files stored in subsites

### ISSUE THREAD

**Issue by maru-sama** [microsoft-search/pnp-modern-search#296]
**Version used**
3.13.0.0

**Describe the bug**
If you have a site collection with subsites, the thumbnail is not working if the files are stored inside a subsite.

**To Reproduce**
Create a new site collection including a subsite. Setup a search page on the main site to search the complete site collection. Store a document in a library in the subsite.
**Expected behavior**
A thumbnail of the document should be shown.

**Additional context**
The issues seems to be that the code does not expect a subsite for the thumbnail url and always creates a link like..
https://tenant.sharepoint.com/sites/sitecollection/_api/v2.0/sites/c42f662e-05a0-4365-8cb1-55a601b5934f/lists/f6d8c891-a944-432a-b9c6-fc1a38c98912/items/047dc110-3370-4779-8747-e003a0b84af8/driveItem/thumbnails/0/large/content?preferNoRedirect=true

In this case the error you will get is..
{"error":{"code":"itemNotFound","message":"The specified list was not found"}}

This is correct since the list is NOT in the main site but in a subsite. The correct url in this case would be...

https://tenant.sharepoint.com/sites/sitecollection/_api/v2.0/sites/c42f662e-05a0-4365-8cb1-55a601b5934f/ **sites/idofsubsite/** lists/f6d8c891-a944-432a-b9c6-fc1a38c98912/items/047dc110-3370-4779-8747-e003a0b84af8/driveItem/thumbnails/0/large/content?preferNoRedirect=true

Please note, clicking on the file opens the preview just fine.

**Comment by wobba** [comment]
Thank you (and you shouldn't use subsites 😉)

**Comment by wobba** [comment]
Fixed, and correct notation is `/sites/<siteid>,<webid>/lists/<listid>`. I just hadn't bothered to include it before :)
