### ISSUE TITLE
Update extensibility documentation with the correct SPFx version

### ISSUE THREAD

**Issue by till-llit** [microsoft-search/pnp-modern-search#2974]
documentation update required.

according to  https://github.com/microsoft-search/pnp-modern-search/releases

`Note 1 This version uses SPFx v1.15.2. Any extensions you have must be upgraded and rebuilt to SPFx v1.15.2 to continue to work.`

this is in conflict with the documentation https://microsoft-search.github.io/pnp-modern-search/extensibility/#prerequistes

```
SPFx version

The SPFx library project must use the same SPFx version as the main solution (currently 1.12.1). 
Owherwise you may face issues at build time. 
See [GitHub issue #1893](https://github.com/microsoft-search/pnp-modern-search/issues/1893)
```

additional question: is exact spfx version 1.15.2 required for extensions or >= 1.15.2 ?

**Comment by wobba** [comment]
Updated in the next doc publish
