### ISSUE TITLE
#Search Verticals Navigation  - more like a suggestion

### ISSUE THREAD

**Issue by pravin080317** [microsoft-search/pnp-modern-search#298]
we have configured search verticals like below and also configured the search result blocks on ALL section of the vertical page in search results. I have a requirement to navigate to other search vertical section when i click on more link. can you please assist me how to achieve this.

for example, in the below image when i click on more hyperlink, it should navigate to application section of the search verticals.  

![image](https://user-images.githubusercontent.com/35328578/83629422-adb2dd00-a5b7-11ea-9951-9e85d558d646.png)

![image](https://user-images.githubusercontent.com/35328578/83629788-5d884a80-a5b8-11ea-88f5-35f50f4a925e.png)

**Comment by FranckyC** [comment]
Hi @pravin080317, so basically you would like to navigate programmatically to a search vertical from a control inside your template? Am I right? It could be possible creating a custom web component, then programmatically invoke the click() event to the DOM element representing your selected vertical. It would be hacky but possible.
