### ISSUE TITLE
SearchResults WebPart keeps losing connection to SearchBox

### ISSUE THREAD

**Issue by Somu76** [microsoft-search/pnp-modern-search#299]
**Version used**
3.13

**Describe the bug**
The Search Results webpart does not show any results, after adding a search box WP and connecting to it. No other customizations. When we go to Configure the Search Results webpart, it does not persist the 'Connect to Source' settings, and shows a blank search query keywords option. How can we persist the 'Connect to Source' option?
This happens even if I hit Back from the 3rd page :(

**To Reproduce**
1. New SitePage
2. Add a SearchBox WP
3. Add a Search Results WP
4. Configure Search Results WP -> Chose to Connect to Source, and select the Search Box/SearchQuery, click Next.
5. Click Back, and the previous selection goes away :(

**Expected behavior**
I would hope to see the connection persist.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Somu76** [comment]
I found some more information here that can possibly shed more light on this... 

When chosing the 'Connect to Source' option, if I select PageEnvironment/Search/SearchQuery first, and then switching to SearchBox/SearchQuery (before we go to the next page), the connection seems to stick.
If I then try to chose 'PageEnvironment' again to play around, we end up getting an error like below:
![image](https://user-images.githubusercontent.com/12059785/83675571-42610f00-a5a7-11ea-9c60-017c5b5a4b6e.png)
I could only remove the connection and start from scratch to make it go away.

**Comment by MakingThingsWorkToronto** [comment]
Please try setting the connection in Edge and let me know if that works. I’ve seen this issue intermittently and believe it’s a tenant / site collection specific SpFx release issue. Also try upgrading to the most recent version :)

**Comment by Somu76** [comment]
Thanks. I thought I was using the latest version (3.13), and I am using the latest Edge Chromium browser. It reproduces in multiple site collections in my tenant and in my customer’s tenant... will try other browsers and tenants tomorrow...



Sent from my iPhone

On Jun 4, 2020, at 10:43 PM, Making Things Work <notifications@github.com> wrote:

﻿

Please try setting the connection in Edge and let me know if that works. I’ve seen this issue intermittently and believe it’s a tenant / site collection specific SpFx release issue. Also try upgrading to the most recent version :)

**Comment by MakingThingsWorkToronto** [comment]
Sorry I should have been more clear. See if you can launch the old non-chromium edge version to connect the WP (if you still have it)...

**Comment by wobba** [comment]
If you can get details this is due to SharePoint/SPFx, and not how we pick the connection in the web parts you can either log an issue at sp-dev-docs, or I can try to escalate.

**Comment by JimmyHang** [comment]
Hi @wobba , experiencing the same issue in multiple tenants with version 3.13, it seems that even if the config stick, somehow results are not connected correctly between the searchbox and results webpart.

This is the results when I'm searching the word "reports"

![image](https://user-images.githubusercontent.com/18226765/85121541-3cb12d80-b225-11ea-89c0-c6445bee977c.png)

And I'm getting the same searching for "sharepoint"

![image](https://user-images.githubusercontent.com/18226765/85121596-5783a200-b225-11ea-803c-d7e6c75c19fc.png)

**Comment by JimmyHang** [comment]
I downgraded to version 3.10, connections seems stable, but search resuslt webpart still displays the same results no matter what i search for????

**Comment by JimmyHang** [comment]
After some more testing, I found out that the culprit is the "Sear Vertical" webpart, if I remove it, then my Search Box and Search Results, behaves the way they should...more testing then...;)

**Comment by wobba** [comment]
Good find @JimmyHang, and could be some connection race conditions here.

**Comment by gmparky** [comment]
I am seeing a similar problem, the search box doesn't seem to be passing the query string to the results web part. I can get the results web part to work as expect when not connected but it shows no results as soon as I connect the search box. I have updated to the latest build 3.14.1

**Comment by wobba** [comment]
@gmparky log a separate issue as this is about it working sometimes. And include the steps on how you connect and setup the webparts.

**Comment by DJS-ECM** [comment]
This is happening with my SharePoint sites as well.  The Search Results doesn't seem to retain its connection to the search box. I know that the query and the result source are fine.  Nothing happens when I use the search box.  And when I look at the search results connection, it is always empty, even though I repeatedly add the information.

**Comment by wobba** [comment]
@DJS-ECM seems related to #325 in your case.

**Comment by MartinSpitz** [comment]
> This is happening with my SharePoint sites as well. The Search Results doesn't seem to retain its connection to the search box. I know that the query and the result source are fine. Nothing happens when I use the search box. And when I look at the search results connection, it is always empty, even though I repeatedly add the information.

Seeing the same issue on different tenants. Both with 3.13 and 3.14.1

**Comment by DJS-ECM** [comment]
This happens to me as well.  It doesn't matter what browser I use.

**Comment by wobba** [comment]
@DJS-ECM any errors in the console when you try to add the connection from search wp to searchbox wp?

**Comment by DJS-ECM** [comment]
Hello, nothing turns up in the console.  There are 0 runtime errors over the past 4 days and I tried configuring the search results web part from two different browsers this morning.  Tank you.

Donna Steinwand | She/Her | Enterprise Content Management | Land O’Lakes, Inc.
4001 Lexington Avenue North | Mail Stop IT Building A | Arden Hills, MN 55126
P 651.375.2423 | C 651.233.6184 | djsteinwand@landolakes.com

FEEDING HUMAN PROGRESS
landolakesinc.com<https://www.landolakesinc.com/> | LinkedIn<https://www.linkedin.com/company/landolakesinc/> | Facebook<https://www.facebook.com/LandOLakesInc> | Twitter<https://twitter.com/landolakesinc> | Instagram<https://www.instagram.com/landolakesinc/>

**Comment by FranckyC** [comment]
What if you try to set "*" as query keywords first in the Search Results WP settings and then retry the connection to the search box?

![image](https://user-images.githubusercontent.com/5659122/86825072-f51c0580-c05c-11ea-8079-9fa8f1f9a5a4.png)

**Comment by DJS-ECM** [comment]
It looks like the query of * works, because the correct number of documents is returned according to what I defined as the search result source.

However, the query in the search box does nothing.  When I look at the search results web part configuration, there is no information saved in the “Connect to source” where I would specify the search box.

Thanks.

Donna Steinwand | She/Her | Enterprise Content Management | Land O’Lakes, Inc.
4001 Lexington Avenue North | Mail Stop IT Building A | Arden Hills, MN 55126
P 651.375.2423 | C 651.233.6184 | djsteinwand@landolakes.com

FEEDING HUMAN PROGRESS
landolakesinc.com<https://www.landolakesinc.com/> | LinkedIn<https://www.linkedin.com/company/landolakesinc/> | Facebook<https://www.facebook.com/LandOLakesInc> | Twitter<https://twitter.com/landolakesinc> | Instagram<https://www.instagram.com/landolakesinc/>

**Comment by DJS-ECM** [comment]
> It looks like the query of * works, because the correct number of documents is returned according to what I defined as the search result source. However, the query in the search box does nothing. When I look at the search results web part configuration, there is no information saved in the “Connect to source” where I would specify the search box.

We are using version 

3.14.1.0
--

**Comment by ofreytag** [comment]
> What if you try to set "*" as query keywords first in the Search Results WP settings and then retry the connection to the search box?
> 
> ![image](https://user-images.githubusercontent.com/5659122/86825072-f51c0580-c05c-11ea-8079-9fa8f1f9a5a4.png)

We have the same issue like the other people here and if we follow your advice it works.

**Comment by wobba** [comment]
Still an issue?

**Comment by DJS-ECM** [comment]
We upgraded to the most recent version and that seems to have fixed the issue.

Thank you.

Donna Steinwand | She/Her | Collaboration Services | Land O’Lakes, Inc.
4001 Lexington Avenue North | Mail Stop IT Building A | Arden Hills, MN 55126
P 651.375.2423 | C 651.233.6184 | djsteinwand@landolakes.com

FEEDING HUMAN PROGRESS
landolakesinc.com<https://www.landolakesinc.com/> | LinkedIn<https://www.linkedin.com/company/landolakesinc/> | Facebook<https://www.facebook.com/LandOLakesInc> | Twitter<https://twitter.com/landolakesinc> | Instagram<https://www.instagram.com/landolakesinc/>
