### ISSUE TITLE
Search Results not loading in Workbench

### ISSUE THREAD

**Issue by khnumtemu** [microsoft-search/pnp-modern-search#30]
<img width="1179" alt="Screen Shot 2019-12-05 at 3 33 35 PM" src="https://user-images.githubusercontent.com/29149559/70280019-d414ce80-1774-11ea-8fe5-b133e4c3cd10.png">

Steps I took:

1. - Downloaded zip file
2. - Added to VSCode
3. - npm install
4. - gulp serve
5. - added to page

**Comment by FranckyC** [comment]
Should be resolved by #34. Feel free to checkout and test the develop branch.

**Comment by khnumtemu** [comment]
Hey Franck,

Thanks for getting back to me. I'm not very good with Git. How do I get these changes from the Develop Branch?

Thanks,

Kevin
________________________________
