### ISSUE TITLE
Lack of documentation regarding preconfiguring filter from the URL

### ISSUE THREAD

**Issue by stevebeauge** [microsoft-search/pnp-modern-search#300]
**Is your feature request related to a problem? Please describe.**

Filters webpart seems to be able to be preconfigured with a specific [filter query parameter](https://github.com/microsoft-search/pnp-modern-search/blob/35ae772b6c21b3bdda25bb5b2d153a17ac9d02fe/search-parts/src/helpers/SearchHelper.ts#L60).

However, there's no documentation of the format in the [web part documentation](https://microsoft-search.github.io/pnp-modern-search/search-parts/search-filters/) (or at least I didn't find it).

**Describe the solution you'd like**

An explanation with some sample in the doc would be appreciated.

**Describe alternatives you've considered**

**Additional context**

**Comment by stevebeauge** [comment]
found here : https://microsoft-search.github.io/pnp-modern-search/search-parts/search-results/#how-default-selected-values-are-set-in-the-search-filters-wp. Maybe a link in the filter result webpart could help to find it.

**Comment by FranckyC** [comment]
Thanks @stevebeauge , you're right, I will add a link in the filter webpart page.
