### ISSUE TITLE
Date formatting in filter web part - possible repaint issue

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#3000]
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/2982

<div type='discussions-op-text'>

<sup>Originally posted by **upcreek** May 18, 2023</sup>
Hi all, I've been working on formatting dates in the search web parts..so far I've been able to format in the results web part and part of the filter web part using some simple handlebars edits in the templates. But one part of the filter web part is eluding me:

![image](https://github.com/microsoft-search/pnp-modern-search/assets/37710523/eea2ab22-0a23-48f5-98d6-9b351529d725)

As the page is loading I can see the date is formatted how I want it but the reverts to the full format when the page finishes loading.

Anyone know how I can format this date? I'm using the checkbox filter template. Is it possible to get that deep into the template or do I need to do something completely custom? Thanks.</div>

**Comment by kasperbolarsen** [comment]
@upcreek Is it on purpose that you are using a RefinableString rather than a RefinableDate ?

**Comment by upcreek** [comment]
> @upcreek Is it on purpose that you are using a RefinableString rather than a RefinableDate ?

Hello @kasperbolarsen , yes I'd like a pick list of single dates, rather than date ranges. RefinableDate filters always render as ranges of some kind, whereas RefinableString just shows the single date.

**Comment by wobba** [comment]
You will get an awful lot of values as the strings include seconds.

**Comment by upcreek** [comment]
> You will get an awful lot of values as the strings include seconds.

I would have thought so too but it doesn't seem to be the case? Maybe my testing set is too small just yet. Also the date column I'm filtering on is set to date only, no time, so theoretically the time portion should be all the same in the backend.

**Comment by wobba** [comment]
If it's date only that reduces it indeed as the time portion is equal for all.

**Comment by wobba** [comment]
Closing this and leaving it at the discussion. Investing time on a modified filter value and passing that downstream does not seem worth the effort.
