### ISSUE TITLE
Feature request : maintain state of the current search in the url / mimic legacy "Query Groups" behavior

### ISSUE THREAD

**Issue by stevebeauge** [microsoft-search/pnp-modern-search#301]
**Is your feature request related to a problem? Please describe.**
One of the great feature on the classic search web parts was to dynamically update URL regarding the current search : refiners, search query, etc...

The immediate benefits is that you can bookmark or send to a specific search setup.

The current implementation of the modern search web parts permits some preconfiguration from url, any subsequent action won't update the url. Thus it disable ability to share a search page with its configuration.

**Describe the solution you'd like**
It would be nice to maintain the search configuration in url parameter (as hash parameter?).

Thinking a bit further, I strongly believe the concept of query group of the legacy web part was great. It allowed a clear separation, of multiple combination of search web parts in the page (ultimately, it was possible to have in the same page 2 search box, 2 refiners wp, 2 search results, ....).
While reusing search results from another WP wasn't very useful in most cases, the usage of query groups helped a lot in complex pages.

I'd don't have any idea of how you plan to build the V4 mentionned in a few other places, but I strongly believe in the concept of query groups.

**Describe alternatives you've considered**

**Additional context**

**Comment by wobba** [comment]
Copy/paste a search link is an edge case. Linking to a preset param set makes sense, and I think you can accomplish this by using different query params per web part. And agree the feature was a good one and we'll keep the idea.

**Comment by wobba** [comment]
Filters are persisted in the v4 URL
