### ISSUE TITLE
German Translation planned?

### ISSUE THREAD

**Issue by ShaneBIS** [microsoft-search/pnp-modern-search#303]
Hi Team,
I am asking you in regard of the Online Consulting AG as we want to use this PnP search solution for our German customers. 
So my question is if a German translation is planned and if not if it would be possible for our company to overtake the translation and what would be the framework/requirements to integrate the German translation into the project?

**Comment by wobba** [comment]
No plans, so any translation of strings of the files in the `loc` folder for German would be appreciated as a PR :)
