### ISSUE TITLE
getPreviewSrc item Handlebar not showing Excel or image files

### ISSUE THREAD

**Issue by PeterVos111** [microsoft-search/pnp-modern-search#304]
**Version used**
Ex: 3.7

**Describe the bug**
I am using the {{getPreviewSrc item}} handlebar in de custom Template Lay-out. It shows all thumbnails correctly, except for Excel and Image files. A previous issue with the Excel Thumb said that Thumbs for Excel files are not available due to not having the right API. Does the same go for images?

**To Reproduce**
1. Open modern search
2. select 'custom template'
3. Add the handlebar {{getPreviewSrc item}} to make thumbnails show
4. See that PDF, and word files show correctly, but Excel and images don't

**Expected behavior**
Thumbnails for Excel and images

**Screenshots**
![image](https://user-images.githubusercontent.com/46716165/84004122-5e7bfc00-a96b-11ea-9075-5a34fade454c.png)

**Desktop (please complete the following information):**
 - Chome, Edge, IE

**Comment by wobba** [comment]
Excel doesn't have thumbs. Images should work fine but seems there is a bug and it doesn't trigger.

**Comment by wobba** [comment]
Fixed the bug.

**Comment by PeterVos111** [comment]
I can wait untill the June release, thanks for the fix!

**Comment by FranckyC** [comment]
Then this will be available in the next release ;)
