### ISSUE TITLE
If more than five refinement values are displayed, show apply button on top as well. -- For files as well

### ISSUE THREAD

**Issue by Georg-Trixl** [microsoft-search/pnp-modern-search#305]
**Version used**
3.13.0

**Describe the bug**
The Feature : "If more than five refinement values are displayed, show apply button on top as well. " PR #284
Works only for **Multi-value refinement item** but not for **Multiple file type**.
The 2 filter types are working on UI side very similar, but therefore the multiple file type should have also an apply on top. (At least I was expecting that behaviour, so I set it up as bug report.) 

**To Reproduce**
Create new refiner select _Filter managed property_ **FileType** and use  **Multiple file type** as _Refiner template_

**Expected behavior**
When **Multiple file type** refiner has more than 5 results, then show the apply button on top and bottom.

**Comment by wobba** [comment]
Closing as v3 is no longer maintained.
