### ISSUE TITLE
PnP Modern Search Home Page- Documentation on GitHub Error

### ISSUE THREAD

**Issue by RamBalani** [microsoft-search/pnp-modern-search#3068]
Log requests as ideas in the discussion forum.
Am sign in Github with my account when I click the Documentation link--I get an error. See screenshot attachments. 
Why ? Are we doing anything wrong?
![GitHub PnP Modern Search Documentation Errors Out On Click](https://github.com/microsoft-search/pnp-modern-search/assets/37209670/322f2336-50e3-48df-9b31-99818910e2d5)

and this for the actual error screenshot 
![Actual Error-June12-2023-GitHub PnP Modern Search Documentation Errors Out On Click_002](https://github.com/microsoft-search/pnp-modern-search/assets/37209670/8f09d5de-4ccb-44d9-a761-7b2ca83ab97b)

**Comment by kasperbolarsen** [comment]
Just check access to https://microsoft-search.github.io/pnp-modern-search , seems to work just fine here. What does the F12 have to say?

**Comment by DragonMamaZ** [comment]
I have the same problem.  
I either see the same error above or "This site can't be reached."
I noticed it this weekend.  It was working on Friday.  Help!

**Comment by kasperbolarsen** [comment]
> I have the same problem. I either see the same error above or "This site can't be reached." I noticed it this weekend. It was working on Friday. Help!
> 
> Is there another way to access the documentation?

Which browsers have you tried , have you tried an InPrivate window etc?

**Comment by DragonMamaZ** [comment]
1. Tried Chrome -> issue
2. Then Chrome Incognito Window -> issue
3. Then Edge -> issue
4. Then Edge In-private window -> issue.

Ran windows diagnostics and now it's working again on all the above browsers/windows.
Thanks!

**Comment by kasperbolarsen** [comment]
false alarm :-)

**Comment by wobba** [comment]
Please log question in the discussion forum, and keep issues list to web part bugs.
