### ISSUE TITLE
Previous change overwritten by recent PR

### ISSUE THREAD

**Issue by patrikhellgren** [microsoft-search/pnp-modern-search#3079]
**Version used**
4.9

**Describe the bug**
I submitted a PR that was merged in #2841 and one of the changes made there seems to since that have been overwritten in #3043, The change was on line 208 in sv-SE.js.
Would you like me to submit a new PR with the same change or do you want to handle it some other way?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by wobba** [comment]
Pushed it directly to the dev branch now :)
