### ISSUE TITLE
Hash is always appended when redirecting using search box

### ISSUE THREAD

**Issue by Tanddant** [microsoft-search/pnp-modern-search#3089]
**Version used**
4.9

**Describe the bug**
In one of the recent updates a changes appears to have been introduced which causes a hashtag to always be introduced when using the searchbox to redirect, even if no hash is present.

This does not affect search pr. say, but previously I've used the seach box to redirect to lists with a filter, i.e:

    /AllItems.aspx?FilterField1=Editor&FilterValue1={inputQueryText}

Unfortunately the # causes lists to clear the URL filters, and therefore this "feature" breaks

Rebuilding the solution without the '#' [here](https://github.com/microsoft-search/pnp-modern-search/blob/main/search-parts/src/helpers/UrlHelper.ts#L67) resolves that issue, but I'm not familiar enough with the rest of the code base to see if it causes other errors, maybe someone else has that insight?

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to a list and filter using modern UI
2. Copy the URL
3. Setup the search box on page with a redirect to that list and replace the filter value with the query replacer
4. Search and hit enter

**Expected behavior**
I used to be able to link to a list and have it pre filtered by whatever the user just entered

**Desktop:**
 - Chrome Version 114.0.5735.134 (Official Build) (64-bit) 
 - Windows 11

**Additional context**
I know that this is not an officially supported use case, but if it doesn't break anything it should be an easy fix to remove the '#' and instead set the hash value to ''

**Comment by Tanddant** [comment]
Maybe converting to using the URL object could make sense, as it is supported by all major browsers
https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

But maybe I'm missing something obvious (hence creating an issue, and not a PR)

But as far as I can see this should give the same result, maybe not the DDOS part, but I'm most certainly not understanding what's going on in that part - so someone smarter than me should definitely look this over!

```
    /**
     * Add or replace a query string parameter
     * @param url The current URL
     * @param param The query string parameter to add or replace
     * @param value The new value
     */
    public static addOrReplaceQueryStringParam(url: string, param: string, value: string): string {      
        const newUrl = new URL(url);
        newUrl .set("Param", "value");
        return newUrl .toString();
    }
```

**Comment by kasperbolarsen** [comment]
Hi Dan, I guess this is the odd one around. I would understand why you would link to a list view with a query parameter from the results, but you lost me when doing it from the search box? The search box is intended to provide input to the results web part, not as a link generator :-)
Can you share a little more about what you are trying to achieve?

**Comment by Tanddant** [comment]
Hi @kasperbolarsen 

I 100% agree that I'm not using the web part as intended, or perhaps just not a way anyone predicted 😁

But the Search box has an option to redirect searches to a new URL using a query parameter, I've used this to link to a separate site with a search center in the past, or link to external systems, in this particular case I had linked to a SharePoint list with a filter in the URL.

So while this not an intended feature, it used to work, and as far as I can see adding a hash to the URL does nothing for search, it was simply the manipulation of the URL that adds it to move it to the end


![image](https://github.com/microsoft-search/pnp-modern-search/assets/6947024/3394b06a-f670-46f8-bbe1-c393d58065fc)


![123](https://github.com/microsoft-search/pnp-modern-search/assets/6947024/53e8febe-516d-448e-ad18-be126ac4909c)
