### ISSUE TITLE
Document tags - search filters/refiners.

### ISSUE THREAD

**Issue by merzibau** [microsoft-search/pnp-modern-search#310]
Hello,

I am looking for a way to include document tags (metadata) from SharePoint classic to be included in the current search filters of SharePoint Online. I was wondering if this release could help accommodate that? Thanks for any help on this!

Best, 
Martin.

**Comment by wobba** [comment]
Hi,
See the documentation at https://microsoft-search.github.io/pnp-modern-search/search-parts/search-filters/

You can already use the Managed property **Tags** to get any tag on an item.

In theory, there is no change on what you used in classic and what you can use in our Filters web part - except we provide translation support of taxonomy based ones.

@FranckyC , seems we are missing docs on which crawled property to map in order to get translations to work.

**Comment by merzibau** [comment]
> Hi,
> See the documentation at https://microsoft-search.github.io/pnp-modern-search/search-parts/search-filters/
> 
> You can already use the Managed property **Tags** to get any tag on an item.
> 
> In theory, there is no change on what you used in classic and what you can use in our Filters web part - except we provide translation support of taxonomy based ones.
> 
> @FranckyC , seems we are missing docs on which crawled property to map in order to get translations to work.

Thank you very much. The issue I am trying to address is that we have a lot of tagged content. We are now trying to see how we can enable filters/search refiners for these tags in SharePoint Online. I will explore this PNP solution in more detail and see if it might solve our issue. Thanks again.

**Comment by wobba** [comment]
@merzibau You map the crawled property corresponding to your SharePoint column to a RefinableStringXX managed property, and use that. Same as when introduced in SharePoint 2013 :)

**Comment by FranckyC** [comment]
Hi @merzibau , you should use the `owstaxidmetadataalltagsinfo` OOTB managed property for that. This prop3rty aggregates all tags in your content. If you want individual refiners, like @wobba said, you must use a RefinableStringXX  mapped to a ows_taxId_xx crawled property to get the translation work. See https://microsoft-search.github.io/pnp-modern-search/search-parts/search-results/#miscellaneous-taxonomy-values-dynamic-translation
