### ISSUE TITLE
The {inputQueryText} is blank after refreshing the page in case of SharePoint data source

### ISSUE THREAD

**Issue by yvsuhas** [microsoft-search/pnp-modern-search#3107]
**Version used**
4.8

**Describe the bug**
The PnP Search Results webpart is not retaining the {inputQueryText} token after refreshing the page using SharePoint Search as the data source. I have a connected webpart on a page which passes dynamic property to the PnP Search Results Webpart. The results are returning fine when the source webpart is changed and the new value is sent to the search results webpart but as soon as the page is refreshed, the results are empty. The query is path:"{\Site.URL\}/libraryName/" IsDocument:"True" RefinableString04:{inputQueryText}. The results appear fine for another search results webpart which is returning Drive Items using Microsoft Search as the data source and the query that is used here is name:{inputQueryText}. The default value in both the search results webparts is {inputQueryText}. Not sure why the SharePoint data source query is emptying the token on page refresh.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Create a test list with few columns with data which will act as the source that will pass dynamic property to other webparts.
2. Create a test library that will be used as the consumer webpart and add some documents. Make sure one of the column in this library is a lookup to the test list created above which is acting as metadata.
3.  Make sure that the associated RefinableString managed properties are configured and the site is indexed.
4. Go to a SharePoint Modern page in the same site.
5. Add a connected webpart (list created above) with data that can be passed as dynamic property to other webparts.
6. Add a PnP Modern Search Webpart, select SharePoint Search as the data source and add the query path:"{\Site.URL\}/TestLibrary/" IsDocument:"True" RefinableString04:{inputQueryText}, choose Details list as the layout and make the input text as dynamic with a default value as {inputQueryText}. Use connected webparts and connect to the test list added to the page which is passing dynamic property.
7. Connect the Search results webpart to a vertical.
8. When a value is passed by the source webpart, associated results appear in the search results webpart but when the page is refreshed, no results appear.

**Expected behavior**
Once the search results webpart is configured and connected to the source webpart passing values as dynamic properties, the search results webpart should display results even on page refresh as the same behavior is exhibited by the search results webpart that is using Microsoft Search as the data source.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Browser [chrome, edge]

**Additional context**
The enable grouping/Group by field and field to use for file extension dropdowns are showing empty and does not allow to be selected in the case of SharePoint search results webpart when the {inputQueryText} token is present in the Query Tenplate. There is an error in the console for the modern-search-result-c75757.js file that says cannot read properties of null. (reading 'innerHTML')

**Comment by wobba** [comment]
`inputQueryText` is tied to search box usage. If you change to use `searchTerms` instead, does that help? And please show a screenshot of your dynamic/default query for the search part.

**Comment by yvsuhas** [comment]
We decided to go with a custom webpart using SPFx and Graph API Search for this requirement. Thanks for your response.
