### ISSUE TITLE
Add exception to DOMpurify for opening Office documents in client application

### ISSUE THREAD

**Issue by ThomasPolfliet** [microsoft-search/pnp-modern-search#311]
**Is your feature request related to a problem? Please describe.**
In our company we have a feature request to open documents from the search results directly in Word/Excel/... desktop application. At the moment whenever we add the "ms-word:ofe|u|..." prefix in a href attribute of an <a> tag in an handlebar, the attribute gets removed and we receive an a tag without a link.

**Describe the solution you'd like**

Configure DOMpurify so it allows all href attribute which start with ms-*:ofe|u|

**Describe alternatives you've considered**
Creating a custom component which will not be sanitized by DOM purify.
Changing the setting on the library of the documents to open the documents with the client application.

**Additional context**

**Comment by wobba** [comment]
Fixed.

**Comment by FranckyC** [comment]
Good catch @ThomasPolfliet. Thanks @wobba
