### ISSUE TITLE
[HTTP]:500 - [CorrelationId]:95ecc2a0-c0c5-6000-c5d4-bf1eb764ed09 [Version]:16.0.0.23814

### ISSUE THREAD

**Issue by jochenfritz-22** [microsoft-search/pnp-modern-search#3113]
Hello,
Currently I get the following error message when I use the PnP Search Result web part:
[HTTP]:500 - [CorrelationId]:9fedc2a0-50a1-6000-eaae-8d711b9254cb [Version]:16.0.0.23814

This bug has already been reported, but that was in 2021 and there was no solution in the course of the conversation.

My environment:

- Browsers: Edge, Chrome
- SharePoint: online
- Language: German
- Pnp Modern Search Version: 4.8.0
- OS: macOS 13.4

When I add the web part and connect it to SharePoint as a data source, I get the error message after about 30 seconds:
`[HTTP]:500 - [CorrelationId]:9fedc2a0-50a1-6000-eaae-8d711b9254cb [Version]:16.0.0.23814`
![Bildschirmfoto 2023-07-03 um 19 38 26](https://github.com/microsoft-search/pnp-modern-search/assets/122534001/8cbf70ad-25f4-4298-b12b-248196172fd2)

In the console I get the following error message:
`modern-search-results-web-part_343763bbe6d907959f1e.js:2  Uncaught (in promise) Error: [HTTP]:500 -  [CorrelationId]:9fedc2a0-50a1-6000-eaae-8d711b9254cb [Version]:16.0.0.23814
    at e.<anonymous> (modern-search-results-web-part_343763bbe6d907959f1e.js:2:1378540)
    at modern-search-results-web-part_343763bbe6d907959f1e.js:2:1376079
    at Object.next (modern-search-results-web-part_343763bbe6d907959f1e.js:2:1376184)
    at o (modern-search-results-web-part_343763bbe6d907959f1e.js:2:1374925) `

I've been observing this behavior for about a week. I have filter page where I am using all Pnp WebParts for a growing number of pages. Currently around 100. In the past there were always error messages, but they only occurred occasionally. Now the site can hardly be used.

What can be the reason for this behavior, where can I start with the optimization?
Thank you for your help in advance.

**Comment by wobba** [comment]
API issue, not a web part issue. Log at https://github.com/SharePoint/sp-dev-docs/issues or Microsoft support.
