### ISSUE TITLE
Search result webpart no longer configurable in a translated page (EN)

### ISSUE THREAD

**Issue by ascheuch** [microsoft-search/pnp-modern-search#3116]
**Version used**
4.9

**Describe the bug**
In a multilingual site (main language: DE, second language EN) I have the problem that I can no longer configure the result web part in the translated version of a page (EN).  I only see 2 steps in the configuration. See my screenshots.
Existing webparts in EN pages lost the configuration.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. I go to a translated page (EN) '
2. I place the result webpart on the page
3. When I try to configure the webpart see above
4. Normally I get all configuration steps after selection of the datasource

**Expected behavior**
The same behavior as before: I can configure the webpart

**Screenshots**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/89776216/a19fc1ba-c0d6-4a97-b33c-8676fe0a3e7b)
![image](https://github.com/microsoft-search/pnp-modern-search/assets/89776216/6fb3aa3c-2768-4bc0-a05f-24f044b160b1)
![image](https://github.com/microsoft-search/pnp-modern-search/assets/89776216/39c090ac-d397-4686-a67f-348c12c1e4f3)

**Desktop (please complete the following information):**
 - Browser [Chrome; Edge, FF]

**Comment by wobba** [comment]
I cannot repro.. all pages showing fine in original and alternative language for me. Newly updated to 4.9?

**Comment by ascheuch** [comment]
Yes from 4.8 to 4.9

**Comment by wobba** [comment]
I can repro when English is the second language.

**Comment by ascheuch** [comment]
It's possible to downgrade 4.9 --> 4.8?

**Comment by wobba** [comment]
Sure. The fix shouldn't be too difficult. Just a matter of time doing. No promise on timelines but might have time this week to get a fix in.

**Comment by ascheuch** [comment]
Ok, thank you.

**Comment by wobba** [comment]
Fixed in v4.9.1 release https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.9.1
