### ISSUE TITLE
Inconsistent Document Previews with handlebars

### ISSUE THREAD

**Issue by ThomasPolfliet** [microsoft-search/pnp-modern-search#312]
**Version used**
3.13 (bug is also apparent in older versions).

**Describe the bug**
We increased the page size to 25.
We added the document preview classes and data attributes in an handlebar.
Code Used:

```
{{#eq FileType 'pdf'}}
    <div title="" loading="lazy" style="position:absolute; top:0; left:0; overflow: auto; width:100%; height: 100%;" class="document-preview-item img-preview" data-src="{{getPreviewSrc item}}" data-url="{{#if ServerRedirectedEmbedURL}}{{ServerRedirectedEmbedURL}}{{else}}{{getPreviewSrc item}}{{/if}}">
    </div>
    <pnp-fabric-icon style="pointer-events:none;" data-icon-name="Preview" data-size="32">
{{else}}
<div title="" loading="lazy" style="position:absolute; top:0; left:0; overflow: auto; width:100%; height: 100%;" class="document-preview-item img-preview" data-src="{{getPreviewSrc item}}" data-url="{{#if ServerRedirectedEmbedURL}}{{ServerRedirectedEmbedURL}}{{else}}{{getPreviewSrc item}}{{/if}}">
</div>    
<pnp-fabric-icon data-icon-name="Preview" data-size="32"/>
{{/eq}}
```

At first sight the document previews are shown but whenever I go to another page or use a refiner, not all results show a document preview.

**To Reproduce**
1. Create search page with paging and refiners
2. Increase page size to 25 (or higher)
3. Use Details list Layout.
4. Add Preview Column and set handlebar of this column to the code above.
5. Refine results (or go to another page).
6. The previews for the items on the bottom of the list aren't shown

**Expected behavior**
The Document Previews are being shown for all results.

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14311727/84477905-b8910000-ac90-11ea-9bf9-28006b8146cd.gif)

**Desktop (please complete the following information):**
Tested with Chrome and Edge

**Additional context**

**Comment by wobba** [comment]
Can you check the network trace?

**Comment by ThomasPolfliet** [comment]
Anything particular I need to look for?
I created an export of the network trace but I'm a bit hesitant to share it on a public forum (already replaced all tenant url references, do I need to replace anything else?)

**Comment by wobba** [comment]
Look for requests being made when you hover and what they look like. Is the issue the same when you use the "Simple list" layout which has previews built in?

**Comment by phillipharding** [comment]
I'm using 3.14.2 and noticed similar inconsistent behaviour around triggering previews
My configuration is using the Details List with a custom handlebars template for a preview button column
```
{{#if (getPreviewSrc item)}}
<div title="click to preview this file" style="position:absolute;top:0;left:0;overflow:auto;width:100%;height:100%;cursor:pointer;" class="document-preview-item img-preview" data-src="{{getPreviewSrc item}}" data-url="{{#if ServerRedirectedEmbedURL}}{{ServerRedirectedEmbedURL}}{{else}}{{getPreviewSrc item}}{{/if}}">
</div>    
<i class="ms-Icon ms-Icon--Preview" style="color:{{@themeVariant.palette.themeSecondary}};font-size:18px;font-weight:600;" role="presentation" aria-hidden="true"></i>
{{else}}
&nbsp;
{{/if}}
```
![image](https://user-images.githubusercontent.com/7671418/87689034-a61e5080-c77f-11ea-86d5-9c0c69abfd0d.png)
Search Results is configured to show 40 items.


When the page loads, what seems to happen is that the preview buttons in the first 10 rows get hooked up to click handlers for preview.
If I scroll the page down, none of the other preview buttons in rows past the first 10 have click handlers attached.
![image](https://user-images.githubusercontent.com/7671418/87689538-3f4d6700-c780-11ea-9749-ae78edc300e2.png)


Weirdly, while the page is loading, if I keep scrolling the page down until all the results have loaded, then all the preview buttons in all the rows have click handlers attached.
![image](https://user-images.githubusercontent.com/7671418/87690149-f9dd6980-c780-11ea-9b1e-71e3b4ed12a5.png)

**Comment by wobba** [comment]
Think I figured out a workaround and optimization in #395 but a timeout doesn't seem ideal to wait for all items to be rendered.
