### ISSUE TITLE
PnP Web part v4 doesn't support Bookmarks

### ISSUE THREAD

**Issue by cbridges12** [microsoft-search/pnp-modern-search#3120]
My customer is using the PnP v4 web parts to customize their SharePoint modern Search. When configuring the query rules, the bookmark is displayed but they want it to display all the time, ie a bookmark. They understand that the feature is currently in Beta but would like to know a release date. Also, they are willing to partner with your team to help test this feature to get the release quicker. Is there any possibility in this? I'm a MS Customer Engineer and willing to help facilitate this. Please let me know what I can tell my customer.
v-cobridges@microsoft.com
Colleen Bridges

**Comment by jakecusack** [comment]
Good day! we are also being asked for this feature as it works well with OOB Microsoft Search and but not yet in PnP, we had promotional links when we were on prem that really worked but we are at a loss without it in the PnP framework and would jump on the chance to test it out with the group!

**Comment by wobba** [comment]
Bookmarks are in v1.0 according to the documentation. There is likely some work to be done to have bookmarks and e.g. files showing at the same time as that API support was added more recently. Any developer willing to assist to bring this in is welcome to contribute.

**Comment by edarroudi** [comment]
They are indeed working...

![image](https://github.com/microsoft-search/pnp-modern-search/assets/935493/6946026f-cc82-48b8-b7f2-1c5b63c6c872)

Set it like this: 
![image](https://github.com/microsoft-search/pnp-modern-search/assets/935493/1bc43693-361e-4d6c-a501-afd5a71aa72e)

Use a custom template, maybe with content like this: 
```
<div class="template">
          {{#each data.items as |item|}}
              {{#> resultTypes item=item}}
                <div class="template--listItem--contentContainer">
                    <div class="template--listItem--title">
                        <pnp-icon data-name='DoubleBookmark'></pnp-icon>
                        <a href="{{slot item @root.slots.Path}}" target="_blank" class="template--link" data-interception="off">
                               {{{slot item @root.slots.Title}}}
                          </a>
                    </div>                   
                    <div class="template--listItem--content">{{getSummary (slot item @root.slots.Summary)}}</div>                     
                </div>              
              {{/resultTypes}}          
          {{/each}}
  </div>
```

**Comment by wobba** [comment]
I'll close this one if you're ok with it? And the plan is to allow bookmarks and results in the same request and add default template support for it.

**Comment by cbridges12** [comment]
Thank you for your help and support Mikael!
