### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by manjunathreddy1** [microsoft-search/pnp-modern-search#3132]
Hi,

We are trying to create custom query modifier but the file '../models/IQueryModification' mentioned in the following example is not found in the source code. Please confirm how we can find it or please confirm where we need to place the following code for custom query modifier. From the documentation it is not clear.

```
public getCustomQueryModifiers(): IQueryModifierDefinition[] {
    return [
        {
          name: 'Custom Query Modifier',
          key: 'CustomQueryModifier',
          description: 'A demo custom query modifier from the extensibility library',
          serviceKey: ServiceKey.create<IQueryModifier>('MyCompany:CustomQueryModifier', CustomQueryModifier)
      }
    ];
  }
```

https://microsoft-search.github.io/pnp-modern-search/v3/search-extensibility-library/getting-started/#create-a-custom-query-modifier

**Comment by wobba** [comment]
We don't do support for v3 any more. See https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_query_modifications/ for v4.
