### ISSUE TITLE
Search Result V4 - No sort available with MS Search

### ISSUE THREAD

**Issue by seanix99** [microsoft-search/pnp-modern-search#3138]
**Version used**
4.9.0.0

**Describe the bug**
When configuring webpart to use MS Search connector, we have no properties available to sort the results. Is this a feature missing or a bug ? 

The MS Search api have the properties sortproperties exposed, so the webpart should make it available when using the MS Search.

**Expected behavior**
A poosibility to specify the properties to use fort sorting by the query sended to MS Search.

**Comment by seanix99** [comment]
This options is not available when using External Items. I should mention it in the first place. My apologize.

**Comment by ccoley0473** [comment]
![Sort](https://github.com/microsoft-search/pnp-modern-search/assets/141053241/2a39f0f4-9865-4d45-adc8-2e64c46e4892)

I setup all my columns to be managed, then mapped them to a RefinableString value in the Schema.     Then as previously mentioned, Edit Sort Settings, and add your RefinableString values in the order you want them to be sorted.    **  These values will not show in the drop down, you'll need to manually add them to the list

**Comment by wobba** [comment]
@ccoley0473 you cannot map to RefinableString for Graph Connector items. Separate schema, hence it's an enhancement to be added.

**Comment by gretchunkim** [comment]
This enhancement will be really great appreciated! 

As for a temporary workaround, I could use list layout then use **groupby** feature to sort  Microsoft Graph External Items.  Then, go back to custom layout to modify some of the properties to hide the groupby text.

**Comment by abates100** [comment]
Version 4.13.1 does allow you to add sort properties with External item now as long as the field is set to refinable.  The default sort is applied, however the user sort function (arrow) does not display.  This is using the Details List layout.
![image](https://github.com/user-attachments/assets/f88fcc2d-113b-4557-b22e-e0487fbfb56a)
![image](https://github.com/user-attachments/assets/28105749-8414-4caf-88bb-039d80af01fe)
