### ISSUE TITLE
Enhancement proposal for Modern Search: Expose an option to turn off telemetry collection by PnP controls in use.

### ISSUE THREAD

**Issue by alexabramkin** [microsoft-search/pnp-modern-search#315]
**Is your feature request related to a problem? Please describe.**
Internal informational security folks not being warm to the idea of use info going outside of organization.

**Describe the solution you'd like**
Modern Search web parts: Expose an option to turn off telemetry collection by PnP controls in use.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by wobba** [comment]
@FranckyC we could in theory turn off telemetry for the components we use, unless we want to add a toggle/setting for it.

**Comment by FranckyC** [comment]
We could turn if off by default, I don't think having a toggle has any value.

**Comment by FranckyC** [comment]
@alexabramkin fixed in the develop branch #363 . Will be available in the next release.

**Comment by alexabramkin** [comment]
@FranckyC you are awesome, thank you!
