### ISSUE TITLE
Issue with searching with quotes on verticals

### ISSUE THREAD

**Issue by mw-new-test** [microsoft-search/pnp-modern-search#3154]
**Version used**
Ex: 4.9

**Describe the bug**
When we are searching with quotes, For ex: **"pnp modern search"** in one vertical and navigate to different vertical with same keyword, the search keyword gets removed

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Configure 2 verticals (All and People), results webparts
2. Searchbox webpart properties - source (Page environment), Query string, Query parameters and q being query string parameter properties
4. People results can be a different page with vertical being a hyperlink - https://*****.sharepoint.com/sites/EnterpriseSearch/SitePages/Enterprise-Search-People.aspx?v=People&q={inputQueryText}
5. On All vertical, search for keyword --> **pnp modern search** without quotes
6. Navigate to People vertical -- keyword from All vertical is passed onto to People vertical
7. Now come back to All vertical and add quotes to keyword **"pnp modern search"** and search
8. Navigate to People vertical -- keyword gets removed from URL
9. See error

**Expected behavior**
With quotes passed in search keyword, on navigating to different verticals, query string should not get stripped out

**Screenshots**

**Desktop (please complete the following information):**
Chrome/Edge

**Additional context**

**Comment by wobba** [comment]
Are you using the header search box, not the PnP search box?

**Comment by till-llit** [comment]
i can reproduce this issue with the pnp search box - but only when the vertical is pointing to a different page

**Comment by wobba** [comment]
@till-llit is the issue with both the header search box and the pnp search box? Don't confuse the setup, clarify the exact repro steps 😉.

**Comment by till-llit** [comment]
its the PnP Search Box.

**Comment by mw-new-test** [comment]
> @till-llit is the issue with both the header search box and the pnp search box? Don't confuse the setup, clarify the exact repro steps 😉.

It is the pnp search box.

**Comment by mw-new-test** [comment]
Issue is with onVerticalSelected function SearchVerticalsContainer.
If vertical is link and has a linkurl and is opening in same tab, if search keyword is passed with quotes, then query string is stripped out from URL. I think query string needs to be encoded before click

**Comment by wobba** [comment]
@mw-new-test care to PR a fix?

**Comment by mw-new-test** [comment]
Sorry a PR is?
I can add the changes made here..
if(vertical.openBehavior === PageOpenBehavior.NewTab){
              window.open(resolvedUrl, "_blank");
}
else{
              // Allow SharePoint to intercept the click and do a soft navigation
              **resolvedUrl = encodeURI(resolvedUrl);
              document.body.insertAdjacentHTML('beforeend', `<a onclick="${this.redirectVertical(resolvedUrl)}" style="display:none;"></a>`);**
}


public redirectVertical(linkUrl:string): void{
    window.location.href=linkUrl;
}

**Comment by wobba** [comment]
A pull request (PR) is when you fork the repository, make a change and then create a pull request against the original repository. See https://microsoft-search.github.io/pnp-modern-search/how-to-contribute/ which has a link to more help.

**Comment by wobba** [comment]
Fixed with #3396
