### ISSUE TITLE
pnp v4.9 mgt-person -> person-card on hover with rtl is displayed incorrectly ( left positioning ) 

### ISSUE THREAD

**Issue by danial999** [microsoft-search/pnp-modern-search#3158]
**Version used**
Ex: 4.9

**Describe the bug**
pnp v4.9 mgt-person -> person-card on hover with rtl is displayed incorrectly ( left positioning ) 

**To Reproduce**
Detailed steps to reproduce the behavior:
added pnp search resault webpart v4.9
use mgt-person with dir="rtl" and person-card="hover" in custom template
when hover on person to see card , the card is displayed in far right of the screen

**Expected behavior**
on hover person card should be displayed on relative position to the person image

**Screenshots**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/9986207/7256cab3-5099-4046-a486-8c8ff81efd6f)
**Desktop (please complete the following information):**
 chrome

**Comment by wobba** [comment]
We don't really control how the mgt components render or show. If you think we can/should fix this in this project any pointer would be useful.

**Comment by danial999** [comment]
I tested the described behavior on Microsoft Graph Toolkit (v3.1.0) Playground (https://mgt.dev/?path=/story/components-mgt-person--person) and found that mgt renders hover cards correctly with rtl.
/*
test example :
<body dir=rtl>
<mgt-person style="margin-right:350px" person-query="me" view="twoLines"  person-card="hover"></mgt-person>
</body>
*/
So I assume the fix should be in this project. 
the calculation of the style attributes on the "flyout" class are not correct when the mgt is used in this project.
![image](https://github.com/microsoft-search/pnp-modern-search/assets/9986207/858f6b4d-951c-490f-ac28-8e16ec5c87af)

**Comment by wobba** [comment]
I'll try to update for the next verison.
