### ISSUE TITLE
Result types are conflicting if multiple search result webparts are on the same page

### ISSUE THREAD

**Issue by stevebeauge** [microsoft-search/pnp-modern-search#316]
**Version used**
Ex: 3.12.1.0

**Describe the bug**
On a page where multiple search web parts are set up, configuring the result types on on the WP applies to all webparts.

**To Reproduce**

1. On a modern page, put two search result webparts
2. Configure both webparts to search for `*`
3. Configure both webparts to use the **simple list** layout.
4. On the first webpart, configure a result type rule:
   a. `Title` is not equals to 'aaaaa' (to ensure the rule applies to some document)
   b. Url of external template : whatever template you want
5. Publish the page

**Expected behavior**
I'd expect to have a custom template for only the 1st web part.

However, I see the external template applied to all webparts in the page.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser FF

**Additional context**
When switching to edit mode, I can see the correct render happens, seems like the render refreshed.

**Comment by stevebeauge** [comment]
A workaround I found : remove the handlebar helper `{{#> resultTypes item=item}}` and the matching closing `{{/resultTypes}}`.

This will disable result type matching.

Of course this works only if the 2nd webpart does not require result type rules

**Comment by stevebeauge** [comment]
I also noticed that setting an external template on either of the webparts (in custom layout section, not result types) also applies to both webparts, not only the one where it's set.

**Comment by wobba** [comment]
I know this has worked in the past so curious what causes this.

**Comment by stevebeauge** [comment]
I submit a PR for this issue

**Comment by stevebeauge** [comment]
The issue is fixed in the 3.14.1 release.
