### ISSUE TITLE
On-Prem Version

### ISSUE THREAD

**Issue by AlAsmarAicha** [microsoft-search/pnp-modern-search#3163]
Please i want to know if there is a version for Sharepoint On-Prem , i try to upload this package it's not working on On-Prem

**Comment by FranckyC** [comment]
Hi @AlAsmarAicha, there is no  Sharepoint On-Prem version for this WebParts as the used SPFx version is not compatible.

**Comment by AlAsmarAicha** [comment]
if i download this code and create a new solution with version compatible it will work ?

**Comment by FranckyC** [comment]
Not really as we use many SPFx features that won't be available on prem like dynamic data or the library components. This would imply to rewrite completely the component.

**Comment by kasperbolarsen** [comment]
Please see https://github.com/pnp/sp-dev-solutions/issues/355 for a version that works on SP2019

😁
