### ISSUE TITLE
Delete search box text to reset results

### ISSUE THREAD

**Issue by xichro** [microsoft-search/pnp-modern-search#317]
When the user deletes **all** text from the search box, it would be nice if that had the same effect as if clicking on the 'x' to reset the search results - an event listener seems appropriate but I understand this could have significant performance issues. Currently however, users are confused as to why it isn't refreshing.

Many thanks,
Xichro

**Comment by wobba** [comment]
You mean delete text and linger in the box? What experience do you show when they enter the page with no query? Do you have a default query set?

**Comment by xichro** [comment]
I have * set as the default query, with verticals having their own query - that isn't a problem :)

I mean when users delete all text from the search box the results don't reset the same as they do when clicking the 'x' in the box. You have to select a new vertical or type something in the box again and then click the 'x' (due to it not appearing if there's no text).

Steps to reproduce:
1. Type something into the search box and hit enter.
2. Search results return as expected.
3. Delete all text from the search box.
4. Search results don't reset to the default query.

Alternatively an approach that works:
1. Type something into the search box and hit enter.
2. Search results return as expected.
3. Clear the search box with its corresponding 'x' button.
4. Search results reset to the default query.

If the search box is empty, could this imitate clicking the 'x', resetting to the default query?

Thanks.

**Comment by wobba** [comment]
I do get what you're after, just not sure it's a good UX pattern or not. Also unsure if * on default is a good thing compared to a blank page like you have for web. I know OOB search shows results on blank enter, but we don't reissue that query if you clear the box.

**Comment by xichro** [comment]
By default we're bringing back a list of documents with a particular content type, it works really well!

No problem, I'll add a quick note on the page to tell users to clear the search box using 'x'. I just know users will get confused when they delete from the search box and it doesn't reset.

Thanks for getting back to me :)
