### ISSUE TITLE
Package name has changed in v4.9.1

### ISSUE THREAD

**Issue by guptasurabhi-git** [microsoft-search/pnp-modern-search#3173]
Package name has changed in v4.9.1 and is no longer consistent with older package names, this is causing issue when deploying this version, causing two different packages to exist in app catalog.

Any suggestions on current issue? And can we try to avoid this in future?

Thanks

**Comment by kasperbolarsen** [comment]
download the 4.9.1 package, rename it to pnp-modern-search-parts-v4.sppkg and upload it to the App Catalog , very minor issue :-)

**Comment by wobba** [comment]
Fixed
