### ISSUE TITLE
Only a limited number of Managed Properties are available  in "Selected Properties" under Search Results webpart

### ISSUE THREAD

**Issue by amilanc** [microsoft-search/pnp-modern-search#3192]
I want to add a couple of filters based on Refinable Managed properties, but "Properties: list only shows Managed properties until letter "N" in in the alphabetical order my tenant (This is a large tenant with lot of manages properties). Since all refinable managed properties are in "R", they dont show up.

**Comment by kasperbolarsen** [comment]
I have not had the opportunity to test this, but most fields in the PnP Modern Search can accept typed text as well as a selection. Have you tried it?

**Comment by kasperbolarsen** [comment]
Are you referring the "Selected properties" field in the Results web part or "Filter field" field in the Refiner web part? A pic would do worders :-)

**Comment by amilanc** [comment]
Hi Kasper,
I am referring to "Selected Properties" in Search Results Web Part.  This is a large tenant with thousands on Managed properties.  It looks like "Selected Properties" only enumerates the first 1000 Managed properties. I am trying to set some filters based on some of the Refinable Managed properties, but they are far doen the list and doesn't show up here.

This would be fantastic tool for my customer. Any help would be much appreciated.

[Graphical user interface, text, application, email  Description automatically generated]

Thanks,
Amila


Sent from Outlook<http://aka.ms/weboutlook>

**Comment by amilanc** [comment]
I tried to type it in, but it doesn't let me. Only allowed to select from the list.



Sent from Outlook<http://aka.ms/weboutlook>

**Comment by kasperbolarsen** [comment]
That is strange, as I have no problem just typing the name of the Managed Property, but if you are sure that this option does not work in your case, then there must be some sort of limit. 
On tab 4 of the Results web part you have Import/Export settings. Perhaps you can export the settings, edit the json file, and import it?
![image](https://github.com/microsoft-search/pnp-modern-search/assets/20593570/97a8f3f7-93fe-4ecc-9921-ef3a025d8f63)

**Comment by amilanc** [comment]
That works like a charm. Thanks for the tip.

Sent from Outlook<http://aka.ms/weboutlook>

**Comment by amilanc** [comment]
Hi Casper,
I have couple of questions.

  1.  This is a question on pnp search filter. I use several refinable managed properties as filters in the search page.  Is there a way to get the filter to show empty metadata fields. Currently the filter only shows ones with data. We are planning on using this as a tool to let users know that they need to fill required metadata.
  2.  In the search results page, how can I add a link to the item properties so users can see the metadata.
  3.  In the search results page, how can I add a link to the library where a result is displayed

Thanks,
Amila


Sent from Outlook<http://aka.ms/weboutlook>
From: Amila Chandrasekera
Sent: Thursday, August 17, 2023 2:47 PM
To: microsoft-search/pnp-modern-search ***@***.***>; microsoft-search/pnp-modern-search ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft-search/pnp-modern-search] Only a limited number of Managed Properties are available in "Selected Properties" under Search Results webpart (Issue #3192)

That works like a charm. Thanks for the tip.

Sent from Outlook<http://aka.ms/weboutlook>

**Comment by amilanc** [comment]
PnP search filters have the option of making total search result count for each filter being available . How did you implement this ? I have a need to get the item count that meets a specific search query in each library within a sharepoint site (hits count per library). I am trying to build this as a Power Automate workflow with SharePoint search REST API. Still no luck. Any help would be appreciated.

Thanks,
Amila



Sent from Outlook<http://aka.ms/weboutlook>
From: Amila Chandrasekera
Sent: Friday, December 1, 2023 11:16 AM
To: microsoft-search/pnp-modern-search ***@***.***>; microsoft-search/pnp-modern-search ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft-search/pnp-modern-search] Only a limited number of Managed Properties are available in "Selected Properties" under Search Results webpart (Issue #3192)

Hi Casper,
I have couple of questions.

  1.  This is a question on pnp search filter. I use several refinable managed properties as filters in the search page.  Is there a way to get the filter to show empty metadata fields. Currently the filter only shows ones with data. We are planning on using this as a tool to let users know that they need to fill required metadata.
  2.  In the search results page, how can I add a link to the item properties so users can see the metadata.
  3.  In the search results page, how can I add a link to the library where a result is displayed

Thanks,
Amila


Sent from Outlook<http://aka.ms/weboutlook>
From: Amila Chandrasekera
Sent: Thursday, August 17, 2023 2:47 PM
To: microsoft-search/pnp-modern-search ***@***.******@***.***>>; microsoft-search/pnp-modern-search ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [microsoft-search/pnp-modern-search] Only a limited number of Managed Properties are available in "Selected Properties" under Search Results webpart (Issue #3192)

That works like a charm. Thanks for the tip.

Sent from Outlook<http://aka.ms/weboutlook>
