### ISSUE TITLE
No search results

### ISSUE THREAD

**Issue by simoniscasesensitive** [microsoft-search/pnp-modern-search#3198]
**Version used**
4.9.2

**Describe the bug**
A simple ootb SharePoint search for the word 'Management', either in-library or Site-wide, produces dozens of results.
However, when I use the Modern Search web parts, I get 0 results, even for the same search terms that have produced results in the standard SharePoint search. No custom filters or query modification.
The SharePoint Search Query Tool tells me there are 84 results, plus 5 duplicates. 

**To Reproduce**
I'm having a very fundamental issue with the Modern Search web parts, and I feel like when I find what the silly mistake I've made is, I'll be facepalming and wanting to retreat from the internet for a year. But here I am all the same. 

Instructions followed from https://microsoft-search.github.io/pnp-modern-search/installation/ and https://microsoft-search.github.io/pnp-modern-search/scenarios/create-simple-search-page/
1. Version 4.9.2 drag'n'dropped to the App Catalog Site in one, uploaded to the other by a Global Admin. Solution is enabled and available on all Sites.
No errors on either classic or Modern management page.
2. On 1 tenant there is also the Learning Pathways solution, the other has no other solutions, enabled or otherwise. 
3. All 14 API permissions on -admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement approved in both.
4. Modern Team Sites configured for document management. 
5. 'set-sposite $site -DenyAddAndCustomizePages 0' on both
6. Don't know that it matters, but on the client tenant I have a single content type published from the ContentTypeHub, whereas on my Dev tenant it’s a straight Site Content Type. 
7. I've created a Site Page in the SitePages library, and created 'Modern-Search.aspx' page, 1 third left column, 2 thirds right.
8. Dropped a 'PnP Search box' and 'PnP Search results' webpart into the right column.
No config on the PnP Search box.
9. Config the Results webpart consists of selecting 'SharePoint Search' on page 1 and on page 3 'Connect to search results Web Part', connect to source 'PnP - Search box' and PnP - Search Box's properties - 'Search Query'.
10. While I plan to have a pnp search filters webpart later for refinement using properties mapped to RefinableStrings, I haven't added it yet. 
11. Search query template is unmodified {searchTerms}
12. Dummy files across 5 file types only at this point, not encrypted, uploaded days ago, appearing in the Search index and OOTB search experience.
13. Publish the page, attempt search. No results.

14. Things I've tried with little apparent modification in result:
	
	• Republishing the page
	• Deleting pnp webpart instances, publishing the page and adding them back in, republishing
	• Remaking the search page
	• Uninstalling, reinstalling sppkg. API permissions didn't need to be regranted
	• Same setup in a second tenant to confirm issue
	• Having 1 page for search box, another for search results. Set 'Send the query to a new Page' to On on Search box. I am taken to the new results page, but there are no results.
	• Adding a Search filters webpart, and connecting it to Results wp and vice versa 
	• After a bit of faffing about enabling old features, I have a Classic Search page with a refinement panel doing pretty much exactly what I need from the Modern page, normal search results, with the refinablestring00-05 refiners based on properties mapped to custom site columns. 

Adding a second Pnp Search results webpart to the same page configured with SharePoint Results as the results source to Microsoft Search does an odd thing on my Dev tenant, a single result, for : 'SharePoint 2007 guide part2{guid}.doc' is displayed prior to a search term being entered. This document is in the root of my OneDrive. 
After hitting return or the arrow next to the search box, again, no change in either search results box. 

Again, I feel like I've done something akin to chasing engine timing when maybe the key isn't in the ignition or something, be as kind as you can :)

**Expected behavior**
I expected the same initial search results as the OOTB search experience returned.

**Screenshots**

![ModernSearch results 00](https://github.com/microsoft-search/pnp-modern-search/assets/25006517/e21b9cd4-000f-4619-ad3c-72f6440657c1)
![ModernSearch results 01](https://github.com/microsoft-search/pnp-modern-search/assets/25006517/e4e51ad8-42de-4491-8c6e-32dee92c0203)
![ModernSearch results 02a](https://github.com/microsoft-search/pnp-modern-search/assets/25006517/86ce02b2-5c33-4465-9e2f-dc3e208af56a)
![ModernSearch results 02b](https://github.com/microsoft-search/pnp-modern-search/assets/25006517/22a10bb9-5421-489b-a120-0f156b5ed495)
![ModernSearch results 02c](https://github.com/microsoft-search/pnp-modern-search/assets/25006517/446f5146-4a17-4771-b8bd-a904f6dddca4)
![ModernSearch results 03](https://github.com/microsoft-search/pnp-modern-search/assets/25006517/83f97671-1188-41c5-af80-9c737d1036a8)
![ModernSearch results 04](https://github.com/microsoft-search/pnp-modern-search/assets/25006517/c9b9d953-7539-4dc5-b774-42d662c3ff11)

![ModernSearch results 05](https://github.com/microsoft-search/pnp-modern-search/assets/25006517/f5f59ca8-3f5a-4b94-a57e-279c206bc31f)

**Desktop (please complete the following information):**
Windows 11, Chrome Version 116.0.5845.97 (Official Build) (64-bit)

**Additional context**
I have reproduced this on 2 other tenants accessible to me. I feel like there's a config step I've somehow missed.

**Comment by jhholm** [comment]
By looking at the screenshots, your search result webpart is not connected to the search box, but rather to itself.

**Comment by simoniscasesensitive** [comment]
> By looking at the screenshots, your search result webpart is not connected to the search box, but rather to itself.
> 
> The part of the guide that tells about how to do the connection: https://microsoft-search.github.io/pnp-modern-search/scenarios/create-simple-search-page/#connect-the-web-parts

aaand there is it. Configured the wrong box. Now to disappear into a hole forever.

**Comment by kasperbolarsen** [comment]
Join the club, we had all tried that one :-)
