### ISSUE TITLE
Custom Search Extensibility Library is not rendered

### ISSUE THREAD

**Issue by arunakshi** [microsoft-search/pnp-modern-search#32]
I downloaded the sample solution **search-extensibility-library**, unzipped it. I did the following steps:

1. npm install
2. gulp --ship
    gulp bundle -- ship
   gulp package-solution --ship

I deployed the package to my tenant app catalog. After that I added the search results webpart into my page and in the Layouts section, I configured for the Custom Result Type. In one of the Result Type configuration, I used the following template to map my new library component which I deployed earlier. 

<my-custom-component my-string-param="{{Title}}" 
my-object-param="{{JSONstringify MyObj}}"></my-custom-component>

This is my template mapping based on ContentTypeId:
![image](https://user-images.githubusercontent.com/12812202/70434611-f82e2380-1a84-11ea-999e-94dc3e5445a4.png)

After saving the page, a place holder is created on the page but it is not rendering into CustomComponent. I followed the documentation as it is. The markup is as follows after rendering the templated from result types: 
![image](https://user-images.githubusercontent.com/12812202/70453626-61c02900-1aa9-11ea-9c31-024810237d99.png)

**Comment by FranckyC** [comment]
Hi @arunakshi, I'm not able to reproduce this error. When I add a custom component in a result type, it is actually rendered:

![image](https://user-images.githubusercontent.com/5659122/70525254-ed22d400-1b14-11ea-9b94-2f40bb9eba02.png)

**Comment by arunakshi** [comment]
Hi @FranckyC, Thank you very much for your reply. I did my tests again with releases version and it is rendering now from my custom extensibility library. 

I am closing this issue. 

Thanks again.
