### ISSUE TITLE
Modern search result spfx webpart keeps firing PostQuery and browser errors Out of Memory

### ISSUE THREAD

**Issue by manishkaushal2015** [microsoft-search/pnp-modern-search#320]
#### Category
- [x] Question
- [x] Bug

Browser: Chrome ver 83.0.4103.106
SP Tenant type: Developer tenant
Deployed sppkg file pnp-modern-search-parts.sppkg from the released version 3.13.0.0
Webpart configuration:
SearchResults webpart connected to SearchBox. For SearchResults configuration please refer to second screenshot.
![Error_SearchResults2](https://user-images.githubusercontent.com/12091712/85082827-65302c00-b213-11ea-90a1-2bd8e875afb8.JPG)
![Search_configuration](https://user-images.githubusercontent.com/12091712/85085250-9829ee00-b21a-11ea-9d1f-565e60077c5b.jpg)

#### Expected or Desired Behavior
Search box connected to SearchResults webpart. User searching in search box should yield results in Search Results webpart. 

#### Observed Behavior
Search results appear on user input in search box but search results webpart keep loading. Record counts are shown correctly in Vertical Search webpart. Results webpart keeps firing search Post Queries without stopping. Please refer to screenshot attached for the number of queries fired for almost 3000 search results. The result is that it finally bringing down the webpage to out of memory. Tested on Chrome browser,  got out of memory error. Removed webparts re-added.
Can you please direct me to a way of finding the underlying issue? Could it be due to a recent commit in code version 3.13?

#### Steps to Reproduce########
Downloaded package pnp-modern-search-parts.sppkg released version 3.13.0.0
Deployed this package to tenant apps catalog, deployment setting available to all sites enabled.
Configured Search Box, Search Results and Refiner webparts as directed in the documentation.
Search results webpart should display results and not keep displaying data loader till the page dies.

Looking forward to your prompt help.

**Comment by manishkaushal2015** [comment]
Found the root cause but not sure about the fix. 

Root cause: When **Search Box** webpart is connected to **Search Results** this issue occurs. If I connect the results webpart to Page Environment data source and querystring as value then it works good. Can someone please help me how to resolve this issue?

**Comment by wobba** [comment]
@manishkaushal2015  I cannot repro. New page, dropped a search box and result part on the page. Edit result part, enter something in the query keywords box, click the ... and connect it to search box. Publish the page and all works.

![image](https://user-images.githubusercontent.com/51104/85158908-17d8ac80-b25d-11ea-8dcf-b460f89856a6.png)

**Comment by manishkaushal2015** [comment]
Found the issue, it was configuration issue on my part. I connected search box webpart two way to search results webpart and that is what was causing it. Closing this now.
