### ISSUE TITLE
Graph searching does not support sovereign/National Cloud Graph endpoints

### ISSUE THREAD

**Issue by mikevasiloff** [microsoft-search/pnp-modern-search#3210]
**Version used**
Ex: 4.9.3

**Describe the bug**
When using the web parts in a National Cloud (such as GCC-High (IL4) or DoD), the Graph API calls are still going to the _commercial_ (**.com**) endpoint instead of the [National Cloud Graph API endpoints](https://learn.microsoft.com/en-us/graph/deployments).

**To Reproduce**
Just select the "Microsoft Search" option instead of "SharePoint Search" and you'll see the error message: "Access token validation failure. Invalid audience."

**Expected behavior**
Graph searching should work in GCC-High and DoD National Clouds just like it does for the commercial cloud.

**Screenshots**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/8918397/5963bf7a-4954-441f-854a-5c9c41b80a3b)

**Desktop (please complete the following information):**
 - Browser: edge (v116.0.1938.62) & chrome (v116.0.5845.111)

**Additional context**
One option (among others) of checking which Graph endpoint to use  is to check the `this.context.pageContext.legacyPageContext.msGraphEndpointUrl` property which returns the endpoint for the current cloud.

**Comment by wobba** [comment]
Thank you for pointing this out.

**Comment by wobba** [comment]
Fixed with #3398
