### ISSUE TITLE
Date range in filter appending wrong value in query url for example if i select 17-08-2023 the url showing 16-08-2023(simply its appending 1 day less in url bar) so refined results also get affected

### ISSUE THREAD

**Issue by ncmadhan1989** [microsoft-search/pnp-modern-search#3211]
### Check existing issues before logging new ones
If you are not using the latest version, triage your issue with the latest version before logging as we won't provide patches to older versions.

### Issues related to data mapping, web part setup etc, and SharePoint columns to crawled properties to managed properties should be asked in the discussion section.

**For any question regarding Web Parts usage, please use the ["Discussions"](https://github.com/microsoft-search/pnp-modern-search/discussions) tab instead of creating a new issue.**.

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
Ex: 4.9.3.0

**Describe the bug**
A clear and concise description of what the bug is. Keep questions and bugs related to the web parts. If the issue relates to KQL or question around crawled and managed properties please use [Microsoft TechCommunity](https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev). Which means, if you experience the same behavior in classic web parts, then it's not an issue with PnP Modern Search 😉

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to '...' in Search filters webpart
2. Click on '....' select the date range, in the query string its appending one day less for eg if I select 29/08/2023 and 30 /08/2023 query string url be(/SitePages/SearchLibrary.aspx?f=%5B%7B"filterName"%3A"CreatedOWSDATE"%2C"values"%3A%5B%7B"name"%3A"2023-08-28T18%3A30%3A00.000Z"%2C"value"%3A"2023-08-28T18%3A30%3A00.000Z"%2C"operator"%3A4%7D%2C%7B"name"%3A"2023-08-29T18%3A30%3A00.000Z"%2C"value"%3A"2023-08-29T18%3A30%3A00.000Z"%2C"operator"%3A5%7D%5D%2C"operator"%3A"and"%7D%5D)
4. Enter setting A, B, C
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
![Untitled](https://github.com/microsoft-search/pnp-modern-search/assets/44596222/c6fbc671-d730-4d84-b339-76ddd6e57a0e)

**Comment by kasperbolarsen** [comment]
Please complete the Issue form, otherwise we will not be able to assist.

**Comment by ncmadhan1989** [comment]
> Please complete the Issue form, otherwise we will not be able to assist.

I have updated with screenshot, pls let me know ,if anything more needed

**Comment by wobba** [comment]
You cannot date query on `CreatedOWSDATE`, which is a text field. You need to use `Created`.

**Comment by ncmadhan1989** [comment]
> You cannot date query on `CreatedOWSDATE`, which is a text field. You need to use `Created`.

Thanks for your reply ,I tried with Created managed property as well ,but for that also i am getting same result,query string is append with one day less, if u check the query string change itself you came to know,pls help me on the same,struggling a lot due to this

**Comment by kasperbolarsen** [comment]
Could sound like the usual "issue" that timestamps are in UTC(0) .
I'll try to set up a test case and revert

**Comment by kasperbolarsen** [comment]
once the query string is cleaned up it looks like this:
/SitePages/SearchLibrary.aspx?f=[{"filterName":"CreatedOWSDATE","values":[{"name":"2023-08-28T18:30:00.000Z","value":"2023-08-28T18:30:00.000Z","operator":4},{"name":"2023-08-29T18:30:00.000Z","value":"2023-08-29T18:30:00.000Z","operator":5}],"operator":"and"}])

The From DateTime is set to 2023-08-28T18:30:00.000Z so it seems like you are 5h30m ahead of UTC so in India or Sri Lanka. When you create a document at 04.00 on 1 Januar the created date return in the search result will be 22.30 31 Dec as the datetime stamps in search always are in URL. In the document library the created date will read as 1 January as that date is corrected for your timezone.

So the query filter actually makes lots of sense as it offsets the search by our timezone.

I hope this explanation makes sense, time zones are a bitch.

**Comment by ncmadhan1989** [comment]
> once the query string is cleaned up it looks like this:
> 
> /SitePages/SearchLibrary.aspx?f=[{"filterName":"CreatedOWSDATE","values":[{"name":"2023-08-28T18:30:00.000Z","value":"2023-08-28T18:30:00.000Z","operator":4},{"name":"2023-08-29T18:30:00.000Z","value":"2023-08-29T18:30:00.000Z","operator":5}],"operator":"and"}])
> 
> 
> 
> The From DateTime is set to 2023-08-28T18:30:00.000Z so it seems like you are 5h30m ahead of UTC so in India or Sri Lanka. When you create a document at 04.00 on 1 Januar the created date return in the search result will be 22.30 31 Dec as the datetime stamps in search always are in URL. In the document library the created date will read as 1 January as that date is corrected for your timezone.
> 
> 
> 
> So the query filter actually makes lots of sense as it offsets the search by our timezone.
> 
> 
> 
> I hope this explanation makes sense, time zones are a bitch.
> 
> 

Is any way to set timezone to utc 0 from the filter webpart? By overriding default browser timezone ...since i have set site timezone as utc 0 not as utc +5.30, so we can only do something from webpart end to overcome this as per my knowledge

**Comment by wobba** [comment]
Time zones and SharePoint is a nightmare as the combination user and site setting never lets you know what some scenario expects to use. If we disregard the time portion, or use browser time zone, someone will complain as well, as they expect dates adjusted to the sites setting.
