### ISSUE TITLE
Filters do not work with pagination.

### ISSUE THREAD

**Issue by jindalv10** [microsoft-search/pnp-modern-search#322]
**Version used**
Ex: 3.11

**Describe the bug**
Filter do not work when navigate to second or third page in results web part. Manually navigate to the first page in the results page.

1. Go to create new search page and deploy search box, search filters and search results.
2. Click on filters and add mapped filter values.
3. Scroll down and go to second page on search results pagination and then use filter to filter the results webpart. 
4. After apply filter, pagination do not automatically go back onto the first page.

**Expected behavior**
Search results navigates back to first page in in results web part. 

**Desktop (please complete the following information):**
 - Browser : Chrome and Edge

**Comment by wobba** [comment]
Duplicate #332
