### ISSUE TITLE
Search Verticals web part is not responsive

### ISSUE THREAD

**Issue by kdeeski** [microsoft-search/pnp-modern-search#324]
The search verticals web part doesn't wrap or resize on a mobile device. It would be great to be able to provide a full responsive search experience on mobile.

**Comment by wobba** [comment]
Should wrap as fixed in #119 

Screenshot is from the latest version.

![image](https://user-images.githubusercontent.com/51104/85372746-91f58380-b532-11ea-961b-506b2268cd0a.png)
