### ISSUE TITLE
Webpart not available after upgrading to last release

### ISSUE THREAD

**Issue by Mathieu-Valmont** [microsoft-search/pnp-modern-search#3254]
**Version used**
4.9.3

**Describe the bug**
I just upgraded the App to the last release on my dev environment and since I did that pnp seach webparts are not anymore available nor showing when trying to add them on a page.

Existing webparts (added prior to the upgrade) are still showing but new ones cannot be added.

**To Reproduce**
Go to "App management" in SharePoint Admin, upload the new package, enable it.
I also consented to Api Access for the first time.

**Expected behavior**
Being able to use pnp search webparts on upgraded or new sites.

**Screenshots**

**Desktop (please complete the following information):**
Edge

**Additional context**
I tried changing my language in my profile and in my browser just in case, but same issue : app is installed on site but webparts are not available

**Comment by kasperbolarsen** [comment]
The PnP Modern Search Web parts app is not available in "add App" in the gear/cog menu on a new site collection?

**Comment by wobba** [comment]
What version are you upgrading from?

**Comment by Mathieu-Valmont** [comment]
I upgraded from 4.7.0.0.
I  uploaded the last version from the modern "Manage apps" page on SharePoint Admin Center, enabled the App, consented Api access. I noticed that I let "Added to all sites" to true and I changed it afterward.

@kasperbolarsen, adding the app on a new site or upgrading one that already had the app installed works fine and apparently without error.
But, when I try to add a pnp search webpart on a page, there are just not in the list of available webparts (same behavior on new sites and upgrade ones).

**Comment by Mathieu-Valmont** [comment]
I made another test by enabling the app catalog at the site collection level on a newly created site on which I had the issue described.
I then removed on this the enabled 4.9 version of the app (the one deployed globally from tenant app catalog), uploaded and deployed the 4.7 version in the site app catalog, and finally added the local App on the site. Webparts are showing.
If I locally deploy on the site app catalog the 4.9 version, webparts go away.

**Comment by wobba** [comment]
See release noted from v4.8. I'l move them to v4.9 as well.

**Comment by Mathieu-Valmont** [comment]
Indeed, it was the issue.
I removed the App from the tenant App Catalog and add it again.
On a site I had to remove and re-add the app to see webparts, while on another one they came back automatically.
Thanks to all of you for your time 👍
