### ISSUE TITLE
Search results are not working

### ISSUE THREAD

**Issue by srinutamada** [microsoft-search/pnp-modern-search#327]
I installed modern search package in my site collection and added search results web part. I configured the web part with default configurations. It was working till last day but from today morning I am getting below error. There is no change in search configuration or data. Everything is same for more than a month. Please help.

Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}} Data: {"response":{},"status":400,"statusText":"","isHttpRequestError":true}

**Comment by kachihro** [comment]
Duplicate - this is being tracked in #325
