### ISSUE TITLE
PNP Search V4 Modern - PNP Search webparts properties

### ISSUE THREAD

**Issue by Stelle80** [microsoft-search/pnp-modern-search#3270]
**Version used**
4.2.3.1

**Describe the bug**

Getting issue while trying to view all items of auto populated 'selected properties' within webparts.  The issue persists even after upgrading to latest version 4.9.3.0

**Screenshot**
![sproperties](https://github.com/microsoft-search/pnp-modern-search/assets/81336938/8fb0c4e3-4763-44d8-ab66-1eb28a931213)

**Expected behavior**
To display all the properties either selected or unselected items. 

**Desktop (please complete the following information):**
 - Both chome and edge

**Comment by kasperbolarsen** [comment]
please see https://github.com/microsoft-search/pnp-modern-search/issues/2944

While your expectation is reasonable it is not something the project can provide.
