### ISSUE TITLE
PNP modern search parts started giving error

### ISSUE THREAD

**Issue by sripak** [microsoft-search/pnp-modern-search#328]
**Version used**

We started getting error in all the places across our tenant where pnp odern search parts are used. Out of the box search web part are working just fine. 

Error Description : Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}}

**To Reproduce**
1. Go to sharepoint online site and type any keyword in search box
2. Click on search
3. this will re direct to search page where pnp search components are configured
4. Getting error : Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}}

**Expected behavior**
Should display search results based on search [[query]](url)

**Screenshots**

Please help to resolve this asap. Started getting this error from today morning

**Comment by kachihro** [comment]
This is being tracked in #325
