### ISSUE TITLE
Specific search in one drive folders

### ISSUE THREAD

**Issue by Patodif** [microsoft-search/pnp-modern-search#3280]
Hello, I am trying to make a search engine but only for a certain OneDrive folder, when I use the expression {searchTerms} path:https://xxxxxxx-my.sharepoint.com/:f:/g/xxxxxxxxx/xxxxxxxxxxxx/Epd8xhwSS3dNmcYb1KIIJJkBrbNcfqhSnp2dMmgDq2055g?e =DVfhMN, I don't get any results. Only by using {searchTerms} I can see all the files. I need to restrict the search to a local file and a shared file.
 I have version 4.0

**Comment by kasperbolarsen** [comment]
Doublet
