### ISSUE TITLE
500 error code (internal server error) "The search request cannot be empty".

### ISSUE THREAD

**Issue by stenssonoscar** [microsoft-search/pnp-modern-search#3285]
**Version used**
Version: 4.9.3

**Describe the bug**
I keep getting this message: "The search request cannot be empty" Error code 500 (internal server error) in Modern Search Web Part. 

I have configured the Modern Search web part to display search results on my SharePoint site. However, I keep encountering the following error message.

What makes this issue particularly puzzling is that it does not always result in the 500 error response. Sometimes, the Modern Search web part works as expected, delivering search results without any errors. However, on other occasions, it triggers the "The search request cannot be empty" error. This inconsistency has left me perplexed, as it seems to occur randomly.

To address this issue, I have updated the Modern Search web part to the latest available version in an attempt to resolve any potential bugs or issues. Despite the update, the problem persists. I have reviewed and validated the configuration of the Modern Search web part, including the query template and data source properties. I have checked the query text source and verified that it is correctly set. I have inspected the query template for any potential issues with variables or dynamic values. I have attempted to use a static query in the queryTemplate property as a test, but the error persists. I have cleared my browser cache to rule out any caching issues.

Given the intermittent nature of this issue and the fact that I've updated to the latest version of the Modern Search web part, I'm unsure about what might be causing it. If anyone in the community has encountered a similar problem or has insights into potential solutions, I would greatly appreciate your assistance.

Additionally, if there are specific troubleshooting steps or configuration details that I may have missed, please feel free to share them with me.

Thank you in advance for your help and expertise. I look forward to your valuable input in resolving this issue and making the most of the Modern Search web part in SharePoint Online.

**To Reproduce**
This error seems to occur randomly.

**Expected behavior**
The solution should display search results from a document library in a SharePoint site. The PnP search filters should make it possible to apply filters for the user to configure in order to show correct values in the search results.

**Comment by kasperbolarsen** [comment]
Hi Oscar,
This one might be hard to debug. Error code 500 is a backend error code, yet it might be caused by something in one of the web parts, but only sporadic.... 
Is the issue isolated to just one site collection, or do you see the same error on multiple site collections?
Can you set up the same query in the classic search center and do you see the same error?
Using the same query but in MS search, same error?

Are you having issues with heavy throttling on your tenant?

Those are the questions I would start looking at if I had the issue, hopes it can lead to some useful findings :-)
