### ISSUE TITLE
Results suddenly are not in order of relevance for some users.

### ISSUE THREAD

**Issue by EricJax** [microsoft-search/pnp-modern-search#3291]
**Version used**
Ex: 4.5.4.0

**Describe the bug**

Search results for some users are no longer in order of most relevant. When comparing search results between me and user with this issue, we get the same result counts, but in different orders of relevance. My page one results make sense, and are expected; their expected results (search term in page/file name) appears only starting on page four.

This happens only for some users, so far.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. I don't know how you would reproduce this.

**Expected behavior**
Most relevant results appear at the top of page one for all users.

**Screenshots**
Due to company security policy, I can only post in a separate personal account; so I can't get screenshots from work environment.

**Desktop (please complete the following information):**
 - Browser:  Edge (all users)

**Additional context**
This issue arose today after several months of use with no issue. I made a change to KQL query recently, but even after reverting, and even rolling back the SharePoint page to a previous version, the issue still persists.

**Comment by kasperbolarsen** [comment]
Without knowing which data source you are using and how the query is constructed, it is almost impossible to assist. 
However, any possibility that you can use any of the tools here https://microsoft-search.github.io/pnp-modern-search/using-query-tools-to-verify-issues/ to test if the problem is in the PnP Modern Search Web parts or in the API?

**Comment by EricJax** [comment]
This morning, the issue was resolved on its own. Also, before that, we found the same results were occurring when performing search in SharePoint search when viewing an actual library; so it appears to be a Microsoft issue under the hood.

So we can close this bug  report.

Thank you for your response!
Eric
