### ISSUE TITLE
SP2019 on premise

### ISSUE THREAD

**Issue by billfredtom** [microsoft-search/pnp-modern-search#33]
Does this work with SharePoint 2019 on Premise? 

I'm aware of this - https://github.com/SharePoint/sp-dev-solutions/releases/tag/ms-2019-08-14 which appears to be an older version of this new repo, but it's incomplete and only has the results webpart with static search query available, and attempts to build the src in the zip has a bunch of version conflicts. 

Thanks for any info.

**Comment by FranckyC** [comment]
Hi @billfredtom Unfortunately no, there is no similar solution for SP2019 due to SPFx version limitation that does not include the dynamic data feature. For now there is no plan to make the current solution compatible for on-premises scenarios until Microsoft upgrade the SPFx version.

**Comment by billfredtom** [comment]
Thanks for the response. Cheers.

**Comment by rtonerii** [comment]
I wanted to see if there were any new plans on making this available for on-premises?

**Comment by wobba** [comment]
@rtonerii Not currently via this project, because SPFx version for on-prem is on v1.4., and it lacks dynamic data support needed for web-parts to communicate. If SP-onprem magically get's a bump to whatever version we use online, then it can work.

See https://github.com/pnp/sp-dev-solutions/issues/355#issuecomment-725252440 for a branch version for on-prem.

**Comment by rtonerii** [comment]
> @rtonerii Not currently via this project, because SPFx version for on-prem is on v1.4., and it lacks dynamic data support needed for web-parts to communicate. If SP-onprem magically get's a bump to whatever version we use online, then it can work.
> 
> See [pnp/sp-dev-solutions#355 (comment)](https://github.com/pnp/sp-dev-solutions/issues/355#issuecomment-725252440) for a branch version for on-prem.

Thank you,
I'll look into it!
