### ISSUE TITLE
Filter Webpart: Translation of taxonomy values not working

### ISSUE THREAD

**Issue by EbSe** [microsoft-search/pnp-modern-search#3302]
**Version used**
4.9.3

**Describe the bug**
I have a multilingual site (german and english, german es base language). In the document library I use a taxonomy field. The values of the term are translated into german and english. On my search page I have a connected search box, search results and filter webpart. In the search results webpart the "Enable localization" flag is on.

Now when I start a search with an english browser language on a translated english sharepoint page all webparts and controls within are translated correctly into english. Except the values of the taxonomy field within the filter webpart are still shown in german.

For the managed property I use a system refinable string properte and mapped the ows_XXX crawled property.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Create a doc library with a metadata field (values in termstore translated to german and english).
2. Map the crawled property to a refinable string managed property.
3. Create a site (base German) and activate english as second language
4. Create a search page an add seach box, results and filter webpart
5. In the filter webpart use the managed property from above as filter
6. Create a translation of the search page

**Expected behavior**
The values of the taxonomy field in the filter webpart should be translated into english.

**Screenshots**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/16380149/06408ff3-4d69-4145-903d-9bef52e6a14f)

Termstore:
![image](https://github.com/microsoft-search/pnp-modern-search/assets/16380149/040ae08c-bdbf-4a60-959b-d0a098c040e0)

**Desktop (please complete the following information):**
 - Browser Edge

**Comment by wobba** [comment]
You need to map to ows_taxid_ properties as per https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-results/#miscellaneous-taxonomy-values-dynamic-translation
