### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by paalolav** [microsoft-search/pnp-modern-search#3304]
**Version used**
Version 4.9.3

**Describe the bug**

Using a refiner for date/time.

When using {{getDate}} in a custom template, we struggle to display the date in a native language (Norwegian in this case).
This worked like a charm in version 4.9.
Even though we configure Language of the search request to Norwegian in the UI, it still displays the date in English.

**To Reproduce**
1. Do any KQL search
2. Pick the built in template Details List
3. Change the Search request to a different language, also make sure your browser and profile is in another language than English.
**Expected behavior**
To show the UI in your native language.
What happens now:
The date will display in English format, not in your native language's format.

**Screenshots**

![Screenshot 2023-10-23 at 13 37 38](https://github.com/microsoft-search/pnp-modern-search/assets/55249575/ef818fcd-75f9-4c6d-aacd-2b8e7476b9e7)

**Desktop (please complete the following information):**
Any browser, PC or mac.

**Additional context**
It worked in previous versions of PnP Modern Search. Bug appeared in version 4.9.3, as far as I can tell.

**Comment by wobba** [comment]
Fixed with #3400
