### ISSUE TITLE
Sorting DDLB state not retained on paging

### ISSUE THREAD

**Issue by quarterhorse** [microsoft-search/pnp-modern-search#331]
**Version used**
3.13.0 - May 2020

**Describe the bug**
When sorting by the drop down list box identifying the sort fields, when paging the drop down selection and direction are not retained and reverts to the default.

**To Reproduce**
Add multiple sort columns to the drop down, select a a non-default column, click on the order to change it to Z to A, and issue a query resulting in multiple pages of results.  Click to a different page and notice the default selection and the sort order icon

**Expected behavior**
The sort column and direction should be retained between pages

**Screenshots**

Initial sort selected:
![image](https://user-images.githubusercontent.com/36413662/85409028-44c5e180-b533-11ea-9e24-2da77920b67f.png)

Click on result page 3:   
![image](https://user-images.githubusercontent.com/36413662/85409094-5c9d6580-b533-11ea-9bd4-cc7e34f9ee07.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]  Chrome

**Additional context**

**Comment by wobba** [comment]
Ack
