### ISSUE TITLE
Web parts fails for guest users without read access to the App Catalog

### ISSUE THREAD

**Issue by kasperbolarsen** [microsoft-search/pnp-modern-search#3310]
**Version used**
4.9.3

**Describe the bug**
A number of users get the error msg for every PnP Modern Search Web part, and some do not. Those getting the error were all guest accounts, and I could solve the problem by giving the guest users read access to the App Catalog (it seems like the default is "everyone except external users" 
The App is NOT added to all site collection by default

I am not sure if this a PnP Modern Search web parts issue or just a common issue with any SPFx solution?

**Desktop (please complete the following information):**
 - Browser any

The error looks like this in Dev tools

![CDNbug](https://github.com/microsoft-search/pnp-modern-search/assets/20593570/33c00cf7-07fa-49dc-b2a0-f07096ab89a7)

**Comment by wobba** [comment]
See https://web.archive.org/web/20220420021131/https://laurakokkarinen.com/sharepoint-online-guest-user-troubles-and-how-to-get-past-them/. The user needs access to the app catalog where the web parts are served from. Or access via CDN.

**Comment by wobba** [comment]
Well.. it's a generic SPFx issue, not modern search one. But all documentation helps :)

**Comment by kasperbolarsen** [comment]
On it

**Comment by kasperbolarsen** [comment]
fixed by #3319
