### ISSUE TITLE
Search results in new page - how to get working?

### ISSUE THREAD

**Issue by TheRealStriff** [microsoft-search/pnp-modern-search#3320]
PNP Modern Search v4 wanting to have the results go to a different page.
Testing this out for a new intranet, and request is to have search results appear not on the home page.

I have the Search box on the home page, set "Send the query to a new page"
Have the url under the "Page URL field:

The new page, I've added the PNP Search Results web part.
But in page 3 of 4 of the settings. - Available connectors
Select "use input query text" to on.
Dynamic value > Connect to source. The PNP Search Box is not an option...

I'm wondering how you actually configure the search results to go to a different page than the search box?

**Comment by kasperbolarsen** [comment]
Perhaps try something like this:
The search box will add a search tag to the URL and the receiving Result web part will grab it from the URL
![image](https://github.com/microsoft-search/pnp-modern-search/assets/20593570/c992abb4-5899-40ea-ab72-f463aa4b3edf)

**Comment by TheRealStriff** [comment]
> Perhaps try something like this: The search box will add a search tag to the URL and the receiving Result web part will grab it from the URL ![image](https://user-images.githubusercontent.com/20593570/279689503-c992abb4-5899-40ea-ab72-f463aa4b3edf.png)

Thanks that worked, thought I tired that, but guess not!....
Much appreciated,
