### ISSUE TITLE
Issue with SharePoint Video Stream Continuously Playing After Closing Preview

### ISSUE THREAD

**Issue by Harshagracy** [microsoft-search/pnp-modern-search#3328]
**Version used**
 4.7.0 and tried in 4.4.1 too.

**Describe the bug**
I have enabled the preview feature for cards on my platform. The preview functionality works as expected. However, I have encountered a problem when displaying videos. The videos are store in SharePoint Library. After clicking on the preview, an iframe opens to play the video. The video plays correctly within the preview. The issue arises when I close the preview – the video continues to play in the background.

**To Reproduce**
Detailed steps to reproduce the behavior:
Select "Cards" from the layout. 
Write the query to fetch Videos from a library
Enable the preview feature for cards
Click on the card to open the preview.
Play the video within the opened iframe.
When it is still playing, Close the preview.

**Expected behavior**
After closing the preview, the video should stop playing as well the iframe should be removed from the DOM.

**Screenshots**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/14230498/25e727bd-8ac0-4e91-a045-e993ccca9a23)
On clicking of the cross icon, the video should stop playing as well the iframe should be removed from the DOM.

**Desktop (please complete the following information):**
 - Browser : Chrome

**Comment by wobba** [comment]
Same issue wth 4.9.3?

**Comment by Harshagracy** [comment]
> Same issue wth 4.9.3?

Hi Wobba, Yes. I tested it with  "4.9.3" and it is the same behavior.

**Comment by Harshagracy** [comment]
Hi @wobba , Is there an workaround for this issue?

**Comment by wobba** [comment]
No, someone has to look at the code and fix the issue to stop the video. Any developer with SPFx skills can contribute :)
