### ISSUE TITLE
View in Library

### ISSUE THREAD

**Issue by verdeterrejim** [microsoft-search/pnp-modern-search#333]
Please add a “View in Library” link to the search results hover panel that navigates to the document library where the document is found.  Currently, there is no clear way for the user to navigate to the document library where the document was found.  

This is a very useful feature of the original search results hover panel.  It is frequently the case that the document exists in a library with associated documents of interest.  

I have worked with customers on several search solutions and it is very common to see that they like going to the library where documents are found.

Without a “View in Library” link users will become frustrated by the lack of ease to navigate to the library where the document was found.

**Comment by wobba** [comment]
You can modify the template to suit your needs yourself. The managed property to use is `ParentLink` which takes you to the container of the item, library root or folder.
