### ISSUE TITLE
Persistent Search Results Issue: Unchanged After Box Reset

### ISSUE THREAD

**Issue by Aminehsppro** [microsoft-search/pnp-modern-search#3331]
Hello everyone ,I encountered a bug in my search box. After performing a search, I reset my box, but the results remain unchanged even after resetting.
<img width="399" alt="Capture4" src="https://github.com/microsoft-search/pnp-modern-search/assets/150242863/12176690-4f5c-4c03-9e19-e379e74f2279">
<img width="378" alt="Capture1" src="https://github.com/microsoft-search/pnp-modern-search/assets/150242863/f0e24413-c0c6-4734-bb5a-6cd35d58d992">
<img width="333" alt="Capture2" src="https://github.com/microsoft-search/pnp-modern-search/assets/150242863/8f696b1d-ab1f-47ed-8fd0-db062ff2a9f2">
<img width="315" alt="Capture3" src="https://github.com/microsoft-search/pnp-modern-search/assets/150242863/049923a2-c701-4793-b441-f32646dd2a90">
<img width="616" alt="Capture5" src="https://github.com/microsoft-search/pnp-modern-search/assets/150242863/e47438f4-4424-41d1-b7f5-24989971a30e">

**Comment by kasperbolarsen** [comment]
Which version are you using?
Can you share "page" 3 of your Search Results web part?

**Comment by Aminehsppro** [comment]
I removed the search box and added a new one without changing its settings. I simply connected it with the other web parts and I still get the same probleme. Note that I am using the latest version: 4.9.3 :/

**Comment by Aminehsppro** [comment]
It works with * as the default value.

Thank you
