### ISSUE TITLE
Document links don't open correctly in Sharepoint App (iOS)

### ISSUE THREAD

**Issue by bernhardk4t** [microsoft-search/pnp-modern-search#334]
**Version used**
3.13

**Describe the bug**
The links to the files in search result don't work in the iOS SharePoint App. A link in the webpart looks like this: 

**https://demo.sharepoint.com/sites/knowledge/Documents/?id=/sites/knowledge/Documents/testdocument.docx&parent=/sites/knowledge/Documents**

If I open this link from the iOS App it will show the files/folders in the library "Documents"

**To reproduce**

- Add a page with the search result webpart
- configure the webpart so it will show documents in the result
- open SharePoint App on iPhone/iPad
- open page with search result webpart
- click on document link
- the link opens the library

**Expected behavior**
I would expect that the Word/Excel/... file is opened directly

**Comment by abates100** [comment]
This should be re-evaluated as a bug as the same issue is currently occurring in browser results parts also in 3.13

**Comment by wobba** [comment]
See #343 for possible work around. And not a bug as I never considered mobile when implementing the current solution. So I'll keep it tagged as an enhancement. 😉

**Comment by wobba** [comment]
Added a check on userAgent, and if detecting mobile it will use the direct URL and not SPO preview URL.
