### ISSUE TITLE
Pnp-Icon Source not up to date compared to https://uifabricicons.azurewebsites.net/

### ISSUE THREAD

**Issue by julianulrichioz** [microsoft-search/pnp-modern-search#3344]
**Version used**
Ex: 4.9.3.0

**Describe the bug**
the pnp-icon tag names are at a older version then the official https://uifabricicons.azurewebsites.net/ names.
pnp-icon tag name "Link" in version 4.9.3.0 shows icon ODLink instead of Link.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to 'https://uifabricicons.azurewebsites.net/'
2. Search for Link
3. Add "<pnp-icon data-name="Link" aria-hidden="true"></pnp-icon>" to a Search Result WebPart (as Column or in a Custom Template) and compare the Link Icon from UIFarbicsicon and the shown Icon
Outputted by the Webparts is ODLink Icon

**Expected behavior**
to see the Link Icon 

**Screenshots**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/78954643/d188efbf-fd5d-41da-ae25-aeaea40625c2)
Expected Icon: 
![image](https://github.com/microsoft-search/pnp-modern-search/assets/78954643/7614fee1-6fa3-4452-ace7-dcc886de8f5d)

**Desktop (please complete the following information):**
 Microsoft Edge for Business Version 119.0.2151.58
Google Chrome Version 119.0.6045.125

**Additional context**
-

**Comment by wobba** [comment]
I think this is a SharePoint issue. The markup turns into `<i data-icon-name="Link" aria-hidden="true" class="root-304"></i>`. If SharePoint loads an older version of the font, then SPFx will not initialise again. When SharePoint updates to newer icons, then that will work automatically in the web part.
