### ISSUE TITLE
Refinement Panel Filter Managed Property Selector Column Width

### ISSUE THREAD

**Issue by quarterhorse** [microsoft-search/pnp-modern-search#335]
**Version used**
3.13.0 - May 2020

**Describe the bug**
When editing the refiners, the filter managed property column is very narrow and one cannot read the selected value or the options in the dropdown.

**To Reproduce**
Add a refinement panel and try to add a filtered managed property.

**Expected behavior**
One should be able to see what is selected and what is selectable as an option.

**Screenshots**
One has to hover over the ellipsis to know what column is selected and, once selected, the assigned value is obscured.

![image](https://user-images.githubusercontent.com/36413662/85411690-a76cac80-b536-11ea-884d-647f5ed91b5c.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]  Chrome

**Additional context**

**Comment by wobba** [comment]
This is unfortunately a side effect of the controls we are using. If you zoom out and make your window wider it should be better.
