### ISSUE TITLE
Empty href attribute on card location

### ISSUE THREAD

**Issue by gabbsmo** [microsoft-search/pnp-modern-search#3359]
**Version used**
Ex: 4.9.3

**Describe the bug**
The card layout displays the result's containing site above the title. This is rendered as an `<a>` element, but with an empty href attribute.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Add a results web part
2. Change layout to card
3. Search for news items (i.e. PromotedState=2)

**Expected behavior**
Since the location is rendered as a link, I expect it to go somewhere. If it is a site title, I expect to go to that site.

**Desktop (please complete the following information):**
 - Browser: Microsoft Edge
 - OS: Windows 10

**Additional context**
I tried setting the data-location attribute on the pnp-documentcard component (i.e. data-location="foobar") but it seems to have no effect on the rendering. I also looked at the default mappings and could not see anything that could provide the data needed for a clickable location, such as SPWebUrl, SPSiteUrl or ParentLink.

**Comment by kasperbolarsen** [comment]
Hi Gabriel,
replace 
{{SPSiteUrl}}
with
{{SPSiteURL}}"
in "Location" in "Manage Card Fields"

and it should be resolved.

**Comment by kasperbolarsen** [comment]
I'll ensure this is fixed asap, unless you want to have a go at it?

**Comment by gabbsmo** [comment]
I will try and see if I can get it done tomorrow.

**Comment by gabbsmo** [comment]
@kasperbolarsen tried to follow your contribution process. Let me know if I got anything wrong.

**Comment by wobba** [comment]
Fixed with #3368
