### ISSUE TITLE
Add sorting by popularity

### ISSUE THREAD

**Issue by bernhardk4t** [microsoft-search/pnp-modern-search#336]
**Is your feature request related to a problem? Please describe.**
A customer requested that most popular files are shown. The standard Highlighted Content Webpart was not the right choice (not enough styling/display options)

**Describe the solution you'd like**
Sorting is possible by managed properties, but it seems that "Popularity" is not available

**Describe alternatives you've considered**
If possible add a way to sort files (ascending/descending) by popularity (most clicked).

**Comment by wobba** [comment]
You can change the result source id to `97c71db1-58ce-4891-8b64-585bc2326c12` which is the old popular result source. Haven't tried it in a while, but it does not correspond to the OOB ranking which is not exposed to the classic SharePoint search API.

You can also sort by `ViewsRecent` which is what `Trending` in HCWP is.

**Comment by bernhardk4t** [comment]
Thanks, that works! One additional comment:
While editing the sort order in the search web part there's a dropdown where the sortable managed properties are displayed. I  checked the values in the dropdown and "ViewsRecent" is not listed (at least not in my environment). But manually entering the value will work.

**Comment by wobba** [comment]
There is no good or even official API to retrieve all properties from the schema, so it is what it is - leaving you for manual entry for some cases :)
