### ISSUE TITLE
Paging not working - Version 4.9.3.0

### ISSUE THREAD

**Issue by BMQMATOS** [microsoft-search/pnp-modern-search#3369]
**Version used**
Ex: 4.9.3

**Describe the bug**
There seems to be a bug with the Paging feature regarding the PnP - Search Results Web part. It is not working for a List, Details List or Cards View

**To Reproduce**
1. Add a PnP - Search Results Web part
2. Configure the web part in a way that the number of results returned is more than the number defined under the Paging options.
3. Navigate on the Paging options at the bottom of the page
4. Notice that no matter what page you click or arrows, the results never change. 

**Expected behaviour**
The expected behaviour is to see a new set of results every time we click on a new page or arrow. The results section is not being refreshed.

**Screenshots**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/22307613/0da679d4-b3f6-402a-b959-d771fd60090b)
In the screen shot you can see that there are 3 results. I configured the web part to show only two results at a time. The first page shows two results correctly. The expectation is if I click on page 2, that I will see the 3 results, i.e., the other item that is missing.

**Desktop (please complete the following information):**
 - Chrome - Version 119.0.6045.160 (Official Build)  (64-bit)

**Comment by wobba** [comment]
Can you share your exact setup of page size? And is it working for any of the views? Most likely it's an API issue - as the result count coming back which is used to build the pagination is very inaccurate. The best is likely to have a pagination control which allows you to go to next page only.

**Comment by kasperbolarsen** [comment]
closed due to inactivity on OP side
