### ISSUE TITLE
Search Results webpart suddenly not working today, the error is "Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}}"

### ISSUE THREAD

**Issue by apzl808** [microsoft-search/pnp-modern-search#337]
it's working in past a few month, just start today, it's not working, is there some changes from Microsoft ?

"Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}}"

**Comment by jcharikofsky** [comment]
I had several clients report this also in the past few hours. I updated their controls to the latest release (3.13) and the error seems to be resolved.

Hope that helps.

**Comment by apzl808** [comment]
thanks jcharikofsky,

I did update latest release (3.13), the issue is same, 
we are using : 
Select Page Environment as 'Connected to source'
Select Query String as 'Page environment's properties'
Select Query parameters as 'Query string'
Select 'What ever user defined string' as 'queryParameter's properties'

**Comment by wobba** [comment]
Tracked in #325 and please check the issue list before reporting.
