### ISSUE TITLE
Search Filters Webpart with Managed Metadata Field showing strange values/Guids

### ISSUE THREAD

**Issue by EbSe** [microsoft-search/pnp-modern-search#3371]
**Version used**
Ex: 4.9.3

**Describe the bug**
With no change in our configuration of the webpart we suddenly see strange values when we use RefinableString ManagedProperty mapped to ManagedMetadata field (we use the ows_taxid_XXX crawled propery).

<img width="415" alt="image" src="https://github.com/microsoft-search/pnp-modern-search/assets/16380149/10f6f1ad-bafe-4056-ac32-6df61806f82d">

This problems showed up with no change in config and used to work already.

**Expected behavior**
The filter values should only display with text, not GUIDs and also not duplicate terms.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Edge

**Comment by EbSe** [comment]
We only see this problem with on Search Portal and one special termset

**Comment by kasperbolarsen** [comment]
Hi

Try mapping the RefinableString to ows_XXX, not ows_taxid_XXX when you intend to use it for display purposes.

**Comment by EbSe** [comment]
As stated here by @wobba we should use ows_taxid_XXX when we want multilingual support: https://github.com/microsoft-search/pnp-modern-search/issues/3302

**Comment by EbSe** [comment]
Could this happen because the managed metadata field allows "multiple values" and we have some document with more than one term flagged. Thats the only difference I see at the moment to other Managed Metadata field, where things look ok

**Comment by kasperbolarsen** [comment]
> As stated here by @wobba we should use ows_taxid_XXX when we want multilingual support: https://github.com/microsoft-search/pnp-modern-search/issues/3302

Yes, that is correct when dealing with multilingual

**Comment by kasperbolarsen** [comment]
> Could this happen because the managed metadata field allows "multiple values" and we have some document with more than one term flagged. Thats the only difference I see at the moment to other Managed Metadata field, where things look ok

Absolutely,  multivalue is always a pain in the behind,  except for people properties.

**Comment by EbSe** [comment]
Ok I have to correct my answer because we have other multivalue columns as well which work correctly.

**Comment by EbSe** [comment]
Problem was localization flag in results webpart
