### ISSUE TITLE
Filtering on large value sets doesn't work

### ISSUE THREAD

**Issue by eajclement** [microsoft-search/pnp-modern-search#3372]
**Version used**
Ex: 4.9.1

**Describe the bug**
The library contains more that 5200 items with a text column containing more that 5200 different values (one per item).
The PnP Search webparts are configured to search only in the current site.

The filter webpart is unable to use the different values.

The filter scroll list displays only the first 500 items (this is correct)
The search field of the filter is unable to reach values after the 500 first ones.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to the search page. 2582 result count is displayed in the search results webpart
2. Click on the filter of the filter webpart.
4. The 500 first filter values are displayed in the list
5. Try to search for a filter value that is not in the ones displayed in the list: no result !

**Expected behavior**
The search field of the filter should be able retrieve data for all possible values of the column.

Our business users naturally try to filter frist by "tenant name" (the column with the largest number of values) before refining with other criterias...

**Screenshots**
First result (correct):
<img width="467" alt="image" src="https://github.com/microsoft-search/pnp-modern-search/assets/50746703/3907c039-365e-4172-a06d-9be1d99b0658">

From the last page of results, we focus on Solution value "Solution B80". This value is not present in the filter value list:
<img width="605" alt="image" src="https://github.com/microsoft-search/pnp-modern-search/assets/50746703/366ab3e3-54a9-4925-926a-8e1af6ec1d7f">

Searching for this value in the filter search box, doesn't allows to retrieve this value:
<img width="428" alt="image" src="https://github.com/microsoft-search/pnp-modern-search/assets/50746703/bf5bd5e9-e468-4e5e-93cc-a0eec5ae5b0a">

**Desktop (please complete the following information):**
 - Browser [Edge, latest version]

**Additional context**
Same problem observed in lists or libraries.

**Comment by kasperbolarsen** [comment]
Have you tried to look at the refiner values returned by the API?  SharePoint search query tool or SP editor can provide this insight

**Comment by wobba** [comment]
One, you cannot trust the result count coming back on the API. It's a (poor) estimation only. As for the number of unique filter values see our docs https://microsoft-search.github.io/pnp-modern-search/usage/search-filters/. Last I checked we got 1000 unique values back only. You can try to enter a higher number and see if you get them back as filter values (which is different from results - where the limit is page size of 500).

**Comment by eajclement** [comment]
Thanks @wobba for this info. I'll dig this way soon.

**Comment by eajclement** [comment]
I've just try to push the limit to 2000 values and... I can only reach the 1008 first ones with the filter search box. Why 1008 ? But that's better than 500.

**Comment by wobba** [comment]
I cannot comment on why the API limits what you get back as that is a backend API issue outside our control.
