### ISSUE TITLE
result template custom value from Sharepoint List without managed properties

### ISSUE THREAD

**Issue by j1n6** [microsoft-search/pnp-modern-search#3374]
Objectives:
We would like to customise the search result display against a specific Sharepoint List. The Sharepoint List has multiple custom columns. Each result item should show value from the List column value for that item.  We checked that each column has already been auto-crawled. 

Limitation:
Our current site collection has restricted permission to add any Managed Property. Our team does not have permission to configure it. 

Question:
As we understand that the template system only allow us to use Managed Properties, due to the limitation, we currently cannot find a way to customize the search result display using existing Sharepoint list values. Are there any way that we can display list values in the search result without Managed Property configuration?

Thank you for your help in advance!

**Comment by kasperbolarsen** [comment]
Hi

You should be able to get SOME of the way without getting the Site Collection admin permissions. 
When the crawled properties are created a managed property is created sometimes , see the "Auto-generated managed properties" section in https://learn.microsoft.com/en-us/sharepoint/manage-search-schema
You should be able to find and select those managed properties in "Selected Properties " in the result web part. 
Refiners/filters and sortable properties must be mapped using the Site Collection search schema, so I guess you will have to ask an admin to map the crawled properties to refinabledate/string as required
