### ISSUE TITLE
Promoted Results and Bookmarks do not display

### ISSUE THREAD

**Issue by quarterhorse** [microsoft-search/pnp-modern-search#338]
**Version used**
3.13.0 - May 2020

**Describe the bug**
When query rules are enabled in the search results web part, neither bookmarks nor promoted results are displayed despite search and Microsoft search being configured with them.

**To Reproduce**
1. Create Microsoft Search bookmarks and Search Promoted Result for Local SharePoint Results.  
2. Test to make sure they appropriately surface on /Search (Enterprise Search) and an OOTB modern search result page.
3. Perform same bookmark and promoted result searches on a newly constructed page with the Search Results Web Part with query rules enabled.
4. Neither a bookmark nor promoted result will display.

**Expected behavior**
Promoted Results and/or bookmarks display when the query rules are enabled on the search results web part.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

**Comment by wobba** [comment]
Microsoft Search bookmarks are not currently exposed in an API, thus we cannot show them. Promoted results via best bets are indeed available. Check the `secondaryResults` or `promotedResults` collection in your response which is accessible via handlebars.

You can inspect the JSON response and if it's present there, then you should be able to access it in a template - but you need to add it yourself. The oob list template has code from `promotedResults` as a sample.
