### ISSUE TITLE
Race condition between multiple post queries when redirecting from Office 365 Searchbox

### ISSUE THREAD

**Issue by dmoorjmalani** [microsoft-search/pnp-modern-search#3383]
**Version used**
Ex: 4.8

**Describe the bug**
We have overridden the Office365 searchbox using the PnP-Powershell command ( Set-PnPSearchSettings -SearchPageUrl $searchurl)  to redirect the queries to a page where we have configured PnP Search Webparts, the searchbox is configured to read the querystring, and the search results webpart is bound to the searchbox. The Search Results webpart has a query template defined that has {searchTerms} placeholder to take the query keyword into account.

The issue is, sometimes when we are firing up a query from the Office 365 Searchbox upon redirect we see that the search results webpart does not take query keyword into account. Upon further investigation using Dev Tools we have seen that there are multiple PostQueries getting fired, one of them takes the keyword and one fires without {searchTerms} as if there was no query keyword supplied, and it seems like there is a race condition happening between these queries and results get displayed for whichever query finishes last. (I have concluded this based on which query has the highest elapsed time and whether the page ends up showing its results or no). Each PostQuery has an unique QueryId. 

**To Reproduce**
It happens randomly as there seems to be a race condition between the queries and it depends which finishes last.

**Expected behavior**
There should be only one query that should get fired

**Screenshots**
**SearchBox and Search Results Webpart Configuration**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/6703440/75076f00-a4c5-4e86-8a8d-5096ba53c7c4)
![image](https://github.com/microsoft-search/pnp-modern-search/assets/6703440/46cb4f21-788f-424a-80c7-f0a20353fa5a)

**Correct Results**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/6703440/a602c2b4-72cf-4692-9240-02e01ed222b9)
**Correct Result Network Trace, which shows two queries getting fired but both of them consider the search keyword**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/6703440/23bbe35e-d744-4ed6-a5fa-d8633f7ff253)
![image](https://github.com/microsoft-search/pnp-modern-search/assets/6703440/63e15f83-4b1f-4cec-acc7-79c98a4b520e)
![image](https://github.com/microsoft-search/pnp-modern-search/assets/6703440/876232ec-f6b2-401f-946a-93655ef32b0c)

**Incorrect result**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/6703440/a93733f9-9be1-4b5d-901d-4de3f4e79f34)
**Network trace when we get the incorrect result, it shows 4 post queries, the first one seems not to have any parameters getting passed 
![image](https://github.com/microsoft-search/pnp-modern-search/assets/6703440/5f7f1595-612a-4d66-9109-8b7a856fb5cb)
![image](https://github.com/microsoft-search/pnp-modern-search/assets/6703440/befd5953-3149-402d-8547-3dcdffc2b0fa)
![image](https://github.com/microsoft-search/pnp-modern-search/assets/6703440/566e8560-cdc4-4b9f-ae42-c8cd9be5154e)
![image](https://github.com/microsoft-search/pnp-modern-search/assets/6703440/7090677e-9655-40a0-8ea9-3c8047b916c5)

**Desktop (please complete the following information):**
 - Chrome, Edge

**Additional context**

**Comment by wobba** [comment]
I would not advice to use two search boxes. Either use the navbar one, or use the PnP one, and configure accordingly. Any reason why you have both? And you can configure the result web part to consume the `q` parameter.

**Comment by dmoorjmalani** [comment]
Thanks @wobba! We are checking if we can re-produce the issue without the second searchbox.

**Comment by dmoorjmalani** [comment]
@wobba , the reason why we have two searchboxes is because we have configured our verticals to open different pages on click, and we need to pass the queries to these pages, which is not happening without searchbox. https://XXX.sharepoint.com/sites/home-staging/SitePages/search-All.aspx?q={inputQueryText}

**Comment by nsreenanhks** [comment]
Hi @dmoorjmalani and @wobba - just wanting to close the loop here and clarify in the end we reconfigured the result web part to consume the `q` parameter _as well_, rather than having it bound to the searchbox. We are no longer getting the postquery that fires without {searchTerms}, so this has eliminated the race condition issue while also allowing us to retain the PnP searchbox, in order to pass queries across the vertical pages.
