### ISSUE TITLE
Results not displaying

### ISSUE THREAD

**Issue by manoj2784** [microsoft-search/pnp-modern-search#339]
**Version used**
Ex: 3.7

**Describe the bug**
The search components were working fine last 4 months, now today all of sudden it is not working. On entering keywords and searching the results are not displayed at all

**Screenshots**
![image](https://user-images.githubusercontent.com/32920340/85498111-6fdb2e80-b622-11ea-9a27-455d530edba6.png)

**Desktop (please complete the following information):**
 - Browser - Chrome, IE, Edge etc

**Additional context**

**Comment by wobba** [comment]
Tracking in #325 as it seems to be an SPFx change
