### ISSUE TITLE
Data hrefs being stripped out of handlebars template in V4

### ISSUE THREAD

**Issue by raytri** [microsoft-search/pnp-modern-search#3418]
**Version used**
4.9.3

**Describe the bug**
In the search results webpart, using a custom handlebars template, when attempting to create a download link with an anchor tag, the "href" property of the anchor is removed. This same template works fine in V3.

For instance, if I have the following in the template:
`<a href="data:text/plain;charset=utf-8,fileContentGoesHere" download="{{slot item @root.slots.Title}}.ics">Download file</a>
`
It removes the href attribute and renders as:
`<a download="Title.ics">Download file</a>
`
If I remove the data definition:
`<a href="fileContentGoesHere" download="{{slot item @root.slots.Title}}.ics">Download file</a>
`
It renders just fine (though obviously doesn't work):
`<a href="fileContentGoesHere" download="Title.ics">Download file</a>
`

**To Reproduce**
Detailed steps to reproduce the behavior:
1. In the search results webpart, choose "Custom" layout
2. Add an anchor tag with a data href, such as `<a href="data:text/plain;charset=utf-8,fileContentGoesHere" download="{{slot item @root.slots.Title}}.ics">Download file</a>`
3. Publish the page. the href attribute will be missing.
4. Edit the webpart, and remove "data:text/plain;charset=utf-8," from the href.
5. Publish the page. The href will render as expected.

**Expected behavior**
Data hrefs should render properly in V4 the way they do in V3. In general, hrefs should not be stripped out even if the syntax is bad.

**Desktop (please complete the following information):**
 - Chrome browser

**Additional context**
This is a template that still works fine in the V3 version of the webpart. It only breaks when trying to use it with V4.

**Comment by kasperbolarsen** [comment]
This works with the default Details List Layout in the Manage columns:
<a href="{{slot item @root.slots.Path}}" download>Download file</a>

I would expect that it would work in a custom Layout as well :-)

**Comment by raytri** [comment]
> This works with the default Details List Layout in the Manage columns: ![image](https://private-user-images.githubusercontent.com/20593570/292218328-07dc9792-c87e-4718-909b-a0c3b2ce4501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjg5NDIsIm5iZiI6MTcwMzE2ODY0MiwicGF0aCI6Ii8yMDU5MzU3MC8yOTIyMTgzMjgtMDdkYzk3OTItYzg3ZS00NzE4LTkwOWItYTBjM2IyY2U0NTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE0MjQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNjFiZGY3ZTkzOTdhZWQxZGQ1MWZlZjFlYzA3ZjdkMzI5NTg2YTdmMWJmMTEyNzZkODMyMzVjOGJjNDc5MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TiKxNQF58EtG4H5nkNN19OFP5jNdBgPytXpc0zH6rbE)
> 
> I would expect that it would work in a custom Layout as well :-)

The downloaded file is generated dynamically via a helper (it's an ics file for a calendar item), so the path is not a value I can assign to a slot.

**Comment by kasperbolarsen** [comment]
I see. We would welcome a PR that would enable that :-)

**Comment by wobba** [comment]
Hi, this is a safety measure to prevent script/css attacks where markup is sanitized. So nothing to do with v3/v4...and may be v3 had security holes tighted in v4.

The workaround is a custom webcomponent solving this case for you.

**Comment by raytri** [comment]
> Hi, this is a safety measure to prevent script/css attacks where markup is sanitized. So nothing to do with v3/v4...and may be v3 had security holes tighted in v4.
> 
> The workaround is a custom webcomponent solving this case for you.

Understood. I will give that a try. Thanks!
