### ISSUE TITLE
How to upgrade from 3.7

### ISSUE THREAD

**Issue by allafridman** [microsoft-search/pnp-modern-search#342]
The package name in 3.7 is pnp-react-search-refiners.sppkg, the latest release package 3.13 is pnp-modern-search-parts.sppkg. When I drop it to the App catalog I see both packages there. Is there anything else I need to do, other than just dropping new package to app catalog?

**Comment by wobba** [comment]
If you look at the release notes there could be breaking changes. You should remove the 3.7 package, then install the 3.13 (package name changed) - and check that everything works as expected - with a good chance you need to edit and do something depending on your setup/scenario of web part usage.

I would do this in a test site or tenant first.
