### ISSUE TITLE
Random Error After Zero Changes

### ISSUE THREAD

**Issue by datraceman84** [microsoft-search/pnp-modern-search#344]
I have had this installed in a tenant for a month properly configured and working and yesterday this happened and we cannot get anything to work. In every instance of the Search Results web part I get this:

"Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}}"

Could use help on this ASAP! Thanks!

**Comment by wobba** [comment]
See #325
