### ISSUE TITLE
Search Results webpart not working when connected Page property Search

### ISSUE THREAD

**Issue by axelgz** [microsoft-search/pnp-modern-search#345]
**Version used**
Ex: 3.13 and 3.13.0.4 

**Describe the bug**
Search Results webpart stopped working when using Page properties other than QueryString and Url fragment. Related to [#325](https://github.com/microsoft-search/pnp-modern-search/issues/325#issuecomment-648823156).   

**Error message**
_Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}}_

**To Reproduce**
1. Go to Modern page, place a Search Results webpart
2. Set **Connect to source**: Page environment
3. Set **Page environment's properties**: Search
4. Set **Search**: Search query

**Expected behavior**
Search Results webpart return from Search Box and from links with QueryStrings

**Screenshots**

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by datraceman84** [comment]
I had this exact same issue. It worked fine Monday and quit working yesterday sometime.

**Comment by wobba** [comment]
See #325
