### ISSUE TITLE
Verticals tab not indicating selected value when using ?v=TabName or ?v=TabValue

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#3452]
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/3449

<div type='discussions-op-text'>

<sup>Originally posted by **boing0** January 14, 2024</sup>
I think I've got verticals set up correctly -- they refine the results as expected when I click on the tabs. When I use the query string v=TabName the results are also pre-refined for that tab value. But the selected tab doesn't indicate the query string value with the blue underline, it always shows the first tab as selected. I'm using {searchTerms} AND Site.Id:{verticals.value} in the Results Query template. I have verticals configured not as hyperlinks, which I thought was correct? I also tried v=TabValue (the Site.Id value) but that didn't work. Any idea what I'm doing wrong? I'm using 4.10.1.

Query string in use, results are correct but the right tab isn't selected, it's showing the first tab.
![image](https://github.com/microsoft-search/pnp-modern-search/assets/8752412/195c7766-e936-43e9-ad29-78bf695c43ff)

![image](https://github.com/microsoft-search/pnp-modern-search/assets/8752412/7ac7022e-6fd9-490e-be3a-8a528a1c722c)

</div>

**Comment by kachihro** [comment]
No - I wouldn't use "Is Hyperlink" - unless you want to navigate to a different page.

Can you try with the Tab Value as the same for the QueryString - within the configuration page ?    
I've often used this approach - eg. display name for the tab (Housing) and the TabValue (H).

Then you can use the query string for ?v=H

But yes, this won't work in your search query - doh !

The main bug would appear to be matching the GUID to the TAB.    Can you try the GUID without - in between, to verify behaviour ??

**Comment by kachihro** [comment]
I've done some debugging & checking - and the correct TAB is being selected (ID) - but there is actually a KEY and UNIQUEID - which might be mis-used ?     I've tried including UniqueId as a property within IDataVerticalConfiguration.

But - the usage of this isn't working properly - I'll keep testing/checking.

![image](https://github.com/microsoft-search/pnp-modern-search/assets/16025947/8f6cbb6a-cbbe-4084-9fe9-bf0d146ee760)

**Comment by ferrarirosso** [comment]
Tested in v4.9.3 : works
Tested in v4.10.1 : doesn't work anymore

- Verticals within the same pages works
- It only affects navigation to a vertical located on a different page.
- The only code changes affecting verticals is this one [3396](https://github.com/microsoft-search/pnp-modern-search/pull/3396) but this is not the culprit
- I've looked at the code changes in v4.10.1 and don't see at first any possible causes other than a spfx / fluentui interaction

**Comment by kachihro** [comment]
Interestingly, the package used for Fluent UI has 'reverted' for those versions you noted @ferrarirosso.

PNP Search v4.9.3
> Fluent UI ^8.109.7

PNP Search v4.10.1
> Fluent UI 8.10**6**.4

Perhaps we can try with an updated (fixed?) FluentUI...

**Comment by ferrarirosso** [comment]
@kachihro The Fluent UI Version 8.106.4 is tied to SPFx 1.18.2, this is a recommendation from the m365 cli spfx upgrade.
Could give it a try, but it's difficult to predict the implications

**Comment by ferrarirosso** [comment]
@kachihro tried with Fluent UI ^8.109.7 AND PnP Search V4.10.2, doesn't work, same problem.

**Comment by patrikhellgren** [comment]
I have recently submitted a PR (#3566) that bumps the Fluent UI version to 8.115.6 and can confirm that it doesn't resolve this issue.

**Comment by wobba** [comment]
Should be fixed with @patrikhellgren PR. You can test and build the dev branch.

**Comment by ferrarirosso** [comment]
@patrikhellgren works perfectly. Thank you !
