### ISSUE TITLE
Search box connection lost v3.8

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#346]
**Version used**
v3.8

**Describe the bug**
Predefined search results still working but any results web part connected to a search box is not finding any results.  😉

**To Reproduce**
1. add a search box web part
2. add a results web part
3. configure "connect to source" to hook up search box query term to results

**Expected behavior**
search term should return results

**Desktop (please complete the following information):**
 - Chrome W10 Enterprise

**Additional context**
I've verified the results source is correct and there is data available to find. As noted a static results source not connected to search box still works. Happy to upgrade to latest version of the solution - but what is the best way to do that?

**Comment by wobba** [comment]
See #325
