### ISSUE TITLE
Deeplink filter using query string fails when multiple managed metadata filters are applied.

### ISSUE THREAD

**Issue by AnujSharmaDssmith** [microsoft-search/pnp-modern-search#3461]
We created a page with deeplink filters so that hyperlink can be inserted on another page for filtered result query. However, we observed when a dynamic URL using deeplink filter which has more than 10 managed metadata items from two unique columns is failing.
<img width="256" alt="searchfilter error" src="https://github.com/microsoft-search/pnp-modern-search/assets/156898922/3cbe4761-db59-4e59-b72c-eecc55a734ba">

**Comment by kasperbolarsen** [comment]
This might be an API issue, so could you try to verify the result you get when calling the API with that URL?

**Comment by wobba** [comment]
Closing as the issue template is not used to fill in version and all repro steps. Please re-log using the template.
