### ISSUE TITLE
Extensibility Docs SPFx Version

### ISSUE THREAD

**Issue by HiltonGiesenow** [microsoft-search/pnp-modern-search#3475]
**Version used**
4.8

**Describe the bug**
Not sure where to raise this so just listing it as a "bug" in the docs. The Extensibility docs [intro](https://microsoft-search.github.io/pnp-modern-search/extensibility/) talks about 

> !!! important "SPFx version" The SPFx library project must use the same SPFx version as the main solution (currently 1.15.2). Owherwise you may face issues at build time. See https://github.com/microsoft-search/pnp-modern-search/issues/1893

But it looks like the library has been updated to 1.18.2, if I'm looking in the right place? If so, please update the docs to reflect this. Happy to do this as a PR, but wanted to check I was correct in my understanding here.

**Comment by wobba** [comment]
Updated with https://github.com/microsoft-search/pnp-modern-search/commit/91e1d886ec5988fa9084872821cc34c72744fbe1. Will go online with the next release.
