### ISSUE TITLE
Search results are not displayed when button with link is added at the beginning.

### ISSUE THREAD

**Issue by manjunathreddy1** [microsoft-search/pnp-modern-search#3487]
Hi All,

Search results webpart is not displayed when button with link is added at the beginning but if we try to add it at the end it is properly displayed. Please help to fix this issue.

![image](https://github.com/microsoft-search/pnp-modern-search/assets/265137/c8ed5800-e3c5-4586-92d9-7b6dd1599539)

**Comment by kasperbolarsen** [comment]
Please follow the issue template or we will to reject
