### ISSUE TITLE
PNP People Search Results suddenly stopped working

### ISSUE THREAD

**Issue by AHast14** [microsoft-search/pnp-modern-search#3495]
Version used
4.10.2.0

*Describe the bug*
We have been using PNP search for nearly a year as a staff directory. Today it has suddenly stopped working. When searching for anything, the results web part is blank. Ive updated to 4.10.2.0 as was previously using 4.6.1.0 but this has had not impact. Its a critcal part of our org so any help would be appreciated.

**Expected behavior**
Users/People are returned in the search.

**Desktop (please complete the following information):**
 - Browser tried both Chrome and Edge

**Comment by kasperbolarsen** [comment]
Same as https://github.com/microsoft-search/pnp-modern-search/discussions/3492
