### ISSUE TITLE
Query not returning correct results when SearchResults webpart is connected with Search Verticals webpart. Result source value is also ignored

### ISSUE THREAD

**Issue by manishkaushal2015** [microsoft-search/pnp-modern-search#350]
**Version used**
3.13.0.0

**Describe the bug**
Bug is related to Search Verticals webpart. When Search Verticals webpart is connected to Search Results webpart then two issues are happening:
1) Search results are not returned based on searchBox query text. Everything is returned irrespective.
2) Result Source Identifier configuration in SearchResults webpart is completely ignored. All results are shown, Result Source is not referred while giving results.

**To Reproduce**
1. Download sppkg file version 3,13,0,0
2. Deploy on SP Tenant and enable global deployment.
3. Setup a result source at a site collection level to display documents only from a document library. Please see screenshot attached.
4. Configure SearchBox, Search Verticals, SearchResults and Search Filter webparts on a page. Connect SearchResult to other webparts via dynamic data connections configuration. Specify the GUID of result source 
<img width="208" alt="SearchVerticals_Bug_screenshot2" src="https://user-images.githubusercontent.com/12091712/85680169-64186680-b70d-11ea-9fb0-71d63740a5f3.PNG">

5. Test searching using any keyword. The results will display all records. Search results will ignore the Result source identifier.

**Expected behavior**
Search Results should display records from Result source if it is specified. Secondly the results should show correct search results based on query text only and not everything.

**Comment by manishkaushal2015** [comment]
<img width="388" alt="SearchVerticals_Bug" src="https://user-images.githubusercontent.com/12091712/85680657-da1ccd80-b70d-11ea-84dd-1ae9cb748936.PNG">

**Comment by wobba** [comment]
Tried with 3.14 and seems to work as expected. Unsure if you issue was side related to #325.
