### ISSUE TITLE
search results webpart not able to connect to search query

### ISSUE THREAD

**Issue by manishasakarvadia** [microsoft-search/pnp-modern-search#351]
**Version used**
Ex: 3.9.0.0/3.10.0.0

**Describe the bug**
I think MS has done some changes in the Search API due to that the search box WebPart has stopped working. They are pushing the changes tenant wise hence it is impacting the tenant which has deployed the latest patch.
Search results webpart is unable to connect to search box with search query.

**To Reproduce**
1) Add Search box web-part and search results web-part
2) Try to configure search results webpart as below:
         a) Connect to source as Search box b) Search box's property - Search query

**Expected behavior**
search should be working as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/33956314/85692239-88585100-b6d5-11ea-8bb3-a7c0734b477d.png)

**Desktop (please complete the following information):**
 -Chrome, Mozilla Firefox, Edge

**Additional context**

**Comment by Safouenebha** [comment]
Started having the same problem today.
If i can add, the error is there once the search results webpart is connected to any source (Search box, querystring, ...)

**Comment by wobba** [comment]
@Safouenebha we know. See #325.
