### ISSUE TITLE
Result links to DocSet not the file when the result is contained in a Doc Set.

### ISSUE THREAD

**Issue by erobillard** [microsoft-search/pnp-modern-search#352]
Version 3.13.0

Description: 
In the search results WP, the link to the result will typically open the result, whether a page or a file. However when the result is contained in a Document Set, the link opens the document set rather than the file itself. This behaviour differs from out-of-box (e.g. a search initiated in the Suite Bar), where the link to a result that is a member of a document set opens the file, and not the document set. 

1. Add a file to a document set and allow it to be crawled.
2. Run a search that returns the file
3. Click through the file in the result set. 
4. The document set will open, not the file. 

Expected behavior: The file should open in the same manner as any other file returned in search results.

**Comment by wobba** [comment]
Can you give an example of the URL it opens vs the one it should be?

**Comment by erobillard** [comment]
URL provided (opens the Document Set): https://TENANT.sharepoint.com/sites/CCO/Conferences%20%20Courses/25th%20Annual%20Regulatory%20Compliance%20for%20Financial%20Institutions/?id=/sites/CCO/Conferences%20%20Courses/25th%20Annual%20Regulatory%20Compliance%20for%20Financial%20Institutions/Day%201_1200_The%20Evolution%20of%20Non-Financial%20Risks.pdf&parent=/sites/CCO/Conferences%20%20Courses/25th%20Annual%20Regulatory%20Compliance%20for%20Financial%20Institutions

URL expected (to the PDF itself): 
https://TENANT.sharepoint.com/sites/CCO/Conferences%20%20Courses/25th%20Annual%20Regulatory%20Compliance%20for%20Financial%20Institutions/Day%201_1200_The%20Evolution%20of%20Non-Financial%20Risks.pdf

DEBUG Info for this item (some properties sanitized): 
    {
      "Rank": "26.7789249420166",
      "DocId": "17598919610546",
      "Title": "Day 1_1200_The Evolution of Non-Financial Risks",
      "Path": "https://REDACTED.sharepoint.com/sites/CCO/Conferences  Courses/25th Annual Regulatory Compliance for Financial Institutions/Day 1_1200_The Evolution of Non-Financial Risks.pdf",
      "Created": "2019-12-04T16:39:12.0000000Z",
      "Filename": "Day 1_1200_The Evolution of Non-Financial Risks.pdf",
      "SiteLogo": null,
      "PictureThumbnailURL": null,
      "ServerRedirectedPreviewURL": "https://REDACTED.sharepoint.com/sites/CCO/_layouts/15/WopiFrame.aspx?sourcedoc={95ba4467-cc16-4784-90e1-a7bf09907485}&action=imagepreview",
      "ServerRedirectedURL": null,
      "HitHighlightedSummary": "REDACTED",
      "FileType": "pdf",
      "contentclass": "STS_ListItem_DocumentLibrary",
      "ServerRedirectedEmbedURL": "https://REDACTED.sharepoint.com/sites/CCO/_layouts/15/WopiFrame.aspx?sourcedoc={95ba4467-cc16-4784-90e1-a7bf09907485}&action=interactivepreview",
      "ParentLink": "https://REDACTED.sharepoint.com/sites/CCO/Conferences  Courses/25th Annual Regulatory Compliance for Financial Institutions",
      "DefaultEncodingURL": "https://REDACTED.sharepoint.com/sites/CCO/Conferences%20%20Courses/25th%20Annual%20Regulatory%20Compliance%20for%20Financial%20Institutions/Day%201_1200_The%20Evolution%20of%20Non-Financial%20Risks.pdf",
      "owstaxidmetadataalltagsinfo": "",
      "Author": "REDACTED",
      "AuthorOWSUSER": "REDACTED",
      "SPSiteUrl": "https://REDACTED.sharepoint.com/sites/cco",
      "SiteTitle": "CCO - Compliance Office",
      "IsContainer": "false",
      "IsListItem": null,
      "HtmlFileType": null,
      "SiteId": "REDACTED",
      "WebId": "REDACTED",
      "UniqueID": "{REDACTED}",
      "OriginalPath": "https://REDACTED.sharepoint.com/sites/CCO/Conferences  Courses/25th Annual Regulatory Compliance for Financial Institutions/Day 1_1200_The Evolution of Non-Financial Risks.pdf",
      "FileExtension": "pdf",
      "LastModifiedTime": "2019-11-25T18:41:15.0000000Z",
      "SitePath": "https://REDACTED.sharepoint.com/sites/cco/conferences%20%20courses/25th%20annual%20regulatory%20compliance%20for%20financial%20institutions/;com.sharepoint.haventreebank./sites/cco/conferences%20%20courses/25th%20annual%20regulatory%20compliance%20for%20financial%20institutions/",
      "PreviewUrl": null,
      "SPContentType": null,
      "UrlZone": "0",
      "Culture": "en-US",
      "ResultTypeId": "0",
      "RenderTemplateId": "~sitecollection/_catalogs/masterpage/Display Templates/Search/Item_Default.js",
      "GeoLocationSource": "CAN",
      "IconExt": "pdf"
    },

**Comment by wobba** [comment]
If you click the pdf in the doc set in a lib, what's the URL then? Not a preview?

**Comment by erobillard** [comment]
If you click the PDF, it should open the file (however PDFs are configured to open, based on machine policy), whether directly from the search results or inside the Doc Set. The problem is that rather than opening the document, clicking on the result (which is a file) opens the Doc Set page and not the file itself. This deviates from the OOB behaviour of clicking a result after a Suite Bar search, which always opens the file and not its container. 

The issue might have slid by if their Doc sets only contained a tiny number of files. However these document sets can have 30+ files, so opening the Doc Set first doesn't really help anyone necessarily find what they're looking for. If it's not on the first page, or the filename doesn't match the title that appeared in the result, it becomes a highly frustrating UX.

**Comment by wobba** [comment]
I'll enable doc sets to look at the data and try to replicate.

**Comment by erobillard** [comment]
I can set up a demo tenant if it would help - it's the only remaining block for a DocSet-dependent client waiting to launch a new Search Centre.

**Comment by wobba** [comment]
Setting up doc set is easy. It's more about someone caring and spend time adressing it 🙂

**Comment by erobillard** [comment]
Update: A retest now succeeds, when a search result is a member of a Document Set, the link now opens the target file rather than the containing Document Set. Not sure which update resolved the issue, my guess would be the recent changes to GetUrl(), but whomever was responsible for the change, much appreciated!
