### ISSUE TITLE
Version 3.14 copies the query from url to search box but the results dont show in search results

### ISSUE THREAD

**Issue by rohit18121812** [microsoft-search/pnp-modern-search#353]
!! Check existing issues before logging new ones !!

**Version used**
3.14

**Describe the bug**
Version 3.14 copies the query from url to search box but the results dont show in search results. Also when you are on the search page and press enter on the search 

**To Reproduce**
1. Go to Homepage
2. Type "capture" on the search box on top
3. The page re-directs to search page and the "capture"  is seen on the "Modern Search" search box but no results are displayed
4. If you manually hit the Search button, no search results shows up
5. But if you type "*" the search results show up but if you type a word on search box the search result doesn't show.

**Expected behavior**
The results should show up

**Screenshots**
Search box setup
![image](https://user-images.githubusercontent.com/67439350/85798580-8b156f00-b6f2-11ea-952b-524210061d4f.png)
Searc Result setup
![image](https://user-images.githubusercontent.com/67439350/85798682-b26c3c00-b6f2-11ea-9028-25e3b6ba3a3c.png)

**Desktop (please complete the following information):**
 - Browser : Chrome

**Additional context**

**Comment by wobba** [comment]
Try 3.14.1. Why do you use two search boxes? You can use the top searchbox directly with the result web part, and you can change page layout to hide the chrome on this one page as well.

**Comment by wobba** [comment]
I tried to repro with the latest version. PnP search box picks query from header search box, search results from pnp search box - and it works. Still a weird setup :)

**Comment by rohit18121812** [comment]
Yes after latest version , it worked fine.  But the suggestion you gave about just using the header search box (not PNP search), didnt work.  The search results is not able to grab the query from the header. I tried the page environment & search box settings on Search results but it didnt work.

**Comment by wobba** [comment]
The dynamic data issue is for any search box. Fix is rolling out this or next week by SPFx team.
