### ISSUE TITLE
Error making HttpClient request in queryable [400]

### ISSUE THREAD

**Issue by gristy58** [microsoft-search/pnp-modern-search#354]
When configuring search results to be connected to a query string the following is shown:

Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}}

This is on the latest May 2020 release - the upgrade was performed after the older version started returning no results.

**Comment by martinewald** [comment]
I had the same Issue with 3.9. But after an Update to 3.13 (May 2020), the Issue was resolved. 

I could observe this on two different SiteCollections each with an SiteCollection scoped app catalog.

**Comment by wobba** [comment]
The issue is there with 3.13. 3.14 has a workaround, as it's a SPFx issue, not web part issue. Tracked in #325 and https://github.com/SharePoint/sp-dev-docs/issues/5947
