### ISSUE TITLE
Sharepoint Search & display files from network server

### ISSUE THREAD

**Issue by Tuckster24** [microsoft-search/pnp-modern-search#3551]
I have been directed to here from Microsoft with the hope someone can help.
I am new to Sharepoint and currently in the process of creating an Intranet site. 
One of the main reasons for this is so we can visit the Intranet from an Android tablet as well as a PC so that our shopfloor workers can use this like a GUI.
On our server network we have a folder structure with drawings all in pdf format.
I have added the Search box part to a page with the hope of selecting a folder location on our network drive.
The idea for the end user is then to either enter or scan a barcode into the search box and the search box will look in the network folder and subfolders for the file.
Once the file is found, it would then be great to click the file to open the pdf file.
I could then do with adding another search box to limit the search to another location on the network server for work instructions.
I really do hope someone has a solution for this.
Thanks

**Comment by kasperbolarsen** [comment]
Hi Tuckster24, this project is focused on a set of search related web parts for SharePoint Online.

Your question is very broad and sounds like a great question for a SharePoint architect.  So I will recommend you to contact a consultancy with expertise in SharePoint or ask your question in a broader forum like Stackexchange or https://learn.microsoft.com/en-us/answers/tags/235/office-sp
