### ISSUE TITLE
Support for querystring i searchbox is no longer working

### ISSUE THREAD

**Issue by kjetilodegaarden** [microsoft-search/pnp-modern-search#356]
**Version used**
3.13 3.14, testet backwards as well

**Describe the bug**
Configurering the search webparts to use a querystring as input for the search does no longer work. The value is picked up by the global(!) searchbox and is no longer being used in the modern search box webpart. This seems like a global issue, have reproduced in different tenants.

**To Reproduce**
1. Open a page with the search webparts. Insert a querystring e.g q=test
2. Configure the searchbox to listen to the querystring q
3. Refresh the page
4. The querystring is not used.

**Expected behavior**
Searchresults are displayed and search is performed with the querystring value

**Screenshots**
![image](https://user-images.githubusercontent.com/11867097/85840991-bacd8100-b79d-11ea-8217-3bf05a5c49ec.png)

**Desktop (please complete the following information):**
Browser: Chrome

**Comment by wobba** [comment]
I cannot really repro this. I go the page. Append `q=test`, page reloads, search box is populated and results appear.

A side not as I've said other places, why do you want to have both the nav bar search box and pnp search box on the same page?

**Comment by kjetilodegaarden** [comment]
This is a prededefined search that opens from a differnet system so its to make this tick and to make the results appear for my client the way they want no. I see now that this duplicates https://github.com/microsoft-search/pnp-modern-search/issues/325

**Comment by kjetilodegaarden** [comment]
I redeployed 3.14 and it works. Thanks!
