### ISSUE TITLE
Search results not displaying from yesterday 

### ISSUE THREAD

**Issue by polashivaprasad** [microsoft-search/pnp-modern-search#357]
**Version used**
Ex: 3.13

**Describe the bug**
I configure the search box and results webpart on the same page. from other page i am triggering the search query with query parameter ex q=mysearchword  i have 2 issues here 
1) search box not picking the query value instead it is displaying under Microsoft search box.
2) search results webpart is not displaying results when i used dynamic connection if i use if i use normal search query keyword it is working as expected.
Error info:
Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}}

**To Reproduce**
1. configure the search webpats on the page.
2. search results  is connected to search box.
and trigger search from different page as well as same page .

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10192487/85869760-08f57b00-b7c4-11ea-8dc5-1b2dfcae7cb4.png)
![image](https://user-images.githubusercontent.com/10192487/85869864-32160b80-b7c4-11ea-8d3d-8ffb3e7dcffa.png)

**Desktop (please complete the following information):**
 - Browser chrome

**Additional context**
This issue started from today till yesterday it is working as expected.
seems out of the search box is making problem.
i also updated the search settings no luck.

**Comment by wobba** [comment]
See #325

**Comment by erobillard** [comment]
I'm seeing the same issue - appears to have started last week though there was no change to the installed version. At first it was simply not picking up on the "q=" parameter though the Suite Bar was correctly populating. After replacing the Search Box part and rewiring it, the error described here is now displayed in the Results WP. Please advise on a solution, thanks!

**Comment by wobba** [comment]
@erobillard If you read all of #325 you would know v3.14.1 is our with a work around 😉 which also links to tracking issue on sp-dev-docs.

**Comment by erobillard** [comment]
Thanks @wobba, appreciate the fast turnaround! Soon after the comment I did find and read 325, apologies for responding too soon though at the time this was the only hit for the error text. Cheers, hope all is great with you and thanks also for all you've done with this project, it's been extremely useful.

**Comment by polashivaprasad** [comment]
Thanks @wobba  on top of pnp search solution i have some customization. i updated my solution with your code fix it is  working as expected . once again thanks you very much for your help.
