### ISSUE TITLE
Hover Over Disabled with Custom Layout

### ISSUE THREAD

**Issue by LeeDrinkwater** [microsoft-search/pnp-modern-search#3573]
**Version used**
Ex: 4.10.2.0

**Describe the bug**
I have added additional styling to the standard "People" layout with the PNP search results. This will then make the layout "custom" but all code within is the same as the "People" layout with the exception of the additional code. The styling I have added is to adjust the results page so it will line up into 2 or 3 columns instead of the default of 1. The extra style code added is as follows:

<style>
        mgt-person {
            --initials-background-color: {{@root.theme.palette.themePrimary}};
        }
        .template--defaultList {
            flex-wrap: wrap;
            display: flex;
            justify-content: left;
            gap: 20px 25px;
        }
        .template--peopleListItem {
            width: 250px;
    }
    </style>

With this code added, the "hover over" feature that is enabled when using the "people" layout will no longer work. Reviewing the code the entry for "hover" is still visible however does not work once the layout becomes "custom":

<mgt-person user-id="{{getUserEmail (slot item @root.slots.PersonQuery)}}" person-card="hover">
                                            <template>
                                                <pnp-persona 
                                                    data-image-url="\{{personImage}}" 
                                                    data-fields-configuration="{{JSONstringify @root.properties.layoutProperties.peopleFields}}" 
                                                    data-item="{{JSONstringify item}}" 
                                                    data-persona-size="{{@root.properties.layoutProperties.personaSize}}"
                                                    data-theme-variant="{{JSONstringify @root.theme}}"
                                                    data-instance-id="{{@root.instanceId}}"
                                                    data-context="{{JSONstringify (truncateContext @root)}}">
                                                </pnp-persona>

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Add PNP Search Results and PNP Search Box to modern page.
2. LocalPeopleResults used for data source
3. Select People as Available layout on page 2 of web part config.
4. Ensure "Show persona on hover" is enabled. 
5. Scroll back up and Click {} to edit results template.
6. Add the following to the style element at the top of the page.

.template--defaultList {
            flex-wrap: wrap;
            display: flex;
            justify-content: left;
            gap: 20px 25px;
        }
        .template--peopleListItem {
            width: 250px;
    }

7. Save
8. When searching for users, if you hover over then people card will not appear.
9. If you edit page again and revert to "People" as layout and save and repeat step 8, it will be possible to show hover over results that appear.

**Expected behavior**
As code for hover-over behaviour is added within the results layout, I was hoping hover-over would still work after adding the style element to align the results into columns. The standard alignment is not tidy and without it, my customer's first response is "can you line up the results"? I am hoping that it will be possible to combine the hover-over feature that the people results template allows with my extra styling to line up the results.

**Desktop (please complete the following information):**
 - Chome 122.0.6261.70

**Comment by patrikhellgren** [comment]
When using your repro steps I have no issues with the hover card.
I am using Edge so could you try with that as well?

You should also be aware of that the next release of PnP Modern Search will have a new version of Microsoft Graph Toolkit included (version 4.0.1) so that could change a few things regarding this also.

**Comment by LeeDrinkwater** [comment]
> When using your repro steps I have no issues with the hover card. I am using Edge so could you try with that as well?
> 
> You should also be aware of that the next release of PnP Modern Search will have a new version of Microsoft Graph Toolkit included (version 4.0.1) so that could change a few things regarding this also.

Thank you @patrikhellgren for your response. I realised as soon as I had posted this that I should probably test in Edge to confirm and sure enough it does not happen in Edge as you have found! Sadly for this customer Chrome is their preferred browser but this does seem to suggest an issue with Chrome. I
