### ISSUE TITLE
Search results not showing all the records

### ISSUE THREAD

**Issue by srinutamada** [microsoft-search/pnp-modern-search#358]
I am using Search results web part to show the results in a specific format. Data is coming in the format without any issue. But when look at number of item it is listing is very minimal. 

Based on the search query, there should be 78 records, but I can see only 21 items in the search results. Its not showing the rest of items. 

For validation i tested with search api and I got all 78 records. in my search query 4 look up columns are there and 2 of them are not required fields.

**Comment by srinutamada** [comment]
I used "and" operation in the query string which cause the problem. Now I removed the operator and it worked

**Comment by wobba** [comment]
AND (has to be uppercase to be used as an operator) is implicit between terms.

**Comment by srinutamada** [comment]
Thank you AND worked, its a case sensitive.

**Comment by wobba** [comment]
See https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference#kql-operators-for-complex-queries or my blog at https://www.techmikael.com/2014/03/s15e01-kql-basics.html :)
