### ISSUE TITLE
 Custom renderer pagination not working with v3.14

### ISSUE THREAD

**Issue by NicolasRoelofs** [microsoft-search/pnp-modern-search#359]
I upgraded pnp modern search from the 3.3.1.0 version to 3.14.0.0 but now the pagination in my custom renderer (search-custom-renderer) not working. Since the search pagination webpart has been removed from the 3.11 version : please which part of code i need to add and where ?

**Comment by wobba** [comment]
See comments pn https://github.com/microsoft-search/pnp-modern-search/pull/155 for more information. The pagination web part was changed to a web component which you could output in your markup. So pagination and custom renderer is a gap today, which we need someone to address for it to be fixed.

Or you can stay on the older version.
