### ISSUE TITLE
PNP Search Results webpart- Cannot read properties of undefined Error Only in Edge Browser

### ISSUE THREAD

**Issue by LabibSalah** [microsoft-search/pnp-modern-search#3591]
**Version used**
4.10.2 and is the latest one

**Describe the bug**
I add a pnp Search Result on a sharepoint page to show me the specified People filtering with its EmployeeType
EmployeeType is managed Property already created and mapped and works fine by the way.

Query:
{searchTerms} 
(EmployeeType:* AND -EmployeeType:AZURESMBX)  
It works fine in **Chrome** but in Edge shows me error on the first Load and then when i try to refresh the page, it disappears

**Expected behavior**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/145577753/f0bc5daf-bb3f-4238-8117-d0ce95cca93b)

**Screenshots Error **
on the page:
![image](https://github.com/microsoft-search/pnp-modern-search/assets/145577753/3d46822e-113e-40b1-968b-1075b2ad4e75)

in developer Tools:
![image](https://github.com/microsoft-search/pnp-modern-search/assets/145577753/e00c5c9a-63f0-4401-9702-f42766c2a2ba)

**Desktop (please complete the following information):**
 - Browser : Edge

**Comment by patrikhellgren** [comment]
See #3505 for identical error message and it will most likely be resolved by the referenced pull request that bumbs the version of Microsoft Graph Toolkit and available in the next release of PnP Modern Search

**Comment by wobba** [comment]
Closing as the fix by @patrikhellgren is in the dev branch. Feel free to test it out before the next release.

**Comment by LabibSalah** [comment]
I already installed the last version of pnp (4.10.2). You are saying that will come new version of PNP that will correct this MGT Error
Is that Correct ?

**Comment by patrikhellgren** [comment]
@LabibSalah Yes, that is correct. I don't know when that will be released, @wobba needs to answer that.

**Comment by LabibSalah** [comment]
Thank you very much Patrick :)
