### ISSUE TITLE
How to replace Created and owstaxidmetadataalltagsinfo with custom field/managed properties using Edit Result template

### ISSUE THREAD

**Issue by saregbesola** [microsoft-search/pnp-modern-search#360]
I have a requirement to replace the created date in the search result with a custom date field, and the owstaxidmetadataalltagsinfo tag with a choice field. I have created managed properties for both fields, and I replaced the two fields with the managed properties I created but they didn't work.

I have replaced the **Created** {{getDate Created 'LL'}} using edit result template with {{getDate RefinableDate04 'LL'}} and 
replaced this block of code:
 {{#if owstaxidmetadataalltagsinfo}}
          <i class="ms-Icon ms-Icon--Tag" aria-hidden="true"></i>
           {{#each (split owstaxidmetadataalltagsinfo ",") as |tag| }}                                                    
            <a href="#owstaxidmetadataalltagsinfo:'{{trim tag}}'">{{tag}}</a>
            {{/each}}
     {{/if}}

with:

{{RefinableString00}}

RefinableDate04  is the managed property for the custom date field while RefinableString00 is the managed property for the choice field. **Note** I have mapped the managed properties to their respective crawled properties and re-indexed. And they both work when I use KQL to search.

am I doing it the right way? Kindly advise. Thanks

Update: Here is the screenshot of the part i'm trying to change
![searchResult](https://user-images.githubusercontent.com/35005799/86130669-7ea66300-bab2-11ea-8d24-cdd196fec17d.PNG)

**Comment by saregbesola** [comment]
@wobba any idea on this? 

Many thanks

**Comment by FranckyC** [comment]
Hi @saregbesola, you need to add these two properties in the 'Selected Properties' in the WP options to use them in your template.

**Comment by saregbesola** [comment]
@FranckyC  Thanks!!!! It's working now.
