### ISSUE TITLE
400 Error in Modern Search Center

### ISSUE THREAD

**Issue by tammybearden** [microsoft-search/pnp-modern-search#362]
!! Check existing issues before logging new ones !!

**Version used**
Modern Search Center

**Describe the bug**
"_**Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}}**_"
 
This is the error on my Search Center before I search (and after) whereas the native "Search this Site" on all my other SP sites' work without error. 

**To Reproduce**
1. Go to 'https://burnsmcd.sharepoint.com/sites/KnowledgeLibrary-1898/SitePages/SearchCenter.aspx'
2. See error

**Expected behavior**
Expecting Search Center to appear and work

**Screenshots**
![image](https://user-images.githubusercontent.com/67649631/86151212-0fd20580-bac4-11ea-9168-4bab2d33080d.png)

**Desktop (please complete the following information):**
 - Chrome and Microsoft Edge

**Additional context**

**Comment by wobba** [comment]
Please respect the first line of the template.

**Comment by tammybearden** [comment]
Please clarify @wobba, as I am a new user of GitHub (as of today) and have not located this issue in the list of previously logged issues. Thanks in advance for your guidance.

**Comment by wobba** [comment]
See the issue list and you find #325 🙂
