### ISSUE TITLE
Properties missing from "Selected properties" picker 

### ISSUE THREAD

**Issue by HiltonGiesenow** [microsoft-search/pnp-modern-search#3624]
**Version used**
Ex: 4.10.1

**Describe the bug**
I'm trying to set up a "Birthday" results display, based on this article in the docs: https://microsoft-search.github.io/pnp-modern-search/scenarios/Setup-Results-web-part-to-show-birthdays/ . I'm able to show the users but I want to show the actual birthday itself. However, the mapped property (I'm also using `RefinableDate00`, set it up several days ago) doesn't appear in the "Selected Properties" picker for the Search Results webpart. I'm seeing actual people results (i.e. people are coming back from the PeopleResults source fine based on the query), and `RefinableDate01` appears in the 'Select properties' list, even though I don't need that, but I can't find `RefinableDate00` there.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Map RefinableDate00 to SPS-Birthday
2. Add Search Results web part to a page
3. Select "People Results" source
4. Set Search query to "RefinableDate00>2000-{CurrentMonth}-{CurrentDate}T00:00:00Z"
5. Try to pick `RefinableDate00` from "Selected properties" on PnP Search Results web part, it doesn't appear.

**Expected behavior**
`RefinableDate00` should appear in "Selected properties"

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Chrome (latest)

**Additional context**
n/a

**Comment by HiltonGiesenow** [comment]
Looking more into this now, I can see the property is not coming back from the 'ManagedProperties' query to the Search service, so I guess it can't really be an issue in the PnP parts, but maybe someone on the team has a tip for what I'm missing?

**Comment by kasperbolarsen** [comment]
Hi Hilton, 
It is pretty common that the Selected Properties doesn't contain all the properties,  so you will have to type in the property name in the Selected Properties box.
