### ISSUE TITLE
Search Filter elements greyed

### ISSUE THREAD

**Issue by Lilian0000** [microsoft-search/pnp-modern-search#364]
**Is your feature request related to a problem? Please describe.**
I made a migration from version 3.9 to 3.14 and it seems that default filter behavior has changed in the webpart search filter. Now when a filter is selected, the others are greyed. So i tried to use multiple values filter but the filter does OR instead of AND for each filter selectionned where the old default filter did AND.

**Describe the solution you'd like**
I would like to know if it's possible to roll back to the old behavior of the default filter or modify the multiple values filter to do AND between each filter selected.

**New feature**
![search_filter_new](https://user-images.githubusercontent.com/40389172/86376976-0db8a400-bc88-11ea-9899-09dcbec24bd7.png)

**Old feature**
![search_filter_old](https://user-images.githubusercontent.com/40389172/86376983-0e513a80-bc88-11ea-95b7-678b17b2e159.png)

**Comment by wobba** [comment]
@FranckyC any reason why values are disabled?

**Comment by BraunJonathan** [comment]
Yeah why disabling the values? 
You are indeed filtering and displaying the refinement results, the is no point on disabling them. 

Right now, there is no more way to search for more specific results by adding filter to one another...
And moreover showing that there are more refinement possible but disabling them is a really frustrating behaviour for end users...

If this is intended behaviour, i'dl like to know the reasons that pushed you towards this solution.

**Comment by FranckyC** [comment]
We disable the value only if the template is single value. This way, you can't select multiple values by accident and get wrng behavior. For the 'OR' condition, we follow the same behavior as the refinement Web Part in classic experience. This Web Part does an 'OR' condition using the mult-value refinement template.

**Comment by BraunJonathan** [comment]
Ok, thanks for the answer @FranckyC 
But how do you do the have a filter that allows user to do a more specific search by adding refinement value to one another?
Why could selecting multiple refiners be a "wrong behaviour"?

**Comment by FranckyC** [comment]
It is a wrong behavior if you select multi values in template allowing only single value ;). You can still use the mult value template for this but with an OR condition.

**Comment by BraunJonathan** [comment]
Yes but that way you cannot anymore do any kind of AND filter in a single refiner...
Let's say you have thousands of news posts and you wan to find one particular. You know it has multiple values in one specific refiner and you know wich ones, how do you manage to find it using filters ?
Before, you could do that by selecting one value, then selecting another (after the first request has narrowed down the results) and then again etc etc...
Now you cannot do that anymore...

If you really want to allow only one filter value on a single refiner, shouldn't your values be self exclusive?

**Comment by josy1024** [comment]
We'v used this on "**TermStore**" Filtering posibility and it is a "Multi" Value Option. 

@FranckyC 
This is a "BUG" or "feature" downgrade to my mind.

**Comment by h3nn3** [comment]
Need this also back as soon as possible.

**Comment by h3nn3** [comment]
Is there any update available on this behaviour?

**Comment by wobba** [comment]
Not unless someone decides to work on it. Most features are driven by developers who need the feature in their project, so you need to get someone to pick this up and work on it :) That's how open source works.

**Comment by wobba** [comment]
v3 is no longer maintained.
