### ISSUE TITLE
Open documents in client applications

### ISSUE THREAD

**Issue by MelanieO365** [microsoft-search/pnp-modern-search#3640]
**Version used**
4.9.3.0

**Describe the bug**
Configurated that documents should open in client applications but when using PnP Modern Search, the result layout "details list" is not opening the documents in the client application.

**To Reproduce**
1. activate the site collection feature to open the documents by default in the client application
2. configure the search results webpart to show the layout as "details list"
3. Test by clicking on the title field to open the document. It will open the document in the browser

**Expected behavior**
Expected the documents to open in the client application. Maybe add a toggle to configure the results webpart to enable "open documents in client application"

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by kasperbolarsen** [comment]
If you use the Handlebar option you can tweak the URLs to either open the document in the browser or in the application.
like <a href="{{Path}}?web=1">link</a> 
web=0 is "open in client", and web=1 is open in browser :-)
