### ISSUE TITLE
With a new search, the result page does not refresh

### ISSUE THREAD

**Issue by JulieLachance** [microsoft-search/pnp-modern-search#365]
Hi,

We have a small problem when integrating the PnP Modern Search webpart on a result page with the OTB search box of the communication site.

The problem is that when we are on the result page, a new search keyword place in the search box will modify the URL but the result page will not refresh.

We have PnP Modern Search v3.14 and we have modified at the root of SharePoint (moderne communication site) the search results page for the one that we have build with the PnP Modern Search.

If we make a search from any pages on the site, the user is redirected to the result page and the result is display.
If we make a search from the result page it self, the url change to show the new search keyword but the result page don't update.

How can we fix this ?

Thanks

**Comment by wobba** [comment]
See #325 and https://github.com/SharePoint/sp-dev-docs/issues/5947

**Comment by polashivaprasad** [comment]
@wobba  do we need to wait for microsoft to fix this or we have a work around till MS  release?

Thanks

**Comment by wobba** [comment]
Read the comment thread on 325.

**Comment by JulieLachance** [comment]
seems like 3.14.2 release doesn't resolve my issue

**Comment by wobba** [comment]
@JulieLachance how have you configured search parts to pick up the oob search box query?

**Comment by JulieLachance** [comment]
Hi!
our environment is in french but here are the configuration
Connect to Source : Page environment
Property : query string
query string : request parameter
query parameters property: q

the page does not refresh when I do 2 consecutive searches but it refreshes when the page is modified.

**Comment by wobba** [comment]
Can you use this connection instead?

![image](https://user-images.githubusercontent.com/51104/89186485-23c5c700-d59c-11ea-937b-099406c84812.png)

**Comment by JulieLachance** [comment]
sorry but I can't  see your  image

**Comment by wobba** [comment]
@JulieLachance https://user-images.githubusercontent.com/51104/89186485-23c5c700-d59c-11ea-937b-099406c84812.png

**Comment by wobba** [comment]
Sorry..wrong setting.
Can you use:

Source: Page environment
Environment properties: Search
Search: Search query

**Comment by JulieLachance** [comment]
Thank 's :) you make my day 🥇

**Comment by MaxMattiello** [comment]
I've a similari issue but i do not understand how to solve it.
I've the attache page where i configured 3 Search Box and one Search Result.
Each Search Box is configured as follow:
- Send teh query to a new page: ON
- Page URL: i send all request to the actual page
- Method: Query string parameter
- Parameter Name: each Search Box has it's own parameter (CustomerOrderNo for the firstone, SerialNo for the second, Crossreference for the third)
- Use dynamic data source as default input: ON
- Connect to source: Page environment
- Page environment's properties: Query String
- Query String: Query parameters
- queryParameters's properties: for each Search Boc i put the relative parameter (CustomerOrderNo for the firstone, SerialNo for the second, Crossreference for the third)

When insert a value in one of these Search Box, page is refreshed and Search Results shows me the correct documents but when i remove the value on the Search box, page is not refreshed so Search Results shows me previous documents.

Can you help me to fix?

![ModernSearch](https://user-images.githubusercontent.com/81249220/117458903-1387b180-af4b-11eb-8f02-44a5421abfec.png)

**Comment by wobba** [comment]
@MaxMattiello If you have an issue, log a new one. Don't comment on closed and resolved ones.
