### ISSUE TITLE
Sample with alternate colors for odd / even rows in the Detailed List layout

### ISSUE THREAD

**Issue by kasperbolarsen** [microsoft-search/pnp-modern-search#3654]
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/3653

<div type='discussions-op-text'>

<sup>Originally posted by **itebet** March 26, 2024</sup>
Adding alternate row colors for odd / even rows (like white / grey) would be really useful for long list format results.
If you know some pieces of code to all will be appreciated. 
If you can add it as a layout option on the UI it will be even better.
Thank you in advance.</div>

**Comment by carry2web** [comment]
Something with CSS like this, anticipating results are in same divs
div.container>div:nth-of-type(odd) {
  background: #e0e0e0;
}
iso hard coding the background better make use of the theme colors.

**Comment by kasperbolarsen** [comment]
Result can be found here, https://github.com/microsoft-search/pnp-modern-search-layouts/tree/main/Results%2FHandlebars%2FList%20Alternating%20background%20color
