### ISSUE TITLE
Changing the "Sort by..." label in the sort dropdown to French

### ISSUE THREAD

**Issue by kasperbolarsen** [microsoft-search/pnp-modern-search#3658]
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/3609

<div type='discussions-op-text'>

<sup>Originally posted by **sinc13** March  7, 2024</sup>
Is it possible to edit or customize the default "Sort by..." label in the sort dropdown? We would like that to appear in French for French users or on French pages.

Thanks</div>

**Comment by jblueml** [comment]
@sinc13 @kasperbolarsen Does that issue still occur in your environment? I've investigated it with the current release-version 4.12.2 and the default label in the sort dropdown is "Trier par..." on a French page.

![image](https://github.com/user-attachments/assets/741ac931-8755-42f1-8b7d-d8fa10f307e1)

**Comment by kasperbolarsen** [comment]
I can confirm that this issue seems to be gone
![image](https://github.com/user-attachments/assets/df934f95-c861-428a-b9bc-e2358a3aacb6)

@sinc13 can you confirm?
