### ISSUE TITLE
Inconsistent Search Results

### ISSUE THREAD

**Issue by sympmarc** [microsoft-search/pnp-modern-search#3659]
**Version used**
Ex: 4.11.0

**Describe the bug**

I'm not sure this can be blamed on PnP Modern Search, but I've seen this is multiple tenants and it bothers me. Maybe I'm doing something wrong.

Situation is this:
* Enterprise Content Type (named Work Instructions below). The CT is published.
* I've enabled the CT on exactly one DocLib to keep things simple.
* In that DocLib, I have 56 files, and all of them are CT Work Instructions (that's the default and only CT enabled in the DocLib)

There are two different ways I can form the query:
1. `{searchTerms} SPContentType:'Work Instructions'`
1. `{searchTerms} Path:https://tenantname.sharepoint.com/sites/Retail/WorkInstructions*  IsDocument:1`

Because there is only one DocLib containing files with CT=Work Instruction, the two queries should provide the same file count, right?

Query 1 returns 22 files
Query 2 returns all 56

Checking the console, here are the serialized queries in the request:

1. `"<Query Culture=\"en-US\" EnableStemming=\"True\" EnablePhonetic=\"False\" EnableNicknames=\"False\" IgnoreAllNoiseQuery=\"True\" SummaryLength=\"180\" MaxSnippetLength=\"180\" DesiredSnippetLength=\"90\" KeywordInclusion=\"0\" QueryText=\"\" QueryTemplate=\" SPContentType:'Work Instructions'\" TrimDuplicates=\"False\" Site=\"7f709567-3352-48fa-9aca-c962df4106df\" Web=\"86769389-8770-4f94-aa7b-c86e84d66919\" KeywordType=\"True\" HiddenConstraints=\"\" />"`

1. `"<Query Culture=\"en-US\" EnableStemming=\"True\" EnablePhonetic=\"False\" EnableNicknames=\"False\" IgnoreAllNoiseQuery=\"True\" SummaryLength=\"180\" MaxSnippetLength=\"180\" DesiredSnippetLength=\"90\" KeywordInclusion=\"0\" QueryText=\"\" QueryTemplate=\" Path:https://tenantname.sharepoint.com/sites/Retail/WorkInstructions* IsDocument:1\" TrimDuplicates=\"False\" Site=\"7f709567-3352-48fa-9aca-c962df4106df\" Web=\"86769389-8770-4f94-aa7b-c86e84d66919\" KeywordType=\"True\" HiddenConstraints=\"\" />"`

This discrepancy only seem to happen when the CT name has a space, thus I have to use the '' around it.

**Expected behavior**
I would expect the number of items returned to match. What am I missing?

**Desktop (please complete the following information):**
 - Browser - Edge

**Comment by kasperbolarsen** [comment]
In cases like this one step one is to run the two queries in SharePoint search query tool or SP Editor in order to test if the problem is in the query or in the API

**Comment by sympmarc** [comment]
Ok, I'm the dummy. It needs to be `SPContentType:"Work Instructions"`, as in double quotes.
