### ISSUE TITLE
Modern Search not working returning nothing

### ISSUE THREAD

**Issue by benhill32-panpac** [microsoft-search/pnp-modern-search#366]
!! Check existing issues before logging new ones !!

**Version used**
Ex: 3.6.3.0

**Describe the bug**
I'm using Modern search on share point online. Nothing seems to be returning when they click on the search icon. It was working a couple weeks ago. But i'm wondering was it caused by the sharepoint updates  a couple weeks ago. Any help would be awesome.

Cheers 

**Desktop (please complete the following information):**
- Any browser does this.

**Comment by benhill32-panpac** [comment]
![Capture](https://user-images.githubusercontent.com/67875519/86540599-c3bb1100-bf5a-11ea-865d-a259d2c124e4.JPG)

**Comment by wobba** [comment]
You need to provide more information on setup. If it was working then most likely related to #325
