### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by mwreyf** [microsoft-search/pnp-modern-search#3662]
Version 4.11.0

Bug Desc:
When trying to load up the page (in Chrome, Edge, etc...) that is set up as a Employee Directory site, anyone other than myself (Azure Global Admin) is getting this error for each webpart. It doesn't matter what rights I give them nothing fixes the issue. I have uninstalled\reinstalled the .sppkg several times to no avail. Even if I just add either of the webparts but not configure anything for it, it's the same result.

![Screenshot 2024-03-29 162607](https://github.com/microsoft-search/pnp-modern-search/assets/48495665/06a4b2c9-9075-4f4a-bcd9-4e8f8056ad5e)

---------------------------------------------------------------------------------------------
Something went wrong.

If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Script error for: 544c1372-7e5a-49ec-8db6-812f76c375f2_4.11.0/CommonStrings
http://requirejs.org/docs/errors.html#scripterror

CALL STACK:
Error: Script error for: 544c1372-7e5a-49ec-8db6-812f76c375f2_4.11.0/CommonStrings
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_51d298c104de8210069207c8824c1cc0.js:190:11658), <anonymous>:8:252)
    at HTMLScriptElement.onScriptError (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_51d298c104de8210069207c8824c1cc0.js:190:11658), <anonymous>:30:244)

---------------------------------------------------------------------------------------------

Any help on where to look for additional info would be greatly appreciated.

TIA!

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

### Follow the template below or we will have to delete this request!!
We can assist a lot faster if you provide the following information:

**Version used**
Ex: 4.8

**Describe the bug**
A clear and concise description of what the bug is. Keep questions and bugs related to the web parts. If the issue relates to KQL or question around crawled and managed properties please use [Microsoft TechCommunity](https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev). Which means, if you experience the same behavior in classic web parts, then it's not an issue with PnP Modern Search 😉

**To Reproduce**
Detailed steps to reproduce the behavior:
4. Enter setting A, B, C
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by kasperbolarsen** [comment]
Hey,

Can you verify if the users can access the tenant App Catalog?

**Comment by mwreyf** [comment]
![Screenshot 2024-03-30 131059](https://github.com/microsoft-search/pnp-modern-search/assets/48495665/b53bc0d9-0be3-4654-ae04-9822d0d7c7c3)

**Comment by BharatKhunti** [comment]
Hello @mwreyf,

If you deployed latest package in app catalog make sure to get latest version from site content. I think recently I have deployed latest package face similar issue when I go to site content get latest app it work fine for all user.

![image](https://github.com/microsoft-search/pnp-modern-search/assets/31878661/5b641914-4d2b-4446-89c9-f24b1549aeb9)

**Comment by mwreyf** [comment]
I am confused. Your screenshot shows "NEW" version 4.11.0.0 with a release date of "April 2024". I installed that exact version last week (March). Are you saying a "NEW" revision was released today "April 1st" and the "major" and "minor" version numbers didn't change"?

![Current PnP version](https://github.com/microsoft-search/pnp-modern-search/assets/48495665/c34028fd-9f21-472e-a064-ab58e0f17d76)

**Comment by BharatKhunti** [comment]
That because I was trying replicate issue. You can go to your site content where you are using PnP Search web part, click on : and open details page and make sure you app catalog web part version and site level install version are same.

![image](https://github.com/microsoft-search/pnp-modern-search/assets/31878661/e9988426-f406-4110-a5f8-9b377fc350b7)

![image](https://github.com/microsoft-search/pnp-modern-search/assets/31878661/20899745-0d08-4cae-91d4-673cc0f722ff)


![image](https://github.com/microsoft-search/pnp-modern-search/assets/31878661/dff3ffd4-fa4d-4279-8ea1-7d6cc0a975a4)


If not then you can find button "Get IT" and it will get latest web part for you site

**Comment by mwreyf** [comment]
Thank you so much for the detailed explanation. I did have a version discrepancy. I updated to the same version in both areas, and now all is working.
