### ISSUE TITLE
PnP Modern Search - Search webpart doesn't work

### ISSUE THREAD

**Issue by mjnda** [microsoft-search/pnp-modern-search#367]
!! Check existing issues before logging new ones !!

**Version used**
3.14.1.0

**Describe the bug**
we use this solution to custom search results pages in SharePoint Online.
for a week, we have had a problem displaying the pages with the new version 3.14.1.0.

**To Reproduce**
1. Go to 'Site collection '
2. Click on 'webpart

![image](https://user-images.githubusercontent.com/67896456/86610599-ddd20f00-bfad-11ea-8bfa-6249ef52a5f8.png)

**Expected behavior**
we have just the picture , not the description

**Screenshots**
![image](https://user-images.githubusercontent.com/67896456/86610671-f4786600-bfad-11ea-9330-7a637e24137b.png)

**Desktop (please complete the following information):**
 - Browser : Chrome v79 | FireFox v31 | IE v11 | Edge |

**Comment by Heidi-Connor** [comment]
I'm having a similar problem. 

**Version used**
3.11.1.0

**Describe the bug**
Some time last week, two working data elements stopped working in search results:

- SiteTitle started returning as "" for all sites except the site where the Search web parts are configured. 
- Vertical filter for user specific OneDrive results no longer works, "(contentclass:STS_ListItem_MySiteDocumentLibrary AND SiteTitle:{User}"

**To Reproduce**
Steps to reproduce the behavior:

Site Title ---------------
1. Navigate to search page
2. Configure Search Result web part to "Debug" layout.
3. Do a query for content that resides on a site other than the one you are on.
4. Notice that SiteTitle returns as "SiteTitle":""

<Debug results SNIP> 
      "SPSiteUrl": "https://bmgf.sharepoint.com/sites/demo",
      "SiteTitle": "",
</SNIP>

5. Do a query for the site you are on
6. Notice that SiteTitle returns the site's name

<Debug results SNIP> 
      "SPSiteUrl": "https://bmgf.sharepoint.com/sites/testsite",
      "SiteTitle": "Test Site",
</SNIP>

OneDrive files -----------------------
1. Navigate to search page
2. Select vertical for My OneDrive. Query Template = 
{searchTerms} (contentclass:STS_ListItem_MySiteDocumentLibrary AND SiteTitle:{User} AND IsDocument="True")

You will see zero results

1. Use SharePoint Search Query tool
2. Use same query

You will get all the results

**Comment by wobba** [comment]
@mjnda can you share your configuration? File type, template used etc. What are you expecting to see, eg. what property is missing?

**Comment by wobba** [comment]
@Heidi-Connor you haven't changed or upgraded web parts, it just stopped working? If so, it's interesting, but not really a web part issue. That said, I can follow up internally if you give details especially on the OneDrive config you are using.

**Comment by Heidi-Connor** [comment]
Hi @wobba, thanks. No, I haven't made any updates to the web part or the queries, it just stopped working for both SiteTitle and OneDrive with {User}. 

The OneDrive Vertical is configured as follows:

**Tab name**: My OneDrive
**Query Template:** {searchTerms} (contentclass:STS_ListItem_MySiteDocumentLibrary AND SiteTitle:{User} AND IsDocument="True")
**Results Source Identifier** = 8413cd39-2156-4e00-b54d-11efd9abdb89 
This is the default Local SharePoint Results results source

Note: Both issues seem to revolve around SiteTitle, as if I don't include the "SiteTitle:{User}" the OneDrive query works fine. 

If I use the SharePoint Search Query Tool (v2.8.6) I see all of SiteTitle values, but the Search Results web part all of the SiteTitle values that are not on this specific site come back as null "".

**Comment by wobba** [comment]
Can you verify SiteTitle is in the list of managed properties asked for in the web part config?

**Comment by Heidi-Connor** [comment]
The Selected Properties? If so, yes (tab 2 of the Search results setup screen), here’s the full string:

Title,Path,Created,Filename,SiteLogo,PreviewUrl,PictureThumbnailURL,ServerRedirectedPreviewURL,ServerRedirectedURL,HitHighlightedSummary,FileType,contentclass,ServerRedirectedEmbedURL,DefaultEncodingURL,owstaxidmetadataalltagsinfo,Author,AuthorOWSUSER,SPSiteUrl,SiteTitle,IsContainer,IsListItem,HtmlFileType,SiteId,WebId,UniqueID,NormSiteID,NormListID,NormUniqueID,SitePath,Modified,ModifiedTitle,AccountName,FirstName,LastName,Department,JobTitle,WorkPhone,LastModifiedTime,DepartmentId,ParentLink,OrignalPath

Thanks!
Heidi

**Comment by wobba** [comment]
I'll try repro tomorrow but find it weird that the query tool works and the web part don't as it's the same API.

**Comment by Heidi-Connor** [comment]
Yes, totally confuses me too.  The difference when I’m using the query tool is that I’m not using the {User} parameter, I’m specifically querying or SiteTitle:MySite.  I’m still flummoxed as to why it suddenly stopped working. It was working great.

Thanks for the assistance!
Heidi

**Comment by wobba** [comment]
I cannot repro. Testing with a query template of `SiteTitle:{User}` I see it expands, and values are returned. If you use the debug template, do you see the variable expanding?

![image](https://user-images.githubusercontent.com/51104/86707740-8cab3500-c018-11ea-92ed-90c136858a00.png)

**Comment by mjnda** [comment]
hello Wobba,
thank you for your response , issue is fixed .
i used the debug to fix ,it was an attribute that the value was changed  due to the last update applied.
thank you everything works well

**Comment by Heidi-Connor** [comment]
@wobba  - here's snips of what I see in debug:

{
  "queryModification": "* (contentclass:STS_ListItem_MySiteDocumentLibrary AND IsDocument=\"True\") -ContentClass=urn:content-class:SPSPeople",
  "items": [
    {
        "Path": "https://mydomain.com/personal/jane_doe_mydomain_org/Documents/Shared",
      "SiteTitle": "",
      "IsContainer": "false",
....

Same missing SiteTitle value exists when I search sites beyond the site I have the web part on. 

Thanks,
Heidi

**Comment by wobba** [comment]
@Heidi-Connor where in the query template should `SiteTitle` appear? I don't see it and seems you are searching using a wild card `*`. Can you try to configure a webpart test without the vertical web part - just to see if you get the data?

Query could be: ` (contentclass:STS_ListItem_MySiteDocumentLibrary AND IsDocument:1) path:https://mydomain.com/personal`

**Comment by Heidi-Connor** [comment]
Hi Mikael,

Sure. I set up a new page with just a search box and results web part. Configured the query as you suggested. Here’s a snippet from the results in Debug for a file called “archive of Library Resources List”.

{
  "queryModification": "\"archive of library resources list\" -ContentClass=urn:content-class:SPSPeople",
  "items": [
    {
      "Title": "Archive of Library Resources List",
      "Path": "  Archive of Library Resources List.xlsx",
      "Created": "2019-11-11T18:50:27.0000000Z",
      "Filename": "Archive of Library Resources List.xlsx",
      "SiteLogo": null,
      "PreviewUrl": null,
      "PictureThumbnailURL": null,
      "ServerRedirectedPreviewURL": null,
      "ServerRedirectedURL": "  Archive of Library Resources List.xlsx",
      "HitHighlightedSummary": "<c0>Archive</c0> <c0>of</c0> <c0>Library</c0> <c0>Resources</c0> <c0>List</c0><ddd/>",
      "FileType": "xlsx",
      "contentclass": "STS_ListItem_MySiteDocumentLibrary",
      "ServerRedirectedEmbedURL": "  Archive of Library Resources List.xlsx",
      "DefaultEncodingURL": "  Archive of Library Resources List.xlsx",
      "owstaxidmetadataalltagsinfo": null,
      "Author": "Heidi Connor (Plaster Group)",
      "AuthorOWSUSER": "Heidi.Connor@mydomain.org | Heidi Connor | 693A30232E667C6D656D626572736869707C68656964692E636F6E6E6F72466F756E646174696F6E2E6F7267 i:0#.f|membership|heidi.connor@gatesfoundation.org<mailto:Heidi.Connor@mydomain.org%20|%20Heidi%20Connor%20|%20693A30232E667C6D656D626572736869707C68656964692E636F6E6E6F72466F756E646174696F6E2E6F7267%20i:0#.f|membership|heidi.connor@gatesfoundation.org>",
      "SPSiteUrl": "https://mydomain-my.sharepoint.com/personal/heidi_connor_mydomain_org",
      "SiteTitle": null,

And, here’s me searching for the same file via the SharePoint Search Query tool:

[A screenshot of a cell phone  Description automatically generated]


[A screenshot of a cell phone  Description automatically generated]


  *   Heidi

**Comment by Heidi-Connor** [comment]
Hi Mikael,

Did some further testing. What I found is that it seems to be restricted to this one site. I am able to create the same query on another site and it works fine. On this site, I tired creating a brand new page and setting up the search, but get the same missing SiteTitle field values. This site is a Hub, so de-hubbed it and tested, same results.

I’ll try forcing a full re-index of the site and see if that has any effect on the issue.


  *   Heidi
