### ISSUE TITLE
Something went wrong - Office user danish display language

### ISSUE THREAD

**Issue by tbergholt** [microsoft-search/pnp-modern-search#3673]
**Version used**
Ex: 4.11 (update from version 4.8)

**Describe the bug**
After update to version 4.11 PnP Result web part is not working and displaying something went wrong. 
PnP Result web part is working fine if the user has english display language.
When running 4.8 no problem was identified with user having danish display language. 
It is primary the People template that's not working, sometimes the rest of the template is displaying the same issue.

Error message:
FEJL:

Cannot read properties of undefined (reading 'General')

**Comment by kasperbolarsen** [comment]
Hi @tbergholt ,
That sounds weird. The 4.11 release has actually been tested a lot with the Danish language pack, as I am a Dane.

However,  we need some more info from you, like which layout you are using,  and which features in the result web part that is enabled,  like showing total count etc.

**Comment by tbergholt** [comment]
Hi Kasper
Thanks for responding to the issue ...
First time I tried to update from 4.8 to 4.11 all web part was effected the second time it was only the People layout. 
I not using any special features, not even the hover features. Showing  total count is not displayed. I installed it with my user, which is SP Admin and with display language set to English and everything seemed to work from my point of view, but for all the other users with display language set to Danish only the blue print "Something is wrong" was displayed.
When I rolled back to 4.8 everything was working for any language settings.
Today I changed my display language to Danish and after a while the web parts was not working for me, after update to version 4.11. Then I changed back my display language to English and everything was working again, but still not for users with Danish as the display language.
Status now : Using list template as compact for content - working
Using People layout - not working
(With display language set to Danish)  
The problem consists both in Global Catalog and local Catalog, where user are permissioned with read. There at no others installations in the App catalog.
Have tried with an out of the box installations without doing any settings than selecting People template and People results source and it is still not working with the Danish setting (But working with the English setting at the display language).
Torben

**Comment by tbergholt** [comment]
Hi Kasper
I've being doing with this working process for a test ...
Office user display language set to Danish,
Created a Communication site with default language as Danish (Tenant default language is set to English),
Created a local SharePoint App Catalog,
Uploading PnP Custom Search 4.11 to the local AppCatalog (Mark for all sites, no need for check in, refresh done and metadatasprog Dansk - 1030 ),
Page created with the blank page template,
PnP Search inbox web part added, and no Error,
PnP Search Results web part added, Error at once - "Der opstod en fejl", Tekniske oplysninger Fejl: Cannot read properties of undefined (reading 'General'),
Then doing the same working proces with site default language set to English - Errors still the same,
Then doing the same working process with user display language set to English - Everything is working.

**Comment by kasperbolarsen** [comment]
This bug has been confirmed by a colleague of mine :-(
I'll try to debug it ASAP

**Comment by kasperbolarsen** [comment]
@wobba I think we have a merge error that have slipped though in 4.11.
In the SearchResultsWebPartStrings_da-dk file in the sites/appcatalog/ClientSideAssets I can see this in the file

          AsTokensDescription: "I denne tilstand bruges de valgte vÃ¦rdier manuelt gennem tokens og tilgÃ¦ngelige metoder. Eksempel med SharePoint sÃ¸geforespÃ¸rgselsskabelon: {?Title:{filters.&lt;destination_field_name&gt;.valueAsText}}",
          FilterValuesOperator: "Den logiske operator, der skal bruges mellem valgte vÃ¦rdier",
<<<<<<< HEAD
          FieldToConsumeLabel: "Kildefelt til at forbruge",
          FieldToConsumeDescription: "Brug denne feltvÃ¦rdi til at skabe forbindelse til den anden datakilde",
=======
          FieldToConsumeLabel: "Kildefelt til at anvende",
          FieldToConsumeDescription: "Brug denne feltvÃ¦rdi til udvalgte varer",
>>>>>>> 4b7c7e1f08e290b3d1232a7b8e787c8c5cac06e4
        },
        AdaptiveCards: {
          HostConfigFieldLabel: "VÃ¦rtskonfiguration"
        }

**Comment by tbergholt** [comment]
Thanks for confirming...  and all your excellent work with the PnP Custom Search.
It's s very useful and I'm using the product a lot.
Thanks 👍
________________________________

**Comment by wobba** [comment]
Create a 4.11.1 release with this fixed

**Comment by kasperbolarsen** [comment]
tested and it sure looks like the issue has been resolved

**Comment by tbergholt** [comment]
Just been away for a week - I'll try to do the update today.
Thanks for the good work as far for now ...
