### ISSUE TITLE
Lazy loading does not work with search result webpart

### ISSUE THREAD

**Issue by mobun** [microsoft-search/pnp-modern-search#3679]
**Version used**
Ex: 4.11

**Describe the bug**
Several web parts are integrated on one page. As soon as the search result web part is also added, the lazy loading of the sharepoint no longer works and causes long loading times.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Create a new SharePoint page
2. Add multiple standard webparts
3. Publish the page (optional)
4. Test lazy loading (optional)
5. Add PnP Search Result Webpart
6. Publish the page
7. Lazy loading does not work.

**Expected behavior**
Lazy loading of the SharePoint should continue to work

**Desktop**
 - Browser [MS Edge 123.0.2420.81]

**Comment by BorisLand** [comment]
Same behavior for us. All other web parts are loaded when scrolling down, except the PnP Search Results web part. This means that a page with several PnP Search Results web parts leads to performance problems, as all calls are executed directly.
In my example, 2 PnP Search Results web parts are included.
One at the top
One from the bottom of the page
When the page is loaded, both search queries are sent directly.
![image](https://github.com/microsoft-search/pnp-modern-search/assets/38751154/b7e87ad0-8656-4d30-b7cf-84873f7437ae)

**Comment by wobba** [comment]
I recommend using the Page Diagnostics browser plugin to assess your page. https://learn.microsoft.com/en-us/microsoft-365/enterprise/page-diagnostics-for-spo?view=o365-worldwide

It will call out if too many web parts are on the page or if too many requests are being made. Anything outside of what this tool says is ok is not really supported from the product side.

And if there is something we can add to the webpart to make it lazy load and execute, please share details and we can see if someone can implement it.

**Comment by mobun** [comment]
We have analyzed the page with the browser plugin, but this also overrides the lazy loading and does not take advantage of the corresponding benefits.

Further research has shown that the reason for the suspension of lazy loading is the registration of the dynamic data components [(Lazy Loading of the Web Parts - SharePoint/sp-dev-docs - Discussion #7918 (github.com)](https://github.com/SharePoint/sp-dev-docs/discussions/7918)).

Here it would be good for performance if the use of the dynamic data components in PnP Search WebParts could be optionally switched off so that lazy loading continues to work on pages that do not require communication between the WebParts.

**Comment by wobba** [comment]
@mobun I suspected dynamic data being a reason, and should be doable.

**Comment by wobba** [comment]
Fixed in #3710 where I added a new manifest entry for a web part named "PnP - Search Rollup". This version will not register for dynamic data and will defer to be loaded and run the API as other web parts when scrolled into view.

**Comment by BorisLand** [comment]
Hello, great that this works.
Unfortunately with this solution all existing "PnP - Search Result" must be replaced with "PnP - Search Rollup".
What do you think of the idea, if no "Available connections" are selected and no "Extensibility libraries to load" are selected, "allowWebPartConnections" is set to "false", if something is active, "allowWebPartConnections" is set to "true"?
Or via an additional property in the web part?

**Comment by wobba** [comment]
Correct.. but it's the only way to support both web part connection and not due to the way SPFx is built and how it detects if it can lazy load or not. 

In theory I could have a web part setting, being default off for web part connection. But then, as soon as you enabled dynamic data, which would be for all existing parts, a setting is stored internally in SPFx to not-lazy load. And no way to revert this internal setting. To support this dynamically the scenario has to be big enough for Microsoft to invest in exposing such a setting.

I'll see if I can dig into a way to script this unsupported. First step would be to run `Set-PnPWebPartProperty -Key "allowWebPartConnections" -Value $true` on an existing web part. But may be something else to clear out as well.
