### ISSUE TITLE
Extensibility - Handlebars helpers documentation issue

### ISSUE THREAD

**Issue by sympmarc** [microsoft-search/pnp-modern-search#3680]
This is a documentation issue, not a technical issue.

The [Handlebars helpers](https://microsoft-search.github.io/pnp-modern-search/extensibility/templating/#handlebars-helpers) section includes a table which gets cut off on some screen sizes. Because it's a very long table, one cannot know there is a scroll bar - and thus more info to the right - unless one is already is at the bottom of the table.

Seeing the examples in he rightmost (third) column is almost required in order to use these helpers. I'm not sure how best to fix this, thus an issue instead of a PR - so far.

**Comment by wobba** [comment]
Maybe splitting up into paragraphs like this?

#### {{getGraphPreviewUrl "<absolute_URL>"}}
**Description:** Try to determine the preview URL based on an absolute URL using the unified Microsoft Graph URL syntax. For instance,
**Example:** {{getGraphPreviewUrl 'https://

#### {{getGraphPreviewUrl "<absolute_URL>"}}
**Description:** Try to determine the preview URL based on an absolute URL using the unified Microsoft Graph URL syntax. For instance,
**Example:** {{getGraphPreviewUrl 'https://

**Comment by sympmarc** [comment]
I was thinking that. The table is just unwieldy. I'm happy to do it if that seems like a good way to go.

**Comment by sympmarc** [comment]
That doc could probably use a little clean up, anyway.

**Comment by wobba** [comment]
Published the updated docs. Thank you!
