### ISSUE TITLE
Manage Columns Template option on Hover shows all the html behind

### ISSUE THREAD

**Issue by allafridman** [microsoft-search/pnp-modern-search#369]
![ManageColumns](https://user-images.githubusercontent.com/43753953/86797716-01dd3100-c03e-11ea-905f-1029ab4484b1.png)

I have added  HTML markup in the column value in the Manage Columns Template Options for the Details List template, which works great. However when hover over it , all markup is showing up for the end user. Is there a way to prevent it, as end users are confused.

Thanks.

**Comment by FranckyC** [comment]
Hi @allafridman , to get rid of the default behavior (i.e. displaying the whole cell content as tooltip), you can just set the HTML `title` attributre to your link or in the container `div`.

```
<div title="My toolip>
     Your cell content
</div>
```
