### ISSUE TITLE
FIlters show "No values for this filter" when same results are returned from search query

### ISSUE THREAD

**Issue by saraakerlundikea** [microsoft-search/pnp-modern-search#3692]
**Version used**
4.8.0.0

**Describe the bug**
Filters are breaking when the same search results are returned in the search query. This is a behavior we see when using search input from query string parameters. We see the same issue when the same results are returned but with different ranking then the previous search. This is a issue when using synonyms with query modifiers. If we search within the same synonym set, the filters will also break.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Add a pnp search result web part on the SharePoint search page
2. Configure the input search parameter to use q in querystring
3. Add a pnp search filtering web part
4. Add file type as a filter
5. Configure the search results wp to use the filtering web part for filtering
6. Use the top search to search on any word. Ex. test
7. Use the top search to on the same search word. (test)
8. The file type filters will show "No values for this filter"

**Expected behavior**
The filters will show the same filters as previous search

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**
In addition to this issue, this bug will also cause other problems like searching on a word within the same synonym set using query modifiers.

**Comment by kasperbolarsen** [comment]
We can only support the current version,  so please test the issue using that version

**Comment by kasperbolarsen** [comment]
closed due to inactivity
