### ISSUE TITLE
(Website/Docs) - Link Broken on Templating Page

### ISSUE THREAD

**Issue by jimmywim** [microsoft-search/pnp-modern-search#370]
https://microsoft-search.github.io/pnp-modern-search/search-parts/templating/#custom-code-renderers

In the Custom Code Renderers page, the link to `search-custom-renderer` is broken. Tries to navigate to https://github.com/microsoft-search/pnp-modern-search/tree/master/search-custom-renderer

(Looks like it's just missed out from the master/main branch rename)

**Comment by FranckyC** [comment]
Thanks @jimmywim . Should be fixed.
