### ISSUE TITLE
Error when entering page for the first time or deleting cookies/cache

### ISSUE THREAD

**Issue by MikeWILA** [microsoft-search/pnp-modern-search#3700]
**Version used**
4.10.2

**Describe the bug**
When entering the page for the first time or deleting cookies/cache, an error occurs.

We use this plugin for an index of all employees and displaying birthdays.
For displaying birthdays we use the following query template:
RefinableDate00=2000-{CurrentMonth}-{CurrentDate}T00:00:00Z
Result source: LocalPeopleResults

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Enter page where the pnp-modern-search is present
2. When entering for the first time the error should pop-up, or press ctrl + f5

**Expected behavior**
No error should occur when entering the page.

**Screenshots**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/167439501/06dc7d45-c5b5-49ee-b60d-7379c2f1a426)

**Desktop (please complete the following information):**
Microsoft Edge

**Comment by wobba** [comment]
I cannot reproduce. Clearing cookies will remove auth information and force a re-login. If I clear session/localStorage and disable cache, the page still loads fine. Testet with v4.11.

**Comment by jeppesc11** [comment]
We have had the same problem. We have tested with several different versions, but we get the same error. After some page reloads, the error disappears. We have only experienced it on one tenant.

**Comment by wobba** [comment]
I would need some more information and repro steps working everywhere to figure this one out.

**Comment by MikeWILA** [comment]
> I would need some more information and repro steps working everywhere to figure this one out.

What kind of information or repro steps do you require?

**Comment by wobba** [comment]
Every single step I need to take in another/new tenant to repro the issue you are seeing.

**Comment by MikeWILA** [comment]
> Every single step I need to take in another/new tenant to repro the issue you are seeing. Which browser you are using, what version, what operating system etc.

1. Create a new active Communication site via the Admin center
2. Add a new PnP Search Results element to the site
3. Insert following settings:
Available data sources: SharePoint Search
SharePoint search Query template:

{searchTerms} -RefinableString01=1
"SPS-HideFromAddressLists":0
UserName:.nl*
UserName:wilatooling.com*
UserName:wilausa.com*
UserName:wila.com.cn*
Department:a*
Department:b*
Department:c*
Department:d*
Department:e*
Department:f*
Department:g*
Department:h*
Department:i*
Department:h*
Department:k*
Department:l*
Department:m*
Department:n*
Department:o*
Department:p*
Department:q*
Department:r*
Department:s*
Department:t*
Department:u*
Department:v*
Department:w*
Department:x*
Department:y*
Department:z*
JobTitle:a*
JobTitle:b*
JobTitle:c*
JobTitle:d*
JobTitle:e*
JobTitle:f*
JobTitle:g*
JobTitle:h*
JobTitle:i*
JobTitle:j*
JobTitle:k*
JobTitle:l*
JobTitle:m*
JobTitle:n*
JobTitle:o*
JobTitle:p*
JobTitle:q*
JobTitle:r*
JobTitle:s*
JobTitle:t*
JobTitle:u*
JobTitle:v*
JobTitle:w*
JobTitle:x*
JobTitle:y*
JobTitle:z*

Result Source Id / Scope|Name: LocalPeopleResults
Selected properties: DepartmentId, JobTitle, RefinableString02, Title, UserName, WorkPhone
Available layouts: People

Everything else I left on default.
When i refresh this page with CTRL + F5, I get the same error:

Cannot read properties of undefined (reading 'isInternal')

CALL STACK:
TypeError: Cannot read properties of undefined (reading 'isInternal')
    at e.loadComponent (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_b854a303309807080a4721ac6e05808c.js:198:1990)
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_b854a303309807080a4721ac6e05808c.js:198:2627
    at async Promise.all (index 0)

**Comment by kasperbolarsen** [comment]
Department and JobTitle are term store based?
![image](https://github.com/microsoft-search/pnp-modern-search/assets/20593570/44efc9ea-89ce-4637-8744-db4e7b83c5e5)

You can refactor that part of the the query to show only people which have a value in the Department and the JobTitle field, see https://www.m365thinking.com/post/sharepoint-people-search-how-to-clean-up-your-results-by-excluding-accounts

**Comment by wobba** [comment]
I still cannot reproduce the issue. Seems you want to show data where you have a value in all three properties so you should be able to shorten the KQL to:

`{searchTerms} -RefinableString01:1 "SPS-HideFromAddressLists":0 UserName:".nl" Department:* JobTitle:*`

**Comment by MikeWILA** [comment]
> I still cannot reproduce the issue. Seems you want to show data where you have a value in all three properties so you should be able to shorten the KQL to:
> 
> `{searchTerms} -RefinableString01:1 "SPS-HideFromAddressLists":0 UserName:".nl" Department:* JobTitle:*`

I've found the cause of the problem. I switched off the Microsoft Graph Toolkit toggle and the issue dissappeared. I don't know why this caused the issue and what else is making use of this functionality?

**Comment by wobba** [comment]
@MikeWILA then you should try a newer version as toolkit implementation has changed in the last versions if I remember correctly.

**Comment by MikeWILA** [comment]
> @MikeWILA then you should try a newer version as toolkit implementation has changed in the last versions if I remember correctly.

This is what solved the issue indeed. Thanks for the support!
