### ISSUE TITLE
Provide the ability to export/import web part configuration

### ISSUE THREAD

**Issue by jimmywim** [microsoft-search/pnp-modern-search#371]
Some search results web part scenarios involve setting up a lot of configuration options, selected properties, template options, result types, etc.

Migrating these across environments involves many manual steps which risk missing those steps, and lost time trying to find out what step was missing when recreating the search page.

It'd be nice to be able to export & import the configuration of a search results web part, so the complete configuration can easily be migrated between environments (in lieu of the "Export" option available in Classic SP).

**Comment by wobba** [comment]
You can import/export using the PnP provisioning engine. Take a look at `Export-PnPClientSidePage` and `Add-PnPClientSideWebPart`. So there's no no get/set cmdlet right now, but you can work it out. I have created pnp templates with a full config for a page for example which works fine.
