### ISSUE TITLE
PnP search web part gives error each time after updating to newer version

### ISSUE THREAD

**Issue by smadhira5275** [microsoft-search/pnp-modern-search#3717]
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/3716

<div type='discussions-op-text'>

<sup>Originally posted by **smadhira5275** April 26, 2024</sup>
Dear Team,
After updating package from 4.10.2 to 4.11.0, PnP search web parts are not working in all our SharePoint sites. Page shows the below error after updating the package: Attached is the word document with screenshots (one image shows web part errors and other one is shows, PnP upgrade required at site level). This was not the case earlier.

[PnP-IssueScreen.docx](https://github.com/microsoft-search/pnp-modern-search/files/15127980/PnP-IssueScreen.docx)

This is not the behavior for other packages which are deploying at app catalog. Issue is happening only with PnP package. Kindly help me here ?

Thanks.
</div>

**Comment by kasperbolarsen** [comment]
Could you add the screen shot in this thread rather than in a doc please

**Comment by smadhira5275** [comment]
thanks Kasper for looking into it. As requested, please find the attached image of the web part error and app information schreenshots

![PnPWebpartError](https://github.com/microsoft-search/pnp-modern-search/assets/168088288/88d9ec58-1625-4726-8e4c-81d2a915b323)

PnP app information at site level :
![PnPAppInfoatSiteLevel](https://github.com/microsoft-search/pnp-modern-search/assets/168088288/2d206b91-c176-4bfb-802e-3e9904965110)

**Comment by kasperbolarsen** [comment]
We had an issue in v4.11.0 when the language was danish, and this has been fixed in v4.11.1. 
It could be related to that. Can you update to the latest version ?

**Comment by patrikhellgren** [comment]
I have seen the same issue with both 4.11.0 and 4.11.1. It was resolved by deleting the app from the app catalog and then adding it again. This will not remove anything from the sites where it is already installed.

**Comment by smadhira5275** [comment]
Yes, once we removed the package from app catalog and install new package in app catalog, web parts are started working fine!

Any idea why it is happneing only with PnP packages? because I didn't see this behavior for other packages in our Tenant. Issue is happening only with PnP package... 

Do we need to follow this in future (remove package from app catalog and install new package)? or can we expect some solution on this. Kindly please suggest and thanks a lot for helping.

**Comment by patrikhellgren** [comment]
The issue seems similar to the one that appeared after upgrading to 4.8.0, see [release notes](https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.8.0) which had the same solution. Maybe @wobba has some more information or idea why this is happening.

**Comment by wobba** [comment]
Closing as I replied in #3616. This is an spfx issue, not web part. Why it happens frequently for PnP? Maybe because it's a big solution, has multiple web parts and is using dynamic data... just guessing.
