### ISSUE TITLE
PictureThumbnailURL is null when search api has a value

### ISSUE THREAD

**Issue by londify** [microsoft-search/pnp-modern-search#3719]
**Version used**
Ex: 4.9.3

**Describe the bug**
Trying to get the image preview to work.  Using PictureThumbnailURL in the PreviewImageUrl slot.  However when I go to debug mode the value for is always  NULL.  When I search for the document using the REST API, I can see that there is a value for PictureThumbnailURL.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Add PictureThumbnailURL to selected properties in search results web part
2. change to debug mode
3. Notice that the value for the property is null
4. Search for the file via the rest API in a browser.
5. Property PictureThumbnailURL has a value

**Expected behavior**
The PictureThumbnailURL property should render a value in the search results web part

**Screenshots**
![PNP Search Results - Thumbnail NULL](https://github.com/microsoft-search/pnp-modern-search/assets/132087480/fb554676-7450-4b41-88f2-5fef688e8343)
![PNP Search Results - Thumbnail From REST API](https://github.com/microsoft-search/pnp-modern-search/assets/132087480/37437273-09cd-4a4d-894e-74c9dfd8679c)

**Desktop **
 - Browser: Microsoft edge

**Additional context**
Had a search call with Microsoft as the value returned via the search API for PictureThumbnailURL would give an access denied error when putting it in the browser.  That is now rectified after doing a full crawl on the affected libraries.

**Comment by kasperbolarsen** [comment]
As you might know we can only support the current version,  so I hope you can verify if the issue is also present in 4.11.1

**Comment by londify** [comment]
Understood.  Will check on new version and repost if necessary.

**Comment by londify** [comment]
closing as not at current version.
