### ISSUE TITLE
Search Results Preview

### ISSUE THREAD

**Issue by Aparna1708** [microsoft-search/pnp-modern-search#372]
Hi Team,

I am using 3.14.1 version of Search Parts

We could see the preview/thumbnail in the search results is displayed as empty for most of the CSV/ExcelFiles/ASPX Pages/Folders/ZIP/Visio/ MP4 or Video Files/SharePoint Sites and People

Is this an expected behaviour? Preview could be displayed atleast for CSV/ExcelFiles.

One another issue, in Search Filters, I have added refiners with theri display name and connected it to the Search Box - Values are defined as ALL for the refiners as in image attached. Is there something wrong with the configuartion 

![image](https://user-images.githubusercontent.com/68010249/86913073-b315c100-c13b-11ea-8741-415f69d80dc8.png)

**Comment by wobba** [comment]
Thumbnail and preview is not the same. Thumbnails are not currently supported for excel files + other file formats.

**Comment by Aparna1708** [comment]
Thanks for the cofirmation @wobba - How about the Filters?

**Comment by wobba** [comment]
Didn't quite catch your refiner/filter configuration. Can you elaborate? What's the error?

**Comment by Aparna1708** [comment]
As you see in the image, I have added Search Filters webpart to the left and added Refiners, 
![image](https://user-images.githubusercontent.com/68010249/86938169-be79e400-c15d-11ea-978f-081418d48175.png)

But I am not seeing individual values of in the Business Unit/Region... it always says **ALL(number)** no idea why.. :(

**Comment by FranckyC** [comment]
@Aparna1708 What is the type of the column you are trying to map? Can you share the RefinableString155 managed property configuration and crawled property mappings?

**Comment by Aparna1708** [comment]
Hi @FranckyC 
Here it is!

![image](https://user-images.githubusercontent.com/68010249/87122049-b925b200-c2a1-11ea-9cb5-441112d906f1.png)

**Comment by wobba** [comment]
@Aparna1708 do you see the correct values for the refiner in for example classic web parts or the search query tool?
