### ISSUE TITLE
Refiners in Filters Web Part not Updating After Term Rename

### ISSUE THREAD

**Issue by dontthroworanges** [microsoft-search/pnp-modern-search#3722]
**Version used**
Ex: 4.10.1

**Describe the bug**
My refiners are tied to managed metadata terms and over time I have renamed quite a few to be consistent. After the rename, the column value properly updates with the new name. However, when looking in the Filters web part, the old values still show. I have found that only manually removing the metadata, and then re-adding it, will force the refiner to show the correct name. Since several thousand documents are possibly affected by this, some other resolution needs to be presented. 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Rename Term
2. Confirm column properly updates
3. Open Filters Web Part
4. Navigate to Refiners
5. Term Name Not Updates

**Expected behavior**
Upon renaming a term, and the column reflecting the rename, the refiners should also change without manual intervention. 

**Screenshots**
Post Term Rename Shows Correct Name in Document Library Column
![Screenshot 2024-05-01 112838](https://github.com/microsoft-search/pnp-modern-search/assets/48330678/2fbdf20a-f88f-4f3f-97e5-19c711ca21ce)
Post Term Rename - Refiners not updated
![Screenshot 2024-05-01 112746](https://github.com/microsoft-search/pnp-modern-search/assets/48330678/0773c7b6-bf05-4204-b046-62c9e72a9898)

**Desktop (please complete the following information):**
 - MSEdge

**Additional context**
Various terms were renamed at least two weeks ago, so time does not appear to affect this issue.

**Comment by kasperbolarsen** [comment]
Could you check the value return by the API, using SP Editor or the SharePoint Search Query tool?
I am pretty sure that this is a reindex issue, so it is likely that the item hasn't been indexed since you updated the term label

**Comment by dontthroworanges** [comment]
> Could you check the value return by the API, using SP Editor or the SharePoint Search Query tool? I am pretty sure that this is a reindex issue, so it is likely that the item hasn't been indexed since you updated the term label

Hi Kasper,
Looks like it may be an indexing issue as you theorized. The Managed Property as shown in SP Search Query Tool shows the original term name.

**Comment by kasperbolarsen** [comment]
You should be able to provide good data for a NS support ticket by running https://pnp.github.io/powershell/cmdlets/Get-PnPSearchCrawlLog.html
Against one or more of the records,  showing that it has been updated and NOT indexed in a timely fashion

**Comment by wobba** [comment]
A term rename will not be reflected in search unless you update the item or reindex the item. This is expected (afaik) and not a bug.

**Comment by kasperbolarsen** [comment]
That is very unfortunately in cases like this, as the person updating the Department termset label for the 5th time this year😉 have no idea where that term is used. The only solution is to run a certain script 🤣
However,  this issue is not a PnP Modern search issue even though it is visible here.
