### ISSUE TITLE
Refiner values max out at 1000 even though more is set in "# of values"

### ISSUE THREAD

**Issue by evobis** [microsoft-search/pnp-modern-search#3728]
**Version used**
4.9.0.2

**Describe the bug**
Reference to similar post: #1068 

We've got RefinableString01 mapped to the CrawledProperty for Suppliers, which is used as a refiner in the filterpanel webpart, but the filter only shows 1000 values. We've set the "# of values" for that property to 5000, because we know there are a lot more than 1000.
![image](https://github.com/microsoft-search/pnp-modern-search/assets/42673817/84bbd513-f4e7-47e7-ba0e-58d7dee7b272)

![image](https://github.com/microsoft-search/pnp-modern-search/assets/42673817/404ccbda-b243-476e-9c25-cc1198707b43)

![image](https://github.com/microsoft-search/pnp-modern-search/assets/42673817/b2267830-447f-4b58-8044-aa2e422f9f59)

**To Reproduce**
Add a filter to your PnP Filter Web Part which you know will have more than 1000 values. Observe that not all the values are returned.

**Expected behavior**
We'd like to see all refiner values for the amount specified in "# of values".

**Comment by kasperbolarsen** [comment]
Hi Bjarke, as I recall it that limit is in the Search API. Will you be able to run the query again the API directly and check the number of refiners being returned?

**Comment by kasperbolarsen** [comment]
This seems to be the current state: https://github.com/microsoft-search/pnp-modern-search/issues/2879

**Comment by evobis** [comment]
Thank you @kasperbolarsen you are of course correct. I just tested through the Rest Api and saw the same results. I will follow the discussion on the referenced issue. 😊
