### ISSUE TITLE
KQL Issue in Search Templates in Search Result

### ISSUE THREAD

**Issue by prakulsairaha** [microsoft-search/pnp-modern-search#373]
I am trying to use KQL to search both title and body for a search term in search box and only search in specific library. 

(title:{searchTerms})XRANK(NB=2.5) (body:{searchTerms})XRANK(NB=.25)
 -contenttypeid:0x0120* Path:"https://LibraryPath"

Doesnt work anymore, can someone help me with the right KQL

**Comment by wobba** [comment]
That syntax seems wacky 😁 Can you verbatim explain what you try to accomplish? Also see my old post https://www.techmikael.com/2014/11/you-should-use-exponential-notation.html when using decimal numbers.

**Comment by prakulsairaha** [comment]
We are trying to search in a specific library and want to boost title results over body results

**Comment by wobba** [comment]
`{searchTerms} XRANK(nb=3) title:({searchTerms}) -contenttypeid:0x0120* path:https://librarypath`

The above searches in general and boosts when hits are in title. The OOB rank model already adds more weight to title as well, but maybe not as much as you want. Stay away from decimal numbers in XRANK - it can cause localization issues.

Can you elaborate on the content as well so I can understand the scenario where items with not a match in title appears higher? I'm researching how we could potentially solve these scenarios in a better way internally.

**Comment by prakulsairaha** [comment]
So we have 2 search Pages -

1. Scenario 1 - We only whant search results is the search term is displayed in title, need help with query for this scenario.
2. Scenario 2 - We want all search results, but boost the ones which have search term in title. I think the query you provided works well for that scenario.

The content is mostly in one library, organized inside folders, mostly PPT, DOC and PDF files.

**Comment by prakulsairaha** [comment]
Hello

I tried using the query provided but when i search term which are there in title they dont show up first.
For example we have a document named "Qualified" in library, when i search the word, the top results dont even contain the word "Qualified" in Title, are we missing something?

**Comment by prakulsairaha** [comment]
Hello Mikael 

Please help on this.

**Comment by MakingThingsWorkToronto** [comment]
@prakulsairaha - apologize for the silly question: Have you configured sorting in the web part by "Rank" "descending"?

**Comment by prakulsairaha** [comment]
![image](https://user-images.githubusercontent.com/54320564/87863295-9c375180-c927-11ea-8fff-f2d29363b06b.png)

Example -
![image](https://user-images.githubusercontent.com/54320564/87863527-b114e480-c929-11ea-9cfc-106be79482b0.png)

**Comment by prakulsairaha** [comment]
![imp1](https://user-images.githubusercontent.com/54320564/87863536-dbff3880-c929-11ea-945b-745b2bd1811c.png)

**Comment by prakulsairaha** [comment]
I am not sure if the image is getting attached or not but in the Sort Order we have "rank : Descending" 
. This is the query we have used - 
{searchTerms} XRANK(nb=3) title:({searchTerms}) -contenttypeid:0x0120* path:"DOC_LIB_URL"

Suppose i search for - Premium Enhancement
The first search result does not have have any of these works in Title but only in body, the second result does have it in Title and body, so ideally it should be other way round.

**Comment by wobba** [comment]
Sorry.. use `cb` and not `nb` and you get better results. Normalized boost is not hard to figure out. Constant boost is easier. And you
