### ISSUE TITLE
PnP Search People

### ISSUE THREAD

**Issue by federicrios** [microsoft-search/pnp-modern-search#374]
**Version used**
Ex: 3.14.2

**Describe the bug**
In the "Search Results" box when I want to show People.
Enter the Sharepoint admin panel to see the profiles, edit a profile and I saw that there is all the data I want to show. And they all work except "Office".

But when adding it in the managed properties that particular one does not show data, but if the other properties are shown correctly

**To Reproduce**
In the SharePoint Admin, under Users -> Profile i can see the info
![YbyZrj35Ak](https://user-images.githubusercontent.com/19908174/86948214-71245500-c112-11ea-8e36-18a75cde377a.png)

And in the SearchBox I add the proerty and return null
![Dmg9cMvrUM](https://user-images.githubusercontent.com/19908174/86948275-81d4cb00-c112-11ea-9fc0-5676d1883499.png)

I try with another properties as Work email, SIP Address, Name and shows the data ok

**Expected behavior**
I want to show the Office from the user, and make a refinable object with the value.

is this posible? or I'm missing someting..

**Comment by wobba** [comment]
This is outside the scope of the web parts. First part is ensuring the properties get values, and the second part is dependent on recall. I've covered it all in my troubleshooting book, but basically you need to ensure a UPA property is:

* made available to search
* this emits a crawled property
* you need to take care to ensure the cp is included in the people search full text index
   * via direct setting
   * or map it to the `ContentsHidden` managed property

For the property you highlight, it's not mapped to a manged property called `Office`, but `OfficeNumber`. :) 

![image](https://user-images.githubusercontent.com/51104/86962219-cdaf6080-c162-11ea-8084-88a717df5ab8.png)

**Comment by federicrios** [comment]
Thanks!

With this I can finish the People Directory. 
I will read about the steps you mention, in case they ask me to add something more in the future.

Again, thank you very much!
