### ISSUE TITLE
Sticky header feature doesn't work as expected

### ISSUE THREAD

**Issue by jsyska** [microsoft-search/pnp-modern-search#3747]
### Version used
4.11.1

### Describe the bug
The sticky header feature introduced in release 4.11.0 (#3580 by @patrikhellgren) does not work as expected when there are many columns that result in a horizontal scroll. When a user scrolls down (the header stays sticky as expected) and then tries to scroll horizontally to view other columns, the header does not scroll horizontally. This causes the wrong columns to be displayed under the wrong headers.

### To Reproduce
Detailed steps to reproduce the behavior:
1. Go to a page with a DetailsList that has a large number of columns.
2. Ensure the number of columns is enough to require horizontal scrolling.
3. Scroll down so the header becomes sticky.
4. Scroll horizontally to view other columns.
5. Observe the misalignment between the sticky header and the columns below.

### Expected behavior
The sticky header should scroll horizontally along with the rest of the content so that the correct columns are displayed under the correct headers.

### Additional context
This issue affects usability when dealing with wide tables requiring horizontal scrolling. A fix or workaround would be greatly appreciated.

**Comment by kasperbolarsen** [comment]
This indeed sounds like an edge case, and most likely not something that the developer of that feature expected.
I will convert this issue to feature request, and then we can only hope that someone finds the time to implement it.

**Comment by wobba** [comment]
Fix from @patrikhellgren is merged so in the dev branch and part of the next release.
