### ISSUE TITLE
Search Refiner Values repeating in refiner web part

### ISSUE THREAD

**Issue by crgstclr** [microsoft-search/pnp-modern-search#375]
I have created refiners based on a standard site column (using managed metadata); I created a managed property and referenced it for the refiners.

Trouble is that the individual values for the refiner show up twice (see image).  Have you seen this issue before and do you have an idea what is going on?  Thanks very much!
![spo refiner](https://user-images.githubusercontent.com/47647060/86965272-426ba600-c135-11ea-8262-a3859aa34323.PNG)

Craig

**Comment by wobba** [comment]
If you see the same behaviour if you configure classic web parts or use SP query tool it's duplicate terms most likely. One with a trailing space.
