### ISSUE TITLE
SearchResults webpart render broken links to documents if document name has '+' character in filename

### ISSUE THREAD

**Issue by manishkaushal2015** [microsoft-search/pnp-modern-search#376]
[x]Bug

Version: 3.14.2

Steps to reproduce
---------------------
Add pnp-modern-search-3.14.2 package to SP Tenant apps catalog and deploy.
Create a document library or use default document library and add a document with '+' character in document file name.
Create a result source that specifies results from a specific document library on the site. Copy the GUID of the result source.
Create a search result page and add Search Results webpart to the page.
Specify configuration * as Default Search Query, in next screen provide Result Source Id created above to narrow down results from a specific document library.
Load the search results page after saving the configuration of webpart.
In the search results the link generated for the document added above does open correctly.

Issue
------
The '+' character in the link URL for this document is replaced with space character by the webpart.

Ideal Behaviour
-----------------
The link to document should work because SP allows '+' character to be added to file names of documents.
![SearchResult_Bug](https://user-images.githubusercontent.com/12091712/87007439-a5c50900-c205-11ea-971c-1ae68da00ead.JPG)
![SearchResult_Bug_1](https://user-images.githubusercontent.com/12091712/87007555-cd1bd600-c205-11ea-8469-2b1f656ca453.JPG)
![SearchResult_Bug_2](https://user-images.githubusercontent.com/12091712/87007568-d3aa4d80-c205-11ea-8791-c21bb1b1cdfc.JPG)

**Comment by wobba** [comment]
I believe this is fixed with v3.15. Can you verify?

**Comment by wobba** [comment]
Closing due to missing feedback.
