### ISSUE TITLE
Filtering based on current page language in pnp modern search webpart v4.9.3

### ISSUE THREAD

**Issue by arunakshi** [microsoft-search/pnp-modern-search#3762]
### Follow the template below or we will have to delete this request!!
We can assist a lot faster if you provide the following information:

**Version used**
4.9.3

**Describe the bug**
I am trying to filter pages / news based on current page language. 
OOB news webparts are working as per page language. 
Pnp modern search webpart is not working as the OOB webpart.

When I am in DE page, i get all results in DE but modern search webpart is respecting my browser language and giving the results.
When I am in EN page, i get all results still in DE because above mentioned reason. 

I have the following query but this respects the SharePoint display language.
(SPTranslationLanguage:{CurrentDisplayLanguage} OR (NOT SPTranslatedLanguages:{CurrentDisplayLanguage} AND NOT SPIsTranslation:true))
 
then I changed the query with this ending: 
{?{SPTranslationLanguage:{Page._SPTranslationLanguage} OR (NOT SPTranslatedLanguages:{Page._SPTranslationLanguage} AND NOT SPIsTranslation:true)} NOT}  (SPTranslationLanguage:{Site.Locale} OR (NOT SPTranslatedLanguages:{Site.Locale}
AND NOT SPIsTranslation:true))

I tried to use {PageContext.currentUICultureName} but this always leads to null after query resolving. 

**To Reproduce**
Create a page with langugae variant. (one in DE and variant in EN) 
Apply above query, we would need to get DE content when we are in DE page.
We would need to get EN content when we are in EN page if translation page available otherwise DE content should be displayed.

**Comment by wobba** [comment]
To understand, you want to follow the page's language or the UX language?

**Comment by arunakshi** [comment]
I want to follow the page language

**Comment by kasperbolarsen** [comment]
Is the page with the PnP Modern Search Results web part also translated? I have looked at it and it seems like only translated pages have a value in {Page._SPTranslationLanguage}
This seems to support my findings:
https://learn.microsoft.com/en-us/answers/questions/1382550/sptranslationlanguage-field-in-a-caml-query

**Comment by kasperbolarsen** [comment]
If you wonder how to see that the token wasn't available I have uploaded a video about it to YT, https://youtu.be/zZN_zMAosaY

**Comment by arunakshi** [comment]
Thanks for your message Kasper
This will work only for translated pages. I also need it for default pages. I am trying to merge both queries for translated pages or default pages so that it’s easy to provision with the webparts.
