### ISSUE TITLE
Container tree shows the full path up to the tenant

### ISSUE THREAD

**Issue by stevebeauge** [microsoft-search/pnp-modern-search#377]
!! Check existing issues before logging new ones !!

**Version used**
Ex: 3.14.2

**Describe the bug**
When I set up a container tree filter, following the documentation guideline to map RefinableString02 to ows_ParentUrl, I got this result :

![image](https://user-images.githubusercontent.com/184604/87154075-da45cd00-c2b8-11ea-9ccf-00037f9d77d8.png)

**To Reproduce**

1. Apply the guide from the documentation to map any RefinableStringXX to ows_ParentUrl.
2. Ensure the index is up to date.
3. put a filter using the container tree

**Expected behavior**

I expect the filter to show path relative to root of the Web.

**Screenshots**

**Desktop (please complete the following information):**
 - Firefox

**Additional context**

An important information, because this is the root of the issue, is that my search page is another site collection. Basically I build a search center that centralize search of documents from a bunch of sites based on the same model (one site per business unit, all sharing the same site structure).

In my case, the actual site collection where the document are stored are not important, but the folder path within the site is.

Am I right to believe it's due to the algorythm that computer path difference between document url and current site Url ?

If I'm right any way to control this behavior (having the ability to choose would be very nice).

thanks

**Comment by wobba** [comment]
If you limit results to start at a doc lib, does it then work? And how do you want root site and my-site to appear as top nodes?

**Comment by wobba** [comment]
What if you have multi-geo?

**Comment by wobba** [comment]
v3 no longer maintained
