### ISSUE TITLE
When importing a search configuration, the PnP Search Results webpart title can't be changed anymore

### ISSUE THREAD

**Issue by SabbeRubbish** [microsoft-search/pnp-modern-search#3770]
### Follow the template below or we will have to delete this request!!
We can assist a lot faster if you provide the following information:
**Version used**
4.11.1

**Describe the bug**
When importing a specific search configuration (exported before with same version/site etc...) the web part title can no longer be edited.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Create a new page with a PnP **Search Results** webpart
2. Import the attached search configuration (4th tab on the bottom)
[webpartproperties(1).json](https://github.com/microsoft-search/pnp-modern-search/files/15495651/webpartproperties.1.json)
3. Try to edit the webpart title from "Strategic projects you have access to:" to anything else
4. Only the first letter you type gets appended to the end of web part title

**Expected behavior**
I can change the name of the webpart as usual

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Firefox 126
 - Edge 125

**Additional context**
See attached exported Search Results webpart configuration.

**Comment by heaira** [comment]
Yep. This seems to be the case. Anyway the title can be changed from the settings from the last page of the pane. From place you can export the setting you also can change them (also webpart title). This way you will save some time at least..

**Comment by BVSanjay** [comment]
Even it happened to me, I changed it in settings

**Comment by SabbeRubbish** [comment]
Hi heaira,

Thank you for pointing me to the workaround.
Can you get this into the backlog?
Thanks :)

**Comment by kasperbolarsen** [comment]
This IS the backlog. The volunteers in this project picks one of the items in the issues list or a feature of their own choosing and creates an update.

**Comment by SabbeRubbish** [comment]
My apologies, just wanted to make sure it was triaged correctly.
Thank you for all of your work. It truly makes a difference.

**Comment by kasperbolarsen** [comment]
My testing showed that each of the PnP Modern Search web parts locks the Title field on the first save ( Save as draft)
I tested if it impected OOTB web parts (Quick Link) and it does not.

**Comment by wobba** [comment]
Issue is that you cannot edit the title once set, not related to config. Fixed with #3789 in the dev branch.
