### ISSUE TITLE
Chat.Create, Chat.ReadWrite API permission for 'send a quick message' chat option in mgt-person-card is not showing for approval

### ISSUE THREAD

**Issue by BVSanjay** [microsoft-search/pnp-modern-search#3778]
Chat.Create, Chat.ReadWrite API permission for 'send a quick message' chat option in mgt-person-card is not showing for approval

**Comment by BVSanjay** [comment]
@kasperbolarsen

**Comment by wobba** [comment]
A PR is needed to support this functionality. Personally I would rather go with the LPC card vs Graph and then this is not needed. You also get M365 parity on what the card looks like.

<img width="328" alt="image" src="https://github.com/microsoft-search/pnp-modern-search/assets/51104/9360d495-ee51-4c1e-893d-b06f816b3576">

**Comment by tandrasi** [comment]
Just saw this issue today.

@wobba Are you opposed to adding these API permission requests to package-solution.json? I quite like the look of the graph persona card 👍 

`Error: Missing scope permissions on the request. API requires one of 'Chat.Create, Chat.ReadWrite'.`

**Comment by wobba** [comment]
@tandrasi feel free to PR the needed change. Ensure any documentation is updated to reflect this.

**Comment by tandrasi** [comment]
@wobba OK, will do when I find some time

**Comment by tandrasi** [comment]
@wobba thanks so much, can confirm this is working as expected in 4.13.1
