### ISSUE TITLE
Deployment Failed

### ISSUE THREAD

**Issue by jmuehlenbein** [microsoft-search/pnp-modern-search#378]
Hi, I installed version 3.13 and was getting errors so upgraded to 3.13.1 and was getting some different errors so attempted to upgrade to 3.14.2, but the deployment failed (as per UI) and the app is no longer available to be added via "add an app." I then deleted everything (via UI, including recycle bins) to do a fresh install with 3.14.2 (vs. upgrading) but deployment failed again. I have a case open with Microsoft to check the correlation id but does anyone have any ideas I can try in the meantime? I'm able to deploy other packages without issue. 

I've done everything via UI. Do I maybe need to be using PowerShell?

**Comment by wobba** [comment]
UI should be fine. Are you getting errors when uploading to the tenant app catalog? Deployment issues should not be related to the web parts, and rather a https://github.com/SharePoint/sp-dev-docs issue as it relates to SPFx. Can you deploy other packages?

**Comment by jmuehlenbein** [comment]
@wobba, there were no upload errors, just a message in the status column that the deployment failed and a correlation id (for which I'm STILL waiting on Microsoft). I was/am able to successfully deploy other packages via UI. With PowerShell, I get:
get-pnpapp : {"error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot find resource for the request SP.RequestContext.current/web/tenantappcatalog/."}}}
At line:1 char:1
+ get-pnpapp
+ ~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPApp], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Apps.GetApp 

....which led me to believe the tenant is somehow unable to find the app catalog and maybe it's an issue with registration so re-registered it. Then I was able to remove and reinstall the package via PowerShell, But now...even though it's showing as successfully deployed in app catalog, the solution doesn't show up when I attempt to 'add an app' in a site collection. I have a feeling there is some orphaned object causing a conflict somewhere but I'm not sure how to clean it up.  (or maybe that has nothing to do with anything--sorry i'm a noob with this stuff--but...) I'm open to any suggestions. =)

**Comment by jmuehlenbein** [comment]
Update. I'm now able to access the web parts even though I never added the solution as an app (as I did in the past in order to add the web parts). Is that a change or is that how it was supposed to work all along or is there still something wrong with my install?

**Comment by wobba** [comment]
Depends if you check/uncheck tenant wide install. We allowed that a while ago.
