### ISSUE TITLE
PNP Search V4 Modern - PNP Search results webparts "Selected properties" not loading 

### ISSUE THREAD

**Issue by karthi2488** [microsoft-search/pnp-modern-search#3783]
Hello Team,
Am using the latest version of webpart 4.11.1.0
And still facing the same issue of Search results webpart Selected Properties not loading, it just showing the loading icon but not showing any values.

![image](https://github.com/microsoft-search/pnp-modern-search/assets/171905572/e9751dd9-4d84-4b6b-b179-d15287f10ba2)

**Comment by jimmywim** [comment]
Same issue here - multiple tenants, freshly added v4 Search results web part - however v3 works.

Only difference I can see in the payload is that V4 is adding a SortList using DocId direction 0, v3 doesn't have this.

**Comment by kasperbolarsen** [comment]
@jimmywim  thanks for pointing out that finding, it got me thinking if the issue can be related to this one https://github.com/SharePoint/sp-dev-docs/issues/9728 , 
In that is the case then you have to wait for Microsoft to fix the bug or we could drop the sort (I prefer not, there are sometimes loads of them, and finding the right one in an unsorted list can be hard)

**Comment by wobba** [comment]
Either way, not a web part issue and will go away once we remove this code and hardcode the list of properties instead.

**Comment by karthi2488** [comment]
Hello @wobba @kasperbolarsen @jimmywim 

Thanks for providing required information and helping in fixing this issue. Awesome!
