### ISSUE TITLE
Question on query usage 

### ISSUE THREAD

**Issue by jimehren** [microsoft-search/pnp-modern-search#379]
I hope this is the right place to ask questions. 

My client has a list of all employees, the date they were tested for Covid, and whether it was positive or negative. I am trying to configure the search web part to display only the list item for the login user. In a view that would be User=[Me].  I cannot seem to figure this out  With the search web part. The list would be the source, the web part the results. 

Can anyone advise?

**Comment by wobba** [comment]
How is the user stored/persisted in the list? User field, list column, site column....?

Also you could look at using the list web part and have a custom list view with the same filter as well. And use column formatting for the display.

**Comment by jimehren** [comment]
Sorry for the delayed answer. 
Data is stored in a simple custom list:  [Employee Name] [Testing Date] [Results]

The View solution is not viable since this info is confidential and users could get in and change view settings to see other employee test results. A View filtered by [ME] works fine, but there is no way to totally hide the View control or put permissions on Views in O365 as far as I know. (You can on prem with tool like Boost Solutions).

That is why I thought the PnP Search part might be the solution if I could filter on the current user.

**Comment by wobba** [comment]
You can use something from the `{User.xyz}` query variable. https://microsoft-search.github.io/pnp-modern-search/search-parts/search-results/#user-properties
