### ISSUE TITLE
Italian translations

### ISSUE THREAD

**Issue by fabiofranzini** [microsoft-search/pnp-modern-search#3792]
### Discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/3510

<div type='discussions-op-text'>

<sup>Originally posted by **Luca3082** February  7, 2024</sup>
Hi, is it possible to have to italian translation, especially for the filtering part of the solution?
Or what can I do to contribute?
Thanks in advance
</div>

**Comment by wobba** [comment]
In the dev branch and next version.
