### ISSUE TITLE
Refiner Side Panel Display Issues

### ISSUE THREAD

**Issue by malcom1120** [microsoft-search/pnp-modern-search#38]
**Version used**
3.8

**Describe the bug**
The display of refiners in the side panel doesn't look correct.  The headings are smaller than the refiner items and there is no indicator the closed refiners can be expanded.  They look correct when in vertical display mode.

**To Reproduce**
1. Add refiners web part to search page
2. Configure for Side Panel display mode
3. Click on Filters button when results are returned
4. See display formatting issues

**Expected behavior**
Expected the display of the filters in the side panel to look like they do on the page when in vertical mode.

**Screenshots**
Display in vertical mode:
![image](https://user-images.githubusercontent.com/8712085/70730638-60724480-1cd3-11ea-9f83-8cfd352b0494.png)

Display in side panel mode:
![image](https://user-images.githubusercontent.com/8712085/70730706-78e25f00-1cd3-11ea-800a-f4bc78a6bd2b.png)

**Desktop (please complete the following information):**
 - Browser: Edge, Edge Beta, Chrome

**Comment by FranckyC** [comment]
Thank for submitting this issue. You're right, the display is not correct anymore due to an update of Office UI Fabric in SPFx. @PooLP, did you have a PR to submit that fix this issue?

**Comment by PooLP** [comment]
Yes, in my latest PR (https://github.com/microsoft-search/pnp-modern-search/pull/37/commits/0ff71fba0bb9ba962b71bba9a28b93ae1bea5e23)

**Comment by FranckyC** [comment]
@malcom1120 This should be resolved by the latest PRs in the develop branch
