### ISSUE TITLE
Unable to get exact modules

### ISSUE THREAD

**Issue by nileshmarathe** [microsoft-search/pnp-modern-search#380]
Hi,

I have tried to install all the required modules. For some of them I am getting error. 
Error: 
Module '"../../../../node_modules/@pnp/sp"' has no exported member 'SortDirection'.
<img width="710" alt="Capture" src="https://user-images.githubusercontent.com/3920207/87334210-e7361b00-c55b-11ea-8539-60c6562c4073.PNG">

Till now I have installed below modules:
npm install react --save
​npm install react-dom --save
npm install @microsoft/sp-core-library
npm install @microsoft/sp-property-pane
npm install @microsoft/sp-webpart-base
npm install immutability-helper
npm install @pnp/telemetry-js
npm i @pnp/sp
npm install @pnp/spfx-property-controls --save --save-exact
npm install --save @types/es6-collections

It would be great if you provide list of modules with vesrion to be installed.

**Comment by FranckyC** [comment]
Hi @nileshmarathe , the solution uses pnp JS v1 and not v2. You should use `npm i @pnp/sp@1.3.4`

**Comment by wobba** [comment]
Use `npm i` and it installed right version of packages.

**Comment by nileshmarathe** [comment]
Thanks for the reply.
Could you please help me with the other error mentioned in the screenshot?

**Comment by wobba** [comment]
If you have SPFx v1.10 installed according to the docs it should just work. Try removing node_modules and retry. Which folder are you standing in when running commands?

**Comment by nileshmarathe** [comment]
I have checked the version

npm ls -g --depth=0

+-- @microsoft/generator-sharepoint@1.10.0
+-- bower@1.8.8
+-- expand-tilde@2.0.2
+-- global-modules@1.0.0
+-- gulp@4.0.2
`-- yo@3.1.1

I am running commands to the below folder
D:\Projects\SPFX\pnp-modern-search-3.14.2

**Comment by wobba** [comment]
Go to `search-parts` folder, retry and enjoy 🙂

**Comment by nileshmarathe** [comment]
Yes. Later I did with search-parts folder and it worked. Thanks
