### ISSUE TITLE
Improve display of tags

### ISSUE THREAD

**Issue by sympmarc** [microsoft-search/pnp-modern-search#3806]
When displaying tags in the list or card view (at least), the display is rather ugly, and doesn't provide the functionality we had in older versions. This is the case even after adding Auto and enabling localization.

Here's a very simple example. In this result, the file has been tagged with two values for a Managed Metadata column: Finance and Risk. As you can see, the two values are squished together as well as being underlined, which suggests they are links.

![image](https://github.com/microsoft-search/pnp-modern-search/assets/1295627/aa60ce52-c6c9-42f6-bd9b-c95759fae742)

I'd suggest two enhancements, the first being easier than the second:

1. Change the formatting for the tags to list them in a more legible way. At the very least, that would mean putting some white space between them. If we can't do No. 2, then we should also remove the underline.
2. Make the tags actual links, which filter the content for that Managed Metadata value.

I expect I could handle No. 1 -this has bugged me for a very long time, and I wish I'd already made the fix! It's probably just a CSS thing. The second is harder, and I'm not sure how to do it. (Maybe it should be a separate issue, but I wanted to capture these ideas together.)

**Comment by kasperbolarsen** [comment]
Something like this is easy enough ( GitHub Copilot did most of the work)
![image](https://github.com/microsoft-search/pnp-modern-search/assets/20593570/252c1274-78f3-490c-ac76-34b7313eff13)


I would actually prefer that the name of the tag was shown as well as the value by it self sometime doesn't make sense
![image](https://github.com/microsoft-search/pnp-modern-search/assets/20593570/2fcb7127-67c3-41a0-bc34-86b30be98624)

**Comment by kasperbolarsen** [comment]
Then you are in a world of pains. As I recall it a GitHub Copilot license is 10 USD/month and it is worth every cent!

**Comment by kasperbolarsen** [comment]
I got this far: The tags are rendered ok, and the links points to `  <a href="?q=Tags:'{{trim tag}}'" data-interception="off">{{tag}}</a>`
Getting it formatted to use the "f" argument and encoding will require a lot more work, or someone smarter then me ;-)

![image](https://github.com/microsoft-search/pnp-modern-search/assets/20593570/c6f9cf8d-64c0-4f26-bc88-75877fb942ec)

**Comment by sympmarc** [comment]
I think it would be great to have a few options for tag display. The two approaches you've taken above both seem to address use cases.

**Comment by wobba** [comment]
Someone care to PR a change to the default templates for this?

**Comment by kasperbolarsen** [comment]
@sympmarc How about I make a PR for this
![image](https://github.com/microsoft-search/pnp-modern-search/assets/20593570/f10e32bc-15d2-4293-9754-2072bf46fb20)

And add another sample to https://github.com/microsoft-search/pnp-modern-search-layouts for the more advanced version ?
![image](https://github.com/microsoft-search/pnp-modern-search/assets/20593570/40d52c7e-8e68-43c9-9056-ba93ddf82538)

**Comment by sympmarc** [comment]
That would be awesome. Just getting the tags to display more nicely, like in your first example, is a big step forward.

**Comment by kasperbolarsen** [comment]
tested in 4.13 :-) Works fine
