### ISSUE TITLE
Results web part not working for a user

### ISSUE THREAD

**Issue by AHast14** [microsoft-search/pnp-modern-search#3820]
**Version used**
Ex: 4.10.2.0

**Describe the bug**
Hello, we are having a strange issue with the PNP results webpart where it will not load for one user in particular. The search and results webpart are both working fine for everyone else I have seen but just not this one user. I have tried on different browsers, clearing cache and even on different Sharepoint sites but the pnp results web part will just not load/show for this user. I realise it must be an issue with that user's device but any ideas as to what?

**Desktop**
 - Browser - both Chrome and Edge including InPrivate browsing

**Comment by DavorSukeri** [comment]
By any chance are you using Refinement filters: DeparmentId:[HUBSITE GUID HERE] in the results webpart and that user does not have permissions to the hubsite?

If so, then the results webpart would just show an empty box and a button that says "Ask for permission" etc...

**Comment by kasperbolarsen** [comment]
Or perhaps you are using a {User} token in the query? 

We will need to know if this issue is for a specific query or for any query

**Comment by AHast14** [comment]
Hi, this is my query {searchTerms} WorkEMail:domain1; WorkEMail:domain2. We use the PNP search as a staff directory which looks up user details. I will attempt to set up another search with a different query to see if that's the issue. The user has said it worked previously for them, it has only stopped over the last few weeks. There is no error, it is jus blank where the results web part should display.

**Comment by AHast14** [comment]
just to update, I have created a new results web part with no query added using the same search and it is displaying for the user.

**Comment by wobba** [comment]
If you could go to the last tab for both web parts, export the config and compare them, then maybe you can spot a difference?
