### ISSUE TITLE
Unable to display the on-prem results in the seaarch results webpart by connecting to the result source. 

### ISSUE THREAD

**Issue by Bhoomi95** [microsoft-search/pnp-modern-search#383]
!! Check existing issues before logging new ones !!

**Version used**
Ex: 3.13

**Describe the bug**
In my web part, we have 3 navigations one for cloud results and 2 for on prem results. Cloud data is coming as expected, but unable to fetch on prem results by connecting to the result source. 
Even on clicking on prem navigation links, I am seeing cloud results only.

**Comment by wobba** [comment]
Very unclear what the issue is. "Cloud data is coming as expected, but unable to fetch on prem results by connecting to the result source."? If you see data with the debug template it's working. If onclick on hybrid does not work, then this is due to the logic not taking hybrid data into account and you must include logic to handle this. Or we add it as an improvement suggestion.

**Comment by Bhoomi95** [comment]
On Tue, 14 Jul 2020 at 3:35 PM, Mikael Svenson <notifications@github.com>
wrote:

> Very unclear what the issue is. "Cloud data is coming as expected, but
> unable to fetch on prem results by connecting to the result source."? If
> you see data with the debug template it's working. If onclick on hybrid
> does not work, then this is due to the logic not taking hybrid data into
> account and you must include logic to handle this. Or we add it as an
> improvement suggestion.
>
>
We configured the separate result source for on- prem results.. on adding
that result Id to search results configuration, it is not  any results from
that result source

**Comment by wobba** [comment]
Use the result source id + debug template and see what the modified query is. You can also network trace and look at the request/response and verify as passing a guid for a result source id should work.

**Comment by Bhoomi95** [comment]
We are using the hybrid connection, in a result source which is working fine in Classic Search. But the same result source is not working in case of PnP Web Part. Thought the connection is successful. Tested the source and below is the screenshot 



<img width="388" alt="image" src="https://user-images.githubusercontent.com/55408489/87520604-d17e3e00-c6a0-11ea-9e50-2fcf63bbb784.png">

**Comment by wobba** [comment]
I'd appreciate a technical debug so you can verify the result source guid is passed over and you see the query template from the result source reflected in the modified query.

Are you sure you use the right id?

**Comment by Bhoomi95** [comment]
Yes...

The same result source id I am using in classic page, where the OOTB search
is configured. There it is displaying accurately

**Comment by wobba** [comment]
Closed due to inaccurate repro or technical details.
