### ISSUE TITLE
script error on one instance of chrome

### ISSUE THREAD

**Issue by VinArse** [microsoft-search/pnp-modern-search#3830]
**Version used**
v4

**Describe the bug**
Issue is only happening for me and only on Chrome (this is the browser I used to add pages to be searched by PnP)
It appeared while I was creating and testing pages. ots of page creation and lots of testing.
I DON'T have the issue with Chrom on stealthmode/private browsing
Everything works fine on Edge or for my colleagues on Chrome. 
NOT a big issue, BUT since we will be rolling out in a couple of months to a community of more then 2000 users, I would like to understand what is happening to avoid it.

***
TECHNICAL DETAILS
ERROR:
Script error for: 544c1372-7e5a-49ec-8db6-812f76c375f2_4.11.0/ControlStrings
http://requirejs.org/docs/errors.html#scripterror
CALL STACK:
Error: Script error for: 544c1372-7e5a-49ec-8db6-812f76c375f2_4.11.0/ControlStrings
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_7a8be378d90cfc9a8042ae15f96e0f93.js:198:10298), <anonymous>:8:252)
    at HTMLScriptElement.onScriptError (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_7a8be378d90cfc9a8042ae15f96e0f93.js:198:10298), <anonymous>:30:244)
***
**To Reproduce**
no idea how to reproduce it for my colleagues

**Expected behavior**
no error ;)

**Screenshots**
see attached
[pnp chrome NOK vs chrome private OK.pdf](https://github.com/user-attachments/files/16018836/pnp.chrome.NOK.vs.chrome.private.OK.pdf)

**Comment by kasperbolarsen** [comment]
4.11.0 had an issue with language settings,  can you test on a more resent
version?

tors. 27. jun. 2024 19.38 skrev VinArse ***@***.***>:

**Comment by VinArse** [comment]
updating will require a medium size effort with my IT team 🙁
I still have to determine how to do this with them.
They approved our usage of pnp BECAUSE we wouldn't need their help.
nothing else can be done ?  NOt sure language is the issue here. Why would not happen on private mode ?
________________________________
De : Kasper Larsen ***@***.***>
Envoyé : jeudi 27 juin 2024 13:42
À : microsoft-search/pnp-modern-search ***@***.***>
Cc : Vincent Arsenault ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft-search/pnp-modern-search] script error on one instance of chrome (Issue #3830)


4.11.0 had an issue with language settings, can you test on a more resent
version?

tors. 27. jun. 2024 19.38 skrev VinArse ***@***.***>:

**Comment by kasperbolarsen** [comment]
We can't support every version,  so we have to ask everyone to test if the issue is present on that version ( it might have been solved in a resent update, and then we are waisted our time)

If upgrading to the most recent version is an issue for you, I will recommend you to install that version on a site collection controlled by you

**Comment by wobba** [comment]
@VinArse which UX language do you use in your browser of SharePoint?

**Comment by VinArse** [comment]
Thank you for looking into this
as I was inspecting the page/network tab I saw the word "cache" next to status error.
So I deleted what I felt was enough (only the images, NOT the history, NOT the cookies) from my chrome cache
now I don't have the issue anymore
yippi

merci :)

**Comment by VinArse** [comment]
danke!
