### ISSUE TITLE
Search Results Webpart Pagination Mobile misalignment 

### ISSUE THREAD

**Issue by Tyrif** [microsoft-search/pnp-modern-search#3831]
**Version used**
Ex: 4.8.0.0, 4.11.1.0, and 4.12.2.0

**Describe the bug**
We are facing Pagination issue with V4 modern Search Results Webpart. We first noticed the issue on version **4.8.0.0** after upgrading to **4.12.2.0**  we  are still able to produce the issue. We have noticed that when changing pages (mobile only 4.8.0.0, 4.11.1.0, and 4.12.2.0) we cannot change pages because the elements move to the results section (This is the red box highlighted below) even though the UI shows it at the bottom of the list (This is the green box highlighted below). 

![image](https://github.com/microsoft-search/pnp-modern-search/assets/84188726/9a65d7d6-3250-4239-ace7-8a4187ec4146)

**Steps to Reproduce:**

1.  Login to a mobile device
2. Connect web inspector to the device
3. Search for content
4. Using the pagination numbers to swap different pages
5. When you cannot change pages even though you are tapping the numbers, inspect the elements then search for **"pagination"**
6. The pagination shifts up as well as the results.

**Expected Behavior**:Pagination should work smoothly on mobile devices, with the focus moving correctly as the user navigates through the pages.
**Observed Behavior**: The focus is off when using pagination on mobile devices, making it difficult to navigate through pages.

**Environment Details:**

- PnP Webpart Version: 4.11.1.0
- Device: iPhone 12, iPhone 11 Pro Max
- OS: IOS 17.5.1
- Browser: Safari and Chrome

**Configuration:**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/84188726/58daef86-b0eb-4989-a74a-2c080d77b998)
![image](https://github.com/microsoft-search/pnp-modern-search/assets/84188726/a37d4d69-cc80-4d07-a069-3dfae23e2135)
![image](https://github.com/microsoft-search/pnp-modern-search/assets/84188726/753c1516-1071-45cb-88d2-99abcfa86c77)
![image](https://github.com/microsoft-search/pnp-modern-search/assets/84188726/8533994c-784d-44cd-9ccf-38a2c9b26fa7)
![image](https://github.com/microsoft-search/pnp-modern-search/assets/84188726/c26472db-cf35-4e3d-84b3-a51c0bd47f65)

**Comment by kasperbolarsen** [comment]
Tried to recreate this issue on an Android phone,  but the pagination works just fine, and wasn't getting stuck at any time 
Version 4.13.1

**Comment by Tyrif** [comment]
Hi @wobba @kasperbolarsen so it turns out that the issue was caused by SharePoint out of the box styling. Whenever you scroll down on a page the suite/header bar would collapse thus reorganizing the elements. We fixed this issue by creating an extension for mobile that would override Microsoft’s styling.
