### ISSUE TITLE
Details list with multiple sorting columns - arrows on all columns change direction when one is clicked

### ISSUE THREAD

**Issue by corriespondent** [microsoft-search/pnp-modern-search#3839]
**Version used**
Ex: 4.9.3 - updated to 4.12.2

**Describe the bug**
When using the details list layout with multiple sortable columns, clicking one column to sort changes the arrow direction on all columns.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Set up a search result web part, make sure to pull in at least 2 fields based on (sortable) managed properties and refer to those in the layout slots configuration.
2. Edit Sort settings. Add the sortable managed properties as sortable fields, and check the "user sort" option on both.
3. Select the Details List layout. Open the Managed columns panel for the details list layout and add the 2 columns for the sortable managed properties. Check the "sortable" option and select the corresponding sort field.
4. At this point, the search results layout should show results in the details list layout with sortable columns.
5. Click on one of the column headers to sort. Click again to reverse the sort. BOTH column header arrows will change direction.

**Expected behavior**
The current experience is confusing as it's not clear which column is being sorted and all column header arrows change direction. I would expect the active arrow to be a different color to provide a visual cue that I'm sorting by that column, and I would expect other columns to retain their original arrow direction or have a different icon (such as an arrow that is both up and down) to indicate that sorting is possible but not actively sorted.

**Screenshots**
Initial state of configured web part is default sorted by PnPRevision date descending, although there is no visual indication:
![image](https://github.com/microsoft-search/pnp-modern-search/assets/23064475/b88cb4d3-8616-4330-ab7a-5967c68f4e99)

Clicking "Site" sorts on that column but reverses ALL the arrows in all the columns:
![image](https://github.com/microsoft-search/pnp-modern-search/assets/23064475/28254ccb-d412-46a8-a729-a690b8ebb241)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by kasperbolarsen** [comment]
Please check if the issue is there in the current release.  We can only provide assistance on that version.

**Comment by corriespondent** [comment]
Hi @kasperbolarsen  - I have upgraded to 4.12.2 and the issue is the same!
