### ISSUE TITLE
Search Results: query string parameter "filters" not displaying any results

### ISSUE THREAD

**Issue by ileana2019** [microsoft-search/pnp-modern-search#385]
**Version used**
3.14.1.0

**Describe the bug**
For the Search Results webpart, when configuring the query string parameters on the first config page, it is not displaying any results.

**To Reproduce**
1. Add the Search Results webpart to a SharePoint modern page
2. Add this to the page url: ?filters=[{"n":"RefinableString112","t":["string('UCC')"]}] and Edit the webpart
3. On the first config page: select the query string parameter "filters"
4. No results are displayed

**Expected behavior**
Expected results in the search results webpart (according to this url: https://microsoft-search.github.io/pnp-modern-search/search-parts/search-results/#filters-deep-links)

**Comment by MakingThingsWorkToronto** [comment]
For this to work, you should not add the query string parameter in the configuration. Filters are consumed by default in the search results web part.

Can you please remove the query string mapping in configuration, set to a default query and report back with your findings :)

There is another issue #230 - take a look at that and let us know if you see something similar.

**Comment by ileana2019** [comment]
Hello,
Indeed, now it works just by adding ?filters=[{"n":"RefinableString112","t":["string('UCC')"]}] to the url and without changing any settings in the search results webpart. However, when I do that, I see also the other filters values inside the filters webpart, although I only filtered on 1 value (see attachment). IS there a fix for this?
![FIlter using query parameters](https://user-images.githubusercontent.com/55545989/88190600-c1370780-cc3a-11ea-955c-0085437b8707.png)

**Comment by MakingThingsWorkToronto** [comment]
@ileana2019 ... A pull request was merged into develop hopefully with a fix that addresses this issue. You can try building from there if you need something quick or wait for the next release.
