### ISSUE TITLE
Search Results: Hide this web part if there's nothing to show: removes padding and margins

### ISSUE THREAD

**Issue by Lou-i3** [microsoft-search/pnp-modern-search#3850]
### Follow the template below or we will have to delete this request!!

**Version used**
Ex: 4.12.2

**Describe the bug**
On the PnP Search Result web part, when the "Hide this web part if there's nothing to show" parameter is enabled, the padding and margin of the web part are broken. 
When this setting is enabled on the WebPart, inspecting the DOM reveals that the div with data-automation-id="CanvasControl" wrapping the results has an inline style set to: `padding-top: 0px; padding-bottom: 0px; margin-top: 0px; margin-bottom: 0px;`. 

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Add PnP Search Result web part to a page
2. Make sure there are results returned from the request
3. Enable "Hide this web part if there's nothing to show"
4. Publish the page 

**Expected behavior**
The layout of the web part should be the same wether this parameter is on or off. 

**Screenshots**
See screenshot, comparing with the setting off (left) and on (right): 
![image](https://github.com/microsoft-search/pnp-modern-search/assets/67910996/f091d68e-a1fc-4581-834c-be0e258cecaf)

**Desktop (please complete the following information):**
 - Browser: Brave 

**Additional context**
I tried with different requests and different templates but always get the same behaviour.

**Comment by kasperbolarsen** [comment]
Hi,
Which layout are you referring to, or is it the same for all layouts?

**Comment by Lou-i3** [comment]
Hi, 
Yes it is the same for all layouts, even Adaptive Cards.

**Comment by wobba** [comment]
I suspect we need to add a check if a web part header is set - then don't remove padding.

**Comment by wobba** [comment]
@Lou-i3 if you have a web part title, and there is no content, then the web part title should also be hidden - would that be the correct fix?

**Comment by Lou-i3** [comment]
@wobba yes if there is no content, the web part should be completely hidden, title hidden too. 

My screenshot showed a lot of results because I just made an example for the screenshot. 
My scenario is that there aren't always documents from the query and if there are no documents, there shouldn't be anything displayed.

**Comment by jblueml** [comment]
@wobba  I just checked this and figured out, what behaviour @Lou-i3 means: 
If you have 2 Search Results web parts side-by-side (e.g. in a 2-column-section) and _one of them_ has the setting "Hide this web part if there's nothing to show" set to TRUE, padding and margin are set to 0px - even if there are results to be shown. 
If _both_ web parts show results > 0, they are displayed misaligned.

Solution would be only to remove padding and margin, if there are no results - and not just if the setting is set to TRUE.

I will check the code and try to fix it.

**Comment by wobba** [comment]
@jblueml I see the issue in the code as you say.... web part removed padding based on the toggle only, not on the results coming back. Curious why I made it this way 😅

**Comment by wobba** [comment]
Fixed by #3867 in the dev branch and will part of the next release.
