### ISSUE TITLE
Search Verticals webpart could not be added to page- only refreshed the page

### ISSUE THREAD

**Issue by Mykie89** [microsoft-search/pnp-modern-search#3859]
**Version used**
4.12.2.0

**Describe the bug**
I want to use Search Verticals webpart on the page, but when I want to add to the page, the webpart not loaded only refresh the page.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to 'Page'
2. Click on 'Edit'
3. Add new webpart and select 'PnP - Search Verticals'
4. The page reloads and the webpart doesn't appaer on the page
5. No error message 

**Expected behavior**
PnP Search Verticals webpart appear on the page and can use.

**Screenshots**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/38752403/2bb33f33-7c20-4673-a3d0-a5832b7b4f49)

**Desktop (please complete the following information):**
 - Chrome Version 123.0.6312.106 (Official Build) (64-bit)
 - Edge 126.0.2592.81

**Additional context**

**Comment by kasperbolarsen** [comment]
Hi, can you check if the delegated permission GroupMember.Read gas been approved?
Search Verticals now supports target audience which requires this permission,  so that might be the reason for the issue

**Comment by Mykie89** [comment]
Thanks, this was the problem, after we approved the permissions the webpart appear on the page

> Hi, can you check if the delegated permission GroupMember.Read gas been approved? Search Verticals now supports target audience which requires this permission, so that might be the reason for the issue

**Comment by kasperbolarsen** [comment]
@patrikhellgren is this property set to false/off by default 🤔?

**Comment by patrikhellgren** [comment]
@kasperbolarsen Hmm, the group membership is probably probably loaded even if no verticals has any audience. I'll have a look later today and at least handle the error if missing permissions.
