### ISSUE TITLE
Check for requiresCustomScript

### ISSUE THREAD

**Issue by kasperbolarsen** [microsoft-search/pnp-modern-search#3877]
Ensure that the web parts don't require requiresCustomScript as per https://learn.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script
Deadline Nov 24

Add finding ti the Q&A section in the documentation

**Comment by wobba** [comment]
What's this task about/for?

These web parts will never allow custom script into the web part solution we deliver - hence all extensibility is via SPFx extensions like handlebar helpers or web components. Governed solutions you must install.

**Comment by kasperbolarsen** [comment]
Excellent,  I just wanted to make absolutely sure that we didn't have an issue in November 😊
Since I didn't know, I guess there might be other users of the web parts that wonder if they might have to do something to avoid this. 
I'll update the Q&A section and close this issue

**Comment by kasperbolarsen** [comment]
Documentation updated
