### ISSUE TITLE
Modern Search Transition to OOB SharePoint Features?

### ISSUE THREAD

**Issue by TracyGH** [microsoft-search/pnp-modern-search#388]
Hi there,

I have a question regarding the future of modern search features.  I assume that many/most of these web parts will eventually become available OOB within SharePoint online.  For example, [this road map](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=SharePoint&searchterms=57054) item currently list as 'In Development'.  What will deployment of this feature look like?  Will these be web part(s) that become available to add in native online SharePoint?  And if so, what happens to the PnP solution equivalents?  Will support for those continue, or should we eventually plan to replace them with OOB versions as they are rolled out?  

I have a number of clients who want to leverage modern search for custom solutions.  But they are leery of anything 'custom' and want to stick with MS supported features/functionality.  If I deploy/implement a PnP solution for them, I'd like to feel confident that it will continue to work as-is for many years to come.  I realize no one has a crystal ball, but I would appreciate any/all insight.

**Comment by MakingThingsWorkToronto** [comment]
I can't speak for Microsoft but there are no SharePoint Modern Web Parts for search in the pipeline.  Microsoft Search will be customized in the admin center where you can build custom UIs using Adaptive Cards (in the browser) & custom verticals. There was a demo video (can't find it), but I haven't seen the functionality in my tenant yet.

Without the ability to build refiners & vertical searches (aside from custom Microsoft Search Connectors) Microsoft Search isn't yet on par with SharePoint search. I'd expect more announcements around Ignite in September.

**Comment by wobba** [comment]
Hi,
As @MakingThingsWorkToronto says there is currently no work in progress to replace the classic web parts with oob modern versions. It's however being evaluated and discussed at regular intervals.

The current process for customization of Microsoft Search is as the roadmap item points to, allow you to configure parts of the OOB UI in terms of what verticals to show, which filters to show per vertical and also allow you to specify additional KQL to limit what a vertical shows.

We're also working to allow you yo use adaptive cards to custom render any element, which today only works for Graph Connector results.

Search wise there are a different search based scenarios to solve. My primary use case for the PnP Modern Search web parts is more advanced highlighted search web part scenarios, or search application scenarios - not a replacement for the OOB search page.

If you think about most of the web parts in modern today they are targeted towards editors/power users crafting some roll-up experience - with some interaction. The full set of PnP modern search web parts is more targeted towards developers and consultants - same as the classic web parts. Striking the right balance is never easy.

@TracyGH , if you can you share what your scenario is - it's easier to say if you should wait for OOB configuration vs going all out custom :)

**Comment by TracyGH** [comment]
Thanks @wobba!  Scenario #1 would be a dynamic vs static query.  I know I can use the Highlight web part to generate a custom KQL query, but it's static.  Is there a modern, OOB way to allow end users to provide search terms included in the query?  If not, do you know what the anticipated solve is for that?

**Comment by wobba** [comment]
@TracyGH currently there are no option in the HCWP to allow passing in terms. Basically you would like to pass in a query param to filter something in HCWP right? Would that solve a scenario you have? Or would you need more templating options as well?
