### ISSUE TITLE
Search Vertical: Send query params or fragments

### ISSUE THREAD

**Issue by sionjlewis** [microsoft-search/pnp-modern-search#389]
**Is your feature request related to a problem? Please describe.**
Extend the Search Vertical webpart

**Describe the solution you'd like**
Send either the query parameters or fragments to another page, if included in the original page's URL. Here is an example of what could be done: https://github.com/sionjlewis/pnp-modern-search/commit/0523c5eeeb9dcd4d3aad75b5e883309828b78b6a

**Comment by wobba** [comment]
Please describe what you are solving and rather do a PR instead of linking. Easier to figure out what you try to accomplish.

**Comment by sionjlewis** [comment]
Thanks for your replay @wobba. 
I'm not sure what a PR is? Sorry I am not down with the cool kids, so here goes :)

Similar to the **Search Box** webpart functionality (see image); when using the **Search Vertical** webpart to open _other_ search results pages we require a way to pass existing search term(s). 

This could be accomplished either appending the "classic" **query string parameter(s)** or a **URL fragment** to each **Link URL**.

 There may be a more elegant way, however my previous message shows [one possible solution](https://github.com/sionjlewis/pnp-modern-search/commit/0523c5eeeb9dcd4d3aad75b5e883309828b78b6a):
_...webparts/searchVerticals/components/SearchVerticalsContainer/SearchVerticalsContainer.tsx_ 

**Line: 9**
`import { isEmpty } from '@microsoft/sp-lodash-subset';`

**Lines 82 to 84**
`// Send either the query parameters or fragments to another page, if included in the original page's URL.
let queryString = !isEmpty(window.location.search) ? window.location.search : !isEmpty(window.location.hash) ? window.location.hash : '';
window.open(resolvedUrl + queryString, behavior);` 

In image 3 I am attempting to show the behaviour:
1. User Action: Enter a search term in the the Search Box webpart and press enter. 
    Function: The page does a postback with appended search term and displays results.
2. User Action: Click on a Search Vertical link. 
    Function: The browser opens a new results page having had the search term appended to the link.
3. User Action: Reviews the URL and results - note the appended search term.
    Function: None

### Image 1: #Search-Box-webpart
![SearchBox](https://user-images.githubusercontent.com/4746622/87732389-ee417f80-c820-11ea-85ab-e1787dfd9123.PNG)

### Image 2: #Search-Vertical-webpart
![SearchVertical](https://user-images.githubusercontent.com/4746622/87732468-28ab1c80-c821-11ea-9b6c-e6ef015ed316.PNG)

### Image 3: #Search-Results-Page
![SearchPage](https://user-images.githubusercontent.com/4746622/87733459-ffd85680-c823-11ea-8e6e-bbd85105939c.PNG)


#PnP-Search-Vertical #configure-search #URL-fragment #query-string

**Comment by MakingThingsWorkToronto** [comment]
How would this be different from the tokens described in the documentation here: https://microsoft-search.github.io/pnp-modern-search/search-parts/search-verticals/

**Comment by sionjlewis** [comment]
> How would this be different from the tokens described in the documentation here: https://microsoft-search.github.io/pnp-modern-search/search-parts/search-verticals/

I've just updated my previous post to include:

Background
I was looking for a way to display different kinds of search results, such as documents/pages, people, images/videos using different layouts. The Search Results webparts has this functionality built-in, including Simple View, Detailed View, Tiles and more...

The Search Vertical webpart give the User the option to display different results on the same page, However, these results always use the same Search Results layouts.

The workaround is to configure the Search Vertical webpart to open a new page, which hosts a Search Results webpart configure to use the desired layouts.

The Challenge
The existing Search Vertical webpart does not have a way to pass a search term to other pages.

**Comment by MakingThingsWorkToronto** [comment]
You can pass in the tokens to a new page. Just append the token as above. For example, https://site/results.aspx?q={searchTerms}

There are a list of tokens in the documentation. If you don’t see the option when you’re editing the search verticals you will need to upgrade to the newest version (read release notes).

**Comment by sionjlewis** [comment]
Cool, I will give it a go

**Comment by sionjlewis** [comment]
> You can pass in the tokens to a new page. Just append the token as above. For example, [https://site/results.aspx?q={searchTerms}](https://site/results.aspx?q=%7BsearchTerms%7D)
> 
> There are a list of tokens in the documentation. If you don’t see the option when you’re editing the search verticals you will need to upgrade to the newest version (read release notes).

Cheers @MakingThingsWorkToronto 
Based upon your replay; I wanted to use a URL Fragment with the search box value, so did this:  [https://site/results.aspx#{SearchBoxQuery}](https://site/results.aspx#{SearchBoxQuery})
