### ISSUE TITLE
Add FileType Refiner Template

### ISSUE THREAD

**Issue by malcom1120** [microsoft-search/pnp-modern-search#39]
**Is your feature request related to a problem? Please describe.**
Would like to see a new Refiner template for FileType that works like classic.

**Describe the solution you'd like**
A new refiner template for the refiner webpart that shows a friendly name for the Filetype like in classic instead of the raw value.

**Describe alternatives you've considered**
Used the default refiner template, but users are not liking having to fine docx instead of Word.

**Additional context**
Screenshot of what classic looks like
![image](https://user-images.githubusercontent.com/8712085/70739298-82c08e00-1ce4-11ea-96e1-120d6952f969.png)

**Comment by FranckyC** [comment]
Hi @malcom1120. This should be resolved by PR #37. Let me know if it works for you.
