### ISSUE TITLE
Search Vertical: to showing the selected vertical

### ISSUE THREAD

**Issue by sionjlewis** [microsoft-search/pnp-modern-search#391]
**Package: pnp-modern-search-parts.sppkg**
**Version:  3.14.2.0**

### Configuration / Set-up:
I have created x4 search results pages, using the Search Vertical webpart to each other:
1. All Documents                 .../Results.aspx
2. Controlled Documents    .../Controlled-Documents-Results.aspx
3. Videos                             .../Video-Results.aspx
4. People                             .../People-Results.aspx

![SearchVertical](https://user-images.githubusercontent.com/4746622/87754564-50b67200-c859-11ea-811e-2b3017f53c7a.PNG)

### As a User:
1. I navigate to the All Documents results page and complete a search
2. I then decide to search for a person and click on the People Link, within the Search Vertical webpart
3. The People-Results.aspx opens:
    **Errors**: the Search Vertical webpart has the **All Documents** link selected
    **Expected Behaviour**: the Search Vertical webpart should have the **People** link selected

![Capture](https://user-images.githubusercontent.com/4746622/87756242-a8a2a800-c85c-11ea-8793-4a67e1ae2721.PNG)

The above image is showing the:
1. Page URL: .../People-Results.aspx
2. A cross next to the "All Documents" vertical/link - which is selected
2. A tick next to the "People" vertical/link - which is not selected

### Functional Requirements:
The expectation is that the webpart would compares the page URL with the configured Link Url(s) and on finding a match selecting/underlining the reliant Link/Vertical.

**Example Date:**
- Results Page URL:            https://tenant.sharepoint.com/sites/Search/SitePages/People-Results.aspx#Si%C3%B4n%20J.%20Lewis
- Search Vertical Link URL: https://tenant.sharepoint.com/sites/IntranetSearch/SitePages/People-Results.aspx#{SearchBoxQuery}
- Suggested Match:           /sites/IntranetSearch/SitePages/People-Results.aspx

### Another side effect:
If the **Search Results** webpart is configured with the **Connect to search verticals** setting On, then the User may never see the results from the correct results source as the wrong vertical is selected.

**Comment by sionjlewis** [comment]
**This turns out to be a non-issue.** 
I installed the package and configure the Search Webparts on another Tenant and the Search Vertical worked as expected. 
I then returned to my original Tenant, removed the Vertical webpart and replaced with a new instance, which resolved the issue I was seeing (see below):

![Capture](https://user-images.githubusercontent.com/4746622/87887643-0d3b4e00-ca7b-11ea-9dd4-f4ed57937c39.PNG)

**Comment by wobba** [comment]
You can pass in the default vertical to use on a page with a query parameter using the name of the vertical.

![image](https://user-images.githubusercontent.com/51104/87929450-bdfb1a80-ca86-11ea-99ea-a13f451e4b69.png)
