### ISSUE TITLE
Web part title editing

### ISSUE THREAD

**Issue by calebmil** [microsoft-search/pnp-modern-search#3911]
### Follow the template below or we will have to delete this request!!
We can assist a lot faster if you provide the following information:

**Version used**
4.12.2

**Describe the bug**
Editing the web part titles on a published page does not work as expected.  After each key stroke, the cursor jumps to the end of the title instead of remaining in place.  As a result, I can only add one character or delete/backspace one character in the title without clicking within the title to move my cursor back to where I was working.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Create a new page and add any of the web parts to it.
2. Add a title value (multiple words works best for illustration purposes)
3. Publish the page
4. Edit the page and attempt to change the web part title somewhere that is not at the end of the title.
5. See error

**Expected behavior**
I expected the cursor to remain in the same place until I used my mouse, arrow keys or otherwise performed an action that should cause the cursor to move.

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome 126.0.6478.127

**Additional context**
Upgraded from 4.12.1 where I could not edit the title at all.  Tested four of the five web parts from the package.  Did not try search rollup.

**Comment by kasperbolarsen** [comment]
I can confirm that when trying th editing the web part title on a results web part the cursor is automatically placed at the end of the title

**Comment by kasperbolarsen** [comment]
@calebmil do you agree that this is a minor annoyance rather than a blocking bug?

**Comment by calebmil** [comment]
> @calebmil do you agree that this is a minor annoyance rather than a blocking bug?

Unfortunately, for our content owners, this is a blocking issue.  I have built a template page that is pre-configured with a search result web part to show results in the context of multiple content elements.  They are copying the page, updating the search criteria in the Query template then renaming the web part to align with the topic of the page.  They are repeating this process for numerous product pages.  The results web part is only one of several other pre-built web parts on the page so editing the title really needs to work for them.

**Comment by wobba** [comment]
Fixed in #3935
