### ISSUE TITLE
When a email address contains a single quote, their user email is truncated

### ISSUE THREAD

**Issue by priests123** [microsoft-search/pnp-modern-search#3916]
**Version used**
4.12.2

**Describe the bug**
As a part of the `pnp-persona` component, there are calls to the `getUserEmail` Handlebars template helper to get a users email address from the search results. However, if their email address contains a single quote, e.g `joe.o'connor@tenant.com`, the email address returned from the `getUserEmail` helper is `connor@tenant.com`

**To Reproduce**
Steps to reproduce:

1. Find a user with a single quote in their email address
2. Set up people search to show the persona card
3. Search for the user

The user's email will display as  `connor@tenant.com`

**Expected behavior**
The user's email should be displayed as ` joe.o'connor@tenant.com`

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: chrome, edge

**Additional context**

I do realise this issue is a duplicate of [#1858](https://github.com/microsoft-search/pnp-modern-search/issues/1858). I believe a fix to be updating the regular expression in the `getUsersEmail` to support characters in email address. The regular expression could be the [valid email address from the HTML standard](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address)

**Comment by priests123** [comment]
I'll look to do a fix for this

**Comment by wobba** [comment]
Fixed with #3925 in the dev branch and will be part of the next release.
