### ISSUE TITLE
People results display

### ISSUE THREAD

**Issue by jmuehlenbein** [microsoft-search/pnp-modern-search#392]
Hi, can you please tell me what the expected behavior is for the People display template? I assumed it might work like in the classic people search vertical where each item in the results list links to the corresponding user's Delve profile. But for me, the pnp people results are not linking to any additional detail. Is that intended?

**Comment by wobba** [comment]
Correct...it uses the ouifr persona component (https://docs.microsoft.com/en-us/javascript/api/overviews/persona overview) which don't have a click target. But agree it would be nice to have a click target.

**Comment by Georg-Trixl** [comment]
Hi you all!

Yes I also see, that it would be nice to have more interactions available for People search.
That is also the reason, why we do use a custom display template for people search.
In our custom solution we have links to Delve (even though Microsoft didn't improve Delve during the last years)
But we have HTML5 links for phone numbers and also display custom data.
We display the city of the co-workers office, the department and the job title.
Those infos have been considered as useful for us in people search and there could be even more infos.
But for our 10000 co-workers is the custom solution quite successful.

The solution to use the Fluent Persona Card in People search is very nice starting point for creating a people search.
But the Fluent Persona Card is also limiting the possibilities of this search solution.

I am very grateful for the impressive implementation this team did, it is a great tool that does a superb job for our organization SOS Children's villages.

**Comment by wobba** [comment]
Added custom rendering of the title to include link to the profile :)

**Comment by jmuehlenbein** [comment]
@wobba , so happy to see you added the click target! Thank you so much! We can now use the pnp web parts for our project. Still, I wanted to review the persona reference info but the link to the api overview is throwing a 404 and I'm not finding any results when searching for "ouifr persona." Any ideas?

**Comment by wobba** [comment]
It's now fluent ui - https://developer.microsoft.com/en-us/fluentui#/controls/web/persona
