### ISSUE TITLE
People Results - Tertiary Field must use UserEmail to display hover correctly

### ISSUE THREAD

**Issue by buildbod** [microsoft-search/pnp-modern-search#3941]
**Version used**
Ex: 4.12.2

**Bug Description**
When the Tertiary Field is a value other than UserEmail e.g. not using the default of 

`{{getUserEmail (slot item @root.slots.UserEmail)}}`

![image](https://github.com/user-attachments/assets/b05edf2e-e8a0-42fe-bdb2-ea8fc6379781)

the hover pane displays incorrect values e.g.

with UserEmail:

![image](https://github.com/user-attachments/assets/8ffbbf1a-480d-44c1-b416-5fce7fbd83a0)

changing the field to any value other than UserEmail e.g.

![image](https://github.com/user-attachments/assets/64d919cc-0aa4-4f35-ba1e-dcd78a19a19c)

![image](https://github.com/user-attachments/assets/6848bbec-31ce-4d5f-8b22-45b49f334cf8)

**Steps to Reproduce**
Detailed steps to reproduce the behavior:
1. Select People as the layout
2. Select the option to use the Microsoft Graph Toolkit
3. Select the option to Show persona card on hover (LPC)
4. Select the option to Manage people fields
5. Change the value of the Tertiary field to something that does not use UserEmail
6. View the results

**Expected behavior**
Hover pane to display the correct values

**Screenshots**
Included above. Screenshots use Extra Large view.

**Desktop**
 - Browser issue appears in both Chrome Version 128.0.6613.85 (Official Build) (64-bit) and Edge Version 128.0.2739.42 (Official build) (64-bit)

**Comment by kasperbolarsen** [comment]
Hi Simon, please review https://github.com/microsoft-search/pnp-modern-search/pull/3835 which have just been released in the new 4.13 version :-) 
I am testing the new release and it seems like the issue has been resolverd

**Comment by buildbod** [comment]
Thank you for addressing this
