### ISSUE TITLE
Sharepoint online global search suggestions are not retrieving data in pnp search

### ISSUE THREAD

**Issue by Shabbar2668** [microsoft-search/pnp-modern-search#3953]
Hi,

We have configured PNP search with SharePoint online global search. So, when a user searches for something from a global search, it redirects to the PNP search results page.

As we all know, SharePoint gives some suggestions related to People, users, documents, and pages. Now, when a user clicks on a person's profile from the suggestions, it does not retrieve any data.
Please refer below image:
<img width="252" alt="image" src="https://github.com/user-attachments/assets/430bafcc-99e8-4c92-bcb5-2e84c8643eea">

PNP search results web part is not retrieving any data it is showing empty

**Comment by kasperbolarsen** [comment]
Please follow the Issue reporting form, as this post is very incomplete and raises a lot of questions that would be answered if you fill out the form

**Comment by Shabbar2668** [comment]
Hi,

Can you please help me where to access that form.

Thank you.

**Comment by kasperbolarsen** [comment]
When you create a new bug report in here, you will see this: Fill out the questions and we will address the report ASAP. 
![image](https://github.com/user-attachments/assets/d0ef14f0-c001-4957-9d99-4e61cae0e3a0)
