### ISSUE TITLE
Vertical links with result count(s) if a SharePoint query is also provided

### ISSUE THREAD

**Issue by Georg-Trixl** [microsoft-search/pnp-modern-search#396]
**Is your feature request related to a problem? Please describe.**
Current status:
* Verticals are showing optional result counts, for configured verticals.
* In the vertical webpart are "external" links configurable
* Verticals do have all the same configured main rendering templates

Desired status:
Verticals are showing result counts also for external links.
Benefit: Page layout can be easy configured with the preconfigured templates,
based on vertical a different page layouts can be configured.
For example vertical "All" shows results in Card-Style, 
meanwhile vertical "Wiki pages" are displaying  results in "Details List" format.
The link in the vertical opens a the other configured page, 
but shows the result amount of the different configured vertical.
  

**Describe the solution you'd like**
If for a external link, a SharePoint search query is configured, 
then render the link like currently, but additional with the result count.
If for the external link, has no search query, then don't render a result count for it.
When a link with query is clicked, then this link should be opened as familiar.

**Describe alternatives you've considered**

**Additional context**

**Comment by wobba** [comment]
Result counts these days are not very reliable and estimations.
