### ISSUE TITLE
Preview callout is disorientating/frustrating users

### ISSUE THREAD

**Issue by Georg-Trixl** [microsoft-search/pnp-modern-search#397]
**Is your feature request related to a problem? Please describe.**
As feedback from our users we got the information, that the click callout is blocking unexpiereced users from getting direct to the document of their seek.

The current preview callout opens on click.
But when a unexpiereced user wants to get to the document it self, 
the onclick callout is disorientating.

**Describe the solution you'd like**
Change based on webpart settings, the behavoir of the callout open event.
Alternative to the click, the callout should open on mouse hover event.

**Describe alternatives you've considered**
A preview alternative could also be, that the preview opens in a side panel - either on the hover or click event 

**Additional context**

**Comment by wobba** [comment]
On hover is not a good experience imo. You can disable the click behavior by using a custom template. See https://microsoft-search.github.io/pnp-modern-search/search-parts/templating/#elements-previews for details.

If someone does a PR for a toggle for the Simple layout, we'll accept it.

**Comment by wobba** [comment]
Closing as click on thumbnail opens preview and click on title opens item.
