### ISSUE TITLE
People search with multiple filters does not work

### ISSUE THREAD

**Issue by Cpoinsignon** [microsoft-search/pnp-modern-search#3970]
**Version used**
Ex: 4.8

**Describe the bug**
I wanted to exclude users having "adm" (technical account for admins) and "EXT" (guests users) in the people search result.
I have tried this filter: not(UserName:"adm" OR UserName:"EXT") but it gives no result
the filter not(UserName:"adm.") gives results
the filter not(UserName:"EXT") gives results
but combination of both does not work

I have also tried without the NOT
UserName:"adm" gives 13 results
UserName:"EXT" gives 15 results
UserName:"adm" OR UserName:"EXT"  gives no result (expected 28)

**To Reproduce**
Detailed steps to reproduce the behavior:
Combine two filters on the same property with OR

**Expected behavior**
Exclude ADM and EXT from people search results

**Screenshots**
![image](https://github.com/user-attachments/assets/ef51f47d-e51b-4503-a140-6cd054d3cbc9)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Additional context**
N/A

**Comment by Cpoinsignon** [comment]
If I put the filter in the query template, it works !

![image](https://github.com/user-attachments/assets/3e835d7e-9dcd-4abf-b1ca-9ae8b0f160ea)

**Comment by kasperbolarsen** [comment]
So the issue has been solved?
If you are looking into additional filters for UPA profiles I have a guide:
https://www.m365thinking.com/post/sharepoint-people-search-how-to-clean-up-your-results-by-excluding-accounts

**Comment by Cpoinsignon** [comment]
Yes, I have a workaround which works.
But why the same filter in the "advanced search filter" does not work?

**Comment by kasperbolarsen** [comment]
Oh, that is not a workaround.  The search query template is absolutely not the same as the search query text, as per the documentation at https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/

If you look at API calls in the dev tools it becomes really clear
