### ISSUE TITLE
Search Box Webpart: Keyboard not closing in mobile when hitting "return/enter" key

### ISSUE THREAD

**Issue by SaltySweats** [microsoft-search/pnp-modern-search#398]
**Version used**
Latest

**Describe the bug**
When using the pnp searchbox on mobile, they keyboard does not close after hitting "return". However, this still allows the search results webpart to search. 

**To Reproduce**
1. On a mobile device, enter some characters into the search box.
2. Click on "return".
3. The search results webpart updates, however the keyboard remains open.

**Expected behavior**
The expected behavior should be similar to the OOTB SharePoint search bar. When you click on the return key, it is the same thing as hitting "enter" on a desktop, so the search query initiates and the input field is unfocused.

**Potential Solution**
Add some logic to the onSearch method to unfocus the input field so the keyboard closes using element.blur().

**Comment by wobba** [comment]
Added blur on search.

**Comment by SaltySweats** [comment]
@wobba  Thank you!!
