### ISSUE TITLE
Results are not getting when searching with multiple words from SharePoint multiline text box

### ISSUE THREAD

**Issue by harigoudA** [microsoft-search/pnp-modern-search#3981]
I am using PNP modern search 4.11.0 version.

When i am searching for multiple words not getting results.

I am having multiline textbox "Objectives" This i made searchable by adding it to managed properties.
PNP search is working when i am searching for single word. Please find the below screen shot for the same.

![image](https://github.com/user-attachments/assets/ededa64e-1551-4b75-a8ec-08e762689c89)

But when i search for multiple keywords it is not working. Please find the below screen shot for the same.
![image](https://github.com/user-attachments/assets/b0edb8fe-362b-4639-8ca0-63f346c5c223)

The same when i am searching with search query tool i am getting exact result. 
![image](https://github.com/user-attachments/assets/acd653d8-e98d-4a71-84ba-f35515759e1f)

**Comment by kasperbolarsen** [comment]
I would suggest looking into the API traffic, as shown here: https://www.youtube.com/watch?v=kPMSiRxK8H8&pp=ygUMbTM2NXRoaW5raW5n

**Comment by harigoudA** [comment]
Hello @kasperbolarsen Thanks for your reply,

I have followed your instructions but i did not find any thing odd in the API traffic.
I can see "Status code: 200 Ok" and in response "Rows": []

**Comment by kasperbolarsen** [comment]
An idea: would it be possible to reduce the query to the very core, like IsDocument:1 KMObjectives:{searchTerms} to ensure that we are not tripped by something else.
I have tested a similar scenario in my end, and it works fine.

**Comment by harigoudA** [comment]
We can close this bug.
