### ISSUE TITLE
Make thumbnail images in Tiles clickable

### ISSUE THREAD

**Issue by eldoro80** [microsoft-search/pnp-modern-search#400]
The thumbnail images of the Tiles in the Tile-layout arent clickable. The mouse pointer changes to a hand when hovering the thumbnail image, but it's not clickable. Perhaps this is a bug instead of a feature request? The thumbnails in the default SharePoint tiles are clickable, so it would be consistent to also implement this in the Tile-layout.

![afbeelding](https://user-images.githubusercontent.com/48433541/88158434-55d64100-cc0c-11ea-8023-415f12d5fb7b.png)

Greetings and keep up the good work!

**Comment by wobba** [comment]
If you enable preview, then a click will open the preview.

![image](https://user-images.githubusercontent.com/51104/88168995-8d98b500-cc1b-11ea-8000-ba89b03e3337.png)

I guess we could/should turn off the click target if you don't have a preview.

**Comment by eldoro80** [comment]
@wobba I'dd like for the image thumbnail to link to the same URL as the Title (when preview is disabled). I think that's expected behaviour for most users. Offcourse a simple fix would be to disable the click target on the image when preview is disabled.  But I personaly would favour the first mentioned solution.

**Comment by wobba** [comment]
I decided to remove the click target instead if there is no preview. Clicking the link will open.

**Comment by eldoro80** [comment]
Alright, thanks!

**Comment by LetMeSP** [comment]
> I decided to remove the click target instead if there is no preview. Clicking the link will open.

Sorry if doing something wrong but my first post here. Is this issue back? I use Cards layout for videos and thumbnail is not clickable but mouse cursor is active. Is there a way to add a URL to that thumbnail.

**Comment by wobba** [comment]
@LetMeSP the latest version do not have a mouse over cursor or open preview for the tile/card layout. Try switch to another layout and back, or re-add the web part and you will see this.

**Comment by HamEv** [comment]
@eldoro80 do you find a solution for that? I have the same need - I want to click on the tiles preview image and open the document. Unfortunalty it's not possible and I cannot add html code within tile configurator.

**Comment by wobba** [comment]
There is no easy way to accomplish this with the fabric component we use.

**Comment by HamEv** [comment]
@wobba thanks for your response. Is there a possiblity to change the "Preview Image" within tiles to allow HTML Code? So, that I can just insert an <a> tag with <img>?

**Comment by FranckyC** [comment]
Hi @HamEv, no you can't add direct HTML in the tiles at this time.
