### ISSUE TITLE
PNP search webparts not available 4.13.1.0

### ISSUE THREAD

**Issue by tommykr2** [microsoft-search/pnp-modern-search#4009]
**Version used**
4.13.1.0

**Describe the bug**
I have used PNP Modern search on many tenants.
I upgraded one tenant from v 4.7.0.0 to 4.13.1.0 last week
It is NOT "deployed to all sites". It is added to individual site collections
The sites I've been testing with (either upgraded from 4.7 or new install of 4.13), I cannot see the PNP search web parts. When I go to add webpart to page and search PNP, there are zero results

**To Reproduce**
Add PNP 4.13.1.0 to site (not deployed to all sites)
add webpart to page
Search "PNP". Zero results

**Desktop (please complete the following information):**
 - Tested in both Chrome and Edge on Windows

**Comment by kasperbolarsen** [comment]
Sometimes it takes up to 24 hours for the package to be synced to the sites.
If it still isn't showing up I'll recommend reinstalling the package again

**Comment by tommykr2** [comment]
@kasperbolarsen about 2 weeks had passed and the web parts weren't showing up. Removing the package from the app catalog and re-adding it resolved the issue immediately. thank you for the suggestion!
