### ISSUE TITLE
Values of RefinableStrings not returned for satellite geos

### ISSUE THREAD

**Issue by buildbod** [microsoft-search/pnp-modern-search#4019]
**Version used**
4.12.2

**Describe the bug**
Classic SharePoint Search includes a switch to include 'Show Multi-Geo results'. Toggling that switch to _on_ results in values stored in RefinableStrings being returned with search results regardless of the geo location of the result.

![image](https://github.com/user-attachments/assets/5d9cc3da-1b4f-44f0-82a1-bfa232342569)

However repeating the search with PnP Search results in empty values for any user profile not in the main geo.

**Expected behaviour**
Results are returned as per classic i.e. regardless of the geo.

I understand that pnp-search v3 is geo aware e.g. https://github.com/microsoft-search/pnp-modern-search/issues/766

**Desktop (please complete the following information):**
 - Browser :: All

**SharePoint Search Query Tool
As an aside, using the SharePoint Search Query Tool with the EnableMultiGeoSearch set to true returns core properties but does not expose the Refiners. 

![image](https://github.com/user-attachments/assets/57f7755c-a6a8-46fb-a714-5ea2b1550764)

Given that Classic Search honours the Refinable Strings, it does not seem right to replicate the RefinableStrings across geos. At present they are not replicated e.g. 

Main geo

![image](https://github.com/user-attachments/assets/8ad1b749-b7aa-4be7-9b07-b7c7e0cdc3cf)

Satellite geo

![image](https://github.com/user-attachments/assets/bb5f0d40-6149-4fa4-b821-49506444a635)

It is seems that Microsoft have included some logic behind the Show Multi-Geo results feature that is not being picked up in the pnp-search.

**Comment by wobba** [comment]
Search schemas has to be manually replicated across GEO's. If a web part is on GEO1, then the property mapping has to occur here. For people search, querying one GEO should be sufficient to avoid duplicate results, but if the web part reside on multiple GEO's you need to replicate the setup when querying one geo only.

Afaik profiles are replicated across GEO's as well, so you don't want multi-geo search on profiles - which means all mappings should be set up on all GEO's to ensure parity.

Ideally we would support fanout to specific GEO's as you could target one GEO for profiles, and happy to accept a PR to support this (https://learn.microsoft.com/en-us/microsoft-365/enterprise/configure-search-for-multi-geo?view=o365-worldwide#sample-post-request-thats-fanned-out-to-some-geo-locations).

Looking at the classic UX it passes a bool property `CrossGeoQuery` which is undocumented and you can play around with it and see if you get some expected results. And seems to be false as the default value.

**Comment by buildbod** [comment]
Closing with a view to creating a PR as suggested

**Comment by buildbod** [comment]
https://github.com/microsoft-search/pnp-modern-search/discussions/4053
