### ISSUE TITLE
PDF documents return first

### ISSUE THREAD

**Issue by Holden15** [microsoft-search/pnp-modern-search#403]
**Version used**
3.14

**Describe the bug**
We are noticing that PDF's tend to be listed first when searching documents.

EDIT:

We were using 3.6, updated due to SharePoint's Dynamic Data issue to 3.14.  Started noticing this issue after that.

**To Reproduce**
Load up a document library with PDF documents.  They will be at the top of the list.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/43765678/88321710-3ced8e80-cce5-11ea-884d-3f8871d8a7e6.png)

![image](https://user-images.githubusercontent.com/43765678/88321833-6e665a00-cce5-11ea-9f7e-5fb216560f1c.png)

There are only 24 pdfs in the document library:

![image](https://user-images.githubusercontent.com/43765678/88322008-abcae780-cce5-11ea-89ce-f37af2925956.png)

Out of 498 documents;

![image](https://user-images.githubusercontent.com/43765678/88322086-cd2bd380-cce5-11ea-8d8e-e8a1e4f91845.png)

**Comment by wobba** [comment]
Check that you have no sort order (default is created date) or sort på Rank:descending. And how weight is treating pdf vs other formats is outside of the web part project.

I also see you have zero term queries, which would more or less only look at file type when ranking.
