### ISSUE TITLE
Change to tag display in templates "breaks" existing PnP Search Results Web Parts

### ISSUE THREAD

**Issue by sympmarc** [microsoft-search/pnp-modern-search#4039]
**Version used**
Ex: 4.13.1 (latest)

**Describe the bug**
The change in this release to better format tags causes a change in the way the settings need to be to display the tags well.

In the past, we had to add "Auto" before owstaxismetatdataalltagsinfo and then turn on localization for the tags to look right - not show the full object. If these settings are in place when we upgrade to 4.13.0, the tags are not displayed at all - just the tag image.

**To Reproduce**
Described above.

**Expected behavior**
Tags set up should work the same as before - existing Web Parts shouldn't have to be changed.  What worries me is as people start upgrading to 4.13.0, they will see their tags as "broken", rather than seeing the improved display.

**Additional context**
Talked to @kasperbolarsen about this on a call - he's aware of the issue and asked me to post.

The template changes were in [Simple List](https://github.com/microsoft-search/pnp-modern-search/blob/main/search-parts/src/layouts/results/simpleList/simple-list.html) and maybe one other template, as discussed in #3806.

**Comment by wobba** [comment]
@kasperbolarsen is this due to the template change?

**Comment by kasperbolarsen** [comment]
> @kasperbolarsen is this due to the template change?

Yes, I think so. 
I guess the recommended way to use these is to use the taxid version and the Auto along with localization?

**Comment by wobba** [comment]
Yes, auto is needed for localization. @kasperbolarsen are you able to do a PR on this or do you need assistance?

**Comment by kasperbolarsen** [comment]
I have a good candidate ready and will validate it again the reported scenario,  but will welcome a review

**Comment by sympmarc** [comment]
Any idea when this fix might be released? Would you like any help testing?

**Comment by wobba** [comment]
@sympmarc I can merge the down branch into a new release. So if you build the dev branch and test that should be sufficient.

**Comment by wobba** [comment]
Should be fixed in the latest release.
