### ISSUE TITLE
# in Query String not Working

### ISSUE THREAD

**Issue by gristy58** [microsoft-search/pnp-modern-search#405]
**Version used**
3.14

**To Reproduce**
1. Confirm Serach Box to point at Query String
2. Have content with #test as a string
3. search for #test in the query string i.e. ?q=#test

**Expected behavior**
#test to appear in the search box and results returned

The search box stays blank and does not function

**Screenshots**
https://imgur.com/HdDqwNt

**Comment by wobba** [comment]
You need to encode # as %23 in the URL as it has special meaning in a URL.

**Comment by gristy58** [comment]
That is not possible. This is executed by the SharePoint search box not by a direct link that has been setup.

**Comment by wobba** [comment]
I see your issue, and it's a bug with SPFx and redirect query, not the PnP web parts. Please log at https://github.com/SharePoint/sp-dev-docs and feel free to tag me and I can alert the right person internally.
