### ISSUE TITLE
Search result not refining on selecting a refiner on any page except 1st page of results

### ISSUE THREAD

**Issue by tariqanwar5897** [microsoft-search/pnp-modern-search#406]
Version used
Ex: 3.14.2

Describe the bug:
On 1st page when I click on a refiner, the results are returned filtered correctly, but when I navigate to 2nd or 3rd Page and then click on a refiner, the results are not refined.

2nd page without any refiner selected:
<img width="629" alt="2nd page without filter" src="https://user-images.githubusercontent.com/54318684/88895986-bda61080-d238-11ea-98ab-c31dd0924942.png">

2nd page with a refiner selected:
<img width="633" alt="2nd page after filter" src="https://user-images.githubusercontent.com/54318684/88895979-bc74e380-d238-11ea-84cd-2c9eff9d7e82.png">

**To Reproduce**
1. Search anything which has more than 2 page of results
2. Go To 2nd page or any other page except 1st.
3. Click on a refiner value from Search Refiner Web Part
4. Results are not filtered.

**Expected behavior**
Result should be filtered and page should come back to 1st page.

Desktop (please complete the following information):
 - chrome

**Additional context**
After the steps to reproduce has been done and I go back to 1st page, the results get filtered and new set of results shows.

**Comment by wobba** [comment]
There's a fix in which will reset to page 1 for next release. #361
