### ISSUE TITLE
Search Box Web Part: react-ace version conflicts

### ISSUE THREAD

**Issue by mirkori** [microsoft-search/pnp-modern-search#407]
**Version used**
Latest

**Describe the bug**
Modern search web part crashes on pages, where "react-ace" version >= 8 is loaded already on the page.

The problem source seems to be a change in the global window ace object:
window.ace.require vs window.ace.acequire

Suggested solution: Upgrade react-ace to version >= 8.0.0

**Comment by wobba** [comment]
What if solutions on the page then use an older version? Global objects are annoying indeed.

**Comment by wobba** [comment]
As we are using pnp spfx controls which use v5.8.0, we sort of have a dependency here.
