### ISSUE TITLE
Failed to load component error

### ISSUE THREAD

**Issue by Aparna1708** [microsoft-search/pnp-modern-search#408]
Hi Team,

We are facing the below issue,
Failed to load component "cc39324a-0913-4a5b-b77f-0b6ade7646f6" (SearchNavigationWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/<vanityURL of application>/sites/AppCatalog/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/xxx.search-searchnavigationwebpartstrings_en-us_7f54bb43aece7e486b3e72679e775f81.js' for resource 'SearchNavigationWebPartStrings' in component 'cc39324a-0913-4a5b-b77f-0b6ade7646f6' (SearchNavigationWebPart).

Search Webparts are displayed intermittently to certain users. Tried in all browsers.

**Comment by Aparna1708** [comment]
Search Webparts version 3.9

**Comment by wobba** [comment]
Hi,
This seems like a general SPFx issue, not related to the web parts in particular. I suggest you remove the app package and re-add and see if this solves the issue. The newer version of the web parts have replaced the navigation web part with a web component as well.

You could try to navigate to the folder `/sites/AppCatalog/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b` and see if you see the file being referenced or not.
