### ISSUE TITLE
Thumbnail of video from document library

### ISSUE THREAD

**Issue by Pepozzo** [microsoft-search/pnp-modern-search#410]
Hi!

I'm using June release of PnP Modern Search on my communication site.

I've a document library where I upload videos. In this document library I've created a Picture column called "Thumbnail" which is automatically populated from SharePoint when a video is uploaded. 

I've now added the Search Box and the Search Results webpart to my home page. I'm using "Tiles" as results template and I would like to show the thumbnail.

This is the result:
![image](https://user-images.githubusercontent.com/3300906/89027467-d8f14880-d32a-11ea-9a2f-f668415fbee1.png)

There is no "Play button" (which I've seen using an Asset Library as source) and also there is no thumbnail.

I've searched with "Debug" mode the result and I'm not getting images URL in the JSON object.

Is there a way to achieve that? Is that a bug or am I doing something wrong?

**Comment by wobba** [comment]
Added support for thumbnails for movies, but I'm not using the thumbnail column as I'm unsure how that column works with search. It should be in the next release which we're planning to preview this week.
