### ISSUE TITLE
Pnp Result Download button remains grayed out

### ISSUE THREAD

**Issue by CSARTAVIQ** [microsoft-search/pnp-modern-search#4116]
Hi
I've dowloaded the last version of PnP Search and I try to enable the new "Download" functionality on the search result.
I'm working for several customers and it is running without problem at several customers.
I'm facing an issue in 1 of my customer. I've enabled it (also the possibility to select multiple items), but when I select files in the Pnp Search Result, the Download button remains grayed out. So no possibility to use it.
What's wrong ?
Regards

**Comment by patrikhellgren** [comment]
The following selected properties needs to be available for it to be enabled SPWebUrl, ContentTypeId, NormListID and NormUniqueID so you are probably missing one of those.
Also required but less likely is that it is only enabled if the files/folders are within the same host as the page you are on, i.e. the host for SPWebUrl is the same host as the one in the browsers url, and that the content type id starts with 0x0101 (files) or 0x0120 (folders). And of course it is only enabled if there is one or more files or folders selected.

**Comment by CSARTAVIQ** [comment]
Hello
Indeed the SPWebURL was missing. It is solved.
Many thanks!

________________________________
De : Patrik Hellgren ***@***.***>
Envoyé : jeudi 21 novembre 2024 10:16
À : microsoft-search/pnp-modern-search ***@***.***>
Cc : SARTEEL Christophe ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft-search/pnp-modern-search] Pnp Result Download button remains grayed out (Issue #4116)


The following selected properties needs to be available for it to be enabled SPWebUrl, ContentTypeId, NormListID and NormUniqueID so you are probably missing one of those.
Also required but less likely is that it is only enabled if the files/folders are within the same host as the page you are on, i.e. the host for SPWebUrl is the same host as the one in the browsers url, and that the content type id starts with 0x0101 (files) or 0x0120 (folders). And of course it is only enabled if there is one or more files or folders selected.

**Comment by ackbarar** [comment]
Hi Not sure if I should comment on a closed issue but anyway I tried to look at previous download issues before writing this. Does the PnP support downloading document sets? Also strangely I am not able to download multiple files and folders at one go even though the documentation says so. Where might I be going wrong? I can select multiple files and folders as well as download single files.
