### ISSUE TITLE
Getting [HTTP]:500 error on all PNP - Search Results webparts

### ISSUE THREAD

**Issue by PicGadm** [microsoft-search/pnp-modern-search#4123]
### Check existing issues before logging new ones
If you are not using the latest version, triage your issue with the latest version before logging as we won't provide patches to older versions.

### Issues related to data mapping, web part setup etc, and SharePoint columns to crawled properties to managed properties should be asked in the discussion section.

**For any question regarding Web Parts usage, please use the ["Discussions"](https://github.com/microsoft-search/pnp-modern-search/discussions) tab instead of creating a new issue.**.

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

### Follow the template below or we will have to delete this request!!
We can assist a lot faster if you provide the following information:

**Version used**
Ex: 4.14.0.0

**Describe the bug**
All of our PNP - Search Results webparts are giving us "[HTTP]:500 - [CorrelationId]: ... [Version]:16.0.0.25430" errors out of the blue.
I installed the latest version 4.14.0.0 (we had 4.10.x.x) and with that version the issue remains.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to a SharePoint Page
2. Edit the page and add a PNP - Search Results webpart
3. Create any search query
4. Save changes
5. See error

**Expected behavior**
Not getting the error and see the files or items based on the search query.

**Screenshots**
![image](https://github.com/user-attachments/assets/adee26bd-dc0c-4866-9a8e-5a4012ecd4cd)

**Desktop (please complete the following information):**
 - Browser: Microsoft Edge for Business Version 131.0.2903.51 (Official build) (64-bit)

**Additional context**

**Comment by CSARTAVIQ** [comment]
Same issue in multiple tenants. We also have issues with normal search (without using PnP), so we suspect this is a general issue at Microsoft, and not related to PnP Search. But this should be confirmed.

**Comment by KaveSys** [comment]
Hello, same here. Filters not fully load and error [HTTP]:500.
MS is already working on it, hoping they fix asap:
![image](https://github.com/user-attachments/assets/f591b77d-b1e4-4fc4-b789-2702112d4fd7)

**Comment by kasperbolarsen** [comment]
It is a general Search outage
![image](https://github.com/user-attachments/assets/a9ccb296-7e0a-4db8-8fd2-d399c5e0c39c)

**Comment by santoshk10** [comment]
Hi Getting same issue

![image](https://github.com/user-attachments/assets/700a7c5c-4ba6-4289-a128-f23a1a500581)

**Comment by wobba** [comment]
API error on Microsoft, not web part related.
