### ISSUE TITLE
Modern PNP Search Results shows HTTP500 error

### ISSUE THREAD

**Issue by ValiPrk** [microsoft-search/pnp-modern-search#4124]
Hello,

We have since this morning the following error on all our Modern PNP Search results webparts (see attached screenshot).
The error is general and is shown even on the webparts that have only the actual site as an query, could it be the same root cause as the one presented by Microsoft for the PowerPlatform? (see attached screenshot)

Thank you for your reply!

Valentin
![PNP Search results Error](https://github.com/user-attachments/assets/e4f42d3a-efba-4738-b59d-9051ddb5e725)
![PowerPlatform issues](https://github.com/user-attachments/assets/b48fd437-64c9-4bbb-8faa-777c203890ef)

**Comment by CSARTAVIQ** [comment]
Seems general issue at Microsoft
See SP941302 in Microsoft Service Health : Some users may be unable to search in SharePoint Online..

**Comment by wobba** [comment]
API error on Microsoft, not web part related.
