### ISSUE TITLE
no results for two users

### ISSUE THREAD

**Issue by leon-hinkel-mtexx** [microsoft-search/pnp-modern-search#4129]
**Version used**
Ex: 4.14

**Describe the bug**
We have two users that have the same permissions as most other users, but they always get 0 results in the search.
The search works for any other user. 
These two users have the permissions to view the documents or sites that should be listed there and it is possible to search for those in the normal SharePoint search at the top.
Additionally we have a page with a search filter and this search filtern is not visible for the effected users.

**To Reproduce**
1. Go to a site with the PnP Search as one of the users
2. type anything into the search (or leave on default which is "*")
3. See how there are 0 results

**Expected behavior**
Search results of e.g. our templates

**Screenshots**
![image](https://github.com/user-attachments/assets/4b1403f0-9910-4c9d-903a-f4ad92bcfff5)
![image](https://github.com/user-attachments/assets/e5da494f-827a-44df-b6bc-34f259b22ba6)
![image](https://github.com/user-attachments/assets/3d51b3d0-4d73-486a-9d1f-bb67f1b75558)
![image](https://github.com/user-attachments/assets/8685e9ee-62af-4b70-94bf-d932f4805563)

**Desktop:**
 - Browser tried with Edge, Chrome, Firefox + cleared cache and tried in incognito 
 
**Additional context**
we used the SP Editor extension, while logged in as the effected user, to search for the path that we have configured in the PnP - Search Results query template and there we get all the results

**Comment by mobun** [comment]
Hi, 
I recently had a similar phenomenon.
This could be solved by setting the language of the search query (in our case English).

![image](https://github.com/user-attachments/assets/013d1394-d151-45c6-837e-870509fb7610)

**Comment by leon-hinkel-mtexx** [comment]
> Hi, I recently had a similar phenomenon. This could be solved by setting the language of the search query (in our case English).
> 
> ![image](https://private-user-images.githubusercontent.com/37617982/391908399-013d1394-d151-45c6-837e-870509fb7610.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzEwMzQsIm5iZiI6MTczMzIzMDczNCwicGF0aCI6Ii8zNzYxNzk4Mi8zOTE5MDgzOTktMDEzZDEzOTQtZDE1MS00NWM2LTgzN2UtODcwNTA5ZmI3NjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEyNTg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMDliZmIxNzA4NTllNzFiY2FjNzliMmI2NDk1YzZlNTU4ZGQ2NTZjYTJkZmUwYzk0N2YyMGNhYjU2NWRiYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gCrHY0nJ0DKe7BES_xTCN6k_tQJYTLYpcbAyEcjQsEU)

unfortunately this did not solve the problem for us.

**Comment by mobun** [comment]
Perhaps you can also check whether the corresponding request (postquery) from the web part returns responses from the search, then you can definitely narrow down the error further (or use the debug display template to receive more informations).

**Comment by kasperbolarsen** [comment]
Just for slow ones, like me: did you had a leading white space?

**Comment by leon-hinkel-mtexx** [comment]
> Just for slow ones, like me: did you had a leading white space?

My bad, I didn't see that the two * (the asterisks) made the text style italic instead of showing them.
We had an asterisk both before and after {searchTerms} in our query tempalte, removing them solved the issue.
