### ISSUE TITLE
"Path: " doesn't work in query template in search results webpart

### ISSUE THREAD

**Issue by shrirampophali** [microsoft-search/pnp-modern-search#413]
**Version used**
3.14.1

**Describe the bug**
**Path:"abcd.aspx"** doesn't work in query template in search results webpart. It works in classic search webparts. 

**To Reproduce**
1. Go to any modern communication site
2. Create 3 site pages (like abcd.aspx, xyz.aspx, pqr.aspx) using blank template
3. Go to abcd.aspx page
4. Edit page and add modern search result webpart
5. Use Query in Query Template as **Path:"abcd.aspx"** (or also tried with full url and w/o quotes)
6. No result returned

**Expected behavior**
- Result should be returned with  abcd.aspx page

**Screenshots**

**Desktop (please complete the following information):** Windows 10
 - Browser: Chrome

**Additional context**
- Results are returned with other Custom Managed Properties without any problem

**Comment by wobba** [comment]
`Path` property requires a full pre-fix URL like `path:"https://tenant.sharepoint.com/sites/mysite/Shared Documents/abcd.aspx"` If you want just a filename use `Filename:abcd.aspx`
