### ISSUE TITLE
Sharepoint Query Suggestions do not work

### ISSUE THREAD

**Issue by bdani1** [microsoft-search/pnp-modern-search#4136]
**Version used**
4.14.0.0

**Describe the bug**
Query suggestions are missing from PnP Search Box. I activated the default SP provider, nothing custom. The input file has been uploaded to the Search Admin site, and the suggestions are showing up properly in the top search bar

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Upload a query suggestion input file
2. wait 24 hours
3. Test it on a standard search box (scoped to tenant wide search) 
4. If it is working, test it with a PnP search box, enable query suggestions in the webpart setttings
5. See error

**Expected behavior**
I expect the same query suggestions that I get back from the top search bar

**Screenshots**
The search bar on top offers me the defined query suggestions:
![image](https://github.com/user-attachments/assets/21ca3e48-1c69-4763-8436-6f69d3983d1a)
The PnP search box does not offer anything
![image](https://github.com/user-attachments/assets/26722647-a2fb-4ed0-9317-dcb185e822f9)

**Desktop (please complete the following information):**
Latest Chrome Version 131.0.6778.109 (Official Build) (64-bit)

**Comment by wobba** [comment]
We rely on whatever the API return. Can you verify the provider is enabled? As static suggestions work fine for my testing and I see requests and data coming from the `/_api/search/suggest`api.

<img width="438" alt="image" src="https://github.com/user-attachments/assets/5ec42955-1c28-4659-8581-59754e218856" />

**Comment by bdani1** [comment]
Hi wobba, 
Unbeliavable, now it's working fine. The provider was enabled yes. Anyway, thanks for checking!
