### ISSUE TITLE
Expose Teams context from SPFx

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#414]
Ensure search web part can work inside a teams tab and expose teams context as needed.

**Comment by Georg-Trixl** [comment]
yep, i like to have that as well 👍

**Comment by paalolav** [comment]
Having issues with files from Document Libraries in Teams.
When displaying search results on a Sharepoint page in a tab in Teams:
Pages open like expected, but files like PDF, Docx, etc opens the Document Library instead of the file.
Is this a bug or is it something I've done wrong?

**Comment by wobba** [comment]
I'll most likely change the logic on how the open links look for the next version.

**Comment by paalolav** [comment]
> I'll most likely change the logic on how the open links look for the next version.

Thanks for the reply and for the AWESOME job you're doing!
I solved it for now by adding ?web=1 to the search result URLs. Works like a charm for now.

**Comment by wobba** [comment]
@paalolav Made the change now - thanks for reminding me.

https://github.com/microsoft-search/pnp-modern-search/blob/22bcdf053a4c3690e110ce710527da7fc4a336e9/search-parts/src/services/TemplateService/BaseTemplateService.tsx#L187-L189

**Comment by sagar2610** [comment]
Hi Team, I downloaded the code and made some changes. It's great that you added "?web=1". I had an unique requirement where the users did not have access to application pages. Most of the files with "?web=1" are redirected to a custom file handler developed by Microsoft. So, when a user with no access to application pages tries to open the file, user gets access denied. To solve this issue I added a new setting in web part settings tab. Now users can choose to turn on or off the default behaviour. If defaultBehaviour is turned "On", links are displayed with "?web=1", if it is not enabled then direct links are displayed, which enables you to directly download the file. The user is not redirected to custom file handler and the file is not opened in the browser but gets downloaded.
![Capture](https://user-images.githubusercontent.com/4516471/92592139-6bc4c180-f29f-11ea-8b19-6155c1ebdd89.PNG)
![url](https://user-images.githubusercontent.com/4516471/92592369-c1996980-f29f-11ea-8284-e86976d87173.png)

**Comment by wobba** [comment]
Curious as to the scenario where a user can access a file, but not view it in the ODSP previewer? And did not think about this.

I would rather add an option to the `getUrl` helper, so people could override and change this in a custom template instead.

**Comment by sagar2610** [comment]
@wobba I made this change because Details list does not give you the option to change the template underneath (<pnp-details-list></pnp-details-list>). For other templates, I directly used the Path column instead in custom template. We are sharing our SharePoint site with external users and SharePoint shows a **share** button on top and all the external users can see other external users by clicking on **Shared With** tab. We do not want external users to see each other so, we had to restrict access to application pages (not a good way but need to wait for Microsoft).

**Comment by wobba** [comment]
@sagar2610 You can pick Details List, then click the {} to customize and it will copy that template over as a basis. Which is why I'd rather extend the helper.

**Comment by sagar2610** [comment]
<content id="template">

    <style>
        /* Insert your CSS overrides here */
    </style>

    <div class="template_root">
        {{#if @root.hasPrimaryOrSecondaryResults}}   
            {{#if showResultsCount}}
                <div class="template_resultCount">
                    <label class="ms-fontWeight-semibold">{{getCountMessage @root.paging.totalItemsCount keywords}}</label>
                </div>
            {{/if}}
            <pnp-details-list data-items="{{JSONstringify items}}" data-columns-configuration="{{JSONstringify detailsListColumns}}" data-show-file-icon="{{@root.showFileIcon}}" data-is-compact="{{@root.isCompact}}"></pnp-details-list>
            {{#if @root.paging.showPaging}}
                <pnp-pagination 
                    data-total-items="{{@root.paging.totalItemsCount}}" 
                    data-hide-first-last-pages="{{@root.paging.hideFirstLastPages}}"
                    data-hide-disabled="{{@root.paging.hideDisabled}}"
                    data-hide-navigation="{{@root.paging.hideNavigation}}"
                    data-range="{{@root.paging.pagingRange}}" 
                    data-items-count-per-page="{{@root.paging.itemsCountPerPage}}" 
                    data-current-page-number="{{@root.paging.currentPageNumber}}"
                >
                </pnp-pagination>
            {{/if}}
        {{else}}
            {{#unless showBlank}}
                <div class="template_noResults">{{@root.strings.NoResultMessage}}</div>
            {{/unless }}
        {{/if}}
    </div>
</content>

<content id="placeholder">
    <style>
        /* Insert your CSS overrides here */
    </style>

    <div class="placeholder_root">
        {{#if showResultsCount}}
            <div class="template_resultCount">
                <span class="shimmer line" style="width: 20%"></span>
            </div>
        {{/if}}
        <pnp-details-list data-columns-configuration="{{JSONstringify @root.detailsListColumns}}" data-show-file-icon="{{@root.showFileIcon}}" data-is-compact="{{@root.isCompact}}" data-show-shimmers="true"></pnp-details-list>
    </div>

</content>


It does not give me an option to modify the underlying URL behaviour.

**Comment by wobba** [comment]
Right, cause it's inside the details component which calls:

` let url = Handlebars.helpers.getUrl(item);`

I would then extend the component to have this as a setting and pass it down to `getUrl` and have that support it.

**Comment by sagar2610** [comment]
Exactly, just to get around it, I added some extra code. But you are right, extending the templates is the best idea. I am not good with handlebars so I took the hard way. Thanks a lot for your help.

**Comment by wobba** [comment]
Could you log a separate issue on this as an improvement? I might take a stab at it as it should be fairly easy to get in.

**Comment by sagar2610** [comment]
Here you go @wobba https://github.com/microsoft-search/pnp-modern-search/issues/464#issue-697155888

**Comment by wobba** [comment]
Teams support and context added
