### ISSUE TITLE
Sorting of refiners regarding german "Umlaute"

### ISSUE THREAD

**Issue by MonsieurMoemm** [microsoft-search/pnp-modern-search#415]
Hi, I have a **refiner webpart** with one refiner being a RefinableString mapped to **Managed Metadata column**. There are Terms starting with an **German Umlaut** (**ÄÖÜ** - https://en.wikipedia.org/wiki/Germanic_umlaut#German_orthography). Even so I choose **"Alphabetical Ascending" sort order** the Terms with an Umlaut are listed at the **end**. 

See also below Screenshot. 
**"Öffentlichkeitsarbeit" should be right below "Notfall".**

![image](https://user-images.githubusercontent.com/54102027/89537359-8667ce80-d7f9-11ea-963c-89c47a6bb833.png)
![image](https://user-images.githubusercontent.com/54102027/89537503-b9aa5d80-d7f9-11ea-9fda-17f9055a9090.png)

**On a classic search page the Terms are sorted the right way:**

![image](https://user-images.githubusercontent.com/54102027/89537688-f7a78180-d7f9-11ea-9b0a-32bd91a19ec7.png)

Can that be fixed or can I help fixing that?

**Comment by wobba** [comment]
Fixed with #420

**Comment by MonsieurMoemm** [comment]
Awesome! Thank you very much!
