### ISSUE TITLE
Search does not function properly with documents that have "_" in title

### ISSUE THREAD

**Issue by ValiPrk** [microsoft-search/pnp-modern-search#4151]
Hello,

We have been using the modern PNP webparts for our search and found some bugs as follows:
- if we search for a full title of a document, ex. "abc_def" it will be found
- if we remove "def" and just search for "abc_" nothing is found, no items at all.

I tried to make some enquires about this issue, but I'm not 100% sure that "_" is in the special characters list.
Is there a way to overcome this situation?

Thank you for your reply
Valentin

**Comment by kasperbolarsen** [comment]
Hi, both SharePoint and Microsoft Search are using the Keyword Query Language,  and that behavior is expected,  please see https://learn.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference

If you are searching for "starts with" you should - [ ] append a *  ( and "ends with" is not supported)

**Comment by ValiPrk** [comment]
Thank you for your answer, it helped me to figure out what I needed.
Wish you happy holidays and Merry Christmas!
