### ISSUE TITLE
Query Rules - Result Blocks - Not Rendering in the Results

### ISSUE THREAD

**Issue by pjurski87** [microsoft-search/pnp-modern-search#417]
**Version used**
3.14.2

**Describe the bug**
The issue occurs when using query rule result blocks. The result block that is created with a simple {searchTerm} from documents source does not display in the search results web part. Only the "Promoted Results" from the query rule shows up. 

**To Reproduce**
* Create a query rule 
* Query Condition: Query Matches Keyword Exactly
* Phrase: test
* Promoted Results Enabled
* Choose result block 
* Query: {?{subjectTerms}}
* Search This Source: "Documents (System)"
* Settings:
* Select "This block is always shown above core results"
* Group Display: "Default Group"
* Item Display Template: "Use Result Types"
* Save

**Expected behavior**
The results from the query rule shows up on the search results web part on the top of the result list. 

**Screenshots**
<img width="500" alt="Screen Shot 2020-08-06 at 5 41 19 PM" src="https://user-images.githubusercontent.com/12953462/89586091-08adbe00-d80d-11ea-9b8d-dba1261d51a1.png">
<img width="500" alt="Screen Shot 2020-08-06 at 5 53 07 PM" src="https://user-images.githubusercontent.com/12953462/89586461-bde07600-d80d-11ea-8d2c-e4dfac6302cf.png">

**Desktop (please complete the following information):**
 - Chrome

**Additional context**

**Comment by wobba** [comment]
Added documentation which will be public with the next release. See https://github.com/microsoft-search/pnp-modern-search/commit/771d824e2fb98d35decc8ec00dab3b0bf11d9b6a

**Comment by pjurski87** [comment]
Thank you! This has helped and now my block results are showing.

**Comment by wobba** [comment]
Sorry for not documenting it before and happy searching 🙂👍
