### ISSUE TITLE
CSS not working

### ISSUE THREAD

**Issue by rohit18121812** [microsoft-search/pnp-modern-search#418]
!! Check existing issues before logging new ones !!

**Version used**
3.14.1.0

**Describe the bug**
We have used the search results to show all approved events with customized css . After the update, Css is not reflecting properly as well as events are not clickable. here is the CSS (see screenshot below of how it looks)

```
<content id="template">
    <style>
        a {
            text-decoration: none;
            color: black;
        }

        .eventCardInfo {
            width: 100%;
            height: 11em;
        }

        .removeTruncate {
            white-space: normal;
            overflow: auto;
        }
    </style>

    <div class="template_root">
        <div class="template_defaultCard">
            <div class="ms-Grid">
                <div class="ms-Grid-row">
                    {{#each items as |item|}}
                    <div class="ms-Grid-col ms-sm12 ms-md6 ms-lg4">
                        {{#> resultTypes}}
                        <div class="singleCard">
                            <li class="ms-ListItem ms-ListItem--image" tabindex="0">
                                <span id="eventSpan" class="ms-ListItem-primaryText eventCardInfo">
                                    <a class="ms-fontColor-themePrimary removeTruncate" href="{{getUrl item}}">
                                        {{Title}}
                                    </a>
                                    <br /><br />
                                    <span class="ms-ListItem-secondaryText removeTruncate">
                                                {{getDate EventsRollUpStartDate "LLL" 0}} To
                                    </span>
                                    <span class="ms-ListItem-secondaryText removeTruncate">
                                                {{getDate EventsRollUpEndDate "LLL" 0}}
                                    </span> 

                                    <span class="ms-ListItem-tertiaryText removeTruncate">
                                        {{Location}}
                                    </span>
                                    <br />
                                    <a class="ms-fontColor-themePrimary ms-ListItem-secondaryText"
                                        href="https://Siteurl/_vti_bin/owssvr.dll?CS=109&Cmd=Display&List={{ListID}}&CacheControl=1&ID={{ListItemId}}&Using=event.ics">
                                        Add to Calendar
                                    </a>
                                </span>
                            </li>
                        </div>
                        {{/resultTypes}}
                    </div>
                    {{/each}}
                </div>
            </div>
        </div>
    </div>
</content>

<content id="placeholder">
    <style>
        .shimmerPrimaryText {
            width: 100%;
            position: relative;
            padding: 0;
            margin-top: 10px;
            height: 10px;
        }

        .shimmerSecondaryText {
            padding: 0;
            width: 75%;
            height: 10px;
        }

        .shimmerTertiaryText {
            padding: 0;
            width: 20%;
            height: 10px;
        }
    </style>

    <div class="placeholder_root">
        <div class="template_defaultCard">
            {{#if showResultsCount}}
            <div class="template_resultCount">
                <span class="shimmer line" style="width: 20%"></span>
            </div>
            {{/if}}
            <div class="ms-Grid">
                <div class="ms-Grid-row">
                    {{#times maxResultsCount}}
                    <div class="ms-Grid-col ms-sm12 ms-md6 ms-lg4">
                        <div class="singleCard">
                            <div class="previewImg document-preview-item">
                                <div class="cardFileIcon shimmer"></div>
                            </div>
                            <li class="ms-ListItem ms-ListItem--document" tabindex="0">
                                <div class="cardInfo">
                                    <span class="shimmerPrimaryText shimmer line"></span>
                                    <span class="shimmerSecondaryText shimmer line"></span>
                                    <span class="shimmerTertiaryText shimmer line"></span>
                                </div>
                            </li>
                        </div>
                    </div>
                    {{/times}}
                </div>
            </div>
        </div>
    </div>
    </div>

</content>
```
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/67439350/89593652-8c16e180-d804-11ea-8ec7-70f4dd5b287b.png)

**Desktop (please complete the following information):**
 - Browser : Chrome, EDGE

**Additional context**

**Comment by wobba** [comment]
Can you share some more info? I see the same as you, which is correct according to your CSS. Using F12 and inspecting I can see the classes are applied.

I assume you are referring to the `ms-List` styles, and you are correct they are not included by default. You can get the FabricJS CSS from https://developer.microsoft.com/en-us/fabric-js/getstarted/getstarted and include it yourself if needed.

**Comment by wobba** [comment]
@rohit18121812 does this solve your issue?

**Comment by rohit18121812** [comment]
Sorry for late reply, i tired adding the fabric css refrences as follows but it didnt works , see below : 
I am trying to have a page theme shaded event box , which when click goes to event details.  Also adding "Add to Outlook", so when it click the .ics files gets event details .
-----
<link
  rel="stylesheet"
  href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css"
/>
<content id="template" class="ms-Fabric" dir="ltr">
        <style>
        @import 'office-ui-fabric-core/dist/sass/References';
            a {
                text-decoration: underline;
                color: blue;
                 background:white           
            }
    
            .eventCardInfo {
                width: 100%;
                height: 11em;
                 position: relative;
                 bottom:0;
                 background: linear-gradient(rgba(125, 185, 232, 0) 55%, rgba(0, 0, 0, 0.1) 60%, rgba(0, 0, 0, 0.2) 65%, rgba(0, 0, 0, 0.4) 75%, rgba(0, 0, 0, 0.6) 80%, rgba(0, 0, 0, 0.75) 85%, rgba(0, 0, 0, 0.8) 90%);           
       
            }
                   
           .eventCardInfo.ms-ListItem-primaryText.title{
            white-space: normal;
        }
            .removeTruncate {
                white-space: normal;
                overflow: auto;
            }
        </style>
     
        <div class="template_root">
         
            <div class="template_defaultCard">
                <div class="ms-Fabric">
                    <div class="ms-Grid-row">
                        {{#each items as |item|}}
                        <div class="ms-Grid-col ms-sm12 ms-md6 ms-lg4">
                            {{#> resultTypes}}
                            <div class="singleCard">
                                <li class="ms-ListItem ms-ListItem--image" tabindex="0">
                                    <span id="eventSpan" class="ms-ListItem-primaryText eventCardInfo">
                                        <a class="ms-fontColor-themePrimary removeTruncate" href="https://pgn4.sharepoint.com/sites/TestMyPge/SitePages/Event-Details.aspx?EventId={{ListItemID}}">
                                            {{Title}}
                                        </a>
                                        <br /><br />
                                        <span class="ms-ListItem-secondaryText removeTruncate">
                                                {{getDate EventsRollUpStartDate "LLL" 1}} To
                                            </span>
                                            <span class="ms-ListItem-secondaryText removeTruncate">
                                                {{getDate EventsRollUpEndDate "LLL" 1}}
                                            </span> 
                                        <span class="ms-ListItem-tertiaryText removeTruncate">
                                            {{Location}}
                                        </span>
                                        <br />
                                        <a class="ms-fontColor-themePrimary ms-ListItem-secondaryText"
                                            href="https://{Site url}/_vti_bin/owssvr.dll?CS=109&Cmd=Display&List={{ListID}}&CacheControl=1&ID={{ListItemId}}&Using=event.ics">
                                            Add to Calendar
                                        </a>
                                    </span>
                                </li>
                            </div>
                            {{/resultTypes}}
                        </div>
                        {{/each}}
                    </div>
                </div>
            </div>
        </div>
    </content>
    
    <content id="placeholder">
        <style>
            .shimmerPrimaryText {
                width: 100%;
                position: relative;
                padding: 0;
                margin-top: 10px;
                height: 10px;
            }
    
            .shimmerSecondaryText {
                padding: 0;
                width: 75%;
                height: 10px;
            }
    
            .shimmerTertiaryText {
                padding: 0;
                width: 20%;
                height: 10px;
            }
       
        </style>
    
        <div class="placeholder_root">
            <div class="template_defaultCard">
                {{#if showResultsCount}}
                <div class="template_resultCount">
                    <span class="shimmer line" style="width: 20%"></span>
                </div>
                {{/if}}
                <div class="ms-Grid">
                    <div class="ms-Grid-row">
                        {{#times maxResultsCount}}
                        <div class="ms-Grid-col ms-sm12 ms-md6 ms-lg4">
                            <div class="singleCard">
                                <div class="previewImg document-preview-item">
                                    <div class="cardFileIcon shimmer"></div>
                                </div>
                                <li class="ms-ListItem ms-ListItem--document" tabindex="0">
                                    <div class="cardInfo">
                                        <span class="shimmerPrimaryText shimmer line"></span>
                                        <span class="shimmerSecondaryText shimmer line"></span>
                                        <span class="shimmerTertiaryText shimmer line"></span>
                                    </div>
                                </li>
                            </div>
                        </div>
                        {{/times}}
                    </div>
                </div>
            </div>
        </div>
        </div>
    
    </content>

**Comment by wobba** [comment]
You cannot use import like this. See https://www.w3schools.com/cssref/pr_import_rule.asp. Either import from a URL which has the CSS, or copy/paste what you need from the fabric CSS into your template. Your import line is a sass import, not css import.
