### ISSUE TITLE
Search Results webpart not working with longer query filters

### ISSUE THREAD

**Issue by arunakshi** [microsoft-search/pnp-modern-search#419]
**Version used**
3.10.

**Describe the bug**
We have a search query which filters the news based on current user's profile properties. Our query is bit longer with length of 1,409 characters, but this is within the limit only. 

Since yesterday, we are getting an error for modern search webpart on our DEV tenant with the following error:
_Error making HttpClient request in queryable [500] ::> {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}_

If I look into consol.log, I see following response error from the results webpart.js for postquery request: 
_Message: Error making HttpClient request in queryable [500]  ::> {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}} Data: {"response":{},"status":500,"statusText":"","isHttpRequestError":true}_

**To Reproduce**
1. Create a query which filters based on current user's profile properties such as department, region, country and additional country, site name and also different news category topics.  
2. If the all the news category topics (we have 20 topics selected), then the webpart starts failing with above given error.

**Expected behavior**
The same webpart with the query is working fine on PROD and other tenants.  We also expect that the webpart works in DEV tenant also like before. It started appearing since yesterday only.

**Comment by wobba** [comment]
This is an API issue and should be reported via support or at https://github.com/SharePoint/sp-dev-docs. It's not related to the PnP web parts themselves. When reporting you should give a sample query which fails.
