### ISSUE TITLE
Search Results Result Types not working as expected

### ISSUE THREAD

**Issue by rgraley** [microsoft-search/pnp-modern-search#425]
**Version used**
Ex: 3.12.1.0

**Describe the bug**
I am trying to utilize the "Edit Result Types" feature.  I have created the template below and placed it in an assets library accessible by the web part.  The Result Type is setup as 
Managed Property bcContentCategory
Operator: Contains
Condition Value: Pay For Skills
External Template Url: https//xxx.sharepoint.com/sites/assets/mytemplate.htm
![image](https://user-images.githubusercontent.com/69590808/90028646-f22db980-dc87-11ea-8c4a-6bd817457e44.png)

NOTE: bcContentCategory is a taxonomy field with a display value of Pay For Skills or a GUID of 9d3e0b38-dc08-4d45-a76f-0b6f4627d12e

There are three different Results possible in the Results web part.  the other two show display the OOTB Simple List template as expected; however when the Result Type "Pay For Skills" is found the only thing displayed is the Shimmer Placeholder.
![image](https://user-images.githubusercontent.com/69590808/90028502-bdb9fd80-dc87-11ea-97ed-9471a9b17718.png)

If I put the code in the Edit Template window or reference the file in Custom Use an external template URL it all works find; however it applies the template to all the results which is not desired.
![image](https://user-images.githubusercontent.com/69590808/90029161-86981c00-dc88-11ea-9352-4d356fcf7937.png)

Just started using these web parts so trying to understand what am I missing? 

<PRE><content id="template">
    <style>
        .root-494{
            font-size: 20pt;
            height:100px;
            display: inline-block;
            -webkit-font-smoothing: antialiased;
            font-style: normal;
            font-weight: normal;
            speak: none;
            font-family: FabricMDL2Icons-15;
            width:35px;
            content:"\F7DB"; 
            color: {{@root.themeVariant.palette.themePrimary}};
        }
        .example-themePrimary a {
            color: {{@root.themeVariant.palette.themePrimary}};
            text-decoration: none;
        }
        .example-themethemeLight {
            font-size: 10px;
            text-transform: capitalize !important;
            color: {{@root.themeVariant.palette.themeTertiary}};
        }
    </style>
    <div class="template_root">
        {{#if @root.hasPrimaryOrSecondaryResults}} 
            {{#if showResultsCount}}
                <div class="template_resultCount">
                    <label class="ms-fontWeight-semibold">{{getCountMessage @root.paging.totalItemsCount keywords}}</label>
                </div>
            {{/if}}
            {{#if promotedResults}}
                <ul class="template_defaultList template_promotedResults">
                <li class="ms-fontWeight-semibold title">{{strings.PromotedResultsLabel}}</li>
                {{#each promotedResults as |promotedResult|}}
                    <li>
                        <div>
                            <i class="ms-Icon ms-Icon--MiniLink" aria-hidden="true"></i>
                        </div>
                        <div>
                            <a class="ms-font-l" href="{{Url}}">{{Title}}</a>
                            <div class="ms-font-s">{{Description}}</div>
                        </div>
                    </li>
                {{/each}}
            </ul>
            {{/if}}
            <ul class="template_defaultList">
                {{#each items as |item|}}
                    <li class="template_listItem" tabindex="0">
                        {{#> resultTypes}}
                            <div class="template_result">
                                <i data-icon-name="D365TalentLearn" role="presentation" aria-hidden="true" class="root-494"></i>
                                <div class="template_contentContainer">
                                    
                                    <span class="template_title example-themePrimary"><a data-interception="off" href="{{getUrl item}}" target="_blank">{{Title}}</a></span>
                                    <span>
                                        {{getSummary HitHighlightedSummary}}
                                    </span>
                                    <span class="example-themeLighter" style="padding-top:10px;">last modified: {{getDate LastModifiedTime "LL"}}</span> 
                                    <div class="template_tags example-themePrimary">
                                        {{#if owstaxidmetadataalltagsinfo}}
                                            <i class="ms-Icon ms-Icon--Tag" aria-hidden="true"></i>
                                            {{#each (split owstaxidmetadataalltagsinfo ",") as |tag| }}                                                    
                                                <span class="example-themethemeLight" style="padding-right:7px;">{{tag}}</span>
                                            {{/each}}
                                        {{/if}}
                                    </div>
                                </div>
                            </div>
                        {{/resultTypes}}
                    </li>
                {{/each}}
            </ul>
            {{#if @root.paging.showPaging}}
                <pnp-pagination 
                    data-total-items="{{@root.paging.totalItemsCount}}" 
                    data-hide-first-last-pages="{{@root.paging.hideFirstLastPages}}"
                    data-hide-disabled="{{@root.paging.hideDisabled}}"
                    data-hide-navigation="{{@root.paging.hideNavigation}}"
                    data-range="{{@root.paging.pagingRange}}" 
                    data-items-count-per-page="{{@root.paging.itemsCountPerPage}}" 
                    data-current-page-number="{{@root.paging.currentPageNumber}}"
                >
                </pnp-pagination>
            {{/if}}
        {{else}}
            {{#unless showBlank}}
                <div class="template_noResults">{{@root.strings.NoResultMessage}}</div>
            {{/unless }}
        {{/if}}
    </div>
</content>

<content id="placeholder">
    <style>
        /* Insert your CSS overrides here */
    </style>

    <div class="placeholder_root">
        {{#if showResultsCount}}
        <div class="template_resultCount">
            <span class="shimmer line" style="width: 20%"></span>
        </div>
        {{/if}}
        <ul class="template_defaultList">
            {{#times @root.paging.totalItemsCount}}   
            <li class="template_listItem" tabindex="0">
                <div class="template_result">
                        <div class="template_icon shimmer"></div>
                        <div class="template_contentContainer">
                            <span class="shimmer line" style="width: 60%"></span>
                            <span class="shimmer line" style="width: 100%"></span>
                            <span class="shimmer line" style="width: 100%"></span>
                            <span class="shimmer line" style="width: 35%"></span>
                            <span class="shimmer line" style="width: 20%"></span>                       
                        </div>
                        <div class="template_previewContainer ms-hiddenSm">
                            <div class="doc-container">
                                <div class="img-container">
                                    <div class="shimmer img-preview" style="width: 120px;height: 70px;"></div>
                                </div>
                            </div>
                        </div>
                </div>
            </li>
            {{/times}}
        </ul>
    </div>

</content></PRE>

**Expected behavior**
A distinct template usage based on the Edit Result Type settings

**Desktop (please complete the following information):**
 - Browser Edge, Edge Chromium, Chrome

**Comment by wobba** [comment]
Best guess, you don't have bcContentCategory in the list of mp's to retrieve. Use the debug template to see mp's and values, which should help for those expressions.

**Comment by rgraley** [comment]
Awesome!  Thanks for the quick response.  I checked the Managed Properties in debug and they are there 
"LastModifiedTime": "2020-06-24T17:08:14.0000000Z",
      "bcContentCategory": "Pay For Skills",
      "RefinableString36": "Pay For Skills",
      "AccountName": null,

This worked but I hope it is what you were suggesting
Just in case others want to see what the template should like after the change.  

`<content id="template">
    <style>
        .root-494{
            font-size: 20pt;
            height:100px;
            display: inline-block;
            -webkit-font-smoothing: antialiased;
            font-style: normal;
            font-weight: normal;
            speak: none;
            font-family: FabricMDL2Icons-15;
            width:35px;
            content:"\F7DB"; 
            color: {{@root.themeVariant.palette.themePrimary}};
        }
        .example-themePrimary a {
            color: {{@root.themeVariant.palette.themePrimary}};
            text-decoration: none;
        }
        .example-themethemeLight {
            font-size: 10px;
            text-transform: capitalize !important;
            color: {{@root.themeVariant.palette.themeTertiary}};
        }
    </style>
<div class="template_result">
    <i data-icon-name="D365TalentLearn" role="presentation" aria-hidden="true" class="root-494"></i>
    <div class="template_contentContainer">
              <span class="template_title example-themePrimary"><a data-interception="off" href="{{getUrl item}}" target="_blank">{{Title}}</a></span>
        <span>
            {{getSummary HitHighlightedSummary}}
        </span>
        <span class="example-themeLighter" style="padding-top:10px;">last modified: {{getDate LastModifiedTime "LL"}}</span> 
        <div class="template_tags example-themePrimary">
            {{#if owstaxidmetadataalltagsinfo}}
                <i class="ms-Icon ms-Icon--Tag" aria-hidden="true"></i>
                {{#each (split owstaxidmetadataalltagsinfo ",") as |tag| }}                                                    
                    <span class="example-themethemeLight" style="padding-right:7px;">{{tag}}</span>
                {{/each}}
            {{/if}}
        </div>
    </div>
</div>`

**Comment by rgraley** [comment]
that didn't show anything so maybe a picture will.  I simply removed all the code except for the code within the {{#>resultTypes}} section and the styles
![image](https://user-images.githubusercontent.com/69590808/90046511-94f13280-dc9e-11ea-9f8d-2b43630260ef.png)

**Comment by rgraley** [comment]
Yes it is resolved. Thanks for the guidance
