### ISSUE TITLE
Search result displaying personal OneDrive result even when it is set to Off in the search results configuration

### ISSUE THREAD

**Issue by limcysam** [microsoft-search/pnp-modern-search#427]
**Version used**
3.9.0.0
--

**Describe the bug**
Search results web part is displaying personal OneDrive results even when it is set to Off in the search results configuration

**To Reproduce**
1. Add the Search Results web part
2. Set the configuration to not display OneDrive Results (see below)

![image](https://user-images.githubusercontent.com/42954663/90350533-c98b3280-e080-11ea-8693-2443f16d3bfe.png)

3. Save the page
4. When you search for a user it displays personal onedrive files

**Expected behavior**
Search results shouldn't display results from onedrive if its configuration is set to Off.

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome

**Comment by wobba** [comment]
Thing is that the underlying API works in different manners depending on tenants, which is why the switch was introduced. Just add the following filter and you're good to do:

`-path:https://tenant-my.sharepoint.com` to remove the files.

**Comment by MariaTusak** [comment]
Hello - I have the same issue - with V4 though. The filter suggested does not work here and creates an error message...

**Comment by wobba** [comment]
Use a path filter. The OneDrive toggle don't work as API's have change. You need to replace `tenant` with the name of your own tenant.
