### ISSUE TITLE
Pagination root URL off if referencing from another site

### ISSUE THREAD

**Issue by scottpartelow** [microsoft-search/pnp-modern-search#431]
**Version used**
3.14.1.0

**Describe the bug**
While I have the full solution running on it's own site, I had a need to reference the data on a different site than the data was deployed.  When I turn on Pagination on the main site, it works without issue, but when I turn in on the secondary site, the Pagination is using the URL from the secondary site for each number instead of the data site.  Each of the search parts are working correctly (all are referencing the data site), but this one item is not working as I would expect.  I can't find any specific area to define the home URL for the Pagination, so it it exists and I missed it I apologize.

So, site A has the data and the refiners running without issue.  Let's call it https://mywebpages.com/sites/siteA.  The site that I am trying to run the refiners from as well is site B.  Let's call it https://mywebpages.com/sites/siteB.  On site A, if I turn on Pagination and look at the numbers, I see https://mywebpages.com/sites/siteA/SitePages/Dashboard.aspx#.  This is the desired value since everything is on the default site.  However, on site B I see https://mywebpages.com/sites/siteB/SitePages/Dashboard.aspx#.  Since everything is referencing site A, having the Pagination refer to site B is undesirable.

**To Reproduce**
Setup a new site with the modern refiners looking back on a different site's data.

**Comment by wobba** [comment]
It would help if you shared the web part setup on query template and result source. If no results source, are the default result source different on the sites, or are there query rules on one and not the other adding to the query?

If you use the debug template you can look at the query modification and compare for the two sites if they are equal or not.

**Comment by scottpartelow** [comment]
Site A and B are identical-
		- Query Template - {searchTerms}(contenttype:"Document")
		- Result Source - Blank

Looking at the debug, the Query Modifications look like this below.  Slightly different, but I think, essentially the same.  I don't think the ContentClass stuff matters if I read this right.

Site A
"queryModification": "Path:\"https://mywebpages.com/sites/PS-Internal_Site/Clients\"(contenttype:\"Document\") -ContentClass=urn:content-class:SPSPeople",

Site B
 "queryModification": "PATH:\"https://mywebpages.com/sites/PS-Internal_Site/Clients\"(contenttype:\"Document\") PATH:\"https://mywebpages.com/sites/PS-Internal_Site/Clients\"",

**Comment by scottpartelow** [comment]
So, I made some changes to the search query configuration since it seemed like the Site B had the URL twice (see above).  Modifying the options there made everything work.  I had changed them a number of different ways, but I have to admit some of the variations are over my head.  Anyway, the Pagination still shows the Site B, but it works as expected when it makes the call.  

Thanks for your help!

**Comment by wobba** [comment]
Those query's look broken for both of them. They should look like: 

`Path:"https://mywebpages.com/sites/PS-Internal_Site/Clients" SPContentType:"Document"` 

Always use `SPContentType` over `ContentType`.

I would clean up the query template either in the search web part or in the result source - and make sure they look exactly the same to ensure you have the same results.

**Comment by scottpartelow** [comment]
Understood.  Thanks for the advice.

**Comment by wobba** [comment]
Let me know if you resolved the issue and we'll close it 🙂

**Comment by scottpartelow** [comment]
All good.  It is working and I applied your suggestions.  Please close.  Thanks.
