### ISSUE TITLE
Opensearch results paging not working

### ISSUE THREAD

**Issue by subramanyamnvr** [microsoft-search/pnp-modern-search#432]
I am working with Opensearch result source and pnp search webpart. Results are showing up as expected on 1st page but clicking on other pages from paging toolbar just refreshes the intial page.  I created result source as http:searchsite.com/api/opensearch?query={searchTerms}&amp;limit={count?}&amp;startIndex={startIndex?}&amp;content-lang={language?}.  Do i need to change the parameters passed to results source. Paging is working fine for other result sources which are targetted to Local and remote sharepoint sites.

**Comment by wobba** [comment]
We haven't done any work to support OpenSearch in particular - and we don't pass in count/startIndex/language as query variables. Our supported list is at: https://microsoft-search.github.io/pnp-modern-search/search-parts/search-results/#out-of-the-box-query-variables
