### ISSUE TITLE
Search Filters: Refiners linked to lookup columns are not displayed

### ISSUE THREAD

**Issue by ileana2019** [microsoft-search/pnp-modern-search#433]
!! Check existing issues before logging new ones !!

**Version used**

3.14.1.0
--

**Describe the bug**
When configuring the Search Filters webpart and adding a refiner which is a RefinableString linked to a lookup column (ex: managed Property of type text: RefinableString11 linked to the crawl property own_Competency), the search filters webpart is empty. The Search Results webpart is correctly displaying the RefinableString11 column.

**To Reproduce**
1. Go to Search Filters webpart settings
2. Click on Edit Refiners
3. Add a refiner linked to a lookup column
4. See that no filters are displayed inside the Search Filters webpart

**Expected behavior**
Refiners linked to lookup columns should be displayed inside the Search Filters webpart.

**Desktop (please complete the following information):**
 - Browser : Chrome

**Comment by wobba** [comment]
1. Does other refiners work?
2. How did you set up the filter web part - with connection etc?
3. If you look at the network trace for the search API call, do you see the request asking for the refiner, and data coming back?

**Comment by ileana2019** [comment]
Hello,
I just made it work. I was using aliases for the managed properties. Now I changed to the actual name of the RefinableString and it works. 
Thanks for the reply!
