### ISSUE TITLE
Search Results: group the results by a certain column

### ISSUE THREAD

**Issue by ileana2019** [microsoft-search/pnp-modern-search#434]
**Is your feature request related to a problem? Please describe.**
Inside the Search Results webpart, I would like to be able to group the results by a column (example: by the library name).

Is there a way to do this in the current solution?

Thanks!

**Comment by wobba** [comment]
Short answer yes.

Read into how handlebars and handlebar helpers can iterate and filter items and you can have a custom rendering based on this logic.
