### ISSUE TITLE
Search Results: Display Publishing HTML field value

### ISSUE THREAD

**Issue by ileana2019** [microsoft-search/pnp-modern-search#435]
**Is your feature request related to a problem? Please describe.**
In the search results webpart, when displaying the RefinableString managed property linked to a Publishing HTML field, the raw HTML is displayed. Is there a way to decode the HTML field value inside the search results custom display template?

**Comment by wobba** [comment]
No, and you should really stop using classic publishing features (my personal opinion) 😉

I'll tag this issue as an enhancement potential in case someone want's to create a handlebar helper method for this scenario.

**Comment by ileana2019** [comment]
Well I was first using just a multiple line of text, with enhanced rich text, but then I am getting only plain text back from the search.
A handlebar helper will be great!
Thanks!

**Comment by HamEv** [comment]
Hi @wobba,
I have the same requirements for my customer. I created a sharepoint list with question/answer column. Column is designed as multipline text box with rich text and I want to show the results in a search result webpart (custom template). The answer column is a managed property (CFAQAnswerOWSMTXT) and it would be great if I can render my answer correct. 
Is there a handler or another solution already implemented?
Thanks.

**Comment by wobba** [comment]
There's a solution in #533 to use triple braces. `{{{CFAQAnswerOWSMTXT}}}`. I recommend trying this.
