### ISSUE TITLE
Display page sections or webparts to search results custom layout accordion

### ISSUE THREAD

**Issue by mongoux** [microsoft-search/pnp-modern-search#438]
Hi,

Is it possible to add page sections or defined page content to a pnp-accordion and to a pnp-popup? 

I have a page that contains an image and a table in the first and third sections of the page and would like to display them in the accordion and the popup.
![image](https://user-images.githubusercontent.com/35407310/91056373-3163ef00-e626-11ea-8474-3e1d6db4f98d.png)

`<pnp-accordion data-accordion-header-text="Accordion Example" data-theme="Neutral" data-size="12" data-start-open="false" data-rounded-corners="false">
                                <h4>Title: {{Title}} Email:{{Author.Email}}</h4>
                                <pnp-popup>
                                    <template id="popupclick">
                                        <span>Solution - Click Me </span>
                                    </template>
                                    <template id="popupheader">
                                        <span>Title: {{Title}}</span><br /><span>Header HTML here</span>
                                    </template>
                                    <template id="popupbody">
                                        <span>Title: {{Title}}</span><br /><span>{{getSummary HitHighlightedSummary}}</span>
                                    </template>
                                </pnp-popup>
                            </pnp-accordion>`

Thanks

**Comment by wobba** [comment]
There is no direct way to have the templating in the search web part access or manipulate HTML outside of it. You can create a custom web component and use that which does whatever you want. See https://microsoft-search.github.io/pnp-modern-search/search-extensibility-library/getting-started/

**Comment by mongoux** [comment]
Thanks for the link.
