### ISSUE TITLE
Refiners are not getting applied on navigating to different pages

### ISSUE THREAD

**Issue by Bhoomi95** [microsoft-search/pnp-modern-search#440]
**Version used**
Ex: 3.13

**To Reproduce**
1: Navigate to any page from pagination displayed in search results webpart
2: Select any refiners and apply
3: The search results is not changing based on the refiners. 
4: On navigating back to the first page, could see refiners getting applied

**Expected behavior**
Refiners should apply on navigating pages also.

**Comment by wobba** [comment]
This is fixed in the dev branch.

**Comment by Bhoomi95** [comment]
When can we expect this in a public release, because we are already having the component in stage environment, making production ready

**Comment by wobba** [comment]
I was planning this week but as I'm busy with other work I cannot promise when. You can always build a version yourself.
