### ISSUE TITLE
Search results web part property panel empty on one site

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#441]
!! Check existing issues before logging new ones !!

**Version used**
3.14.2

**Describe the bug**
Results web part edit properties panel is empty (only on one site - other sites not an issue, though I have definitely seen this issue before but it "went away" for  some unknown reason)
**To Reproduce**
1. Insert search results web part on a site page
2. Click on edit or configure
3. Panel opens but is empty

**Expected behavior**
Should be able to configure the results web part
**Screenshots**

**Desktop (please complete the following information):**
 Chrome on W10 Enterprise

**Additional context**
Initially the solution wasn't tenant deployed, but when I switched to this version I did deploy it tenant wide. It continued to work normally on existing sites.
When I inspect the problem site, the code set up looks exactly the same as the working sites. There's no other customization on this site not on working sites. 
![Untitled](https://user-images.githubusercontent.com/51796756/91463175-11684180-e859-11ea-827b-f46acbecba5e.png)

**Comment by wobba** [comment]
I cannot repro, and seems you cannot either consistently :) Can you try to remove it and re-add? Any details in the browser console?

**Comment by webbrewer** [comment]
I did remove and readd, and tried on a new page. Also added to a "working" site and there was no issue.
Console:
The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
search-results-web-part_1586fa82c159ee12d67c608126b4c722.js:1 
Message: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://xxx.sharepoint.com/sites/inclusion-diversity-belonging/_api/web/regionalsettings/installedlanguages' exceeded the quota. Data: {"stack":"Error: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://xxx.sharepoint.com/sites/inclusion-diversity-belonging/_api/web/regionalsettings/installedlanguages' exceeded the quota.\n    at e.put (https://xxx.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_1586fa82c159ee12d67c608126b4c722.js:1:684058)\n    at e.cacheData (https://xxx.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_1586fa82c159ee12d67c608126b4c722.js:1:797396)\n    at https://xxx.sharepoint.com/sites/apps/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_1586fa82c159ee12d67c608126b4c722.js:1:797283"}
e.log @ search-results-web-part_1586fa82c159ee12d67c608126b4c722.js:1
search-results-web-part_1586fa82c159ee12d67c608126b4c722.js:1 

Message: [SearchService._getQueryLanguages()]: Error: QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://xxx.sharepoint.com/sites/inclusion-diversity-belonging/_api/web/regionalsettings/installedlanguages' exceeded the quota.
e.log @ search-results-web-part_1586fa82c159ee12d67c608126b4c722.js:1
2search-results-web-part_1586fa82c159ee12d67c608126b4c722.js:1 

Uncaught (in promise) Error: QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://xxx.sharepoint.com/sites/inclusion-diversity-belonging/_api/web/regionalsettings/installedlanguages' exceeded the quota.
    at e.<anonymous> (search-results-web-part_1586fa82c159ee12d67c608126b4c722.js:1)
    at search-results-web-part_1586fa82c159ee12d67c608126b4c722.js:1
    at Object.throw (search-results-web-part_1586fa82c159ee12d67c608126b4c722.js:1)
    at a (search-results-web-part_1586fa82c159ee12d67c608126b4c722.js:1)

**Comment by webbrewer** [comment]
@wobba  I rebooted the laptop and now it seems to be working fine. Not sure why that would be the fix, but it was.

**Comment by wobba** [comment]
Seems weird browser or React related.
