### ISSUE TITLE
Refiners only work on first page

### ISSUE THREAD

**Issue by schatti** [microsoft-search/pnp-modern-search#442]
**Version used**
Ex: 3.13

**Describe the bug**
The Refiners/Filters only work when used on the first page of results. When paging is enabled and you navigate to second, third, etc. page, the refiners are not working.

**To Reproduce**
1. Setup Search Box WP
2. Setup Search Filters WP
3. Setup Search Results WP
4. Connect WPs correctly
5. Search for "*"
6. Go to second page (or another, not first)
7. Use Filter WP
8. No filtering occours

**Expected behavior**
Filter the results as defined

**Comment by wobba** [comment]
Fixed in the dev branch - will arrive in the next release. Several resolved issues related to this :)
