### ISSUE TITLE
Refiners don't work with pagination (page 2 and onwards)

### ISSUE THREAD

**Issue by poidah** [microsoft-search/pnp-modern-search#443]
**Version used**
3.13

**Describe the bug**
I have a page with the search box, refiners and search results web parts on it and nothing else.
The refiners have no affect on the results when you are not on the first page of results.
I have tried all types of refiners
I have tried all layouts including custom
My search page size is 20 items

**To Reproduce**
1. Go to custom search page
2. Run a search
3. Use the pagination to move to another page
4. Click on any refiner

**Expected behavior**
The number of search results is reduced based on the refiner selected

**Actual behavior**
The search results becomed greyed out, appear to reload/refresh but do not change

**Screenshots**
Please see screen shot attached. There should only be 1 result according to the refiners and there is _but only if you are on page 1 of the results_.
![refining and pagination](https://user-images.githubusercontent.com/10804466/91674040-6918ec80-eb7a-11ea-9793-bf4b51d9df05.png)

**Desktop**
Windows 10
Edge (old)
Edge (chromium) - 85.0.564.41
Chrome - 84.0.4147.135

**Comment by wobba** [comment]
Multiple issues closed on this already. Fixed in the dev branch and will be released in the next version.
