### ISSUE TITLE
Can not configure "No Results" message for custom result template

### ISSUE THREAD

**Issue by poidah** [microsoft-search/pnp-modern-search#444]
**Version used**
Ex: 3.13

**Describe the bug**
If no search results are returned for a query I would like to display the text "No Results". This works with a toggle switch in the results web part for standard layouts but not with the custom template layout. There is no documentation on how to do this. 

**To Reproduce**
1. Go to custom search page
2. Search for something that retuns no results
3. No text is tesplayed when there are no results reurde despite having the results webpart configured to do so

**Expected behavior**
The words "No Results" appear when a search query returns nothing

**Screenshots**
![custom no results](https://user-images.githubusercontent.com/10804466/91674624-cc0b8300-eb7c-11ea-9c43-a56a7f741cd8.png)
![table no results](https://user-images.githubusercontent.com/10804466/91674627-ce6ddd00-eb7c-11ea-9cc9-5b0326fb1fca.png)

**Desktop**
Windows 10
Edge (old)
Edge (chromium) - 85.0.564.41
Chrome - 84.0.4147.135

**Comment by wobba** [comment]
Pick one of the default templates. Click the {} beside "Edit template" and you see how the default ones do this. Copy as needed.

```
{{#if @root.hasPrimaryOrSecondaryResults}}
....
{{else}}
   {{#unless showBlank}}
      <div class="template_noResults">{{@root.strings.NoResultMessage}}</div>
   {{/unless }}
{{/if}}
```

Agree it could be added to the docs.

**Comment by poidah** [comment]
Awesome! Thank you, that's exactly what I needed 👍

**Comment by dheerajbalmuri** [comment]
Hi, I just wanted display some SVG file when there are no results for search. can it be done and what would it be like syntax wise?

**Comment by wobba** [comment]
In the section for no results in your template you add an image tag pointing to your svg.
