### ISSUE TITLE
Refiner only showing and filtering 100 items in SPO

### ISSUE THREAD

**Issue by DiHendriks** [microsoft-search/pnp-modern-search#445]
The refiner has more than 100 items from the termset.
Only the first 100 items are shown and when searching it will only searches within these 100 items. 

![image](https://user-images.githubusercontent.com/70517570/91714245-991cbb80-eb8b-11ea-90d2-f334354dbcd0.png)

Is it possible to show all items in the refiners and if not, make it possible to filter all items even if they are not shown.

**Comment by wobba** [comment]
API wise it's possible to increase this. The default is 100 buckets (it seems, but not documented afaik). Do you envision a parameter to specify the max? UX wise a refiner with 100+ is not very usable, so what's the user scenario for needing this? If it's searching, then they can enter the term itself in the query box as well.

**Comment by DiHendriks** [comment]
Hello @wobba , 
the termset has all hardware for customers documentation so engineers in the field can filter on the specific hardware.
Showing only 100 items is not the main issue but not finding an item that isn't showing is. So searching them by entering the term is not working.  Now an engineer in the field first has to bring down the result of the hardware beneath 100 items..  So in the picture showing he now first selects the customer and in this case only 16 hardware items are showing and he/she finds the device with the correct manual. Most customers have more than 100 hardware devices and more filtering needs to be done. When searching "wave" I do not fins any results without filtering and it should be nice if the items should appear in the results without them having to choose other filters. 
![image](https://user-images.githubusercontent.com/70517570/91719531-c706fd80-eb95-11ea-9f3f-8a9fc04c8359.png)

**Comment by wobba** [comment]
So the users don't know the codes, but parts of. So want to filter on what they remember? Do I get this right?

**Comment by DiHendriks** [comment]
Yes, that is correct. The engineers know it is wave or searching on the number they remember. 
Problem now is that, if the hardware like wave 6140-e55 (or any other hardware with the name wave) is not listed in the first 100 results within the refiner, it cannot be found by the (hardware) filter.

**Comment by wobba** [comment]
The alternative is to teach them to query like below.

`Hardware:wave`

I'm thinking if we should just ask for max 500/1000/5000 buckets for all refiners, or have a config parameter so you can enter the refinerspec yourself. See https://docs.microsoft.com/en-us/sharepoint/dev/general-development/query-refinement-in-sharepoint#adding-refiners-to-the-end-users-query-by-using-refiner-specs

**Comment by DiHendriks** [comment]
It would be nice if we can ask for max 5000 buckets for all refiners. In that case it would solve it and they can easily find the specific term within the refiner. We are now around 800 different hardware devices.

**Comment by SPNass** [comment]
Hi @wobba @DiHendriks 
I confirm this limitation is also a big issue for me, as I'm facing this behavior on all my search pages.
Would be great to have an additional parameter to go further 100 items within filters.

Anyone has an idea on when this enhancement would be available ?

**Comment by wobba** [comment]
When someone decides to add as this is a community project. If you want it, you add it 😉 Or wait for someone to spend time doing it.

**Comment by alexhamakers** [comment]
I'm having the same issue too. I was glad to see it was already identified. Our use case is quite similar to that of DiHendriks. For us it is learning catalogs for competences. We have more than 100 competences, and each of them has their own learning catalogs. We also noticed that once we go past the 100 competences, some results drop from the refiner. Next to that, to me it appears to be random which result drops exactly. 

For now we are able to work around it by first selecting a so called domain, before zooming in on the competences. There are only 18 domains, and all competences belong to one of them. But is would be nice to give users the opportunity to go through the complete list of 100+ competences if they want.

**Comment by wobba** [comment]
Added this to the dev branch. Don't have a refiner with more than a 100 values so would be great if someone could test it. The change should not impact when you have less values so should be ok.

**Comment by alexhamakers** [comment]
We are currently running version 3.15.3. I can confirm the refiner now shows all results. Thanks!
