### ISSUE TITLE
Impossible to install extensibility library

### ISSUE THREAD

**Issue by MaximeChofardet** [microsoft-search/pnp-modern-search#446]
After successfully adding & deploying the package "pnp-modern-search-parts.sppkg" in a site collection app catalog, I am unable to deploy with success package "pnp-modern-search-extensibility-library.sspkg".
Repro steps :

Package app np-modern-search-extensibility-library
Add the package in the dedicated site collection app catalog
Try to deploy the app => No error message
When returning to "Site Contents", the app stay blurred as below :
blurrd

Could you please indicate us what is the issue.

Thanks in advance,

**Comment by wobba** [comment]
This sounds like a generic SPFx issue actually, not related to search (sorry for sending you here in the first place). Can you try to uninstall the app from the site. Remove it from the app catalog, and re-add it. Can you also try it via a tenant wide app catalog?

**Comment by MaximeChofardet** [comment]
Already tested on site collection app catalog and also in tenat wide app catalog.
No issue when deploying the app in an app catalog but impossible to install the instance (after "Add an app" -> select extensibility lib app)
According to previous issue (https://github.com/SharePoint/sp-dev-docs/issues/5706) it seems that library components could be successfully deployed on site collection app catalog but does not seem to work for me and my team !

**Comment by wobba** [comment]
By setting to tenant wide, did that resolve your issue? Even when deploying on a site.

**Comment by MaximeChofardet** [comment]
None of these deployments work.
Any dependencies with other product of PNP Modern Search ?

**Comment by wobba** [comment]
Shouldn't be anything special needed. We're reworking how we do extensibility more dynamically in v4, but that does not help you.

If you follow the settings from https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial#how-to-create-a-third-party-spfx-library it should work.


> Do you want to allow the tenant admin the choice of being able to deploy the solution to all sites immediately without running any feature deployment or adding apps in sites?: Yes
> Which type of client-side component to create?: Library

Docs also only point to tenant wide app catalog. https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial#how-to-deploy-and-consume-a-third-party-spfx-library-from-tenant-app-catalog

Have you tried tenant app catalog + tenant wide deployment? That seems to be the option to use. Nothing you should add manually as an app.

**Comment by stact** [comment]
It seems that's working when installing tenant wide catalog and deploying globally
![image](https://user-images.githubusercontent.com/9899166/96714164-0c7bc600-13a2-11eb-903d-7e412788551e.png)

When trying on tenant wide catalog and not globally (uncheck solution available on all sites) it's not working when installing on a site collection 
![image](https://user-images.githubusercontent.com/9899166/96714333-4947bd00-13a2-11eb-9e0b-ed7d0680fdb4.png)

![image](https://user-images.githubusercontent.com/9899166/96714376-58c70600-13a2-11eb-897c-6b0d68bf34f1.png)

Can't access details of the errors ^^ (SharePoint show me blank page when cliking on "4 errors")

@wobba hope it helps to understand the issue and maybe to get extensibility to be working for v4 or to update the documentation if the spfx is not considering this approach

**Comment by stact** [comment]
Related to #93 
Unfortunatelly, we provide a solution that include extensibility, with this approach we must seperate the extensibility

**Comment by wobba** [comment]
Libraries has to be installed tenant wide globally. It's a SPFx limitation.

**Comment by Holden15** [comment]
I would suggest updating the installation page:

> For the pnp-modern-search-parts.sppkg package, you can choose to make the solution available in all sites or force to install an app to the site every time.

Doesn't mention that the extensibility library needs to be installed in the tenant wide globally.  I had no idea that it did until I found this thread.

**Comment by wobba** [comment]
@Holden15 I've made doc updates which we will push later via #710.
