### ISSUE TITLE
Question: Can we increase the search scope to all the sites on tenant or some specific sites on the tenant?

### ISSUE THREAD

**Issue by mrshahidmehmood** [microsoft-search/pnp-modern-search#448]
Hello, I am new to SharePoint and I want to implement this webpart in a modern page sharepoint site but my requirements include to add all the sites in the search scope. Is it possible with this webpart? 

We cannot use hubsite according to requirements so I am open to any other suggestions where we can customize the search to n number of sites without using Hub site or classical approach. 

Thanks,

**Comment by wobba** [comment]
If you want an arbitrary set of sites you need some way to include them. It could for example be by URL convention with a prefix.

`path:https://contoso.sharepoint.com/sites/intra_*` 

If you know all the sites and it don't change you can use multiple path filters, or `SiteID:<id1> OR SiteID:<id2>` or similar.

So it depends on if the scenario is dynamic or static and how you can identify the sites you want to include.

**Comment by wobba** [comment]
Did this work for you?
