### ISSUE TITLE
Date Refiner not working

### ISSUE THREAD

**Issue by schatti** [microsoft-search/pnp-modern-search#449]
**Version used**
Current DEV Branch

**Describe the bug**
When installing the current develpment branch, the refiner for Created Date (Managed Property = "Created", as in default setting) is showing the following Error Message: "This template only works for Created, LastModifiedTime, LastModifiedTimeForRetention and RefinableDateXX properties" even if the Managed Property is set to "Created". 

**To Reproduce**
1. Default setup with Serach Box, Search Verticals, Search Results, Search Filter
2. Connect all togehther
3. Do any search
4. Open the Filter for "Created Date"
5. See the Error Message

**Expected behavior**
Show Filter Values like "Last Week", "Last Year", etc

**Screenshots**
![image](https://user-images.githubusercontent.com/20019646/91980283-47109d00-ed27-11ea-9d63-5cd1112dfebb.png)
![image](https://user-images.githubusercontent.com/20019646/91980339-60194e00-ed27-11ea-84fb-e3a9810f6680.png)

**Desktop (please complete the following information):**
 - Browser Crome

**Comment by wobba** [comment]
I cannot repro this.

1. Added search result web part with a query of *
2. Added a filter web part
3. Connected filter web part to result web part
4. Connected result web part to filter web part
5. Clicked edit refiners in the refiner wp

**Comment by schatti** [comment]
Strange, I can reproduce every time, don't get it to work. The other control "Date Range" works. 
I will restart, uninstall the app, delete from recycle bin, pull dev branch, build, reinstall und try again...

**Comment by schatti** [comment]
To make sure it is not my development environment I asked a colleague to build the develop branch. After that I installed the package on another environment and got the same result. The control "Date Range (fixed intervals)" shows the error message. I also tried to use another Managed Property (RefinableDate00) with the same result.

**Comment by wobba** [comment]
I'll retest and take a look 👍

**Comment by schatti** [comment]
Thanks a lot. I only experience this when I take the develop branch. Regards, Marco

**Comment by wobba** [comment]
Looking at the code I see this check `if (this.props.refinementResult.Values.length !== 6) `. Can you look at how many values and which ones you get back in your response via the network trace?

**Comment by wobba** [comment]
Found the issue, and I believe it might have been an error for something else I did :)

**Comment by wobba** [comment]
@schatti Fixed in dev branch.

**Comment by schatti** [comment]
Thanks a lot.

**Comment by wobba** [comment]
Now in the sept release 😀
