### ISSUE TITLE
Search results: managed column handlebar expression won't render line break and images

### ISSUE THREAD

**Issue by mongoux** [microsoft-search/pnp-modern-search#450]
Hi, 
I have created a list that has a multiline column with enhanced rich text called solution and added this handlebar expression to the detailed list managed column: 
 ```
<pnp-popup>
    <template id="popupclick">
         <span>More information and solution</span>
    </template>
    <template id="popupheader">
        <span>{{Title}}</span>
    </template>
    <template id="popupbody">
                                       
    <span>Solution:<p>{{KEDBSolution}}</p>  </span>
                                   
    </template>
                                  
</pnp-popup>
```
The text is displayed in the search results, however, there are no line breaks. The text is one line and no image.

Expected behavior:
![image](https://user-images.githubusercontent.com/35407310/92096360-1425e200-edd7-11ea-8c7e-672987d652d4.png)

Search result output:
![image](https://user-images.githubusercontent.com/35407310/92096540-4cc5bb80-edd7-11ea-9668-caea66012641.png)

No line breaks or the image. 

How can I fix this please? 

Thanks in advance! Thanks for these webparts too!

**Comment by mongoux** [comment]
@wobba Can you please help me with this problem? If I can make this work, it will be a game changer for us!

**Comment by wobba** [comment]
Look at the markup - and we probably have to add handlebar helper which can properly render a richtext field.

**Comment by mongoux** [comment]
Sorry, what you mean "look at the markup"?  What am I looking for?   How can I add the handlebar helper  please?

**Comment by mongoux** [comment]
> Look at the markup - and we probably have to add handlebar helper which can properly render a richtext field.

Sorry, what you mean "look at the markup"? What am I looking for? How can I add the handlebar helper please?

**Comment by wobba** [comment]
What does the HTML look like for the one line data you are looking at using F12 and dev tools?

**Comment by mongoux** [comment]
@wobba looks like this: 
![image](https://user-images.githubusercontent.com/35407310/92244112-c5557680-eec2-11ea-8116-801780b52306.png)

**Comment by mongoux** [comment]
This the HTML markup from the list form page:

`<div class="od-FieldRenderer-text"><div class="ExternalClassB4D1A94B1D274F0DAD65FDAC4540C191"><div>Registration team has to register the unknown  account number
<br></div><div>
<br><span style="font-family:impact;">Step 1: Do this....
</span><ol><li><span style="font-family:impact;">Do this....x</span></li><li><span style="font-family:impact;">Do this....</span></li><li><span style="font-family:impact;">Do this....x</span></li><li><span style="font-family:impact;">Do this....</span></li><li><span style="font-family:impact;">Do this....x</span><br></li></ol></div></div><div>&lt;br&gt;<br></div><div class="ExternalClassB4D1A94B1D274F0DAD65FDAC4540C191"><div>Step 2: Do this.....
<br>
<img alt="" style="max-width:100%;"><img alt="" style="max-width:100%;">&lt;/br&gt;<br>Step 3: Do this....
<br>
<br>Step 4: Do this.....<div style="margin-top:14px;margin-bottom:14px;"><img src="https://www.enjoysharepoint.com/wp-content/uploads/2018/07/sharepoint-2013-error-bcs-there-are-no-address-available-for-this-application.png" style="max-width:100%;"><br></div><div style="margin-top:14px;margin-bottom:14px;"><img alt="" style="max-width:100%;"><br></div></div></div></div><div class="ReactFieldEditor-MoreToggle" tabindex="0">See less</div>`

**Comment by mongoux** [comment]
This is the HTML markup from the list form display page:

<div class="od-FieldRenderer-text"><div class="ExternalClassB4D1A94B1D274F0DAD65FDAC4540C191"><div>Registration team has to register the unknown  account number
<br></div><div>
<br><span style="font-family:impact;">Step 1: Do this....
</span><ol><li><span style="font-family:impact;">Do this....x</span></li><li><span style="font-family:impact;">Do this....</span></li><li><span style="font-family:impact;">Do this....x</span></li><li><span style="font-family:impact;">Do this....</span></li><li><span style="font-family:impact;">Do this....x</span><br></li></ol></div></div><div>&lt;br&gt;<br></div><div class="ExternalClassB4D1A94B1D274F0DAD65FDAC4540C191"><div>Step 2: Do this.....
<br>
<img alt="" style="max-width:100%;"><img alt="" style="max-width:100%;">&lt;/br&gt;<br>Step 3: Do this....
<br>
<br>Step 4: Do this.....<div style="margin-top:14px;margin-bottom:14px;"><img src="https://www.enjoysharepoint.com/wp-content/uploads/2018/07/sharepoint-2013-error-bcs-there-are-no-address-available-for-this-application.png" style="max-width:100%;"><br></div><div style="margin-top:14px;margin-bottom:14px;"><img alt="" style="max-width:100%;"><br></div></div></div></div><div class="ReactFieldEditor-MoreToggle" tabindex="0">See less</div>

**Comment by mongoux** [comment]
![image](https://user-images.githubusercontent.com/35407310/92246065-870d8680-eec5-11ea-8e07-598320bc3348.png)

**Comment by wobba** [comment]
Seems you need to add some CSS then to your template and it should work as the HTML is there for your list.

**Comment by mongoux** [comment]
@wobba Adding CSS doesn't seem to work. any idea why? Is there any way to make this work?

**Comment by wobba** [comment]
What's the CSS you added to the template? And if you inspect the DOM you should see why no line break is there, and you can experiment with what to add.

**Comment by wobba** [comment]
Closing as an old issue
