### ISSUE TITLE
Not seeing Search Query's properties in search query configuration

### ISSUE THREAD

**Issue by scolladoajws** [microsoft-search/pnp-modern-search#451]
Hi there,

While setting up the search query configuration, I am not getting a search query property option as indicated in the guide
![image](https://user-images.githubusercontent.com/70716143/92147960-d41c2a80-ede9-11ea-858c-ca1c125f0dc7.png)

This is what I get
![image](https://user-images.githubusercontent.com/70716143/92148158-25c4b500-edea-11ea-82b4-609fb9394209.png)

Thoughts?

Thanks,

Steven

**Comment by wobba** [comment]
Seems things have changed and you are good to go as it is. I'll make a note to update the screenshot 👍

**Comment by scolladoajws** [comment]
Okay got it!
