### ISSUE TITLE
Search Document Titels

### ISSUE THREAD

**Issue by NicoFabr** [microsoft-search/pnp-modern-search#452]
**Version used**
Ex: 3.14

**Describe the bug**
Trying to find Documents by name with the follwing Query Template: 

Path:{Site} Filename:({SearchBoxQuery}) OR Title:({SearchBoxQuery})

When trying to find something, I am not getting all the Documents with the correct name. There are missing many results? 
Any ideas what could be wrong?

**Comment by wobba** [comment]
This is a question outside of the web parts itself and relates to your content. `Title` is populated by a set of crawled properties in order, and you have to to ensure one of them has the value you suspect. A top "Title" style in the document itself, does not really mean that's the "Title" extracted.

**Comment by NicoFabr** [comment]
Mhh thanks for your quick reply! Any ideas and how to solve this problem or what I could check? For example: When searching for a document which has the name ABC in the document library, the search web part can't find it...

**Comment by wobba** [comment]
I have plenty :D If the name is "abc", target `Filename:abc` instead of `Title`. Name and Title are two very different things.
