### ISSUE TITLE
Site Feature not showing and unable to add the App

### ISSUE THREAD

**Issue by gmparky** [microsoft-search/pnp-modern-search#454]
**Version used**
Ex: 3.14.2

**Describe the bug**
I am unable to add the solution to Site Collections. I have used the web parts on several sites and the solution & app are available on those sites. 

However, If I try to add the Solution / App to a new site collection the App is not listed and I am unable to add it to the site collection. The App is deployed from the App Catalog and is Deployed across the tenant. 

**To Reproduce**
1. Go to Site Collection
2. New App
3. PnP Modern Search is not listed to add
4. Go to Site Settings
5. Manage Site Features - No Search features enable to activate. 

**Expected behavior**
Add should be available to add.

**Comment by wobba** [comment]
Does this only apply to the PnP solution or other SPFx solutions as well? It all depends how it was installed, tenant wide or not. So not a specific issue to this project but more on you need to figure out how the package was installed etc - SPFx related.

**Comment by gmparky** [comment]
Hi, It's specific to the PnP solution the other solutions are available. It has been working previously as I have used it. It's tenant wide 
![Annotation 2020-09-04 123040](https://user-images.githubusercontent.com/40665509/92234766-874c5880-eeaa-11ea-861e-f283e68ab2be.png)

**Comment by wobba** [comment]
Can you try to remove it, then re-install?

**Comment by gmparky** [comment]
OK I have re-added and the deployment has changed as the webparts are now available on all the sites without adding the app. 
Thanks for your help
