### ISSUE TITLE
Resultswebpart not working in SharePoint Mobile App on iOS

### ISSUE THREAD

**Issue by EbSe** [microsoft-search/pnp-modern-search#455]
When I open up a search result in the SharePoint mobile app on ios the results are displayed but when I click on a word or pdf document I'm redirected to the document library and not to the preview of the document.

I played around with custom formating and different URLs but found no good solution which works with all document types.

**Comment by wobba** [comment]
@EbSe try the dev branch.. should have URL's which probably should work on mobile as well. I changed the logic on the URL's.

**Comment by EbSe** [comment]
Is there a compiled version?

**Comment by wobba** [comment]
Coming.......

**Comment by EbSe** [comment]
> Coming.......

Hi @wobba, where will you provide it? Will you make a new release build? I need the functionality in a current customer project ^^ BR, Sebastian

**Comment by wobba** [comment]
Release made on Friday :) You can add an alert by watching the repo.

![image](https://user-images.githubusercontent.com/51104/92359538-b7366e80-f0eb-11ea-941e-c77ea51798fa.png)
