### ISSUE TITLE
For one result page, pagination web part should not render

### ISSUE THREAD

**Issue by quarterhorse** [microsoft-search/pnp-modern-search#46]
**Version used**
3.7.0.0

**Describe the bug**
Pagination should hide if there is only one page of results.

**To Reproduce**
Create a page having the query box, result part, and pagination part all appropriately connected.

Issue a query resulting in one page of results.  The pagination web part is visible with only page 1 displaying as an option.

**Expected behavior**
A single page of results should hide the pagination control as there is no option to move from page to page.  Frankly, it looks awkward.

![image](https://user-images.githubusercontent.com/36413662/71312372-f99e0b00-23f7-11ea-99c5-f1cdd826e9f9.png)

**Comment by FranckyC** [comment]
Hi @quarterhorse, you're right, it does not make so much sense. I will update this behavior to actually hide the WP in there is only one page. Thank you for your feeback!

**Comment by FranckyC** [comment]
@quarterhorse  should be resolved by #63 . Feel free to checkout the develop branch and test.
