### ISSUE TITLE
hover panels on list items

### ISSUE THREAD

**Issue by cpluceDev** [microsoft-search/pnp-modern-search#462]
is this possible to do? can we do hover panels or previews for list items?

**Comment by wobba** [comment]
Sure, if you do it with a web component. https://microsoft-search.github.io/pnp-modern-search/search-extensibility-library/getting-started/

**Comment by cpluceDev** [comment]
i saw this. thanks. ill take a look. trying ot replicate delve profile properties in the hover panel like classic people search
