### ISSUE TITLE
Extending Custom template in Details view.

### ISSUE THREAD

**Issue by sagar2610** [microsoft-search/pnp-modern-search#464]
**Is your feature request related to a problem? Please describe.**
As discussed with @wobba, currently there is no way to get around "?web=1" query string parameter in Details view.

**Describe the solution you'd like**
It would be great to have an option to change the details view template and add the option to change or extend the {{getUrl}} helper in the template.

**Comment by wobba** [comment]
@sagar2610 are you dealing with list items or files.. for files you would want the DefaultEncodingURL most likely and not the Path right? As path gives dispform and not the file itself.

**Comment by wobba** [comment]
@sagar2610 you can check the logic in my commit.
