### ISSUE TITLE
How can I sort or search based on column criteria?

### ISSUE THREAD

**Issue by scolladoajws** [microsoft-search/pnp-modern-search#465]
I was looking to see how I can  configure the search to search based on column metadata we have on our files. 

Below is an example of all the metadata characteristics we have available for files within our SharePoint site. 
![image](https://user-images.githubusercontent.com/70716143/92765562-76488f00-f363-11ea-8d9c-ebc0ea5dbf36.png)
![image](https://user-images.githubusercontent.com/70716143/92765603-7fd1f700-f363-11ea-9fee-9ce4fd718507.png)

How can i configure the results to show more than the default 3 columns which I tried to add additional columns to view but the setting doesnt save. Additionally search based off the column metadata criteria like Country as shown below:
![image](https://user-images.githubusercontent.com/70716143/92766880-9f1d5400-f364-11ea-8b44-bc4ee03076e0.png)

Let me know if you need additional information.

Thanks,

Steven

**Comment by wobba** [comment]
You need to map the crawled property for you SharePoint column to a refinable managed property (which also is sortable), and then use that on in search. You can read more at https://docs.microsoft.com/en-us/sharepoint/manage-search-schema

**Comment by scolladoajws** [comment]
Got it, thanks!

**Comment by wobba** [comment]
Remember to re-crawl or add new content once you have done the mapping. If not you won't get any values in the managed property.
