### ISSUE TITLE
PNP-Modern Search Road Map

### ISSUE THREAD

**Issue by dpc80111** [microsoft-search/pnp-modern-search#466]
**What is the Road Map for the pnp-modern-search?** 
Does the road map include updates for 2,5,10 years out?
Is MS going to incorporate this into the Modern OOTB search
We just want to know the investment of time and knowledge is worth long term effort.

Thank you for your time.

**Comment by wobba** [comment]
1. The current roadmap involves getting v4 out at some point with more modular support and also incorporate Microsoft Graph Search API capability. It's open source and not driven with long term plans. Suggestions and ideas are always welcome, and everyone can influence the direction.
2. A discussion being brought up internally at least twice per year, but no current plans. It has to be considered in light of where should the Highlighted Content web part go, and the customization options being introduced to the OOB search page.
3. Depends what you use the web parts for. I don't see them as a replacement for OOB search, but more as an enabler of search based portals/app or a more advanced HCWP.

We know there are quite a lot of tenants using the web parts today, so I would not be afraid of using it. Also, if what is there today solves your usecase, you don't need to upgrade as SPFx solutions continue to work on the version they were built.
