### ISSUE TITLE
Extensibility Library web component undefined 

### ISSUE THREAD

**Issue by cpluceDev** [microsoft-search/pnp-modern-search#467]
version 3.14

undefined when using the  custom web component element. the accordion and the popup work. i am using the {{Title}} 
`           <my-custom-component my-string-param="{{bdkmSkills}}" my-object-param="{{JSONstringify MyObjectProperty 2}}"> {{Title}}</my-custom-component>
`

![modernextprop](https://user-images.githubusercontent.com/25770942/92810609-51641400-f383-11ea-8d58-7684d94e74ef.PNG)

**Comment by wobba** [comment]
I suggest you debug your component and figure out what is sent to it and why it's not working as expected.

**Comment by cpluceDev** [comment]
i am still learning the development of these web parts. all i did was download latest solution, do npm install and build and package solution and uploaded the extensibility app to the catalog and used title.  i will verify my properties as i didnt change any of the code

**Comment by cpluceDev** [comment]
anybody else ran into something similar here? i cannot see what the issue is?

**Comment by MakingThingsWorkToronto** [comment]
Try appending "data-" as a prefix on each of the attributes. For example "data-my-string-param" ... "data-my-object-param" ... the [current release](https://github.com/microsoft-search/pnp-modern-search/blob/main/search-extensibility-library/src/models/BaseWebComponent.ts) will not parse attributes if this is missing.

There are some more functional panel components here if you're interested in testing: https://github.com/MakingThingsWorkToronto/mtw-search-extensibility

**Comment by MakingThingsWorkToronto** [comment]
Also, inspect the HTML to ensure there are valid values being passed into the web component.

**Comment by cpluceDev** [comment]
awesome. thanks. i had to append the data- now i need to figure out how to add some design with html as it seems to just to a run-on without breaks or formatting. between my properties

**Comment by cpluceDev** [comment]
how can i achive something like this. i know one way would be to use the my-custom-component tag/element for each property but id think there would be an easier way  data-my-string-param="{{propTitle}}</br>{{propone}}</br>{{proptwo}}"

instead of this:
item properties for propTItle propone proptwo

i want 

Item Properties for propTItle

Label One: PropOne
LabelTwo: PropTwo

**Comment by MakingThingsWorkToronto** [comment]
my-custom-component was built as an example ... you'd need to modify the code & redeploy to achieve that.

Try the Side Panel Template component [here](https://github.com/MakingThingsWorkToronto/mtw-search-extensibility/blob/master/README.md#sidepanel-template-component).  You can add custom HTML and inline CSS to style the component.

**Comment by cpluceDev** [comment]
thanks for the help. i downloaded your web component and tried to gulp build or package it but ran into a couple of errors. looks promising and very useful.  still new to some of this code development and type script and react.  i have created a few spfx web parts but nothing that uses models and libraries.

**Comment by MakingThingsWorkToronto** [comment]
Great - can we close this one - addressed that issue in the other repo!

**Comment by cpluceDev** [comment]
yes thx
