### ISSUE TITLE
Filter managed properties dropdown is empty for edit refiners  

### ISSUE THREAD

**Issue by ymihir** [microsoft-search/pnp-modern-search#469]
**Version: 3.15.1.0**

When I try to edit refiners for "Search Refiners" web part, blank dropdown is displaying for "Filter Managed Property" option. With default options no filters are displaying.
![image](https://user-images.githubusercontent.com/7568187/92918263-e54de280-f44c-11ea-9861-7e7212b930d5.png)

**Comment by wobba** [comment]
This happens sometimes as it's using an non-document approach to fetch the values. Just enter in what you need manually instead of the dropdown. Also, zoom out, and it's easier to navigate that page as you get more width.

**Comment by wobba** [comment]
Can I close this issue?
