### ISSUE TITLE
Search web part does not translate 'space' betwee searchquery

### ISSUE THREAD

**Issue by dennishaxe** [microsoft-search/pnp-modern-search#47]
**Version used**
3.7

**Describe the bug**
I have the search web part on a empty page and it sends the input to the standard SharePoint result page.

https://********/_layouts/15/search.aspx/siteall?q=

When I search 'Test Test' for example then the result url is https://********/_layouts/15/search.aspx/siteall?q=Test%2520Test

The result of this search is nothing can be found for test%20test

**To Reproduce**
Create a page and add de 'Search' web part. Configure the settings as below: 

Send the query to a new page: https://****.sharepoint.com/sites/zis/_layouts/15/search.aspx/siteall?
Behavior for open: Use existing tab
Method: Searchquery parameter 
Searchquery parameter name: q

Save the page and search for 2 words with a space in between. For example 'Test Test'. You will see the result as:

Their are 0 results found for test%20test. 

**Expected behavior**
Searchresults. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54180234/71807035-addf9880-306a-11ea-9e98-23bca0d686f2.png)

**Desktop (please complete the following information):**
 - Browser = Every browser

**Comment by FranckyC** [comment]
@dennishaxe should be resolved by #63 . Feel free to checkout the develop branch and test.
