### ISSUE TITLE
Filters webpart : wrong order

### ISSUE THREAD

**Issue by lsavard** [microsoft-search/pnp-modern-search#470]
While doing "Edit Filters", you get to specify in which order you want the filters to be displayed.
However, this order is not respected.
Filter with the most values seem to appear first and filter with the less values appear last.
The filters even get reordered when a value is checked to be applied.
Version 3.15.1
Thanks

**Comment by wobba** [comment]
Can you share a bit about the setup?

- Type of filter (number, string, date)
- How you configured the filter

**Comment by lsavard** [comment]
Sure !
More details in the screenshot below. I am using many "RefinableStringXX" filters (with aliases) and the built-in "FileExtension" one.
![image](https://user-images.githubusercontent.com/51333566/93099684-4dcbd800-f676-11ea-9dc9-2582b0e612f3.png)
![image](https://user-images.githubusercontent.com/51333566/93099758-65a35c00-f676-11ea-88ba-322432bde011.png)
Thanks !

**Comment by wobba** [comment]
If you start filling out the column for "sort type" and "sort order" it should help :) I see "sort type" is not set, which means it will do the default from the search back end.

**Comment by lsavard** [comment]
Thanks for the suggestion. I tried to set values to "sort type" and "sort order" fields, but this only affects sorting of values inside each filter. Order of filters themselves is not affected by this setting.

**Comment by wobba** [comment]
@lsavard right.. you want them to show in the order defined. Makes sense.

**Comment by wobba** [comment]
Bug fixed in dev branch as I'm the one who introduced it :)

**Comment by lsavard** [comment]
Woah that was quick :) Great work !

**Comment by cpluceDev** [comment]
yes. thanks. the orders of my refiners were also getting mixed up and need to be addressed. it didnt matter what i had the sort order set to
