### ISSUE TITLE
Refiners translation not working

### ISSUE THREAD

**Issue by MaximeChofardet** [microsoft-search/pnp-modern-search#472]
Hi, 
When I am using searchRefiners in a page.
When testing multilingual with a web browser configured with languages "Italian" or "Portuguese", my filters value (which are mapped to a Taxonomy field) are not translated even if labels have been assigned in the selected language to all terms in the filter.
Could you confirme if missing something ?

**Comment by wobba** [comment]
I assume you checked this one in the result web part?
![image](https://user-images.githubusercontent.com/51104/93098876-a36ca880-f6a7-11ea-9e0d-3f24c9d19001.png)

And followed the guidance at https://microsoft-search.github.io/pnp-modern-search/search-parts/search-results/#miscellaneous-taxonomy-values-dynamic-translation on how to set up a filter value for taxonomy translation?

**Comment by MaximeChofardet** [comment]
Indeed this option have been checked.

![image](https://user-images.githubusercontent.com/36511028/93215453-bb573180-f766-11ea-86b3-460db0104416.png)

I also mapped the managed property RefinableString106 with both crawled properties 
![image](https://user-images.githubusercontent.com/36511028/93215023-2fdda080-f766-11ea-8271-4d050dfaf5cf.png)

I also added all labels in the related termsets (such as Francia for Italian related to the termset Country used for column REFCountry) and i still see refiners in French 
![image](https://user-images.githubusercontent.com/36511028/93215373-9b277280-f766-11ea-8d39-aca20a31e68c.png)

**Comment by MaximeChofardet** [comment]
I also tried to add querystring in my page url the following querystring "ql=1040" to force translation but nothing happen

**Comment by wobba** [comment]
Map only to ows_taxId_name. This is the regular expression used to match for a term:

`L0\|#(.+)\|`

and you should check network trace if you see any taxonomy calls happening to look up the translation.

**Comment by MaximeChofardet** [comment]
Seems to now work correctly for refiners mapped to taxonomy  field  but for boolean ones, I still have values "True" & "False" that are not translated.

**Comment by wobba** [comment]
Boolean refiners are not taxonomy, and we have no explicit translation. There are no explicit RefinableBool refiners so I assume you are using a string. Feel free to log a separate issue for this as an improvement.
