### ISSUE TITLE
link in search results changed from previous version 

### ISSUE THREAD

**Issue by cpluceDev** [microsoft-search/pnp-modern-search#473]
from the prior version i was able to use this for the hyperlink for the title in the search results:
`<span class=""><a href="{{getUrl item}}">{{Title}}</a></span>`

The above was taking me to the proper list item in url which redirected me to this link:
..../DispForm.aspx?ID={{ListItemID}}

when i updated to 3.15 version, the {{get URL item}} now uses this for the link:

 .....list/2280_.000?web=1

This is no good as it produces this. so i had to hard code hyperlink above a dynamically populate listitemID

![errLink](https://user-images.githubusercontent.com/25770942/93135070-57b60100-f69f-11ea-9887-c7960269bff1.PNG)

**Comment by wobba** [comment]
That's a bug and should not affect documents. I'll see if we can do a dot fix release for this.

**Comment by wobba** [comment]
@cpluceDev if you can check the dev branch and see if the logic is better for you know that would be great.

**Comment by cpluceDev** [comment]
i am glad i can help test.  :)  Ill take a look at the branch.

**Comment by cpluceDev** [comment]
as long as the link works for office docs and list items without getting an error page. code changes look good to me. :) thanks for quick turn around.

**Comment by wobba** [comment]
I'll close this for now and thank you for the feedback! I added logic for handling mobile browser specifically as the preview links doesn't necessarily work, and an override for `getUrl` to skip the part trying to generate a smart preview link.
