### ISSUE TITLE
Problem with Right to left Sites?

### ISSUE THREAD

**Issue by Freeway6** [microsoft-search/pnp-modern-search#479]
Hello,

we have a problem with the refiners results. The refiner Webpart is on an hebrew site, which has a master page that is right to left written. The refiner results are not displayed correctly.
![image](https://user-images.githubusercontent.com/11316900/93757870-c1865b80-fc07-11ea-992d-3390554e7bc2.png)
Is there already a fix in the current version?

Version: 3.5.0.0

Best regards

**Comment by wobba** [comment]
Most likely not a fix and don't believe we have tested this particularly. Would be nice if someone did an assessment and possibly a PR to make sure it works.

**Comment by Freeway6** [comment]
> Most likely not a fix and don't believe we have tested this particularly. Would be nice if someone did an assessment and possibly a PR to make sure it works.

I have discovered, that this problem only occurs if the users are using Chrome. With Edge and Internet Explorer this problem doesn´t occur.

**Comment by wobba** [comment]
Closing out as an old issue
