### ISSUE TITLE
Support for deep linking refiners (configuring refiners from the query string)

### ISSUE THREAD

**Issue by rudfoss** [microsoft-search/pnp-modern-search#48]
**Is your feature request related to a problem? Please describe.**
I can't seem to find any documentation on if it's possible to control which refiners are active based on url query parameters (deep linking). Is this possible and if so how would I go about using it?

**Describe the solution you'd like**
Support for deep linking into specific refiners as well as some documentation on how to use it.

**Describe alternatives you've considered**
I've considered building a custom web part to handle this or simply hard coding a search into the results web part.

**Comment by FranckyC** [comment]
Hi @rudfoss. Currently this is not possible. Thank you for the feedback, we will think how to handle this scenario correctly for next releases.

**Comment by rudfoss** [comment]
@FranckyC Thanks for the reply. Any chance of getting a timeline for this feature? Would it be hard to implement as a PR, do you think? I haven't looked at the code much yet.

**Comment by FranckyC** [comment]
It could be depending what we want to support. For now, no timeline for this feature. If you think about a specific schema, please let us know before starting coding and then you could submit a PR once validated.

**Comment by FranckyC** [comment]
Fixed by #116
