### ISSUE TITLE
Unable to control the order of Search refiner filters

### ISSUE THREAD

**Issue by coupalm** [microsoft-search/pnp-modern-search#480]
**Version used**
3.15.1.0

**Describe the bug**
When I set the filters display order in the search refiner (ex: 1. Content Type, 2. Subject, 3. File Type), it does not display in this order in the web part.

**Expected behavior**
Should be displayed in the order speficied in the webpart config.

**Screenshots**
![image](https://user-images.githubusercontent.com/11309224/93779320-d60d2880-fbf4-11ea-91f8-43280c4fe185.png)

**Desktop (please complete the following information):**
 - Edge Chromium

**Comment by cpluceDev** [comment]
there is a fix for that posted in this thread. https://github.com/microsoft-search/pnp-modern-search/issues/470

i just made the code edits in my project and repackaged solution. there might be another way to update your file.
