### ISSUE TITLE
avoid duplicates in people search

### ISSUE THREAD

**Issue by cpluceDev** [microsoft-search/pnp-modern-search#482]
is the a non code / KQL way to remove duplicate people search results. im getting more duplicates with local people search than the classic search web parts. i tried using this but not much info on how to use it. CollapseSpecification

**Comment by cpluceDev** [comment]
they have issues with people search. anyone successfully implemented people search with this web part? and used hover panel with details? i get 5 results (duplicates) with my user profile compared to the search query tool which is 1 result.

**Comment by wobba** [comment]
CollapseSpecification is not hard to use, but not exposed in the web part.

The query is no different using webpart vs search tool. Use the debug template to investigate the output, and see if they are duplicates or other issue.

**Comment by cpluceDev** [comment]
CollapseSpecification  isnt doing anything. seems straightforward KQL. any other options?

**Comment by cpluceDev** [comment]
the docid for the results are different. not sure why. and the query tool shows correct results.

**Comment by wobba** [comment]
Turn off duplicate trimming in the tool :) cause it's not a good feature, I would rather figure out why you have duplicates - check the UPA for example. If you look at the account names I assume they are different? Is this multi-geo?

**Comment by cpluceDev** [comment]
i removed trimming in the search query tool. same correct results. what is UPA?  using debug in webpart: doci ids are differetn but acct names are the same. i havent done anything extra for multi -geo on these webparts but at our tenant level, multi-geo is configured. thx

**Comment by wobba** [comment]
Enable multigeo in the query tool as well...in the extra parameters section. So, seems to be a geo issue and we enable multi-geo by default in the web parts. UPA is the User Profile Application, where you can edit and look at all the profiles.

I'm unsure how indexing of profiles work in multi-geo, but we should be able to fix this somehow.

**Comment by cpluceDev** [comment]
ha  i thought it was UPSA :) 

where or how do i enable multi-geo in the tool?
![image](https://user-images.githubusercontent.com/25770942/94071616-dacf0980-fdb9-11ea-89f3-0e984ab8e878.png)

**Comment by cpluceDev** [comment]
yes sir, you were spot on again. i enabled this in the classic web part and there was my duplicates. 

![image](https://user-images.githubusercontent.com/25770942/94082243-17a0fd80-fdc6-11ea-8623-e03cca5a3c43.png)

**Comment by cpluceDev** [comment]
can we add this checkbox to the pnp search results web part?  and do we have a quick solution i can do before this update? thx

**Comment by wobba** [comment]
Checked internally and I will add a collapsespec on AADObjectID to solve this issue. If you're in a hurry add this in SearchService.ts around line 190.

```
searchQuery.CollapseSpecification = "AADObjectID:1";
```

**Comment by cpluceDev** [comment]
what is the difference between adding that to line 190 and setting this to false?

![image](https://user-images.githubusercontent.com/25770942/94149478-92f1c600-fe3d-11ea-89bf-197bdbde1cb1.png)

**Comment by cpluceDev** [comment]
thx so that will help return unique azure ad objects

**Comment by cpluceDev** [comment]
is this correct? I still see dupes.

![image](https://user-images.githubusercontent.com/25770942/94171135-8332ab80-fe56-11ea-80b4-cf0af0ddd010.png)

**Comment by cpluceDev** [comment]
what would be the impact by settign this to false?
![image](https://user-images.githubusercontent.com/25770942/94171224-a198a700-fe56-11ea-9e46-de9e82601eed.png)

**Comment by wobba** [comment]
The collapsespec you set should in theory help. You may also try `AccountName:1`. If you disable multi-geo it should not matter for people, but it will matter for content if spread across your geo.

**Comment by cpluceDev** [comment]
ill test the accountname:1 setting. the geo setting to false shouldn't be an issue as we currently dont have this enabled on our other classic search results web parts.

**Comment by brianpmccullough** [comment]
Is this still open? I am facing same issue (duplicates on multi-geo People Search). If anyone hasn't already started it, perhaps I can have a peek and see if I can get a fix in?

**Comment by wobba** [comment]
Latest v3 has a toggle for multi-geo. Not in v4 yet. You can work around it by using a path filter as well.

**Comment by brianpmccullough** [comment]
Can confirm that Path filter appears to work as a workaround for this on People.

Path:https://[tenant]-my.sharepoint.com
