### ISSUE TITLE
Select result layout based on vertical selected

### ISSUE THREAD

**Issue by kristianbkjaer** [microsoft-search/pnp-modern-search#483]
This a feature request.
When using search verticals a use case is often to create a vertical per content type, e.g. "Pages", "Files", "People" and so on.
Most often results for each content type are best shown in a specific layout, e.g. you would render a file result differently than a page or people result.
Today you can implement different layouts using a managed property filter, however, often you actually don't want to mix different layouts in a single result view.
A solution is to let the layout choice in the search result web part be picked from the verticals web part. Just like the query template today which becomes inactive when connected to search verticals web part. On the search vertical web part it should then be possible to select the desired layout for each vertical.
When the result web part renders the result it should use the layout from the selected vertical.

**Comment by Georg-Trixl** [comment]
Yes that is a popular feature request.
One way to solve that could be, that you use verticals which have a redirect URL configured, so you would have a separate Page with a different standard layout of the PNP Modern Search.
The other option we did choose was to write custom templates for the search results with many "Result Types" - so on the people vertical the only returned Result Types from are People and those results are handled by our custom People "Result Type"

I also posted change requests like you proposed, but in the end, we are more happy with the custom code solution. To have different layouts per vertical out of the box, would just have been a starting point for us. To implement a solution that could do different layouts per vertical, is also development effort, which isn't that small.

**Comment by kristianbkjaer** [comment]
Thanks for the suggestion. I actually investigated option 1 you propose, but It's not good as clicking the link vertical goes to the page but does not carry the search query from the search box. Also to make the page shift transparent I would use the same vertical web part inserted with the same verticals, which should then be all links to different search pages (setup with same web parts but different layouts). However, then the problem is there is no way to select default vertical on a page, which would be needed to make it smooth.
It's unfortunately a show stopper for us so I'll stick with our current custom built modern search. But I hoped I could switch to this community based solution (to lower dev costs ;)
I'll give it some more time to mature, because actually I'm quite impressed with the progress since I saw it first in Prague last year.
(Or I'll start contributing to development myself?) :)

**Comment by Georg-Trixl** [comment]
Okay to get a "premium feeling" search out of the PNP Modern Search, you need anyway a developer.
The other option is, that you are just simple satisfied with the out of the box features - which are already a amazing job.

Besides verticals can be preselected via URL parameter (see docu about vertical webparts).
use the **Default vertical querystring parameter** for example query string parameter is **v**
then you have in URL **?v=People** (if already something has a **?** in the URL then you have **&v=People**)
then the page loads preselected the People vertical

**Comment by kristianbkjaer** [comment]
Yes, agree, but it's really nice to be able to get 80% of the way "for free". Actually I think these web parts should an official MS offering. Without these or custom development we are pretty much left in the dark regarding a good search experience...
I tried to use the "Default vertical querystring parameter" but could not get anything useful out of it. And it is not documented - I think it is fairly new. I'll give it another go then...

**Comment by Georg-Trixl** [comment]
In the company where I work, we have pretty good solution with these webparts deployed.
We had to put many developer hours in it to get it up and running as desired and it was necessary to read many of this entries here and also the source code ....

**Comment by wobba** [comment]
You can use Result Types with a filter matching your vertical filter to have different templates per vertical. See the sample solution at  https://github.com/microsoft-search/pnp-modern-search/releases/tag/pnp-template which employs this. Template code over at https://github.com/SharePoint/sp-dev-provisioning-templates/tree/master/tenant/ModernSearch
