### ISSUE TITLE
Thumbnail Support in Search Results for newer file types

### ISSUE THREAD

**Issue by dirkzwart** [microsoft-search/pnp-modern-search#484]
This is a great plug-in, thank you for all the work that has gone in to it. I have noticed however that the search on a modern page will display thumbnails in the search results for newer Adobe PDF documents (those saved in Adobe version 1.5 - Acrobat 6.x), but the PNP Modern Search only shows a pixelated icon. The PNP Search does show thumbnails for older PDF documents (those saved in Adobe version 1.4 - Acrobat 5.x).
SharePoint Default Search Result with Thumbnail:
![sharepointsearch](https://user-images.githubusercontent.com/71520279/93888278-67d86c80-fcad-11ea-96b9-1b7c696d8d58.png)
PNP Modern Search with icon:
![PNPmodernsearch](https://user-images.githubusercontent.com/71520279/93888408-97877480-fcad-11ea-9090-62913a2cbcbd.png)

**Comment by wobba** [comment]
Do you have a sample pdf? Backend wise it should be the same logic, and can you share which version of Modern Search wp you are using?

**Comment by dirkzwart** [comment]
Mikael,

Thanks for reaching out. I am using the latest version of Modern Search (I
installed the package last week). Please find attached the PDF I was using
for testing.

Cheers,
Dirk

**Comment by wobba** [comment]
Don't see an attachment?

**Comment by dirkzwart** [comment]
[infographic_steps_to_securing_elections_04-10-20.pdf](https://github.com/microsoft-search/pnp-modern-search/files/5293773/infographic_steps_to_securing_elections_04-10-20.pdf)

**Comment by wobba** [comment]
Using simple list with the newest build and seems to work as expected.
![image](https://user-images.githubusercontent.com/51104/94559894-2eca6a00-0262-11eb-8f2a-356ac56f0ac2.png)
