### ISSUE TITLE
Metadata Tag Spacing

### ISSUE THREAD

**Issue by dirkzwart** [microsoft-search/pnp-modern-search#485]
A suggestion for the future display on tags. Currently it does not appear that spaces are placed between tags and that long tags word wrap. I propose a space between tags and no word wrapping. If there are more tags/space required than fits on one line, wrap the tags to the following line.
![tagspacing](https://user-images.githubusercontent.com/71520279/93888552-c7367c80-fcad-11ea-9fd4-1440b9b20fec.png)

**Comment by wobba** [comment]
Fixed in v4.4
