### ISSUE TITLE
in Refiners only 100 Results are coming what to do if i need to have those results which are there in refiners but not shown in first 100 resutls

### ISSUE THREAD

**Issue by Asfandtnt** [microsoft-search/pnp-modern-search#487]
First of all let me say this its brilliant product undoubtedly 
and base on your previous release we choose to configure it for our SharePoint Online Search.

but today we found a show stopper for us ...kindly see if you can come up with a solution.

in Refiners only 100 Results are coming what to do if I need to have those results which are there in refiners but not shown in first 100 results.

**Comment by Georg-Trixl** [comment]
This is the same as Enhancement #445 this should be closed.

The filters are sorting the filter item with the most hits on the top.
So when you say that you need excatly the items above the first 100, then you with other words also not "that" popular stuff.
In normal document / pages search, filter items which are over the 100 limit are usually not the thing that leads to an successful reuslt.
I can also understand if you search for data of an custom built solution, where SharePoint partially serves as database, it could make sense to have more filter items in place than the 100 items.

A work around would be, to create verticals. One verticals deals one half of the filter results, the vertical deals with rest of the filter items. Coming from classic search, it was always a strategy to slice content in different segments either by verticals or by use of refiners, to get to the nitty gritty of the desired search result.

**Comment by wobba** [comment]
This is in the dev branch. Set the max to 50.000.

**Comment by DiHendriks** [comment]
Hi @wobba, 

is this still in the dev branch to set it to 5.000 ? Or is it all closed based on the comment from @Georg-Trixl ?
Saying it it not in the toplist and not being important is not right when you deal with hardware or software components. Making a vertical is nice but getting a bigger list than 100 is needed for the engineers as requested in [445 ](https://github.com/microsoft-search/pnp-modern-search/issues/445)

**Comment by wobba** [comment]
Should be in the .2 release I believe.
