### ISSUE TITLE
using component properties without escaping

### ISSUE THREAD

**Issue by NewUser29** [microsoft-search/pnp-modern-search#488]
Hello,
I ran PnP code through a share point security scanner and received the following security rule violation:
"Do not use component properties without escaping". The link below describes the issue in details and provides a possible solution. Has anyone encountered this error/violation? Is there a workaround other than using the escape() function as described in the link. 
https://docs.rencore.com/spcaf/v7/SPF020802_DontUseWebPartPropertiesWithoutEscaping.html?version=7.7.6.0
Thanks

**Comment by wobba** [comment]
@NewUser29 it would be good if you could point to an exact code line. Also, we sanitize all markup/css to avoid injection before rendering.

**Comment by NewUser29** [comment]
Thanks for the response Wobba. Please see the attached screenshot with the highlighted line of code.
This serves as an example of how the escape() has to be used ( Good practice). The code in 3.10.0 does not use the escape function ( bad practice). Just wanted to get an opinion whether this is a critical vulnerability or if the issue has been fixed in later versions. Thanks 

![Good Practice](https://user-images.githubusercontent.com/71733109/94024166-16031580-fd85-11ea-99e3-81ee655678a7.PNG)

**Comment by wobba** [comment]
I did see the sample, but I'd like to see where it happens in this code - instead of hunting for it :)

**Comment by NewUser29** [comment]
Sorry for the confusion. please see the attached screenshots. 
![1](https://user-images.githubusercontent.com/71733109/94030009-582f5580-fd8b-11ea-8732-17c450b92ead.PNG)
![2](https://user-images.githubusercontent.com/71733109/94030010-582f5580-fd8b-11ea-85d1-41a21858cb66.PNG)
![3](https://user-images.githubusercontent.com/71733109/94030011-582f5580-fd8b-11ea-8972-dd5fe796820c.PNG)

**Comment by wobba** [comment]
And now you can do a PR with proposed fixes :D

**Comment by NewUser29** [comment]
what is PR ? I am not technical person

**Comment by wobba** [comment]
Pull Request :) If you're not a dev, the it's ok.

**Comment by wobba** [comment]
v3 no longer maintained
