### ISSUE TITLE
Working with umlaut in search vertical

### ISSUE THREAD

**Issue by Praios81** [microsoft-search/pnp-modern-search#489]
**Version used**
Ex: 3.15.1

**Describe the bug**
We have a choice column _PublishingType_ that is used in a search vertical. The vertical works good for 3 of the choices. The fourth contains a german umlaut ("Bücher"). We use the following vertical setup:
{searchTerms} PublishingTypeOWSCHCS:Bücher

When the vertical is selected the correct items are shown. Also we see the correct number of results next to the search vertical label. However when another vertical is selected, the vertical only shows "0" as items. As all other verticals work as expected I think that the resolving of the results for a vertical is not working with umlaut characters.

We helped ourselves by using "Buecher" instead of "Bücher" as choice value but that looks odd to German speakers.

**To Reproduce**
1. Set up a column with 2 choices, one containing an umlaut
2. use that column as a search vertical and set up two verticals for the choices
3. Upload items and set up the choices as metadata
4. See the verticals not showing elements (0) when inactive and containing an Umlaut

**Expected behavior**
Verticals should always show the results for the vertical, no matter if containing umlaut or not.

**Screenshots**
![active vertical Bücher shows 92](https://user-images.githubusercontent.com/60870622/93977812-5d84a400-fd7b-11ea-88bf-2ba60ad4bec8.jpg)
![inactive vertical Bücher shows 0](https://user-images.githubusercontent.com/60870622/93977816-5e1d3a80-fd7b-11ea-8897-ebcdd6f4a2e5.jpg)

**Desktop (please complete the following information):**
 - chrome

**Comment by Georg-Trixl** [comment]
Did you already try it with **&uuml;** not Bücher but **B&uuml;cher**?

Bin gespannt ob das funktioniert.

**Comment by wobba** [comment]
@Georg-Trixl what's the difference with those two?

@Praios81 Can you inspect the stored value in the managed property `PublishingTypeOWSCHCS` and copy/paste that one into the KQL filter for the vertical?

**Comment by wobba** [comment]
Closed due to inactivity.
