### ISSUE TITLE
Right side on Site unused

### ISSUE THREAD

**Issue by PeterVos111** [microsoft-search/pnp-modern-search#49]
**Version used**
Ex: 3.7

**Describe the bug**

I have a SharePoint site with One-column layout.
I have Search verticals here, but added so many that some of it is Blanked out.

**To Reproduce**
1. Go to Sharepoint site and add the search verticals
2. Add 10 or more verticals
3. add images and Rowcounter
4. See that part of it is blank or disappears behind the page background

**Expected behavior**
Search vertical using more width, or creating a second row if the width is too great

**Screenshots**
<img width="845" alt="2020-01-06 11_19_40-Zoekcentrum" src="https://user-images.githubusercontent.com/46716165/71812707-30228980-3078-11ea-84cf-730b6e69d783.png">

**Desktop (please complete the following information):**
 - Chrome, but issue persists on all browsers

**Additional context**
I did find out that this is an issue on all SP-sites. i'm looking for a way to show more than 10 verticals, since it is also not poissble to add 2 searchverticals and connect them both to the results.

**Comment by FranckyC** [comment]
Hi @PeterVos111 I see your issue but unfortunately internally we use the Office UI Fabric '[Pivot](https://developer.microsoft.com/en-us/fabric#/controls/web/pivot)' control who, for now, is not responsive. There is already an [issue ](https://github.com/OfficeDev/office-ui-fabric-react/issues/4066) in their repository for this so they are aware of this behavior.
