### ISSUE TITLE
App Monitoring

### ISSUE THREAD

**Issue by Oegl** [microsoft-search/pnp-modern-search#490]
I deployed the PnP Search WebParts solution tenant wide, so that it is available in all Site Collections:

![PnP Search tenant AppMonitoring_001](https://user-images.githubusercontent.com/65904352/93980019-5dd26e80-fd7e-11ea-9193-f593a82e62b3.png)

When I try to add the App to the "App Monitoring", the App is not shown to be selected.
![PnP Search tenant AppMonitoring_002](https://user-images.githubusercontent.com/65904352/93980030-6165f580-fd7e-11ea-940f-7a521e75ca3b.png)

Is it not possible or am I doing something wrong?

Thanks for your support.

**Comment by wobba** [comment]
My best guess is that SPFx tenant wide deployed apps won't show up for this feature. I would check with another app and log this at https://github.com/SharePoint/sp-dev-docs as it's not related to this solution in particular.

**Comment by Oegl** [comment]
Hi!
Thanks for checking - I have other apps, also deployed tenant wide, and they are shown in the Monitor App selection.

**Comment by wobba** [comment]
I've never used the Monitor App feature so cannot really say why it's an issue.

**Comment by Oegl** [comment]
Do you know another possibility to see how often and where the Webparts are used?

**Comment by Oegl** [comment]
Meanwhile I had a check again, and you are right - if the App is "tenant deployed" - the app cannot be added to monitoring. Because in this case - the users have no need to add the app to their site collection. Only apps that are "deployed" via tenant app catalog but not deployed "tenant deployed" can be added to monitoring.

**Comment by wobba** [comment]
You can use my approach from https://www.techmikael.com/2018/05/locating-where-term-set-is-used-in.html with the web parts manifest id :)
