### ISSUE TITLE
Refiners Web Part not working as expected

### ISSUE THREAD

**Issue by gmparky** [microsoft-search/pnp-modern-search#491]
**Version used**
Ex: 3.15.1

**Describe the bug**
I have a search box and a search results web part that is working well, I have added in the Search Refiners based on the search results. I have added some fields that I can see are in the search results but do not show within the refiners although I can clearly see they are in the results

**To Reproduce**

1. Go to 'Search Results, selected the 'Selected Properties' requeired'
2. Click on 'Search Refiners'  and edit refiners to show properties selected.
3. Save 

**Expected behavior**
I expect that the Refiners to show the managed property within the webpart however nothing renders

**Screenshots**
![image](https://user-images.githubusercontent.com/40665509/94002973-82384600-fd92-11ea-9959-09197f5fa63b.png)
![image](https://user-images.githubusercontent.com/40665509/94003002-8e240800-fd92-11ea-8bd3-b31001fd341e.png)
![image](https://user-images.githubusercontent.com/40665509/94003045-a005ab00-fd92-11ea-988c-8877ef93ca8f.png)

**Desktop (please complete the following information):**
 - Browser Chromium Edge

**Additional context**
This is happening for a couple of properties some are for Managed Metadata in the term store another is just a Choice Column within SharePoint.

I am not sure if I am doing something in error or what I am missing.

**Comment by wobba** [comment]
You can only use refinable managed properties in the refiner/filter web part. See https://docs.microsoft.com/en-us/sharepoint/manage-search-schema for information.

**Comment by Georg-Trixl** [comment]
For me refiners works perfect. The managed property must also be of the type **Refinable**

**Comment by ishaisagi** [comment]
Not working for me - I have the same issue as the original poster. 
I added "refinablestring001" to the properties, made sure in debug that it has content in the results web part, but the refiner shows blank.
In edit mode it shows "No available filter to display." which is because "this.props.availableFilters" is always empty.

**Comment by wobba** [comment]
@ishaisagi did you connect the result wp to the refiner wp, and also the refiner wp to the result wp. You need to connect it both ways.

**Comment by Georg-Trixl** [comment]
@ishaisagi if your RefinableStringXX is fresh configured, then also can be empty as indexing of a new confugred RefinableStringXX does take some time

**Comment by wobba** [comment]
@Georg-Trixl there is data, see the screenshot :)

**Comment by wobba** [comment]
@ishaisagi @gmparky is this only happening in Edit mode? If so, I won't prioritize figuring out the data bind sync issue.

**Comment by ishaisagi** [comment]
Mikael, you were correct...the results wp wasn't connected to the filter. Maybe add some instructions on the filter wp's property pane?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gmparky** [comment]
@wobba  apologies for not coming back but we resolved this by setting up the managed properties as you advised via the link.
