### ISSUE TITLE
hover panel for people search results details like classic

### ISSUE THREAD

**Issue by cpluceDev** [microsoft-search/pnp-modern-search#492]
i noticed the classic people search ahs a hover panel that uses the delve profile details. is this functionality avaible for the peopel search? is this easy to enable? i noticed this i nthe debug mode:

      "RenderTemplateId": "~sitecollection/_catalogs/masterpage/Display Templates/Search/Item_Default.js",
can we enable the hover panel display in this web part or would you have to write code in the solution ?

**Comment by wobba** [comment]
Not in a supported manner. See https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/38451154-provide-support-for-livepersonacard-in-3rd-party-s.

It is possible to use it unsupported but you have to figure it out as we cannot officially recommend using this approach.
