### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by harish2425** [microsoft-search/pnp-modern-search#496]
Search Results webpart showing below error message when trying to run  in workbench 

![image](https://user-images.githubusercontent.com/25765541/94301833-1b489780-ff20-11ea-914b-51ff93302946.png)

Below are the configuration settings for the search result app 
![image](https://user-images.githubusercontent.com/25765541/94302011-6367ba00-ff20-11ea-8bd4-50112874d08c.png)

**Comment by prasadregula** [comment]
we are also facing the same issue with 3.15.2. while configuring with Search Box.

**Comment by wobba** [comment]
Happens on new pages and all sites? TR or GA tenant?

**Comment by prasadregula** [comment]
we are facing this issue with workbench. Older versions are working. only the new version we are facing the issue. we are developing some custom template to for the search results. For that purpose we are started the project. while debugging in workbench we are facing this issue. But build and deploy it is working.

**Comment by wobba** [comment]
Local workbench or hosted workbench? And I cannot repro in either. You can also test on a modern page by loading the manifest directly using `?loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js` on the URL.

**Comment by cpluceDev** [comment]
i also get this issue in my hosted workbench. works fine in dev site (this dev site already had a previous old version of this pnp search web part so it was an upgrade) and hopefully it will work with the new production site and new pages which will be all clean and new install.

**Comment by cpluceDev** [comment]
i cant even configure it in local workbench it freezes at this step and need to refresh page. freezes everytime

![image](https://user-images.githubusercontent.com/25770942/94820697-5f2b1900-03c6-11eb-81cf-03a6acdf0c49.png)

**Comment by wobba** [comment]
To be honest I never test in local workbench, as it's sort of useless when it comes to search as you usually need good data when testing. And it seems to work well in the hosted workbench for me, or on a page. So you're saying it fails in a GA tenant, but works in a TR tenant?

**Comment by prasadregula** [comment]
I am facing the issue on Hosted Workbench. How i can fix it?

**Comment by wobba** [comment]
Unsure as I cannot repro your issue.

**Comment by cpluceDev** [comment]
hosted workbench  environment latest release
![image](https://user-images.githubusercontent.com/25770942/95139242-a4867800-0731-11eb-82f7-e204b667ab15.png)

**Comment by cpluceDev** [comment]
this is what i see when testing in hosting workbench with the latest bump version:

![image](https://user-images.githubusercontent.com/25770942/95218011-7187c700-07b9-11eb-9d22-0710d67976ce.png)

**Comment by cpluceDev** [comment]
from hosted workbench with the latest bump version
![image](https://user-images.githubusercontent.com/25770942/95218209-a8f67380-07b9-11eb-8d35-40d9ea36900c.png)

**Comment by henningTheDev** [comment]
I have the same problem with hosted workbench

**Comment by wobba** [comment]
Found the issue, and my mistake. Pushed to dev branch, and will include in next release as it's not a real blocker.
