### ISSUE TITLE
refinabledecimal does not appear to work

### ISSUE THREAD

**Issue by cpluceDev** [microsoft-search/pnp-modern-search#498]
i have a currency field in a list and one of my requirements is to have the $ range as shown below which works for classic refiner. 

![image](https://user-images.githubusercontent.com/25770942/94453438-475d5600-0176-11eb-8c67-da6d488bb315.png)

Can achieve this in the modern filters? as of now i don't even see any options to filter on  (like it isnt even crawled but it is because it works in classic) for filtering but the refinablestring works but the format wont satisfy our needs.

**Comment by wobba** [comment]
@cpluceDev what does it look like if you pick the `Default refinement item` template? And you can manually enter `RefinableDecimal00` in the setup for it to show as long as your query return values in it. 
![image](https://user-images.githubusercontent.com/51104/94561654-9a153b80-0264-11eb-9aeb-9f9ca2a2601f.png)

**Comment by cpluceDev** [comment]
![image](https://user-images.githubusercontent.com/25770942/94580755-e732e680-023f-11eb-86ec-7b664fa110e5.png)

![image](https://user-images.githubusercontent.com/25770942/94580823-fade4d00-023f-11eb-97d7-2ea9fb84c9c8.png)

**Comment by cpluceDev** [comment]
it works in the classic web part as illustrated in fist comment. seems straightforward.

**Comment by cpluceDev** [comment]
refinableint also does not work. the column that is mapped is a currency column type

**Comment by wobba** [comment]
I have to map up some data to see if I can repro.

**Comment by cpluceDev** [comment]
if this helps any, i will say i have the same options for the refiner templates no matter what the refinable type i have entered for the filtered managed property. in th classic refiner web part is changes depending on what is selected

**Comment by wobba** [comment]
Found the error - and it's due to the change to bring back more buckets for strings. Working on a fix.

**Comment by cpluceDev** [comment]
thanks so much. i needed this. :)

**Comment by cpluceDev** [comment]
as long as this web part has been in use, I cant believe no one else caught this :)

**Comment by wobba** [comment]
Pushed a fix to the dev branch.

**Comment by wobba** [comment]
Pushed a .3 release with the fix just now.

**Comment by cpluceDev** [comment]
thank you

**Comment by cpluceDev** [comment]
will this give me the range template as illustrated above?

**Comment by wobba** [comment]
It will yes, as it divides results in 4 equal buckets. If you want custom buckets we need to add a setting.

**Comment by cpluceDev** [comment]
I downloaded and isntalled the latest version but

says it is declared but the value is never read.

![image](https://user-images.githubusercontent.com/25770942/95149472-a8bf8f00-074b-11eb-9396-6e2774ae739a.png)

**Comment by wobba** [comment]
There is no need to read it.. I added it for future need. If it's not a date or a string, then default buckets are used.

**Comment by wobba** [comment]
I have this:
![image](https://user-images.githubusercontent.com/51104/95194633-c9342b80-07d5-11eb-8516-afbed4d39cd7.png)
which in 3.15.3 shows as
![image](https://user-images.githubusercontent.com/51104/95194682-d7824780-07d5-11eb-8bbd-496c052c2f56.png)

I left the regex in there in case we need it later, so it's correct it's not in use.

**Comment by cpluceDev** [comment]
anything i can check? none of these are displaying any results.

![image](https://user-images.githubusercontent.com/25770942/95269359-dc0f2600-07fe-11eb-8322-6f8d19113314.png)

**Comment by cpluceDev** [comment]
![image](https://user-images.githubusercontent.com/25770942/95269549-3c05cc80-07ff-11eb-9222-656deb696ea5.png)
![image](https://user-images.githubusercontent.com/25770942/95269585-53dd5080-07ff-11eb-84b3-753694dbd045.png)
