### ISSUE TITLE
Override/filter default search query results with search keyword results

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#499]
**Is your feature request related to a problem? Please describe.**
Using a search box and results web part, I can't figure out how to have a default search query overridden by search terms entered.  

**Describe the solution you'd like**
On page load, I'd like to see all results from a default query (say, all docs in a library) and then filter those results based on a search term entered. 

**Describe alternatives you've considered**
I've tried formatting the KQL default search syntax using a wildcard "*", but the results don't change when a search keyword is entered. 

**Additional context**

**Comment by wobba** [comment]
Add search box and search result web part to your page. Connect result web part to search box web part and set a default query. If you enter something in the search box and search, that will override the default query.

![image](https://user-images.githubusercontent.com/51104/94557697-33d9ea00-025f-11eb-8ac1-4ea1ce424163.png)

**Comment by webbrewer** [comment]
Thanks @wobba . I was able to figure it out after fumbling around with different queries in the default query and query template boxes.
