### ISSUE TITLE
Depolyment question to existing pages

### ISSUE THREAD

**Issue by Georg-Trixl** [microsoft-search/pnp-modern-search#500]
Hello!

My goal is to replace "Content Highlight" Webparts with a better configured Search Results Webpart in over 1000 SiteCollections.
I stuck a little bit, because the query "Search query keywords" value is not stored in way, that I can update it programmatically with Powershell. I found out that the query is stored in DynamicDataValues.
Is there a way to add a search result webpart to a existing page and set its "Search query keywords" from powershell?

In the provisioning template it is already solved for new site collections.
I tryed to provision the webparts to existing pages, but everything else on existing pages is lost, is there a way to preserve the old content and get at any place on the page the webpart provisioned?

Thanks for having the time to read that problem entry and specially if you have an answer to it.

**Comment by wobba** [comment]
@Georg-Trixl Something similar to https://www.techmikael.com/2017/11/modifying-query-template-for.html 

`Add-PnPClientSideWebPart -Page "MyPage" -Component "Search Results" -WebPartProperties $json`

You can get the JSON from an existing page/component.

**Comment by Georg-Trixl** [comment]
Thank you very much @wobba for your proposal.
I found the way to do that.

1. As preparation setup a page that serves as model - export the model as provision template
2. Export the "to be updated page" as provision template
3. Replace the old  "Content Highlight" Webparts from the provision template with the "Search Results" Webpart from the provision model
4. Reprovision the updated template

In the provision template are the **DynamicDataValues** accessible- but if I would use PNP PowerShell to operate directly in the Page or Webpart Object It would not be accessible

**Comment by wobba** [comment]
@Georg-Trixl nice.. makes sense. I know dynamic data works in a complete template, but haven't tried to set it my adding just one webpart.

**Comment by Georg-Trixl** [comment]
@wobba Thanks. I already did the code job and it works as expected. Have a nice day.
