### ISSUE TITLE
Result Type Template not always loading?

### ISSUE THREAD

**Issue by rgraley** [microsoft-search/pnp-modern-search#501]
**Version used**
Ex: 3.12.1.0
{890AFFEF-33E0-4D72-BD72-36399E02143B}

**Describe the bug**
We have a Search Results web part with 1 to many result sources; however, the display templates don't always show up when entering the page or when selecting a search vertical.  If the page is refreshed the display template does work sometimes; but it isn't consistent.  It seems to happen in both Edge (Chromium) and Chrome. Is this a known bug or a configuration on my end that needs to be tweaked?

NOTE:  the External Template URL is in a document library in another site collection configured as a public Assets Library

**To Reproduce**
1. Go to Search Results Web part
2. Click on Edit Result Types
3. Add 1 or more Result Type conditions
4. Provide the External Template URL
5. Click Save

View Results

**Expected behavior**
I would expect to see results using the appropriate external template at all times

**Screenshots**
The screen shot shows the unexpected results on the left and the expected results on the right.  This seems to happen intermittently and without reason.  It also happens on all external templates not just a particular one.

![external template](https://user-images.githubusercontent.com/69590808/94710388-cc7e7180-0314-11eb-8253-8f5821c50995.png)

**Comment by wobba** [comment]
Do you see any errors when it happens? And does it happen if you embed the template into the web part instead of referencing a file? And you can reproduce it on multiple site collections? Is the template loaded via direct SP URL or via CDN URL?

**Comment by rgraley** [comment]
Thanks for the response, here are my answers
Do you see any errors when it happens? **Outside of the developer console I do not see any errors.  Is there another place errors are logged?  Still learning the web parts.**

And does it happen if you embed the template into the web part instead of referencing a file? **I did embed the template into the inline template field and it appears to be working without issue in the short span of testing.**

And you can reproduce it on multiple site collections? **Yes, every site collection we use the Search Results pointing to an external template gives the same action.**

Is the template loaded via direct SP URL or via CDN URL? **We are not using a CDN URL. We are using either the Copied URL from SharePoint Online Library**
**https://XXXXX.sharepoint.com/:u:/r/sites/company_assets/result_templates/Result_Type_Policies.htm
or a direct URL 
https://XXXXX.sharepoint.com/sites/company_assets/result_templates/Result_Type_Policies.htm**

**Comment by wobba** [comment]
I would not use the :u/r notation, and I'll see if I can repro this.

**Comment by rgraley** [comment]
I'm not in a position to upgrade to the new release at this time with our delivery date being in a couple of months.  I am happy to do a teams meeting to show what we are experiencing, share templates which may be incorrect.  This really shows up when there are multiple Search Results Web Parts on the same page even if they are named differently.

**Comment by wobba** [comment]
My page is on a separate site. I point to URL https://tenant.sharepoint.com/SiteAssets/template.html, and it loads fine when switching pages and verticals. Both with cache enabled and disabled. Tested in Edge (chromium). Every switch I see the file loading in the network tab with 200 or 304 depending on cache.

**Comment by rgraley** [comment]
I appreciate you looking into this.  My only thought is perhaps my external templates are incorrectly formatted.  Would it be possible to get a copy of the external template you used so I can compare them to mine (I'm sure mine could be better)?  

We have seen much better response in the one web parts where the templates were put inline. I have attached my result type templates.    Again thanks for your efforts.

[Result_Type_Applications.txt](https://github.com/microsoft-search/pnp-modern-search/files/5371041/Result_Type_Applications.txt)

Expected Results
![application template](https://user-images.githubusercontent.com/69590808/95856334-dc8c4d00-0d27-11eb-973b-126247502e5d.PNG)

Intermittent Results
![application template2](https://user-images.githubusercontent.com/69590808/95857494-afd93500-0d29-11eb-9609-2e458b96a59f.PNG)

**Comment by wobba** [comment]
```html
<style>
    /* Insert your CSS here */
</style>

<div class="template_result">
    <pnp-fabric-icon data-file-extension='{{IconExt}}' data-image-url='{{SiteLogo}}'></pnp-fabric-icon>
    <div class="template_contentContainer">
        <span class=""><a href="{{getUrl item}}">{{Title}}</a></span>
        YOYO
    </div>
</div>
```

**Comment by rgraley** [comment]
I corrected all of the external templates and was hopeful it would work.  I ensured all URLs are using direct URLs to the files and not the notation URLs.  But it still occurs.  The page loads, all external templates are loaded (304 status codes), the results are displayed, the search vertical counts are updated but the external templates are not applied...UNITL the user clicks one of the search verticals (any one of them).  Once the first search vertical is chosen then ALL of the external templates for all the search verticals are displayed as expected.  It seems to be some sort of loading.  I tried Control F5 to get a fresh copy of the page and all external templates were loaded with (200 status codes) however the templates were not applied UNTIL another search vertical was selected.  From that point on while on the page they work consistently.  It appears it may be user error, but not sure what to do next.  We may have to put the code inline; but there are so many pages we are using these web parts it will be a lot of rework.

**Comment by rgraley** [comment]
I think I have found the issue.  It was an issue in the templates.  I was not correctly loading the icon on each template.  There was no issue with the web part.  Thanks for all the assistance.

**Comment by wobba** [comment]
Awesome!

**Comment by rgraley** [comment]
Mikael,

I see the v3 search we a parts are being depreciated, but We are not ready
to install v4 yet.  I identified the issue I am having with the display
templates not showing.  Actually it isn’t the result type templates at
all.  The actual issue is in the Search Vertical & Search Results
connection.  The templates do not load properly if a Query is provided in
the search vertical query template.  As soon as I add something other than
{searchTerms} in the query template the templates do not load.  So
{searchTerms} works
where
{searchTerms} managedProperty:”value” does not.  Any thoughts?

**Comment by wobba** [comment]
@rgraley Can you please log a separate issue with your exact experience and repro steps. As long as someone contributes we will keep fixing issues in v3 and release it. But not adding new features.
