### ISSUE TITLE
Possible bug for count on for search verticals

### ISSUE THREAD

**Issue by cpluceDev** [microsoft-search/pnp-modern-search#502]
my initial setup had the count displaying on all vertical tabs. no matter what search vertical was selected. ever since i removed the search results web part and re-added it. now the count only displays for the search vertical that is selected.  all my config and settings are the same. my question is how is the vertical count suppose to be display? 
thx

**Comment by wobba** [comment]
It's a batch call which should fetch the count for all verticals in one call. Do you see anything weird on the REST call or in the console? Added a vertical + result wp to test now and I do see counts on all verticals in the default setup.

**Comment by cpluceDev** [comment]
i have this in the console
![image](https://user-images.githubusercontent.com/25770942/94824765-fdb97900-03ca-11eb-9b1c-08df5e385e47.png)

did a glance in fiddler and done see any errors

**Comment by wobba** [comment]
Can you share some of the setup as I cannot repro.

**Comment by cpluceDev** [comment]
yes, when i get chance ill share my setup

**Comment by cpluceDev** [comment]
![image](https://user-images.githubusercontent.com/25770942/95222577-3fc52f00-07be-11eb-9745-eb69b7aaff6e.png)
![image](https://user-images.githubusercontent.com/25770942/95222602-48b60080-07be-11eb-91a7-26fef7a91a98.png)
![image](https://user-images.githubusercontent.com/25770942/95222640-510e3b80-07be-11eb-83b4-e6b4d9f79c36.png)
![image](https://user-images.githubusercontent.com/25770942/95222698-62efde80-07be-11eb-8438-a2ca824bd46f.png)

and search results is connected to verticals and filters

**Comment by wobba** [comment]
![2020-10-09_16-18-31](https://user-images.githubusercontent.com/51104/95594401-27b60f80-0a4b-11eb-886c-89f91f006e58.gif)

Numbers do vary which is expected as they are not exact, but I have numbers for all. This is with the latest code.

**Comment by cpluceDev** [comment]
the numbers will vary yes, i use to see them all at once but now i have to go to each vertical to see the count. 

this is the behavior tested on 3 different site collections with their own app catalog. i also have the very latest version as i needed the fix for refinable decimals :)

**Comment by FranckyC** [comment]
Hi @cpluceDev, could you inspect the REST calls in the console and compare search parameters? Counts from search results and verticals don't use the same API call. To get count from search results, we use a POST request but for verticals we use a GET requests (to be able to batch it). Normally the two requests have the same search parameters but depending of your setup, it could different explaining why you get 0 results for veticals. Do you have any query rules activated or other similar options set in the Web Part?

**Comment by cpluceDev** [comment]
thx.  ill check when i get some time. ran into a more critical issue now with this web part conflicting with the Microsoft search when suing side by side.
