### ISSUE TITLE
failed to load component

### ISSUE THREAD

**Issue by cpluceDev** [microsoft-search/pnp-modern-search#504]
![image](https://user-images.githubusercontent.com/25770942/94829747-7838c780-03d0-11eb-8f5e-e58a130157ee.png)

do i need to:

1. gulp clean
2. gulp build
3. gulp bundle --ship
4. gulp package-solution --ship

to fix this. it was working and now after a small code change it is trying to access resources from localhost

![image](https://user-images.githubusercontent.com/25770942/94830429-2d6b7f80-03d1-11eb-91b2-0e4f58e6b9d6.png)

**Comment by Saroj48** [comment]
Did you get any solution? If yes, please let me know
