### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Christian-Stahl** [microsoft-search/pnp-modern-search#505]
Hi, I hope this is a way to ask a question. 

I just wonder if it is possible and supported to write an if statement in a result template? What I'm looking for is something like this:

{{#if(RefinableString00 == "Yes")}}<div>YES</div>{{/if}}

You know, in the old good display templates the sytax was for example... 
var likesCount = ctx.CurrentItem.LikesCount;
if (!(likesCount > 0)) {
likesCount = '0';
}

Any way to

**Comment by wobba** [comment]
Sure. Look at some of the oob templates (pick one layout and click {} beside the custom option and it will copy the last selected into the custom editor) or Google on handlebars and handlebars helpers 🙂

**Comment by Christian-Stahl** [comment]
Thanks, yes I have tried to found a samle syntax for this in the templates, I do also have googled on handlebar conditions, but not luck so far. What I try to do is this... Lets say I've got a list with a custom column called color, and it's a choice with two values (Red and Green), I had mapped this crawled prop to a lets say RefinableString00. Then, what I want to do is:

{{# if (RefinableString00 == "Blue") }}<p>Blue</p>{{/if}}
{{# if (RefinableString00 == "Red") }}<p>Red</p>{{/if}}

Any hints for me? Thanks in advance

**Comment by wobba** [comment]
https://github.com/helpers/handlebars-helpers#eq
https://docs.brightspot.com/4.2/en/theme-guide/templating--handlebars-/helpers.html

**Comment by Christian-Stahl** [comment]
Ok, I see - handlebar uses eq.. I was looking for IF-statements. It works now, thanks!

{{#eq RefinableString03 "Yes" }}<p style="color:red">{{RefinableString03}}</p>
{{else}}
<p style="color:green">{{RefinableString03}}</p>
{{/eq}}

**Comment by wobba** [comment]
Takes time to learn new frameworks 🙂
