### ISSUE TITLE
Selecting search refiner option generates error

### ISSUE THREAD

**Issue by McBamm** [microsoft-search/pnp-modern-search#506]
**Version used**
Ex: 3.14.1.0

**Describe the bug**
Run a search on document library content and returning All items successfully (i.e. 7500+ item).  When selecting search refiner option the refiners are removed from the page and the following error generated.

![image](https://user-images.githubusercontent.com/72252669/94912394-80ac0380-049f-11eb-92df-4136ea375de5.png)

Using a search vertical to refine the results to a smaller results set ( i.e. 100 items) rebuilds the refiners and the allows the affected search refiner option to be used to filter the search results.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create search results for document library;
2. Connect a search refiner web part and include a refiner for Modified By (based on a RefinableString mapped to crawled 
    properties ows_ModifiedBy and ows_Modified_x0020_By);

![image](https://user-images.githubusercontent.com/72252669/94912975-5a3a9800-04a0-11eb-9fa1-b7a8103c9c3d.png)

3. Enable search verticals for All results and Edited within last 7 days ({searchTerms} AND LastModifiedTime>={Today-7});
4. Complete search for 100+ items and attempt to refine by Modified By, refiners will generate error;
5. Switch to  Edited within last 7 days vertical, refiners will rebuild;
6. Now able to refine by Modified By;
7. Switch to All vertical, refiner will persist and will display all users recorded as modifying items.

**Expected behaviour**
Able to run search and the filter results using Modified By refiner, refiner to return same behaviour across all search verticals.

**Desktop (please complete the following information):**
 - Browser: Chrome 85.0.4183.121 (Official Build) (64-bit) 

**Additional context**
Oddly using the search vertical to rebuild the Refiners and the Modified By field appears to append to the Modified By list rather than rebuilding this.
![image](https://user-images.githubusercontent.com/72252669/94914159-66275980-04a2-11eb-8c64-191cadecd84e.png)

**Comment by McBamm** [comment]
Some more troubleshooting on the site involved:

1. Switching the refiners display type from "Default refinement item" instead of "Persona" works around the issue for the field 
    involved i.e. the refiners work as expected on first use;

2.  The document libraries metadata is far from robust for example authorship by "Joe Bloggs" has been assigned to the users 
     items as: Bloggs, J A Bloggs and Joe Bloggs.

**Comment by wobba** [comment]
If you read the release notes of v3.15 you see there were fixes to the persona template for refiners.

**Comment by McBamm** [comment]
*facepalm* I missed that issue (#422) completely when I first checked the release notes...Thanks!
