### ISSUE TITLE
PNP Modern Search Webpart - filter results based on column value of a library

### ISSUE THREAD

**Issue by Namrata99sah** [microsoft-search/pnp-modern-search#508]
I'm using PNP modern search web part i.e. search box and search results web part. I want to get a search result based on one single library. There are two cases here user search based on the 'Title' column or 'CaseNumber' column of the library. How can I format the KQL query to achieve this?
Currently, the Query template is : {searchTerms} (ParentLink:{/LibraryName/} AND (ContentTypeId:{0x01234*}

There are few columns which contain related list item i.e. custom column to relate one item to another. For eg, If the user search with ID - 1234, it returns 2 results, one the item itself and 2nd the related item as it searches in the whole library.

OR, if there a way I can exclude the column from the search using any filters etc.

**Comment by wobba** [comment]
You can use:

`path:https://contoso.sharepoint.com/sites/site/Lists/MyList` + the contenttype. If there are columns you don't want to be searchable you can set the column to be excluded from indexing. Programatically there is a property on a field named `NoCrawl` which you can set.

You can also target columns specifically with:

`Title:({searchTerms}) OR CaseNumber:({searchTerms})`

**Comment by Namrata99sah** [comment]
So, as a whole, can I write - 
(ParentLink:{/LibraryName/} AND (ContentTypeId:{0x01234*})) AND (Title:({searchTerms}) OR CaseNumber:({searchTerms}))

**Comment by wobba** [comment]
You can :)

**Comment by Namrata99sah** [comment]
For upto how many columns will it work? I tested for 2 and it worked but if
I add any more it doesn't seem to work.

**Comment by Namrata99sah** [comment]
@wobba Please help

**Comment by wobba** [comment]
Crafting KQL is outside the scope of the web part itself, so another forum is probably better.

**Comment by Namrata99sah** [comment]
Is there a way I can apply if-else kind of condition in the query or
exclude few columns from coming into the search..NoCrawl will affect the
search outside the webpart so can't apply this.

Upto how many columns can I keep in the above query? Is there any
limitations on multiline columns?

**Comment by wobba** [comment]
KQL has a max limit of 2048 characters. Depending on your setup ypu can map the crawled properties of your columns to a managed property, and query this property only. Make sure to use a managed property which is searchable and queryable so as not to break regular search on these columns. May I close the issue, as your questions is outside the scope of the web parts.

**Comment by lokeshumapathy01** [comment]
Can we show single line of text column in search refiner?
