### ISSUE TITLE
best way/method to get latest updates in branch

### ISSUE THREAD

**Issue by cpluceDev** [microsoft-search/pnp-modern-search#509]
git pull isnt working for me.

git pull https://github.com/microsoft-search/pnp-modern-search.git

fatal: Not a git repository (or any of the parent directories): .git

i thought you use this the same as git clone

**Comment by wobba** [comment]
First you clone, then you pull. Closing as your issue is related to learning git, not the web parts.

**Comment by cpluceDev** [comment]
i figured it out.  

thanks sorry about that but not sure why i had to do a git init on this repository and others i did not. get pull worked right from the start after i git clone of course :)
