### ISSUE TITLE
Search Results WebPart: KQL query does not support optional querystring parameters?

### ISSUE THREAD

**Issue by mk0023** [microsoft-search/pnp-modern-search#512]
**Version used**
3.13

**Describe the bug**
The search result Webpart allows to enter a KQL query. It seems using optional query string parameters in the form of 

> {? AND Title:{QueryString.Title}}

is not working here (as it used to in the classic search results webpart). Maybe this was a deliberate decision and therefore is not a bug?

**To Reproduce**
Configure search results WebPart as shown in the following screenshot:
![image](https://user-images.githubusercontent.com/72552424/95449933-c0725f80-0965-11eb-8756-23a2f3b04a0a.png)

**Expected behavior**
The condition "AND Title: " should not be present in the resulting queryModification as the query string does not contain a parameter "Title".

**Comment by wobba** [comment]
As `QueryString` is a custom implementation in the web part this is expected as we haven't implemented `\` `|` `?` support. Until someone adds this support I'll try to update the docs on this specific point.

**Comment by mk0023** [comment]
Thank you very much for the fast reply & clarification: Good to know that I am not doing something wrong but that this functionality just was not implemented yet.

**Comment by mahmoudhamed** [comment]
@mk0023 But I think that "AND Title:" will not change the result by any means if I am not mistaken, as you cant search for null value anyway so I think it will give you the same result as if it's not there.

**Comment by mk0023** [comment]
@mahmoudhamed: Unfortunately that is not the case, the added "AND Title:" leads to no results in my case. When removing it I get the expected results.

**Comment by mahmoudhamed** [comment]
Ah, okay in my case when I type it the query directly it doesn't matters. But good to know!

**Comment by mk0023** [comment]
Yes I think when typing directly into the searchbox it removes empty parameters before submitting the query to SharePoint.

**Comment by wobba** [comment]
v3 no longer maintained
