### ISSUE TITLE
[Question] - Full image size

### ISSUE THREAD

**Issue by Christian-Stahl** [microsoft-search/pnp-modern-search#513]
Hi there, I hope this is a ok way to ask questions.

What I need to do is to display news pages with help of the search result web part. Everything works great, how ever I need to get the full size of the news page title image. The only option I can find to get the image is with this helper:
{{getPreviewSrc item}}

Is there a way to get the original image path with it's size or a larger preview src perhaps? I have looked for this in the Debug template layout, but I can see that it's not there.

Thanks for a great web part PnP team!

**Comment by wobba** [comment]
You can pull the `PictureThumbnailUrl` and change the dimension properties. Change `c400x99999` part to `c99999x99999`. See https://docs.microsoft.com/en-us/graph/api/driveitem-list-thumbnails?view=graph-rest-1.0&tabs=http#requesting-custom-thumbnail-sizes for documentation. If you pick a dimension you know is larger than the max you should in theory get the original.

https://contoso.sharepoint.com/_api/v2.1/sites/contoso.sharepoint.com,945b013d-3568-4f98-bfe3-f1f3e3f76289,a16bd9fc-c7dd-447a-9048-3f0b0a656691/items/3d5bdbb8-3ad5-4cd9-a741-5dd49d1a0e9b/driveItem/thumbnails/0/c400x99999/content?preferNoRedirect=true

**Comment by wobba** [comment]
Try to wrap a string replace function around it https://github.com/helpers/handlebars-helpers#replace

**Comment by Christian-Stahl** [comment]
Ok great, I see. I'll try with this. Again, thanks and have a great weekend!
