### ISSUE TITLE
Lack of documentation regarding search-query-enhancer

### ISSUE THREAD

**Issue by MaximeChofardet** [microsoft-search/pnp-modern-search#514]
Lack of documentation regarding search-query-enhancer : 

- [ ]  Impossible to find the architecture to set 
- [ ]  Impossible to know how to activate/ show the section «Search Query enhancement » in search box webpart.
- [ ] Impossible to understand all the interactions between Azure resources such as (Apps LUIS /  Bing Spell Check / Text Analytics / Azure Function) 
.
Is it possible to have more details about those topics ?

Thanks in advance,

**Comment by wobba** [comment]
Can you be more specific what is missing at https://microsoft-search.github.io/pnp-modern-search/search-query-enhancer/getting-started/ ?

**Comment by MaximeChofardet** [comment]
First of all when directly deploying the sppkg package from June or September release, I can't see the section dedicated to the search query enhancement.
I only got this  : 
![image](https://user-images.githubusercontent.com/36511028/95718204-6841a300-0c6e-11eb-8ecc-ac813b9a3bac.png)

I am missing from steps ?

**Comment by wobba** [comment]
There's a button "Configure Suggestions", which should list the providers available. I haven't tried this option myself, and maybe someone wants to PR on updated docs.

**Comment by MaximeChofardet** [comment]
The button "Configure Suggestions" (which is only activated once the extensibility library is deployed) is, to my knowledge, only for addind a list of suggestions and is used in our case to provide suggestions according to page context langage. Not sure to enable NLP with this section.

**Comment by MaximeChofardet** [comment]
After few searches in the history, it seems that the option has been removed since release https://github.com/microsoft-search/pnp-modern-search/releases/tag/3.11.1.
Could you please confirm that this option is still available (even through code if the option has been removed from webpart property panel)

**Comment by wobba** [comment]
Did you follow https://microsoft-search.github.io/pnp-modern-search/search-extensibility-library/getting-started/, and then have that call your `search-query-enhancer` project? The query enhancer project is what ties in whatever module you create.

**Comment by MaximeChofardet** [comment]
Great that reassures me 
Yes I followed every steps of this page. 
I also followed each steps of https://microsoft-search.github.io/pnp-modern-search/search-query-enhancer/getting-started/
What is missing me now is **how** to set or declare my search box to trigger the Azure Function which will allow me to communicate with the Azure Cognitives Services.
I well understood with the settings in the panel before March version but with next releases, I really think it's missing some steps to integrate NLP (and so Azure Function) via the Query modifier.
Possible to have more ressources / samples o this topics ?

**Comment by wobba** [comment]
Took a look, and you have to re-implement that part in the library yourself. So you're pretty free to figure this out.

For v4 we want to have more flexibility on providers, and have the provider/library also be able to support exposing custom configs. There is currently no timeline.

I'll update the docs around you having to re-implement calling the NL function yourself.

**Comment by wobba** [comment]
v3 no longer maintained
