### ISSUE TITLE
Documents are opened in client in Simple List

### ISSUE THREAD

**Issue by schoier** [microsoft-search/pnp-modern-search#515]
!! Check existing issues before logging new ones !!

**Version used**
Ex: 3.15

**Describe the bug**
When using the result layout "Simple list" all documents are opened in client office application (instead of browser) when clicking on the title.
If I change to Details lists, documents are opened in the browser.

**To Reproduce**
1. Configure a search result web part
2. Choose result layout Simple list
3. Click the title
4. The file is opened in client application
5. Switch to result layout Details list
6. Click the title
7. The file is opened in the browser

**Expected behavior**
As in previous versions (at least up to 3.10) I want the file to be opened in the browser when clicking on the title.

**Screenshots**
Simple list:
![image](https://user-images.githubusercontent.com/33417064/95744659-f3815f80-0c93-11eb-8209-49af3fbc4671.png)

Details list:
![image](https://user-images.githubusercontent.com/33417064/95744676-fc723100-0c93-11eb-8f45-08cb17ef8206.png)

**Desktop (please complete the following information):**
 - Browser: Edge, FireFox

**Comment by wobba** [comment]
Fixed in dev branch.

**Comment by HamEv** [comment]
Hi @wobba,

is there a way to open the link in client application? If a set getUrl item with paramter false, the document is opened in browser, when setting the value to 'true' the file is just downloaded.
How can I set the value to force the document opend in Word (Client app)?

Thanks!

**Comment by wobba** [comment]
@HamEv Then you need to add custom logic, and it's operating system dependent as well. See https://stackoverflow.com/questions/37965041/details-of-microsoft-office-url-protocol

**Comment by HamEv** [comment]
@wobba, thanks a lot for the link :-)

**Comment by MaruVC** [comment]
Hi. looks like this changed because i tried List and the file still opens in the browser.
I tried other options  like geturl=false, and web=o and others but still, either it opens on a new tab, or downloads the file, but it does not open the file on client's desktop app.

Anything else i can try?
Thank you
