### ISSUE TITLE
Search Webparts not loading on unmanaged device with web-only access

### ISSUE THREAD

**Issue by sdevreese** [microsoft-search/pnp-modern-search#516]
**Version used**

3.15.2.0
--

**Describe the bug**
Installed the solution in a new app catalog. The tenant has web-only access policy activated for unmanaged devices.
This causes the webparts to not load properly and returns this error:

![95712985-0e3cdf80-0c66-11eb-8ccc-c1c9f6e35f5e](https://user-images.githubusercontent.com/72727150/95827748-70641600-0d34-11eb-8514-cf87690d7503.png)

When working on a managed device, there is no error and we can configure the webparts. So it has something to do with the policy. 
On a managed device, we get the SAME error when using IE for example.

**To Reproduce**
1. Activate policy in SharePoint Admin center

![image](https://user-images.githubusercontent.com/72727150/95828080-ca64db80-0d34-11eb-811b-8602379c77d9.png)

2.. Install Solution in App Catalog
3.. Add webparts to a communication site
4. reload page

**Expected behavior**
webparts should show up and we should be able to configure the webpart properties

**Screenshots**
![95712985-0e3cdf80-0c66-11eb-8ccc-c1c9f6e35f5e](https://user-images.githubusercontent.com/72727150/95827748-70641600-0d34-11eb-8514-cf87690d7503.png)
![image](https://user-images.githubusercontent.com/72727150/95828080-ca64db80-0d34-11eb-811b-8602379c77d9.png)

**Desktop (please complete the following information):**
 - Chrome
- Firefox
- IE

**Comment by wobba** [comment]
This is not related to the web part per say the way I understand it, but generally how SPFx web parts work with policies and setup. The correct place to ask questions around this is at https://github.com/SharePoint/sp-dev-docs/issues.

My best guess is to enable public CDN for SPO, as this will ensure js bundles are loaded from an anonymous URL.
