### ISSUE TITLE
Return results based on the results of a query returning a list of sites.

### ISSUE THREAD

**Issue by sfarq** [microsoft-search/pnp-modern-search#518]
I appreciate that this might not be the place for this, as not sure if this is possible with a standard KQL query.
I want to be able to search within selected set of sites (using a user provided search term), where the scope of the search is limited to a set of sites returned by another query. 
e.g. say i wanted to look for files but only within special set "Active Project" sites. I can use a query (using a managed search property) to return the active project sites list of sites (data from propertybag in the sites), but now i want to essentially set the "path: " managed property for my next query equal to this list of sites...
I cant seem to find a way to do this just with KQL. (If there is a way please educated me! :-) )

**A possible alternate solution**
I was thinking, what if i could create a property on the PNP Search Results WP, that i could set a KQL query that only returned sites, and when set, it would append a "Path:<sitename>" of each returned site urls, to the final query sent to the search service before display the results etc. A bit like a search scope where content is restricted to sites associated with a hub. 

The content within an active project site, does not hold any data about the site type / propertybag data, and therefore cant be used to filter the content, because when set it only returns sites.

If i could build a query, i could just set a results source. 
If i could just use a hub and its restricted scope i would, but the site set i want to search against is dynamic and a subset of all the possible associated sites in the hub.

If the only way to do this is programmatically, i would like to fork the results webpart and add the code directly myself. Although the code is quite intimidating, i would ask to be pointed in the right direction to achieve this goal. 
I would be happy to send it back, if you wanted it. (Although i am sure you would want to sanitise it before inclusion!)

Hope this makes sense.
Simon

**Comment by wobba** [comment]
There's no support to do a two-phase query. If you want to filter on the first result you need that value to be stamped on all items, not just on the site object. The easier solution if you start from scratch is to use prefix on the site URL's matching your pattern,

https://sharepoint.com/sites/prefix-sitename

then you can filter with a path query `path:https://sharepoint.com/sites/prefix*`
