### ISSUE TITLE
Search Result Web Part sometimes bypasses Query Template

### ISSUE THREAD

**Issue by quarterhorse** [microsoft-search/pnp-modern-search#519]
!! Check existing issues before logging new ones !!

**Version used**
3.15.3

**Describe the bug**
When a Search Box passes whitespace to the Search Results web part, the Search Results web part bypasses or ignores the Query Template

**To Reproduce**
1. Have a tenant with several indexed site collections
2, On one of the site collections with indexed content, create a search page adding a Search Box and connecting it to a Search Results web part
2. Edit the Search Results web part setting: the default Search Query to *; Query Template to {searchTerms} Path:{SiteCollection.URL} [This will limit the results to the current site collection]
3. Save and reload the page
4. In the Search Box, press the space bar several times, then submit the query
5. Examine the results and notice that the results are not limited to the current site collection.

**Expected behavior**
The search results conform to the Query Template regardless of the search criteria, to include whitespace only queries.

**Desktop (please complete the following information):**
Minimally, Chrome

**Additional context**
Whitespace only searches probably should not be allowed to be submitted, to include being passed by parameters like the querystring.  It's unclear what value a whitespace only search would provide, though someone could incorrectly submit it instead of a * wildcard, so perhaps if it's whitespace only the search box substitutes it with * or some other default?

**Comment by wobba** [comment]
I cannot repro. Can you use the debug and check what the queryModification look like? Are you using a custom result source, either explicitly or as the default one on the site/tenant which could mess this up.

![image](https://user-images.githubusercontent.com/51104/96758335-ecb2c500-13d6-11eb-8192-ef9af62e6eae.png)

**Comment by quarterhorse** [comment]
I'm not able to reproduce it again across any of the pages I was working on today.  I concur that it's not reproducible for whatever reason.
