### ISSUE TITLE
Service calls in component

### ISSUE THREAD

**Issue by Bhargavikandru** [microsoft-search/pnp-modern-search#52]
Context cannot be passed through the templateContext, By using the context perform the service calls for getting the data of that item.

**Comment by FranckyC** [comment]
Hi @Bhargavikandru, are you talking about custom web components in the extensibility library? In this case, you can use the provided private property `this._ctx` directly in your component class derived from `BaseWebComponent` class:

Ex: 
```
export class MyCustomComponentWebComponent extends BaseWebComponent {
   
    public constructor() {
        super(); 
    }
 
    public async connectedCallback() {
        
       let props = this.resolveAttributes();

       // You can use this._ctx here to access current Web Part context
       const customComponent = <CustomComponent {...props} context={this._ctx}/>;
       ReactDOM.render(customComponent, this);
    }    
}
```

**Comment by Bhargavikandru** [comment]
Thanks @FranckyC, I got the context in the web components.
