### ISSUE TITLE
Search Box Dynamic Data Source for QueryString Parameters Fails

### ISSUE THREAD

**Issue by quarterhorse** [microsoft-search/pnp-modern-search#520]
!! Check existing issues before logging new ones !!

**Version used**
3.15.3

**Describe the bug**
There are several related issues.  

- The drop downs only display the querystring parameters passed to the page as it renders, if the querystring parameters are not present, there's no means to specify any.  An example is creating a search results page that consumes the q parameter.  In order to use the parameter, one needs to specify it on the address line and refresh the page.  I don't see a means to declaratively specify a querystring parameter to use.

- This raises a second issue in that when the page is accessed with a querystring and configured to consume it, if the querystring is not provided on subsequent page renderings, web part rendering fails with the error indicating the querystring parameter is not present.  One cannot edit the web part in this state.

**To Reproduce**

First challenge:
1. Create a modern page.  Give the page a name and add a Search Box web part.
2. Edit the search box web part by checking Use a dynamic data source, Connect to Page environment, Query string as page environment's properties, query parameters as the query string, and try to identify q as the parameter that will be used.

Second challenge:
1. Create a modern page.  Give the page a name and add a Search Box web part, and save the page.
2 Update the URL to include ?q=sometext and reload the page so the querystring is read by the page.
2. Edit the page and assign Q as the parameter.  Save the page.
3. Remove the querystring from the URL and press enter.  The web part displays an error message indicating q is not present. 
![image](https://user-images.githubusercontent.com/36413662/96282256-79f5b400-0fa8-11eb-9839-efbeccbc7595.png)

4. Edit the page and edit the web part.  The web part properties pane will not display.
5. Open a new tab and navigate to the page, edit it, and edit the search web part.  The configured q parameter is not available in the dropdown.  Sometimes this fails, too, with the same error as above.  In this case, add a ?q=testvalue to the URL and press enter to reload the page with a provided querystring.  The same error is displayed.

**Expected behavior**
1. Configuring the search box to consume a querystring parameter should not be limited to only those available to the page during web part editing.  Users should be able to enter any valid querystring parameter name.
2. The search box should render and allow editing regardless of the presence of the querystring parameter

**Screenshots**

![image](https://user-images.githubusercontent.com/36413662/96282857-423b3c00-0fa9-11eb-8369-b4fcf775412b.png)

**Desktop (please complete the following information):**
Chrome

**Additional context**
I was hoping to create a page that was multi-use between being able to be a self contained search/result page along with consuming site collection searches by configuring the new page to be the target for site collection search requests.

**Comment by wobba** [comment]
This is "by design" and part of how SPFx dynamic data works. You need to add the query parameter before you hit "edit" for the page. We could probably handle it with a better error, but you still need to have the query param present for it to work as expected.

**Comment by quarterhorse** [comment]
I'm not sure what feedback is needed.  It sounds as if no action will be taken.  Unfortunately, when the page is being edited, the assigned querystring parameter name is deleted from the settings so it goes into an error condition and if you add the parameter, it's still in an error because the settings are now invalid.

**Comment by wobba** [comment]
I do understand the issue, but you just have to ensure you have the params in the URL when you click edit as I don't think there is a way to handle this. If anyone has a solution we'd happily take it.

**Comment by rachelmarshall** [comment]
So many features are gone in search now.  You can no longer pass parameters in the URL. ie 
/whoswho/Pages/default.aspx#Default={"k":"(EmpFName:Rachel*%20AND%20EmpLName:Marshall*)"}
Not the value is sent between the web parts.

How do you create a custom search box?  so that you can filter on a specific field like first name or last name?
Honestly passing parameters in the URL address is an awesome feature because it can send results to people in emails.  

Everything is so controlled in the o365 environment.

**Comment by rachelmarshall** [comment]
So many features are gone in search now.  You can no longer pass parameters in the URL. ie 
/whoswho/Pages/default.aspx#Default={"k":"(EmpFName:Rachel*%20AND%20EmpLName:Marshall*)"}
Not the value is sent between the web parts.

How do you create a custom search box?  so that you can filter on a specific field like first name or last name?
Honestly passing parameters in the URL address is an awesome feature because it can send results to people in emails.  

Everything is so controlled in this new environment.

**Comment by rachelmarshall** [comment]
Is there a way to change the combox in the refiner web part to a string?

**Comment by wobba** [comment]
@rachelmarshall please don't comment on closed issues. You should log new ones. If it's a bug for v3, log as such, if it's a missing feature with v4, then log as such. Your link alludes to a classic page using classic search parts and is not related to the PnP Modern Search web part project (which do support passing in values).

**Comment by rachelmarshall** [comment]
Yes, I understand this is a classic page.  I am sorry I wrote this here. I don't understand how to remap this to the modern page.  It like we have no control over anything.  So, I need to create a custom solution to be able to search on partial names like first name r* and last name M*. 

I just can't figure out how to customize this in a modern page.

**Comment by wobba** [comment]
It's a matter of how you craft the query template.

Basically you set the **query template** portion of the result web part to be something like:

`Firstname:{searchTerms}* OR Lastname:{searchTerms}*` if you pass KQL as URL parameter and want it picked up you can use:

`{Request.<PropertyName>}`

It's analog to how you would set up classic web parts more or less.

Take a look at the docs https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-results/#out-of-the-box-query-variables.
