### ISSUE TITLE
ASPX result links to preview rather than the page

### ISSUE THREAD

**Issue by quarterhorse** [microsoft-search/pnp-modern-search#521]
!! Check existing issues before logging new ones !!

**Version used**
3.15.3

**Describe the bug**
Under classic search results, ASPX pages are linked to the actual page so that when a user clicks on it, the page itself is displayed.  Under modern search results, ASPX pages are linked to the preview.

**To Reproduce**
1. Perform a search that includes ASPX content results on a search center
2. Click on an ASPX page result.
3. The page, itself, is displayed.
4. Perform a search that includes ASPX content results on a modern result part.
5. Click on an ASPX page result.
6. The page preview is displayed.

**Expected behavior**
Display the ASPX page itself to be consistent with classic search results.  Frankly, users typically would expect the page to render rather than seeing a preview of the header image.

**Screenshots**

**Desktop (please complete the following information):**
Chrome

**Additional context**

**Comment by quarterhorse** [comment]
For some content, an error message is displayed like

![image](https://user-images.githubusercontent.com/36413662/96458617-1dd0a100-11ef-11eb-9fa0-3a9c41b9966c.png)

**Comment by wobba** [comment]
Thank you for catching this, and pushed to the dev branch.
