### ISSUE TITLE
Why does pnp modern search or handlebarjs removes MediaQueries on Safari?

### ISSUE THREAD

**Issue by SaimenAndSchwyter** [microsoft-search/pnp-modern-search#524]
**Describe the bug**
I have a pnp-modern-search-result webpart on my sharepoint site. I made a custom template which includes media queries for mobile. On desktop browsers and on chromebased mobile browsers the media queries work properly. But on safari browsers (mobile) the media queries do not work.

When I analysed the compiled code on safari I saw that all properties of @media were set to undefined. Instead of `@media screen and (max-width: 1024px){}` it displays `@media undefined {}` on Safari in the debug tools.

**To Reproduce**
1. Create a custom layout and save it on your SP
2. Add media queries in your custom layout
3. Connect the custom layout with the pnp-modern-search-result webpart and display the results
4. The media query works on chrome mobile. The media query do not works on safari mobile. 

**Expected behavior**
Media Queries should be `@media screen and (max-width: 1024px){}` on safari mobile as well

**Desktop:**
- Chrome mobile
- Safari mobile v12, v13
- Edge Chromium
- Chrome

**Images**
How it looks on Desktop
![image](https://user-images.githubusercontent.com/22655223/96578618-bfcab900-12d5-11eb-8b3d-d2e21518ec29.png)

How it should look on Mobile
![image](https://user-images.githubusercontent.com/22655223/96578801-13d59d80-12d6-11eb-9b04-f8b07a7a4599.png)

**Custom Template**
```
<content id="template">
  <style type="text/css">
    /* Zoom in Keyframes */
    /*[... SOME CODE ...]*/
    /*End of Zoom in Keyframes */

    /*IE11 Fixes*/
    /*[... SOME CODE ...]*/

    /*IE11 Fixes - END*/

    .template_root {
      height: 400px;
      width: 100%;
      display: flex;
      overflow: hidden;
      box-shadow: 0px 0.3px 0.9px rgba(0, 0, 0, 0.108),
        0px 1.6px 3.6px rgba(0, 0, 0, 0.132);
      background-color: white;
    }

    @media screen and (max-width: 1024px) {
      .template_root {
        height: unset;
        flex-direction: column;
      }
    }

    /* First News Style*/
    /*[... SOME CODE ...]*/

    /* First News Style - END*/

    /* Older News Style*/
    .older_news {
      flex-grow: 1;
      list-style: none;
      margin: 0px 10px;
      padding: unset;
      max-width: 380px;
    }

    @media screen and(max-width: 1024px) {
      .older_news {
        max-width: 100%;
        margin: 0px 10px;
      }
    }

    /*[... SOME CODE ...]*/

    /* Older News Style - END*/

    /* Button Style*/
    a.more {
      line-height: 32px;
      width: 120px;
      color: white;
      text-decoration: none;
      display: block;
      box-sizing: border-box;
      text-align: center;
      border-radius: 2px;
    }

    a.more:hover {
      opacity: 0.8;
    }

    @media screen and(max-width: 480px) {
      a.more {
        font-size: 1rem;
      }
    }
    /* Button Style - END*/

  </style>
  {{#if items.0.Title}}
  <div class="template_root">
    <div class="template_result news">
      <div
        style="background-image:url({{items.0.SPSiteUrl}}/_layouts/15/getpreview.ashx?guidSite={{items.0.SiteId}}&guidWeb={{items.0.WebId}}&guidFile={{items.0.UniqueID}}&resolution=5)"
        class="backgroundImage"
      ></div>
      <div class="template_innerblock">
        <div class="template_contentContainer">
          <h1 style="color: {{@root.themeVariant.palette.themePrimary}};">
            {{items.0.Title}}
          </h1>
          <p>{{items.0.Description}}</p>
          <a
            class="more"
            style="background-color: {{@root.themeVariant.palette.themePrimary}};"
            href="{{items.0.Path}}"
            >Weiterlesen</a
          >
        </div>
      </div>
    </div>
    <ul class="older_news">
      {{#if items.1.Title}}
      <li>
        <div
          class="news_image"
          style="background-image:url({{items.1.PictureThumbnailURL}})"
        ></div>
        <div class="news_content">
          <h3>{{items.1.Title}}</h3>
          <a
            style="color: {{@root.themeVariant.palette.themePrimary}};"
            href="{{items.1.Path}}"
            >Weiterlesen</a
          >
        </div>
      </li>
      {{/if}} {{#if items.2.Title}}
      <li>
        <div
          class="news_image"
          style="background-image:url({{items.2.PictureThumbnailURL}})"
        ></div>
        <div class="news_content">
          <h3>{{items.2.Title}}</h3>
          <a
            style="color: {{@root.themeVariant.palette.themePrimary}};"
            href="{{items.2.Path}}"
            >Weiterlesen</a
          >
        </div>
      </li>
      {{/if}} {{#if items.3.Title}}
      <li>
        <div
          class="news_image"
          style="background-image:url({{items.3.PictureThumbnailURL}})"
        ></div>
        <div class="news_content">
          <h3>{{items.3.Title}}</h3>
          <a
            style="color: {{@root.themeVariant.palette.themePrimary}};"
            href="{{items.3.Path}}"
            >Weiterlesen</a
          >
        </div>
      </li>
      {{/if}}
      <li>
        <div
          class="news_image"
          style="
            background-image: url(https://TENANT.sharepoint.com/SiteAssets/Static%20Images/Archiv.svg);
          "
        ></div>
        <div class="news_content">
          <h3>Weitere Artikel</h3>
          <a
            style="color: {{@root.themeVariant.palette.themePrimary}};"
            href="https://TENANT.sharepoint.com/sites/inet-CorporateNews/"
            >Zum Archiv</a
          >
        </div>
      </li>
    </ul>
  </div>
  {{/if}}
</content>

<content id="placeholder">
  <!--TEMPLATE Placeholder-->
</content>
<html
  xmlns:mso="urn:schemas-microsoft-com:office:office"
  xmlns:msdt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
>
  <head> </head>
</html>


```

**Comment by wobba** [comment]
Can you provide a sample template? We don't do any special handling per browser/device, so weird that it works differently. Would be good if you can test this with some other SPFx web part as well.

**Comment by SaimenAndSchwyter** [comment]
@wobba 
I updated the code and added some images

**Comment by wobba** [comment]
You need to ensure there is a space between `and` and the `(` for the parsing to work when the DOM is traversed for santization.

Correct
```
@media screen and (max-width: 1024px) {
```

Incorrect
```
@media screen and(max-width: 1024px) {
```

If you read the RFC at https://www.w3.org/TR/mediaqueries-4/#mq-syntax it states this as well.

![image](https://user-images.githubusercontent.com/51104/96754892-364ce100-13d2-11eb-93c8-ca3633ad78db.png)

**Comment by SaimenAndSchwyter** [comment]
Thank you for your answers.
Unfortunately your fix does not change anything.

**Comment by wobba** [comment]
@SaimenAndSchwyter Your template failed in Chrome for me, but adding whitespace made when I used F12 to investigate. Can you verify in dev tool on a non Safari browser? Also try to add some other media tags higher up and see if they are changed or kept.

**Comment by emflaugh** [comment]
I am also experiencing this issue. The template works fine in Chrome / mobile dev tools. But fails to apply media queries on Safari / iOS mobile device.

**Comment by wobba** [comment]
So seems more like a browser parsing issue than a PnP modern web part issue. Is this correct? If you look at the network packet coming to Safari/iOS, does it include all the CSS, but fail to parse it?

**Comment by emflaugh** [comment]
Yes, the css is coming through in the network packet for the template, but it is not being applied in Safari browser desktop and mobile.

**Comment by wobba** [comment]
Then I'll close the issue as it's Safari related, not related to this project.

**Comment by SaimenAndSchwyter** [comment]
So what is the issue now?

**Comment by wobba** [comment]
@SaimenAndSchwyter as the CSS is coming thru to Safari, it's Safari which parses it wrong and fails. That's the issue - Safari and HTML+CSS parsing.

**Comment by SaimenAndSchwyter** [comment]
hmmm... that is strange because the html template on its own with the MediaQueries works on safari. But in combination with the modern search it is not the case.
![image](https://user-images.githubusercontent.com/22655223/97270649-cb673400-182f-11eb-91cb-23780858b567.png)

So I have to look for a workaround

**Comment by wobba** [comment]
If the template is coming thru with the network packet, it's still a parsing/rendering error by Safari as other browsers seem to handle it imo. 

You should capture the network trace to Safari and look at what is returned, verify all spaces etc.

**Comment by SaimenAndSchwyter** [comment]
@wobba Thank you for our anwser. I will check that.

@emflaugh Have you already found a solution for your case?
