### ISSUE TITLE
Support for audience

### ISSUE THREAD

**Issue by coupalm** [microsoft-search/pnp-modern-search#525]
Get the ability to filter results based on current user audience membership.

Thanks

**Comment by wobba** [comment]
You can do this manually via KQL similar to what the HCWP adds:

`(ModernAudienceAadObjectIds:{User.Audiences} OR NOT IsAudienceTargeted:true)`

**Comment by coupalm** [comment]
Thanks! I was not aware of User.audiences and the other managed properties. 
Just found Microsoft reference: https://docs.microsoft.com/en-us/sharepoint/technical-reference/query-variables
