### ISSUE TITLE
getUrl Handlebars helper & ContentType= Post

### ISSUE THREAD

**Issue by Georg-Trixl** [microsoft-search/pnp-modern-search#527]
**Version used**
3.15.3

**Describe the bug**
getUrl Handlebars helper returns for ContentType= Post a URL that should show Office Documents.
But the web viewer doesn't handle the Post type ... and writes "Hmm... looks like this file doesn't have a preview we can show you."

**To Reproduce**
Search for a blog post entry of a classic Blog site collection.
Make sure that the result items are displaying the search result URL generated by getUrl Handlebars helper.
Open the URL from getUrl in browser.

**Expected behavior**
getUrl should return "OriginalPath" or "Path" both are containing the right URL for a blog post entry
if ContentType = "Post"

**Additional context**
I did that research based on Blogs, I didn't check other results which are also ContentType="Post" - as far as I remember comments are also "Post", but I gues a web view doesn't serve that kind of results well.

**Comment by wobba** [comment]
You should use `SPContentType` not `ContentType` as the latter can have some extra data in it.

That said I added a fix to the dev branch this week to ensure .aspx files are handled correct. Logic can be seen at https://github.com/microsoft-search/pnp-modern-search/blob/develop/search-parts/src/services/TemplateService/BaseTemplateService.tsx#L206-L233

**Comment by Georg-Trixl** [comment]
Yes @wobba thank you very much. I saw the code fix and it's perfectly coded.
Thank you also for the hint with the content types.
Have a nice day.
Best regards from Austria sends
Georg
