### ISSUE TITLE
Search results web part doesn't retain the filtered set of results. Instead shows all results.

### ISSUE THREAD

**Issue by SaratchandraPeddinti** [microsoft-search/pnp-modern-search#528]
**Version used: 3.11** (updated version)

**Description:**
When a search is performed using URL fragment (eg: https://site/searchpage.aspx#**managed_prop:"filter_value"**), the results webpart shows the filtered results for a fraction of time & then shows all the results. (results webpart is configured to show all results using alternate query on page load). This issue occurs intermittently.

**To Reproduce**
1. Modify the results template to show a filter link explained as below (i.e., this link appears for each item repeatedly)
2. Add a link on a page in this format using anchor tag https://site/searchpage.aspx#**managed_prop:"filter_value"**
2. Configure the anchor tag to open link in new tab
3. Test the links by clicking on them. Works for most part but starts showing the above explained behavior

**Expected behavior**
To show only the filtered items

**Screenshots**
![image](https://user-images.githubusercontent.com/16175517/96737842-be83b400-13db-11eb-9e7c-fed1394ae366.png)

**Browser information:**
 - chrome & edge

**Comment by wobba** [comment]
Can you repro with v3.15.3?

**Comment by SaratchandraPeddinti** [comment]
> Can you repro with v3.15.3?
@wobba 
Thanks for responding. I'll try this.

**Comment by SaratchandraPeddinti** [comment]
Hi @wobba 

Unfortunately, even the latest version(3.15.3) of the webpart has this issue.

**Comment by wobba** [comment]
Can you share the exact page setup and share a sample template?

**Comment by SaratchandraPeddinti** [comment]
Hey @wobba 

Search page refresh is not the issue I reported. However, I'm sharing my settings if that helps. (the settings I haven't included are default settings)
**Note:** On load of my page, the results would be 200K+
![image](https://user-images.githubusercontent.com/16175517/96954954-22a89400-1512-11eb-9407-d93bf56373b6.png)

**Comment by wobba** [comment]
Can you try to use a query parameter instead of query fragment.. could be the fragment code which is impacted.

**Comment by SaratchandraPeddinti** [comment]
Hey @wobba , forgot to update here. in fact, I tried with both settings. Result is same.

**Comment by wobba** [comment]
@SaratchandraPeddinti if possible, could you check if the dev branch fix for routing navigation resolves this issue? I have no problem using fragment now.

Connected search box to use URL fragment, and web part to consume the search box.

On my search page I added a text link:

`https://tenant.sharepoint.com/sites/aiste/SitePages/Apage.aspx#title:"foo"`

When clicking the link the URL changes, and the property query is picked up by search.

The URL changes to `https://techmikael.sharepoint.com/sites/adal/SitePages/Apage.aspx#title%3a%22foo%22` when clicked but works as expected.

**Comment by SaratchandraPeddinti** [comment]
@wobba I think we are good with this. No issue now.
