### ISSUE TITLE
Bug with Search Refiners webpart 

### ISSUE THREAD

**Issue by mag210** [microsoft-search/pnp-modern-search#53]
Hi all, 

I've noticed a small issue with the Search Refiners webpart when you have it configured as a Multi Value refinement item. 

By default the "Apply | Clear" buttons are greyed out until you select an item to filter. This makes sense, If you then select a single item and click "Apply", the webpart filters the search results as expected. However, if you then uncheck the item, the "Apply and Clear" buttons are greyed out but the search results are still being filtered. You then need to recheck the item so that the buttons appear again. We really need Apply and Clear to stay visible if a filter is still in affect so the user can clear their selection. 

Hope this makes sense, 

Thanks, 

-Max

![Filter](https://user-images.githubusercontent.com/15345746/71903171-73095d80-315b-11ea-87c2-e6221332a078.PNG)

**Comment by FranckyC** [comment]
@mag210 should be resolved by #63 . Feel free to checkout the develop branch and test.
