### ISSUE TITLE
Can we use these web Parts in SharePoint online in Classic pages ?

### ISSUE THREAD

**Issue by Asfandtnt** [microsoft-search/pnp-modern-search#531]
I have used these web parts in SPO modern pages and it worked smooth.
then I try to rebrand the whole page added images some CSS and some DOM manipulation so far so good.
but yesterday my page layout get disturbed. After some inspection I figure out behind the scene Microsoft updated layout of modern pages a bit and some CSS (added by Microsoft) was causing the trouble.
my question is how to avoid it .... should we use Classic pages for these web part or what.... Your expert advice needed badly.

**Comment by Asfandtnt** [comment]
@wobba

**Comment by wobba** [comment]
YOU SHALL NEVER TAKE A DEPENDENCY ON THE DOM AS AN API. DOM MANIPULATION IS ALWAYS AT YOUR OWN RISK AND WILL BREAK.

**Please keep questions to things you know should be supported - not hacking the experience.**

That said, my expert advice is to brand within what the platform offers for modern. If you think the business value validates a really custom design, sure use classic, but I would not do it.

Take a look at https://docs.microsoft.com/en-us/sharepoint/branding-sharepoint-online-sites-modern-experience for official guidance.

(This is my own personal opinion and not an official opinion from Microsoft)

**Comment by wobba** [comment]
@Asfandtnt Wanted to highlight the Note part here as well https://docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance#in-perspective-sharepoint-framework-in-the-broader-sharepoint-platform
