### ISSUE TITLE
Sort functionality breaking after entering new search query or changing filter

### ISSUE THREAD

**Issue by vchou265** [microsoft-search/pnp-modern-search#535]
**Version used**
3.15.3.0
 
**Describe the bug**
When we try to use the Sort functionality after entering a new search query or changing our selected filters, we are unable to switch between “Ascending” and “Descending” and have to change to a different sort option so that it works again. And if we already selected a sort option before entering a new search query or changing our selected filters, the sort option stays selected but the results are not sorted.
 
 
**To Reproduce**
1. Add a Search Box to a page.
2. Add a Search Results in the same page.
3. Connect the Search Results to the Search Box and add two sortable fields under the “Sortable properties” option. We will refer to these two fields as “Field1” and “Field2”.
4. Select “Field1” in the Sort dropdown and “Descending” next to the Sort dropdown. The search results should sort as expected.
5. Enter a search query and/or select a filter if you have a Refiner connected. The search results will now no longer be sorted as expected but the Sort dropdown still shows “Field1” and “Descending”. You are now unable to switch from “Descending” to “Ascending”. 
6. If you switch the Sort dropdown option from “Field1” to “Field2”, the search results now sort as expected and you can switch between “Ascending” and “Descending” again.
 
 
**Expected behavior**
Two options:
1. The Sort dropdown should be reset to the default/empty values (ie. “Sort by”) upon a new search query or filter; or
2. The search results should reflect the selected option in the Sort dropdown despite a new search query or filter and allow us to switch between “Ascending” and “Descending” on the current sort option.
 
 
**Desktop**
Chrome, Firefox, Safari (we did not test IE)
 
 
**Additional context**
This issue might have been resolved and then reinstated in recent updates.

**Comment by wobba** [comment]
I think option 2 would be the best approach, and I see there are some UX issues on default showing.

**Comment by wobba** [comment]
I believe this works as expected in newer releases. Feel free to re-open if you experience an issue with the latest release.
