### ISSUE TITLE
Selected Properties dropdown stuck

### ISSUE THREAD

**Issue by minokin** [microsoft-search/pnp-modern-search#539]
**Version used**
3.15.3

**Describe the bug**
In the Configuration Pane of the Search Result webpart, the dropdown that let you choose the Selected Properties the loading of list the properties remain stuck and it's not possible to add or remove properties.

**Screenshots**
![image](https://user-images.githubusercontent.com/12963278/97971951-1e0e9600-1dc4-11eb-8723-6a162e7197cf.png)

**Desktop (please complete the following information):**
 - Browser Chrome and Edge

**Additional context**
Through the Dev Tools i've encountered the following error: 
_search-results-web-part_1b44032aa56d936ba15300b790e6b8e0.js:1 Message: Error making HttpClient request in queryable [500]  ::> {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}} Data: {"response":{},"status":500,"statusText":"","isHttpRequestError":true}_

**Comment by wobba** [comment]
Hit the `END` key, and add them manually instead. The API to fetch managed properties is not official and has hiccups every so often (as you encountered). You might have to go next/prev if the box blanks out to see your changes, but they should be there.

**Comment by minokin** [comment]
Ok l'll try manualli, thank you.

**Comment by wobba** [comment]
Closing as it's a backend issue, not the web part per say.
