### ISSUE TITLE
Incorporate modern audience targeting to search parameters

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#54]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the option in the results or refiners web part (or both) to turn on audience targeting and filter results based on aud targeting selections in libraries/lists. So user A will only get results targeted to him/her. 
**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by FranckyC** [comment]
Hi @webbrewer, good suggestion. Already thought about it but not prioritized yet. Stay tuned.
