### ISSUE TITLE
Filter multiple Search Results with one Refiner

### ISSUE THREAD

**Issue by jonasesser** [microsoft-search/pnp-modern-search#540]
**Is your feature request related to a problem? Please describe.**
We want to use one refiner to filter two search results. Both results are from the same source, but the second one should display a more specific result.

**Describe the solution you'd like**
To add second search results web part in the search filter properties "Connect to search results Web Part".

**Describe alternatives you've considered**
If the second search result will use the results from the first one and filter it down with a another search query. This would be fine. So the first search results will be filtered by the refiner and based on these results the second search results will filter it further down.

**Additional context**
In SharePoint 2013 this was possible out of the box but very complicated: https://blog.ioz.ch/mehrere-search-webparts-mit-einem-refinement-filtern/

**Comment by wobba** [comment]
This is doable today. Have two result web parts connect to the same Filter web part. The Filter web part can however only get values from one web part.

**Comment by MKGy** [comment]
The following article might just be an answer to the question: 
https://johanerixon.wordpress.com/2014/10/28/filtering-multiple-search-webparts-from-one-refinement-panel/

**Comment by jonasesser** [comment]
Thanks @wobba ! It's working.

**Comment by wobba** [comment]
@MKGy your reply reference classic web parts. An article from 2014.

PnP Modern Search web parts is an open source project for SP modern page web parts, so solutions outside of these are clearly not the right thing to point to.

Better luck next time 🙂
