### ISSUE TITLE
Limit number of refinement values displayed in a Filter webpart

### ISSUE THREAD

**Issue by raymond-tishenko** [microsoft-search/pnp-modern-search#541]
**Is your feature request related to a problem? Please describe.**
I'd like to limit the number of refinement values displayed by the Filter webpart on a managed property basis.

Currently when the result set returns many refinement values the Filter webpart UI takes a long time to expand/collapse a particular refiner. In our current use-case we have a result set with over 1000 refinement values, the items are tagged with Keywords. When opening the refiner to select values it takes a long time for the refinement values to display and taxes the client system.

**Describe the solution you'd like**
When editing the refiners in the Filter webpart, I'd like to have the ability to specify a limit to the number of refinement values. This would have the effect of only displaying (x) refinement values and ideally indicate that only (x) values are being displayed.
Alternatively we could enable 'paging' of refinement values and only display the first (x) number, with a link to display the next (x) or 'more' refinement values.

**Describe alternatives you've considered**
We've considered forcing users to specify a keyword query in the search box and sending them to a results page to limit the number of results and Keywords in the filter; however, they prefer to use refiners to narrow the scope and 'browse/refine' to a result set of items.

**Additional context**
Our search results set contains many thousands of items, most of which are tagged with one or more Keywords - this creates a scenario where there is a huge number of refinement values.

**Comment by raymond-tishenko** [comment]
Hi, is there any chance we could see this enhancement hit v3? It'd make a huge difference for a few of our use cases.
Thanks!

**Comment by wobba** [comment]
@raymond-tishenko  If someone has the time to add the functionality we could. Are you seeing to many now? Currently all RefinableString propties, JobTitle, Department, FileType and Tags will pull back all values, which should cover most cases. Question is if you want less values for these?

**Comment by raymond-tishenko** [comment]
Hi @wobba, we'd like to have the limit to reduce the number of values coming back - currently seeing too many.

**Comment by wobba** [comment]
How do you know which ones should be used? I think what you want is to limit what UX shows in the initial list, not omitting values. And then with a show more link. In v4 you could build this with a custom handlebar template for the filter values.

**Comment by raymond-tishenko** [comment]
We'd simply only show the first (x) number of values based on the sort order specified in the Filters configuration, ie: alphabetical or count. A 'show more' link would be great, showing the next (x) number of values. I'll admit that limiting the display of values is somewhat arbitrary.

If limiting the values shown in the list using this approach would reduce the processing required by the client system that would meet our needs. Again, currently when the filter has many (thousand or more) values it takes a significant amount of time to expand the filter, in the range of 8-10 seconds at times.

**Comment by wobba** [comment]
UX rendering is not always easy. Another question. If you have thousands of values coming back, how do you know if they are useful to the people using the experience? Especially if you cap it at say 10.

**Comment by raymond-tishenko** [comment]
True, we don't know if the values coming back are ideal for the users but are making the compromise that the top (x) based on the sort order are most relevant (by their specification). Is it the best way to go? I'm not completely convinced but it seems like a decent middle ground.

I guess it really is a UX issue, with the heavy time to fetch/load the items in the filter creating a sub-optimal experience. Maybe another way to approach this would be to have the filter fetch values in a paginated fashion with a 'show more' link based on the specified sort order. This way there'd be no cap, but rather a reasonable batch size for each fetch/load - but I'm not sure if that's possible or how difficult it would be to implement?

What are your thoughts on this?

**Comment by wobba** [comment]
I think there are no middle ground. You should be able to show all values, preferably with a filter on top if there are too many to show. And it's up to the UX to render this quick enough. We are using uifabric components and I know these can be slow when there are a lot of values - but something we should try to work out on the UX instead of capping the number of values at the users expence :)

**Comment by wobba** [comment]
Closing as I won't add this to v3.
