### ISSUE TITLE
Search results with connected search box

### ISSUE THREAD

**Issue by Oegl** [microsoft-search/pnp-modern-search#543]
Which fields will be considered automatically in search results by the text, entered in the search box.

I defined some refinablestring manged properties - for some of them, when entering a text in the searchbox they seems to be considered automatically by search result, some not.

How to knwo which fields are considered by search result, with the text, entered in the search box.

Thanks for your help!

**Comment by Oegl** [comment]
I could answer it by my own - each managed property, defined as "searchable" will be considered by the text, entered in the searchbox.

**Comment by Oegl** [comment]
I could answer it by my own - each managed property, defined as "searchable" will be considered by the text, entered in the searchbox.

**Comment by wobba** [comment]
In addition any SharePoint Field not mapped is also searchable. See my old post: https://www.techmikael.com/2014/07/what-makes-sharepoint-column-searchable.html
