### ISSUE TITLE
Guidance / Documentation on Web Component Usage

### ISSUE THREAD

**Issue by OmarStewey** [microsoft-search/pnp-modern-search#544]
Is there any walk through or guidance on how/where the Web Components can be used? I'm looking to leverage the <pnp-panel> component listed here, but I haven't been able to find any guidance on how and where it can be used. 

When I add the markup to a Custom Template, I get nothing in the render.

Components listed here are what i'm referring to.
https://microsoft-search.github.io/pnp-modern-search/extensibility/web_components_list/

**Comment by wobba** [comment]
@OmarStewey are you testing v4?

**Comment by OmarStewey** [comment]
I'm using 3.15.3.
I'm attempting to use a <pnp-panel> in a Custom Template.

**Comment by FranckyC** [comment]
Custom components can be used in any Handlebars templates like search results, search filters. The documentation you're refering to is for the new v4 version. For the v3 version the documentation and available components are listed here https://web.archive.org/web/20201014031827/https://microsoft-search.github.io/pnp-modern-search/search-parts/templating/#web-components

**Comment by OmarStewey** [comment]
Works like a charm, thank you so much for the help.
