### ISSUE TITLE
Custom Renderer - Additional template parameters

### ISSUE THREAD

**Issue by frankok** [microsoft-search/pnp-modern-search#547]
Hi,

I see that the OOTB templates have several custom parameters available in the bottom on page 3 in the web part properties. Here is an example from the Carousel template:

![image](https://user-images.githubusercontent.com/20436301/98860747-6c770100-2464-11eb-938a-15a020899e6b.png)

I am wondering if this is possible to achieve in a custom renderer as well?

**Comment by wobba** [comment]
@FranckyC does the new extensibility option support UX config options? Now, or maybe later?

**Comment by frankok** [comment]
Not possible? :)

**Comment by FranckyC** [comment]
Hi all, for now this is not possible sorry. Only customizations listed here are allowed: https://microsoft-search.github.io/pnp-modern-search/extensibility/#supported-extensions
