### ISSUE TITLE
Do we need to do anything to deployed web parts after an upgrade to a newer version of solution?

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#548]
!! Check existing issues before logging new ones !!

**Version used**
3.14.2

**Describe the bug**
More of a question: when you upgrade to a  newer version, do you need to do anything to web parts already deployed on pages? I ask because after installing v3.14.2 a few months ago I've noticed the results web part stops working intermittently and starts again when the page is put into edit mode. Hard to troubleshoot because it's very inconsistent.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Chrome

**Additional context**

**Comment by wobba** [comment]
It says in the release note if there are breaking changes, but typically no action needed. Newer versions may have bugs though.

You're saying if you edit and save, the problem goes away? And what version did you upgrade from? What was the settings?
