### ISSUE TITLE
Feature request : ability to see actual transformed query

### ISSUE THREAD

**Issue by stevebeauge** [microsoft-search/pnp-modern-search#55]
**Is your feature request related to a problem? Please describe.**

The classic search result webpart have a very useful feature : the "Test" tab of the query editor. Especially, when writing complex queries, with a lot of tokens, or when the result source has complex syntax, the test tab shows the actual, final, KQL query passed to the search engine. 

This helps a lot to debug complex syntax, or to copy/paste the query (into Search Query Tool for example).

The modern search web part does not show the final query.

**Describe the solution you'd like**

It would be cool to show the query somewhere. It may at least in the browser dev console, or in the debug template, or in the component source (as Html comment), or shown using a hidden shortcut, ...

**Describe alternatives you've considered**

**Additional context**

**Comment by FranckyC** [comment]
Hi @stevebeauge. Should be doable by getting this info from the search JSON response (the `QueryModification` part). I can output it in the debug template. Thank you for your feedback.

**Comment by FranckyC** [comment]
@stevebeauge should be resolved by #63 . Feel free to checkout the develop branch and test.

**Comment by stevebeauge** [comment]
Seems to works as expected. Thanks!
