### ISSUE TITLE
Sort not sorting all results

### ISSUE THREAD

**Issue by teylyn** [microsoft-search/pnp-modern-search#550]
!! Check existing issues before logging new ones !!

**Version used**
Ex: 3.15.3.0

**Describe the bug**
When Search returns many results, broken into several pages in Detail layout, sorting sorts only the results visible on the page, not all results returned.

**To Reproduce**
1. create a search result web part
2. use the Detail layout
3. create a search that returns paged results
4. click the Create column in the Search Results to sort by the date.

**Expected behavior**
sorting results with multiple pages should sort all results

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by wobba** [comment]
You need to set the sort order on the search request.
![image](https://user-images.githubusercontent.com/51104/98956416-4b63ee00-2500-11eb-80f4-4634bbd48177.png)

![image](https://user-images.githubusercontent.com/51104/98956443-54ed5600-2500-11eb-9379-913da33e3888.png)

**Comment by teylyn** [comment]
No, I want the default sort order to be by relevance, so I do not define anything in the "Edit sort order". If I do that, my search will always be sorted by that parameter, which is not what I want. 

When I manually click on a column headers to sort by that column, I then expect the results to be sorted by that column, but that should include ALL results, not just the visible ones.  I want to be able to sort my search results by the different columns in the layout. Is that not what the command is for, then???

**Comment by wobba** [comment]
Per docs on column sorting. So this is by design:

> Sortable: allows you to sort column values alphabetically when the column header is clicked (ascending or descending). The sort is done statically on **the current page results set** and works only when the column value is not an Handlebars expression.
