### ISSUE TITLE
Date sort on managed property date not working

### ISSUE THREAD

**Issue by teylyn** [microsoft-search/pnp-modern-search#551]
!! Check existing issues before logging new ones !!

**Version used**
Ex: 3.15.3

**Describe the bug**
When sorting by clicking the column header of a managed property date  in the Details layout, the results are not sorted chronologically by that date. The order appears to be random. However, if the Created column is also shown on the page, the sort seems to be aligned to the Created column, not the column used for the sort.

**To Reproduce**
1. create a search results web part
2. use the Details List layout
3. insert a managed property date, sortable
4. click the column heading to sort

**Expected behavior**
When clicking the column header of a managed property date in a Details List Search Result, the data should be sorted chronologically by the selected date.

**Screenshots**
The data is sorted by the column "ManagedDate" and appears in random order. After sorting by that column, I edited the web part and just added the Created column without changing the existing sort order. Note how the Created column appears in chronological order despite the ManagedDate column being the one with the active sort indicator.

![image](https://user-images.githubusercontent.com/6252689/98880883-a50eed00-24ed-11eb-8ce7-ed0d410ffe87.png)

**Desktop (please complete the following information):**
 - Browser Chrome, Windows 10

**Additional context**

**Comment by wobba** [comment]
Is `ManagedDate` of type sortable?

**Comment by teylyn** [comment]
Yes. It's RefinableDate01, which in the Search Schema is Sortable (by default and cannot be changed) and in the "Manage columns" dialog is set to Sortable.
![image](https://user-images.githubusercontent.com/6252689/98987115-acd09f00-258a-11eb-8bb4-e7971816e4e0.png)

**Comment by wobba** [comment]
Got it, and as per the docs when sorting on columns like this.

> Sortable: allows you to sort column values alphabetically when the column header is clicked (ascending or descending). The sort is done statically **on the current page results set** and works only when the column value is not an Handlebars expression.

If you need full result set sorting you need to add sorting fields - not layout sorting.

**Comment by teylyn** [comment]
thanks for the clarification
