### ISSUE TITLE
Cannot find module '@pnp/modern-search-extensibility' 

### ISSUE THREAD

**Issue by MKGy** [microsoft-search/pnp-modern-search#552]
**Version used**
feature/v4

**Describe the bug**
Cannot bundle --ship webparts. Hence, unable to create sppkg package. 
The compiler provides reasons such as : 
(1)  error TS2339: Property 'properties' does not exist on type 'PanelFilterLayout'.
(2) error TS2307: Cannot find module '@pnp/modern-search-extensibility'.

PS.: Please note that I successfully bundled and packaged modern-search-extensibility which is included in the folder search-extensibility.
 

**To Reproduce**
1. Clone feature/v4 branch
2. Navigate to folder search.parts\src\webparts
3. run  npm install
4. run  gulp bundle --ship
5. run  gulp package-solution --ship  

**Expected behavior**
expected a sppkg file to be created

**Screenshots**
none

**Desktop (please complete the following information):**
 - Browser : chrome, edge

**Additional context**
none
[errors.txt](https://github.com/microsoft-search/pnp-modern-search/files/5529924/errors.txt)

**Comment by wobba** [comment]
Read the docs https://microsoft-search.github.io/pnp-modern-search/how-to-contribute/#setup-the-search-parts-and-search-extensibility-demo-projects :)

**Comment by MKGy** [comment]
Thanks wobba for the reference !
