### ISSUE TITLE
Modern pnp search results link type change

### ISSUE THREAD

**Issue by westronman** [microsoft-search/pnp-modern-search#553]
Hi, I need the default search results web part links to open documents (e.g. office documents) in the browser (office online) however the default search results template links downloads them for opening in the desktop apps. How do I change this to open in the browser, please?

**Comment by wobba** [comment]
Don't know the version or template you are using, but default for the `getUrl` handler is to open in web.

Please adhere to the issue template, and don't delete all the questions.

**Comment by wobba** [comment]
Do you have more background on your initial question? If not we will close the issue.

**Comment by westronman** [comment]
Hi I'm using app version 3.15.3.0 and  the search results web part is currently using the 'Simple List' display template with no further modifications. The links in the search results web part are being rendered as the absolute URL to the document and not using the _layouts/15/Doc.aspx page (which would open them in the browser) as per the default SharePoint search.
![image](https://user-images.githubusercontent.com/74354988/99846252-e34f8080-2b6d-11eb-9f4e-fc5b3aa520a4.png)

**Comment by wobba** [comment]
Can you create a new page, add the web part and test? Or switch to another template, save, and then back. It should work for just about all file types in the version you have, but the upcoming version simplifies the logic to use `DefaultEncodingURL + ?web=1`. Then SharePoint redirects to what it believes is the best experience for that file type.

**Comment by westronman** [comment]
Ok, the 'simple list' display template seems to open documents natively (e.g. downloads them) whereas a test with the 'details list' display template opens them in the browser (appends the url with the ?web=1 parameter). Can I tweak the 'simple list' template to add the ?web=1 parameter?

**Comment by wobba** [comment]
@westronman which is the weird part, as I get ?web=1 with the simple list template as well - at least with the develop branch. Should be same logic for v3.15.3 as long as `DefaultEncodingURL` and `contentclass` are part of retrieved mp's.

**Comment by wobba** [comment]
v3 no longer maintained
