### ISSUE TITLE
Filter results based on people picker and Column Value

### ISSUE THREAD

**Issue by Rbob3267** [microsoft-search/pnp-modern-search#555]
I'm using PNP modern search web part (search box and search results web part) and Results source which is configured with 3 different Content types. I am able to see the results coming from all the lists. 

For 2 of the list we have Publisher, Approver and Status columns . 

Now, I need to filter and display the results only if current logged user is on either Publisher or Approver column ( Approver /Publisher will be a single user or might be a SharePoint Group). 

Also I need to show the results only if  Status is Approved for one ContentType and Status is Published for Other Content Type.

**Comment by wobba** [comment]
You need to look into how to use managed properties with query variables. This is not specific to these web parts, but search/KQL specific.

On a high level you need to map the crawled property corresponding to your SharePoint fields/columns are mapped to a managed property which is queryable. Then add something like this to your filter, depending on the value you store/show in the field

`ManagedProperty:{User.AccuntName}`

If you are using site columns it's easier as they have automatically generated managed properties you can query against.

See https://docs.microsoft.com/en-us/sharepoint/technical-reference/automatically-created-managed-properties-in-sharepoint (which does apply to SPO as well)

**Comment by wobba** [comment]
Closing this issue as it relates to KQL, not web part specifics.
