### ISSUE TITLE
AAD application not setup

### ISSUE THREAD

**Issue by marschallphilipp** [microsoft-search/pnp-modern-search#556]
**Version used**
4.0.0.0

**Describe the bug**
I´m trying to search for people and show the persona card on hover as described here.
[https://microsoft-search.github.io/pnp-modern-search/usage/search-results/layouts/#people]
Unfortunately I can´t find any newly created app within app registrations for granting the needed permissions.
I allready used version 3.x.x.x and could find the applications ("SharePoint Online Client Extensibility Web Application Principal", "SharePoint Online Client Extensibility Web Application Principal Helper"), but with version 4.0.0.0 no new application is created automatically.

**To Reproduce**
1. Install packages in tenant app catalog
2. deploy app
3. Search in [https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade] for granting the permissions

**Expected behavior**
AAD apps should be listed in AAD app registrations after deploying the apps

**Desktop (please complete the following information):**
 - Edge browser

**Comment by FranckyC** [comment]
Hi @marschallphilipp. The SharePoint Online Client Extensibility AD app is unique in your tenant and created only the first time you deploy a package requesting for permissions. As described [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient):

_"All permissions are granted to the whole tenant and not to a specific application that has requested them. When the administrator grants a specific permission, it is added to the SharePoint Online Client Extensibility Azure AD application, which is provisioned by Microsoft in every Azure AD and which is used by the SharePoint Framework in the OAuth flow to provide solutions with valid access tokens."_

In your case, the v4 package asks for additional MS Graph API permissions. You need to grant them in the SharePoint admin center in the 'API access' [menu ](https://docs.microsoft.com/en-us/sharepoint/api-access). Hope it helps.

**Comment by marschallphilipp** [comment]
Hi @FranckyC  thanks for the quick resonse! Yes it helps but it doesn´t work yet.
Permissions in SP Admin Center are granted.
![2020-11-17 08_29_20-SharePoint admin center and 6 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/6168689/99359849-f8978700-28af-11eb-8666-bf4590f782ef.png)

I also added the "other permissions granted for...." to the "configured permissions" within app registrations in Azure portal.
![2020-11-17 08_38_17-SharePoint Online Client Extensibility Web Application Principal - Microsoft Azu](https://user-images.githubusercontent.com/6168689/99360158-76f42900-28b0-11eb-9bc1-f094800db328.png)

But still getting an "access denied" when loading the search page.
![2020-11-17 08_33_40-Window](https://user-images.githubusercontent.com/6168689/99360213-8a9f8f80-28b0-11eb-8d16-86587fe0f501.png)

Any idea?
Thank you very much!

**Comment by FranckyC** [comment]
Try to sign-out of of your current session et re sign-in. This could be caused by cached credentials. This way the access token will be refreshed with new permissions.

**Comment by wobba** [comment]
Or try `sessionStorage.clear()` `localStorage.clear()`

**Comment by marschallphilipp** [comment]
Thank you very much for the quick and helpful response!
