### ISSUE TITLE
Search webparts at tenent workbench

### ISSUE THREAD

**Issue by sekharB487** [microsoft-search/pnp-modern-search#557]
I am getting "**Cannot read property 'id' of undefined**" when added to workbench. Can anyone share your views how I can load search results in workbench?
![image](https://user-images.githubusercontent.com/71835451/99381044-c2c6c280-28f0-11eb-8288-d9db7167468e.png)

**Comment by wobba** [comment]
I cannot repro. What version are you using? (We have the bug template for a reason).

**Comment by sekharB487** [comment]
I'm using https://github.com/microsoft-search/pnp-modern-search/tree/main/search-parts 
pnp-modern-search-3.15.3
node: v10.20.1

**Comment by wobba** [comment]
If you check "use a default query" on/off, does that help? I still cannot repro. Can you check the debug console to get more details of which `id` is not defined.

**Comment by FranckyC** [comment]
@sekharB487 make sure the solution is not deployed already in your app catalog. I had the same issue but after removing existing app from my site catalog, this issue was gone, Not sure about the cause though :(.
