### ISSUE TITLE
Search document library folder

### ISSUE THREAD

**Issue by nimchak** [microsoft-search/pnp-modern-search#559]
Not really a bug but didn't know how to ask a question.

It is possible to search a document library folder location specifically?  We want the search to only provide results from a specific folder.

If this is possible how do you do this?

-Nima

**Comment by phillipharding** [comment]
Add an expression such as below to your search query

```path:https://<tenant>.sharepoint.com/sites/<siteurl>/<library>/<folder>```
_or_
```path:"{\SiteCollection.URL}/<library>/<folder>"```

_e.g._
      `https://contoso.sharepoint.com/sites/site01/Documents/Folder1`

Ref:
[https://www.techmikael.com/2014/05/s15e03-query-variables-constant-trouble.html](https://www.techmikael.com/2014/05/s15e03-query-variables-constant-trouble.html)

**Comment by FranckyC** [comment]
Thanks @phillipharding for the answer! I close this one as it is not related to the solution itself but more a KQL question.
