### ISSUE TITLE
Page not refreshing

### ISSUE THREAD

**Issue by tommysegoro** [microsoft-search/pnp-modern-search#560]
**Version used**
3.15.3

**Describe the bug**
When the first page loads eg. the homepage, I typed in search keyword and hit Enter. SharePoint redirects me to the search results page correctly. I then navigate to other pages eg. back to homepage, the search keyword remains in the search box.

This time when I go to the search box and hit Enter again, I can see the URL changes on the browser but nothing happens. I still stay on the homepage. This doesn't happen with the OOTB search.

**To Reproduce**
1. Load SharePoint online site homepage
2. Type keyword in search box, press ENTER
3. From the search results page, click on the Sharepoint icon to be redirected back to homepage
4. Go to search box again, previous keyword should still remain here. Press ENTER. Nothing will happen from this point on unless I refresh the browser.

**Expected behavior**
Search results page open correctly instead of staying on the homepage.

**Comment by wobba** [comment]
Is your scenario a custom search page and using the header search box? And suspect it's related to the routing issue in #537. Does it work if you revert your version?

**Comment by waynel2** [comment]
@wobba - I work with Tommy so I'll try to add some further context.  

Yes, we believe it relates to #537 as we're seeing the same error in the code.  We haven't reverted versions though from what I recall we had the same issue with 3.12 (the version we deployed in May) hence we tried to update to the latest version to resolve the issue.

Steps below:

2. Installed version 3.15.3.0 into global app catalogue (from what I recall we had the same issue with 3.12 hence why we tried to install the latest version)
1. Created a SharePoint Modern communications site
3. Created a custom search results page - https://companyname.sharepoint.com/sites/sitename/SitePages/Results.aspx
4. Updated the custom results page in Search Settings to point to https://companyname.sharepoint.com/sites/sitename/SitePages/Results.aspx
5. Run a search query from the standard SharePoint search box within the header
6. Navigate away from the results page and try to run another search OR click on a page link.
7. After leaving the results page you have to click on links twice to make it work, or if you try to perform another search using the standard SharePoint search box within the header it doesn't work (The url will update with the new search value though the user isn't taken to the custom search page).

Note, we've tried this across multiple tenancies and experience the same result.

thanks for your assistance,

Wayne

**Comment by wobba** [comment]
If related to #537 I pushed a fix for this to the dev branch yesterday.

**Comment by waynel2** [comment]
Thanks @wobba - we tested the fix and its now working as expected:)
