### ISSUE TITLE
Search verticals in filtering out results

### ISSUE THREAD

**Issue by yahookevin** [microsoft-search/pnp-modern-search#561]
**Is your feature request related to a problem? Please describe.**
In the V3 version of Search vertical, we could give the "*Result Source Identifier*" to filter out the results.
E.g. for V3-
![image](https://user-images.githubusercontent.com/67360002/99624721-d7d35b00-2a82-11eb-8a9a-2c854d0b1644.png)
But this feature is not available in the V4 version. Is there any other way to achieve similar functionality? Hard to understand how we can make use of Verticals and Search box together. It seems it's either the verticals or the search box.
**Describe the solution you'd like**
Using the Search verticals, i would be able to filter the results based on result source.
May be filter the results based on the Everything, Videos, People etc..

**Describe alternatives you've considered**
Search box and verticals doesn't seem to work together, its either of the two.
Since we can't give more than 1 result source for the results page, we can't possibly do any other alternatives.
**Additional context**

**Comment by FranckyC** [comment]
Hi @yahookevin actually new verticals act as "visibility" controllers for connected Web Parts. Basically you can now connect multiple search results WPs to one search vertical WP and toggle visibility by tab. This way, you can leverage all the features of search results WP including result source ID. The search setttings are no more included in the verticals.

In your case, you should have the same number of search results WPs configured on the page as your vertical tabs. Each WP having its own configuration.

**Comment by yahookevin** [comment]
Thanks @FranckyC . This will help me with the functionality I'm looking for.
Cheers.
