### ISSUE TITLE
Not able to compile solution

### ISSUE THREAD

**Issue by marschallphilipp** [microsoft-search/pnp-modern-search#562]
**Version used**
4.0.0

**Describe the bug**
I´m not able to compile the webparts in order to slightly change the person details shown for person layout option.
I can install npm within the folders "pnp-modern-search-4.0.0-preview\search-extensibility" and "pnp-modern-search-4.0.0-preview\search-extensibility-demo" but I get errors when trying install npm in "pnp-modern-search-4.0.0-preview\search-parts" folder.

**To Reproduce**
1. Download source code of version 4.0.0 from GitHub
2. change to folder "xxxx\search-parts"
3. try to install npm (npm install)
4. because of the errors shown in screenshot I´m not able to serve or package the solution

**Expected behavior**
npm install should run without error in order to package the solution afterwards

**Screenshots**
![2020-11-19 09_12_26-Windows PowerShell](https://user-images.githubusercontent.com/6168689/99645631-c0c74580-2a4f-11eb-989e-231c74c6aa27.png)

**Comment by wobba** [comment]
Read the docs :) https://microsoft-search.github.io/pnp-modern-search/how-to-contribute/

**Comment by marschallphilipp** [comment]
Thank you :-) Can I ask for additional help though?

Steps I followed are:
1) change to "xxx\pnp-modern-search-4.0.0-preview\search-extensibility"
2) run
`npm i`
according [https://microsoft-search.github.io/pnp-modern-search/how-to-contribute/](url)
3) run
`gulp bundle`
according [https://microsoft-search.github.io/pnp-modern-search/how-to-contribute/](url)
4) run
`npm link`
according [https://microsoft-search.github.io/pnp-modern-search/how-to-contribute/](url)

5) change to "xxx\pnp-modern-search-4.0.0-preview\search-parts"
6) run
`npm link @pnp/modern-search-extensibility`
according [https://microsoft-search.github.io/pnp-modern-search/how-to-contribute/](url)
So far so good...

When trying to run
`gulp bundle` or `gulp serve`
I´m getting an error:
`[08:50:47] Local gulp not found in \pnp-modern-search-4.0.0-preview\search-parts
[08:50:47] Try running: npm install gulp`
When running `npm install gulp` I´m getting different error (`Error: Cannot find module 'webpack'`)

Any idea? Thank you very much!

**Comment by wobba** [comment]
Step 7. `npm i`, then `gulp bundle` in the xxx\pnp-modern-search-4.0.0-preview\search-parts folder

**Comment by marschallphilipp** [comment]
No luck, still getting these errors....

`npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/microsoftgraph/msgraph-typescript-typings.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\p.marschall\AppData\Roaming\npm-cache\_logs\2020-11-23T15_42_56_508Z-debug.log`

**Comment by FranckyC** [comment]
Hmm seems to be an env issue. What version of Node.js are you sing? You should use v10.x. Also make sure you don't have a global .npmrc file that could interfer somewhere.

If doesn't work, you can still use [pnpm](https://pnpm.js.org/) instead of npm to install dependencies.

**Comment by marschallphilipp** [comment]
I´m using node v10.23.0
`PS C:\pnp-modern-search-4.0.0-preview\search-parts> node -v
v10.23.0`

I have setup a virtual machine and tried all 7 steps above but no luck.
Same errors, I am not able to install npm within the "xxx\search-parts" directory.
 
`PS C:\pnp-modern-search-4.0.0-preview\search-parts> npm i
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated es6-collections@0.5.6: not actively maintained anymore
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number ofnpm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/microsoftgraph/msgraph-typescript-typings.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-12-10T08_17_27_116Z-debug.log

PS C:\pnp-modern-search-4.0.0-preview\search-parts> gulp bundle
[00:18:20] Local gulp not found in C:\pnp-modern-search-4.0.0-preview\search-parts
[00:18:20] Try running: npm install gulp`

I found a .npmrc file in folder "C:\Program Files\nodejs\node_modules\npm" but it´s an empty file and removing it doesn´t help.

**Comment by FranckyC** [comment]
Hi @marschallphilipp  can you try using [pnpm](https://github.com/pnpm/pnpm) instead?

**Comment by FranckyC** [comment]
@marschallphilipp Tested with the latest `feature/v4` branch. Works fine.
- Node v10.19.0
- Windows 10
- Run as administrator

I also remove my `node_modules` folder to perform a clean install.

**Comment by marschallphilipp** [comment]
> Hi @marschallphilipp can you try using [pnpm](https://github.com/pnpm/pnpm) instead?

Big thank you!
Now it worked. First I only used pnpm for step 7, then I realized this does´nt make sense and replaced all npm commands with same pnpm commands. After an error and fixing it by installing git it worked!
Thanks again!

**Comment by bhlaws** [comment]
For anyone else having this issue, using PNPM worked for me, but I also had to install GIT (https://git-scm.com/download/win) to successfully run the final "pnpm install" from the web parts folder

**Comment by wobba** [comment]
@bhlaws as the latest code only requires the main solution any package manager should work. pnpm is my preffered one as well 🙂 We just haven't updated the docs yet to reflect this. The extensibility project is now pulled down as an npm package.
