### ISSUE TITLE
"Show X" number of of items dropdown

### ISSUE THREAD

**Issue by codyrhowe** [microsoft-search/pnp-modern-search#563]
Is it possible to override the value for the 'Number of items per page' setting by building something using the extensibility capabilities? Our users are wanting a dropdown that allows them to show x number of items.

**Comment by FranckyC** [comment]
Hi @codyrhowe , unfortunately this is not currently possible even with extensibility features as this setting is not exposed.

**Comment by codyrhowe** [comment]
@FranckyC, thanks for the quick response.
