### ISSUE TITLE
Show Text Field Column in a List

### ISSUE THREAD

**Issue by renatoromao** [microsoft-search/pnp-modern-search#564]
Hi,

I'm developing a solution that contains the Search Results web part.
I already create an Alias to the managed property and I can see the managed column on the Refiners panel and also on the Manage Columns button.

But the values are empty when showing this property. I already reset the crawl to SharePoint Online but I'm getting the same issue yet.

Do you know if has any delay to show it?

**Comment by wobba** [comment]
If you use the alias using for example the Search Query Tool, do you see a value? Please verify that you get data from the API, before posting this as a web part issue. You can also look at the search request/response from the webpart to verify you are asking for the right values.
