### ISSUE TITLE
Optional filter for query string is not working with Query Template.

### ISSUE THREAD

**Issue by mkchiliveri** [microsoft-search/pnp-modern-search#565]
I have given Query Template as "{searchTerms} {?RefinableString00={QueryString.AssetCategory}}", it will take AssetCategory from query string and shows the proper result but when I do not have the query string in the URL, normal search is not working even though I have given ? before RefinableString00. Same thing is working in SharePoint Query builder.

**Comment by wobba** [comment]
`QueryString` is a custom implementation in the web parts and we have not implemented logic for the {?} notation.

**Comment by mkchiliveri** [comment]
Thanks @wobba for your response, is there any plan implement it in future?

**Comment by wobba** [comment]
@mkchiliveri if demand is there and someone wants to take a stab. I've tagged it as an enhancement for now for anyone to take a stab at if they want to contribute.
