### ISSUE TITLE
Documentation or example for a custom data source

### ISSUE THREAD

**Issue by MarkusLanger** [microsoft-search/pnp-modern-search#566]
Hi,

I am very impressed with the PnP Modern Search solution and the documentation. I have downloaded version 4 preview and would like to develop my own data source.
On [the page](https://microsoft-search.github.io/pnp-modern-search/extensibility/) there is a hint that this should be possible. But I didn’t find any other documentation or example.

Did I miss something?

Best Regards,
Markus

**Comment by FranckyC** [comment]
Hi @MarkusLanger, custom data source is not supported in the open source version as we only limit to search scenarios including SharePoint Search and Microsoft Search. However what you want is still possible either by developing it yourself based on the existing code or use the [original version](https://bit.ly/3kPfAvC).

**Comment by MarkusLanger** [comment]
Hi @FranckyC , thank you for the quick response.

**Comment by wobba** [comment]
If someone wants to build the support for more sources we'll happily accept PR's. And plan is to support this via extensibility libraries as well. If you look at the `MicrosoftSearchDataSource` you get a good idea how to build it.
