### ISSUE TITLE
Filter on fileextension:xlsx causes issues with Results web part display

### ISSUE THREAD

**Issue by melkinsco** [microsoft-search/pnp-modern-search#567]
**Version used**
Ex: 3.15.3.0

**Describe the bug**
User searches for a term, gets a large number of hits, and selects to filter by filetype of .xlsx.  Once that's done, the Search Result web part has display issues.  In this case, there are 282 results.  I can use the arrows to push down to see about 12 and then it appears that the web part allocates space for all of the results.  If I scroll to the bottom, I can get to the pagination and a few more results with a large blank gap in between.  The pagination is turned on and the number of items at one time is set to 15 with up to 10 pages of results.  I cannot get this to happen with other file extensions.  Only xlsx.

**To Reproduce**
1. Search for a term with a lot of results.
2. Filter results by .xlsx extension (either by refiner or by fileextension:xlsx in the search string.)
3. Try to scroll down through the results

**Expected behavior**
Expected to see my 15 results from the first page and the pagination at the bottom.  

**Screenshots**

**Desktop (please complete the following information):**
 - Browser:  Edge Chromium or Chrome both have issues

**Additional context**

**Comment by wobba** [comment]
Which template?

**Comment by melkinsco** [comment]
I was using the Simple List display.  I just tested it against the detailed list and it worked fine.  Thanks!

**Comment by wobba** [comment]
I cannot repro this one. If you order the items different, does it happen? Thinking it has to do with the summary extracted perhaps from one particular item.

**Comment by melkinsco** [comment]
I'll dig in a bit today.  I'm thinking you're right on the summary on a particular item.  Now time to figure out which one.  Thanks for looking into it!

**Comment by melkinsco** [comment]
FYI, it does appear to be an issue with generating the preview of the file.  The files that appear to cause the issues are .xlsx files with pivot tables and graphics in them. The reason I don't see the issues when going to the Details List is because there's no file viewer involved like there is in the Simple List.

**Comment by wobba** [comment]
If you can give me file which cause repro I'll take a look.

**Comment by wobba** [comment]
v3 no longer maintained
