### ISSUE TITLE
Redirecting search queries to PnP Modern Search results page only fires once

### ISSUE THREAD

**Issue by colonelclaypoo** [microsoft-search/pnp-modern-search#57]
Hello,

I'm not sure if this is an issue but I wanted to make you aware of the following:

Based on Mikael Svensons Ignite presentation I was eager to learn that you can redirect search queries to a PnP Modern Search results page. Has anyone encountered the issue that it only works for the initial query?

So from site collection A I'm entering a query that is passed on to site collection B which hosts the results page. The parameters passed are Home.aspx?k=test&ql=2055, for example.

I have configured the result source web part to use the page environments query parameter k.

![image](https://gxcuf89792.i.lithium.com/t5/image/serverpage/image-id/165011iC8AA0B8FB58BF790/image-size/large?v=1.0&px=999)

The search results web part correctly shows hits for the query. However, I can't get a new query to fire.

When I use the out of the box modern page's search box the url in the address bar changes but it's not passed on to the search results web part:

![image](https://gxcuf89792.i.lithium.com/t5/image/serverpage/image-id/165018iA1E0F33AA6A4D899/image-size/large?v=1.0&px=999)

When I refresh the browser page the new query is passed on and the web part shows the new results.

Is anyone experiencing this behaviour?

I though of putting a PnP Modern Search box onto the page for further queries but the results web part can only be connected to one source it seems.

Thanks.

**Comment by FranckyC** [comment]
Hi @colonelclaypoo, thanks for your feedback. Actually this due to the way the search box is implemented and also  the way SharePoint handles page redirection via its own page router. By default, the search box  "listens" the URL only when the URL hash changes ("#"). Unfortunately it doesn't work for query parameters because there is no page postback when you submit your search.

This is definitely something we should improve to get a nice experience.
@wobba do you know an "SPFx" way (via the page router) to catch the event when a query string parameter is changed?

For the hash I use the builtin listener `hashchange`.

**Comment by wobba** [comment]
Could be that some of Elio's approaches from https://www.eliostruyf.com/handling-navigation-in-a-sharepoint-framework-application-customizer/ work for query param changes.

**Comment by FranckyC** [comment]
Yeah but it will introduce a new component in the solution and again, add more complexity to the whole solution. It is too complicated to resolve only this issue in my opinion. We need to think about an other approach, lighter.

**Comment by wobba** [comment]
@FranckyC there's no event in SPFx for this. I'll ping you offline on this.

**Comment by colonelclaypoo** [comment]
Thank you both for processing my feedback. 

So am I correct in understanding that if I want to use the out of the box Microsoft Search search box with a PnP Modern Search reuslts page that for each subsequent query the user has to either reload the results page or go back to the page where the query was fired from?

I was thinking that it if a Results web part could accept queries from two sources, a) the page environment's query parameter from the initial query and b) from a Search Box web part that's on the results page, a user could carry out any subsequent queries from the results page instead of having to navigate back to the page from where the initial query was fired. 

You could then hide the out of the box Microsoft Search search box on the results page and the user would have a friendly experience for carrying out forther search operations.

Sorry for the long winded sentences. Do you know what I mean? This could be a way around the issue.

Thanks

**Comment by wobba** [comment]
@colonelclaypoo you can also wait for the feature where you can re-use the header searchbox with dynamic data with the PnP parts to become available. We announced this at Ignite where I demoed this.  

For your scenario we need to add a listener which picks up the change of the URL, a feature we should look into implementing for this scenario.

**Comment by colonelclaypoo** [comment]
@wobba Okay, understood. Thanks for your support and keep up the good work.
