### ISSUE TITLE
Unable to link the extensibility library – PnP Modern Search (v4)

### ISSUE THREAD

**Issue by MarcoSimon** [microsoft-search/pnp-modern-search#572]
**Version used**
4.0.0-preview

**Describe the bug**
I'd like to follow [the instructions of PnP Modern Search (v4)](https://microsoft-search.github.io/pnp-modern-search/extensibility/#create-an-extensibility-library), but when I try to link the extensibility library with my new library using the _npm link @pnp/modern-search-extensibility_ command, it throws an error.

**To Reproduce**
1. Create a new SPFx library using the yeoman generator
2. Navigate to the project folder in your favourite console (I tried in PowerShell console as well as in VSCode console)
3. Execute the command (as it is described in documentation): `npm link @pnp/modern-search-extensibility`

**Expected behavior**
I expected the script to run properly and successful. But unfortunately, the following error is thrown:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@pnp%2fmodern-search-extensibility - Not found
npm ERR! 404 
npm ERR! 404  '@pnp/modern-search-extensibility@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Screenshots**
![2020-11-23-15_51_39](https://user-images.githubusercontent.com/6904649/99977721-4aa34580-2da5-11eb-8ce2-0b5dde97f89c.png)

**Desktop**
 - Windows 10 Pro, Version 1909 (Build 18363.1198)
 - VSCode 1.51.1 (Node 12.14.1)
 - PowerShell 5.1.18362.1171 (Node 12.18.3)
 - npm 6.14.6
 - yeoman generator @microsoft/generator-sharepoint@1.11.0

**Comment by FranckyC** [comment]
Hi @MarcoSimon did you build the `@pnp/modern-search-extensibility` project first using `gulp bundle`?

**Comment by MarcoSimon** [comment]
Hi @FranckyC, I was stuck with a few other issues (so I had to switch to Node v10.x due to a gulp error `ReferenceError: primordials is not defined` with Node 12.x for example), but finally it works for me!

Thanks a lot for your hint, I didn't found anything about it, neither in the documentation for the search-extensibility nor in the README files of the search-extensibility or the search-extensibility-demo.

**Comment by wobba** [comment]
https://microsoft-search.github.io/pnp-modern-search/how-to-contribute/#setting-up-the-solution-locally

**Comment by heatherzhang080** [comment]
I got this same problem too... Followed all the steps but still same error

**Comment by wobba** [comment]
@heatherzhang080 if you have everything installed correctly in terms of SPFx versions and node it should just work. Works for me with both npm and pnpm.
