### ISSUE TITLE
V4 - Unable to choose Content Source for "Microsoft Search"

### ISSUE THREAD

**Issue by jimmywim** [microsoft-search/pnp-modern-search#573]
Not sure if this is something still on the backlog or has intended to be there but not working right...

I've used the UI in the Admin centre to create a Content Source that has 1400 odd items in it (DevOps OOTB connector, to a specific Team Project)

When I use the v4 results web part and I choose Microsoft Search, I can tell it to return External Items, but running queries returns the error:

`SearchRequest Invalid Content Source cannot be null or empty for entity type - ExternalItem`

I'm assuming if you pick "External Item" it would then fetch from `/external/connections` to let you pick a Connector that's then used for this query. Otherwise, I'm also assuming the plan is for this web part to somehow be able to query over or roll up content from multiple connectors or sources in some way?

**Comment by FranckyC** [comment]
Hi @jimmywim, try with the latest build on the v4 branch. We've added the `contentSource` parameter with the connection id.

**Comment by FranckyC** [comment]
@jimmywim can I close this one for now? Does it work with the latest code on develop?

**Comment by jimmywim** [comment]
@FranckyC Giving it a try now, but the dropdown doesn't populate:

![image](https://user-images.githubusercontent.com/3036301/100363145-3dc86100-2ff4-11eb-9320-d6de22974281.png)

And if I put the GUID manually, it doesn't update either.

I created the Content Source using the UI in the M365 Admin Centre.

**Comment by FranckyC** [comment]
@jimmywim for now, the dropdown does not lookup through the connection ids. Can you inspect the HTTP query sent using the browser console? It should include your id if added manually.

**Comment by FranckyC** [comment]
@jimmywim nevermind, my mistake, the property was never set in the code. I updated the pacakges so this time you could use your custom IDs.

**Comment by FranckyC** [comment]
I close this one for now. An other issue has been reported #607
