### ISSUE TITLE
Stopped working in IE11 only

### ISSUE THREAD

**Issue by allafridman** [microsoft-search/pnp-modern-search#574]
**Version used**
Ex: 3.14.2.0
All works perfect in Edge and Chrome.
In IE 11 getting the error:

**Search webpart is producing and Error: Failed to load component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchResultsWebPart). Original error: Failed to load URL  https://publiccdn.sharepointonline.com/company.sharepoint.com/sites/apps/ClientSideAssets/890affef...
for resource 'search-results-web-part' in component '42ad2740-3c60-49cf-971a-c44e33511b93' (SearchResultsWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.**

**Comment by SPDEV20201** [comment]
We are experiencing the same issue IE11 only, tested on two tenants with versions: 3.15.10 and 3.15.3.0. 
Chrome and Edge have tested fine

[SPLoaderError.loadComponentError]:
Failed to load component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchResultsWebPart). Original error: Failed to load entry point from component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchResultsWebPart). Original error: Error loading https://component-id.invalid/42ad2740-3c60-49cf-971a-c44e33511b93_3.15.3
 Cannot redefine non-configurable property 'includes'

**Comment by FranckyC** [comment]
Hi, we don't support IE11 for Modern Search Web Parts.

**Comment by SteveBre** [comment]
We have the same issue. Can understand that nobody want to develop for old applications, but the reality is that many companies are still in the transition phase to move from IE to a modern browser. This means for us we cannot use the web parts anymore and we have to find an alternative. We have another 3rd party web part which stopped working at the same time and the developers will fix it now. So not sure what was changed in SP Online recently which caused this

**Comment by jonthenerd** [comment]
There look to be two issues being reported. Creating a new issue to track the IE11 cannot redefine non-configurable property, which only started occurring today without any updates to the solution in our tenant.

**Comment by wobba** [comment]
Hi, from your description it seems the web parts were working with IE11 until recently? Can you verify this? To isolate if it's an issue with SPFx or the web parts.

And as @FranckyC says, IE11 is not a goal, but if it's easy to support we can probably do so - as we have up until now.

**Comment by wobba** [comment]
Tracking in #576
