### ISSUE TITLE
IE11 - Failed to load entry point from component... Cannot redefine non-configurable property 'includes'

### ISSUE THREAD

**Issue by jonthenerd** [microsoft-search/pnp-modern-search#576]
**Version used**
3.14.1

**Describe the bug**
Starting today, we're seeing an issue in our tenant using this solution (which has not been updated for some time), only in IE. Error text is: 

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
Technical Details
[SPLoaderError.loadComponentError]:
Failed to load component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchResultsWebPart). Original error: Failed to load entry point from component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchResultsWebPart). Original error: Error loading https://component-id.invalid/42ad2740-3c60-49cf-971a-c44e33511b93_3.14.1
 Cannot redefine non-configurable property 'includes'

INNERERROR:
Failed to load entry point from component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchResultsWebPart). Original error: Error loading https://component-id.invalid/42ad2740-3c60-49cf-971a-c44e33511b93_3.14.1
 Cannot redefine non-configurable property 'includes'
CALLSTACK:
Error
   at t._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:849936)
   at t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:849454)
   at t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:994853)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:1035751)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:1031790)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:1024059)
   at a (https://tenant.sharepoint.com/sites/appcat/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_c3ed204f9d0e1833b30fb9112dbed878.js:1:26174)
   at Anonymous function (https://tenant.sharepoint.com/sites/appcat/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_c3ed204f9d0e1833b30fb9112dbed878.js:1:26321)
   at c (https://tenant.sharepoint.com/sites/appcat/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_c3ed204f9d0e1833b30fb9112dbed878.js:1:30318)

**To Reproduce**
Open IE to a page with the search results webpart. We haven't narrowed it down any further than that yet.

**Expected behavior**
Render in IE11, which is still supported by Microsoft in SharePoint Online and was working fine until today. Yes we're getting off of IE11 soon. Nobody likes supporting it still.

Related comment in #574

**Comment by jonthenerd** [comment]
Reading online, this seems to happen when two polyfills are included on the same page for the same method. In this case, likely string.includes. The only place in the codebase which has ".includes" is https://github.com/microsoft-search/pnp-modern-search/blob/ae2dd0862d881da74817cc419eb6fbc47a7b5760/search-parts/src/services/TemplateService/BaseTemplateService.tsx . Reading that code, it doesn't appear to even be used, just imported.

**Comment by jonthenerd** [comment]
We've got it working by removing line 2 of the above mentioned file from the current source. Continuing to test. Any subsequent code that actually needs the polyfill (which I couldn't find any in this repo, but some dependency could potentially need it) should find Microsoft's polyfill on the page already. This should get us back working again. 

Can the project consider removing this polyfill (and potentially others, as no doubt this will happen more if Microsoft continues adding them)?

**Comment by jonthenerd** [comment]
Test went well. Deployed modified solution and got our users going again. We're hoping to be off of IE11 in the coming weeks...

**Comment by paulryan** [comment]
FWIW we encountered the same issue and arrived at the same solution independently. No undesired side effects identified as yet.

**Comment by prashanth1261** [comment]
I have also faced the same issue, thanks Jonthenerd for your suggestion. It works removing the second line.

**Comment by wobba** [comment]
If it suddenly stopped working, it's a SPFx issue imo. Feel free to PR a solution which is future-proof and won't break if we suddenly removes this import.

**Comment by Siphlex** [comment]
Just here to mention that it indeed stopped working here also starting from this monday on IE only.

**Comment by wobba** [comment]
I logged a question/issue at sp-dev-docs on how best to avoid these types of issues.

**Comment by wobba** [comment]
@FranckyC are we actually using this polyfill anywhere? Cannot find a .includes reference in code? Same with array and is-nan. If we're not using them we could remove them as well.

**Comment by sithender** [comment]
@jonthenerd @wobba 

I commented 2nd a line of code for https://github.com/microsoft-search/pnp-modern-search/blob/ae2dd0862d881da74817cc419eb6fbc47a7b5760/search-parts/src/services/TemplateService/BaseTemplateService.tsx

But I Am not sure how to build and package the solution as I am new to client-side web parts. Could you please share any documentation if you have for step-by-step instructions for building and shipping the solution to the App catalog?

Thanks
sith

**Comment by Siphlex** [comment]
hey @sithender,

If you have downloaded the pnp package.
1) navigate to the following folder:  XXXXX\pnp-modern-search-3.13.0\pnp-modern-search-3.13.0\search-parts
2) Open this folder in Visual studio code 
3) Open a new terminal
4) Type: npm i and enter
5) Type: gulp bundle --ship and enter
6) Type: gulp package-solution --ship and enter
7) The spkkg now becomes visible in the sharepoint folder XXX\pnp-modern-search-3.13.0\pnp-modern-search-3.13.0\search-parts\sharepoint\solution

That's how I did the modification.

**Comment by wobba** [comment]
We'll most likely remove the line(s) in question as we're not using them.

**Comment by wobba** [comment]
Added a fix, which will be included in 3.17 release.

**Comment by sithender** [comment]
> Added a fix, which will be included in 3.17 release.

Hello Wobba,
Thank you for the update.  Any update on the release date for 3.17 ?

**Comment by wobba** [comment]
We'll try get a January release out. Let me know if it's urgent and you cannot build yourself and I'll provide a download link until we do a release.

**Comment by sithender** [comment]
> We'll try get a January release out. Let me know if it's urgent and you cannot build yourself and I'll provide a download link until we do a release.

That would be great Wobba. Could you please share the link?. I tried from my side but got a different issue when deployed. Might be issue with building the solution. Hence could you please share the link Please?

**Comment by wobba** [comment]
@sithender Let me know if this 3.17.0 pre-release works for you: https://1drv.ms/u/s!AsQPRl4COMyeoq42TbOuuSoIg7Vwag?e=MU3PoS

**Comment by sithender** [comment]
> @sithender Let me know if this 3.17.0 pre-release works for you: https://1drv.ms/u/s!AsQPRl4COMyeoq42TbOuuSoIg7Vwag?e=MU3PoS

Thank you Wobba

**Comment by wobba** [comment]
Want to follow up that this should now be resolved from the SharePoint side - meaning old versions should now work (if it's rolled out 100%)

**Comment by Tin-Bui** [comment]
Hi @wobba , I deployed the pre-release version above of your, but the Search Result web part still not render in IE11.
![image](https://user-images.githubusercontent.com/33175306/110591707-82f05780-81cd-11eb-9a6e-d9dc6b8cbb19.png)

I didn't have much luck with the latest [3.18 release](https://github.com/microsoft-search/pnp-modern-search/releases/download/v3.18.0/pnp-modern-search-parts.sppkg) either.
