### ISSUE TITLE
Filters CSS

### ISSUE THREAD

**Issue by afinn-tech** [microsoft-search/pnp-modern-search#577]
hi
is it possible to edit the css for 
![Screenshot 2020-11-25 at 20 47 31](https://user-images.githubusercontent.com/65241024/100280173-a7e2f680-2f5f-11eb-8c53-446092692c3b.png)
just to add width to the css?

.calloutMain-864 {
    background-color: rgb(255, 255, 255);
    overflow: hidden auto;
    position: relative;
**width: fit-content;**
}

**Comment by wobba** [comment]
This one is tricky as it's a component. Workaround is to make your window wider, or zoom out to make it wider. That allows easy entry.
