### ISSUE TITLE
Errors while installing "pnp-modern-search-extensibility.sppkg".

### ISSUE THREAD

**Issue by shekhar0603** [microsoft-search/pnp-modern-search#579]
**Version used**
pnp-modern-search v4.0.0

**Issue Description**
This is regarding Pnp-modern-search-webpart  v4.0.

We are trying to use webparts in Sharepoint Online site available at "https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.0.0-preview."

We have downloaded 2 sppkg files, namely : "pnp-modern-search-extensibility.sppkg" and "pnp-modern-search-parts.sppkg".

After adding  "pnp-modern-search-extensibility.sppkg" to app catalog, when we are adding this app we are facing below error:

![image](https://user-images.githubusercontent.com/39938835/100342129-8b989580-3003-11eb-9191-23c4879c7357.png)

Details: Deployment failed in host web https://xxxxxxxx.sharepoint.com/sites/SearchTest for app PnP Modern Search - Search Extensibility Library Core/f13a5866-004f-4219-b078-69731f848bd1. Microsoft.SharePoint.SPException: Feature definition with Id 96dcffa8-2c69-47ec-ba5c-770213aeb4fe failed validation, file '/96dcffa8-2c69-47ec-ba5c-770213aeb4fe/Library_96dcffa8-2c69-47ec-ba5c-770213aeb4fe.xml', line 1, character 1383: The 'Type' attribute is invalid - The value 'Library' is invalid according to its datatype 'http://schemas.microsoft.com/sharepoint/:ClientComponentType' - The Enumeration constraint failed. at Microsoft.SharePoint.Administration.SPSolutionPackage.FeatureXmlValidationCallback.XmlValidationCallBack(Object sender, ValidationEventArgs evtargs) at System.Xml.Schema.XmlSchemaValidator.CheckAttributeValue(Object value, SchemaAttDef attdef) at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String lName, String ns, XmlValueGetter attributeValueGetter, String attributeStringValue, XmlSchemaInfo schemaInfo) at System.Xml.XsdValidatingReader.ValidateAttributes() at System.Xml.XsdValidatingReader.ProcessElementEvent() at System.Xml.XsdValidatingReader.Read() at Microsoft.SharePoint.Utilities.SPUtility.XsdValidateXml(XmlTextReader xmlStreamReader, String friendlyName, String pathXsdFile, String tagExpectedRootNode, Int32 desiredPathVersion, ValidationEventHandler xsdValEventHandler) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ValidateAppPartFeatureXsd(PackagePart appPart, Guid featureGuid) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractElementPartToWsp(PackagePart elementPart, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId, SPAppInstance appInstance, Guid featureId, String featureWspRelativeDirectory) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractFeaturePartToWsp(SPFeatureAppPart featureAppPart, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId, SPAppInstance appInstance) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractFeaturePartsToWsp(List`1 featureAppParts, SPWeb web, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.GenerateAndActivateUserSolutionFromPackage(SPWeb web, SPAppPackage appPackage, Guid productId, String solutionName, SPSolutionLevel solutionLevel) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.InstallOrUpgrade(SPSite site, Nullable`1& solutionId, Boolean& swapNeeded)

We have tried to add the same on multiple environments but every time same error occurs.

**To Reproduce**
1. Download "pnp-modern-search-extensibility.sppkg" from https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.0.0-preview.
2. Add it to your app catalog.
3.Try adding this app in your site.
4. We get error while installing this app.

**Expected behavior**
App should install so that we can use pnp modern search webpart.

**Screenshots**
![image](https://user-images.githubusercontent.com/39938835/100342716-648e9380-3004-11eb-9767-987c9ce32e55.png)

**Comment by AndyBolam** [comment]
I'm also having this issue after deploying the packages yesterday.  Tried full removal and re-adding to app catalog, still same deployment error.

**Comment by skothari120790** [comment]
I am also facing the same issue while deploying the "pnp-modern-search-extensibility.sppkg" package at Site Collection's App catalog. I recreated the package after forking the solution and tried to deploy in two different tenants but still it is giving the same error.

Regards,
Sanjay

**Comment by FranckyC** [comment]
Are you using tenant or site collection app catalog?

**Comment by AndyBolam** [comment]
@FranckyC Tenant app catalog, I didn't deploy the solution tenant wide as I wanted to select the sites I installed the web parts on.
Should the extensibility package be deployed and available tenant wide?

**Comment by shekhar0603** [comment]
> Are you using tenant or site collection app catalog?

@FranckyC : We are tried at both levels . 

"pnp-modern-search-parts.sppkg" gets installed but "pnp-modern-search-extensibility.sppkg" gives error.

**Comment by FranckyC** [comment]
No the both catalogs should work. I'll try to take a look and see if I can repro.

**Comment by FranckyC** [comment]
It seems I can't repro on my env :(. Can you try to build the packages from the latest feature/v4 branch and see if still the same?

**Comment by AndyBolam** [comment]
Thanks @FranckyC - will try to build from the latest release packages sometime today (hopefully) and will report back here with findings.

**Comment by AndyBolam** [comment]
I've built the packages from the provided source code for the latest release, unfortunately I get the same behaviour, the modern search web parts package installs fine, but the extensibility package does not install.  I am using a modern Communication Site, which has had several lists and libraries provisioned using the PnP provisioning tool - is there anything that I should be checking on the site before I attempt to install the app?

**Comment by shekhar0603** [comment]
> It seems I can't repro on my env :(. Can you try to build the packages from the latest feature/v4 branch and see if still the same?

@FranckyC - Still getting same issue.

I have downloaded Source Code from https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.0.0-preview and build the solution. After adding same I am still facing error.

**Comment by FranckyC** [comment]
Unfortunatelty I can't repro your issue even after using multiple environments. It is like SPFx library component feature was not supported on your tenant. Is there someting special about your tenants (like education tenant, first-release)? @wobba can you try with multiple tenants if you have the chance?

**Comment by FranckyC** [comment]
Coult it be related https://github.com/SharePoint/sp-dev-docs/issues/6496? If the issue persists, my suggestion is to follow the discussion in sp-dev-docs as it appear to be an env issue.

**Comment by shekhar0603** [comment]
> Unfortunatelty I can't repro your issue even after using multiple environments. It is like SPFx library component feature was not supported on your tenant. Is there someting special about your tenants (like education tenant, first-release)? @wobba can you try with multiple tenants if you have the chance?

@FranckyC - I have other SPFx webparts running perfectly fine on my tenant. Getting issue for this one only.

**Comment by backrowbloke** [comment]
I get the same after adding to the tenant app catalog

`Microsoft.SharePoint.SPException: Feature definition with Id 96dcffa8-2c69-47ec-ba5c-770213aeb4fe failed validation, file '/96dcffa8-2c69-47ec-ba5c-770213aeb4fe/Library_96dcffa8-2c69-47ec-ba5c-770213aeb4fe.xml', line 1, character 1383: The 'Type' attribute is invalid - The value 'Library' is invalid according to its datatype 'http://schemas.microsoft.com/sharepoint/:ClientComponentType' - The Enumeration constraint failed. at Microsoft.SharePoint.Administration.SPSolutionPackage.FeatureXmlValidationCallback.XmlValidationCallBack(Object sender, ValidationEventArgs evtargs) at System.Xml.Schema.XmlSchemaValidator.CheckAttributeValue(Object value, SchemaAttDef attdef) at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String lName, String ns, XmlValueGetter attributeValueGetter, String attributeStringValue, XmlSchemaInfo schemaInfo) at System.Xml.XsdValidatingReader.ValidateAttributes() at System.Xml.XsdValidatingReader.ProcessElementEvent() at System.Xml.XsdValidatingReader.Read() at Microsoft.SharePoint.Utilities.SPUtility.XsdValidateXml(XmlTextReader xmlStreamReader, String friendlyName, String pathXsdFile, String tagExpectedRootNode, Int32 desiredPathVersion, ValidationEventHandler xsdValEventHandler) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ValidateAppPartFeatureXsd(PackagePart appPart, Guid featureGuid) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractElementPartToWsp(PackagePart elementPart, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId, SPAppInstance appInstance, Guid featureId, String featureWspRelativeDirectory) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractFeaturePartToWsp(SPFeatureAppPart featureAppPart, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId, SPAppInstance appInstance) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractFeaturePartsToWsp(List`1 featureAppParts, SPWeb web, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.GenerateAndActivateUserSolutionFromPackage(SPWeb web, SPAppPackage appPackage, Guid productId, String solutionName, SPSolutionLevel solutionLevel) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.InstallOrUpgrade(SPSite site, Nullable`1& solutionId, Boolean& swapNeeded)`

Notes:

- I am not Tenant Admin, but I am SharePoint Admin with full access to admin centre and app catalogue site
- Tenant is a standard UK based tenancy, standard release
- Package has installed to other tenancies OK where I am Tenant Admin

**Comment by FranckyC** [comment]
Thank you for the update @backrowbloke! I'll close this one for now. Let us know if you encounter other issues.
