### ISSUE TITLE
Search Results web part - displayed columns, data sources, Slots

### ISSUE THREAD

**Issue by mcasaz** [microsoft-search/pnp-modern-search#580]
version used: v4 Preview on Communication site, Chrome

I don't see an option to customise the columns displayed in the search results web part; checking/unchecking Selected Properties doesn't seem to have an effect

I also don't see the source options showed in the [documentation](https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/) (SharePoint Search or Microsoft Search)

I can't see the Slots options either 

![image](https://user-images.githubusercontent.com/33139177/100373686-71fb4c00-300b-11eb-9e0d-d49e1453f54e.png)

![image](https://user-images.githubusercontent.com/33139177/100373702-79baf080-300b-11eb-8601-834c70dff7cc.png)

**Comment by FranckyC** [comment]
@mcasaz probably because you are using v3 instead of v4 :). Make sure you add "PnP- Search Results" Web Part instead of "Search Results"

**Comment by mcasaz** [comment]
> @mcasaz probably because you are using v3 instead of v4 :). Make sure you add "PnP- Search Results" Web Part instead of "Search Results"

I'm using V4, mentioned in the first line of my post

**Comment by FranckyC** [comment]
@mcasaz the screenshots you provided refer to the v3. So my guess is you added v3 Web Parts on the page  instead of v4 despite you deployed the v4 solution. So my question. To make sure you use only v4, remove the v3 SPFx solution from your app catalog.

**Comment by mcasaz** [comment]
@FranckyC sorry You were right, must have mixed that up at some point.
When I select Microsoft Search I get this error. I am using an SP Admin (and global admin) account
![image](https://user-images.githubusercontent.com/33139177/100589887-f263ca80-32f3-11eb-8587-05747ff3ec91.png)

**Comment by wobba** [comment]
@mcasaz Can you use the SharePoint provider? The Graph provider requires consent to API's. https://microsoft-search.github.io/pnp-modern-search/installation/#installation
