### ISSUE TITLE
Cannot add managed properties to the list in v4

### ISSUE THREAD

**Issue by wobba** [microsoft-search/pnp-modern-search#583]
**Version used**
4.0-prerelease

**Describe the bug**
When using the SP provider and navigating to the `Selected properties` list you cannot manually type in managed properties you want retrieved. Once you exit the box the setting is removed. The pre-selected list seems fixed.

If `Layout slots` is the correct approach to add in more managed properties, then the `Selected properties` section should be removed.

**Expected behavior**
A uniform intuitive way to add properties to be used in the templates.

**Comment by FranckyC** [comment]
@wobba so you are not able to add managed property to the "Selected properties" field manually, even after pressing "Enter"? I'm not able to reproduce your issue :(. The slots configuration and `Slot field` dropdown only lists the fields extracted from the data source response and therefore your selected properties for the SharePoint data source. It means, it is better to first get your results and then configure slots. However, if you already know the field name you can also type its name in the slot field dropdown manually and press enter the same way as selected proeprties

**Comment by wobba** [comment]
As per our discussion, requiring "ENTER" is acceptable, but not ideal :)
