### ISSUE TITLE
gulp bundle errors in both folders search-parts and search-extensibility-demo

### ISSUE THREAD

**Issue by MKGy** [microsoft-search/pnp-modern-search#584]
**Version used**
feature/v4

**Describe the bug**
Having gulp bundle  errors with web parts search-parts and search-extensibilit-demo.
Strangely, the first time I installed the Version 4, I was able to successfully gulp bundle search-parts. Now, I can't gulp bundle neither search-parts nor search-extensibility-demo.

Note: I can successfully gulp bundle search-extensibility

**To Reproduce**

1. Clone feature/v4 branch
2. Navigate to folder search-extensibility
3. run npm i
4. run gulp bundle
5. run npm link
6. Navigate to folder search-extensibility-demo
7. run npm i
8. run npm link @pnp/modern-search-extensibility
9. run gulp bundle

**Expected behavior**
Expected a clean run through the gulp bundle process in order for me to then run the following commands to generate an .spkgg file: 
1. gulp package-solution --ship
2. gulp bundle --ship 

**Screenshots**
![image](https://user-images.githubusercontent.com/64076713/100595751-a157d480-32fb-11eb-8add-a2ec6c10064f.png)

**Desktop (please complete the following information):**
 - Browser : chrome, edge

**Additional context**
none

**Comment by FranckyC** [comment]
Hi @MKGy, should be fixed in the `feature/v4` branch. Can you confirm?

**Comment by MKGy** [comment]
Gulp bundle is processing fine now. Thanks
