### ISSUE TITLE
Unable to see best bets data in query

### ISSUE THREAD

**Issue by RiddhiKarani** [microsoft-search/pnp-modern-search#585]
i added a best bet on the site with query rules, when i use the OOB search result page i can see the promoted result come up however on the PnP search result page with list template i do not see the best bet come up

also in the developer tool in the query the secondaryqueryresults i do not see the data

![image](https://user-images.githubusercontent.com/18136022/100604491-a41eed80-332c-11eb-9968-01036c2d39ae.png)

**Comment by wobba** [comment]
https://github.com/microsoft-search/pnp-modern-search/blob/main/docs/search-parts/templating.md#accessing-items

**Comment by RiddhiKarani** [comment]
@wobba the template for list already has the promoted results , the query is not returning data

**Comment by wobba** [comment]
You should check the issued query, and see that it triggers on the query rule you have for promoted results. There's no magic as long as you have enabled query rules in the web part.

![image](https://user-images.githubusercontent.com/51104/100620071-44b9e100-331e-11eb-8dba-0e6330dd7c7e.png)

**Comment by RiddhiKarani** [comment]
@wobba  i did enable the query rules setting in the webpart, for the same search query i see the promoted result on the OOB sharepoint search page but not on the pnp webpart query

**Comment by wobba** [comment]
You need to look at the response JSON and see if your query rule triggered. Also, can you paste your request JSON?

**Comment by RiddhiKarani** [comment]
@wobba  

see below the query rule configured - 

![image](https://user-images.githubusercontent.com/18136022/100849487-a9a14280-34a8-11eb-8db9-55882da4fbc5.png)

the OOB search result page shows the best bet - 

![image](https://user-images.githubusercontent.com/18136022/100849549-bc1b7c00-34a8-11eb-8523-b159137b1b07.png)

the PnP search returns only result not  the best bet - 

![image](https://user-images.githubusercontent.com/18136022/100849607-d05f7900-34a8-11eb-9396-000526e93f3a.png)

here is the response json of the pnp web part query - 

{"ElapsedTime":62,"PrimaryQueryResult":{"CustomResults":[],"QueryId":"3374e862-fc99-4a34-8258-e61ea73bfb53","QueryRuleId":"00000000-0000-0000-0000-000000000000","RefinementResults":null,"RelevantResults":{"GroupTemplateId":null,"ItemTemplateId":null,"Properties":[{"Key":"GenerationId","Value":"9223372036854775806","ValueType":"Edm.Int64"},{"Key":"indexSystem","Value":"","ValueType":"Edm.String"},{"Key":"ExecutionTimeMs","Value":"47","ValueType":"Edm.Int32"},{"Key":"QueryModification","Value":"test Path:\"https://akuminadev02.sharepoint.com/sites/delivery-cloud-qa-maindev02_112020\" -ContentClass=urn:content-class:SPSPeople","ValueType":"Edm.String"},{"Key":"RenderTemplateId","Value":"~sitecollection/_catalogs/masterpage/Display Templates/Search/Group_Default.js","ValueType":"Edm.String"},{"Key":"StartRecord","Value":"0","ValueType":"Edm.Int32"},{"Key":"IsLastBlockInSubstrate","Value":"true","ValueType":"Edm.Boolean"},{"Key":"IsFirstBlockInSubstrate","Value":"false","ValueType":"Edm.Boolean"},{"Key":"IsFirstPinnedResultBlock","Value":"false","ValueType":"Edm.Boolean"},{"Key":"IsLastPinnedResultBlock","Value":"false","ValueType":"Edm.Boolean"},{"Key":"IsFirstRankedResultBlock","Value":"true","ValueType":"Edm.Boolean"},{"Key":"IsLastRankedResultBlock","Value":"true","ValueType":"Edm.Boolean"},{"Key":"MixedTableOrder","Value":"0","ValueType":"Edm.Int32"},{"Key":"GeoLocationSource","Value":"NAM","ValueType":"Edm.String"}],"ResultTitle":null,"ResultTitleUrl":null,"RowCount":1,"Table":{"Rows":[{"Cells":[{"Key":"Rank","Value":"0","ValueType":"Edm.Double"},{"Key":"DocId","Value":"18992572461292055","ValueType":"Edm.Int64"},{"Key":"Title","Value":"test","ValueType":"Edm.String"},{"Key":"Path","Value":"https://akuminadev02.sharepoint.com/sites/delivery-cloud-qa-maindev02_112020/Shared Documents/test.docx","ValueType":"Edm.String"},{"Key":"Created","Value":"2020-11-24T07:26:50.0000000Z","ValueType":"Edm.DateTime"},{"Key":"Filename","Value":"test.docx","ValueType":"Edm.String"},{"Key":"SiteLogo","Value":null,"ValueType":"Null"},{"Key":"PictureThumbnailURL","Value":null,"ValueType":"Null"},{"Key":"ServerRedirectedPreviewURL","Value":"https://akuminadev02.sharepoint.com/sites/delivery-cloud-qa-maindev02_112020/_layouts/15/Doc.aspx?sourcedoc={5272dab8-549c-4a2b-9453-e48a8644bceb}&action=imagepreview","ValueType":"Edm.String"},{"Key":"ServerRedirectedURL","Value":"https://akuminadev02.sharepoint.com/sites/delivery-cloud-qa-maindev02_112020/_layouts/15/Doc.aspx?sourcedoc=%7B5272DAB8-549C-4A2B-9453-E48A8644BCEB%7D&file=test.docx&action=default&mobileredirect=true&DefaultItemOpen=1","ValueType":"Edm.String"},{"Key":"HitHighlightedSummary","Value":"","ValueType":"Edm.String"},{"Key":"FileType","Value":"docx","ValueType":"Edm.String"},{"Key":"contentclass","Value":"STS_ListItem_DocumentLibrary","ValueType":"Edm.String"},{"Key":"ServerRedirectedEmbedURL","Value":"https://akuminadev02.sharepoint.com/sites/delivery-cloud-qa-maindev02_112020/_layouts/15/Doc.aspx?sourcedoc={5272dab8-549c-4a2b-9453-e48a8644bceb}&action=interactivepreview","ValueType":"Edm.String"},{"Key":"DefaultEncodingURL","Value":"https://akuminadev02.sharepoint.com/sites/delivery-cloud-qa-maindev02_112020/Shared%20Documents/test.docx","ValueType":"Edm.String"},{"Key":"owstaxidmetadataalltagsinfo","Value":"","ValueType":"Edm.String"},{"Key":"Author","Value":"Riddhi Karani","ValueType":"Edm.String"},{"Key":"AuthorOWSUSER","Value":"rkarani@akuminadev02.onmicrosoft.com | Riddhi Karani | 693A30232E667C6D656D626572736869707C726B6172616E6940616B756D696E6164657630322E6F6E6D6963726F736F66742E636F6D i:0#.f|membership|rkarani@akuminadev02.onmicrosoft.com","ValueType":"Edm.String"},{"Key":"SPSiteUrl","Value":"https://akuminadev02.sharepoint.com/sites/delivery-cloud-qa-maindev02_112020","ValueType":"Edm.String"},{"Key":"SiteTitle","Value":"delivery-cloud-qa-maindev02_112020","ValueType":"Edm.String"},{"Key":"UniqueID","Value":"{5272DAB8-549C-4A2B-9453-E48A8644BCEB}","ValueType":"Edm.String"},{"Key":"SiteId","Value":"4a419029-6185-415a-ab32-f1462a864fc5","ValueType":"Edm.String"},{"Key":"WebId","Value":"a319205c-dcfe-4810-b1c8-c7cc65fa28d6","ValueType":"Edm.String"},{"Key":"IsExternalContent","Value":"false","ValueType":"Edm.Boolean"},{"Key":"ListId","Value":"d1e27d21-2566-431a-94b6-21f69cfa90fc","ValueType":"Edm.String"},{"Key":"OriginalPath","Value":"https://akuminadev02.sharepoint.com/sites/delivery-cloud-qa-maindev02_112020/Shared Documents/test.docx","ValueType":"Edm.String"},{"Key":"Size","Value":"16824","ValueType":"Edm.Int64"},{"Key":"PreviewUrl","Value":null,"ValueType":"Null"},{"Key":"ResultTypeIdList","Value":null,"ValueType":"Null"},{"Key":"ResultTypeId","Value":null,"ValueType":"Null"},{"Key":"RenderTemplateId","Value":"~sitecollection/_catalogs/masterpage/Display Templates/Search/Item_Default.js","ValueType":"Edm.String"},{"Key":"piSearchResultId","Value":"ARIA\u01c2733c1fd5-1f34-43e0-842d-c1dcf2f3751e\u01c20fb34a7d-a86c-4714-8934-09e9fd05b6fc\u01c2733c1fd5-1f34-43e0-842d-c1dcf2f3751e.1000.1\u01c2","ValueType":"Edm.String"},{"Key":"GeoLocationSource","Value":"NAM","ValueType":"Edm.String"},{"Key":"PartitionId","Value":"29433ce8-8a81-420b-aed3-30acc756d09d","ValueType":"Edm.Guid"},{"Key":"UrlZone","Value":"0","ValueType":"Edm.Int32"},{"Key":"Culture","Value":"en-US","ValueType":"Edm.String"}]}]},"TotalRows":1,"TotalRowsIncludingDuplicates":1},"SpecialTermResults":null},"Properties":[{"Key":"WordBreakerLanguage","Value":"en","ValueType":"Edm.String"},{"Key":"RowLimit","Value":"23","ValueType":"Edm.Int32"},{"Key":"SourceId","Value":"8413cd39-2156-4e00-b54d-11efd9abdb89","ValueType":"Edm.Guid"},{"Key":"CorrelationId","Value":"de4c939f-d0fb-b000-a468-efaeaac8a779","ValueType":"Edm.Guid"},{"Key":"WasGroupRestricted","Value":"false","ValueType":"Edm.Boolean"},{"Key":"IsPartialUpnDocIdMapping","Value":"false","ValueType":"Edm.Boolean"},{"Key":"EnableInterleaving","Value":"true","ValueType":"Edm.Boolean"},{"Key":"IsMissingUnifiedGroups","Value":"false","ValueType":"Edm.Boolean"},{"Key":"Constellation","Value":"iB3FC8","ValueType":"Edm.String"},{"Key":"MultiGeoSearchStatus","Value":"Full","ValueType":"Edm.String"},{"Key":"HasParseException","Value":"false","ValueType":"Edm.Boolean"},{"Key":"IsPartial","Value":"false","ValueType":"Edm.Boolean"},{"Key":"InternalRequestId","Value":"733c1fd5-1f34-43e0-842d-c1dcf2f3751e","ValueType":"Edm.String"},{"Key":"SerializedQuery","Value":"<Query Culture=\"en-US\" EnableStemming=\"True\" EnablePhonetic=\"False\" EnableNicknames=\"False\" IgnoreAllNoiseQuery=\"True\" SummaryLength=\"180\" MaxSnippetLength=\"180\" DesiredSnippetLength=\"90\" KeywordInclusion=\"0\" QueryText=\"test\" QueryTemplate=\"{searchTerms} Path:{Site}\" TrimDuplicates=\"False\" Site=\"4a419029-6185-415a-ab32-f1462a864fc5\" Web=\"a319205c-dcfe-4810-b1c8-c7cc65fa28d6\" KeywordType=\"True\" HiddenConstraints=\"\" />","ValueType":"Edm.String"}],"SecondaryQueryResults":[],"SpellingSuggestion":"","TriggeredRules":[]}

**Comment by RiddhiKarani** [comment]
@wobba  it worked after i update the scope to all of the query result

**Comment by wobba** [comment]
Was the scope part of the query or query template? If you have a property query in the query/template, then your query rule won't trigger. For these cases you need to create a result source with the filter, and have the query rule trigger for this result source, and use that result source in the web part.
