### ISSUE TITLE
CreatedBy is not working in Search Filter web part

### ISSUE THREAD

**Issue by RyanLong88** [microsoft-search/pnp-modern-search#586]
**Version used**
3.15

**Describe the bug**
Can filter by other columns but not CreatedBy. 
I use column CreatedBy in Search Result and it displays properly no issue.
The returned result got lots of value, but the filter for CreatedBy only has 1 value, the value also not displaying the correct value.
In Refinement Filters setting in Search Result web part, I tried using Author: Value or CreatedBy: Value also working properly.

**To Reproduce**
1. Add CreatedBy as refiner for Search Filter
2. Search * to show all results
3. Click filter CreatedBy

**Expected behavior**
Should show the distinct values from CreatedBy column in the Search Result.

**Screenshots**
![image](https://user-images.githubusercontent.com/75305999/100725487-0f38f480-33ff-11eb-9287-63317eb457d4.png)

**Comment by wobba** [comment]
`CreatedBy` is not a refinable or sortable managed property. `Author` is sortable, not refinable. `DisplayAuthor` is refinable. You need to check the schema for how you can use a property.

**Comment by RyanLong88** [comment]
Thanks Wobba for your explanation!

I thought all the columns displaying in the refiners are refinable.
Anyway will try DisplayAuthor and get back the result.

Cheers

**Comment by RyanLong88** [comment]
Dear Wobba,

Yeah I did recheck on Search Schema and both CreatedBy / Author are not refinable. 
Thanks to you, I realize DisplayAuthor is refinable and actually used as 1 of the default refiners in Search Center.

Now can use DisplayAuthor in PnP refiner, however I can see that for few records CreatedBy and DisplayAuthor are not same, seems that DisplayAuthor also takes the original author, while CreatedBy is only the person who uploaded document to SharePoint which is what I want to retrieve.
![image](https://user-images.githubusercontent.com/75305999/100855718-7620e100-34c5-11eb-9f21-02eb8911f29f.png)

So I created some RefinableString to map with CreatedBy and Author as the following screenshot:
![image](https://user-images.githubusercontent.com/75305999/100855880-a7011600-34c5-11eb-8f63-043939d55c22.png)

But then now I only can see RefinableString02 and RefinableString00, RefinableString01 for ows_Created_x0020_By does not display. Do you have some idea about it?
Thanks.

**Comment by wobba** [comment]
Created by is named ows_Author. And you probably want to follow https://github.com/microsoft-search/pnp-modern-search/blob/main/docs/search-parts/search-filters.md#persona

**Comment by RyanLong88** [comment]
Thanks Wobba but I cannot see ows_Author

![image](https://user-images.githubusercontent.com/75305999/101469335-977b4480-397f-11eb-9723-c351e3eee868.png)

**Comment by wobba** [comment]
`ows_q_USER_Author` should work, but it includes the claim as well, or try using `Author`.

**Comment by alabonte** [comment]
I get the same problem with ModifiedBy.  I mapped RefinableString00 to many properties, but the content remains empty.

![2020-12-17 14_24_46-RefinableString00_definition](https://user-images.githubusercontent.com/7327483/102533952-10f7ee80-4074-11eb-914d-cd89eeba4f1d.png)
![2020-12-17 14_24_46-RefinableString00](https://user-images.githubusercontent.com/7327483/102533954-10f7ee80-4074-11eb-943e-934bf35ab051.png)

**Comment by wobba** [comment]
I'm closing this as it's not related to the web parts themselves, but data issue on your mapping. Search technical questions are outside the scope of the PnP web parts as it relates just as much to classic web parts, and we don't have bandwidth to troubleshoot/consult on these issues.

**Comment by RyanLong88** [comment]
> I get the same problem with ModifiedBy. I mapped RefinableString00 to many properties, but the content remains empty. I checked RefinableString00 in the selected properties field.
> 
> ![2020-12-17 14_24_46-RefinableString00_definition](https://user-images.githubusercontent.com/7327483/102533952-10f7ee80-4074-11eb-914d-cd89eeba4f1d.png)
> 
> Results display :
> 
> ![2020-12-17 14_24_46-RefinableString00](https://user-images.githubusercontent.com/7327483/102533954-10f7ee80-4074-11eb-943e-934bf35ab051.png)

You can map to this:
![image](https://user-images.githubusercontent.com/75305999/102735786-42c3ca80-437e-11eb-9fcb-1e4995e5dbbc.png)

I notice that this one only has value when the document is actually modified on SharePoint. By default when you first upload a document, Modified and ModifiedBy got same value with Created and CreatedBy. So if a document has never been edited on SharePoint then LastModifiedBy will be empty.
