### ISSUE TITLE
Using query variable in Modern Search Results Web Part (v3) based in a news page property of type Choice

### ISSUE THREAD

**Issue by miguelisidoro** [microsoft-search/pnp-modern-search#588]
Hello,

I am using the Search Results web part v3 at https://web.archive.org/web/20201014031829/https://microsoft-search.github.io/pnp-modern-search/search-parts/search-results in a Communication Site and I am trying to set a dynamic query that depends on a page property.

If set the query with a fixed value as: path:https://<tenant>.sharepoint.com/sites/contosonews/Photos Company=Microsoft, the results are correctly returned.

But if I change my query to use a page property called Company, it doesn't work. I am using a query variable explained in the above article as follows:

path:https://<tenant>.sharepoint.com/sites/contosonews/Photos Company={Page.Company}, the results are correctly returned.

IMPORTANT: Company is a choice field and the user chooses in the Page Details the value of the Company field when editing the page.

I configired the Search Results web part into debug mode and the query seems not to be being transformed based on the page value but the lilteral "{Page.Company}" is being passed into the query.

  "queryModification": "https://<tenant>.sharepoint.com/sites/contosonews/Photos Company={Page.Company} -ContentClass=urn:content-class:SPSPeople",

How can I use the page property of type Choice (in this case called Company) in my search query to have a dynamic query?

Thanks

**Comment by wobba** [comment]
Can you verify that the internal name of your "Company" field is indeed "Company"?

**Comment by miguelisidoro** [comment]
Solved. Token page.fieldname must be placed in query template field, not in the query text Field.
Thanks
