### ISSUE TITLE
Search Verticals - connecting tabs to more than one Results WepPart

### ISSUE THREAD

**Issue by MoominMammaa** [microsoft-search/pnp-modern-search#590]
Version used: **v4**

I am trying to use new Verticals (v4). I created two tabs and added two Search Results WPs on my page (with different result sources e.g. pages and people). Each Results WP displays the results correctly.
Then I connected each search results WPs to vertical WP and configured visibility using „Display data only when the following vertical is selected” option.  **After saving changes the Results WPs and data are not visible on the page.** In edit mode I can see Results WPs and results correctly. The same (correct) is when Results WB is disconected with Vertical WP.
What else should I do to configure Verticals WP with more than one Results WP on one page (each vertical tab for each Results WP)? Help, please!

**To Reproduce**
1. PnP-Search Verticals WP - configure two tabs (not hyperlink)
2. Add two PnP-Search Results on the page – each one with different result source
3. Connect each PnP Search Result WP to Vertical WP. Use „Display data only when the following vertical is selected” option to specified visibility for each tab.
4. Save the page (save as draft or publish)
5. Use vertical tabs + search box and see there are no results and no results web parts…

**Desktop**
 - Browser: Chrome, Edge

**Comment by FranckyC** [comment]
Hi @MoominMammaa do you get any error message in the console?

**Comment by MoominMammaa** [comment]
Hi @FranckyC! Yes, I see a few:
![2020-12-02_22h44_06](https://user-images.githubusercontent.com/75377202/100935417-5ce15a00-34f0-11eb-9693-6cd8990f48fa.png)

**Comment by FranckyC** [comment]
Ok I'll will look into it

**Comment by MoominMammaa** [comment]
I will be gratefull :-). I didn't grant API permissions (Microsoft Graph). Is it necessary in this case?

**Comment by FranckyC** [comment]
@MoominMammaa Did you use the latest code on the v4 branch? We had a fix for this a couple of commits ago.

**Comment by MoominMammaa** [comment]
@FranckyC I use 4.0.0 version
![2020-12-04_21h04_56](https://user-images.githubusercontent.com/75377202/101210050-26811780-3675-11eb-9e0a-4c7a66c801df.png)

**Comment by MoominMammaa** [comment]
@FranckyC  I don't know how to build latest version from the repo. When are you going to release next version?

**Comment by FranckyC** [comment]
no ETA for now as we need to address few issues. Did you try with the latest package?

**Comment by MoominMammaa** [comment]
I will try take the latest and reinstall. Thanks!

**Comment by Laul0** [comment]
Hi @MoominMammaa, does the latest version fixes your issue?

**Comment by wobba** [comment]
Stale issue
