### ISSUE TITLE
Language support: Sorting

### ISSUE THREAD

**Issue by yrrgeirs** [microsoft-search/pnp-modern-search#592]
Hi, I see you have been addin some langue support :) 
It would be great if you could add correct sorting for the icelandic alphabet :D 

A Á B C D E É F G H I Í J K L M N O Ó P Q R S T U Ú V X Y Ý Z Þ Æ Ö
a á b c d e é f g h i í j k l m n o ó p q r s t u u ú v x y ý z þ æ ö

Love these web parts by the way!! Thanks!

**Comment by wobba** [comment]
@yrrgeirs that's a bit unspecific :) Where do you want sorting? and we don't have Icelandic native support in the web parts. As for sorting we can pick up the UI language and use that where supported.

**Comment by yrrgeirs** [comment]
Ooops, sorry about that! I'm talking about the search refiners :) Default refinement item, Refiner sort type "Alphabetical".
Not sure about the correct "technical terms" for things... There is no Icelandic UI version for SharePoint, but the Reginonal settings/sorting fixes the default A-Z sorting in list columns at least (Sort order: Icelandic). Is that something?

**Comment by wobba** [comment]
I'll tag this as a feature enhancement.

**Comment by yrrgeirs** [comment]
Wait, we tried upgrading to this newest version from a few days ago, and now the sorting works! Yay!
So....apparently some changes were made for the benefit of the icelandic sorting, haha :)

**Comment by yrrgeirs** [comment]
Works with newest version from November 2020
