### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by SaratchandraPeddinti** [microsoft-search/pnp-modern-search#593]
**Need a suggestion on the feature I want to implement**
I'm planning to implement Advanced search that functions same as "classic" advanced search.
The web part mockup is similar to the one you can see below.
1. The managed properties mapped to the input fields
2. Idea is to form the KQL query & append as the URL segment so that the "Results" webpart can pull the results as per the criteria
3. I have a question - **Do you see a possibility of running into the "URL" length issues if it crosses over 400 characters?** (or) does the URL segment has any length limitations?
4. This is also regarding URL length - is the segment after **"#"** prone to encounter URL-segment limitation of around 255 characters?
Eg: https://spo-site/sitepages/search.aspx**#ManagedPropertyName:"search-value"**
5. My final question is, is there any other way of achieving this functionality by connecting the new webpart with results webpart & pass the KQL query to it?

**Mockup of the planned advanced search webpart**
![image](https://user-images.githubusercontent.com/16175517/100995493-d96e4a00-357d-11eb-91de-f56266a51b2c.png)

**Comment by wobba** [comment]
Feel free to look at the existing search box web part and extend it for your own need.

Project wise we don't plan to support advanced search like this as it's not very user friendly to most people. If you create such a web part we could be inclined to accept it as a PR for v4.

5. If you create a new web part I would pass the data via dynamic data, not query params

**Comment by FranckyC** [comment]
Hi @SaratchandraPeddinti, great idea. I would suggest to implement it as a separated Web Part but connectable using dynamic data to the "inputQueryText" option of the search results Web Part. It would be a other choice to classic search box. 

You can focus on your Web Part implementation and we could take care of the connection to the main Web Part once PR. As long as you follow the same connection pattern used for the search box, we should be good. Just output the generated KQL query. 

Also, I suggest you to let people type their own fields names in addition to be able to select managed properties. This has to be compatible with Microsoft search as well, not only SharePoint search.

Finally, v4 is still in preview so your PR won't be processed until we release a stable version. Just to let you know.
