### ISSUE TITLE
How to add Single Line of text column in Search refiner?

### ISSUE THREAD

**Issue by lokeshumapathy01** [microsoft-search/pnp-modern-search#595]
I need to add a single line of text column as Search refiner in Search Filters webpart.
I also need to customize the Search filters webpart.
Currently I'm using 3.16.0

**Comment by wobba** [comment]
You need to map the crawled property matching your SharePoint column/filed to a managed property, for example RefinableString00. After the mapping you need to re-index any existing content (out of scope to comment on this here), and then you can use the refiner in the web parts.

How to get data into search is out of scope for this web part project, and there should be ample documentation out on the internet for this :)

**Comment by lokeshumapathy01** [comment]
I was able to get the Crawled property for that column and I had added that to **Search Filters** as refiner, but the search filters is not showing values for this particular Column alone.
I was able to get the filters for Metadata columns but not for this "single line of text column"

**Comment by wobba** [comment]
If you can get values to show in the classic web parts, then feel free to report an issue here. If you don't get values in classic web parts, it's a data mapping issue for you to figure out.
