### ISSUE TITLE
Error if 'People Name in SharePoint Search' Query rule fires when using promoted results

### ISSUE THREAD

**Issue by abates100** [microsoft-search/pnp-modern-search#596]
Very similar to 'specific keyword search gives error #463' 
Error occurs on POST
Error does not occur in OOB Modern Search pages

**Version used**
Ex: 3.15.1

**Describe the bug**
We have narrowed our issue down to the combo of 'Use Query rules' in the results web part and when the keyword triggers one of the rules in 'People Name and Popular Queries Group'.  Inactivating these rules clear the errors and results are returned. Majority of our keyword failures trigger the 'People Name in SharePoint Search' rule (test, merchant, global support, etc.)

**To Reproduce**
1. Create single page with Search Box and Results web parts
2. Use Local SharePoint Results as source, enable 'Use Query Rules' in results part and select the Simple List template in order to display promoted results
3. Search for 'test' (verify in Search Admin if it matches a query rule like 'People Name in SharePoint Search')
4. Search for 'global support'  (verify in Search Admin if it matches a query rule like 'People Name in SharePoint Search' or PowerPoint)
4. Error :  HttpClient request in queryable [500] Internal Server Error ::> {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}

**Expected behavior**
Expect search results to display with or without Promoted Results block as was working prior to sometime early November.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Chrome or Edge

**Additional context**
This may be localized to our tenant as we cannot recreate in a development environment with same version of the web parts but obviously a different People Names dictionary.

**Comment by wobba** [comment]
Can you share what the POST request looks like? Are you able to create a similar POST request via the SharePoint Search Query Tool, and verify that it works there? Trying to figure out if the request is wrong or not, or if it could be some other parameter causing the issue.

OOB modern search does not use the same query internally, so you should compare with classic web parts to get as close comparison as possible in OOB UX.

**Comment by abates100** [comment]
Good to know, hopefully this is what you're asking for.  I did verify the classic parts return our expected promoted results and do not throw the error.   

Attached POST output is from Search Query tool.  The promoted results at the end of the output show the query rule for 'PowerPoint' fired and was listed first which seems to be the pattern that causes the error in the browsers.  Once I inactivate that rule and just the 2nd rule is triggered, the browser display in the PnP results web part is fine. 

[SPSQ_post.txt](https://github.com/microsoft-search/pnp-modern-search/files/5667067/SPSQ_post.txt)

  "results": [
                    **"b7a8363a-05df-44a5-8900-da28699e1de8",**
                    "2335149d-6791-4702-90e6-6d5c30852806"
                ]

When that system rule for Powerpoint is inactivated and results display successful in browser (Edge) this is the POST  

request: {__metadata: {type: "Microsoft.Office.Server.Search.REST.SearchRequest"},…}
ClientType: "PnPModernSearch"
Culture: 1033
EnableNicknames: false
EnablePhonetic: false
EnableQueryRules: true
HitHighlightedProperties: {results: []}
Properties: {results: [{Name: "EnableDynamicGroups", Value: {BoolVal: true, QueryPropertyValueTypeIndex: 3}},…]}
QueryTemplate: "{searchTerms} ((filetype:pdf AND path:https://somesite/sites/site/Shared%20Documents/*) OR  (Path:"https://somesite.sharepoint.com/sites/somesite*" AND SPContentType:"*Page*"))"
Querytext: "employee support"
RefinementFilters: {results: []}
Refiners: "FileExtension(sort=name/ascending),LastModifiedTime(discretize=manual/2019-12-09T15:57:57.724Z/2020-09-09T14:57:57.724Z/2020-11-09T15:57:57.724Z/2020-12-02T15:57:57.724Z/2020-12-08T15:57:57.724Z)"
ReorderingRules: {results: []}
RowLimit: 10
SelectProperties: {,…}
SortList: {results: []}
SourceId: "8413cd39-2156-4e00-b54d-11efd9abdb89"
TimeZoneId: 2
TrimDuplicates: false
__metadata: {type: "Microsoft.Office.Server.Search.REST.SearchRequest"}

**Comment by wobba** [comment]
I'd like you to try to mimic the PnP web part POST request in the query tool, to have them look the same. HiddenConstraints is not the same as QueryTemplate etc ;) Can you get the same query to fail in the query tool for repro.

A 500 error means something happened on the server side when trying to handle your query.

**Comment by abates100** [comment]
Sorry I was out a couple of days then I've been attempting to test and recreate the last couple of days however I cannot recreate the issue. Mainly because I cannot re-enable the rule that was causing the error.  MS seems to have us locked down.

This configuration change cannot be made at this time because the service is in read-only mode.
-- 
General Information | General Information
General Information

**Comment by wobba** [comment]
I'll close this one, as it should be addressed in an upcoming v4 release.
