### ISSUE TITLE
Missing sortable dropdown in V4

### ISSUE THREAD

**Issue by PrabhuChandar** [microsoft-search/pnp-modern-search#597]
**Version Used**
4.0.0.0

**Describe the Feature**

Sortable dropdown is missing in the latest version of PnP modern search. But we had this in our older version (3). Please find the screenshot for your reference. 

![image](https://user-images.githubusercontent.com/32821161/101437956-4cd5da00-3937-11eb-9a0d-9b9bc970a63d.png)

This is the main feature in the Modern search Result webpart. So kindly update it in upcoming release if possible.

**Comment by FranckyC** [comment]
Hi @PrabhuChandar, you're right. It is not implemented right now. In the backlog, but no ETA yet.

**Comment by PieterVandendriessche** [comment]
Hi @FranckyC is there an ETA yet?

**Comment by FranckyC** [comment]
Hi @PieterVandendriessche , still no ETA sorry.

**Comment by wobba** [comment]
Available for the list template in v4
