### ISSUE TITLE
Web Part Title field not aligned with default for page

### ISSUE THREAD

**Issue by kasperbolarsen** [microsoft-search/pnp-modern-search#599]
**Version used**
4.0.0

The Web part title for any of the web parts does not look identical to the OOTB web parts

![PnPSear400_TitleField](https://user-images.githubusercontent.com/20593570/101739290-96edc580-3ac7-11eb-82aa-14b990f1d215.png)

**Expected behavior**
I expected the "styling" of the Title to align with the theme for the page/site. Or an option to style the Title

**Desktop (please complete the following information):**
 - Browser : Chredge

**Additional context**

**Comment by FranckyC** [comment]
Thanks @kasperbolarsen for letting us know. Microsoft changes UI every two weeks. Hard to keep up ;)

**Comment by FranckyC** [comment]
@kasperbolarsen Should be resolved in the next realease but more as a temporary fix (i.e. ugly CSS). We use the WebPartTitle control from the [sp-dev-fx-controls-react](https://github.com/pnp/sp-dev-fx-controls-react) library. There is already an issue for this https://github.com/pnp/sp-dev-fx-controls-react/issues/605.
