### ISSUE TITLE
Handlebars theme colors doesn't work in an expression of the Details List layout of the Search Results webpart

### ISSUE THREAD

**Issue by Thyregod** [microsoft-search/pnp-modern-search#600]
**Version used**
Ex: 3.16.0

**Describe the bug**
{{@root.theme.palette.themePrimary}} and {{@root.themeVariant.palette.themePrimary}} does not work when used in the Handlebars Expression of the Manage Column option in the Details List layout of the Search Results webpart.

The expected color seems to be an empty string.

Handlebars expression:
![image](https://user-images.githubusercontent.com/22339038/101740750-86d6e580-3ac9-11eb-9f96-cbeced35a295.png)

Handlebars expression in DOM:
![image](https://user-images.githubusercontent.com/22339038/101741091-edf49a00-3ac9-11eb-8c53-0d5fc37f9f0f.png)

**To Reproduce**
1. Add the "Search Results" Webpart
2. Select the "Details List" layout
3. Click on "Manage Columns"
4. Add a Handlebars expression using the {{@root.theme.palette.themePrimary}} and {{@root.themeVariant.palette.themePrimary}}
5. Validate none of the two themePrimary colors works on the DOM element

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by FranckyC** [comment]
Hi @Thyregod, with v3.x, in the cards and details list layout, you must use the `@themeVariant.palette.themePrimary` expression to access the theme values. See https://web.archive.org/web/20201014031827/https://microsoft-search.github.io/pnp-modern-search/search-parts/templating/#template-options.
