### ISSUE TITLE
Ability to query term store

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#601]
**Is your feature request related to a problem? Please describe.**
I am frustrated with term sets. If I have a Lookup list, I can query that list and display a list of terms on a page. If I use managed metadata, I don't have a way to search for and display a list of all terms in a term set. I've run into this over the years and it always drives me crazy!

**Describe the solution you'd like**
I would like to be able to do a query against a TermId and get a list of term store values.

**Describe alternatives you've considered**
I tried querying the taxonomyhiddenlist (which is not live data, but was all I could think of). 

**Additional context**
Is there some way to do this that I am just unaware of?

**Comment by FranckyC** [comment]
Hi @bryllyg, this is definitely a great idea! However, this is not the purpose of this Web Part as it is targeted for search usages (SharePoint search and Microsoft Search only). Sorry.

**Comment by bryllyg** [comment]
Thanks for the info! Appreciate the response. I LOVE the web parts! Thanks!
