### ISSUE TITLE
Multiple Search Refiners

### ISSUE THREAD

**Issue by knaveenstar** [microsoft-search/pnp-modern-search#602]
!! Check existing issues before logging new ones !!

**Version used**
Ex: 3.13

**Describe the bug**
I would like to two Search Refiners webpart and try to connect the source as same , but the filter only applied from one webpart. is there any way to get filters from both webparts. I had customized the search result webpart such as its send values to both filters webpart.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by FranckyC** [comment]
Hi @knaveenstar, this is not possible using the v3. However, this scenario is now supported in the v4 if you want to give it a try https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.0.0-preview
