### ISSUE TITLE
Documentation of V3 inaccessible

### ISSUE THREAD

**Issue by lennertcc** [microsoft-search/pnp-modern-search#603]
**Version used**
3.x

**Describe the bug**
The documentation of V3 is only available via web.archive.org, which results in 404 errors every time when following a link to the V3 documentation from, for example, Issues in this project. Also Internet searches for V3 features don't show results from V3.

**To Reproduce**
Example: 
https://microsoft-search.github.io/pnp-modern-search/search-query-enhancer/getting-started/
Link broken and unable to find this page through Google.

**Expected behavior**
Have the documentation side by side. Restore V3 documentation to the original url's, so we can search and use previously shared links to the documentation that actually point to the expected documentation page.

**Additional context**
With V4 not even stable, it's way to early to do away with the V3 documentation like this.

**Comment by wobba** [comment]
You can find it at https://github.com/microsoft-search/pnp-modern-search/tree/develop/docs but we will move it to the main branch as well. We'll see if we can find a good way to keep them side by side and working on github.io.

**Comment by wobba** [comment]
I spent some time on this and think I have a working solution which we'll test out later today. Fingers crossed!

**Comment by wobba** [comment]
Now published and you can access is directly from https://microsoft-search.github.io/pnp-modern-search/v3/

**Comment by lennertcc** [comment]
Thanks Mikael
