### ISSUE TITLE
Question - how do i remove the text box when I hover over a link or text? 

### ISSUE THREAD

**Issue by mongoux** [microsoft-search/pnp-modern-search#608]
Hi, This text box shows all the additional code ( html, css ) included with handlebars expressions. I'd like to disable it so users don't see it.
See image: 
![image](https://user-images.githubusercontent.com/35407310/102010355-dde4f080-3d3d-11eb-8ae9-4819f5381912.png)

Thanks

**Comment by FranckyC** [comment]
Hi @mongoux this is controlled by the HTML `title` property on the parent item. In your column makrup, you can try to set it as an empty string `<div title="">...</div>` and see if it works

**Comment by mongoux** [comment]
HI @FranckyC  I customized the details list to add css, so I'm not sure how i can do that now. there's no `<div title >`

Template:
`<div class="template_root">
        {{#if @root.hasPrimaryOrSecondaryResults}}   
            {{#if showResultsCount}}
                <div class="template_resultCount">
                    <label class="ms-fontWeight-semibold">{{getCountMessage @root.paging.totalItemsCount keywords}}</label>
                </div>
            {{/if}}
            <pnp-details-list data-items="{{JSONstringify items}}" data-columns-configuration="{{JSONstringify detailsListColumns}}" data-show-file-icon="{{@root.showFileIcon}}" data-is-compact="{{@root.isCompact}}"></pnp-details-list>
            {{#if @root.paging.showPaging}}
                <pnp-pagination 
                    data-total-items="{{@root.paging.totalItemsCount}}" 
                    data-hide-first-last-pages="{{@root.paging.hideFirstLastPages}}"
                    data-hide-disabled="{{@root.paging.hideDisabled}}"
                    data-hide-navigation="{{@root.paging.hideNavigation}}"
                    data-range="{{@root.paging.pagingRange}}" 
                    data-items-count-per-page="{{@root.paging.itemsCountPerPage}}" 
                    data-current-page-number="{{@root.paging.currentPageNumber}}"
                >
                </pnp-pagination>
            {{/if}}
        {{else}}
            {{#unless showBlank}}
                <div class="template_noResults">{{@root.strings.NoResultMessage}}</div>
            {{/unless }}
        {{/if}}
    </div>
</content>`

**Comment by Laul0** [comment]
Hi @mongoux, does the @FranckyC's answer fixes your issue?
