### ISSUE TITLE
Unable to open search result item into a new tab

### ISSUE THREAD

**Issue by coupalm** [microsoft-search/pnp-modern-search#61]
Is there a way to open a search result item into a new tab? using target="_blank" has no effect.

`<span class="template_title example-themePrimary"><a href="{{getUrl item}}" target="_blank">{{Filename}} </a></span>`

Thanks.

**Comment by FranckyC** [comment]
Use `data-interception=off` attribute. More info here https://docs.microsoft.com/en-us/sharepoint/dev/spfx/hyperlinking

**Comment by coupalm** [comment]
Thank you very much!

**Comment by apthecool** [comment]
I am using PnP search results webpart and i cannot see the span class in result template.

**Comment by wobba** [comment]
You need to customize it.. click the `{}` and you get the selected template as default when customizing.
