### ISSUE TITLE
Metadata Column in Search Filters

### ISSUE THREAD

**Issue by knaveenstar** [microsoft-search/pnp-modern-search#610]
!! Check existing issues before logging new ones !!

**Version used**
Ex: 4.0.0.0 Preview

**Describe the bug**
Hi Team,

I am trying to use PNP Modern search web part and configured search filter and search result web part. In the search filter web part I have configured the one of the metadata column. in the filter section its listed the values with the GUID of the metadata value.  I need to show only the display name in the filter webpart section.

**Screenshots**
![image](https://user-images.githubusercontent.com/30283702/102048312-ea804c00-3e04-11eb-8765-2a7d0c55c187.png)

**Comment by kasperbolarsen** [comment]
Hi,
Is it possible that it can be a mapping issue, that you might have mapped the refinablestring to the taxid crawled property rather than the text one?

![image](https://user-images.githubusercontent.com/20593570/102069548-354a9580-3dfe-11eb-9840-54ac0cd442e1.png)

**Comment by knaveenstar** [comment]
HI,

I have mapped with taxid field only.

![image](https://user-images.githubusercontent.com/30283702/102070593-54105280-3e25-11eb-8fd4-1d1257db84ea.png)

**Comment by kasperbolarsen** [comment]
I have just tested it by mapping a RefinableString to the text crawled property, and it works just fine :-) I have never dared to mess around with the owstaxidmetadataalltagsinfo, and prefers to map the crawled property to a RefinableString and I believe that this is the approach recommended by MS

![image](https://user-images.githubusercontent.com/20593570/102076531-1fda6900-3e08-11eb-9783-eb3a9df7de77.png)

**Comment by knaveenstar** [comment]
Thanks kasperbolarsen. Can you please show me the mapping fields so that I will create a new mapping .

**Comment by kasperbolarsen** [comment]
Sorry, I didn't noticed that you are using the All Tags property. I tested that approach on 3.16 and 4.0.0 and you are correct. The refiner in 3.16 only shows the text value and 4.0.0 shows the entire path.

**Comment by knaveenstar** [comment]
Yes, 
team can you please help me on this issue with 4.0.0

**Comment by FranckyC** [comment]
Hi @knaveenstar, in slots, you need to use the `Autoowstaxidmetadataalltagsinfo` property for the "Tags" slot. Then in the Search Results Web Part, enable the "Enable Localization" option. See the documentation https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/

> 

To use translated values in your template, you must use the 'Auto + <property_name>' property format instead of the original property name. For instance, to use translated values of the 'owstaxidmetadataalltagsinfo' property, you must use the 'Autoowstaxidmetadataalltagsinfo' auto created property. |  
-- | --

**Comment by knaveenstar** [comment]
Thanks @FranckyC . Its works fine after enabled localization.

**Comment by JoelHJ** [comment]
I have the same issue as this but in the on prem version from [here](https://github.com/David74000/SP2019-modern-search-webpart-with-taxonomy-refiner) 

Is there a fix for this for the on prem? I mapped the refinableStrng but it didn't change anything. I have the search and all working just want to be able to use refiners. 

Thank you
Joel

**Comment by wobba** [comment]
This project does not cover on-prem forks.
