### ISSUE TITLE
Pagination Not working after applied Filter

### ISSUE THREAD

**Issue by knaveenstar** [microsoft-search/pnp-modern-search#612]
!! Check existing issues before logging new ones !!

**Version used**
Ex: 4.0.0 preview

**Describe the bug**
I have configured Search Result and Search Filter webpart. I am facing issue with pagination. 

Initially the pagination working fine but after applying any filter value the pagination not working.

Please help me on this issue

**To Reproduce**
1. Add Search Result webpart
2. Add Search Filter webpart
3. Configure all settings
4. Search and apply filter and click pagination

**Expected behavior**
its should go to next page

**Screenshots**
First Page
![image](https://user-images.githubusercontent.com/30283702/102111385-52ae4c80-3e5c-11eb-9976-cd1bb042c9a4.png)

Second Page
![image](https://user-images.githubusercontent.com/30283702/102111407-5cd04b00-3e5c-11eb-9f22-d4635e032276.png)

**Comment by wobba** [comment]
@knaveenstar no longer an issue?
