### ISSUE TITLE
If Promoted Result in search schema is worked at pnp search app

### ISSUE THREAD

**Issue by tony-philipose** [microsoft-search/pnp-modern-search#614]
MS search box can be showing the promoted result as priorly, if it,s available in pnp modernsearch app

**Comment by wobba** [comment]
@tony-philipose can you elaborate a bit on what you mean exactly? "Promoted results" is typically pointing to the classic feature of using query rules to create a best bet/bookmark.

**Comment by tony-philipose** [comment]
I have to create Promoted result in Manage search schema, Query string of given promoted result is searched in Sharepoint Global search the promoted result is appear above the ranked results.
![image](https://user-images.githubusercontent.com/30836715/102306458-52ab6b00-3f88-11eb-9867-23bd31d7dc35.png)

But the Promoted results are not showing in  pnp modern search

**Comment by wobba** [comment]
You can get these by enabling query rules in the PnP web parts.

The Microsoft Search box do not show promoted results, the search result page does - and, that capability is being replaced by the new Bookmarks feature over time. You can however still use query rules and promoted results with the SharePoint API provider in the PnP web parts. When/if bookmarks are exposed via the Microsoft Graph Search API, we can support it in v4.

See https://github.com/microsoft-search/pnp-modern-search/blob/develop/docs/search-parts/templating.md#accessing-items for docs.

**Comment by tony-philipose** [comment]
> You can get these by enabling query rules in the PnP web parts.
> 
> The Microsoft Search box do not show promoted results, the search result page does - and, that capability is being replaced by the new Bookmarks feature over time. You can however still use query rules and promoted results with the SharePoint API provider in the PnP web parts. When/if bookmarks are exposed via the Microsoft Graph Search API, we can support it in v4.
> 
> See https://github.com/microsoft-search/pnp-modern-search/blob/develop/docs/search-parts/templating.md#accessing-items for docs.

Thanks, @wobba I got the promoted results, and working fine 👍

**Comment by wobba** [comment]
v3 docs are now re-published and available via https://microsoft-search.github.io/pnp-modern-search/v3

**Comment by tony-philipose** [comment]
> v3 docs are now re-published and available via https://microsoft-search.github.io/pnp-modern-search/v3

Great work 👍

**Comment by JonoSuave** [comment]
I'm using PnP Modern Search v4 with Query Rules enabled, but the query rule I set up only shows at the top with OOB search results page and not within the PnP search results web part.
![PnP Modern Search Enable query rules](https://user-images.githubusercontent.com/22969971/123293485-06665800-d4e2-11eb-9ad9-0b4a0ea431fe.png)
![Query Rules Displaying with OOB Search Results](https://user-images.githubusercontent.com/22969971/123293504-09f9df00-d4e2-11eb-80a6-5db233b9c61c.png)

**Comment by simesy** [comment]
> You can get these by enabling query rules in the PnP web parts.

So I'm reading that this works in v3 and not v4 (until Bookmarks is out of beta in the Graph).

**Comment by JonoSuave** [comment]
> > You can get these by enabling query rules in the PnP web parts.
> 
> So I'm reading that this works in v3 and not v4 (until Bookmarks is out of beta in the Graph).

Promoted Results has worked for me in v4

**Comment by simesy** [comment]
> > > You can get these by enabling query rules in the PnP web parts.
> > 
> > 
> > So I'm reading that this works in v3 and not v4 (until Bookmarks is out of beta in the Graph).
> 
> Promoted Results has worked for me in v4

I must be missing backend search configuration that I don't have access to.

**Comment by simesy** [comment]
To be clear I'm only using Bookmarks and not Promoted results. I can't see any way to point custom Query Rules to Bookmarks. I have looked through the different Result Sources.

**Comment by wobba** [comment]
@simesy
query rules = SharePoint API
bookmarks = Graph Search API

**Comment by simesy** [comment]
Thanks for your patience with me, this isn't my usual domain. I assume that Graph Search is the same as Microsoft Search. And the so the reason I can't access bookmarks through this PNP webpart yet is because Bookmarks endpoint is only in beta.

Works: https://graph.microsoft.com/beta/search/bookmarks
Doesn't work: https://graph.microsoft.com/v1.0/search/bookmarks

<img width="149" alt="graphql" src="https://user-images.githubusercontent.com/188856/161867853-588dd564-0aa1-4b14-8dd1-d6ba8dbbbe9e.png">

**Comment by wobba** [comment]
Correct.... I should have said "Microsoft Search". We do support calling the /beta endpoint but no one has added support to return bookmarks yet, and then rendering them.
