### ISSUE TITLE
A mixture of term-ID and label  is shown  in search result instead of just the label 

### ISSUE THREAD

**Issue by MKGy** [microsoft-search/pnp-modern-search#615]
**Version used**
feature/v4

**Describe the bug**
After updating from November 2020 release to current release and reconnecting web parts as necessary, my taxonomy term id filter values are not all translated to their label any longer. It worked fine before.

Unfortunately, I didn't save the code for the November 2020 release. Hence, I am unable to recreate an .sppkg file for it.

**To Reproduce**
1. Set up a refinable string managed search property to point to the "ows_taxid_***" crawled property in existing content.
2. Reindex the list/library.
3. Configure a filter pointing to this refinable string mangaged search property.

**Expected behavior**
The values of the terms should be presented by their labels only.
Notice how the refiner option "Tag" shows the labels of the term-IDs. At the same time the results webpart is showing a mixture of term-ID and label.

**Screenshots**
![image](https://user-images.githubusercontent.com/64076713/102223145-9a78b680-3ee4-11eb-8984-e2b0b2ab5968.png)

**Desktop (please complete the following information):**
 - Browser  chrome,Edge

**Additional context**
none

**Comment by knaveenstar** [comment]
Hi,
I have faced the same issue, please try the below one

Add the "Auto" before the field name e.g. "Autoowstaxid" in slot configuration
Enable locazation in configuration

**Comment by MKGy** [comment]
@knaveenstar  thanks for the hint. Now it works as desired. I made the small adjustment as follows:
![image](https://user-images.githubusercontent.com/64076713/102336226-352ecf00-3f91-11eb-845c-f750af53cc81.png)

And as result I get the following:
![image](https://user-images.githubusercontent.com/64076713/102336311-4bd52600-3f91-11eb-97e2-3ed2dcdf3dea.png)
