### ISSUE TITLE
Date Interval as Combo Box 

### ISSUE THREAD

**Issue by knaveenstar** [microsoft-search/pnp-modern-search#616]
!! Check existing issues before logging new ones !!

**Version used**
Ex: 4.0.0.0

**Describe the bug**
I have customized the PnP search result and Search Filter webpart. I want to display the Date interval values in the combo box. 

Currently, when I choose combo box for created fields it's showing as below Image
![image](https://user-images.githubusercontent.com/30283702/102230143-821f9080-3f12-11eb-81c2-68f31451d10e.png)

But I need the Date Interval value inside the combo box instead of DateTime value. I try to customize this but I unable to find which methods its converting the Datetime values to Date Interval values.

Please help me find this 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by wobba** [comment]
Use date range template in v4

**Comment by bhuviagrawal** [comment]
Hi @knaveenstar 
Did you find a solution to this? I'm looking for the exact same thing as you . 
If I use 'combo box' for the filters, then 'modified date' is not proper. And if I use 'date interval' only for modified date, then the UI doesn't match with others.

**Comment by kasperbolarsen** [comment]
This issue should have been resolved in the current version. If not , please create a new issue as this one is closed.
