### ISSUE TITLE
Additional custom layouts 

### ISSUE THREAD

**Issue by stact** [microsoft-search/pnp-modern-search#618]
**Is your feature request related to a problem? Please describe.**
It could be nice to allow extensibility to add additional layouts without selection of custom layout and pick a template url.
It will allow non developers to add PnP Search parts and configure without coding or asking if a template is existing.
![image](https://user-images.githubusercontent.com/9899166/102359803-88b11500-3fb1-11eb-8d9c-7c567a453c05.png)

**Describe the solution you'd like**
Allow extend globally Available layouts, when webmasters or a super users to display specific layout
![image](https://user-images.githubusercontent.com/9899166/102360554-71bef280-3fb2-11eb-80e7-9996e9b0ba83.png)

**Describe alternatives you've considered**
Apply a template url. Needs advanced knowledge.

**Additional context**
This V4 is promising! 🥇

**Comment by wobba** [comment]
We're working on supporting this for v4 - just need to have the right pieces in.

**Comment by FranckyC** [comment]
Hi @stac, working on it. We are aware of this use case ;)

**Comment by gary-walker-82** [comment]
@FranckyC  @wobba  is this feature still been worked on? and if not would you be open to a PR if I did it?

**Comment by FranckyC** [comment]
Hi @gary-walker-82, still on the backlog but no ETA for now. Sorry for the delay.

**Comment by wobba** [comment]
See https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_layout/
