### ISSUE TITLE
Search term "<html>AAAAAAAAAAAAAAAA</html>" resulting incorrect results when we configure query template.

### ISSUE THREAD

**Issue by mkchiliveri** [microsoft-search/pnp-modern-search#619]
I have configured modern search web part and configured with a query template having filters and comparing whether search term contains in a managed properties like below 

RefinableString00={QueryString.Category} Path:{SiteCollection.URL} DocumentStatusOWSCHCS=Published  (AssetTitleOWSTEXT:{searchTerms} OR AssetDescription:{searchTerms} OR AssetTags:{searchTerms})

**Comment by mkchiliveri** [comment]
I have configured modern search web part and configured with a query template having filters and comparing whether search term contains in a managed properties like below 

RefinableString00={QueryString.Category} Path:{SiteCollection.URL} DocumentStatusOWSCHCS=Published  (AssetTitleOWSTEXT:{searchTerms} OR AssetDescription:{searchTerms} OR AssetTags:{searchTerms})

**Comment by wobba** [comment]
Closing as the bug template was removed, and you did a free form issue, omitting all important details for repro.

**Comment by mkchiliveri** [comment]
@wobba Sorry, I did not fill the issue according to the template, i have opened new one with all the details i have here https://github.com/microsoft-search/pnp-modern-search/issues/620
