### ISSUE TITLE
Search term "<html>AAAAAAAAAAAAAAAA</html>" resulting incorrect results when we configure query template.

### ISSUE THREAD

**Issue by mkchiliveri** [microsoft-search/pnp-modern-search#620]
!! Check existing issues before logging new ones !!

**Version used**
Ex: 3.13

**Describe the bug**
I have configured modern search web part and configured with a query template like "RefinableString00={QueryString.AssetCategory} {searchTerms}" and searched in the search box with text `<html>AAAAAAAAAAAAAAAA</html>`. It is giving incorrect results. I have tested same web part without query template and it is giving results according to the search term.

**To Reproduce**
1. Configure webpart and search with `<html>AAAAAAAAAAAAAAAA</html>`
2. It will give results according to the search term AAAAAAAAAAAAAAAA
3. Now add some query in the query template and search again with `<html>AAAAAAAAAAAAAAAA</html>`
4. It is giving incorrect results

**Expected behavior**
It should filter the results according to query template and escape these "<html>" tags like it is doing for without query template.

**Screenshots**
![image](https://user-images.githubusercontent.com/13349122/102397644-259c9e00-4004-11eb-84b4-b9f0d8bb9ec7.png)
![image](https://user-images.githubusercontent.com/13349122/102397697-3fd67c00-4004-11eb-8ff1-09123bd12b57.png)

**Desktop (please complete the following information):**
Chrome

**Additional context**

**Comment by wobba** [comment]
What results do you get in OOB search using tags like that? And special characters are not searchable by default as they are tokenized away.

**Comment by mkchiliveri** [comment]
If i search with a word `CAR` it gives proper 15 results. But if i search with a word `<html>CAR</html>` it is giving more than 1000 incorrect results. Somehow html tags are affecting the search results.

**Comment by wobba** [comment]
As I said, special characters are not supported like that. Enclose them in quotes.

`"<html>CAR</html>"`

This is not a web part issue, but how KQL works.
