### ISSUE TITLE
Image included in multiline richtext list column not displayed

### ISSUE THREAD

**Issue by mongoux** [microsoft-search/pnp-modern-search#621]
Version used 3.13

**Describe the bug**

**If an image is added to the multi-line rich-text list column, it is not displayed when using handlebars expression.**
 
**Image:** rich text edit 
![image](https://user-images.githubusercontent.com/35407310/102399344-cb3e1600-3fe0-11eb-9e46-72976a7d68b3.png)

**Results web part:** Added the "Steps to Avoid and Correct Error" column to the template with {{CorrectiveActions}} managed property.
![image](https://user-images.githubusercontent.com/35407310/102399610-21ab5480-3fe1-11eb-83fb-ad73c8be0162.png)

**To Reproduce**
1. Create List and add multi-line rich-text list column
2. Select and edit list item
3. Add text and image to multi-line rich-text and save
3. Create a managed property for multi-line rich-text list column
4. add results web part to page
5. add {{multi-line rich-text list column managed property}} to custom template
6. Only text displayed in results, no image.

**Expected behavior**
Image and text displayed correctly when using handlebars expression.

**Desktop (please complete the following information):**
 - Browser [all]

**Comment by wobba** [comment]
Does #533 help?

**Comment by wobba** [comment]
@mongoux did you get a chance to test?

**Comment by wobba** [comment]
Close due to inactivity.
