### ISSUE TITLE
Unable to search onedrive with User.Name

### ISSUE THREAD

**Issue by alabonte** [microsoft-search/pnp-modern-search#622]
**Version used**
3.16

When a user name contains hyphens, his search returns noresult.  When the user name does not contain hyphens, it work properly.

I created a vertical search with this template to search in user files only : 

{searchboxquery} {?SPSiteURL:{User.Name}}

The results origin is set to organization. 

So, the User.Name function returns Jean-François Beaudoin but the hyphen seems to be a problem. 

I did many tests and i replaced the User.Name function with a string and i escaped the hypen.

     {searchboxquery} {?SPSiteURL:"Jean\-Francois Beaudoin"}

With this string, it worked.  If i replace the hyphen by a space, it works too.

Is it possible to escape or replace the hypen for the value returned by User.Name?

**Comment by wobba** [comment]
Name and SPSiteURL is not a good match as the URL contains the upn name.

`SiteTitle={User.Name} contentclass:sts_site SiteTemplate:SPSPERS` seems better

As the variable is expanded server side, there is little we can do.

**Comment by alabonte** [comment]
> Name and SPSiteURL is not a good match as the URL contains the upn name.
> 
> `SiteTitle={User.Name} contentclass:sts_site SiteTemplate:SPSPERS` seems better
> 
> As the variable is expanded server side, there is little we can do.

Thank you wobba.  It is working now with SiteTitle and SiteTemplate, but without contentclass.
