### ISSUE TITLE
RefinableDate Managed Property not sorting correctly

### ISSUE THREAD

**Issue by rslavey** [microsoft-search/pnp-modern-search#623]
**Version used**
Ex: 4

**Describe the bug**
I have a crawled property that is a date/time. I have mapped it to managed property RefinableDate00. I am able to see the data just fine in my results, but that column is not sorting correctly. Oddly, it appears to be sorting on the time and then the date part of the field.

I tried to use the handlebar getDate and the date appeared formatted correctly, but the sorting arrow went away altogether.

1. Can I sort on a column that uses the getDate handlebar?
2. Why would a date column be sorting on the time?

**To Reproduce**
1. Add SharePoint document library
2. Add custom column that is date/time format
3. Upload documents to doc library
4. Set the custom date column for each document
5. Wait for indexing
6. Find crawled property of your custom date/time column
7. Map it to RefinableDate00 (or whatever refinable date you want)
8. Wait for indexing
9. Add the RefinableDate00 column to the search results
10. Enable the "Sortable" checkbox.
11. Try to sort by this column -- does not sort correctly
12. Go back to columns and use handlebar {{getDate RefinableDate00 "MM/DD/YYYY"}}
13. After saving, sorting arrow goes away.

**Expected behavior**
It should sort by date for this column.

**Screenshots**
![image](https://user-images.githubusercontent.com/21177142/102418228-8ef7bf00-3fba-11eb-917a-dd417dcecf06.png)

![image](https://user-images.githubusercontent.com/21177142/102418265-a040cb80-3fba-11eb-8de6-9180c482fad7.png)

![image](https://user-images.githubusercontent.com/21177142/102418312-b8184f80-3fba-11eb-8ad5-ec12a26f43f7.png)

![image](https://user-images.githubusercontent.com/21177142/102418550-32e16a80-3fbb-11eb-8ce0-cc59e19a455d.png)

**Desktop (please complete the following information):**
 - Browser Edge (Chromium)

**Comment by wobba** [comment]
Sortable fields are text sorting only, and on-page sorting only. See https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-results/#search-settings
