### ISSUE TITLE
Question: Is there any way that we can access results of Vertical from URL

### ISSUE THREAD

**Issue by sekharB487** [microsoft-search/pnp-modern-search#624]
**Version used**
Ex: 3.15.3

**Describe the bug**
Question: Is there any way that we can access results of Vertical from URL as we see in Modern Search? if its possible, Kindly let me know the changes we have to make in our end. 

**Expected behavior**
As we see in Modern search, do we able to render vertical content with URL?
![image](https://user-images.githubusercontent.com/71835451/102477955-08f37b00-4083-11eb-9598-6ecb9c947a9b.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/71835451/102479388-d8acdc00-4084-11eb-94e2-0177be21f02d.png)

 - Browser [chrome, Edge, IE]

**Comment by wobba** [comment]
No, there is currently no API to read Microsoft Search configuration.
