### ISSUE TITLE
Rename ASPX label in filetype filter

### ISSUE THREAD

**Issue by alabonte** [microsoft-search/pnp-modern-search#626]
Is there a way to replace ASPX label in the filetype filter by another value?

I would like to replace « ASPX » by « Web pages » or something like that.

Thank you

![2020-12-17 10_26_49-Window](https://user-images.githubusercontent.com/7327483/102507791-a71b1d00-4052-11eb-822b-a67bf488dbdc.png)

**Comment by wobba** [comment]
1. Please don't remove the bug template - it's there for a reason
2. v4 will support custom templates for filters, so you can change the logic - we might add logic to file types to aggregate it a bit further out.
