### ISSUE TITLE
How to Link Custom Created Verticals with Custom Display Templates

### ISSUE THREAD

**Issue by Naveen-Rangarajan** [microsoft-search/pnp-modern-search#627]
I have created some custom verticals like All, Sites and News and re-used an existing vertical "People" (default available and deleted the other two named Video and Recently Used Item).

Search Vertical looks like - All   Sites    News    People

My query is how to have different display templates for each of the newly created custom vertical without loading the page or navigating to different pages like  all.aspx or sites.aspx or news.aspx.

**Comment by wobba** [comment]
Closed as bug template was removed and we don't know version or repro steps.

(and the answer can be found if you look at old closed issues)
