### ISSUE TITLE
Manually adding a selected property does not work

### ISSUE THREAD

**Issue by FKatrin** [microsoft-search/pnp-modern-search#629]
**Version used**
Ex: 4.0.0.0

**Describe the bug**
As my managed property does not appear in the drop-down list "Selected Properties", I manually added it and pressed "Enter". Now this seems to have created a new long item in this list that is all the properties concatenated. See the screenshots for reference.

**To reproduce**
1. Go to 'Selected Properties'
2. Click into the text, move the cursor to the end, type ",PropertyName", press Enter
3. Go to 'Manage People Fields'
4. Open the drop-down list in the 'Value' column.

OR
3. Copy the text in the field 'Selected Properties'
4. Paste the text into notepad and see the items appear multiple times.

**Expected behavior**
The property I inserted manually should be added to the drop-down list as a new single item.

**Screenshots**
![image](https://user-images.githubusercontent.com/76202478/102592984-90d59580-4114-11eb-8d7c-2b18e2452347.png)
![image](https://user-images.githubusercontent.com/76202478/102593913-ccbd2a80-4115-11eb-913a-ebdeaaa1b8f3.png)

**Desktop (please complete the following information):**
Google Chrome 84.0.4147.135 (Official Build) (64-bit)

**Comment by FranckyC** [comment]
Hi @FKatrin, to add a custom value to the selected properties, you have first to clear the combo box value, add your own value then and press 'Enter' to add it tho the list. Otherwise, the whole string is considered as the new property.
