### ISSUE TITLE
Page navigation followed by a search doesn't work as expected

### ISSUE THREAD

**Issue by VerlindenEAM** [microsoft-search/pnp-modern-search#630]
**Version used**
3.16

**Describe the bug**
If you navigate to a page in page navigation and then enter a query text in the searchbox, then the result doesn't show up but returns all values (you can see the result in a flash before all values are shown). If you refresh the page then the results from the query show up.

**To Reproduce**
1. Go to 'search page with searchbox, filters and search resutls'
2. Click on 'page 5 in page navigation'
3. Result shows in a flash
4. Previous results when click on page 5 in page navigation show up again.
5. Refresh page with F5
6. Result from query shows up.

**Expected behavior**
When you navigate to one of the pages in page navigation, then enter a search query in the searchbox, it should show the query results.

**Screenshots**
If needed I can sent out a screenshot, but due to customer data I cannot add it here.

**Desktop (please complete the following information):**
Both Chrome and Edge Chromium

**Additional context**
I noticed that when I remove the Dynamic Data Source connection (Page environment, Query string, Url fragment), the search works correct. But we have configured a search box on the front page, so we also need the data source connection.

**Comment by wobba** [comment]
I cannot repro.
- Searched for `FileType:docx`
- DOCX shows p1
- Nav to page 5
- DOCX shows p5
- Searched for `FileType:pptx`
- PPTX shows p1
- Nav to page 5
- PPTX shows p5

**Comment by VerlindenEAM** [comment]
Did you use Dynamic Data Source connection in the searchbox? It only happens with this connection.

________________________________

**Comment by VerlindenEAM** [comment]
I did some more testing and it happens only when using the following setting:
![image](https://user-images.githubusercontent.com/35732908/102764697-d8aa2600-437b-11eb-8530-7f80ad4d7bdd.png)

When I use Query string>Query paramenters it works fine.
Also I noticed on one search page the search box doesn't give the option queryParameters's properties>q
![image](https://user-images.githubusercontent.com/35732908/102764835-0f803c00-437c-11eb-9d0b-593fa23732d9.png)

**Comment by wobba** [comment]
Does it happen on query string using the nav-bar searchbox? Because you wouldn't use query string and the PnP search box together. You would tie the PnP search box to the result web part using dynamic data. Can you update the repro steps to a scenario you would use?

If you want the query params to list, they have to be part of the URL when you click "edit page" - only params in the URL will display - that's how SPFx build page environment.

**Comment by VerlindenEAM** [comment]
Hi Mikael,

First of all, best wishes for 2021 !

Thanks for the update, I managed to configure it as followed.

[cid:77760152-c6e5-4b36-b207-9d8b292d1e53]

[cid:b6b161f4-bb74-4372-89e8-85334839929e]

It is working now correctly from Searchbox or after searchbox from other page.
Also page navigation is working without issues.

Regards,
Erwin


________________________________
Van: Mikael Svenson <notifications@github.com>
Verzonden: maandag 21 december 2020 14:49
Aan: microsoft-search/pnp-modern-search <pnp-modern-search@noreply.github.com>
CC: Erwin Verlinden <verlindeneam@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [microsoft-search/pnp-modern-search] Page navigation followed by a search doesn't work as expected (#630)


Does it happen on query string using the nav-bar searchbox? Because you wouldn't use query string and the PnP search box together. You would tie the PnP search box to the result web part using dynamic data. Can you update the repro steps to a scenario you would use?

If you want the query params to list, they have to be part of the URL when you click "edit page" - only params in the URL will display - that's how SPFx build page environment.

**Comment by wobba** [comment]
Images are missing in your reply, but can we close the issue?

**Comment by VerlindenEAM** [comment]
Yes, you can close it

________________________________
