### ISSUE TITLE
New Property: QueryTemplatePropertiesUrl to allow Search in Modern Sites with Anonymous access

### ISSUE THREAD

**Issue by rumos-epc** [microsoft-search/pnp-modern-search#634]
**Is your feature request related to a problem? Please describe.**
In different projects we have the necessity to use Sharepoint Search in anonymous sites. As you know, by default, if you try to call the SharePoint Search REST API in an anonymous Sharepoint site you will have this error:

The SafeQueryPropertiesTemplateUrl "The SafeQueryPropertiesTemplateUrl "{0}" is not a valid URL." is not a valid URL

Article: https://blog.mastykarz.nl/configuring-sharepoint-2013-search-rest-api-anonymous-users/

**Describe the solution you'd like**
This problem is solved if we use the QueryTemplatePropertiesUrl parameter when invoking the Search REST API. Example:

sp.search({
                    Querytext: '*',
                    TrimDuplicates: false,
                    RowLimit: 1,
                    **QueryTemplatePropertiesUrl: 'spfile://webroot/queryparametertemplate.xml'**
                });

It would be nice if this component had a property "Anonymous Access" so we could use the PNP Modern Search Web Part also in Modern Sites with anonymous access.

**Describe alternatives you've considered**
The only alternative now is to customize our webparts to use this parameter in the request which would be a lot of work. Also, Modern Sites don't offer a solution OOB to allow native webparts to show results when navigating in anonymous sites

Thanks in Advance!

**Comment by wobba** [comment]
v3 and v4 of the web parts don't work for SharePoint on-prem, and anonymous login is not available for SharePoint Online.
