### ISSUE TITLE
supportsFullBleed is missing on V4

### ISSUE THREAD

**Issue by stact** [microsoft-search/pnp-modern-search#636]
On V3 we got full width support, not implemented on v4.

https://github.com/microsoft-search/pnp-modern-search/blob/2a2edd144b19c8674c4d4d8de71a9cc177bc7d43/search-parts/src/webparts/searchResults/SearchResultsWebPart.manifest.json#L8
vs
https://github.com/microsoft-search/pnp-modern-search/blob/feature/v4/search-parts/src/webparts/searchResults/SearchResultsWebPart.manifest.json

I could create a PR for this change, but maybe you need to enable additional settings on manifest?

**Comment by FranckyC** [comment]
Hi @stact, thank you for letting us know. We will add it the code before the release. Thanks!

**Comment by FranckyC** [comment]
Fixed in @stact  the v4 branch.
