### ISSUE TITLE
Open pnp-document-card news link in the same browser tab

### ISSUE THREAD

**Issue by davidoliveiracreateit** [microsoft-search/pnp-modern-search#637]
Hi.
I'm currently using the modern search webpart and i need to open the link from pnp-document-card in the current window/tab. How can we do that instead of opening the news link in a new tab? Exists any option by default we can use? 

The following lines describes what we have in the display template:

<div class="template_root">

        {{#if @root.hasPrimaryOrSecondaryResults}}

            <div class="template_defaultCard">

                {{#if showResultsCount}}

                <div class="template_resultCount">

                    <label class="ms-fontWeight-semibold">{{getCountMessage @root.paging.totalItemsCount keywords}}</label>

                </div>

                {{/if}}

                <div class="document-card-container">

                    {{#each items as |item|}}

                    <div class="document-card-item">

                        {{#> resultTypes item=item}}

                            {{!-- The block below will be used as default item template if no result types matched --}}

                            {{#eq item.contentclass 'STS_ListItem_851'}}

                                <pnp-video-card data-item="{{JSONstringify item}}" data-fields-configuration="{{JSONstringify @root.documentCardFields}}" data-enable-preview="{{@root.enablePreview}}" data-show-file-icon="{{@root.showFileIcon}}" data-is-compact="{{@root.isCompact}}"></pnp-video-card>

                            {{else}}

                                <pnp-document-card data-item="{{JSONstringify item}}" data-fields-configuration="{{JSONstringify @root.documentCardFields}}" data-enable-preview="{{@root.enablePreview}}" data-show-file-icon="{{@root.showFileIcon}}" data-is-compact="{{@root.isCompact}}"></pnp-document-card>

                            {{/eq}}

                        {{/resultTypes}}

                    </div>

                    {{/each}}

                </div>

            </div>

            {{#if @root.paging.showPaging}}

                <pnp-pagination

                    data-total-items="{{@root.paging.totalItemsCount}}"

                    data-hide-first-last-pages="{{@root.paging.hideFirstLastPages}}"

                    data-hide-disabled="{{@root.paging.hideDisabled}}"

                    data-hide-navigation="{{@root.paging.hideNavigation}}"

                    data-range="{{@root.paging.pagingRange}}"

                    data-items-count-per-page="{{@root.paging.itemsCountPerPage}}"

                    data-current-page-number="{{@root.paging.currentPageNumber}}"

                >

                </pnp-pagination>

            {{/if}}

        {{else}}

            {{#unless showBlank}}

                <div class="template_noResults">{{@root.strings.NoResultMessage}}</div>

            {{/unless}}

        {{/if}}

    </div>

</content>

 

<content id="placeholder">   

    <div class="placeholder_root">

        <div class="template_defaultCard">

            {{#if showResultsCount}}

                <div class="template_resultCount">

                    <span class="shimmer line" style="width: 20%"></span>

                </div>

            {{/if}}

            <div class="document-card-container">

                {{#times @root.paging.totalItemsCount}}

                    <div class="document-card-item">

                        <pnp-document-card-shimmers data-is-compact="{{@root.isCompact}}"></pnp-document-card-shimmers>

                    </div>

                {{/times}}

            </div>

        </div>

    </div>

</content>

**Comment by wobba** [comment]
The web components do not support this option right now. Marking this issue as a possible enhancement.

**Comment by fredericklin** [comment]
I'm interested in having the links open in the existing tab and not a new tab as well.  We are using pnp-document-card for metadata-driven local site navigation.
