### ISSUE TITLE
Is the managed properties ViewLifeTime and ViewLifeTimeUniqueUsers available ?

### ISSUE THREAD

**Issue by Naveen-Rangarajan** [microsoft-search/pnp-modern-search#638]
Hi,

I use Modern Search Version 3.16. 

How to retrieve the view counts as I don't see these managed properties either in Sort or Selected Properties of Search Results web part.

<img width="340" alt="ViewCount" src="https://user-images.githubusercontent.com/61411651/102999619-5d00d280-454f-11eb-8a9c-e3b0922a7cda.png">

**Sort** 
<img width="788" alt="Search Results Sort" src="https://user-images.githubusercontent.com/61411651/102999806-bd900f80-454f-11eb-87a7-dc992d1c96b3.png">

**Selected Properties**
<img width="461" alt="Selected Props" src="https://user-images.githubusercontent.com/61411651/103000000-25def100-4550-11eb-83a3-642f54f36847.png">

Any help truly appreciated 👍

**Comment by FranckyC** [comment]
Hi @Naveen-Rangarajan, you can add it manually to the selected properties dropdown list, Just clear all values in the text field, add you value and press enter. This should work.

**Comment by Naveen-Rangarajan** [comment]
Thank you :)

I am able to get the count. Thank you again for the quick reply.
