### ISSUE TITLE
Microsoft is deprecating some operators of FQL

### ISSUE THREAD

**Issue by darharis** [microsoft-search/pnp-modern-search#640]
Hi,

Recently we came to know that Microsoft is retiring some operators of FQL by February 2021 below is the link of that blog post from Microsoft team.

https://techcommunity.microsoft.com/t5/microsoft-search-blog/we-re-making-changes-to-search-in-sharepoint-online/ba-p/1971119

We are using pnp modern search version 3.14.2.0 in our sharepoint online SPFX application and we find out that modern search application is using FQL query when applying filters from Search Filters WebPart and it is also using FQL OR operator when selecting multiple values against a single Filter. As per the blog post Microsoft is deprecating the FQL OR operator with other operators.

What would be the solution for this ? Modern search application's Search Filter functionality will break after the retiring of OR Operator of FQL.

Below is the screenshot of the Search API request payload which is currently sending from modern search application using the FQL OR operator.
![image](https://user-images.githubusercontent.com/76810017/103408995-c45fe900-4b32-11eb-8a41-664321895a63.png)

**Comment by wobba** [comment]
If you read closely it's rank difference between `ANY` and `OR` which is impacted. Not `OR` itself.
