### ISSUE TITLE
'OR' operator in FQL is going to deprecated as per microsoft... will these web part work properly or we have to amend our code ? 

### ISSUE THREAD

**Issue by Asfandtnt** [microsoft-search/pnp-modern-search#641]
OR operator of FQL by February 2021 is going to retire following is the link of that blog post from Microsoft.

https://techcommunity.microsoft.com/t5/microsoft-search-blog/we-re-making-changes-to-search-in-sharepoint-online/ba-p/1971119

are you guys planning to update your web parts or they will work with out any change ?

**Comment by wobba** [comment]
@Asfandtnt read the post a bit closer and you see it's not going away. It's ranking between OR/ANY which is impacted.
