### ISSUE TITLE
Breadcrumbs and Redirect from another page to specific Search Vertical

### ISSUE THREAD

**Issue by Naveen-Rangarajan** [microsoft-search/pnp-modern-search#642]
Hi,

I use Modern Search Version 3.16

I have two queries -

1) Is it possible to have breadcrumb similar to SharePoint OOTB search result page. If possible, please redirect me on resources for the same.
<img width="278" alt="Breadcrumb" src="https://user-images.githubusercontent.com/61411651/103639193-01cdd780-4f74-11eb-9e77-96cd8aacc83e.png">

2) Is it possible to redirect to a specific vertical say People/ News from another page (say within the same tenant), like targeting a specific vertical?

Any help is appreciated. Thank you.

**Comment by wobba** [comment]
1. You can split up the property "ParentLink" and generate this.
2. Configure a parameter name and pass the name of the vertical as the value. E.g. `?vertical=people`
![image](https://user-images.githubusercontent.com/51104/103653131-5cf7ce00-4f64-11eb-8dec-0af586a75043.png)

**Comment by Naveen-Rangarajan** [comment]
Thank you for the response. 

So with this, I can have multiple target for Verticals from different pages right?

**Comment by wobba** [comment]
@Naveen-Rangarajan If someone codes a bread-crumb control you can have it. We're not adding features to v3, and for v4 you can build and load your own web-component.

And yes, you can create links like below to default start at a vertical.
* https://foo/mypage.aspx?vertical=Sales
* https://foo/mypage.aspx?vertical=Documents

**Comment by vishalgoyal2472** [comment]
> @Naveen-Rangarajan If someone codes a bread-crumb control you can have it. We're not adding features to v3, and for v4 you can build and load your own web-component.
> 
> And yes, you can create links like below to default start at a vertical.
> 
> * https://foo/mypage.aspx?vertical=Sales
> * https://foo/mypage.aspx?vertical=Documents

Do PnP community have any plan to launch breadcrumb feature in any newer version of PnP Search.

**Comment by kasperbolarsen** [comment]
No, the way it works is that an individual contributor decides to spend time on creating a PR that implements a feature that this individual finds valuable. 
You are of course welcome to create a PR implementing this feature,  and if we find the quality of the code sufficient, we will add the PR to a future version
