### ISSUE TITLE
Applying any of the Search Filters result in an empty Search Results webpart

### ISSUE THREAD

**Issue by AndyBolam** [microsoft-search/pnp-modern-search#643]
**Version used**
Version 4 

**Describe the bug**
Applying any of the Search Filters result in an empty Search Results webpart

**To Reproduce**

I have configured the search results web part to use the following properties:

AuthorOWSUSER,ContentTypeId,Created,CreatedBy,DefaultEncodingURL,FileType,HitHighlightedSummary,JobTitle,NormListID,NormSiteID,NormUniqueID,owstaxidmetadataalltagsinfo,Path,RefinableString40,RefinableString41,RefinableString42,RefinableString43,RefinableString44,RefinableString45,RefinableString46,RefinableString47,RefinableString48,RefinableString49,SiteTitle,SPSiteUrl,Title,UniqueID,UserName

I'm using result sources that I have created within the site collection and can filter the results using the Query Builder, however the equivalent filtering doesn't work in the V4 web parts.

The RefinableString properties are all mapped to different site columns such as Market, Language, Application etc as per the filters in the below screenshot:

![image](https://user-images.githubusercontent.com/30048002/103653901-1357b500-4f5d-11eb-895c-f812eb3add16.png)

As you can see I've configured the Search Filters web part which shows counts of results that match various properties within the search results, however when clicking on a Search Filter, all results are blanked in the Search Results web part and the search count next to the filter switches to zero:

![image](https://user-images.githubusercontent.com/30048002/103654086-57e35080-4f5d-11eb-861a-ebef40aa7a6c.png)

**Expected behavior**

When clicking on a filter option, I expect the Search Results web part to show a filtered view of the results according to the refinable property.

**Screenshots**
As above

**Desktop (please complete the following information):**
 - Browser Chrome, also tested in ChrEdge, and Edge

**Additional context**

I'm sure I'm doing something wrong configuration wise, as nobody else has appeared to have reported this, can anyone advise where I might have gone wrong?  Feel as though if this was a bug many other users would have seen it by now, don't see any other issues that describe the same thing.  All help appreciated.

**Comment by FranckyC** [comment]
Hi @AndyBolam, can we see the configuration you've made in the search filters WP? Make sure to use the 'RefinableStringXX' as field names for filters. Also make sure, the connection between search results and search filters WPs is configured as two ways.

**Comment by Laul0** [comment]
Hi @AndyBolam, does the @FranckyC's answer fixes your issue?
