### ISSUE TITLE
Expected date PnP Modern Search v4 Next Stable Release

### ISSUE THREAD

**Issue by sharmaanshu008** [microsoft-search/pnp-modern-search#648]
Hi,

We want to customize search filters template but this feature is not there in PnP Modern Search V3 so how we can modify filters template in v3?
I have seen that filters template customization is available in V4, Can we use V4 preview in production release and  if not what is expected date of production version release of this ?

**Comment by wobba** [comment]
If you want to do so in v3 you need to pull the code and add what is needed in a custom branch.

As for a v4 release we haven't set a date yet. Most likely we won't change much, but we'd like more feedback and testing before finalizing on something which won't break if we have to change it.

**Comment by FranckyC** [comment]
Hi @sharmaanshu008, what kind of customizations are you talking about? In the v4, only the Handlebars templates are customizable for refiners.  However, you can't write your own web component filters using the extensibility library. Just to make sure ;).

**Comment by wobba** [comment]
@FranckyC `However, you can't write your own web component filters using the extensibility library` <- are you saying custom web components cannot be used in the handlebar templates for refiners?

**Comment by FranckyC** [comment]
What I'm saying is you can use 'regular' web components in refiner HB template but you can't write 'filter' web components because you don't have access to the underlying events used to filter results. Sorry for the confusion.

**Comment by FranckyC** [comment]
I close this one as the production version is now available.
