### ISSUE TITLE
V4 - Filter web part not hiding according to selected vertical

### ISSUE THREAD

**Issue by ggelosi** [microsoft-search/pnp-modern-search#649]
**Version used**
4.0 preview

**Describe the bug**
When using in a single page both verticals, filters and search results web parts, verticals allow only to show/hide associated results web part but filter web part will always be visible after the connected results web part has been shown at least once, even if it's no more visible due to the change of the selected vertical

**To Reproduce**
1. Create a page with two search results web parts and two filter web parts and connect each filter web part to one of the search results
2. Add a vertical webpart and set both search results to be visible only when one of the verticals is selected and save the page 
3. Navigate to the page, the first vertical should be selected, one search results is visible and filters connected to that search results are visible too
4. Change vertical
5. First search results become hidden while its filters are still visible and second search results and filter web part show
6. Change vertical again to first value
7. First search results web part return visible, second search results gets hidden but second filter web part is still shown

**Expected behavior**
Connected filter web parts should show/hide accordingly to the search results web part, when this is connected to verticals

**Desktop (please complete the following information):**
 - Browser [chrome, edge]

**Comment by FranckyC** [comment]
Hi @ggelosi, this behavior is not supported. However, you can connect multiple search web parts to a single search filter WP. 

![image](https://user-images.githubusercontent.com/5659122/104133342-05d16f00-5351-11eb-9125-11c66052ff38.png)

This way the displayed, filters will only be related to the current visible search results.

**Comment by ggelosi** [comment]
Hi @FranckyC,

thanks for your suggestion, I haven't thought about using webparts like them (maybe I suggest to include some description on this behaviour on web part documentation?)

For me, this issue can be closed now..thanks again!
