### ISSUE TITLE
Mapping Crawled Property to Managed Refinable

### ISSUE THREAD

**Issue by EdgarasKarpavicius** [microsoft-search/pnp-modern-search#65]
Hello,

I am attempting to map a managed metadata tag to a refinable string i.e.(RefinableString100 - reserved for SPO by Microsoft), however when trying to save my changes, I encounter the below issue:

![Screenshot](https://user-images.githubusercontent.com/59877249/72798679-7f051d00-3c3b-11ea-80ef-a60d6b7d8934.png)

I appreciate it's a problem with SharePoint Online itself, rather than the Web Part but wanted to ask whether anyone has experienced this before, and whether there is a workaround for this.

Many Thanks

**Comment by FranckyC** [comment]
Hi @EdgarasKarpavicius This is definitely an issue with your tenant and obviously not related to this solution. I have to close it. I suggest you to post your issue in the [Tech Community Forum](https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint) or submit a ticket to Microsoft through your Office 365 portal.
