### ISSUE TITLE
Impact on pnp-modern-search due to Microsoft changes to search in SharePoint Online 

### ISSUE THREAD

**Issue by akansha1102** [microsoft-search/pnp-modern-search#650]
**Version used**
3.14.2.0

**Describe the bug**
Is there any impact of Microsoft changes to search in SharePoint Online on pnp-modern-search webparts, 
Received below update from Microsoft message center
•	We will be retiring several FQL conditions in SharePoint Online search. Instead we recommend the utilization of KQL, which is where we will continue to invest.
o	Learn more about KQL here: Keyword Query Language (KQL) syntax reference.
•	We will be updating search query rules and removing specific conditions from SharePoint Online and recommend using answers in Microsoft Search.
o	Learn more about answers in Microsoft Search here: Plan your content.
•	We will be removing the ability to configure authoritative pages in SharePoint Online and recommend using Microsoft Answers.
o	Learn more about answers in Microsoft Search here: Plan your content.
•	We will be removing personal favorites and recommend using personal query history in Microsoft Search.
o	Learn more about personal favorites here: Change settings for query suggestions, people suggestions, and personal favorites results.
•	Custom rank models and Manage Query Client Types were inherited from the on-premises version(s) of SharePoint Server and are not supported in SharePoint Online. As part of our continued investments in Microsoft Search we’ll be retiring these capabilities and related settings from SharePoint Online.
o	Learn more about how to leverage these capabilities in SharePoint Online review:
	Manage query client types
	Create a custom ranking model by using the Ranking Model Tuning App

**Comment by wobba** [comment]
Short answer, no.

If you have implemented a feature impacted by the above statement (99.99% change the answer is no), then you would be impacted if you used those features also via PnP Modern Search web parts.

If you don't really understand the implications of the deprecation message you should be good 🙂
