### ISSUE TITLE
Modern script editor not able to add on page

### ISSUE THREAD

**Issue by Sarvesh700** [microsoft-search/pnp-modern-search#651]
Hi team,

We are using modern script editor webpart in our different site collections and it's working fine. Recently we have created new site collection and we want to use same modern web part in this site collection. Problem is we are able to add script editor web part on site but not on any site pages. Can anyone suggest what is the problem here? Do we need to add any settings at site collection level?

**Comment by wobba** [comment]
See https://github.com/pnp/sp-dev-fx-webparts/blob/master/samples/react-script-editor/README.md#deploy-to-non-script-sites--modern-team-sites
