### ISSUE TITLE
question about results types

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#652]
**Is your feature request related to a problem? Please describe.**
I'm wondering if it is possible to have logic applied inside of an "Edit Results Type" results layout (V3). I'm trying to determine if I can use logic to change the color of a refinablestring value based on the value.

**Describe the solution you'd like**
In the html of the results type layout, I display {{RefinableString122}}. Is there any way to use logic to change the color of the result based on the value? 

**Describe alternatives you've considered**
I have tinkered and tried to figure out if you can use handlebar (if, contains, eq) to compare the refinablestring with a value and thus modify the display, but am having no luck. I'm not even sure if you can use handlebars here, or if you can use them with a refinablestring value.

**Additional context**
Examples or suggestions greatly appreciated. Is this even possible? If it is, what would the syntax be? 
{{#eq ({{RefinableString122}} "active")}} xyz {{/eq}} and other variations most definitely did not work!  :-)

**Comment by wobba** [comment]
You can use result types and set the triggering condition to "RefinableString122 equals xyz", and then have one template per condition.

**Comment by Heidi-Connor** [comment]
Thanks much wobba. The catch is that I'm already using Results Types to target specific contenttypes to specific verticals (for result layout). It doesn't look like there's any way to do an OR in the Edit Result Type screen, and I'd need to be able to say contentclass contains STS_ListItem_GenericList AND RefinableString122:xyz. It doesn't look like I can stack them. Oh well.

**Comment by wobba** [comment]
@Heidi-Connor Got it, so you would need multiple conditions. In theory you should be able to do handle bar expressions in the result type templates as well, but I haven't tried it.

**Comment by bryllyg** [comment]
Thanks. I'll keep hunting to see if I can figure out a way.

**Comment by bryllyg** [comment]
Got it working :-) I wasn't grasping that the {{}} were not always included around the term being queried. Once I got over that misconception, easy. 
 {{#is RefinableString122 'active'}}
	<span class="statusActive">{{RefinableString122}}</span>
{{/is}}

Thanks for the assistance!
