### ISSUE TITLE
V4 Search Query Template escape/ignore curly braces/tokens

### ISSUE THREAD

**Issue by taylorjandrew** [microsoft-search/pnp-modern-search#653]
**Version used**
4.0.0-preview

**Describe the bug**
I am trying to use the Query template in the PnP - Search Results web part to set the scope for the search results. I need to filter on specific Hub Site Ids (departmentId) which are guids. The guid contains curly braces, which the web part interprets as a token delimiter. I need to escape the curly braces somehow.

**To Reproduce**
Edit a V4 PnP - Search Results web part and add a filter to a known hub site id in the Query template such as "{searchTerms} departmentId:'{c141ac11-6db9-4773-985e-1c1effe79eda}'

**Expected behavior**
There should be a way to use (escape) curly braces in the search template without engaging token substitution.

**Screenshots**
n/a

**Desktop (please complete the following information):**
any

**Additional context**
This works in V3.x
I have tried using html or url escape codes, double/triple/quad brackets, backslash, handlebar ignore methods, etc. etc.
I filter by guid(s) to scope searches to particular related selection of (hubbed) sites .

**Comment by wobba** [comment]
Did you try?

`{searchTerms} departmentId:'{{c141ac11-6db9-4773-985e-1c1effe79eda}}`

**Comment by taylorjandrew** [comment]
Hi, yes, that results in - departmentId:'{}'

**Comment by FranckyC** [comment]
Hi @taylorjandrew , I'm able to reproduce the issue. Working on a fix. Thanks!

**Comment by FranckyC** [comment]
@taylorjandrew Should be resolved in the v4 branch if you have the chance to test it.
