### ISSUE TITLE
Set refiners programmatically

### ISSUE THREAD

**Issue by Abrissirba** [microsoft-search/pnp-modern-search#655]
We have a custom web part that we have used to build up a search query with refiners for the old search. We are now looking at migrating this to instead use pnp-modern-search for the search result and refiners. The problem we have is that we can't update the refiners after the page has loaded.

The flow that we have tried 

1. The user makes a search though our search component.
2. The url is updated with the querystring parameters q and filters .
3. The search result is updated with the q query but the update of the filter parameter does not update the refiners.
4. If the page is reloaded, the refiners is set to what is available in the url.

Looking at the code it seems like the refiners are only updated on the first load, https://github.com/microsoft-search/pnp-modern-search/blob/9b8e48d6664d0b83d42a8fba42ae22a806cc353e/search-parts/src/webparts/searchResults/SearchResultsWebPart.ts#L210

Is it possible to force the refiners to be updated from the url or some other source?

**Comment by wobba** [comment]
1. You have deleted the issue logging template which you need to fill out for us to know which version of the web parts etc you are using
2. v3 support deep linking on filters as per https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-results/#filters-deep-links

Issue is closed due to point 1

**Comment by Abrissirba** [comment]
Thanks, sorry about deleting the template. I am using v3 and from your answer I take that there are no way of setting the refiners from code/url after page load.

**Comment by wobba** [comment]
Not without a page re-load. But, you can look at the dynamic data interface between the refiner and search result wp - and implement the same thing. This way you should in theory be able to connect your webpart with the two others. The challenge is that they only support one connection each, not two, v4 allows connection to multiple refiner wp's - so it should be possible there.
