### ISSUE TITLE
QUESTION: is there a way to put custom javascript into template?

### ISSUE THREAD

**Issue by evlo** [microsoft-search/pnp-modern-search#659]
Is there a way to put custom javascript into custom search results template?

My idea is something like this:
```
<content id="template">

    <style>
        /* Insert your CSS overrides here */
    </style>

<script type="text/javascript">
$('#myElementInSearchResults').click(
	function(e) {
alert('test')
	}
);
</script>
....
```

**Comment by FranckyC** [comment]
Hi @evlo, short answer: no. You must use a custom web component to do that https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_web_component/. Any `<script>` tag will be removed automatically from your template at runtime.

**Comment by wobba** [comment]
@evlo ..and the reason is to avoid script injection and potential security issues.

**Comment by evlo** [comment]
Thank, i thought it might be the case, even looked at it, so now i'm trying to implement the extension, but can't figure out where should I get **BaseWebComponent**.

**Comment by evlo** [comment]
I'm quite new to this npm and react thing, so I'm trying to create library component as I wanted to try project from scratch and not use the example and I simply don't see option create library component in yeoman
https://i.imgur.com/jX5xdVI.png

what am I doing wrong? :)

**Comment by evlo** [comment]
So I'm quite new to the whole npm, react thing - should I just copy models from the example?

**Comment by wobba** [comment]
Depending on version 3 or 4, start with docs at https://microsoft-search.github.io/pnp-modern-search/
