### ISSUE TITLE
Displaying Multiline Columns in Search Results custom layout

### ISSUE THREAD

**Issue by Somu76** [microsoft-search/pnp-modern-search#663]
__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
Ex: 3.14.2

**Describe the bug**
I am trying to use a custom layout to display a MultiLine Column associated with a search result, in the search results webpart. I have configured a RefinableString MP to return the column, and am able to see the result coming back. However, it seems like the newline character that is part of the Multi-Line field seems to be ignored, and I am getting everything in a single line instead.

![image](https://user-images.githubusercontent.com/12059785/104513655-f9058300-55bd-11eb-8947-9610a985c99c.png)

The search Result JSON has the value coming back like this:
{
								"Key": "RefinableString01",
								"Value": "Test\nMultiLine\nPlainText\nListColumn",
								"ValueType": "Edm.String"
},

The layout has the item specified as below:
<span><p>
      {{#if RefinableString01}}
      {{RefinableString01}}
      {{/if}}</p></span>

Trying to see if this is something that can be fixed, or if it is not feasible to get the '\n' converted to <br> here.,.. 

**To Reproduce**
1. Create a MultiLine column (Text) in a list, and configure it to be returned as a Managed Property
2. Add some items with values in that column, and have multiple lines to display.
2. Display it in a Search Result webpart

**Expected behavior**
The column would preserve the multi-line feature of the column.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser : Edge

**Additional context**

**Comment by wobba** [comment]
You need to add `<pre>` tags around the data or replace the newline with a `<br>` tag in order to get HTML to render it.

**Comment by Somu76** [comment]
Thanks much. The <pre> tag worked. What is the <pre> tag doing here? Is that like a pre-compilation header?

**Comment by Somu76** [comment]
Thanks, the  `<pre>` tag worked. Is this like a pre-compilation header?

**Comment by wobba** [comment]
Read up on the HTML spec :)
