### ISSUE TITLE
Not able to successfully install example extension library on Sharepoint online site collection

### ISSUE THREAD

**Issue by evlo** [microsoft-search/pnp-modern-search#664]
Hi, 

I got latest example library from github, run
```
npm i
gulp bundle --ship
gulp package-solution --ship
```
added PnP Modern Search - Search Web Parts sppkg to site collection appCatalog
added pnp-modern-search-extensibility-library.sppkg to site collection appCatalog
added app PnP Modern Search - Search Web Parts
added app PnP Modern Search - Extensibility Library Demo

I ended up with 4 errors in app install
https://i.imgur.com/w6KQqPn.png
when clicking on number 4 i just get blank page

Same thing happened for me when I tried creating library from scratch using yoman sharepoint template and selecting library component, setting id in manifest specified in documentation (2501f2fd-d601-4da4-a04d-9f0bd85b1f54) and copying models from example and adding basically empty component that just displays hello world div

We are on V3 NPM search thought.

**Comment by evlo** [comment]
Running
```
Connect-SPOService -Url $tenantUrl
Set-SPOSite -Identity $siteUrl -DenyAddAndCustomizePages $false
Disconnect-SPOService 
```
I was able to see the error is
The 'Type' attribute is invalid - The value 'Library' is invalid according to its datatype 'http://schemas.microsoft.com/sharepoint/:ClientComponentType' - The Enumeration constraint failed. at Microsoft.SharePoint.Administration.SPSolutionPackage.FeatureXmlValidationCallback.XmlValidationCallBack

**Comment by wobba** [comment]
Closing as you found the SPFx limitation in the linked issue.

**Comment by evlo** [comment]
I have created dev tenant and tried both tenant and site collection solutions and ended with same error, even generating empty library produces these errors.

**Comment by wobba** [comment]
The extension library HAS to be deployed with `Make this solution available to all sites in the organization` as per https://microsoft-search.github.io/pnp-modern-search/installation/
