### ISSUE TITLE
Option to search on partial text 

### ISSUE THREAD

**Issue by annetimdegraaf** [microsoft-search/pnp-modern-search#666]
Hi, don't know if this is a bug or feature question. Is there any workaround with this webpart to search within metadata? For example:

Metadata tag: Creamcheese, oldcheese

Lets say I want to find all content that contains cheese in the metadata. Default you can only use * at the end of a seach term. Is there any solution with this tool to work around it? 

Running the latest v3

Thanks in advanced!

**Comment by wobba** [comment]
Neither, it's related to core search capabilities and outside the scope of this project :) 

Search support adding * at the end of a term for wildcard, not at the start.

`cheese*` works `*cheese` does not.
