### ISSUE TITLE
Search query log files

### ISSUE THREAD

**Issue by tony-philipose** [microsoft-search/pnp-modern-search#671]
Is there any way to create/get log files for the user searching keywords, for analyzing the frequent search keyword like...

**Comment by wobba** [comment]
Microsoft Search admin page should show trending/top queries https://admin.microsoft.com/Adminportal/Home?source=applauncher#/MicrosoftSearch

**Comment by tony-philipose** [comment]
I think the page [https://admin.microsoft.com/Adminportal/Home?source=applauncher#/MicrosoftSearch](https://admin.microsoft.com/Adminportal/Home?source=applauncher#/MicrosoftSearch) showing the search query data provided by ‎Microsoft Search in Bing‎ and also showing zero results. 

Is this the same is used for keeping the search query logs from the PNP Search and MS Intelligent search

**Comment by wobba** [comment]
See https://docs.microsoft.com/en-us/sharepoint/view-search-usage-reports for the options provided by the product. I checked a few sites and don't see any numbers so unsure of how/if it logs. I would raise a support ticket to get clarity.

Your other option is to add custom logging to the page.

**Comment by tony-philipose** [comment]
> See https://docs.microsoft.com/en-us/sharepoint/view-search-usage-reports for the options provided by the product. I checked a few sites and don't see any numbers so unsure of how/if it logs. I would raise a support ticket to get clarity.
> 
> Your other option is to add custom logging to the page.

thank you @wobba
