### ISSUE TITLE
Can't enable the v4 solution in app catalog because it has same product id as older version

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#672]
**Version used**
4.0

**Describe the bug**
Can't enable the solution in app catalog because it has same product id as older version (3.14.2). 

**To Reproduce**
1. Download sppkg file
2. Upload to app catalog

**Expected behavior**
Docs state older version can co exist with v4

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
SP Online

**Comment by FranckyC** [comment]
Hi @webbrewer , did you use the latest package version, The IDs shouldn't be the same between v3 and v4.

**Comment by webbrewer** [comment]
I used the _latest_ Nov 29 one but I guess that's an update to v3. I'll try the v4 preview next. Thanks!

**Comment by webbrewer** [comment]
@FranckyC  It turns out the v4 Preview DOES have the same product id so won't deploy: {890AFFEF-33E0-4D72-BD72-36399E02143B}

**Comment by FranckyC** [comment]
@webbrewer the version numbers are incorrect so it may be the wrong package for v4. Let me check and regenerate a new package if it is the case.

**Comment by FranckyC** [comment]
@webbrewer Can you try now? https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.0.0-preview

**Comment by webbrewer** [comment]
@FranckyC  That worked - thank you!
