### ISSUE TITLE
Unable to add pnp-modern-search-extensibility-library for query suggestion

### ISSUE THREAD

**Issue by sekharB487** [microsoft-search/pnp-modern-search#673]
**Version used**
Ex: 3.15.3

Hi, I had deployed pnp-modern-search-extensibility-library package in app catalog with site collection scope. I am trying to install as an app from site contents. Facing issue as 4 install errors. I am unable to find what are those errors. Please help me out to resolve this.
![image](https://user-images.githubusercontent.com/71835451/104888763-33db3280-5993-11eb-8faf-231364b4b9e7.png)
![image](https://user-images.githubusercontent.com/71835451/104888811-46ee0280-5993-11eb-9a7f-d15f031def95.png)

If I deploy in tenent wide, I am able to see configure suggestions in searchbox webpart propertypane. Enabled sharepoint query suggestions. its been nearly 48 hrs but I am unable to see any suggestion below search box on typing. Not sure whether I am doing wrong or Need to update custom code.?

**Expected behavior**
Install in site collection/tenent scope, need to get query suggestions under search box webpart. 
![image](https://user-images.githubusercontent.com/71835451/104889445-43a74680-5994-11eb-8d14-006ad68fd9ad.png)

 - Browser [chrome, Edge,IE]

**Comment by moezbouattour** [comment]
Hello,
You have to deploy it in the site collection app catalog and not in the tenant app catalog and you have to select "Make this solution available to all sites in the organization"
you don't need to add the app to the site contents
![image](https://user-images.githubusercontent.com/25154586/104928216-ab648e00-59a2-11eb-8fa3-d4ce76369551.png)

**Comment by sekharB487** [comment]
Hi @moezbouattour, thanks for your response.
I did this. Do I need to wait upto 24hrs to get the suggestions under searchbox?
![image](https://user-images.githubusercontent.com/71835451/104940768-357b1980-59d8-11eb-9490-e6e5ddea98b3.png)

**Comment by sekharB487** [comment]
Hi @moezbouattour, Enabling **SharePoint Query Suggestions**, Do we get suggestions from SharePoint site collection or it gets suggestions as is as OOB search?
![image](https://user-images.githubusercontent.com/71835451/105048494-a6cad300-5a91-11eb-8305-c27e1fa16bca.png)
![image](https://user-images.githubusercontent.com/71835451/105048526-af230e00-5a91-11eb-9325-bcd5d875c80d.png)

**Comment by wobba** [comment]
@sekharB487 it should behave same as classic yes as suggestions are provided based on site id and result source id + global manually entered ones.

**Comment by wobba** [comment]
Library solutions have to be installed in the tenant app catalog - not in a site. That's a limitation by SPFx.
