### ISSUE TITLE
Entries in the filter webpart are missing (v4.0.0)

### ISSUE THREAD

**Issue by aThuemmel** [microsoft-search/pnp-modern-search#674]
**Version used**
Ex: 4.0.0

**Describe the bug**
Hi team, i experience a problem with the filters webpart. I build a overview´s page with some compared lists. It´s about a Market Managing Site with a lot of lists. But all lists are related to the Market List. Now i have the problem that the filter webpart does not show all entries that it should be.

In the Screenshot you can see that for example on page 17 there is a market called: "Mahrburg-Wehrda". But in the filters Webparts it is not appearing.  The entry above is Mainh.-Mainflingen, this entry appears in the Filters Webpart.

I see an entry in the Search Results Webpart, but this (and more other entries) do not show up in the Filters webpart. But the webparts are connected.

Is it a problem that these entries appear at page 15 or later? Does the webpart just loads entries from the first 10 pages? Has it a limit of loading entries? But i have pages where it works with 30.000 entries, so i don´t think so.

**To Reproduce**
1. Add a Search Refiner Webpart to your page.
2. Add Search Results Webparts to your page.
3. Connect the Search Filters Webpart to the Search Results Webpart.
4. Check if all entries from the Search Results Webpart are also shown in the Filters Webpart.

**Expected behavior**
I expect that all entries from the search results webpart does appear in the search filters webpart.

**Screenshots**
![image](https://user-images.githubusercontent.com/43062820/104898347-d38bc700-5979-11eb-8bcf-45f2c63ad041.png)
![image](https://user-images.githubusercontent.com/43062820/104898508-05049280-597a-11eb-9529-73ecd76e9f3e.png)

**Desktop (please complete the following information):**
 Browser: Chrome

**Comment by wobba** [comment]
Can you look at the JSON response of the query being issued and see if the data is being returned?

**Comment by aThuemmel** [comment]
Sorry for my late reply! And also sorry, but i dont get it which response you mean and how to get it? The Debug layout in the search results webpart:
{
        "Rank": "0",
        "DocId": "17659127164630",
        "AuthorOWSUSER": " | Systemkonto | 5348415245504F494E545C73797374656D SHAREPOINT\\system",
        "ContentTypeId": "0x0100F9F7A7F1390524499C539F79FC824F0B",
        "Created": "2017-09-18T13:41:25.0000000Z",
        "CreatedBy": "Systemkonto",
        "DefaultEncodingURL": "https://heurich.sharepoint.com/sites/Objektverwaltung_Logo/Lists/Eigentmer%20%20Vermieter/138_.000",
        "FileType": null,
        "HitHighlightedSummary": "",
        "NormListID": "d7a89c39-dfea-4a12-94a6-13f1be074e08",
        "NormSiteID": "f911494e-0884-4f33-89db-6155e791e31f",
        "NormUniqueID": "48ed3e4a-d94d-414f-84ce-871b93246a52",
        "ows-ansprechpartner-I": "Grundstücksgemeinschaft Schwarz - Schwarz Manfred",
        "owstaxidmetadataalltagsinfo": "",
        "Path": "https://heurich.sharepoint.com/sites/Objektverwaltung_Logo/Lists/Eigentmer  Vermieter/DispForm.aspx?ID=138",
        "RefinableString01": "Marburg-Wehrda",
        "SiteTitle": "Objektverwaltung Logo",
        "SPSiteUrl": "https://heurich.sharepoint.com/sites/objektverwaltung_logo",
        "Title": "DispForm.aspx",
        "UniqueID": "{48ED3E4A-D94D-414F-84CE-871B93246A52}",
        "UserName": null,
        "WorkPhone": null,
        "SiteId": "f911494e-0884-4f33-89db-6155e791e31f",
        "WebId": "1d2c06c1-5cfb-422c-88e6-52ae82c68e4f",
        "contentclass": "STS_ListItem_GenericList",
        "IsExternalContent": "false",
        "ListId": "d7a89c39-dfea-4a12-94a6-13f1be074e08",
        "OriginalPath": "https://heurich.sharepoint.com/sites/Objektverwaltung_Logo/Lists/Eigentmer  Vermieter/DispForm.aspx?ID=138",
        "VermieterabOWSDATE": "31.12.2005 23:00:00",
        "VermieterbisOWSDATE": null,
        "ResultTypeIdList": null,
        "ResultTypeId": null,
        "RenderTemplateId": "~sitecollection/_catalogs/masterpage/Display Templates/Search/Item_Default.js",
        "piSearchResultId": "ARIAǂ3e111f9b-f438-431a-8d93-653fb1229906ǂe50f3fd8-9294-42a1-b8f4-b1c686e71766ǂ3e111f9b-f438-431a-8d93-653fb1229906.1000.110ǂ",
        "GeoLocationSource": "EUR",
        "PartitionId": "29647f11-9566-488e-98ae-ec6b2d569dca",
        "UrlZone": "0",
        "Culture": "en-US",
        "AutoPreviewUrl": "https://heurich.sharepoint.com/sites/Objektverwaltung_Logo/Lists/Eigentmer%20%20Vermieter/138_.000?web=1"
      }
    ],
    "filters": [
      {
        "filterName": "RefinableString01",
        "values": [
          {
            "count": 6,
            "name": "Baunatal",
            "value": "\"ǂǂ4261756e6174616c\"",
            "operator": 6
          },
          {
            "count": 5,
            "name": "Ebelsbach",
            "value": "\"ǂǂ4562656c7362616368\"",
            "operator": 6
          },
          {
            "count": 5,
            "name": "Heringen",
            "value": "\"ǂǂ486572696e67656e\"",
            "operator": 6
          },
          {
            "count": 5,
            "name": "Groß Gerau",
            "value": "\"ǂǂ47726fc39f204765726175\"",
            "operator": 6
          },
          {
            "count": 4,
            "name": "Sterzhausen",
            "value": "\"ǂǂ537465727a68617573656e\"",
            "operator": 6
          },
          {
            "count": 4,
            "name": "Niederdorfelden",
            "value": "\"ǂǂ4e6965646572646f7266656c64656e\"",
            "operator": 6
          },
          {
            "count": 4,
            "name": "Bad Kissingen",
            "value": "\"ǂǂ426164204b697373696e67656e\"",
            "operator": 6
          },
          {
            "count": 4,
            "name": "Haßfurt II",
            "value": "\"ǂǂ4861c39f66757274204949\"",
            "operator": 6
          },
          {
            "count": 4,
            "name": "Mainh.-Mainflingen",
            "value": "\"ǂǂ4d61696e682e2d4d61696e666c696e67656e\"",
            "operator": 6
          },
          {
            "count": 4,
            "name": "Bad Wildungen",
            "value": "\"ǂǂ4261642057696c64756e67656e\"",
            "operator": 6
          },
          {
            "count": 4,
            "name": "Ludwigsau",
            "value": "\"ǂǂ4c7564776967736175\"",
            "operator": 6
          },
          {
            "count": 4,
            "name": "Hofheim/Unterfranken",
            "value": "\"ǂǂ486f666865696d2f556e7465726672616e6b656e\"",
            "operator": 6
          },
          {
            "count": 4,
            "name": "Birstein",
            "value": "\"ǂǂ426972737465696e\"",
            "operator": 6
          },
          {
            "count": 3,
            "name": "Witzenhausen",
            "value": "\"ǂǂ5769747a656e68617573656e\"",
            "operator": 6
          },
          {
            "count": 3,
            "name": "Aschaffenburg",
            "value": "\"ǂǂ41736368616666656e62757267\"",
            "operator": 6
          },
          {
            "count": 3,
            "name": "Sontra",
            "value": "\"ǂǂ536f6e747261\"",
            "operator": 6
          },
          {
            "count": 3,
            "name": "Solms-Oberbiel",
            "value": "\"ǂǂ536f6c6d732d4f6265726269656c\"",
            "operator": 6
          },
          {
            "count": 3,
            "name": "Büdingen I",
            "value": "\"ǂǂ42c3bc64696e67656e2049\"",
            "operator": 6
          },
          {
            "count": 3,
            "name": "Karlstadt I",
            "value": "\"ǂǂ4b61726c73746164742049\"",
            "operator": 6
          },
          {
            "count": 3,
            "name": "Niederaula",
            "value": "\"ǂǂ4e696564657261756c61\"",
            "operator": 6
          },
          {
            "count": 3,
            "name": "Nidderau-Heldenbergen",
            "value": "\"ǂǂ4e696464657261752d48656c64656e62657267656e\"",
            "operator": 6
          },
          {
            "count": 3,
            "name": "Gießen I",
            "value": "\"ǂǂ476965c39f656e2049\"",
            "operator": 6
          },
          {
            "count": 3,
            "name": "Litzendorf-Pödeldorf",
            "value": "\"ǂǂ4c69747a656e646f72662d50c3b664656c646f7266\"",
            "operator": 6
          },
          {
            "count": 3,
            "name": "Eschwege I",
            "value": "\"ǂǂ45736368776567652049\"",
            "operator": 6
          },
          {
            "count": 3,
            "name": "XXGroßenlüder",
            "value": "\"ǂǂ585847726fc39f656e6cc3bc646572\"",
            "operator": 6
          },
          {
            "count": 3,
            "name": "Königstädten",
            "value": "\"ǂǂ4bc3b66e69677374c3a46474656e\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Hanau",
            "value": "\"ǂǂ48616e6175\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Hünfeld I",
            "value": "\"ǂǂ48c3bc6e66656c642049\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Kreuzwertheim",
            "value": "\"ǂǂ4b7265757a776572746865696d\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Mittelkalbach",
            "value": "\"ǂǂ4d697474656c6b616c62616368\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Neuh.-Taunusstein",
            "value": "\"ǂǂ4e6575682e2d5461756e7573737465696e\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Bad Hersfeld I",
            "value": "\"ǂǂ426164204865727366656c642049\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Niederissigheim",
            "value": "\"ǂǂ4e696564657269737369676865696d\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Zeil am Main",
            "value": "\"ǂǂ5a65696c20616d204d61696e\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Pohlheim",
            "value": "\"ǂǂ506f686c6865696d\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Bad Königshofen II",
            "value": "\"ǂǂ426164204bc3b66e696773686f66656e204949\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Bad Neustadt I",
            "value": "\"ǂǂ426164204e657573746164742049\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Rodenbach",
            "value": "\"ǂǂ526f64656e62616368\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Rodheim",
            "value": "\"ǂǂ526f646865696d\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Bad Schwalbach",
            "value": "\"ǂǂ4261642053636877616c62616368\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Rödelheim",
            "value": "\"ǂǂ52c3b664656c6865696d\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Bad Vilbel",
            "value": "\"ǂǂ4261642056696c62656c\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Alsfeld II",
            "value": "\"ǂǂ416c7366656c64204949\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Schweinfurt",
            "value": "\"ǂǂ5363687765696e66757274\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Seligenstadt",
            "value": "\"ǂǂ53656c6967656e7374616474\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Stockstadt II",
            "value": "\"ǂǂ53746f636b7374616474204949\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Weiherweg",
            "value": "\"ǂǂ576569686572776567\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Wiesbaden",
            "value": "\"ǂǂ57696573626164656e\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Breitengüßbach",
            "value": "\"ǂǂ4272656974656e67c3bcc39f62616368\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Brendlorenzen",
            "value": "\"ǂǂ4272656e646c6f72656e7a656e\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Würzburg",
            "value": "\"ǂǂ57c3bc727a62757267\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Gießen II",
            "value": "\"ǂǂ476965c39f656e204949\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Dittelbrunn",
            "value": "\"ǂǂ44697474656c6272756e6e\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "XXFlörsheim a. Main",
            "value": "\"ǂǂ5858466cc3b672736865696d20612e204d61696e\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "XXGerolzhofen",
            "value": "\"ǂǂ58584765726f6c7a686f66656e\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "XXSchaafheim",
            "value": "\"ǂǂ58585363686161666865696d\"",
            "operator": 6
          },
          {
            "count": 2,
            "name": "Großkrotzenburg",
            "value": "\"ǂǂ47726fc39f6b726f747a656e62757267\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Alsfeld III",
            "value": "\"ǂǂ416c7366656c6420494949\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Altenstadt-Lindheim",
            "value": "\"ǂǂ416c74656e73746164742d4c696e646865696d\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Aschaffenburg-Strietwald",
            "value": "\"ǂǂ41736368616666656e627572672d53747269657477616c64\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Babenhausen",
            "value": "\"ǂǂ426162656e68617573656e\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Bad Brückenau",
            "value": "\"ǂǂ426164204272c3bc636b656e6175\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Bad Hersfeld III",
            "value": "\"ǂǂ426164204865727366656c6420494949\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Bad Kissingen - Garitz",
            "value": "\"ǂǂ426164204b697373696e67656e202d2047617269747a\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Bad Königshofen I",
            "value": "\"ǂǂ426164204bc3b66e696773686f66656e2049\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Bad Neustadt II",
            "value": "\"ǂǂ426164204e65757374616474204949\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Bad Orb",
            "value": "\"ǂǂ426164204f7262\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Bad Soden-Salmünster",
            "value": "\"ǂǂ42616420536f64656e2d53616c6dc3bc6e73746572\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Baunatal II",
            "value": "\"ǂǂ4261756e6174616c204949\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Bebra II",
            "value": "\"ǂǂ4265627261204949\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Bischofsheim Rüsselsheim",
            "value": "\"ǂǂ42697363686f66736865696d2052c3bc7373656c736865696d\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Bischofsheim/Rhön",
            "value": "\"ǂǂ42697363686f66736865696d2f5268c3b66e\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Bodenheim",
            "value": "\"ǂǂ426f64656e6865696d\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Bruchköbel",
            "value": "\"ǂǂ42727563686bc3b662656c\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Büdingen II",
            "value": "\"ǂǂ42c3bc64696e67656e204949\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Dr.-Raabe-Str.",
            "value": "\"ǂǂ44722e2d52616162652d5374722e\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Dörnigheim I",
            "value": "\"ǂǂ44c3b6726e69676865696d2049\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Dörnigheim II",
            "value": "\"ǂǂ44c3b6726e69676865696d204949\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Eichenzell",
            "value": "\"ǂǂ45696368656e7a656c6c\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Eisingen",
            "value": "\"ǂǂ456973696e67656e\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Erlensee",
            "value": "\"ǂǂ45726c656e736565\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Erlensee II",
            "value": "\"ǂǂ45726c656e736565204949\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Eschwege II",
            "value": "\"ǂǂ4573636877656765204949\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Flörsheim a. Main",
            "value": "\"ǂǂ466cc3b672736865696d20612e204d61696e\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Frankenberg",
            "value": "\"ǂǂ4672616e6b656e62657267\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Friedberg",
            "value": "\"ǂǂ467269656462657267\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Fulda, Frankfurter Str. 8",
            "value": "\"ǂǂ46756c64612c204672616e6b667572746572205374722e2038\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Fulda, Heidelsteinstr. 2a",
            "value": "\"ǂǂ46756c64612c2048656964656c737465696e7374722e203261\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Fulda, Leipziger Str.",
            "value": "\"ǂǂ46756c64612c204c6569707a69676572205374722e\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Gau-Odernheim",
            "value": "\"ǂǂ4761752d4f6465726e6865696d\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Geisa",
            "value": "\"ǂǂ4765697361\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Gelnhausen",
            "value": "\"ǂǂ47656c6e68617573656e\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Gelnhausen II",
            "value": "\"ǂǂ47656c6e68617573656e204949\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Gelnhausen-Haitz",
            "value": "\"ǂǂ47656c6e68617573656e2d486169747a\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Gerolzhofen II",
            "value": "\"ǂǂ4765726f6c7a686f66656e204949\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Gerolzhofen II - Stellplätze",
            "value": "\"ǂǂ4765726f6c7a686f66656e204949202d205374656c6c706cc3a4747a65\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Ginsheim Gustavsburg",
            "value": "\"ǂǂ47696e736865696d204775737461767362757267\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Gochsheim",
            "value": "\"ǂǂ476f6368736865696d\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Großauheim",
            "value": "\"ǂǂ47726fc39f61756865696d\"",
            "operator": 6
          },
          {
            "count": 1,
            "name": "Hofbieber",
            "value": "\"ǂǂ486f66626965626572\"",
            "operator": 6
          }
        ]
      }
    ],
    "queryModification": "ListID:D7A89C39-DFEA-4A12-94A6-13F1BE074E08   (contentclass:STS_ListItem)",
    "secondaryResults": []
  },
  "paging": {
    "currentPageNumber": 17

 or Input from Developer Tools in Browser?

**Comment by aThuemmel** [comment]
> Can you look at the JSON response of the query being issued and see if the data is being returned?

See my answer above

**Comment by aThuemmel** [comment]
im still waiting for an answer or something?!

**Comment by wobba** [comment]
I think it's the issue where max 100 values are retrieved for refiners. We have fixed this in v3, and will look to implement a setting in v4 where you can set the max number.

**Comment by wobba** [comment]
v4.1 will have a setting per refiner/filter to specify max numbers to get back.
