### ISSUE TITLE
Replace String and Query Rule Error

### ISSUE THREAD

**Issue by Mr-Clrscr** [microsoft-search/pnp-modern-search#675]
Hi,

this is more of questions/queries. 

1. i'm trying to use replace to remove or substitute the site url with blank space in parentlink such as 
{{#replace "https://company.sharepoint.com/sites/sitename"  " " }}{{ParentLink}}{{/replace}} but i'm having no luck.

eg: https://company.sharepoint.com/sites/sitename/library/hr  ==>   library/hr

2. i'm trying to add promoted result's by enabling query rules. it is throwing the following error 

"Error making HttpClient request in queryable [500] Internal Server Error ::> {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}"  -> this is working fine in normal search webpart

3. how can i display a library column( suppose department [single line]) in search result's template. i tried mapping to refinable string and tried something like {{department}} or {{RefinableStringXX}} but no use

suggestions or references will really help me out.

thanks.

**Comment by wobba** [comment]
1. See docs on replace at https://github.com/helpers/handlebars-helpers#replace
2. Hard to troubleshoot what happens without knowing what the request JSON looks like
3. A SP column yields a crawled property named ows_columnname, which has to be mapped to a managed property. After mapping, you need to re-index items for the value to be populated in search.

**Comment by Mr-Clrscr** [comment]
Hi @wobba ,
Thanks for reply.

for the replace i want to replace the value of a variable i.e parentlink something like 
{{replace {{ParentLink}} "https://company.sharepoint.com/sites/sitename/" "newstr"}}

i think it is not considering parentlink variable is there a way where i can use variable or escape that flowerbraces.

**Comment by Mr-Clrscr** [comment]
Thanks @wobba , it helped me, but i'm still facing the issue for query reply, i'll try to put request json

**Comment by wobba** [comment]
Which of the 3 questions are not resolved?

**Comment by Leighton365** [comment]
This has started happening today for a customer of ours.  It's been working fine for around a year, and nothing has been changed in the configuration.  I logged this as #1914 and attached the error log, however it's been closed.  Can you access the error log still?

**Comment by wobba** [comment]
Will close this as it's an old issue.
