### ISSUE TITLE
How to combine search results from multiple sources without affecting the MaxResultsPerPage

### ISSUE THREAD

**Issue by Naveen-Rangarajan** [microsoft-search/pnp-modern-search#676]
Hi , 

Is there a possibility to combine data from multiple sources without affecting the MaxResultsPerPage (or Pagination).

For example, I need to always show data from a particular list on top of search results for a specific vertical. Based on the Query Text, I was able to retrieve the data using REST call from the list, and once retrieved, I push (or rather unshift) data to original search results. Since I have specified  MaxResultsPerPage as 20 (from Property Pane), the total results from the list REST API Call+ MaxResultsPerPage is shown. 

In KQL, I tried to promote the results to top, but due to some reasons, it is not working. 

By using Display Template, the results are not shown in the first page, rather displayed elsewhere (say in 10th or 20th page).

Is there any option to show data from the list on first page ?

**Comment by wobba** [comment]
A solution is to use query rules and result blocks with a result source, where the result block is rendered on top of page 1.

**Comment by Naveen-Rangarajan** [comment]
Thank you for the reply. Will try the same.

Also, is there a possibility to combine data from multiple APIs, like, one from the Search API provided in this solution and other from an API say Yammer  - https://api.yammer.com/api/v1/search.json?search="queryText"? Again without affecting the pagination and MaxResultsPerPage

Any help is appreciated.

**Comment by wobba** [comment]
No, we only support one API call. For Graph we may extend to allow more sources, as one call can get multiple result sets.
