### ISSUE TITLE
Hide "Created By", "Modified By",  "Modified Date" and "Created Date" for "Sites" vertical (and just show for "Documents" vertical) ) 

### ISSUE THREAD

**Issue by hsamdani12** [microsoft-search/pnp-modern-search#677]
Currently in v3 version of PnP Search Filters/ Refiners, we are unable to hide refiners based on the vertical selected.
We want the ability to hide certain OOTB refiners fields like "Created By", "Modified By", "Created Date" and "Modified Date",
We have 3 Verticals - All, Sites and Documents. We don't want to show these in refiners when Site Vertical is selected.  

Is there a workaround to hide the refiners in PnP Refiner web part based on the vertical ?  Should we use DOM manipulation to hide using custom css ?

**Comment by wobba** [comment]
No easy way to do this in v3.

**Comment by hsamdani12** [comment]
Thanks. So is it possible to this v4 ?

**Comment by wobba** [comment]
@hsamdani12 sorry not in v4 either as filter config is not tied per vertical. You can propose this as a new feature.

In March Microsoft Search will ship the ability to add custom verticals and configure refiners per vertical - this should cover your All/Sites/Documents scenario.
