### ISSUE TITLE
JS in custom template not working

### ISSUE THREAD

**Issue by mongoux** [microsoft-search/pnp-modern-search#678]
Hi there,

I've added some JavaScript in in the custom template. but it does not appear to be working. 
 
 The HTML and CSS work just fine. 

I've also found that SCSS does not work when added to the template.

JS added:
`(function (){
		    var radios = document.getElementsByName('choice');
		    console.log(radios);
		    for(var i = 0; i < radios.length; i++){
		        radios[i].onclick = function(){
		            document.getElementById('choiceLabel').className = this.value;
		            document.getElementById('choiceLabel2').className = this.value;
		            document.getElementById('choiceLabel3').className = this.value;
		            document.getElementById('choiceLabel4').className = this.value;
		            document.getElementById('choiceLabel5').className = this.value;
		            document.getElementById('choiceLabel6').className = this.value;
		            document.getElementById('choiceLabel7').className = this.value;
		        }
		    }
		})();`

If it can't be done, can you please suggest another way to do it.

Thanks in Advance.
 
**Version used**
Ex: 3.16

**Comment by FranckyC** [comment]
Hi @mongoux , custom JS is not supported in templates for security reasons. See #659

**Comment by FranckyC** [comment]
@mongoux  you can do it using a custom web component and the extensibility library. See https://microsoft-search.github.io/pnp-modern-search/v3/search-extensibility-library/getting-started/
