### ISSUE TITLE
Limitation of 100 results in refiners appear again (handle in #445 and #487)

### ISSUE THREAD

**Issue by mloslier** [microsoft-search/pnp-modern-search#679]
I'm using v3.16 since 21/12/2020 and the maximum of 100 results in refiners was solved in [#447 ](url).
But from the beginning of this year, the limitation appear again (update from Microsoft side ?).

For testing, I have a list with 15000 items and a managed metadata field with lot of 'tags'.
I'm able to reproduce the issue on a customer tenant and a personal dev tenant created today.

When I do a search for 'test tube', I have results :
![image](https://user-images.githubusercontent.com/77447270/105055210-2006fd80-5a73-11eb-9f34-33e99a779b97.png)

But using the default query to display all results in search results web part, the value on 'test tube' is not available in refiners:
![image](https://user-images.githubusercontent.com/77447270/105055385-4b89e800-5a73-11eb-80db-c058e6644584.png)

Someone has notice the same issue ? 
Of course I stay available for testing purpose.

**Comment by wobba** [comment]
@mloslier what's the refiner name you use? We only fetch up to 5000 values for `RefinableStringXX` properties. We could probably add names of other oob refinable properties if useful.

We're not adding new UI functionality for v3 but could be an improvement option for v4. Also, fetching that many values has a latency impact on search.

**Comment by mloslier** [comment]
@wobba : I use RefinableString101. So if I understand, refiners are calculated only for 5000 first results ? All results above 5000 will be not affect refiners ?

**Comment by wobba** [comment]
Correct - even loading 5000 values for a refiner to a UX is not very efficient nor user friendly. I would consider other better user experiences if you have that many values.

**Comment by Autophanous** [comment]
@wobba : i'm sorry to be probably re-asking something that might already be answered somewhere, but I just hit this issue (i have a refiner that has more that 100 values and the filters webpart is only showing the first 100) and I'm struggling to understand the current state of it in the related issues I found ( #445 and #487 ).
I'm using [Modern Search - September 2020 (v3.15.3)](https://github.com/microsoft-search/pnp-modern-search/releases/tag/v3.15.3).

**Comment by wobba** [comment]
Which managed properties are you using?

**Comment by Autophanous** [comment]
> Which managed properties are you using?

I'm using various refinable strings (RefinableString00 to 05) mapped to managed metadata site columns that I'm using on a document library.

**Comment by Autophanous** [comment]
I saw you referring above:
> We only fetch up to 5000 values for `RefinableStringXX` properties.
Does that mean that a refiner in the Filters webpart lists up to 5000 values that it gets from the search results?
Or am I misunderstanding ?

**Comment by wobba** [comment]
RefinableXXYY props should return up to 5000 values/buckets, fixed in v3.15.3. I haven't checked the v4 code yet for this.

**Comment by evlo** [comment]
Hi, 

I'm working on the solution with @Autophanous .
We have tried https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.0.0 and results are bit different:

Both version search result webparts return same 35004 items for the query.

I'm unsure about what you mean by buckets, but
- **V3** (3.15.3) filter for manage metadata field refiner offers user choice of **100** items exactly, when doing sum of number in the brackets I count  **455**
- **V4** filter on the same manage metadata field refiner offers user choice of **200*** items exactly, when doing sum of number in the brackets I count  **32350**

Correct number of offered choices for 35004 in this particular search query and that manage metadata refiner field in the filter should be **987**

Interestingly choices filter offers are different between V3 and V4
Altrought when both V3 and V4 shows same item in the filter options it does display same count in the brackets.

I'm attaching screenshot (some items are removed as it might be confidential data)


![image](https://user-images.githubusercontent.com/8813196/110124096-fb1bdf00-7dc1-11eb-9502-593708bc3fb7.png)

**Comment by wobba** [comment]
@evlo Please give me the name of the managed property you want more than 100 items for? If you use `RefinableString02` it should return more with 3.15.3 or newer. If you use the alias, then there's a limit. Returning a lot of items will have a negative impact on search speed, which is why there is a limit.

A bucket is a value returned. As numeric and date refiners support ranges, we call them "buckets" technically :) For string ones, each value would be one bucket.

**Comment by Autophanous** [comment]
Hi @wobba,

Yeah, after a bit of analysis on the traffic generated by the search web parts I see that the request to /_api/search/postquery is beings issued with:

-  (in v3.15.3): //request/Refiners: "RefinableString01(sort=name/ascending),RefinableString02" in the request payload Body.
-    I get a response structure in //PrimaryQueryResult/RefinementResults/Refiners that has max 100 items and they are sorted accordingly.
-  (in v4): //request/Refiners: "RefinableString01,RefinableString02" in the request payload Body.
- -    I get a response structure in //PrimaryQueryResult/RefinementResults/Refiners that has max 100 items and they are not sorted accordingly.

So I believe in v4 there is an additional issue regarding sorting (the refiner is not following the corresponding sorting config) which was not there in v3.15.3.

Regarding the main point of the limitation of 100 results for each refiner, I believe this is the default max value defined in the API that can be overridden by specifying the filter param in //request/Refiners: "RefinableString01(sort=name/ascending,**filter=1000/0/***),RefinableString02" in the request payload Body.

That way I'm getting a max of 1000 results for each refiner.

Does this makes sense to you?
Would you see the max number of items for each Refiner as a possible config param on the Refiner's config ?
Let me know if I'm missing something or making incorrect assumptions on this.

Thanks once more for your help.

**Comment by wobba** [comment]
From v3.15.3 RefinableString queries should look like:

![image](https://user-images.githubusercontent.com/51104/110147149-9bcac880-7ddb-11eb-9a09-25304c6e3e12.png)

Feel free to use v3.17 for testing as well.

**Comment by Autophanous** [comment]
> From v3.15.3 RefinableString queries should look like:
> 
> ![image](https://user-images.githubusercontent.com/51104/110147149-9bcac880-7ddb-11eb-9a09-25304c6e3e12.png)
> 
> Feel free to use v3.17 for testing as well.

Hmmm ... that's weird then ... in our tests it's not.
I'm wondering what we might be doing wrong ...

**Comment by wobba** [comment]
Upgrade and re-test 🙂

**Comment by wobba** [comment]
I'll close this issue for now, and if number of values coming back on 3.17 is weird the reopen a new bug. If count specified is 50000 in the json and you get 100, then it's an API issue and not web part issue.

**Comment by Autophanous** [comment]
Hi @wobba ,

Just to give you a final feedback on this, you were right, v3.15.3 shows all available refiner values (or buckets) when using RefinableStringXX and not an alias (we were testing incorrectly).
This was introduced https://github.com/microsoft-search/pnp-modern-search/commit/474845f85be6655d407590ea2a27875a5d5ec37f

Regarding v4, I tried to check if this was migrated to the new code base, and as far as I could see it does not seem so.
I believe that the logic to build the Refiners query migrated from https://github.com/microsoft-search/pnp-modern-search/blame/version-3/search-parts/src/services/SearchService/SearchService.ts#L255 to https://github.com/microsoft-search/pnp-modern-search/blame/main/search-parts/src/dataSources/SharePointSearchDataSource.ts#L760 but the logic to add the sort direction and filter=50000/0/* for refinable strings seems not to be there.
And this seems aligned with our tests.

Just wanted to give you that feedback.

Thanks once more for your help.

**Comment by wobba** [comment]
For v4 I think we might try to have some UI for refinerspec.
