### ISSUE TITLE
Searching on some keywords gives "Error making client request " error

### ISSUE THREAD

**Issue by rohit18121812** [microsoft-search/pnp-modern-search#680]
**Version used**
3.16.0.0

**Describe the bug**
Searching for certain keywords like "Standards" gives "Error making client request " error . It happens with just few keywords. 

**To Reproduce**
Enter keyword "Standards" and throws error.

**Expected behavior**

**Screenshots**
see attached

**Desktop (please complete the following information):**
 - Browser : Chrome , Edge
 -
![errorSP Search](https://user-images.githubusercontent.com/67439350/105083613-0604f500-5a4a-11eb-989d-e3a275a4127a.jpg)

**Additional context**

**Comment by wobba** [comment]
Without knowing what setup you have all up, and looking at what the JSON request and response looks like it's impossible to figure out why the backend gave you the error. Do you get the same error if you on the site you are searching from navigate to:

`https://tenant.sharepoint.com/sites/somesite/_layouts/15/osssearchresults.aspx` which is the classic site search page.

**Comment by wobba** [comment]
v3 no longer maintained
