### ISSUE TITLE
Manifest not found for component id

### ISSUE THREAD

**Issue by edwincsabo** [microsoft-search/pnp-modern-search#681]
Hello, I have a problem when I try to add any webpart and it shows me the following message

![image](https://user-images.githubusercontent.com/56757686/105147025-98e77300-5ace-11eb-8238-d65881933159.png)

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Manifest not found for component id "96dcffa8-2c69-47ec-ba5c-770213aeb4fe" and version "1.0.0".

INNERERROR:
Manifest not found for component id "96dcffa8-2c69-47ec-ba5c-770213aeb4fe" and version "1.0.0".
CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c874943af8330f8f53cf153ee1fb4889.js:1:864164)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c874943af8330f8f53cf153ee1fb4889.js:1:1009396)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c874943af8330f8f53cf153ee1fb4889.js:1:1049750)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c874943af8330f8f53cf153ee1fb4889.js:1:1045795)
    at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_c874943af8330f8f53cf153ee1fb4889.js:1:1038062

**Comment by eyuberol** [comment]
Hello, I have the same problem and also when installing the extension application it gives the following error:

![image](https://user-images.githubusercontent.com/9775280/105154774-2a280b00-5b0a-11eb-83bd-a16e62e6f760.png)

Deployment failed in host web https://*.sharepoint.com for app PnP Modern Search - Search Extensibility Library Core/f13a5866-004f-4219-b078-69731f848bd1. Microsoft.SharePoint.SPException: Feature definition with Id 96dcffa8-2c69-47ec-ba5c-770213aeb4fe failed validation, file '/96dcffa8-2c69-47ec-ba5c-770213aeb4fe/Library_96dcffa8-2c69-47ec-ba5c-770213aeb4fe.xml', line 1, character 1383: The 'Type' attribute is invalid - The value 'Library' is invalid according to its datatype 'http://schemas.microsoft.com/sharepoint/:ClientComponentType' - The Enumeration constraint failed. at Microsoft.SharePoint.Administration.SPSolutionPackage.FeatureXmlValidationCallback.XmlValidationCallBack(Object sender, ValidationEventArgs evtargs) at System.Xml.Schema.XmlSchemaValidator.CheckAttributeValue(Object value, SchemaAttDef attdef) at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String lName, String ns, XmlValueGetter attributeValueGetter, String attributeStringValue, XmlSchemaInfo schemaInfo) at System.Xml.XsdValidatingReader.ValidateAttributes() at System.Xml.XsdValidatingReader.ProcessElementEvent() at System.Xml.XsdValidatingReader.Read() at Microsoft.SharePoint.Utilities.SPUtility.XsdValidateXml(XmlTextReader xmlStreamReader, String friendlyName, String pathXsdFile, String tagExpectedRootNode, Int32 desiredPathVersion, ValidationEventHandler xsdValEventHandler) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ValidateAppPartFeatureXsd(PackagePart appPart, Guid featureGuid) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractElementPartToWsp(PackagePart elementPart, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId, SPAppInstance appInstance, Guid featureId, String featureWspRelativeDirectory) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractFeaturePartToWsp(SPFeatureAppPart featureAppPart, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId, SPAppInstance appInstance) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractFeaturePartsToWsp(List`1 featureAppParts, SPWeb web, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.GenerateAndActivateUserSolutionFromPackage(SPWeb web, SPAppPackage appPackage, Guid productId, String solutionName, SPSolutionLevel solutionLevel) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.InstallOrUpgrade(SPSite site, Nullable`1& solutionId, Boolean& swapNeeded)

**Comment by MSchmittnaegel** [comment]
I had the same deployment issue with the Extensibility Library as described by @eyuberol. After deleting the extensiblity app package from of the app catalog and deploying it again with the "Make this solution available to all sites in the organization" checkbox set, it worked for me.

**Comment by jorisbaiutti** [comment]
I have the same Issue with Site Collection app catalog

**Comment by motly-ca** [comment]
Also have same issue with Site Collection app catalog.

**Comment by edwincsabo** [comment]
> Tuve el mismo problema de implementación con la biblioteca de extensibilidad que se describe en @eyuberol. Después de eliminar el paquete de la aplicación de extensiblidad del catálogo de aplicaciones e implementarlo de nuevo con el conjunto de casillas de verificación "Hacer que esta solución esté disponible para todos los sitios de la organización", funcionó para mí.

I did what @MSchmittnaegel proposed and it worked perfectly, thanks for the help.

**Comment by colonelclaypoo** [comment]
I can also confirm that @eyuberol's workaround fixed it for us. Thx.

**Comment by jorisbaiutti** [comment]
Sadly for us, the workaround is not an option, because we are not allowed by company policy to deploy it on all sites.

**Comment by wobba** [comment]
@jorisbaiutti it's a limitation of SPFx.

**Comment by michikammerer** [comment]
Have the same issue

**Comment by FranckyC** [comment]
Refer to for more explanation https://github.com/microsoft-search/pnp-modern-search/issues/686#issuecomment-765444117

**Comment by jorisbaiutti** [comment]
@wobba Yes you're right. And it works :) thanks for the help
