### ISSUE TITLE
Search verticals not searching in the result source

### ISSUE THREAD

**Issue by dconcor** [microsoft-search/pnp-modern-search#683]
Hi all,
In a Communcation site configured as a Hub site we have a dedicated page for to search using the pnp modern search. The problem is when we change the resource source in the verticals and we always receive the same results no matter how we configure them.
Do you have any tip or suggestion to fix this?

**Comment by wobba** [comment]
My best tip is to fill in the issue/bug template with all information it asks. It has a nice section titled "Reproduction steps" which is needed.

You can either edit your question to include the template, or close this one and log a new issue.
