### ISSUE TITLE
PnP modern search (v3): people results duplicates

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#684]
**Version used**
3.14.2

**Describe the bug**
I'm getting 4 results for each person using this query:
{searchTerms} ContentClass=urn:content-class:SPSPeople
The query builder tool only gets one result. We have 4 geolocations set up so I'm guessing that's the issue. Is there a way to filter down to one geolocation in the query by adding a "Path" or some other filter? Each geolocation instance has a separate subdomain in theory, so this should be possible. Alternatively, is there a way to limit the results to the first one only and eliminate duplicates?

**To Reproduce**
1. Add search box and connected results web parts to page
2. Add people query as "{searchTerms} ContentClass=urn:content-class:SPSPeople"

**Expected behavior**
Same as query builder tool  - one result per person

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
Note that this ONLY seems to affect people results, and not document or other content search queries.

**Comment by wobba** [comment]
This is an API related issue to geo location. Adding a path filter does work as a work around though as it contains the GEO.

`path:https://tenant-my.sharepoint.com`

**Comment by webbrewer** [comment]
@wobba  Yes, this works. Thanks!
