### ISSUE TITLE
Refiner not showing all values when used on vertical targeted to People

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#687]
**Is your feature request related to a problem? Please describe.**
Job Title Refiner only shows 99 items, with no scroll option or way to access the rest. This is making it so the Job Title list only shows items that start with a - c. If I enable "show filter for refinement value", I can still only search these first 99 Job Titles.

**Describe the solution you'd like**
On other verticals, all results come back, which gives a very long list, but it's workable by enabling "show filter for refinement value". Is there a way to get the People vertical to behave in the same manner? I'm trying to figure out if this s this a refiner issue, or a Microsoft results source issue.

**Describe alternatives you've considered**
Enabled "show filter for refinement value", so I can enter a Job Title not shown by name, this does not work. No results beyond the 99 provided are searched.

**Additional context**

Bottom of the Job Title refiner list:
![image](https://user-images.githubusercontent.com/2616432/105380234-7fbfee80-5bc2-11eb-845c-a7d4dae3e94b.png)

**Comment by wobba** [comment]
I'll add more oob properties to allow more than 100 values for the next bug release, and include JobTitle. Default 100 buckets are returned, but we have a list of properties to allow up to 5000 values.

**Comment by bryllyg** [comment]
Excellent! Thank you!

**Comment by bryllyg** [comment]
Quick follow up question, will this be added to next 3.x bug release? Wasn't sure if you meant that or 4. (Hoping for 3.x, as that's what we are using in prod)

**Comment by wobba** [comment]
I'll add it to v3.18, and if you have a list of fields you want added feel free to share.

**Comment by bryllyg** [comment]
Wonderful! Job Title, Department, and Tags are the fields I'm looking for. Those lists are gnarly

**Comment by meklulose** [comment]
@wobba Hi there! sorry to butt in on this issue but I has question regarding this. I noticed that File Type refiner is only bringing back 100 results. Is this behavior expected or should this bring back more results? We have lots of different type of files and notice that some file type were not showing up in the refiner.

**Comment by wobba** [comment]
@meklulose Adding `FileType` to the next release. In v4 you can specify the max number yourself.

**Comment by Jasonvan39** [comment]
I recently worked with a Microsoft rep on an issue similar but my refiner shows 100 of about 145 and orders them by number of items that the refiner has, so for instance i have refiners 
345 - A (20)
346 - A (17)
348 - A (13)

And so on it skips 347 - A (2) because it only has 2 items which is less than the other 100 refiners so my scenario for sure fits this bug but doesnt work the same way you described above.

**Comment by wobba** [comment]
@Jasonvan39 Don't log issues on other closed issues, especially if the bug is not the same and the solution does not apply to you.
