### ISSUE TITLE
Card layout display issue

### ISSUE THREAD

**Issue by coupalm** [microsoft-search/pnp-modern-search#689]
**Version used**
4.0.0

**Describe the bug**
Cards Layout display document preview only on odd card sequence (prewiew ok in document 1, 3, 5 etc.). Also do not display the Author picture.

**To Reproduce**
1) Add PnP Results web part and set a static query like FileExtension=pdf
2) Use the Card Display Layout

**Expected behavior**
An image preview in the card should always be displayed for supported document type. Also author picture should display.

**Screenshots**
Screen shots provided
![PnPSearch-01](https://user-images.githubusercontent.com/11309224/105410379-dac40680-5bff-11eb-9cd9-27625945399a.png)
![PnPSearch-02](https://user-images.githubusercontent.com/11309224/105410381-dac40680-5bff-11eb-931f-e018fa34264e.png)

**Desktop (please complete the following information):**
 - Browser Edge Chromium

**Additional context**
None.

**Comment by FranckyC** [comment]
Nice catch @coupalm. A very weird issue but should be fixed in the develop branch by now. Thanks.
