### ISSUE TITLE
Changes to Result Types are not saving

### ISSUE THREAD

**Issue by shuenSL** [microsoft-search/pnp-modern-search#690]
Not sure if I am doing it wrong. In the Search Results web part (V4), I click on Edit Result Types in page 2, select a data source field and operator, and enter a condition value. At this point it does not matter whether I modify the inline template or not. When I click Save and then click to edit the Result Types again, nothing I enter is there. Any ideas?

**Comment by wobba** [comment]
Closed as issue is not following bug template guidelines.
