### ISSUE TITLE
v4.0 Intallation Documentation is missing permission

### ISSUE THREAD

**Issue by quarterhorse** [microsoft-search/pnp-modern-search#692]
### Issues related to data mapping, e.g. SharePoint columns to crawled properties to managed properties, will be closed by default and should be asked elsewhere as it's outside the scope of this project. However if you cannot repro the issue with classic web parts, then it's ok as it relates to these web parts 🙂

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
v4.0

**Describe the bug**
The installation documentation for v4.0's Requested API permission table is missing the Files.Read.All permission.

It might also be nice to refer to the Consume MSFT Graph tutorial at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#deploy-the-solution-and-grant-permissions

**To Reproduce**
N/A

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by wobba** [comment]
Should be updated.
