### ISSUE TITLE
v3 results web part empty properties panel

### ISSUE THREAD

**Issue by webbrewer** [microsoft-search/pnp-modern-search#694]
**Version used**
Ex: 3.14.2

**Describe the bug**
Curious why **sometimes** the search results web part properties pane is empty. (see attached image)

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/51796756/105506503-20cca900-5c98-11eb-8ee2-e4ec0af68792.png)

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
Was working in this site yesterday, nothing changed on my end. Not an issue on other sites with exact same set up. Have seen this  issue pop up before.

**Comment by wobba** [comment]
Can you repro on v3.17 as well? We load the code async for the panel which could be the reason. Do you see any errors in the console or in network tab when this occurs?

**Comment by webbrewer** [comment]
@wobba  I looked today and it's working fine with v3.14, so not sure what's going on. Pretty sure it's not related to the search app as I've noticed it before on other web parts.
