### ISSUE TITLE
Can't get itemID from slots

### ISSUE THREAD

**Issue by heatherzhang080** [microsoft-search/pnp-modern-search#696]
I tried to customise the search results template where an item ID will be needed. In Search Schema managed properties, I found ows_ID is mapped to itemID, so I added it to the Search Results web part slots and used in template `{{slot item @root.slots.itemID}}` but it's not showing item ID as expexted. I reindexed the list and waited for a few days already.

**Comment by FranckyC** [comment]
Hi @heatherzhang080, you must use the slot name instead of the filed name. The default slot name is "ItemId" and it is case sensitive. Thanks.

**Comment by heatherzhang080** [comment]
Hi @FranckyC, I'm aware of that slot item, but it simply is not what I want. If you try to output this "ItemID" slot it is not the item ID you see in the list or library. That's why I was adding my own slot.

**Comment by wobba** [comment]
@heatherzhang080 You can use the debug template to examine what data you are getting back. I believe you might be looking for `ListItemID`.

**Comment by heatherzhang080** [comment]
@wobba Thank you. I just took a look at the debug template and it seems it's not returning the ID attribute for any list item or document. I was thinking if we added the attribute to the slots it will get this attribute, but according to what you said, we can only get the attributed returned in the debug template?

**Comment by wobba** [comment]
1. Add `ListItemID` to the properties you want to fetch (it's not included by default). Clear the field and click ENTER and it will be added.
   
![image](https://user-images.githubusercontent.com/51104/106140232-c9827900-616e-11eb-80fb-bd2b3a26b2fd.png)

2. Ensure it's checked when you click the expand list of properties
![image](https://user-images.githubusercontent.com/51104/106140512-2a11b600-616f-11eb-9356-8cd1a10ac4f4.png)

3. Add a new slot mapping to use to access it via slots - or access directly via `item.ListItemID`
![image](https://user-images.githubusercontent.com/51104/106140333-eb7bfb80-616e-11eb-849e-373a185ba376.png)

This will allow you to
