### ISSUE TITLE
"Did You Mean" and SpellingSuggestions - for Search Results

### ISSUE THREAD

**Issue by kachihro** [microsoft-search/pnp-modern-search#697]
**Version used**
v. 4.0.0

**Describe the bug**
Within the results display, there is a {{spellingSuggestion}} tags, mentioned in the documentation - but it never has any results returned.   Users have asked about the old "Did You Mean ?" functionality.

This is working within the main (suite bar) search - but not in the custom SPFX modern search.

**To Reproduce**
* Enter a deliberate mis-spelt word - eg. documnet - or polciy
* This does an exact search match - and no results found

Have included the tag for {{ spelling Suggestion }} - but nothing is shown.

**Expected behavior**
Ability to include a 'did you mean' - or similar function

**Screenshots**
NOTE - within the MAIN search area - this is showing correctly ;
![image](https://user-images.githubusercontent.com/16025947/105665435-2db4fb00-5f2b-11eb-8f85-be5749230d47.png)

**Comment by wobba** [comment]
Look at the output in the debug template. I added a static query of "vacaation" to the web part.

![image](https://user-images.githubusercontent.com/51104/105898009-37b52780-6019-11eb-9595-65441ee68b32.png)

And the API used by Microsoft Search is not publicly available.

**Comment by kachihro** [comment]
OK - so I'd need to format that inside a custom template ?   

I guess I could add an A-HREF to "did you mean {{spellingSuggestion}}".
And link to the same page - but replace the K=, with the suggestion.

If anyone else has done that before - or similar - please let me know...

**Comment by emilyLin** [comment]
> OK - so I'd need to format that inside a custom template ?
> 
> I guess I could add an A-HREF to "did you mean {{spellingSuggestion}}". And link to the same page - but replace the K=, with the suggestion.
> 
> If anyone else has done that before - or similar - please let me know...

I would like to know if you have found the solution??????

**Comment by kachihro** [comment]
Yes - I just added a link within the 'template' - via the CUSTOM editor ;

{{#if spellingSuggestion}}
            <p>Did you mean <a href="?k={{spellingSuggestion}}">{{spellingSuggestion}}</a>?</p>
        {{/if}}

![image](https://user-images.githubusercontent.com/16025947/181134781-98bc3f99-7fe5-47d7-b96b-5391f286af22.png)
