### ISSUE TITLE
v4 Panel layout option in Filters web part appears blank 

### ISSUE THREAD

**Issue by aaronrwilson** [microsoft-search/pnp-modern-search#698]
**Version used**
v4.0.0.0

**Describe the bug**
The Panel option in Filters web part appears blank when using.  The other layout options work fine.

**To Reproduce**
1. Go to PnP - Search Filters web part in edit mode, screen 2
2. Click on Panel layout
3. Save page and perform search
4. Click to open Filters
5. See blank panel

**Expected behavior**
See the same filters as the other layouts show.  The first screenshot below shows the filters in Vertical layout.  The second screenshot shows the blank panel layout.  No other settings were changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/40477360/105667230-bd0cd080-5e8f-11eb-9824-2e1fdfe39275.png)
![image](https://user-images.githubusercontent.com/40477360/105667239-c0a05780-5e8f-11eb-8fda-ab01c6c3027c.png)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Additional context**
n/a

**Comment by FranckyC** [comment]
Hi @aaronrwilson, resolved in the develop branch and will be available in the next release. You can use the develop branch if you don't want to wait. Thanks!
