### ISSUE TITLE
Search Results v4 - Grouping - Show collapsed - Does not save status when switched off. Always reverts to On.

### ISSUE THREAD

**Issue by sfarq** [microsoft-search/pnp-modern-search#699]
### Check existing issues before logging new ones
No Issues logged re v4 results grouping.

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
v4

**Describe the bug**
A clear and concise description of what the bug is. Keep questions and bugs related to the web parts. If the issue relates to KQL or question around crawled and managed properties please use [Microsoft TechCommunity](https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev). Which means, if you experience the same behavior in classic web parts, then it's not an issue with PnP Modern Search 😉

Search results v4 - Configured to show documents correctly. However, Grouping feature is always shown in a Collapsed state on page save / page published / page refresh, after setting Show Collapsed to False (Off).

**To Reproduce**
1. Go to Page 2 of Search results settings. 
2. Click on Grouping Feature, select appropriate Field. 
3. Switch Off - Show Collapsed.
4. wait for Part to save / Save Draft / Republished Page.
5. View of Group is always collapsed.
6. Re open Search Results properties settings, go to page to - Show Collapsed is switch on. I.e. page is not saving state.

**Expected behavior**
I expect that when you set Show Collapsed to off - it stays off after you save the page.

**Screenshots**
Can be provided if required

**Desktop (please complete the following information):**
 - FireFox - Current version.

**Additional context**

**Comment by FranckyC** [comment]
Hi @sfarq , good catch, there was a typo in the property name. Resolved in the develop branch and available next release. Thanks!
