### ISSUE TITLE
Search refiners web part: open filter options by default

### ISSUE THREAD

**Issue by webbrewers1** [microsoft-search/pnp-modern-search#70]
**Describe the solution you'd like**
Search refiners web part: is it possible in the vertical presentation to have the filter nodes open up by default when a search is entered (similar to the way the panel option works)? Requiring the filter group category to be clicked to open it may confuse users.

**Comment by webbrewer** [comment]
Update: this is actually working as desired on one page but with the exact same configuration, not on another.....I can't figure out what the difference between the two is.

**Comment by webbrewer** [comment]
Never mind - I missed the "expand filter by default option on the new page. DOH! We can close this out.

**Comment by FranckyC** [comment]
@webbrewer Np I was about to reply about the existing option ;). Hope you like the solution!
