### ISSUE TITLE
Multi-Select Search Filter - "Clear" greyed out unless a checkbox is checked

### ISSUE THREAD

**Issue by Lopamudra-Das** [microsoft-search/pnp-modern-search#704]
**Version used**
3.14.1.10

**Describe the bug**
Once we apply a "multi-select" filter, we cannot clear the filter until we check at least one option. This is non-intuitive and very confusing for end users.

**To Reproduce**
1. Install a search results and associated search filter web part on a page.
2. Change at least one search refiner to be use "multi-value refinement item" refiner template.
3. Save page and look at the search results and associated search filter.
4. Select one or more filter values in the multi-value search refiner and click "Apply". The search results will get filtered per selection.
5. Now try clicking the "clear" button to reset search filters. Both "Apply" and "Clear" are greyed out at this point. Users can reset filter only by selecting one of the search values available, which then enables the "Clear" button.

**Expected behavior**
Users should be able to click in "clear" under a multi-value search filter without having to select a checkbox first.

**Screenshots**
![image](https://user-images.githubusercontent.com/16367223/105737448-f4b56000-5f03-11eb-8da5-fa9f97a97369.png)

**Desktop (please complete the following information):**
 - Browser, Chrome and Edge

**Additional context**

**Comment by wobba** [comment]
This is fixed in later releases.
