### ISSUE TITLE
Search Box settings -Configure available providers 

### ISSUE THREAD

**Issue by kasperbolarsen** [microsoft-search/pnp-modern-search#705]
**Version used**
4.0.0

**Describe the bug**
I have uploaded a file containing a number of Search Suggestion phrases, and it works as expected on the /Search site collection and in version 3.16
However in 4.0.0 it seems like the option to enable the suggestion provider does not work
**To Reproduce**
1. Enter the settings for the Search Box
2. Go to page two
3. Click on "Enable query suggestions"
4. Click on "Configure available providers"
5. Enable "SharePoint Static search suggestions"
6. Click on Save
7. Publish the page
8. Edit the page again and go to the "Configure available provideres"
9. Note that the option is disabled again 

**Expected behavior**
That the setting remains active ;-)

 - Browser: Edge Chromium

**Comment by FranckyC** [comment]
Hi @kasperbolarsen , good catch, there was an issue with the custom suggestion providers initialisation. Should be fixed in the develop branch. Thanks!
