### ISSUE TITLE
When selecting Sites or List Items error "The List is read only"

### ISSUE THREAD

**Issue by floh0310** [microsoft-search/pnp-modern-search#706]
**Version used**
4.0.0

**Describe the bug**
In the section Entity types is Sites selected (or List Items or Messages or Events) and the webpart displays "The List if read only".

**To Reproduce**
add the webpart to any SharePoint page. Edit the webpart properties. In section "Entity types" select "Sites".

**Expected behavior**
Expected the webpart to show results with SharePoint Pages found on the web site.

**Screenshots**
![image](https://user-images.githubusercontent.com/78021557/105835942-d23b4980-5fcc-11eb-8978-db667ae51620.png)

**Desktop (please complete the following information):**
 - Chrome (87.0.4280.141) on Windows 10 (1909)

**Comment by wobba** [comment]
Have you approved/allowed the needed scopes at https://tenant-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement ?

**Comment by floh0310** [comment]
> Have you approved/allowed the needed scopes at https://tenant-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement ?

thank you for your interest!
yes, the permissions are approved
![image](https://user-images.githubusercontent.com/78021557/106247449-d6a37480-620f-11eb-8453-67c10b23db58.png)
any other idea?

**Comment by wobba** [comment]
Yes :) We didn't include enough scopes in the release, but have added them in the dev branch. Sites.Read.All for example.

**Comment by floh0310** [comment]
> Yes :) We didn't include enough scopes in the release, but have added them in the dev branch. See https://github.com/microsoft-search/pnp-modern-search/blob/develop/search-parts/config/package-solution.json#L30-L44 for the missing ones. You can use for example the O365 CLI or similar to add them.

oh, okay. i hope you have a new release shortly. i think for many situations these scopes are needed.
thank you for your investigation and your suggestions for a workaround.
Unfortunatly, at the moment i am not that deep in the topic of packaging or O365 CLI.
So i use the last v3 release. this works for my situation (creating a searchable news archiv).
