### ISSUE TITLE
App Install Error: PnP Modern Search - Search Extensibility Library Core - Search

### ISSUE THREAD

**Issue by brianpmccullough** [microsoft-search/pnp-modern-search#707]
**Version used**
4.0,0.0

**Describe the bug**
When installing/deploying the "PnP Modern Search - Search Extensibility Library Core - Search" app, I get the following App Install error:
There were problems with the app web definition in the package.
Details: Deployment failed in host web https://[tenant].sharepoint.com/sites/Search for app PnP Modern Search - Search Extensibility Library Core/f13a5866-004f-4219-b078-69731f848bd1. Microsoft.SharePoint.SPException: Feature definition with Id 96dcffa8-2c69-47ec-ba5c-770213aeb4fe failed validation, file '/96dcffa8-2c69-47ec-ba5c-770213aeb4fe/Library_96dcffa8-2c69-47ec-ba5c-770213aeb4fe.xml', line 1, character 1383: **The 'Type' attribute is invalid - The value 'Library' is invalid according to its datatype 'http://schemas.microsoft.com/sharepoint/:ClientComponentType' - The Enumeration constraint failed.** at Microsoft.SharePoint.Administration.SPSolutionPackage.FeatureXmlValidationCallback.XmlValidationCallBack(Object sender, ValidationEventArgs evtargs) at System.Xml.Schema.XmlSchemaValidator.CheckAttributeValue(Object value, SchemaAttDef attdef) at System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String lName, String ns, XmlValueGetter attributeValueGetter, String attributeStringValue, XmlSchemaInfo schemaInfo) at System.Xml.XsdValidatingReader.ValidateAttributes() at System.Xml.XsdValidatingReader.ProcessElementEvent() at System.Xml.XsdValidatingReader.Read() at Microsoft.SharePoint.Utilities.SPUtility.XsdValidateXml(XmlTextReader xmlStreamReader, String friendlyName, String pathXsdFile, String tagExpectedRootNode, Int32 desiredPathVersion, ValidationEventHandler xsdValEventHandler) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ValidateAppPartFeatureXsd(PackagePart appPart, Guid featureGuid) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractElementPartToWsp(PackagePart elementPart, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId, SPAppInstance appInstance, Guid featureId, String featureWspRelativeDirectory) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractFeaturePartToWsp(SPFeatureAppPart featureAppPart, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId, SPAppInstance appInstance) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.ExtractFeaturePartsToWsp(List`1 featureAppParts, SPWeb web, TemporaryDirectory wspTempDir, SHA256Managed sha, Guid productId) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.GenerateAndActivateUserSolutionFromPackage(SPWeb web, SPAppPackage appPackage, Guid productId, String solutionName, SPSolutionLevel solutionLevel) at Microsoft.SharePoint.Packaging.SPTargetWebDeploymentGroup.InstallOrUpgrade(SPSite site, Nullable`1& solutionId, Boolean& swapNeeded)

**To Reproduce**
1. Install to Tenant App Catalog
2. Create site collection using Blank Communications Site.
3. Navigate to site collection as site collection administrator.
4. Site Contents > Add An App > "PnP Modern Search - Search Web Parts - v4" (installs successfully)
5. Site Contents > Add An App > "PnP Modern Search - Search Extensibility Library" (fails)

**Expected behavior**
PnP Modern Search - Search Extensibility Library installs successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/8305245/105848184-a0b28600-5fac-11eb-98eb-17f578f32c11.png)

**Desktop (please complete the following information):**
Edge Chromium

**Additional context**
N/A

**Comment by brianpmccullough** [comment]
Confirmed on a second tenant in first release ring.

**Comment by steventys** [comment]
I encountered the same as described above when trying to install the app. Install worked with no issues about 2 weeks ago when I was testing it on another site collection.

**Comment by wobba** [comment]
I'm updating the docs as part of #710 to explain how the two packages should be installed.
