### ISSUE TITLE
V3 - Pagination clicks scrolling top of container to middle of viewport, not top

### ISSUE THREAD

**Issue by jimmywim** [microsoft-search/pnp-modern-search#708]
On 3.17.0

Set up any query (I test with "*"), use the "Simple List" layout (also happens on any custom layout).

Get enough results for pagination to show with multiple pages.

Position the web part such that you need to scroll down the page to get to pagination & the top of the results is off the top of the viewport.

Hit any of the numbers, notice the view scrolls to show the top of the results in the middle of the viewport.

This can look confusing to a user, as the page appears to have jumped arbitrarily.

I believe this is the line that causes the jump in the page:

https://github.com/microsoft-search/pnp-modern-search/blob/4f98214e02b44c5c3cb241c9e99d04ba2937e260/search-parts/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx#L320

Ideally I wonder if the top of the container should be set to the top of the viewport, so it's clearer to the user that you're now viewing a new page of results, and it starts from the top of where you're looking.

**Comment by jimmywim** [comment]
Experimenting with `scrollIntoView(true);` instead of the code in the OP, which seems to behave nicer. Any opinions?

**Comment by jimmywim** [comment]
PR contains defensive code, so this behaviour (scrolling to top, only if needed) occurs if available, otherwise it falls back to the original `focus();` call (for Firefox primarily).

**Comment by wobba** [comment]
`scrollIntoView` has good browser support https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView and you could try something like this which should work for most browsers - and fallback is ok.

```
element.scrollIntoView({behavior: "smooth"});
```

**Comment by jimmywim** [comment]
@wobba Yep - the problem with `scrollIntoView` is that it will **always** scroll the element to the top of the viewport - even if the webpart (contents & pagination) is entirely within the viewport. 

`scrollIntoViewIfNeeded` is perfect because it won't scroll the page if the element is entirely in the viewport.

I guess it depends what is the more expected scenario - to always jump the element to top of viewport, or to only jump if some of the element is outside the viewport.

**Comment by wobba** [comment]
Tested in my console now.. using `element.scrollIntoView` nicely scrolls to the top of the web part. Not top of the page.

**Comment by wobba** [comment]
I propose to call `scrollIntoViewIfNeeded` if available, and fallback to `scrollIntoView` if not there. And remove `focus`.
