### ISSUE TITLE
Custom renderers not available in workbench

### ISSUE THREAD

**Issue by frankok** [microsoft-search/pnp-modern-search#71]
**Version used**
3.8

**Describe the bug**
We are debugging custom renderers on the remote workbench (https://<your_tenant>.sharepoint.com/sites/<your_site>/_layouts/workbench.aspx). However, after adding the Search Results web part, none of our custom renderers appears in the web part property pane. 
They do appear as expected when we modify the Search Results web part on ordinary pages on the tenant.

Is this a known bug, or is it by design?

**Comment by FranckyC** [comment]
@taraldga any idea? @frankok if not to complicated, I strongly suggest you to move from custom renderers to the new web component extensibility. The custom renderer feature will be probably deprecated soon.

**Comment by frankok** [comment]
Is there any guideline or documentation on moving them or rewriting them?



Sendt fra min Samsung Galaxy-smarttelefon.



-------- Opprinnelig melding --------
Fra: Franck Cornu <notifications@github.com>
Dato: 23.01.2020 17:14 (GMT+01:00)
Til: microsoft-search/pnp-modern-search <pnp-modern-search@noreply.github.com>
Ko: Frank-Ove Berg Kristiansen <frank.kristiansen@bouvet.no>, Mention <mention@noreply.github.com>
Emne: Re: [microsoft-search/pnp-modern-search] Custom renderers not available in workbench (#71)


@taraldga<https://github.com/taraldga> any idea? @frankok<https://github.com/frankok> if not to complicated, I strongly suggest you to move from custom renderers to the new web component extensibility. The custom renderer feature will be probably deprecated soon.

**Comment by FranckyC** [comment]
Not specifically but a complete documentation is available to start creating web components https://microsoft-search.github.io/pnp-modern-search/search-extensibility-library/getting-started/#create-a-custom-web-component. From here, it is the same React concepts as the custom renderers.

**Comment by mherrema** [comment]
> @taraldga any idea? @frankok if not to complicated, I strongly suggest you to move from custom renderers to the new web component extensibility. The custom renderer feature will be probably deprecated soon.

I get the ability/benefits of extending with web components, but from a configuration standpoint custom renderers are much more friendly. I don't want end users to have to do anything "custom" like entering html into the custom template field. If there was a way to surface the web components available and select them, that would help, but I'm not sure that's feasible. 

It probably doesn't mean much but I'd like to hold on to custom renderers unless there's a user friendly way to configure web components/templates on the front end.

**Comment by taraldga** [comment]
Hi!

I have seen an issue coming from time to time because of a race condition in "what-get-rendered-first" in the property pane, but I haven't been able to create a pull request for a fix yet. I guess what we are seeing is that this issue is occuring more often / all the time in the workbench. 

I'll try to look into this week, will keep you updated!

**Comment by FranckyC** [comment]
Thanks @taraldga ;)

**Comment by FranckyC** [comment]
@mherrema I understand, and unfortunately, there is not way to do that for now. Web components are more a technical feature than a end user feature. They can't be configured through custom property option (for now). Sorry about that.

**Comment by frankok** [comment]
Thank you for your help and feedback in this matter. I have to agree with @mherrema, the renderers are favorable at the moment.

@taraldga, looking forward hearing from you regarding your findings in the matter. :-)

**Comment by taraldga** [comment]
I just realised that Application Customizers are not loading in .../workbench.aspx, and the Custom Renderers are made as Application Customizers. 
The easiest way to test your application customizers is to install the search webpart on a test site and set up the Custom Renderers serve configuration to point you to this site. Could you try that out, and let me know if it works?
