### ISSUE TITLE
V3.17.0 version in appcatalog is still 3.16.0

### ISSUE THREAD

**Issue by alexabramkin** [microsoft-search/pnp-modern-search#711]
**Version used**
3.17  [https://github.com/microsoft-search/pnp-modern-search/releases/tag/v3.17.0](url)

**Describe the bug**
When deployed to app catalog version still reads as 3.16

**To Reproduce**
Get the .sppkg from [https://github.com/microsoft-search/pnp-modern-search/releases/tag/v3.17.0](url)
Upload into appcatalog

**Expected behavior**
In app catalog version shall read 3.17  to match the release

**Screenshots**
<img width="373" alt="Screen Shot 2021-01-27 at 1 43 39 PM" src="https://user-images.githubusercontent.com/5289058/106038382-e30bbe00-60a5-11eb-91a5-96fa065ceab3.png">

**Desktop (please complete the following information):**
Any

**Additional context**
NA

**Comment by wobba** [comment]
Damn.. thought I had fixed it.. now it's ok :)
