### ISSUE TITLE
v3.11 Synonym matching only working one direction in People Results vertical 

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#713]
**Version used**
3.11.1

**Describe the bug**
I have a search vertical pointing to the People Results source. When I query for the parent synonym term 
   community health workers   -> this works, 11 results
I get results tagged to community health workers.
if I query for a child (synonym) term without using quotes around the term, I get no results.
   lady health worker    ---> this fails, 0 results
If I put quotes around my query for the same child (synonym) term, I get resutls.
  "lady health worker"   ---> this works, 11 results

**To Reproduce**

1. Configure a synonym
2. In our case, parent term is "community health workers". Synonyms are "healthcare   workers", "frontline workers",   "lady health worker", "ASHA", "village health   worker", "auxiliary nurse midwife"
3. search for community health workers - works fine
4. search for lady health worker - no results
5. search for "lady health worker" - works fine

**Expected behavior**
Acts like all the other verticals and gives me the same results if I use the quotes or not around the synonym

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Here's the top of the details view from the query:

Works:
{
  "queryModification": "(\"lady health worker\" OR \"healthcare workers\" OR \"frontline workers\" OR \"anganwadi worker\" OR \"asha\" OR \"village health worker\" OR \"auxiliary nurse midwife\" OR \"community health worker\" OR \"community
![working-with quote](https://user-images.githubusercontent.com/2616432/106059255-4f3af180-60a7-11eb-8da1-85b5ad67ca19.jpg)
![not working-no quotes](https://user-images.githubusercontent.com/2616432/106059259-4fd38800-60a7-11eb-94e5-152d705bc08e.jpg)

 health workers\")  ContentClass=urn:content-class:SPSPeople",
  "items": [

Works:
{
  "queryModification": "community health workers  ContentClass=urn:content-class:SPSPeople",
  "items": [

Fails:
{
  "queryModification": "lady health worker  ContentClass=urn:content-class:SPSPeople",
  "items": [],

It does not seem to recognize that this is a synonym.

**Comment by wobba** [comment]
Can you set up a parallel install with the latest v3 and verify if it's still an issue? Seems related to #133

**Comment by bryllyg** [comment]
Certainly. I'll give it a try.

**Comment by bryllyg** [comment]
Just tested with version 3.17. Same problem. Synonyms work if its a single word/acronym synonym, but not if the synonym is a phrase.

**Comment by wobba** [comment]
Which means #133 is not fixed? Will re-test it.

**Comment by bryllyg** [comment]
It doesn't seem like it. Thanks much.

**Comment by bryllyg** [comment]
Hi again, I'm finding that the synonyms are not working for phrases (multiple word synonyms) at all, for any of the verticals. I'd thought it was confined to the People vertical. Works fine for a single word.

**Comment by wobba** [comment]
It's not really a bug, if you search for `"lady health worker"` as a phrase it works.

Would you expect any substring to match the synonyms?

If I query:

`foo lady health worker bar`, should the `lady health worker` trigger a substitution?

I'm adding a special case if the original query matches as a phrase we match on it.

**Comment by bryllyg** [comment]
Correct, the feedback we've gotten from our users is that they expect it to trigger the synonym matching whether it's on its own Lady Health Workers, or part of a larger query entry Foo Lady Health Worker Window. Thanks!

**Comment by wobba** [comment]
Will be part of v3.18
