### ISSUE TITLE
V4.0 Error: Manifest not found for component ID 

### ISSUE THREAD

**Issue by myatix** [microsoft-search/pnp-modern-search#714]
Hi,
I resently deployed Modern Search V4 to a test tenant and the package deployed successfully, however when I try to add the webpart to the page I get the below error?

Version used
v4.0

Describe the bug
When adding the webpart to a page a Manifest not found for component ID error is shown.

To Reproduce
Deploy both packages at a Site level and then add webparts to a communication site page.

Expected behavior
The webpart should be added to the page without the shown error message.

Screenshots:

![image](https://user-images.githubusercontent.com/48433526/106110840-88c53880-614b-11eb-94f3-c8da88256c04.png)

![image](https://user-images.githubusercontent.com/48433526/106134703-342fb680-6167-11eb-974e-d86930499e04.png)

Desktop (please complete the following information):

Browser: Edge

**Comment by wobba** [comment]
We have updated the install docs but they are not live yet. Please review https://github.com/microsoft-search/pnp-modern-search/blob/develop/docs/installation.md

**Comment by myatix** [comment]
Thanks Mikael, I will give it a go! :)

**Comment by wobba** [comment]
As you see you have to deploy the extensibility package to the tenant app catalog - that's what fails for you.

**Comment by myatix** [comment]
Hi Again, 

Just a little feedback... I suggest you update the updated documentation that isn't live yet and remove the "Not Mandatory" label on the image.  ;)

**Comment by wobba** [comment]
Image is correct for the web part itself - we just don't have an image for the extensibility library.

**Comment by myatix** [comment]
OK... Perhaps a little miss leading... Or maybe it's just me! :)

**Comment by wobba** [comment]
I'll consider adding another screenshot or removing it next time I do doc changes. It's an unfortunate limitation. That said, you failed to look at the closed issues as this has been addressed multiple times already 😉
