### ISSUE TITLE
v3 Refiners appearing twice when the terms are reused in the Term Store

### ISSUE THREAD

**Issue by roberAlb** [microsoft-search/pnp-modern-search#715]
**Version used**
3

**Describe the bug**
Some refiners where appearing twice when the terms are reused in different Term Sets to tag the content.

**To Reproduce**
1. One term reused in two term sets
2. Two Managed Metadata columns one with each term set.
3. Tag content selecting the reuse term created
4.  Two refinablestring properties based on these new columns
5. Refiners webpart with these two refinablestring properties

**Expected behavior**
As the Id is the same for the reused term I was not expecting to see refiners duplicated.

**Screenshots**
![image](https://user-images.githubusercontent.com/50910751/106141624-ab1d7d00-6170-11eb-9232-d8854348c837.png)

**Desktop (please complete the following information):**
 - Browser [Chrome, Edge]

**Comment by wobba** [comment]
@roberAlb Look at the data coming back on your response. My bet is it appears twice, thus a data issue, not a web part issue. And likely one of them has some kind of space in the label name.

**Comment by roberAlb** [comment]
@wobba Thanks for your quick response, I'll take a look but just one term "Development" was appearing, after that I made the term reused in another term set and after tagging the content with that It was duplicated in the refiners, but I'll confirm thanks.

**Comment by wobba** [comment]
Open dev tools `F12` and look at the JSON response.

**Comment by roberAlb** [comment]
Hi again, this is what is coming in the response, as you can see only one Development tag is appearing but the webpart displays two.

![image](https://user-images.githubusercontent.com/50910751/106600719-1396a080-655b-11eb-9a98-823d61940037.png)

**Comment by wobba** [comment]
Is that JSON for the screenshot where the count is 2?

**Comment by roberAlb** [comment]
Sorry, I took the screenshot with a different query, this is the results for the first screenshot

![image](https://user-images.githubusercontent.com/50910751/106709894-75a3e400-65f5-11eb-81c8-0e5e9422a369.png)

**Comment by Yermek-Zhandauov** [comment]
@wobba Hey, is there any update on this? Same issue here.

Best,

Yermek

**Comment by wobba** [comment]
@Yermek-Zhandauov what are minimum repro steps for this? What I'm looking for is if the JSON response has the term twice or not. If it has, then it's an API issue, if it's once, then it's a weird UX issue.

**Comment by wobba** [comment]
v3 no longer maintained
