### ISSUE TITLE
V4.0 AADSTS65001: The user or administrator has not consented to use the application with ID

### ISSUE THREAD

**Issue by myatix** [microsoft-search/pnp-modern-search#716]
**Version used**
V4.0

**Describe the bug**
AADSTS65001: The user or administrator has not consented to use the application with ID '6430e589-2c2a-4fb5-bde4-3c50c78c950b' named 'SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource. Trace ID: d3e9ed44-c3c7-454a-b93f-d739f9dc2300 Correlation ID: 34f5ef0c-83c3-4910-afd6-be0b0ec271ec Timestamp: 2021-01-28 13:20:22Z

I didn't get a popup rsking for AppRegistration approval?

App Registration is enabled for users in AAD and PnP Modern Search was installed by a user with Global Administrator role.

**To Reproduce**
- Configured Results webpart to use Microsoft Search(see screenshots)
- Approved API permissions in SharePoint Admin Center

**Expected behavior**
Don't expect to get the above error in the results box. I would expect to see search results....

**Screenshots**

![image](https://user-images.githubusercontent.com/48433526/106146471-fd619c80-6176-11eb-97a6-d6d7db32160e.png)

![image](https://user-images.githubusercontent.com/48433526/106146770-63e6ba80-6177-11eb-9385-3c5a0ed39e50.png)

![image](https://user-images.githubusercontent.com/48433526/106146954-97294980-6177-11eb-9ba7-a781b1a6b423.png)

![image](https://user-images.githubusercontent.com/48433526/106146408-ede25380-6176-11eb-9f72-f4993e66b97f.png)

![image](https://user-images.githubusercontent.com/48433526/106147353-0acb5680-6178-11eb-90b0-b786d804b18e.png)

![image](https://user-images.githubusercontent.com/48433526/106148334-38fd6600-6179-11eb-8081-a14293c1f57f.png)

![image](https://user-images.githubusercontent.com/48433526/106148765-bfb24300-6179-11eb-9e01-db263c24ecc6.png)

**Desktop (please complete the following information):**
 - Browser: Edge

**Comment by wobba** [comment]
This is not a PnP modern web part issue but related to SPFx in general. See for example https://github.com/SharePoint/sp-dev-docs/issues/6520 and other similar issues.

**Comment by myatix** [comment]
Thanks... Strange because I was using Edge Chromium and the link you sent related to Legacy Edge and IE11.
