### ISSUE TITLE
Can not configure "No Results" message or Image for custom result template.

### ISSUE THREAD

**Issue by dheerajbalmuri** [microsoft-search/pnp-modern-search#718]
### Check existing issues before logging new ones

**Version used**
Ex: 3.16

**Describe the bug**

I'm trying to configure the custom template to display a text message and an image when there is no results for the search results web part, however I'm not able to do since it's showing blank screen in **Display** Mode or "No result returned for this query. This Web Part will remain blank in display mode according to parameters."  in the **Edit** mode. I also a custom web component for styling the results but it's not going to the custom component since the result set is empty.

A clear and concise description of what the bug is. Keep questions and bugs related to the web parts. If the issue relates to KQL or question around crawled and managed properties please use [Microsoft TechCommunity](https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev). Which means, if you experience the same behavior in classic web parts, then it's not an issue with PnP Modern Search 😉

**To Reproduce**
1. Edit Web Part 
2.  write Some text that does not give us documents result in "Search Key Words" 
2. Go to 3rd page
3. select Custom in results Layout
4. 

**Expected behavior**
In Custom template when the following code (or any  sample code that works) is changed it should render the text  that we are willing to put in case of no documents to display.
```
     {{else}}
            {{#unless showBlank}}
                <div class="template_noResults">{{@root.strings.NoResultMessage}}</div>
            {{/unless }}
```
             or

it should be customizable with customcomponent.tsx file which is also not being possible now. 

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] : Chrome

**Additional context**

**Comment by wobba** [comment]
* Set "Show blank if no result" to off
* Add this to your template
```
{{else}}
            {{#unless showBlank}}
                <img src="<URL to image>">Type your message here - text in the HTML
            {{/unless }}
        {{/if}}
```

**Comment by annetimdegraaf** [comment]
Hi, I had this working in the latest version of v3. Now I'm migrating to v4 and this does not work anymore. I'm not seeing any issue about this in v4. Can we extend this issue to v3 & v4?

I think it has something to do with the following not being in the v4 result template:

`{{#if @root.hasPrimaryOrSecondaryResults}}`

What can I do to get this working in v4?

**Comment by wobba** [comment]
@annetimdegraaf Use the debug template to look at the data available, then add handlebar logic as needed. As this is an old issue I'm inclined to close it as well if indeed still an issue.
