### ISSUE TITLE
escaping special characters in url 

### ISSUE THREAD

**Issue by Mr-Clrscr** [microsoft-search/pnp-modern-search#722]
Hi,

i'm trying to filter the search results based on the parameter from url, while i'm trying to give r&d it is not giving any result is it because the url is having two parameters and considering the d as third value

this is the final url
https://xyz.sharepoint.com/sites/testsite/SitePages/SearchResults.aspx?q=r&d&k=r&d

can we limit it to have only one parameter, or is there any other work around for this issue

**Comment by wobba** [comment]
You need to URL encode special characters

?q=r%26d&k=r%26d

**Comment by Mr-Clrscr** [comment]
hi @wobba , yes we can encode with %26, but entering %26 for generating & will be difficult task

**Comment by Mr-Clrscr** [comment]
Hi @wobba  
i'm using the default search box of sharepoint, 

<img width="356" alt="se" src="https://user-images.githubusercontent.com/39514550/106306293-dcd33880-6283-11eb-8855-a28e83f65e50.PNG">
<img width="363" alt="se2" src="https://user-images.githubusercontent.com/39514550/106306298-df359280-6283-11eb-9d06-03117907a018.PNG">

**Comment by wobba** [comment]
If the nav bar search box is not encoding & when redirecting to a custom page then that's a bug to report at sp-dev-docs.

**Comment by Mr-Clrscr** [comment]
Hi @wobba , actually it's working fine for all the sites, only for pnp webpart site it is not considering the thing

**Comment by wobba** [comment]
I have repro and have alerted the internal dev of the bug. When hitting search the query should be encoded when added to the URL. Closing here as it's not PnP related.

**Comment by Mr-Clrscr** [comment]
Hi @wobba , pnp search webpart is behaving the same
<img width="593" alt="def" src="https://user-images.githubusercontent.com/39514550/106311656-80741700-628b-11eb-85b5-061f41e42151.PNG">
