### ISSUE TITLE
Sort not active after switching verticals

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#723]
**Version used**
3.17

**Describe the bug**
I have multiple Sort by options set up, and multiple verticals. If I select to Sort by something, say Date, it works fine on the vertical I am on. I can click the AZ arrow icon 
![image](https://user-images.githubusercontent.com/2616432/106339626-f8225180-624b-11eb-8730-e3c6c49324b8.png)
to flip it from ascending to descending. All good.

Now, if I click on a different vertical, Date still shows in the Sort by box, but the Date filter is not applied, and the AZ arrow icon is not active (no pointer on hover, nothing happens when you click). 
![image](https://user-images.githubusercontent.com/2616432/106339666-1f791e80-624c-11eb-84a4-bb521929a593.png)
In order to sort vertical 2 by Date I must first change to a different Sort by option, then re-select Date. Once I do that it works as expected for vertical 2. 
![image](https://user-images.githubusercontent.com/2616432/106339686-2d2ea400-624c-11eb-8e36-ad34c23e3ecb.png)

Change verticals again, same problem.

**To Reproduce**

1. Configure a search page with multiple search Verticals and multiple Sort by options
2. On the first vertical, select a sort option. 
3. Click AZ arrow to switch between ascending/descending. Works fine.
4. Click vertical 2.
5. Click AZ arrow to switch between ascending/descending. Nothing. No pointer. Not clickable.
6. Select a different Sort by option. Sort works fine.
7. Reselect the original Sort by option. Sort works fine.
8. Click on vertical 1.
9. Sort is once again not active.

**Expected behavior**
Sort option selected on vertical one is still active as an option on vertical 2 OR it defaults back to the "Sort by" default selection,

**Screenshots**
See above

**Desktop (please complete the following information):**
Edge, Chrome

**Additional context**

**Comment by wobba** [comment]
Before investing time on state changes - can you share what the sorting scenarios on different properties are? As an example we don't offer sort in Microsoft Search as a relevance model using multiple factors serves search better. What is the use case for the end-user for having multiple sorting options on a search result?

**Comment by bryllyg** [comment]
Hi, Certainly! 

We're creating a single search interface that allows users to search a variety of related contexts. In the long run we will be including content from SQL and other sources. (Since we are currently using Search 3.x (we need the synonym support), we can not directly query SQL. so we have a Flow set up to grab the SQL content and duplicate it in a SharePoint list.) This SQL/List content has a variety of fields that the users want to be able to sort by. For example, in our Investments list, the users want to be able to sort the list by:
- Investment Name
- Number of Investment
- Investment ID
- Start Date
We do have filters configured for these fields, but the input we got from our HCD team from their needs assessment was that the users want the option to sort by these fields. Our testing feedback is also supporting the user's desire to be able to sort, particularly by number of investments. 

Currently, we have 5 verticals set up. In situations where they share a sort option, for example Name A-Z and Date, when you switch between tabs, the options is no longer applied to the new vertical, which makes our users think that sort is broken. We are explaining that they have to select another sort option, then re-select the original option in order for it to be applied to the current vertical, but that's a bit non-intuitive. 

Thanks much! Let me know if I can provide any additional details.

**Comment by wobba** [comment]
Have you considered using column/row formatting on the SP list itself, and then use sorting there? I'll take a look to see how easy it is to get state to work in the web part as well on the sorting.

**Comment by bryllyg** [comment]
Yah, the list sort options are kind of what I'm trying to replicate. The idea of this project, however, is to bring all of the content into a shared search context, not have users go to the unique lists and libraries. Thanks for checking on the state.

**Comment by wobba** [comment]
Pushed a fix to reset the sorting on vertical change. Will be part of v3.18
