### ISSUE TITLE
Refiner search "show filter for refinement value" clear does not clear selected item

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#724]
**Is your feature request related to a problem? Please describe.**

When a Refiner is configured to "show filter for refinement values" after you start typing the "clear" link becomes available. Clicking this clears the filter search box; however, if you've already clicked on and selected an option, the check box is not cleared at the same time. This is confusing my users. 

**Describe the solution you'd like**

It would be more intuitive if clicking "clear" cleared both the text in the search box and any selected items/check boxes.

**Describe alternatives you've considered**

User training.

**Additional context**
Thanks!

**Comment by wobba** [comment]
Bug template not followed.

**Comment by bryllyg** [comment]
Sorry. I didn't think it was a bug, just a feature request.

**Comment by wobba** [comment]
Now it is :)

**Comment by wobba** [comment]
Still an issue for v4? v3 no longer maintained
