### ISSUE TITLE
Search Refiner FileSize in MB

### ISSUE THREAD

**Issue by Sharu-k** [microsoft-search/pnp-modern-search#727]
Hi,

this is a question regarding search refiner i.e. file size.

is there a way where i can show up the file size in MB now it is showing as the following: 
<img width="205" alt="Capture" src="https://user-images.githubusercontent.com/78362857/106468188-9c61fd80-64c3-11eb-8c70-73bd8d185989.PNG">

I'm using v3

**Comment by wobba** [comment]
We don't support templating on filters. That said, is the file size filter really useful? What's your scenario where it gives value?

**Comment by Sharu-k** [comment]
@wobba , we have bunch of videos, where end user want's to filter upon the file sizes/duration of videos

**Comment by Sharu-k** [comment]
and we are also not able to see the preview of video, we are only able to see a preview of document. in case of video it didn't playing up. is it how preview works for videos ?

**Comment by wobba** [comment]
Thumbnails should work fine for videos using the default templates (simple list, tiles, carousel). Interactive preview is not available.

Right now if you want to have filters like you suggest you need to develop a custom filter web part which works with the PnP web part. Or you create a webpart with static filters which add KQL to filter via the URL params.

We might add something like this as an improvement for v4 to specify the bucket ranges and formatting.

**Comment by wobba** [comment]
v4 support templating for filters
