### ISSUE TITLE
V3.16 User Token not resolved in query

### ISSUE THREAD

**Issue by mark-ferkaluk** [microsoft-search/pnp-modern-search#728]
Hey guys, I hope you can help me...

**Version used**
3.16

**Describe the bug**
I have configured a search result web part with the following Search query keywords:
ContentType:"Quicklink" AND Author:"{User.Name}"

It seems that the Token is not resolved in the query. Because if I am entering a static name it works. I also tried Author:{User.Name}, without the quotes. Do you have an idea.

I am using Chrome to configure.

I would expect I only get items with content type "Quicklink" (which is a custom content type), that are created by the current user.

Do you have an idea?

Thanks and best regards,

Mark

**Comment by wobba** [comment]
Query variables have to go in the query template field, not the search text field. Assuming that is your case.

**Comment by mark-ferkaluk** [comment]
Okay, got it! Works now. But to understand. What is the difference between the "Search query keywords" and the "Query template" configuration?

Thanks!

**Comment by wobba** [comment]
Query keywords are meant for user input, while the template is where you would put additional application logic/filters.
