### ISSUE TITLE
managed Property handlebar expression - Unable to view Image in list item

### ISSUE THREAD

**Issue by sankara2020** [microsoft-search/pnp-modern-search#729]
I have created a list that has a multiline column with enhanced rich text and added a handlebar expression to the detailed list managed column.

The  multiline column contains text and images. The problem is that when using the handlebar expression for that column, the image is not shown in the results.

Any help would be appreciated!
 
**To Reproduce**
1. Create a list 
2. add a multiline column with rich text 
3. Add images and text
3. create a Managed Property for the column
4. Search result > custom template > add managed Property handlebar expression

**Expected behavior**
Image should be visible in the list search results

**Comment by wobba** [comment]
Issue does not follow the template. And please check previous issues before asking, like #533
