### ISSUE TITLE
combining two handlebar expressions in single statement

### ISSUE THREAD

**Issue by Sharu-k** [microsoft-search/pnp-modern-search#730]
Hi,

I'm trying to apply handlebar expression on the output of another handlebar expression something like below:

{{replace {{lowercase ParentLink}} SPSiteUrl " "}}

so first i want to convert the parentlink to lowercase then on that output i want to replace the spsite url with blank, but i was not able to escape the flowerbracess inside the expression. is there a way where we can achieve this kind of functionality

**Comment by wobba** [comment]
Trying to web search for some handlebar help solves it. https://handlebarsjs.com/guide/expressions.html#subexpressions
