### ISSUE TITLE
Missing Managed Properties

### ISSUE THREAD

**Issue by sparkitect** [microsoft-search/pnp-modern-search#731]
I'm attempting to build a 'staff directory' using the Modern Search Web Parts. The customer wants a table layout with columns for First Name, Last Name, Job Title, Department, Phone and Email. However, some of those are not showing up in the "Selected properties" chooser, nor in the "Manage columns" chooser for the details list layout. Specifically, the FirstName, LastName and Department Managed Properties are not listed.

**Describe the solution you'd like**
The Managed Properties for FirstName, LastName and Department should be selectable when configuring a People-based search.

**Describe alternatives you've considered**
I may be misremembering, but I believe v3 allowed us to manually type in the name of any Managed Properties we wanted to include that weren't showing up in the picker. If this were possible in v4 that would be a good-enough fix.

**Comment by wobba** [comment]
v4 support entering props as well. It's a bit weird (due to the control we use). Put cursor in the box. Type the mp name which clears existing content and hit ENTER when done. Next click the dropdown to ensure the mp is selected.

**Comment by cironis-adam** [comment]
@wobba  @sparkitect I had the exactly same issue. I'm also building a staff directory via Details list layout and wanted to add my custom managed properties and couldn't find them in the dropdown as I didn't know that I can type in the property and hit enter to actually add it to the list of properties. Might be great addition to describe more in the documentation. 🙏

**Comment by carry2web** [comment]
Thank you @wobba this is a pitfall for more I'm very sure. Thank you @sparkitect for asking this exact question.

**Comment by sparkitect** [comment]
Perfect!

**Comment by jeffangama** [comment]
Hi, did you manage to show the mobile phone ?
