### ISSUE TITLE
Search Query Log is available?

### ISSUE THREAD

**Issue by AnjalyDeepak** [microsoft-search/pnp-modern-search#734]
The users can search 'Search queries' in Microsoft intelligence search in a SharePoint site collection. Can we get a search query report(any other SharePoint log for the search queries) in that particular site collection only?

![ContentManagement_SharePoint_example_AI_search_results_mobile](https://user-images.githubusercontent.com/78209273/106721672-f8936180-662a-11eb-865c-0de82b09dada.jpg)

**Comment by wobba** [comment]
Questions about search telemetry is outside the scope of these web parts. See https://techcommunity.microsoft.com/t5/microsoft-search-blog/we-re-improving-search-usage-reports-in-sharepoint-online-with/ba-p/1849502 for the latest information shared.
