### ISSUE TITLE
Site Usage Analytics

### ISSUE THREAD

**Issue by AnjalyDeepak** [microsoft-search/pnp-modern-search#735]
How to get an overview of all subsites in a site collection, not only the root site collection? Or How can we get site usage analytics for aggregate information including all subsites /team sites in a site collection?

**Comment by wobba** [comment]
Search for `contentclass:sts_web OR contentclass:sts_site` and you will get a list of all sites/subsites. If you want to limit a specific site collection add a path filter for the site itself together with the above.

 `(contentclass:sts_web OR contentclass:sts_site) path:https://tenant.sharepoint.com/sites/somesite`
