### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by myatix** [microsoft-search/pnp-modern-search#736]
Hi All,

I am sorry if this is the incorrect location to add a feature request but I couldn't see any other location.

On the current PnP Results WebPart it is only possible to setup pagination for results that are outside the normal view. It would be nice if we had the ability to add "See all" so the solutions usability could be configured so it was more inline with the Out of the Box SharePoint modern webparts such as News and Highlighted Content WebParts. 

This would provide a more consistent user experience for end users.

Keep up the great work guys! :)

**Comment by wobba** [comment]
There's no way to get more than 500 results in one search request, so "See all" will involve lazy loading on scroll, and there's also a limitation to how far you can page today if sorting is arbitrary.

**Comment by myatix** [comment]
OK... It was more in terms of the usability with regards to user experience. How do the OoB webParts work with regards to these limits? If there are the same restrictions on the OoB WebParts then I am guesssing most people will accept the limits.

**Comment by wobba** [comment]
Not sure where you have see all in the HCWP. Can you share screenshots of OOB experiences showing "all"?

**Comment by myatix** [comment]
Hi Mikael,

You can see the "See all" in the screenshot below...
This shows up when you have more items than set in the "Show up to this many items at a time" in the Layout section of the HCWP.
See below for details:
![image](https://user-images.githubusercontent.com/48433526/107041208-818fd180-67c0-11eb-9058-dd9e7e11354c.png)
![image](https://user-images.githubusercontent.com/48433526/107041366-b56af700-67c0-11eb-9284-febf27c2758c.png)

**Comment by wobba** [comment]
The SeeAll.aspx page is limited to 200 results, with no paging. I'll close this one.
