### ISSUE TITLE
Encoding the special characters from url

### ISSUE THREAD

**Issue by Sharu-k** [microsoft-search/pnp-modern-search#737]
Hi,

Is there a way where we can grab the URL and encode the values then send it to pnp webpart to filter the results, i'm facing some issues while encoding the url keywords before passing it to pnp webpart, so i was looking for a way to encode the values with the help of pnp webpart

**Comment by wobba** [comment]
If you consume query parameteres via dynamic data you will get the unencoded data from the parameter which can be used in the web parts. Might not understand your scenario completely.

**Comment by Sharu-k** [comment]
Hi @wobba, in our case data is not getting encoding in url, so the special characters stays same without encoding something like q=j&j not as q=j%26j, so we are looking for something where we can get the value from url and trying to encode with the help of pnp webpart

**Comment by wobba** [comment]
Is your issue that you are creating links in the handlebar template and need encoding there? If it's about reading the URL from the browser, then you cannot use & as that's a URL special character.
