### ISSUE TITLE
PnP Modern Search Web parts on home page break new page creation (Return to issue #526)

### ISSUE THREAD

**Issue by Kostadin-cmd** [microsoft-search/pnp-modern-search#738]
Hi I experience the same problem as issue #526 

I haven`t read any useful solution for me there. Could you please clarify how can I fix this? I`m using version 3.16. When I try to create a new page in the site the header is hidden and can`t edit or publish the page. 

Thanks

**Comment by wobba** [comment]
Please update your issue and use the bug template. Full repro steps and screenshots if possible. If not we'll close the issue.
