### ISSUE TITLE
Filtering videos & documents

### ISSUE THREAD

**Issue by Sharu-k** [microsoft-search/pnp-modern-search#740]
Hi,

I'm trying to filter only videos & documents in search results using KQL. 
 something like below:

{searchTerms} Path:{SiteCollection} IsDocument="true"

is there any similar condition for video to filter videos as well like IsVideo="true"

return results when either it is a document or video

**Comment by wobba** [comment]
`FileType:mpg FileType:wmv FileType:mp4 FileType:asf FileType:wmv FileType:mov` something like that.

**Comment by Mr-Clrscr** [comment]
Hi @wobba  is there way similar to not to show specific file? like not show filetype:aspx

**Comment by wobba** [comment]
`-FileType:docx` or `NOT FileType:docx`. Start reading my post #1 https://www.techmikael.com/2014/03/s15e01-kql-basics.html and move on to the other parts as needed :)
