### ISSUE TITLE
Error code on click of image thumbnail

### ISSUE THREAD

**Issue by Sharu-k** [microsoft-search/pnp-modern-search#741]
Hi,

we are getting an error code on click of image thumbnail of video as shown below:
<img width="407" alt="issu" src="https://user-images.githubusercontent.com/78362857/106869845-68bae980-66f6-11eb-97d0-3a37ee5267e9.PNG">

this is the following code snippet we are using 

 ```
 <li class="template_listItem" tabindex="0">
    {{#> resultTypes item=item}} {{!-- The block below will be used as default item template if no result types matched --}}
    <div class="template_result">
     <div class="template_previewContainer ms-hiddenSm">
      {{#if (getPreviewSrc item)}}
      <div class="doc-container">
       <div class="img-container">
        <img
         class="document-preview-item img-preview"
         width="120"
         loading="lazy"
         src="{{getPreviewSrc item}}"
         data-src="{{getPreviewSrc item}}"
         data-url="{{#if ServerRedirectedEmbedURL}}{{ServerRedirectedEmbedURL}}{{else}}{{getPreviewSrc item}}{{/if}}"
         onerror="this.onerror=null;this.src='{{@root.utils.defaultImage}}';"
        />
        <div class="hover">
         <div><i class="ms-Icon ms-Icon--Preview" aria-hidden="true"></i></div>
        </div>
       </div>
      </div>
      {{/if}}
     </div>
```

**Comment by Sharu-k** [comment]
<img width="417" alt="issu3" src="https://user-images.githubusercontent.com/78362857/106890543-7761ca80-670f-11eb-90b2-5ae0f931a020.PNG">
the same issue is getting from simple list layout

**Comment by wobba** [comment]
That's an internal API error for the file in question. If you visit the library for the same file, are you then seeing a thumbnail in the library info pane?

**Comment by Sharu-k** [comment]
hi @wobba , how can we handle this case? can we show any placeholder ?

**Comment by wobba** [comment]
I think we should perhaps handle the error in the pop-up component instead of showing the error.

**Comment by Sharu-k** [comment]
Hi @wobba , can we know how can we show error message

**Comment by Sharu-k** [comment]
and @wobba  also is there a way where we can compare the value something like {{#if size > 0 }} show this img else show this img

**Comment by wobba** [comment]
Not runtime. You already have onerror on the img tag - and if it fails the onclick hover should also ideally be disabled. Have to recheck if we ignore onerror, as it allows script injection, which we don't. So I believe we must create components handling this internally better.

**Comment by Sharu-k** [comment]
Hi @wobba , on error, it's not working we are able to click on the image. and for the user it might be misleading

**Comment by wobba** [comment]
I know, hence the web component should handle this - and why I tagged this issue so someone can take a look when they have time.

**Comment by wobba** [comment]
I'm adding a `<pnp-img>` component which support onerror, and hide onerror. So you can replace your `img` tag with this one.

**Comment by wobba** [comment]
Closing.
