### ISSUE TITLE
Configure the PnP WebParts for multiple existing sites with PowerShell?

### ISSUE THREAD

**Issue by myatix** [microsoft-search/pnp-modern-search#742]
Is there a nice way to auto configure WebParts using a PowerShell script? We would like to deploy PnP Search results WebParts across multiple existing sites with a predefined configuration. I understand we could have done this using PnPSiteTemplates but these sites already exist and we need to deploy just under 100 PnP Search Results WebParts on almost as many pages and sites.

If this doesn't exist it would be a really nice feature to have... :)

**Comment by kasperbolarsen** [comment]
Sure, as the settings are stored as JSON it is easy to update existing settings:
Below I update the Selected Properties for the Results Web part on the "Home.aspx" page for a specific Site Collection 

Connect-PnPOnline -Url $siteurl -Credentials $cred
$page = Get-PnPClientSidePage -Identity "home.aspx"
$webpart = $page.Controls | Where-Object {$_.Title -eq "Search Results"}
if($webpart)
{
    $instanceid = $webpart.InstanceId
    $json = $webpart.PropertiesJson  

    $convertedjson = $json| ConvertFrom-Json |Select selectedProperties
  if($convertedjson.selectedProperties.IndexOf("WorkspaceIsArchivedOWSBOOL") -eq -1)
  {
      $newjson = $newjson.Replace('"selectedProperties":"', '"selectedProperties":"WorkspaceIsArchivedOWSBOOL,')

      Set-PnPPageWebPart -Page "home.aspx"-Identity $webpart.InstanceId -PropertiesJson $newjson | Out-Null
      $page.Publish()
           
  }
}

**Comment by kasperbolarsen** [comment]
I would use the Apply-PnPProvisioningTemplate method to add or modify the pages containing the search web parts, and just use the approach above in order to fix minor issues

**Comment by wobba** [comment]
Relates to #761

**Comment by Laul0** [comment]
Hi @kasperbolarsen,

You can use `Get-PnPProvisioningTemplate` and edit the schema to change the static values by tokens or Template parameters (like URL, custom field, etc), then use `Apply-PnPProvisioningTemplate` to update the page or create a new one.

I am doing this with most of my projects currently and it works well 😄
