### ISSUE TITLE
Filter web part not displaying refiners when set to panel

### ISSUE THREAD

**Issue by joelfmrodrigues** [microsoft-search/pnp-modern-search#743]
**Version used**
3.15.3 - works
3.16 - does not work
3.17 - does not work

**Describe the bug**
Filter panel is empty. Refiners are configured and display when layout is set to Vertical, but not when layout is set to Panel.

**To Reproduce**
1. Add search results web part to a page
2. Add Filters web part to a page
3. Connect web parts
4. Ensure Filters web part layout is set to panel
![image](https://user-images.githubusercontent.com/19577724/106911672-4f1ba100-66fa-11eb-9a05-f188070cf37b.png)
5. Search for results
6. Open filter panel - **no refiners available!**
7. Edit page and change filter web part layout to Vertical
8. Repeat search query and validate that refiners are now displayed

**Expected behavior**
Refiners to be displayed when using Vertical layout

**Screenshots**
![image](https://user-images.githubusercontent.com/19577724/106912454-ef71c580-66fa-11eb-9d79-604e91708971.png)

**Desktop (please complete the following information):**
 - Browser: Edge (new)

**Additional context**

**Comment by coupalm** [comment]
Same issue for me.
