### ISSUE TITLE
Manifest not found for component when adding Web part

### ISSUE THREAD

**Issue by spsanders** [microsoft-search/pnp-modern-search#744]
**Version used**
4.0.0 January 2021

**Describe the bug**
The two required packages were uploaded to the tenant app catalog.  During upload, the deploy to tenant option was not selected for either package.  Both apps were installed on a Communication site.  The documentation provides no guidance as to whether both or just the Web parts apps require installation on a given site collection.  The supporting extensibility package is greyed in site contents (see below).  The Web parts app installed as expected in site contents.
Attempted to add a search box web part and received an error stating the manifest not found for component

**To Reproduce**
1. Upload the two packages to the tenant app catalog but do not deploy to tenant.
2. Add the two apps to a communication site from site contents new > app then search for pnp.
3. Edit a page and search for pnp in the web parts dialog.
4. Select the search bar web part or any other modern search web part.

**Expected behavior**
We previously deployed these modern search apps successfully in another tenant, but each were deployed to all sites.  All modern search web parts worked as expected in this tenant.  It was expected that we could upload the apps to the tenant app store but not deploy to all sites then selectively add the app to sites.  The tenant where modern search web parts work as expected is in Targeted Release whilst the tenant that failed is not.

**Screenshots**
![image](https://user-images.githubusercontent.com/16594511/106942099-61411380-66e9-11eb-9eab-a1d616f60300.png)
![image](https://user-images.githubusercontent.com/16594511/106942147-7322b680-66e9-11eb-9c8a-4f689f78bf27.png)

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Manifest not found for component id "96dcffa8-2c69-47ec-ba5c-770213aeb4fe" and version "1.0.0".

INNERERROR:
Manifest not found for component id "96dcffa8-2c69-47ec-ba5c-770213aeb4fe" and version "1.0.0".
CALLSTACK:
Error
    at t [as constructor] (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_3a7c8205e7e2b619a5038473c7f52b6d.js:1:870052)
    at new t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_3a7c8205e7e2b619a5038473c7f52b6d.js:1:1013805)
    at Function.e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_3a7c8205e7e2b619a5038473c7f52b6d.js:1:1036979)
    at Function.e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_3a7c8205e7e2b619a5038473c7f52b6d.js:1:1033024)
    at https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_06fb90fbb103ba8a0bb1.js:1:66114

**Desktop (please complete the following information):**
 - Browser Edge

**Comment by FranckyC** [comment]
Hi @spsanders, can you redeploy the extensibility library and set "Make this solution available to all sites in the organization"?

**Comment by spsanders** [comment]
Thank you for the prompt response @FranckyC.  I deleted then uploaded using the deploy to tenant option.  The issue has been resolved.
