### ISSUE TITLE
PNP results web part 500 error using result source id GUID

### ISSUE THREAD

**Issue by dorjemrav** [microsoft-search/pnp-modern-search#745]
**Version used**
Ex: 4.0

**Describe the bug**
PNP - results web part shows [HTTP]:500 error when added to a Modern web page of a site, containing only the PNP - Search Box web part, once the "Result Source ID" field is changed from "LocalSharePointResults" to the GUID for a result source, that exists at the tenant level.

The error displayed in the web part is 

[HTTP]:500 - Internal Server Error [CorrelationId]:1d12a89f-006b-b000-7d27-49962a741943 [Version]:16.0.0.20913

From the Chrome browser console shows the following

`Fetch finished loading: GET "https://<mytenant>.sharepoint.com/sites/Test-1Widget/_api/site?$select=IsHubSite,HubSiteId,Id".
e.fetch @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
e.fetchCore @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
(anonymous) @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Promise.then (async)
e._fetchWithInstrumentation @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
(anonymous) @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Promise.then (async)
e.fetchCore @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
e._fetch @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
e.fetch @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
e.get @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
u @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
e.getHubInfo @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
u @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
e.replaceHubTokens @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
a @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
Promise.then (async)
l @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
a @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
Promise.then (async)
l @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
a @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
Promise.then (async)
l @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
u @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
e.resolveTokens @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
F @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
t.buildSharePointSearchQuery @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
F @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
t.getData @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
M @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
t.getDataFromDataSource @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
M @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
t.componentDidUpdate @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
To @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
t.unstable_runWithPriority @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
dl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
xo @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
po @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
(anonymous) @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
t.unstable_runWithPriority @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
dl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
vl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
ml @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
co @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Ho @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Qo @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Jo @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
render @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
t.renderCompleted @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
a @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
Promise.then (async)
l @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
Ri @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
t.render @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
t.onCustomPropertyUpdate @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
g @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
t.onChange @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
jl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Al @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
To @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
t.unstable_runWithPriority @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
dl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
xo @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
po @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
(anonymous) @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
t.unstable_runWithPriority @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
dl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
vl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
ml @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
vo @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
In @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Show 47 more frames
sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1 POST https://<mytenant>.sharepoint.com/sites/Test-1Widget/_api/search/postquery 500 (Internal Server Error)
e.fetch @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
e.fetchCore @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
(anonymous) @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Promise.then (async)
e._fetchWithInstrumentation @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
(anonymous) @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Promise.then (async)
(anonymous) @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Promise.then (async)
e.fetchCore @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
e._fetch @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
e.post @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
m @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
e.search @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
n @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
Promise.then (async)
s @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
F @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
t.getData @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
M @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
t.getDataFromDataSource @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
M @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
t.componentDidUpdate @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
To @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
t.unstable_runWithPriority @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
dl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
xo @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
po @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
(anonymous) @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
t.unstable_runWithPriority @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
dl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
vl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
ml @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
co @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Ho @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Qo @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Jo @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
render @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
t.renderCompleted @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
a @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
Promise.then (async)
l @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
Ri @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
t.render @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
t.onCustomPropertyUpdate @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ chunk.sharepoint-search-datasource_816f94bdf02b26f20aaf.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
g @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
t.onChange @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
(anonymous) @ modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
jl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Al @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
To @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
t.unstable_runWithPriority @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
dl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
xo @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
po @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
(anonymous) @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
t.unstable_runWithPriority @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
dl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
vl @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
ml @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
vo @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
In @ sp-pages-assembly_en-nz_4fbca39c62ef103848097363a8761f69.js:1
Show 25 more frames
modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1 Uncaught (in promise) Error: [HTTP]:500 - Internal Server Error [CorrelationId]:6d12a89f-b0a7-b000-7d27-4bc5df597df1 [Version]:16.0.0.20913
    at e.<anonymous> (modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1)
    at modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
    at Object.next (modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1)
    at a (modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1)`

NOTE despite the 500 error, if the page is published, and a search term entered the correct results are returned from the search source, and the 500 error doesn't show any longer.

**To Reproduce**
1. Go to PNP - Search Box web part
2. Edit the web part properties
3. Change the available data sources to "SharePoint search"
4. Change the Result Source ID to the guid of a result source that exists at https://<mytenante>-admin.sharepoint.com/_layouts/15/searchadmin/EditResultSource.aspx?level=tenant&sourceid=a3574412-ee31-4927-8cbe-51b1c986f16f
5. Immediately on entering the Result Source guid, the PNP - search results web part shows a 500 error

**Expected behavior**
No 500 error is shown when changing the "Result Source ID" field

**Screenshots**
pnpsearch500error.png
![pnpsearch500error](https://user-images.githubusercontent.com/73564735/106959186-3913ec00-679f-11eb-8b6d-adad28ffe98b.png)

**Desktop (please complete the following information):**
 - Browser Chrome 
 - Windows 10
 - SharePoint online, team site

**Additional context**
Another user I know using V3 of the pnp modern search, has the same setup without the 500 error.

**Comment by dorjemrav** [comment]
Is there anything else I can provide that would help with resolving this one ?

**Comment by wobba** [comment]
If you find a developer which has time to triage for repro and possibly fix it, that helps :)

**Comment by wobba** [comment]
Close due to inactivity.
