### ISSUE TITLE
Can't pull Author and Document ID from the filters

### ISSUE THREAD

**Issue by yahookevin** [microsoft-search/pnp-modern-search#746]
I'm unable to configure the Author and Document ID from the filter tab. Although I can see the properties coming up in the filter field, they don't pull any results.
When searching, these field do have some value along with it.

"AuthorOWSUSER": "****@***** | Firstname Lastname| 693A30232E667C6D656D626572736869707C6A656D2E77696C736F6E406D656C626F75726E652E7669632E676F762E6175 i:0#.f|membership|firstname.lastname@****",

"DocumentID": "COMPOC-2039685342-7",

Here document ID is the OOTB id generated once the feature is activated.
Attached screenshots.
Any help appreciated.
![SearchGrab2](https://user-images.githubusercontent.com/67360002/106974119-4386b380-67a8-11eb-8d80-b5083206438c.png)
![SearchGrab](https://user-images.githubusercontent.com/67360002/106974123-44b7e080-67a8-11eb-86ba-9a807c9f044f.png)

**Comment by wobba** [comment]
You can only use managed properties which are refinable as filters. Navigate to https://tenant-admin.sharepoint.com/_layouts/15/searchadmin/ta_listmanagedproperties.aspx?level=tenant and check the settings for each property in the schema.
