### ISSUE TITLE
Enable Multiple Selection in Search Refiners

### ISSUE THREAD

**Issue by BhoomeshJoshi** [microsoft-search/pnp-modern-search#747]
Hello Everyone,

I have implemented pnp-modern-search (version 3.16.0.0) in my modern term site.

It is working correctly showing search results and refiners.

In refiners i can select only one option from one category.

Now, I will need enable multiple selection in the category under refiners.

Please refer attached screenshot for better understanding.

![SS](https://user-images.githubusercontent.com/78580802/106991984-724b5c80-679d-11eb-9aef-17a031fa44ab.png)

Can anyone help me for the same?

Thanks in advance.

**Comment by wobba** [comment]
Use the multi-value template.
![image](https://user-images.githubusercontent.com/51104/107047219-dd118d80-67c7-11eb-8baa-e336838d17d7.png)
