### ISSUE TITLE
Failed to load component...

### ISSUE THREAD

**Issue by myatix** [microsoft-search/pnp-modern-search#748]
**Version used**
V4.0

**Describe the bug**
The PnP Results WebPart doesn't load but instead returns the below error:

SPLoaderError.loadComponentError]:
Failed to load component "544c1372-42df-47c3-94d6-017428cd2baf" (pnpSearchResultsWebPart). Original error: Failed to load component dependency "544c1372-42df-47c3-94d6-017428cd2baf" from component "pnpSearchResultsWebPart" (Failed to load component "96dcffa8-2c69-47ec-ba5c-770213aeb4fe" (pnpSearchExtensibilityLibrary). Original error: Failed to load entry point from component "96dcffa8-2c69-47ec-ba5c-770213aeb4fe" (pnpSearchExtensibilityLibrary). Original error: Error loading https://component-id.invalid/96dcffa8-2c69-47ec-ba5c-770213aeb4fe_1.0.0
	Unable to load script https://<tenant>.sharepoint.com/sites/app-catalog/ClientSideAssets/f13a5866-004f-4219-b078-69731f848bd1/pnp-search-extensibility-library_cd42f9721ba957f6ff603ad080e9ad4d.js). Original error: {3}

**To Reproduce**
Add the PnP Results WebPart to a Communication site page.

**Expected behavior**
Expected PnP Results WebPart to load without an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/48433526/107003767-9606a680-678d-11eb-9100-9a68d3274cc5.png)
![image](https://user-images.githubusercontent.com/48433526/107003974-e2ea7d00-678d-11eb-9119-d48671579c41.png)

**Desktop (please complete the following information):**
Chrome

**Additional context**

**Comment by myatix** [comment]
This issue seems to be related to Guest Users (external access) not being aloud on the App Catalog.

https://sharepoint-tricks.com/enable-external-users-to-access-custom-solution-on-sharepoint/

**Comment by Saroj48** [comment]
I do have same issue, can anyone help me I am new to this. I uploaded the package to app catalog and deployed the package. After adding add to site contents, I went to modern page and tried to add search web parts but showed error same as above.

Thanks in advance.. I don't think above author comment is my solution.

**Comment by wobba** [comment]
@Saroj48 please open new issues, don't comment on old ones as your scenario may be different. This way you can provide detailed steps of what you did, which version etc.
