### ISSUE TITLE
Open Search Results in Client App

### ISSUE THREAD

**Issue by EdgarasKarpavicius** [microsoft-search/pnp-modern-search#75]
Hi,

Is there a way to force results (e.g. documents) to open in Work Desktop, rather than Online?

I have made the relevant changes in the Library settings to default to desktop client etc., but that has no effect.

Thanks

**Comment by FranckyC** [comment]
Hi @EdgarasKarpavicius, the library settings has no effect on this. However what you can do is to update the Handlebars template and use the `href="{{Path}}"` property instead of the `href="{{getUrl item}}"` expression for the href link.

**Comment by EdgarasKarpavicius** [comment]
Perfect, thank you very much!
