### ISSUE TITLE
V4.0 Every 3rd Image in Infomation Card Layout not showing

### ISSUE THREAD

**Issue by myatix** [microsoft-search/pnp-modern-search#750]
**Version used**
V4.0

**Describe the bug**
When configuring the PnP Search Results WebPart to show results in the Information Card layout every third image is missing.
The screenshot below uses a Results source to show only News items.

Possibly related to this comment in the code...
// Can lead to 404 errors but it is a trade of for performances. We take a guess with this url instead of batching calls for all items and process only 200.
                        item[AutoCalculatedDataSourceFields.AutoPreviewImageUrl] = `${this.props.pageContext.site.absoluteUrl}/_api/v2.1/sites/${siteId}/lists/${listId}/items/${itemId}/driveItem/thumbnails/0/large/content?preferNoRedirect=true`;

Working images=  src="https://<tenant>.sharepoint.com/sites/cuprainfonet/_api/v2.1/sites/eb414dc4-c0de-4446-9330-583c1049e586/lists/0895be8c-3a6d-49aa-8820-6bcb66cfbd22/items/22b89be7-91a5-40c2-a4cd-10cb7ee33ba0/driveItem/thumbnails/0/large/content?preferNoRedirect=true"

Images not loading = previewImageSrc: processedProps.previewImage ? UrlHelper.decode(processedProps.previewImage) : '#',

**Expected behavior**
All images should appear in all information cards.

**Screenshots**
![image](https://user-images.githubusercontent.com/48433526/107045719-21039300-67c6-11eb-99e3-ba190ab0d25c.png)

**Desktop (please complete the following information):**
Chrome

**Comment by wobba** [comment]
Can you check network trace for errors? Is it every 3rd, or just by chance.

**Comment by myatix** [comment]
Hi Mikael,

It is every 3rd image...
We have created a nasty work around that resolves our issue by re-mapping the card field to https://<tenant>.sharepoint.com/_api/v2.1/sites/eb414dc4-c0de-4446-9330-583c1049e586/lists/0895be8c-3a6d-49aa-8820-6bcb66cfbd22/items/{{slot item @root.slots.ItemId}}/driveItem/thumbnails/0/large/content?preferNoRedirect=true

But this is not pretty...

**Comment by FranckyC** [comment]
Seems to be the same as https://github.com/microsoft-search/pnp-modern-search/issues/689. Did you used the latest package?

**Comment by myatix** [comment]
> Seems to be the same as #689. Did you use the latest package?

Yes we used v4.0 downloaded from the Github site

**Comment by Laul0** [comment]
Hi @myatix, does the latest version (4.2.3) fixes your issue?
