### ISSUE TITLE
V3.17: Web Part error on load of SearchBoxWebPartStrings

### ISSUE THREAD

**Issue by alexabramkin** [microsoft-search/pnp-modern-search#751]
**Version used**
Ex: 3.17

**Describe the bug**
The following error is displayed when adding web part to the page and after:
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "096b96cc-8a44-41fa-9b4d-c0ab2ab2a779" (SearchBoxWebPart). Original error: Failed to load URL 'https://….sharepoint.com/sites/SPFx-Development/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-parts-searchboxwebpartstrings_en-us_4ff299871f4ee540126dd8f99a7d2c08.js' for resource 'SearchBoxWebPartStrings' in component '096b96cc-8a44-41fa-9b4d-c0ab2ab2a779' (SearchBoxWebPart). The file was not found in the server.

INNERERROR:
Failed to load URL 'https://….sharepoint.com/sites/SPFx-Development/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-parts-searchboxwebpartstrings_en-us_4ff299871f4ee540126dd8f99a7d2c08.js' for resource 'SearchBoxWebPartStrings' in component '096b96cc-8a44-41fa-9b4d-c0ab2ab2a779' (SearchBoxWebPart). The file was not found in the server.
CALLSTACK:
Error
at t [as constructor] (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_3a7c8205e7e2b619a5038473c7f52b6d.js:1:870052)
at new t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_3a7c8205e7e2b619a5038473c7f52b6d.js:1:1013805)

**To Reproduce**
1. Go to modern page
2. Click on + sign to add web part
3. Scroll down to search box web part

**Expected behavior**
Web Part being added to the page without any errors

**Desktop (please complete the following information):**
 - Browser: Mac OS / Chrome

**Additional context**
In addition any existing PnP Search web parts (Refiners,Reslts) added to the pages previously fail with similar error

**Comment by wobba** [comment]
Can you retry in a browser on Windows, to isolate if it's OS or browser related? Also, does the user have read access on the app catalog, as I see you haven't enabled CDN.

**Comment by alexabramkin** [comment]
Yes user is site collection admin on app cat

**Comment by alexabramkin** [comment]
Closing this one as I am unable to reproduce any more, even on the same site/tenant - must be something specific to the site collection

**Comment by rachelmarshall** [comment]
I have this error too.. 

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Manifest not found for component id "96dcffa8-2c69-47ec-ba5c-770213aeb4fe" and version "1.0.0".

INNERERROR:
Manifest not found for component id "96dcffa8-2c69-47ec-ba5c-770213aeb4fe" and version "1.0.0".
CALLSTACK:
Error
    at t [as constructor] (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_f2a6d5a2ddacad6fe99f72579e74f146.js:65:19896)
    at new t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_f2a6d5a2ddacad6fe99f72579e74f146.js:65:164857)
    at Function.e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_f2a6d5a2ddacad6fe99f72579e74f146.js:65:202176)
    at Function.e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_f2a6d5a2ddacad6fe99f72579e74f146.js:65:198221)
    at https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_01c8e48deab9f3a3784f.js:1:66061

**Comment by wobba** [comment]
@rachelmarshall your error is related to not installing the extension library for v4, not v3. And you should not comment on closed issues. Log new ones. See https://microsoft-search.github.io/pnp-modern-search/installation/
