### ISSUE TITLE
V 3.15.1.0/3.16 and 3.17 on classic pages in GCC tenant: Web Part fails with "Source id contains invalid characters, like "_"." error message and webpart configuration will not open.

### ISSUE THREAD

**Issue by alexabramkin** [microsoft-search/pnp-modern-search#752]
**Version used**
Ex: 3.15.1.0/3.16 and 3.17

**Describe the bug**
While adding the Search Box Web Part to the classic page it fails with "Source id contains invalid characters, like "_"."  error message. Web Part properties can be open, but Configure button is not reacting to clicks.
Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Source id contains invalid characters, like "_". Id: "WebPart.096b96cc-8a44-41fa-9b4d-c0ab2ab2a779.g_101b1756_16cd_4eeb_ada6_13ffc5143c75".

CALL STACK:
Error: Source id contains invalid characters, like "_". Id: "WebPart.096b96cc-8a44-41fa-9b4d-c0ab2ab2a779.g_101b1756_16cd_4eeb_ada6_13ffc5143c75".
at e._validateSource (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-classic-page-assembly_en-us_a58e15c973e7345858d7c9ea4058bb03.js:1:559944)
at e.addSource (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-classic-page-assembly_en-us_a58e15c973e7345858d7c9ea4058bb03.js:1:559034)
at e.initializeSource (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-classic-page-assembly_en-us_a58e15c973e7345858d7c9ea4058bb03.js:1:655096)
at t.<anonymous> (https://....sharepoint.com/sites/SPFx-Development/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_271505b0f0003bd40b7c5947d698ce42.js:1:468884)
at https://....sharepoint.com/sites/SPFx-Development/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_271505b0f0003bd40b7c5947d698ce42.js:1:466028
at Object.next (https://....sharepoint.com/sites/SPFx-Development/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_271505b0f0003bd40b7c5947d698ce42.js:1:466133)
at https://....sharepoint.com/sites/SPFx-Development/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_271505b0f0003bd40b7c5947d698ce42.js:1:465069
at new Promise (<anonymous>)
at le (https://....sharepoint.com/sites/SPFx-Development/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_271505b0f0003bd40b7c5947d698ce42.js:1:464846)
at t.onInit (https://....sharepoint.com/sites/SPFx-Development/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-box-web-part_271505b0f0003bd40b7c5947d698ce42.js:1:468709)

**To Reproduce**
1. Go to classic page
2. Click on start editing the page and add the web part
3. Scroll down to PnP grouping and select Search Box

**Expected behavior**
Web part added to the page and configurable.

**Desktop (please complete the following information):**
 - Browser Chrome on Mac OS
 - Tenant: GCC

**Comment by wobba** [comment]
Is this a MacOS issue? As I cannot repro on Windows.

**Comment by alexabramkin** [comment]
I do not think so, but let me try on windows machine.

**Comment by alexabramkin** [comment]
Tried it in chrome on Windows machine - same error: also tried 3.15.1.0 and it has the same error message. This is GCC tenant - let me see if I can reproduce in commercial.

**Comment by wobba** [comment]
Could be GCC related but I'm not aware of what the differences is on SPFx with GCC and commercial.

**Comment by alexabramkin** [comment]
Other SPFx web part (not using CDN) can be added and works just fine on both classic and modern pages. Same PnP Search web parts are working fine on modern pages.

**Comment by alexabramkin** [comment]
Attaching screenshot that shows how web parts are added:
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/5289058/107082809-bac94100-67c2-11eb-963f-f9117ff60f08.png">

**Comment by alexabramkin** [comment]
Just checked on commercial tenant in Chrome on Windows with v3.16, same error

**Comment by wobba** [comment]
Can you try it in a modern page?

**Comment by alexabramkin** [comment]
Modern page works

**Comment by wobba** [comment]
Then it seems to be some SPFx issue, and not directly related to these web parts. And we won't focus to troubleshoot on classic pages either as classic, is, well, classic. Stop using it 😉

**Comment by alexabramkin** [comment]
Politely disagree on SPFx issue as other (non PnP modern search 3.15.1/3.16/3.17) SPFx web parts work on both classic and modern pages. So I still think it is PnP Modern Search web parts specific issue. :) And personally I would stop using classic, but it is not my call and we were trying to see if we can address some of the scenarios with adding PnP Search web parts to classic page. Thank you for you attention to this Mikael!

**Comment by wobba** [comment]
Well, if someone wants to look at the code and figure it out and provide a fix, that is ok. If you're on classic you can still use the classic web parts and customize them any way you want more or less.

**Comment by wobba** [comment]
Closing as it seems 3rd party SPFx which uses dynamic data won't work on classic pages. The id which breaks is nothing we can control. Feel free to log this at https://github.com/SharePoint/sp-dev-docs
