### ISSUE TITLE
Installation doc inconsistency

### ISSUE THREAD

**Issue by sympmarc** [microsoft-search/pnp-modern-search#753]
**Version used**
Ex: 4

**Describe the bug**
I wanted to make some updates to the [Installation doc](https://microsoft-search.github.io/pnp-modern-search/installation/), at first just to fix a couple spelling things. But when I clicked the pencil to edit, it looks like the [Github version](https://github.com/microsoft-search/pnp-modern-search/blob/main/docs/installation.md) is out of sync with the [published version](https://microsoft-search.github.io/pnp-modern-search/installation/).

Can you let me know if it makes sense for me to edit the Github version or not?

**Additional context**
As I'm going through the installation instructions, I think it makes sense to explain how to approve the permissions a bit better, too. I'm happy to make those edits as well, but I want to be sure I'm editing the right thing.

**Comment by wobba** [comment]
@sympmarc target the dev branch for doc updates. And if you are updating can you reference https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-overview and say that ext lib can be installed in a site app catalog, but has to check off "all sites" (which in itself is such a weird setup, and you can only deploy a lib once in the tenant.. weird)

**Comment by sympmarc** [comment]
Well, note that the pencil on the existing pages sends you to the `main` branch. Confusing!

**Comment by wobba** [comment]
@sympmarc hardcore people clone the repo and push  for a PR 😉 but yes, I totally get that. We typically update main before each release.

**Comment by sympmarc** [comment]
Of course. But if you have that pencil there...

**Comment by FranckyC** [comment]
Hi @sympmarc , I fixed the edit URL to redirect to the develop branch. You can now submit a PR :)
