### ISSUE TITLE
Hide Pagination navigation until there are enough items for 2 pages

### ISSUE THREAD

**Issue by myatix** [microsoft-search/pnp-modern-search#756]
**Version used**
V4.0

**Describe the bug**
In the current version of the PnP Results WebPart pagination navigation "1" is shown as soon as you add a single item. In the Information Card layout. The navigation shouldn't appear until items start to populate the second page. 

**Expected behavior**
Expect Pagination navigation to be hidden until items exceed the "Number of items per page" set in the webpart.

![image](https://user-images.githubusercontent.com/48433526/107229990-c9139900-6a1e-11eb-9cbd-04fa77c74d66.png)

![image](https://user-images.githubusercontent.com/48433526/107229866-a1bccc00-6a1e-11eb-9055-9efd130fe15e.png)

**Desktop (please complete the following information):**
 - Chrome

**Comment by wobba** [comment]
You can click  `{}` to customize the template and add that logic yourself as well by expanding on the `{{#if @root.properties.paging.showPaging}}` statement.

![image](https://user-images.githubusercontent.com/51104/107786593-5f60fb00-6d4e-11eb-89ca-2c787f2b7061.png)

**Comment by FranckyC** [comment]
Fixed in develop.
