### ISSUE TITLE
Tab value missing from configure verticals

### ISSUE THREAD

**Issue by spsanders** [microsoft-search/pnp-modern-search#757]
**Version used**
4.0.0

**Describe the bug**
The documentation shows that there should be a **Tab value** in the configure verticals dialog.  This column is missing when accessing the configure data verticals.

**To Reproduce**
1. After installing and deploying the two required packages as directed including API permissions, go to a modern page and edit.
2. Search for the PnP web parts and add the search box, verticals, and results PnP modern search web parts.
3. Edit the verticals web part then click configure verticals.
4. The tab value is missing.

**Expected behavior**
A tab value column should be available in the configure verticals dialog as stated in the documentation.  I am experiencing this issue in two tenants.

**Screenshots**
![image](https://user-images.githubusercontent.com/16594511/107259455-9fe50f80-6a02-11eb-8ad0-edddaf3c648b.png)

**Desktop (please complete the following information):**
 - Edge browser
 - Windows 10

**Comment by wobba** [comment]
@FranckyC missing column or wrong docs?

**Comment by spsanders** [comment]
Hi @wobba.  After watching videos and reading documentation for v3, I think it is a documentation error for v4 under configure verticals.
![image](https://user-images.githubusercontent.com/16594511/107536673-a6e95a80-6b87-11eb-9094-a6aa7c3a7ca2.png)

**Comment by NerijusV** [comment]
It is not possible to configure search verticals without "Tab value" property. Am I right?

**Comment by popeadam** [comment]
Same issue for us - without the 'tab value' column, the verticals web part configuration only supports hyperlinks - which means they're largely redundant, might as well use a quick links webpart...

**Comment by myatix** [comment]
I agree the documentation on the site is very misleading here. Where is the "Tab Value" field and if there is no Tab Value field how do we specify a token for another search scope?

**Comment by wobba** [comment]
It's in v4
