### ISSUE TITLE
Property Pane Values in Library component

### ISSUE THREAD

**Issue by Bhargavikandru** [microsoft-search/pnp-modern-search#76]
I have a doubt,
Can we get Property Pane values in the Library Component.

**Comment by FranckyC** [comment]
Hi @Bhargavikandru . Not directly no. However what you can do is pass any relevant property through web component attributes. Just reference tem with `@root.<property>`. You can use the debug layout to see all available properties.

![image](https://user-images.githubusercontent.com/5659122/73302997-9a47cd80-41e3-11ea-9f42-b9ecd77fd0d8.png)
