### ISSUE TITLE
Search web parts not loading after upgrading from V4 Preview to latest V4

### ISSUE THREAD

**Issue by jhammar** [microsoft-search/pnp-modern-search#760]
Search web parts not loading after upgrading from V4 Preview to latest V4.

Is there any way around this so that we don't have to reconfigure all search web parts?

Was this expected, i. e. will it happen the next time we install a V4 update? 

This v4 preview was installed with configured search web parts.
pnp-modern-search-parts.sppkg Product ID : {59903278-DD5D-4E9E-BEF6-562AAE716B8B}
PnP Modern Search - Search Web Parts 4.0.0.0

Installed latest V4 by deleting preview & installing this latest version. It won't deploy if I don't delete old one or change this filename to old one; i.e. no " - v4". Same web part loading errors either way. Also, tried emptying recycle bins & toggle "Add as new version to existing files".
pnp-modern-search-parts-v4.sppkg Product ID : {59903278-DD5D-4E9E-BEF6-562AAE716B8B}
PnP Modern Search - Search Web Parts - v4 4.0.0.0

Configured webparts give these type errors on page load:
[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-7e5a-49ec-8db6-812f76c375f2" (pnpSearchBoxWebPart). Original error: Manifest not found for component id "96dcffa8-2c69-47ec-ba5c-770213aeb4fe" and version "1.0.0".

INNERERROR:
Manifest not found for component id "96dcffa8-2c69-47ec-ba5c-770213aeb4fe" and version "1.0.0".
CALLSTACK:
Error
    at t [as constructor] (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_f2a6d5a2ddacad6fe99f72579e74f146.js:65:19896)
    at new t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_f2a6d5a2ddacad6fe99f72579e74f146.js:65:164857)
    at Function.e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_f2a6d5a2ddacad6fe99f72579e74f146.js:65:202176)
    at Function.e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_f2a6d5a2ddacad6fe99f72579e74f146.js:65:198221)
    at https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_01c8e48deab9f3a3784f.js:1:66061

**Comment by Grahamworth** [comment]
Same issue here

**Comment by wobba** [comment]
Unsure what happens here as the manifest alias and id seems to be the same. If you add parts to a new page, then it works? But we did do some renaming etc before release. You should not expect unannounced breaking changes in upcoming v4.x releases, and we strive not to break anything.
