### ISSUE TITLE
Thumbnails not showing

### ISSUE THREAD

**Issue by nicholascrosby** [microsoft-search/pnp-modern-search#765]
Good morning. Newbie here, so, please excuse me if I am missing something easy.

I am using a PnP Search Results web part, Details layout, Show Thumbnail selected. The results are filtered to the site which contains a graphics library. No thumbnails from the actual graphics are showing. Yet, if I click on the grey standard thumbnail image, a larger image does pop up.

Any advice on how to get thumbnails working would be greatly appreciated.

![image](https://user-images.githubusercontent.com/78870977/107546926-8377dd00-6b92-11eb-939e-ac60bba0c463.png)

**Comment by nikosmsk** [comment]
Look here:  #689 , #750 
That should have been fixed already and will be available with the next release

**Comment by wobba** [comment]
Closing the issue as it doesn't follow the bug template description to point to which version of the web parts etc.
