### ISSUE TITLE
All queries are multi-geo enabled.  Need to turn off multi-geo.

### ISSUE THREAD

**Issue by edixon-github** [microsoft-search/pnp-modern-search#766]
__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
Ex: 3.16

**Describe the bug**
All queries are submitted with multi-geo enabled.  In a multi-geo environment, need ability to scope queries to the geo from which the query is submitted.

**To Reproduce**
Issue any query.

**Expected behavior**
The ability to scope the query to the geo from which the query is submitted.

**Screenshots**
![image](https://user-images.githubusercontent.com/28318509/107554852-b79fcd80-6b93-11eb-9a53-bb8cb6c9dc2b.png)

**Desktop (please complete the following information):**
 - All

**Additional context**

**Comment by wobba** [comment]
Fixed for v3.18
