### ISSUE TITLE
Last modified is not giving exact results

### ISSUE THREAD

**Issue by Mr-Clrscr** [microsoft-search/pnp-modern-search#767]
I've added the last modified time and tried displaying in search result's, even after reindexing the library it is showing the old date value but not the latest

**Comment by wobba** [comment]
If you're not getting the expected date, you need to troubleshoot indexing, it's not related to these web parts. Before logging an issue, search for the same file in Microsoft Search, is it also showing the wrong date?

Re-indexing of a library can take time, no SLA. I cover troubleshooting in my troubleshooting book on Amazon, as there are several steps you can take.
