### ISSUE TITLE
Refinable property unavailable when map to a people crawled property

### ISSUE THREAD

**Issue by coupalm** [microsoft-search/pnp-modern-search#769]
**Version used**
4.0.0

**Describe the bug**
If the account configuring the search result web part **does not have an SP licence** (It occurs when I access my customers tenant with an account they created for me), it will not display a refinable property map to a people crawl property. Ex: I've map RefinabelString02 to SPS-Birthday. I can use it in the search criteria successfully but I can see it in the selected properties to include in result template.
When I log with a user account with a licence, I see it. I've tried with classic, and I was able to see the property in classic refiners with an account with no licence.

**To Reproduce**
1. Log with an account with no licence assigned and edit or full control permission to the site
2. Make sure a userprofile has the anniversary (birthday) set : Ex: Febuary 12
3. Map a RefinableString to SPS-Birthday
4. Configure the search result web part query template with {searchTerms} RefinableStringXX=2/* and apply. The result will return user profiles meeting the search criteria
5. In selected properties drop box, look for RefinableStringXX. It will not display.

**Expected behavior**
Need to see the Refinable property map to a People Property

**Screenshots**
![Refinable](https://user-images.githubusercontent.com/11309224/107690058-9a442f80-6c77-11eb-89e0-9cdb406e7e50.png)

**Desktop (please complete the following information):**
 - Edge Chromium

**Additional context**

**Comment by wobba** [comment]
Type it manually. And, if you don't have an SP license, well, you shouldn't use SharePoint or configure a SP page.

* put cursor in the "selected properties" field
* Type your mp name and hit ENTER
* The mp should now be in the drop-down.

**Comment by coupalm** [comment]
I have a SP licence in my tenant, but I don't have a licence for every customers tenants. Even if I log with my user account/licence in my customers tenant, it will not work.

I've tried typing the managed property manually but it does not work. 

But that's ok I will work this out.

Thanks.

**Comment by wobba** [comment]
Well, you are sort of breaking / bending the license, so if some API's block you, then that's how its. That said, I'm adding a import/export web part setting function in v3.18 which could help. You can also use PowerShell to set web part properties.

**Comment by coupalm** [comment]
It works, I was typing the property name at the end of the selected properties. When clicking in the field and typing the property (it removes everything in ths field), it worked.

Thanks.
