### ISSUE TITLE
Handlebars expression show up as Title in Details list

### ISSUE THREAD

**Issue by martinewald** [microsoft-search/pnp-modern-search#77]
If I use a Handlebars expression in a Column on a "Details list". The full content is shown as Title. 

![image](https://user-images.githubusercontent.com/22732855/73341229-83a18500-427c-11ea-9200-da5e09f05a61.png)

Is there a way to change what is shown as Title?

**Comment by FranckyC** [comment]
Hi @martinewald , try `<strong title="My custom tooltip">SubFolder</strong>` instead. You can control the tooltip text using the 'title' HTML attribute.
