### ISSUE TITLE
V4 Sort by date fields not working

### ISSUE THREAD

**Issue by omarelanis** [microsoft-search/pnp-modern-search#771]
**Version used**
V4 Search Results Webpart

**Describe the bug**
In the new v4 search result webpart I cannot select any date fields to be sorted by even if they are sortable, applies to both built-in fields like "Created" and managed property fields which are Sortable (RefinableDate01 etc), after selecting the field and clicking apply the value is not actually saved so if I go back into the sort properties section the value has been cleared. Selecting a string based field like RefineableString01 saves however.

1. Go to webpart properties screen and click on ""Edit sort order"
![image](https://user-images.githubusercontent.com/35841910/107783013-adbbcd00-6d41-11eb-9fa9-0e20b00f3e40.png)
2. in the field name input select any date based field
![image](https://user-images.githubusercontent.com/35841910/107783208-e9569700-6d41-11eb-8687-e68109bf3694.png)
3. Save the change and then go back in and the value has been wiped
4. The results also do not sort by date

**Expected behavior**
The results would be sorted by the date field

**Screenshots**
![image](https://user-images.githubusercontent.com/35841910/107783731-7c8fcc80-6d42-11eb-912d-7e4eda5fcc62.png)

**Comment by wobba** [comment]
Tested just now and now issue using Created.

* Added result web part
* Set static query to `*`
* Clicked Sort Order
* Typed in `Created` and picked ascending
* Click Save
* Results are ok
* Changed to descending
* Results are ok

**Comment by omarelanis** [comment]
Reinstalled it on a dev environment and working fine following your steps, have tried reinstalling the extension on the production site again but same issue occurs, tried on two different site collections but same issue occurring. Basically the Save button doesn't change to say "Add and save" and just stays as "Save".

Must be something in the production environment causing this so will need to investigate on my side, thank you for taking the time to respond

**Comment by wobba** [comment]
Weird indeed, and not easy when repro is not consistent :(
