### ISSUE TITLE
Vertical selection based on querystring

### ISSUE THREAD

**Issue by BarendDS** [microsoft-search/pnp-modern-search#772]
Hi Guys,

Is the an option the select the rendered vertical based on the querystring?
I need this because I'm using links to different pages in the verticals.

I can't find any documentation on this.

Tx in advance.

Cheers

**Comment by wobba** [comment]
v3 support this. v4 not yet. As you don't say what version you are using and since you think our issue templates are just for fun, I'll close this one 🙂

**Comment by BarendDS** [comment]
Hi Mikael,

My apologies, I’m using V4 so this answers my question.

Have a nice weekend!

Cheers

**Comment by HiteshDuggal** [comment]
Hey there, just putting a comment, so that it can be considered an enhancement, as I have a similar requirement.

**Comment by wobba** [comment]
@HiteshDuggal already an issue for this for someone to start working on if they want #732
