### ISSUE TITLE
Search Result is getting refreshed again and again without any change in Search Query

### ISSUE THREAD

**Issue by prabhu8323** [microsoft-search/pnp-modern-search#774]
**Version used**
3.17

**Describe the bug**
I have downloaded the solution from the link https://github.com/microsoft-search/pnp-modern-search/releases and executed NPM Install command. Upon gulp serve the Result is returning but it is getting refreshed again and again. I see that code is getting into ComponentDidUpdate method in SearchResultContainer.tsx. It does check the condition (!isEqual(this.props, prevProps)) and it returns always true (infinite loop). If we dont use Search box and just put the query in Search Result webpart it returns the result properly and dont go into infinite loop.

**To Reproduce**
1. Go to 'https://github.com/microsoft-search/pnp-modern-search/releases/tag/v3.17.0'
2. Download the source code (Zip) from asset and unzip
3. Open Node.JS command prompt and point to the folder Search-Parts as in below screen shot and run gulp serve

![image](https://user-images.githubusercontent.com/48989167/107854999-c8776a00-6e45-11eb-9a02-310ad63b896b.png)

4. Go to workbench add Search box and Search result WebPart. put the query i.e keyword in Search result webpart (in section Search query keywords in the config). it works fine
![Capture1](https://user-images.githubusercontent.com/48989167/107855143-b34f0b00-6e46-11eb-827c-541af1232b48.JPG)

5. Config the Search box and Search Result webpart as in below screen shot and put some keyword in search box and search, then issue occurs and it goes into infinite loop
![Search Box Config](https://user-images.githubusercontent.com/48989167/107855101-813da900-6e46-11eb-9152-6b6ba80f632f.JPG)
![Search Result Config](https://user-images.githubusercontent.com/48989167/107855151-bba74600-6e46-11eb-810f-d1f98de1d3e3.JPG)
![Capture2](https://user-images.githubusercontent.com/48989167/107855256-3a9c7e80-6e47-11eb-9860-b5d8341a8396.JPG)

**Expected behavior**
The screen/search result should not refresh without any change in query or pagination

**Desktop (please complete the following information):**
 - Browser Chrome, Edge

**Comment by wobba** [comment]
Does this only happen on the SP hosted workbench? Does it happen if you deploy it?

**Comment by wobba** [comment]
Why are you connecting the search box to the result web part? I assume your error is due to misconfiguration. See https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-box/ for search box config options and https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-results/#search-query-configuration for how to connect the result web part to the search box.

**Comment by prabhu8323** [comment]
@wobba , Thank you so much. yes, I guess it was due to misconfiguration. Now, this issue is no more. Thanks again!
