### ISSUE TITLE
Filtering Null Values

### ISSUE THREAD

**Issue by Mr-Clrscr** [microsoft-search/pnp-modern-search#775]
Hi,

I've been trying to remove unwanted files from the search results, and tried using the following condition
-FileType:' ' / -FileType: null / NOT FileType: null (but somehow i was not able to remove, is there a way where we can remove files with filtype with null)

I've also tried filtering based on IconExt i.e. -IconExt: "aspx" [but not able to filter using this as well] is there a way to write condition based on IconExt

**Comment by wobba** [comment]
This is a KQL question, outside of the project.

KQL only support matching on values which exists, not empty values. So you need to either include on know values, or exclude known values.

**Comment by wobba** [comment]
@StephenHoughton4 you might want to read https://www.techmikael.com/2023/04/filter-on-managed-properties-in-search.html

**Comment by spplante** [comment]
@wobba A bit late, but it seems like the new KQL syntax mentioned in the article above only works for SharePoint results, does not work when searching for Graph external items :(
