### ISSUE TITLE
Format search result then inherit default theme

### ISSUE THREAD

**Issue by jm06** [microsoft-search/pnp-modern-search#776]
Dear Frank 
I use the PnP Search Result v4. Query returns old style content type based pages. The layout selected is the list. This is what I got returned. Encouraging as Count, Pagination show, Data is being returned (see below)   
![image](https://user-images.githubusercontent.com/16796220/107997982-01e1de00-6fdc-11eb-9585-cc8e5f01dd25.png)

I am just surprised some items do not show. 
1. see the gap between the Hyperlink and the Created Date
2. the grey placeholder image. it would be preferable if displayed the rollup image property from the content type. (When hovering and clicked, the preview actually display a preview. Fab)
3. in the gap, expected to see Author followed, if possible, by created date then No Views (views is a nice to have)

This is closer to what I would like to achieve in terms of format
![thumbnail_image (1)](https://user-images.githubusercontent.com/16796220/107999455-4ae76180-6fdf-11eb-8972-31661de60357.png)

File icon  then Title as hyperlink to the page
                        Name of Library (Path - breadcrumb)
                        Site > Author followed, if possible, by created date then No Views (views is a nice to have)
                        bit of text from the page content

or on the extreme right-side, the image pointing at the rollup content image. 

I also suspect that the result search layout should inherit the bespoke Theme from the hub site. It doesn't seem to do so in the first screenshot.

I took a quick look at the code and attended replacing author by Created By. It made not changes to the result displayed. Could one please assist and put me in the right direction. I ought to believe the piece of code is this one

My main interest for now, is formatting the data. Then the styling. 
I believe modifications should be made in that bit of code (hopefully this is a good uneducated guess)
```
<div class="template--listItem--contentContainer">
    <span class="template--listItem--title example-themePrimary">
        <a href="{{slot item @root.slots.PreviewUrl}}" target="_blank" data-interception="off">{{slot item @root.slots.Title}}</a>
    </span>
    <span> {{getSummary (slot item @root.slots.Summary)}}
        <span class="template--listItem--author">
                {{#with (split (slot item @root.slots.author) '|')}}
                    {{[1]}}
                {{/with}}
        </span>
    </span>
    <span>{{getDate (slot item @root.slots.Date) "LL"}}</span>
        <div class="template--listItem--tags example-themePrimary">
            {{#if (slot item @root.slots.Tags)}}
                <pnp-icon data-name="Tag" aria-hidden="true" data-theme-variant="{{JSONstringify @root.theme}}"></pnp-icon>
                    {{#each (split (slot item @root.slots.Tags) ",") as |tag| }}
                        <a href="#{{slot item @root.slots.Tags}}:'{{trim tag}}'">{{tag}}</a> {{/each}} {{/if        
        </div>
</div>
```

I hope this makes sense. If you needed to clarify a point and/or If you believe this is not the best to achieve the result, take me out of my misery and do not hesitate to advise me. 

Thank you in advance for your time and assistance

**Comment by wobba** [comment]
You are free to craft your own templates and show any metadata you would like. Which means the only "bug" per say is that the title is not styled according to the theme.

**Comment by jm06** [comment]
I would like firstly to thank Frank who kindly nudge me to look at the slots, instead of read the manual. And thank you for the efforts putting that part together. I am fully aware that "La critique est facile, l'Art plus difficile"

I mapped the columns used in my content type with the relevant fields
- Summary => PublishingPageContentOWSHTML
- PreviewImageUrl => PublishingPageImageOWSIMGEX
So far so good

AUTHOR: Using the Card layout, I noticed that the author was being picked up and displayed, where in the List/Details List it wasn't. Changed the layout to List, took a look at the code and remembered that the split function produces a ZERO based array. Replacing the {{[1]}} by a {{[0]}} (see code below) displayed the value of the author within the list. Then the layout selected changed to Custom
`                {{#with (split (slot item @root.slots.author) '|')}}
                    {{[1]}}
                {{/with}}`

DATE: the date displays in US format February 24, 2021. I thought the format picked up the Regional Settings of my Site Collections. Both Time zone set to UTC London and Locale to English (United Kingdom). Checking the layout DEBUG brought the answer Culture: "en-US"
![searchDebugCultureEnglishUS](https://user-images.githubusercontent.com/16796220/108982652-efc00980-7685-11eb-856f-5fc9c8627d17.jpg)

IMAGE: still no luck with those... I have tried the Card / List / Details List. The slot mapping works and returns the relevant path as confirmed within the DEBUG view for 
 "PublishingPageImageOWSIMGEX": "<img alt=\"\" src=\"/sites/archive/Site%20Asset%20Images%20WhosWho/rsz_******_*******.jpg\" style=\"BORDER&#58;0px solid;\" />",

![searchCardReturn](https://user-images.githubusercontent.com/16796220/108985296-cce32480-7688-11eb-9765-8362769b6915.jpg)

TEMPLATE: I would happily give it a go but I am not sure how, or may be wobba could give me a pointer. As Frank already suggested so nicely (no sarcasm, I am genuinely grateful), I am going back to the documentation. 

SUMMARY: It displayed the WHOLE content of the column/property. I tried to amend the getsummary to only display the first 150/180 characters using the LEFT(getsummary, 150) but failed miserably. More a question of syntax at the right place I suspect. May be another pointer from you.

STYLE: is that a bug well not too worried about that. More trying to provide a feedback

Any return from you much appreciated

**Comment by wobba** [comment]
@jm06 it's not clear if you have added mappings to `PublishingPageContentOWSHTML` etc. If so, don't mess with the OOB implicit managed properties. You will only hurt yourself in the long run. Use `RefinableString` instead for text ones.

By default author uses `AuthorOWSUser` which is in this format `user@email.com | Display Name | <base64 upn> i:0#.f|membership|user@upn.com`, which is why we pick 1, as that's the display name.

Locale is picked from the SharePoint UX using whatever SPFx picks up `this.pageContext.cultureInfo.currentUICultureName`.

Image has to be a valid URL, meaning you need to strip out the html in that tag.

See #533 on how to render a rich html field.

**Comment by wobba** [comment]
Fixed the simple list layout a bit for the upcoming v4.1 release. Still not perfect, but better.

**Comment by Ofer-Gal** [comment]
I am using 
`{{#with (split (slot item @root.slots.author) '|')}} {{[1]}} {{/with}}` 
But nothing is showing 
With ` <span class="template--listItem--author">` around it did not show either.

Anything else I should try?
Thanks
