### ISSUE TITLE
PnP search Refiner(v4) Web Part is not translating Date range labels(From, To) and Calendar popup in French

### ISSUE THREAD

**Issue by ShariqSiddiquie** [microsoft-search/pnp-modern-search#778]
These are the steps. Please see attached file with screenshots.

1.	Communication site collection (language – English and French).
2.	Create site page (English) and render PnP search result & Refiner web parts.
3.	Set the Refiner web part properties, save and publish the page.
4.	Translate page(Multilingual) for French language and publish the page.
5.	Login with French user profile account and access the French page.
6.	Concern, Refiner web part – Date range labels are showing in English.  

Issue1 – “From” and “To” labels are showing in English. It is an issue.
Issue2 – Calendar is coming in English only. It is an issue.
Issue3 – Selected values from calendar popup are showing in French. It is correct.
               
[PnP Search Refiner Issue - French Profile.docx](https://github.com/microsoft-search/pnp-modern-search/files/5991203/PnP.Search.Refiner.Issue.-.French.Profile.docx)

**Comment by wobba** [comment]
We currently only have English language support in v4, and we will accept PR's for translating the en-us.js files 👍

**Comment by robegoja** [comment]
Thanks @wobba for the update. I am creating corresponding es-es.js and fr-fr.js files with the translations to provide support for French and Spanish and will be submitting a PR once I get through that.

**Comment by FranckyC** [comment]
Merci @robegoja !

**Comment by SammyKrosoft** [comment]
> Thanks @wobba for the update. I am creating corresponding es-es.js and fr-fr.js files with the translations to provide support for French and Spanish and will be submitting a PR once I get through that.

Hey, I'll help @robegoja for the French translation ... I'm French from France and moved to Canada in 2010, adopting the French-Canadian language (both Franco-Ontarian and Québécois) during this time :-) - there will be a couple of challenges as I'm more an Exchange specialist than a Sharepoint specialist, but we'll manage to do it correctly :-)

**Comment by FranckyC** [comment]
@SammyKrosoft ça devrait le faire, l'important c'est que les traductions aient du sens ;)

**Comment by SammyKrosoft** [comment]
> @SammyKrosoft ça devrait le faire, l'important c'est que les traductions aient du sens ;)

Oui, notre bon Robert m'a parlé un peu de ses déboires avec le Francais, hehe :-) Francky, connais-tu un peu le produit et pourrais-tu valider quelques unes des traductions (comme "Page Token" - "Jeton de page" ? ou encore "Array type field" - "Champ de type tableau" ?) ? Merci d'avance :-)

**Comment by FranckyC** [comment]
Haha @SammyKrosoft, if I know the solution? Well pretty much I would say ;). Just submit a PR and I will review the terms. If you plan to do translations for multiple languages, please do this is separate PRs. Thanks!

**Comment by SammyKrosoft** [comment]
> Haha @SammyKrosoft, if I know the solution? Well pretty much I would say ;). Just submit a PR and I will review the terms. If you plan to do translations for multiple languages, please do this is separate PRs. Thanks!

Excellent, I'll do this :-) I'll only do this for the language I know (French), I'll let our good Robert coordinate for the other languages ;-)

**Comment by robegoja** [comment]
Thanks @SammyKrosoft once again and @FranckyC, I am meeting with another colleague who was from Columbia and lived in Spain for a while regarding the Spanish.

**Comment by SammyKrosoft** [comment]
@FranckyC j'ai le droit de faire un PR dans ce repository ?

**Comment by FranckyC** [comment]
@SammyKrosoft you can submit a PR yes, that's how open source works ;). Doing a PR is different than commiting directly in the repo.

**Comment by SammyKrosoft** [comment]
> @SammyKrosoft you can submit a PR yes, that's how open source works ;). Doing a PR is different than commiting directly in the repo.

Ooooh got it thanks ! Apologize for asking, I'm fairly new in Open source collaboration :-) ... mostly coding Powershell code :s

**Comment by stevebeauge** [comment]
Any update regarding the french translation ?

**Comment by martincyr** [comment]
@FranckyC any plans on merge to master and perhaps even release? 
Avec autant de francophones sur le dossier, surement qu'on peut faire avancer ça.
Si il y a besoin de revision linguistique, ou que je regarde quelque chose, juste me le laisser savoir.

**Comment by FranckyC** [comment]
@martincyr No ETA yet for the next version but you can still build from the develop branch. Pour la révision linguistique, simplement revoir les fichier fr-fr.js si possible. Merci!

**Comment by wobba** [comment]
I will try to get a version out this week.

**Comment by Mcdga** [comment]
Hello, we are testing "PnP - Search Results" and "PnP - Search Filters" with
"PnP Modern Search (v4)" and we have the same problems you report with the French language. Don't forget the term "44 **Results for** *" is not translated in webpart "PnP - Search Results" when configuring the results count :
![ImpossibleToSetFrench](https://user-images.githubusercontent.com/25668196/120788823-c6bdd900-c4fe-11eb-8c3a-2137072cbaa6.JPG)

It is not possible to configure French in the "PnP - Search Results" web part. The configuration does not apply.
![ImpossibleToSetFrench](https://user-images.githubusercontent.com/25668196/120788493-675fc900-c4fe-11eb-83e5-004826300358.JPG).

Are you going to produce a 4.1 version to solve these issues?  Please keep us informed as soon as the update is ready.

**Comment by wobba** [comment]
4.2.2 is out.
![image](https://user-images.githubusercontent.com/51104/120792613-14a20380-c536-11eb-95bf-ae24dfcfe109.png)
