### ISSUE TITLE
Instant search filter in multiselect filters without clicking Apply

### ISSUE THREAD

**Issue by jensotto** [microsoft-search/pnp-modern-search#779]
**Describe the solution you'd like**
When a multiselect filter is used you are required to click the Apply link after the filters are selected. Would it be possible to filter the search result immediately after selecting a filter element even in multi select filters? It's often not clear to the user that this needs to be done, and it's an extra step that feels unnecessary, especially when similar filtering in a modern library is instant without the need of clicking an apply button.

**Additional context**
![image](https://user-images.githubusercontent.com/13898671/108205668-acb1e380-7125-11eb-81c1-45f1541f8859.png)

**Comment by wobba** [comment]
The issue is a bit technical related. If you click one value, and the control rebinds, should you then remove values? State becomes a challenge. It's not unsolvable, just more tricky. And we accept PR's :)
