### ISSUE TITLE
v3.15 search filters with panel layout not displayed with the same order as configured 

### ISSUE THREAD

**Issue by naufalCA** [microsoft-search/pnp-modern-search#780]
**Version used**
Ex: 3.15

**Describe the bug**
After configuring the Modern Search WebParts in the search results page (Verticals, Filters and Results WebParts), I've realized that in case of the Search Filters WebPart it does not take into consideration the defined refiners orders set during the WebPart configuration.  

**To Reproduce**

1. Edit search results page
2. Edit refiners webpart 
3. Select Panel layout
4. Click in "Edit refiners" button in the property pane
5. Add refiners (screenshot 1)
6. Save as draft
7. Make a search
8. open filters pane (screenshot 2)

**Expected behavior**
Display the refiners with the same order as the specified during the WebPart configuration

**Comment by naufalCA** [comment]
@wobba @FranckyC I appreciate your help with this issue

**Comment by wobba** [comment]
@naufalCA fixed in #470 from v3.15.3 and onwards. Can you verify your version or try with the latest?

**Comment by naufalCA** [comment]
> @naufalCA fixed in #470 from v3.15.3 and onwards. Can you verify your version or try with the latest?

@wobba I've v3.15.1 installed I'll try to install the 3.15.3. Much appreciated

**Comment by naufalCA** [comment]
@wobba we have just installed the v3.17 and it has solved the issue. Many thanks for your support much appreciated!!
