### ISSUE TITLE
v4 Filter panel not showing any filters

### ISSUE THREAD

**Issue by Lucho999** [microsoft-search/pnp-modern-search#781]
**Version used**
4.0.0.0

**Describe the bug**
In the filter webpart, when choosing the Panel layout no filters are showing up when

**To Reproduce**

**Expected behavior**
That the filter fields that are shown in the other layout options are shown in panel layout aswell.

 - Browser  chrome

**Comment by wobba** [comment]
Duplicate of #698 and will be part of the next release.
