### ISSUE TITLE
Question: Availability

### ISSUE THREAD

**Issue by PikeSal** [microsoft-search/pnp-modern-search#782]
Since these webparts come with a disclaimer on github, what happens when MS decides to push an update which could possibly break the search webpart. As a consumer of these webparts I would like to know how to go about ensuring I have a stable search implementation which would not break due to an update.

**Comment by wobba** [comment]
The web parts are built on SPFx which is well supported on the UX side. API wise they are using public API's which there are no plans to stop support for. So, any version of these web parts you install should continue to work for as long as SharePoint lives and support people building on top of it.

Which disclaimer are you thinking about? Maybe we need to improve on wording.

**Comment by FranckyC** [comment]
As @wobba said these Web Part are built on top of SPFx and native APIs, which are actively supported by MS. However, these are also open source Web Parts and not maintaned by Microsoft directly. Knowing that, there is no guarantee a new version will not break existing configurations. Of course we try to avoid that but remember we do this on our own time for most part just like other PnP initiatives.

**Comment by wobba** [comment]
The web parts are used by quite a number of of companies - and they are acknowledged inside of Microsoft. Even been on our official roadmap slides 🙂 The fact that we host them on the Microsoft Search github org should speak to that we (Microsoft) take them seriously.

**Comment by PikeSal** [comment]
> The web parts are built on SPFx which is well supported on the UX side. API wise they are using public API's which there are no plans to stop support for. So, any version of these web parts you install should continue to work for as long as SharePoint lives and support people building on top of it.
> 
> Which disclaimer are you thinking about? Maybe we need to improve on wording.

Thanks @wobba @FranckyC , appreciate the feedback and effort put into building these amazing web parts.

I was referring to the below disclaimer,
Disclaimer
THIS CODE IS PROVIDED AS IS WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.

**Comment by wobba** [comment]
@PikeSal that is normal text for an open source project. The developers/contributors/github project don't take any responsibility for the code in case it somehow causes you harm. This means, no SLA etc. But the code is there for anyone to scrutinize. It's more if you want to tap into the goodness of open source, or want to pay someone to re-create the parts with a support agreement. It's not uncommon for companies to provide support on open source projects either.

The code is more than production ready, we do look at bugs when logged, but we release and work on it when we have time - or when others contribute. And it's open for any developer to help out.
