### ISSUE TITLE
@pnp/modern-search-extensibility not in npm

### ISSUE THREAD

**Issue by MakingThingsWorkToronto** [microsoft-search/pnp-modern-search#783]
**Version used**
Ex: 4 -> 4.0.0.0

**Describe the bug**
npm install fails with "npm 404 - Not found error" on @pnp/modern-search-extensibility.

**To Reproduce**
Clone latest version of v4 into empty directory. run npm install on the search-parts solution.

**Expected behavior**
npm install should function by design with either of the below changes being acceptable:
a) extensibility package made public in npm
b) @pnp/modern-search-extensibility be removed from "package.json dependencies" falling back to "npm link @pnp/modern-search-extensibility" to bake your own build.

**Desktop (please complete the following information):**
Windows 10, Visual Studio Code

**Additional context**
Not pushing a PR as it is unclear if you're planning on adding the extensibility solution to npm.

**Comment by FranckyC** [comment]
Hi @MakingThingsWorkToronto, we don't plan to move the extensibility library to npm. Not a technical issue (as it would be better imo) but more organizational (who is the owner, who can contribute, bla bla). Also, as stated in the SPFx library component documentation: 

> npm install will throw an error if you create a web part and you just added a reference to package.json and don't create a local reference using npm link. If you have created a link using npm link and run npm install, you will not receive an error during npm install but the symbolic link will be removed. If you want to run npm install, you will have to temporarily remove the reference to the corporate library and re-establish the reference by running npm link corporate-library and update the reference in package.json.

May the documentation can be improved on this point. Feel free to PR ;).

**Comment by MakingThingsWorkToronto** [comment]
@FranckyC - this doesn't imply that the linked library should be included in the dependencies section of package.json. If it is, npm install will throw an error. The npm link @pnp/modern-search-extensibility command adds the symbolic link required for the solution to build.

**Comment by MakingThingsWorkToronto** [comment]
To clarify, @pnp/modern-search-extensibility need not be included in the dependencies node as it's the symbolic link is what's creating the reference.

**Comment by wobba** [comment]
I'll check if we can host it via the PnP npm. Libraries are weird in a way as you need it for building, but deploy it separate. And we just mimic the official tutorial https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial 

I think a better approach is if we can add the steps needed as check tasks in the gulp file. To automate things.

**Comment by MakingThingsWorkToronto** [comment]
This "library" is being used as a shared dependency to support extensibility projects. It is not leveraging the documented SpFx library pattern. Hence npm would be the best practice. Alternatively, use it as a development library by removing from dependencies & building using the npm symbolic link. Additionally, I've not had to install the extensibility package in SharePoint for v4 to work properly (but I also removed the dependency line b4 building). There are no concrete classes in there, nothing is being consumed, so the "SpFx limitation" doesn't add up. I did note the documentation / issues... Is there any additional meta on that?

**Comment by MakingThingsWorkToronto** [comment]
Also, just to clarify,I am referring to the @pnp/modern-search-extensibility library, not a consumable third party library which does use the SpFx library pattern.

**Comment by wobba** [comment]
@MakingThingsWorkToronto Either way, you original issue is not a bug, as you didn't follow the docs. It's also a duplicate issue as others have ran into the same of not reading the docs first 😉

I'm all for making it smoother as the lib contains base classes and interfaces. I guess depending on what you use or not it works without the lib installed. I'll see if we can get it in as an @pnp/ package on npm.

**Comment by wobba** [comment]
@MakingThingsWorkToronto npm it is...will let you know when.
