### ISSUE TITLE
Getting intermittent error: "Cannot read property 'RawSearchResults' of null" when search page refreshed

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#787]
**Version used**
3.17

**Describe the bug**
On the custom search page we've built using Search PNP 3.17 we've added a link to "Clear search" (link = https://domain.sharepoint.com/sites/sitename/SitePages/Search.aspx). This link reloads the page with no query text. We are occasionally getting an error when the page refreshes: "Cannot read property 'RawSearchReslts' of null. 

![image](https://user-images.githubusercontent.com/2616432/108546590-32589f00-729e-11eb-9983-5b342739671d.png)

If you click Clear search again, or refresh, it all loads properly

**To Reproduce**
1. Go to the custom search page.
2. Click the "Clear search" link (https://domain.sharepoint.com/sites/sitename/SitePages/Search.aspx)
3. Sometimes, you get the error. Not very frequently, but enough that our beta group is reporting it. 

**Expected behavior**
The page refreshes with the default query shown. Default query is "*".

**Screenshots**
![image](https://user-images.githubusercontent.com/2616432/108546903-a2672500-729e-11eb-8569-ab56a998b27c.png)

**Desktop (please complete the following information):**
- Wndows 10
- Edge 88.0.705.74 

**Additional context**
We have 5 verticals configured with targeted results types for each. This normally works fine.

Thanks!

**Comment by wobba** [comment]
Added a check to remove the error, but it won't solve the possible underlying issue. I don't know how the clear link is made, but in general SPFx injects smart routing nav to links on the page.  To force a full reload you need the link to include this attribute:
`<a data-interception='off'>...</a>` as mentioned at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/hyperlinking.

The x in the search box will clear your search.

**Comment by bryllyg** [comment]
Thanks for the details. The link is simply an on page link in a Text web part, so unfortunately I can't add the data-interception setting. Thanks for adding the null check. much appreciated.

In regards to the X clearing the search, it clears the text in the search box, but does not clear the page. This may be purely a testing based problem, but our test group was finding it confusing not to be able to set the query back to it's default (*), so I added the Clear Search link.

**Comment by wobba** [comment]
I didn't test with a default * query for the X part and will take a look.

**Comment by wobba** [comment]
I haven't been able to reproduce the error (only tested after my null check). I'll close for now and you can re-open if it's an issue with v3.18 (once released).
