### ISSUE TITLE
Filter webparts not dynamically rendering with absent values when switching vertical tabs - PROPOSED FIX

### ISSUE THREAD

**Issue by DA-Mena** [microsoft-search/pnp-modern-search#788]
**Version used**
V4

**Describe the bug**
When utilizing all three dynamic webparts (filters, verticals, results), having multiple filter webparts will not dynamically hide with their respective search webpart when changing the search vertiacals webpart. It works fine in edit mode but not in display mode

**To Reproduce**
provision at least 2 filter/results webpart and one search vertical wp on the page.

map the results wp to the filters wp and vice versa. Make search query default some results using wildcard (*) if you dont want to utilize the search box. Configure filters wp to at least show a common filterable managed property.

map the results wp to a unique search vert tab.

As multiple search wp produce their search results, switching between them via the verticals wp will work but the filters wp will not behave the same and remain active.

**Expected behavior**
filters wp should hide with their respective results wp

**Additional context**

I found the issue on SearchResultsWebPart.ts line 428

renderRootElement = null;

Proposed

renderRootElement = React.createElement('div', {}, null, renderRootElement);

It seems ReactDom.render(renderRootElement, this.domElement); will not overwrite anchor's contents if the argument is null

**Comment by wobba** [comment]
I'm guessing when you change the vertical, the result wp being empty is then not triggering the attached filter wp to clear itself. Does that sound about correct? And if so, we should be able to trigger a clear.

That said, using multiple result and filter wp's with one vertical wp is stretching the intended design a bit. What you really want is to define a set of filters per vertical is my guess. And you can solve different rendering per vertical using result types.

**Comment by DA-Mena** [comment]
The behavior is not consistent when viewing between Edit and Display mode. The results in the filter wp clear in edit mode but not in display mode.

I was using the vertical wp to switch between result sources and already using custom renders by result type in the results wp. I don’t want to define all refinable fields into one filter wp because with each search result source there’s a specific order and view that goes to these sources per my project’s requirements.

“What you really want is to define a set of filters per vertical is my guess“. Last I checked, the filter wp only dynamically listens to a results wp and results wp is the only wp to listen to verticals so I might not be understanding your suggestion.

**Comment by FranckyC** [comment]
Hi @DA-Mena, in the current implemention, the filter WP doesn't have any connection with the verticals WP. Like @wobba said, what you want is either to be able to show/hide a specific filter according to a selected vertical OR an option to hide the filter WP if the connected search results WP have no result. We could add it to the backlog but there is no eaasy way currently to do that.

However, you can try to connect only one filter WP to many search results. This way, filters will display/hide according the current results. This will works even if search results WPs share the same filters.

**Comment by DA-Mena** [comment]
@wobba ,@FranckyC, I’ve made my own edit on v4 release source and satisfied with it and I thought I could point out the bug.

The suggestions made here are going against what I’m trying to achieve with my project but thanks for responding.

**Comment by FranckyC** [comment]
@DA-Mena can we close this one then?

**Comment by wobba** [comment]
@DA-Mena can you share your change? We can always add the change. My point was to understand your scenario, not to say we don't want to make it work like this.

**Comment by DA-Mena** [comment]
<img width="350" alt="v4search filter issue" src="https://user-images.githubusercontent.com/9761338/108753359-a307f180-7512-11eb-9c54-e36c842b86e7.png">
This is the issue explained visually, @wobba 

It is just a mere line change as noted in the original post

**Comment by DA-Mena** [comment]
@wobba, here's with what I went with, make the irrelevant filters to clear:
```typescript
export default class SearchResultsWebPart extends BaseWebPart<ISearchResultsWebPartProps> implements IDynamicDataCallables {
  ...
  /**
   * Track if previously matched, helps with multiple filters/results WPs
  */
  private _matchedVerticalKey: boolean = false;
  ...
  protected renderCompleted(): void {
  ...
      if (verticalData && verticalData.selectedVertical.key !== this.properties.selectedVerticalKey) {

          ...
        } else {
          ...

          if(this._matchedVerticalKey) {
            this.context.dynamicDataSourceManager.notifyPropertyChanged(ComponentType.SearchResults);
            this._matchedVerticalKey = false;
          }

          ...
        }

      } else {
        this._matchedVerticalKey = true;

        ...
      }
  ...
}
```
