### ISSUE TITLE
Are pnp-filter-multi / custom handlebars helper not available in custom templates?

### ISSUE THREAD

**Issue by MakingThingsWorkToronto** [microsoft-search/pnp-modern-search#794]
**Version used**
Ex: 4.0.0.0 > Develop

**Describe the bug**
This may be more of a question. When leveraging the custom filter layout, with a multi value filter, the pnp-filter-multi web component is not rendering.  Additionally, custom handlebars helpers added via results web part extensibility are not available in the template. Is this by design?

**To Reproduce**
Add search results web part.  Add v4 extensibility library with custom handlebars helpers.

Add filter web part and connect.  Add filter property with multi values. Change filter layout to custom.  
- Note the pnp-filter-multi web component is missing on the filter.

Modify custom layout to add custom handlebars helper, note missing helper error in console .

**Expected behavior**
Not sure what the expected behavior is on these.

**Desktop (please complete the following information):**
 - Chrome.

**Comment by MakingThingsWorkToronto** [comment]
Wanted to add, end user experience positive. See a marked improvement in rendering speed. @wobba @FranckyC very nicely done :) Just hoping for clarification on purpose.... thanks for everything you've created!!!

**Comment by wobba** [comment]
Can you explain a bit more? I see the `<pnp-filtermultiselect>` (assuming that's the one you refer to?) is used in collapsible footer, but have no idea what it does. If it renders in the oob templates, then picking one of these, then clicking `{}` to customize should copy the existing template in as basis.

**Comment by MakingThingsWorkToronto** [comment]
The issue I'm seeing is custom handlebars helpers are not available in the refiner templates.  Additionally, the pnp-filter-multi, does not render within a custom filter template. I'd imagine an order of operations issue.

As I understand the v4 architecture should include all helpers & web components on the page when referenced/included in the Results web part settings. Making them available via the singular template service to every component on the page.

It would be useful to understand a priority, as it exists by design, to have these accessible within whatever template is on the page.

**Comment by wobba** [comment]
Believe this should work now.
