### ISSUE TITLE
Link directly to a specific vertical - feature request? Or am I just missing something?

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#795]
**Is your feature request related to a problem? Please describe.**
I would like to be able to send users directly to a specific search vertical, but can find no way to do so. Am I just missing something? Or is this not possible?

**Describe the solution you'd like**
I have 5 verticals. I would like to have a link on the results card of one vertical that includes a link to another tab, with a pre-defined filter targeted to that second vertical. 

**Describe alternatives you've considered**
Looked through the documentation and searched the boards. I was unable to find anything relating to this funcationality. 

I've considered creating pages for each of the verticals and using urls to link them, but that would greatly increase the amount of upkeep I would need to do. Particularly since we are using the synonyms feature, so i would need to update any changes to synonyms on each of the 5 pages (verticals) ugh! 

**Additional context**

**Comment by wobba** [comment]
v3 or v4?

**Comment by bryllyg** [comment]
Sorry, V3.17

**Comment by wobba** [comment]
See this comment https://github.com/microsoft-search/pnp-modern-search/issues/391#issuecomment-660951641
I see we have potential for updating the docs here. Does this help?

**Comment by bryllyg** [comment]
YES! Thank you! That is exactly what I was looking for.

**Comment by umaknow-lp** [comment]
What about for V4?

**Comment by wobba** [comment]
@umaknow-lp it's a feature request for someone to implement #732

**Comment by umaknow-lp** [comment]
Thank you! Will look forward to when its implemented.
