### ISSUE TITLE
How to show filters/ refiners for APIs other than Search API

### ISSUE THREAD

**Issue by Naveen-Rangarajan** [microsoft-search/pnp-modern-search#796]
Hi Team,

I have added a vertical which does not use Search API. What I have done is, on click of that vertical, the results will be fetched from a specific list. 

Background of why I fetch from a specific list is that it has a plain multi-line text field where data is stored in JSON Format and I need to parse it twice to get the actual data and show it in the Search Results Container with UI using display template.

I was to able to retrieve the list data, parse the column data and show all the results. But since I cannot have refiners, it is showing empty.

Now how do we show the filter/ refiners for APIs other than Search API
<img width="630" alt="Filter for Custom API Results" src="https://user-images.githubusercontent.com/61411651/108850520-784c9480-7609-11eb-8f03-41c3024a2370.png">

**Comment by wobba** [comment]
@Naveen-Rangarajan you would need to implement some logic to pass the data via dynamic data to the filter webpart based on your logic. The web parts are not really built to support multiple backends and full flexibility like this.

I would rather try to index the data, and create a custom web component to handle the JSON decoding and rendering per item.
