### ISSUE TITLE
Link to list item and containing site

### ISSUE THREAD

**Issue by sympmarc** [microsoft-search/pnp-modern-search#797]
**Is your feature request related to a problem? Please describe.**

This may be a bug, but I wasn't sure, so I figured I'd start here.

**Describe the solution you'd like**

I've built a search page which shows list items which meet certain criteria.  All the items are from lists built using the Task Content Type as their base.

Among other things, I'd like to be able to have:
* The item `Title` link to the item itself (no surprise there), and
* The `SiteName` link to the containing site. I have a Managed Property mapped to `ows_SiteName`, so I easily have the site's name.

**Describe alternatives you've considered**

I'm using v4 and I have a centrally managed Handlebars template, which works great. (Love that we can do this now!) I'm trying to use these two properties for my links:
* `Path` for the item `Title`. This value takes the form `https://[tenantname].sharepoint.com/sites/DG-PA-1149/Lists/TaskManagement/DispForm.aspx?ID=2`. Unfortunately, this opens the item in a classic page. I think this is due to using the Task Content Type.
* `SitePath` for the `SiteName` link. This value seems off to me. They all look like this: `https://[tenantname].sharepoint.com/sites/dg-pa-1149/lists/taskmanagement/dispform.aspx?id=2/;com.sharepoint.[tenantname]./sites/dg-pa-1149/lists/taskmanagement/dispform.aspx?id=2/`

Any thoughts on how best to do this? Is the `SitePath` value a bug? It looks like that is what is coming back from `postquery`. I've looked at all of the other Url-like properties, and I don't see anything else I can use.

**Comment by wobba** [comment]
* The `SiteTitle` mp already has the site name for all items, so no need to re-map 😉
* How SharePoint treats the DispForm.aspx URL's for rendering is unrelated to search, and agree there's no good reason for the Task CT to be treated this way.
* `SitePath` has the correct value and is used internally for some scenario's and not really useful for people building on search

**Comment by sympmarc** [comment]
Sad monkey. How would you suggest linking back to the containing site if not SitePath?

**Comment by wobba** [comment]
@sympmarc `SPSiteURL` or `ParentLink`

**Comment by sympmarc** [comment]
I truly don't know how I missed `SPSiteUrl` before. Doh!

`ParentLink` is a link to the containing list, not the containing site:
`https://[tenantname].sharepoint.com/sites/DG-PA-1149/Lists/TaskManagement/AllItems.aspx`
Makes sense, but different purpose.

Oh, and `SiteTitle` isn't refinable, so I need to map it to a RefinableStringxx mp to use it as a refiner.

**Comment by wobba** [comment]
For refinable I get it 👍 And I know `ParentLink` has the lis - but that's on the site as well. Depends on where you want to land 🙂  If you play with subsites you can also use `SPWebUrl`.
