### ISSUE TITLE
Metadata not being displayed in search results from associated sites

### ISSUE THREAD

**Issue by denhosi1** [microsoft-search/pnp-modern-search#798]
**Version used**
Ex: Using three webparts that are all version 4.0.0
- PnP - Search Box
- PnP - Search Filters
- Pnp - Search Results

**Describe the bug**
I have created a search page on a hub site that I have added the three webparts listed above to. I have set up some filters linked to managed properties and set up a result source to connect the search results web part to. The result source has the following query (modified to exclude sensitive data).

{searchTerms} Path:https://[TENANT NAME].sharepoint.com/sites/[HUB SITE NAME]* Path:https://[TENANT NAME].sharepoint.com/sites/[ASSOCIATED SITE NAME]*

 When I do a search that I know will return one document from the hub site and one document from the associated site this works fine. Both documents are returned. However; the metadata linked to the hub site result is displayed but the metadata for the associated site search result is not displayed. This causes the filters to not work correctly.

I have also tried adding the PnP modern search webparts to a page in the associated site itself and get the same issue.

**To Reproduce**
1. Add the PnP modern search web parts to a hub site with at least one associated site
2. Configure the filters on the Search Filters webpart (ensure the filters match metadata that will match a document on the hub site and a document on the associated site) 
3. Add a result source that will only return results from the hub site and the associated site.
4. Add the columns to the search results webpart that will display the metadata of your document
5. Ensure a document exists on the hub site and has metadata that matches your search filters
6. Ensure a document exists on the associated site and has metadata that matches your search filters (name the document similar to the document on the hub site to ensure they come back in the same search)
7. Wait for the crawl to run so these documents are included in the search results
8. Re-index both sites.
9. Navigate to the search page and perform a search for the document on the hub site.
10. You will see the associated site document has no metadata. If the hub site document is also returned in the search results then this will have metadata displayed.

**Expected behavior**
No matter where the document is returned from, whether it be a hub site or associated site, any metadata that is attached to the document should also be returned and visible in the search results. The search filters should be able to filter on the metadata for  search results from an associated site.

**Screenshots**

Search Page with webparts showing two documents. The one with metadata is from the hub site and the one without metadata is from the site associated to the hub.

![image](https://user-images.githubusercontent.com/8766267/108926068-8c90a000-76a2-11eb-8bbd-65eda0d8b850.png)

Screenshot of associated sites document library that contains the document returned in the search results. As you can see there is metadata attached to the document. 

![image](https://user-images.githubusercontent.com/8766267/108924850-5eaa5c00-76a0-11eb-8feb-a863b938b667.png)

**Desktop (please complete the following information):**
 - Browser Chrome Version 88.0.4324.182

**Additional context**
When I perform a search in modern or classic search on any of the metadata for any document in a hub site or associated site the expected document is returned in the results.

**Comment by wobba** [comment]
Point 4, did you do schema mapping on the tenant level, or on all sites where the content resides? And you know you can use `DepartmentId:{guid}` instead of path https://microsoft-search.github.io/pnp-modern-search/usage/search-results/tokens/#supported-tokens-all-data-sources  (there's a bug #759 pending to make this easier as well).

**Comment by denhosi1** [comment]
Hi @wobba thank you for your reply. I did my schema mapping at the hub site level which should trickle down to all associated sites correct? Unable to do it at the associated site level as it is linked to the hub site schema settings. I didn't want to do the search schema mapping at the tenant level as we have a lot of unrelated hub sites that don't need the managed properties setup there.

 Screenshot below shows the hub sites managed properties configuration.

![image](https://user-images.githubusercontent.com/8766267/109054760-20b24400-7743-11eb-9bda-b862288099ee.png)

And the screenshot below shows the search results webpart column config.

![image](https://user-images.githubusercontent.com/8766267/109054894-51927900-7743-11eb-940d-f0a6b8067356.png)

Thank you for sharing the link to the supported tokens documentation. Don't fully understand them yet so will need to do some more reading and experimentation to see if they will help. The reason I used path in my result source was to restrict search results to only results from the hub site and any associated sites.

Is the metadata not showing up for associated sites related to my config and misunderstanding of how the webparts work or is it an issue with the webparts?

Thank you in advance.

**Comment by wobba** [comment]
1. Mapping must occur on the site where the content is or global
2. Site level mapping "overwrite" tenant level mappings
3. You can query and retrieve the value from anywhere as the index item is global

Remember that a hub hierarchy is not a real one, it's just by association. Also see https://www.techmikael.com/2016/02/search-schema-mapping-level-explained.html
