### ISSUE TITLE
PnP Modern Search WPs (Version V3 -3.17.0) | Promoted results (query rules) are not visible if relevant results are not available.

### ISSUE THREAD

**Issue by ArzooCamd** [microsoft-search/pnp-modern-search#799]
•	According to the article provided web part supports best bet results (Query rules/promoted results) –
o	For us the search results web part is returning promoted results only from the same site collection, not from the tenant Query rules.
o	Is there any limitation to this functionality?

**Comment by wobba** [comment]
@ArzooCamd not really. Check the response on the call in the network tab, and you can see what is returned. Or use the debug template. First detect if it's a data issue as you don't share details of the setup, if data is coming back, then it's a matter of getting the handlebar template correct to render them all.

See https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/templating/#accessing-items and the "Simple list" template should have placeholder for rendering these.

**Comment by ArzooCamd** [comment]
@wobba  I observed the code by debugging & logging the code in the console. 

Promoted results (SpecialTermResults) were logging but not displaying in the UI Even if we write 

{{#each promotedResults as |promotedResult|}}
  <div>
    {{Title}}
    ...
  </div>
{{/each}}

outside of the {{#if @root.hasPrimaryOrSecondaryResults}}  condition.

Could you please me in this?

**Comment by wobba** [comment]
I have two promoted results, one on tenant and one on the site. I enable query rules in the part, pick the simple list layout and both render just fine triggering on the term I picked.

![image](https://user-images.githubusercontent.com/51104/109018562-85748c80-76b8-11eb-8818-4f60bed32ba8.png)

If you first pick the simple list layout, then click the  `{}` under `Edit template` it will take that simple list layout as your starting point. If you pick the debug template you can see `promotedResults` as well.

![image](https://user-images.githubusercontent.com/51104/109019089-f4ea7c00-76b8-11eb-8602-6c3d941e4e7d.png)

**Comment by ArzooCamd** [comment]
@wobba 

The query rule is enabled and promoted results are visible on the debug template but not in the custom or simple list layout.

It happens when the search keyword is not present in the primary results.

Please see the snippets below

![image](https://user-images.githubusercontent.com/63994838/109119638-fa080380-776a-11eb-951b-a220ca3a9351.png)

![Screenshot 2021-02-25 131328](https://user-images.githubusercontent.com/63994838/109119890-46534380-776b-11eb-8ff2-98936cf79784.png)

![Screenshot2](https://user-images.githubusercontent.com/63994838/109120051-78fd3c00-776b-11eb-9c17-3ac4130e6000.png)

Thanks in advance!!

**Comment by wobba** [comment]
Got it. Seems to be a bug in `hasPrimaryOrSecondaryResults` as it says false and not true.

**Comment by wobba** [comment]
Pushed a fix for the next relase but you can solve it by moving the `check and loop on `promotedRestults outside the `hasPrimaryOrSecondaryResults` check.

**Comment by ArzooCamd** [comment]
@wobba Still not able to see promoted results even after applying the latest condition you pushed in this file.

https://github.com/microsoft-search/pnp-modern-search/blob/3fa76c4dfe96501a1cbb91a01053c09c95633ae5/search-parts/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx

**Comment by wobba** [comment]
@ArzooCamd it's in the v318 branch.

**Comment by ArzooCamd** [comment]
@wobba  could you please provide the link for v318?

**Comment by wobba** [comment]
It's not published yet. Follow the releases and you'll see it when it ships.
