### ISSUE TITLE
Unable to filter on the current user

### ISSUE THREAD

**Issue by louiserh** [microsoft-search/pnp-modern-search#80]
Version 3.9.0.0

The query for filtering by current user does not work in the modern search webparts.

CreatedBy={User.Name}
CustomValue={User.Name}

When filtering using the highlighted content webpart this query works but it will not work in the modern search webpart

**Comment by FranckyC** [comment]
Hi @louiserh, Can you inspect the transformed query using the debug layout (the `queryModification` property) and see if it seems correct. Thanks

**Comment by stevebeauge** [comment]
The {user} tokens are supposed to be the ones handled by the search engine itselft, aren't they (https://github.com/microsoft-search/pnp-modern-search/blob/b9c9d82082e64a145c1a4b2fb26199625e9f5e67/search-parts/src/services/TokenService/TokenService.ts#L45) ? If I'm right, the query modification prop will keep this token.

**Comment by FranckyC** [comment]
Correct `{User}` tokens are handled server-side by SharePoint but you should see the final transformed query in the `queryModification` proeprty in the debug layout.

**Comment by FranckyC** [comment]
@louiserh any update on this? Can you see the query?

**Comment by louiserh** [comment]
Hi Francky, I'm not really sure how to debug the layout. Can you provide some details on what I would need to do to do this check?

Louise

**Comment by louiserh** [comment]
Hi guys, any update on how to resolved this issue

**Comment by FranckyC** [comment]
Hi @louiserh. Do you use the {User.Name} in the "Query Template" field and not the Query Text field? You can also see the query using the debug layout:

![image](https://user-images.githubusercontent.com/5659122/74241803-bef37900-4caa-11ea-86f7-0414f4e03f05.png)

**Comment by louiserh** [comment]
Hi Francky, Thanks for getting back to me. I got it working. Thank you for your time on this.
