### ISSUE TITLE
Can we display OOTB contact card/persona card on mouser hover of a user in People Template

### ISSUE THREAD

**Issue by ArzooCamd** [microsoft-search/pnp-modern-search#801]
Can we display the OOTB contact card/persona card on the mouser hover of a user in 'People' Template?

**Comment by wobba** [comment]
Not supported. Read my comments over at https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/38451154-provide-support-for-livepersonacard-in-3rd-party-s
