### ISSUE TITLE
Allow configuration of more than 50 items per page in v4

### ISSUE THREAD

**Issue by MakingThingsWorkToronto** [microsoft-search/pnp-modern-search#805]
**Is your feature request related to a problem? Please describe.**
- "Number of items per page" in v4 should be consistent with v3 (which allows up to 500 items to be returned).
- "Number of items per page" should be configurable independently of the "Show Paging" setting. If the "Show Paging" setting is "off", we cannot adjust the "Number of items per page".
- I personally find it frustrating using the sliders to configure numeric values.

**Describe the solution you'd like**
- "Number of items per page" should be 500 max.
- "Number of items per page" should be moved out of the conditional property section such that it can be modified when "Show Paging" is set to "off".
- Modify the "Number of items per page" sliders to use the PropertyFieldNumber spfx property control to provide a better UX.

**Describe alternatives you've considered**
- Fork the code.
- Submit a PR if the above is concept is acceptable.

**Comment by wobba** [comment]
I think this is a good idea. Ideally maybe change number of results to a text field as well imo.

**Comment by MakingThingsWorkToronto** [comment]
Yep. You OK if I submit a PR for this?

**Comment by wobba** [comment]
Please do.

**Comment by wobba** [comment]
Will be fixed for v4.1
