### ISSUE TITLE
MS-Icons not showing anymore

### ISSUE THREAD

**Issue by VerlindenEAM** [microsoft-search/pnp-modern-search#807]
### Check existing issues before logging new ones
I could not find it in the existing issues.

### Issues related to data mapping, e.g. SharePoint columns to crawled properties to managed properties, will be closed by default and should be asked elsewhere as it's outside the scope of this project. However if you cannot repro the issue with classic web parts, then it's ok as it relates to these web parts 🙂

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
3.16

**Describe the bug**
On all pages that have MS-ICON included, the icon is not showing anymore. Only when editing the page, the icons are shown.
Example: <a class="outlook" href="mailto:{{Title}}"><i class="ms-Icon ms-Icon--OutlookLogo16" aria-hidden="true"></i></a>

**To Reproduce**
Edit the page

**Expected behavior**
Icon should be visible when the page is published

**Screenshots**
Published mode: 
![image](https://user-images.githubusercontent.com/35732908/109121644-ccf62980-7747-11eb-8ebe-0880a7620faa.png)

In edit mode: ![image](https://user-images.githubusercontent.com/35732908/109121525-a6d08980-7747-11eb-8319-726f489fdd82.png)

**Desktop (please complete the following information):**
 - Chrome and Edge (chromium)

**Additional context**

**Comment by wobba** [comment]
@VerlindenEAM can you give repro steps? Icons can be rendered using `<pnp-fabric-icon>` as mentioned at https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/templating/#web-components

**Comment by VerlindenEAM** [comment]
Thanks, pnp-fabric-icon is working.

Didn’t notice this change before.

Can be closed

________________________________
