### ISSUE TITLE
Missing tabs in MGT person card

### ISSUE THREAD

**Issue by albegut** [microsoft-search/pnp-modern-search#809]
**Version used**
4.0.0

**Describe the bug**
If we enable the Graph Toolkit functionality the person card do not show the person cards sections. We've checked that the app has all of the required Graph permissions

**To Reproduce**
1. Configure the results web part to show people 
2. Enable Graph toolkit functionality
3. Hover un person card

**Expected behavior**
Show person card with all of the sections as the image below

**Screenshots**

Currently person card in PnP Modern Search Webparts
![CurrentPersonCard](https://user-images.githubusercontent.com/9661096/109182748-93481180-778d-11eb-8237-bc569485ca0d.JPG)

Exptected person card
![PersonCardWithAllTabs](https://user-images.githubusercontent.com/9661096/109182751-94793e80-778d-11eb-8afa-dd55094ce399.JPG)

**Comment by FranckyC** [comment]
Hi @albegut, this is due to the current MGT version used in the Web Parts, this is not the latest one. If compatbile, we will upgrade to the latest for sure. Thanks!

**Comment by randhawaryan** [comment]
Hi @FranckyC, I see the same behavior with the 4.2.3 web parts (using version 2.2.0 of @microsoft/mgt). I tried switching to mgt-spfx (related issue [1127](https://github.com/microsoft-search/pnp-modern-search/issues/1127)) and I still only see the Contact tab/section. Any idea what's missing?

**Comment by FranckyC** [comment]
@randhawaryan the UI output will likely depend on MGT library version implementation. We can't really do something about this unfortunately. I didn't test with mgt-spfx specifically but you can explore the available component parameters in the doc just in case but I doubt you change the behavior to your requirement,

**Comment by wobba** [comment]
The spfx version is just a wrapper on top of the other from what I can tell.

**Comment by randhawaryan** [comment]
I did a bit more investigation and it looks like the User.Read.All Microsoft Graph [permission ](https://docs.microsoft.com/en-us/graph/permissions-reference#delegated-permissions-72) is required to display the additional tabs on the Person Card. 
@FranckyC @wobba would you support a pull request to include this permission + related documentation updates?

**Comment by wobba** [comment]
I changed the scope from ReadBasic to Read in the dev branch - makes sense.

**Comment by HamEv** [comment]
Hi everybody, has this bug still fixed? In my case the pop up is just looking like that: 
![image](https://user-images.githubusercontent.com/61208008/133668401-867512be-efe2-421e-9ee6-198b6de1bc13.png)
and I would like to have the person card like the picture in inital post.

**Comment by wobba** [comment]
@HamEv If you deploy the August version and approve of the scopes, then I assume it should work. If not, log a new issue.
