### ISSUE TITLE
Unable to install in Sharepoint Online Site

### ISSUE THREAD

**Issue by SteveRabbit** [microsoft-search/pnp-modern-search#81]
I uploaded the package file ( pnp-modern-search-parts.sppkg ) in my app catalog at Sharepoint Online. Then I added the app to my site ( Add App ).
When I trying to insert der Webpart ( Search Box ) into my page, I get the following error messages:

[SPLoaderError.loadComponentError]:
Failed to load component "cc39324a-0913-4a5b-b77f-0b6ade7646f6" (SearchNavigationWebPart). Original error: Failed to load URL 'https://localhost:4321/lib/webparts/searchNavigation/loc/en-us.js' for resource 'SearchNavigationWebPartStrings' in component 'cc39324a-0913-4a5b-b77f-0b6ade7646f6' (SearchNavigationWebPart). There was a network problem. Make sure that you are running 'gulp serve' and you have run 'gulp trust-dev-cert'.

INNERERROR:
Failed to load URL 'https://localhost:4321/lib/webparts/searchNavigation/loc/en-us.js' for resource 'SearchNavigationWebPartStrings' in component 'cc39324a-0913-4a5b-b77f-0b6ade7646f6' (SearchNavigationWebPart). There was a network problem. Make sure that you are running 'gulp serve' and you have run 'gulp trust-dev-cert'.
CALLSTACK:
t@https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_26fecec28f9e808d5b9f022e6be1635b.js:4:53651
t@https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_26fecec28f9e808d5b9f022e6be1635b.js:20:119648
jx2P/s</e.buildErrorWithVerboseLog@https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_26fecec28f9e808d5b9f022e6be1635b.js:20:129580
jx2P/s</e.buildLoadComponentError@https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_26fecec28f9e808d5b9f022e6be1635b.js:20:125611
e/</<@https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_de-de_26fecec28f9e808d5b9f022e6be1635b.js:20:115862

**Comment by FranckyC** [comment]
It seems the loaded package is not the right one since the URL try to load from localhost. Make sure there is no other installed SPFx package overriding this one (like an app installed at the site collection level).

**Comment by mherrema** [comment]
This could very likely be a solution packaging issue as well. I've found I've had the best luck with the following commands:
```
gulp build
gulp bundle --ship
gulp package-solution --ship
```

I believe if the bundle gets missed you see similar errors as what is shown above.

**Comment by FranckyC** [comment]
Of course you can rebuild the package yourself by using @mherrema technique. usingthe master branch. However, it is weird that the package provided with the release doesn't work in your env. I've tested it on several tenants and everything works fine.

**Comment by FranckyC** [comment]
@SteveRabbit any update regarding your issue?

**Comment by SteveRabbit** [comment]
@FranckyC Hi Francky, thank you for the support, your first tip solved my Issue, I had other apps installed in my Site, after deleting them there were no errors.
