### ISSUE TITLE
Fabric icons used within custom search templates suddenly gone

### ISSUE THREAD

**Issue by spicht** [microsoft-search/pnp-modern-search#810]
**Version used**
3.17

**Describe the bug**
All my templates for search results using icons suddenly don't render the icons anymore. 
I used this `<i class="ms-Icon ms-Icon--Heart" aria-hidden="true"></i> ` syntax.

**To Reproduce**
just write a custom template and use the syntax above for rendering an icon. Worked like a charm until today.

**Expected behavior**
See screenshots provided below...

**Screenshots**
Before today: 
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/79656972/109188243-030ccb00-7793-11eb-90ea-29ed272936bd.png)

Now (have the same problem within different tenants and different version of PNP modern search)
![skill](https://user-images.githubusercontent.com/79656972/109188246-04d68e80-7793-11eb-97c1-1e1eeb68adf8.jpg)
**Desktop (please complete the following information):**
all browsers (Chrome, Edge)

**Comment by spicht** [comment]
Update --- suddenly they're back. Does anyone possibly know, what could have been the cause?

**Comment by wobba** [comment]
You never know what kind of fabric css is on the page. Icons are better solved using `<pnp-fabric-icon>` as mentioned at https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/templating/#web-components

Duplicate #807
