### ISSUE TITLE
Question: Is there any way to achieve promoted results in V4 pnp search webparts.

### ISSUE THREAD

**Issue by ManuhinSPalath** [microsoft-search/pnp-modern-search#811]
We have to use the promoted results feature in the V4 search web parts. Is there any way to achieve promoted results in V4 pnp search webparts.

**Comment by ManuhinSPalath** [comment]
Can anybody help on this question ASAP? @wobba @FranckyC @bschlintz 

Is there any way to achieve promoted results in V4 pnp search results webparts?

**Comment by wobba** [comment]
Fixed the simple list template to render promoted results in #818. Will be part of v4.1.

And we address issues when we have time. If it's urgent, you need to look at it yourself or get someone else to help out.
