### ISSUE TITLE
Question: Is PnP Search Web Part sorted by relevance?

### ISSUE THREAD

**Issue by saregbesola** [microsoft-search/pnp-modern-search#812]
My team is wondering if PnP search is sorted by relevance. Like if we leave the sort order empty in the result web part, does it sort the result by relevance? I mean does it use something like ranking score or something else to sort the result?

Thanks in anticipation.

@wobba

**Comment by wobba** [comment]
If you remove the sort orders, then it's by default relevance. The rank values are coming back in the `Rank` managed property. Switch to the debug template and you can view the data coming back.

**Comment by saregbesola** [comment]
@wobba thanks for your prompt response! well appreciated.
