### ISSUE TITLE
Sort/order by (Czech or any other) alphabet (or set locale) 

### ISSUE THREAD

**Issue by cironis-adam** [microsoft-search/pnp-modern-search#813]
**Version used**
4.0.0.0

**Describe the bug**
Is it possible to sort by (order by) alphabet (which works fine) but to specify Czech alphabet, which has specific letters in addition to English? We have built employee directory based on Locale People Results but we are unable to sort by Czech alphabet. Therefore for example letter "Č" which is after letter "C" is at the end of directory as special character. Our sharepoint site language is set to Czech, basically everything is in Czech, but not the alphabet. Not sure if the question is related to KQL as I couldn't find any resources there. Custom managed property probably can not be used as number of employees is not final.
Any help would be much appreciated.

**Desktop (please complete the following information):**
 - Chrome/Edge/Mozilla (not related to browser I suppose)

Thank you in advance,
Adam

**Comment by FranckyC** [comment]
Hi @cironis-adam , so the sort works in English for but not for Czech right? Is it a sort order problem or you get an issue when sorting by Czech alphabet? Not sure to fully understand. If it is related to results sort order without getting any error message, the problem would be related to the search engine itself I guess. @wobba any hint how the sort should behave in this situation?

**Comment by wobba** [comment]
I believe my old post which I dug up answers this https://www.techmikael.com/2015/08/how-to-do-case-insensitive-sorting-in.html 

Short answer, you can't. If it for some reason have changed, change your UX locale and see if sorting changes.

**Comment by cironis-adam** [comment]
Hi @FranckyC and @wobba! Thank you both for such a quick reply and sorry for my delayed reply.

@FranckyC: Yes, the sorting works in both languages. It doesn`t throw any error, but it actually sorts the same way altough sorting by Czech should "reorganize" the alphabet a bit. For example letter "Č" is right after "C". But in the package it looks like it sorts by English as the letter "Č" is at the end of alphabet as special character altough Sorting in Language settins of the site is set to Czech (please see the image below - it`s in Czech, but I have highlighed the part with Sorting).

<img width="1136" alt="Screenshot 2021-03-02 at 4 49 23" src="https://user-images.githubusercontent.com/2216357/109594274-c7675d80-7b12-11eb-9ac6-f9fea7a5000d.png">

@wobba Thank you. I was honestly afraid that might be true. But somehow I`m suprised that in Language settings of the site there is an option to set Sorting language. Shouldn`t that be then inherited even in the package or be able to set in KQL?

**Comment by wobba** [comment]
The oob refinablestring properties are tokenized by default. And no way to create a sortable/refinable mp with this turned off. Not much we can do unfortunately.

```
Enable to return results independent of letter casing and diacritics(for example accented characters) used in the query.
```
