### ISSUE TITLE
Search Results Display Template Image Not Displaying every second image

### ISSUE THREAD

**Issue by darrenpeat** [microsoft-search/pnp-modern-search#814]
This issue may be similar to other issues where every third image is not displayed

This issue related to the PnP search results web part not correctly displaying images

**Version used**
Ex: 4.0.0

**Describe the bug**
Modern PnP search web part does not display images properly; every second image is missing

**To Reproduce**
1.  Add a Search Box PnP web part to a new modern page (use the pages library of a comms or teams site)
2. Add a Search Results Web Part to the same page and configure as follows
3. Choose "SharePoint Search" 
4. Connect to the search box added in 1 above, pass through the query with a default query of "*"
5. Leave other settings as default
5. Publish the Page
6. In the search box type "jpeg" and then search

1. As above

**Expected behavior**
Card layout display template should show images for all search items

**Screenshots**
This is the issue every second image is missing
![image](https://user-images.githubusercontent.com/79695669/109293843-47947700-7824-11eb-8c2f-029a338e17f3.png)

**Desktop (please complete the following information):**
 - Chrome and Edge

**Additional context*
Every second images misses the AutoPreviewImageUrl field when viewed with the dubug display template

Image working example debug

"Rank":   "16.4980812",
--
"DocId": "1636571971568896056",
"Title": "image8",
"Path":   "https://bdwdevelopment.sharepoint.com/sites/ADEDemo/Southern   Division/Forms/DispForm.aspx?ID=1002",
"DefaultEncodingURL":   "https://bdwdevelopment.sharepoint.com/sites/ADEDemo/Southern%20Division/Construction/Construction%20Alerts/Construction%20Alert%2034/Cane%20Hill/image8.jpeg",
"FileType": "jpeg",
"HitHighlightedSummary": "",
"AuthorOWSUSER":   "darren.peat@bdwdevelopment.onmicrosoft.com \| Darren Peat \|   693A30232E667C6D656D626572736869707C64617272656E2E7065617440626477646576656C6F706D656E742E6F6E6D6963726F736F66742E636F6D   i:0#.f\|membership\|darren.peat@bdwdevelopment.onmicrosoft.com",
"owstaxidmetadataalltagsinfo":   "L0\|#0cd508e8a-74d8-4237-9770-c3c3c3c9d884\|Construction",
"Created": "2021-02-23T22:29:54.0000000Z",
"UniqueID":   "{9F54367B-7748-40B2-BF35-6B0EF563EF5B}",
"NormSiteID":   "219f778d-c6d2-4e06-9c6a-5ee362a9276c",
"NormListID":   "7c803333-6b83-4fc4-9c92-f04c35223a79",
"NormUniqueID":   "9f54367b-7748-40b2-bf35-6b0ef563ef5b",
"ContentTypeId":   "0x01010070EF51AFE6B45047AFAB611F0E2A8335",
"UserName": null,
"JobTitle": null,
"WorkPhone": null,
"SPSiteUrl":   "https://bdwdevelopment.sharepoint.com/sites/adedemo",
"SiteTitle": "ADE Demo",
"CreatedBy": "Darren Peat",
"SiteId": "219f778d-c6d2-4e06-9c6a-5ee362a9276c",
"WebId": "1426b349-b1cb-4091-b436-9e4b857639f6",
"contentclass": "STS_ListItem_DocumentLibrary",
"IsExternalContent": "false",
"ListId": "7c803333-6b83-4fc4-9c92-f04c35223a79",
"OriginalPath":   "https://bdwdevelopment.sharepoint.com/sites/ADEDemo/Southern   Division/Forms/DispForm.aspx?ID=1002",
"ResultTypeIdList": null,
"ResultTypeId": null,
"RenderTemplateId":   "~sitecollection/_catalogs/masterpage/Display   Templates/Search/Item_Default.js",
"piSearchResultId":   "ARIAǂ577a38a5-448d-4fcd-b9cd-6cb4891191f4ǂ92ff3c4b-b147-4a49-9fe2-6e3e14b94506ǂ577a38a5-448d-4fcd-b9cd-6cb4891191f4.1000.13ǂGBR:142760017_-1_1033:0_1",
"GeoLocationSource": "GBR",
"PartitionId":   "2ef98ce7-b31b-4cf9-a177-891e6c91cbe3",
"UrlZone": "0",
"Culture": "en-US",
"AutoPreviewUrl":   "https://bdwdevelopment.sharepoint.com/sites/ADEDemo/Southern%20Division/Construction/Construction%20Alerts/Construction%20Alert%2034/Cane%20Hill/image8.jpeg?web=1",
"AutoPreviewImageUrl":   "https://bdwdevelopment.sharepoint.com/sites/ADEDemo/_api/v2.1/sites/219f778d-c6d2-4e06-9c6a-5ee362a9276c/lists/7c803333-6b83-4fc4-9c92-f04c35223a79/items/9f54367b-7748-40b2-bf35-6b0ef563ef5b/driveItem/thumbnails/0/large/content?preferNoRedirect=true"

Image not working

"Rank":   "16.4980812",
--
"DocId": "1636571971568946051",
"Title": "image2",
"Path":   "https://bdwdevelopment.sharepoint.com/sites/ADEDemo/Southern   Division/Forms/DispForm.aspx?ID=994",
"DefaultEncodingURL":   "https://bdwdevelopment.sharepoint.com/sites/ADEDemo/Southern%20Division/Construction/Construction%20Alerts/Construction%20Alert%2034/Cane%20Hill/image2.jpeg",
"FileType": "jpeg",
"HitHighlightedSummary": "",
"AuthorOWSUSER":   "darren.peat@bdwdevelopment.onmicrosoft.com \| Darren Peat \|   693A30232E667C6D656D626572736869707C64617272656E2E7065617440626477646576656C6F706D656E742E6F6E6D6963726F736F66742E636F6D   i:0#.f\|membership\|darren.peat@bdwdevelopment.onmicrosoft.com",
"owstaxidmetadataalltagsinfo":   "L0\|#0cd508e8a-74d8-4237-9770-c3c3c3c9d884\|Construction",
"Created": "2021-02-23T22:24:32.0000000Z",
"UniqueID":   "{A7AECBD6-D7B5-49E9-917C-4A92B09F46A1}",
"NormSiteID":   "219f778d-c6d2-4e06-9c6a-5ee362a9276c",
"NormListID":   "7c803333-6b83-4fc4-9c92-f04c35223a79",
"NormUniqueID":   "a7aecbd6-d7b5-49e9-917c-4a92b09f46a1",
"ContentTypeId":   "0x01010070EF51AFE6B45047AFAB611F0E2A8335",
"UserName": null,
"JobTitle": null,
"WorkPhone": null,
"SPSiteUrl":   "https://bdwdevelopment.sharepoint.com/sites/adedemo",
"SiteTitle": "ADE Demo",
"CreatedBy": "Darren Peat",
"SiteId": "219f778d-c6d2-4e06-9c6a-5ee362a9276c",
"WebId": "1426b349-b1cb-4091-b436-9e4b857639f6",
"contentclass": "STS_ListItem_DocumentLibrary",
"IsExternalContent": "false",
"ListId": "7c803333-6b83-4fc4-9c92-f04c35223a79",
"OriginalPath":   "https://bdwdevelopment.sharepoint.com/sites/ADEDemo/Southern   Division/Forms/DispForm.aspx?ID=994",
"ResultTypeIdList": null,
"ResultTypeId": null,
"RenderTemplateId":   "~sitecollection/_catalogs/masterpage/Display   Templates/Search/Item_Default.js",
"piSearchResultId":   "ARIAǂ577a38a5-448d-4fcd-b9cd-6cb4891191f4ǂ92ff3c4b-b147-4a49-9fe2-6e3e14b94506ǂ577a38a5-448d-4fcd-b9cd-6cb4891191f4.1000.14ǂGBR:142760017_-1_1033:1_1",
"GeoLocationSource": "GBR",
"PartitionId":   "2ef98ce7-b31b-4cf9-a177-891e6c91cbe3",
"UrlZone": "0",
"Culture": "en-US",
"AutoPreviewUrl":   "https://bdwdevelopment.sharepoint.com/sites/ADEDemo/Southern%20Division/Construction/Construction%20Alerts/Construction%20Alert%2034/Cane%20Hill/image2.jpeg?web=1"

**Comment by FranckyC** [comment]
Hi @darrenpeat , already resolved in https://github.com/microsoft-search/pnp-modern-search/issues/784. You can try the `develop` branch. Thanks!
