### ISSUE TITLE
Site Collection App Catalog

### ISSUE THREAD

**Issue by Mario4272** [microsoft-search/pnp-modern-search#815]
I have a client that's deployed Site Collection level App Catalogs.  

When I install the V4 package, it deploys without issue.  I am NOT checking "Make available on all Sites"

When I deploy the V4 extensibility package.  I get 4 errors.  But when I access the errors pages I see nothing.  The page loads blank.  

I'm just curious if this is designed to be deployed this way.

**Comment by Mario4272** [comment]
Disregard

@jorisbaiutti it's a limitation of SPFx and shouldn't be an issue. Even though it's available, there are no discovery mechanisms to see that a library is available. You need to know the manifest id to load it. Which means end-users will never see a lib anyways.

**Comment by wobba** [comment]
v4.1 will remove the dep of the ext lib.
