### ISSUE TITLE
handlebars {{keywords}} is not displaying anything

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#816]
**Version used**
3.17

**Describe the bug**
I'm unsure if this is a bug or a configuration issue. I'm trying to use the {{keywords}} handlebars helper that is described under Templating (here: https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/templating/). I've added keywords to the selected properties for my Search Results web part, and to my results type template (as {{keywords}}), but no value is returned. 

**To Reproduce**
1. Add keywords to Search Results web part's Selected Properties.
2. Add {{keywords}} to results type template
3. Save
4. enter a search
5. the search key words are not shown on the results card

**Expected behavior**
I was expecting the search query terms to show up on the results card. Other custom helpers, such as {{getSummary HitHighlightedSummary}} do show on the card after a search. 

**Screenshots**

**Desktop (please complete the following information):**
Windows 10
Edge

**Additional context**
I'm first tying to just get the search query words to show up on the results card. My end goal is to insert keywords as part of a #has block, so the only items returned contain the search keywords. I have a multi lines of text field that contains ID numbers and descriptions, and I'd like to show only those items that contain the search query keywords.

Example:

		{{#each (split fieldoneOWSMTXT ";") as |inv| }}
			{{#has inv keywords}}		
				{{inv}}
			{{/has}}
		{{/each}}

Can this type of nesting even be done? It works if I hard code in a term in the #has line, but I've not been able to grab the keywords dynamically.

Thanks much!

**Comment by wobba** [comment]
`{{keywords}}` will output the end-user query. It is not related to the managed property `Keywords`. So point 1 is not needed. If you add `{{keywords}}` at the top of your template you will see it render. Also see how the OOB templates use it when display the count.

E.g.
```html
<label class="ms-fontWeight-semibold">{{getCountMessage @root.paging.totalItemsCount keywords}}</label>
```

If you are inside a loop use `{{@root.keywords}}`. Handlebars is working on objects so you need to reference the object at the right level.

**Comment by bryllyg** [comment]
Thanks. That was most helpful. I've been able to figure out how to tinker with the handlebars from there. I wasn't quite following how the data was structured.
