### ISSUE TITLE
PNP Modern Search v3.16.0 not running javascript

### ISSUE THREAD

**Issue by cajetan77** [microsoft-search/pnp-modern-search#817]
### Issues related to data mapping, e.g. SharePoint columns to crawled properties to managed properties, will be closed by default and should be asked elsewhere as it's outside the scope of this project. However if you cannot repro the issue with classic web parts, then it's ok as it relates to these web parts 🙂

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
Ex: 3.16

**Describe the bug**
While creating the search handlebar templates , a piece of js code was written to  perform toggling of element

**To Reproduce**
1. Go to 'Edit template in Search Results'
2. Click on 'Edit Template, Paste any JS Code'

3. See error
![image](https://user-images.githubusercontent.com/26503913/109407010-6d677a80-79e2-11eb-8d61-a6f6e8a611bb.png)

**Expected behavior**
The javascript to run
**Screenshots**
![image](https://user-images.githubusercontent.com/26503913/109407125-3e053d80-79e3-11eb-92d3-9ebeac0449a5.png)

**Desktop (please complete the following information):**
 -  All Browsers

**Additional context**
The same code works fine in v3.14

**Comment by FranckyC** [comment]
@cajetan77 Writing custom JS is not allowed with the PnP Modern Search, It is by design. Use the Modern Script Editor WP for this https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-script-editor#support-for-teams-tabs
