### ISSUE TITLE
People layout should show user details on click or mouse over

### ISSUE THREAD

**Issue by stevebeauge** [microsoft-search/pnp-modern-search#82]
**Is your feature request related to a problem? Please describe.**

The result search WebPar may be use to build company directory. The oob people layout template is built for displaying such results.

However, there's no "more details" or similar button to see profile information regarding the user. The classic search result webpart is a lot more usable, because of the shown callout.

It would be a huge improvement to mimic this behavior.

**Describe the solution you'd like**

The ideal solution (in my sense should be to reuse the same behavior that user click in list view).

This pops up a callout with all required information. However, I've read somewhere that MS doesn't allow reusing such component (in #27).

**Describe alternatives you've considered**

As an alternative, the result container should be clickable, with the user's delve profile page as default.

**Additional context**

Related issues : 

* https://github.com/SharePoint/sp-dev-solutions/issues/358
* https://github.com/microsoft-search/pnp-modern-search/issues/27

**Comment by stevebeauge** [comment]
Maybe [this](https://docs.microsoft.com/en-us/graph/toolkit/components/person-card) may help

**Comment by FranckyC** [comment]
@stevebeauge Technically this feature is already here but we are not allowed to use the builtin component (Live Persona). Your suggestion to use the MSGraph Toolkit is cool. I will see how it can be integrated in the solution.

**Comment by stevebeauge** [comment]
the drawbakc of the mgt is that you will require additional permissions. Don't know the implications.

**Comment by FranckyC** [comment]
@stevebeauge In this case, you can use Office 365 CLI to add the correct MSGraph permissions. No need to update the SPFx solution for that.

**Comment by stevebeauge** [comment]
Beware of the [browser support of the MGT](https://docs.microsoft.com/en-us/graph/toolkit/overview#browser-support).

Unfortunately, there are still customers with IE 10 or worse :(

**Comment by FranckyC** [comment]
@stevebeauge We don't support IE10 anyway.

**Comment by wobba** [comment]
Implemented using mgt.
