### ISSUE TITLE
person card doesn't displayed on hover

### ISSUE THREAD

**Issue by Kaldrim** [microsoft-search/pnp-modern-search#821]
**Version used**
4.0.0

**Describe the bug**
The person card is not displayed when hover on person card

**To Reproduce**
1. Configure the results web part to show people
2. Enable Graph toolkit functionality
3. Hover on person card

**Expected behavior**
Show the person card

**Screenshots**
I can see a error on the graph request: Error ApplicationThrottled
![error](https://user-images.githubusercontent.com/59488016/109516805-e92bfa80-7aa8-11eb-97bc-291e9cb1ff65.jpg)

**Desktop (please complete the following information):**
 - Browser: chrome

**Comment by wobba** [comment]
Did you approve the needed scopes as per https://microsoft-search.github.io/pnp-modern-search/installation/?

**Comment by Kaldrim** [comment]
> Did you approve the needed scopes as per https://microsoft-search.github.io/pnp-modern-search/installation/?

Yes

**Comment by wobba** [comment]
Ah...you're getting throttled. That's an API and toolkit issue, not search web part issue. You can find info on the error on the web.
