### ISSUE TITLE
Dynamic Pagination and sorting controls for page size and sort by

### ISSUE THREAD

**Issue by ishaisagi** [microsoft-search/pnp-modern-search#822]
**Is your feature request related to a problem? Please describe.**
I have a requirement to let the user specify in run time (after searching) the page size and the sort by.

**Describe the solution you'd like**

1. A new web part property for "allow user to change page size". If set, the user gets a "results per page" dropdown that offers options of 10, 20, 30, 40, 50,100
2. A new web part property for "allow user to change the sort order". If set, the user gets a "sort by" dropdown that allows changing from "most relevant" as the default to a specific field (allow selection of fields to show the user). If a sort order was specified in the existing sort options, make that sort order the default instead of "most relevant"

**Additional context**
![paging](https://user-images.githubusercontent.com/32532384/109586985-65cae180-7b5a-11eb-94ea-f0f2136fd2a4.jpg)

**Comment by Ofer-Gal** [comment]
Yes this is even better. Please add.

**Comment by wobba** [comment]
Sorting is now added in the dev branch for v4. Would be good if people would test it out.

**Comment by taliamath** [comment]
I also need the user to be able to sort results dynamically. Thumbs up twice for expediting finalization of this feature.

**Comment by wobba** [comment]
@FranckyC sorting should be in right?

**Comment by wobba** [comment]
Closing as sorting is available for the list template.
