### ISSUE TITLE
Empty search box, still results in entries

### ISSUE THREAD

**Issue by asadrajput** [microsoft-search/pnp-modern-search#826]
Hi
When we have the search results webpart set to "Hide this web part if there's nothing to show" and nothing is in search box, it still results in entries in search results. In V3 it used to be empty unless we write a query. How can we achieve this in v4? Thanks

**Comment by asadrajput** [comment]
![Capture1](https://user-images.githubusercontent.com/24537830/109733041-6fb01b80-7c12-11eb-902b-73db7316acff.JPG)

**Comment by asadrajput** [comment]
V3

![Capture2](https://user-images.githubusercontent.com/24537830/109733104-979f7f00-7c12-11eb-81f8-efe8fe3763bd.JPG)

**Comment by ghazifazalabbas** [comment]
Hi, I am also facing the same issue, when I load the search page with PnP v4 web parts, search results are shown without any refiners applied or search query entered in search box. 
Moderators and contributors, can you please help us with this.

**Comment by eoverfield** [comment]
You might want to check your query, and/or could you provide that here for review?

as an example, if you had a query such as:

`{?{searchTerms}} path:"https://mytenant.sharepoint.com/sites/portal/sitepages" `

then even without searchTerms being supplied by the search box webpart, results will appear. if this where changed to:

`{{searchTerms}} path:"https://mytenant.sharepoint.com/sites/portal/sitepages"`

then no results would appear until searchTerms was provided by the search box webpart. All assuming you have properly tied the results webpart to the search box webpart.

**Comment by wobba** [comment]
@asadrajput please reformat your ask with the bug template, providing full repro steps of web part config. If not we'll close the issue.

**Comment by asadrajput** [comment]
Hi All
Thanks to @eoverfield , {{searchTerms}} sis the trick as I was filtering for specific sites.
cheers
