### ISSUE TITLE
Limiting Search Scope

### ISSUE THREAD

**Issue by Mr-Clrscr** [microsoft-search/pnp-modern-search#828]
**Version used**
Ex: 3

**Describe the bug**
I've been limiting the search scope to site collection as "{searchTerms} Path:{SiteCollection}", it is working fine but for some cases like when we enter "(" or ")" symbols in searchbox, the search results web part is fetching all the results over the tenant

**To Reproduce**
1. Go to search result's webpart
2. Go to Query template, place this "{searchTerms} Path:{SiteCollection}"
3. Go to search box enter "("
4. and see the search results giving entire tenant results

**Expected behavior**
it should only retrieve the results within site collection.

**Comment by wobba** [comment]
We cannot really validate the KQL as it's a bit complex. A better way to set up your template is:

`({searchTerms}) Path:{SiteCollection}`

as you encapsulate the user query as a group. Still not perfect, but it's better.
