### ISSUE TITLE
getting following error for video files

### ISSUE THREAD

**Issue by Mr-Clrscr** [microsoft-search/pnp-modern-search#829]
Hi, 

I see the following error in the preview of some video files, i thought the video is corrupted one, but i was able to play the video from source without any issue

![Capture](https://user-images.githubusercontent.com/39514550/109764527-af2e3600-7c19-11eb-969a-fd8d55231c1b.PNG)

**Comment by wobba** [comment]
Issue template not followed - and we cannot control the backend of serving files.
