### ISSUE TITLE
Build Documentation for Completing a Branch

### ISSUE THREAD

**Issue by darrenpeat** [microsoft-search/pnp-modern-search#830]
This may well be down to my lack of knowledge. I'm trying to build the dev branch from GitHub in Visual Studio Code. I've installed Node.js  14.16.0, but I'm getting build errors. Is there a guide for this in terms of what dependencies are needed. Maybe this is already available.

**Comment by wobba** [comment]
First follow this guide: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment

Then follow https://microsoft-search.github.io/pnp-modern-search/how-to-contribute/
