### ISSUE TITLE
Version 4.0 Search box not connected to Search results

### ISSUE THREAD

**Issue by lraspbe** [microsoft-search/pnp-modern-search#833]
**Version used**
4.0

**Describe the bug**
When typing search terms in Search Box, Search Results returns nothing. There should be items.
here is the configuration for Search Results:
![image](https://user-images.githubusercontent.com/59847213/109865094-a6e1f500-7c31-11eb-8ff1-1ac747e2e281.png)
![image](https://user-images.githubusercontent.com/59847213/109865222-ced15880-7c31-11eb-99ae-1dfb5d61b9b5.png)

**Expected behavior**
When typing search terms in Search Box, Search Results should return results.

**Desktop (please complete the following information):**
 - Browser [chrome]

Thanks for helping!

**Comment by FranckyC** [comment]
Hi @lraspbe, can you please share the configuration of the connected search results WP? Especially the query template. Thanks!

**Comment by lraspbe** [comment]
> Hi @lraspbe, can you please share the configuration of the connected search results WP? Especially the query template. Thanks!

![image](https://user-images.githubusercontent.com/59847213/109869487-e9f29700-7c36-11eb-887f-f140637a01af.png)
![image](https://user-images.githubusercontent.com/59847213/109869578-0f7fa080-7c37-11eb-9b3c-cb884399026f.png)

**Comment by FranckyC** [comment]
Ok it appears you are using a custom result source. Make sure the the underlying query template for this source actually returns items and has the `{searchTerms}` keyword to be wired with the search box.

**Comment by lraspbe** [comment]
> Ok it appears you are using a custom result source. Make sure the the underlying query template for this source actually returns items and has the `{searchTerms}` keyword to be wired with the search box.

Thanks!
Now I am using Query template, I see results, still search box not connected to search results. Should I wire Search Box to Search Results?
![image](https://user-images.githubusercontent.com/59847213/109870496-2a064980-7c38-11eb-86c4-96d8b4aae641.png)
![image](https://user-images.githubusercontent.com/59847213/109870535-37233880-7c38-11eb-80e0-8da35582eb7a.png)

**Comment by FranckyC** [comment]
I see no whitespace between `{searchTerms}` and the rest of the query.

**Comment by lraspbe** [comment]
> I see no whitespace between `{searchTerms}` and the rest of the query.

I tried to put spaces between {searchTerms} and "Path", when I click "Apply", it took the space away.

**Comment by FranckyC** [comment]
Also did you connect the search box to the search results again?

**Comment by lraspbe** [comment]
> Also did you connect the search box to the search results again?

Now I did and it's working!! Thank you so much! One more quick question: Can version 4 Search do the following:

![image](https://user-images.githubusercontent.com/59847213/109872560-96824800-7c3a-11eb-887d-9d4f36f8c49a.png)

**Comment by FranckyC** [comment]
Ok good. Short answer: no. But you could use the extensibility library to create those components. https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_web_component/

**Comment by lraspbe** [comment]
> Ok good. Short answer: no. But you could use the extensibility library to create those components. https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_web_component/

Just want to say thank you again for helping me!!
