### ISSUE TITLE
Within the template it would be great to know the current user

### ISSUE THREAD

**Issue by FrazzApps** [microsoft-search/pnp-modern-search#834]
When I'm displaying the search results of a people search, it would be great to be able to know who the current user (doing the search) is so that their result can be modified as needed.

**Comment by wobba** [comment]
Good suggestion to expose some of the on page context variables. You may do this today with custom web components as well https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_web_component/

**Comment by wobba** [comment]
You can use `{{@root.context.user.loginName}}` to access the login name. If you use the debug template you can see everything accessible from the `@root` object. Tagging as documentation to show how this can be done.

**Comment by wobba** [comment]
Improved docs for next publish
