### ISSUE TITLE
pnp-panel issue

### ISSUE THREAD

**Issue by dguarneri71** [microsoft-search/pnp-modern-search#835]
**Version used**
Modern Search v4 - January 2021

**Describe the bug**
when I use pnp-panel I don't see the content.

**To Reproduce**
Insert this code in Handelbars template.
`<pnp-panel   
	data-is-open="false" 
	data-is-light-dismiss="true"
	data-is-blocking="true"
	data-size="3"
	data-panel-header-text="{{Filename}}">
	<template id="panel-open">
		<pnp-icon data-name="Info" aria-hidden="true"></pnp-icon>
	</template>
	<template id="panel-content">
		<div style="background-color:red">{{JSONstringify item}}</div>
	</template>
</pnp-panel>`

**Expected behavior**
I expect to see a red box under the panel title 

**Screenshot**
![Cattura1](https://user-images.githubusercontent.com/36726531/110093203-baf53600-7d9a-11eb-9c0a-65482b209a6d.PNG)

![Cattura2](https://user-images.githubusercontent.com/36726531/110093248-c8122500-7d9a-11eb-839b-7b415c05a5b2.PNG)

**Desktop (please complete the following information):**
 - Microsoft Edge. Version 88.0.705.81 (Official Build) (64 bit)

**Comment by FranckyC** [comment]
Hi @dguarneri71, seems to be related to an other issue https://github.com/microsoft-search/pnp-modern-search/issues/698. Can you test with the develop branch. This should be resolved. Thanks!

**Comment by dguarneri71** [comment]
Thanks @FranckyC, I will try with the develop branch in my development environment, but in the customer environment I prefer to use the next release.
When will the next release be available?

**Comment by wobba** [comment]
v4.1 will be released when we have time to address issues in the list. So no firm date - as it depends on people having spare time to contribute.
