### ISSUE TITLE
Sending multiple parameters in query string for filtering results

### ISSUE THREAD

**Issue by asadrajput** [microsoft-search/pnp-modern-search#836]
Hi
This is more of a question.

Is there a way to send multiple parameters in query string in Pnp 4.0?

Example: 

/sites/TransformationKnowledgeBankTEST/SitePages/SearchSpecific.aspx?q=kp102&refinablestring12

I am trying to send multiple parameters in URL but it only takes one, the first one.

cheers

![search Capture](https://user-images.githubusercontent.com/24537830/110035520-e7f01b80-7d8f-11eb-9d46-b395e55e862b.JPG)

**Comment by wobba** [comment]
Instead of consuming data via dynamic data, you can pick up the query parameters and use them in the query template.

See https://microsoft-search.github.io/pnp-modern-search/usage/search-results/tokens/#context-tokens

**Comment by asadrajput** [comment]
Thanks for the answer. 

If I am not mistaken, is this what you are referring to?

It still does only search for the keyword and not filter based on managed metadata field which is mapped to refinablestring. You will notice that it still pulls up all categories instead of only 1.

I used QueryString.a in my case to filter based on managed metadata field

cheers
![Capture](https://user-images.githubusercontent.com/24537830/110386964-17b36200-80b5-11eb-9e50-bc3d91281a79.PNG)

**Comment by FranckyC** [comment]
Hi @asadrajput, the deep links for filters feature is not implemented yet in the v4. Query string parameters can only be used for keywords. If you really need to preconfigure filters using the URL, you can still use the v3. See https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-results/#filters-deep-links

**Comment by wobba** [comment]
It's a bug that `{searchTerms} Foo:{QueryString.a} Foo:{QueryString.b}` only will read the first parameter, and then stop processing more.

**Comment by wobba** [comment]
Fixed in upcoming v4.1
