### ISSUE TITLE
Build Question

### ISSUE THREAD

**Issue by darrenpeat** [microsoft-search/pnp-modern-search#837]
Hi. I have 2 minute question on the build. I have the development branch now and I can build it.  I want to "includeClientSideAssets", but not sure how to do that.  I've tried the --ship / --production in the gulp command, but it errors.  Understand that this is a newbie question from a non developer :). Essentially I'm looking to build the complete package so I can re-deploy the whole thing.

**Comment by wobba** [comment]
See https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment and https://microsoft-search.github.io/pnp-modern-search/installation/ 

If you are using the dev branch for v4 you can skip the part about the extensibility library and npm link - updated docs will arrive shortly. Outside of these doc pages you should ask general SPFx questions over at https://github.com/SharePoint/sp-dev-docs
