### ISSUE TITLE
File Type counts changes when click on the checkbox

### ISSUE THREAD

**Issue by lraspbe** [microsoft-search/pnp-modern-search#838]
**Version used**
4.0

Issue:
When click on FileType checkbox, the count number changes and getting more files.
![image](https://user-images.githubusercontent.com/59847213/110140685-58079d00-7da2-11eb-9cfe-36c0179a1c83.png)

![image](https://user-images.githubusercontent.com/59847213/110140728-648bf580-7da2-11eb-9423-ae9d0e5cbe89.png)

**Comment by wobba** [comment]
The API returns estimated counts depending on the query and not something we can control. Closing as it's related to search API's, not the web parts.
