### ISSUE TITLE
Filter web part v4 - Filters not getting added with check box or combox box template

### ISSUE THREAD

**Issue by harinvp** [microsoft-search/pnp-modern-search#839]
_**Version used**_
4.0
![errorRefiners](https://user-images.githubusercontent.com/25250424/110192994-9033dc00-7e85-11eb-9e59-a93f6e78cd16.png)

**Describe the bug**
I deployed the two .sppkg files from PnP search v4. Added the search results and filter web parts to page. The search results web part works as expected. The filter web part is connected to the results web part. While I select the filters, no filter is getting added if I select checkbox, combo box or date interval. If I select date range as the template, the filter gets added. But the filtering is not happening even for the date fields. Tried with all the existing managed properties.
Looks like the filter web part is broken and does not establish a connection to the results web part. Also, looks like there is an issue with check box or combo box template as well

**To Reproduce**
1. Go to App catalog and upload 'pnp-modern-search-parts-v4.sppkg' and 'pnp-modern-search-extensibility.sppkg'
2. Deploy each package selecting 'make this solution available to all sites'.
3. Go to a communication site within the same tenant and add search results and filter web parts to a modern page
4. Configure results webpart and see the results are getting displayed. There are 50+ results
5. Configure filter web part, connect to search results web part. Click on 'Edit' on customize filters
6. Add any filter field and select 'check box' or combo box and save. The filter field not appearing on the filters web part. It says no refiners available
7. Add a date field like 'Created; and select 'date range' as template. The filter gets added. 
8. Select a date range and the results are not getting refined.

**Expected behavior**
On selecting check box as template, the filter field should get added with the available values of the filter from the connected search results web part
On filtering a date range, the results should be refined

**Screenshots**
Screen shot attached

**Desktop (please complete the following information):**
 Chrome

**Additional context**
The metadata properties which added to the search results web part. - before trying to add the same to the filter

**Comment by wobba** [comment]
Seems you are missing connecting the result wp to the filter wp. You need to connect both ways.

**Comment by harinvp** [comment]
Yes, I missed it. Thank you!
