### ISSUE TITLE
{QueryString.parameter} not fetching the value -  Refinement filters box - Search results web part

### ISSUE THREAD

**Issue by harinvp** [microsoft-search/pnp-modern-search#840]
**Version used**
Modern Search v4 - January 2021

**Describe the bug**
The value of {QueryString.q} not getting fetched in Refinement filters box - in the search results web part

**To Reproduce**
1. Configure Search Results Web part with 'Use input query text' on and point to Dynamic value
2. Connect to page environment->Query String ->Query Parameters -> q 
3.  In the refinement filters query is "and(Path:"library url*", RefinableString01:{QueryString.q})"
4. Hit the browser with "{siteURL}/sitepages/modernsearch.aspx?q=Food"
5. Search result web part displaying no results , saying "0 results for 'Food'
6. Replace the refinement filter in step 3 with the hardcoded value, that is RefinableString01:Food)
7. Results getting displayed. So the cause is {QueryString.q} does not read from query string.
8. Tried adding '{QueryString.q}' to Query template as well, didn't work

**Expected behavior**
{QueryString.q} reads the value from the URL and passes it on to refinement filters.

**Screenshot**
![image](https://user-images.githubusercontent.com/25250424/110270469-f94c5880-8019-11eb-99ea-e6753e287c22.png)

**Comment by harinvp** [comment]
@wobba Is there is any other way to filter based on the query string. Adding {QueryString.q} in the Query template field also didn't work. Appreciate if any suggestions. Thank you!

**Comment by wobba** [comment]
You can add it as filter in the QueryTemplate part. Same same.

**Comment by harinvp** [comment]
Thank you. But, for some reason, the query template filter does not work for me at all. Even if I put a hardcoded value, say Path:"libURL", the results not getting filtered, all results are getting displayed. The same filter works if I put it under refinement filters

**Comment by wobba** [comment]
Can you post your repro steps for querytemplate setup?

**Comment by harinvp** [comment]
**To Reproduce**

1.	Configure Search Results Web part with 'Use input query text' on and point to Dynamic value
2.	Connect to page environment->Query String ->Query Parameters -> q
3.	In the Query template add "RefinableString01:"{QueryString.q} "
4.	Hit the browser with "{siteURL}/sitepages/modernsearch.aspx?q=Food"
5.	Search result web part displaying 50 results , saying "50 results for 'Food'
6.	Replace the Query template with hardcoded value, "RefinableString01:"Food "
7.	Exactly the same result as step 5, with 50 results getting displayed
8.	Remove everything from the Query template keeping it empty.
9.	Exactly the same result as step 5, with 50 results
10.	Try changing the query template to “Path:libUrl*”, again same 50 results getting displayed, with results from outside the library as well
The issue is, no filtering happening with the Query template

**Comment by wobba** [comment]
Is your step 8-10 in edit mode? And we have done changes since January so I suggest you re-try with a more recent version.
