### ISSUE TITLE
Question: PNP Search Results Breadcrumb

### ISSUE THREAD

**Issue by MizzyMeaks** [microsoft-search/pnp-modern-search#841]
Hi 
In the native search results page, there is a breadcrumb for the location of a document that is returned in the search result.  I would like to customise search using the pnp-modern search results but also include this item. Is there a way to achieve this on the simple list or card?  
Thank you
![image](https://user-images.githubusercontent.com/80259627/110320549-62c36b80-8008-11eb-9514-020fe8a104e8.png)

**Comment by wobba** [comment]
Duplicate of #642
