### ISSUE TITLE
Search reports empty

### ISSUE THREAD

**Issue by asadrajput** [microsoft-search/pnp-modern-search#843]
Hi
I noticed that SharePoint search reports are all empty in the site collection. Is there a way to get these reports when using modern search? Like top queries, top no results queries which are available out of the box in SharePoint?
Thanks

### Issues related to data mapping, e.g. SharePoint columns to crawled properties to managed properties, will be closed by default and should be asked elsewhere as it's outside the scope of this project. However if you cannot repro the issue with classic web parts, then it's ok as it relates to these web parts 🙂

__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
Ex: 3.16

**Describe the bug**
A clear and concise description of what the bug is. Keep questions and bugs related to the web parts. If the issue relates to KQL or question around crawled and managed properties please use [Microsoft TechCommunity](https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev). Which means, if you experience the same behavior in classic web parts, then it's not an issue with PnP Modern Search 😉

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by wobba** [comment]
Analytics is outside the scope of this project. API calls are no longer available in the reports as analytics is transitioning, and you will have to follow whatever is made available going forward.

If you want proper analytics you should instrument this yourself, using for example web-components and log it somewhere you have control over.

**Comment by asadrajput** [comment]
Thanks
So I guess this does not cover pnp search?

cheers

https://docs.microsoft.com/en-us/sharepoint/view-search-usage-reports


![Capture](https://user-images.githubusercontent.com/24537830/110554864-b01e1500-818f-11eb-9cd1-a0afa3b60ae7.PNG)

**Comment by wobba** [comment]
I'm saying search reports will cover OOB search, which makes sense. And these web parts have never implemented click logging on the classic API's either, which makes sense from my point of view. You might use them to replace OOB search, which I always have believed is the wrong approach (https://www.techmikael.com/2020/09/microsoft-search-vs-pnp-modern-search.html)

So, if you want logging, you can implement this to tailor your needs.
