### ISSUE TITLE
Open results in new tab & Select multiple results for download

### ISSUE THREAD

**Issue by SPLeon** [microsoft-search/pnp-modern-search#844]
Hi,

I just started to use the PnP Search addon. Very impressive addon :-)

I have a couple of questions regarding the functionality:

1. Is it possible to open an item within the search result webpart in a new tab? I'm using the detail list but I dont see an option to open a specific result in a new tab.

2. Our company has asked if it's possible to select mutiple items in the result webpart and download the selected items. Is this also possible? We don't write custom code as we are not experience in this so we prefer a OOTB option.

Many thanks.

**Comment by FranckyC** [comment]
Hi @SPLeon:

> Is it possible to open an item within the search result webpart in a new tab? I'm using the detail list but I dont see an option to open a specific result in a new tab.

Yes by modifying the "Title" column HTML value and using the `data-interception="off"` attribute:

![image](https://user-images.githubusercontent.com/5659122/110476231-bdfc6900-80af-11eb-8f77-8844745c95b0.png)

> Our company has asked if it's possible to select mutiple items in the result webpart and download the selected items. Is this also possible? We don't write custom code as we are not experience in this so we prefer a OOTB option.

Not available for any layout for now. Maybe we will implement this in a next release but nothing planned yet.

Thanks!

**Comment by SPLeon** [comment]
Thanks for the quick reply. Opening in new tab is working now.
Is there also a possibility to get a preview of a file within this detail view?

**Comment by FranckyC** [comment]
Yes, but you have to update the column value and use the custom component `<pnp-filepreview>`. See https://microsoft-search.github.io/pnp-modern-search/extensibility/web_components_list/#ltpnp-filepreviewgt

**Comment by fedewagner** [comment]
Hi, 

is there any news about the plan to include the **download button** for multiple selected files from the Result Web Part in the next release? 

Have you seen any other customization for enabling that?

Any other further information will be appreciated.

**Comment by SylvieLet** [comment]
I'm also super interested to know if there's been any development on the possibility of downloading multiple selected files from the Results web part.

Anyone know of such a customisation?
