### ISSUE TITLE
Search results grouping repeats rows in multiple groups 

### ISSUE THREAD

**Issue by jhammar** [microsoft-search/pnp-modern-search#846]
**Version used**
4

**Describe the bug**
Search results web part grouping repeats result row in multiple groups. Number of result rows is correct. Total result count is correct & group counts are correct, but some rows inside groups are duplicated from another group.

**To Reproduce**
1. Add search results web part to page
2. Enable grouping at bottom of pg 2 config
3. Select a group by field & save page
4. Add a few items with different group field values
5. See screenshot results

**Expected behavior**
Show only actual results in each group.

**Screenshots**
<img width="703" alt="image" src="https://user-images.githubusercontent.com/7122184/110526697-1cdbd580-80e4-11eb-8555-49b15e4ff0e5.png">

**Desktop (please complete the following information):**
 MS Edge 88+

**Additional context**

**Comment by FranckyC** [comment]
Hi @jhammar , I was able to reproduce the issue. I'll look into it. Thanks!

**Comment by FranckyC** [comment]
@jhammar Fixed and will be available in the next release.
