### ISSUE TITLE
Search box not connecting

### ISSUE THREAD

**Issue by mouseman85** [microsoft-search/pnp-modern-search#849]
Having an issue with the search box, i've followed the guides and videos, and it doesn't pull through any results. I have a search results thats connected to a specific document library using:

`{searchTerms}Path:https://tennat.sharepoint.com/sites/OurDocuments/Live%20Forms%20and%20Templates`

and then a refinement filter:

`or(filetype:xls*, filetype:url, filetype:pdf, filetype:doc*, filetype:pp*, filetype:mp*, filetype:png, filetype:jp*)`

I've connected it to a filters webpart this works as expected. But connecting to a Search box, when searching no results are returned. I'm using dynamic value setting, Connect to source PnP - Search Box and then PnP search box properties Search Query, as per the guide and the update video but not luck.

**Comment by wobba** [comment]
Issue template omitted and repro steps missing.
