### ISSUE TITLE
Pagination for search result disappear in PNP Modern Search Result web part when using custom renderer.

### ISSUE THREAD

**Issue by Suryansh-Tripathi** [microsoft-search/pnp-modern-search#850]
**Version used**
Ex: 3.14.2.0

**Describe the bug**
We are using PNP Modern search result web part to show search results. We have created a custom renderer to show the search result. It was working as expected before but when we updated the PNP modern search package to 3.14.2.0 the pagination for search result stopped showing. We tried with the sample in the PnP Modern Search - Custom renderer, there also the problem persists.

**To Reproduce**
1. Install the PnP Modern Search - Search Web Parts 3.14.2.0.
2. PnP Modern Search - Custom renderer  1.0.1.0
3. Set CodeRenderer as Result layout in PNP modern Search Result web part
4. The pagination will disappear for the search results.

**Expected behavior**
The pagination should not disappear for the Search Result.

**Comment by Suryansh-Tripathi** [comment]
We were able to show pagination by using handlebars in the “tsx” file of our custom renderer. We added <pnp-pagination> tag using handlebars and rendered that as HTML. The following snippet worked for us.
import * as Handlebars from "handlebars";

const data = {
root: {
     paging:{
totalItemsCount:this.props.searchResults.PaginationInformation.TotalRows,
hideFirstLastPages:false,
hideDisabled:false,
hideNavigation:false,
pagingRange:this.props.searchResults.PaginationInformation.MaxResultsPerPage,
itemsCountPerPage:this.props.searchResults.PaginationInformation.MaxResultsPerPage,
currentPageNumber:this.props.searchResults.PaginationInformation.CurrentPage
       }
   }
}; 
const hbr = ` <pnp-pagination 
data-total-items="{{root.paging.totalItemsCount}}" 
data-hide-first-last-pages="{{root.paging.hideFirstLastPages}}"
data-hide-disabled="{{root.paging.hideDisabled}}"
data-hide-navigation="{{root.paging.hideNavigation}}"
data-range="{{root.paging.pagingRange}}" 
data-items-count-per-page="{{root.paging.itemsCountPerPage}}" 
data-current-page-number="{{root.paging.currentPageNumber}}"
>
</pnp-pagination>`;
const template = Handlebars.compile(hbr);

  <div dangerouslySetInnerHTML={{ __html: template(data) }} />

**Comment by wobba** [comment]
I would probably use web components and not the custom renderer going forward. It was a start, but not the best approach.

**Comment by savajosa** [comment]
> We were able to show pagination by using handlebars in the “tsx” file of our custom renderer. We added tag using handlebars and rendered that as HTML. The following snippet worked for us.
> import * as Handlebars from "handlebars";
> 
> const data = {
> root: {
> paging:{
> totalItemsCount:this.props.searchResults.PaginationInformation.TotalRows,
> hideFirstLastPages:false,
> hideDisabled:false,
> hideNavigation:false,
> pagingRange:this.props.searchResults.PaginationInformation.MaxResultsPerPage,
> itemsCountPerPage:this.props.searchResults.PaginationInformation.MaxResultsPerPage,
> currentPageNumber:this.props.searchResults.PaginationInformation.CurrentPage
> }
> }
> };
> const hbr = ` <pnp-pagination
> data-total-items="{{root.paging.totalItemsCount}}"
> data-hide-first-last-pages="{{root.paging.hideFirstLastPages}}"
> data-hide-disabled="{{root.paging.hideDisabled}}"
> data-hide-navigation="{{root.paging.hideNavigation}}"
> data-range="{{root.paging.pagingRange}}"
> data-items-count-per-page="{{root.paging.itemsCountPerPage}}"
> data-current-page-number="{{root.paging.currentPageNumber}}"
> 
> > 
> 
> `;
> const template = Handlebars.compile(hbr);

Can you please let me know how you got it working. I mean, in the code renderer render() method, I called it as  template({}) , but this just output the html
