### ISSUE TITLE
Issue with Search Bar not returning results

### ISSUE THREAD

**Issue by mouseman85** [microsoft-search/pnp-modern-search#851]
**Version used**
v4

**Describe the bug**

I've connected search results it to a filters webpart this works as expected. But connecting to a Search box, when searching no results are returned. I'm using dynamic value setting, Connect to source PnP - Search Box and then PnP search box properties Search Query, as per the guide and the update video but not luck.

I have a search results thats connected to a specific document library using:

{searchTerms}Path:https://tennat.sharepoint.com/sites/OurDocuments/Live%20Forms%20and%20Templates

and then a refinement filter:

or(filetype:xls*, filetype:url, filetype:pdf, filetype:doc*, filetype:pp*, filetype:mp*, filetype:png, filetype:jp*)

**To Reproduce**
1. Add a search results webpart with the following search terms: - 
{searchTerms}Path:https://tennat.sharepoint.com/sites/OurDocuments/Live%20Forms%20and%20Templates
and the following refiners:
or(filetype:xls*, filetype:url, filetype:pdf, filetype:doc*, filetype:pp*, filetype:mp*, filetype:png, filetype:jp*)
2. Add a search box webpart 
3. connect the search box to the search results using the Connect to source PnP - Search Box and then PnP search box properties Search Query
4. Publish page, and enter text such file name - no results returns 

**Expected behavior**
Searching by file name should return results in search box, similar issue I had is that search doesn't search the file name, just seem to search the content. 

**Screenshots**

![image](https://user-images.githubusercontent.com/11850876/110633891-3d1d9a00-81a1-11eb-857b-18e83cb3a999.png)

![image](https://user-images.githubusercontent.com/11850876/110637723-a1425d00-81a5-11eb-9e9b-00d70bd0b48a.png)

**Comment by wobba** [comment]
Can you add a space between `}`and `path`?

`{searchTerms} Path:https://tennat.sharepoint.com/sites/OurDocuments/Live%20Forms%20and%20Templates`

**Comment by wobba** [comment]
Filename:({searchTerms})
