### ISSUE TITLE
Search results web part pushState changes breaks client-side navigation

### ISSUE THREAD

**Issue by mbice** [microsoft-search/pnp-modern-search#852]
**Version used**
Ex: 3.17.0, 3.18.0, 4.x (earlier versions may also be affected, but haven't gone back to check)

**Describe the bug**
There seems to be a scenario where client-side navigation is broken and it's related to the modification of history.pushState. Basically, when the PnP search results web part is on a page and you navigate using local site navigation, it stops working and the pushState is corrupted somehow.

**To Reproduce**
1. Create an fresh communications site
2. Drop the PnP search results web part on the page
3. Navigate to "Pages" using the local site navigation
4. Use local site navigation to navigate back to "Home"
5. Notice the navigation does not work at this point and there's a console error related to pushState.

**Screenshots**

Use the "Pages" link in the local site navigation

![image](https://user-images.githubusercontent.com/985283/110718140-4453a080-81bf-11eb-8248-0b733cfe747d.png)

Once on the Pages library (same issue happens with Documents), click on any other local site navigation link and navigation is broken with the following error in the console.

![image](https://user-images.githubusercontent.com/985283/110718092-2e45e000-81bf-11eb-8fc9-65efed0c30e0.png)

**Desktop (please complete the following information):**
 - Windows 10, Chrome (latest)

**Comment by WolfSchertler** [comment]
We are seeing exactly the same issue with the latest V3 and V4 webparts. v3.14.2 is the last version working well.

**Comment by wobba** [comment]
I cannot repro with the steps provided for  dev branch of v4. v3 I do have repro.

**Comment by wobba** [comment]
Fixed for upcoming v4 and release v3.18.1 with a fix.
