### ISSUE TITLE
What version should I choose?

### ISSUE THREAD

**Issue by schoier** [microsoft-search/pnp-modern-search#853]
Should I download v3 or v4 when seting up solutions in new environments?
I see regular updates on v3, but when is next release for v4 planned (waiting for some fixes)?

**Comment by wobba** [comment]
v3 is mainly small fixes, not new features. Next v4 is work in progress as @FranckyC and I haven't had time to spend on it recently. We'd be happy to get more people involved addressing open issues on the list.

If all you care about is SharePoint items then v3 will keep on serving that scenario. If you think you might need to get connector items and new features from Microsoft Search, then v4.
