### ISSUE TITLE
Deleted file still visible in Search results

### ISSUE THREAD

**Issue by PeterVos111** [microsoft-search/pnp-modern-search#854]
**Version used**
3.15.1

**Describe the bug**
I have a pdf that is still showing up in the search results. This file has been deleted last year (exact date unknown). I already contacted Microsoft to see if the issue is related to the SharePoint search, but we could not reproduce it here. The issue is only when searching for the file in this solution.

- The Thumbnail is also not showing, pressing the search result, results in a 'Page not found'.
- Tried uploading a pdf with the same name, the search result now points to this pdf! Deleting this file had the same result. 
- Tried uploading a pdf with the same name and then renaming it, but then search result is no longer pointing to this file.

**To Reproduce**
1. Open the search center
2. search for file
3. Press on result
4. 'Page not found'

**Expected behavior**
Expect the file to disappear from the search results, as it's been long replaced by a different file (with a different name)

**Screenshots**

Screenshot of search result:
![image](https://user-images.githubusercontent.com/46716165/110765470-7fec7a00-8254-11eb-8d16-367e94bd906f.png)

Screenshot of when i click on the file. translation: "Page not found"
![image](https://user-images.githubusercontent.com/46716165/110765547-95fa3a80-8254-11eb-99d0-c74745957783.png)

**Desktop (please complete the following information):**
 - Happens in all browsers, Chrome, FireFox, Edge

**Additional context**

**Comment by wobba** [comment]
This is a search back end issue, not related to the search web parts.
