### ISSUE TITLE
Question: Support for __ModerationStatus in v3 or v4

### ISSUE THREAD

**Issue by L7Lynx** [microsoft-search/pnp-modern-search#859]
Hello

I'm having some issues with __ModerationStatus (Approval Status) only showing up as a number in the Search Refiners webpart. When using this field as a refiner, the users would like to filter this as the correct label "Approved", "Draft", etc instead of "0","1", etc.

Is there a functionality within the Search Refiners webpart that allows to send a different label for the refiners, so I can do the mapping there? Or is this something that can be resolved using the Templates functionality? What possibilities exist in v3 or v4 for this?

My apologies if this would have been asked before, I did not find an answer in the documentation or the resolved/open issues on Github.

Kind regards

**Comment by wobba** [comment]
Take a look at the custom templating in v4 for filters.

![image](https://user-images.githubusercontent.com/51104/110962974-d2f82700-8351-11eb-932b-b9994261b9a0.png)
