### ISSUE TITLE
Verticals web part is missing the tab value

### ISSUE THREAD

**Issue by perritoMedia** [microsoft-search/pnp-modern-search#861]
**Version used**
4.0.0.0

**Describe the bug**
Verticals web part is missing the tab value

**To Reproduce**
1. Add a PnP Search Verticals web part to your page
2. Notice Tab Value is missing

**Expected behavior**
Tab Value should be have the same behaviour as Query Template in v3

**Screenshots**
Version 4
![image](https://user-images.githubusercontent.com/4068044/110977150-b4962980-8359-11eb-8568-7217dd012469.png)

Version 3
![image](https://user-images.githubusercontent.com/4068044/110977346-fb841f00-8359-11eb-84cd-4ad018398199.png)

**Desktop (please complete the following information):**
 - Browser : Chrome on Windows 10

**Additional context**
v3 is also installed in the site

**Comment by FranckyC** [comment]
Hi @perritoMedia. This feature is currently not implemented in the v4 Web Part. This is a mistake in the documentation. Also keep in mind verticals vetween v3 and v4 are very different so they can't have the same behavior. Added it as an enhancement. Thanks.

**Comment by wobba** [comment]
Duplicate of #757
