### ISSUE TITLE
Cannot use async calls in Handlebars registerHelper

### ISSUE THREAD

**Issue by heatherzhang080** [microsoft-search/pnp-modern-search#862]
Async calls don't seem to work. Code as below:

```
public registerHandlebarsCustomizations(namespace: typeof Handlebars) {
    namespace.registerHelper('myAsyncCall', async (pathStr: string) => {
      let data= await this.getData(pathStr);
      return data;
    });
}
```

**Comment by FranckyC** [comment]
Hi @heatherzhang080 , please use the issue template when submitting...Anyway Handlebars helpers are not meant to be async regardless of this solution. For your scenario, you may use a web [component ](https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_web_component/)instead.
