### ISSUE TITLE
File preview image shows on every other file 

### ISSUE THREAD

**Issue by lraspbe** [microsoft-search/pnp-modern-search#863]
**Version used**
4

I am using the list view in Search results. It shows the file preview thumbnails but it only shows every other file. When I click on one of those not having preview thumbnails, it does show the document in the window.

![image](https://user-images.githubusercontent.com/59847213/111162586-aa02ac80-8572-11eb-90aa-6b1393648162.png)

**Comment by wobba** [comment]
Already solved in the dev branch and will be part of the next v4 release. Please check the issue list.
