### ISSUE TITLE
How can I use web part context within a Custom Component?

### ISSUE THREAD

**Issue by heatherzhang080** [microsoft-search/pnp-modern-search#865]
I'm trying to build a custom component based on one of my SP lists. I need to setup spfxContext for pnp. How can I pass in the context?

**Comment by FranckyC** [comment]
@heatherzhang080, please use the issue template!!! Next time, your issue will be closed automatically without review.

To use the context, in your web component file, import the `PageContext` module:

```
import { PageContext } from "@microsoft/sp-page-context"
```

Then in the `connectedCallback` method, resolve an instance using service scope:

```
const pageContext = this._serviceScope.consume<PageContext>(PageContext.serviceKey);
```

**Comment by heatherzhang080** [comment]
Thanks @FranckyC. Is that from Open a blank issue?

**Comment by FranckyC** [comment]
![image](https://user-images.githubusercontent.com/5659122/111239799-52932980-85d0-11eb-816c-2e7f6bba83ac.png)

**Comment by wobba** [comment]
Blank issue option is now removed :)
