### ISSUE TITLE
V4 PnP Search Results WebPart effects OoB Footer placement

### ISSUE THREAD

**Issue by myatix** [microsoft-search/pnp-modern-search#867]
**Version used**
v4.0

**Describe the bug**
When adding the PnP Results webpart to page with no other webparts and comments turned off the footer on a communication site is not located at the bottom of the page anymore. This seems to be a CSS issue that is impacting the out of the box footer placement. 

**To Reproduce**
1. Enable Footer on a communication site
2. Disabled "Comments" on the page
3. Remove all standard webparts
4. Add a pnp Results webpart

**Expected behavior**
The footer should always be shown at the bottom of the screen.

**Screenshots**

![image](https://user-images.githubusercontent.com/48433526/111288959-f4ecf480-8644-11eb-88d0-2bfbbf3cdfb0.png)

**Desktop (please complete the following information):**
 - Edge Chromium
 -

**Comment by wobba** [comment]
Will be included in the v4.1 and affected card layout.
