### ISSUE TITLE
Ability to filter by Hub Site

### ISSUE THREAD

**Issue by ravinleague** [microsoft-search/pnp-modern-search#869]
I'm wondering if there is a way to filter search results by Hub site. The idea is to narrow down search results of that hub site (and its associated sites). There is a DepartmentId field that we can use to refine by. However it displays as a GUID rather than the hub site title. 

Any recommendations greatly appreciated.

**Comment by wobba** [comment]
`DepartmentId:\{{Hub.HubSiteId}\}` Docs will be updated with the sample.

**Comment by ravinleague** [comment]
![IMG_342AE9E9931E-1](https://user-images.githubusercontent.com/18733308/111718592-f36e3700-88a5-11eb-85a0-7af3f9b6ee5a.jpeg)
Not quite what I was looking for... see attached.

**Comment by wobba** [comment]
"Filter" as a refinement filter was not clear from your question. Of you want all hubs to show by name as a filter you need to use v4 and a custom render template to look up sitetitle based on the hubid (which is the SiteID of the hub).

If SiteTile is refinable you can use those...as long as you don't have overlapping names.

**Comment by ravinleague** [comment]
Is there documentation for custom render template usage ? The v4 documentation is very basic and lacks a lot of information

**Comment by wobba** [comment]
@ravinleague that's a not a very descriptive comment on what to improve and what you think is missing. Web components are well documented on the internet and https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_web_component/ tells you how to get started
