### ISSUE TITLE
Promoted results not shown correctly

### ISSUE THREAD

**Issue by MariaTusak** [microsoft-search/pnp-modern-search#870]
Hello, 
I have stumbled across the following issue: 

We have several promoted results. When using the V4 Search-Results webpart I get the following picture: 

![image](https://user-images.githubusercontent.com/79101518/111591139-56d56780-87c7-11eb-8702-96e96ac641af.png)

It seems, that the 2 promoted results are retreived (minilinks) but are not displayed? 
It is a simple-list view without any customization. 

Localization, Graph and Queries are active in the configuration. 
I was able to reproduce this issue on different tenants with different promoted results and different users. The results were displayed correctly in the V3. 

Did I miss out on something, or is this a bug? 

Thanks for Feedback of any kind.

**Comment by wobba** [comment]
Should be fixed in the dev branch and upcoming v4.1 for the list template.

![image](https://user-images.githubusercontent.com/51104/111609403-89d52680-87da-11eb-956b-23b457876539.png)
