### ISSUE TITLE
How to get additional columns in the search results

### ISSUE THREAD

**Issue by chaitanya81it** [microsoft-search/pnp-modern-search#872]
Hi 

Am using PNP Search  3.15.1.0 V and it is working good. However my user wanted to have some additional columns like Modified By, Library Name from the files are stored. 

![image](https://user-images.githubusercontent.com/67157521/111627279-e6553780-8814-11eb-9c31-0067c3ff8404.png)
I tried different combinations and nothing helped. 

Is there away to show the Site Name using Result Source Id? 

Also if i download and upload 3.18, does it effect the existing search pages which are already in production?

regards
Chetan

**Comment by wobba** [comment]
Upgrade to 3.18 should not break anything. To see more data you need to bring in more managed properties. Describing SharePoint data over to crawled properties to managed properties is outside of these web parts. Some documentation can be found at https://docs.microsoft.com/en-us/sharepoint/technical-reference/crawled-and-managed-properties-overview.

Adding more guides would be useful for sure, for those not experienced with SP search.
