### ISSUE TITLE
Persona Card - To many request Graph

### ISSUE THREAD

**Issue by ronbet** [microsoft-search/pnp-modern-search#875]
**Version used**
4.0

**Describe the bug**
Using People layout with SharePoint People Result, people is displayed correctly. After activating the Persona Hover Card with correct approved API permission - The hover function is not working.
There is 7000+ user and the error from the web console is "To many request (429) microsoft graph. It seem to be all user called om search at one user and no reaction in network traffic when hover the inactivate persona card.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by wobba** [comment]
@FranckyC is this all on graph toolkit?

**Comment by FranckyC** [comment]
@wobba Yes the persona card is implemented through MGT, we need to check what queries are made when hover.

**Comment by fisketryne5** [comment]
Any update on this? I am having the same problem. (~5000 searchable users.)

**Comment by wobba** [comment]
When no comments have been added to an issue, it means no one in the community has looked at it yet :)

**Comment by stevebeauge** [comment]
Also experiencing this very annoying issue.

Looking in the network reveal that for each personna in the search result, Two requests are emitted. A first using the OPTIONS verb, and a second using a GET verb. Both pointing to `https://graph.microsoft.com/v1.0/me/people?$search=%22someemail@corp.com%22`.

In my case, I have a people search that shows 30 results. This means each time the page loads, 60 requests is made.

Any advise or workaround ?

**Comment by wobba** [comment]
Seems that when adding the onhover card functionality the graph toolkit with fire off the graph query per item before hovering via the `<mgt-person>` component. Not sure there's any way we can fix that.

**Comment by stevebeauge** [comment]
I also noticed there's no caching with the search WP.

In the [mgt doc](https://docs.microsoft.com/en-us/graph/toolkit/customize-components/cache), a caching mechanism is described and should appears in the local indexdDB.

In my environment, I don't see the expected cache DB.

Not clear if it's supposed to be enabled by default thought. 

It won't solve first load performance issue, but I guess it wouldn't arm ?

**Comment by wobba** [comment]
@stevebeauge adding cache seems like a smart thing to do :)
