### ISSUE TITLE
Thumbnail for PDF files goes to Document library

### ISSUE THREAD

**Issue by lraspbe** [microsoft-search/pnp-modern-search#876]
**Version used**
3.12.1

**Describe the bug**
Thumbnail for PDF files goes to Document library instead of the file itself. All Word documents are fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/59847213/111800458-5c53b000-88a2-11eb-85fb-7dc33bb3bc00.png)

**Desktop (please complete the following information):**
 - chrome

**Comment by wobba** [comment]
This has changed after your version. You can always create the Url yourself in the template.

**Comment by lraspbe** [comment]
I downloaded 3.18 version. Now it doesn't open file in preview window at all. Could you please help me create the url link? I am not a SharePoint Developer. Thanks!

**Comment by wobba** [comment]
Seem I broke the preview in v3.18 for the "Simple list" layout. I have made a fix so it will come back in the next fix version.
