### ISSUE TITLE
Synonyms not returning any results

### ISSUE THREAD

**Issue by lraspbe** [microsoft-search/pnp-modern-search#877]
**Version used**
3.16

**Describe the bug**
When I configured synonyms, it didn't return any search results. Other than configures in Edit synonyms, other settings need to be changed?

**Screenshots**
![image](https://user-images.githubusercontent.com/59847213/111872990-8372b600-8964-11eb-8135-c55df6d815b0.png)

**Desktop (please complete the following information):**
 - chrome

**Comment by FranckyC** [comment]
Hi @lraspbe, can you inspect the query in the browser network tab and make sure the submitted keywords are correctly sent and should actually return results?

**Comment by lraspbe** [comment]
Here is the error:

![image](https://user-images.githubusercontent.com/59847213/111907941-b9c83800-8a2d-11eb-9a50-7261d480cf57.png)

**Comment by lraspbe** [comment]
![image](https://user-images.githubusercontent.com/59847213/111909202-b4b9b780-8a32-11eb-8ff8-8f5dc71010bb.png)

**Comment by lraspbe** [comment]
Hi @FranckyC ,
There is something wrong with the querytext, please see the screenshot:

![image](https://user-images.githubusercontent.com/59847213/112045240-02145280-8b21-11eb-8eb2-df4d8fc28de1.png)

**Comment by wobba** [comment]
@lraspbe can you show your synonym config and what term are you searching with?

**Comment by lraspbe** [comment]
@wobba, I made sure "leave" and "2020" in files.

![image](https://user-images.githubusercontent.com/59847213/112050258-07749b80-8b27-11eb-9f77-52ee380487aa.png)

**Comment by lraspbe** [comment]
@wobba, here is the text file from developer tool:

{"request":{"__metadata":{"type":"Microsoft.Office.Server.Search.REST.SearchRequest"},"ClientType":"PnPModernSearch","Properties":{"results":[{"Name":"EnableDynamicGroups","Value":{"BoolVal":true,"QueryPropertyValueTypeIndex":3}},{"Name":"EnableMultiGeoSearch","Value":{"BoolVal":true,"QueryPropertyValueTypeIndex":3}},{"Name":"ClientFunction","Value":{"StrVal":"PnPSearchWebPart","QueryPropertyValueTypeIndex":1}},{"Name":"ListId","Value":{"StrVal":"6c6c8eac-240e-4e20-892f-26cc1d2ac41e","QueryPropertyValueTypeIndex":1}},{"Name":"ListItemId","Value":{"StrVal":"10","QueryPropertyValueTypeIndex":1}}]},"**Querytext":"(\"(\"leave\" OR \"2020\")\" OR \"2020\")"**,"TimeZoneId":10,"EnableQueryRules":false,"QueryTemplate":"{searchTerms} Path: https://myguilford.sharepoint.com/sites/GCHRhub/HRForms/*","RowLimit":10,"SelectProperties":{"results":["Title","Path","Created","Filename","SiteLogo","PreviewUrl","PictureThumbnailURL","ServerRedirectedPreviewURL","ServerRedirectedURL","HitHighlightedSummary","FileType","contentclass","ServerRedirectedEmbedURL","ParentLink","DefaultEncodingURL","owstaxidmetadataalltagsinfo","Author","AuthorOWSUSER","SPSiteUrl","SiteTitle","IsContainer","IsListItem","HtmlFileType","SiteId","WebId","UniqueID","OriginalPath","FileExtension","IsDocument","NormSiteID","NormWebID","NormListID","NormUniqueID"]},"TrimDuplicates":false,"SortList":{"results":[{"Property":"Created","Direction":0},{"Property":"Size","Direction":1}]},"Culture":1033,"Refiners":"","HitHighlightedProperties":{"results":[]},"RefinementFilters":{"results":[]},"ReorderingRules":{"results":[]}}}

**Comment by wobba** [comment]
I reworked the logic and will be part of the next release. I think you should be able to work around it by not using 2-way synonyms, but have one line per expansion until the release is out.

**Comment by lraspbe** [comment]
@wobba Thank you. I will wait for the next release. I tried not using 2-way synonyms, it still doesn't return anything.
