### ISSUE TITLE
Custom Results Display Template

### ISSUE THREAD

**Issue by Mario4272** [microsoft-search/pnp-modern-search#878]
**Is your feature request related to a problem? Please describe.**
I am trying to get a grid together that will display documents based on certain metadata

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/19327923/111918681-a4b6cd80-8a5c-11eb-9508-a4c63c49f1f2.png)

**Describe alternatives you've considered**
I tried the grid but I cant customize without messing up other MS related styles

**Additional context**
I am using react-flexbox-grid for "Bubble & Title" and react-router for "Link".

Any and all suggestions would be helpful.  The above code is just one column in a12 column grid.  Ultimately I would like to add this grid to a results template and let PnP do the work.  But it got very complicated.  Ive resorted to building my own SPFx webpart, that I now need to connect to the search box and results.

**Comment by wobba** [comment]
The templates are html/css, so should be doable. If you want to use some other framework then that should be wrapped as web components which you can load in v4.

**Comment by wobba** [comment]
Closed due to inactivity.
