### ISSUE TITLE
Modern Search results Web part V3: All Images are not loading in the Tiles view template

### ISSUE THREAD

**Issue by ArzooCamd** [microsoft-search/pnp-modern-search#879]
Version: 3.17

The Tile template is not working properly, the images are not loading on UI, while after redirecting from **DocumentCardTitle** it reloads the image on the browser.

**To Reproduce**
1. Add a Search box web part,
2. Add a vertical and add query ({searchTerms} -Path:SiteAssets -Path:Microfeed -Filename:.aspx -Filename:.zip -FileType:aspx -Path:SiteCollectionImages  -ContentTypeId:0x0120* (FileType="jpg") OR (FIleType="jpeg") OR (FIleType="bmp") OR (FIleType="png"))
3. Add search results web part, connect with search box & verticals
4. Search on the search box with any keyword
5. Check if all the images are loading properly

We are expecting to load all the image results properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/63994838/111999370-ea4dc600-8b42-11eb-8b66-adc22e7a970a.png)

**Desktop (please complete the following information):**
 - Browser: Chrome

Console logs:
![image](https://user-images.githubusercontent.com/63994838/111999069-a0fd7680-8b42-11eb-9f86-ac83c912cb11.png)

**Comment by wobba** [comment]
Can you check network tab for errors when loading the thumbnails?

**Comment by ArzooCamd** [comment]
@wobba no errors while loading thumbnails in network tab
![image](https://user-images.githubusercontent.com/63994838/112127918-eaee6700-8beb-11eb-9a39-5e2aba34bba4.png)

**Comment by ArzooCamd** [comment]
Hi @wobba,

The preview image is null for most of the images, could you please help me to know, how and from where we are forming the preview image URL?

![image](https://user-images.githubusercontent.com/63994838/112141151-f39a6980-8bfa-11eb-92ec-ed1783c7d1f2.png)

**Comment by wobba** [comment]
I cannot repro with the latest code in this branch which I'm working on (https://github.com/microsoft-search/pnp-modern-search/tree/wobba/v3-fixes).

Are the ones not showing stored in special folders? Are you in a multi-geo environment?

On the network tab filter on image(img) requests only and look for URL's like:

* https://tenant.sharepoint.com/sites/adal/_api/v2.0/sites/d47f521d-19e7-4fc8-9e0f-715663ee4061,a585ba8d-34c9-47ba-878b-c3e783644080/lists/478b9fa7-1469-4b41-ade2-4fb128588760/items/ff1b746c-3888-4005-ba7a-0bdb05915fb0/driveItem/thumbnails/0/large/content?preferNoRedirect=true
* https://northeurope1-mediap.svc.ms/transform/thumbnail?provider=spo....

**Comment by ArzooCamd** [comment]
Hi @wobba   Now we are using the V4 version so no issues there.
