### ISSUE TITLE
Transparency on web parts

### ISSUE THREAD

**Issue by frankok** [microsoft-search/pnp-modern-search#88]
**Is your feature request related to a problem? Please describe.**
When setting another background color that white on the web part sections, the search web part backgrounds themselves stay white.

**Describe the solution you'd like**
When setting another background color on the web part sections, the search web parts should inherit this background color (i.e. they should not have a fixed white background).

![image](https://user-images.githubusercontent.com/20436301/73865742-03fb5380-4844-11ea-86b6-ac1b5dc8f9b5.png)

**Comment by FranckyC** [comment]
@frankok Which version are you using? This issue should be fixed with the latest.

**Comment by frankok** [comment]
[cid:image001.png@01D5DC52.FE2675A0]

Mvh / Kind Regards,
Frank-Ove Berg Kristiansen
Konsulent
Mobil +47 48019794

**Comment by FranckyC** [comment]
@frankok Didn't get the image :(

**Comment by frankok** [comment]
Version 3.8.0



Mvh Frank-Ove i farta!



-------- Opprinnelig melding --------
Fra: Franck Cornu <notifications@github.com>
Dato: 05.02.2020 18:45 (GMT+01:00)
Til: microsoft-search/pnp-modern-search <pnp-modern-search@noreply.github.com>
Ko: Frank-Ove Berg Kristiansen <frank.kristiansen@bouvet.no>, Mention <mention@noreply.github.com>
Emne: Re: [microsoft-search/pnp-modern-search] Transparency on web parts (#88)


@frankok<https://github.com/frankok> Didn't get the image :(

**Comment by FranckyC** [comment]
Not the latest. Could you upgrade to 3.9.0 and test?

**Comment by frankok** [comment]
Thanks Frank, that did the trick.
My bad, I should have checked and tested this first… 😊
