### ISSUE TITLE
Refiners not working as expected

### ISSUE THREAD

**Issue by meklulose** [microsoft-search/pnp-modern-search#880]
**Version used**
Ex: 3.18.1

**Describe the bug**
When in the panel filter, the Refiner doesn't seem to remove checked refined item when selecting additional refinement item even though there is no value that matches it. When you start to deselect the refined item, keeping the one that doesn't match the value causes the system to crash. 

**To Reproduce**
1. Search all
2. Click on filters 
3. Select multiple filters from one group
4. Click apply 
5. Select multiple filters from another group (Titlefield)
6. Click apply
**Note: some of the previous selected filters will have no item associated with it so it will be removed from the panel view but not from the filters in search.**
7. Start removing the filters making sure that you do not remove the one with no value. 

**Expected behavior**
The search reset to search without filter

**Actual behavior Screenshots**
![image](https://user-images.githubusercontent.com/81180944/112029001-b073c400-8b30-11eb-8e80-d09809264814.png)

The filter button is gone and no results are being displayed. 

**Desktop (please complete the following information):**

**Comment by wobba** [comment]
I assume you are running with OR between filter values? Did you have this issue before or a newly discovered one? 

And it's a state nightmare to fix. Because if you removed fem group 2 you'd expect to get to the first selected ones probably...which is then not possible if they are removed.

**Comment by meklulose** [comment]
Yes we are running with OR between filter values. We have had this issue since the start. Is there any workaround for this? Is there way to keep the filter button available so the user can go in and clear all the filters? Right now the button also disappears.

**Comment by wobba** [comment]
No clear workaround, and OR filters + state is not fun to code. I'll tag it as an enhancement if someone wants to give it a go.

**Comment by wobba** [comment]
Won't add to v3.
