### ISSUE TITLE
"Link to item" missing in manage columns (search results)?

### ISSUE THREAD

**Issue by mthanos7** [microsoft-search/pnp-modern-search#883]
**Version used**
Ex: 4.10

**Describe the bug**
I just got around to updating an old build that used v3 to now use v4. I noticed that the option to make a column "link to item" is no longer available in v4. Was this changed and is there still functionality to make column items linkable?

**To Reproduce**
1. Add Search Results web part
2. Navigate to page 2
3. Press "Manage Columns"
4. Option for "Link to Item" no longer available in v4, where this was an option in v3

**Expected behavior**
Would like for any given items in a details list to be hyperlinked so that a user could navigate to said item. Demos I've seen of this new v4 build show that the items are hyperlinked immediately out of the box, but my items in the details list somehow are not hyperlinked. I am able to to check "link to item" in v3 to achieve this behavior.

**Desktop (please complete the following information):**
 - Brave, Firefox

**Comment by FranckyC** [comment]
This option has been removed in v4 yes. In v4, you can update the HTML of the 'Title' column and insert your `href` here:

![image](https://user-images.githubusercontent.com/5659122/114040367-8c62f300-9851-11eb-9ac8-4277ad0ee771.png)

The href in here by default.
