### ISSUE TITLE
Search reverting back to previous search when using pagination

### ISSUE THREAD

**Issue by thebigs1992** [microsoft-search/pnp-modern-search#884]
__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

V3.18.1

When starting a new search having previously searched something and used the pagination it will return to the old search when using pagination with the new search

1. Search all
2. Click on Page 2
3. Search for something else (search goes to new search)
4. Go to Page 2 (reverts back to old search)

**Expected behavior**
Search will continue with new search when on next page

![image](https://user-images.githubusercontent.com/81215561/112106564-c1125180-8ba5-11eb-8ee5-3faca588c5d9.png)
![image](https://user-images.githubusercontent.com/81215561/112106808-09ca0a80-8ba6-11eb-96d8-154c50ab53ce.png)
![image](https://user-images.githubusercontent.com/81215561/112106914-2d8d5080-8ba6-11eb-85ce-dbe16326885c.png)

 - Browser tested in chrome

**Comment by wobba** [comment]
I have repro and have to figure out the best approach as it impacts sorting as well.

**Comment by wobba** [comment]
You can test a fix in the branch https://github.com/microsoft-search/pnp-modern-search/tree/wobba/v3-fixes.

**Comment by thebigs1992** [comment]
That looks to work a treat, thanks so much :). Will keep testing. Really interesting reading through the code trying to figure out how it all works haha

**Comment by wobba** [comment]
@thebigs1992 Fixing these things in v3 is not fun as the codebase is not optimal and you patch on patching sort of. The caveat with my fix is that you get two API queries for some user scenarios - but figured that was better to ensure all UX components were in proper sync.
