### ISSUE TITLE
v3.17 Search page not properly displaying Search web part

### ISSUE THREAD

**Issue by naufalCA** [microsoft-search/pnp-modern-search#886]
I'm facing an issue with the search page using v3.17 of the PnP modern search. I'd like to emphasize that it was working in the past few days and it has suddenly stopped working. Currently it throws the following error message in the console.

`Access to XMLHttpRequest at 'https://waconatm.officeapps.live.com/apc/trans.gif?d3ec553e88ca7eba31a549ee8124a6b3' from origin 'https://xxx.sharepoint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

@wobba, @stevebeauge @PooLP  @mbice  @sympmarc I really appreciate if you can provide me with your support because the site is currently in production and it is used by so many people within the organization.

**Comment by wobba** [comment]
1. You disregarded the bug template 
2. If it was working it's not a web part issue 🙂

**Comment by sympmarc** [comment]
And just to add - that error is some other part of Microsoft's stuff. @wobba - It would be great if you could get people over there to fix all their bugs!

**Comment by wobba** [comment]
@sympmarc filing APi issues via support to get proper escalation is usually better. If I have repro I can always log it, but without repro it's hard. Which componet caused the call, how, and what is the error and correlation etc.

**Comment by sympmarc** [comment]
@wobba Always hard to tell where all the errors in the console are coming from. It's getting a lot worse than it used to be.

**Comment by sympmarc** [comment]
And yes, I know I'm off on a tangent here.

**Comment by wobba** [comment]
In general if things suddenly change behavior, it's a platform thing, and not open source's fault 😇
