### ISSUE TITLE
URLToken query variable uses REST url and not page url

### ISSUE THREAD

**Issue by vandest** [microsoft-search/pnp-modern-search#89]
It seems that the URLToken query variable uses https://siteurl/_api/search/postquery, not the current page URL. Is this a limitation or bug?

**Comment by FranckyC** [comment]
Hi @vandest you're right. Actually these token are processed server-side by SharePoint so it seems it takes the calling URL not the context URL. To resolve this issue we would need to right our own token parser. I'll see what I can do.

**Comment by FranckyC** [comment]
@vandest This should be fixed in the develop branch.
