### ISSUE TITLE
file type filter displays as docx, doc, xlsx rather than Microsoft Word, Microsoft Excel etc..

### ISSUE THREAD

**Issue by ravinleague** [microsoft-search/pnp-modern-search#890]
The OOTB Search page has a file type filter that displays file types as PowerPoint, Word, Excel, OneNote, PDF, Photo etc....
However, the pnp v4 search refiner web part displays this as docx, doc, odf, xlsx etc. Is there a way or a future plan to maintain consistency that matches the file types as the OOTB one ?

OOTB Search.aspx
![image](https://user-images.githubusercontent.com/18733308/112462548-e7560e00-8dac-11eb-8d41-610060dae101.png)

PnP search v4 Search Filter Web part
![image](https://user-images.githubusercontent.com/18733308/112462645-048adc80-8dad-11eb-9c29-845c844cf177.png)

**Comment by wobba** [comment]
OOB uses a static filter, not driven by results. Currently no plans but you can create a web component to accomplish this. Or if someone decided to build one and contribute we'll happily take it :)

**Comment by ravinleague** [comment]
@wobba  - When you say web components, do you mean SPFX React Component ?

**Comment by wobba** [comment]
https://developer.mozilla.org/en-US/docs/Web/Web_Components

can be built in React if you want. We have sample docs at https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_web_component/

**Comment by ravinleague** [comment]
Ok thanks. Is there like a go-to place for any help documentation regarding creating web components and passing data to other web parts like search results?

**Comment by wobba** [comment]
See the links I gave you :) Tells you how to create a component and pass data inn via JSON. You can also look at components in the web part itself for inspiration like https://github.com/microsoft-search/pnp-modern-search/blob/main/search-parts/src/components/IconComponent.tsx
