### ISSUE TITLE
V4.1 Combining Multiple Refiners not working

### ISSUE THREAD

**Issue by myatix** [microsoft-search/pnp-modern-search#891]
Hi Guys,

Great work on releasing V4.1 of the PnP Modern Search solution.

I just wanted to point out that I think a new bug has been introduced to the PnP Refiner webpart. There appears to be a bug resulting in only being able to refine results using a single refiner. If you select a second refiner then this doesn't reduce the result set as expected.

I would expect to only have 2 results showing in the screenshot below.

![image](https://user-images.githubusercontent.com/48433526/112461546-4fcace00-8d60-11eb-8df2-5caaeeeb7fb7.png)

Browser: Edge Chromium, Google Chrome

**Comment by Laul0** [comment]
Hi @myatix,

I tried on my side to reproduce your issue.

In my case, I created:
* Site Column: Manufacturer (Choice)
* Content Type: Car (inherit from `Site Page`)
    * I added the Manufacturer column into this content type
* Update Search Shema to include Manufacturer as `RefinableStringXX`

Once the Modern search was configured, it seems works like a charm:

| Select Car filter | Select Manufacturer |
|------------------|-----------------------|
| ![GitHub-msv4-issue891-01](https://user-images.githubusercontent.com/15279205/112855465-d2170300-907c-11eb-9e8d-ea3d9f4a13e7.PNG) | ![GitHub-msv4-issue891-02](https://user-images.githubusercontent.com/15279205/112856262-992b5e00-907d-11eb-8c13-0d1b33035fdb.PNG) |

In accordance with your issue, it seems your default operator is "OR". From your filters Web Part, ensure the operator is effectively configured at "AND":

| Global Filter Web Part Operator | Operator between values |
|------------------|-----------------------|
| ![GitHub-msv4-issue891-03](https://user-images.githubusercontent.com/15279205/112856515-dd1e6300-907d-11eb-94d9-9afbdef8065f.PNG) | ![GitHub-msv4-issue891-04](https://user-images.githubusercontent.com/15279205/112856822-325a7480-907e-11eb-91bf-3f1131f5b198.PNG) |

Hoping this information will help you 😉

**Comment by myatix** [comment]
Thanks for the feedback...
