### ISSUE TITLE
Search Results flashes

### ISSUE THREAD

**Issue by frankok** [microsoft-search/pnp-modern-search#893]
**Version used**
3.14.1, 3.16, 3.18.1

**Describe the bug**
When performing a search using the search box, the Search Results starts to flash or flicker. Please see attached video file for demo.

**To Reproduce**
1. Go to a page
2. Add a Search Box and a Search Results WebPart. Connect the two.
3. Perform a search, and press Enter
4. The Search Results flashes with a circle icon indicating it's loading repeatedly

**Expected behavior**

**Screenshots**
Screenshot of Network traffic:
![image](https://user-images.githubusercontent.com/20436301/112542800-4a4ba300-8db5-11eb-8d5f-5d64936165cf.png)

**Desktop (please complete the following information):**
- Windows 10
- Google Chrome
- SharePoint Online

**Additional context**
Please see attached screen recording for more info:
[Modern Search Results flashes - demo.zip](https://github.com/microsoft-search/pnp-modern-search/files/6207832/Modern.Search.Results.flashes.-.demo.zip)

**Comment by wobba** [comment]
Cannot repro and I do this setup all the time. Can you repro on multiple sites/tenants? Any other spfx running on the page/site etc.

**Comment by frankok** [comment]
I tried on my dev tenant now, which I created only a few months back. This had only a couple of custom spfx solutions installed, which I removed.
Added Modern Search WebParts 3.18.1, and the result was the same.

Could it be a conflict with a new SPO update recently rolled out?

Mvh / Kind Regards,
Frank-Ove Berg Kristiansen
Konsulent
Mobil +47 48019794

**Comment by frankok** [comment]
This was the third tenant I tested on, BTW.

**Comment by Coligor** [comment]
I may have the same issue: I have a tenant with about 12 sites/homepages with search webparts installed. Everywhere on these modern sites the webparts stopped working: the results wp flashes and no results are shown, on existing terms.
The webparts worked for months (since May 2020) without problems 
'classis search' is still working (classic homepage root site search box) and also I get results in the Query Builder

setup 12 sites:
homepage with search box. Search redirects to results page in site with result wp, filter wp and box wp. I search within each site under a custom Result Source, with a query like:
{searchTerms} path:https://tenantname.sharepoint.com/sites/document* path:https://tenantname.sharepoint.com/sites/sitename -contentclass: STS_List_*


in edit mode the webpart shows 'no results for this query' on any term

**Comment by wobba** [comment]
Might coincide with something rolling out..will check.

**Comment by wobba** [comment]
Tried in two tenants using v.3.18.1, and cannot repro with:

* New page
* Add search box wp
* Add result web
* Connect them 
* Search + ENTER
* I get results

What kind of sites are you using? I test comm and modern team site.

If someone has a demo tenant to share ping me somewhere and share details.

**Comment by wobba** [comment]
@Coligor PnP Search Box or nav bar search box?

**Comment by Coligor** [comment]
@wobba: Both. First checked on PnP Search box, but they're connected. 
When I change the result wp connection to include 'query' in page environment, I get results, but bypassing the Resukt source. Might be result source in conjunction with search index, or, page environment cannot read/use the Result source (GUID)
both give results based on this workaround..but too many..

**Comment by wobba** [comment]
Let me try to hook up a result source id. Without repro it's hard to figure out the issue.

**Comment by wobba** [comment]
No repro :(

**Comment by frankok** [comment]
@wobba, I can send you a PM with login info. Where should I send it?

**Comment by wobba** [comment]
E-mailed your live account

**Comment by wobba** [comment]
Seems related to `import { isEqual } from '@microsoft/sp-lodash-subset` not comparing correct.. digging into it.

**Comment by wobba** [comment]
Waiting for redmond to wake up. It's easy enough to work around the bug in the web parts - but sort of doesn't help all deployed solutions.

**Comment by wobba** [comment]
Issue is acknowledged, but not sure how/when it will be fixed. Pushed v.3.18.2 as a workaround for the issue.

https://github.com/microsoft-search/pnp-modern-search/releases/tag/v3.18.2

@frankok let me know if this fixes it in your tenant.

**Comment by frankok** [comment]
This did the trick. The search results now loads and appears as expected.
Thank you for awesome and speedy service!

**Comment by Coligor** [comment]
Hi Michael,
I also installed the bug fix and it works now as expected. 
Awesome response and speed..  Thanks!
