### ISSUE TITLE
[Question] Search Filter templates - more options in documentation

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#894]
Hi,

I'm looking at the 3.x documentation for Search Filters: https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-filters/. At the bottom of the page, it talks about Filter layouts and Templates. Is this an old feature? I am not seeing a Filter layouts option in 3.17 or 3.18.

I'm looking at this because it appears that you can use Container Tree to provide a nested metadata heirarchy filter option. I'm working on mapping geography, which is a nested metadata field (Americas > North America > Canada ...). I'd like the users to be able to see the nested list to select from, but this doesn't appear to be a current option. Am I just missing something, or is this feature deprecated?

Thanks!

**Comment by wobba** [comment]
This one you mean? Setting per refiner you pick.
![image](https://user-images.githubusercontent.com/51104/112624871-73f4e080-8e2e-11eb-8db4-7ab4f0aa0de6.png)

If you follow the directions, is this not working for you?

**Comment by bryllyg** [comment]
Ugh, I totally missed that. Apparently I needed more coffee ;-) Sorry for the additional churn. Thanks!
