### ISSUE TITLE
Search Results for v3.18.2 in IE11

### ISSUE THREAD

**Issue by thebigs1992** [microsoft-search/pnp-modern-search#900]
**Version used**
3.18.2

**Describe the bug**
I know this is in IE11 and its not really supported. When i open search page in IE11 and do a search, the search results appear blank yet the search filters etc. are showing like there is results.

**To Reproduce**
Search box using Url Fragment and connected to a Search Results with the following query {searchterms} * connected to Search Box and Filters using the Details List layout(have also tested other layouts and get same result)
 
1. Open in IE11
2. Search something in IE11

**Expected behavior**
Search results should appear

**Screenshots**

![image](https://user-images.githubusercontent.com/81215561/113000488-c94f2b80-9167-11eb-9f0a-4f810a661e12.png)
![image](https://user-images.githubusercontent.com/81215561/113000980-4084bf80-9168-11eb-8835-64249b5c1f02.png)
![image](https://user-images.githubusercontent.com/81215561/113001041-52666280-9168-11eb-9ac6-404c99b9921f.png)
![image](https://user-images.githubusercontent.com/81215561/113001194-7b86f300-9168-11eb-8333-b336fea7f76d.png)
![image](https://user-images.githubusercontent.com/81215561/113001296-948fa400-9168-11eb-843e-ecd605a81caa.png)

**Desktop (please complete the following information):**
 - Browser IE11

**Additional context**

I've checked the standard issues pollyfil, core.js but can't seem to pinpoint what is going on. As it's IE11 I am happy to help so can point me in the right direction to fix :)

**Comment by wobba** [comment]
You need to provide a bit more info like console log errors etc. And, not a priority to fix IE11 issues. It's an old browser and should not be used, and also it will stop being supported in M365 in August.

**Comment by thebigs1992** [comment]
I completely agree that it should not be used. It's for a client, they are still using Windows 7 and i am trying my hardest for them to move away from it to no avail. The error i get in dev tools is _Unhandled promise rejection TypeError: Cannot redefine non-configurable property 'options'_

**Comment by wobba** [comment]
Can you share exact repro steps? Those provided are a hit vague as to webpart config.

**Comment by thebigs1992** [comment]
Googling i don't get exact error but TypeError only seems to reference Polyfill. I can see there is polyfill-ie11 imported, is there an options property within this that is failing somewhere?

**Comment by wobba** [comment]
I get the same error you have but it's not helpful at all in order to track down what could cause it. I think we officially leave IE11 behind at this point. It's not related to IE11 and SP calls, but probably something trivial somewhere.
