### ISSUE TITLE
Question on Search Ranking and Frequency of Hits

### ISSUE THREAD

**Issue by ultrawide** [microsoft-search/pnp-modern-search#901]
This may be related to SharePoint Search in general, rather than pnp-modern-search.

**Is your feature request related to a problem? Please describe.**

It looks like there are no properties to display the number of times a term was matched per search result item. I would like to aggregate the number of times a search term was hit for a document set and its contents. 

**Describe the solution you'd like**

I would like the search result item to contain a property for the number of times a term was hit.

Example: A document set named 'Quick Document Set' contains a text document which has the content 'The quick brown fox jumps over the lazy dog'. I would like the search result to contain a property: ` "HitFrequency": 2 ` The number 2 is calculated by the number of matching terms: Document Set Title, Content of Text File

**Describe alternatives you've considered**

- Looked into the Ranking Details using the SharePoint search query tool, but was unable to find something that appears to help
- Explored HitHighlightedSummary, but it gets information specific to the document set without its contents

**Comment by wobba** [comment]
Not directly part of the search API's. The rank details page in 2013 (also available via the SP Search Query Tool) gives some info, but requires admin permissions to get data, and this feature will most likely go away online. See this post for some info https://blog.mastykarz.nl/understanding-item-ranking-sharepoint-2013-search
