### ISSUE TITLE
Preview inner close redirects users to document library

### ISSUE THREAD

**Issue by ishaisagi** [microsoft-search/pnp-modern-search#902]
I do not think you can avoid this, but you should know that when people click the "X" inside the preview
![image](https://user-images.githubusercontent.com/32532384/113065743-11705b80-9205-11eb-8617-5a2d1f9ade4d.png)
the browser redirects to the document library the document is in.

I have not found a way to construct the URL of the iframe (https://[document full path]?web=1) in a way that does not show that X or that changes its behaviour. If someone has any advice on that, it would be great.

I would suggest not using the ?web=1 preview (as useful as it is) and instead loading the document's interactive preview :
https://[site url]/_layouts/15/WopiFrame.aspx?sourcedoc={[List item GUID]}&action=interactivepreview

**Comment by ishaisagi** [comment]
Update - I have confirmed the [List item GUID] is the managed property "UniqueID"
I achieved a better result by changing (in the layout template) the data-preview-url property of the pnp-filepreview tag to
<pnp-filepreview data-preview-url="**[SITEURL]/_layouts/15/WopiFrame.aspx?sourcedoc={{UniqueID}}&action=interactivepreview**"

**Comment by wobba** [comment]
Will be fixed in the next release as I reworked the interactive preview code. If that preview page shows, we cannot really control the behavior once in a frame. The change is similar to what you do, but use the value from `ServerRedirectedEmbedURL`.
