### ISSUE TITLE
Search Results web part connection to Search Query is getting dropped

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#903]
**Version used*
3.17

**Describe the bug**
Similar to Issue [299](https://github.com/microsoft-search/pnp-modern-search/issues/299). Twice over the last week, our Search Results web parts, on two different sites, have lost their connection to the Search Query. In both cases we get reports from users that search is not filtering results based on their search query, and that the "# results for "<query>" is showing the query as "*", which is our default query.

**To Reproduce**

1. Configure Search Results web part as follows: 
2. Connect to source = Page environment
3. Page environment's properties = Search
4. Search = Search query
5. Use a default search query = selected
6. Default Search query = *
7. Wait....

This worked fine for months. It's just in the last week that the connection has stopped working on two different site collections, our "dev" site collection and our "prod" site collection.  If we have a report that one has stopped working, the other has also stopped working.

![image](https://user-images.githubusercontent.com/2616432/113071544-d07f3500-9179-11eb-9643-4b0e6db448f9.png)

When we go look at the Search Results web part, the Page environment's properties and Search fields are blank. Re-selecting those and Republishing resolves the problem, until the next time.

**Expected behavior**
User enters search query into default O365 search box, query is sent to PnP Search Results web part and results are displayed. This behavior does not change.

**Screenshots**

**Desktop (please complete the following information):**
Current versions of Edge and Chrome

**Additional context**
We will be upgrading to 3.18 this coming sprint, and I'll update this bug if we still see this behavior.

**Comment by wobba** [comment]
Next time you see the error, can you via powershell export the webpart configs before editing the page? To see if the config is actually there, but not being read/used for some reason. Seems weird that it should suddenly drop. Can you also check if there has been other edits to the page? And when it happens, refreshing does not work..to rule out intermittent issues.

Trying to figure out if dynamic data in SPFx is causing it, or if page data is changing the behaviour. As it's on two site collection it seems related to SPFx somehow, but uncertain what.

**Comment by bryllyg** [comment]
Shall do. I checked the page edit, and it's just me updating on the Dev site page, but no recent updates to the Prod site page. It's odd that it would just start up after working smoothly for a few months. Re refresh, we tried multiple users and browsers and still saw the same problem. I'll check it again if/when it crops up again, and will export the webpart config before editing. Thanks!

**Comment by bryllyg** [comment]
RE powershell, use export-csv?

**Comment by wobba** [comment]
There are some samples on how to do this at  https://docs.microsoft.com/en-us/microsoft-365/community/working-with-modern-clientside-pages-using-pnp-powershell#now-we-want-to-modify-another-page-homeaspx

**Comment by bryllyg** [comment]
Thanks!

- Heidi
