### ISSUE TITLE
Vertical filter webpart : Field name look&feel

### ISSUE THREAD

**Issue by hervedorierai3** [microsoft-search/pnp-modern-search#904]
**Version used**
v4

**Describe the bug**
A little style issue in the vertical layout of the filter webpart.
The style of the field name label is not always the same.

**To Reproduce**
1. When use the Filter webpart
2. Choose "Vertical" layout.
3. Create a "Combox" filter.
4. Create a "Checkbox" filter.
2. See the field name hasn't the same look and fied.

**Expected behavior**
Having the same fieldname look and feel when a filter is either "ComboBox" or "CheckBox".

**Screenshots**
![image](https://user-images.githubusercontent.com/68116737/113205281-63999700-926e-11eb-8012-d911bec90724.png)

**Desktop (please complete the following information):**
 - Edge

**Additional context**
Here is the issue in the tempate : 
![image](https://user-images.githubusercontent.com/68116737/113206185-71035100-926f-11eb-8a3e-271254a23152.png)
=> The 'font-size' shouldn't having the 'px' string because it's in the JSON : 
![image](https://user-images.githubusercontent.com/68116737/113207736-44e8cf80-9271-11eb-9b93-1e28149470ee.png)

**Comment by wobba** [comment]
Fixed for next release and thank you :)
