### ISSUE TITLE
Error when combining multiple refiner filters in search results

### ISSUE THREAD

**Issue by scara1701** [microsoft-search/pnp-modern-search#906]
**Version used**
4.1.0.0
**Describe the bug**
Everytime I combine multiple KQL queries in the refinement filters of the search results webpart there is an Error 400

**To Reproduce**
1. Add a search result webpart
2. Add a refinement filter of format -> filetype:pdf -> works
3. Replace refinement filter with -> Path:"{url of document library}/*" -> works
4. Combine above filters -> Path:"{url of document library}/*" filetype:pdf -> Error 400 in Search Results

**Expected behavior**
Combination of above KQL filters should not end up in an error 400

**Screenshots**
Just KQL for the filetype
![filetype_works](https://user-images.githubusercontent.com/31825690/113282262-fa099f00-92e6-11eb-8ea1-72c53b5b3b84.png)
Just KQL for the path
![path_works](https://user-images.githubusercontent.com/31825690/113282274-fd048f80-92e6-11eb-873a-67f352363c13.png)
Error when above is combined
![combined_fails](https://user-images.githubusercontent.com/31825690/113282280-ff66e980-92e6-11eb-9b28-5cb7d9da11c0.png)

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**
Above KQL seems to work in "Highlighted content" webpart.

**Comment by FranckyC** [comment]
Hi @scara1701 , for refinement filters, you should use [FQL ](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/fast-query-language-fql-syntax-reference) instead of KQL for multiple conditions. So something like this:

```
and(Path:"{url of document library}/*", filetype:pdf)
```

**Comment by scara1701** [comment]
Hi FrankyC,

`and(Path:"doc libary url/*", FileType:equals("pdf"))`

Works like a charm. Thanks!
