### ISSUE TITLE
FileName sort is not working

### ISSUE THREAD

**Issue by guptarajesh001** [microsoft-search/pnp-modern-search#908]
ersion used
Ex: V4

Describe the bug
When Search returns many results, broken into several pages in Detail layout, sorting sorts correctly only on few of pages, not all of the results.

To Reproduce

create a search result web part
use the Detail layout
create a search that returns paged results
Click the "Edit sort order" to define the sorting on "FileName"
![image](https://user-images.githubusercontent.com/13049898/113383716-20d8db80-93a2-11eb-9635-e1cca1625b84.png)

Expected behavior
sorting results with multiple pages should sort all results

Screenshots
![image](https://user-images.githubusercontent.com/13049898/113384148-0ce1a980-93a3-11eb-8b1c-4415594f5c54.png)
![image](https://user-images.githubusercontent.com/13049898/113383789-4b2a9900-93a2-11eb-8034-c11d7c8583e4.png)
after the 5th page its again restart to sort the documents, which weren't sort initially:
![image](https://user-images.githubusercontent.com/13049898/113383947-9a70c980-93a2-11eb-8726-a76572b19f59.png)

**Comment by wobba** [comment]
Can you repro outside of the PnP web parts? Tested with page size 500 and I can page just fine. Would be interesting to see the JSON request for the page which starts failing which is needed to see if it's the request which is wrong, or if it's the API ignoring it.

**Comment by guptarajesh001** [comment]
Thanks wobba, could you ellaborate on repro outside of the PnP web parts?  We have debugged the code and found search query as follows:                                                                                                                                                                
searchQuery: Object
ClientType: "PnPModernSearch"
Culture: 1033
EnableNicknames: false
EnablePhonetic: false
EnableQueryRules: false
Properties: (6) [{…}, {…}, {…}, {…}, {…}, {…}]
QueryTemplate: "{searchTerms} (DepartmentId:{aaaaafbc-95ad-4fce-adf9-ea96f18e9541}  OR DepartmentId:aaaaafbc-95ad-4fce-adf9-ea96f18e9541) IsDocument:True  (contentclass:"STS_ListItem_DocumentLibrary" OR contentclass:"STS_ListItem_WebPageLibrary")"
Querytext: "document"
RefinementFilters: []
Refiners: "FileType,RefinableString00,RefinableString01,RefinableString02"
RowLimit: 10
SelectProperties: (24) ["AuthorOWSUSER", "ContentTypeId", "Created", "CreatedBy", "DefaultEncodingURL", "Filename", "FileType", "HitHighlightedSummary", "JobTitle", "NormListID", "NormSiteID", "NormUniqueID", "owstaxidmetadataalltagsinfo", "Path", "RefinableString00", "RefinableString01", "RefinableString02", "RefinableString03", "SiteTitle", "SPSiteUrl", "Title", "UniqueID", "UserName", "WorkPhone"]
SortList: Array(1)
0: {Property: "Filename", Direction: 0}
length: 1
__proto__: Array(0)
SourceId: "8ab4eddddd00-b54d-11efd9abdb89"
StartRow: 0
TimeZoneId: 13
TrimDuplicates: false

**Comment by wobba** [comment]
Seems StartRow is somehow 0 for page 6.. which is weird. StartRow should be pagesize * pagenumber. I changed how paging works for the upcoming v3.19 release - so that might solve it for you.

**Comment by wobba** [comment]
@guptarajesh001 have you checked further..if not we'll close the issue as we don't have repro.
