### ISSUE TITLE
Default activate a vertical not working

### ISSUE THREAD

**Issue by VerlindenEAM** [microsoft-search/pnp-modern-search#909]
**Version used**
3.18.3

**Describe the bug**
According to the manual you can default activate a vertical, but this doesn't seem to work:
Parameter to pick up from the query string to default activate a vertical. Matches the name of the tab. Enter v if you for pass in v=People as part of your URL to match a vertical named People.

**To Reproduce**
Default vertical querystring parameter 
v=People

**Expected behavior**
When opening the page, the People vertical should be set by default.
Could not find clear information how to set this up.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]; Edge Chromium

**Additional context**
Also tried adding to the URL ?v=People

**Comment by wobba** [comment]
Seems to work just fine with this config.
![image](https://user-images.githubusercontent.com/51104/113426995-89d94700-93d4-11eb-8e2a-390df624e7a7.png)
![image](https://user-images.githubusercontent.com/51104/113427075-b8efb880-93d4-11eb-94bb-f369d1e960d6.png)

Url is `Apage.aspx?v=people`

**Comment by VerlindenEAM** [comment]
I guess wrong usage, will try again
Maybe add the screenshot to the docs.

Regards,
Erwin


________________________________

**Comment by wobba** [comment]
We could 🙂 If you think the current text highlighting `v` could be improved, feel free to propose something.

**Comment by VerlindenEAM** [comment]
No need to improve, clear for now! Thanks
