### ISSUE TITLE
Search results - sortable fields improvements

### ISSUE THREAD

**Issue by joelfmrodrigues** [microsoft-search/pnp-modern-search#91]
I am currently configuring a search page for a client and they have provided some feedback that I found valid, so sharing here to start the discussion on possible improvement points

#### 1. Default dropdown label

The default dropdown label for sortable fields is "Select a field". It would be more user friendly with something like "Sort By"

![image](https://user-images.githubusercontent.com/19577724/74335343-e7a36d80-4d93-11ea-88ff-d430440296fb.png)

![image](https://user-images.githubusercontent.com/19577724/74335370-f68a2000-4d93-11ea-8279-f64d4281f886.png)

#### 2. Default dropdown value

If a field is used as the default sorting on the results web part, it would be great if the sortable fields dropdown would automatically default to that field and order (assuming the same field is added on both sort configuration options). 

#### 3. Default sortable field direction

It would be great if a sortable field could be configured to have a default direction.
As an example, if you currently want to add a sortable field of date/time (for instance Modified), it will be ascending by default, which is unlikely to be the desired result so users have to always invert the direction.

#### 4. First dropdown selection

When selecting a sortable field for the first time, the dropdown automatically defaults to the first option, which is quite inconvenient.

**Comment by FranckyC** [comment]
Thanks for your feedback @joelfmrodrigues. I'll what I can do for the next release.

**Comment by joelfmrodrigues** [comment]
Do you know roughly when will be the cut off date for PRs to be included on the next release?
I could try to help with some of this depending on timings as I will be off work

**Comment by joelfmrodrigues** [comment]
Sorry closed by mistake... Doesn't ask to confirm and it's easy to hit the close button by accident on the phone

**Comment by FranckyC** [comment]
Next release will be at the end of the month. You can submit a PR to fix this if you have time.

**Comment by joelfmrodrigues** [comment]
@FranckyC Just trying to run the solution locally and everything seems to be fine, except that search box and search results web parts are not available to add to the workbench page. All other web parts are available. Any idea why this may happen?

**Comment by joelfmrodrigues** [comment]
All sorted...it was an issue with my tenant...

**Comment by FranckyC** [comment]
@joelfmrodrigues Could it be considered as resolved according to your PRs?

**Comment by joelfmrodrigues** [comment]
My PRs cover points 1 and 4. I should have created  separate items for each point, sorry for the mess 😕
If you want to close, I will open separate items for 2 and 3.

**Comment by FranckyC** [comment]
Yes please ;). I close this one for now
