### ISSUE TITLE
Vertical query template not working with OR

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#910]
**Version used**
Ex: 3.17

**Describe the bug**
I'm trying to target the results in a search vertical by modifying the vertical's Query Template field. I'd like results to show if either the TopicOwner or TopicSecond field contains the query string name parameter, but it does not seem to work. I can get it to filter by one or the other, but when I try using OR, it completely ignores the second options.

Query Template:  {searchTerms} (TopicOwnerOWSTEXT:{QueryString.name} OR TopicSecondOWSTEXT:{QueryString.name})

Do I have the syntax wrong (I use it often in the SharePoint Search Query tool), or does it not allow comparison operators?

**To Reproduce**

1. Set up a list with two single line of text fields. 
2. Enter a few name into each field, make sure at least one name exists in both fields, in different rows.
3. Set up a Search Vertical and Search Results web part.
4. Configure Search Results to accept a query string parameter called 'name'
5. Use the Details list results layout
6. Update Manage Columns to include the two single line of text fields noted above (in this case, containing names)
7. Edit the Search Vertical web part
8. Update the vertical's Query Template to {searchTerms} (TopicOwnerOWSTEXT:{QueryString.name} OR TopicSecondOWSTEXT:{QueryString.name})
9.  enter a url query that includes ?name=<a name that exists in both fields>
10. Note that only the first field results are returned (TopicOwner). The same name in the second field (TopicSecond) is not returned.

**Expected behavior**
Items that have the query string name in either the TopicOwner OR TopicSecond field are displayed.

**Screenshots**

**Desktop (please complete the following information):**
Current version of Edge and Chrome

**Additional context**

**Comment by wobba** [comment]
Tested this and I see the QueryTemplate field of the search query being replaced when I have `?name=foo` in the URL

`{searchTerms} (TopicOwnerOWSTEXT:{QueryString.name} OR TopicSecondOWSTEXT:{QueryString.name})`

turns into

`{searchTerms} (TopicOwnerOWSTEXT:Foo OR TopicSecondOWSTEX:Foo)`

Can you inspect the `postquery` network call and see if you see the expansion being correct or not?

**Comment by bryllyg** [comment]
I just re tested a few times and can't reproduce the problem now. The filters work and the postquery is showing as expected. Not sure what was up the other day, it simply would not work. All better now though.

**Comment by wobba** [comment]
v3.19 has some fixes related to nav switch and paging as well.

**Comment by sanazubair-debug** [comment]
how to combine two list in one vertical tb of search query template, should i also use OR opertaor for combining two ist content type id

**Comment by wobba** [comment]
@sanazubair-debug Please do not ask generic questions on closed issues. 

And OR is the way. See https://www.techmikael.com/2014/03/s15e01-kql-basics.html and https://sharepoint.stackexchange.com/questions/96777/search-results-from-only-contenttype-x
