### ISSUE TITLE
Filters dont appear

### ISSUE THREAD

**Issue by levalencia** [microsoft-search/pnp-modern-search#914]
**Version used**
4

**Describe the bug**
I created a property Keywords with a managed property Keywords (type: Managed Metadata).  If I type keywords:keyword1 in the search bar of this webpart it works perfectly fine.   However when I add it to the filters, it wont appear on the refiner webpart.

**To Reproduce**
1. Add Keywords column to a site page library (Managed metadata field)
2. Add some pages with keywords 
3. Add searchbox webpart and filters webpart
4.  Add property Keywords in filters webpart

**Expected behavior**
A list of keywords should appear on the filter webpart to refine the results

**Screenshots**
the new field wont appear

**Desktop (please complete the following information):**
Chrome

**Comment by wobba** [comment]
`Keywords` is an existing managed property, but it's not refinable. You need to use refinable managed properties as filters.
