### ISSUE TITLE
Add PNP Search Box to Library View?

### ISSUE THREAD

**Issue by dirkzwart** [microsoft-search/pnp-modern-search#915]
My apologies, I couldn't find where to submit general questions. Is it possible to add a Webpart/custom code to a modern Library view? I would like to add the PNP Modern Search box to the top of a Library view. I would like a separate search box and not changing the search center to interfere with the default search box at the top of the page. Tweaking the HTML in Allitems.aspx using SharePoint Designer has not yet yielded the custom search box in the view (I have only managed a line of text to appear).

**Comment by wobba** [comment]
No :)
