### ISSUE TITLE
Read only user do not get search results

### ISSUE THREAD

**Issue by pjurski87** [microsoft-search/pnp-modern-search#916]
**Version used**
3.18

**Describe the bug**
When new user gets created and placed into Site Visitor permissions with only read only access. Search results in the pnp search results do not show up for that user. Users that have Edit functionality has no issues with the web part. Reindexing the site does nothing to fix this. 

**To Reproduce**
1. Create user with no licence in Office 365 admin
2. Add user into "Site Name Visitor" permissions
3. Go To site and search using the pnp modern search box
4. Search results do not show up anything

If user gets placed into editor permissions, search results show up.

**Expected behavior**
Search results showing up for read only user

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**
Re-indexing the site does nothing.

**Comment by pjurski87** [comment]
@wobba It seems to be the case here, it took long time to get any results, the re-index only occurred once I forced the Site Pages document library re-index and the site re-index and waited a long time. This is a bit inconvenient because if we add high level user that needs to search right away, they will think the site search is broken and looks terrible on my end. Is there anything that can be done to speed up the reindexing? or another way that can produce search results right away. 

I see that there is v4 in development would that help the situation?

Thanks for the response! Appreciate it!

**Comment by pjurski87** [comment]
Also, when I tested with additional user accounts that has visitor permissions, I realized that It seemed to not have any search results for days. It only fixed the problem once I forced the reindex. That's another issue because if a new user gets created, we will need to force re-index each time and that's tedious.

**Comment by wobba** [comment]
Security crawls do run, but not sure on what schedule. It's always better to add users via AD groups compared to direct SP permission. Then it works right away.
