### ISSUE TITLE
Support for Microsoft Search connectors

### ISSUE THREAD

**Issue by kshitijkhanna** [microsoft-search/pnp-modern-search#917]
**Is your feature request related to a problem? Please describe.**
We can configure and show results from various Search connectors(i.e SN connector etc)  in Microsoft search Now.  Can you make it work with PnP search webparts as well

**Describe the solution you'd like**
PnP search supports the Microsoft Search connectors and we can build query and create vertical to pull in content from various sources and show in PnP search too.

**Comment by wobba** [comment]
Version 4 support this. See documentation at https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/#microsoft-search

![image](https://user-images.githubusercontent.com/51104/113911109-df995f00-97d9-11eb-957a-f200abbe37c8.png)
