### ISSUE TITLE
How to filter by datetime using the timezone of the site

### ISSUE THREAD

**Issue by mjbcruz** [microsoft-search/pnp-modern-search#919]
I'm using this query in the search results webpart:
EventDate=Today
It returns events based on UTC time, but we're on UTC+8 so the results before 8am will still return events for yesterday.
How do I filter by date using the local timezone.

What I'm currently doing is getting (EventDate<={Today+1} AND EventDate>=Today) to get yesterday and today's event.
Then on the template i used this condition so that it will only display the today's date(based on site timezone).
{{#eq (getDate EventDateOWSDATE "YYYY-MM-DD") (moment d format="YYYY-MM-DD")}}
However my problem is i want to only display 5 items, how do I do that if i can't set a variable in the template?

**Comment by wobba** [comment]
We can't control how the API backend handles time zones when transforming query variables. Check the time zone of your site and see if that impacts anything. You can try to use this query instead and see if it returns different results:

`EventDate=today OR EventDate=yesterday`

See my post https://www.techmikael.com/2014/03/s15e01-kql-basics.html for supported date keywords in KQL.

**Comment by mjbcruz** [comment]
Thanks for the prompt reply.
I'm using this query "(EventDate<={Today+1} AND EventDate>=Today)" and it works.
On the template I just use this conditional block "{{#eq (getDate EventDateOWSDATE "YYYY-MM-DD") (moment d format="YYYY-MM-DD")}}" to only display the today (based on our timezone). This works well.
My problem now is that I want to limit the number of displayed items to 5 only (for today's event those that will qualify the conditional block). Is there a way to set a variable in the handlebar template so that I can count the number of times it enters the conditional block?

**Comment by wobba** [comment]
@mjbcruz You would have to look into handlebars/handlebars-helpers documentation to see if you can figure out a good way for this. v4 also support custom helpers: https://microsoft-search.github.io/pnp-modern-search/extensibility/handlebars_customizations/
