### ISSUE TITLE
Container Tree: Compact View

### ISSUE THREAD

**Issue by EdgarasKarpavicius** [microsoft-search/pnp-modern-search#92]
Hi,

The container tree is a great addition to the Modern Search refiner web part.

One aspect which I think could be greatly improved is in the case of when the container tree being set to **not** expand by default, and user clicks on container tree header, the tree view 'opens' and displays the folder structures fully expanded, revealing all folders and sub-folders. 

Is it possible for the container tree refinement to display only the first level of folders, which then the user can choose to click through themselves to further 'drill-through into their search.
I have attached a screenshot to be demonstrate what I mean:

![Container Tree](https://user-images.githubusercontent.com/59877249/74419634-23950c00-4e42-11ea-9eb4-8ed9c3587816.png)

Thanks,
Edgar

**Comment by FranckyC** [comment]
Hi @EdgarasKarpavicius. This should be resolved by #98. Now the container tree refiner template follows the "Expand filter by default" option set in the associated refiner configuration.
