### ISSUE TITLE
Search results not loading after forwarding from search box within another page

### ISSUE THREAD

**Issue by HeKr09** [microsoft-search/pnp-modern-search#920]
**Version used**
3.6.3.0

**Describe the bug**
I have got two aspx-SitePages within the same site. The first one contains a search box and sends the query to a new page with the url: https://customer.sharepoint.com/sites/site/SitePages/Customer-Search.aspx.
Within the results page there are refiners, a search box and a search result WebPart.
Most of the time the result is shown as expected but sometimes the result contains the results as if I would search a star (*).

Example:
- Search for "Data Protection"
- Click on search
- Navigating to results page
- Expected results would be 13 but the results are 596

The results WebPart shows:

> 596 results for Data Protection

But if I click again on search within the results page the results WebPart shows:

> 13 results for Data Protection

**To Reproduce**
Steps to reproduce the behavior: See above
The error doesn't occur every time but sometimes.
It also seems that the results WebPart loads several times.

**Expected behavior**
Show the result as found.

**Desktop (please complete the following information):**
 - Google Chrome

**Comment by wobba** [comment]
v3.6 is too old for us to triage bugs on and we won't do patches on it.
