### ISSUE TITLE
Display managed metadata field as tree view in search filters

### ISSUE THREAD

**Issue by rakhigithub** [microsoft-search/pnp-modern-search#922]
I have a requirement to display all the managed metadata terms in a tree view structure in filters.

please suggest is there any option to display the managed matdaata terms in the tree view structure not as checkbox in filter webpart.

**Comment by wobba** [comment]
Nothing implemented, and the returned data don't typically have the full term path.

**Comment by bryllyg** [comment]
Adding to this request. it would be really nice to have the ability to show nested managed metadata in a parent/child format. This is supported when you go to a list/document library and filter. For example:
![heirarchy](https://user-images.githubusercontent.com/2616432/116142042-4948b280-a68e-11eb-84c1-28d2c5f5b24d.png)

**Comment by wobba** [comment]
It's a complicated scenario to solve from the search side as the refiners don't have all data needed to render them. If we were to look up all labels via API calls it would also be very slow.

In a library they read the termset tied to a column - a connection not directly available in search.

A work around would be to have a static taxonomy filter connected to a termset - and use that as the filter - similar to what you have in a library. We'd be happy to include such an option if someone develops it.

**Comment by bryllyg** [comment]
Ah-ha! Libraries are just extra sneaky :-).  Thanks for the explanation, it's very helpful.

**Comment by WardCornetteRFN** [comment]
Dear @wobba ,

Is there any update on this thread? The possibility to show the tree structure of a managed metadata property would by a big improvement for User Experience (even as a filter similar to the libraries instead of a refiner, I understand how that would be slow).

Thanks in advance!

**Comment by wobba** [comment]
No planned work, but a static filter ties to a term set would be the better approach. If anyone is up to do the work feel free :)
