### ISSUE TITLE
Cannot remove Author property in Sharepoint online

### ISSUE THREAD

**Issue by KFOC** [microsoft-search/pnp-modern-search#924]
Using Modern Search web part v3 in Sharepoint, I cannot uncheck the Author / AuthorOWSUSER property. When I do, the property disappears from the results however when I refresh the page, the property is checked again. Reported the issue in Microsoft Community and they were able to reproduce the issue and they advised me to report it here.

**Comment by wobba** [comment]
Please use the bug template when logging. It's there for a reason. That said, the web parts bring back a minimal set of properties needed for the OOB templates. What's your concern that the property is brought back even if you're not using it?

**Comment by KFOC** [comment]
The concern is that we don't want users to see who posted the document.

Then what is the point of the "New issue" button if that is not the right way to do it?

**Comment by FranckyC** [comment]
Hi @KFOC, if you don't want this property to appear in the results, you still have the ability to remove it completely from the Handlebars template. This will create a new custom template. If this change is only targeted to a specific page, you can do this only at Web Part level as the template content will be embed in the properties. However, if the change is global, you can create a new .html file with the customized template content, upload the file in a SharePoint library (with all users with read permissions) and reference it in all Web Parts.
