### ISSUE TITLE
Filters/Refiners in multilingual environment on SPContentType and Site Names

### ISSUE THREAD

**Issue by coupalm** [microsoft-search/pnp-modern-search#925]
**Is your feature request related to a problem? Please describe.**
My request is more a question: Is there a way to display, in a refiner/filter, content type names in the current user default language (content type names have been translated). I'm using the SPContentType managed properties. I have the same requirement for the ows_SiteName that I've mapped to a RefinableString managed properties to be able to refine/filter by site name (also translated). 

**Describe the solution you'd like**
I would like to be able to display content type names or site names in the current user default language in refiner/filter

**Describe alternatives you've considered**
Set content type names and sites names with all language supported Ex: "Policy / Politique", "IT Portal / Portail TI".

**Additional context**

![image](https://user-images.githubusercontent.com/11309224/113933165-3e52de80-97c2-11eb-97a2-e099736fbe17.png)

**Comment by wobba** [comment]
Sorry, no easy way to accomplish this. Search indexes only one language and there are no good API's to get this as we cannot easily tie a content type or site title to an actual site where this has been defined and translated. It would also be very ineffective with additional API calls if it was possible to do this.

**Comment by wobba** [comment]
I think this should be doable yes.
