### ISSUE TITLE
Filter choices have ';#' appended to the end of each option

### ISSUE THREAD

**Issue by codyrhowe** [microsoft-search/pnp-modern-search#926]
I have implemented the PnP - Search Filters web part on a page and setup a filter on a RefinableString that is mapped to a crawled property for a choice field. When the refiners show up there are the characters ';#' appended to the end of each filter option. Is there a way to remove that or do I have something misconfigured? I'm using version 4.0.0.
![Filters](https://user-images.githubusercontent.com/25972267/113942718-7f48f400-97be-11eb-83f3-2a1b3cd51434.png)

**Comment by wobba** [comment]
You can probably use a custom handlebar template for filters to strip this.

![image](https://user-images.githubusercontent.com/51104/113974643-929ba400-983e-11eb-8113-f30f89acdf6a.png)
