### ISSUE TITLE
Failed to load component

### ISSUE THREAD

**Issue by Saroj48** [microsoft-search/pnp-modern-search#927]
**Version used**
v4

**Describe the bug**
[SPLoaderError.loadComponentError]:
Failed to load component "544c1372-fb1d-4e96-bc1e-31fd66979667" (pnpSearchFiltersWebPart). Original error: Failed to load path dependency "CommonStrings" from component "544c1372-fb1d-4e96-bc1e-31fd66979667" (pnpSearchFiltersWebPart). Original error: Error loading https://component-id.invalid/544c1372-fb1d-4e96-bc1e-31fd66979667_4.1.0/CommonStrings
	Unable to load script https://tenent/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/search-parts-commonstrings_en-us_f826aa444e51002d51a683846b72f207.js

INNERERROR:
Failed to load path dependency "CommonStrings" from component "544c1372-fb1d-4e96-bc1e-31fd66979667" (pnpSearchFiltersWebPart). Original error: Error loading https://component-id.invalid/544c1372-fb1d-4e96-bc1e-31fd66979667_4.1.0/CommonStrings
	Unable to load script https://tenent/ClientSideAssets/59903278-dd5d-4e9e-bef6-562aae716b8b/search-parts-commonstrings_en-us_f826aa444e51002d51a683846b72f207.js
CALLSTACK:
Error
    at t [as constructor] (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_efc84dd469d9902215c0adab050d7aaa.js:65:19890)
    at new t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_efc84dd469d9902215c0adab050d7aaa.js:65:117986)
    at Function.e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_efc84dd469d9902215c0adab050d7aaa.js:65:155305)
    at Function.e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_efc84dd469d9902215c0adab050d7aaa.js:65:151350)
    at https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_2ebb0419bb86e53022fa.js:1:65977
![failed to load](https://user-images.githubusercontent.com/82099987/113978246-5af22380-9861-11eb-8fab-522ab6cb5dbe.PNG)

**To Reproduce**
I have deployed the solution in SharePoint Online version.
I went to https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.1.0 and downloaded latest release.
Then I have uploaded the .sppkg file in Apps catalog.
Then I have deployed by clicking on deploy option from ribbon.
Then my admin added that App to Site Contents as I dont have access to add.
Then I have added the all web parts in modern page, four of them are not working.

AS MENTIONED IN THE DOCUMENTATION OF V4, I HAVE DONE SAME AS LIKE THAT. EXCEPT ACTIVATING GRAPH API'S BECAUSE I SAW THOSE ARE NOT MANDATORY.

**Expected behavior**
I tried as per article about deployment and setup but didn't happen as expected

**Screenshots**

Attached in attachments

**Desktop (please complete the following information):**
 - chrome, 

**Additional context**
I downloaded the package file and uploaded into apps catalog then deployed. Added the app in Apps and went for modern page, tried to add web parts then showing "something went wrong"

@wobba help me

**Comment by wobba** [comment]
You forgot to fill in repro steps. How did you install, where did you install etc. Does it affect filter web part only?

**Comment by Saroj48** [comment]
To Reproduce
Steps to reproduce the behavior:

I went to **https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.1.0** and downloaded latest release.
Then I uploaded the sppkg file in **Apps catalog**.
Then I deployed by clicking on deploy option from ribbon.
Then my admin added that App to Site Contents as I dont have access to add.
Then I added the webparts in modern page, all web parts are not happening.

**Comment by Saroj48** [comment]
@wobba I have added that missing part and also mentioned in comments session. Please let me know if any

**Comment by wobba** [comment]
@Saroj48 Can you have your admin re-deploy the solution?

**Comment by Saroj48** [comment]
Sure, I can do that but what about files stored in tenet folder "Client side assets > 59903278-dd5d-4e9e-bef6-562aae716b8b"

**Comment by wobba** [comment]
The package has all files, hence my ask to re-deploy to see if it resolves itself. Did you deploy v4 or v4.1? v4.1 is recommended.

**Comment by Saroj48** [comment]
V 4.1.0 latest release only showed in [](https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.1.0). What I was asking is when I first deployed the package, some files stored in SharePoint folder "Client side assets > 59903278-dd5d-4e9e-bef6-562aae716b8b". So before re-deploy the solution, do we need to remove those files or can we keep them like that?

**Comment by wobba** [comment]
I would remove the app from the site, and re-add it. Then check that all files are correctly added. I also suggest you enable public CDN for faster serving of SPFx solutions. See https://docs.microsoft.com/en-us/sharepoint/dev/spfx/enable-microsoft-365-content-delivery-network

**Comment by Saroj48** [comment]
Okay, I will do that and let you know please don't close the issue until resolved. Thank you...

**Comment by Saroj48** [comment]
Hi again, admin deployed the solution package but this time web parts are not even showing up in the webparts section.
![image](https://user-images.githubusercontent.com/82099987/115198459-b351dc80-a10f-11eb-802a-4e37573bd0d9.png)

**Comment by wobba** [comment]
Seems you should remove it, ensure there is no traces in `Lists/ComponentManifests/AllItems.aspx` in the app catalog site, then re-add. Sometimes deployment of SPFx has hiccups - which is not dependent on the PnP web parts themselves.

**Comment by Saroj48** [comment]
Okay I will try this, hope it will work. Is there any chance to connect with you, any screen share session?

**Comment by wobba** [comment]
@Saroj48 send me a private msg on twitter/linkedin and I'll try to help out.

**Comment by Saroj48** [comment]
I just created linkedin and sent you request, please accept so we can do if in case

**Comment by Saroj48** [comment]
Hi @wobba, 
I got an issue, it worked fine from earlier itself but it is not working for me only. I am using my personal laptop for office purpose. Other than me can add web parts in the page but not me. When I tried to add web parts, showing same error as above. Is it really machine issue or anything? Please let me know.

![image](https://user-images.githubusercontent.com/82099987/115563064-c2ce5280-a2d4-11eb-9bc7-2fee94737981.png)

**Comment by wobba** [comment]
Do you have access policies in place, and what errors do you see on the network tab or in the console? Are you getting 401's or 404's?

**Comment by Saroj48** [comment]
I checked with my colleague and also with admin, they could add web part and it was working fine. But when I come to add showing "something went wrong". Here the problem is I am using personal machine, they are using company provided machine. Apart that I didn't get any errors while adding. Coming to console thing I don't understand what you are asking. If you have any free time let me know, we will just connect through any and you can see what my problem is.

Thank you, Saroj.

**Comment by Saroj48** [comment]
I am closing this issue, thank you for your help. It was nice meeting with you.

**Comment by wobba** [comment]
For those wondering the issue was related to a conditional access policy when not using CDN.
