### ISSUE TITLE
How to filter search results coming from two different servers

### ISSUE THREAD

**Issue by Naveen-Rangarajan** [microsoft-search/pnp-modern-search#928]
**Version used**
3.16

**Describe the bug**
In the People's vertical, when I search for users, it is showing two results for each users. Further investigation revealed that the data comes from two servers, one hosted in NA and other hosted in EU region. OOTB Search shows only 1 result where as PnP Modern Search fetches the data from both servers and results are duplicated. Please check the Screen shots attached. Any help in this regard is appreciated. 

**Expected behavior**
Need to filter the results and duplicates to be removed.

**Screenshots**

**OOTB Search Result**
<img width="639" alt="OOTB Search" src="https://user-images.githubusercontent.com/61411651/113983031-19647700-9867-11eb-90d7-1f722283e931.png">

**PnP Modern Search Screen Shot 1**
<img width="639" alt="pnp-modern-search-ss1" src="https://user-images.githubusercontent.com/61411651/113983638-c3440380-9867-11eb-959d-019b378b1a01.png">

**PnP Modern Search Screen Shot 2 - Debug Mode**
<img width="639" alt="pnp-modern-search-ss2" src="https://user-images.githubusercontent.com/61411651/113985223-8c6eed00-9869-11eb-9253-045529eb1a57.png">

**Desktop (please complete the following information):**
 - Browser [Chrome, Edge]

**Comment by wobba** [comment]
You can either add a path filter to you KQL to limit to the main GEO, or upgrade to v3.18.1 which has an option to turn off multi-geo calls.

**Comment by Naveen-Rangarajan** [comment]
Thanks a lot for the reply.

Just one more question. For V3.18, do we need to download the code and replace the files ? Or is there a npm command to update to 3.18 ?

If its the former, can you please share the URL for V3.18. For latter, if available, can you please share the npm command.

Thanks a ton in advance

**Comment by wobba** [comment]
You can download the sppkg from the release page and install as a new version over the old one.

**Comment by Naveen-Rangarajan** [comment]
Hi @wobba ,

I have made code changes to many files and added some more files. So, a direct deployment is not a possible solution correct? In this case, is it fine to replace certain files, update other files accordingly and finally run "npm install" on the project ?
