### ISSUE TITLE
How to update from v3 to v4

### ISSUE THREAD

**Issue by HeKr09** [microsoft-search/pnp-modern-search#929]
**Version used**
3.6

**Is your feature request related to a problem? Please describe.**
We used the WebParts on several pages within our tenant. Now we want to update to the latest version.
As mentioned in the [introduction](https://microsoft-search.github.io/pnp-modern-search/):

> v3 and v4 don't share the same package name, Web Part and solution IDs meaning you can have them side by side on a page if necessary without overlap.

So that's why I guess that there is no replacing of the used WebParts, isn't it?
How can I update to v4 without manually replace the WebParts?

**Describe the solution you'd like**
Something like a script or anything else to update existing pages.

**Comment by FranckyC** [comment]
Hi @HeKr09, unfortunately, there is no direct upgrade path from v3 to v4 so versions are not compatible. To use v4, you need to add new Web Parts on your pages.
