### ISSUE TITLE
Search extensibility library app fails to add in Site collection

### ISSUE THREAD

**Issue by arunakshi** [microsoft-search/pnp-modern-search#93]
**Version used**
3.8.0
3.90

**Describe the bug**
I deployed the search extensibility library app tenant app catalog and trying to add app in my site collection. I am getting error and not able to see the details and its blank page when I click on errors.

**To Reproduce**
1. Download Pnp Modern Searh solution
2. add Pnp-modern-search-parts.sppkg into tenant app catalog. 
3. Go to search extensibility library folder
4. open the search extensibility library folder in visual studio code 
5. run npm install
6. run gulp --ship
  run gulp bundle --ship
  run gulp package-solution --ship
7. add/deploy search extensibility library.sppkg file to tenant app catalog
8.  Go to one site collection, try to add search extensibility library App to site. 
9. There comes error.

**Expected behavior**
I expected that the app add to site collection without problems

**Desktop (please complete the following information):**
 - Browser Chrome and IE.

The standard search extensibility library from Pnp Demo project is also having same problem. My customization implementation done based on PnP extensibility library, link is here: 
https://microsoft-search.github.io/pnp-modern-search/search-extensibility-library/getting-started/

**Comment by FranckyC** [comment]
@arunakshi You don't need to add the app to the site. It is an SPFx library component project type so the search resuls WP will load it automtically without the need od "deploying" the app.
