### ISSUE TITLE
Search Result Summary Text Formatting

### ISSUE THREAD

**Issue by dirkzwart** [microsoft-search/pnp-modern-search#933]
**Version used**
4.1.0

**Describe the bug**
Selected Property - HitHighlightedSummary is displaying a summary of the file content with the search terms highlighted, but is placing a carriage return before and after each highlighted word. The search term I used was "ballot audit," and this is how the document summary is displayed:
The system
**audit**
log shall contain sufficient information to allow the auditing of all operations related to
**ballot**
tabulation, results consolidation, and report …

**Expected behavior**
No carriage returns before and after the highlighted search terms. (i.e. The system **audit** log shall contain sufficient information to allow the auditing of all operations related to **ballot** tabulation, results consolidation, and report …)

**Desktop (please complete the following information):**
Chrome and EdgeCr on Win10

**Comment by wobba** [comment]
Which template are you using to render the results?

**Comment by dirkzwart** [comment]
List Layout, no additional configurations for template.

**Comment by FranckyC** [comment]
Hi @dirkzwart try to enclose the `{{getSummary ...}` expression in the template with  a `<div>`. This should fix your issue:

![image](https://user-images.githubusercontent.com/5659122/115439716-e3b37c80-a1dc-11eb-958b-15ce796e1a73.png)

**Comment by FranckyC** [comment]
Will be fixed in next release
