### ISSUE TITLE
Promoted Results not returning consistent results

### ISSUE THREAD

**Issue by Pbear74** [microsoft-search/pnp-modern-search#938]
__Remove the above section before submitting, and removal of the below template will result in the issue being closed.__

**Version used**
3.15.3.0
4.0.0.0

**Describe the bug**
A clear and concise description of what the bug is. Keep questions and bugs related to the web parts. If the issue relates to KQL or question around crawled and managed properties please use [Microsoft TechCommunity](https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev). Which means, if you experience the same behavior in classic web parts, then it's not an issue with PnP Modern Search 😉

We are using the pnp modern search results web part, version 3.15.3.0,  on a modern site where it is connected to the SharePoint search box.  When a search term is entered the expected promoted results are not being returned. In the query rule there are two keywords, "handeling" and "handling", when "handeling" is entered no results are returned, however if "handling" is entered the expected results are returned.

On a different page, within the same site collection, the pnp modern search box is used with the pnp modern search results, the same behavior is displayed.

I created a different site collection, created as a classic team site, using the same result source and query rule.  Using the OOTB SharePoint search returns the expected results, both keywords returned the defined promoted results. 

I created a modern page in this site collection and dropped in the pnp search box and search results, running a search on this page does not return the expected results.

I also created a new modern site and added the pnp search box and search results web parts, searching for the keyword "handling" returns the expected results but "handeling" does not.

**To Reproduce**
1. Go to Site settings > site collection administration > search query rules
2. Create a new query rule with the following settings, Query Conditions = 'Query Matches Key Exactly', add multiple keywords; Actions = add a promoted result
3. Add the pnp modern search box and search result web part, connect the two.
4. Run a search and no results are returned.

**Expected behavior**
It is expected to behave just as the OOTB search works, promoted results should be returned when keywords are entered into search.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: MS Edge v. 89.0.774.68

**Additional context**

**Comment by wobba** [comment]
You have to:
* Toggle on query rule support in the web part
* Ensure the query rule is created on the default result source or on the result source used in the web part
* Only the list layout has markup for promoted results. Click the `{}` to customize it and see how it's added.

**Comment by wobba** [comment]
Closed due to inactivity.
