### ISSUE TITLE
Result source ID Pictures and Documents ignore Query template

### ISSUE THREAD

**Issue by achimismaili** [microsoft-search/pnp-modern-search#940]
**Version used**
4.1.0

**Describe the bug**
In the PnP - Search Results web part, in the edit mode, there is a **Result source ID** dropdown on wizard page 1, where the default is LocalSharePointResults.
When selecting Result source ID **"Pictures"** (or **"Documents"** ) there, always the maximum number of pictures (or documents) is shown and any queries in a search box or anything entered in the Query template is ignored. 
I am working on a German SPO tenant, not sure, if that is relevant.

**To Reproduce**
1. Create a new SharePoint page
2. Add pnp result source web part
3. configure with "Pictures" as result source ID and publish --> All pictures are shown
4. Edit the Query template from default "{searchTerms}" to e.g. "{searchTerms} SharePoint" and publish --> now, a smaller number of results should appear (expected) but the number of results does not change.

**Expected behavior**
adding a string to Query template should reduce number of picture (or documents) results, but that does not work, when result source ID Pictures (or Documents) is selected.
Entering a string in a connected search box should reduce number of picture (or documents) results, but that does not work, when result source ID Pictures (or Documents) is selected.

**Screenshots**
In the Screenshot, the total number of results when filtering for Frankfurt Straße in the Query Template and Result Source ID LocalSharePointResults is selected, is 6.

![image](https://user-images.githubusercontent.com/19372423/114315116-b04a6100-9afd-11eb-851e-6874bf79531a.png)

If the Result Source ID "Pictures" is selected, this number must not be higher than 6, as that is supposed to be the number of results of all Result types. But it is 38 in this tenant, because in this tenant, only 38 pictures are indexed by the search. The number 38 does not change, no matter, what string is entered in the search box or in the Query template when editing the web part.

![image](https://user-images.githubusercontent.com/19372423/114315314-bbea5780-9afe-11eb-9bfd-f184b511950c.png)

**Desktop (please complete the following information):**
 - Browser: Brave Browser with Shields down

**Additional context**
I am working on a German SPO tenant and the default language is German (lcid 1031), not sure, if that is relevant.
I had this issue once on a search page, where I configured several result source web parts with filters, search box and verticals, but I also was able to reproduce this on an empty page with only the result source webpart and editing the Query template only.

**Comment by wobba** [comment]
The result sources you pick don't have `{searchTerms}` as part of their definition. Go check the result source definitions on a site to see how they are defined and how they work. E.g. `_layouts/15/EditResultSource.aspx?level=sitecol&sourceid=e7ec8cee-ded8-43c9-beb5-436b54b31e84&view=1`
