### ISSUE TITLE
Missing configuration property in Available connections Page-Search when no query string in browser address bar

### ISSUE THREAD

**Issue by achimismaili** [microsoft-search/pnp-modern-search#941]
**Version used**
4.1.0

**Describe the bug**
This problem appears when configuring the **Search Box web part** as well as the **Search Result web part**.
In wizard step 3 - "Available Connections", when connecting to "Page-Environment" - "Search", a third configuration option is required (Searchrequest [German: Suchabfrage]), but it is not showing up, if the current URL does not contain a search query.
In that case, the configuration is not working and not valid. The only option is to add a search query in the URL and then reopen the configuration. In that case, a third dropdown "Search" appears on the page 3 of the search wizard and the option Searchrequest [German: Suchabfrage] is available.

I am using a German SharePoint Online tenant, I hope this does not affect the functionality of the web part.

**To Reproduce**

1. Create a new SharePoint page, 
2. Make sure, in the browser address bar, the URL does contain a query string like ?q=somestring
2. select edit page mode
2. Add pnp search result source web part and pnp search box to the page
3. configure both web parts, in step 3 of 4 from the wizard "Available Connections", select 
      - connect to source (German: Mit Quelle verbinden)):  Page Environment (German: Seitenumgebung)
      - Properties of Page Environment (German: Eigenschaften von Seitenumgebung): Search (German: Suche)
      - There is no additional dropdown available.
4. Then save and publish
5. When you try to search for something, errors appear
6. Edit the URL to contain a query string like ?q=somestring
7. select edit page mode
8. in step 3 of 4 from the wizard "Available Connections", a third option Search is now available. When selecting "Search Request" in this dropdown and saving + publishing, search is possible.

**Expected behavior**
The third "Search" option seems to be required for a valid configuration.
Therefore, it should also be available, even if there is no query currently available in the URL.

**Screenshots**

- Search results web part **without** the option (if **URL contains no search string**)
![image](https://user-images.githubusercontent.com/19372423/114322829-8ce5dd00-9b22-11eb-8236-111d62f29e52.png)

When trying to search with this configuration, an error shows up in the web part.
![image](https://user-images.githubusercontent.com/19372423/114322884-de8e6780-9b22-11eb-87a9-d11d14665db4.png)

- Search box web part **without** the option (if **URL contains no search string**)
![image](https://user-images.githubusercontent.com/19372423/114322838-9a02cc00-9b22-11eb-98ff-af56151b486c.png)

After saving, adding a query string in the browser URL, hitting enter (to send the request with the query string in the URL) and selecting edit page and edit webpart again, the missing option is available in the web parts.

- Search results web part **with** the option (if URL **contains** a search string)
![image](https://user-images.githubusercontent.com/19372423/114322887-e6e6a280-9b22-11eb-8391-b19e62f3463c.png)

- Search box web part **with** the option (if URL **contains** a search string)
![image](https://user-images.githubusercontent.com/19372423/114322903-fc5bcc80-9b22-11eb-9fb5-0d7617acdd7e.png)

**Desktop (please complete the following information):**
 - Browser: Brave Browser with Shields down

**Additional context**
I am working on a German SPO tenant and the default language is German (lcid 1031), not sure, if that is relevant.

**Comment by wobba** [comment]
This is by design from the dynamic data in SharePoint framework, and not something we can control in these web parts. You always have to include a URL query parameter in order for the framework to pick it up.
