### ISSUE TITLE
Vertical Link redirection not working if URL link is clicked from another vertical

### ISSUE THREAD

**Issue by Naveen-Rangarajan** [microsoft-search/pnp-modern-search#942]
**Version used**
3.16

**Describe the bug**
I have a vertical named All. Page UI is like below and has a link called "View more on Sites" where the URL is https://mydomain.sharepoint.com/sites/mySite/SitePages/search.aspx?q=about&vertical=Sites

<img width="352" alt="vertical1" src="https://user-images.githubusercontent.com/61411651/114506684-c6683680-9c4f-11eb-92b1-07882c3fafe1.png">

When I click on this link, it does not redirect to Sites vertical. But a page reload takes me to Sites vertical. Is is possible to achieve without page reload the navigation to a specific vertical from another vertical through click of a link.

**Screenshots**

**Direct Link click from ALL vertical**
<img width="315" alt="vertical2" src="https://user-images.githubusercontent.com/61411651/114506218-1b577d00-9c4f-11eb-8c3b-c64ca8d6fe95.png">

**On Reload**
<img width="401" alt="vertical3" src="https://user-images.githubusercontent.com/61411651/114509949-bce0cd80-9c53-11eb-8d24-ce71dc216526.png">

**Desktop (please complete the following information):**
 - Browser [Chrome, Edge]

**Comment by wobba** [comment]
@Naveen-Rangarajan you need to share repro steps on your setup. On what page is the link to https://mydomain.sharepoint.com/sites/mySite/SitePages/search.aspx?q=about&vertical=Sites, on search.aspx or on some other page?

Tested with the latest version soon to be released and don't really understand the issue. I can link from the home page to my search page and it loads without a full reload.

**Comment by Naveen-Rangarajan** [comment]
In the ALL tab (or ALL vertical), using handleBar templating, I added a link "**View more on Sites**". 
Please Refer screen shot 1 in my earlier post.

The link is 
https://mydomain.sharepoint.com/sites/mySite/SitePages/search.aspx?q=myQueryText&vertical=Sites

where,
mydomain --> This is my company domain
mySite --> My Company Site
myQueryText --> Some keyword

There is no redirection from any other pages. Link(s) is/are present in the same search page where we have the ALL tab along with other verticals like "Pages", "Sites", "People" etc.

Now, if I click on the link in the ALL tab (Vertical), shouldn't it redirect to "Sites" tab (Vertical), since the vertical query parameter is added?

**Comment by wobba** [comment]
Can you try with and without the `data-interception` parameter as mentioned at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/hyperlinking

**Comment by Naveen-Rangarajan** [comment]
Sure @wobba , Will try this out and check

**Comment by wobba** [comment]
Issue will be soon closed due to inactivity.

**Comment by Naveen-Rangarajan** [comment]
Hi @wobba 

Sorry for getting to this so late.

If data-interception="off"  --> Opens in New Tab the selection happens to desired Tab/Vertical

Say, If I am in ALL tab and click on a link in the ALL tab , it takes me to new tab where Sites is selected.


If not added, the navigation to the desired Tab/Vertical is not happening. But it stays in the same Tab/Vertical

Say, if I am in ALL tab, it stays there and Sites Tab is not selected and loaded.

Is there any other way to navigate within the Tabs on click of link in ALL Tab/Vertical?

**Comment by wobba** [comment]
Can you re-test with the latest version as v3.18 introduced navigation fixes.

**Comment by wobba** [comment]
Closed due to author inactivity.
