### ISSUE TITLE
Mapping a Crawled Property in Provisioning

### ISSUE THREAD

**Issue by mhomol** [microsoft-search/pnp-modern-search#943]
I have tried finding this answer before coming here, but haven't had any luck yet.  Since you guys seem to be the **search masters**, I'm putting my hope in you lol.  I apologize in advance if I say something wrong below.

I have setup a site collection with the local term store as a managed metadata site column that's also setup on most lists and libraries within the site.   I have this managed property mapped to RefinableString101. 

I have a page on the site collection, which is using the PnP v4 search box, filter and results parts.  The filter is pointing to RefineableString101.  This works great.

I want to use this site collection as the source for a provisioning template.  I'm using the following PnP call to generate the provisioning template:

``` powershell
Get-PnPProvisioningTemplate -Out baseline.xml -IncludeHiddenLists -PersistBrandingFiles -IncludeAllClientSidePages -Force
```

When I apply the template, everything works and looks great with one exception: the managed property did **NOT** map to RefinableString101.  Is this possible in PnP Provisioning?  Is there a PowerShell command I can run to map the crawled property?

Thanks in advance for any help anyone can lend.

**Comment by wobba** [comment]
Search schema work is outside the scope of the PnP Modern Search web parts. You should try the Tech community forums at https://techcommunity.microsoft.com/.

You can use Get-PnPSearchConfiguration to get the XML config, which can be added to a template.

**Comment by mhomol** [comment]
@wobba thank you.  I knew it wasn't necessarily related, but didn't know where to turn next.  Thanks for pointing me in the right direction
