### ISSUE TITLE
Search Results WebPart link to list open dialogue preview and not the item.

### ISSUE THREAD

**Issue by asadrajput** [microsoft-search/pnp-modern-search#945]
**Version used**
4.0.0.0

**Describe the bug**
The item link does not work if the list is used to crawl. When clicking on the item link, it opens a web preview and asks to download the item.

**To Reproduce**
1. Simply crawl a list which has modern experience enabled.
2. Search and get the result.
3. Click on item URL to open.

**Expected behavior**

**Screenshots**

1.

![1Capture](https://user-images.githubusercontent.com/24537830/114816561-b8efaf80-9dfb-11eb-8f7d-d1fca9348b57.JPG)

2.
![2Capture](https://user-images.githubusercontent.com/24537830/114816577-c3aa4480-9dfb-11eb-9f8e-a88e4d9e16f0.JPG)

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**

**Comment by wobba** [comment]
You can work around it by adding "contentclass" to the list of managed properties and also add it to the slot mapping list.  These will be added by default in the next release when you add a web part to a page - meaning already added web parts has to be manually updated as per the workaround.
