### ISSUE TITLE
Preview of documents in "Simple list" not working, Version 3.18.2

### ISSUE THREAD

**Issue by MarkusLanger** [microsoft-search/pnp-modern-search#946]
3.18.2

The preview of documents is not working in "Simple list" layout.

**To Reproduce**
1. Add "Search Results" Webpart with a query for documents
2. Use "Simple list" layout
3. Click on the preview icon of the document.
4. Preview does not open 

**Expected behavior**
The preview of the document should open.

**Screenshots**
HTML of the preview with the new "pnp-img" tag.
![image](https://user-images.githubusercontent.com/12131918/114865891-2f3be400-9df3-11eb-8eeb-ff48a3e53213.png)

When debugging the script you can see that the "getAttribute("data-url")" is null because this attribute is part of the "pnp-img" tag and the element in the script is the child "img" tag.

![image](https://user-images.githubusercontent.com/12131918/114865109-1aab1c00-9df2-11eb-9334-9bf1809489e1.png)

If I switch the layout to a "Custom" layout and change the HTML part of the preview from "pnp-img" to the "img" of the previous version the preview opens correctly.
The script gets the right element with the attributes "data-url" and "data-src".
![image](https://user-images.githubusercontent.com/12131918/114865735-f734a100-9df2-11eb-88f9-3dfd18af5764.png)

**Desktop (please complete the following information):**
 - Browser Google Chrome

**Comment by wobba** [comment]
Should be fixed for the next version.

**Comment by wobba** [comment]
Related to #876, and fixed.
