### ISSUE TITLE
Error in Search results in the last page when clicked on the >> in search pagination.

### ISSUE THREAD

**Issue by Naveen-Rangarajan** [microsoft-search/pnp-modern-search#947]
**### Check existing issues before logging new ones**
https://github.com/microsoft-search/pnp-modern-search/issues/463
https://github.com/pnp/sp-dev-solutions/issues/376

Unable to find any solution here. Hence opening it again. Any suggestions are much appreciated. Thanks in advance.

**Version used**
Ex: 3.16

**Describe the bug**
On clicking the last page >> in search pagination, getting below error. MultiGeoSearch is disabled. 

Error making HttpClient request in queryable [500] ::> {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}

Total Results - 4333192

**Expected behavior**
Search Results for the last page should be displayed.

**Screenshots**
<img width="639" alt="searchLastpageError" src="https://user-images.githubusercontent.com/61411651/114985908-f9f5cb80-9eb0-11eb-8770-b54abc9fa3fe.png">

<img width="698" alt="requestpayload" src="https://user-images.githubusercontent.com/61411651/114986550-c2d3ea00-9eb1-11eb-9d50-4e55662355e8.png">

**Desktop (please complete the following information):**
 - Browser [chrome, edge]

**Comment by wobba** [comment]
Likely fixed in the upcoming version - as I changed paging code.

**Comment by Naveen-Rangarajan** [comment]
@wobba , Can you please share in which version the fix is updated?

**Comment by wobba** [comment]
v3.19 in releases.

**Comment by Naveen-Rangarajan** [comment]
Thank you @wobba
