### ISSUE TITLE
People:Manager mapped to RefinableString showing as i:0#.f|membership|user@domain.com

### ISSUE THREAD

**Issue by cor315** [microsoft-search/pnp-modern-search#948]
**Version used**
4.1.0

I'm trying to create a custom staff list with Search Results.  I've added RefinableString01 but the manager is shown as i:0#.f|membership|user@domain.com.

Is it possible to show as Display Name?
![image](https://user-images.githubusercontent.com/12423774/114987332-e4998680-9e49-11eb-9e8e-fae56feca2f6.png)

**Comment by wobba** [comment]
Depending on what cp you have mapped to RefinableString01 you can get display name. Mapping cp/mp is a bit outside the scope of this issue list and I recommend using https://techcommunity.microsoft.com/
