### ISSUE TITLE
ShowPersonaCardOnHover Does Not Display When Building the Solution From SourceCode

### ISSUE THREAD

**Issue by dimitrie-agafitei-FNR** [microsoft-search/pnp-modern-search#952]
**Version used**
--
4.10
https://github.com/microsoft-search/pnp-modern-search/releases/tag/4.1.0

**Describe the bug**
--
When I build the **SEARCH-PARTS** solution from the provided source code the persona card is not displaying when hovering over  a person type result.  If I use the provided build it works. All MSGraph API needed  permissions are approved.

**To Reproduce**
--
1. Go to '**https://github.com/microsoft-search/pnp-modern-search/archive/refs/tags/4.1.0.zip**' and download the source code
2. Build the solution
3. Deploy the package to the app store
4. Activate an configure it by approving the needed GraphAPI.
5. Execute a search that should return people results
6. Hover over the image and the the Person card will not appear
7.  Retract, and install provided build for **pnp-modern-search-parts-v4.sppkg**
 from '**https://github.com/microsoft-search/pnp-modern-search/releases/download/4.1.0/pnp-modern-search-parts-v4.sppkg**'

**Expected behavior**
--
I should be able to hover over a person's picture and see a persona card pop-up.

**Screenshots**
--

**Desktop (please complete the following information):**
 - Browser Chrome Version 89.0.4389.128

**Additional context**
--
The "**SEARCH-EXTENSIBILITY**" solution is not deployed

**Comment by dimitrie-agafitei-FNR** [comment]
Any update on this issue? It seems to me that the published source code should match the features from the build.

**Comment by wobba** [comment]
For the next release we are updating to a newer version of the graph toolkit. You can update this yourself to test if this resolves the issue. Seems to work just fine in the fixes I'm adding which will be pushed to the dev branch soon.

**Comment by wobba** [comment]
Haven't tested the zip myself and it should be a snapshot of what was built at the time in the main branch. That said I would advice to clone the main or develop branch and use that instead of downloading the zip. Main should reflect the latest release and develop the upcoming one.

**Comment by dimitrie-agafitei-FNR** [comment]
@wobba Upgrading to the latest version of the graph toolkit solves the issue. Thank you.
