### ISSUE TITLE
Site Title as Token

### ISSUE THREAD

**Issue by eemancini** [microsoft-search/pnp-modern-search#954]
**Version used**
Consistently an issue in 3.15 and 4.1

**Describe the bug**
Trying to use a token for site URL and content type ID. The token is coming back blank. I am using {searchTerms} Path: {PageContext.site.absoluteUrl} and also tried {searchTerms} Path: "{PageContext.Site.absoluteUrl}"
![image](https://user-images.githubusercontent.com/61661610/115287981-e3ed4280-a11e-11eb-9502-402c15a627cf.png)

**To Reproduce**
1. Add search results webpart to a page
2. On page 2 under Query template add: {searchTerms} Path: "{PageContext.site.absoluteUrl}"

**Expected behavior**
Documents from current site

**Desktop (please complete the following information):**
 - Edge

Thank you so much for your help! I appreciate it.

**Comment by wobba** [comment]
@eemancini the issue title seems a bit different from what you are asking?

You cannot use spaces in a property query between property operator or value as per specs https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference#specifying-property-restrictions.

Try: `Path:{PageContext.site.absoluteUrl}`

**Comment by eemancini** [comment]
Thank you so much for your help, @wobba.

My apologies for the confusion. I am trying to have the search results web part identify which site it is within and only pull results matching this site and a specific content type.

My query is: {searchTerms} ((ContentTypeId: 0x010100ED5AEEC63EB9EB46B161EB780D58AFBB02*) AND (Path:{PageContext.site.absoluteUrl})
And the request payload is: QueryTemplate: "{searchTerms} ((ContentTypeId: 0x010100ED5AEEC63EB9EB46B161EB780D58AFBB02*) AND (Path:)"

There should be 3 results and I am getting results from across the tenant:
![image](https://user-images.githubusercontent.com/61661610/115434101-4bb29480-a1d6-11eb-9760-46a315b1d52d.png)

**Comment by wobba** [comment]
You can't have space between the property, operator and value.

`prop:value`, not `prop: value`

**Comment by eemancini** [comment]
Thank you for calling our the end paren. Copying and pasting your exact query I am still receiving this in the request payload: QueryTemplate: "{searchTerms} ((ContentTypeId:0x010100ED5AEEC63EB9EB46B161EB780D58AFBB02*) AND (Path:))"
Querytext: "*"

**Comment by wobba** [comment]
Looking at it it seems there might be an issue with Path:{PageContext.site.absoluteUrl}. So use {Site} instead for now.

**Comment by eemancini** [comment]
Thank you. Using Site resolves it!

**Comment by wobba** [comment]
Figured it out. Check the docs at https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-results/#custom-query-variables.

PageContext maps to values from the legacy context object, and we don't really document what those are. You can use:

* {PageContext.webAbsoluteUrl}
* {PageContext.siteAbsoluteUrl}
* etc.

@sympmarc has an old list covering some values you can get, but there are more. https://sympmarc.com/2013/03/26/using-_sppagecontextinfo-to-determine-the-current-sharepoint-context-in-script/

**Comment by sympmarc** [comment]
This is the kind of thing that drives people insane trying to get search solutions to work.

Note that {PageContext.site.absoluteUrl} is listed as an option in the [tokens documentation](https://microsoft-search.github.io/pnp-modern-search/usage/search-results/tokens/).

**Comment by wobba** [comment]
@sympmarc Seems `_spPageContextInfo.site` is no longer there. Adding some UX showing what is available would def help. I'll make a point to update the docs.
