### ISSUE TITLE
How to show search results based on Content Type

### ISSUE THREAD

**Issue by BhattMeet98** [microsoft-search/pnp-modern-search#955]
Hello,

I have added Search Box and Search Results web parts in my page.

Now I need to get search results based on Content-Type.

For Example, "**Lorem ipsum**".is the content type of document.

If anyone searches **Lorem ipsum**, then all files are shown in the search result which content type is **Lorem ipsum**.

Thanks

**Comment by wobba** [comment]
Filter on `SPContentType:"Lorum ipsum"` or use `ContentTypeId:0x012424234` if you have the id.

**Comment by BhattMeet98** [comment]
Thanks for your response. I have created a document library for demo and add content type with the name "Document"

I am trying to filter with SPContentType:"Document" but it is not working correctly.

Can you please help me with the same?

**Comment by wobba** [comment]
Troubleshooting this is outside the scope of this project. You can try to ask over at https://tech community . microsoft.com

Easiest is to use the debug template, ensure you ask to get SPContentType back as a managed property and look at your value. Or use the CT I'd instead which is never language dependent 🙂

**Comment by BhattMeet98** [comment]
Hi @wobba 

Can you please let me know where I need to define SPContentType:"Document" in the search result web-part?

Thanks

**Comment by wobba** [comment]
Either in search text or the query template. Query template filed is preferred.

`{searchTerms} SPContentType:"Document"`
