### ISSUE TITLE
Question: V3 - Custom HTML and CSS in card fields

### ISSUE THREAD

**Issue by corily18** [microsoft-search/pnp-modern-search#959]
I am trying to customize the card fields in the search result webpart.
There are 2 card fields which are accepting HTML and CSS: Location and Tags
I am trying to add some HTML markup to one of the HTML card fields:
`<a href="{{Path}}" download>
<button class="ms-Button ms-Button--primary">
    <span class="ms-Button-label">Download</span>
</button>
</a>`

It is just a simple button that downloads the search result (an image). Every time the markup is added, the button is there, but the link does not point to the URL of the image. It doesn't matter which managed property I am using; it is never accepted.
I am currently working with v3. I have tested this also in v4, and there it is working. But I cannot use v4 for other reasons.
Any idea to tip?
Many thanks for considering my request.

**Comment by wobba** [comment]
It would help if you can share exact repro steps as it's quicker for me to get up and running. Or, if using the latest version go to the last setup page and export the full web part config and share it.

**Comment by corily18** [comment]
Hey @wobba,

Steps to reproduce:
1. Added the Search Results web part
2. Added a query by path (Path:https//.....). The query gives back files from the specified library
3. In the layout, I am using the card fields
4. started to configure the card fields by adding some HTML markup in one of the fields that are accepting HTML
Expected:
The card with the HTML 
`<a href="{{Path}}" download> <button class="ms-Button ms-Button--primary"> <span class="ms-Button-label">Download</span> </button> </a>`
shows a download button. By clicking on the button, the file is downloaded
Current behavior:
The card shows the button. The link behind the button is not the path to the file. It is just a link referencing the root URL of the site.
Thanks!

**Comment by wobba** [comment]
You should use `DefaultEncodingURL` as the managed property in the download link, not Path. Not easy to know this :)
