### ISSUE TITLE
Can the Search Box be used as a Filter on the Search Results?

### ISSUE THREAD

**Issue by clublek** [microsoft-search/pnp-modern-search#96]
If the Search Results are displaying a number of results from a fixed query (like certain sites using a specific path), can the Search Box be setup as a kind of filter of those Search Results? So when you type it narrows down the Search Results instantly...

Regards,
Chris

**Comment by FranckyC** [comment]
HI @clublek . Not sure to fully understand but yes the search box can be connected to the search results to '"narrow" results. Also you can connect the search box to an other source like a query string parameter. This way, the query text will be cascaded to the search results as well on the initial load. Does it answer your question?

**Comment by clublek** [comment]
I'm trying to make this happen. Is it wise to first create a Result Source of my default query? Then no other items can be found when using the Search Box...

**Comment by FranckyC** [comment]
You can only set the default **query text** when using the search box:

![image](https://user-images.githubusercontent.com/5659122/74594226-a617fa00-5001-11ea-8c69-aa66458fdeeb.png)

However, you can update your query template like this by adding the `{searchTerms}` expression:

`{searchTerms} contentclass:STS_Site path:https://tenant.sharepoint.com/teams/Project_*`

And the default query to: `*`

This way, this will be replaced dynamically by either the search box value when submitted or the defaut search query `*`.

**Comment by clublek** [comment]
Thanks! It works now what i had imagined and it filters the search results.
However, when emptying the search box and pressing Enter it will not rollback the Search Results web part to display all initial results. It stays filtered, and I have to refresh the page...

**Comment by FranckyC** [comment]
@clublek This because you can't submit an empty query and this is expected. To clear the search box value, use the 'Cross' icon. Filters and results will be reset.

![image](https://user-images.githubusercontent.com/5659122/74668874-19da1400-5174-11ea-8d3b-897eacf14094.png)

I close the issue since it is resolved.

Thanks!
