### ISSUE TITLE
Date Refiner template

### ISSUE THREAD

**Issue by tony-philipose** [microsoft-search/pnp-modern-search#963]
- Is there any way to set the date value as a multi-value refinement item template in refiner?

- I have created a refinable string for the date field and set that refinable string for the filter with a multi-value refinement template but only the alphabetical sort option is available. If any trick is available for sorting the date strings values in date ascending or descending order?

![image](https://user-images.githubusercontent.com/30836715/116094458-2b4a7480-a6c5-11eb-831c-c30cff37d323.png)

**Comment by wobba** [comment]
By using the custom template option in v4 you should be able to add sorting to the values.

![image](https://user-images.githubusercontent.com/51104/116704423-a8c6fb00-a9cb-11eb-8bb8-ca645687812a.png)

**Comment by wobba** [comment]
The filters are sorted based on string or frequence, so if you had dates in the format of yyyy-MM-dd it would work.

![image](https://user-images.githubusercontent.com/51104/119148832-2e7b1b00-ba4d-11eb-9c2a-f093b539481a.png)

**Comment by Laul0** [comment]
Hi @tony-philipose, do the @wobba's answer solve your issue?

**Comment by tony-philipose** [comment]
@Laul0 Yes

**Comment by tony-philipose** [comment]
> The filters are sorted based on string or frequence, so if you had dates in the format of yyyy-MM-dd it would work.
> 
> ![image](https://user-images.githubusercontent.com/51104/119148832-2e7b1b00-ba4d-11eb-9c2a-f093b539481a.png)

@wobba Thanks, It's working fine in my application.
