### ISSUE TITLE
Getting error "Invalid regular expression: /*/: Nothing to repeat" in Search Results web part with * default query since upgrade

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#964]
**Version used**
Ex: 3.19

**Describe the bug**
My Search Results web part is configured to use a wildcard for the Default Search Query: *. This has been working just fine to get be a list of all results if nothing is entered into the search query box. However, we upgraded to 3.19 (from 3.17 and 3.18) and now when there is no query text, I get a pink error stating "Invalid regular expression: /*/: Nothing to repeat" . 

![image](https://user-images.githubusercontent.com/2616432/116159591-62a92900-a6a5-11eb-8168-207e6f4decc4.png)

![image](https://user-images.githubusercontent.com/2616432/116159596-663cb000-a6a5-11eb-905d-a5c917ec4fcc.png)

**To Reproduce**
1. Configure a Search Results web part.
2. Connect to source = Page environment
3. Select Page environment property = Search
4. Select Search = Search query
5. Select the Use a default search query check box
6. in the Default search query box, enter *

**Expected behavior**
I get a full list of all results by default, unless I have a search query entered.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - Edge and Chrome (current version)

**Additional context**
My Search Results web part is connected to vertical and filter web parts. I did test with only the Search Results web part and get the same error if I try to use a wildcard as the default.

**Comment by wobba** [comment]
I'm not able to repro.

1. First I type something like * in the Search query keywords, as that makes dynamic connection work better for some reason
2. Connect to search.
![image](https://user-images.githubusercontent.com/51104/116709140-aadf8880-a9d0-11eb-8000-0ef8f7a1a651.png)

Do you have q= in the query string, or something in the header search box?

**Comment by wobba** [comment]
Related to wildcard query and synonyms. Will fix as part of #965.

**Comment by bryllyg** [comment]
No query string on this page. We had to roll back to 3.18 temporarily, but I'll get it set up on another site and see if I can reproduce.

**Comment by wobba** [comment]
It was related to wildcard and synonym expansion where the regular expressions messed up. Added special handling for *, but should probably add if * is in any term.

**Comment by bryllyg** [comment]
Thanks!
