### ISSUE TITLE
Synonyms back to requiring quotes around phrases in order to work in 3.19

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#965]
**Version used**
Ex: 3.19

**Describe the bug**
There are two parts to this:

3.19 - Synonym phrases once again require quotes around them to work, breaking a fix that was included in 3.18

3.18 - In 3.18 there was a change (issue 713) added to make is to users did not need to put quotes around search phrases in order to have the phrase recognized as a synonym. In 3.17, you had to put quotes around any phrase in order for it to be recognized as a synonym. However, after more testing, 3.18 did have the reverse issue, users didn't have to put quotes around phrases to have them recognized as synonyms, but suddenly they had to put quotes around single words. So,.

Maternal health = worked
but, 
MH only worked if you searched for "MH"

Can we get not having to use quotes in order for synonyms to be recognized back in the queue? Users never know that they are looking for a phrase that is a synonym, so they have no way to know that they should use quotes around it. 

**To Reproduce**
Using 3.19 
- Configure two way synonyms, with the associated synonym containing multiple entries. Some single word, some multi word.
    - "Community Related Work" - CRW, "Community focused work"
- Search using one of the single word synonyms, CRW (no quotes around it) this works
- Search using a multi word synonym, community focused work (no quotes) this does not work
- Search using a multi word synonym, "community focused work" (with quotes) this works... but users don't know that it's a synonyms and they should use quotes

Using 3.18
- Configure two way synonyms, with the associated synonym containing multiple entries. Some single word, some multi word.
    - "Community Related Work" - CRW, "Community focused work"
- Search using one of the single word synonyms, CRW (no quotes around it) this does not work
- Search using one of the single word synonyms, "CRW" (with quotes around it) this works
- Search using a multi word synonym, community focused work (no quotes) this works

**Expected behavior**
Synonyms will work when the term is a single word or a phrase, without the need for quotes

**Screenshots**

**Desktop (please complete the following information):**
 - Edge and Chrome, current versions
 - Windows 10
 
**Additional context**

Thanks!

**Comment by wobba** [comment]
Published a v3.19.1 release which should fix your issue.

If the entire query matches a synonym it will be replaced even if quotes are not added. If you have a multi term synonym which is part of a longer query it will not work.

Query | Synonym | Rewrite 
--- | --- | ---
foo bar | foo bar -> something |  (foo bar) OR (("foo bar" OR something))
foo bar test | foo bar -> something | foo bar test
foo bar test | bar -> something | (foo bar test) OR (foo (bar OR something) test)

**Comment by bryllyg** [comment]
Fabulous! I'll get it installed on a site and give it a whirl!

**Comment by wobba** [comment]
Sorry for all the issues here. Synonym cases are tricky. I might think to create a better framework for synonym expansion to cover all cases with property queries and phrases etc.

**Comment by bryllyg** [comment]
Thanks much. I'm hoping in the long run that O365 will have an over arching solution for synonyms that we can apply, but having it in the Search Results web part is SO helpful!
