### ISSUE TITLE
Search query with dash in it requires quotes around it as of 3.19 update

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#966]
**Version used**
3.19

**Describe the bug**
Queries for terms that include a dash, such as ADM-4458 or ID-9856 no longer work as up the 3.19 update. To get them to work, you now have to put quotes around the term, "ID-9856".  This worked fine with or without quotes in 3.17 and 3.18.

**To Reproduce**
1. Create a list 
2. Add a text field for Admin ID.
2. Populate a few rows of the field with ID numbers following the patter ID-####
3. Set up a Search Results web part and connect it to the Search Query string and show number of hits.
4. Enter a search query for one of the ID number, for example: ID-9856
5. Notice that the number of hits is equal to the number of rows in your source list.
6. Now, put quotes around the query text: "ID-9856"
7. Notice that you now get the correct specified item.

**Expected behavior**
Results shows the single item I queried for, without having to put quotes around it. It's not a phrase.

**Screenshots**

**Desktop (please complete the following information):**
Edge and Chrome, current versions

**Additional context**
Debug queryModification WITHOUT quotes:

"queryModification": "Path:\"https://bmgf.sharepoint.com/sites/auroradev/Lists/InvestmentDestials\" (id-9856) OR (\"id\"-9856)  contentclass:STS_ListItem_GenericList  -ContentClass=urn:content-class:SPSPeople ",
  "items": [

![image](https://user-images.githubusercontent.com/2616432/116180993-ab290c80-a6ce-11eb-8a30-8b6bfd427541.png)

Debug queryModification WITH quotes:
{
  "queryModification": "Path:\"https://bmgf.sharepoint.com/sites/auroradev/Lists/InvestmentDestials\" (\"id-9856\") OR (\"id-9856\")  contentclass:STS_ListItem_GenericList -ContentClass=urn:content-class:SPSPeople",
  "items": [

![image](https://user-images.githubusercontent.com/2616432/116181006-b1b78400-a6ce-11eb-9e06-66727f86c446.png)

**Comment by wobba** [comment]
Fixed with the synonym fix in v3.19.1.
