### ISSUE TITLE
Thumbnails are not displayed when documents are located in subWebs

### ISSUE THREAD

**Issue by FelixMD15** [microsoft-search/pnp-modern-search#967]
Version: 4.1.0

**Describe the bug**

No thumbnails are displayed if the documents are not in the root web, but in subWebs.

**To Reproduce**

1. Create a SharePoint Online Team Site
2. Create a SharePoint SubSite within the Team Site
2. Create a document library or use one which is created automatically
3. Upload a document into the library
4. Find the document within the search WebPart
5. There is only a placeholder image not the thumbnail

**Expected behavior**
Thumbnails are displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/83283919/116235764-8a0ffc80-a75e-11eb-8439-ef5365d83197.png)
![image](https://user-images.githubusercontent.com/83283919/116236198-0f93ac80-a75f-11eb-8f01-a297a46bd026.png)

**Desktop (please complete the following information):**
 - Browser: Chrome and New Edge

**Additional context**

In my oppinion the problem with the request _/_api/v2.1/sites/**e1f2d341-7212-4837-a25e-9bbc8650f1b9**/lists/**c651e9a5-c692-47ae-bfbf-24b8c5d332ec**/items/eb5b04bd-ca0b-4cd7-abd6-65f8865b7eed/driveItem/thumbnails/0/large/content?preferNoRedirect=true_ is the following:

- e1f2d341-7212-4837-a25e-9bbc8650f1b9 is the siteId of the rootWeb
- c651e9a5-c692-47ae-bfbf-24b8c5d332ec is the listId. But this list is not part of the rootWeb but is located at the subweb

The request tries to get the list from the wrong web. It should get it from the subweb not from the rootweb.

**Comment by FelixMD15** [comment]
I just cloned the repo and think i got my answer :/:

SearchResultsContainer.tsx | line 309 

// Can lead to 404 errors but it is a trade of for performances. We take a guess with this url instead of batching calls for all items and process only 200.
                        item[AutoCalculatedDataSourceFields.AutoPreviewImageUrl] = `${this.props.pageContext.site.absoluteUrl}/_api/v2.1/sites/${siteId}/lists/${listId}/items/${itemId}/driveItem/thumbnails/0/large/content?preferNoRedirect=true`;

**Comment by FelixMD15** [comment]
With this adaption within "SearchResultsContainer.tsx" i could solve the problem in my dev environment:

![image](https://user-images.githubusercontent.com/83283919/116252145-96508580-a76f-11eb-8d58-1a835e77344f.png)

Just read the webId (line 300) of the dataItem and put it into the request in line 311.

**Comment by FelixMD15** [comment]
Reference to get subWeb List with comma separated {siteId}, and {webId}:

https://docs.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0

![image](https://user-images.githubusercontent.com/83283919/116253812-1a573d00-a771-11eb-889c-227c370bdde8.png)

**Comment by wobba** [comment]
Makes sense...it's a bug, but so are sub-sites 😁

**Comment by FelixMD15** [comment]
Ok, thanks! We have a lot of subSites (600 siteCollections which have 500 subsites each)

Does it mean that the fix will be put in the next release?

**Comment by wobba** [comment]
@FelixMD15 if I have time, or someone else want to fix it. 500 sub-sites sounds like SP security group mayhem :D

**Comment by wobba** [comment]
Will be fixed in the next release. You will have to manually update slots/managed properties to get `NormWebID` on existing installs. If you add new web parts they should include this.

**Comment by FelixMD15** [comment]
Thanks a lot! Is there an approximate date for the next release.

**Comment by awan015** [comment]
Was this missed in the latest release (4.2.2)? 

![image](https://user-images.githubusercontent.com/60472505/121125832-4e974080-c87b-11eb-8f80-3f7e06884056.png)

**Comment by wobba** [comment]
This was not fixed yet in v4, v3 only. Forgot to address it as I'm not a fan of subwebs 😉 Should be easy to get in - for v4.5.

**Comment by wobba** [comment]
Fixed with #1385
