### ISSUE TITLE
Modified "selected properties" do not persist when page saved

### ISSUE THREAD

**Issue by dgwebb** [microsoft-search/pnp-modern-search#968]
I am trying to add some selected properties to the standard list -- specifically RefinableString00 - RefinableString03.

When I click the dropdown, the scrollable list of managed properties appears.  I select the 4 new fields I want.  I can click Next and Back, look at the list of properties again, and they are still selected.  I can close the web part properties and reopen it, and they are still selected.  However, when I save the page as Draft, Edit it again, and inspect the selected properties, they are no longer selected - the standard fields are selected, and my new fields are not selected.  

The same behaviour occurs if I simply type the properties at the end of the combo box.

**Comment by wobba** [comment]
Fill out version, and repro steps. If not issue will be deleted.
