### ISSUE TITLE
Results Page layout multiple sections - Link between WebPart Results & Refiner

### ISSUE THREAD

**Issue by Alambique99** [microsoft-search/pnp-modern-search#969]
Hi,

I'm implementing the latest version of the solution. After few work, all is working.
However, the page layout 2tird-1tird is not fine.

So, I changed the strategy.
For Result WebPart, I used a OneColumn section, then for the Refiner I added a additional Vertical Section; This layout give more space for the Results with some Columns diplayed.

The problem: In this configuration, the Refiner doesn't work anymore and stay blank without any filter. Nothing other has changed in the configuration of WebPart,
One I change back the section layout to 2tird-1tird and put back the 2 WebPart (result and refiner) in the same Section, it works.

Does someone any idea ?

Regards

**Comment by wobba** [comment]
Issue is not using the issue templates, so hard to understand the issue/question as it's lacking information like repro steps or screenshots.
