### ISSUE TITLE
Filter not removed when new search option is selected 

### ISSUE THREAD

**Issue by meklulose** [microsoft-search/pnp-modern-search#971]
Version 3.18.1

We have a problem where we have radio buttons which user can select and it has different options like just search for document or folders. The issue we are facing is that when user have selected a filter, the search result brings back correct results but when they change to different option and do search for the same keyword the filter stays. Ideally, we want all the filters to be removed when the option is changed. 

1. Choose a radio button option 
2. Search all "*"
2. Select a filter
3. Choose a different radio button option
4. Click on search again without changing query keyword

Expected behavior
The search result brings back all the materials that matches the radio button option

Actual behavior
The search result only brings back materials that matches the radio button option and filter applied before

Tested in Chrome

**Comment by wobba** [comment]
Please provide exact web part setups, and possibly screenshots.

**Comment by meklulose** [comment]
Hi @wobba Please find the attached zip file containing the changes we have made to web parts. 

When we search the url fragment gets added based upon radio button, from there the search results we have added a props which looks at url, which will allow a search without changing the keyword.
We find that at first it will show the correct results but then the results will re-render with the results based on refiner but the refiner does not show.
Any help or pointers would be greatly appreciated. Many thanks :) 

[Main Search files.zip](https://github.com/microsoft-search/pnp-modern-search/files/6405310/Main.Search.files.zip)

The Search Box has been set up as follows:
{
	"searchInNewPage": false,
	"pageUrl": "",
	"queryPathBehavior": 0,
	"queryStringParameter": "q",
	"openBehavior": 0,
	"enableQuerySuggestions": false,
	"useDynamicDataSource": true,
	"NlpServiceUrl": "",
	"enableNlpService": false,
	"enableDebugMode": false,
	"isStaging": true,
	"placeholderText": "",
	"suggestionProviders": [
		{
			"providerName": "default",
			"providerDisplayName": "SharePoint Query Suggestions",
			"providerDescription": "Default SharePoint query suggestions.",
			"providerEnabled": true
		}
	],
	"defaultQueryKeywords": {
		"__type": "DynamicProperty",
		"reference": {
			"_reference": "PageContext:UrlData:fragment",
			"_sourceId": "PageContext",
			"_property": "UrlData",
			"_propertyPath": "fragment"
		}
	}
}


The Search Results is as follows:
{
	"queryTemplate": " {searchTerms} Path:https://defradev.sharepoint.com/sites/EADMSTest* \n(ContentTypeId:{QueryString.CTId} -ContentTypeId:{QueryString.NoCTId}) OR\n(ContentTypeId:{QueryString.CTId2})\n(Created={QueryString.datefrom}..{QueryString.dateto})\n",
	"sortList": [
		{
			"sortField": "RefinableString122",
			"sortDirection": 2,
			"sortIdx": 1
		},
		{
			"sortField": "Created",
			"sortDirection": 2,
			"sortIdx": 2
		}
	],
	"selectedProperties": "Title,Path,Created,Filename,SiteLogo,PreviewUrl,PictureThumbnailURL,ServerRedirectedPreviewURL,ServerRedirectedURL,HitHighlightedSummary,FileType,contentclass,ServerRedirectedEmbedURL,ParentLink,DefaultEncodingURL,owstaxidmetadataalltagsinfo,Author,AuthorOWSUSER,SPSiteUrl,SiteTitle,IsContainer,IsListItem,HtmlFileType,SiteId,WebId,UniqueID,OriginalPath,FileExtension,IsDocument,NormSiteID,NormWebID,NormListID,NormUniqueID,PermitNumber,ModifiedBy,ModifiedOWSDATE,ActivityGrouping,SiteAddress,SiteName,DisclosureStatus0,SitePlotName,FacilityAddress,DisclosureStatus,LastModifiedTime,SiteNameOWSTEXT,DiscussionCategory,PermitDocumentType,CreatedBy,ReplyCount,ItemCount,Size,DMSTotalItemCount,RefinableString122",
	"enableQueryRules": true,
	"includeOneDriveResults": false,
	"showBlank": true,
	"showResultsCount": true,
	"webPartTitle": "Search Results",
	"enableLocalization": true,
	"useDefaultSearchQuery": false,
	"resultTypes": [],
	"useExternalRefinersDisplay": false,
	"useExternalPaginationDisplay": false,
	"appliedRefiners": [],
	"refinersConfiguration": [],
	"sortableFields": [
		{
			"uniqueId": "51264009-8ba3-41b6-9e64-5972f7fe4c18",
			"sortField": "RefinableString110",
			"displayValue": "Permit Number",
			"sortDirection": 1,
			"sortIdx": 1
		},
		{
			"uniqueId": "861e39e8-b971-444f-85dd-1601157f1c0f",
			"sortField": "Created",
			"displayValue": "Uploaded Date",
			"sortDirection": 2,
			"sortIdx": 2
		},
		{
			"uniqueId": "a6d6c651-f3c7-45d3-ad53-8f678e77358f",
			"sortField": "RefinableString112",
			"displayValue": "Activity Grouping",
			"sortDirection": 1,
			"sortIdx": 3
		},
		{
			"uniqueId": "17588b1b-9b23-4515-8428-4760dafce753",
			"sortField": "RefinableString116",
			"displayValue": "Facility Name",
			"sortDirection": 1,
			"sortIdx": 4
		},
		{
			"uniqueId": "dddf34d9-f5a4-4a66-8593-76ac44539ca7",
			"sortField": "RefinableString117",
			"displayValue": "Facility Address",
			"sortDirection": 1,
			"sortIdx": 5
		},
		{
			"uniqueId": "39ec66c7-5ac5-4dcf-8eac-067f701bfd44",
			"sortField": "RefinableString118",
			"displayValue": "Disclosure Status ",
			"sortDirection": 1,
			"sortIdx": 6
		},
		{
			"uniqueId": "de16f646-00e1-47a5-b89f-03cac13ee3e8",
			"sortField": "RefinableString119",
			"displayValue": "Permit Document Type",
			"sortDirection": 1,
			"sortIdx": 7
		}
	],
	"synonymList": [],
	"searchQueryLanguage": -1,
	"templateParameters": {
		"detailsListColumns": [
			{
				"name": "Name",
				"value": "{{Filename}} {{#gt DMSTotalItemCount 0}}\n    ({{DMSTotalItemCount}})\n{{/gt}}\n\n",
				"useHandlebarsExpr": true,
				"minWidth": "150",
				"maxWidth": "200",
				"enableSorting": false,
				"isMultiline": true,
				"isResizable": true,
				"isResultItemLink": true,
				"sortIdx": 1
			},
			{
				"name": "Uploaded Date",
				"value": "{{getDate Created \"DD/MM/YYYY\"}}",
				"useHandlebarsExpr": true,
				"minWidth": "75",
				"maxWidth": "90",
				"enableSorting": false,
				"isMultiline": false,
				"isResizable": true,
				"isResultItemLink": false,
				"sortIdx": 2
			},
			{
				"name": "Permit No.",
				"value": "PermitNumber",
				"useHandlebarsExpr": false,
				"minWidth": "50",
				"maxWidth": "120",
				"enableSorting": false,
				"isMultiline": true,
				"isResizable": true,
				"isResultItemLink": false,
				"sortIdx": 3
			},
			{
				"uniqueId": "292f515b-f2fc-4715-98f4-749aed1e25ca",
				"name": "Facility Name",
				"value": "SiteNameOWSTEXT",
				"useHandlebarsExpr": null,
				"minWidth": "50",
				"maxWidth": "120",
				"enableSorting": false,
				"isResizable": true,
				"isMultiline": false,
				"isResultItemLink": null,
				"sortIdx": 4
			},
			{
				"uniqueId": "bc39f151-23db-4701-aed0-7cbd9220a6ec",
				"name": "Facility Address",
				"value": "FacilityAddress",
				"useHandlebarsExpr": null,
				"minWidth": "50",
				"maxWidth": "300",
				"enableSorting": false,
				"isResizable": true,
				"isMultiline": true,
				"isResultItemLink": null,
				"sortIdx": 5
			},
			{
				"uniqueId": "0bb072ae-e796-4fae-8723-aa5d6f29e987",
				"name": "Activity Grouping",
				"value": "ActivityGrouping",
				"useHandlebarsExpr": null,
				"minWidth": "50",
				"maxWidth": "120",
				"enableSorting": false,
				"isResizable": true,
				"isMultiline": false,
				"isResultItemLink": null,
				"sortIdx": 6
			},
			{
				"uniqueId": "8028210e-f30c-4d1b-b678-2abe140216e8",
				"name": "Disclosure Status",
				"value": "DisclosureStatus",
				"useHandlebarsExpr": null,
				"minWidth": "50",
				"maxWidth": "120",
				"enableSorting": false,
				"isResizable": true,
				"isMultiline": false,
				"isResultItemLink": null,
				"sortIdx": 7
			},
			{
				"uniqueId": "d7d2b4ed-7a93-479e-a410-a1935e9114b2",
				"name": "Created By",
				"value": "CreatedBy",
				"useHandlebarsExpr": null,
				"minWidth": "50",
				"maxWidth": "120",
				"enableSorting": false,
				"isResizable": true,
				"isMultiline": false,
				"isResultItemLink": null,
				"sortIdx": 8
			},
			{
				"uniqueId": "fed694ef-2137-4ef5-b9ad-cd2284f9deb7",
				"name": "Size",
				"value": "{{#gt Size 1073741824 }}\n{{toFixed (divide Size 1073741824.0) 1}}GB\n{{else gt Size 1048576}}\n{{toFixed (divide Size 1048576.0) 1}}MB\n{{else gt Size 1024}}\n{{toFixed (divide Size 1024.0) 1}} KB\n{{else gt Size 0}}\n{{toFixed Size 1}}Bytes\n{{else}}\n{{toFixed Size}}\n{{/gt}}\n",
				"useHandlebarsExpr": true,
				"minWidth": "50",
				"maxWidth": 310,
				"enableSorting": null,
				"isResizable": null,
				"isMultiline": false,
				"isResultItemLink": null,
				"sortIdx": 9
			}
		],
		"showFileIcon": true,
		"isCompact": false,
		"documentCardFields": [
			{
				"name": "Title",
				"field": "title",
				"value": "Title",
				"useHandlebarsExpr": false,
				"supportHtml": false
			},
			{
				"name": "Location",
				"field": "location",
				"value": "<a style=\"color:{{@themeVariant.palette.themePrimary}}\" href=\"{{SPSiteUrl}}\">{Document Management Service}</a>",
				"useHandlebarsExpr": true,
				"supportHtml": true
			},
			{
				"name": "Tags",
				"field": "tags",
				"value": "{{#if owstaxidmetadataalltagsinfo}}<i class='ms-Icon ms-Icon--Tag' aria-hidden='true'></i> {{#each (split owstaxidmetadataalltagsinfo ',') as |tag| }}<a class=\"ms-Link\" href=\"#owstaxidmetadataalltagsinfo:'{{trim tag}}'\">{{tag}}</a>{{/each}}{{/if}}",
				"useHandlebarsExpr": true,
				"supportHtml": true
			},
			{
				"name": "Preview Image",
				"field": "previewImage",
				"value": "{{{getPreviewSrc item}}}",
				"useHandlebarsExpr": true,
				"supportHtml": false
			},
			{
				"name": "Preview URL",
				"field": "previewUrl",
				"value": "{{#eq contentclass 'STS_ListItem_851'}}{{{DefaultEncodingURL}}}{{else}}{{#eq FileType 'pdf'}}{{#contains Path '-my.sharepoint'}}{{{ServerRedirectedEmbedURL}}}{{else}}{{{Path}}}{{/contains}}{{else}}{{{ServerRedirectedEmbedURL}}}{{/eq}}{{/eq}} ",
				"useHandlebarsExpr": true,
				"supportHtml": false
			},
			{
				"name": "Date",
				"field": "date",
				"value": "{{getDate item.Created 'LL'}}",
				"useHandlebarsExpr": true,
				"supportHtml": false
			},
			{
				"name": "URL",
				"field": "href",
				"value": "{{getUrl item}}",
				"useHandlebarsExpr": true,
				"supportHtml": false
			},
			{
				"name": "Author",
				"field": "author",
				"value": "Author",
				"useHandlebarsExpr": false,
				"supportHtml": false
			},
			{
				"name": "Profile Image",
				"field": "profileImage",
				"value": "{{#with (split AuthorOWSUSER '|')}}/_layouts/15/userphoto.aspx?size=L&username={{[0]}}{{/with}}",
				"useHandlebarsExpr": true,
				"supportHtml": false
			},
			{
				"name": "IconSrc",
				"field": "iconSrc",
				"value": "{{IconSrc}}",
				"useHandlebarsExpr": true,
				"supportHtml": false
			},
			{
				"name": "IconExt",
				"field": "iconExt",
				"value": "{{IconExt}}",
				"useHandlebarsExpr": true,
				"supportHtml": false
			},
			{
				"name": "File Extension",
				"field": "fileExtension",
				"value": "FileType",
				"useHandlebarsExpr": false,
				"supportHtml": false
			}
		]
	},
	"queryModifiers": [],
	"refinementFilters": "",
	"paging": {
		"itemsCountPerPage": "20",
		"pagingRange": 5,
		"showPaging": true,
		"hideDisabled": true,
		"hideFirstLastPages": false,
		"hideNavigation": false
	},
	"selectedLayout": 3,
	"useRefiners": true,
	"defaultSearchQuery": "",
	"isFullWidth": false,
	"refinerDataSourceReference": "WebPart.e899ac12-9256-4c8d-a8ad-dbd20fc459c3.0bcdb522-d80d-41f1-8a8e-298939fe8760:refinersWebPart",
	"resultSourceId": "",
	"multiGeo": true,
	"inlineTemplateText": "<content id=\"template\">\n\n    <style>\n        /* Insert your CSS overrides here */\n    </style>\n\n    <div class=\"template_root\">\n        {{#if @root.hasPrimaryOrSecondaryResults}}   \n            {{#if showResultsCount}}\n                <div class=\"template_resultCount\">\n                    <label class=\"ms-fontWeight-semibold\">{{getCountMessage @root.paging.totalItemsCount keywords}}</label>\n                </div>\n            {{/if}}\n            <pnp-details-list aria-label=\"test\" data-items=\"{{JSONstringify items}}\" data-columns-configuration=\"{{JSONstringify detailsListColumns}}\" data-show-file-icon=\"{{@root.showFileIcon}}\" data-is-compact=\"{{@root.isCompact}}\"></pnp-details-list>\n            {{#if @root.paging.showPaging}}\n                <pnp-pagination \n                    data-total-items=\"{{@root.paging.totalItemsCount}}\" \n                    data-hide-first-last-pages=\"{{@root.paging.hideFirstLastPages}}\"\n                    data-hide-disabled=\"{{@root.paging.hideDisabled}}\"\n                    data-hide-navigation=\"{{@root.paging.hideNavigation}}\"\n                    data-range=\"{{@root.paging.pagingRange}}\" \n                    data-items-count-per-page=\"{{@root.paging.itemsCountPerPage}}\" \n                    data-current-page-number=\"{{@root.paging.currentPageNumber}}\"\n                >\n                </pnp-pagination>\n            {{/if}}\n        {{else}}\n            {{#unless showBlank}}\n                <div class=\"template_noResults\">{{@root.strings.NoResultMessage}}</div>\n            {{/unless }}\n        {{/if}}\n    </div>\n</content>\n\n<content id=\"placeholder\">\n    <style>\n        /* Insert your CSS overrides here */\n    </style>\n\n    <div class=\"placeholder_root\">\n        {{#if showResultsCount}}\n            <div class=\"template_resultCount\">\n                <span class=\"shimmer line\" style=\"width: 20%\"></span>\n            </div>\n        {{/if}}\n        <pnp-details-list aria-label=\"test\" data-columns-configuration=\"{{JSONstringify @root.detailsListColumns}}\" data-show-file-icon=\"{{@root.showFileIcon}}\" data-is-compact=\"{{@root.isCompact}}\" data-show-shimmers=\"true\"></pnp-details-list>\n    </div>\n\n</content>",
	"externalTemplateUrl": "",
	"queryKeywords": {
		"__type": "DynamicProperty",
		"reference": {
			"_reference": "WebPart.096b96cc-8a44-41fa-9b4d-c0ab2ab2a779.21f8e2d3-e4a5-495d-8316-1e54eedd61ef:searchQuery",
			"_sourceId": "WebPart.096b96cc-8a44-41fa-9b4d-c0ab2ab2a779.21f8e2d3-e4a5-495d-8316-1e54eedd61ef",
			"_property": "searchQuery"
		}
	}
}

**Comment by meklulose** [comment]
@wobba we have added the radio button as html on searchboxcontainer.tsx. Should it be added somewhere else?

**Comment by wobba** [comment]
Right now only the search box re-trigger search on fragment URL change without a reload. Not sure how easy it is to make this work with the result wp by itself.

If you follow SPFx guidance on hyper links https://docs.microsoft.com/en-us/sharepoint/dev/spfx/hyperlinking try adding `data-interception="off"` to your link. This will cause a hard refresh, but should work as a workaround.

**Comment by meklulose** [comment]
@wobba Thank you for your help. I really appreciate it :)
