### ISSUE TITLE
I decided to remove the click target instead if there is no preview...

### ISSUE THREAD

**Issue by LetMeSP** [microsoft-search/pnp-modern-search#973]
Is this issue back? I use Cards layout for videos and thumbnail is not clickable but click target is active. Is there a way to add a URL to that thumbnail?

=============
I decided to remove the click target instead if there is no preview. Clicking the link will open.

_Originally posted by @wobba in https://github.com/microsoft-search/pnp-modern-search/issues/400#issuecomment-662400904_

**Comment by wobba** [comment]
Tile/card layout do not have a preview click target in the current template.

**Comment by wobba** [comment]
Seems to work just fine when enabled.

![image](https://user-images.githubusercontent.com/51104/116585939-30076680-a919-11eb-8072-9e06b5ad8635.png)

**Comment by LetMeSP** [comment]
Apologies - I am new to github... In your screenshot you have the preview enabled. I am referring to an option when the preview is disabled.

**Comment by wobba** [comment]
When disabled, there is no mouse over.
![image](https://user-images.githubusercontent.com/51104/116586715-0dc21880-a91a-11eb-8d8e-555e4266b835.png)

**Comment by LetMeSP** [comment]
I will test it again. I assume the preview link is the main link behavior and there is no option to add a regular link to the item?

**Comment by wobba** [comment]
To open the item you click the Title.. "bluetop" in my image.

**Comment by LetMeSP** [comment]
I use the 4.1 version and I do have click target on the thumbnail with preview disabled. Maybe because this is a video file (mp4)? 
![image](https://user-images.githubusercontent.com/41652178/116652734-a2d50980-a93a-11eb-920f-3901278dce2e.png)

**Comment by wobba** [comment]
Let me verify video results.

**Comment by wobba** [comment]
@LetMeSP added the for v4 as well and will be part of the next release. If you disable preview there will not be a mouse over.

**Comment by LetMeSP** [comment]
Just wanted to confirm that the issues is resolved in the newest release (4.2.2.0). Thanks @wobba!
