### ISSUE TITLE
handlebars split not working with showing persona card on hover

### ISSUE THREAD

**Issue by Jeroen00** [microsoft-search/pnp-modern-search#977]
Trying to get custom user/person field data from sitepage metadata. Using a split on an OWSUSER field. Working fine until I turn on the 'Show persona card on hover' because this breaks the with or split helper.

**Version**
 4.1.0.0

**To Reproduce**
1. Set slot for UserDisplayName to the person metadata field of the page/list item you are querying (in my example to LeidinggevendeOWSUSER)
2. Set layout to People
3. In 'manage people fields' set 'Value' for 'Primary text' to: {{#with (split (slot item @root.slots.UserDisplayName) "|")}}{{[1]}}{{/with}}
4. Web part should display the email address from person field (see example of full person field output below)
5. Toggle 'show persona card on hover' to on
6. Notice that web part no longer displays the email address but only the array index text [1]

**Expected behavior**
The with and split helpers to also work when 'show persona card on hover' is on.

**Desktop (please complete the following information):**
 - Chrome in Windows

**Additional context**
Example for content of person field:
"LeidinggevendeOWSUSER": "user@company.nl | Lastname, Firstname | 693A30232E667C6D656D626572736869707C6D617269652D6A6F73652E7665726D65756C656E406576696465732E6E6C i:0#.f|membership|user@company.nl"

**Comment by wobba** [comment]
Have you included `LeidinggevendeOWSUSER` in the list of properties to retrieve in addition to adding it to slots?

![image](https://user-images.githubusercontent.com/51104/119851378-a5f9f000-bf0e-11eb-9015-05c5f9a75d57.png)

**Comment by Jeroen00** [comment]
Yes, that field is included, see below. But when toggling 'show persona card on hover', the display goes to:

![image](https://user-images.githubusercontent.com/42589264/121872823-05753f80-cd06-11eb-883d-544f6e7b1aeb.png)

With that option off, the view is displaying the users as expected:
![image](https://user-images.githubusercontent.com/42589264/121873585-ceebf480-cd06-11eb-967e-4e3e429196b7.png)

 
**Debug properties**
![image](https://user-images.githubusercontent.com/42589264/121872744-ed052500-cd05-11eb-8f25-61bf4fca4db0.png)

**Comment by wobba** [comment]
I understand what you are trying to do. And you need to use a custom template in order to split out the e-mail address and pass as parameter to `<mgt-person person-query="{{getUserEmail (slot item @root.slots.PersonQuery)}}" person-card="hover">`

I would also use `{{itemAt (split (slot item @root.slots.UserDisplayName) "|") 1}}` to pick the display name.

It's about figuring out how to pass the right values to mgt-person and to pnp-persona. Right now they are sort of made to work with people result sources, not OWSUser props from SP results.
