### ISSUE TITLE
How to configure the PnP v3/v4 to set the same results as the OOTB search engine? 

### ISSUE THREAD

**Issue by Aydannajafi** [microsoft-search/pnp-modern-search#978]
I am trying to set-up the PnP modern search on a test page to give me the same Search Results on a test page as the current running OOTB(out of the box) solution. 

In the progress of updating the current OOTB search engine we want to create a better model using the PnP modern search. However we want to update the model based on the current OOTB model since we want to build incremental enhancements. This requires however that we can configure it correctly. 

Do you have any advice for how to do that?

**Comment by wobba** [comment]
@Aydannajafi not really doable as OOB search uses a personal rank model not directly exposed to any API. The closest you can get is to use v4 with Graph API and then figure out the OOB query templates used.

May I ask which functionality OOB does not provide which is a dependency for your scenario?

**Comment by Aydannajafi** [comment]
@wobba in our current configuration of the vs.3 (test environment), the search results does not include News and Articles from the internal intranet page. They appear in the original OOTB search page. I am not sure why. 

<img width="782" alt="Pnp moden search solution" src="https://user-images.githubusercontent.com/83406753/116861826-0d6c9a80-ac04-11eb-99e6-edae159a0d83.PNG">

**Comment by Aydannajafi** [comment]
@wobba in our current configuration of the vs.3 (test environment), the search results does not include News and Articles from the internal intranet page. They appear in the original OOTB search page. I am not sure why.

**Comment by wobba** [comment]
You need to look at your query template, or any query template of the default result source from your config which can impact this. Any SharePoint item can be returned. I'll close this for now as it's not directly web part, but related to how you write KQL and limit items. Those questions are right now better asked at https://techcommunity.microsoft.com/ or https://www.yammer.com/searchexplained.
