### ISSUE TITLE
Unable to drop down Slot field/Manage Columns

### ISSUE THREAD

**Issue by tseward** [microsoft-search/pnp-modern-search#983]
**Version used**
4.10

**Describe the bug**
When attempting to add a Slot field or a Managed Column, the drop down to select the columns is blank. In addition, the browser throws the below JS error. This occurs with Chrome (current) and Edge Canary (current).

```
Uncaught (in promise) TypeError: Cannot read property 'dynamicDataSourceManager' of undefined
    at Object.onDataRetrieved (modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1)
    at t.<anonymous> (modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1)
    at modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1
    at Object.next (modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1)
    at a (modern-search-results-web-part_3ca3954ff7cd63af5ad33d2a16997f6d.js:1)
```

**To Reproduce**
Edit a Search Result webpart on a Modern Page.  On the first tab, go to Layout slots -> Customize. Attempt to drop down the Slot field dropdown. No results appear.
On the second tab of the Search Result webpart properties, go to Manage Columns. Click the Column value dropdown. No results appear.

**Expected behavior**
Managed properties should appear in the dropdowns.

**Desktop (please complete the following information):**
Chrome/Edge Canary on Windows 10

**Additional context**
This is a relatively new issue. I was able to perform this operation roughly 1.5 months ago. We have not updated the PnP Search v4 webpart solution since Jan 26th.
EDIT: Updated to 4.10 today, no change.

**Comment by wobba** [comment]
Workaround is to ensure the web part has results before picking. Will be fixed in the next release.
