### ISSUE TITLE
3.19.1 Synonyms with dashes

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#986]
**Version used**
3.19.1

**Describe the bug**
3.19.1 is mostly working great, but we've run into a bug with dashes. I have a few synonyms that contains dashes that are not being recognized as a synonym. Example: Covid-19 or sars-cov2.

**To Reproduce**
1. Set up synonym, parent = "Covid 19", child = "sars-cov2", child = "Covid-19"
2. run query and look at the query in Debug

Query looks like:: {
  "queryModification": "Path:\"https...Details\" \"sars-cov2\"  contentclass:STS_ListItem_GenericList -ContentClass=urn:content-class:SPSPeople -InvestmentStatusOWSTEXT:\"Cancelled\"",
  "items": [
    {

It's not catching that it's a synonym.  I see the same behavior with or without quotes around it.

**Expected behavior**
The terms is processed as a synonym of "Covid 19"

**Screenshots**

**Desktop (please complete the following information):**
 Edge and Chrome. Windows 10

**Additional context**

**Comment by wobba** [comment]
You can work around synonyms with dashes by removing them. A dash is not considered in search anyways as it is tokenized away. If a document has "foo-bar", you will get the same match if you query for "foo bar".

**Comment by bryllyg** [comment]
Correct. the situation occurs when the query has a dash in it. This happens in both 3.17 and 3.19.1. If I search the list directly, I do see the same results for "foo-bar" and "foo bar", however when wrapping synonyms into it, synonyms with a dash are not being recognized as synonyms, so the results are drastically different. Is there some way to make it so the synonym process recognizes terms with dashes?

**Comment by wobba** [comment]
Fixed.
