### ISSUE TITLE
Synonyms - 3.19.1 need a way to prioritize the order in which child terms are applied

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#987]
**Is your feature request related to a problem? Please describe.**
We've installed v3.19.1 and are running into issues when we have a synonym term defined that is used on its own and also inside of a phrase. For example:

parent term = "Covid 19"
Child terms = "Covid", "Covid-19", "Covid Related"

In this case, the query phrase "Covid Related" is not recognizes as a synonym, rather "Covid" is recognized as a synonym, but then the second word is added, which makes it so it is no longer treated as a synonym and appears to be parsed as "covid" AND "related", rather than as the child term "Covid Related"

**Describe the solution you'd like**
It would be great if the terms were parsed in sequence so that I could set up the child terms as "Covid Related", "Covid-19", "Covid" and the synonyms check would run into "Covid Related" first and use it as a synonym and not get thrown out because it got caught by "Covid"

**Describe alternatives you've considered**
I tried changing parent and child terms, quotes, no-quotes, escaping,... 

**Additional context**

**Comment by wobba** [comment]
Would you want to match on the order, or by the most specific/longest match first?

**Comment by bryllyg** [comment]
Either would work. Longest would be easier for my brain, since I wouldn't have to think about how to sort them while setting it up :-)
