### ISSUE TITLE
Sharepoint PnP modern search - Display parent folder in column without registering custom handlebar expressions

### ISSUE THREAD

**Issue by bldeveloper** [microsoft-search/pnp-modern-search#989]
On Sharepoint Online: Using Sharepoint Search and Details format

I have use cases where users need to be able to see the parent folder name for each result, displayed as a column in the Search Results (details list) web part. This would help them easily see where the file is stored within a document library for more context.

I'm using {{slot item @root.slots.Path}} to show the full URL of the result.

Is there a way to only show the segment to the right of the second last '/' in the string? That would help show the parent folder name. 

I am not allowed to register custom Handlebars in my company.

Please help. Thanks!

**Comment by wobba** [comment]
You can get the URL to the parent using the managed property `ParentLink`. You can use string helpers like `split` and `last` from handlebar helpers to get the part you need in the template.  https://github.com/helpers/handlebars-helpers#split

**Comment by bldeveloper** [comment]
Thank you @wobba ! i used your site to get: {{replace (first (last (split (slot item @root.slots.Path) "/") 2)) "%20" " " }}
