### ISSUE TITLE
Result blocks not displaying

### ISSUE THREAD

**Issue by sureshkanag** [microsoft-search/pnp-modern-search#99]
**Version used**
Ex: 3.9

**Describe the bug**
We are not able to see the result blocks although they were defined through setting. enabled option query rules on web part settings. can you help fix it?

**To Reproduce**
1) create a result source
2) create query rules on top of result source 
3) result source should contain 2 to 3 results blocks
4) define a term set, site column (connected to termset), custom managed property for the site column
4) on SharePoint site pages, add a page, on the page pnp  search web part, search result web part and search refiners web part and define settings.
4) enable query rules on pnp search result web part
5) finally when searched for term from term store, refiners get populated for the term and search does not come up with result block, when selecting term, search result web part throws errorrs.

**Expected behavior**
result block should be displayed.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by FranckyC** [comment]
Hi @sureshkanag , actually this does not come by default in the templates. To display a result block triggered by a query rule, you must create or update an existing template and use the `@root.secondaryResults` object. Then you can iterate with a `{{#each}}` and display the block items the way you want.

![image](https://user-images.githubusercontent.com/5659122/74670363-07150e80-5177-11ea-9d3c-8028f02e003d.png)


Hope this help.
