### ISSUE TITLE
Synonyms and vertical number counts

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#990]
**Version used**
3.17 and 3.19.1

**Describe the bug**
We have 5 verticals configured on our search results page. We also have synonyms configured. When the vertical results count comes back on your default vertical, that vertical count is accurate for the term and all synonyms; however all the other vertical counts are potentially not accurate as it appears that the synonyms are not yet applied to those verticals. This makes it so that as you move through the verticals, the vertical counts change, leaving users confused.

**To Reproduce**
1. Configure two verticals with different sources
2. Configure some synonyms that will impact the number of results you get back on both verticals
3. Do a query for a synonym term or phrase. Note the vertical counts. 
4. Change to the second vertical. Notice that the count changes as the new vertical loads.

**Expected behavior**
Synonyms would be applies across all tabs at the outset so the counts are accurate.

**Screenshots**
When the first vertical is selected, the third shows a count of 15:
![image](https://user-images.githubusercontent.com/2616432/117476267-d05d1c80-af11-11eb-94c6-2ddb7ae425c5.png)

When the third vertical is selected, the count changes to 52:
![image](https://user-images.githubusercontent.com/2616432/117476475-dbb04800-af11-11eb-81df-8e60a0034fb2.png)

**Desktop (please complete the following information):**
Windows 10, edge and Chrome (current versions)

**Additional context**
I noticed another thread about getting counts being difficult in 4.x. I'd like to add my vote that it's a necessary feature.

**Comment by wobba** [comment]
Added synonym expansion for vertical counts. Will consider a dot release.
