### ISSUE TITLE
Case insensitive alphabetical order

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#992]
**Is your feature request related to a problem? Please describe.**
When users sort files alphabetically, they are sorted in ascii order, 0-1,A-Z, a-z (special characters in ascii locations). Users have no idea that this is case sensitive and sorting lowercase after uppercase. This is causing users to think search is broken.

**Describe the solution you'd like**
Change sort so it is case insensitive, mixing upper and lower case.

**Describe alternatives you've considered**
Looked at all the great suggestions here. Also posting a request for the product. 
https://www.techmikael.com/2015/08/how-to-do-case-insensitive-sorting-in.html 

**Additional context**

**Comment by wobba** [comment]
Well, seeing my short answer in that post this is not easily achieved from a web part point of view. This has to be solved at the API layer first.
