### ISSUE TITLE
Graph Connector Source

### ISSUE THREAD

**Issue by billyperalta89** [microsoft-search/pnp-modern-search#995]
**Version used**
4.1.0

**Describe the bug**
Getting "error" when trying to use my Data Source from my Graph Connector

**To Reproduce**
1.  I installed graph connector in our O365 and use it to connect to our file share. 
![image](https://user-images.githubusercontent.com/37436984/118056661-30ebbf80-b33f-11eb-92d2-a2f1d66f7ad4.png)
2. I used the Connection ID in my graph connector and feed it into the PnP Search Results
![image](https://user-images.githubusercontent.com/37436984/118056781-62648b00-b33f-11eb-9107-d29738b7bc8a.png)
3. After using it the follow error shows up in the PnP search result webpart
![image](https://user-images.githubusercontent.com/37436984/118057367-b2901d00-b340-11eb-8962-729dcef7dae0.png)

**Expected behavior**
It should show the item available in my file Share

**Desktop (please complete the following information):**
 - Google Chrome(Version 90.0.4430.93 (Official Build) (64-bit))

**Comment by wobba** [comment]
Have you followed https://microsoft-search.github.io/pnp-modern-search/installation/#approving-scopes ?

**Comment by billyperalta89** [comment]
> Have you followed https://microsoft-search.github.io/pnp-modern-search/installation/#approving-scopes ?

Yup I did, I already approved the scope in the API prior to adding the webpart in my page

**Comment by wobba** [comment]
Then you have to debug the request and response coming back to see what goes wrong. Possibly try the request sent in the graph explorer to compare. You should also change the managed properties fetched to match what you have for your connection.

**Comment by billyperalta89** [comment]
I figure out that I need to uncheck all selected fields first then select them again

**Comment by wobba** [comment]
Thank you, and might be something we could improve on for this scenario.
