### ISSUE TITLE
Unique Filters per vertical, without using separate pages

### ISSUE THREAD

**Issue by bryllyg** [microsoft-search/pnp-modern-search#998]
**Is your feature request related to a problem? Please describe.**
We have 5 verticals. Some fields are not unique between verticals, such as Modified Date. If we configure a filter for Source for the Documents vertical (pulling documents from a variety of sources), that filter appears for all verticals, even though the field makes no sense as a filter in 4 of the verticals. Our users are expressing frustration and confusion with this behavior and want to know why they're seeing Source on verticals where they are looking at results from a single list. 

Describe the solution you'd like**
I would love to have a multi-select field in the verticals settings that allows me to select which verticals the filter should apply to.

**Describe alternatives you've considered**
We considered using multiple search pages, but the non-selected vertical counts all show as "0", which is even more confusing to users. They never click on those verticals, as they think they have no content.

**Additional context**

**Comment by bryllyg** [comment]
Another possible option,  in the new Filters Edit Properties dialog, have a parameter where admin can enter verticals where the filter should be shown

**Comment by nikosmsk** [comment]
Linking #733 here as an idea for V4: . From all configured filters the Search Filters WP shows only those, which can be applied to the content under selected vertical - and this is already good. Not good is that the filter selections done for the first vertical, automatically come over to the second vertical, even if such filter selections are not applicable to the content under the second vertical

**Comment by wobba** [comment]
v3 no longer maintained
